ACPTUTL ;IHS/SD/RNB - ACPT*2.10*1 Utility routine ; 04 Nov 2009 10:47 AM
 ;;2.15;CPT FILES;**1**;DEC 11, 2014;Build 1
 ; 12/05/13 - Replaced/Updated TEXT/CLEAN tags
 ;          - Add common utility tags
 ; 03/03/14 - Exclude State codes from Category assignment
 Q
 ;
RSLT(%) ; EP - ISSUE MESSAGES DURING INSTALL
 D MES^XPDUTL(%)
 Q
 ;
TEXT(ACPTSTR) ; EP - convert Description text to Word-Processing data type
 ; input: .ACPTSTR = passed by reference, starts out as long string,
 ; ends as Fileman WP-format array complete with header
 ;
 N ACPTSTRN,ACPTCNT
 S ACPTSTRN=ACPTSTR ; copy string out
 S ACPTCNT=0 ; count WP lines for header
 K ACPTSTR ; clear what will now become a WP array
 F  Q:ACPTSTRN=""  D  ; loop until ACPTSTRN is fully transformed
 . N ACPTBRK S ACPTBRK=0 ; character position to break at
 . D  ; find the character position to break at
 . . N ACPTRY ; break position to try
 . . S ACPTRY=$L(ACPTSTRN) ; how long is the string?
 . . I ACPTRY<81 S ACPTBRK=ACPTRY Q  ; if 1 full line or less, we're done
 . . F ACPTRY=80:-1:2 D  Q:ACPTBRK
 . . . I $E(ACPTSTRN,ACPTRY+1)=" " D  Q  ; can break on a space
 . . . . S $E(ACPTSTRN,ACPTRY+1)="" ; remove the space
 . . . . S ACPTBRK=ACPTRY ; and let's break here
 . . . I "&_+-*/<=>}])|:;,.?!"[$E(ACPTSTRN,ACPTRY),$E(ACPTSTRN,ACPTRY+1)=" " D  Q  ; on delimiter?
 . . . . S ACPTBRK=ACPTRY ; so let's break here
 . . Q:ACPTBRK  ; if we found a good spot to break, we're done
 . . S ACPTBRK=80 ; otherwise, hard-break on 80 (weird content)
 . S ACPTCNT=ACPTCNT+1 ; one more line
 . S ACPTSTR(ACPTCNT)=$E(ACPTSTRN,1,ACPTBRK) ; copy line into array
 . S $E(ACPTSTRN,1,ACPTBRK)="" ; & remove it from the string
 Q
 ;
CLEAN(ACPTSTR,ACPTUP) ; EP - REPLACES/REMOVES CONTROL CHARS AND STRIPS MULTIPLE SPACES
 ; ACPTSTR=STRING TO CLEAN     ACPTUP=CONVERT TO UPPERCASE
 N ACPTI
 I ACPTSTR?.E1C.E D
 . F ACPTI=$L(ACPTSTR):-1:1 I ($A($E(ACPTSTR,ACPTI))<32)!($A($E(ACPTSTR,ACPTI))>126) D
 . . N ACPTC,ACPTR
 . . S ACPTC=$E(ACPTSTR,ACPTI)
 . . ; replace control chars that have standard ASCII equivalents
 . . S ACPTR=$TR(ACPTC,$C(28,145,146,147,148,150,151),"C''""""--")
 . . ; if no replacement, delete it
 . . I ($A(ACPTR)<32)!($A(ACPTR)>126) S ACPTR=""
 . . S $E(ACPTSTR,ACPTI)=ACPTR ; replace the ctl char
 S ACPTI=0 F  S ACPTI=$F(ACPTSTR,"  ") Q:'ACPTI  S $E(ACPTSTR,ACPTI-2,ACPTI-1)=" "
 I $E(ACPTSTR,1)=" " S ACPTSTR=$E(ACPTSTR,2,$L(ACPTSTR))
 I $E(ACPTSTR,$L(ACPTSTR))=" " S ACPTSTR=$E(ACPTSTR,1,$L(ACPTSTR)-1)
 I $G(ACPTUP) S ACPTSTR=$$UP^XLFSTR(ACPTSTR)
 Q ACPTSTR
 ;
CPTIEN(ACPTC) ; EP - RETURNS IEN TO BE USED IN NEW CPT CODE ENTRY
 N ACPTN,ACPTCNT
 S ACPTN=$$NUM^ICPTAPIU(ACPTC) ; ATTEMPT NUMERIC CONVERSION
 Q:'$D(^ICPT(ACPTN)) ACPTN ; RETURN NUMERIC CONVERSION IF IEN IS FREE
 S ACPTN=0 F ACPTCNT=100000:1 Q:ACPTN  S:'$D(^ICPT(ACPTCNT)) ACPTN=ACPTCNT ; STARTING FROM 100000, FIND NEXT AVAILABLE IEN
 Q ACPTN
 ;
CPTMASG ; EP - ASSIGN RANGES TO CPT MODIFIERS FOR EHR USE
 N ACPTI,ACPTR
 D RSLT(""),RSLT("Correcting CPT Modifiers with blank CPT Ranges.")
 S ACPTI=0,ACPTR="" F  S ACPTI=$O(^DIC(81.3,ACPTI)) Q:'ACPTI  D
 . Q:'$D(^DIC(81.3,ACPTI,60))
 . Q:$D(^DIC(81.3,ACPTI,10))
 . N FDA
 . S FDA(81.32,"?+1,"_ACPTI_",",.01)="00100" ; Begin CPT Range
 . S FDA(81.32,"?+1,"_ACPTI_",",.02)="9999Z" ; End CPT Range
 . S FDA(81.32,"?+1,"_ACPTI_",",.03)="3100101" ; Active Date
 . D UPDATE^DIE(,"FDA",)
 . S ACPTR=ACPTR_$$GET1^DIQ(81.3,ACPTI,.01)_$J("",3)
 . I $L(ACPTR)>79 D RSLT(ACPTR) S ACPTR=""
 I $L(ACPTR)>0 D RSLT(ACPTR)
 Q
CATFIND(ACPTC,ACPTCAT) ; EP - FIND CATEGORY FOR A GIVEN CPT/HCPCS CODE
 ; ACPTC=CPT/HCPCS CODE     ACPTCAT=S:SUB,M:MAJOR,BLANK:BOTH
 N ACPTN,ACPTRES,ACPTR,ACPTRI,ACPTIND,ACPTCNT
 I (ACPTC=99224)!(ACPTC=99225)!(ACPTC=99226) Q $O(^DIC(81.1,"B","HOSPITAL OBSERVATION SERVICES",0))
 S ACPTN=$$NUM^ICPTAPIU(ACPTC)
 S:'$D(ACPTCAT) ACPTCAT="S^M" ; IF NO CATEGORY SPECIFIED, SEARCH BOTH
 S (ACPTRES,ACPTR)=""
 Q:'(ACPTN?.N) ACPTRES  ; IHS/OIT/NKD ACPT*2.14*1 - EXCLUDE STATE CODES
 F ACPTCNT=1:1:$L(ACPTCAT,U) Q:ACPTRES]""  D
 .S ACPTIND=$S($P(ACPTCAT,U,ACPTCNT)="S":"R",1:"M") ; CONVERT CATEGORY TYPE TO RANGE X-REF
 .S (ACPTRES,ACPTR)=""
 .; ADD .01 TO NUMERIC CODE AND SEARCH LAST 2 CATEGORY RANGES
 .S ACPTR=$O(^DIC(81.1,ACPTIND,ACPTN+.01),-1),ACPTRI=$S(ACPTR]"":$O(^DIC(81.1,ACPTIND,ACPTR,0)),1:"")
 .S:ACPTRI]"" ACPTRES=$S($$CATCHK(ACPTC,ACPTRI):ACPTRI,1:"")
 .Q:ACPTRES]""
 .S:ACPTR]"" ACPTR=$O(^DIC(81.1,ACPTIND,ACPTR),-1),ACPTRI=$S(ACPTR]"":$O(^DIC(81.1,ACPTIND,ACPTR,0)),1:"")
 .S:ACPTRI]"" ACPTRES=$S($$CATCHK(ACPTC,ACPTRI):ACPTRI,1:"")
 .Q:ACPTRES]""
 .S ACPTR=""
 .; SUBTRACT .01 FROM NUMERIC CODE AND SEARCH NEXT 2 CATEGORY RANGES
 .S ACPTR=$O(^DIC(81.1,ACPTIND,ACPTN-.01)),ACPTRI=$S(ACPTR]"":$O(^DIC(81.1,ACPTIND,ACPTR,0)),1:"")
 .S:ACPTRI]"" ACPTRES=$S($$CATCHK(ACPTC,ACPTRI):ACPTRI,1:"")
 .Q:ACPTRES]""
 .S:ACPTR]"" ACPTR=$O(^DIC(81.1,ACPTIND,ACPTR)),ACPTRI=$S(ACPTR]"":$O(^DIC(81.1,ACPTIND,ACPTR,0)),1:"")
 .S:ACPTRI]"" ACPTRES=$S($$CATCHK(ACPTC,ACPTRI):ACPTRI,1:"")
 Q ACPTRES
 ;
CATCHK(ACPTC,ACPTCI) ; CHECK IF CODE FALLS WITHIN CATEGORY RANGE
 ; ACPTC=CPT/HCPCS CODE    ACPTCI=CATEGORY IEN
 N ACPTN,ACPTB,ACPTE
 S ACPTN=$$NUM^ICPTAPIU(ACPTC) ; CONVERT CODE TO NUMERIC
 S ACPTB=$$NUM^ICPTAPIU($$GET1^DIQ(81.1,ACPTCI,4)) ; CONVERT BEGIN CODE TO NUMERIC
 S ACPTE=$$NUM^ICPTAPIU($$GET1^DIQ(81.1,ACPTCI,5)) ; CONVERT END CODE TO NUMERIC
 Q:(ACPTB=ACPTN)!(ACPTE=ACPTN) 1 ; RETURN 1 IF CODE = BEGIN OR END CODE
 Q ((ACPTB<ACPTN)&(ACPTN<ACPTE)) ; RETURN 1 IF BEGIN<CODE<END, 0 OTHERWISE
 ;
CATUPD ; EP - ATTEMPT TO ASSIGN/UPDATE ALL CPT CODES TO A CATEGORY
 N ACPTI,ACPTR
 S (ACPTI,ACPTR("TOT"),ACPTR("UPD"),ACPTR("SUB"),ACPTR("MAJ"))=0
 D RSLT(""),RSLT("ADDING/UPDATING ALL CPT CODES WITH CATEGORIES...")
 F  S ACPTI=$O(^ICPT(ACPTI)) Q:('ACPTI)  D
 . N ACPTC,ACPTCS,ACPTCP,ACPTCA,FDA
 . Q:'$D(^ICPT(ACPTI,0))
 . S ACPTC=$$GET1^DIQ(81,ACPTI,.01,"I")
 . Q:ACPTC']""
 . S ACPTCP=$$GET1^DIQ(81,ACPTI,3,"I"),ACPTCA=$$CATFIND(ACPTC) ; SET PREVIOUS AND AFTER CATEGORIES
 . ; SPECIAL CASE FOR THESE RE-SEQUENCED CODES
 . F ACPTCS=99224,99225,99226 S:ACPTC=ACPTCS ACPTCA=$O(^DIC(81.1,"B","HOSPITAL OBSERVATION SERVICES",0))
 . S FDA(81,ACPTI_",",3)=$S(ACPTCA]"":ACPTCA,1:"@")
 . I ACPTCP'=ACPTCA D UPDATE^DIE(,"FDA")
 . ; CALCULATE RESULTS
 . S ACPTR("TOT")=ACPTR("TOT")+1
 . S:((ACPTCA]"")&(ACPTCP'=ACPTCA)) ACPTR("UPD")=ACPTR("UPD")+1
 . S:($$GET1^DIQ(81.1,ACPTCA,2,"I")="s") ACPTR("SUB")=ACPTR("SUB")+1
 . S:($$GET1^DIQ(81.1,ACPTCA,2,"I")="m") ACPTR("MAJ")=ACPTR("MAJ")+1
 . I '(ACPTR("TOT")#5000) W "."
 D RSLT("TOTAL CODES SCANNED: "_ACPTR("TOT"))
 D RSLT("            UPDATED: "_ACPTR("UPD")_$S(ACPTR("UPD")=0:" (ALL ARE CURRENT)",1:""))
 D RSLT("ASSIGNMENT CATEGORY (MAJOR): "_ACPTR("MAJ"))
 D RSLT("                      (SUB): "_ACPTR("SUB"))
 Q
