ACPT214D ;IHS/OIT/NKD - ACPT V2.14 CPT UPDATE DRIVER 12/05/13 ;
 ;;2.14;CPT FILES;**1,2,3**;DEC 05, 2013;Build 1
 ; 02/06/13 - ACPT*2.13*1 - ADDED SPECIAL CASE FOR 'RI' MODIFIER
 ; 07/03/13 - ACPT*2.13*2 - ADDED SPECIAL CASE FOR 'K0008' AND 'K0013' HCPCS
 ;                        - ADDED SPECIAL CASE FOR 'JE' MODIFIER
 ; 12/05/13 - Updated to new ACPTUTL calls
 ;          - Combined Annual and Incremental drivers into 1 routine
 ;          - Included Category update
 ; 02/03/14 - Added debug/change list
 ;          - Added special case for 'HI' modifier
 ; 05/21/14 - Added Effective column to display
 ;
 Q
UPDATE ; EP - PRIMARY UPDATE DRIVER
 N ACPTT,ACPTA,ACPTC
 F ACPTT="CAT","CPT","HCPCS"  D
 . Q:'$D(^ACPT(ACPTT))
 . F ACPTA="A","C","D","M"  D
 . . Q:'$D(^ACPT(ACPTT,ACPTA))
 . . D RSLT^ACPTUTL("")
 . . I ACPTT="CAT" D
 . . . D RSLT^ACPTUTL($G(^ACPT(ACPTT,ACPTA,0))_" "_$S(ACPTA="C":"Adding/Modifying",1:"")_" Categories:")
 . . . D RSLT^ACPTUTL($J("",2)_"NAME"_$J("",50)_"NEW TYP SRC BEGIN END")
 . . . D RSLT^ACPTUTL($J("",2)_"===="_$J("",50)_"=== === === ===== =====")
 . . E  D
 . . . D RSLT^ACPTUTL($G(^ACPT(ACPTT,ACPTA,0))_" "_ACPTT_" "_$S(ACPTA="A":"Adding",ACPTA="C":"Modifying",ACPTA="D":"Deleting",1:"Modifier")_" Codes:")
 . . . ;D RSLT^ACPTUTL($J("",2)_"CODE    SHORT DESCRIPTION"_$J("",16)_"NEW STATUS SHORT LONG"_$S(ACPTA'="M":" CAT",1:""))  ;IHS/OIT/NKD ACPT*2.14*2 - MODIFIED DISPLAY
 . . . D RSLT^ACPTUTL($J("",2)_"CODE    SHORT DESCRIPTION"_$J("",16)_"NEW STATUS SHORT LONG"_$S(ACPTA'="M":" CAT",1:"    ")_" EFFECTIVE")
 . . . ;D RSLT^ACPTUTL($J("",2)_"====    ================="_$J("",16)_"=== ====== ===== ===="_$S(ACPTA'="M":" ===",1:""))  ;IHS/OIT/NKD ACPT*2.14*2 - MODIFIED DISPLAY
 . . . D RSLT^ACPTUTL($J("",2)_"====    ================="_$J("",16)_"=== ====== ===== ===="_$S(ACPTA'="M":" ===",1:"    ")_" =========")
 . . S ACPTC=0 F  S ACPTC=$O(^ACPT(ACPTT,ACPTA,ACPTC)) Q:'ACPTC  D
 . . . D @(ACPTT)(ACPTA,$G(^ACPT(ACPTT,ACPTA,ACPTC)))
 Q
 ;
CPT(ACPTA,ACPTD) ; CPT DRIVER
 ; IHS/OIT/NKD ACPT*2.14*1 - DEBUG/CHANGE LIST - START NEW CODE
 N ACPTL
 S ACPTL=""
 ; IHS/OIT/NKD ACPT*2.14*1 - END NEW CODE
 I ACPTA="M" D CPTM(ACPTD)  Q  ; CPT Modifier
 ; Input transforms
 N ACPTIEN,ACPTCODE,ACPTNAME,ACPTDESC,ACPTADT,ACPTEDT,ACPTTDT,ACPTCNT,ACPTRES,ACPTCHG
 S ACPTCODE=$P(ACPTD,"^",1)
 S ACPTNAME=$TR($$CLEAN^ACPTUTL($P(ACPTD,"^",2),1),";",",")
 S ACPTDESC=$$CLEAN^ACPTUTL($P(ACPTD,"^",3),1)
 S ACPTADT=$S($P(ACPTD,"^",4)]"":$P(ACPTD,"^",4)-17000000,1:"")
 S ACPTEDT=$S($P(ACPTD,"^",5)]"":$P(ACPTD,"^",5)-17000000,1:ACPTYR)
 S ACPTTDT=$S($P(ACPTD,"^",6)]"":$P(ACPTD,"^",6)-17000000,1:ACPTYR)
 S:((ACPTA="D")&(ACPTTDT']"")) ACPTTDT=ACPTEDT
 ; CPT search
 S ACPTIEN=""
 D FIND^DIC(81,,"@;.01;2;8I","OPX",ACPTCODE,,,"I ($P(^(0),U,4)'=1)",,"ACPTRES") ; Search actives
 S ACPTCNT=$P($G(ACPTRES("DILIST",0)),"^",1)
 S:ACPTCNT=0 ACPTIEN="" ; No matches found, create new
 S:ACPTCNT=1 ACPTIEN=$P($G(ACPTRES("DILIST",1,0)),"^",1) ; One match found, store IEN
 S:ACPTCNT>1 ACPTIEN=$P($G(ACPTRES("DILIST",ACPTCNT,0)),"^",1) ; Multiple matches found, use the last
 I 'ACPTIEN D
 . K ACPTRES,ACPTCNT
 . D FIND^DIC(81,,"@;.01;2;8I","OPX",ACPTCODE,,,,,"ACPTRES") ; Include inactives
 . S ACPTCNT=$P($G(ACPTRES("DILIST",0)),"^",1)
 . S:ACPTCNT=0 ACPTIEN="" ; No matches found, create new
 . S:ACPTCNT=1 ACPTIEN=$P($G(ACPTRES("DILIST",1,0)),"^",1) ; One match found, store IEN
 . S:ACPTCNT>1 ACPTIEN=$P($G(ACPTRES("DILIST",1,0)),"^",1) ; Multiple matches found, use the first
 K ACPTRES
 ;
 I ((ACPTIEN']"")&(ACPTA="D")) D RSLT^ACPTUTL($J("",2)_ACPTCODE_$J("",8-$L(ACPTCODE))_"Couldn't find code to inactivate") Q
 S ACPTCHG=""
 D UPD81^ACPT214U,DIS81^ACPT214U
 Q
 ;
HCPCS(ACPTA,ACPTD) ; HCPCS DRIVER
 ; IHS/OIT/NKD ACPT*2.14*1 - DEBUG/CHANGE LIST - START NEW CODE
 N ACPTL
 S ACPTL=""
 ; IHS/OIT/NKD ACPT*2.14*1 - END NEW CODE
 ; Input transforms
 N ACPTIEN,ACPTCODE,ACPTNAME,ACPTDESC,ACPTADT,ACPTEDT,ACPTTDT,ACPTCNT,ACPTRES,ACPTCHG
 S ACPTCODE=$P(ACPTD,"^",1)
 S ACPTNAME=$$CLEAN^ACPTUTL($P(ACPTD,"^",2))
 S ACPTDESC=$$CLEAN^ACPTUTL($P(ACPTD,"^",3),1)
 S ACPTADT=$S($P(ACPTD,"^",4)]"":$P(ACPTD,"^",4)-17000000,1:"")
 S ACPTEDT=$S($P(ACPTD,"^",5)]"":$P(ACPTD,"^",5)-17000000,1:"")
 S ACPTTDT=$S($P(ACPTD,"^",6)]"":$P(ACPTD,"^",6)-17000000,1:"")
 I ACPTA="M" D HCPCSM(ACPTD) Q
 ; HCPCS search
 S ACPTIEN=""
 D FIND^DIC(81,"","@;.01;2;8I","OPX",ACPTCODE,"","","","","ACPTRES")
 S ACPTCNT=$P($G(ACPTRES("DILIST",0)),"^",1)
 S:ACPTCNT=0 ACPTIEN="" ; No matches found, create new
 S:ACPTCNT=1 ACPTIEN=$P($G(ACPTRES("DILIST",1,0)),"^",1) ; One match found, store IEN
 I ACPTCNT>1 D
 . F ACPTCNT=1:1:$P($G(ACPTRES("DILIST",0)),"^",1) D  Q:ACPTIEN]""
 . . ; If the Active Date (8) matches the HCPCS Add Date, store IEN
 . . I $P($G(ACPTRES("DILIST",ACPTCNT,0)),"^",4)=ACPTADT S ACPTIEN=$P($G(ACPTRES("DILIST",ACPTCNT,0)),"^",1) Q
 . ; If no entries match Active Date, use most recently added
 . S:ACPTIEN']"" ACPTIEN=$P($G(ACPTRES("DILIST",$P($G(ACPTRES("DILIST",0)),"^",1),0)),"^",1)
 K ACPTRES
 ;
 ; If the code was added the same year as the install, a previous match was found, and the active dates are different,
 ; then ignore and create new
 ; Activates when codes are re-used and should NOT be linked to their previous definition
 I ((ACPTIEN]"")&(ACPTA'="D")) D
 . Q:((ACPTCODE="K0008")!(ACPTCODE="K0013"))  ; IHS/OIT/NKD ACPT*2.13*2 RE-ACTIVATES
 . S:($E(ACPTADT,1,3)=$E(ACPTYR,1,3))&(ACPTADT'=$P($G(^ICPT(ACPTIEN,0)),"^",8)) ACPTIEN=""
 ;
 I ((ACPTIEN']"")&(ACPTA="D")) D RSLT^ACPTUTL($J("",2)_ACPTCODE_$J("",8-$L(ACPTCODE))_"Couldn't find code to inactivate") Q
 S ACPTCHG=""
 D UPD81^ACPT214U,DIS81^ACPT214U
 Q
 ;
CAT(ACPTA,ACPTD) ; CATEGORY DRIVER
 ; IHS/OIT/NKD ACPT*2.14*1 - DEBUG/CHANGE LIST - START NEW CODE
 N ACPTL
 S ACPTL=""
 ; IHS/OIT/NKD ACPT*2.14*1 - END NEW CODE
 N ACPTIEN,ACPTNAME,ACPTCAT,ACPTSRC,ACPTBEG,ACPTEND,ACPTPNM,ACPTMAJ,ACPTRES,ACPTCNT,ACPTCHG
 S ACPTNAME=$$CLEAN^ACPTUTL($P(ACPTD,"^",1),1)
 S ACPTCAT=$P(ACPTD,U,2)
 S ACPTSRC=$$CLEAN^ACPTUTL($P(ACPTD,"^",3),1)
 S ACPTBEG=$P(ACPTD,U,4)
 S ACPTEND=$P(ACPTD,U,5)
 S ACPTPNM=$$CLEAN^ACPTUTL($P(ACPTD,"^",6),1)
 S ACPTMAJ=$S(ACPTCAT="s":$$CATFIND^ACPTUTL(ACPTBEG,"M"),1:"") ; FIND MAJOR CATEGORY (IF SUB)
 S ACPTIEN=""
 ; CATEGORY SEARCH BY NAME THEN PREVIOUS NAME
 D FIND^DIC(81.1,"","@;.01","PX",$E(ACPTNAME,1,63),,"B",,,"ACPTRES")
 S ACPTCNT=$P($G(ACPTRES("DILIST",0)),U,1)
 S ACPTIEN=$S(ACPTCNT=1:$P($G(ACPTRES("DILIST",1,0)),U,1),ACPTCNT>1:$P($G(ACPTRES("DILIST",$P($G(ACPTRES("DILIST",0)),U,1),0)),U,1),1:"")
 I ACPTIEN']"" D
 . N ACPTRES,ACPTCNT
 . D FIND^DIC(81.1,"","@;.01","PX",$E(ACPTPNM,1,63),,"B",,,"ACPTRES")
 . S ACPTCNT=$P($G(ACPTRES("DILIST",0)),U,1)
 . S ACPTIEN=$S(ACPTCNT=1:$P($G(ACPTRES("DILIST",1,0)),U,1),ACPTCNT>1:$P($G(ACPTRES("DILIST",$P($G(ACPTRES("DILIST",0)),U,1),0)),U,1),1:"")
 S ACPTCHG=""
 D UPD811^ACPT214U,DIS811^ACPT214U
 Q
 ;
CPTM(ACPTD) ; CPT MODIFIER DRIVER
 ; Input transforms
 N ACPTIEN,ACPTCODE,ACPTNAME,ACPTDESC,ACPTPNM,ACPTINAC,ACPTADT,ACPTEDT,ACPTTDT,ACPTCNT,ACPTRES,ACPTCHG
 S ACPTCODE=$P(ACPTD,"^",1)
 S ACPTNAME=$TR($$CLEAN^ACPTUTL($P(ACPTD,"^",2),1),";",",")
 S ACPTDESC=$$CLEAN^ACPTUTL($P(ACPTD,"^",3),1)
 S ACPTPNM=$$CLEAN^ACPTUTL($P(ACPTD,"^",4),1)
 S ACPTINAC=$S($P(ACPTD,"^",5)]"":$P(ACPTD,"^",5),1:0)
 S ACPTADT=""
 S ACPTEDT=ACPTYR
 S ACPTTDT=$S(ACPTINAC:ACPTYR,1:"")
 S:ACPTNAME']"" ACPTNAME=$E(ACPTDESC,1,60)
 ; CPT Modifier search
 S ACPTIEN=""
 D FIND^DIC(81.3,,"@;.01;.02;.04I","OPX",ACPTCODE,,,,,"ACPTRES")
 S ACPTCNT=$P($G(ACPTRES("DILIST",0)),"^",1)
 S:ACPTCNT=0 ACPTIEN="" ; No matches found, create new
 S:ACPTCNT=1 ACPTIEN=$P($G(ACPTRES("DILIST",1,0)),"^",1) ; One match found, store IEN
 I ACPTCNT>1 D
 . F ACPTCNT=1:1:$P($G(ACPTRES("DILIST",0)),"^",1) D  Q:ACPTIEN]""
 . . ; If the source doesn't match, skip
 . . Q:$P($G(ACPTRES("DILIST",ACPTCNT,0)),"^",4)'="C"
 . . I $$UP^XLFSTR($P($G(ACPTRES("DILIST",ACPTCNT,0)),"^",3))=ACPTNAME S ACPTIEN=$P($G(ACPTRES("DILIST",ACPTCNT,0)),"^",1) Q
 . . I $$UP^XLFSTR($P($G(ACPTRES("DILIST",ACPTCNT,0)),"^",3))=ACPTPNM S ACPTIEN=$P($G(ACPTRES("DILIST",ACPTCNT,0)),"^",1) Q
 . Q:ACPTIEN]""
 . I ACPTIEN']"" F ACPTCNT=1:1:$P($G(ACPTRES("DILIST",0)),"^",1) D  Q:ACPTIEN]""
 . . I $$UP^XLFSTR($P($G(ACPTRES("DILIST",ACPTCNT,0)),"^",3))=ACPTNAME S ACPTIEN=$P($G(ACPTRES("DILIST",ACPTCNT,0)),"^",1) Q
 . . I $$UP^XLFSTR($P($G(ACPTRES("DILIST",ACPTCNT,0)),"^",3))=ACPTPNM S ACPTIEN=$P($G(ACPTRES("DILIST",ACPTCNT,0)),"^",1) Q
 K ACPTRES
 ;
 I ((ACPTIEN']"")&(ACPTINAC)) D RSLT^ACPTUTL($J("",2)_ACPTCODE_$J("",8-$L(ACPTCODE))_"Couldn't find code to inactivate") Q
 S ACPTCHG=""
 D UPD813^ACPT214U,DIS813^ACPT214U
 Q
 ;
HCPCSM(ACPTD) ; HCPCS MODIFIER DRIVER
 ; Input transforms
 N ACPTIEN,ACPTCNT,ACPTRES,FDA,NEWIEN,ACPTLST,ACPTDFR,ACPTDTO,ACPTNEW
 S ACPTNAME=$$UP^XLFSTR(ACPTNAME)
 ; CPT Modifier search
 S ACPTIEN=""
 D FIND^DIC(81.3,"","@;.01;.02;8I","OPX",ACPTCODE,"","","","","ACPTRES")
 S ACPTCNT=$P($G(ACPTRES("DILIST",0)),"^",1)
 S:ACPTCNT=0 ACPTIEN="" ; No matches found, create new
 S:ACPTCNT=1 ACPTIEN=$P($G(ACPTRES("DILIST",1,0)),"^",1)
 ; IHS/OIT/NKD ACPT*2.13*1 - SPECIAL CASE FOR 'RI' MODIFIER
 ;S:(ACPTCNT=1)&(ACPTCODE="RI") ACPTIEN=$S($P($G(ACPTRES("DILIST",ACPTCNT,0)),"^",4)=ACPTADT:ACPTIEN,1:"")
 ; IHS/OIT/NKD ACPT*2.13*2 - SPECIAL CASE FOR 'JE' MODIFIER
 ;S:(ACPTCNT=1)&(ACPTCODE="JE") ACPTIEN=$S($P($G(ACPTRES("DILIST",ACPTCNT,0)),"^",4)=ACPTADT:ACPTIEN,1:"")
 I ACPTCNT>1 D
 . F ACPTCNT=1:1:$P($G(ACPTRES("DILIST",0)),"^",1) D  Q:ACPTIEN]""
 . . S:$P($G(ACPTRES("DILIST",ACPTCNT,0)),"^",4)=ACPTADT ACPTIEN=$P($G(ACPTRES("DILIST",ACPTCNT,0)),"^",1)
 . Q:ACPTIEN]""
 . I ACPTIEN']"" F ACPTCNT=1:1:$P($G(ACPTRES("DILIST",0)),"^",1) D  Q:ACPTIEN]""
 . . S:$$UP^XLFSTR($P($G(ACPTRES("DILIST",ACPTCNT,0)),"^",3))=ACPTNAME ACPTIEN=$P($G(ACPTRES("DILIST",ACPTCNT,0)),"^",1)
 . . ; IHS/OIT/NKD ACPT*2.14*1 - SPECIAL CASE FOR 'HI' MODIFIER
 . . S:(ACPTCODE="HI")&($$UP^XLFSTR($P($G(ACPTRES("DILIST",ACPTCNT,0)),"^",3))="M HLTH/M RETRDTN/DEV DIS PRO") ACPTIEN=$P($G(ACPTRES("DILIST",ACPTCNT,0)),"^",1)
 K ACPTRES
 ;
 I ((ACPTIEN']"")&(ACPTTDT]"")) D RSLT^ACPTUTL($J("",2)_ACPTCODE_$J("",8-$L(ACPTCODE))_"Couldn't find code to inactivate") Q
 S ACPTCHG=""
 D UPD813^ACPT214U,DIS813^ACPT214U
 Q
 ;
