ACPT215U ;IHS/OIT/NKD - ACPT V2.15 CPT UPDATER 12/11/14 ;
 ;;2.15;CPT FILES;**1**;DEC 11, 2014;Build 1
 ; 02/06/13 - ACPT*2.13*1 - MODIFIED BREAK LOGIC FOR LONG DESCRIPTION
 ; 07/03/13 - ACPT*2.13*2 - MODIFIED DINUM LOGIC FOR NEW CPT CODES
 ;                        - INCLUDED CPT CATEGORY FIELD WHEN UPDATING CPT/HCPCS CODES
 ;                        - ADDED CPT RANGE ON MODIFIERS FOR EHR
 ; 12/05/13 - Updated to new ACPTUTL calls
 ;          - Included Category update
 ; 02/03/14 - Added debug/change list
 ; 12/11/14 - Single-value add/active date fields for re-used codes should be newest date
 ;          - Store debug information only if flag is set
 ; 01/06/15 - Corrected display of Active/Inactive flag for modifiers
 ;
 Q
 ; EXPECTED VARIABLES
 ; ACPTA       ACPTT       ACPTIEN
 ; ACPTCODE    ACPTNAME    ACPTDESC
 ; ACPTADT     ACPTEDT     ACPTTDT
UPD81 ; EP - PRIMARY UPDATER TO CPT FILE
 N FDA,NEWIEN,ACPTRES,ACPTLST,ACPTCNT,ACPTLSI,ACPTDFR,ACPTDTO,ACPTNEW,ACPTPYR,ACPTCAT
 I ACPTIEN']"" D  ; If there isn't one, create it
 . K FDA,NEWIEN
 . S FDA(81,"+1,",.01)=ACPTCODE ; CPT Code (.01)
 . S NEWIEN(1)=$$CPTIEN^ACPTUTL(ACPTCODE) ; Attempt DINUM or next available IEN starting from 100000
 . D UPDATE^DIE(,"FDA","NEWIEN") ; Add the entry
 . S ACPTIEN=NEWIEN(1),ACPTCHG="N"
 Q:'ACPTIEN
 ;
 ;S ACPTPYR=$$GET1^DIQ(81,ACPTIEN,8,"I") ; SET PREVIOUS ACTIVE DATE  ;IHS/OIT/NKD ACPT 2.15 - USE NEW ACTIVE DATE IF ACTION IS ADD
 S ACPTPYR=$S(ACPTA'="A":$$GET1^DIQ(81,ACPTIEN,8,"I"),1:"") ; SET PREVIOUS ACTIVE DATE
 ; Effective Date (60)
 K FDA,ACPTRES,ACPTLST
 D LIST^DIC(81.02,","_ACPTIEN_",","@;.01I;.02I","P",,,,,,,"ACPTRES",)
 S ACPTLST=$P($G(ACPTRES("DILIST",$P($G(ACPTRES("DILIST",0)),"^",1),0)),"^",3)
 I ((ACPTLST=0)&(ACPTA'="D"))!((ACPTLST=1)&(ACPTA="D"))!(ACPTLST']"") D
 . S FDA(81.02,"?+1,"_ACPTIEN_",",.01)=ACPTEDT
 . S FDA(81.02,"?+1,"_ACPTIEN_",",.02)=$S(ACPTA="D":0,1:1)
 . D UPDATE^DIE(,"FDA",)
 . S ACPTCHG=ACPTCHG_$S(ACPTA="D":"I",1:"A")
 ;
 ; Non-versioned fields
 K FDA
 S:ACPTA'="D" FDA(81,ACPTIEN_",",2)=ACPTNAME ; Short Name (2)
 S FDA(81,ACPTIEN_",",6)=$S(ACPTT="CPT":"C",ACPTT="HCPCS":"H",1:"@") ; Source (6)
 S FDA(81,ACPTIEN_",",5)=$S(ACPTA="D":1,1:"@") ; Inactive Flag (5)
 S FDA(81,ACPTIEN_",",8)=$S(ACPTADT]"":ACPTADT,ACPTPYR]"":ACPTPYR,1:ACPTYR) ; Active Date (8)
 S FDA(81,ACPTIEN_",",9999999.06)=$S(ACPTADT]"":ACPTADT,ACPTPYR]"":ACPTPYR,1:ACPTYR) ; Date Added (9999999.06)
 S FDA(81,ACPTIEN_",",7)=$S(ACPTA="D":ACPTTDT,1:"@") ; Inactive Date (7)
 S FDA(81,ACPTIEN_",",9999999.07)=$S(ACPTA="D":ACPTTDT,1:"@") ; Date Deleted (9999999.07)
 S ACPTCAT=$$CATFIND^ACPTUTL(ACPTCODE)
 S:ACPTA'="D" FDA(81,ACPTIEN_",",3)=$S(ACPTCAT]"":ACPTCAT,1:"@"),ACPTCHG=ACPTCHG_$S($$GET1^DIQ(81,ACPTIEN,3,"I")'=ACPTCAT:"C",1:"")
 ;
 D UPDATE^DIE(,"FDA",)
 Q:ACPTA="D"
 ;
 ; Description (50)
 K FDA,ACPTCNT,ACPTRES
 D TEXT^ACPTUTL(.ACPTDESC) ; Convert string to WP array
 I $L($G(^ICPT(ACPTIEN,"D",0)))<1 S ^ICPT(ACPTIEN,"D",0)="^81.01A" ; Fix global due to CSV
 ; Remove previous Description
 S ACPTCNT=0
 D GETS^DIQ(81,ACPTIEN,"50*",,"ACPTRES")
 F  S ACPTCNT=$O(ACPTRES(81.01,ACPTCNT)) Q:'ACPTCNT  D
 . S ACPTRES(81.01,ACPTCNT,.01)="@"
 D UPDATE^DIE(,"ACPTRES",)
 ; Add new Description
 S ACPTCNT=0
 F  S ACPTCNT=$O(ACPTDESC(ACPTCNT)) Q:'ACPTCNT  D
 . S FDA(81.01,"+"_ACPTCNT_","_ACPTIEN_",",.01)=$G(ACPTDESC(ACPTCNT))
 D UPDATE^DIE(,"FDA",)
 ;
 ; Short Name (Versioned) (61)
 K FDA,ACPTRES,ACPTLST,ACPTCNT
 ; Find the last Short Name
 D LIST^DIC(81.061,","_ACPTIEN_",","@;.01I;1I","P",,,,,,,"ACPTRES",)
 S ACPTLST=$P($G(ACPTRES("DILIST",$P($G(ACPTRES("DILIST",0)),"^",1),0)),"^",3)
 ; If the last is blank, find the previous until a Short Name is found
 I ACPTLST']"" F ACPTCNT=1:1:$P($G(ACPTRES("DILIST",0)),"^",1)-1 S ACPTLST=$P($G(ACPTRES("DILIST",$P($G(ACPTRES("DILIST",0)),"^",1)-ACPTCNT,0)),"^",3) Q:ACPTLST]""
 ; If the two are different, create a new entry
 I $$CLEAN^ACPTUTL(ACPTLST,1)'=$$CLEAN^ACPTUTL(ACPTNAME,1) D
 . ;S ACPTL=ACPTL_"SHORT|"_ACPTLST_"|"_ACPTNAME_"^"  ; IHS/OIT/NKD ACPT*2.14*1 - DEBUG/CHANGE LIST
 . S:$D(ACPTDEBUG) ACPTL=ACPTL_"SHORT|"_ACPTLST_"|"_ACPTNAME_"^"  ; IHS/OIT/NKD ACPT 2.15 - CONDITIONAL BASED ON DEBUG FLAG
 . S FDA(81.061,"?+1,"_ACPTIEN_",",.01)=ACPTEDT ; Look for an entry for this install, add if not found
 . S FDA(81.061,"?+1,"_ACPTIEN_",",1)=ACPTNAME ; Set to ACPTNAME
 . D UPDATE^DIE(,"FDA",)
 . S ACPTCHG=ACPTCHG_"S"
 ;
 ; Description (Versioned) (62)
 K FDA,NEWIEN,ACPTRES,ACPTLST,ACPTLSI,ACPTCNT,ACPTDFR,ACPTDTO,ACPTNEW
 S ACPTNEW=0
 ; Find the last Description
 D LIST^DIC(81.062,","_ACPTIEN_",","@;.01I","P",,,,,,,"ACPTRES",)
 S ACPTCNT=$P($G(ACPTRES("DILIST",0)),"^",1)
 S ACPTLSI=$P($G(ACPTRES("DILIST",ACPTCNT,0)),"^",1)
 D GETS^DIQ(81.062,ACPTLSI_","_ACPTIEN,"1*",,"ACPTLST")
 ; Merge the entries into one string
 S ACPTCNT=0,ACPTDTO="" F  S ACPTCNT=$O(ACPTDESC(ACPTCNT)) Q:'ACPTCNT  S ACPTDTO=ACPTDTO_" "_ACPTDESC(ACPTCNT)
 S ACPTCNT=0,ACPTDFR="" F  S ACPTCNT=$O(ACPTLST(81.621,ACPTCNT)) Q:'ACPTCNT  S ACPTDFR($P(ACPTCNT,",",1))=ACPTLST(81.621,ACPTCNT,.01)
 S ACPTCNT=0 F  S ACPTCNT=$O(ACPTDFR(ACPTCNT)) Q:'ACPTCNT  S ACPTDFR=ACPTDFR_" "_ACPTDFR(ACPTCNT)
 ; If the two are different, create a new entry
 I $$CLEAN^ACPTUTL(ACPTDFR,1)'=$$CLEAN^ACPTUTL(ACPTDTO,1) D
 . ;S ACPTL=ACPTL_"LONG|"_$$CLEAN^ACPTUTL(ACPTDFR,1)_"|"_$$CLEAN^ACPTUTL(ACPTDTO,1)_"^"  ; IHS/OIT/NKD ACPT*2.14*1 - DEBUG/CHANGE LIST
 . S:$D(ACPTDEBUG) ACPTL=ACPTL_"LONG|"_$$CLEAN^ACPTUTL(ACPTDFR,1)_"|"_$$CLEAN^ACPTUTL(ACPTDTO,1)_"^"  ; IHS/OIT/NKD ACPT 2.15 - CONDITIONAL BASED ON DEBUG FLAG
 . S FDA(81.062,"?+1,"_ACPTIEN_",",.01)=ACPTEDT ; Look for an entry for this install, add if not found
 . D UPDATE^DIE(,"FDA","NEWIEN")
 . I $D(NEWIEN) D
 . . ; Remove previous Description
 . . K ACPTRES
 . . S ACPTCNT=0
 . . D GETS^DIQ(81.062,NEWIEN(1)_","_ACPTIEN,"1*",,"ACPTRES")
 . . F  S ACPTCNT=$O(ACPTRES(81.621,ACPTCNT)) Q:'ACPTCNT  D
 . . . S ACPTRES(81.621,ACPTCNT,.01)="@"
 . . D UPDATE^DIE(,"ACPTRES",)
 . . ; Add new Description
 . . S ACPTCNT=0
 . . F  S ACPTCNT=$O(ACPTDESC(ACPTCNT)) Q:'ACPTCNT  D
 . . . S FDA(81.621,"+"_ACPTCNT_","_NEWIEN(1)_","_ACPTIEN_",",.01)=$G(ACPTDESC(ACPTCNT))
 . . D UPDATE^DIE(,"FDA",)
 . . S ACPTCHG=ACPTCHG_"L"
 Q
 ;
UPD813 ; EP - PRIMARY UPDATER TO CPT MODIFIER FILE
 N FDA,NEWIEN,ACPTRES,ACPTLST,ACPTCNT,ACPTDFR,ACPTDTO,ACPTNEW,ACPTPYR
 I ACPTIEN']"" D  ; If there isn't one, create it
 . K FDA,NEWIEN
 . S FDA(81.3,"+1,",.01)=ACPTCODE ; Modifier (.01)
 . S FDA(81.3,"+1,",.02)=ACPTNAME ; Name (.02)
 . D UPDATE^DIE(,"FDA","NEWIEN") ; Add the entry
 . S ACPTIEN=NEWIEN(1),ACPTCHG="N"
 Q:'ACPTIEN
 ;
 S ACPTPYR=$$GET1^DIQ(81.3,ACPTIEN,8,"I") ; SET PREVIOUS ACTIVE DATE
 ; Effective Date (60)
 K FDA,ACPTRES,ACPTLST
 D LIST^DIC(81.33,","_ACPTIEN_",","@;.01I;.02I","P",,,,,,,"ACPTRES",)
 S ACPTLST=$P($G(ACPTRES("DILIST",$P($G(ACPTRES("DILIST",0)),"^",1),0)),"^",3)
 I ((ACPTLST=0)&(ACPTTDT']""))!((ACPTLST=1)&(ACPTTDT]""))!(ACPTLST']"") D
 . S FDA(81.33,"?+1,"_ACPTIEN_",",.01)=ACPTEDT ; Look for an entry for this install, add if not found
 . S FDA(81.33,"?+1,"_ACPTIEN_",",.02)=$S(ACPTTDT]"":0,1:1)
 . D UPDATE^DIE(,"FDA",)
 . ;S ACPTCHG=ACPTCHG_$S(ACPTTDT]"":"I",1:"D")  ; IHS/OIT/NKD ACPT*2.15*1 - CORRECTED DISPLAY OF ACTIVE FLAG
 . S ACPTCHG=ACPTCHG_$S(ACPTTDT]"":"I",1:"A")
 ;
 ; Non-versioned fields
 K FDA
 S:ACPTTDT']"" FDA(81.3,ACPTIEN_",",.02)=ACPTNAME ; Name (.02)
 S FDA(81.3,ACPTIEN_",",.04)=$S(ACPTT="CPT":"C",ACPTT="HCPCS":"H",1:"@") ; Source (.04)
 S FDA(81.3,ACPTIEN_",",5)=$S(ACPTTDT]"":1,1:"@") ; Inactive Flag (5)
 S FDA(81.3,ACPTIEN_",",7)=$S(ACPTTDT]"":ACPTTDT,1:"@") ; Inactive Date (7)
 S FDA(81.3,ACPTIEN_",",8)=$S(ACPTADT]"":ACPTADT,ACPTPYR]"":ACPTPYR,1:ACPTYR) ; Active Date (8)
 D UPDATE^DIE(,"FDA",)
 Q:ACPTTDT]""
 ;
 ; Range (10)
 K FDA
 S FDA(81.32,"?+1,"_ACPTIEN_",",.01)="00100" ; Begin CPT Range
 S FDA(81.32,"?+1,"_ACPTIEN_",",.02)="9999Z" ; End CPT Range
 S FDA(81.32,"?+1,"_ACPTIEN_",",.03)="3100101" ; Active Date
 D UPDATE^DIE(,"FDA",)
 ;
 ; Description (50) WP
 D TEXT^ACPTUTL(.ACPTDESC) ; convert string to WP array
 D WP^DIE(81.3,ACPTIEN_",",50,,"ACPTDESC")
 ;
 ; Name (Versioned) (61)
 K FDA,ACPTRES,ACPTLST
 ; Find the last Name
 D LIST^DIC(81.361,","_ACPTIEN_",","@;.01I;1I","P",,,,,,,"ACPTRES",)
 S ACPTLST=$P($G(ACPTRES("DILIST",$P($G(ACPTRES("DILIST",0)),"^",1),0)),"^",3)
 I ACPTLST'=ACPTNAME D  ; If the two are different, create a new entry
 . ;S ACPTL=ACPTL_"SHORT|"_ACPTLST_"|"_ACPTNAME_"^"  ; IHS/OIT/NKD ACPT*2.14*1 - DEBUG/CHANGE LIST
 . S:$D(ACPTDEBUG) ACPTL=ACPTL_"SHORT|"_ACPTLST_"|"_ACPTNAME_"^"  ; IHS/OIT/NKD ACPT 2.15 - CONDITIONAL BASED ON DEBUG FLAG
 . S FDA(81.361,"?+1,"_ACPTIEN_",",.01)=ACPTEDT ; Look for an entry for this install, add if not found
 . S FDA(81.361,"?+1,"_ACPTIEN_",",1)=ACPTNAME ; Set to ACPTNAME
 . D UPDATE^DIE(,"FDA",)
 . S ACPTCHG=ACPTCHG_"S"
 ;
 ; Description (Versioned) (62)
 K FDA,NEWIEN,ACPTRES,ACPTLST,ACPTCNT,ACPTDFR,ACPTDTO,ACPTNEW
 S ACPTNEW=0
 ; Find the last Description
 D LIST^DIC(81.362,","_ACPTIEN_",","@;.01I","P",,,,,,,"ACPTRES",)
 S ACPTCNT=$P($G(ACPTRES("DILIST",0)),"^",1)
 S ACPTLST=$$GET1^DIQ(81.362,ACPTCNT_","_ACPTIEN_",",1,,"ACPTLST",)
 ; Merge the entries into one string
 S ACPTCNT=0,ACPTDTO=0 F  S ACPTCNT=$O(ACPTDESC(ACPTCNT)) Q:'ACPTCNT  S ACPTDTO=ACPTDTO+1
 S ACPTCNT=0,ACPTDFR=0 F  S ACPTCNT=$O(ACPTLST(ACPTCNT)) Q:'ACPTCNT  S ACPTDFR=ACPTDFR+1
 I ACPTDFR'=ACPTDTO S ACPTNEW=1
 E  F ACPTCNT=1:1:ACPTDTO D
 . S:ACPTDESC(ACPTCNT)'=ACPTLST(ACPTCNT) ACPTNEW=1
 ; If the two are different, create a new entry
 I ACPTNEW D
 . S FDA(81.362,"?+1,"_ACPTIEN_",",.01)=ACPTEDT ; Look for an entry for this install, add if not found
 . D UPDATE^DIE(,"FDA","NEWIEN")
 . I $D(NEWIEN) D WP^DIE(81.362,NEWIEN(1)_","_ACPTIEN_",",1,,"ACPTDESC") S ACPTCHG=ACPTCHG_"L"
 Q
 ;
UPD811 ; EP - PRIMARY UPDATER TO CPT CATEGORY FILE
 N FDA,NEWIEN,ACPTRES,ACPTCNT
 I ACPTIEN']"" D  ; If there isn't one, create it
 . K FDA,NEWIEN
 . S FDA(81.1,"+1,",.01)=ACPTNAME ; Name (.01)
 . D UPDATE^DIE(,"FDA","NEWIEN") ; Add the entry
 . S ACPTIEN=NEWIEN(1),ACPTCHG="N"
 Q:'ACPTIEN
 ;
 S FDA(81.1,ACPTIEN_",",.01)=ACPTNAME ; CATEGORY NAME (.01)
 S FDA(81.1,ACPTIEN_",",2)=ACPTCAT ; TYPE OF CATEGORY (2)
 S FDA(81.1,ACPTIEN_",",3)=$S(ACPTMAJ]"":ACPTMAJ,1:"@") ; MAJOR CATEGORY (3)
 S FDA(81.1,ACPTIEN_",",4)=ACPTBEG ; BEGIN CPT RANGE (4)
 S FDA(81.1,ACPTIEN_",",5)=ACPTEND ; END CPT RANGE (5)
 S FDA(81.1,ACPTIEN_",",6)=ACPTSRC ; SOURCE (6)
 D UPDATE^DIE(,"FDA")
 Q
 ;
DIS81 ; EP - DISPLAY CPT FILE ENTRY
 N ACPTDISP,ACPTCNT,ACPTDN
 ;I ACPTCHG]"" D  ;IHS/OIT/NKD ACPT*2.15*1
 I ACPTCHG]""!$D(ACPTDEBUG) D
 . S:ACPTCHG["N" ACPTCHG="N"
 . S ACPTDISP=""
 . S ACPTDISP=ACPTDISP_$S(ACPTCHG["N":"N",1:" ")_$J("",3)
 . S ACPTDISP=ACPTDISP_$S(ACPTCHG["A":"A",ACPTCHG["I":"I",1:" ")_$J("",6)
 . S ACPTDISP=ACPTDISP_$S(ACPTCHG["S":"S",1:" ")_$J("",5)
 . S ACPTDISP=ACPTDISP_$S(ACPTCHG["L":"L",1:" ")_$J("",4)
 . ;S ACPTDISP=ACPTDISP_$S(ACPTCHG["C":"C",1:" ")  ;IHS/OIT/NKD ACPT*2.14*2 - MODIFIED DISPLAY
 . S ACPTDISP=ACPTDISP_$S(ACPTCHG["C":"C",1:" ")_$J("",3)
 . S ACPTDN=$S(ACPTNAME]"":$E(ACPTNAME,1,30),1:$$GET1^DIQ(81,ACPTIEN,2,"I"))
 . ;D RSLT^ACPTUTL($J("",2)_ACPTCODE_$J("",8-$L(ACPTCODE))_ACPTDN_$J("",33-$L(ACPTDN))_ACPTDISP)  ;IHS/OIT/NKD ACPT*2.14*2 - MODIFIED DISPLAY
 . D RSLT^ACPTUTL($J("",2)_ACPTCODE_$J("",8-$L(ACPTCODE))_ACPTDN_$J("",33-$L(ACPTDN))_ACPTDISP_$J("",24-$L(ACPTDISP))_$$FMTE^XLFDT($S(ACPTCHG["I":ACPTTDT,1:ACPTEDT),5))
 . ; IHS/OIT/NKD ACPT*2.14*1 - DEBUG OUTPUT - BEGIN NEW CODE
 . I $D(ACPTDEBUG),ACPTCHG'="N",ACPTL]"" D
 . . F ACPTCNT=1:1:$L(ACPTL,U) I $P(ACPTL,U,ACPTCNT)]"" D
 . . . D RSLT^ACPTUTL($E($P($P(ACPTL,U,ACPTCNT),"|",1),1,1)_" FR: "_$P($P(ACPTL,U,ACPTCNT),"|",2))
 . . . D RSLT^ACPTUTL($E($P($P(ACPTL,U,ACPTCNT),"|",1),1,1)_" TO: "_$P($P(ACPTL,U,ACPTCNT),"|",3))
 . . D RSLT^ACPTUTL("")
 . ; IHS/OIT/NKD ACPT*2.14*1 - END NEW CODE
 Q
 ;
DIS813 ; EP - DISPLAY CPT MODIFIER FILE ENTRY
 N ACPTDISP,ACPTCNT,ACPTDN
 I ACPTCHG]"" D
 . S:ACPTCHG["N" ACPTCHG="N"
 . S ACPTDISP=""
 . S ACPTDISP=ACPTDISP_$S(ACPTCHG["N":"N",1:" ")_$J("",3)
 . S ACPTDISP=ACPTDISP_$S(ACPTCHG["A":"A",ACPTCHG["I":"I",1:" ")_$J("",6)
 . S ACPTDISP=ACPTDISP_$S(ACPTCHG["S":"S",1:" ")_$J("",5)
 . ;S ACPTDISP=ACPTDISP_$S(ACPTCHG["L":"L",1:" ")  ;IHS/OIT/NKD ACPT*2.14*2 - MODIFIED DISPLAY
 . S ACPTDISP=ACPTDISP_$S(ACPTCHG["L":"L",1:" ")_$J("",8)
 . S ACPTDN=$S(ACPTNAME]"":$E(ACPTNAME,1,30),1:$$GET1^DIQ(81.3,ACPTIEN,.02,"I"))
 . ;D RSLT^ACPTUTL($J("",2)_ACPTCODE_$J("",8-$L(ACPTCODE))_ACPTDN_$J("",33-$L(ACPTDN))_ACPTDISP)  ;IHS/OIT/NKD ACPT*2.14*2 - MODIFIED DISPLAY
 . D RSLT^ACPTUTL($J("",2)_ACPTCODE_$J("",8-$L(ACPTCODE))_ACPTDN_$J("",33-$L(ACPTDN))_ACPTDISP_$J("",24-$L(ACPTDISP))_$$FMTE^XLFDT($S(ACPTCHG["I":ACPTTDT,1:ACPTEDT),5))
 . ; IHS/OIT/NKD ACPT*2.14*1 - DEBUG OUTPUT - BEGIN NEW CODE
 . I $D(ACPTDEBUG),ACPTCHG'="N",ACPTL]"" D
 . . F ACPTCNT=1:1:$L(ACPTL,U) I $P(ACPTL,U,ACPTCNT)]"" D
 . . . D RSLT^ACPTUTL($E($P($P(ACPTL,U,ACPTCNT),"|",1),1,1)_" FR: "_$P($P(ACPTL,U,ACPTCNT),"|",2))
 . . . D RSLT^ACPTUTL($E($P($P(ACPTL,U,ACPTCNT),"|",1),1,1)_" TO: "_$P($P(ACPTL,U,ACPTCNT),"|",3))
 . . D RSLT^ACPTUTL("")
 . ; IHS/OIT/NKD ACPT*2.14*1 - END NEW CODE
 Q
 ;
DIS811 ; EP - DISPLAY CPT CATEGORY ENTRY
 N ACPTDISP
 S:ACPTCAT="m" ACPTDISP=$E(ACPTNAME,1,50)_$J("",54-$L($E(ACPTNAME,1,50)))
 S:ACPTCAT="s" ACPTDISP="  "_$E(ACPTNAME,1,48)_$J("",52-$L($E(ACPTNAME,1,48)))
 S ACPTDISP=ACPTDISP_ACPTCHG_$J("",4-$L(ACPTCHG))_$$UP^XLFSTR(ACPTCAT)_$J("",4-$L(ACPTCAT))_ACPTSRC_$J("",4-$L(ACPTSRC))
 S ACPTDISP=ACPTDISP_ACPTBEG_$J("",6-$L(ACPTBEG))_ACPTEND
 D RSLT^ACPTUTL($J("",2)_ACPTDISP)
 Q
 ;
