AGMPPURG ; IHS/SD/TPF - MPI HLO MESSAGE PURGE;JAN 07, 2011
 ;;1.0;AGMP;**3,4**;Apr 30, 2021;Build 55
 Q
 ;
 ;NOT FINISHED
INTERACT ;EP - USER INTERACTIVE PURGE
 N ONLYSUC,ONLYFAIL,ONLYADT,ONLYACK,ONLYA28,ONLYA08
 N ONLYMFN,ONLYMFK
 Q
 ;
PURGE  ;EP PURGE MPI HL7 MESSAGES
 ;
 N MPIIEN,MPIIEN2,MPIDATE,MPIDT1,MPIDAYS,MPITYPE,QUIT
 N GRDTOTAL,EVENTTOT,DIRECTOT,MSGTYPTO,ACKCODET,STATUSTO
 N CURRTM,PURGTM,USAGE,MAXUS,USCOUNT,MSGDT
 S (GRDTOTAL,EVENTTOT,DIRECTOT,MSGTYPTO,STATUSTO)=0
 S (MPIIEN,MPIIEN2,QUIT)=0
 ;S ^XTMP("AGMPPURG",0)=$$FMADD^XLFDT(DT,58)_U_DT_U_"AGMP MPI PURGE HLO MSGS"
 S CURRTM=$$NOW^XLFDT  ; CURRENT TIME
 S USAGE=+$G(^XTMP("AGMPPURG","AGE")) I USAGE<1 S USAGE=60 ;AGE FOR PURGING UNSUCCESSFUL MSGS
 S X="N-"_USAGE,%DT="T" D ^%DT S PURGTM=Y  ;CUTOFF FOR UNSUCCESSFUL MESSAGES
 S MAXUS=+$G(^XTMP("AGMPPURG","MAX")) I MAXUS=0 S MAXUS=5000 ;MAX RESUBS OF UNSUCCESSFUL MSGS
 S USCOUNT=0
 F  S MPIIEN=$O(^HLB(MPIIEN)) Q:'MPIIEN!(QUIT)  D
 .S LINK=$P($G(^HLB(MPIIEN,0)),U,5)
 .Q:LINK'="MPI"
 .S MPIDIREC=$P($G(^HLB(MPIIEN,0)),U,4)   ;DIRECTION INCOMING DO NOT HAVE A COMPLETION STATUS
 .S COMSTAT=$P($G(^HLB(MPIIEN,0)),U,20)  ;COMPLETION STATUS
 .S SCHEDPUR=$P($G(^HLB(MPIIEN,0)),U,9)  ;SCHEDULED PURGE
 .S MSGBOD=$P($G(^HLB(MPIIEN,0)),U,2)  ;MESSAGE BODY
 .S MSGTYPE=$P($G(^HLA(MSGBOD,0)),U,3)  ;MESSAGE TYPE
 .S EVENT=$P($G(^HLA(MSGBOD,0)),U,4)  ;EVENT
 .S TRANDATE=$P($G(^HLB(MPIIEN,0)),U,16)  ;TRANSMISSION DATE/TIME
 .S MSGID=$P($G(^HLB(MPIIEN,0)),U)   ;MESSAGE ID
 .S ACKCODE=$P($G(^HLA(MSGID,1,1,0)),U,2)
 .S MSGDT=$$HL7TFM^XLFDT($P($G(^HLB(MPIIEN,2)),U,2))  ;MESSAGE DATE/TIME
 .I COMSTAT="SU",$G(SCHEDPUR)>CURRTM Q  ;SUCCESSFUL MSG, NOT READY FOR PURGE
 .I COMSTAT'="SU",$G(MSGDT)>PURGTM Q  ;UNSUCCESSFUL MSG, NOT READY FOR PURGE
 .I COMSTAT'="SU",MPIDIREC="O" S USCOUNT=USCOUNT+1 Q:USCOUNT>MAXUS  D RESUB  ;UNSUCCESSFUL OB MSG
 .S GRDTOTAL=GRDTOTAL+1
 .S:EVENT'="" EVENTTOT(EVENT)=$G(EVENTTOT(EVENT))+1
 .S:MPIDIREC'="" DIRECTOT(MPIDIREC)=$G(DIRECTOT(MPIDIREC))+1
 .S:MSGTYPE'="" MSGTYPTO(MSGTYPE)=$G(MSGTYPTO(MSGTYPE))+1
 .S:ACKCODE'="" ACKCODET(ACKCODE)=$G(ACKCODET(ACKCODE))+1
 .S COMSTAT=$S(COMSTAT'="":COMSTAT,1:"UNDEF")
 .S STATUSTO=$G(STATUSTO(COMSTAT))+1
 .I '$D(ZTQUEUED) D
 ..W !!,"TRANDATE: ",TRANDATE
 ..W !,"PURGE: ",MPIIEN
 ..W !,"MPIDIREC: ",MPIDIREC
 ..W !,"MSG TYPE: ",MSGTYPE
 ..W !,"EVENT: ",EVENT
 ..W !,"ACKCODE: ",ACKCODE
 .S DA=MPIIEN,DIK="^HLB(" D ^DIK
 .S DA=MSGBOD,DIK="^HLA(" D ^DIK
 .D AC(MPIIEN,MSGID)  ;CLEAN UP FOR HLB
 .I MPIDIREC="I" D ADI,QUEUEI Q
 .I MPIDIREC="O" D ADO(SCHEDPUR),QUEUEO
 I '$D(ZTQUEUED) D PRINT
 Q
 ;
PRINT ;EP - PRINT COUNTS
 N EVENT,MPIDIREC,MSGTYPE,ACKCODE
 S EVENT=""
 F  S EVENT=$O(EVENTTOT(EVENT)) Q:EVENT=""  W !,"EVENT: ",EVENT,?25,EVENTTOT(EVENT)
 S MPIDIREC=""
 F  S MPIDIREC=$O(DIRECTOT(MPIDIREC)) Q:MPIDIREC=""  W !,"DIRECTION: ",MPIDIREC,?25,DIRECTOT(MPIDIREC)
 S MSGTYPE=""
 F  S MSGTYPE=$O(MSGTYPTO(MSGTYPE)) Q:MSGTYPE=""  W !,"MSG TYPE: ",MSGTYPE,?25,MSGTYPTO(MSGTYPE)
 S ACKCODE=""
 F  S ACKCODE=$O(ACKCODET(ACKCODE)) Q:ACKCODE=""  W !,"ACK CODE: ",ACKCODE,?25,ACKCODET(ACKCODE)
 W !,"GRAND TOT PURGED: ",GRDTOTAL
 Q
 ;
AC(MPIIEN,MSGID) ;DELETE "AC" XREF FOR IEN
 ;MPI EXAMPLE:HLB("AC","8990MPI14752 26",26)=
 ;STATION # MPI = 8990
 ;HL LOGICAL LINK = MPI
 ;MSG ID = 14752 26
 K ^HLB("AC",MSGID,MPIIEN)
 S CMP="8990MPI"_MSGID
 K ^HLB("AC",CMP,MPIIEN)
 Q
ADI ;DELETE "AD" XREF FOR "IN" IEN
 K ^HLB("AD","IN",MPIIEN)
 Q
ADO(SCHEDPUR) ;DELETE "AD" XREF FOR "OUT" IEN
 Q:$G(SCHEDPUR)=""
 ;EXAMPLE:  ^HLB("AD","OUT",3090819.1143,3)=""
 K ^HLB("AD","OUT",SCHEDPUR,MPIIEN)
 Q
QUEUEI ;DELETE "QUEUE" XREF FOR IEN
 ;EXAMPLE: ^HLB("QUEUE","IN",8990,"RPMS-MPI",42)
 K ^HLB("QUEUE","IN",TRANDATE,"RPMS-MPI",MPIIEN)
 Q
QUEUEO ;DELETE "QUEUE" XREF FOR IEN
 ;EXAMPLE: ^HLB("QUEUE","OUT","MPI:8899","MPI RPMS",41)=
 N HLOG,PORT,MPILINK,REC
 S HLOG=$O(^HLCS(870,"B","MPI",""))  ;MPI LOGICAL LINK
 S PORT=$$GET1^DIQ(870,HLOG_",",400.08,"E")  ;TCP/IP PORT (OPTIMIZED)
 S MPILINK="MPI:"_PORT
 K ^HLB("QUEUE","OUT",MPILINK,"MPI RPMS",MPIIEN)
 Q
RESUB ;SUBMIT A NEW MESSAGE FOR THE SAME PATIENT
 N MSGTYPE,SEGID,DFN,SEG,PID,X,SUCCESS
 I $G(MPIIEN)=""!($G(MSGBOD)="")!$G(^XTMP("AGMPPURG","NORESUB")) Q
 ;GET MESSAGE TYPE. SKIP BLANK OR A40.
 S MSGTYPE=$P($P($G(^HLB(MPIIEN,2)),"^",4),"~",2)
 I MSGTYPE=""!(MSGTYPE="A40") Q
 ;FIND DFN
 S SEGID=0,DFN=""
 F  S SEGID=$O(^HLA(MSGBOD,1,SEGID)) Q:'SEGID  D  Q:DFN'=""
 .S SEG=$G(^HLA(MSGBOD,1,SEGID,0))
 .I $E(SEG,1,3)'="PID" Q
 .S PID=$P(SEG,"^",4)
 .I PID="" Q
 .F X=1:1:$L(PID,"|") I $P($P(PID,"|",X),"~",5)="PI" S DFN=$P($P(PID,"|",X),"~")
 I DFN="" Q
 D CREATMSG^AGMPHLO(DFN,MSGTYPE,,.SUCCESS)
 Q
