BGPLD713 ; IHS/CMI/LAB - measure 31 ;
 ;;19.1;IHS CLINICAL REPORTING;**3**;MAY 30, 2019;Build 12
 ;
PREGSCRN ;EP
 S BGPTOB=$$TOBHF^BGPLD712(DFN,BGP20M,BGPEDATE)  ;get last HF from the 3 categories during the report period
 S BGPSDX=$$DX^BGPLD7(DFN,BGP20M,BGPEDATE)  ;LAST OF ANY SCREENING DX
 S BGPUDX=$$DXU^BGPLD7(DFN,BGP20M,BGPEDATE)  ;last of user dx
 S BGPSMDX=$$DXS^BGPLD7(DFN,BGP20M,BGPEDATE)  ;last of smoking
 S BGPSLDX=$$DXSL^BGPLD7(DFN,BGP20M,BGPEDATE)  ;LAST OF THE SMOKELESS
 S BGPXPHD=$$PED^BGPLD7(DFN,BGP20M,BGPEDATE)
 S BGP1320=$$DENT^BGPLD7(DFN,BGP20M,BGPEDATE)
 S BGPSCPT=$$CPTSM^BGPLD7(DFN,BGP20M,BGPEDATE)
 S BGPN6=$S(BGPTOB]"":1,1:0)
 I BGPSDX]"" S BGPN6=1
 I BGPSLDX]"" S BGPN6=1
 I BGPXPHD]"" S BGPN6=1
 I BGP1320]"" S BGPN6=1
 I BGPSCPT]"" S BGPN6=1
 I BGPUDX]"" S BGPN6=1
 I BGPSMDX]"" S BGPN6=1
 S (BGPVALUE,BGPVAL)=""
 S F=BGPTOB
 S %=""
 S T=$O(^ATXAX("B","BGP TOBACCO PAST USE DXS",0))
 I BGPSDX]"" S I=$P(BGPSDX,U,3) I $$ICD^BGPLUTL2(I,T,9) S %=1
 ;BGPN7 - USER
 D
 .;I $P(F,U,1)["CURRENT"!($P(F,U,1)["CESSATION")!($P(F,U,1)["HEAVY TOBACCO SMOKER")!($P(F,U,1)["LIGHT TOBACCO SMOKER") S BGPN7=1,BGPVAL=$P(BGPTOB,U,2)_" SCREEN (20 MONTHS), "_$P(BGPTOB,U,2)_" USER (20 MONTHS)" Q  ;SMOKING CATEGORY
 .I $P(F,U,4)="F108"!($P(F,U,4)="F109")!($P(F,U,4)="F002")!($P(F,U,4)="F122")!($P(F,U,4)="F121")!($P(F,U,4)="F030") S BGPN7=1,BGPVAL=$P(BGPTOB,U,2)_" SCREEN (20 MONTHS), "_$P(BGPTOB,U,2)_" USER (20 MONTHS)" Q  ;SMOKING CATEGORY
 .;I $P(F,U,4)["CURRENT"!($P(F,U,4)["CESSATION") S BGPN7=1,BGPVAL=$P(BGPTOB,U,5)_" SCREEN (20 MONTHS), "_$P(BGPTOB,U,5)_" USER (20 MONTHS)" Q  ;SMOKELESS CATEGORY
 .I $P(F,U,8)="F030"!($P(F,U,8)="F003") S BGPN7=1,BGPVAL=$P(BGPTOB,U,9)_" SCREEN (20 MONTHS), "_$P(BGPTOB,U,6)_" USER (20 MONTHS)" Q  ;SMOKELESS CATEGORY
 .;I $P(F,U,10)["CURRENT"!($P(F,U,10)["CESSATION") S BGPN7=1,BGPVAL=$P(BGPTOB,U,11)_" SCREEN (20 MONTHS), "_$P(BGPTOB,U,11)_" USER (20 MONTHS)" Q  ;ENDS
 .I $P(F,U,16)="F124"!($P(F,U,16)="F155") S BGPN7=1,BGPVAL=$P(BGPTOB,U,14)_" SCREEN (20 MONTHS), "_$P(BGPTOB,U,14)_" USER (20 MONTHS)" Q  ;ENDS
 .I BGPUDX]"" S BGPN7=1,BGPVAL=$$DATE^BGPLUTL($P(BGPUDX,U,2))_" SCREEN (20 MONTHS), "_$$DATE^BGPLUTL($P(BGPUDX,U,2))_" USER (20 MONTHS)" Q
 .I BGPSMDX]"" S BGPN7=1,BGPVAL=$$DATE^BGPLUTL($P(BGPSMDX,U,2))_" SCREEN (20 MONTHS), "_$$DATE^BGPLUTL($P(BGPSMDX,U,2))_" USER (20 MONTHS)" Q
 .I BGPSLDX]"" S BGPN7=1,BGPVAL=$$DATE^BGPLUTL($P(BGPSLDX,U,2))_" SCREEN (20 MONTHS), "_$$DATE^BGPLUTL($P(BGPSLDX,U,2))_" USER (20 MONTHS)" Q
 .I ($P(BGPSCPT,U)="1034F")!($P(BGPSCPT,U)="1035F")!($P(BGPSCPT,U)="G0376")!($P(BGPSCPT,U)="G0375")!($P(BGPSCPT,U)=99407)!($P(BGPSCPT,U)="G9276") D
 ..S BGPN7=1,BGPVAL=$$DATE^BGPLUTL($P(BGPSCPT,U,2))_" SCREEN (20 MONTHS), "_$$DATE^BGPLUTL($P(BGPSCPT,U,2))_" USER (20 MONTHS)" Q
 .I $P(BGPSCPT,U)=99406!($P(BGPSCPT,U)="G8455")!($P(BGPSCPT,U)="G8456")!($P(BGPSCPT,U)="G8402")!($P(BGPSCPT,U)="G8453") D
 ..S BGPN7=1,BGPVAL=$$DATE^BGPLUTL($P(BGPSCPT,U,2))_" SCREEN (20 MONTHS), "_$$DATE^BGPLUTL($P(BGPSCPT,U,2))_" USER (20 MONTHS)" Q
 ;BGPN8 - SMOKER OR NOT
 D
 .I $P(F,U,4)="F108"!($P(F,U,4)="F109")!($P(F,U,4)="F002")!($P(F,U,4)="F122")!($P(F,U,4)="F121")!($P(F,U,4)="F030") S BGPN8=1,BGPVAL=BGPVAL_", "_$P(F,U,2)_" SMOKER (20 MONTHS)" Q
 .I BGPSMDX]"" S BGPN8=1,BGPVAL=BGPVAL_", "_$$DATE^BGPLUTL($P(BGPSMDX,U,2))_" SMOKER (20 MONTHS)" Q
 .I $P(BGPSCPT,U)="1034F"!($P(BGPSCPT,U)="G0376")!($P(BGPSCPT,U)="G0375")!($P(BGPSCPT,U)=99407)!($P(BGPSCPT,U)=99406)!($P(BGPSCPT,U)="G8455")!($P(BGPSCPT,U)="G8402")!($P(BGPSCPT,U)="G8453") D
 ..S BGPN8=1,BGPVAL=BGPVAL_", "_$$DATE^BGPLUTL($P(BGPSCPT,U,2))_" SMOKER (20 MONTHS)" Q
 ;BGPN9 - SMOKELESS
 D
 .I $P(F,U,8)="F030"!($P(F,U,8)="F003") S BGPN9=1,BGPVAL=BGPVAL_", "_$P(F,U,6)_" SMOKELESS (20 MONTHS)" Q
 .I $P(BGPSCPT,U)="1035F"!($P(BGPSCPT,U)="G8456") S BGPN9=1,BGPVAL=BGPVAL_", "_$$DATE^BGPLUTL($P(BGPSCPT,U,2))_" SMOKELESS (20 MONTHS)" Q
 .I BGPSLDX]"" S BGPN9=1,BGPVAL=BGPVAL_", "_$$DATE^BGPLUTL($P(BGPSLDX,U,2))_" SMOKELESS (20 MONTHS)" Q
 ;BGPN5 - ETS
 I $P(F,U,9)="SMOKER IN HOME"!($P(F,U,9)["ENVIRON") S BGPN10=1,BGPVAL=$S(BGPVAL["SCREEN (20 MONTHS)":BGPVAL_", "_$P(F,U,10)_" ETS (20 MONTHS)",1:$P(F,U,10)_" SCREEN (20 MONTHS), ETS (20 MONTHS)")
 ;ENDS USER
 D
 .I $P(F,U,16)="F124"!($P(F,U,16)="F155") S BGPN12=1,BGPVAL=BGPVAL_", "_$P(F,U,14)_" ENDS (20 MONTHS)" Q
 I BGPN6,BGPVAL="" D
 .S T=" SCREEN (20 MONTHS)"
 .I BGPTOB]"" S BGPVAL=$S($P(BGPTOB,U,1)]"":$P(BGPTOB,U,2)_T,$P(BGPTOB,U,6)]"":$P(BGPTOB,U,6)_T,$P(BGPTOB,U,10)]"":$P(BGPTOB,U,10)_T,$P(BGPTOB,U,14)]"":$P(BGPTOB,U,14)_T,1:"") Q
 .I BGPSDX]"" S BGPVAL=$$DATE^BGPLUTL($P(BGPSDX,U,2))_" SCREEN (20 MONTHS)" Q
 .I BGPSCPT]"" S BGPVAL=$$DATE^BGPLUTL($P(BGPSCPT,U,2))_" SCREEN (20 MONTHS)" Q
 .I BGPXPHD]"" S BGPVAL=$$DATE^BGPLUTL($P(BGPXPHD,U,2))_" SCREEN (20 MONTHS)" Q
 .I BGP1320]"" S BGPVAL=$$DATE^BGPLUTL($P(BGP1320,U,2))_" SCREEN (20 MONTHS)" Q
 S V=$S(BGPD1:"UP",1:"")_$S(BGPACTCL:",AC",1:"")_$S(BGPD8:",PREG",1:"")
 S BGPVALUE=V_"|||"_BGPVAL
 Q
