BGPLD76 ;IHS/CMI/LAB - MEASURE LOGIC; 
 ;;19.1;IHS CLINICAL REPORTING;**3**;MAY 30, 2019;Build 12
 ;
 ;
TOBCESSD ;EP = tobacco cessaton, gpra dev v18
 I 'BGPACTUP S BGPSTOP=1 Q  ;must be at least user pop
TOBFOR S (BGPVALUD,BGPVALUE)=""
 S (BGPD1,BGPD2,BGPD3,BGPD4,BGPD5,BGPD6,BGPD7,BGPD8,BGPD9,BGPD10,BGPD11,BGPD12,BGPD13,BGPD14,BGPN1,BGPN2,BGPN3)=0
 K BGPTOBS,BGPTOBL,BGPTOBE,BGPTOBT
 S (BGPTOBSL,BGPTOBLL,BGPTOBEL,BGPTOBTL)=""  ;for last of each
 S (BGPCTU,BGPSMK,BGPSMKL,BGPSMKE,BGPDNV,BGPNMV,BGPGOT,BGPGOTS,BGPGOTL,BGPL,BGPPTU,BGPTU)=""
 ;get all TOBACCO (SMOKING) during report period
 S BGPL=""
 D ALLHF(DFN,BGPBDATE,BGPEDATE,"C017","BGPTOBS")
 S X=0 F  S X=$O(BGPTOBS(X)) Q:X'=+X!(BGPSMK)  D
 .S BGPL=X
 .I $P(BGPTOBS(BGPL),U,3)="F108" S BGPCTU=1,BGPSMK=1 Q
 .I $P(BGPTOBS(BGPL),U,3)="F109" S BGPCTU=1,BGPSMK=1 Q
 .I $P(BGPTOBS(BGPL),U,3)="F002" S BGPCTU=1,BGPSMK=1 Q
 .I $P(BGPTOBS(BGPL),U,3)="F122" S BGPCTU=1,BGPSMK=1 Q
 .I $P(BGPTOBS(BGPL),U,3)="F121" S BGPCTU=1,BGPSMK=1 Q
 .;I BGPTOBS(BGPL)="F030" S BGPCTU=1,BGPSMK=1 Q
 I BGPCTU S BGPDNV="USER: "_$P(BGPTOBS(BGPL),U,2)_"("_$$DATE^BGPLUTL($P(BGPTOBS(BGPL),U,1))_")",BGPGOT=1
 I BGPSMK S BGPDNV=BGPDNV_"; SMOKER: "_$P(BGPTOBS(BGPL),U,2)_"("_$$DATE^BGPLUTL($P(BGPTOBS(BGPL),U,1))_")",BGPGOTS=1
SML ;
 S BGPL=""
 D ALLHF(DFN,BGPBDATE,BGPEDATE,"C016","BGPTOBL")
 S X=0 F  S X=$O(BGPTOBL(X)) Q:X'=+X!(BGPSMKL)  D
 .S BGPL=X
 .I $P(BGPTOBL(BGPL),U,3)="F003" S BGPCTU=1,BGPSMKL=1 Q
 I BGPCTU,'BGPGOT S BGPDNV="USER: "_$P(BGPTOBL(BGPL),U,2)_"("_$$DATE^BGPLUTL($P(BGPTOBL(BGPL),U,1))_")",BGPGOT=1
 I BGPSMKL S BGPDNV=BGPDNV_"; SMOKELESS: "_$P(BGPTOBL(BGPL),U,2)_"("_$$DATE^BGPLUTL($P(BGPTOBL(BGPL),U,1))_")",BGPGOTL=1
ENDS ;
 S BGPL=""
 D ALLHF(DFN,BGPBDATE,BGPEDATE,"C019","BGPTOBE")
 S X=0 F  S X=$O(BGPTOBE(X)) Q:X'=+X!(BGPSMKE)  D
 .S BGPL=X
 .I $P(BGPTOBE(BGPL),U,3)="F124" S BGPCTU=1,BGPSMKE=1 Q
 .I $P(BGPTOBE(BGPL),U,3)="F155" S BGPCTU=1,BGPSMKE=1 Q
 I BGPCTU,'BGPGOT S BGPDNV="USER: "_$P(BGPTOBE(BGPL),U,2)_"("_$$DATE^BGPLUTL($P(BGPTOBE(BGPL),U,1))_")",BGPGOT=1
 I BGPSMKE S BGPDNV=BGPDNV_"; ENDS: "_$P(BGPTOBE(BGPL),U,2)_"("_$$DATE^BGPLUTL($P(BGPTOBE(BGPL),U,1))_")"
 ;
PREV ;get last of each before time period.
 S BGPBDX=$$DOB^AUPNPAT(DFN),BGPEDX=$$FMADD^XLFDT(BGPBDATE,-1)
 ;
PSMK I 'BGPSMK D   ;IF NOT A SMOKER GET LAST IN PREVIOUS TIME PERIOD
 .K BGPTOBS
 .S C=$$LASTHF^BGPLD7(DFN,"C017",BGPBDX,BGPEDX)
 .I C]"" S BGPTOBS(1)=$P(C,U,3)_"^"_$P(C,U,1)_"^"_$P(C,U,4)
 .;now recheck all
 .S BGPL=1 I $D(BGPTOBS(1)) D
 ..I $P(BGPTOBS(BGPL),U,3)="F108" S BGPPTU=1,BGPSMK=1 Q
 ..I $P(BGPTOBS(BGPL),U,3)="F109" S BGPPTU=1,BGPSMK=1 Q
 ..I $P(BGPTOBS(BGPL),U,3)="F002" S BGPPTU=1,BGPSMK=1 Q
 ..I $P(BGPTOBS(BGPL),U,3)="F122" S BGPPTU=1,BGPSMK=1 Q
 ..I $P(BGPTOBS(BGPL),U,3)="F121" S BGPPTU=1,BGPSMK=1 Q
 .Q:'BGPSMK
 .I 'BGPCTU,BGPPTU S BGPDNV="USER: "_$P(BGPTOBS(BGPL),U,2)_"("_$$DATE^BGPLUTL($P(BGPTOBS(BGPL),U,1))_")",BGPGOT=1
 .S BGPDNV=BGPDNV_"; SMOKER: "_$P(BGPTOBS(BGPL),U,2)_"("_$$DATE^BGPLUTL($P(BGPTOBS(BGPL),U,1))_")",BGPGOTS=1
PSML ;
 I 'BGPSMKL D
 .K BGPTOBL
 .S C=$$LASTHF^BGPLD7(DFN,"C016",BGPBDX,BGPEDX)
 .I C]"" S BGPTOBL(1)=$P(C,U,3)_"^"_$P(C,U,1)_"^"_$P(C,U,4)
 .S BGPL=1 I $D(BGPTOBL(1)) D
 ..I $P(BGPTOBL(BGPL),U,3)="F003" S BGPPTU=1,BGPSMKL=1 Q
 .Q:'BGPSMKL
 .I BGPPTU,BGPDNV'["USER:" S BGPDNV="USER: "_$P(BGPTOBL(BGPL),U,2)_"("_$$DATE^BGPLUTL($P(BGPTOBL(BGPL),U,1))_")",BGPGOT=1
 .S BGPDNV=BGPDNV_"; SMOKELESS: "_$P(BGPTOBL(BGPL),U,2)_"("_$$DATE^BGPLUTL($P(BGPTOBL(BGPL),U,1))_")",BGPGOTL=1
PREVENDS ;
 I 'BGPSMKE D
 .K BGPTOBE
 .S C=$$LASTHF^BGPLD7(DFN,"C019",BGPBDX,BGPEDX)
 .I C]"" S BGPTOBE(1)=$P(C,U,3)_"^"_$P(C,U,1)_"^"_$P(C,U,4)
 .S BGPL=1 I $D(BGPTOBE(1)) D
 ..I $P(BGPTOBE(BGPL),U,3)="F124" S BGPTU=1,BGPSMKE=1 Q
 ..I $p(BGPTOBE(BGPL),U,3)="F155" S BGPTU=1,BGPSMKE=1 Q
 .Q:'BGPSMKE
 .I BGPTU,'BGPCTU,BGPDNV'["USER:" S BGPDNV="USER: "_$P(BGPTOBE(BGPL),U,2)_"("_$$DATE^BGPLUTL($P(BGPTOBE(BGPL),U,1))_")",BGPGOT=1
 .S BGPDNV=BGPDNV_"; ENDS: "_$P(BGPTOBE(BGPL),U,2)_"("_$$DATE^BGPLUTL($P(BGPTOBE(BGPL),U,1))_")"
 ;
 ;
SET ;
 I BGPCTU!(BGPPTU) S BGPTU=1
 I 'BGPTU S BGPSTOP=1 D KVARS Q  ;not in this denominator at all
 S BGPD1=1  ;UP
 I BGPACTCL S BGPD2=1
 I BGPD1,BGPAGEB<12 S BGPD3=1
 I BGPD1,BGPAGEB>11,BGPAGEB<18 S BGPD4=1
 I BGPD1,BGPAGEB>17 S BGPD5=1
 I BGPD2,BGPAGEB<12 S BGPD6=1
 I BGPD2,BGPAGEB>11,BGPAGEB<18 S BGPD7=1
 I BGPD2,BGPAGEB>17 S BGPD8=1
 ;
 ;get numerator stuff
 ;BGPN1=tobacco cessation counseling or prescription
 ;BGPN2=quit
 ;BGPN3 - any of them
 S BGPTC1=$$PED^BGPLD711(DFN,BGPBDATE,BGPEDATE,1)
 I $P(BGPTC1,U)]"" S BGPN1=1,BGPN2=1  ;EITHER, EDUC
 ;did they quit?  check each
 ;SMOKER
 S BGPQ="",BGPC=BGPSMK+BGPSMKL+BGPSMKE,BGPC1=0
 I BGPSMK S X=$$LASTHF^BGPLD7(DFN,"C017",$$DOB^AUPNPAT(DFN),BGPEDATE) I $P(X,U,4)="F004"!($P(X,U,4)="F024") S BGPQ="QUIT SMOKING: "_$P(X,U,2)_" "_$P(X,U,1),BGPC1=BGPC1+1
 I BGPSMKL S X=$$LASTHF^BGPLD7(DFN,"C016",$$DOB^AUPNPAT(DFN),BGPEDATE) I $P(X,U,4)="F005"!($P(X,U,4)="F023") S BGPQ=BGPQ_$S(BGPQ]"":"; ",1:"")_"QUIT SMOKELESS: "_$P(X,U,2)_" "_$P(X,U,1),BGPC1=BGPC1+1
 I BGPSMKE S X=$$LASTHF^BGPLD7(DFN,"C019",$$DOB^AUPNPAT(DFN),BGPEDATE) I $P(X,U,4)="F125"!($P(X,U,4)="F126") S BGPQ=BGPQ_$S(BGPQ]"":"; ",1:"")_"QUIT ENDS: "_$P(X,U,2)_" "_$P(X,U,1),BGPC1=BGPC1+1
 I BGPC=BGPC1 S BGPN1=1,BGPN3=1,BGPQ=BGPQ_";QUIT ALL"
S2 ;SET BGPVALUE
 S BGPVALUE="UP"_$S(BGPD2:",AC",1:"")_" "_BGPDNV
 D
 .S BGPVALUE=BGPVALUE_"|||"_$S($P(BGPTC1,U):"COUNSEL: "_$$DATE^BGP7UTL($P(BGPTC1,U))_" "_$P(BGPTC1,U,2),1:"")
 .I BGPQ]"" S BGPVALUE=BGPVALUE_$S($P(BGPVALUE,"|||",2)]"":"; "_BGPQ,1:BGPQ)   ;_" "_$P(BGPQ,U,3)
KVARS ;
 Q:$G(BGPINFO)
 K BGPTOBS,BGPTOBL,BGPTOBE,BGPTOBT,BGPTOBSL,BGPTOBLL,BGPTOBEL,BGPTOBTL,BGPTU,BGPSMK,BGPSMKL,BGPSMKE,BGPGOT,BGPGOTS,BGPGOTL,BGPL,BGPTU,BGPCTU,BGPPTU
 Q
ALLHF(P,BD,ED,CAT,RETVAL) ;
 NEW H,D,C,N
 S (H,D,C)=0
 S N=CAT
 I N="" Q ""
 S CAT=$O(^AUTTHF("B",CAT,0))
 I 'CAT S CAT=$O(^AUTTHF("C",N,0))
 I 'CAT Q ""
 F  S H=$O(^AUTTHF("AC",CAT,H))  Q:'+H  D
 .Q:'$D(^AUPNVHF("AA",DFN,H))
 .S D="" F  S D=$O(^AUPNVHF("AA",DFN,H,D)) Q:D'=+D  D
 ..Q:(9999999-D)>ED  ;after time frame
 ..Q:(9999999-D)<BD  ;before time frame
 ..S C=C+1
 ..S @RETVAL@(C)=(9999999-$P(D,"."))_"^"_$P(^AUTTHF(H,0),U,1)_"^"_$P(^AUTTHF(H,0),U,2)
 .Q
 Q
