BGPL7 ;IHS/CMI/LAB-CREATED BY ^ATXSTX ON AUG 06, 2019;
 ;;19.1;IHS CLINICAL REPORTING;**1**;MAY 30, 2019;Build 7
 ;
 ; See referenced routines to see taxonomies being loaded.
 ;
START ;
 D ^BGPL7A ;    BGP IPC FLU ENCOUNTER CPTS
 D ^BGPL7B ;    BGP IPC INFLUENZA CPT CODES
 D ^BGPL7C ;    BGP IPC INFLUENZA CVX CODES
 D ^BGPL7D ;    BGP IPC DTAP CVX CODES
 D ^BGPL7E ;    BGP IPC DTAP CPT CODES
 D ^BGPL7F ;    BGP IPC HIB CPT CODES
 D ^BGPL7G ;    BGP IPC PNEUMO CVX CODES
 D ^BGPL7H ;    BGP IPC PNEUMO CPT CODES
 D ^BGPL7I ;    BGP IPC HEPA CVX CODES
 D ^BGPL7J ;    BGP IPC ROTA 3 DOSE CVX CODES
 D ^BGPL7K ;    BGP IPC CHILD FLU CPT CODES
 D ^BGPL7L ;    BGP IPC CHILD FLU CVX CODES
 D ^BGPL7M ;    BGP IPC HYSTERECTOMY CPTS
 D ^BGPL7N ;    BGP IPC HPV LOINC CODES
 D ^BGPL7O ;    BGP IPC MAMMOGRAM LOINC CODES
 D ^BGPL7P ;    BGP IPC CT COLONOGRAPHY CPTS
 D ^BGPL7Q ;    BGP IPC DEP SCRN ENC CPTS
 D ^BGPL7R ;    BGP IPC DEP REM OFFICE CPTS
 D ^BGPL7S ;    BGP IPC BMI ENCOUNTER CPTS
 D ^BGPL7T ;    BGP IPC ESRD OPT SRV CPTS
 D ^BGPL7U ;    BGP IPC KIDNEY TRANSPLANT CPTS
 D ^BGPL7V ;    BGP IPC PREVCARE OTHER CPTS
 Q
