AGED14 ; IHS/OIT/NKD - EDIT PG 11 - SEXUAL ORIENTATION/GENDER IDENTITY DATA ; 04/06/2020
 ;;7.1;PATIENT REGISTRATION;**15**;AUG 25, 2005;Build 1
 ;
VAR ;
 N AG,AGI,AGY,CLLST,DFOUT,DIR,DIROUT,DLOUT,DQOUT,DTOUT,DUOUT,DIRUT,DOTS,MYERRS,MYVARS,ROUTID,Y
 ;
 ;Initialize variables
 S ROUTID=$P($T(+1)," ")  ;SET ROUTINE ID FOR PROGRAMMER VIEW
 S $P(DOTS,".",22)="."
 ;
 ;Draw the page
 D DRAW
 ;
 ;Quit if View Mode
 Q:$D(AGSEENLY)
 ;
 ;Print Header
 W !,AGLINE("EQ")
 ;
 K AG("ER")
 ;
 ;Prompt user for input
 K DIR S DIR("A")="CHANGE which item? ("_$S('AG("E"):0,1:"1-"_AG("E"))_") NONE//" D READ
 I $D(MYERRS("C","E")),(Y'?1N.N),(Y'=AGOPT("ESCAPE")) D  H 3 D KILL G VAR
 . W !,"ERRORS ON THIS PAGE. PLEASE FIX BEFORE EXITING!!"
 ;
 ;Quit on "^^" entry
 I Y=AGOPT("ESCAPE") S DIROUT=1 G END
 ;
 ;Additional exit handling
 I $D(DFOUT)!$D(DIROUT)!$D(DTOUT)!$D(DUOUT)!$D(DLOUT)!(Y["N") G END
 ;
 ;Loop if there is still an error
 I $D(AG("ERR")) D KILL G VAR
 ;
 ;Switch Pages
 I $D(AG("ED"))&('$D(AGXTERN)) N PAGE S PAGE=AG("ED") D KILL S AG("ED")=PAGE K PAGE G @("^AGED"_AG("ED"))
 ;
 ;Edit field(s)
 I $D(DQOUT)!(+Y<1)!(+Y>AG("E")) W !!,"You must enter a number from 1 to ",AG("E") H 2 D KILL G VAR
 S AGY=Y
 ;
 I $TR(AGY,",")'?1N.N W !!,"Invalid entry - Enter a line number or line numbers separated by a ',' to edit" H 3 G VAR
 F AGI=1:1 S AG("SEL")=+$P(AGY,",",AGI) Q:AG("SEL")<1!(AG("SEL")>AG("E"))  D
 . D @(CLLST(AG("SEL")))
 D UPDATE1^AGED(DUZ(2),DFN,2,"")
 G VAR
END ;
 K AG,AGI,AGIO,AGY,CLLST,DLOUT,DQOUT,DFOUT,DTOUT,DA,AGSCRN,Y,QUAN,TRIBE
 K ROUTID
 Q:$D(AGXTERN)
 Q:$D(DIROUT)
 G ^AGED10A:$D(DUOUT)
 Q
 ;Variable clean up
KILL K AG,AGI,AGY,CLLST,DFOUT,DIR,DIROUT,DLOUT,DQOUT,DTOUT,DUOUT,DIRUT,DOTS,MYERRS,MYVARS,ROUTID,Y
 Q
 ;
DRAW ;EP
 S CLLST=0
 S CALLS="PRN^AGED14,LSEX^AGED14,GI^AGED14,SO^AGED14"
 S AG("PG")=11
 S AG("N")=4
 S ROUTID=$P($T(+1)," ")  ;SET ROUTINE ID FOR PROGRAMMER VIEW
 S DA=DFN
 D ^AGED                          ;Main editor routine
 K ^UTILITY("DIQ1",$J)
 F AG=1:1:AG("N") D
 . N AGSCRN,LBL,LEN,CLM,DIC,DR,VLEN,VALUE,CNT
 . S AGSCRN=$P($T(@1+AG),";;",2,17)
 . S LBL=$P(AGSCRN,U)
 . S LEN=$P(AGSCRN,U,2)
 . S CLM=$P(AGSCRN,U,3)
 . S DIC=$P(AGSCRN,U,4)
 . S DR=$P(AGSCRN,U,5)
 . S VLEN=$P(AGSCRN,U,6)
 . ;
 . ;Prompt position
 . I CLM="" W !
 . E  W ?CLM
 . ;
 . ;Display Number
 . S CLLST=CLLST+1,CLLST(CLLST)=$P(CALLS,",",AG),AG("E")=CLLST
 . W CLLST,". "
 . ;
 . ;Display label
 . W LBL,$$REPEAT^XLFSTR(".",LEN-$L(LBL)),": "
 . ;
 . I AG=1 D  Q
 . . S VALUE=$$GETPRN^AUPNSOGI(DFN,$S($$CHKPRN^AUPNSOGI(DFN,"ASKU")!$$CHKPRN^AUPNSOGI(DFN,"UNK"):"E",1:"D")) W VALUE
 . I AG=2 D  Q
 . . S VALUE=$$GETLSEX^AUPNSOGI(DFN) I $L(VALUE) W $P(VALUE,U,2)," (",$P(VALUE,U,3),")"
 . I AG=3 D  Q
 . . N CNT
 . . S VALUE=$$GETGI^AUPNSOGI(DFN,"E") F CNT=2:1:$L(VALUE,U) W $P(VALUE,U,CNT) I CNT<$L(VALUE,U) W !,?32
 . I AG=4 D  Q
 . . N CNT
 . . S VALUE=$$GETSO^AUPNSOGI(DFN,"E") F CNT=2:1:$L(VALUE,U) W $P(VALUE,U,CNT) I CNT<$L(VALUE,U) W !,?32
 . ;
 . S VALUE=$$GET1^DIQ(DIC,DFN,DR)
 . S:VLEN>0 VALUE=$E(VALUE,1,VLEN)
 . W VALUE
 ;
 W !,AGLINE("EQ")
 K MYERRS,MYVARS
 D FETCHERR^AGEDERR(AG("PG"),.MYERRS)
 S MYVARS("DFN")=DFN,MYVARS("FINDCALL")="",MYVARS("SELECTION")=$G(AGSELECT),MYVARS("SITE")=DUZ(2)
 D EDITCHEK^AGEDERR(.MYERRS,.MYVARS,1)
 W !,AGLINE("-")
 D VERIF^AGUTILS
 Q
PREF ;EP - EDIT PREFERRED NAME
 N DA,DR,DIE,DUOUT,DTOUT,Y
 S DA=DFN
 S DIE="^AUPNPAT("
 S DR="9001Preferred Name"
 D ^DIE
 ;
 Q
 ;
PRN ;EP - EDIT PRONOUNS
 N DA,DR,DIE,DUOUT,DTOUT,Y
 S DA=DFN
 S DIE="^AUPNPAT("
 S DR="9002Pronouns"
 D ^DIE
 Q:$D(DUOUT)!$D(DTOUT)!$D(Y)
 ;
 S DA=DFN
 S DIE="^AUPNPAT(",DIE("NO^")=""
 S DR="9003"_$S($$CHKPRN^AUPNSOGI(DFN,"OTH"):"R~Other Pronouns",1:"////@")
 D ^DIE
 ;
 Q
 ;
LSEX ;EP - EDIT LEGAL SEX
 N DA,DR,DIC,DIE,DUOUT,DTOUT,X,Y,RES,CNT
 S RES=$$HISTLSEX^AUPNSOGI(DFN,,,.RES)
 W !!,"EFFECTIVE DT",?15,"LEGAL SEX",?30,"LEGAL SEX SOURCE",?68,"DT ENTERED",!,$$REPEAT^XLFSTR("-",80)
 I '+RES W !,"No Legal Sex records to display."
 S CNT=0 F  S CNT=$O(RES(CNT)) Q:'CNT  D
 . W !,$$FMTE^XLFDT($P(RES(CNT),U),5),?15,$P(RES(CNT),U,2),?30,$E($P(RES(CNT),U,3),1,37),?68,$P(RES(CNT),U,4)
 W !,$$REPEAT^XLFSTR("-",80)
 ;
 S DIC="^AUPNPAT("_DFN_",92,"
 S DA(1)=DFN
 S DIC(0)="AELMQZ"
 S DIC("A")="Select Effective Date of Legal Sex: "
 S DIC("B")=$P(RES,U,2)
 S DIC("DR")=".01;1;2;3////"_$$DT^XLFDT
 D ^DIC
 K DIC
 Q:$D(DUOUT)!$D(DTOUT)!(+Y<1)
 Q:+$$HISTLSEX^AUPNSOGI(DFN)>+RES
 ;
 S DA=+Y,DA(1)=DFN
 S DIE="^AUPNPAT("_DFN_",92,"
 S DR=".01;1;2"
 D ^DIE
 ;
 Q
 ;
SO ;EP - EDIT SEXUAL ORIENTATION
 N DA,DR,DIE,DUOUT,DTOUT,X,Y,OLD,NEW
 ;
 S OLD=$$GETSO^AUPNSOGI(DFN,"I")
 ; ALWAYS EDIT ENTRY FOR TODAY, CREATE/COPY VALUES FROM PREVIOUS IF NEEDED
 S NEW=$S($P(OLD,U)'=$$DT^XLFDT:$$SETSO^AUPNSOGI(DFN,$P(OLD,U,2,$L(OLD,U)-1),$P(OLD,U,$L(OLD,U))),1:OLD)
 ;
 S DA=$P(NEW,U),DA(1)=DFN
 S DIE="^AUPNPAT("_DA(1)_",93,"
 S DR="1Sexual Orientation(s)"
 D ^DIE
 ;
 ; IF USER EXITED OR TIMED-OUT, CHECK IF CHANGES WERE MADE THEN QUIT
 I $D(Y)!$D(DTOUT) D  Q
 . ; IF ENTRY WAS CREATED AND VALUES ARE THE SAME, DELETE NEW ENTRY
 . I $P(OLD,U)'=$P(NEW,U),$P(OLD,U,2,99)=$P($$GETSO^AUPNSOGI(DFN,"I"),U,2,99) S NEW=$$SETSO^AUPNSOGI(DFN,"@")
 ;
 S DA=$P(NEW,U),DA(1)=DFN
 S DIE="^AUPNPAT("_DA(1)_",93,",DIE("NO^")=""
 S DR="2"_$S($$CHKSO^AUPNSOGI(DFN,"OTH"):"R~Other Sexual Orientation",1:"////@")
 I $$SO^AUTSOGI($G(X),"C")="OTH"!('$$CHKSO^AUPNSOGI(DFN,"OTH")) D ^DIE
 ;
 D CHKSG^AGUTL2(DFN,"S")
 ;
 Q
 ;
GI ;EP -  EDIT GENDER IDENTITY
 N DA,DR,DIE,DUOUT,DTOUT,X,Y,OLD,NEW
 ;
 S OLD=$$GETGI^AUPNSOGI(DFN,"I")
 ; ALWAYS EDIT ENTRY FOR TODAY, CREATE/COPY VALUES FROM PREVIOUS IF NEEDED
 S NEW=$S($P(OLD,U)'=$$DT^XLFDT:$$SETGI^AUPNSOGI(DFN,$P(OLD,U,2,$L(OLD,U)-1),$P(OLD,U,$L(OLD,U))),1:OLD)
 ;
 S DA=$P(NEW,U),DA(1)=DFN
 S DIE="^AUPNPAT("_DA(1)_",94,"
 S DR="1Gender Identity(s)"
 D ^DIE
 ;
 ; IF USER EXITED OR TIMED-OUT, CHECK IF CHANGES WERE MADE THEN QUIT
 I $D(Y)!$D(DTOUT) D  Q
 . ; IF ENTRY WAS CREATED AND VALUES ARE THE SAME, DELETE NEW ENTRY
 . I $P(OLD,U)'=$P(NEW,U),$P(OLD,U,2,99)=$P($$GETGI^AUPNSOGI(DFN,"I"),U,2,99) S NEW=$$SETGI^AUPNSOGI(DFN,"@")
 ;
 S DA=$P(NEW,U),DA(1)=DFN
 S DIE="^AUPNPAT("_DA(1)_",94,",DIE("NO^")=""
 S DR="2"_$S($$CHKGI^AUPNSOGI(DFN,"OTH"):"R~Other Gender Identity",1:"////@")
 I $$GI^AUTSOGI($G(X),"C")="OTH"!('$$CHKGI^AUPNSOGI(DFN,"OTH")) D ^DIE
 ;
 D CHKSG^AGUTL2(DFN,"G")
 ;
 Q
 ;
READ ;EP
 D EDREAD^AGUTL2
 Q
 ;
 ;
 ; ****************************************************************
 ; ON LINES BELOW:
 ; PIECE 1= FLD LBL
 ; PIECE 2= FLD LENGTH
 ; PIECE 3= POSITION ON LINE TO DISP FLD, IF BLANK NEW LINE
 ; PIECE 4= FILE #
 ; PIECE 5= FLD #
 ; PIECE 6= Length (optional)
1 ;
 ;;PRONOUN^27^^9000001^9002
 ;;LEGAL SEX^27^^9000001^9201
 ;;GENDER IDENTITY^27^^9000001^9401
 ;;SEXUAL ORIENTATION^27^^9000001^9301
