AGLDOC ;IHS/SD/EFG - ADD/EDIT LEGAL DOCS ; [ 9/30/2003 2:10:07 PM ]
 ;;7.0;IHS PATIENT REGISTRATION;**2**;MAR 28, 2003
 ; THIS ROUTINE WAS CREATED TO REMOVE THESE SUBROUTINES
 ; FROM ^AGED11A DUE TO ROUTINE SIZE RESTRICTIONS
 ;
LDOC ; EP - ASK ADD OR EDIT LEGAL DOCUMENTS ENTRY
 N DA,DIC,DD,DLAYGO,DO,X,Y,DIK
 K DD,DO
 I $D(^AUPNPLDC("C",DFN))  D
 . S (PTR,REC,DOCPTR)=0
 . S (ENT,DOC,ADD)=""
 . W !,"ENTRY DT/TIME"
 . W ?23,"DOCUMENT"
 . W ?64,"DT ADDED TO FILE"
 . F  S PTR=$O(^AUPNPLDC("C",DFN,PTR)) Q:'PTR  D
 .. S REC=$G(^AUPNPLDC(PTR,0))
 .. S ENT=$P(REC,U,1)
 .. S DOCPTR=$P(REC,U,3)
 .. S DOC=$P(^AUPNELM(DOCPTR,0),U,1)
 .. S ADD=$P(REC,U,4)
 .. W !,$$FMTE^XLFDT(ENT,1)
 .. W ?23,$E(DOC,1,38)
 .. W ?64,$$FMTE^XLFDT(ADD,1)
 ; BEGIN CODE CHANGES FROM HERE THRU SUBROUTINE "EDTDOC" IHS/SD/EFG  AG*7*2  #16
 ;D NOW^%DTC
 ;S X=%
 ;S DIC="^AUPNPLDC("
 ;S DIC(0)="L"
 ;S DLAYGO=9000034
 ;S DIC("DR")=".03;.04;.02////^S X=DFN"
 ;D FILE^DICN W !,"***+Y= ",+Y
 ;Q:$D(DTOUT)!($D(DUOUT))
 ;I $P($G(^AUPNPLDC(+Y,0)),U,3)=""  D
 .; S DIK="^AUPNPLDC("
 .; S DA=+Y
 .; D ^DIK
 K DIR,X,Y
 S DIR(0)="F"
 S DIR("A")="Do you wish to E(dit) or A(dd) a new legal doc ?"
 D ^DIR
 Q:$D(DTOUT)!$D(DIRUT)!$D(DUOUT)
 I Y'="E"&(Y'="A") G LDOC
 I Y="E" D EDTDOC
 I Y="A" D ADDDOC
 Q
ADDDOC ; ADD NEW LEGAL DOC
 N DA,DIC,DD,DLAYGO,DO,X,Y,REC
 K DD,DO
 S DA=DFN
 D NOW^%DTC
 S X=%
 S DIC="^AUPNPLDC("
 S DIC(0)="L"
 S DLAYGO=9000034
 S DIC("DR")=".03R;.04R;.02////^S X=DFN"
 D ^DIC S REC=+Y
 Q:$D(DTOUT)!$D(DUOUT)!(REC=-1)
 Q
EDTDOC ; EDIT LEGAL DOC
 N DIE,DR,X,Y,REC,D
 S DIC(0)="AEQZ"
 S DA=DFN
 S D="C"
 S DIC("S")="I $P(^(0),U,2)=DFN"
 S DIC="^AUPNPLDC("
 D ^DIC S REC=+Y
 Q:$D(DTOUT)!$D(DUOUT)!(Y=-1)
 S DIE=DIC
 S DA=REC
 S DR=".03"
 D ^DIE
 I $P($G(^AUPNPLDC(DA,0)),U,3)=""  D
 . S DIK="^AUPNPLDC("
 . S DA=REC
 . D ^DIK
 I $P($G(^AUPNPLDC(DA,0)),U,3)'=""  D
 . S DR=".04"
 . S DA=REC
 . D ^DIE
 Q
