RAHLCV ;IHS/HQW/SCR - HL7 file update for IHS patch 10 [ 11/21/2001  2:49 PM ]
 ;;4.0;RADIOLOGY;**10**;Nov 20, 1997
 ;
 ;This routine is a VA routine incorporated into IHS patch 10 which
 ;performs two conversions needed to install patch 11. This routine
 ;is intended to be called from the post-init routine RA410CNV after
 ;confirmation of no HL7 data present and flag "DONE" set by
 ;the pre-init routine RA410MCK
 ;
 ;HISC/CAH;Conversion of Rad HL7 files to DHCP HL7 files
 ;;4.0;RADIOLOGY;**25**;Feb 24, 1992
 ;
EN I '$D(DUZ) D BMES^XPDUTL("Sorry, DUZ is undefined.") Q
 I $G(DUZ(0))'="@" D BMES^XPDUTL("Sorry, you must be in Programmer Mode.") Q
 I '$D(^HL(770,0))!('$D(^HL(771,0))) D BMES^XPDUTL("Sorry, the DHCP HL7 package is not installed.") S ^RA("IHSPATCH10","VA_HL7_CONVERSION",0)="FAILED" Q
 K ^TMP($J,"RAHLCV") S ERCNT=0
 D FILE771,FILE770,CLEAN,OPTDEL^RAHLCV1,RAD,MSG10^RAHLCV1,BULL,KILL
 S ^RA("IHSPATCH10","VA_HL7_CONVERSION",0)="DONE"
 Q
 ;
FILE771 ;Convert File 77.1 data to File 771
 D BMES^XPDUTL(".") I '$D(^RAH(77.1,0)) D MSG1^RAHLCV1 Q
 D BMES^XPDUTL(".") S RAIEN=$O(^RAH(77.1,"B","RADIOLOGY",0)) I 'RAIEN K RAIEN D MSG2^RAHLCV1 Q
 I $O(^HL(771,"B","RADIOLOGY",0)) K RAIEN D MSG3^RAHLCV1 Q
 S ^RA("IHSPATCH10","VA_HL7_CONVERSION",RAIEN)=""
 S RA0=$G(^RAH(77.1,RAIEN,0)),RAEC=$G(^RAH(77.1,RAIEN,"EC")),RAFS=$G(^RAH(77.1,RAIEN,"FS"))
 K DIC,DO,DD S DIC="^HL(771,",DIC(0)="LZ",X="RADIOLOGY" D FILE^DICN S RAIEN2=+Y K DIC
 K DIE S DIE="^HL(771,",DA=RAIEN2,DR="" S:$L($P(RA0,U,2)) DR=DR_"2///"_$P(RA0,U,2)_";" S:$L(RAEC) DR=DR_"101////"_RAEC_";" D ^DIE K DIE
 S:$L(RAFS) ^HL(771,RAIEN2,"FS")=RAFS
 D BMES^XPDUTL(".") I '$O(^RAH(77.1,RAIEN,"MSG",0)) G FILE770
 S ^HL(771,RAIEN2,"MSG",0)="^771.06P^^",(RAX,SUBERR)=0 F  S RAX=$O(^RAH(77.1,RAIEN,"MSG",RAX)) Q:RAX'?1N.N  D  
 .S RAX0=$G(^RAH(77.1,RAIEN,"MSG",RAX,0)) I RAX0=""!("^^^^^^^^"[RA0) Q
 .S X=$P(RAX0,U),RAMU=$P($G(^RAH(77.3,X,0)),U) I '$L(RAMU) S SUBERR=SUBERR+1 Q
 .S RAMUIEN=$O(^HL(771.2,"B",RAMU,0)) I RAMUIEN="" Q
 .S RARTN=$G(^RAH(77.1,RAIEN,"MSG",RAX,"R")) I RARTN["7" S RARTN=$P(RARTN,"7",1)_$P(RARTN,"7",2) ;Change to newer version of RAH* msg processing rtns
 . K DIC,DA,DD,DO,DINUM,DLAYGO S DIC(0)="L",DIC="^HL(771,"_RAIEN2_",""MSG"",",DA(2)=771,DA(1)=RAIEN2,X=RAMUIEN D FILE^DICN
 . D BMES^XPDUTL(".") I +Y>0 K DIE,DR S DIE="^HL(771,"_RAIEN2_",""MSG"",",DA=+Y,DA(1)=RAIEN2,DR="" S:$L(RARTN) DR=DR_"1////"_RARTN D:DR'="" ^DIE
 D:SUBERR>0 MSG4^RAHLCV1 D MSG4A^RAHLCV1
 K RAIEN,RAEC,RAFS,RAX,RAMU,DIE,DIC,DR,DA,RA0,RAMUIEN,RARTN
 Q
FILE770 ;Convert File 77.2 data to file 770 if entry exists in 77.2, and not 770
 D BMES^XPDUTL(".") I '$O(^RAH(77.2,0)) D MSG5^RAHLCV1 Q
 D BMES^XPDUTL(".") S RAIEN=0 F  S RAIEN=$O(^RAH(77.2,RAIEN)) Q:RAIEN'?1N.N  D  
 . S RA0=$G(^RAH(77.2,RAIEN,0)) Q:'$L(RA0)!("^^^^^^^^"[RA0)
 . S RANAME=$P(RA0,U) I $O(^HL(770,"B",RANAME,0)) D MSG6^RAHLCV1 Q
 . S RASTN=$P(RA0,U,2),RAFAC=$P(RA0,U,3),RAMAXB=$P(RA0,U,4),RATRIES=$P(RA0,U,5),RADEV=$P(RA0,U,6)
 . I RAFAC=""!(RASTN="") D MSG7^RAHLCV1 Q
 . S RALOG=$G(^RAH(77.2,RAIEN,"LOG"))
 . K DIC,DO,DD S DIC="^HL(770,",DIC(0)="L",X=RANAME,DIC("DR")="2////"_RASTN_";3////"_RAFAC
 . D FILE^DICN S RAIEN2=+Y K DIC
 . K DIE,DA,DR S DIE="^HL(770,",DA=RAIEN2,DR="" S:RAMAXB DR=DR_"4////"_RAMAXB_";" S:RATRIES DR=DR_"5////"_RATRIES_";" S:$L(RADEV) DR=DR_"6////"_RADEV_";" S DR=DR_"7///2.1" D ^DIE
 . D BMES^XPDUTL(".") I RALOG'="" S DIE="^HL(770,",DA=RAIEN2,DR="50////"_RALOG D ^DIE
 D BMES^XPDUTL(".") D MSG8^RAHLCV1 K DIE,DA,DR,DIC,DO,DD,RAIEN,RAIEN2,RAMAXB,RATRIES,RADEV,RAFAC,RALOG,RANAME,RASTN Q
CLEAN ;Delete data and DD's for files 77, 77.1, 77.2, 77.3, 77.4, 77.5, 77.6
 D BMES^XPDUTL(".") K DIU S DIU="^RAH(77,",DIU(0)="DT" D EN^DIU2
 F RAX=1:1:6 K DIU S DIU="^RAH(77."_RAX_",",DIU(0)="DT" D EN^DIU2
 K DIU D MSG9^RAHLCV1 Q
RAD ;If the RADIOLOGY entry is still not in File 771, stuff it in
 D BMES^XPDUTL(".") I $O(^HL(771,"B","RADIOLOGY",0)) Q
 K DIC,DO,DD S DIC="^HL(771,",DIC(0)="LZ",X="RADIOLOGY" D FILE^DICN S RAIEN2=+Y K DIC
 K DIE S DIE="^HL(771,",DA=RAIEN2,DR="" S DR=DR_"2///INACTIVE;101////~|\&" D ^DIE K DIE,DR S ^HL(771,RAIEN2,"FS")="^"
 S ^HL(771,RAIEN2,"MSG",0)="^771.06P^^" S RARTN="NONE^NONE^RAHLO^RAHLQ",RAMSG="ACK^ORF^ORU^QRY" F RAI=1:1:4 D  
 . S X=$P(RAMSG,U,RAI),RARTNIEN=$O(^HL(771.2,"B",X,0)) I 'RARTNIEN Q
 . K DIC,DA,DD,DO,DINUM,DLAYGO S DIC(0)="L",DIC="^HL(771,"_RAIEN2_",""MSG"",",DA(2)=771,DA(1)=RAIEN2,X=RARTNIEN D FILE^DICN
 . I +Y>0 K DIE,DR S DIE="^HL(771,"_RAIEN2_",""MSG"",",DA=+Y,DA(1)=RAIEN2,DR="" S DR=DR_"1////"_$P(RARTN,U,RAI) D ^DIE
 D BMES^XPDUTL(".") D MSG2A^RAHLCV1
 Q
BULL ;Send Mail message to user signed on
 ;
 ;This code has been modified to write the message to the screen as well
 ;as sending a mail bulletin for IHS patch10 IHS/HQW/SCR 10/25/01 **10**
 ;
 D BMES^XPDUTL("**HL7 CONVERSION COMPLETED SUCCESSFULLY.***")
 D MES^XPDUTL("A detailed mail message has been sent to you.")
 ;
 N DIFROM
 S XMY(DUZ)="",XMDUZ=.5,XMSUB="Rad HL7 to DHCP HL7 Conversion"
 S X=0 F  S X=$O(^TMP($J,"RAHLCV",X)) Q:X=""  S R(X)=^TMP($J,"RAHLCV",X)
 S XMTEXT="R(" D ^XMD Q
 ;
KILL K DIU,Y,RAI,RAIEN,RA0,RAEC,RAFS,RAX,RAMU,ERCNT,DIE,DIC,DR,DA,RAMUIEN,RARTN,RAMSG,XMY,XMSUB,XMDUZ,XMTEXT,X,R,RADEV,RAFAC,RAIEN2,RALOG,RAMAXB,RANAME,RASTN,RATRIES,RAX0,RARTNIEN,SUBERR
 K DIK,DO,DD,DLAYGO,RAUSER,RAUSER1,RAOPTIEN,RAOPT,^TMP($J,"RAHLCV") Q
