RAORR1 ; IHS/ADC/PDW -EDIT A REQUEST FROM OERR WHEN NEW 16:16 ;   [ 11/01/2001  11:07 AM ]
 ;;4.0;RADIOLOGY;**11**;NOV 20, 1997
 ;OE/RR Utility routine for Radiology
 ;
 I $S('$D(ORIFN):1,'$L(ORIFN):1,1:0) G END
 I $S('$D(ORPK):1,'$D(^RAO(75.1,+ORPK,0)):1,1:0) G END
 G END:'$D(ORVP)!('$D(ORL))!('$D(ORPV))
 ;S RADFN=+ORVP,RALIFN=+ORL,RAPIFN=+ORPV
 ;
 ;Above line modified for VA patches IHS/HQW/SCR - 9/5/01 **11**
 S RADFN=+ORVP,RALIFN=+ORL,RAPIFN=+ORNP
SELECT ;
 S RAORIFN=ORIFN,RAOIFN=+ORPK D OERR1
 Q
OERR1 ;
 S RAORD0=$S($D(^RAO(75.1,RAOIFN,0)):^(0),1:"") G END:'RAORD0 D SETDIV
 I ORACTION=1 S DA=RAOIFN,DIE="^RAO(75.1,",DR="[RA OERR EDIT]" D ^DIE K DR,DIE S RAORD0=^RAO(75.1,RAOIFN,0)
UPDATE ;
 S RABLNK="",$P(RABLNK," ",40)=""
 K RAMOD F I=0:0 S I=$O(^RAO(75.1,RAOIFN,"M","B",I)) Q:'I  I $D(^RAMIS(71.2,+I,0)) S RAMOD=$S('$D(RAMOD):$P(^(0),U),1:RAMOD_", "_$P(^(0),U))
 ;
 ;BEGIN changes for VA patches IHS/HQW/SCR - 9/5/01 **11**
 ;
 ;I $D(^RAMIS(71,+$P(RAORD0,U,2),0)) S RAPRC=$E($P(^(0),U),1,40),ORETURN("ORTX")=RAPRC_$S($D(RAMOD):$E(RABLNK,1,40-$L(RAPRC))_$E(RAMOD,1,80),1:""),ORETURN("ORIT")=$P(RAORD0,U,2)_";RAMIS(71,"
 ;S DIC="^RA(79.2,",DIC(0)="",X="RADIOLOGY" D ^DIC K DIC S ORETURN("ORPURG")=$S(Y<0:30,$D(^RA(79.2,+Y,.1)):+$P(^(.1),U,6),1:30)
 ;
 S RASEX=$P($G(^DPT(+RAORD0,0)),U,2)   ;IHS/HQW/SCR 9/5/01 **11**
 I $$ORVR^RAORDU()>2 S (RAPRC,ORETURN("ORTX",1))=$P($G(^RAMIS(71,+$P(RAORD0,U,2),0)),U)_"," D  ;IHS/HQW/SCR 9/5/01 **11**
 .I $D(RAMOD) S ORETURN("ORTX",2)="Modifiers: "_$E(RAMOD,1,80)_","  ;IHS/HQW/SCR 9/5/01 **11**
 .S ORETURN("ORTX",3)="Urgency: "_$S($P(RAORD0,U,6)=1:"STAT",$P(RAORD0,U,6)=2:"URGENT",1:"ROUTINE")_","   ;IHS/HQW/SCR 9/5/01 **11**
 .I $P(RAORD0,U,19)]"" S X=$P(RAORD0,U,19),ORETURN("ORTX",3)=ORETURN("ORTX",3)_"Transport: "+$S(X="a":"AMBULATORY",X="p":"PORTABLE",X="s":"STRETCHER",1:"WHEELCHAIR")_","   ;IHS/HQW/SCR 9/5/01 **11**
 .I $D(RASEX),RASEX'="M" S ORETURN("ORTX",3)=ORETURN("ORTX",3)_" Pregnant: "+$S($P(RAORD0,U,13)="n":"NO",$P(RAORD0,U,13)="y":"YES",1:"")   ;IHS/HQW/SCR 9/5/01 **11**
 .S ORETURN("ORIT")=$P(RAORD0,U,2)_";RAMIS(71,"   ;IHS/HQW/SCR 9/5/01 **11**
 I $$ORVR^RAORDU()<2 S RAPRC=$P($G(^RAMIS(71,+$P(RAORD0,U,2),0)),U) D   ;IHS/HQW/SCR 9/5/01 **11**
 .S ORETURN("ORTX")=$E(RAPRC,1,40)_$S($D(RAMOD):$E(RABLNK,1,40-$L(RAPRC))_$E(RAMOD,1,80),1:""),ORETURN("ORIT")=$P(RAORD0,U,2)_";RAMIS(71,"   ;IHS/HQW/SCR 9/5/01 **11**
 S DIC="^RA(79.2,",DIC(0)="N",X=+$P(^RAMIS(71,+$P(RAORD0,U,2),0),U,12) D ^DIC K DIC S ORETURN("ORPURG")=$S(Y<0:30,$D(^RA(79.2,+Y,.1)):+$P(^(.1),U,6),1:30)  ;IHS/HQW/SCR 9/5/01 **11**
 ;
 ;END changes for VA patches IHS/HQW/SCR - 9/5/01 **11**
 ;
 S ORETURN("ORSTRT")=$P(^RAO(75.1,RAOIFN,0),U,21)
 D RETURN^ORX
 I $D(ORGY),ORGY=9 D RELEASE
 D END Q
QUE ;
 F RAORIFN=0:0 S RAORIFN=$O(^XUTL("OR",$J,"RA",RAORIFN)) Q:'RAORIFN  F RAOIFN=0:0 S RAOIFN=$O(^(RAORIFN,RAOIFN)) Q:'RAOIFN  S RADIV=^(RAOIFN) D DIV I $D(^RAO(75.1,RAOIFN,0)) S RAORD0=^(0),RADFN=+RAORD0 D ^RAORDQ K ^XUTL("OR",$J,"RA",RAORIFN)
 ;
END ;
 K RAOIFN,RAORD0,DA,DIE,DR,RABLNK,RAMOD,RAPRC,DIC,RADFN,RALOCFLG,RADIV,RAFIN,RAL0,RALIFN,RALOC,RANME,RAPIFN,RAREQPRT,RAX,VA,RACAT,RAORIFN,RAWARD,RAOIFN0
 K RASEX   ;IHS/HQW/SCR 9/5/01 **11**
 Q
DIV ;
 I $D(RADIV),$D(^RA(79,+RADIV,.1)),$P(^(.1),U,21)="y" S RALOCFLG="" Q
 I '$D(RADIV) S RADIV=$O(^RA(79,"AL",+$P($G(^RAO(75.1,RAOIFN,0)),U,20),0)) Q:'RADIV  I $D(^RA(79,+RADIV,.1)),$P(^(.1),U,21)="y" S RALOCFLG=""
 Q
SETDIV ;
 ;set RADIV and RACAT
 S RAL0=$S($D(^SC(RALIFN,0)):^(0),1:0),RADIV=$S($D(^DG(40.8,+$P(RAL0,U,15),0)):+$P(^(0),U,7),1:0),RADIV=$S($D(^RA(79,RADIV,0)):RADIV,1:$O(^RA(79,0)))
 S RACAT=$P($P(^DD(75.1,4,0),$P(RAORD0,U,4)_":",2),";")
 Q
RELEASE ;
 ;called to release an order
 I $D(RADIV),$D(^RA(79,+RADIV,.1)),$P(^(.1),U,21)="y" S RALOCFLG=""
 I $S('$D(RADIV):1,'RADIV:1,1:0) S RADIV=$O(^RA(79,"AL",+$P($G(^RAO(75.1,RAOIFN,0)),U,20),0)) Q:'RADIV
 S DA=RAOIFN,DIE="^RAO(75.1,",DR="5////^S X=5" D ^DIE K DIE,DA,DR
 S RAMES="W """"" D ^RAORDQ K ^XUTL("OR",$J,"RA") Q
