BCHUDSP ; IHS/CMI/LAB - display record in detail ; 
 ;;2.0;IHS RPMS CHR SYSTEM;**1**;OCT 23, 2012;Build 6
 ;
 ;CALLER passes BCHR as record ien
EN ;EP
 Q:'$G(BCHR)
 Q:'$D(^BCHR(BCHR,0))
 D @("HEAD"_(2-($E(IOST,1,2)="C-")))
 ;D EOP
 D EOJ
 Q
 ;
HEAD1 ; if terminal
 W:$D(IOF) @IOF
HEAD2 ; if printer    
 NEW D0,DA,DIC,DIQ,DR,DL,DK,DX,S
 S BCHBRK=0 ;ACC
 S BCHVDSH="----------------------------"
 ;S X="",$P(X,"~",80)="" W X,!!
 S X="",$P(X,"~",80)="" W !,X,!!
 W ?13,"********** CONFIDENTIAL PATIENT INFORMATION **********",!
 W BCHVDSH,"     CHR RECORD     ",BCHVDSH
 S DIC="^BCHR(",DA=BCHR,DR=0 D EN^DIQ
 K ^UTILITY("DIQ1",$J)
 I '$D(^BCHR(BCHR,11)) G REST
 S DIC="^BCHR(",DA=BCHR,DR="1101:1103;1105:1113" D EN^DIQ1
 I $G(^UTILITY("DIQ1",$J,90002,BCHR,1101))]"",$Y>(IOSL-5) D EOP Q:BCHBRK
 I $G(^UTILITY("DIQ1",$J,90002,BCHR,1101))]""  S BCHX=$P(^DD(90002,1101,0),U)_": "_^UTILITY("DIQ1",$J,90002,BCHR,1101) W ?2,BCHX
 I $G(^UTILITY("DIQ1",$J,90002,BCHR,1102))]""  S BCHX=$P(^DD(90002,1102,0),U)_": "_^UTILITY("DIQ1",$J,90002,BCHR,1102) W ?40,BCHX,!
 I $G(^UTILITY("DIQ1",$J,90002,BCHR,1103))]""  S BCHX=$P(^DD(90002,1103,0),U)_": "_^UTILITY("DIQ1",$J,90002,BCHR,1103) W ?2,BCHX
 I $G(^UTILITY("DIQ1",$J,90002,BCHR,1105))]""  S BCHX=$P(^DD(90002,1105,0),U)_": "_^UTILITY("DIQ1",$J,90002,BCHR,1105) W ?40,BCHX,!
 F BCHY=1106:1:1113 D  Q:BCHBRK
 .Q:$G(^UTILITY("DIQ1",$J,90002,BCHR,BCHY))=""
 .I $Y>(IOSL-2) D EOP Q:BCHBRK
 .I $G(^UTILITY("DIQ1",$J,90002,BCHR,BCHY))]""  S BCHX=$P(^DD(90002,BCHY,0),U)_": "_^UTILITY("DIQ1",$J,90002,BCHR,BCHY) W ?2,BCHX,!
 S E=0
 F X=12,13,21,31,41,42,61,71,81,86,87,89 I $D(^BCHR(BCHR,X)) S E=1
 I E D EOP Q:BCHBRK
 K BCHT,BCHX,BCHY
 K ^UTILITY("DIQ1",$J)
 Q:BCHBRK
REST ;
 S DIC="^BCHR(",DA=BCHR,DR="12:99" D EN^DIQ
DSPLY1 ;DISPLAY V FILE DATA
 S BCHVFLE=90002 F BCHVL=0:0 S BCHVFLE=$O(^DIC(BCHVFLE)) Q:BCHVFLE>90002.09!(BCHVFLE'=+BCHVFLE)!(BCHBRK)  D DSPLY2 Q:BCHBRK  ;ACC
 I 'BCHBRK S X="",$P(X,"~",80)="" W !!,X,!!
 Q
 ;
DSPLY2 S BCHVNM=$P(^DIC(BCHVFLE,0),U)
 S BCHVDG=^DIC(BCHVFLE,0,"GL"),BCHVIGR=BCHVDG_"""AD"",BCHR,BCHVDFN)"
 S BCHVDFN=""!(BCHBRK) F BCHVI=1:1 S BCHVDFN=$O(@BCHVIGR) Q:BCHVDFN=""  D DSPLY3 Q:BCHBRK  ;ACC
 Q
 ;
DSPLY3 ;
 ;I $Y<(IOSL-5) W !!,"Return to continue, '^' to halt " R BCHX:DTIME S:'$T BCHBRK=1 S:BCHX="^" BCHBRK=1 K S W:$D(IOF) @IOF
 I $Y>(IOSL-5) D EOP
 Q:BCHBRK
 I BCHVI<2 S X=20-$L(BCHVNM),Y=X\2,Z=X-Y W !,BCHVDSH," ",$J("",Z),BCHVNM,$J("",Y)," ",BCHVDSH
 K DR
 S DIC=BCHVDG,DA=BCHVDFN,DIQ(0)="C" D EN^DIQ
 Q
 ;
EOJ ; EOJ CLEANUP
 I 'BCHBRK,IOST["C-" W ! S DIR(0)="E",DIR("A")="End of record display, HIT <RETURN> to continue" K DA D ^DIR K DIR
 K BCHVDFN,BCHVDG,BCHVDSH,BCHVFLE,BCHVI,BCHVIGR,BCHVL,BCHVNM,BCHX,BCHBRK,BCHT,BCHX,BCHY
 Q
 ;
EOP ; pause OR form feed between pages for terminal/printer
 I $E(IOST,1,2)="P-"!($D(IO("S"))) W @IOF Q
 W ! S DIR(0)="EO" D ^DIR K DIR S:$D(DUOUT) (DIRUT,BCHBRK)=1
 Q
