BEHOEP4 ; GDIT/IHS/FS - EPCS RPMS Reports - In OR EPCS VALIDATION REPORTS Option (Menu);29-Jun-2018 09:46;PLS
 ;;1.1;BEH COMPONENTS;**070001**;Mar 20, 2007;Build 10
 ;
 ;
 Q
PROFAUDT ;EP - EPCS Ad hoc Provider Logical Access Control Audit Report
 ;REP IS HANDLED BY REPORTS^ORDEA01
 N DISINC,PROVARRY,STARTDT,ENDDT,EXIT,SAVE
 W !!,"Report is available in Roll and scroll only!",!
 W "The report can be exported to the HFS host system. ",!
 W "A site has the ability to assign a user (i.e. security officer) to access",!
 W "the report.",!
 W "Report is run ad hoc.",!
 W "File input = BUSA",!
 S DISINC=$$DISPRMPT^BEHOEP3
 Q:$G(DISINC)="^"
 D PROVNAME^BEHOEP3(.PROVARRY)
 I $O(PROVARRY(0))'>0,$G(PROVARRY)="^" Q
 W:$O(PROVARRY(0))'>0 "ALL"
 D DTRANGE^BEHOEP3(.STARTDT,.ENDDT,.EXIT)
 Q:$G(EXIT)
 Q:DISINC=U
 S SAVE=("DISINC")=""
 D DEVICE^ORUTL("PRFAUDTQ^BEHOEP4","EPCS LOGICAL ACCESS AUDIT REPORT","Q",.SAVE)
 Q
 ;
PRFAUDTQ ;EP - TASKMAN ENTRY POINT
 ;CBUFFER IS HANDLED BY DEVICE^ORUTL OR TASKMAN
 N DOCS,DATA,ERROR,INDEX,PGNUM,COL,STOP,ACCOUNT,OUTPUT,COVERCOL
 N TMP,LOGDT,USR,LOGDESC,ACTION,RPTNAME,DSPLYSD,DSPLYED,NOW,I
 S RPTNAME="EPCS LOGICAL ACCESS AUDIT REPORT"
 ;RETRIEVE ALL USERS WITH A EPCS PROFILE HASH in FILE #200
 S DOCS=$NA(^TMP($J,"EPCSAUDIT")),DATA=$NA(^TMP($J,"EPCSAUDITDATA"))
 S DSPLYSD=$P($$UP^XLFSTR($$FMTE^XLFDT(STARTDT)),"@",1),DSPLYED=$P($$UP^XLFSTR($$FMTE^XLFDT(ENDDT)),"@",1)
 S NOW=$$UP^XLFSTR($$HTE^XLFDT($H)),NOW=$P(NOW,"@",1)_"  "_$P($P(NOW,"@",2),":",1,2),I=0
 K @DOCS,@DATA
 S I=$$SENSTIV1^BEHOEP3(.COL,"PAR",DSPLYSD,DSPLYED)
 S I=I+1,COL(I)="LOG DATE/TIME                      USER NAME                    ACTION"
 S I=I+1,COL(I)="    DESCRIPTION"
 S I=$$SENSTIV2^BEHOEP3(.COVERCOL,"PAR",DSPLYSD,DSPLYED)
 S I=I+1,COVERCOL(I)="LOG DATE/TIME                      USER NAME                    ACTION"
 S I=I+1,COVERCOL(I)="    DESCRIPTION"
 S SCR="I 1"
 S SCR=SCR_" & (($P($G("_"^"_"(0)),""^"",1))>="_STARTDT_")"
 S SCR=SCR_" & (($P($G("_"^"_"(0)),""^"",1))<="_ENDDT_")"
 S INDEX=$O(PROVARRY(0))
 I +INDEX>0 S TMP=" & ("
 I +INDEX>0 F  D  Q:(+INDEX'>0)
 .S TMP=$G(TMP)_"(($P($G("_"^"_"(0)),""^"",2))="_$G(INDEX)_")"
 .I $O(PROVARRY(INDEX))>0 S TMP=$G(TMP)_" ! "
 .S INDEX=$O(PROVARRY(INDEX))
 S:$G(TMP)'="" TMP=$G(TMP)_")",SCR=SCR_$G(TMP)
 S SCR=SCR_" & ($$UP^XLFSTR(($P($G("_"^"_"(0)),""^"",6)))[""EPCS CREDENTIALING"")"
 S SCR=SCR_" & (($P($G("_"^"_"(0)),""^"",5))'=""Q"")"
 S SCR=SCR_" & (($P($P($P($G("_"^"_"(1)),""^"",1),""|"",2),""~"",2))=""PP"")"
 ;BUSA AUDIT LOG SUMMARY File
 D LIST^DIC(9002319.01,,".02;.05;1;.02I","PQ",,STARTDT-1,,"B",SCR,,DOCS,"ERROR")
 I $D(ERROR) D  Q
 .D FMERROR^ORUTL(.ERROR)
 .S:$D(ZTQUEUED) ZTREQ="@"
 .K @DOCS
 S INDEX=0 F  S INDEX=$O(@DOCS@("DILIST",INDEX)) Q:+$G(INDEX)=0  D
 .S ACCOUNT=1
 .N ACCOUNT S ACCOUNT=$$ACTIVE^XUSER($P(@DOCS@("DILIST",INDEX,0),U,6))
 .I 'DISINC,(+ACCOUNT<1) Q
 .;INCLUDE USERS WHO CANNOT SIGN-ON IN ACTIVE LISTING
 .I ACCOUNT=0 S ACCOUNT=1
 .S LOGDT=$P(@DOCS@("DILIST",INDEX,0),U,2),USR=$P(@DOCS@("DILIST",INDEX,0),U,3)
 .S LOGDESC=$P($P(@DOCS@("DILIST",INDEX,0),U,5),"|",1),ACTION=$P(@DOCS@("DILIST",INDEX,0),U,4)
 .S ACCOUNT("TEXT")=$$LJ^XLFSTR($G(LOGDT),35,"  ")_$$LJ^XLFSTR($G(USR),29,"  ")_$$LJ^XLFSTR($G(ACTION),20,"  ")_$G(LOGDESC)
 .S @DATA@(+ACCOUNT,$P(@DOCS@("DILIST",INDEX,0),U))=ACCOUNT("TEXT")
 F ACCOUNT=1:-1:0  D  Q:$G(STOP)
 .Q:'$D(@DATA@(ACCOUNT))
 .I ACCOUNT=0 D
 ..I ($Y+CBUFFER+4)>IOSL!($Y=0) D  Q:$G(STOP)
 ...S STOP=$$HEADER^BEHOEP3(RPTNAME,.PGNUM,.COL,.COVERCOL)
 ..D DISUSERD
 ..W $$CJ^XLFSTR($$REPEAT^XLFSTR("-",34),$S(+$G(IOM)>0:IOM,1:80)," "),!
 .S NAME="" F  S NAME=$O(@DATA@(ACCOUNT,NAME)) Q:NAME=""!($G(STOP))  D
 ..I ($Y+CBUFFER)>IOSL!($Y=0) D  Q:$G(STOP)
 ...S STOP=$$HEADER^BEHOEP3(RPTNAME,.PGNUM,.COL,.COVERCOL)
 ..;W $$LJ^XLFSTR(NAME,37," ")_@DATA@(ACCOUNT,NAME),!
 ..W @DATA@(ACCOUNT,NAME),!
 ..S OUTPUT=1
 I '$G(STOP) D
 .I '$G(OUTPUT) D  Q:$G(STOP)
 ..S STOP=$$HEADER^BEHOEP3(RPTNAME,.PGNUM,.COL,.COVERCOL)
 ..Q:STOP
 ..D NODTRNGE
 .I ($Y+2)>IOSL S STOP=$$HEADER^BEHOEP3(RPTNAME,.PGNUM,.COL,.COVERCOL)
 .Q:$G(STOP)
 .D RPTEND
 K @DOCS,@DATA
 S:$D(ZTQUEUED) ZTREQ="@"
 Q
 ;
PPI ;EP - EPCS Provider Profile Integrity Report; 10/17/17 Build
 ;REP IS HANDLED BY REPORTS^ORDEA01
 N DISINC,PROVARRY,SAVE
 W !!,"This report loops through users with EPCS PROFILE HASH; field",!
 W "in the NEW PERSON FILE (#200). Report will display Mismatch Profile first.",!
 S DISINC=$$DISPRMPT^BEHOEP3()
 Q:$G(DISINC)="^"
 D PROVNAME^BEHOEP3(.PROVARRY)
 I $O(PROVARRY(0))'>0,$G(PROVARRY)="^" Q
 W:$O(PROVARRY(0))'>0 "ALL"
 Q:DISINC=U
 S SAVE=("DISINC")=""
 D DEVICE^ORUTL("PPIQ^BEHOEP4","PROVIDER PROFILE INTEGRITY REPORT","Q",.SAVE)
 Q
 ;
PPIQ ;EP - TASKMAN ENTRY POINT
 ;CBUFFER IS HANDLED BY DEVICE^ORUTL OR TASKMAN
 N DOCS,DATA,SCR,ERROR,INDEX,PGNUM,COL,STOP,ACCOUNT,OUTPUT,PISTATUS,PROVIEN,TMP,MISMATCH,NAME,RPTNAME,COVERCOL,R
 ;RETRIEVE ALL USERS WITH A EPCS PROFILE HASH in FILE #200
 S DOCS=$NA(^TMP($J,"EPCSPPI")),DATA=$NA(^TMP($J,"EPCSPPIDATA")),RPTNAME="PROVIDER PROFILE INTEGRITY REPORT"
 K @DOCS,@DATA
 S I=$$SENSTIV1^BEHOEP3(.COL)
 S I=I+1,COL(I)="NAME                               DEA#       HASH STATUS    ACCOUNT STATUS"
 S I=$$SENSTIV2^BEHOEP3(.COVERCOL)
 S I=I+1,COVERCOL(I)="NAME                               DEA#       HASH STATUS    ACCOUNT STATUS"
 S SCR="I 1"
 S SCR=SCR_" & (($P($G("_"^"_"(""IHSEPCS1"")),""^"",1))'="""""_")"
 S INDEX=$O(PROVARRY(0))
 I +INDEX>0 S TMP=" & ("
 I +INDEX>0 F  D  Q:(+INDEX'>0)
 .S TMP=$G(TMP)_"(($P($G("_"^"_"(0)),""^"",1))="_""""_$G(PROVARRY(INDEX))_""""_")"
 .I $O(PROVARRY(INDEX))>0 S TMP=$G(TMP)_" ! "
 .S INDEX=$O(PROVARRY(INDEX))
 S:$G(TMP)'="" TMP=$G(TMP)_")",SCR=SCR_$G(TMP)
 D LIST^DIC(200,,"@;.01;53.2","PQ",,,,,SCR,,DOCS,"ERROR")
 I $D(ERROR) D  Q
 .D FMERROR^ORUTL(.ERROR)
 .S:$D(ZTQUEUED) ZTREQ="@"
 .K @DOCS
 S INDEX=0 F  S INDEX=$O(@DOCS@("DILIST",INDEX)) Q:+$G(INDEX)=0  D
 .S PROVIEN=$P(@DOCS@("DILIST",INDEX,0),U),NAME=$P(@DOCS@("DILIST",INDEX,0),U,2)
 .N ACCOUNT S ACCOUNT=$$ACTIVE^XUSER($G(PROVIEN)),DEA=$P(@DOCS@("DILIST",INDEX,0),U,3)
 .D VRFYPHSH^BEHOEP3(.R,$G(PROVIEN))
 .I $G(R)=1 S PISTATUS="MATCH",MISMATCH=0
 .E  S PISTATUS="MISMATCH",MISMATCH=1 ;Display Mismatch First
 .I 'DISINC,(+ACCOUNT<1),($P(ACCOUNT,U,2)'="") Q
 .S ACCOUNT("TEXT")=$S($P(ACCOUNT,U,2)'="":$P(ACCOUNT,U,2),ACCOUNT=0:"CANNOT SIGN ON",1:"UNKNOWN")
 .;INCLUDE USERS WHO CANNOT SIGN-ON IN ACTIVE LISTING
 .I ACCOUNT=0 S ACCOUNT=1
 .S @DATA@(+ACCOUNT,MISMATCH,NAME)=$$LJ^XLFSTR($G(DEA),11,"  ")_$$LJ^XLFSTR($G(PISTATUS),15,"  ")_ACCOUNT("TEXT")
 F ACCOUNT=1:-1:0  D  Q:$G(STOP)
 .Q:'$D(@DATA@(ACCOUNT))
 .F MISMATCH=1:-1:0  D  Q:$G(STOP)
 ..Q:'$D(@DATA@(ACCOUNT,MISMATCH))
 ..I ACCOUNT=0 D
 ...I ($Y+CBUFFER+4)>IOSL!($Y=0) D  Q:$G(STOP)
 ....S STOP=$$HEADER^BEHOEP3(RPTNAME,.PGNUM,.COL,.COVERCOL)
 ...D DISUSERD
 ...W $$CJ^XLFSTR($$REPEAT^XLFSTR("-",34),$S(+$G(IOM)>0:IOM,1:80)," "),!
 ..S NAME="" F  S NAME=$O(@DATA@(ACCOUNT,MISMATCH,NAME)) Q:NAME=""!($G(STOP))  D
 ...I ($Y+CBUFFER)>IOSL!($Y=0) D  Q:$G(STOP)
 ....S STOP=$$HEADER^BEHOEP3(RPTNAME,.PGNUM,.COL,.COVERCOL)
 ...W $$LJ^XLFSTR(NAME,35," ")_@DATA@(ACCOUNT,MISMATCH,NAME),!
 ...S OUTPUT=1
 I '$G(STOP) D
 .I '$G(OUTPUT) D  Q:$G(STOP)
 ..S STOP=$$HEADER^BEHOEP3(RPTNAME,.PGNUM,.COL,.COVERCOL)
 ..Q:STOP
 ..D NODATA
 .I ($Y+2)>IOSL S STOP=$$HEADER^BEHOEP3(RPTNAME,.PGNUM,.COL,.COVERCOL)
 .Q:$G(STOP)
 .D RPTEND
 K @DOCS,@DATA
 S:$D(ZTQUEUED) ZTREQ="@"
 Q
 ;
IEC ;EP - IR EPCS Integrity Check Report
 ;REP IS HANDLED BY REPORTS^ORDEA01
 N DISINC,PROVARRY,SAVE
 W !!,"This report loops through users with EPCS PROFILE HASH; field",!
 W "in the NEW PERSON FILE (#200). And will display MISMATCH profiles only!",!
 ;S DISINC=$$DISPRMPT^BEHOEP3()
 S DISINC=1
 Q:DISINC=U
 S SAVE=("DISINC")=""
 D DEVICE^ORUTL("IECQ^BEHOEP4","IR EPCS INTEGRITY CHECK","Q",.SAVE)
 Q
 ;
IECQ ;EP - TASKMAN ENTRY POINT
 ;CBUFFER IS HANDLED BY DEVICE^ORUTL OR TASKMAN
 N DOCS,DATA,SCR,ERROR,INDEX,PGNUM,COL,STOP,ACCOUNT,OUTPUT,PISTATUS,PROVIEN,TMP,MISMATCH,NAME,RPTNAME,DEA
 N COVERCOL,I
 ;RETRIEVE ALL USERS WITH A EPCS PROFILE HASH in FILE #200
 S DOCS=$NA(^TMP($J,"EPCSPPI")),DATA=$NA(^TMP($J,"EPCSPPIDATA")),RPTNAME="IR EPCS INTEGRITY CHECK",I=0
 K @DOCS,@DATA
 W "",!
 S DISINC=1
 S I=$$SENSTIV2^BEHOEP3(.COVERCOL)
 S I=I+1,COVERCOL(I)="NAME                               DEA#       HASH STATUS    ACCOUNT STATUS"
 S I=I+1,COL(I)="                           **SENSITIVE INFORMATION**                       "
 S I=I+1,COL(I)="NAME                               DEA#       HASH STATUS    ACCOUNT STATUS"
 S SCR="I 1"
 S SCR=SCR_" & (($P($G("_"^"_"(""IHSEPCS1"")),""^"",1))'="""""_")"
 D LIST^DIC(200,,"@;.01;53.2","PQ",,,,,SCR,,DOCS,"ERROR")
 I $D(ERROR) D  Q
 .D FMERROR^ORUTL(.ERROR)
 .S:$D(ZTQUEUED) ZTREQ="@"
 .K @DOCS
 S INDEX=0 F  S INDEX=$O(@DOCS@("DILIST",INDEX)) Q:+$G(INDEX)=0  D
 .S PROVIEN=$P(@DOCS@("DILIST",INDEX,0),U),NAME=$P(@DOCS@("DILIST",INDEX,0),U,2),MISMATCH=0
 .N ACCOUNT S ACCOUNT=$$ACTIVE^XUSER($G(PROVIEN)),DEA=$P(@DOCS@("DILIST",INDEX,0),U,3)
 .D VRFYPHSH^BEHOEP3(.R,$G(PROVIEN))
 .I '$G(R) S PISTATUS="MISMATCH",MISMATCH=1 ;Display Mismatch First
 .;Mismatch only
 .I 'DISINC,(+ACCOUNT<1),($P(ACCOUNT,U,2)'=""),'MISMATCH Q
 .S ACCOUNT("TEXT")=$S($P(ACCOUNT,U,2)'="":$P(ACCOUNT,U,2),ACCOUNT=0:"CANNOT SIGN ON",1:"UNKNOWN")
 .;INCLUDE USERS WHO CANNOT SIGN-ON IN ACTIVE LISTING
 .I ACCOUNT=0 S ACCOUNT=1
 .S:$G(MISMATCH)=1 @DATA@(+ACCOUNT,MISMATCH,NAME)=$$LJ^XLFSTR($G(DEA),11,"  ")_$$LJ^XLFSTR($G(PISTATUS),15,"  ")_ACCOUNT("TEXT")
 S STOP=$$HEADER^BEHOEP3(RPTNAME,.PGNUM,.COL,.COVERCOL)
 F ACCOUNT=1:-1:0  D  Q:$G(STOP)
 .Q:'$D(@DATA@(ACCOUNT))
 .F MISMATCH=1:-1:0  D  Q:$G(STOP)
 ..Q:'$D(@DATA@(ACCOUNT,MISMATCH))
 ..I ACCOUNT=0 D
 ...I ($Y+$G(CBUFFER)+4)>IOSL!($Y=0) D  Q:$G(STOP)
 ....S STOP=$$HEADER^BEHOEP3(RPTNAME,.PGNUM,.COL,.COVERCOL)
 ...D DISUSERD
 ...W $$CJ^XLFSTR($$REPEAT^XLFSTR("-",34),$S(+$G(IOM)>0:IOM,1:80)," "),!
 ..S NAME="" F  S NAME=$O(@DATA@(ACCOUNT,MISMATCH,NAME)) Q:NAME=""!($G(STOP))  D
 ...I ($Y+$G(CBUFFER))>IOSL!($Y=0) D  Q:$G(STOP)
 ....S STOP=$$HEADER^BEHOEP3(RPTNAME,.PGNUM,.COL,.COVERCOL)
 ...W $$LJ^XLFSTR(NAME,35," ")_@DATA@(ACCOUNT,MISMATCH,NAME),!
 ...S OUTPUT=1
 I '$G(STOP) D
 .I '$G(OUTPUT) D  Q:$G(STOP)
 ..S STOP=$$HEADER^BEHOEP3(RPTNAME,.PGNUM,.COL,.COVERCOL)
 ..Q:STOP
 ..D NODATA
 .I ($Y+2)>IOSL S STOP=$$HEADER^BEHOEP3(RPTNAME,.PGNUM,.COL,.COVERCOL)
 .Q:$G(STOP)
 .D RPTEND
 K @DOCS,@DATA
 S:$D(ZTQUEUED) ZTREQ="@"
 Q
 ;
RPTEND ;EP - Common for All BEH EPCS Reports
 W !,$$CJ^XLFSTR("[END OF REPORT]",$S(+$G(IOM)>0:(IOM-1),1:79)," ")
 Q
 ;
NODATA ;EP - Common for All BEH EPCS Reports
 W !,$$CJ^XLFSTR("NO DATA FOUND...",$S(+$G(IOM)>0:(IOM-1),1:79)," "),!
 Q
 ;
NODTRNGE ;EP - Common for All BEH EPCS Reports
 W !,$$CJ^XLFSTR("**No Data Found for Requested Date Range**",$S(+$G(IOM)>0:(IOM-1),1:79)," "),!
 Q
 ;
DISUSERD ;EP - Common for All BEH EPCS Reports
 W !,$$CJ^XLFSTR("*** DISUSERED/TERMINATED USERS ***",$S(+$G(IOM)>0:(IOM-1),1:79)," "),!
 Q
 ;
