BEHOGMY2 ;IHS/MSC/MGH-TMP FOR SUMMING UP PATIENT I/O ;01-Sep-2023 16:46;PLS
 ;;1.1;BEH COMPONENTS;**077001**;Mar 20, 2007;Build 3
SUM ;
 N BEHDATE,BEHTYPE,BEHIEN,BEHDATA,BEHXDTE,BTIME,BTYPE,MATCH,MCNT,BNAME
 N BEHOUTA,BTIME2,STRING,STRING2,BEHAMT,BEHNAME,BEHNUM,BLANK,DAY,OUTDATE,OUTTIME
 N STOTI,STOTIV,STOTO,XTRA,AMT,LEN,DATA
 S BEHDATE=0 F  S BEHDATE=$O(^TMP("BEHOG",$J,BEHDATE)) Q:'BEHDATE  D
 .S BEHXDTE=9999999-BEHDATE
 .S BEHTYPE="" F  S BEHTYPE=$O(^TMP("BEHOG",$J,BEHDATE,BEHTYPE)) Q:BEHTYPE=""  D
 ..S BEHIEN="" F  S BEHIEN=$O(^TMP("BEHOG",$J,BEHDATE,BEHTYPE,BEHIEN)) Q:'BEHIEN  D
 ...S BEHDATA=$G(^TMP("BEHOG",$J,BEHDATE,BEHTYPE,BEHIEN))
 ...S BEHAMT=$P(BEHDATA,U)
 ...S BEHNAME=$P(BEHDATA,U,2)
 ...S BEHNUM=$S(BEHTYPE="IV":1,BEHTYPE="I":2,BEHTYPE="O":3,1:2)
 ...S BEHOUTA(+$E(BEHXDTE,1,12),BEHNUM,BEHNAME)=$G(BEHOUTA(+$E(BEHXDTE,1,12),BEHNUM,BEHNAME))+BEHAMT
 ;Output data for one date/time
 K DTOTI
 S OUTDATE="",BLANK="     "
 S STOTI=0,STOTO=0,STOTIV=0
 S BTIME="" F  S BTIME=$O(BEHOUTA(BTIME)) Q:BTIME=""  D
 .S BTIME2=$$ENTRY^CIAUDT(BTIME,2)
 .I $P(BTIME2," ")'=OUTDATE W:OUTDATE !! S OUTDATE=$P(BTIME2," ") W OUTDATE
 .S STRING=""
 .S BTYPE="" F  S BTYPE=$O(BEHOUTA(BTIME,BTYPE)) Q:BTYPE=""  D
 ..S BNAME="" F  S BNAME=$O(BEHOUTA(BTIME,BTYPE,BNAME)) Q:BNAME=""  D
 ...S MATCH="" F  S MATCH=$O(BEHARR(BTYPE,MATCH)) Q:'+MATCH  I $G(BEHARR(BTYPE,MATCH))=$P(BNAME,";") D  Q
 ....S DATA=$G(BEHOUTA(BTIME,BTYPE,BNAME))
 ....S $P(STRING,U,MATCH)=$P(STRING,U,MATCH)+DATA
 ....S $P(DTOTI(OUTDATE),U,BTYPE)=$P($G(DTOTI(OUTDATE)),U,BTYPE)+DATA
 ....S SUMVAR="STOT"_$S(BTYPE=1:"IV",BTYPE=2:"I",1:"O"),@SUMVAR=@SUMVAR+DATA
 .S STRING2=""
 .F MCNT=1:1:BEHCNT D
 ..S LEN=$L($P(STRING,U,MCNT))
 ..S AMT=$P(STRING,U,MCNT)
 ..S XTRA=$E(BLANK,1,5-LEN)
 ..S STRING2=STRING2_AMT_XTRA_"|"
 .S OUTTIME=$P(BTIME2," ",2)
 .S:$L(OUTTIME)<5 OUTTIME=$S(OUTTIME:OUTTIME_":00",1:"00:00")
 .W !,$E(OUTTIME,1,5)_"  |"_STRING2
 W !!,"DAILY TOTALS"
 S DAY="" F  S DAY=$O(DTOTI(DAY)) Q:DAY=""  D
 .W !,DAY,?18,"Intake: "_$P(DTOTI(DAY),U,2)
 .W ?32,"IV Intake: "_$P(DTOTI(DAY),U,1)
 .W ?49,"Output: "_$P(DTOTI(DAY),U,3)
 .W ?65,"Fluid balance: "_($P(DTOTI(DAY),U,2)+$P(DTOTI(DAY),U,1)-$P(DTOTI(DAY),U,3))
 W !,"TOTAL SUMMARY"
 W !,"Intake: "_STOTI,?15,"IV Intake: "_STOTIV,?35,"Output: "_STOTO,?50,"Fluid Balance: "_(STOTI+STOTIV-STOTO)
 Q:'$D(^TMP("BEHOG",$J,"COMM"))
 W !!,"Itemized List including COMMENTS:",!,"Date/Time",?18,"Type",?24,"Amount",?31,"Comment",!
 N DTM,LP,TP,ITP S DTM="" F  S DTM=$O(^TMP("BEHOG",$J,"COMM",DTM)) Q:'DTM  D
 .S LP="" F  S LP=$O(^TMP("BEHOG",$J,"COMM",DTM,LP)) Q:LP=""  D
 ..S TP=$S(LP="I":"Intake",LP="O":"Output",1:LP)
 ..S ITP="" F  S ITP=$O(^TMP("BEHOG",$J,"COMM",DTM,LP,ITP)) Q:ITP=""  D
 ...N REC,AMT,COM,DTME S REC=^TMP("BEHOG",$J,"COMM",DTM,LP,ITP)
 ...S AMT=$P(REC,U),COM=$P(REC,U,2),DTME=$P(REC,U,3)
 ...W DTME,?18,TP,?25,AMT,?30,$P(ITP,";"),": ",COM,!
 Q
