BEHOEPIP ; MSC/IHS/PLS - Installation support;07-Nov-2018 14:39;PLS
 ;;1.1;BEH COMPONENTS;**070001**;Mar 20, 2007;Build 10
POST ;EP-
 D REGMENU^BEHUTIL("BEHO EPCS MAIN",,"EPCS","BEHOMENU")
 D RESCH^XUTMOPT("BEHO EPCS AUDIT SUMMARY REPORT","T+1@02:00","","24H","L")
 ; Link Mail Group to BEH EPCS AUDIT LOG MESSAGES
 D ALMLINK
 Q
 ;
ALMLINK ;EP-
 ;Link the BEHO EPCS INCIDENT RESPONSE Mail Group to the
 ;EPCS03 and EPCS04 IDs.
 N MGIEN,EVTID
 S MGIEN=$O(^XMB(3.8,"B","BEHO EPCS INCIDENT RESPONSE",0))
 Q:'MGIEN
 F EVTID="EPCS03","EPCS04" D
 .D LINKIT(MGIEN,EVTID)
 Q
 ;Make the link of Mail Group to Event ID
LINKIT(MAILGRP,EVENTID) ;EP-
 N EVTIEN,FDA
 S EVTIEN=$O(^BEHOEP(90460.14,"B",EVENTID,0))
 Q:'EVTIEN
 S FDA(90460.14,EVTIEN_",",6)=MAILGRP
 D FILE^DIE(,"FDA")
 Q
