BEHOGMY ;MSC/IND/PLS - Patient Input/Output Support ;06-Sep-2023 15:59;PLS
 ;;1.1;BEH COMPONENTS;**077001**;Mar 20, 2007;Build 3
 ;=================================================================
 ; Return information from GMRY PATIENT I/O FILE
 ; Input: DFN - IEN to File 2
 ;        Start Date
 ;        End Date
GETPTIO(DATA,DFN,SDT,EDT) ;
 S DATA=$$TMPGBL^CIAVMRPC("_BEHOGMY")
 K @DATA
 N LP,LP1,IENS,IVIEN,GIEN,ITYPE,OTYPE,SDATE,EDATE,CNT
 S CNT=0
 S EDT=$G(EDT,$$NOW^XLFDT())
 S SDATE=9999999-SDT,EDATE=9999999-(EDT_".24")
 Q:'$D(^GMR(126,DFN,0))
 S LP=EDATE F  S LP=$O(^GMR(126,DFN,"IO",LP)) Q:LP>SDATE!'LP  D
 .S LP1="" F  S LP1=$O(^GMR(126,DFN,"IO",LP,LP1)) Q:LP1=""  D
 ..S GIEN="" F  S GIEN=$O(^GMR(126,DFN,"IO",LP,LP1,GIEN)) Q:'GIEN  D
 ...I LP1="IN"!(LP1="OUT") D GETFLDS(DFN,LP1,GIEN)
 ...I LP1="IV" D
 ....S IVIEN=""
 ....F  S IVIEN=$O(^GMR(126,DFN,"IO",LP,LP1,GIEN,IVIEN)) Q:'IVIEN  D
 .....D GETIV(DFN,LP1,GIEN,IVIEN)
 Q
GETFLDS(DFN,LP1,GIEN) ;Get the fields for an entry
 N IENS,ITYPE,LOC,WHO,TYP,INDTE,FLD,IOFILE,COM,OIEN,SUBTYPE
 I LP1="IN" S IOFILE=126.01,TYP="I",FLD=4,COM=5
 I LP1="OUT" S IOFILE=126.02,TYP="O",FLD=3,COM=4
 S IENS=GIEN_","_DFN_","
 S INDTE=9999999-LP
 ;Quit if the item is EIE
 Q:+$$GET1^DIQ(IOFILE,IENS,9999999.01,"I")
 S ITYPE=$$GET1^DIQ(IOFILE,IENS,1,"I")_";"_$$GET1^DIQ(IOFILE,IENS,1)
 S LOC=$$GET1^DIQ(IOFILE,IENS,$S(LP1="OUT":6,1:7),"I")_";"_$$GET1^DIQ(IOFILE,IENS,$S(LP1="OUT":6,1:7))
 S WHO=$$GET1^DIQ(IOFILE,IENS,$S(LP1="OUT":5,1:6),"I")_";"_$$GET1^DIQ(IOFILE,IENS,$S(LP1="OUT":5,1:6))
 S OIEN=$$GET1^DIQ(IOFILE,IENS,9999999.04)
 D ADD(GIEN_U_TYP_":"_ITYPE_U_INDTE_U_$$GET1^DIQ(IOFILE,IENS,FLD)_U_WHO_U_$$GET1^DIQ(IOFILE,IENS,COM)_U_LOC_U_$G(SUBTYPE)_U_OIEN)
 Q
GETIV(DFN,LP1,GIEN,IVIEN) ;Get the fields for an IV entry
 N IENS,IENS2,ITYPE,LOC,WHO,INDTE,SUBTYPE,OIEN
 S IENS2=IVIEN_","_GIEN_","_DFN_","
 S IENS=GIEN_","_DFN_","
 S INDTE=9999999-LP
 Q:+$$GET1^DIQ(126.313,IENS2,9999999.11,"I")
 S ITYPE=$$GET1^DIQ(126.03,IENS,3,"I")_";"_$$GET1^DIQ(126.03,IENS,3)
 S LOC=$$GET1^DIQ(126.313,IENS2,4,"I")_";"_$$GET1^DIQ(126.313,IENS2,4)
 S WHO=$$GET1^DIQ(126.313,IENS2,3,"I")_";"_$$GET1^DIQ(126.313,IENS2,3)
 S OIEN=$$GET1^DIQ(126.313,IENS2,9999999.14)
 D ADD(GIEN_":"_IVIEN_U_"IV:"_ITYPE_U_INDTE_U_$$GET1^DIQ(126.313,IENS2,2)_U_WHO_U_$$GET1^DIQ(126.313,IENS2,9999999.01)_U_LOC_U_$G(SUBTYPE)_U_OIEN)
 Q
ADD(STR) S CNT=$G(CNT)+1
 S @DATA@(CNT)=STR
 Q
SAVEIO(DATA,INP) ;Save the intake and output
 N DFN,DFN2,LOC,TYP,LEN,FILE,STR,SIEN,IVTYPE,TIME,I,ENCTIME,PIECE,SUB,NIEN,COM
 N OIEN
 S DATA=1
 S DFN=$P(INP,U,1)
 I $D(^GMR(126,DFN))=0 D  I '+DFN2 S DATA="-1^Unable to store patient in file 126" Q
 .S DFN2=$$NEWPT(DFN)
 S LOC=$P($P(INP,U,2),":",2)
 S ENCTIME=$P($P(INP,U,2),":",1)
 S TIME=$$ADJTIME(DFN,$P(INP,U,3))
 S TYP=$P(INP,U,4)
 S STR=$P(INP,U,5)
 S OIEN=$P(INP,U,6)  ; Hold IEN of edited entry now EIE
 S FILE=$S(TYP="I":126.01,TYP="O":126.02,TYP="IV":126.03,1:"")
 S LEN=$L(STR,";")
 F I=1:1:LEN D  Q:+DATA<0
 .S PIECE=$P(STR,";",I)
 .Q:PIECE=""
 .S SUB=$P(PIECE,":",1)
 .S AMT=$P(PIECE,":",2)
 .S COM=$P(PIECE,":",3)
 .I TYP="I" S SIEN=SUB
 .I TYP="O" S SIEN=SUB
 .I TYP="IV" S IVTYP=SUB
 .I TYP="I"!(TYP="O") D
 ..N FDA,NIEN,BEHERR
 ..S FDA=$NA(FDA(FILE,"+1,"_DFN_","))
 ..S @FDA@(.01)=TIME
 ..S @FDA@(1)=SIEN
 ..I TYP="I" D
 ...S @FDA@(4)=AMT
 ...S @FDA@(5)=COM
 ...S @FDA@(6)=DUZ
 ...S @FDA@(7)=LOC
 ...S @FDA@(9999999.04)=$G(OIEN)
 ..I TYP="O" D
 ...S @FDA@(3)=AMT
 ...S @FDA@(4)=COM
 ...S @FDA@(5)=DUZ
 ...S @FDA@(6)=LOC
 ...S @FDA@(9999999.04)=$G(OIEN)
 ..D UPDATE^DIE("","FDA","NIEN","BEHERR")
 ..I $G(BEHERR) S DATA="-1^Unable to store entry"
 ..E  D
 ...S DATA=NIEN(1)
 ...D:DFN BRDCAST^CIANBEVT("BEHOIO."_DFN)
 .I TYP="IV" D IVSTORE(DFN,LOC,TIME,AMT,FILE,ENCTIME,COM,OIEN)
 Q
IVSTORE(DFN,LOC,TIME,AMT,FILE,ENCTIME,COM,OIEN) ;Store the IV information
 ;First see if the patient has an IV of this type
 N IVIEN,TYPE,FOUND
 S FOUND=0
 S IVIEN="" F  S IVIEN=$O(^GMR(126,DFN,"IV","B",ENCTIME,IVIEN)) Q:'IVIEN!(+FOUND)  D
 .S TYPE=$P($G(^GMR(126,DFN,"IV",IVIEN,0)),U,4)
 .I IVTYP=TYPE S FOUND=IVIEN
 ;Did not find an exising IV for this date so make one
 I FOUND=0 S FOUND=$$MAKENEW(DFN,IVTYP,ENCTIME)
 D STORIV(DFN,LOC,TIME,AMT,FOUND,COM,OIEN)
 Q
MAKENEW(DFN,IVTYP,ENCTIME) ;Store the IV
 N IEN,SOL
 K NIEN,FDA,BEHERR
 S FDA=$NA(FDA(FILE,"+1,"_DFN_","))
 S @FDA@(.01)=ENCTIME
 S @FDA@(1)="OTHER"
 S @FDA@(3)=IVTYP
 ;I IVTYP="A" D
 ;.S SOL="OTHER"
 ;I IVTYP="P" D
 ;.S SOL="GENERIC PIGGYBACK"
 ;I IVTYP="B" D
 ;.S SOL="BLOOD PRODUCT"
 S SOL=$$GETSOL(IVTYP)
 S @FDA@(2)=SOL
 S @FDA@(4)=0
 S @FDA@(6)=DUZ
 S @FDA@(7)=LOC
 D UPDATE^DIE("","FDA","NIEN","BEHERR")
 I $G(BEHERR) S DATA="-1^Unable to store entry"
 Q NIEN(1)
 ;
GETSOL(IVTYP) ;Return external form of Set of Codes value
 N RES
 D CHK^DIE(126.03,3,"E",IVTYP,.RES)
 Q $S($L($G(RES(0))):RES(0),1:"UNKNOWN")
STORIV(DFN,LOC,TIME,AMT,IVIEN,COM,OIEN) ;Store the IV intake
 N SFILE,FDA,BEHERR,NSIEN
 S SFILE=126.313
 S FDA=$NA(FDA(SFILE,"+1,"_IVIEN_","_DFN_","))
 S @FDA@(.01)=TIME
 S @FDA@(2)=AMT
 S @FDA@(3)=DUZ
 S @FDA@(4)=LOC
 S @FDA@(9999999.01)=COM
 S @FDA@(9999999.14)=$G(OIEN)
 D UPDATE^DIE("","FDA","NSIEN","BEHERR")
 I $G(BEHERR) S DATA="-1^Unable to store entry"
 E  D
 .S DATA=NSIEN(1)
 .D:DFN BRDCAST^CIANBEVT("BEHOIO."_DFN)
 Q
NEWPT(DFN) ;EP Store a new patient in the 126 file
 N FDA,IEN,ERR,RETURN
 S FDA(126,"+1,",.01)=DFN
 S IEN(1)=DFN
 D UPDATE^DIE("","FDA","IEN","ERR")
 I $D(IEN(1)) S RETURN=IEN(1)
 I $D(ERR) S RETURN="Unable to store patient"
 Q RETURN
DETAIL(DATA,DFN,START,END,STYPE) ;Return the detail report
 N ITIME,TYPE,NTIME,CNT,OLDTYP,ITIME,TYP,IEN,NODE,WHO,WHERE,WHAT,WHEN,AMT,COM,UNDERLN
 S STYPE=$G(STYPE),END=$G(END)
 S DATA=$$TMPGBL^CIAVMRPC("_BEHOGMY")
 S NTIME="",OLDTYP="",CNT=0
 S UNDERLN=$$REPEAT^XLFSTR("-",80)
 I END="" S END=$P(START,".")_".2400"
 K ^TMP("BEHOG",$J)
 I STYPE'="" D START^BEHOGMY1(DFN,START,END)
 I STYPE="" D SAVE(DFN,START,END,STYPE)
 N BEHDATE,BEHXDTE,BEHTYPE,BEHIEN,BEHDATA,BEHAMT,BEHNAME,BEHNUM,BEHOUTA,BEHDTI
 S BEHDATE=0 F  S BEHDATE=$O(^TMP("BEHOG",$J,BEHDATE)) Q:'BEHDATE  D
 .S BEHDTI=$E(9999999-BEHDATE,1,12)
 .S BEHTYPE="" F  S BEHTYPE=$O(^TMP("BEHOG",$J,BEHDATE,BEHTYPE)) Q:BEHTYPE=""  D
 ..S BEHIEN="" F  S BEHIEN=$O(^TMP("BEHOG",$J,BEHDATE,BEHTYPE,BEHIEN)) Q:'BEHIEN  D
 ...S BEHDATA=$G(^TMP("BEHOG",$J,BEHDATE,BEHTYPE,BEHIEN))
 ...S BEHAMT=$P(BEHDATA,U)
 ...S BEHNAME=$P(BEHDATA,U,2)
 ...S BEHNUM=$S(BEHTYPE="IV":1,BEHTYPE="I":2,BEHTYPE="O":3,1:2)
 ...S BEHOUTA(-BEHDTI,BEHNUM,BEHNAME)=$G(BEHOUTA(-BEHDTI,BEHNUM,BEHNAME))+BEHAMT
 ...S BEHOUTA(-BEHDTI)=$P(BEHDATA,U,3,4)
 S ITIME="" F  S ITIME=$O(BEHOUTA(ITIME)) Q:'ITIME  D
 .S WHEN=-ITIME,WHENEXT=$$ENTRY^CIAUDT(WHEN,2)
 .S:$L($P(WHENEXT," ",2))<5 $P(WHENEXT," ",2)="00:00"
 .S WHO=$P($P(BEHOUTA(ITIME),U),";",2)
 .S WHERE=$P($P(BEHOUTA(ITIME),U,2),";",2)
 .S:CNT CNT=CNT+1,@DATA@(CNT)=""
 .S CNT=CNT+1 S @DATA@(CNT)=WHENEXT_"      Location: "_WHERE_" Entered by: "_WHO
 .S CNT=CNT+1 S @DATA@(CNT)=UNDERLN
 .S TYP="" F  S TYP=$O(BEHOUTA(ITIME,TYP)) Q:TYP=""  D
 ..S TYPNM=$S(TYP=1:"IV Intake",TYP=2:"Intake",TYP=3:"Output",1:"")
 ..S CNT=CNT+1 S @DATA@(CNT)=TYPNM
 ..S BEHNAME="" F  S BEHNAME=$O(BEHOUTA(ITIME,TYP,BEHNAME)) Q:BEHNAME=""  D
 ...S AMT=$G(BEHOUTA(ITIME,TYP,BEHNAME))
 ...S WHAT=$E($P(BEHNAME,";",2),1,14)
 ...S CNT=CNT+1 S @DATA@(CNT)="     "_WHAT_$J(AMT,20-$L(WHAT))_"ml"
 Q:'$D(^TMP("BEHOG",$J,"COMM"))
 S CNT=CNT+1,@DATA@(CNT)=""
 S CNT=CNT+1,@DATA@(CNT)="Itemized List including COMMENTS:"
 S CNT=CNT+1,@DATA@(CNT)="Date/Time         Type    Amount  Comment"
 N DTM,LP,ITP S DTM="" F  S DTM=$O(^TMP("BEHOG",$J,"COMM",DTM),-1) Q:'DTM  D
 .S LP="" F  S LP=$O(^TMP("BEHOG",$J,"COMM",DTM,LP)) Q:LP=""  D
 ..N TP S TP=$S(LP="I":"Intake",LP="O":"Output",1:LP)
 ..S ITP="" F  S ITP=$O(^TMP("BEHOG",$J,"COMM",DTM,LP,ITP)) Q:ITP=""  D
 ...N REC,AMT,COM,DTME S REC=^TMP("BEHOG",$J,"COMM",DTM,LP,ITP)
 ...S AMT=$P(REC,U),COM=$P(REC,U,2),DTME=$P(REC,U,3)
 ...S CNT=CNT+1,@DATA@(CNT)=DTME_"  "_TP_$J("",8-$L(TP))_AMT_$J("",8-$L(AMT))_$P(ITP,";")_": "_COM
 Q
SAVE(DFN,BEHSTRT,BEHFIN,STYPE) ;Put type of IO into tmp global
 N LP,LP1,GIEN,IVIEN,SDATE,EDATE,BEHDT,BEHDAY,BEHLN
 S SDATE=9999999-BEHSTRT,EDATE=9999999-BEHFIN
 S BEHDT=0,BEHDAY=0 ;D NEXT
 S LP=EDATE
 F  S LP=$O(^GMR(126,DFN,"IO",LP)) Q:LP>SDATE!'LP  D
 .S LP1="" F  S LP1=$O(^GMR(126,DFN,"IO",LP,LP1)) Q:LP1=""  D
 ..S GIEN="" F  S GIEN=$O(^GMR(126,DFN,"IO",LP,LP1,GIEN)) Q:'GIEN  D
 ...I LP1="IN"!(LP1="OUT") D GETFLDS^BEHOGMY1(DFN,LP,LP1,GIEN)
 ...I LP1="IV" D
 ....S IVIEN="" F  S IVIEN=$O(^GMR(126,DFN,"IO",LP,LP1,GIEN,IVIEN)) Q:'IVIEN  D
 .....D GETIV^BEHOGMY1(DFN,LP,LP1,GIEN,IVIEN)
 Q
EDIT(DATA,IEN,INP) ;Allow user to delete or edit an entry
 N DFN,VALUE,TYPE,ENTER,ENC,SUBTYPE,SUB,STRING,LOC,LOCATE,AIEN,IVTIME,COM
 S DFN=$P(INP,U,1)
 S LOC=$P(INP,U,2)
 S TYPE=$P(INP,U,4)
 S VALUE=$P($P(INP,U,5),":",2)
 S COM=$P($P(INP,U,5),":",3)
 S SUB=$P($P(INP,U,5),":",1)
 I VALUE="@" D EIE(TYPE,IEN)
 I +VALUE D
 .I TYPE="I" D
 ..;S SUBTYPE=$$GET1^DIQ(126.56,SUB,.01)
 ..S SUBTYPE=SUB
 ..I '+LOC D
 ...S AIEN=IEN_","_DFN_","
 ...S LOC=$$GET1^DIQ(126.01,AIEN,7,"I")
 ..S LOCATE="0:"_LOC
 .I TYPE="O" D
 ..;S SUBTYPE=$$GET1^DIQ(126.58,SUB,.01)
 ..S SUBTYPE=SUB
 ..I '+LOC D
 ...S AIEN=IEN_","_DFN_","
 ...S LOC=$$GET1^DIQ(126.02,AIEN,7,"I")
 ..S LOCATE="0:"_LOC
 .I TYPE="IV" D
 ..S SUBTYPE=SUB
 ..S AIEN=$P(IEN,":",1)_","_DFN_","
 ..I '+LOC D
 ...S LOC=$$GET1^DIQ(126.03,AIEN,7,"I")
 ..S IVTIME=$$GET1^DIQ(126.03,AIEN,.01,"I")
 ..S LOCATE=IVTIME_":"_LOC
 .D EIE(TYPE,IEN)
 .S STRING=DFN_U_LOCATE_U_$P(INP,U,3)_U_TYPE_U_SUBTYPE_":"_VALUE_":"_COM_U_IEN
 .D SAVEIO(.DATA,STRING)
 Q
EIE(TYPE,IEN) ;Mark an entry as entered in error
 N FILE,FDA,NIEN,BEHERR
 Q:'+IEN
 S FILE=$S(TYPE="I":126.01,TYPE="O":126.02,TYPE="IV":126.313,1:"")
 I TYPE="I"!(TYPE="O") D
 .S FDA=$NA(FDA(FILE,IEN_","_DFN_","))
 .S @FDA@(9999999.01)=1
 .S @FDA@(9999999.02)=DUZ
 .S @FDA@(9999999.03)=4
 .D FILE^DIE("","FDA","BEHERR")
 I TYPE="IV" D
 .S FDA=$NA(FDA(FILE,$P(IEN,":",2)_","_$P(IEN,":",1)_","_DFN_","))
 .S @FDA@(9999999.11)=1
 .S @FDA@(9999999.12)=DUZ
 .S @FDA@(9999999.13)=4
 .D FILE^DIE("","FDA","BEHERR")
 Q
 ;
GETTYPES(DATA) ;Return list of data input types
 ;ID^TYPE^LABEL
 N LP,N0,NAME,TMP,SET,EXC
 D GETPARLI^CIAVMRPC(.EXC,"BEHOGMY EXCLUDE IV TYPES",,,DUZ)
 K DATA,CNT
 S CNT=0
 S LP=0 F  S LP=$O(^GMRD(126.56,LP)) Q:'LP  S N0=^(LP,0) D
 .S NAME=$P(N0,U)
 .S CNT=CNT+1,DATA(CNT)=LP_U_"I"_U_NAME_U_$S(NAME="PO":"ORAL",1:NAME)
 S LP=0 F  S LP=$O(^GMRD(126.58,LP)) Q:'LP  S N0=^(LP,0) D
 .S NAME=$P(N0,U)
 .S CNT=CNT+1,DATA(CNT)=LP_U_"O"_U_NAME_U_NAME
 ;IV set of codes
 D FIELD^DID(126.03,3,"","POINTER","TMP")
 S SET=$G(TMP("POINTER"))
 I $L(SET) D
 .S LP=1 F  S VAL=$P(SET,";",LP) Q:'$L(VAL)  D  S LP=LP+1
 ..Q:$$EXCLUDE($P(VAL,":"))  ;value in BEHOGMY EXCLUDE IV TYPES xpar
 ..S CNT=CNT+1,DATA(CNT)=$P(VAL,":")_U_"IV"_U_$P(VAL,":",2)_U_$S($P(VAL,":")="B":"BLOOD PRODUCTS",1:$P(VAL,":",2))
 Q
EXCLUDE(V) ;Check for exclusion
 N LP,ND,RES
 S RES=0
 S LP=0 F  S LP=$O(@EXC@(LP)) Q:'LP!RES  S ND=$G(@EXC@(LP)) D
 .S RES=$P(ND,U,2)=V
 Q RES
 ;
ADJTIME(DFN,TIME) ;Adjust seconds if inpatient and capture time is same as admission time sans seconds
 N VAIN,ADTM,PADTM,PTIME
 D INP^VADPT
 S ADTM=$P($G(VAIN(7)),U)
 Q:'ADTM TIME
 S PADTM=$E(ADTM,1,12)
 S PTIME=$E(TIME,1,12)
 I PADTM=PTIME,(TIME<ADTM) D
 .S TIME=PTIME_$S($L($E(ADTM,13,14)):$E(ADTM,13,14),1:"00")
 Q TIME
