BEHOGMY1 ;IHS/MSC/MGH - OE/RR REPORTS FOR I&O;07-Sep-2023 07:14;PLS
 ;;1.1;BEH COMPONENTS;**077001**;Mar 20, 2007
 ;; Entry point for OE/RR REPORT file
IANDO(ROOT,ORDFN,ID,ALPHA,OMEGA,ORDTRNG,REMOTE,ORMAX,ORFHIE) ; -- get Intake and output report
 ;D START^ORWRP(80,"IANDOSB^BEHOGMY1(.ROOT,.ORDFN,.ID,.ALPHA,.OMEGA,.ORDTRNG,.REMOTE,.ORMAX,.ORFHIE)")
 D IANDOP(.ROOT,ORDFN,ID,ALPHA,OMEGA,ORDTRNG,$G(REMOTE),ORMAX)
 Q
 ; RPC: Retrieve reports for date range
IANDOP(ROOT,ORDFN,ID,ALPHA,OMEGA,ORDTRNG,REMOTE,ORMAX) ;PEP - Retrieve report
 S ROOT=$$TMPGBL^CIAVMRPC
 D CAPTURE^CIAUHFS("D IANDOSB^BEHOGMY1(ORDFN,ALPHA,OMEGA)",ROOT,80)
 S:'$D(@ROOT) @ROOT@(1)="No Intake and output information"
 Q
IANDOSB(ORDFN,ALPHA,OMEGA) ; -- build I&O report
 N ORVP,XQORNOD,ORSSTRT,ORSSTOP
 Q:'$G(ORDFN)
 I $L(ORDTRNG),'$G(ALPHA) S ALPHA=$$FMADD^XLFDT(DT,-ORDTRNG),OMEGA=$$NOW^XLFDT
 Q:'$G(ALPHA)  Q:'$G(OMEGA)
 I '$P(OMEGA,".",2) S OMEGA=OMEGA_".2359"
 S ORVP=ORDFN_";DPT(",XQORNOD=1,ORSSTRT(XQORNOD)=ALPHA,ORSSTOP(XQORNOD)=OMEGA
 D IOCUM(ORDFN,.ORSSTRT,.ORSSTOP)
 Q
IOCUM(ORDFN,ORSSTRT,ORSSTOP) ; Print I&O Cumulative Report
 N VA,VADM,DFN,%,BEHEDB,BEHSTRT,BEHFIN,BEHCOL,BEHPT,BEHDT1,BEHDT2
 S DFN=+ORDFN,BEHSTRT=$G(ORSSTRT(+XQORNOD)),BEHFIN=$G(ORSSTOP(+XQORNOD))
 S BEHEDB="P",BEHPT=1
 D START(ORDFN,BEHSTRT,BEHFIN)
 D REPORT1(DFN)
 Q
START(DFN,BEHSTRT,BEHFIN) ;Start the cummulative report
 N Y,DA
 S Y=BEHSTRT D DD^%DT S BEHDT1=Y,Y=BEHFIN D DD^%DT S BEHDT2=Y
 S DA(1)=$O(^GMR(126,"B",DFN,0))
 K ^TMP("BEHOG",$J)
 I $D(^GMR(126,"B",DFN)) D SAVE(BEHSTRT,BEHFIN)
 Q
SAVE(BEHSTRT,BEHFIN) ;Put type of IO into tmp global
 N LP,LP1,GIEN,IVIEN,SDATE,EDATE,BEHDT,BEHDAY,BEHLN
 D TYPEABBR
 S SDATE=9999999-BEHSTRT,EDATE=9999999-(BEHFIN+.000001)
 S BEHDT=0,BEHDAY=0
 S LP=EDATE F  S LP=$O(^GMR(126,DFN,"IO",LP)) Q:'LP!(LP>SDATE)  D
 .S LP1="" F  S LP1=$O(^GMR(126,DFN,"IO",LP,LP1)) Q:LP1=""  D
 ..S GIEN="" F  S GIEN=$O(^GMR(126,DFN,"IO",LP,LP1,GIEN)) Q:'GIEN  D
 ...I LP1="IN"!(LP1="OUT") D GETFLDS(DFN,LP,LP1,GIEN)
 ...I LP1="IV" D
 ....S IVIEN="" F  S IVIEN=$O(^GMR(126,DFN,"IO",LP,LP1,GIEN,IVIEN)) Q:'IVIEN  D
 .....D GETIV(DFN,LP,LP1,GIEN,IVIEN)
 Q
GETFLDS(DFN,INDT,LP1,GIEN) ;Get the fields for an I or O type
 N IENS,ITYPE,LOC,WHO,TYP,INDTE,FLD,AMT,IOFILE,COM,OF,DTM
 I LP1="IN" S IOFILE=126.01,TYP="I"
 I LP1="OUT" S IOFILE=126.02,TYP="O"
 S IENS=GIEN_","_DFN_","
 S INDTE=9999999-INDT,OF=(LP1="OUT"),DTM=$$ENTRY^CIAUDT(INDTE,2)
 S:$L($P(DTM," ",2))<5 $P(DTM," ",2)=$S($P(DTM," ",2):$P(DTM," ",2)_":00",1:"00:00")
 ;Quit if EIE
 Q:+$$GET1^DIQ(IOFILE,IENS,9999999.01,"I")
 S ITYPE=$$GET1^DIQ(IOFILE,IENS,1,"I"),ITYPED=$$GET1^DIQ(IOFILE,IENS,1)
 S LOC=$$GET1^DIQ(IOFILE,IENS,7-OF,"I")_";"_$$GET1^DIQ(IOFILE,IENS,7-OF)
 S AMT=$$GET1^DIQ(IOFILE,IENS,4-OF,"I")
 S WHO=$$GET1^DIQ(IOFILE,IENS,6-OF,"I")_";"_$$GET1^DIQ(IOFILE,IENS,6-OF)
 S COM=$$GET1^DIQ(IOFILE,IENS,5-OF)
 S ^TMP("BEHOG",$J,INDT,TYP,GIEN)=AMT_U_ITYPE_";"_ITYPED_U_WHO_U_LOC
 S ^TMP("BEHOG",$J,"COMM",+$E(INDTE,1,12),TYP,ITYPED_";"_GIEN)=AMT_U_COM_U_DTM
 S IVINPUT(TYP,ITYPE)=ITYPED
 Q
GETIV(DFN,INDT,LP1,GIEN,IVIEN) ;Get the IV fields
 N IENS,IENS2,ITYPE,LOC,WHO,INDTE,COM,DTM
 S IENS2=IVIEN_","_GIEN_","_DFN_","
 S IENS=GIEN_","_DFN_","
 S INDTE=9999999-INDT,DTM=$$ENTRY^CIAUDT(INDTE,2)
 S:$L($P(DTM," ",2))<5 $P(DTM," ",2)=$S($P(DTM," ",2):$P(DTM," ",2)_":00",1:"00:00")
 ;Quit if EIE
 Q:+$$GET1^DIQ(126.313,IENS2,9999999.11,"I")
 S ITYPE=$$GET1^DIQ(126.03,IENS,3,"I"),ITYPED=$$GET1^DIQ(126.03,IENS,3)
 S LOC=$$GET1^DIQ(126.313,IENS2,4,"I")_";"_$$GET1^DIQ(126.313,IENS2,4)
 S WHO=$$GET1^DIQ(126.313,IENS2,3,"I")_";"_$$GET1^DIQ(126.313,IENS2,3)
 S COM=$$GET1^DIQ(126.313,IENS2,9999999.01),AMT=$$GET1^DIQ(126.313,IENS2,2)
 S ^TMP("BEHOG",$J,INDT,"IV",GIEN_";"_IVIEN)=AMT_U_ITYPE_";"_ITYPED_U_WHO_U_LOC
 S ^TMP("BEHOG",$J,"COMM",+$E(INDTE,1,12),LP1,ITYPED_";"_GIEN_";"_IVIEN)=AMT_U_COM_U_DTM
 Q:'$D(IVTPARR)
 S ORD=$O(IVTPARR(ITYPE,"")),ABBR=IVTPARR(ITYPE,ORD)
 S IVINPUT(ORD)=ABBR
 Q
REPORT1(DFN) ;Write out the report
 N BEHQT,BEHX,BEHPC,BEHARR,BEHCNT,BEHLN
 S BEHX="",$P(BEHX,"-",130)="" D TITLE
 S BEHPC=0
 D HEADER S BEHQT=1 D BODY,FOOTER
 D KVAR^VADPT K VA
 Q
TITLE ;CREATE HEADER FOR I/O SUMMARY REPORT,GTYPI(TYPE)=ORDER,GTYP(O)=ORDER
 N BEHBLNK,BEHN,BEHITYP,VAIN
 S BEHBLNK=$J("",80),BEHLN(3)=$E(BEHBLNK,1,7)_"|"
 S ORD="" F I=0:1 S ORD=$O(IVINPUT(ORD)) Q:'ORD  D
 .S BEHLN(3)=BEHLN(3)_$E(IVINPUT(ORD)_BEHBLNK,1,5)_"|",BEHARR(1,I+1)=IVTPARR1(ORD)
 S BEHCNT=I
 S BEHLN(1)="TIME"_$E(BEHBLNK,1,3)_"|INPUT"_$E(BEHBLNK,1,I-1*6)_"|"
 S ITYPE="" F  S ITYPE=$O(IVINPUT("I",ITYPE)) Q:ITYPE=""  D
 .S BEHLN(1)=BEHLN(1)_"      "
 .S BEHLN(3)=BEHLN(3)_$E(IVINPUT("I",ITYPE)_BEHBLNK,1,5)_"|"
 .S BEHCNT=BEHCNT+1,BEHARR(2,BEHCNT)=ITYPE
 S $E(BEHLN(1),$L(BEHLN(1)))="|OUTPUT"
 S ITYPE="" F  S ITYPE=$O(IVINPUT("O",ITYPE)) Q:ITYPE=""  D
 .S BEHLN(3)=BEHLN(3)_$E(IVINPUT("O",ITYPE)_BEHBLNK,1,5)_"|"
 .S BEHCNT=BEHCNT+1,BEHARR(3,BEHCNT)=ITYPE
 S BEHCOL=6*BEHCNT+8
 Q
HEADER ;write out header for report
 N BEHGG,BEHLOC,BEHFACI
 D FOOTER
 S BEHQT=1,BEHPC=BEHPC+1 S BEHGG=$S(BEHPT=1:23,1:20) W !,?BEHGG,"PATIENT INTAKE/OUTPUT SUMMARY" K BEHGG
 D INP^VADPT S BEHLOC=$P($G(^DIC(42,+$G(VAIN(4)),44)),"^")
 S BEHFACI=$S(BEHLOC>0:$$GET1^DIQ(4,+$$GET1^DIQ(44,+BEHLOC,3,"I"),.01,"I"),1:"")
 W !,BEHDT1_" - "_BEHDT2,! Q:'BEHCNT
 W BEHLN(1),!,BEHLN(3),!,$E(BEHX,1,BEHCOL),!
 Q
FOOTER ;  Write out footer for report
 N BEHWARD,BEHSEX,BEHRMBD,BEHNAM,BEHRM,BEHBED,BEHAGE,BEHAGE,BEHBTH,HRCN,BEHVHLOC
 D 1^VADPT S BEHWARD(1)=$P(VAIN(4),U,2),BEHWARD=$P(VAIN(4),U),BEHRMBD=$S(VAIN(5)'="":VAIN(5),1:""),BEHNAM=$S(VADM(1)'="":VADM(1),1:"BLANK"),BEHRM=$S($P(BEHRMBD,"-")'="":$P(BEHRMBD,"-"),1:"BLANK")
 S BEHBED=$S($P(BEHRMBD,"-",2)'="":$P(BEHRMBD,"-",2),1:"BLANK")
 S BEHSEX=$P(VADM(5),U,2),BEHAGE=VADM(4),BEHBTH=$P(VADM(3),U,2),HRCN=VA("PID")
 W !,$E(BEHX,1,BEHCOL),!
 W !,BEHNAM W:HRCN'="" ?17,HRCN W:BEHBTH'="" ?32,BEHBTH W:BEHAGE'="" ?42,"(",BEHAGE," YRS)" W:BEHSEX'="" ?53,BEHSEX
 W !,"UNIT: " W:BEHWARD(1)'="" ?7,BEHWARD(1) W ?33,"RM/BED: " W:BEHBED'="" ?41,BEHBED W !
 S BEHVHLOC=$P($G(^DIC(42,+$G(VAIN(4)),44)),"^")
 W "DIVISION: "_$S(BEHVHLOC>0:$$GET1^DIQ(4,+$$GET1^DIQ(44,+BEHVHLOC,3,"I"),.01,"I"),1:""),!
 Q
BODY ; Get the body of the report
 N BEHTOTIN,BEHTOOUT,BEHIN,BEHSIP,BEHSOP,BEHDIP,BEHDOP,BEHGRIP,BEHDROP
 I '$D(^TMP("BEHOG",$J)) W:BEHPT<5 !,"     NO DATA FOR THIS PERIOD",!! S BEHQT=1 Q
 D SUM^BEHOGMY2
 Q
TYPEABBR ; Create an array of IV Types
 K IVTPARR
 F I=1:1 S LN=$T(ABBR+I) Q:LN=""  D
 .S TP=$P(LN,";",2),ABBR=$P(LN,";",3)
 .S IVTPARR(TP,I)=ABBR,IVTPARR1(I)=TP
 Q
ABBR ;
 ;A;ADMIX
 ;P;IVPB
 ;H;HYPER
 ;B;BLOOD
 ;I;LIPID
 ;L;LOCK
