BEHOEPUT ; IHS/MSC/MGH - CONTROLLED SUBSTANCE UTILITIES ;08-Jun-2018 09:13;DU
 ;;1.1;BEH COMPONENTS;**070001**;Sep 23, 2004;Build 74
 ; Prompt for entry from file
 ; BEHFILE = File #
 ; BEHPMPT = Prompt
 ; BEHDFLD = Field whose value is to be used for default value
 ;          Set to -1 for no default value
 ; D - x-ref (C^D)
 ; BEHSCRN = DIC("S") SCREEN LOGIC
 ; BEHDFLT = Default value set in DIC("B") - not used if BEHDFLD is >0
GETIEN1(BEHFILE,BEHPMPT,BEHDFLD,D,BEHSCRN,BEHDFLT) ; EP
 N DIC,BEHD,Y,X
 S D=$G(D,"B")
 S:'$L(D) D="B"
 S BEHDFLD=$G(BEHDFLD,.01)
 S BEHD=""
 S DIC("S")=$G(BEHSCRN)
 S:BEHDFLD>0 BEHD=$$GET1^DIQ(BEHFILE,$$FIND1^DIC(BEHFILE,,," ",.D,DIC("S")),BEHDFLD)
 I BEHDFLD<0,$L($G(BEHDFLT)) S BEHD=BEHDFLT
 S DIC=BEHFILE,DIC(0)="AE",DIC("A")=$G(BEHPMPT),DIC("B")=BEHD
 I $L(D,U)>1,DIC(0)'["M" S DIC(0)=DIC(0)_"M"
 D MIX^DIC1
 S:Y'>0 BEHPOP=1,$P(BEHPOP,U,2)=X="@"
 Q +Y
ASKDATES(BEHB,BEHE,BEHPOP,BEHBDF,BEHEDF,BEHSAME,BEHTIME) ; EP
 N BEHOPT
 W !!,"   *** Date Range Selection ***"
 S BEHPOP=0,BEHOPT=$S($G(BEHTIME):"T",1:"")
 S BEHB=$$ASKDATE("   Begin with DATE: ",.BEHBDF,,BEHOPT)
 S:'BEHPOP BEHE=$$ASKDATE("     End with DATE: ",$S($G(BEHSAME):BEHB,$G(BEHEDF):BEHEDF,1:""),BEHB,BEHOPT)
 Q
ASKDATE(BEHPMT,BEHDFL,BEHMIN,BEHOPT) ;
 N %DT,Y
 S %DT="APEX"_$G(BEHOPT)
 S %DT("A")=BEHPMT
 S:$G(BEHMIN) %DT(0)=BEHMIN
 I $G(BEHDFL) D
 .S Y=BEHDFL
 .D DD^%DT
 .S %DT("B")=Y
 D ^%DT
 S:Y<0 BEHPOP=1
 Q Y
DIR(BEHDTP,BEHPMT,BEHDFL,BEHHLP,BEHPOP,BEHSCN) ; EP
 N DIR,DTOUT,DUOUT,Y
 S DIR(0)=BEHDTP,DIR("B")=$G(BEHDFL)
 I '$G(BEHPMT) M DIR("A")=BEHPMT
 E  D GETTEXT(BEHPMT,$NA(DIR("A")))
 I '$G(BEHHLP) M DIR("?")=BEHHLP
 E  D GETTEXT(BEHHLP,$NA(DIR("?")))
 S:$L($G(BEHSCN)) DIR("S")=BEHSCN
 D ^DIR
 S:$D(DUOUT)!$D(DTOUT) BEHPOP=1
 Q Y
GETTEXT(BEHDG,BEHAR) ;
 N BEHPM,X
 K @BEHAR
 F X=2:1:$L(BEHDG,U) S BEHPM(X-1)=$P(BEHDG,U,X)
 S BEHDG=$S(BEHDG<0:-BEHDG,1:+BEHDG)
 D BLD^DIALOG(BEHDG/1000+59000,.BEHPM,,BEHAR)
 Q
