BEHOIMP2 ;IHS/MSC/PLS - SUPPORT FOR IMPLANTABLE DEVICES ;22-Nov-2022 16:54;PLS
 ;;1.1;BEH COMPONENTS;**073001,073003**;March 20,2007;Build 9
 ;
 Q
 ;Input: XML string containing data to store
 ;Returns flag 1 or 0^Error text
SAVE(DATA,XML) ;-
 N IEN,UPDATE
 S IEN="+1"
 S UPDATE=0
 D STORE(.DATA,.XML,IEN,UPDATE)
 Q
STORE(DATA,XML,IEN,UPDATE) ;Store the data
 N HANDLE,LST,NODE,CNT2,STRING,NAME,CNAME,FDA,IENS,ERR,STS,TXT
 N VISIT,DFN,PRV,IDARR,CNT,CURSTAT
 I +UPDATE S CURSTAT=$$GET1^DIQ(9000091,IEN,3.1,"I")
 E  S CURSTAT=""
 S CNT=0
 K ^TMP("BEHIMP",$J)
 S DATA=""
 S STS="A^ACTIVE"
 S ^TMP("BEHIMP",$J,1)="<?xml version=""1.0"" ?>"
 S ^TMP("BEHIMP",$J,2)="<!DOCTYPE Change>"
 S CNT=0,CNT2=3
 F  S CNT=$O(XML(CNT)) Q:'+CNT  D
 .S ^TMP("BEHIMP",$J,CNT2)=XML(CNT)
 .S CNT2=CNT2+1
 S HANDLE=$$EN^MXMLDOM($NA(^TMP("BEHIMP",$J)),"D")
 I HANDLE=0 S DATA="0^Unable to store XML string" Q
 S NODE=1,CNT=0,STRING=""
 F  S NAME=$$NAME^MXMLDOM(HANDLE,NODE) Q:NAME=""  D
 .I NAME="ImplantEntry" D
 ..D CHILD(HANDLE,NODE)
 ..S NODE=$$SIBLING^MXMLDOM(HANDLE,NODE)
 .E  S NODE=NODE+1
 K ^TMP("BEHIMP",$J)
 Q
CHILD(HANDLE,NODE) ;Handle the child nodes
 N FDA,ERR,CHILD
 S CHILD=0
 S CHILD=$$CHILD^MXMLDOM(HANDLE,NODE,CHILD) Q:'CHILD
 S NAME=$$NAME^MXMLDOM(HANDLE,CHILD)
 D PROCESS(HANDLE,CHILD,NAME)
 D NEXT(HANDLE,CHILD)
 ;Store the file here
 Q
NEXT(HANDLE,CHILD) ;After getting the first child, retrieve the rest of them
 N CHILD2,NAME
 S CHILD2=CHILD
 F  S CHILD2=$$SIBLING^MXMLDOM(HANDLE,CHILD2) Q:CHILD2=0  D
 .S NAME=$$NAME^MXMLDOM(HANDLE,CHILD2)
 .D PROCESS(HANDLE,CHILD2,NAME)
 Q
PROCESS(HANDLE,NODE,NAME) ;Process the tag data for storage in the file at the top level
 N RESP,RET,IENS,RET,DIEN
 S VISIT=""
 S DIEN=IEN_","
 I NAME="Category" D  Q
 .S RESP=$$GETTXT(HANDLE,NODE)
 .S FDA(9000091,DIEN,.01)=RESP
 I NAME="PatientDFN" D  Q
 .S DFN=$$GETTXT(HANDLE,NODE)
 .S FDA(9000091,DIEN,.02)=DFN
 I NAME="VisitIEN"  D  Q
 .S VISIT=$$GETTXT(HANDLE,NODE)
 .I +VISIT S FDA(9000091,DIEN,.03)=VISIT
 I NAME="VisitStr" D  Q
 .I '+VISIT D
 ..S RESP=$$GETTXT(HANDLE,NODE)
 ..I RESP'="" D
 ...D FETCH^BEHOENCX(.RET,DFN,RESP,PRV,1)
 ...S FDA(9000091,DIEN,.03)=$P(RET,U,6)
 I NAME="ProviderIEN" D  Q
 .S PRV=$$GETTXT(HANDLE,NODE)
 .I +PRV S FDA(9000091,DIEN,.04)=PRV
 I NAME="ImplantDate" D  Q
 .S RESP=$$GETTXT(HANDLE,NODE)
 .I +RESP S FDA(9000091,DIEN,.06)=RESP
 .S FDA(9000091,DIEN,.05)=$$DT^XLFDT
 I NAME="ImplantedByValue" D  Q
 .S RESP=$$GETTXT(HANDLE,NODE)
 .S FDA(9000091,DIEN,6.01)=RESP
 ;I NAME="SearchValue" D  Q
 ;.S RESP=$$GETTXT(HANDLE,NODE)
 ;.I RESP'="" S FDA(9000091,DIEN,2.1)=RESP
 I NAME="Description" D  Q
 .S RESP=$$GETTXT(HANDLE,NODE)
 .I RESP'="" S FDA(9000091,DIEN,2)=RESP
 I NAME="EffectiveUntilDate" D  Q
 .S RESP=$$GETTXT(HANDLE,NODE)
 .S RESP=$S(RESP:RESP,1:"@") S FDA(9000091,DIEN,.13)=RESP
 I NAME="BodyLocation" D  Q
 .S RESP=$$GETTXT(HANDLE,NODE)
 .I RESP'="" D
 ..S FDA(9000091,DIEN,.1)=$P(RESP,U,2)
 ..D BSTSBLOC(RESP,FDA(9000091,DIEN,.01))
 I NAME="ImplantFacility" D  Q
 .N SITE,SITETXT
 .S RESP=$$GETTXT(HANDLE,NODE)
 .S SITE=+RESP  ;$P($P(RESP,"|",1),";",1)
 .S SITETXT=$P(RESP,"|",2)
 .I +SITE S FDA(9000091,DIEN,1.01)=SITE
 .E  D
 ..S FDA(9000091,DIEN,1.01)="@"
 ..S FDA(9000091,DIEN,1.02)=SITETXT
 I NAME="AssociatedProblem" D  Q
 .S RESP=$$GETTXT(HANDLE,NODE)
 .I RESP'="" S FDA(9000091,DIEN,.08)=RESP
 I NAME="Procedure" D  Q
 .S RESP=$$GETTXT(HANDLE,NODE)
 .I RESP'="" S FDA(9000091,DIEN,.09)=RESP
 I NAME="Comment" D
 .S RESP=$$GETTXT(HANDLE,NODE)
 .I RESP'="" D
 ..S TXT(1,0)=RESP
 I NAME="Devices" D
 .;Store or edit the top level
 .S FDA(9000091,DIEN,.12)=$$NOW^XLFDT()
 .I +UPDATE D FILE^DIE("","FDA","ERR")
 .E  D
 ..D UPDATE^DIE(,"FDA","IENS","ERR")
 ..I $D(IENS(1)) S IEN=IENS(1)
 .I $D(ERR) S DATA="0^Unable to store implant data"
 .E  S DATA=1
 .K FDA,ERR,IENS
 .I +IEN D
 ..;Update the status node
 ..D:$P(STS,U,2)'=CURSTAT UPTSTS^BEHOIMP1(.RET,IEN,$P(STS,U,1),"")
 ..D COMMENT(.TXT)
 ..I UPDATE=1 D
 ...D DELDEV(IEN,"*")
 ..D DEVICES(HANDLE,NODE,IEN,.IDARR)      ;Add in the devices
 ..I +UPDATE D
 ...S TXT(1,0)="This record has been updated"
 ...D COMMENT(.TXT)
 Q
GETTXT(HANDLE,NODE) ;Get the data stored in the tag
 N TXT,RESP,CHOICE
 S RESP=$$TEXT^MXMLDOM(HANDLE,NODE,"TXT")
 S CHOICE=$G(TXT(1))
 Q CHOICE
DEVICES(HANDLE,NODE,IEN,IDARR) ;Begin the retrieval of the data in the device subentry
 N DCHILD,AIEN,FDA,ERR,IENS,IMPIEN,MRI,DESC
 S DCHILD=0,IMPIEN=""
 S CNT=CNT+1
 S AIEN="+"_CNT_","_IEN_","
 F  S DCHILD=$$CHILD^MXMLDOM(HANDLE,NODE,DCHILD) Q:'DCHILD  D
 .S NAME=$$NAME^MXMLDOM(HANDLE,DCHILD)
 .I NAME="Device" D
 ..D DDATA(HANDLE,DCHILD,.AIEN)
 ..;Store the subentry
 ..I $G(FDA(9000091.4,AIEN,.01))'="" D
 ...D UPDATE^DIE(,"FDA","IENS","ERR")
 ...S DATA=$S($G(ERR("DIERR",1)):-ERR("DIERR",1)_U_ERR("DIERR",1,"TEXT",1),1:1)
 ...I $D(IENS(1)) D
 ....S SIEN=IENS(1)_","_IEN_","
 ....D WP^DIE(9000091.4,SIEN,4,,"DESC")
 ....D WP^DIE(9000091.4,SIEN,5,,"MRI")
 ...K FDA,ERR,IENS
 Q
DDATA(HANDLE,DEVICE,AIEN) ;Retrieve the fields for the subfile
 N DNODE,NAME
 S DNODE=0
 F  S DNODE=$$CHILD^MXMLDOM(HANDLE,DEVICE,DNODE) Q:'DNODE  D
 .S NAME=$$NAME^MXMLDOM(HANDLE,DNODE)
 .D ADDSUB(HANDLE,DNODE,NAME,.AIEN)
 I $G(FDA(9000091.4,AIEN,.01))="" S FDA(9000091.4,AIEN,.01)="Not Provided"
 Q
IMPLANT(HANDLE,DEVICE,AIEN) ;Retrieve the fields for the subfile
 N INODE,NAME
 S INODE=0
 F  S INODE=$$CHILD^MXMLDOM(HANDLE,DEVICE,INODE) Q:'INODE  D
 .S NAME=$$NAME^MXMLDOM(HANDLE,INODE)
 .D ADDPRV(HANDLE,INODE,NAME,AIEN)
 Q
ADDPRV(HANDLE,NODE3,NAME,AIEN) ;Get the implanter
 N RESP,PRV
 I NAME="IEN" D
 .S RESP=$$GETTXT(HANDLE,NODE3)
 .I RESP'="",$L($$TRIM^XLFSTR(RESP)) S IMPIEN=RESP
 .S PRV=$$GET1^DIQ(200,IMPIEN,.01)
 .S FDA(9000091.4,AIEN,.02)=$G(IMPIEN)_"|"_PRV
 I NAME="Name" D
 .S RESP=$$GETTXT(HANDLE,NODE3)
 .Q:RESP=""
 .I $G(IMPIEN)="" S FDA(9000091.4,AIEN,.02)="|"_RESP
 Q
ADDSUB(HANDLE,NODE2,NAME,AIEN) ;Get the text of the fields and put it in array for storage
 N RESP
 I NAME="IEN" D
 .S RESP=$$GETTXT(HANDLE,NODE2)
 .I +RESP D
 ..S FDA(9000091.4,AIEN,.01)=RESP
 I NAME="ID" D  Q
 .S RESP=$$GETTXT(HANDLE,NODE2)
 .I RESP'="" S FDA(9000091.4,AIEN,.01)=RESP
 I NAME="ID_Issuing_Agency" D  Q
 .S RESP=$$GETTXT(HANDLE,NODE2)
 .I RESP'="" S FDA(9000091.4,AIEN,8.01)=RESP
 I NAME="Name" D  Q
 .S RESP=$$GETTXT(HANDLE,NODE2)
 .I RESP'="" S FDA(9000091.4,AIEN,10.01)=RESP
 I NAME="UDI" D  Q
 .S RESP=$$GETTXT(HANDLE,NODE2)
 .I RESP'="" S FDA(9000091.4,AIEN,9.01)=RESP
 I NAME="ImplantedBy" D  Q
 .D IMPLANT(HANDLE,NODE2,AIEN)
 I NAME="SerialNumber" D  Q
 .S RESP=$$GETTXT(HANDLE,NODE2)
 .I RESP'="" S FDA(9000091.4,AIEN,.03)=RESP
 I NAME="Lot_Batch" D  Q
 .S RESP=$$GETTXT(HANDLE,NODE2)
 .I RESP'="" S FDA(9000091.4,AIEN,.04)=RESP
 I NAME="ManufacturedDate" D  Q
 .S RESP=$$GETTXT(HANDLE,NODE2)
 .I RESP'="" S FDA(9000091.4,AIEN,.05)=RESP
 I NAME="ExpirationDate" D  Q
 .S RESP=$$GETTXT(HANDLE,NODE2)
 .I RESP'="" S FDA(9000091.4,AIEN,.06)=RESP
 I NAME="HCTP" D  Q
 .S RESP=$$GETTXT(HANDLE,NODE2)
 .S RESP=$S(RESP="false":0,RESP="true":1,1:"")
 .I RESP'="" S FDA(9000091.4,AIEN,.07)=RESP
 I NAME="GMDN_PT_Name" D  Q
 .S RESP=$$GETTXT(HANDLE,NODE2)
 .I RESP'="" S FDA(9000091.4,AIEN,1.01)=RESP
 I NAME="SNOMED_CT_CODE" D  Q
 .S RESP=$$GETTXT(HANDLE,NODE2)
 .I RESP'="" S FDA(9000091.4,AIEN,1.02)=RESP
 I NAME="SNOMED_CT_DESC" D  Q
 .S RESP=$$GETTXT(HANDLE,NODE2)
 .I RESP'="" S FDA(9000091.4,AIEN,11.01)=RESP
 I NAME="BrandName" D  Q
 .S RESP=$$GETTXT(HANDLE,NODE2)
 .I RESP'="" S FDA(9000091.4,AIEN,2.01)=RESP
 I NAME="Version_Model" D  Q
 .S RESP=$$GETTXT(HANDLE,NODE2)
 .I RESP'="" S FDA(9000091.4,AIEN,2.02)=RESP
 I NAME="CompanyName" D  Q
 .S RESP=$$GETTXT(HANDLE,NODE2)
 .I RESP'="" S FDA(9000091.4,AIEN,3.01)=RESP
 I NAME="LatexWarning" D  Q
 .S RESP=$$GETTXT(HANDLE,NODE2)
 .S RESP=$S(RESP="false":0,RESP="true":1,1:"")
 .I RESP'="" S FDA(9000091.4,AIEN,3.02)=RESP
 I NAME="MRI_Safety_Info" D  Q
 .S RESP=$$GETTXT(HANDLE,NODE2)
 .I RESP'="" S MRI(1,0)=RESP
 I NAME="SearchValue" D  Q
 .S RESP=$$GETTXT(HANDLE,NODE2)
 .I RESP'="" S FDA(9000091.4,AIEN,7.01)=RESP
 I NAME="Description" D  Q
 .S RESP=$$GETTXT(HANDLE,NODE2)
 .I RESP'="" S DESC(1,0)=RESP
 Q
COMMENT(TXT) ;Store the comments
 N FDA,ERR,CIEN,IENS,SIEN
 Q:$D(TXT)=0
 S CIEN="+1,"_IEN_","
 S FDA(9000091.5,CIEN,.01)=$$NOW^XLFDT
 S FDA(9000091.5,CIEN,.02)=DUZ
 D UPDATE^DIE(,"FDA","IENS","ERR")
 I +IENS(1) D
 .S SIEN=IENS(1)_","_IEN_","
 .D WP^DIE(9000091.5,SIEN,1,,"TXT")
 Q
DELDEV(IEN,ITM) ;
 N SUB,DEV
 I ITM="*" D
 .S DEV="" F  S DEV=$O(^AUPNPDEV(IEN,4,"B",DEV)) Q:DEV=""  D
 ..S SUB=0 F  S SUB=$O(^AUPNPDEV(IEN,4,"B",DEV,SUB)) Q:'+SUB  D
 ...D DELETE(IEN,SUB)
 E  D DELETE(IEN,ITM)
 Q
DELETE(IEN,SUB) ;Delete a device
 N ERR,DA,DIK,RES
 S DA(1)=IEN,DA=SUB
 S DIK="^AUPNPDEV(DA(1),4,"
 S:DA RES=$$DELETE^BGOUTL(DIK,.DA)
 Q
SAVEIDS(IEN,IDARR) ;Find and save the IDS
 N ID,DEV
 S DEV=0 F  S DEV=$O(^AUPNPDEV(IEN,4,DEV)) Q:'+DEV  D
 .S ID=$P($G(^AUPNPDEV(IEN,4,DEV,0)),U,1)
 .S IDARR(DEV)=ID
 Q
BSTSBLOC(DATA,CAT) ; Notify BSTS of body location selection
 N DTSSUB
 S DTSSUB=$$GET1^DIQ(9999999.106,+$G(CAT),.04)
 D SELECT^BSTSRPC1("",$P(DATA,U,2),36,$P(DATA,U),DTSSUB)
 Q
