BGOVEM ; IHS/MSC/MGH - E&M coding ;24-Aug-2021 08:59;DU
 ;;1.1;BGO COMPONENTS;**30**;Mar 20, 2007;Build 2
 ;---------------------------------------------
GETSL(RET) ;Return all the service levels for E&M coding
 N EIEN,CNT
 S RET=$$TMPGBL^BGOUTL("EM")
 S (CNT,EIEN)=0
 F  S EIEN=$O(^BEHOEMSL(EIEN)) Q:'EIEN  D
 .S CNT=CNT+1
 .S @RET@(CNT)=EIEN_U_$G(^BEHOEMSL(EIEN,0))
 Q
 ;Return the data for one service level
GETDATA(RET,IEN) ; EP
 N CNT,COL,STRING,CNAME,TYP,TYPIEN,ENTRY,SUB,AIEN,EXM,LVL,TIME,CPT
 S RET=$$TMPGBL^BGOUTL("EM")
 S CNT=0
 S STRING=""
 S COL=0 F  S COL=$O(^BEHOEMSL(IEN,2,COL)) Q:'+COL  D
 .S CNT=CNT+1
 .S CNAME=$G(^BEHOEMSL(IEN,2,COL,0))
 .I STRING="" S STRING=CNAME
 .E  S STRING=STRING_U_CNAME
 S @RET@(0)=CNT_U_STRING
 S (CNT,TYP)=0
 S TYP="" F  S TYP=$O(^BEHOEMSL(IEN,1,"B",TYP)) Q:TYP=""  D
 .S TYPIEN="" F  S TYPIEN=$O(^BEHOEMSL(IEN,1,"B",TYP,TYPIEN)) Q:'+TYPIEN  D
 ..S STRING=""
 ..S STRING=$P($G(^BEHOEMSL(IEN,1,TYPIEN,0)),U,1)_U_$P($G(^BEHOEMSL(IEN,1,TYPIEN,0)),U,2)
 ..S ENTRY=0 F  S ENTRY=$O(^BEHOEMSL(IEN,1,TYPIEN,1,"B",ENTRY)) Q:'+ENTRY  D
 ...S SUB=0 F  S SUB=$O(^BEHOEMSL(IEN,1,TYPIEN,1,"B",ENTRY,SUB)) Q:'+SUB  D
 ....S CNT=CNT+1
 ....S AIEN=SUB_","_TYPIEN_","_IEN_","
 ....S EXM=$$GET1^DIQ(90362.2511,AIEN,.01)
 ....S LVL=$$GET1^DIQ(90362.2511,AIEN,.02)
 ....S TIME=$$GET1^DIQ(90362.2511,AIEN,.03)
 ....S CPT=$$GET1^DIQ(90362.2511,AIEN,.04)
 ....S @RET@(CNT)=STRING_U_EXM_U_LVL_U_TIME_U_CPT
 Q
