ABMFPOA ; IHS/SD/SDR - Fix POA;
 ;;2.6;IHS 3P BILLING SYSTEM;**10**;NOV 12, 2009;Build 43
 S ABMDUZ2=0
 F  S ABMDUZ2=$O(^ABMDCLM(ABMDUZ2)) Q:'ABMDUZ2  D
 .S ABMP("CDFN")=0
 .F  S ABMP("CDFN")=$O(^ABMDCLM(ABMDUZ2,ABMP("CDFN"))) Q:'ABMP("CDFN")  D
 ..S ABMP("DX")=0
 ..F  S ABMP("DX")=$O(^ABMDCLM(ABMDUZ2,ABMP("CDFN"),17,ABMP("DX"))) Q:'ABMP("DX")  D
 ...Q:$P($G(^ABMDCLM(ABMDUZ2,ABMP("CDFN"),17,ABMP("DX"),0)),U,5)=""
 ...I "^Y^N^U^W^1^"'[("^"_$P($G(^ABMDCLM(ABMDUZ2,ABMP("CDFN"),17,ABMP("DX"),0)),U,5)_"^") D
 ....W !,ABMP("CDFN"),?12,ABMP("DX"),?20,$P($G(^ABMDCLM(ABMDUZ2,ABMP("CDFN"),17,ABMP("DX"),0)),U,5)
 ....K DIC,DIE,DIR,X,Y,DA,DR
 ....S DA(1)=ABMP("CDFN")
 ....S DA=ABMP("DX")
 ....S DIE="^ABMDCLM("_ABMDUZ2_","_DA(1)_",17,"
 ....S DR=".05////@"
 ....D ^DIE
 ;
 S ABMDUZ2=0
 F  S ABMDUZ2=$O(^ABMDBILL(ABMDUZ2)) Q:'ABMDUZ2  D
 .S ABMP("CDFN")=0
 .F  S ABMP("CDFN")=$O(^ABMDBILL(ABMDUZ2,ABMP("CDFN"))) Q:'ABMP("CDFN")  D
 ..S ABMP("DX")=0
 ..F  S ABMP("DX")=$O(^ABMDBILL(ABMDUZ2,ABMP("CDFN"),17,ABMP("DX"))) Q:'ABMP("DX")  D
 ...Q:$P($G(^ABMDBILL(ABMDUZ2,ABMP("CDFN"),17,ABMP("DX"),0)),U,5)=""
 ...I "^Y^N^U^W^1^"'[("^"_$P($G(^ABMDBILL(ABMDUZ2,ABMP("CDFN"),17,ABMP("DX"),0)),U,5)_"^") D
 ....W !,ABMP("CDFN"),?12,ABMP("DX"),?20,$P($G(^ABMDBILL(ABMDUZ2,ABMP("CDFN"),17,ABMP("DX"),0)),U,5)
 ....K DIC,DIE,DIR,X,Y,DA,DR
 ....S DA(1)=ABMP("CDFN")
 ....S DA=ABMP("DX")
 ....S DIE="^ABMDBILL("_ABMDUZ2_","_DA(1)_",17,"
 ....S DR=".05////@"
 ....D ^DIE
 Q
