ABMPPAD6 ; IHS/SD/SDR - Prior Payments/Adjustments page (CE); 
 ;;2.6;IHS 3P BILLING SYSTEM;**37**;NOV 12, 2009;Build 739
 ; split routine from ABMPPADJ because of size
 ;IHS/SD/SDR 2.6*37 ADO76009 Added check for PI multiple to separate out insurers better
 ;
 ;ABMPL(Insurer priority, Insurer IEN)=
 ;  P1=13 multiple IEN
 ;  P2=Billing status
 ;ABMPP(Insurer IEN, PI multiple or '1', "P" or "A", Counter)=
 ;  P1=Amount
 ;  P2=Adj Category
 ;  P3=Trans. Type
 ;  P4=Std Adj. Reason
 ;  P5=billable?(Y/N)
 ;  P6=Payment multiple IEN
GATHER ;
 ;loop thru active bills
 S ABMBSTA=""
 F  S ABMBSTA=$O(^ABMDBILL(DUZ(2),"AS",ABMP("CDFN"),ABMBSTA)) Q:ABMBSTA=""  D
 .Q:ABMBSTA="X"
 .S ABMBFIEN=0
 .F  S ABMBFIEN=$O(^ABMDBILL(DUZ(2),"AS",ABMP("CDFN"),ABMBSTA,ABMBFIEN)) Q:+ABMBFIEN=0  D
 ..S ABMBNUM=$P($G(^ABMDBILL(DUZ(2),ABMBFIEN,0)),U)
 ..;get prev payments
 ..S ABMPIEN=0,ABMTFLAG=0
 ..F  S ABMPIEN=$O(^ABMDBILL(DUZ(2),ABMBFIEN,3,ABMPIEN)) Q:+ABMPIEN=0  D
 ...S ABMLN=+$G(ABMLN)+1
 ...S ABMPREC=$G(^ABMDBILL(DUZ(2),ABMBFIEN,3,ABMPIEN,0))
 ...;check if summary or split out entries; if split set flag so it won't get trans from A/R again
 ...S ABMBINS=$P($G(^ABMDBILL(DUZ(2),ABMBFIEN,0)),U,8)
 ...S ABMEMLT=$S(+$P($G(^ABMDBILL(DUZ(2),ABMBFIEN,0)),U,26)'=0:$P($G(^ABMDBILL(DUZ(2),ABMBFIEN,0)),U,26),1:1)  ;abm*2.6*37 IHS/SD/SDR ADO76009
 ...I $P($G(^ABMDBILL(DUZ(2),ABMBFIEN,2)),U)'=(+$P(ABMPREC,U,3)+($P(ABMPREC,U,4))+($P(ABMPREC,U,6))+($P(ABMPREC,U,7))+($P(ABMPREC,U,9))+($P(ABMPREC,U,10))+($P(ABMPREC,U,12))+($P(ABMPREC,U,13))+($P(ABMPREC,U,14))) D
 ....S ABMTFLAG=1
 ....S ABMOPDT=$P(ABMPREC,U)
 ....I +$P(ABMPREC,U,10)'=0 S ABMCAT="P",ABMAMT=$P(ABMPREC,U,10)
 ....E  D
 .....S ABMCAT="A"
 .....S ABMADJC=$P(ABMPREC,U,15)
 .....S ABMADJT=$P(ABMPREC,U,16)
 .....S ABMSAR=$P(ABMPREC,U,17)
 .....I ABMADJC=3 S ABMAMT=$P(ABMPREC,U,6)
 .....I ABMADJC=4 S ABMAMT=$P(ABMPREC,U,7)
 .....I ABMADJC=13 S ABMAMT=$P(ABMPREC,U,3)
 .....I ABMADJC=14 S ABMAMT=$P(ABMPREC,U,4)
 .....I ABMADJC=15 S ABMAMT=$P(ABMPREC,U,9)
 .....I ABMADJC=16 S ABMAMT=$P(ABMPREC,U,12)
 .....I ABMADJC=19 S ABMAMT=$P(ABMPREC,U,13)
 .....I ABMADJC=20 S ABMAMT=$P(ABMPREC,U,14)
 ....S ABMBINS=$P($G(^ABMDBILL(DUZ(2),ABMBFIEN,0)),U,8)
 ....S ABMEMLT=$S(+$P($G(^ABMDBILL(DUZ(2),ABMBFIEN,0)),U,26)'=0:$P($G(^ABMDBILL(DUZ(2),ABMBFIEN,0)),U,26),1:1)  ;abm*2.6*37 IHS/SD/SDR ADO76009
 ....I '$D(^ABMDBILL(DUZ(2),ABMBFIEN,13,"B",ABMBINS)) D  ;means it is replacement insurer
 .....S ABMTIEN=0,ABMTFLG=0
 .....F  S ABMTIEN=$O(^ABMDBILL(DUZ(2),ABMBFIEN,13,ABMTIEN)) Q:'ABMTIEN  D  Q:ABMTFLG
 ......I $P($G(^ABMDBILL(DUZ(2),ABMBFIEN,13,ABMTIEN,0)),U,11)=ABMBINS D  ;this is our replacement
 .......S ABMBINS=$P($G(^ABMDBILL(DUZ(2),ABMBFIEN,13,ABMTIEN,0)),U)
 .......S ABMTFLG=1
 .....K ABMTIEN,ABMTFLG
 ....Q:(+$G(ABMAMT)=0)&(($G(ABMCAT)="A")&(+$G(ABMADJC)=0))  ;stop <UNDEF>GATHER+42 error
 ....;start old abm*2.6*37 IHS/SD/SDR ADO76009
 ....;S ABMPP(ABMBINS,ABMCAT,ABMLN)=ABMAMT_$S(ABMCAT="A":"^"_ABMADJC_"^"_ABMADJT_"^"_ABMSAR,1:"")
 ....;I ABMCAT="P" S $P(ABMPP(ABMBINS,ABMCAT,ABMLN),U,5)="N"
 ....;I ABMCAT="A",(ABMADJC=13!(ABMADJC=14)) S $P(ABMPP(ABMBINS,ABMCAT,ABMLN),U,5)="Y"
 ....;I ABMCAT="A",(ABMADJC'=13&(ABMADJC'=14)) S $P(ABMPP(ABMBINS,ABMCAT,ABMLN),U,5)="N"
 ....;S $P(ABMPP(ABMBINS,ABMCAT,ABMLN),U,6)=ABMPIEN  ;save payment IEN w/trans
 ....;end old start new abm*2.6*37 IHS/SD/SDR ADO76009
 ....;S ABMEMLT=$S(+$P($G(^ABMDBILL(DUZ(2),ABMBFIEN,0)),U,26)'=0:$P($G(^ABMDBILL(DUZ(2),ABMBFIEN,0)),U,26),+$P($G(^ABMDBILL(DUZ(2),ABMBFIEN,13,ABMTIEN,0)),U,8)'=0:$P($G(^ABMDBILL(DUZ(2),ABMBFIEN,13,ABMTIEN,0)),U,8),1:1)
 ....I +$G(ABMTIEN)=0 S ABMTIEN=1
 ....I +$P($G(^ABMDBILL(DUZ(2),ABMBFIEN,0)),U,26)'=0 S ABMEMLT=$P($G(^ABMDBILL(DUZ(2),ABMBFIEN,0)),U,26)
 ....I ((+$G(ABMEMLT)=0)&(+$P($G(^ABMDBILL(DUZ(2),ABMBFIEN,13,ABMTIEN,0)),U,8))) S ABMEMLT=$P($G(^ABMDBILL(DUZ(2),ABMBFIEN,13,ABMTIEN,0)),U,8)
 ....;
 ....S ABMPP(ABMBINS,ABMEMLT,ABMCAT,ABMLN)=ABMAMT_$S(ABMCAT="A":"^"_ABMADJC_"^"_ABMADJT_"^"_ABMSAR,1:"")
 ....I ABMCAT="P" S $P(ABMPP(ABMBINS,ABMEMLT,ABMCAT,ABMLN),U,5)="N"
 ....I $P($G(ABMPREC),U,18)'="" S $P(ABMPP(ABMBINS,ABMEMLT,ABMCAT,ABMLN),U,5)=$P(ABMPREC,U,18)
 ....I ABMCAT="A",(ABMADJC=13!(ABMADJC=14)) S $P(ABMPP(ABMBINS,ABMEMLT,ABMCAT,ABMLN),U,5)="Y"
 ....I ABMCAT="A",(ABMADJC'=13&(ABMADJC'=14)&$P($G(ABMPREC),U,18)="") S $P(ABMPP(ABMBINS,ABMEMLT,ABMCAT,ABMLN),U,5)="N"
 ....S $P(ABMPP(ABMBINS,ABMEMLT,ABMCAT,ABMLN),U,6)=ABMPIEN  ;save payment IEN w/trans
 ....;end new abm*2.6*37 IHS/SD/SDR ADO76009
 ...S ABMILST(ABMBINS,ABMBFIEN)=""
 ...I $P($G(^ABMDBILL(DUZ(2),ABMBFIEN,2)),U)=(+$P(ABMPREC,U,3)+($P(ABMPREC,U,4))+($P(ABMPREC,U,6))+($P(ABMPREC,U,7))+($P(ABMPREC,U,9))+($P(ABMPREC,U,10))+($P(ABMPREC,U,12))+($P(ABMPREC,U,13))+($P(ABMPREC,U,14))) D
 ....S ABMOPDT=$P($G(^ABMDBILL(DUZ(2),ABMBFIEN,3,ABMPIEN,0)),U)  ;original pymt dt
 ....K ^ABMDBILL(DUZ(2),ABMBFIEN,3)  ;remove summary entry; indiv entries will be filed later
 ..Q:($G(ABMTFLAG)=1)  ;trans split; skip next part
 ..;get trans for those bills
 ..I (($P($G(^ABMDPARM(ABMP("LDFN"),1,2)),U,4)'="")&($G(ABMBSUF)'="")) S ABMBNUM=$G(ABMBNUM)_"-"_ABMBSUF
 ..I (($P($G(^ABMDPARM(ABMP("LDFN"),1,3)),U,3)=1)&($G(ABMPHRN)'="")) S ABMBNUM=$G(ABMBNUM)_"-"_ABMPHRN
 ..;
 ..S ABMHOLD=DUZ(2)
 ..S ABMSAT=ABMP("LDFN")  ;Satellite=3P Visit loc           
 ..S ABMPAR=0  ;Parent
 ..; check site active at DOS to ensure bill added to correct site
 ..S DA=0
 ..F  S DA=$O(^BAR(90052.06,DA)) Q:DA'>0  D  Q:ABMPAR
 ...Q:'$D(^BAR(90052.06,DA,DA))  ;Pos Parent UNDEF Site Parameter
 ...Q:'$D(^BAR(90052.05,DA,ABMSAT))  ;Satellite UNDEF Parent/Satellit
 ...Q:+$P($G(^BAR(90052.05,DA,ABMSAT,0)),U,5)  ;Par/Sat not usable
 ...;Q if sat NOT active at DOS
 ...I ABMP("VDT")<$P($G(^BAR(90052.05,DA,ABMSAT,0)),U,6) Q
 ...;Q if sat became NOT active before DOS
 ...I $P($G(^BAR(90052.05,DA,ABMSAT,0)),U,7),(ABMP("VDT")>$P($G(^BAR(90052.05,DA,ABMSAT,0)),U,7)) Q
 ...S ABMPAR=$S(ABMSAT:$P($G(^BAR(90052.05,DA,ABMSAT,0)),U,3),1:"")
 ..Q:+ABMPAR=0
 ..S DUZ(2)=ABMPAR
 ..S ABMAIEN=$O(^BARBL(DUZ(2),"B",ABMBNUM,0))
 ..I +$G(ABMAIEN)=0 S:+$G(ABMHOLD)'=0 DUZ(2)=ABMHOLD K ABMHOLD Q  ;there isn't an A/R bill w/this number
 ..Q:$P($G(^BARAC(DUZ(2),$P($G(^BARBL(DUZ(2),ABMAIEN,0)),U,3),0)),U)'["AUTNINS"
 ..S ABMBINS=+$P($G(^BARAC(DUZ(2),$P($G(^BARBL(DUZ(2),ABMAIEN,0)),U,3),0)),U)
 ..I '$D(^ABMDBILL(DUZ(2),ABMBFIEN,13,"B",ABMBINS)) D  ;means it is a replacement insurer
 ...S ABMTIEN=0,ABMTFLG=0
 ...F  S ABMTIEN=$O(^ABMDBILL(DUZ(2),ABMBFIEN,13,ABMTIEN)) Q:'ABMTIEN  D  Q:ABMTFLG
 ....I $P($G(^ABMDBILL(DUZ(2),ABMBFIEN,13,ABMTIEN,0)),U,11)=ABMBINS D  ;this is our replacement
 .....S ABMBINS=$P($G(^ABMDBILL(DUZ(2),ABMBFIEN,13,ABMTIEN,0)),U)
 .....S ABMEMLT=$S(+$P($G(^ABMDBILL(DUZ(2),ABMBFIEN,13,ABMTIEN,0)),U,8)'=0:$P($G(^ABMDBILL(DUZ(2),ABMBFIEN,13,ABMTIEN,0)),U,8),1:1)  ;abm*2.6*37 IHS/SD/SDR ADO76009
 .....S ABMTFLG=1
 ...K ABMTIEN,ABMTFLG
 ...S ABMILST(ABMBINS,ABMBFIEN)=""
 ..S ABMTRIEN=0,ABMLN=1
 ..F  S ABMTRIEN=$O(^BARTR(DUZ(2),"AC",ABMAIEN,ABMTRIEN)) Q:ABMTRIEN=""  D
 ...S ABMREC=$G(^BARTR(DUZ(2),ABMTRIEN,0))
 ...I $G(ABMOPDT)="" S ABMOPDT=$P($P(ABMREC,U),".")
 ...Q:+$P(ABMREC,U,2)=0&(+$P(ABMREC,U,3)=0)
 ...S ABMTTYP=$P($G(^BARTR(DUZ(2),ABMTRIEN,1)),U,1)
 ...S ABMADJC=$P($G(^BARTR(DUZ(2),ABMTRIEN,1)),U,2)
 ...S ABMCAT=""
 ...I ABMTTYP=40 S ABMCAT="P"
 ...I "^3^4^13^14^15^16^19^20^"[("^"_ABMADJC_"^") S ABMCAT="A",ABMTTYP=$P($G(^BARTR(DUZ(2),ABMTRIEN,1)),U,3)
 ...Q:ABMCAT=""
 ...;S ABMPP(ABMBINS,ABMCAT,ABMLN)=$S(+$P(ABMREC,U,2)'=0&(ABMCAT="A"):$P(ABMREC,U,2),+$P(ABMREC,U,2)'=0&(ABMCAT="P"):$P(ABMREC,U,2),1:$P(ABMREC,U,3))_"^"_ABMADJC_"^"_ABMTTYP  ;abm*2.6*33 ADO60189
 ...S ABMTAMT=$$GET1^DIQ(90050.03,ABMTRIEN_",",3.5)  ;abm*2.6*33 ADO60189
 ...;start old abm*2.6*37 IHS/SD/SDR ADO76009
 ...;S ABMPP(ABMBINS,ABMCAT,ABMLN)=ABMTAMT_"^"_ABMADJC_"^"_ABMTTYP  ;abm*2.6*33 ADO60189
 ...;I ABMCAT="A",$D(^BARADJ("C",ABMADJC,ABMTTYP)) S $P(ABMPP(ABMBINS,ABMCAT,ABMLN),U,4)=$O(^BARADJ("C",ABMADJC,ABMTTYP,0))
 ...;I ABMCAT="P" S $P(ABMPP(ABMBINS,ABMCAT,ABMLN),U,5)="N",ABMLN=ABMLN+1 Q
 ...;;S $P(ABMPP(ABMBINS,ABMCAT,ABMLN),U,5)="Y",ABMLN=ABMLN+1  ;abm*2.6*31 CR8944
 ...;;start new abm*2.6*31 CR8944
 ...;I ABMCAT="A",(ABMADJC=13!(ABMADJC=14)) S $P(ABMPP(ABMBINS,ABMCAT,ABMLN),U,5)="Y",ABMLN=ABMLN+1
 ...;I ABMCAT="A",(ABMADJC'=13&(ABMADJC'=14)) S $P(ABMPP(ABMBINS,ABMCAT,ABMLN),U,5)="N",ABMLN=ABMLN+1
 ...;end old start new abm*2.6*37 IHS/SD/SDR ADO76009
 ...S ABMPP(ABMBINS,ABMEMLT,ABMCAT,ABMLN)=ABMTAMT_"^"_ABMADJC_"^"_ABMTTYP  ;abm*2.6*33 ADO60189
 ...I ABMCAT="A",$D(^BARADJ("C",ABMADJC,ABMTTYP)) S $P(ABMPP(ABMBINS,ABMEMLT,ABMCAT,ABMLN),U,4)=$O(^BARADJ("C",ABMADJC,ABMTTYP,0))
 ...I ABMCAT="P" S $P(ABMPP(ABMBINS,ABMEMLT,ABMCAT,ABMLN),U,5)="N",ABMLN=ABMLN+1 Q
 ...I ABMCAT="A",(ABMADJC=13!(ABMADJC=14)) S $P(ABMPP(ABMBINS,ABMEMLT,ABMCAT,ABMLN),U,5)="Y",ABMLN=ABMLN+1
 ...I ABMCAT="A",(ABMADJC'=13&(ABMADJC'=14)) S $P(ABMPP(ABMBINS,ABMEMLT,ABMCAT,ABMLN),U,5)="N",ABMLN=ABMLN+1
 ...;end new abm*2.6*37 IHS/SD/SDR ADO76009
 ...;end new abm*2.6*31 CR8944
 ..I +$G(ABMHOLD)'=0 S DUZ(2)=ABMHOLD K ABMHOLD
 ..D ^ABMPPAD3
 ..I ABMTFLAG=0 D ^ABMPPFLR  ;do filer if trans not split
 S ABMTFLAG=1
 Q
