ABMPPAD3 ; IHS/SD/SDR - COB page merge duplicate SAR entries; 
 ;;2.6;IHS 3P BILLING SYSTEM;**19,31,37**;NOV 12, 2009;Build 739
 ;IHS/SD/SDR 2.6*19 HEAT168248 New routine to merge same SARs into one entry.
 ;IHS/SD/SDR 2.6*31 CR8944 Fix so it will stop merged SARs for different insurers together
 ;IHS/SD/SDR 2.6*37 ADO76009 Rewrote all of looping; Took out loops for insurer and added ABMEMLT subscript
 ;
 K ABMTPP,ABMTI,ABMTSAR,ABMTREAL
 K ABMTPP  ;reset this array for each insurer  ;abm*2.6*31 IHS/SD/SDR CR8944
 S ABMTT=0
 F  S ABMTT=$O(ABMPP(ABMBINS,ABMEMLT,"A",ABMTT)) Q:'ABMTT  D
 .S ABMTSAR=$P($G(ABMPP(ABMBINS,ABMEMLT,"A",ABMTT)),U,4)
 .I $G(ABMTSAR)="" Q  ;no SAR
 .I $D(ABMTPP(ABMTSAR)) D
 ..S ABMTREAL=$O(ABMTPP(ABMTSAR,0))
 ..S $P(ABMPP(ABMBINS,ABMEMLT,"A",ABMTREAL),U)=$P(ABMPP(ABMBINS,ABMEMLT,"A",ABMTREAL),U)+$P(ABMPP(ABMBINS,ABMEMLT,"A",ABMTT),U)
 ..K ABMPP(ABMBINS,ABMEMLT,"A",ABMTT)
 .I '$D(ABMTPP(ABMTSAR)) S ABMTPP(ABMTSAR,ABMTT)=""
 K ABMTPP,ABMTI,ABMTSAR,ABMTREAL
 M ABMTPP(ABMBINS,ABMEMLT)=ABMPP(ABMBINS,ABMEMLT)
 K ABMPP(ABMBINS,ABMEMLT)
 S ABMCNT=1
 S ABMTTTYP=""
 F  S ABMTTTYP=$O(ABMTPP(ABMBINS,ABMEMLT,ABMTTTYP)) Q:ABMTTTYP=""  D
 .S ABMTT=0
 .F  S ABMTT=$O(ABMTPP(ABMBINS,ABMEMLT,ABMTTTYP,ABMTT)) Q:'ABMTT  D
 ..S ABMPP(ABMBINS,ABMEMLT,ABMTTTYP,ABMCNT)=$G(ABMTPP(ABMBINS,ABMEMLT,ABMTTTYP,ABMTT))
 ..S ABMCNT=ABMCNT+1
 K ABMTPP,ABMTI,ABMTSAR,ABMTREAL,ABMTTTYP,ABMCNT,ABMTT
 Q
