ABMP2643 ; IHS/SD/SDR - 3P BILLING 2.6 Patch 43 POST INSTALL ;  
 ;;2.6;IHS Third Party Billing;**43**;NOV 12, 2009;Build 794
 ;IHS/SD/SDR 2.6*43 ADO127005 UB-04 Table updates as of 7.1.2025
 ;
 Q
POST ;EP
 D ECODES  ;new UB-04 codes
 Q
ECODES ;
 K DIC,X
 F ABMI=1:1 S ABMLN=$P($T(ECODETXT+ABMI),";;",2) Q:ABMLN="END"  D
 .S ABMCODE=$P(ABMLN,U)
 .I $D(^ABMDCODE("AC",$P(ABMLN,U,2),ABMCODE)) D  Q
 ..S DA=$O(^ABMDCODE("AC",$P(ABMLN,U,2),ABMCODE,0))
 ..S $P(^ABMDCODE(DA,0),U,2)=$P(ABMLN,U,2),$P(^(0),U,3)=$P(ABMLN,U,3)
 ..S $P(^ABMDCODE(DA,0),U,4)=0  ;activates code
 ..D BMES^XPDUTL("Updated code "_ABMCODE_" "_$P(ABMLN,U,2)_" "_$P(ABMLN,U,3)_$S("^84^86^"[("^"_ABMCODE_"^"):" (inactive)",1:""))
 .S ABMDESC=$P(ABMLN,U,3)
 .S DIC="^ABMDCODE("
 .S DIC(0)="ML"
 .S X=ABMCODE
 .S DIC("DR")=".02///"_$P(ABMLN,U,2)
 .S DIC("DR")=DIC("DR")_";.03///"_ABMDESC
 .K DD,DO
 .D FILE^DICN
 .I Y>0 D BMES^XPDUTL("Added code "_ABMCODE_" "_$P(ABMLN,U,2)_" "_$P(ABMLN,U,3)_$S("^84^86^"[("^"_ABMCODE_"^"):" (inactive)",1:""))
 Q
ECODETXT ;
 ;;CA^C^CYBERATTACK OR OTHER SYSTEM OUTAGE (EFF 7/1/2025)
 ;;KX^C^DOCUMENTATION ON FILE (EFFECTIVE 7/1/2025)
 ;;63^C^INCARCERATED BENEFICIARIES (EFFECTIVE 7/1/2025)
 ;;92^V^DRUG/BIOLOGIC INVOICE COST (EFFECTIVE 1/1/2026)
 ;;END
