PSOBBC ;IHS/DSD/JCM - BATCH BARCODE DRIVER  [ 01/21/2003  3:56 PM ]
 ;;6.0;OUTPATIENT PHARMACY;**4**;09/03/97
 ;;6.0;OUTPATIENT PHARMACY;**48**;09/03/97
 ;-------------------------------------------------------------------
START ;
 D INIT
 S PSOBBC("QFLG")=0,PSORX("BAR CODE")=1
 D FROM I PSOBBC("QFLG") S PSORX("QFLG")=1 G END
 D ASK I PSOBBC("QFLG") S PSORX("QFLG")=1 G END
 D PROCESS
END D EOJ
 Q
 ;--------------------------------------------------------------------
INIT ;
 S PSOBBC("QFLG")=0,PSORX("BAR CODE")=1 K PPL
 I '$G(PSOINST) S PSOINST="000" I $D(^DD("SITE",1)) S PSOINST=^(1)
 Q
FROM ;
 S DIR(0)="S^1:REFILLS;2:RENEWS;"
 S DIR("A")="Batch Barcode for",DIR("B")="REFILLS"
 D DIR G:'Y FROMX
 S PSOBBC1("FROM")=$S(Y=1:"REFILL",1:"NEW")
FROMX K X,Y,DIR
 Q
 ;
ASK ;
 W !,"Please answer the following for this session of prescriptions",!
 D EN^PSOREF1(.PSOBBC) I PSOBBC("DFLG") S PSOBBC("QFLG")=1 G ASKX
 D SUSP
 D INPT
 D EARLY
 D SET
ASKX Q
 ;
SUSP ;
 I $G(VEXRX) S (PSOBBC1("QS"),PSOBBC("QS"))="Q" D SUSPX Q  ;cmi/maw 01/21/2003
 S DIR(0)="SAB^Q:QUEUED;S:SUSPENDED"
 S DIR("A")="Will these refills be Queued or Suspended ? "
 S DIR("B")="Q"
 D DIR G:PSOBBC("QFLG") SUSPX
 S (PSOBBC1("QS"),PSOBBC("QS"))=Y
SUSPX K X,Y,DIR
 Q
 ;
INPT ;
 S DIR(0)="YA"
 S DIR("A")="Allow fills for inpatient and CNH ? "
 S DIR("B")="N"
 D DIR G:PSOBBC("QFLG") INPTX
 S (PSOBBC1("INOK"),PSOBBC("INOK"))=Y
INPTX K X,Y,DIR
 Q
 ;
EARLY ;
 S DIR(0)="YA"
 S DIR("A")="Allow early refills ? "
 ;S DIR("B")="N" IHS/ITSC/ENM 01/21/2003 maw MODS NEXT LINE
 S DIR("B")="Y"  ;cmi/maw for auto refill system 12/09/2002
 D DIR G:PSOBBC("QFLG") EARLYX
 S (PSOBBC1("EAOK"),PSOBBC("EAOK"))=Y
EARLYX K X,Y,DIR
 Q
 ;
SET ;
 S PSOBBC1("MAIL/WINDOW")=PSOBBC("MAIL/WINDOW")
 S PSOBBC1("FILL DATE")=PSOBBC("FILL DATE")
 S:$G(PSOBBC("CLERK CODE")) PSOBBC1("CLERK CODE")=PSOBBC("CLERK CODE")
 S:$G(PSOBBC("EXPIRATION DATE")) PSOBBC1("EXPIRATION DATE")=PSOBBC("EXPIRATION DATE")
 Q
DIR ;
 D ^DIR
 S:$D(DUOUT) PSORX("QFLG")=1
 S:$D(DIRUT) PSOBBC("QFLG")=1
 K DIRUT,DUOUT,DTOUT,DIROUT
 Q
 ;
PROCESS ;
 S PSOBBC("DFLG")=0
 D GETRXM G:PSOBBC("QFLG") PROCESSX
 I $G(PSODFN)'=$P(^PSRX(PSOBBC("IRXN"),0),"^",2) D PT G:PSOBBC("DFLG") PROCESS
 S PSOBBC("DONE")=PSOBBC("IRXN")_","
 D @PSOBBC1("FROM") G PROCESS
PROCESSX ;I $G(PPL) D Q^PSORXL K PPL ;IHS/ITSC/ENM 01/21/2003 maw MODS
 I $G(PPL),'$G(VEXRX) D Q^PSORXL K PPL  ;cmi/maw 09/09/02 ORIG
 I $G(PPL),$G(VEXRX) D OPT^APSPNE4 K PPL,VEXPPL  ;cmi/maw 09/09/02 mod
 Q
GETRXM ;
 K DIR,PSOBBC("IRXN")
 S DIR(0)="FO^5:245^K:X'?3N1""-""1.N X"
 S DIR("A")="WAND BARCODE"
 S DIR("?",1)="Wand the barcoded number of the prescription to be processed."
 S DIR("?",2)="The number should be of the form NNN-NNNNNN"
 S DIR("?",3)="where the number before the dash is your station number."
 S DIR("?")="Enter ""^"", or a RETURN to quit."
 D DIR G:PSOBBC("QFLG") GETRXMX
 I $P(X,"-")'=PSOINST W !?7,*7,*7,*7,"Not From this Institution" G GETRXM
 S (PSOBBC("IRXN"),PSOBBC("OIRXN"))=$P(X,"-",2)
 I $G(^PSRX(PSOBBC("IRXN"),0))']"" W !,*7,"Rx data is not on file !",! G GETRXM
 I $P(^PSRX(PSOBBC("IRXN"),0),"^",15)=13 W !,*7,"Rx has already been deleted." G GETRXM
 I $G(PSOBBC("DONE"))[PSOBBC("IRXN")_"," W !,*7,"Rx has already been entered" G GETRXM
GETRXMX K X,Y,DIR
 Q
 ;
PT ;
 I $G(PPL),$G(VEXRX) D OPT^APSPNE4 K PPL,VEXPPL  ;cmi/maw 09/09/02 mod
 W !,*7,"New Patient, please pause"
 ;I $G(PPL) D Q^PSORXL K PPL  ;IHS/ITSC/ENM 01/21/03
 I $G(PPL),'$G(VEXRX) D Q^PSORXL K PPL  ;cmi/maw 09/09/02
 I '$G(PSORX("PSOL",1)) S PSORX("PSOL",1)=$G(PSOBBC("IRXN",0))  ;cmi/maw 09/09/02
 S PSODFN=$P(^PSRX(PSOBBC("IRXN"),0),"^",2),PSORX("NAME")=$P(^DPT(PSODFN,0),"^")
 S PSOX=$G(^PS(55,PSODFN,"PS")) I PSOX]"" S PSORX("PATIENT STATUS")=$P($G(^PS(53,PSOX,0)),"^")
 K PSOX
 D GET^PSOPTPST
 I $G(PSOPTPST(2,PSODFN,.351))]"" S PSOBBC("DFLG")=1 W !,*7,?10,"PATIENT DIED "_PSOPTPST(2,PSODFN,.351),! G PTX
 I $G(PSOPTPST(2,PSODFN,.1))]"" W !,*7,?10,"PATIENT IS AN INPATIENT ON WARD ",PSOPTPST(2,PSODFN,.1)," !!" I 'PSOBBC("INOK") S PSOBBC("DFLG")=1 G PTX
 K PSORX("CNH")
 I $G(PSOPTPST(2,PSODFN,148))="YES" W !,*7,?10,"PATIENT IS IN A CONTRACT NURSING HOME !!" S:PSOBBC("INOK") PSORX("CNH")=1 I 'PSOBBC("INOK") S PSOBBC("DFLG")=1 G PTX
 D:PSOBBC1("FROM")="NEW" COPAY^PSOPTPST
 D PROFILE^PSORX
PTX K PSOPTPST,PSOBBC("DONE")
 W:PSOBBC("DFLG") !!,*7,"Rx not filled"
 Q
 ;
REFILL ;
 I $P(%APSITE,U,15)="Y",$G(VEXRX) D ^APSPCCV  ;cmi/maw 09/09/02 auto ref
 ;N PSOFROM S PSOFROM="REFILL" ;IHS/ITSC/ENM 01/21/03
 I '$G(VEXRX) N PSOFROM S PSOFROM="REFILL"  ;cmi/maw new for auto ref
 D EN^PSOREF0(.PSOBBC)
 Q
REFILLX ;
 Q
 ;
NEW ;
 ;N PSOFROM S PSOFROM="NEW"  ;IHS/ITSC/ENM 01/21/03
 I '$G(VEXRX) N PSOFROM S PSOFROM="NEW"  ;cmi/maw 11/18/02 NEW FOR AUTO REF
 S PSOBBC("OIRXN")=PSOBBC("IRXN")
 S PSORNW("FILL DATE")=PSOBBC1("FILL DATE")
 D EN^PSORENW0(.PSOBBC)
 S PSOBBC("MAIL/WINDOW")=PSOBBC1("MAIL/WINDOW")
 S PSOBBC("EAOK")=PSOBBC1("EAOK")
 S PSOBBC("QS")=PSOBBC1("QS")
 S PSOBBC("INOK")=PSOBBC1("INOK")
 S:$G(PSOBBC1("CLERK CODE")) PSOBBC("CLERK CODE")=PSOBBC1("CLERK CODE")
 S:$G(PSOBBC1("EXPIRATION DATE")) PSOBBC("EXPIRATION DATE")=PSOBBC1("EXPIRATION DATE")
 K PSORNW
 Q
 ;
EOJ ;
 K PSOBBC,PSOBBC1,Y,X
 Q
