PSOCST5 ;BHAM/ISC/SAB - PROVIDER BY DRUG COST  [ 03/01/2001  4:58 PM ]
 ;;6.0;OUTPATIENT PHARMACY;**3**;09/03/97
BEG W ! S %DT("A")="BEGINNING DATE: ",%DT="APE" D ^%DT G:"^"[X EX G:Y<0 BEG S (%DT(0),BEGDATE)=Y
EN W ! S %DT("A")="ENDING DATE: " D ^%DT G:"^"[X EX G:Y<0 EN S ENDDATE=Y
EN1 F G=0:0 W !,"Do you want to look at data concerning a specific provider" S %=1 D YN^DICN Q:%  I %Y["?" D YN^PSOUTLA G EN1
 G:%=-1 EN1 I %=2 S IFN=0 G DEV
 S DIC("S")="I $G(^VA(200,+Y,""PS""))]""""",DIC(0)="AEQM",DIC="^VA(200,",DIC("A")="Select Provider: " D ^DIC K DIC G:Y<0 EX S IFN=1,PHY=+Y
DEV K %ZIS,IOP,POP,ZTSK S %ZIS("B")="",PSOION=ION,%ZIS="QM" D ^%ZIS K %ZIS I POP S IOP=PSOION D ^%ZIS K POP,PSOION G EX
 ;I $E(IOST)["C"!($G(IOM)<132) W *7,!!,"PRINTOUT MUST BE SENT TO A 132 COLUMNS PRINTER !!",!! G DEV ;IHS/ASDS/ENM 03/01/2001
 K PSOION I $D(IO("Q")) S ZTDESC="PROVIDER BY DRUG COST",ZTRTN="START^PSOCST5" F G="BEGDATE","ENDDATE","IFN","PHY" S:$D(@G) ZTSAVE(G)=""
 I  K IO("Q") D ^%ZTLOAD W:$D(ZTSK) !,"REPORT QUEUED TO PRINT !!",! K ZTSK G EX
START U IO K ^TMP($J) S PAGE=1 F PSDT=(BEGDATE-1):0:ENDDATE S PSDT=$O(^PSCST(PSDT)) Q:'PSDT!(PSDT>ENDDATE)  D @$S('IFN:"PHY",1:"DRUG")
 S (CNT,CNTO,CNTR,COST)=0,PHY="" F I=0:0 S PHY=$O(^TMP($J,PHY)) Q:PHY=""  D HD S DRUGX="" F G=0:0 S DRUGX=$O(^TMP($J,PHY,DRUGX)) D:DRUGX="" SUB Q:DRUGX=""  D PRT3
EX W ! W:$E(IOST)'["C" @IOF D ^%ZISC K ^TMP($J),%ZIS,%,AVG,BEGDATE,CNT,CNTO,CNTR,COST,DIC,DRUG,DRUGX,ENDDATE,FILLS,I,IFN,%Y,PAGE,PHY,PHYX,PSDT,G,UTL,X,Y,%DT,ZTRTN,ZTDESC S:$D(ZTQUEUED) ZTREQ="@"
 Q
PRT3 D HD:($Y+4)>IOSL S Y=^TMP($J,PHY,DRUGX),FILLS=($P(Y,"^",2)+$P(Y,"^",3)),CNT=CNT+FILLS,CNTO=CNTO+$P(Y,"^",2),CNTR=CNTR+$P(Y,"^",3),COST=COST+$P(Y,"^",4)
 W !,DRUGX,?50,$J($P(Y,"^",2),6),?57,$J($P(Y,"^",3),6),?66,$J(FILLS,6),?75,$J($P(Y,"^",4),10,2),?91 S AVG=$S(FILLS=0:0,1:($P(Y,"^",4)/FILLS)) W $J(AVG,10,2)
 Q
PHY F PHY=0:0 S PHY=$O(^PSCST(PSDT,"P",PHY)) Q:'PHY  D DRUG
 Q
DRUG F DRUG=0:0 S DRUG=$O(^PSCST(PSDT,"P",PHY,"D",DRUG)) Q:'DRUG  I $D(^(DRUG,0)) S X=^(0) D STORE
 Q
STORE S PHYX=$S($D(^VA(200,+PHY,0)):$P(^(0),"^"),1:"UNKNOWN")
 Q:'$D(^PSDRUG(DRUG,0))  S DRUGX=$P(^(0),"^") S:'$D(^TMP($J,PHYX,DRUGX)) ^TMP($J,PHYX,DRUGX)="^0^0^0"
 S UTL=^TMP($J,PHYX,DRUGX),^TMP($J,PHYX,DRUGX)="^"_($P(UTL,"^",2)+$P(X,"^",2))_"^"_($P(UTL,"^",3)+$P(X,"^",3))_"^"_($P(UTL,"^",4)+$P(X,"^",4))
 Q
HD I PAGE>1,$E(IOST)="C" W !!,*7,"(Enter ""^"" TO Halt) " R X:DTIME S:'$T X="^" G:X="^" EX
 W @IOF,!,"Drug Costs by Provider by Drug for the period: " S Y=BEGDATE D DT^DIO2 W " to " S Y=ENDDATE D DT^DIO2 W !,"RUN DATE: " S Y=DT D DT^DIO2 W ?88,"PAGE ",PAGE S PAGE=PAGE+1
 W !!,?51,"ORIGN",?57,"TOTAL",?80,"TOTAL",?93,"AVG COST",!,"DRUG",?51,"FILLS",?57,"REFILLS",?68,"FILLS",?80,"COST",?93,"per FILL"
 W ! F I=1:1:110 W "-"
 W !,?5,"PROVIDER: ",PHY
 Q
SUB D HD:($Y+2)>IOSL W !!,"TOTAL FOR ",PHY,?50,$J(CNTO,6),?57,$J(CNTR,6),?66,$J(CNT,6),?75,$J(COST,10,2),?91 S AVG=$S(CNT=0:0,1:(COST/CNT)) W $J(AVG,10,2)
 S (CNT,CNTO,CNTR,COST)=0
 Q
