PSODIR ;IHS/DSD/JCM - ASKS DATA FOR RX ORDER ENTRY  [ 01/13/2003  1:15 PM ]
 ;;6.0;OUTPATIENT PHARMACY;**3,4**;11/11/2002
 ;;6.0;OUTPATIENT PHARMACY;**55,64,94**;09/03/97
 ;MODIFIED DEFAULT PROVIDER IHS/OKCAO/POC 11/11/2002
 ;----------------------------------------------------------------
 ;
PROV(PSODIR) ;
PROVEN ; Entry point for failed lookup
 K DIC,X,Y
 I $G(PSODIR("PROVIDER"))]"" S PSODIR("OLD VAL")=PSODIR("PROVIDER")
 S DIC="^VA(200,",DIC(0)="QEAM",PSODIR("FIELD")=0
 S DIC("W")="W ""     "",$P(^(""PS""),""^"",9)"
 S DIC("A")="PROVIDER: ",DIC("S")="I $D(^(""PS"")),$P(^(""PS""),""^""),$S('$P(^(""PS""),""^"",4):1,1:$P(^(""PS""),""^"",4)'<DT)"
 S:$G(PSORX("PROVIDER NAME"))]"" DIC("B")=PSORX("PROVIDER NAME")
 I $G(DIC("B"))']""&($G(APSPX1("PROV"))]"") S DIC("B")=APSPX1("PROV")  ;DEFAULT PROVIDER
 I '$D(DIC("B"))&($G(^DISV($G(DUZ),"RX"))]"") S DIC("B")=$P($G(^VA(200,^DISV(DUZ,"RX"),0)),U,1)  ;TO DEFAULT TO BEFORE THIS SESSION IHS/OKCAO/POC 10/24/2002
 D ^DIC K DIC
 I X[U,$L(X)>1 D JUMP G PROVX
 I $D(DTOUT)!$D(DUOUT) S PSODIR("DFLG")=1 G PROVX
 I Y=-1 G PROVEN
 S ^DISV($G(DUZ),"RX")=+Y  ;TRICKY USED ABOVE FOR DEFAULT VALUE IHS/OKCAO/POC 10/24/2002
 ;I $P($G(^PSDRUG($S($G(PSODRUG("IEN")):PSODRUG("IEN"),1:PSORENW("DRUG IEN")),"CLOZ1")),"^")="PSOCLO1",$P(^VA(200,+Y,"PS"),"^",2)'?2U7N D  K Y,PSORX("PROVIDER NAME"),DIC("B") G PROVEN ;IHS/OKCAO/POC FAST OPTION ???? DELETE THIS
 ;.W *7,!!,"Only providers with DEA numbers can write prescriptions for clozaril.",!
 S PSODIR("PROVIDER")=+Y,APSPX1("PROV")=$P(Y,"^",2)  ;IHS/DSD/ENM 12/21/95
 S (PSODIR("PROVIDER NAME"),PSORX("PROVIDER NAME"))=$P(Y,"^",2)
 I $G(PSODIR("OLD VAL"))'=+Y K PSODIR("GENERIC PROVIDER"),PSODIR("COSIGNING PROVIDER")
 I $G(PSODIR("OLD VAL"))'=$G(PSODIR("PROVIDER")),$P(Y,"^",2)="PROVIDER,OTHER"!($P(Y,"^",2)="PROVIDER,OUTSIDE") D GENERIC
 I $G(PSODIR("OLD VAL"))'=$G(PSODIR("PROVIDER")),$P(^VA(200,PSODIR("PROVIDER"),"PS"),"^",7) D COSIGN
PROVX K X,Y
 Q
 ;
GENERIC ;
 K DIR,DIC,PSODIR("GENERIC PROVIDER")
 S DIR(0)="52,30"
 D DIR G:PSODIR("DFLG")!PSODIR("FIELD") GENERICX
 S PSODIR("GENERIC PROVIDER")=Y
GENERICX K X,Y
 Q
 ;
COSIGN ;
 K DIC,PSODIR("COSIGNING PROVIDER")
 S DIC(0)="QEAM",DIC="^VA(200,",DIC("B")=$P(^VA(200,PSODIR("PROVIDER"),"PS"),"^",8)
 S DIC("S")="I $D(^(""PS"")),$P(^(""PS""),""^""),$S('$P(^(""PS""),""^"",4):1,1:$P(^(""PS""),""^"",4)'<DT)"
 S DIC("W")="W ""     "",$P(^(""PS""),""^"",9)",DIC("S")=DIC("S")_",'$P(^(""PS""),""^"",7)"
 S DIC("A")="COSIGNING PROVIDER: " D ^DIC K DIC
 I $D(DTOUT)!$D(DUOUT) S PSODIR("DFLG")=1 G COSIGNX
 S:+Y>0 PSODIR("COSIGNING PROVIDER")=+Y G:Y<0 COSIGN
COSIGNX K X,Y
 Q
 ;
DIR ;
 S PSODIR("FIELD")=0
 G:$G(DIR(0))']"" DIRX
 D ^DIR K DIR,DIE,DIC,DA
 I $D(DUOUT)!($D(DTOUT))!($D(DIROUT)),$L($G(X))'>1 S PSODIR("DFLG")=1 G DIRX
 I X[U,$L(X)>1 D JUMP
DIRX K DIRUT,DTOUT,DUOUT,DIROUT,PSOX
 Q
 ;
JUMP ;
 S X=$P(X,"^",2),DIC="^DD(52,",DIC(0)="QM" D ^DIC K DIC
 I Y=-1 S PSODIR("FIELD")=PSODIR("FLD") G JUMPX
 I $G(PSONEW1)=0 D JUMP^PSONEW1 G JUMPX
 I $G(PSOREF1)=0 D JUMP^PSOREF1 G JUMPX
 I $G(PSONEW3)=0 D JUMP^PSONEW3 G JUMPX
 I $G(PSORENW3)=0 D JUMP^PSORENW3 G JUMPX
JUMPX S X="^"_X
 Q
