PSODIR2(PSODIR) ;IHS/DSD/JCM - RX ORDER ENTRY CONTD  [ 01/13/2003  1:50 PM ]
 ;;6.0;OUTPATIENT PHARMACY;**1,3,4**;09/03/97
 ;;6.0;OUTPATIENT PHARMACY;**21,79,94,115,136**;09/03/97
 ;---------------------------------------------------------------------
 ;
EXP(PSODIR) ;
 ;IHS/DSD/ENM 09-28-94 DISABLE EXP DATE (PSG REQ) NOW SET IN APSPMAN
 ;K DIR,DIC
 ;I $G(PSODRUG("EXPIRATION DATE"))]"" S Y=PSODRUG("EXPIRATION DATE") X ^DD("DD") S PSORX("EXPIRATION DATE")=Y
 ;S DIR("A")="EXPIRES",DIR("B")=$S($G(PSORX("EXPIRATION DATE"))]"":PSORX("EXPIRATION DATE"),1:"T+6M")
 ;S DIR(0)="D^NOW::EX"
 ;S DIR("?")="Both the month and date are required."
 ;D DIR G:PSODIR("DFLG")!PSODIR("FIELD") EXPX
 ;D NOW^%DTC S X1=X,X2=182 D C^%DTC S PSODIR("EXPIRATION DATE")=X
 ;S PSODIR("EXPIRATION DATE")=Y
EXPX ;K X,Y
 Q
 ;
CLINIC(PSODIR) ;
 K DIR,DIC S PSODIR("FIELD")=0
 S DIC=44,DIC(0)="AEQM",DIC("A")="CLINIC: ",DIC("S")="I '$P($G(^(""SL"")),""^"",5)" S:$G(PSORX("CLINIC"))]"" DIC("B")=PSORX("CLINIC") D ^DIC
 S PSODIR("FIELD")=0 D DIRS G:PSODIR("DFLG")!PSODIR("FIELD") CLINICX  ;IHS/OKCAO/POC 8/18/2000 COMMENT OUT NEXT TWO LINES
 ;I $G(PSOFROM)="FAST" S:$D(DUOUT) PSODIR("DFLG")=1  ;WANT TO DELETE IF PUT IN UPARROW IHS/OKCAO/POC FAST OPTION 8/18/2000
 ;G:PSODIR("DFLG")!PSODIR("FIELD") CLINICX
 I +Y>0 S PSODIR("CLINIC")=+Y,PSORX("CLINIC")=$P(Y,"^",2)
 E  S PSORX("CLINIC")=""
CLINICX K X,Y,PSOX,DIC ;P136
 Q
 ;
MW(PSODIR) ;IHS/DSD/ENM 09/28/94 next three lines added to set 'window pickup' variable
 S PSODIR("MAIL/WINDOW")="W",PSORX("MAIL/WINDOW")="WINDOW"
 S (PSODIR("METHOD OF PICK-UP"),PSORX("METHOD OF PICK-UP"))=""
 Q
 K DIR,DIC
 S DIR(0)="52,11"
 S DIR("B")=$S($G(PSORX("MAIL/WINDOW"))]"":PSORX("MAIL/WINDOW"),1:"WINDOW")
 D DIR G:PSODIR("DFLG")!PSODIR("FIELD") MWX
 I $G(Y(0))']"" S PSODIR("DFLG")=1 G MWX
 S PSODIR("MAIL/WINDOW")=Y,PSORX("MAIL/WINDOW")=Y(0)
 I $G(PSORX("EDIT"))]"",PSODIR("MAIL/WINDOW")'="W" K PSODIR("METHOD OF PICK-UP")
MW1 G:PSODIR("MAIL/WINDOW")'="W"!('$P($G(PSOPAR),"^",12)) MWX
 S DIR(0)="52,35O"
 S:$G(PSORX("METHOD OF PICK-UP"))]"" DIR("B")=PSORX("METHOD OF PICK-UP")
 D DIR G:PSODIR("DFLG") MWX
 I X[U W !,"Cannot jump to another field ..",! G MW1
 S (PSODIR("METHOD OF PICK-UP"),PSORX("METHOD OF PICK-UP"))=Y
MWX K X,Y
 Q
 ;
RMK(PSODIR) ;
RMKEN K DIR,DIC
 S DIR(0)="52,12"
 S:$G(PSODIR("REMARKS"))]"" DIR("B")=PSODIR("REMARKS")
 D DIR G:PSODIR("DFLG") RMKX
 I X[U W !,"Cannot jump to another field ..",! G RMKEN
 S:$L(X)>0 PSODIR("REMARKS")=X  ;P136
RMKX K X,Y
 Q
 ;
TRIP(PSODIR)  ;TRIPLICATE FOR SCHEDULE TWO DRUGS IHS/OKCAO/POC 11/20/2002
 Q:$G(PSODRUG("DEA"))'["2"  ;MUST BE A SCHEDULE TWO DRUG!
TRIP1 K DIR,DIC
 ;S DIR(0)="52,9999999.13"
 S DIR(0)="52,9999999.14"  ;LISA
 S:$G(PSODIR("TRIP"))]"" DIR("B")=PSODIR("TRIP")
 ;D DIR G:PSODIR("DFLG") TRIPX
 D DIR G:PSODIR("DFLG")!PSODIR("FIELD") TRIPX
 ;I X[U W !,"Cannot jump to another field ..",! G TRIP1
 S:$L(X)>0 PSODIR("TRIP")=X
TRIPX K X,Y
 Q
 ;
ISSDT(PSODIR) ;
 K DIR,DIC
 ;S DIR("A")="ISSUE DATE",DIR("B")=$S($G(PSORX("ISSUE DATE"))]"":PSORX("ISSUE DATE"),1:"TODAY")
 ;S DIR(0)="52,1"
 ;D DIR G:PSODIR("DFLG")!PSODIR("FIELD") ISSDTX
 ;S PSODIR("ISSUE DATE")=Y
 ;X ^DD("DD") S PSORX("ISSUE DATE")=Y
 ;IHS/DSD/ENM/POC 01/16/98 NEXT 8 LINES ADDED TO BRING BACK ENCOUNTER DT
ISS ;S DIR(0)=$S('$P(%APSITE,U,36):"D^:DT:EX",1:"D^:DT:ET"),DIR("A")=$S('$P(%APSITE,U,36):"ISSUE DATE",1:"ENCOUNTER FORM DATE & TIME")
 S DIR(0)=$S('$P(%APSITE,U,36):"D^:DT:EX",1:"D^:-NOW:ET"),DIR("A")=$S('$P(%APSITE,U,36):"ISSUE DATE",1:"ISSUE/ENCOUNTER FORM DATE & TIME")
 I '$D(APSEFDT) S DIR("B")=$S('$P(%APSITE,U,36):"TODAY",1:"")
 I $D(APSEFDT) S Y=APSEFDT X ^DD("DD") S APSEFDT=Y,DIR("B")=APSEFDT
 S (PSONEW("FIELD"),PSORENW("FIELD"))=0  ;IHS/DSD/ENM/POC TO STOP LOOPING
 D ^DIR G:PSODIR("DFLG")!PSODIR("FIELD") ISSDTX
 S APSEDT=Y,PSODIR("ISSUE DATE")=Y\1
 X ^DD("DD") S PSORX("ISSUE DATE")=Y
 ;COULD COMMENT OUT THE NEXT LINE TO ALLOW BACK RXING BEYOND 180 DAYS IHS/OKCAO/POC
 S APSE=PSODIR("ISSUE DATE"),X1=DT,X2=-180 D C^%DTC I APSE<X W !?4,*7,$S('$P(%APSITE,U,36):"ISSUE DATE",1:"ISSUE/ENCOUNTER FORM DATE")," CANNOT BE MORE THAN 180 DAYS IN THE PAST!" K APSE G ISS  ; IHS IHS/OKCAO/POC 9/3/99
 S APSEFDT=APSEDT  ;IHS/DSD/ENM 08/13/97 USE THIS VAR TO PASS TO PCC
ISSDTX K X,Y,APSE,APSEDT
 Q
 ;
FILLDT(PSODIR) ;
 K DIR,DIC
 ;S DIR("A")="FILL DATE",DIR("B")=$S($G(PSORX("FILL DATE"))]"":PSORX("FILL DATE"),1:"TODAY")  ;IHS/DSD/ENM 08/14/97
 ;S DIR(0)="D^"_$S($G(PSODIR("ISSUE DATE"))]"":PSODIR("ISSUE DATE"),1:DT)_$S($G(DUZ("AG"))="I":":"_DT_":EX",1:"::EX")
 ;IHS/DSD/ENM LINES 5/19/95 ^v 6Mo DATE RANGE DISABLED PER PSG
 ;IHS/DSD/ENM 08/14/97 NEXT 7 LINES REPLACED FOR ENCOUNTER DATE CODE
 ;S DIR(0)="D^::EX"  ;IHS/DSD/ENM 11/29/96
 ;S DIR("?",1)="The earliest fill date allowed is determined by the ISSUE DATE,"
 ;S DIR("?",2)="the FILL DATE cannot be before the ISSUE DATE."
 ;S DIR("?")="Both the month and date are required."
 ;D DIR G:PSODIR("DFLG")!PSODIR("FIELD") FILLDTX
 ;S PSODIR("FILL DATE")=Y,APSPRFD=Y ;IHS/DSD/ENM 3/17/94
FIL ;X ^DD("DD") S PSORX("FILL DATE")=Y
 S DIR(0)=$S('$P(%APSITE,U,36):"D^:DT:EX",1:"D^:-NOW:ET"),DIR("A")=$S('$P(%APSITE,U,36):"FILL DATE",1:"FILL/ENCOUNTER FORM DATE & TIME")  ;IHS/DSD/ENM/POC DT ADDED TO PREV FUTURE DT
 I $G(APSRNEW)=1 S DIR("A")="FILL DATE"
 I '$D(APSEFDT) S DIR("B")=$S('$P(%APSITE,U,36):"TODAY",1:"")
 I $D(APSEFDT) S Y=APSEFDT X ^DD("DD") S APSEFDT=Y,DIR("B")=APSEFDT
 ;S (PSONEW("FIELD"),PSORENW("FIELD"))=0 ;IHS/DSD/ENM/POC TO STOP LOOPING
 S (PSOREF("FIELD"),PSONEW("FIELD"),PSORENW("FIELD"))=0  ;IHS/DSD/ENM/POC TO STOP LOOPING IHS/OKCAO/POC 8/18/2000
 ;S PSORENW("FILL DATE") POSSIBLE FIX FOR NEXT LINE IHS/DSD/ENM 11/28/97
 ;D ^DIR G:PSODIR("DFLG")!PSODIR("FIELD") FILLDTX
 D ^DIR G:PSODIR("DFLG")!PSODIR("FIELD") FILLDTX
 S APSEDT=Y,PSODIR("FILL DATE")=Y\1
 X ^DD("DD") S PSORX("FILL DATE")=Y
 S APSE=PSODIR("FILL DATE"),X1=DT,X2=-180 D C^%DTC I APSE<X W !?4,*7,$S('$P(%APSITE,U,36):"FILL DATE",1:"FILL/ENCOUNTER FORM DATE")," CANNOT BE MORE THAN 180 DAYS IN THE PAST!" K APSE G FIL  ; IHS
 S APSEFDT=APSEDT  ;IHS/DSD/ENM 08/14/97 USE THIS VAR TO PASS TO PCC
FILLDTX K X,Y,APSE,APSEDT,APSRNEW
 Q
 ;
CLERK(PSODIR) ;
 I $G(DUZ("AG"))'="I",$G(DUZ) S PSODIR("CLERK CODE")=DUZ,PSORX("CLERK CODE")=$P($G(^VA(200,DUZ,0)),"^") G CLERKX
 K DIR,DIC
 S DIR("A")="CLERK",DIR("B")=$S($G(PSORX("CLERK CODE"))]"":PSORX("CLERK CODE"),1:$P($G(^VA(200,DUZ,0)),"^",1)),DIR(0)="52,16"  ;IHS/DSD/ENM "B" CHG TO NAME INSTEAD OF INITIALS
 D DIR G:PSODIR("DFLG")!PSODIR("FIELD") CLERKX
 ;S PSODIR("CLERK CODE")=+Y,PSORX("CLERK CODE")=$P(Y,"^")
 S PSODIR("CLERK CODE")=+Y,PSORX("CLERK CODE")=$P(Y,"^",2)  ;IHS/DSD/ENM 9/27/94
CLERKX Q
 ;
DIR ;
 S PSODIR("FIELD")=0
 G:$G(DIR(0))']"" DIRX
 D ^DIR K DIR,DIE,DIC,DA
DIRS I $D(DUOUT)!($D(DTOUT))!($D(DIROUT)),$L($G(X))'>1 S PSODIR("DFLG")=1 G DIRX  ;DIRS IS A SPECIAL ENTRY POINT 8/18/2000 IHS/OKCAO/POC 
 I $D(DUOUT)!($D(DTOUT))!($D(DIROUT)),$L($G(X))'>1!(Y="") S PSODIR("DFLG")=1 G DIRX
 I X[U,$L(X)>1 D JUMP
DIRX K DIRUT,DTOUT,DUOUT,DIROUT,PSOX
 Q
 ;
JUMP ;
 S X=$P(X,"^",2),DIC="^DD(52,",DIC(0)="QM" D ^DIC K DIC
 I Y=-1 S PSODIR("FIELD")=PSODIR("FLD") G JUMPX
 I $G(PSONEW1)=0 D JUMP^PSONEW1 G JUMPX
 I $G(PSOREF1)=0 D JUMP^PSOREF1 G JUMPX  ;IHS/OKCAO/POC 8/18/2000 SHOULD HAVE ALREADY BEEN HERE
 I $G(PSONEW3)=0 D JUMP^PSONEW3 G JUMPX
 I $G(PSORENW3)=0 D JUMP^PSORENW3 G JUMPX
 I $G(PSOREF2)=0 D JUMP^PSOREF2 G JUMPX  ;IHS/OKCAO/POC 8/18/2000
JUMPX S X="^"_X
 Q
