PSONEW2 ;IHS/DSD/JCM - DISPLAYS NEW RX INFORMATION FOR EDIT  [ 01/15/2003  10:27 AM ]
 ;;6.0;OUTPATIENT PHARMACY;**3,4**;11/11/2002
 ;;6.0;OUTPATIENT PHARMACY;**57,69,94**;09/03/97
 ;ACTUAL ACQUISTION COST FIELDS ADDED IHS/OKCAO/POC 11/11/2002
 ; This routine displays the entered new rx information and
 ; asks if correct, if not allows editing of the data.
 ;------------------------------------------------------------
EP ;IHS/DSD/ENM 10/7/95 EP TO CHECK FOR DUE QUESTIONNAIRE
 S APFLAG="N" D ^APSPQ
START ;
 S (PSONEW("DFLG"),PSONEW2("QFLG"))=0
 D DISPLAY ; Displays information
 D ASK G:PSONEW2("QFLG")!PSONEW("DFLG") END
 D EDIT
 G:'PSONEW("DFLG") START
END D EOJ
 Q
 ;------------------------------------------------------------
DISPLAY ;
 W !!,"Rx # ",PSONEW("RX #")
 W ?23,$E(PSONEW("FILL DATE"),4,5),"/",$E(PSONEW("FILL DATE"),6,7),"/",$E(PSONEW("FILL DATE"),2,3)
 ;W !,$G(PSORX("NAME")),?30,"#",PSONEW("QTY")
 W !,$G(PSORX("NAME")),?30,"#",PSONEW("QTY"),?45,"NDC ",$S($G(PSONEW("NDC"))]"":PSONEW("NDC"),1:$G(PSODRUG("NDC")))  ;NOTE IF NDC FIELD TURNED OFF WITH PSONDC THEN USE PSONEW("NDC") NOT DEFINED IHS/OKCAO/POC 8/18/2000
 ;W " ("_$S($G(PSONEW("AWP"))]"":PSONEW("AWP"),1:$G(PSODRUG("AWP")))_")" ;SAME AS ABOVE 8/18/2000
 I ('$D(IOBON))!('$D(IOBOFF)) S X="IOBON;IOBOFF" D ENDR^%ZISS  ;IHS/OKCAO/POC 8/18/2000
 W " ("_$S($G(PSONEW("AWP"))]"":PSONEW("AWP"),$G(PSODRUG("AWP"))]"":PSODRUG("AWP"),1:IOBON_"NO AWP"_IOBOFF)_")"  ;SAME AS ABOVE FOR NDC IHS/OKCAO/POC 8/18/2000
 W " ("_$S($G(PSONEW("COST"))]"":PSONEW("COST"),$G(PSODRUG("COST"))]"":PSODRUG("COST"),1:IOBON_"NO COST"_IOBOFF)_")"  ;SAME AS ABOVE FOR AWP IHS/OKCAO/POC 8/18/2000 1/21/2001 IMPROVE COST
 W:$G(PSONEW("TRIP"))]"" " TRIPLICATE SERIAL # "_PSONEW("TRIP")  ;IHS/OKCAO/POC TRIPLICATE 12/10/2002
 S X=PSONEW("SIG") D SIGONE^PSOHELP W !,$G(SIG),!!,$S($G(PSODRUG("TRADE NAME"))]"":PSODRUG("TRADE NAME"),1:PSODRUG("NAME"))
 W !,PSONEW("PROVIDER NAME"),?25,PSORX("CLERK CODE")
 W !,"# of Refills: ",PSONEW("# OF REFILLS")
 I ((APSPMAN=1)!(APSPMAN=2)) S APSPDZ=PSONEW("EXPIRATION DATE")  ;IHS/DSD/ENM 8/18/2000 IHS/OKCAO/POC
 I APSPMAN=1 W !,"Drug Mfg: ",PSONEW("MANUFACTURER"),?35,"Exp Date: ",$E(APSPDZ,4,5)_"/"_$E(APSPDZ,2,3),?55,"Lot #: ",PSONEW("LOT #"),! Q  ;IHS/DSD/ENM 1/6/95
 I APSPMAN=2 W !,?35,"Exp Date: ",$E(APSPDZ,4,5)_"/"_$E(APSPDZ,2,3),! Q  ;IHS/DSD/ENM 1/22/96
 Q
 ;
ASK ;
 K DIR,X,Y
 S DIR("A")="Is this correct"
 S DIR(0)="Y",DIR("B")="YES"
 D ^DIR K DIR
 I $D(DIRUT) S PSONEW("DFLG")=1 G ASKX
 I Y S PSONEW2("QFLG")=1
ASKX K X,Y,DIRUT,DTOUT,DUOUT
 W !
 Q
 ;
EDIT ;
 S PSORX("EDIT")=1
 D ^PSONEW3
 S PSONEW("DFLG")=$S($G(PSORX("DFLG")):1,1:0)
 Q
 ;
EOJ ;
 K PSONEW2,PSORX("EDIT"),PSORX("DFLG")
 Q
 ;
EN1(PSONEW2) ; Entry point to just display and ask if okay
 S PSONEW("DFLG")=0
 S:$G(PSONEW2("NDC"))]"" PSONEW("NDC")=PSONEW2("NDC")  ;IHS/OKCAO/POC 8/18/2000 IN CASE COMING FROM PSORXED
 S:$G(PSONEW2("AWP"))]"" PSONEW("AWP")=PSONEW2("AWP")  ;IHS/OKCAO/POC 8/18/2000 IN CASE COMING FROM PSORXED
 S:$G(PSONEW2("COST"))]"" PSONEW("COST")=PSONEW2("COST")  ;IHS/OKCAO/POC 1/21/2001 DRUG IMPROVE
 I $G(^PSRX(PSONEW2("IRXN"),0))']"" S PSONEW("DFLG")=1 G EN1X
 S PSOX=^PSRX(PSONEW2("IRXN"),0),PSONEW("TRADE NAME")=$G(^("TN")),PSONEW("FILL DATE")=$P($G(^(2)),"^",2)
 S PSONEW("RX #")=$P(PSOX,"^"),PSORX("NAME")=$P(^DPT($P(PSOX,"^",2),0),"^")
 S PSONEW("QTY")=$P(PSOX,"^",7),PSODRUG("NAME")=$P(^PSDRUG($P(PSOX,"^",6),0),"^"),PSONEW("# OF REFILLS")=$P(PSOX,"^",9)
 I $P(PSOX,"^",16)?1N.N S PSORX("CLERK CODE")=$P(^VA(200,$P(PSOX,"^",16),0),"^")  ;IHS/DSD/ENM 08/16/96
 I $P(PSOX,"^",16)?1A.A S PSORX("CLERK CODE")=$P(^VA(200,DUZ,0),"^"),$P(PSOX,"^",16)=DUZ,$P(PSORXED("RX0"),"^",16)=DUZ  ;IHS/DSD/ENM 08/16/96
 S:$G(PSONEW("PROVIDER NAME"))="" PSONEW("PROVIDER NAME")=$P(^VA(200,$P(PSOX,"^",4),0),"^")
 S PSONEW("SIG")=$P(PSOX,"^",10)
 D DISPLAY
 D ASK
 I PSONEW("DFLG")=1 S PSONEW2("DFLG")=1
EN1X K PSOX,PSONEW,PSORX("NAME"),PSODRUG,PSORX("CLERK CODE")
 Q
