PSON52 ;IHS/DSD/JCM - FILES NEW ENTRIES IN PRESCRIPTION FILE  [ 05/07/2003  1:06 PM ]
 ;;6.0;OUTPATIENT PHARMACY;**3,4**;11/11/2002
 ;;6.0;OUTPATIENT PHARMACY;**22,34**;09/03/97
 ;ADD STUFF FOR ACTUAL ACQUISTION COST IHS/OKCAO/POC 11/11/2002
 ; This routine is responsible for the actual
 ; filing of the new prescription.
 ;
 ;IHS/SD/lwj 6/24/03 (patch 4) new logic for POS DUR value
 ;---------------------------------------------------------   
EN(PSOX) ;Entry Point
START ;
 D:$D(XRTL) T0^%ZOSV ; Start RT Monitor
 D INIT G:PSON52("QFLG") END
 D NFILE
 D PS55
 D DIK
 S:$D(XRT0) XRTN=$T(+0) D:$D(XRT0) T1^%ZOSV ; Stop RT Monitor
 D FINISH
 I $P($G(^PS(53,+$P(^PSRX(PSOX("IRXN"),0),"^",3),0)),"^",7)'=1,$G(DUZ("AG"))="V" S PSOFLAG=1 D COPAY^PSOCPB
 I $P(^PSRX(PSOX("IRXN"),0),"^",11)="W",$G(^("IB")) S ^PSRX("ACP",$P(^PSRX(PSOX("IRXN"),0),"^",2),$P(^(2),"^",2),0,PSOX("IRXN"))=""
 S X="APSQCK" X ^%ZOSF("TEST") I $T S NFRXIEN=PSOX("IRXN") D RXSET^APSQCK  ;IHS/OKCAO/POC 9/28/98
END D EOJ
 Q
 ;---------------------------------------------------------
 ;
INIT ;
 K X,%DT
 S PSON52("QFLG")=0
 S X1=PSOX("ISSUE DATE"),X2=PSOX("DAYS SUPPLY")*(PSOX("# OF REFILLS")+1)\1
 S X2=$S(PSOX("DAYS SUPPLY")=X2:X2,X2<181:184,X2=360:366,1:X2)
 D C^%DTC
 S PSOX("STOP DATE")=$P(X,".") K X
 I PSOX("# OF REFILLS")>0 S X1=PSOX("FILL DATE"),X2=$S((PSOX("DAYS SUPPLY")-10\1)<1:1,1:PSOX("DAYS SUPPLY")-10\1) D C^%DTC S PSOX("NEXT POSSIBLE REFILL")=$P(X,".") K X
 S PSOX("TYPE OF RX")=0,PSOX("DISPENSED DATE")=PSOX("FILL DATE")
 D NOW^%DTC
 S PSOX("LOGIN DATE")=% K %,X
 S PSOX("STATUS")=$S($G(PSOX("STATUS"))]"":PSOX("STATUS"),$D(PSORX("VERIFY")):1,1:0)
 S PSOX("COPIES")=$S($G(PSOX("COPIES"))]"":PSOX("COPIES"),1:1)
 I $G(PSORX("PHARM"))]"" S PSOX("PHARMACIST")=PSORX("PHARM") K PSORX("PHARM")
 ;I PSODRUG("IEN") S PSOX("AWP")=$S($D(^PSDRUG(PSODRUG("IEN"),999999931)):$P(^(999999931),U,2),1:"")  ;GETTING READY FOR AWP TO BE FILED IHS/OKCAO/POC 11/12/98
 ;I '$D(PSOX("AWP")),PSODRUG("IEN") S PSOX("AWP")=$S($D(^PSDRUG(PSODRUG("IEN"),999999931)):$P(^(999999931),U,2),1:"") ;GETTING READY FOR AWP TO BE FILED IHS/OKCAO/POC 8/18/2000 XXXX
 ;I $G(PSORX("PATIENT STATUS"))]"" D  ;12/21/2001 DON'T NEED THIS NOW THIS IS A NASTY PROBLEM WITH PATIENT STATUS NOT DEFINED NOW DONE IN PSONEW1
 ;.N DIC
 ;.S DIC=53,X=PSORX("PATIENT STATUS"),DIC(0)="MNO"
 ;.D ^DIC
 ;.I Y>0 S PSOX("PATIENT STATUS")=+Y
 ;END OF CHANGES IHS/OKCAO/POC 8/18/2000
INITX Q
 ;
NFILE ;     
 S DIC="^PSRX(",DLAYGO=52,DIC(0)="L",X=PSOX("RX #")
 K DD,DO
 D FILE^DICN S PSOX("IRXN")=+Y K DLAYGO,X,Y,DIC D:+$G(DGI) TECH^PSODGDGI
 L +^PSRX(PSOX("IRXN"))
 F PSOX1=0:1 S PSON52=$P($T(DD+PSOX1),";;",2,4) Q:PSON52=""  K PSOY S PSOY=$P(PSON52,";;") I $D(@PSOY) S $P(PSON52(PSOX("IRXN"),$P(PSON52,";;",2)),"^",$P(PSON52,";;",3))=@PSOY
 K PSOX1,PSOY
 S PSOX1="" F  S PSOX1=$O(PSON52(PSOX("IRXN"),PSOX1)) Q:PSOX1=""  S ^PSRX(PSOX("IRXN"),PSOX1)=$G(PSON52(PSOX("IRXN"),PSOX1))
 K PSOX1
 L -^PSRX(PSOX("IRXN"))  ;IHS/DSD/ENM 06/19/97
 Q
 ;
PS55 ;
 L +^PS(55,PSODFN,"P")
 S:'$D(^PS(55,PSODFN,"P",0)) ^(0)="^55.03PA^^"
 F PSOX1=$P(^PS(55,PSODFN,"P",0),"^",3):1 Q:'$D(^PS(55,PSODFN,"P",PSOX1))
 S PSOX("55 IEN")=PSOX1
 S ^PS(55,PSODFN,"P",PSOX1,0)=PSOX("IRXN"),$P(^PS(55,PSODFN,"P",0),"^",3,4)=PSOX1_"^"_($P(^PS(55,PSODFN,"P",0),"^",4)+1)
 S ^PS(55,PSODFN,"P","A",PSONEW("STOP DATE"),PSOX("IRXN"))=""
PS55X L -^PS(55,PSODFN,"P")
 K PSOX1
 Q
 ;
DIK ;
 K DIK,DA
 S DIK="^PSRX(",DA=PSOX("IRXN") D IX1^DIK K DIK,DA
 Q
 ;
FINISH ;
ANQ I $G(ANQDATA)]"" L +^PS(52.52) D NOW^%DTC G:$D(^PS(52.52,"B",%)) ANQ D
 . K DD,DO S DIC="^PS(52.52,",DIC(0)="L",DLAYGO=52.52,X=% D FILE^DICN K DIC
 . K LAYGO
 . S ^PS(52.52,+Y,0)=$P(Y,"^",2)_"^"_PSOX("IRXN")_"^"_ANQDATA
 . S ^PS(52.52,"A",PSOX("IRXN"),+Y)=""
 . K ANQDATA,X,Y,% L -^PS(52.52)
 . Q
 G:PSOX("STATUS")=4 FINISHP
 I $D(PSORX("VERIFY")) D  G FINISHX
 . K DIC,DLAYGO,DINUM,DIADD,X,DD,DO
 . S DIC="^PS(52.4,",DLAYGO=52.4,DINUM=PSOX("IRXN"),DIC(0)="ML"
 . S X=PSOX("IRXN")
 . D FILE^DICN K DIC,DLAYGO,DINUM
 . S ^PS(52.4,PSOX("IRXN"),0)=PSOX("IRXN")_"^"_PSODFN_"^"_DUZ_"^"_"^"_$E(PSOX("LOGIN DATE"),1,7)_"^"_PSOX("IRXN")_"^"_PSOX("STOP DATE")
 . K DIK,DA
 . S DIK="^PS(52.4,",DA=PSOX("IRXN")
 . D IX^DIK K DIK,DA
 . Q
 ;
 I PSOX("FILL DATE")>DT,$P(PSOPAR,"^",6) D  G FINISHX
 . S DA=PSOX("IRXN")
 . D SUS^PSORXL K DA
 . Q
 ;
FINISHP I $G(PSORX("PSOL",1))']"" S PSORX("PSOL",1)=PSOX("IRXN")_"," G FINISHX
 F PSOX1=0:0 S PSOX1=$O(PSORX("PSOL",PSOX1)) Q:'PSOX1  S PSOX2=PSOX1
 I $L(PSORX("PSOL",PSOX2))+$L(PSOX("IRXN"))<220 S PSORX("PSOL",PSOX2)=PSORX("PSOL",PSOX2)_PSOX("IRXN")_","
 E  S PSORX("PSOL",PSOX2+1)=PSOX("IRXN")_","
FINISHX ; 
 K PSOX1,PSOX2
EOJ ;
 L -^PSRX(PSOX("IRXN")) ;IHS/DSD/ENM 06/19/97
 K PSON52
 Q
 ;..;;PSODRUG("MANUFACTURER");;2;;8 ;IHS/DSD/ENM 12/22/94 SAVE THIS IHS/OKCAO/POC 8/18/2000
 ;
 ;IHS/DSD/ENM 12/22/94 DD+5 'CM' ADDED
DD ;;PSOX("RX #");;0;;1
 ;;PSOX("ISSUE DATE");;0;;13
 ;;PSODFN;;0;;2
 ;;PSOX("PATIENT STATUS");;0;;3
 ;;PSOX("PROVIDER");;0;;4
 ;;PSOX("CM");;9999999;;2
 ;;PSOX("CLINIC");;0;;5
 ;;PSODRUG("IEN");;0;;6
 ;;PSODRUG("TRADE NAME");;TN;;1
 ;;PSOX("QTY");;0;;7
 ;;PSOX("DAYS SUPPLY");;0;;8
 ;;PSOX("# OF REFILLS");;0;;9
 ;;PSOX("SIG");;0;;10
 ;;PSOX("COPIES");;0;;18
 ;;PSOX("MAIL/WINDOW");;0;;11
 ;;PSOX("REMARKS");;3;;7
 ;;PSOX("CLERK CODE");;0;;16
 ;;PSODRUG("COST");;0;;17
 ;;PSOX("COST");;0;;17 ;IHS/OKCAO/POC 1/21/2001 IMPROVE COST
 ;;PSOSITE;;2;;9
 ;;PSOX("LOGIN DATE");;2;;1
 ;;PSOX("FILL DATE");;2;;2
 ;;PSOX("PHARMACIST");;2;;3
 ;;PSOX("LOT #");;2;;4
 ;;PSOX("DISPENSED DATE");;2;;5
 ;;PSOX("STOP DATE");;2;;6
 ;;PSODRUG("NDC");;2;;7
 ;;PSOX("NDC");;2;;7 ;IHS/OKCAO/POC 8/18/2000
 ;;PSOX("MANUFACTURER");;2;;8
 ;;PSOX("EXPIRATION DATE");;2;;11
 ;;PSOX("GENERIC PROVIDER");;2;;12
 ;;PSOX("RELEASED DATE/TIME");;2;;13
 ;;PSOX("METHOD OF PICK-UP");;MP;;1
 ;;PSOX("STATUS");;0;;15
 ;;PSOX("LAST DISPENSED DATE");;3;;1
 ;;PSOX("NEXT POSSIBLE REFILL");;3;;2
 ;;PSOX("COSIGNING PROVIDER");;3;;3
 ;;PSOX("TYPE OF RX");;TYPE;;1
 ;;PSOX("SAND");;SAND;;1
 ;;PSODRUG("AWP");;9999999;;6 ;IHS/OKCAO/POC 8/18/2000
 ;;PSOX("AWP");;9999999;;6 ;IHS/OKCAO/POC GETTING READY FOR AWP 11/12/98
 ;;PSOX("BST");;9999999;;7 ;IHS/OKCAO/POC BILLING STATUS 8/18/2000
 ;;PSOX("INSURER");;9999999;;12 ;IHS/OKCAO/POC INSURER INFO 8/18/2000
 ;;PSOX("DUR");;9999999;;13 ;IHS/SD/lwj DUR POS segment 6/24/2003
 ;;PSOX("TRIP");;9999999;;14  ;IHS/OKCAO/POC TRIPLICATE FIELD 11/20/2002LORI
