PSOPTPST ;IHS/DSD/JCM - POST PATIENT SELECTION ACTION  [ 05/15/2003  1:16 PM ]
 ;;6.0;OUTPATIENT PHARMACY;**1,2,4**;11/11/2002
 ;;6.0;OUTPATIENT PHARMACY;**27,35,74,73,121**;09/03/97
 ;DISPLAY SAFETY BOTTLE STATUS IHS/OKCAO/POC 11/11/2002
 ;---------------------------------------------------------
START ;
 S PSOQFLG=0
 D GET  ; Gets data from Patient file
 D DEAD G:PSOQFLG END  ; Checks to see if patient still alive
 G:$G(PSOFROM("PTLKUP"))']"" END  ; skips questions if not called by RX data entry
 D INP G:PSOQFLG END  ;Checks to see if inpatient and whether to continue
 D INSUR  ;IHS/ITSC/ENM/POC 05/15/03
 D CAP  ;DISPLAYS SAFETY CAP STATUS IHS/OKCAO/POC 11/8/2001
 D CNH G:PSOQFLG END  ; Checks to see if nursing home patient
 D ELIG  ; Checks elegibility
 D:$G(DUZ("AG"))="V" COPAY G:PSOQFLG END  ; Deals with copay
 D ADDRESS  ; Display address information
 D:$G(^PS(55,PSODFN,1))]"" REMARKS  ; Displays narrative about patient
END D RETURN,EOJ  ;IHS/OKCAO/POC 11/13/2001
 Q
 ;----------------------------------------------------------
GET ;
 K DIC,DR,DIQ
 S DIC=2,DA=PSODFN,DR=".1;.172;.351;.361;148",DIQ="PSOPTPST"
 D EN^DIQ1 K DIC,DA,DR,DIQ
 Q
 ;
DEAD ;
 I $G(PSOPTPST(2,PSODFN,.351))]"" S PSOQFLG=1 W !,*7,?10,"PATIENT DIED "_PSOPTPST(2,PSODFN,.351),!
 Q
 ;
INP ;
 I $G(PSOPTPST(2,PSODFN,.1))]"" S APSTAT=2 W !,*7,?10,"PATIENT IS AN INPATIENT ON WARD ",PSOPTPST(2,PSODFN,.1)," !!" D DIR  ;IHS/DSD/ENM 01/26/98
 ;IHS/DSD/ENM 02/12/99 NEXT LINE SETS STAT TO OUTPAT
 ;I $G(PSOPTPST(2,PSODFN,.1))="" S APSTAT=1 W !,*7,?10,"PATIENT IS AN OUTPATIENT",!
 I $G(PSOPTPST(2,PSODFN,.1))="" S APSTAT=1 W !,*7,?10,"PATIENT IS AN OUTPATIENT"  ;GET RID OF THE RETURN! IHS/OKCAO/POC 11/8/2001
 Q
 ;
CNH ;
 K PSORX("CNH")
 I $G(PSOPTPST(2,PSODFN,148))="YES" W !,*7,?10,"PATIENT IS IN A CONTRACT NURSING HOME !!" D DIR S:'PSOQFLG PSORX("CNH")=1
 Q
 ;
ELIG ;
 I $G(PSOPTPST(2,PSODFN,.361))]"",$G(PSOPTPST(2,PSODFN,.172))'="I" W !,"MAS ELIGIBILITY: ",PSOPTPST(2,PSODFN,.361)
 S DFN=PSODFN D RE^PSODEM
 Q
 ;
COPAY ;
 K PSOBILL,PSOCPAY S DFN=PSODFN
 S (X,PSOPTIB)=$P($G(^PS(59,+PSOSITE,"IB")),"^")_"^"_PSODFN ;D XTYPE^IBARX  ;IHS/DSD/ENM 05/28/96 IB CALL DISABLED, NOT USED BY IHS
 I '$D(^IBE(350.1,"ANEW",+PSOPTIB,1,1)) S PSOQFLG=1 D  K PSOPTIB Q
 .W *7,!!,"There is a problem with the IB SERVICE/SECTION entry in your Pharmacy Site File."
 .W !,"You will not be able to enter any new prescriptions until this is corrected!",!
 S (ACTYP,BL)="",(PSOBILL,PSOCPAY)=0
 I +Y=-1 W !,"ERROR IN COPAY ELIGIBILITY ENCOUNTERED." G COPAYX
COPAY1 S ACTYP=$O(Y(ACTYP)) G:'ACTYP COPAYX F III=0:0 S BL=$O(Y(ACTYP,BL)) Q:BL=""  I BL>0 S PSOBILL=BL,PSOCPAY=BL_"^"_Y(ACTYP,BL)
 G COPAY1
COPAYX K X,Y,ACTYP,BL,III
 Q
 ;
ADDRESS ;
 N DFN
 S (DA,DFN)=PSODFN D ADD^VADPT
 L +^DPT(DA):0 I '$T W !,"File currently being updated, please try again later!",! Q
 I +VAPA(10)'<DT W !!,*7,?2,">> TEMPORARY ADDRESS  ",$P(VAPA(9),"^",2)," - ",$P(VAPA(10),"^",2)," <<"
 I VAPA(1)="" W !,*7,"NO ADDRESS INFORMATION ..",! S DIE=2,DR="[PSO OUTPTA]" D ^DIE:$P($G(PSOPAR),"^",22) G ADDRESSX
 F PSOI=1:1:4 W:VAPA(PSOI)]"" !,?5,VAPA(PSOI)
 ;IHS/DSD/ENM 10/07/95 $G added to next L var VAPA(11)
 W "  ",$P(VAPA(5),"^",2)_"  "_$S($G(VAPA(11))]"":$P($G(VAPA(11)),"^",2),1:$G(VAPA(6)))
 I $P($G(PSOPAR),"^",22) K DIE,DR S DIE=2,DR="[PSO OUTPTA]" D ^DIE
 L -^DPT(DA)
ADDRESSX K DFN,PSOI,DA,DR
 Q
 ;
REMARKS ;
 S PSOX=$G(^PS(55,PSODFN,1))
 W !!,?5
 F PSOI=1:1 Q:$P(PSOX," ",PSOI,900)=""  W:$X>76 !,?5 W $P(PSOX," ",PSOI)," "
 K PSOX,PSOI
 Q
 ;
INSUR ;IHS/ITSC/ENM/POC 05/15/03
 ;INSURANCE INFO WAS IN PSODEM IHS/ITSC/ENM/POC 05/07/03
 ;ADD A LINE HERE TO INDICATE 3RD PARTY PATIENT
 ;IHS/OKCAO/POC/lwj  05/03/01  change blink & reverse to kernal commands
 S X="IORVON;IORVOFF;IOBON;IOBOFF" D ENDR^%ZISS  ;IHS/OKCAO/POC/lwj 5/3/01
 ;I $$MCD^AUPNPAT($S($D(PSODFN):PSODFN,$D(DFN):DFN,1:""),DT) W !,?30,IORVON,IOBON,"MEDICAID PATIENT",IORVOFF,IOBOFF F I=1:1:2 W *7," " ;IHS/OKCAO/POC 10/30/98 8/18/2000 5/3/2001
 I $$MCD^APSQPINS($S($D(PSODFN):PSODFN,$D(DFN):DFN,1:""),DT) W !,?30,IORVON,IOBON,"MEDICAID PATIENT"_"*"_$$GP^APSQPINS($$MCD^APSQPINS($S($D(PSODFN):PSODFN,$D(DFN):DFN,1:""),DT))_"*"_IORVOFF,IOBOFF F I=1:1:2 W *7," "  ;IHS/OKCAO/POC 11/23/2001
 ;I $$MCR^AUPNPAT($S($D(PSODFN):PSODFN,$D(DFN):DFN,1:""),DT) W !,?30,IORVON,IOBON,"MEDICARE PATIENT",IORVOFF,IOBOFF F I=1:1:2 W *7," " ;IHS/OKCAO/POC 10/30/98 8/18/2000 5/3/2001
 I $$MCR^APSQPINS($S($D(PSODFN):PSODFN,$D(DFN):DFN,1:""),DT) W !,?30,IORVON,IOBON,"MEDICARE PATIENT"_"*"_$$GP^APSQPINS($$MCR^APSQPINS($S($D(PSODFN):PSODFN,$D(DFN):DFN,1:""),DT))_"*",IORVOFF,IOBOFF F I=1:1:2 W *7," "  ;IHS/OKCAO/POC 5/3/2001
 ;
 ;IHS/DSD/lwj  05/03/01 problem with line length and rev/blnk  
 ; force CR/LF (problem spotted at Siletz) (old line rmkd out-nxt added)
 ;I $$PIN^APSQPINS($S($D(PSODFN):PSODFN,$D(DFN):DFN,1:""),DT,"E")]"" W !,?30,$C(27)_"[7m"_$C(27)_"[5m"_$$PIN^APSQPINS($S($D(PSODFN):PSODFN,$D(DFN):DFN,1:""),DT,"E")_$C(27)_"[m" F I=1:1:2 W *7," "  ;IHS/OKCAO/POC 10/30/98 8/18/2000
 I $$PIN^APSQPINS($S($D(PSODFN):PSODFN,$D(DFN):DFN,1:""),DT,"E")]"" W !,?10,IORVON,IOBON,$$PIN^APSQPINS($S($D(PSODFN):PSODFN,$D(DFN):DFN,1:""),DT,"E"),!,IORVOFF,IOBOFF F I=1:1:2 W *7," "  ;IHS/OKCAO/POC 10/30/98 8/18/2000 5/3/2001
 ;IHS/DSD/lwj  end of 5/3/01 changes
 Q
CAP ;
 ;IHS/OKCAO/POC 11/8/2001 DISPLAY THE SAFETY STATUS FOR BOTTLES
 N X,Y
 S Y=$$GET1^DIQ(55,PSODFN_",",.02,"I")
 I Y=1 S X="IORVON;IORVOFF" D ENDR^%ZISS
 W ?($X+2),"CAP STATUS: ",$S(Y=0:"SAFETY CAPS OK",Y=1:IORVON_"NON SAFETY CAPS REQUESTED"_IORVOFF,1:"UNKNOWN STATUS") Q
 ;
DIR ;
 K DIR
 S DIR(0)="Y",DIR("B")="NO",DIR("A")="DO YOU WISH TO CONTINUE"
 D ^DIR K DIR
 S:'Y PSOQFLG=1
 K X,Y,DIRUT,DTOUT,DUOUT
 Q
 ;
EOJ ;
 K:PSOQFLG PSORX("CNH")
 K PSOPTPST,PSOPTIB,VAPA
 Q
 ;
RETURN ;ADD A RETURN PROMPT BECAUSE SCREEN SCROLLS PAST WITH LOTS OF MEDS
 ;QUIT IF NOT NEW OR REFILL--SO ONLY GO ON IF NEW OR REFILL
 Q:'($G(PSOFROM)="NEW"!($G(PSOFROM)="REFILL"))
 S DIR(0)="E"
 S DIR("A")="Press RETURN to continue"
 D ^DIR
 K DIR
