PSORN52 ;IHS/DSD/JCM - FILES RENEWAL ENTRIES IN PRESCRIPTION FILE [ 01/15/2003  3:50 PM ]
 ;;6.0;OUTPATIENT PHARMACY;**1,3,4**;11/11/2002
 ;;6.0;OUTPATIENT PHARMACY;**22,34**;09/03/97
 ;ACTUAL ACQUISTION COST ADDED IHS/OKCAO/POC 11/11/2002
 ;IHS/DSD/ENM 10/29/97 XXXX("STOP DATE") IS CALCULATED IN PSON52
 ;IHS/SD/lwj 6/24/03 (patch 4) new logic for POS DUR 5.1
EN(PSOX) ;Entry Point
START ;
 D:$D(XRTL) T0^%ZOSV  ; Start RT Monitor
 D INIT G:PSORN52("QFLG") END D DATA,FILE,PS55,DIK
 S:$D(XRT0) XRTN=$T(+0) D:$D(XRT0) T1^%ZOSV  ; Stop RT Monitor
 D FINISH
 I '$P($G(^PS(53,+$P(^PSRX(PSOX("IRXN"),0),"^",3),0)),"^",7),$G(DUZ("AG"))="V" S PSOFLAG=0 D COPAY^PSOCPB
 ;D ACP^PSOUTIL  ;IHS/DSD/ENM 12/07/93
 ;The above line was disabled because line tag doesn't
 ;exist in PSOUTIL. Line below was added to replace the above.
 D RNPSOSD^PSOUTIL
 S X="APSQCK" X ^%ZOSF("TEST") I $T S NFRXIEN=PSOX("IRXN") D RXSET^APSQCK  ;IHS/OKCAO/POC 9/28/98
END D EOJ
 Q
 ;
INIT ;
 S PSORN52("QFLG")=0
 S:'$D(PSOX("DAYS SUPPLY")) PSOX("DAYS SUPPLY")=$P(PSOX("RX0"),"^",8)
 S:'$D(PSOX("# OF REFILLS")) PSOX("# OF REFILLS")=$P(PSOX("RX0"),"^",9)
 S:'$D(PSOX("ISSUE DATE")) PSOX("ISSUE DATE")=DT
 D INIT^PSON52 K PSON52
 Q
 ;
DATA ;
 S PSOX("NRX0")=PSORENW("RX0"),PSOX("NRX2")=PSORENW("RX2"),PSOX("NRX3")=PSORENW("RX3")
 S $P(PSOX("NRX0"),"^")=PSOX("NRX #") S:$G(PSOX("PROVIDER"))]"" $P(PSOX("NRX0"),"^",4)=PSOX("PROVIDER")
 S $P(PSOX("NRX0"),"^",7)=PSOX("QTY")
 S:$G(PSOX("DAYS SUPPLY"))]"" $P(PSOX("NRX0"),"^",8)=PSOX("DAYS SUPPLY")  ;IHS/DSD/ENM/POC 11/21/97
 S $P(PSOX("NRX0"),"^",5)=PSOX("CLINIC"),$P(PSOX("NRX0"),"^",9)=PSOX("# OF REFILLS")
 S $P(PSOX("NRX0"),"^",11)=$S(PSOX("FILL DATE")>DT:"M",$D(PSOX("MAIL/WINDOW")):PSOX("MAIL/WINDOW"),1:$P(PSOX("NRX0"),"^",11))
 S $P(PSOX("NRX0"),"^",13)=PSOX("ISSUE DATE"),$P(PSOX("NRX0"),"^",15)=PSOX("STATUS"),$P(PSOX("NRX0"),"^",16)=$S($G(PSOX("CLERK CODE"))]"":PSOX("CLERK CODE"),1:DUZ)
 ;S $P(PSOX("NRX0"),"^",17)=$G(PSODRUG("COST"))  ;CHANGED IHS/OKCAO/POC 1/21/2001 IMPROVE COST
 S $P(PSOX("NRX0"),"^",17)=$S($D(PSOX("COST")):PSOX("COST"),1:$G(PSODRUG("COST")))  ;IHS/OKCAO/POC 1/21/2001 IMPROVE COST
 ;
 S $P(PSOX("NRX2"),"^")=PSOX("LOGIN DATE"),$P(PSOX("NRX2"),"^",2)=PSOX("FILL DATE"),$P(PSOX("NRX2"),"^",3)="",$P(PSOX("NRX2"),"^",5)=PSOX("DISPENSED DATE")
 S $P(PSOX("NRX2"),"^",6)=PSOX("STOP DATE"),$P(PSOX("NRX2"),"^",7)=$S($G(PSOX("NDC"))]"":PSOX("NDC"),1:$G(PSODRUG("NDC")))
 ;S $P(PSOX("NRX2"),"^",8)=$S($G(PSOX("MANUFACTURER"))]"":PSOX("MANUFACTURER"),1:$G(PSODRUG("MANUFACTURER")))  ;CHANGE THIS LINE TO NEXT 3 LINES IHS/OKCAO/POC 8/18/2000
 S $P(PSOX("NRX2"),"^",8)=""  ;IN CASE CARRIES FROM RENEWED RX
 I $G(APSPMAN)=1 S $P(PSOX("NRX2"),"^",8)=$S($G(PSODRUG("MANUFACTURER"))]"":PSODRUG("MANUFACTURER"),1:"")  ;DEFAULT SET
 I $G(PSOX("MANUFACTURER"))]"" S $P(PSOX("NRX2"),"^",8)=PSOX("MANUFACTURER")  ;IF USER CHANGES
 ;IHS/DSD/ENM 10/06/95 LOT # ADD, NEXT LINE
 ;S $P(PSOX("NRX2"),"^",4)=$S($G(PSOX("LOT #"))]"":PSOX("LOT #"),1:"")  ;CHANGE THIS LINE TO NEXT 3 LINES IHS/OKCAO/POC 8/18/2000
 S $P(PSOX("NRX2"),"^",4)=""  ;IN CASE CARRIES FROM RENEWED RX
 I $G(APSPMAN)=1 S $P(PSOX("NRX2"),"^",4)=$S($G(PSODRUG("LOT #"))]"":PSODRUG("LOT #"),1:"")  ;DEFAULT SET
 I $G(PSOX("LOT #"))]"" S $P(PSOX("NRX2"),"^",4)=PSOX("LOT #")
 S $P(PSOX("NRX2"),"^",9)=+PSOSITE,$P(PSOX("NRX2"),"^",10)=""
 ;S $P(PSOX("NRX2"),"^",11)=$S($G(PSOX("EXPIRATION DATE"))]"":PSOX("EXPIRATION DATE"),1:$G(PSODRUG("EXPIRATION DATE")))  ;CHANGE THIS LINE TO NEXT 3 LINES IHS/OKCAO/POC 8/18/2000
 S $P(PSOX("NRX2"),"^",11)=""  ;IN CASE CARRIES FROM RENEWED RX
 I $G(PSODRUG("EXPIRATION DATE"))["T+" S %DT="" S X=PSODRUG("EXPIRATION DATE") D ^%DT S:Y'=-1 PSODRUG("EXPIRATION DATE")=Y  ;IHS/OKCAO/POC 1/9/2001 WHAT IF THIS FIELD WAS STUFFED WITH T+
 ;I (($G(APSPMAN)=1)!($G(APSPMAN)=2)) S $P(PSOX("NRX2"),"^",11)=$S($G(PSODRUG("EXPIRATION DATE")):PSODRUG("EXPIRATION DATE"),1:"")  ;DEFAULT SET
 I (($G(APSPMAN)=1)!($G(APSPMAN)=2)) S $P(PSOX("NRX2"),"^",11)=$S($G(PSODRUG("EXPIRATION DATE"))]"":PSODRUG("EXPIRATION DATE"),1:"")  ;DEFAULT SET IHS/OKCAO/POC 1/9/2001 JUST FOR CONTINUITY WITH NEXT LINE
 I $G(PSOX("EXPIRATION DATE"))["T+" S %DT="" S X=PSOX("EXPIRATION DATE") D ^%DT S:Y'=-1 PSOX("EXPIRATION DATE")=Y  ;IHS/OKCAO/POC 1/9/2001 WHATI IF THIS FIELD WAS STUFFED WITH T+
 I $G(PSOX("EXPIRATION DATE"))]"" S $P(PSOX("NRX2"),"^",11)=PSOX("EXPIRATION DATE")
 S:$G(PSOX("GENERIC PROVIDER"))]"" $P(PSOX("NRX2"),"^",12)=PSOX("GENERIC PROVIDER")
 S $P(PSOX("NRX2"),"^",13)="",$P(PSOX("NRX2"),"^",15)=""
 ;
 S PSOX("LAST DISPENSED DATE")=PSOX("DISPENSED DATE"),$P(PSOX("NRX3"),"^",4)=$P(PSOX("NRX3"),"^")
 S $P(PSOX("NRX3"),"^")=PSOX("LAST DISPENSED DATE")
 S:$G(PSOX("NEXT POSSIBLE REFILL"))]"" $P(PSOX("NRX3"),"^",2)=PSOX("NEXT POSSIBLE REFILL")
 S:$G(PSOX("COSIGNING PROVIDER"))]"" $P(PSOX("NRX3"),"^",3)=PSOX("COSIGNING PROVIDER")
 S:$G(PSOX("REMARKS"))']"" PSOX("REMARKS")="RENEWED FROM RX # "_$P(PSOX("RX0"),"^")
 S $P(PSOX("NRX3"),"^",7)=PSOX("REMARKS")
 S $P(PSOX("NRX9999999"),"^",6)=$S($D(PSOX("AWP")):PSOX("AWP"),1:$G(PSODRUG("AWP")))  ;IHS/OKCAO/POC 8/18/2000 9/8/2000
 S $P(PSOX("NRX9999999"),"^",7)=$S($D(PSOX("BST")):PSOX("BST"),1:$G(PSOBILST))  ;IHS/OKCAO/POC 8/18/2000
 S:$D(PSOX("INSURER")) $P(PSOX("NRX9999999"),"^",12)=PSOX("INSURER") ;IHS/OKCAO/POC 8/18/2000
 S:$D(PSOX("DUR")) $P(PSOX("NRX9999999"),"^",12)=PSOX("DUR") ;IHS/SD/lwj 6/24/03 (patch 4)
 S:$G(PSOX("TRIP"))]"" $P(PSOX("NRX9999999"),"^",14)=PSOX("TRIP")  ;IHS/OKCAO/POC 11/20/2002 TRIPLICATE FIELD FOR LORI
 Q
 ;
FILE ;     
 S DIC="^PSRX(",DLAYGO=52,DIC(0)="L",X=PSOX("NRX #")
 K DD,DO
 D FILE^DICN S PSOX("IRXN")=+Y K DLAYGO,X,Y,DIC D:+$G(DGI) TECH^PSODGDGI
 L +^PSRX(PSOX("IRXN"))
 S PSORN52(PSOX("IRXN"),0)=PSOX("NRX0")
 S PSORN52(PSOX("IRXN"),2)=PSOX("NRX2")
 S PSORN52(PSOX("IRXN"),3)=PSOX("NRX3")
 S PSORN52(PSOX("IRXN"),9999999)=PSOX("NRX9999999")  ;IHS/OKCAO/POC 8/18/2000
 S:$G(PSOX("TN"))]"" PSORN52(PSOX("IRXN"),"TN")=PSOX("TN")
 I $G(PSOX("METHOD OF PICK-UP"))]"",PSOX("FILL DATE")'>DT S PSORN52(PSOX("IRXN"),"MP")=PSOX("METHOD OF PICK-UP")
 S PSORN52(PSOX("IRXN"),"TYPE")=0
 S PSOX1="" F  S PSOX1=$O(PSORN52(PSOX("IRXN"),PSOX1)) Q:PSOX1=""  S ^PSRX(PSOX("IRXN"),PSOX1)=$G(PSORN52(PSOX("IRXN"),PSOX1))
 ;CK/SET CHRONIC MED DATA  ;IHS/DSD/ENM 09/19/96
 I $G(PSOX("ZCM"))="Y" S DIE=52,DA=PSOX("IRXN"),DR="9999999.02///Y" D ^DIE  ;IHS/DSD/ENM 09/19/96
 K ^PS(55,PSODFN,"P","CP",PSOX("OIRXN"))  ;IHS/DSD/ENM 09/19/96
 K PSOX1
 Q
 ;
PS55 ;
 L +^PS(55,PSODFN,"P")
 S:'$D(^PS(55,PSODFN,"P",0)) ^(0)="^55.03PA^^"
 F PSOX1=$P(^PS(55,PSODFN,"P",0),"^",3):1 Q:'$D(^PS(55,PSODFN,"P",PSOX1))
 S PSOX("55 IEN")=PSOX1
 S ^PS(55,PSODFN,"P",PSOX1,0)=PSOX("IRXN"),$P(^PS(55,PSODFN,"P",0),"^",3,4)=PSOX1_"^"_($P(^PS(55,PSODFN,"P",0),"^",4)+1)
 S ^PS(55,PSODFN,"P","A",PSOX("STOP DATE"),PSOX("IRXN"))=""
PS55X L -^PS(55,PSODFN,"P")
 K PSOX1
 Q
 ;
DIK ;
 K DIK,DA
 S DIK="^PSRX(",DA=PSOX("IRXN") D IX1^DIK K DIK,DA
 Q
 ;
FINISH ;
 G:PSOX("STATUS")=4 FINISHP
 I $D(PSORX("VERIFY")) D  G FINISHX
 . K DIC,DLAYGO,DINUM,DIADD,X,DD,DO
 . S DIC="^PS(52.4,",DLAYGO=52.4,DINUM=PSOX("IRXN"),DIC(0)="ML"
 . S X=PSOX("IRXN")
 . D FILE^DICN K DIC,DLAYGO,DINUM,X
 . S ^PS(52.4,PSOX("IRXN"),0)=PSOX("IRXN")_"^"_$P(PSOX("NRX0"),"^",2)_"^"_DUZ_"^"_$G(PSOX("OIRXN"))_"^"_$E(PSOX("LOGIN DATE"),1,7)_"^"_PSOX("IRXN")_"^"_PSOX("STOP DATE")
 . K DIK,DA
 . S DIK="^PS(52.4,",DA=PSOX("IRXN")
 . D IX^DIK K DIK,DA
 . Q
 ;
 I $G(PSOX("QS"))="S" D  G FINISHX
 . S DA=PSOX("IRXN")
 . D SUS^PSORXL K DA
 . Q
 ;
 I PSOX("FILL DATE")>DT,$P(PSOPAR,"^",6) D   G FINISHX
 . S DA=PSOX("IRXN")
 . D SUS^PSORXL K DA
 . Q
 ;
 I $G(PSOX("QS"))="Q" D  G FINISHX
 . N PSOFROM S PSOFROM="BATCH"
 . I $G(PPL),$L(PPL_PSOX("IRXN")_",")>240 D Q^PSORXL K PPL
 . I $G(PPL) S PPL=PPL_PSOX("IRXN")_","
 . E  S PPL=PSOX("IRXN")_","
 . Q
 ;
FINISHP I $G(PSORX("PSOL",1))']"" S PSORX("PSOL",1)=PSOX("IRXN")_",",APSPZRP=PSORX("PSOL",1) G FINISHX  ;IHS/DSD/ENM 12/22/95 APSPZRP ADDED FOR RELEASE RTN
 F PSOX1=0:0 S PSOX1=$O(PSORX("PSOL",PSOX1)) Q:'PSOX1  S PSOX2=PSOX1
 I $L(PSORX("PSOL",PSOX2))+$L(PSOX("IRXN"))<220 S PSORX("PSOL",PSOX2)=PSORX("PSOL",PSOX2)_PSOX("IRXN")_","
 E  S PSORX("PSOL",PSOX2+1)=PSOX("IRXN")_","
 S APSPZRP=PSORX("PSOL",1)  ;IHS/DSD/ENM 12/22/95 VAR ADDED FOR RELEASE
FINISHX ; 
 K PSOX1,PSOX2
 Q
EOJ ;
 L -^PSRX(PSOX("IRXN"))
 K PSORN52
 Q
