PSORXED ;IHS/DSD/JCM - EDIT RX UTILITY  [ 05/14/2003  4:17 PM ]
 ;;6.0;OUTPATIENT PHARMACY;**1,2,3,4**;11/11/2002
 ;;6.0;OUTPATIENT PHARMACY;**13,30,44,74,94,73,124**;09/03/97
 ;ACTUAL ACQUISTION COST ADDED IHS/OKCAO/POC 11/11/2002
 ;IHS/SD/lwj 6/24/03 (patch 4) added logic for POS 5.1 DUR
START D INIT,LKUP G:PSORXED("QFLG") END D PARSE,EOJ G START
END D EOJ
 Q
INIT ;
 S PSORXED("QFLG")=0
 Q
LKUP ;
 N PSOOPT S PSOOPT=3
 K PSOSD  ;IHS/DSD/ENM/POC 01/29/98 FORCE REBUILD AFTER EDIT
 S PSONUM("A")="EDIT ",PSOQFLG=0 D ^PSONUM I PSOQFLG!($Q(PSOLIST)']"") S PSORXED("QFLG")=1  ;IHS/DSD/ENM 08/08/96
 K PSOQFLG Q
 ;
PARSE F PSORXED("LIST")=1:1 Q:'$D(PSOLIST(PSORXED("LIST")))!PSORXED("QFLG")  F PSORXED("I")=1:1:$L(PSOLIST(PSORXED("LIST"))) S PSORXED("IRXN")=$P(PSOLIST(PSORXED("LIST")),",",PSORXED("I")) D:+PSORXED("IRXN") PROCESS
 Q
PROCESS S PSORXED("DFLG")=0 G:$G(^PSRX(PSORXED("IRXN"),0))']"" PROCESSX
 S PSORXED("RX0")=^PSRX(PSORXED("IRXN"),0),PSORXED("RX2")=^(2),PSORXED("RX3")=^(3),PSORXED("RX9999999")=$G(^(9999999)),PSODAYS=$P(PSORXED("RX0"),"^",8)  ;IHS/OKCAO/POC 8/18/2000 NEED 9999999 NODE
 ;--- --- --- --- ---
 ;IHS/DSD/ENM SET PAR FOR PCC LINK
 S (I,RFD,RFDT)=0 F  S I=$O(^PSRX(PSORXED("IRXN"),1,I)) Q:'I  S RFD=I,PSORXED("RX1")=^PSRX(PSORXED("IRXN"),1,I,0),PSORXED("RX19999999")=$G(^(9999999)),RFDT=$P(^(0),"^"),PSODAYS=$P(^(0),"^",10) S:$P(^(0),"^",17) PSONEW("PROVIDER NAME")=$P(^VA(200,$P(^(0),"^",17),0),"^")  ;IHS/OKCAO/POC 8/18/2000 NEED 9999999 REFILL NODE
 I $P(%APSITE,U,15)="Y" S APSRX=PSORXED("IRXN"),APSRCT=0 I $D(RFD),$D(^PSRX(APSRX,1,RFD,0)) S APSRCT=RFD  ;IHS/DSD/ENM/POC 11/29/98
 S APSRM=$G(^PSRX(APSRX,1,RFD,999999911))  ;IHS/DSD/ENM/POC VMED VALUE
 ;S APSPRIEN=APSRX  ;IHS/DSD/ENM/POC 01/29/98
 S APSPRIEN=PSORXED("IRXN")  ;IHS/ITSC/ENM/POC 05/07/03
 S PSODRDEA=$P($G(^PSDRUG($P(^PSRX(PSORXED("IRXN"),0),"^",6),0)),"^",3)  ;IHS/OKCA/POC 11/20/2002 DEA FIELD IN DRUG FILE FOR TRIPLICATE NUMBER
 S PSORXST=+$P($G(^PS(53,+$P(PSORXED("RX0"),"^",3),0)),"^",7) N DA S DA=PSORXED("IRXN") D EN^PSORXPR
 D CHECK G:PSORXED("DFLG") PROCESSX D DIE,LOG,POST
PROCESSX Q
CHECK L +^PSRX(PSORXED("IRXN")):0 I '$T W *7,!!,"Rx Number is Locked by Another User!",! S PSORXED("DFLG")=1 H 5 Q
 I $G(^PSDRUG($P(PSORXED("RX0"),"^",6),"I"))]"",^("I")<DT D  G CHECKX
 . W !,*7,"This drug has been inactivated. ",! S PSORXED("DFLG")=1 Q
 K PSPOP I $G(PSODIV),$P(PSORXED("RX2"),"^",9)'=PSOSITE S PSPRXN=PSORXED("IRXN") D CHK1^PSOUTLA I $G(PSPOP)=1 S PSORXED("DFLG")=1 G CHECKX
 ;
 I $D(^PS(52.4,"B",PSORXED("IRXN"))) S PSORXED("DFLG")=1 W !,*7,"Non-verified prescriptions cannot be edited.",!
CHECKX K PSPOP,DIR,DTOUT,DUOUT,Y,X Q
 ;
DIE W !,"Now Editing Rx # ",$P(PSORXED("RX0"),"^") K DIE,DA,DIC,DR S DIE="^PSRX(",DA=PSORXED("IRXN")
 S APSAZIEN=$P(PSORXED("RX0"),"^",6)  ;6TH PIECE OF ZERO NODE DRUG POINTER IHS/OKCAO/POC 8/18/2000
 ;IHS/DSD/ENM/POC 01/29/98 NEXT LINE APSREFD EDIT THE LAST REFILL,
 ;NO EDITING OF THE .01 OF 52.1
 S DR="1;22R;"_$S('$G(RFD):"3;",1:"")_"4;5"_$S($P(PSOPAR,"^",3):";6",1:"")_";6.5:8;9:11;"_$S($P(PSOPAR,"^",12):"35;",1:"")_"12;20;9999999.02" S DR=DR_";23",DR(2,52.1)="I +D'=$G(APSREFD) S Y=0 W ""ONLY THE LAST REFILL CAN BE EDITED"";1;1.1;2:4;8;15"
 S DR=DR_$S(($G(PSOTRIP)&(PSODRDEA["2")):";9999999.14;",1:"")  ;IHS/OKCAO/POC TRIPLICATE 11/20/2002 FOR LORI
 S DR=DR_";27;S APSAZNDC=X;W !,""DELETE AWP FIELD TO RECALCUATE"";9999999.06//^S X=$$AWP^APSQDAWP($S($G(APSAZNDC):APSAZNDC,1:$P(PSORXED(""RX2""),U,7)),APSAZIEN,.MESS);I X="""" S Y=9999999.06;W !,$G(MESS) K MESS"  ;IHS/OKCAO/POC 7/3/2001
 S DR=DR_";W !,""DELETE COST FIELD TO RECALCULATE"";17//^S X=$$COST^APSQDAWP($S($G(APSAZNDC):APSAZNDC,1:$P(PSORXED(""RX0""),U,17)),APSAZIEN,.MESS);I X="""" S Y=17;W !,$G(MESS) K MESS;9999999.07" ;IHS/OKCAO/POC 1/21/2001 IMPROVE COST;IHS/OKCAO/POC 7/3/200
 S DR(2,52.1)=DR(2,52.1)_";11;S APSARNDC=X;W !,""DELETE REFILL AWP FIELD TO RECALCULATE"";9999999.06//^S X=$$AWP^APSQDAWP($S($G(APSARNDC):APSARNDC,1:$P(PSORXED(""RX1""),U,13)),APSAZIEN,.MESS);I X="""" S Y=9999999.06;W !,$G(MESS) K MESS"  ;IHS/OKCAO/POC 7/03/2001 IMPROVE COST FLD 9999999.07 IS INSERTED NEXT LINE
 S DR(2,52.1)=DR(2,52.1)_";W !,""DELETE REFILL CURRENT COST FIELD TO RECALCULATE"";1.2//^S X=$$COST^APSQDAWP($S($G(APSARNDC):APSARNDC,1:$P(PSORXED(""RX1""),U,11)),APSAZIEN,.MESS);I X="""" S Y=1.2;W !,$G(MESS) K MESS;9999999.07" ;IHS/OKCAO/POC 7/3/2001 IMPROVE COST
 S (APSREFF,APSREFD,I)=0 F  S I=$O(^PSRX(PSORXED("IRXN"),1,I)) Q:'+I  S APSREFF=APSREFF+1  ;IHS/DSD/ENM/POC 01/29/98
 S:APSREFF APSREFD=+(^PSRX(PSORXED("IRXN"),1,APSREFF,0)) ;IHS/DSD/ENM/POC 01/29/98
 I APSPMAN=1&(RFD) S DR(2,52.1)=DR(2,52.1)_";5;12;13" ;IHS/DSD/ENM 03/27/96 ASK REFILL MFG DATA FM 52
 I APSPMAN=2&(RFD) S DR(2,52.1)=DR(2,52.1)_";13" ;IHS/DSD/ENM 03/27/96 ASK REFILL MFG DATA FM 52
 I APSPMAN=1&'$G(RFD) S DR=DR_";24;28;29"
 I APSPMAN=2&'$G(RFD) S DR=DR_";29"
 S:RFD DR=DR_";52"  ;IHS/OKCAO/POC 8/18/2000 MOVE DOWN HERE TO HAVE REFILLS AT END
 ;IHS/SD/lwj 6/24/03 patch 4   ;ADD SOME MORE 8/18/2000 IHS/OKCAO/POC
 S PSOBXIEN=$P($G(^PSRX(PSORXED("IRXN"),9999999)),"^",12)  ;INSUER INFO OF RX
 S:RFD PSOBRIEN=$P($G(^PSRX(PSORXED("IRXN"),1,RFD,9999999)),"^",12)  ;INSURER INFO OF LAST REFILL
 S PSODXIEN=$P($G(^PSRX(PSORXED("IRXN"),9999999)),U,13)   ;IHS/SD/lwj 6/24/03 patch 4
 S:RFD PSODRIEN=$P($G(^PSRX(PSORXED("IRXN"),1,RFD,9999999)),"^",13)  ;IHS/SD/lwj 6/24/03 patch 4
 N APSQDUR S APSQDUR=""
 S:'RFD DR=DR_";W !,""DO YOU WANT TO EDIT RX INSURER INFO"" S %=2 D YN^DICN S:%'=1 Y=0;9999999.12///^S X=$$OVERRIDE^APSQBRES($G(PSOBXIEN),$G(PSODXIEN))"  ;IF NO REFILL
 S:RFD DR(2,52.1)=DR(2,52.1)_";W !,""DO YOU WANT TO EDIT REFILL INSURER INFO"" S %=2 D YN^DICN S:%'=1 Y=0;9999999.12///^S X=$$OVERRIDE^APSQBRES($G(PSOBRIEN),$G(PSODRIEN))"  ;IF A REFILL EXISTS
 ;IHS/SD/lwj 6/24/03 patch 4  ;END OF CHANGES 8/18/2000 IHS/OKCAO/POC 
 D ^DIE K DIE,DR,DA,X,Y L -^PSRX(PSORXED("IRXN")) I RFD,$G(^PSRX(PSORXED("IRXN"),1,RFD,0))]"" D
 .S:$P(PSORXED("RX1"),"^",17)'=$P(^PSRX(PSORXED("IRXN"),1,RFD,0),"^",17) PSONEW("PROVIDER NAME")=$P(^VA(200,$P(^PSRX(PSORXED("IRXN"),1,RFD,0),"^",17),0),"^")
 ;IHS/SD/lwj 6/24/03 (patch 4) update DUR in PSRX
 D  ;do it so we can isolate the variables
 . N FDA,MSG
 . I RFD S FDA(52.1,RFD_","_PSORXED("IRXN")_",",9999999.13)=APSQDUR
 . I 'RFD S FDA(52,PSORXED("IRXN")_",",9999999.13)=APSQDUR
 . D FILE^DIE(,"FDA","MSG")
 ;IHS/SD/lwj 6/24/03 (patch 4) end of DUR changes
APCOM S COM=""
 I APSPMAN=""!(APSPMAN=3) S PSONEW("EXPIRATION DATE")="",PSONEW("MANUFACTURER")="",PSONEW("LOT #")=""
 ;IHS/DSD/ENM 12/28/95 SETUP COM VAR FOR CHG MFG DATA
 I APSPMAN=1&'$G(RFD) S APSP91=^PSRX(PSORXED("IRXN"),2),PSONEW("EXPIRATION DATE")=$P($G(APSP91),"^",11),PSONEW("MANUFACTURER")=$P($G(APSP91),"^",8),PSONEW("LOT #")=$P($G(APSP91),"^",4) D  ;IHS
 .I PSONEW("EXPIRATION DATE")'=$P($G(PSORXED("RX2")),"^",11) S COM=COM_$P(^DD(52,29,0),"^")_" ("_PSONEW("EXPIRATION DATE")_"),"
 .I PSONEW("MANUFACTURER")'=$P($G(PSORXED("RX2")),"^",8) S COM=COM_$P(^DD(52,28,0),"^")_" ("_PSONEW("MANUFACTURER")_"),"
 .I PSONEW("LOT #")'=$P($G(PSORXED("RX2")),"^",4) S COM=COM_$P(^DD(52,24,0),"^")_" ("_PSONEW("LOT #")_"),"
 I APSPMAN=2&'$G(RFD) S APSP91=^PSRX(PSORXED("IRXN"),2),PSONEW("EXPIRATION DATE")=$P($G(APSP91),"^",11)
 ;IHS/DSD/ENM 12/29/95 SETUP COM FOR REFILL MFG DATA
 I APSPMAN=1&(RFD) S APSP92=$G(^PSRX(PSORXED("IRXN"),1,RFD,0)),APSP44("EXP DATE")=$P($G(APSP92),"^",15),APSP44("MFG")=$P($G(APSP92),"^",14),APSP44("LOT #")=$P($G(APSP92),"^",6) D  ;IHS
 .S PSONEW("EXPIRATION DATE")=APSP44("EXP DATE"),PSONEW("MANUFACTURER")=APSP44("MFG"),PSONEW("LOT #")=APSP44("LOT #")
 .I APSP44("EXP DATE")'=$P($G(PSORXED("RX1")),"^",15) S COM=COM_$P(^DD(52.1,13,0),"^")_" ("_APSP44("EXP DATE")_"),"
 .I APSP44("MFG")'=$P($G(PSORXED("RX1")),"^",14) S COM=COM_$P(^DD(52.1,12,0),"^")_" ("_APSP44("MFG")_"),"
 .I APSP44("LOT #")'=$P($G(PSORXED("RX1")),"^",6) S COM=COM_$P(^DD(52.1,5,0),"^")_" ("_APSP44("LOT #")_"),"
 I APSPMAN=2&(RFD) S APSP92=$G(^PSRX(PSORXED("IRXN"),1,RFD,0)),APSP44("EXP DATE")=$P($G(APSP92),"^",15),PSONEW("EXPIRATION DATE")=APSP44("EXP DATE") D  ;IHS
 .I APSP44("EXP DATE")'=$P($G(PSORXED("RX1")),"^",15) S COM=COM_$P(^DD(52.1,13,0),"^")_" ("_APSP44("EXP DATE")_"),"
 S PSORXED("NDC")=$P($G(^PSRX(PSORXED("IRXN"),2)),"^",7),PSORXED("AWP")=$P($G(^(9999999)),"^",6)  ;IHS/OKCAO/POC 8/18/2000 FOR DISPLAYING AT EN1^PSONEW2
 S PSORXED("COST")=$P(^PSRX(PSORXED("IRXN"),0),"^",17)  ;IHS/OKCAO/POC 1/21/2001 IMPROVE DRUG
 I $G(RFD) S PSORXED("NDC")=$P($G(^PSRX(PSORXED("IRXN"),1,RFD,0)),"^",13),PSORXED("AWP")=$P($G(^PSRX(PSORXED("IRXN"),1,RFD,9999999)),"^",6)  ;IHS/OKCAO/POC 8/18/2000 FOR DISPLAYING AT EN1^PSONEW2
 I $G(RFD) S PSORXED("COST")=$P(^PSRX(PSORXED("IRXN"),1,RFD,0),"^",11)  ;IHS/OKCAO/POC 1/21/2001 IMPROVE COST
 D EN1^PSONEW2(.PSORXED) I PSORXED("DFLG") S PSORXED("QFLG")=1 G DIEX
 G:'PSORXED("QFLG") DIE S PSORXED("QFLG")=0
DIEX Q
LOG K PSFROM S DA=PSORXED("IRXN"),(PSRX0,RX0)=PSORXED("RX0"),QTY=$P(RX0,"^",7),ZD=$P(^PSRX(DA,2),"^",2),QTY=QTY-$P(^(0),"^",7)
 F I=3,4,5:1:13,17 I $P(PSRX0,"^",I)'=$P(^PSRX(DA,0),"^",I) S PSI=$S(I=13:1,1:I),COM=COM_$P(^DD(52,PSI,0),"^")_" ("_$P(PSRX0,"^",I)_"),"
 I $P(PSORXED("RX2"),"^",7)'=$P($G(^PSRX(DA,2)),"^",7) S COM=COM_$P(^DD(52,27,0),"^")_" ("_$P(PSORXED("RX2"),"^",7)_"),"  ;IHS/OKCAO/POC 8/18/2000 NEED NDC
 I $P(PSORXED("RX9999999"),"^",6)'=$P($G(^PSRX(DA,9999999)),"^",6) S COM=COM_$P(^DD(52,9999999.06,0),"^")_" ("_$P(PSORXED("RX9999999"),"^",6)_"),"  ;IHS/OKCAO/POC 8/18/2000 NEED AWP
 I $P(PSORXED("RX3"),"^",7)'=$P(^PSRX(DA,3),"^",7) S COM=COM_$P(^DD(52,12,0),"^")_" ("_$P(PSORXED("RX3"),"^",7)_"),"
 I $G(APSQCOM)]"" S COM=COM_APSQCOM K APSQCOM  ;TO GURANTEE PRINTING AND BILLING IF EDIT INSURER INFO NOTE APSQCOM SET IN CALL TO OVERRIDE^APSQBRES IHS/OKCAO/POC 8/18/2000
 G:COM="" LOGX K PSRX0 S X=$S($D(PSOCLC):PSOCLC,1:DUZ)
 S COM=COM_$$POS  ;ADD NEGATIVE ANSWER TO POS REFILLING QUESTION IHS/OKCAO/POC 5/16/2003
 S K=1,D1=0 F Z=0:0 S Z=$O(^PSRX(DA,"A",Z)) Q:'Z  S D1=Z,K=K+1
 S D1=D1+1 S:'($D(^PSRX(DA,"A",0))#2) ^(0)="^52.3DA^^^" S ^(0)=$P(^(0),"^",1,2)_"^"_D1_"^"_K
 S ^PSRX(DA,"A",D1,0)=DT_"^E^"_X_"^0^"_COM
 S:QTY ^PSDRUG($P(^PSRX(DA,0),"^",6),660.1)=$S($D(^PSDRUG(+$P(^PSRX(DA,0),"^",6),660.1)):^(660.1)+QTY,1:QTY)
 S:$P(RX0,"^",6)'=$P(^PSRX(DA,0),"^",6) ^PSDRUG(+$P(^PSRX(DA,0),"^",6),660.1)=$S($D(^PSDRUG(+$P(RX0,"^",6),660.1)):^(660.1)+$P(RX0,"^",7),1:$P(RX0,"^",7))
 S REPRINT="",RX0=^PSRX(DA,0),RX2=^(2),(PPL,J)=DA,OEXDT=+$P(RX2,"^",6) D ^PSOEXDT S NEXDT=+$P(RX2,"^",6) I OEXDT'=NEXDT D
 . S D=+$P(^PSRX(DA,0),"^",2) K ^PS(55,D,"P","A",OEXDT,DA) S ^PS(55,D,"P","A",NEXDT,DA)="" K D,OEXDT,NEXDT
 . Q
 G:+$P(RX0,"^",15) LOGX I $G(PSORX("PSOL",1))']"" S PSORX("PSOL",1)=PSORXED("IRXN")_"," G LOGX
 F PSOX1=0:0 S PSOX1=$O(PSORX("PSOL",PSOX1)) Q:'PSOX1  S PSOX2=PSOX1
 I $L(PSORX("PSOL",PSOX2))+$L(PSORXED("IRXN"))<220 S PSORX("PSOL",PSOX2)=PSORX("PSOL",PSOX2)_PSORXED("IRXN")_","
 E  S PSORX("PSOL",PSOX2+1)=PSORXED("IRXN")_","
LOGX D ^PSORXED1
 ;HOOK FOR DATA LINK LINK TO IHS/PCC ;IHS/DSD/ENM 11/28/95
 I $P(%APSITE,U,15)="Y" D ^APSPCCE  ;IHS/DSD/ENM 11/28/95
 ;XXXX HOOK FOR BILLING USE CLAIM PART IHS/OKCAO/POC 8/18/2000 HAVE TO RESUBMIT ORIGINAL RX AND LAST REFILL DA=PSORXED("IRXN") AND IF EXISTS LAST REFILL IS $O(^PSRX(PSRXED("IRXN"),1,"A"),-1)
 Q
 ;
POS() ;IHS/OKCAO/POC 5/16/2003 ONLY GET HERE IF CHANGE SOME FIELDS!!
 ;HOOK FOR BILLING USE CLAIM PART IHS/OKCAO/POC
 ;RESUBMIT ORIGINAL RX AND LAST REFILL DA=PSORXED("IRXN") AND IF EXISTS LAST REFILL IS $O(^PSRX(PSRXED("IRXN"),1,"A"),-1)
 D
 .;IF HERE MEANS POS MAY BE CALLED-DECIDE IF REALLY WANT TO RESUBMIT TO POS IF GOT ENTRY IN ACCOUNTS RECEIVABLE
 .D TEST^APSQBRES("ABSPOSRX") I $G(QUIT) S ANS="" Q  ;QUIT IF POS NOT INSTALLED! ADDED 7/1/2003
 .N APSQPOS,APSQPOST,APSQIT
 .S APSQIT=0
 .S ANS="CLAIM WAS NOT RESUBMITTED TO POS"
 .S APSQPOS=$$IEN59^ABSPOSRX(PSORXED("IRXN"),$G(LASTR,0))  ;IEN OF ^ABSPT
 .I +$G(APSQPOS) S APSQPOST=$O(^ABSPTL("B",APSQPOS,"A"),-1)  ;LAST IEN OF ^ABSPTL
 .I +$G(APSQPOST) D:+$$GET1^DIQ(9002313.57,+APSQPOST_",",.15)  ;ENTRY DEFINED AS NUMERIC IF GOT ENTRY IN ACCOUNTS RECEIVABLE
 ..S DIR("A",1)="THERE IS AN ENTRY FOR THIS PRESCRIPTION IN THE ACCOUNTS RECEIVABLE PACKAGE"
 ..S DIR("A")="DO YOU REALLY WANT TO REVERSE THIS ENTRY AND RESEND IT TO THE INSURER AND PUT ANOTHER ENTRY IN ACCOUNTS RECEIVABLE"
 ..S DIR("B")="YES"
 ..S DIR(0)="Y"
 ..D ^DIR
 ..S:Y=0 APSQIT=1  ;ANSWERED NO
 .I 'APSQIT D
 ..S ANS="CLAIM WAS RESUBMITTED TO POS"
 ..N APSQPST,LASTR
 ..S LASTR=$O(^PSRX(PSORXED("IRXN"),1,"A"),-1)
 ..I 'LASTR S APSQPST=$$EN^APSQBRES(PSORXED("IRXN"),"","A")  ;YES I WANT TO ADD A CLAIM, POS KNOWS TO BACK OUT AND RESUBMIT
 ..I LASTR S APSQPST=$$EN^APSQBRES(PSORXED("IRXN"),LASTR,"A")
 Q ANS
 ;END OF CHANGES IHS/OKCAO/POC 5/16/2003
 ;
POST D NEXT D:$G(^PSRX(PSORXED("IRXN"),"IB"))]"" COPAY K PSODAYS,PSORXST
 Q
COPAY S DA=PSORXED("IRXN") I +^PSRX(DA,"IB"),'RFD,PSODAYS'=+$P(^PSRX(DA,0),"^",8) D CPCK G RXST
 I +^PSRX(DA,"IB"),RFD,+$G(^PSRX(DA,1,RFD,0)),PSODAYS'=$P($G(^PSRX(DA,1,RFD,0)),"^",10) D CPCK
RXST G:PSORXST=+$P($G(^PS(53,+$P(^PSRX(DA,0),"^",3),0)),"^",7) COPAYX
 W !,*7,"Patient Status field for this Rx has been changed from a ",$S(PSORXST=0:"COPAYMENT ELIGIBLE",PSORXST=1:"COPAYMENT EXEMPT",1:""),!,"patient status to a ",$S(PSORXST=1:"COPAYMENT ELIGIBLE",PSORXST=0:"COPAYMENT EXEMPT",1:"")
 W " patient status.",!,"If action needs to be taken to adjust charges or status of this Rx, you MUST",!,"use the REMOVE and RESET copay options."
COPAYX K DA,PSODAYS,PSO,PSODA,PSOFLAG,PSORXST,RFD
 Q
CPCK ;update COPAY
 S PSO=2,PSODA=DA,PSOFLAG=1,PSOPAR7=$G(^PS(59,PSOSITE,"IB")) D RXED^PSOCPA
 Q
NEXT D NEXT^PSOUTIL(.PSORXED) K DIE,DR,DA S DIE="^PSRX(",DA=PSORXED("IRXN")
 S DR="101///"_$P(PSORXED("RX3"),"^")_";102///"_$P(PSORXED("RX3"),"^",2) L +^PSRX(DA) D ^DIE L -^PSRX(DA) K DIE,DR,DA,X,Y
 Q
EOJ K PSORXED,PSOLIST,END,PSRX0
 K APSP,APSP1,APSP2,APSPDZ,APSPLTYP,APSPM0,APSPPDY,APSPPLOT,APSPPMF,APSPRXX,PSOREF,APSP91,APSPMM,APSPL
 K APSREFF,APSREFD  ;IHS/DSD/ENM 01/30/98
 K APSAZNDC,APSAZIEN,APSARNDC  ;IHS/OKCAO/POC 8/18/2000
 K PSOBXIEN,PSOBRIEN,PSODRDEA  ;TRIPLICATE IHS/OKCAO/POC 11/20/2002
 K PSODXIEN,PSODRIEN,APSQDUR   ;IHS/SD/lwj 6/27/03 DUR segment
 Q
XIT K APSP44("EXP DATE"),APSP44("MFG"),APSP92
 Q
KILL ;
 W !,"GOT HERE"
