PSORENW1 ;IHS/DSD/JCM - RENEW MAIN DRIVER CONTINUATION [ 01/28/2003  4:17 PM ]
 ;;6.0;OUTPATIENT PHARMACY;**4**;09/03/97
 ;
START ;
 S PSORENW("RX0")=^PSRX(PSORENW("OIRXN"),0),PSORENW("RX2")=^(2),PSORENW("RX3")=^(3),PSORENW("TN")=$G(^("TN"))
 S PSORENW("PROVIDER")=$P(PSORENW("RX0"),"^",4)
 S PSORX("PROVIDER NAME")=$P($G(^VA(200,PSORENW("PROVIDER"),0)),"^")
 S PSORENW("QTY")=$P(PSORENW("RX0"),"^",7) ;IHS/DSD/ENM 08/06/96
 S PSORENW("ZCM")=$P($G(^PSRX(PSORENW("OIRXN"),9999999)),"^",2) ;IHS/DSD/ENM 09/19/96 CK FOR CHRONIC MED ENTRY IN OLD RX
 S PSORENW("CLINIC")=$P(PSORENW("RX0"),"^",5)
 S PSORENW("REMARKS")="RENEWED FROM RX # "_$P(PSORENW("RX0"),"^")
 S PSORENW("SIG")=$P(PSORENW("RX0"),"^",10)
 S:$P(PSORENW("RX3"),"^",3) PSORENW("COSIGNER")=$P(PSORENW("RX3"),"^",3)
 S PSORENW("PSODFN")=$P(PSORENW("RX0"),"^",2)
 S PSORENW("ORX #")=$P(PSORENW("RX0"),"^")
 S PSORENW("DRUG IEN")=$P(PSORENW("RX0"),"^",6)
 ;
 S PSORENW("PATIENT STATUS")=$P(PSORENW("RX0"),"^",3)  ;IHS/OKCAO/POC 12/21/2001
END Q
