PSOREF0 ;IHS/DSD/JCM - REFILL DATA ENTRY CON'T [ 01/21/2003  1:57 PM ]
 ;;6.0;OUTPATIENT PHARMACY;**3,4**;11/11/2002
 ;;6.0;OUTPATIENT PHARMACY;**83,93,128**;09/03/97
 ;ACTUAL ACQUISITION COST ADDED ISH/OKCAO/POC 11/11/2002
 ;IHS/DSD/ENM 04/20/94 modules EXD,EXDT,IHSH,CHECK+24
PROCESS ;
 S PSOREF("RX0")=^PSRX(PSOREF("IRXN"),0),PSOREF("RX2")=^(2),PSOREF("RX3")=^(3),PSOREF("PSODFN")=$P(PSOREF("RX0"),"^",2)
 S PSOREF("DRUG IEN")=$P(PSOREF("RX0"),"^",6)  ;IHS/OKCAO/POC 11/5/2002 CALL FOR LAB
 S PSOREF("DAYS SUPPLY")=$P(PSOREF("RX0"),"^",8)
 ;S PSODRUG("IEN")=$P(PSOREF("RX0"),"^",6)  ;IHS/OKCAO/POC 8/18/2000 NEED DRUG FOR AWP PRICING IN PSOREF1
 ;I $P(PSOREF("RX0"),U,6) S PSOREF("NDC")=$P($G(^PSDRUG($P(PSOREF("RX0"),U,6),2)),U,4) ;IHS/OKCAO/POC NEED NDC ON REFILLS 11/12/98 SEE PSOREF1 8/18/2000
 I $D(PSORX("BAR CODE")),PSODFN'=PSOREF("PSODFN") D NEWPT
 W !,"Now refilling Rx # ",$P(PSOREF("RX0"),"^")_"   DRUG: "_$P(^PSDRUG($P(PSOREF("RX0"),"^",6),0),"^")
 D PRINT^APSQLAB  ;IHS/OKCAO/POC 11/05/2002 CALL FOR LAB
 S APSPLTYP="R"
 ;DELETED THESE TAGS IHS/OKCAO/POC 3 LINES 8/18/2000
 ;I APSPMAN=1 D ^APSPMAN1 ;IHS/DSD/ENM 01/29/96 Get Mfg,Lot,Exp data
 ;I APSPMAN=2 D DTO^APSPMAN1 ;IHS/DSD/ENM 01/29/96
 ;I APSPMAN=""!(APSPMAN=3) D NMFG^APSPMAN1 ;IHS/DSD/ENM 02/15/96
 S PSOREF("DFLG")=0
 D ^PSOREF2  ;IHS/OKCAO/POC 8/18/2000
 D DSPLY G:PSOREF("DFLG") PROCESSX
 D CHECK G:PSOREF("DFLG") PROCESSX
EXD ;IHS/DSD/ENM Check %APSITE P11 for Exp Date 4/20/94
 ;I $P(%APSITE,U,11)]"" D ^PSOZEXP
 ;S PSOREF("RELEASED DATE/TIME")=PSOREF("FILL DATE") ;IHS/DSD/ENM 4/18/94
 ;S APSPZRP=PSOREF("IRXN") ;IHS/DSD/ENM 02/15/96 USED IN PSORX FOR REL
 ;IHS/DSD/ENM 02/15/96 DUE QUESTIONNAIRE CALL
 S APFLAG="RF" D ^APSPQ
 D EN^PSOR52(.PSOREF)  ; Files entry in File 52
 S APSPZRP=PSORX("PSOL",1)  ;IHS/DSD/ENM 12/14/95 USED IN PSORX FOR REL
 ;D NOW^%DTC S APSPZRD=% ;IHS/DSD/ENM 12/14/95
 S APSPLTYP="R"  ;IHS/DSD/ENM 12/14/95
 ;S DR="17////"_APSPZRD,DIE="^PSRX("_PSOREF("IRXN")_","_1_",",DA(1)=PSOREF("IRXN"),DA=PSOREF("NUMBER") D ^DIE ;IHS/DSD/ENM 12/14/95
EXDT ;LABEL EXPIRATION DATE SET ;IHS/DSD/ENM 4/20/94
 I $D(P(99)) S $P(^PSRX(PSOREF("IRXN"),9999999),"^")=+P(99)  ;IHS/DSD/ENM 09/19/96
 ;I $D(P(99)) S ^PSRX(PSOREF("IRXN"),9999999)=$S('$D(^(9999999)):P(99),1:P(99)_U_$P(^(9999999),U,2,9))
 ;D EN^PSOR52(.PSOREF) ;File entry in file 52
IHSH ;HOOK FOR DATA LINK TO IHS/PCC ;IHS/DSD/ENM 03/18/94
 ;IHS/DSD/ENM 11/27/95 NEXT LINE ADDED TO CHECK IF FILE 200 CONVERSION HAS BEEN DONE AND IF NOT GETS PROVIDER VALUE FROM FILE 16, VICE 200
 S APSPDOC1=$P($G(^VA(200,$P(^PSRX(PSOREF("IRXN"),0),U,4),0)),U,16),APCDALVR("APCDTPRV")=$S($P($G(^AUTTSITE(1,0)),U,22):$P(^PSRX(PSOREF("IRXN"),0),U,4),1:APSPDOC1)
 ;I $P(%APSITE,U,15)="Y" S APSRX=PSOREF("IRXN"),APSRCT=APSPRN,APCDALVR("APCDDATE")=DT,APCDALVR("APCDTPRV")=$P(^PSRX(PSOREF("IRXN"),0),U,4) D ^APSPCCR
 I $G(VEXRX),'$G(APSEFDT) S APSEFDT=$G(PSOREF("FILL DATE"))  ;cmi/maw 01/21/03
 I $P(%APSITE,U,15)="Y" S APSRX=PSOREF("IRXN"),APSRCT=APSPRN,APCDALVR("APCDDATE")=APSEFDT D ^APSPCCR  ;IHS/DSD/ENM 08/14/97 APSEFDT REPLACED DT
 ;----  ----  ----  ----  ----
PROCESSX D:$G(PSOREF("OLD FILL DATE"))]"" SUSDATEK^PSOUTIL(.PSOREF)
 Q
DSPLY ;
 W !!,$P(PSOREF("RX0"),"^"),?12," ",$P(^PSDRUG($P(PSOREF("RX0"),"^",6),0),"^"),?45," SIG: ",$P(PSOREF("RX0"),"^",10),?60," QTY: ",$P(PSOREF("RX0"),"^",7)
 W !,"NDC: ",$G(PSOREF("NDC"))  ;IHS/OKCAO/POC 8/18/2000
 W " ("_$G(PSOREF("AWP"))_")"  ;IHS/OKCAO/POC 8/18/2000
 W " ("_$G(PSOREF("COST"))_")"  ;IHS/OKCAO/POC 1/21/2001 IMPROVE COST
 W:PSOREF("DFLG") !,*7,"DELETED REFILL FOR RX# ",$P(PSOREF("RX0"),"^")," ",$P(^PSDRUG(PSODRUG("IEN"),0),"^"),!  ;IHS/OKCAO/POC 8/18/2000
DSPLYX Q
CHECK ;
 I '$P(PSOPAR,"^",11),$G(^PSDRUG($P(PSOREF("RX0"),"^",6),"I"))]"",DT>$G(^("I")) W !!,*7," *** Drug is inactive for Rx # "_$P(PSOREF("RX0"),"^")_" ***",! S PSOREF("DFLG")=1 G CHECKX
 I '$D(PSORX("BAR CODE")),PSOREF("PSODFN")'=PSODFN W !!,?5,*7,"Can't refill Rx # ",$P(PSOREF("RX0"),"^"),", it is not for this patient." S PSOREF("DFLG")=1 G CHECKX
 S (PSOX,PSOY)=""
 I $D(PSOSD)>1 F  S PSOX=$O(PSOSD(PSOX)) Q:PSOX']""!(PSOREF("DFLG"))  I PSOREF("IRXN")=+PSOSD(PSOX) S PSOY=PSOSD(PSOX) I $P(PSOY,"^",4)]"" D
 . S PSOREF("DFLG")=1
 . W !,*7,"Cannot refill Rx # ",$P(PSOREF("RX0"),"^")
 . S PSOREA=$P(PSOY,"^",4),PSOSTAT=$P(PSOREF("RX0"),"^",15)
 . D STATUS^PSOUTIL(PSOREA,PSOSTAT) K PSOREA,PSOSTAT
 . Q
 I PSOY="" W !,*7,"Cannot refill Rx # ",$P(PSOREF("RX0"),"^")," later Rx exists." S PSOREF("DFLG")=1
 K PSOX,PSOY G:PSOREF("DFLG") CHECKX
 I $O(^PS(52.5,"B",PSOREF("IRXN"),0)),'$G(^PS(52.5,+$O(^PS(52.5,"B",PSOREF("IRXN"),0)),"P")) W !,*7,"Rx is in suspense and cannot be refilled" S PSOREF("DFLG")=1 G CHECKX
 S PSOREF("RXSTATUS")=$P(PSOREF("RX0"),"^",15)
 I PSOREF("RXSTATUS"),PSOREF("RXSTATUS")'=6 D  G CHECKX
 . S PSOY=";"_PSOREF("RXSTATUS"),PSOX=$P(^DD(52,100,0),"^",3),PSOY=$F(PSOX,PSOY),PSOY=$P($E(PSOX,PSOY,999),";",1)
 . W !,*7,"Rx is in ",PSOY," status, cannot be refilled" S PSOREF("DFLG")=1
 . Q
 D CHKDIV G:PSOREF("DFLG") CHECKX
 D NUMBER
 S APSPRN=PSOREF("NUMBER")  ;IHS/DSD/ENM 03/18/94
 I PSOREF("NUMBER")>$P(PSOREF("RX0"),"^",9) W !?5,"Can't refill, no refills remaining." S PSOREF("DFLG")=1 G CHECKX
 D DATES
CHECKX Q
CHKDIV ;
 G:$P(PSOREF("RX2"),"^",9)=+PSOSITE CHKDIVX
 W !?5,*7,"RX # ",$P(PSOREF("RX0"),"^")," is for (",$P(^PS(59,$P(PSOREF("RX2"),"^",9),0),"^"),") division."
 I '$P($G(PSOSYS),"^",2) S PSOREF("DFLG")=1 G CHKDIVX
 D:$P($G(PSOSYS),"^",3) DIR
CHKDIVX Q
NUMBER ;
 K PSOX,PSOY
 S PSOREF("# OF REFILLS")=0
 I $G(^PSRX(PSOREF("IRXN"),1,0))]"" F PSOX=0:0 S PSOX=$O(^PSRX(PSOREF("IRXN"),1,PSOX)) Q:'PSOX  S PSOREF("# OF REFILLS")=PSOX
 S PSOREF("NUMBER")=PSOREF("# OF REFILLS")+1
 Q
DATES ;
 S PSOREF("STOP DATE")=$P(PSOREF("RX2"),"^",6)
 D NEXT^PSOUTIL(.PSOREF)
 D:$D(PSOBBC("QFLG"))&($P(PSOPAR,"^",6)) EDATE Q:$G(PSOREF("DFLG"))
 I $P(PSOPAR,"^",6),PSOREF("FILL DATE")<$P(PSOREF("RX3"),"^",2) D SUSDATE^PSOUTIL(.PSOREF)
 I PSOREF("FILL DATE")>PSOREF("STOP DATE") D
 . W !!?5,*7,"Can't refill, Refill Date "
 . W $E(PSOREF("FILL DATE"),4,5),"/",$E(PSOREF("FILL DATE"),6,7),"/"
 . W $E(PSOREF("FILL DATE"),2,3)," is past Stop Date "
 . W $E(PSOREF("STOP DATE"),4,5),"/",$E(PSOREF("STOP DATE"),6,7),"/"
 . W $E(PSOREF("STOP DATE"),2,3)
 . S PSOREF("DFLG")=1
 . Q
EDATE S PSOREF("LAST REFILL DATE")=$P(PSOREF("RX3"),"^",1)
 I PSOREF("LAST REFILL DATE"),PSOREF("FILL DATE")=PSOREF("LAST REFILL DATE") D  G DATESX
 . W !?5,"Can't refill, Fill Date already exists for ",$E(PSOREF("FILL DATE"),4,5),"/",$E(PSOREF("FILL DATE"),6,7),"/",$E(PSOREF("FILL DATE"),2,3)
 . S PSOREF("DFLG")=1
 . Q
 I PSOREF("LAST REFILL DATE"),PSOREF("FILL DATE")<PSOREF("LAST REFILL DATE") D  G DATESX
 . W !?5,"Can't refill, later Refill Date already exists for ",$E(PSOREF("LAST REFILL DATE"),4,5),"/",$E(PSOREF("LAST REFILL DATE"),6,7),"/",$E(PSOREF("LAST REFILL DATE"),2,3)
 . S PSOREF("DFLG")=1
 . Q
 I '$P(PSOPAR,"^",6),'$D(PSOREF("EAOK")),$P(PSOREF("RX3"),"^",2)>PSOREF("FILL DATE") D
 . S PSOX1=(PSOREF("NUMBER")+1)*PSOREF("DAYS SUPPLY")-10
 . W !?5,*7,"LESS THAN ",PSOX1," DAYS FOR ",PSOREF("NUMBER")+1," FILLS",! D DIR
 . K PSOX1
 . Q
 I '$P(PSOPAR,"^",6),$G(PSOREF("EAOK"))=0,$P(PSOREF("RX3"),"^",2)>PSOREF("FILL DATE") D
 . S Y=$P(PSOREF("RX3"),"^",2) D DD^%DT
 . W !!,*7,"Cannot be refilled until "_Y_"."
 . S PSOREF("DFLG")=1
 . K Y
 . Q
DATESX Q
DIR ;
 K DIR,X,Y
 S DIR(0)="Y",DIR("A")="Continue ",DIR("B")="N"
 S DIR("?")="Answer YES to Refill, NO to bypass"
 D ^DIR K DIR
 S:$D(DIRUT)!('Y) PSOREF("DFLG")=1
 K DIRUT,DTOUT,DUOUT,X,Y
 Q
NEWPT ;
 S PSOQFLG=0
 S (DFN,PSODFN)=PSOREF("PSODFN")
 D ^PSOPTPST I PSOQFLG S PSOREF("DFLG")=1,PSOQFLG=0 G NEWPTX
 D PROFILE^PSORX
NEWPTX Q
EN(PSOREF)         ; Entry Point for Batch Barcode Option
 D PROCESS
 Q
XIT K APSPDOC1
 Q
