PSORENW2 ;IHS/DSD/JCM - DISPLAYS RENEW RX INFORMATION FOR EDIT  [ 01/15/2003  3:26 PM ]
 ;;6.0;OUTPATIENT PHARMACY;**1,3,4**;11/11/2002
 ;;6.0;OUTPATIENT PHARMACY;**57,69**;09/03/97
 ;ACTUAL ACQUSITION COST ADDED IHS/OKCAO/POC 11/11/2002
 ; This routine displays the entered new rx information and
 ; asks if correct, if not allows editing of the data.
 ;------------------------------------------------------------
START ;
 S (PSORENW("DFLG"),PSORENW2("QFLG"))=0
 D DISPLAY  ; Displays information
 D ASK G:PSORENW2("QFLG")!PSORENW("DFLG") END
EN D EDIT
 G START
END D EOJ
 Q
 ;------------------------------------------------------------
DISPLAY ;
 W !!,"Rx # ",PSORENW("NRX #")
 W ?23,$E(PSORENW("FILL DATE"),4,5),"/",$E(PSORENW("FILL DATE"),6,7),"/",$E(PSORENW("FILL DATE"),2,3)
 ;W !,$G(PSORX("NAME")),?30,"#",PSORENW("QTY")
 W !,$G(PSORX("NAME")),?30,"#",PSORENW("QTY"),?45,"NDC ",PSORENW("NDC")  ;IHS/OKCAO/POC 8/18/2000
 W " ("_PSORENW("AWP")_")"  ;IHS/OKCAO/POC 8/18/2000
 W " ("_PSORENW("COST")_")"  ;IHS/OKCAO/POC 8/18/2000 IHS/OKCAO/POC 1/21/2001 IMPROVE COST
 S X=PSORENW("SIG") D SIGONE^PSOHELP W !,$G(SIG),!!,$S($G(PSODRUG("TRADE NAME"))]"":PSODRUG("TRADE NAME"),1:PSODRUG("NAME"))
 W !,PSORENW("PROVIDER NAME"),?25,PSORX("CLERK CODE")
 W !,"# of Refills: ",PSORENW("# OF REFILLS"),!
 Q
 ;
ASK ;
 K DIR,X,Y
 S DIR("A")="Is this correct"
 S DIR(0)="Y",DIR("B")="YES"
 D ^DIR K DIR
 I $D(DIRUT) S PSORENW("DFLG")=1 G ASKX
 I Y S PSORENW2("QFLG")=1
ASKX K X,Y,DIRUT,DTOUT,DUOUT,SIG
 Q
 ;
EDIT ;
 S PSORX("EDIT")=1
 D ^PSORENW3
 S PSORENW("DFLG")=0
 Q
 ;
EOJ ;
 K PSORENW2,PSORX("EDIT"),PSORENW("EDIT")
 Q
