PSORXVW ;BHAM/ISC/SAB - VIEW OF A PRESCRIPTION  [ 05/14/1998   4:04 PM ]
 ;;6.0;OUTPATIENT PHARMACY;**1**;09/03/97
 S PS="VIEW"
A1 W ! S DIC("S")="I $P(^(0),""^"",15)'=13",DIC=52,DIC(0)="QEAM",DIC("A")=PS_" PRESCRIPTION: " D ^DIC K DIC("A") G KILL:X=""!(X="^") G A1:Y<0 S DA=+Y
 D:PS="PARTIAL"  Q:$G(X)="^"
 .S DFN=$P(^PSRX(DA,0),"^",2) D DEM^VADPT I +VADM(6) W !!,*7,"PATIENT DIED "_$P(VADM(6),"^",2),! S X="^"
 .I $P($G(^PSRX(DA,0)),"^",15)=12 W !!,*7,"Medication Cancelled !",! S X=""
 I $G(PSODIV),PS'="VIEW",$P($G(^PSRX(DA,2)),"^",9)'=PSOSITE S PSPOP=0,PSPRXN=DA D CHK1^PSOUTLA G:PSPOP A1
 K PSPOP,PSPRXN S %=1 D OUT S:PS="REINSTATE" PS="CANCEL" G A1:%'=1 Q
OUT ;D ^PSORXPR S %=2 Q:PS="VIEW"
 S APSPLTYP="V" D ^PSORXPR S %=2 Q:PS="VIEW"  ;IHS/DSD/ENM 1/20/95
ASK ;IHS/DSD/ENM/POC 01/20/98 DON'T DELETE RX'S WITH REFILLS
 ;I PS="DELETE",$O(^PSRX(DA,1,0)) W !!,"YOU CAN'T DELETE RXS WITH REFILLS" S X="^" Q ;IHS/DSD/ENM/POC 01/28/98 CALL NOW MADE IN PSORXDL
 W !!,PS D YN^DICN S X=% I %Y["?" W !!,"Enter 'Y' for 'Yes' or Press Return for 'No'",! S %=2 G ASK
 S:%=2 X="^"
 Q
A11 I PSODIV,$D(^PSRX(DA,2)),+$P(^(2),"^",9),+$P(^(2),"^",9)'=PSOSITE S PSPOP=0,PSPRXN=DA D CHK^PSOUTLA Q:PSPOP
 K PSPOP,PSPRXN S %=1 D OUT1 S:PS="REINSTATE" PS="CANCEL" Q
OUT1 D ^PSORXPR S %=2 Q
 ;
KILL I PS="PARTIAL" S APSP("PM")=$G(APSPMM),APSP("PD")=$G(APSPD),APSP("PL")=$G(APSPL) ;IHS/DSD/ENM 09/02/96 MFG VAR USED AT PARTIAL RX
 I PS="VIEW" K %,DA,DIC,I,II,J,N,PHYS,PS,RFDATE,RFL,RFL1,ST,ST0,X,Y,Z,RFLL,APSPMM,APSPL,APSPD,APSP,APSPCP,APSPLTYP,APSPRXX
 Q
