PSORENW0 ;IHS/DSD/JCM - RENEW MAIN DRIVER CONTINUATION [ 01/15/2003  2:21 PM ]
 ;;6.0;OUTPATIENT PHARMACY;**1,3,4**;11/11/2002
 ;;6.0;OUTPATIENT PHARMACY;**22,83,93**;09/03/97
 ;ADDED REASON FOR CANCELLING IHS/OKCAO/POC 11/11/2002
 ;
PROCESS ;
 D ^PSORENW1
 I $D(PSORX("BAR CODE")),PSODFN'=PSORENW("PSODFN") D NEWPT
 S PSORENW("DFLG")=0,PSORENW("FILL DATE")=PSORNW("FILL DATE")
 ;W !!,"Now Renewing Rx # "_PSORENW("ORX #")_"   Drug: "_$P($G(^PSDRUG(+$G(PSORENW("DRUG IEN")),0)),"^"),!
 W !!,"Now Renewing Rx # "_PSORENW("ORX #")_"   Drug: "_$P($G(^PSDRUG(+$G(PSORENW("DRUG IEN")),0)),"^")  ;TAKE OUT THE LINE FEED IHS/OKCAO/POC 11/05/2002
 D PRINT^APSQLAB W !  ;PRINT LAB DATA IHS/OKCAO/POC 11/05/2002
 D  ;LET'S WRITE THE COMMENTS FOR CANCELLED RXS IHS/OKCAO/POC 7/12/2001 FOR PATCH 4
 .N PSOASUB
 .;S PSOASUB=0 F  S PSOASUB=$O(^PSRX(PSORENW("OIRXN"),"A",PSOASUB)) Q:PSOASUB'=+PSOASUB  D
 .S PSOASUB=$O(^PSRX(PSORENW("OIRXN"),"A","A"),-1) Q:PSOASUB=""  D
 ..I $P(^PSRX(PSORENW("OIRXN"),"A",PSOASUB,0),U,2)="C" W IORVON,"This Prescription was cancelled with comments:  ",!,$P(^(0),U,5),IORVOFF D DIR
 ;END OF CHANGES IHS/OKCAOPOC 7/12/2001
 D CHECK G:PSORENW("DFLG") PROCESSX
 D FILDATE
 D DRUG G:PSORENW("DFLG") PROCESSX
 D RXN G:PSORENW("DFLG") PROCESSX
 ;SET 3RD PEICE OF ZERO NODE = TO PATIENT STATUS IHS/OKCAO/POC 8/18/2000
 I $G(PSORX("PATIENT STATUS"))]"" D
 .N DIC
 .S DIC="53",X=PSORX("PATIENT STATUS"),DIC(0)="MNO" D ^DIC
 .I Y>0 S $P(PSORENW("RX0"),"^",3)=+Y
 D DSPLY^PSORENW3 G:PSORENW("DFLG") PROCESSX
 ;D DTO^APSPMAN2  ;IHS/OKCAO/POC 8/18/2000
 D EDIT I PSORENW("DFLG") G PROCESSX
 D EN^PSORN52(.PSORENW)
ENM ;--- --- --- ---
 ;IHS/DSD/ENM 09/13/96 HOOK FOR PCC PARAM ARRAY
 I $P(%APSITE,U,15)="Y" D ^APSPCCV
 ;--- --- --- ---
 ;IHS/DSD/ENM 11/28/95 PCC LINK
 S APSPDOC1=$P($G(^VA(200,PSORENW("PROVIDER"),0)),U,16),APCDALVR("APCDTPRV")=$S($P($G(^AUTTSITE(1,0)),U,22):PSORENW("PROVIDER"),1:APSPDOC1)
 S APCDALVR("APCDPAT")=PSODFN,APCDALVR("APCDLOC")=DUZ(2)
 I $P(%APSITE,U,15)="Y" S APSRX=PSORENW("IRXN"),APCDALVR("APCDDATE")=APSEFDT S:PSORENW("PATIENT STATUS")'=1 APCDALVR("APCDCAT")="I" D ^APSPCCN  ;IHS/DSD/ENM 12/08/97 PSORENW("IRXN") ADDED APCDCAT IHS/OKCAO/POC 8/18/2000
 ;I $P(%APSITE,U,15)="Y" S APSRX=PSORENW("IRXN"),APCDALVR("APCDDATE")=APSEFDT D ^APSPCCN ;IHS/DSD/ENM 12/08/97 PSORENW("IRXN") ADDED
 ;I $P(%APSITE,U,15)="Y" S APSRX=PSORENW("OIRXN"),APCDALVR("APCDDATE")=PSORENW("FILL DATE") D ^APSPCCN
 ;--- --- --- ---
 D:$D(^PS(52.5,"B",PSORENW("OIRXN"))) DELETE
 D RNPSOSD^PSOUTIL
 D CAN
PROCESSX W:PSORENW("DFLG") !,*7,"RENEWED RX DELETED",!
 D:$G(PSORENW("OLD FILL DATE"))]"" SUSDATEK^PSOUTIL(.PSORENW)
 K PSORENW,PSODRUG,PSORX("PROVIDER NAME"),PSORX("CLINIC")
 S:$G(PSORENW("FROM"))="" (PSORENW("DFLG"),PSORENW("QFLG"))=0
 Q
 ;
CHECK ;
 I '$D(PSORX("BAR CODE")),PSORENW("PSODFN")'=PSODFN W !!,?5,*7,"Can't renew Rx # ",$P(PSORENW("RX0"),"^"),", it is not for this patient." S PSORENW("DFLG")=1 G CHECKX
 ;
 S (PSOX,PSOY)=""
 I $D(PSOSD)>1 F  S PSOX=$O(PSOSD(PSOX)) Q:PSOX']""!(PSORENW("DFLG"))  I PSORENW("OIRXN")=+PSOSD(PSOX) S PSOY=PSOSD(PSOX) I $P(PSOY,"^",3)]"" D
 . S PSORENW("DFLG")=1
 . W !,*7,"Cannot renew Rx # ",$P(PSORENW("RX0"),"^")
 . S PSOREA=$P(PSOY,"^",3),PSOSTAT=$P(PSORENW("RX0"),"^",15)
 . D STATUS^PSOUTIL(PSOREA,PSOSTAT) K PSOREA,PSOSTAT
 . Q
 I PSOY="" W !,*7,"Cannot renew Rx # ",$P(PSORENW("RX0"),"^")," later Rx exists." S PSORENW("DFLG")=1
 K PSOX,PSOY G:PSORENW("DFLG") CHECKX
 ;
 D CHKDIV G:PSORENW("DFLG") CHECKX
 ;
 I $A($E(PSORENW("ORX #"),$L(PSORENW("ORX #"))))=90 D
 . W !,*7,"Cannot renew Rx # ",PSORENW("ORX #"),", Max number of renewals reached."
 . S PSORENW("DFLG")=1
 . Q
 ;
 D CHKPRV^PSOUTIL
CHECKX Q
 ;
CHKDIV ;
 G:$P(PSORENW("RX2"),"^",9)=+PSOSITE CHKDIVX
 W !?5,*7,"RX # ",$P(PSORENW("RX0"),"^")," is for (",$P(^PS(59,$P(PSORENW("RX2"),"^",9),0),"^"),") division."
 I '$P($G(PSOSYS),"^",2) S PSORENW("DFLG")=1 G CHKDIVX
 D:$P($G(PSOSYS),"^",3) DIR
CHKDIVX Q
 ;
DRUG ;
 K PSOY
 S PSOY=PSORENW("DRUG IEN"),PSOY(0)=^PSDRUG(PSOY,0)
 D SET^PSODRG
 D POST^PSODRG S:PSORX("DFLG") PSORENW("DFLG")=1
 S:$D(PSONEW("STATUS")) PSORENW("STATUS")=PSONEW("STATUS")
 K PSOY,PSORX("DFLG"),PSONEW("STATUS")
 Q
 ;
RXN ;
 K PSOX
 S PSOX=$E(PSORENW("ORX #"),$L(PSORENW("ORX #")))
 S PSORENW("NRX #")=$S(PSOX?1N:PSORENW("ORX #")_"A",1:$E(PSORENW("ORX #"),1,$L(PSORENW("ORX #")-1))_$C($A(PSOX)+1))
RXNX K PSOX
 Q
 ;
FILDATE ;
 S PSORENW("IRXN")=PSORENW("OIRXN")
 ;D NEXT^PSOUTIL(.PSORENW)  ;IHS/DSD/ENM 08/12/96
 ;I PSORENW("FILL DATE")<$P(PSORENW("RX3"),"^",2) D SUSDATE^PSOUTIL(.PSORENW) ;IHS/DSD/ENM 08/12/96
 D EM^PSOUTIL(.PSORENW)  ;IHS/DSD/ENM 08/12/96 IHS RENEW FILL DT
 K PSORENW("IRXN")
 Q
 ;
EDIT ;
 K DIR,X,Y
 S DIR(0)="Y",DIR("B")=$S($G(DUZ("AG"))'="I":"Y",1:"N")
 S DIR("A")="Edit renewed Rx "
 S DIR("?")="Answer YES to edit the renewed Rx, NO not to."
 D ^DIR K DIR
 S:$D(DIRUT) PSORENW("DFLG")=1
 G:PSORENW("DFLG") EDITX
 I Y D EN^PSORENW2
EDITX K X,Y,DIRUT,DTOUT,DUOUT
 Q
 ;
DELETE ;
 K DA,DIK
 S DA=$O(^PS(52.5,"B",PSORENW("OIRXN"),0)),DIK="^PS(52.5,"
 D ^DIK K DIK,DIC
 Q
 ;
CAN ;
 K REA,DA,MSG
 S REA="C",DA=PSORENW("OIRXN")
 S MSG="RENEWED"
 S PSCAN(PSORENW("ORX #"))=DA_"^C"
 D CAN^PSOCAN
 K REA,DA,MSG,PSCAN
 Q
 ;
DIR ;
 S DIR(0)="Y",DIR("A")="CONTINUE ",DIR("B")="N"
 S DIR("?")="Answer YES to Continue, NO to bypass"
 D ^DIR K DIR
 S:$D(DIRUT)!('Y) PSORENW("DFLG")=1
DIRX K DIRUT,DTOUT,DUOUT,X,Y
 Q
NEWPT ;
 S PSOQFLG=0
 S PSODFN=PSORENW("PSODFN")
 D ^PSOPTPST I PSOQFLG S PSORENW("DFLG")=1,PSOQFLG=0 G NEWPTX
 D PROFILE^PSORX
NEWPTX Q
 ;
EN(PSORENW)        ; Entry Point for Batch Barcode Option
 D PROCESS
 Q
XIT K APSPDOC1
 Q
