PSORXL ;BHAM/ISC/SAB - ACTION TO BE TAKEN ON PRESCRIPTIONS  [ 01/27/2003  11:07 AM ]
 ;;6.0;OUTPATIENT PHARMACY;**3,4**;09/03/97
 ;;6.0;OUTPATIENT PHARMACY;**31,58,66,60,88,59,104,114**;09/03/97
 ;IHS/DSD/ENM 06/14/96 Mod's at QLBL+1, P1+2, ZZ1
 S:'$D(PPL) PPL=$G(PSORX("PSOL",1)) G:$P(PSOPAR,"^",26) P
LBL W !! S DIR("A")="LABEL: QUEUE"_$S($P(PSOPAR,"^",23):"/HOLD",1:"")_$S($P(PSOPAR,"^",24):"/SUSPEND",1:"")_$S($P(PSOPAR,"^",26):"/LABEL",1:"")_" or '^' to bypass "
 S DIR("?",1)="Enter 'Q' to queue labels to print",DIR("?")="Enter '^' to bypass label functions",DIR("?",4)="Enter 'S' to suspend labels to print later"
 S DIR("?",2)="Enter 'H' to hold label until Rx can be filled",DIR("?",3)="Enter 'P' for Rx profile"
 S:$P(PSOPAR,"^",26) DIR("?",5)="Enter 'L' to print labels without queuing"
 S DIR(0)="SA^P:PROFILE;Q:QUEUE"_$S($P(PSOPAR,"^",23):";H:HOLD",1:"")_$S($P(PSOPAR,"^",24):";S:SUSPENSE",1:"")_$S($P(PSOPAR,"^",26):";L:PRINT",1:""),DIR("B")="Q" D ^DIR G:$D(DIRUT)!($D(DUOUT)) EX
 K DIR S LBL=Y G Q:Y="Q",S:Y="S",H1:Y="H",P:Y="L" I Y="P" W ! S PSDFN=DFN,PSFROM="" D ^PSODSPL K PSDFN,PSFROM G LBL
EX I $D(DUOUT)!$D(DIRUT) K DIR,X,DIRUT,DUOUT,ACT,Y,DTOUT,PPL,REPRINT Q
Q S PPL1=1 G:$G(PPL)']"" D1 S PSNP=0,PSL=1 I $G(PSOFROM)="NEW",$P(PSOPAR,"^",8) S PSNP=1
 I $G(PSOLAP)]"",$G(PSOLAP)'=ION G QLBL
Q1 W ! K POP S %ZIS("B")="",%ZIS="MNQ",%ZIS("A")="Select LABEL DEVICE: " D ^%ZIS S PSLION=ION K %ZIS("A") G:POP!(IO=IO(0)) LBL S PSOLAP=ION
 F J=0,1 S @("PSOBAR"_J)="" I $D(^%ZIS(2,^%ZIS(1,IOS,"SUBTYPE"),"BAR"_J)) S @("PSOBAR"_J)=^("BAR"_J)
 S PSOBARS=PSOBAR1]""&(PSOBAR0]"")&$P(PSOPAR,"^",10)
 D ^%ZISC S PSL=0
 ;IHS/DSD/ENM 09/15/94 QLBL,+1 PSOLBL changed to APSPLBL
QLBL ;S ZTRTN="DQ^PSOLBL",ZTIO=$S($G(SUSPT):PSLION,1:PSOLAP),ZTDESC="Outpatient Pharmacy "_$S($G(SUSPT):"SUSPENSE ",$G(DG):"DRUG INTERACTION ",1:"")_"LABELS OUTPUT ROUTINE",ZTDTH=$S($G(PSOTIME):PSOTIME,1:$H),PDUZ=DUZ
 S ZTRTN="DQ^APSPLBL",ZTIO=$S($G(SUSPT):PSLION,1:PSOLAP),ZTDESC="Outpatient Pharmacy "_$S($G(SUSPT):"SUSPENSE ",$G(DG):"DRUG INTERACTION ",1:"")_"LABELS OUTPUT ROUTINE",ZTDTH=$S($G(PSOTIME):PSOTIME,1:$H),PDUZ=DUZ
 F G="PPL1","PSOSYS","DFN","PSOPAR","PDUZ","PCOMX",$S($G(SUSPT):"PFION",1:"PSOLAP"),"PPL","PSOSITE","RXP","RXY","REPRINT","COPIES","SIDE","PSOSUSPR","PSOBARS","PSOBAR1","PSOBAR0","PSODELE","PSOPULL","PSTAT","PSODBQ" S:$D(@G) ZTSAVE(G)=""
 S ZTSAVE("%APSITE")="" ;IHS/DSD/ENM 6/10/97
 S ZTSAVE("APSPMAN")="" ;IHS/DSD/ENM 1-10-95
 ;F SAVE="APSPZRP","DUZ","PSOFROM" S ZTSAVE(SAVE)="" ;IHS/OKCAO/POC 7/7/98
 F SAVE="APSPZRP","DUZ","PSOFROM","%APSITE3" S ZTSAVE(SAVE)="" ;IHS/OKCAO/POC 7/7/98
 S ZTSAVE("PSORX(")="" D ^%ZISC,^%ZTLOAD S PPL1=99 W:$D(ZTSK)&('$G(SUSPT)) !!,"LABEL(S) QUEUED TO PRINT",!! K G,PDUZ K:'$G(SUSPT) ZTSK Q:$G(DG)
 G:'$G(PSNP) QUEUP G:$G(PSOPRFLG) QUEUP S:'$D(PSOPRPAS) PSOPRPAS=$P(PSOPAR,"^",13)
PLBL S PSOION=ION
 I '$D(PSOPROP)!($G(PSOPROP)=ION) W *7,!,"PROFILES MUST BE SENT TO PRINTER !!",! K IOP,%ZIS,IO("Q"),POP S %ZIS="MNQ",%ZIS("A")="Select PROFILE DEVICE: " D ^%ZIS K %ZIS("A") G:POP QUEUP G:$E(IOST)["C"!(PSOION=ION) PLBL S PSOPROP=ION
QPRF S ZTRTN="DQ^PSOPRF",ZTIO=PSOPROP,ZTDESC="Outpatient Pharmacy "_$S($G(SUSPT):"SUSPENSE ",1:"")_"PATIENT PROFILES",ZTDTH=$S($G(PSOTIME):PSOTIME,1:$H)
 F G="PSOPAR","PSODTCUT","PSOPRPAS","DFN","PSOSITE","NEW1","NEW11","PSOBMST","PFIO","PPL" S:$D(@G) ZTSAVE(G)=""
 D ^%ZTLOAD W:$D(ZTSK)&('$G(SUSPT)) !,"PROFILE IS QUEUED TO PRINT",!! K G K:'$G(SUSPT) ZTSK D ^%ZISC
QUEUP S PSNP=0 G D1
 Q
S G S^PSORXL1
SUS G SUS^PSORXL1
H1 S PPL1=1 S:'$D(PPL) PPL=$G(PSORX("PSOL",PPL1))
 G:$G(PPL)']"" D1 D FLD^PSOUTL I $D(DUOUT)!($D(DIRUT)) K DIRUT,DUOUT,FLD,DIR G LBL
H K SPPL G:$D(DTOUT) D1 S SPPL="" F PI=1:1 Q:$P(PPL,",",PI)=""  D
 .S DA=$P(PPL,",",PI) I $P(^PSRX(DA,0),"^",15)<10,$P(^(0),"^",15)'=4 D H^PSOHLD Q
 .I $P(^PSRX(DA,0),"^",15)=4 S SPPL=SPPL_DA_"," Q
 I $G(SPPL)]"" D
 .W !!,*7,"Drug Interaction Rx(s) " F I=1:1 Q:$P(SPPL,",",I)=""  W $P(^PSRX($P(SPPL,",",I),0),"^")_", "
 .S PPL=SPPL,DG=1 D QLBL K DG,SPPL
D1 I $O(PSORX("PSOL",$G(PPL1))) S PPL1=$O(PSORX("PSOL",PPL1)),PPL=PSORX("PSOL",PPL1) G @$S(LBL="H":"H",LBL="L":"P1",1:"QLBL")
 K LBL,PPL1,PPL,DIR,%DT,%,SD,COUNT,EXDT,L,PDUZ,REF,REPRINT,RFDATE,RFL1,RFLL,RXN,WARN,ZY,FLD,PI,ZD,ACT,X,Y,DIRUT,DUOUT,DTOUT,DIROUT Q
P S PPL1=1 S:'$D(PPL) PPL=$G(PSORX("PSOL",1)) G:$G(PPL)']"" D1
 I $G(PSOLAP)']"" W ! K POP,ZTSK S %ZIS="M",%ZIS("A")="Select LABEL DEVICE: " D ^%ZIS K %ZIS("A") G:POP LBL S PSOLAP=ION
PZ S IOP=PSOLAP D ^%ZIS ;IHS/DSD/ENM 02/26/97 PZ ADDED
 I POP W !,"The label printer is busy, do you want to wait? " S %=1 D YN^DICN K POP Q:%=2  K %,%Y G PZ ;IHS/DSD/ENM 02/26/97
 F J=0,1 S @("PSOBAR"_J)="" I $D(^%ZIS(2,^%ZIS(1,IOS,"SUBTYPE"),"BAR"_J)) S @("PSOBAR"_J)=^("BAR"_J)
 ;IHS/DSD/ENM 10/07/95 P1 copied, P1+1 split
P1 ;S PSOBARS=PSOBAR1]""&(PSOBAR0]"")&$P(PSOPAR,"^",10),PDUZ=DUZ D DQ1^PSOLBL,^%ZISC
ZZ1 ;IHS/DSD/ENM 10/07/95 RTN call to APSPLBL
 S PDUZ=DUZ D DQ1^APSPLBL,^%ZISC
 G:'$P(PSOPAR,"^",8)!(+$G(REPRINT)) D1 I $G(PSOPROP)']"" S PSOION=ION,%ZIS="M",%ZIS("A")="Select PROFILE DEVICE: " D ^%ZIS K %ZIS("A") G:POP D1 S PSOPROP=ION
 S IOP=PSOPROP D ^%ZIS D DQ^PSOPRF,^%ZISC G D1
 Q
RELES ;CALLED FROM APSPLBL--- --- --- --- --- IHS/OKCAO/POC 7/7/98
 ;IHS/DSD/ENM 12/01/95 RX RELEASE FEATURE
 ;WHAT ABOUT LABEL REPRINTING?? PSOFROM NOT DEFINED SO $G IT
 I $G(PSOFROM)="NEW"!($G(PSOFROM)="REFILL")!($G(PSOFROM)="FAST")!($G(PSOFROM)="PARTIAL")&($D(^XUSEC("PSORPH",DUZ))) D  ;IHS/DSD/ENM 11/30/95 RELEASE DT SET
 .I $G(VEXRX) S APSPZRP=$G(PPL)  ;cim/maw 11/18/02 QUICK FIX
 .Q:$G(APSPZRP)']""
 .F APSP1=1:1 Q:$P(APSPZRP,",",APSP1)=""  S RXP=$P(APSPZRP,",",APSP1) D  ;GET RELEASE INFO 
 ..;S RXP=APSPZRP,PSRH=DUZ,PSIN=$P($G(^PS(59.7,1,49.99)),"^",2)
 ..;D  ;IHS/OKCAO/POC 8/18/2000
 ..S PSRH=DUZ,PSIN=$P($G(^PS(59.7,1,49.99)),"^",2)
 ..S APSPBIEN=RXP ;RXP GETS KILLED NEED IT IHS/OKCAO/POC 8/18/2000
 ..S APSPNOPR=1 D ^APSPDISP ;IHS/OKCAO/POC SET VARIABLE FOR NO PRINT RELEASE INFO
 ..K APSPNOPR ;IHS/OKCAO/POC 7/7/98
 ..D  ;IHS/OKCAO/POC 8/18/2000
 ...N APSQPST
 ...Q:$G(PSOFROM)="PARTIAL"  ;NO GO IF PARTIAL
 ...S APSQPST=$$EN^APSQBRES(APSPBIEN,$O(^PSRX(APSPBIEN,1,"A"),-1),"A")
 ..K APSPBIEN
 ..Q
 .Q
 Q
