PSORXRPT ;BHAM/ISC/SAB - REPRINT OF A PRESCRIPTION LABEL  [ 05/14/1998   4:04 PM ]
 ;;6.0;OUTPATIENT PHARMACY;**1**;09/03/97
 ;;6.0;OUTPATIENT PHARMACY;**28,31,114**;09/03/97
 I '$D(PSOPAR) D ^PSOLSET I '$D(PSOPAR) G KILL
 ;IHS/DSD/ENM 12/23/97 APSPLTYP ADDED TO N-LINE
LRP K REPRINT,APSPLTYP W !! S DIC("S")="I $P(^(0),""^"",15)<10,+$G(^(2))",DIC="^PSRX(",DIC("A")="REPRINT LABEL FOR PRESCRIPTION: ",DIC(0)="QEAZ" D ^DIC K P,DIC("A") K:Y<0 PCOMX G KILL:Y<0!("^"[X)
 S (PPL,DA,RX)=+Y,PDA=Y(0),RXF=0,ZD=DT,REPRINT=1
 I DT>$P(^PSRX(RX,2),"^",6) W !!,*7,"Medication Expired on "_$E($P(^PSRX(RX,2),"^",6),4,5)_"-"_$E($P(^(2),"^",6),6,7)_"-"_$E($P(^(2),"^",6),2,3) S $P(^PSRX(RX,0),"^",15)=11 G LRP
 S DFN=$P(PDA,"^",2) D DEM^VADPT I $P(VADM(6),"^",2)]"" D  G LRP
 .W *7,!!,$P(^DPT($P(PDA,"^",2),0),"^")_" Died "_$P(VADM(6),"^",2)_".",!
 .S $P(^PSRX(RX,0),"^",15)=12,PCOM="Patient Expired "_$P(VADM(6),"^",2),ST="C"
 .D ACT1,KILL
 S X=$O(^PS(52.5,"B",DA,0)) I X,'$G(^PS(52.5,X,"P")) W !,*7,"RX MAY NOT BE PRINTED using this option, use SUSPENSE FUNCTIONS Options." K X G LRP
 K X
 I $D(^PS(52.4,DA)) W !,"PRESCRIPTION IS NON-VERIFIED",!! G LRP
 S DFN=$P(^PSRX(DA,0),"^",2) I $D(^PS(52.4,"AREF",DFN,DA)) W !,"PRESCRIPTION IS WAITING FOR OTHERS TO BE VERIFIED",!! G LRP
 I $G(PSODIV),$D(^PSRX(DA,2)),+$P(^(2),"^",9),+$P(^(2),"^",9)'=PSOSITE S PSPOP=0,PSPRXN=DA D CHK1^PSOUTLA G:PSPOP LRP
 I $P(PDA,"^",15)=3 W !?3,"PRESCRIPTION IS ON HOLD" G LRP
 I $P(PDA,"^",15)=4 W !?3,"PRESCRIPTION IS PENDING DUE TO DRUG/DRUG INTERACTIONS" G LRP
 I $P(PDA,"^",15)=12 W !?3,"PRESCRIPTION IS CANCELLED" G LRP
 S COPIES=$S($P(PDA,"^",18)]"":$P(PDA,"^",18),1:1)
ZZ ;IHS/DSD/ENM 09/14/94 Nbr of Copies changed to 999
 ;K DIR S DIR("A")="NUMBER OF COPIES? ",DIR("B")=COPIES,DIR(0)="N^1:99:0",DIR("?")="ENTER THE NUMBER OF COPIES YOU WANT (1 TO 99)"
 K DIR S DIR("A")="NUMBER OF COPIES? ",DIR("B")=COPIES,DIR(0)="N^1:999:0",DIR("?")="ENTER THE NUMBER OF COPIES YOU WANT (1 TO 999)"
 D ^DIR K DIR G:$D(DTOUT)!($D(DUOUT))!($D(DIRUT))!($D(DIROUT)) KILL S COPIES=X
ZZE ;IHS/DSD/ENM 09/15/94 next 4 lines disabled (for VA labels)
 ;K DIR S DIR("A")="PRINT 'LEFT' SIDE OF LABEL ONLY? ",DIR(0)="SA^Y:YES;N:NO",DIR("B")="N",DIR("?",1)="If both sides of the label are to print press Return for default."
 ;S DIR("?")="Else if only package and mailing label are to print enter 'Y'" D ^DIR K DIR I $D(DUOUT) D KILL G LRP
 ;G:$D(DTOUT)!($D(DIRUT))!($D(DIROUT)) KILL
 ;S SIDE=$S(X="Y":1,1:0) D ACT I $D(DUOUT)!($D(DTOUT))!($D(DIRUT))!($D(DIROUT)) D KILL G LRP
 D ACT I $D(DUOUT)!($D(DTOUT))!($D(DIROUT)) D KILL G LRP ;IHS/DSD/ENM 9-15-94 ;DIRUT REMOVED
 G LRP:$D(PCOM)
 F I=1,2,4,6,7,10,13,16 S P(I)=$P(PDA,"^",I)
 S P(6)=+P(6) I $D(^PSRX(DA,"TN")),^("TN")]"" S P(6)=^("TN")
 W !!,P(1),?23,$E(P(13),4,5),"/",$E(P(13),6,7),"/",$E(P(13),2,3),!,$S($D(^DPT(+P(2),0)):$P(^(0),"^"),1:"NOT ON FILE"),?30,"#",P(7),!,P(10)
 W !!,$S((P(6)=+P(6))&$D(^PSDRUG(P(6),0)):$P(^(0),"^"),1:P(6)),! S PHYS=$S($D(^VA(200,+P(4),0)):$P(^(0),"^"),1:"UNKNOWN"),ZCK=$P($G(^VA(200,+P(16),0)),"^",2) W PHYS,?25,ZCK,! K PHYS ;IHS/DSD/ENM 3.23.95 G INITIALS
 ;W !!,$S((P(6)=+P(6))&$D(^PSDRUG(P(6),0)):$P(^(0),"^"),1:P(6)),! S PHYS=$S($D(^VA(200,+P(4),0)):$P(^(0),"^"),1:"UNKNOWN") W PHYS,?25,P(16),! K PHYS
 ;D @$S($P($G(PSOPAR),"^",26):"^PSORXL",1:"Q^PSORXL") K PSPOP,PPL,COPIES,SIDE,REPRINT,PCOM,IOP,PSL,PSNP G LRP ;IHS/DSD/ENM 10/23/96
 D P^PSORXL K PSPOP,PPL,COPIES,SIDE,REPRINT,PCOM,IOP,PSL,PSNP G LRP ;IHS/DSD/ENM 10/23/96
 ;
 ;IHS/DSD/ENM 09/07/95 'O' ADDED TO DIR(0) BELOW
ACT K DIR S DIR("A")="COMMENTS: ",DIR(0)="FAO^5:60",DIR("?")="5-60 characters input required for activity log." S:$G(PCOMX)]"" DIR("B")=$G(PCOMX)
 ;D ^DIR K DIR Q:$D(DUOUT)!($D(DTOUT))!($D(DIRUT))!($D(DIROUT))  S (PCOM,PCOMX)=X
 D ^DIR K DIR Q:$D(DUOUT)!($D(DTOUT))!($D(DIROUT))  S (PCOM,PCOMX)=X ;IHS/DSD/ENM 09/07/95 DIRUT REMOVED
 I '$D(PSOCLC) S PSOCLC=DUZ
ACT1 S RXF=0 F J=0:0 S J=$O(^PSRX(DA,1,J)) Q:'J  S RXF=J
 S IR=0 F J=0:0 S J=$O(^PSRX(DA,"A",J)) Q:'J  S IR=J
 S IR=IR+1,^PSRX(DA,"A",0)="^52.3DA^"_IR_"^"_IR
 D NOW^%DTC S ^PSRX(DA,"A",IR,0)=%_"^"_$S($G(ST)'="C":"W",1:"C")_"^"_DUZ_"^"_RXF_"^"_PCOM_$S($G(ST)'="C":" ("_COPIES_" COPIES)",1:""),PCOMX=PCOM K PC,IR,PS,PCOM,XX,%,%H,%I,RXF
 Q
 ;
KILL K %,DIR,DUOUT,DTOUT,DIROUT,DIRUT,PCOM,PCOMX,C,DA,DIC,I,J,JJJ,K,RX,RXF,X,Y,Z,ZD,DFN,P,PDA,PSPRXN,COPIES,SIDE,PPL,REPRINT D KVA^VADPT
 K APSHRN,APSP,APSPDY,APSPLOT,APSPM0,APSPMF,APSPZ,APSPZZ,APSPZZN,ARRAY,LOT,PSZB,PSZE,PSZK,PSZL,PSZQ,PSZRM,PSZTAB,PSZW ;IHS/DSD/ENM 01/24/97
