PSOSUINV ; BHAM/ISC/SAB - UPDATE OR INITIALIZE INVENTORY  [ 02/20/2001  3:48 PM ]
 ;;6.0;OUTPATIENT PHARMACY;**3**;09/03/97
 S DIR("A",1)="1     Update Current Inventory",DIR("A",2)="2     Initialize Inventory"
 S DIR("A")="CHOOSE 1 OR 2> ",DIR(0)="SA^1:Update Current Inventory;2:Initialize Inventory" D ^DIR G:$D(DUOUT)!($D(DIROUT))!($D(DIRUT)) EX K DIR S F=Y-1
A W ! S (DIE,DIC)="^PSDRUG(",DIC(0)="QEAM",DIC("W")="I $D(^PSDRUG(Y,""I"")),^(""I""),^(""I"")'>DT W *7,?45,""INACTIVE DRUG""" D ^DIC G:"^"[X EX G:Y<0 A
 ;K DIC S DA=+Y,DR="12;15;13;1000:99999;W !,$P(^DD(50,16,0),""^"",1),"" is "" W:$D(^PSDRUG(DA,660)) $P(^(660),""^"",6)"
 K DIC S DA=+Y,DR="12;15;13;31;1000:99999;W !,$P(^DD(50,16,0),""^"",1),"" is "" W:$D(^PSDRUG(DA,660)) $P(^(660),""^"",6)" ;ADDED FIELD NDC IHS/OKCAO/POC 1/13/00
 W !!,$P(^PSDRUG(DA,0),"^"),?45,"CURRENT INVENTORY: ",$S($D(^(660.1)):^(660.1),1:0) L +^PSDRUG(DA) D ^DIE L -^PSDRUG(DA) G A:'$D(^PSDRUG(DA,660))!($D(Y))
B R !,"UNITS RECEIVED: ",X:DTIME S:'$T X="^" G A:"^"[X,Q:X?1"?".E,U:X?1N.N0.1"."0.1N1"D" S X=X*$P(^PSDRUG(DA,660),"^",5)
 ;S X=+X I X'?1N.N W *7,"  ??" G Q
U S X=+X I X'?1N.N0.1"."0.1N W *7,"  ??" G Q ;IHS/OKCAO/POC 2/9/99 ALLOW ONE DECIMAL
 W !,$S(F:"SET INVENTORY TO ",1:"UPDATE INVENTORY BY "),X," UNITS?  YES//" R Y:DTIME G B:"Y"'[$E(Y,1) S ^PSDRUG(DA,660.1)=$S(F:X,'$D(^PSDRUG(DA,660.1)):X,1:^(660.1)+X) W ?45,"NEW INVENTORY: ",^(660.1) G A
 ;NEXT LINE CHANGED TO CALL UPDATING LOG OF INVENTORY IHS/OKCAO/POC 9/27/99
 ;W !,$S(F:"SET INVENTORY TO ",1:"UPDATE INVENTORY BY "),X," UNITS?  YES//" R Y:DTIME G B:"Y"'[$E(Y,1) S ^PSDRUG(DA,660.1)=$S(F:X,'$D(^PSDRUG(DA,660.1)):X,1:^(660.1)+X) W ?45,"NEW INVENTORY: ",^(660.1) S AZOUQTY=X,X="AZODRGIN" X ^%ZOSF("TEST") D UP^AZODRGIN:$T K AZOUQTY G A
Q W !!?5,"ENTER THE NUMBER OF ORDER UNITS (CASES, BOXES, BOTTLES, ETC.) RECEIVED."
 W !?5,"IF YOU WISH TO UPDATE THE INVENTORY BY DISPENSING UNITS, TYPE THE NUMBER"
 W !?5,"OF UNITS FOLLOWED BY THE LETTER 'D'.",! G B
 Q
EX K DIR,DUOUT,DTOUT,DIRUT,DIC,DIE,X,Y,DA,DR,DIR,F,DI,D0
 Q
