PSOSUTL ;BHAM/ISC/RTR - SUSPENSE UTILITY ROUTINE [ 02/05/2002  3:47 PM ]
 ;;6.0;OUTPATIENT PHARMACY;**4**;09/03/97
 ;;6.0;OUTPATIENT PHARMACY;**132,137,173**;09/03/97
AREC1 S SFN=$O(^PS(52.5,"B",RX,0)) Q:'SFN
 D NOW^%DTC S DTTM=% S COM="Suspense Label Pulled Early"_$S($G(^PS(52.5,SFN,"P"))=2:" (REPRINT)",1:"")_$S($G(RXP):" (PARTIAL)",1:"") S CNT=0 F JJ=0:0 S JJ=$O(^PSRX(RX,"A",JJ)) Q:'JJ  S CNT=JJ
 I $G(^PS(52.5,SFN,"P"))=2 S (SUSREP,REPRINT)=""
 S $P(^PSRX(RX,0),"^",15)=0 D DEL K PSODEL S RFCNT=0 F RF=0:0 S RF=$O(^PSRX(RX,1,RF)) Q:'RF  S RFCNT=RF
 ;IHS/ITSC/ENM 02/05/02 VA PATCH CHANGE ADDED TO NEXT LINE
 I 'RFCNT,'$G(RXP) S (X,OLD)=$P(^PSRX(RX,2),"^",2),DA=RX,DR="22///"_DT_";101///"_DT_";25///"_DT,DIE=52 L +^PSRX(DA):0 D ^DIE K DIE L -^PSRX(DA) Q:$D(DTOUT)!($D(DUOUT))
 ;IHS/ITSC/ENM 02/05/02 VA PATCH CHANGE ADDED TO NEXT LINE
 I RFCNT,'$G(RXP) S (OLD,X)=+$P($G(^PSRX(RX,1,RFCNT,0)),"^"),DA(1)=RX,DA=RFCNT,DIE="^PSRX("_DA(1)_",1,",DR=".01///"_DT_";10.1///"_DT L +^PSRX(RX):0 D ^DIE K DIE L -^PSRX(RX) S $P(^PSRX(RX,3),"^")=DT S DA=DA(1)
 S CNT=CNT+1,^PSRX(RX,"A",0)="^52.3DA^"_CNT_"^"_CNT L +^PSRX(RX):0 S ^PSRX(RX,"A",CNT,0)=DTTM_"^"_"S"_"^"_DUZ_"^"_$S(RFCNT'<0&(RFCNT<6):RFCNT,$G(RXP):6,1:(RFCNT+1))_"^"_COM L -^PSRX(RX)
 Q
DEL I PSODELE S PSOSDEL=1,DA=SFN,DIK="^PS(52.5," D ^DIK K DIK Q
 I 'PSODELE S NODE=^PS(52.5,SFN,0) K ^PS(52.5,"C",$P(NODE,"^",2),SFN),^PS(52.5,"AC",$P(NODE,"^",3),$P(NODE,"^",2),SFN) S $P(^PS(52.5,SFN,0),"^",2)=DT,^PS(52.5,"C",DT,SFN)="",^PS(52.5,SFN,"P")=1 K NODE
 ;IHS/ITSC/ENM 02/05/02 VA PATCH CHANGE ADDED TO NEXT LINE
 I $P($G(^PS(52.5,SFN,0)),"^",7)'="" N DA,DR,DIE S DA=SFN,DIE="^PS(52.5,",DR="3////P" D ^DIE
 Q
AREC S $P(^PSRX(RX,0),"^",15)=0 S SFN=$O(^PS(52.5,"B",RX,0)) Q:'SFN  D NOW^%DTC S DTTM=% S COM="Suspense Label "_$S($G(^PS(52.5,SFN,"P"))=2:"Reprinted",1:"Printed")_$S($G(RXP):" (PARTIAL)",1:"")
 I $G(^PS(52.5,SFN,"P"))=2 S (REPRINT,SUSREP)=""
 S ^PS(52.5,SFN,"P")=1 K ^PS(52.5,"AC",DFN,$P(^PS(52.5,SFN,0),"^",2),SFN) S CNT=0 F JJ=0:0 S JJ=$O(^PSRX(RX,"A",JJ)) Q:'JJ  S CNT=JJ
 S RFCNT=0 F RF=0:0 S RF=$O(^PSRX(RX,1,RF)) Q:'RF  S RFCNT=RF S:RF>5 RFCNT=RF+1
 ;IHS/ITSC/ENM 02/05/02 VA PATCH CHANGE ADDED TO NEXT LINE
 S CNT=CNT+1,^PSRX(RX,"A",0)="^52.3DA^"_CNT_"^"_CNT L +^PSRX(RX):0 S ^PSRX(RX,"A",CNT,0)=DTTM_"^S^"_DUZ_"^"_$S($G(RXP):6,1:RFCNT)_"^"_COM L -^PSRX(RX)
 Q
ARECD D NOW^%DTC S CNT=0,DTTM=% F JJ=0:0 S JJ=$O(^PSRX(RX,"A",JJ)) Q:'JJ  S CNT=JJ
 S RFCNT=0 F RF=0:0 S RF=$O(^PSRX(RX,1,RF)) Q:'RF  S RFCNT=RF S:RF>5 RFCNT=RF+1
 S RXP=$P(^PS(52.5,SFN,0),"^",5)
 ;IHS/ITSC/ENM 02/05/02 VA PATCH CHANGE ADDED TO NEXT LINE
 S CNT=CNT+1,^PSRX(RX,"A",0)="^52.3DA^"_CNT_"^"_CNT L +^PSRX(RX):0 S ^PSRX(RX,"A",CNT,0)=DTTM_"^S^"_DUZ_"^"_$S($G(RXP):6,1:RFCNT)_"^"_COM L -^PSRX(RX) K RXP
 Q
 ;IHS/ITSC/ENM 02/05/02 NEXT VA SUB-ROUTINE ADDED
ZZ(RX) ;    Returns VA print name, Trade Name, Generic Name
 S I50=$P(^PSRX(RX,0),U,6),ZDRUG=$P(^PSDRUG(I50,0),U)
 I $G(ZDRUG)']"" S ZDRUG="DRUG NOT ON FILE ("_I50_")" G END
 I $G(^PSRX(RX,"TN"))]"" S ZDRUG=^("TN") G END
 I $D(^PSDRUG("AQ",I50)),($D(^PSDRUG(I50,"ND"))) D
 .S Z1=$P($G(^PSDRUG(I50,"ND")),U),Z2=$P($G(^("ND")),U,3)
 .I $G(Z1),($G(Z2)) S Z3=$$PROD2^PSNAPIS(Z1,Z2),ZDRUG=$P(Z3,U)
 .K Z1,Z2,Z3,I50
END K I50
 Q ZDRUG
