BQI28P1 ;GDIT/HCSD/ALA-iCare Version 2.8 Patch 1 ; 10 Jan 2020  2:55 PM
 ;;2.8;ICARE MANAGEMENT SYSTEM;**1**;Aug 29, 2019;Build 21
 ;
PRE ;
 NEW DA,DIK
 S DA=0,DIK="^BQI(90507.8,"
 F  S DA=$O(^BQI(90507.8,DA)) Q:'DA  D ^DIK
 S DA=0,DIK="^BQI(90509.9,"
 F  S DA=$O(^BQI(90509.9,DA)) Q:'DA  D ^DIK
 K ^BQI(90507.7,"AC")
 Q
 ;
POS ;
 NEW DIK
 S DIK="^BQI(90507.7," D IXALL^DIK
 ;
 ; Set flags - INCLUDE SUICIDE?, and CANES CCDA EXPORT
 NEW DA,UPD,IENS
 S DA=1,UPD(90508,DA_",",.03)=1,UPD(90508,DA_",",.06)="@"
 ; Set up Community Alerts in Site parameters
 S DA(1)=1,DA=4 D
 . S ^BQI(90508,1,DA(1),15,DA,0)="Behavorial Health^^30^"
 F DA=1:1:3 D
 . S IENS=$$IENS^DILF(.DA),UPD(90508.015,IENS,.04)=1
 D FILE^DIE("","UPD","ERROR")
 S ^BQI(90508,1,15,0)="^90508.015A^4^4",^BQI(90508,1,15,"B","Behavorial Health",4)=""
 ;
 D ^BQITAXXU
 ;
 D ^BQIUSRC
 ;
 D ^BQIH
 ;
GLS ;Update glossary
 NEW GN,GNM,GSN,BQIUPD
 S GN=0
 F  S GN=$O(^BQI(90509.9,GN)) Q:'GN  D
 . S GNM=$P(^BQI(90509.9,GN,0),U,1)
 . S GSN=$O(^BQI(90508.2,"B",GNM,"")) Q:GSN=""
 . S BQIUPD(90508.2,GSN_",",1)="@"
 . D FILE^DIE("","BQIUPD","ERROR")
 . M ^BQI(90508.2,GSN,1)=^BQI(90509.9,GN,1)
 ;
JB ;EP
 NEW ZTDTH,ZTDESC,ZTRTN,ZTIO,ZTSAVE,BQIUPD
 S ZTDTH=$$FMADD^XLFDT($$NOW^XLFDT(),,,3)
 S ZTDESC="Lab Send",ZTRTN="LAB^BQI28P1",ZTIO=""
 D ^%ZTLOAD
 S BQIUPD(90508,"1,",11.06)=ZTSK
 D FILE^DIE("","BQIUPD","ERROR")
 Q
 ;
LAB ;EP - Send COVID labs to EPI
 NEW SDT
 S SDT=3200301,TMFRAME="T-"_$$FMDIFF^XLFDT(DT,SDT,1)
 S TREF=$NA(^TMP("BQITAX",$J)) K @TREF
 F TAX="BQI COVID QUAL ANTIBODY LOINC","BQI COVID QUAN ANTIBODY LOINC","BQI COVID ANTIGEN LOINC" D BLD^BQITUTL(TAX,.TREF)
 F TAX="BQI COVID QUAL ANTIBODY TAX","BQI COVID QUAN ANTIBODY TAX","BQI COVID ANTIGEN TEST TAX" D BLD^BQITUTL(TAX,.TREF,"L")
 D FND^BQICAVAL(82)
 K @TREF
 F TAX="BQI COVID QUAL TESTING LOINC","BQI COVID QUAN TESTING LOINC" D BLD^BQITUTL(TAX,.TREF)
 F TAX="BQI COVID QUAN TESTING TAX","BQI COVID QUAL TESTING TAX" D BLD^BQITUTL(TAX,.TREF,"L")
 D FND^BQICAVAL(83)
 K @TREF
 ;
 S ASUN=$P(^AUTTSITE(1,0),U),ASUFAC=$P($G(^AUTTLOC(ASUN,0)),U,10),ASUNM=$P(^DIC(4,ASUN,0),U)
 S CT=0,N=0
 K ^BQIDATA($J)
 ;
 S FRM=$P($G(^BQI(90508,1,0)),U,2)
 S IN=+$G(^BQIDATA($J))
 S DELIM=$S(FRM="D":",",1:"~")
 I FRM="D",$G(^BQIDATA($J))=0 S HDR=$$JDATE^BQICAEXP(DT)_DELIM_CT_DELIM_ASUNM,^BQIDATA($J,IN)=HDR
 D PROC^BQICAVAL
 I FRM'="D" D ^BQICAHLO
 NEW XBGL,XBQ,XBQTO,XBNAR,XBMED,XBFLT,XBUF,XBFN
 S XBMED="F",XBQ="N",XBFLT=1,XBF=$J,XBE=$J
 S XBGL=$S(FRM="D":"BQIDATA",1:"BQIHL7")
 S XBNAR="CANE SURVEILLANCE EXPORT"
 S ASUFAC=$P($G(^AUTTLOC($P(^AUTTSITE(1,0),U),0)),U,10)  ;asufac for file name
 S XBFN="CANE3_"_ASUFAC_"_"_$$DATE^BQICAEXP(DT)_".txt"
 S XBS1="CANE SURVEILLANCE SEND"
 S XBUF=$P($G(^AUTTSITE(1,1)),"^",2)
 I XBUF="" S XBUF=$P($G(^XTV(8989.3,1,"DEV")),"^",1)
 ;
 D ^XBGSAVE
 ;
 K ^BQIDATA($J),^BQIHL7($J)
 K HLSTATE,XBFLG
 Q
