BQI27P2 ;GDIT/HCSD/ALA-iCare Version 2.7 Patch 2 ; 14 Dec 2018  2:18 PM
 ;;2.7;ICARE MANAGEMENT SYSTEM;**2**;Dec 19, 2017;Build 10
 ;
PRE ;EP
 S DIK="^BQI(90509.1,",DA=0
 F  S DA=$O(^BQI(90509.1,DA)) Q:'DA  D ^DIK
 Q
 ;
POS ;EP
 ; fix Pregnant factors
 NEW IEN,STAT,DFN
 S IEN="" F  S IEN=$O(^BQIREG("B",16,IEN)) Q:IEN=""  D
 . S STAT=$P(^BQIREG(IEN,0),"^",3)
 . I STAT'="V",'$D(^BQIREG(IEN,5)) S DFN=$P(^BQIREG(IEN,0),"^",2) D MOV^BQITDPRC(DFN,16)
 ;
 ; Update Nightly Job
 NEW OPTN
 S OPTN=$O(^DIC(19,"B","BQI NIGHTLY BACKGROUND",""))
 I OPTN'="" S UPD(19,OPTN_",",25)="BQINIGZT" D FILE^DIE("","UPD","ERROR")
 ;
 ; Fix unfold routine for CRS
 NEW BQIH,BQIYR,BQGYRN,BGPIN,BQIN4,DA,IENS
 S BQIH=$$SPM^BQIGPUTL()
 S BQIYR=$$GET1^DIQ(90508,BQIH_",",2,"E")
 S BQGYRN=$O(^BQI(90508,BQIH,20,"B",BQIYR,""))
 S BGPIN=$O(^BGPCTRL("B",BQIYR,0))
 S BQIN4=$$GET1^DIQ(90241.01,BGPIN_",",.3,"E")
 S DA(1)=BQIH,DA=BQGYRN,IENS=$$IENS^DILF(.DA)
 S BQIUPD(90508.01,IENS,.07)=BQIN4
 D FILE^DIE("","BQIUPD","ERROR")
 ;
 ; Fix % Impanelled for Facility
 NEW BQIH,BGPHOME,FIEN,IDATE,FDIEN
 S BQIH=$$SPM^BQIGPUTL()
 S BGPHOME=$$HME^BQIGPUTL()
 S FIEN=$O(^BQIFAC(BGPHOME,30,"B","IPC_PEMP","")) I FIEN="" Q
 S IDATE="" F  S IDATE=$O(^BQI(90508,BQIH,22,4,3,"B",IDATE)) Q:IDATE=""  D
 . S FDIEN=$O(^BQIFAC(BGPHOME,30,FIEN,1,"B",IDATE,"")) I FDIEN="" Q
 . I $P(^BQIFAC(BGPHOME,30,FIEN,1,FDIEN,0),"^",2)'=0,$P(^(0),"^",3)'=0 Q
 . D EN^BQIIPEMP($G(IDATE),$G(BQFROM),$G(BQTHRU))
 ;
BSE ; Create baseline Opioid export file
 NEW ZTDTH,ZTDESC,ZTRTN,ZTIO,ZTSAVE
 S ZTDTH=$$FMADD^XLFDT($$NOW^XLFDT(),,,2)
 S ZTDESC="Baseline Opioid File EPI",ZTIO=""
 S ZTRTN="BASE^BQICAEP3"
 D ^%ZTLOAD
 K ZTSK
 Q
