BQIBTX ;GDIT/HCSD/ALA-CREATED BY ^ATXSTX ON MAY 24, 2023;
 ;;2.9;ICARE MANAGEMENT SYSTEM;**5**;Mar 01, 2021;Build 20
 ;
 ; See referenced routines to see taxonomies being loaded.
 ;
START ;
 D ^BQIBTXA ;   BQI HERPES SIMPLEX ANTIBODY LC
 D ^BQIBTXB ;   BQI HERPES SIMPLEX NUCL LOINC
 D ^BQIBTXC ;   BQI HERPES SIMPLEX CULT LOINC
 D ^BQIBTXD ;   BQI COVID ALL CPTS
 D ^BQIBTXE ;   BQI COVID ADDTL DOSE CPTS
 Q
