BQICMUT4 ;GDIT/HCSD/ALA-Care Mgmt group APIs ; 09 Nov 2021  9:20 AM
 ;;2.9;ICARE MANAGEMENT SYSTEM;**2,3,4,5**;Mar 01, 2021;Build 20
 ;
EX(TYPE,RIEN,FIELD,RESULT) ;EP
 NEW MDATA
 I TYPE="PR" D
 . S RESULT=""
 . I FIELD=.01 D  Q
 .. S DN=$$GET1^DIQ(9000011,RIEN_",",FIELD,"I")
 .. I $$VERSION^XPDUTL("AICD")>3.51 S RESULT=1_U_$$VST^ICDCODE(DN,"",80)_" ["_$$CODEC^ICDCODE(DN,80)_"]" Q
 .. S RESULT=1_U_$P(^ICD9(DN,0),U,3)_" ["_$P(^ICD9(DN,0),U,1)_"]"
 . I FIELD="ONSET" D  Q
 .. S MDATA=$$PROB^BQIUL1(RIEN) I MDATA="" S RESULT=0
 .. S RESULT=1_U_MDATA
 . I DIS="D" S RESULT=1_U_$$GET1^DIQ(9000011,RIEN_",",FIELD,"I") Q
 . S RESULT=1_U_$$GET1^DIQ(9000011,RIEN_",",FIELD,"E")
 . I RESULT="" S RESULT=0
 I TYPE="AL" D
 . NEW ARIEN
 . S RESULT=""
 . I FIELD=4 S RESULT=1_U_$$GET1^DIQ(120.8,RIEN_",",FIELD,"I") Q
 . I FIELD=14.5 S ARIEN=$O(^GMR(120.85,"C",RIEN,"")) I ARIEN'="" S RESULT=1_U_$$GET1^DIQ(120.85,ARIEN_",",FIELD,"E") Q
 . S RESULT=1_U_$$GET1^DIQ(120.8,RIEN_",",FIELD,"E")
 . I RESULT="" S RESULT=0
 I TYPE="ME" D  Q
 . NEW FILE
 . S FILE=9000010.14,RESULT=""
 . I FIELD="DATE" D
 .. S RES=$$VISD(FILE,RIEN)
 .. I RES'="" S RESULT=1_U_(RES\1)
 . I FIELD?.N!(FIELD?1".".N) D  Q
 .. S RESULT=1_U_$$GET1^DIQ(FILE,RIEN_",",FIELD,"E")
 . S RXN=$$GET1^DIQ(9000010.14,RIEN_",",1102,"E") I RXN="" Q
 . S RXIEN=$O(^PSRX("B",RXN,"")) I RXIEN="" Q
 . I FIELD="STAT" S RESULT=1_U_$$GET1^DIQ(52,RXIEN_",",100,"E")
 . I FIELD="NREF" S RESULT=1_U_$$GET1^DIQ(52,RXIEN_",",9,"E")
 . I FIELD="LDDT" S RESULT=1_U_$$GET1^DIQ(52,RXIEN_",",101,"I")
 . I FIELD="EXPDT" S RESULT=1_U_$$GET1^DIQ(52,RXIEN_",",26,"I")
 . I FIELD="RXNUM" S RESULT=1_U_$$GET1^DIQ(52,RXIEN_",",.01,"E")
 . I FIELD="RXNRM" D
 .. NEW BQDRN,BQRXNRM
 .. S BQDRN=$P(^AUPNVMED(RIEN,0),"^",1),BQRXNRM=$P($G(^PSDRUG(BQDRN,999999924)),"^",4)
 .. I BQRXNRM'="" S RESULT=1_U_BQRXNRM
 . I RESULT="" S RESULT=0
 I TYPE="CP" D  Q
 . NEW FILE
 . S FILE=9000010.18,RESULT=""
 . I FIELD?.N!(FIELD?1".".N) D  Q
 .. S RESULT=1_U_$$GET1^DIQ(FILE,RIEN_",",FIELD,"E")
 . I FIELD="DATE" D
 .. S RES=$$VISD(FILE,RIEN)
 .. I RES'="" S RESULT=1_U_(RES\1)
 . I FIELD="CPT" D
 .. S DN=$P($G(^AUPNVCPT(RIEN,0)),U,1) I DN="" Q
 .. S RESULT=1_U_$P(^ICPT(DN,0),U,1)_" - "_$P(^ICPT(DN,0),U,2)
 . I RESULT="" S RESULT=0
 I TYPE="ER" D  Q
 . NEW FILE
 . S FILE=9009080,RESULT=""
 . I FIELD?.N!(FIELD?1".".N)!(FIELD?.N1".".N) D  Q
 .. I DFN=RIEN,FIELD'=.05 Q
 .. I DFN=RIEN,FIELD=.05 S RESULT=1_U_$$GET1^DIQ(9009081,RIEN_",",3,"E") Q
 .. S RESULT=1_U_$$GET1^DIQ(FILE,RIEN_",",FIELD,"E")
 . I FIELD="ADATE" D
 .. I DFN=RIEN S RESULT=1_U_$P($G(^AMERADM(RIEN,0)),U,2)\1 Q
 .. S RESULT=1_U_$P($G(^AMERVSIT(RIEN,0)),U,1)
 . I FIELD="DDATE" D
 .. I DFN=RIEN Q
 .. S RESULT=1_U_$P($G(^AMERVSIT(RIEN,6)),U,2)
 . I FIELD="MODE" D
 .. I DFN=RIEN S RESULT=1_U_$$GET1^DIQ(9009081,RIEN_",",6,"E") Q
 .. NEW MODE
 .. S MODE=$$GET1^DIQ(FILE,RIEN_",",.25,"E")
 .. I MODE="" S MODE=$$GET1^DIQ(FILE,RIEN_",",17.3,"E")
 .. I MODE'="" S RESULT=1_U_MODE
 . I RESULT="" S RESULT=0
 I TYPE="LA" D  Q
 . NEW FILE,TEXT,LN,RES
 . S FILE=9000010.09,RESULT=""
 . I FIELD?.N!(FIELD?1".".N)!(FIELD?.N1".".N) D  Q
 .. S RESULT=1_U_$$GET1^DIQ(FILE,RIEN_",",FIELD,"E")
 . I FIELD="LOC" D  Q
 .. NEW LVIS,LOC
 .. S LVIS=$P($G(^AUPNVLAB(RIEN,0)),"^",3)
 .. S RESULT=1_U
 .. I LVIS'="" S LOC=$$GET1^DIQ(9000010,LVIS_",",.06,"E"),$P(RESULT,U,2)=LOC
 . I FIELD="COM" D  Q
 .. S TEXT="",LN=0
 .. F  S LN=$O(^AUPNVLAB(RIEN,21,LN)) Q:'LN  D
 ... S TEXT=TEXT_^AUPNVLAB(RIEN,21,LN,0)_$C(10)_$C(13)
 .. S RESULT=1_U_$$TKO^BQIUL1(TEXT,$C(10)_$C(13))
 . I FIELD="ABN" D
 .. NEW TEXT,ABN
 .. S TEXT=""
 .. S ABN=$P($G(^AUPNVLAB(RIEN,0)),"^",5)
 .. I ABN["*" S TEXT="Critical "
 .. S TEXT=TEXT_$S(ABN["L":"Low",ABN["H":"High",ABN["A":"Abnormal",1:ABN)
 .. S RESULT=1_U_TEXT
 . I FIELD="DATE" D
 .. ;S VISIT=$P($G(^AUPNVLAB(RIEN,0)),U,3) I VISIT="" Q
 .. S RES=$$VISD(FILE,RIEN)
 .. I RES'="" S RESULT=1_U_(RES\1)
 . I FIELD="RDATE" D
 .. S RES=$P($G(^AUPNVLAB(RIEN,12)),"^",12)
 .. I RES'="" S RESULT=1_U_$$FMTMDY^BQIUL1(RES)
 . I FIELD="CDATE" D
 .. S RES=$P($G(^AUPNVLAB(RIEN,12)),"^",1)
 .. I RES'="" S RESULT=1_U_$$FMTMDY^BQIUL1(RES)
 . I RESULT="" S RESULT=0
 I TYPE="ED" D  Q
 . NEW FILE,RES
 . S FILE=9000010.16,RESULT=""
 . I FIELD?.N!(FIELD?1".".N)!(FIELD?.N1".".N) D  Q
 .. S RESULT=1_U_$$GET1^DIQ(FILE,RIEN_",",FIELD,"E")
 . I FIELD="DATE" D
 .. S RES=$$VISD(FILE,RIEN)
 .. I RES'="" S RESULT=1_U_(RES\1)
 . I RESULT="" S RESULT=0
 I TYPE="OR" D  Q
 . NEW FILE,RES
 . S FILE=100,RESULT=""
 . I FIELD?.N!(FIELD?1".".N)!(FIELD?.N1".".N) D  Q
 .. S RESULT=1_U_$$GET1^DIQ(FILE,RIEN_",",FIELD,"E")
 . I FIELD["DATE" D
 .. I FIELD="ODATE" S RESULT=1_U_$$GET1^DIQ(FILE,RIEN_",",4,"I")
 .. I FIELD="SADATE" S RESULT=1_U_$$GET1^DIQ(FILE,RIEN_",",21,"I")
 .. I FIELD="SODATE" S RESULT=1_U_$$GET1^DIQ(FILE,RIEN_",",22,"I")
 . I FIELD="ACTDTM" D
 .. NEW LAC
 .. S LAC=$O(^OR(100,RIEN,8,"A"),-1)
 .. S RESULT=1_U_$P(^OR(100,RIEN,8,LAC,0),"^",1)
 . I FIELD="ORITM" D
 .. NEW OIN,OITM
 .. S OIN=$O(^OR(100,RIEN,.1,0)) I OIN="" S RESULT=1_U Q
 .. S OITM=$P(^OR(100,RIEN,.1,OIN,0),"^",1)
 .. S RESULT=1_U_$P($G(^ORD(101.43,OITM,0)),"^",1)
 . I FIELD="SLOC" D
 .. NEW OLN,SLN,SLNM
 .. S RESULT=0
 .. S OLN=$P($$GET1^DIQ(100,RIEN_",",6,"I"),";",1) I OLN="" Q
 .. S SLN=$P($G(^SC(OLN,0)),"^",4) I SLN="" Q
 .. S SLNM=$P($G(^DIC(4,SLN,0)),"^",1) I SLNM="" Q
 .. S RESULT=1_U_SLNM
 . I FIELD="CLICD" D
 .. NEW CLDN
 .. S CLDN=$O(^OR(100,RIEN,4.5,"ID","CLININD2","")) I CLDN="" Q
 .. S RESULT=1_U_$G(^OR(100,RIEN,4.5,CLDN,1))
 . I FIELD="SNOM" D
 .. NEW SNNN
 .. S SNNN=$O(^OR(100,RIEN,4.5,"ID","SNMDCNPTID","")) I SNNN="" Q
 .. S RESULT=1_U_$G(^OR(100,RIEN,4.5,SNNN,1))
 . I FIELD="CLIND" D
 .. S CLDTX=""
 .. S CLDTX=$O(^OR(100,RIEN,4.5,"ID","CLININD","")) I CLDTX="" Q
 .. S RESULT=1_U_$G(^OR(100,RIEN,4.5,CLDTX,1))
 I TYPE="NT" D  Q
 . NEW FILE,RES
 . S FILE=8925,RESULT=""
 . I FIELD?.N!(FIELD?1".".N)!(FIELD?.N1".".N) D  Q
 .. S RESULT=1_U_$$GET1^DIQ(FILE,RIEN_",",FIELD,"E")
 . I FIELD["DATE" D
 .. I FIELD="EDATE" S RESULT=1_U_$$GET1^DIQ(FILE,RIEN_",",1201,"I")
 .. I FIELD="SGDATE" S RESULT=1_U_$$GET1^DIQ(FILE,RIEN_",",1501,"I")
 .. I FIELD="CODATE" S RESULT=1_U_$$GET1^DIQ(FILE,RIEN_",",1507,"I")
 .. I FIELD="VDATE" S RES=$$VISD(FILE,RIEN) I RES'="" S RESULT=1_U_(RES\1)
 . I FIELD="ADNTS" S RES="" D
 .. NEW ADZ
 .. S ADZ="" F  S ADZ=$O(^TIU(8925.7,"AE",RIEN,ADZ)) Q:ADZ=""  S RES=RES_$P($G(^VA(200,ADZ,0)),"^",1)_$C(10)_$C(13)
 .. I RES'="" S RESULT=1_U_$$TKO^BQIUL1(RES,$C(10)_$C(13))
 . I FIELD="VTYPE" D
 .. NEW VISIT
 .. S VISIT=$P($G(^TIU(8925,RIEN,0)),"^",3) I VISIT="" Q
 .. S RESULT=1_U_$$GET1^DIQ(9000010,VISIT_",",.07,"E")
 Q
 ;
VISD(FILE,RIEN) ; EP - Get visit date
 NEW VFILE
 S VFILE=$$ROOT^DILFD(FILE,"",1)
 S VISIT=$P($G(@VFILE@(RIEN,0)),U,3) I VISIT="" Q ""
 Q $P($G(^AUPNVSIT(VISIT,0)),U,1)
 ;
BRK(BQDFN) ; EP - COVID Breakthrough Infection
 K FLAG
 ; Find immunizations
 S JIEN=$O(^AUTTIMM("C",212,""))
 S TREF="BQICVIM" K @TREF
 D BLD^BQITUTL("BQI COVID IZ CVX CODES",.TREF)
 S ITEMP="BQIPTIM" K @ITEMP
 S IJCT=0,ICT=0,FLAG=""
 S IIEN="" F  S IIEN=$O(@TREF@(IIEN)) Q:IIEN=""  D
 . I $G(TMFRAME)="" S EDT="",BDT=""
 . F  S BDT=$O(^AUPNVIMM("AA",BQDFN,IIEN,BDT)) Q:BDT=""  D
 .. S MIEN=""
 .. F  S MIEN=$O(^AUPNVIMM("AA",BQDFN,IIEN,BDT,MIEN)) Q:MIEN=""  D
 ... S VISIT=$P($G(^AUPNVIMM(MIEN,0)),"^",3) I VISIT="" Q
 ... S IDTM=$P($G(^AUPNVIMM(MIEN,12)),"^",1)\1
 ... I +IDTM=0 S IDTM=$P($G(^AUPNVSIT(VISIT,0)),"^",1)\1 I IDTM=0 Q
 ... S @ITEMP@(IDTM,MIEN)=IIEN
 ... I JIEN'=""&(IIEN=JIEN) S IJCT=IJCT+1 Q
 ... S ICT=ICT+1
 ;
 ; No immunizations found
 I $D(@ITEMP)=0 D CLN Q FLAG
 I ICT<2&(IJCT=0) D CLN Q FLAG
 ;
 ; find positive lab
 K TREF
 S TREF="BQICVLB" D
 . F TAX="BQI COVID BRKTHRU LOINC" D BLD^BQITUTL(TAX,.TREF)
 . F TAX="BQI COVID BRKTHRU TAX" D BLD^BQITUTL(TAX,.TREF,"L")
 ;
 ; Find positive labs
 S LTEMP="BQIPTLB" K @LTEMP
 S TIEN=""
 F  S TIEN=$O(@TREF@(TIEN)) Q:TIEN=""  D
 . I $G(TMFRAME)="" S EDT="",BDT=""
 . F  S BDT=$O(^AUPNVLAB("AA",BQDFN,TIEN,BDT)) Q:BDT=""  D
 .. S LIEN=""
 .. F  S LIEN=$O(^AUPNVLAB("AA",BQDFN,TIEN,BDT,LIEN)) Q:LIEN=""  D
 ... S BVALUE=$P(^AUPNVLAB(LIEN,0),U,4)
 ... S VIEN=$P(^AUPNVLAB(LIEN,0),U,3) I VIEN="" Q
 ... S FLAG=$P($G(^AUPNVLAB(LIEN,11)),U,9) I FLAG="" Q
 ... ; Check collection date/time
 ... S VSDTM=$P($G(^AUPNVSIT(VIEN,0)),"^",1) I VSDTM="" Q
 ... S CLDTM=$P($G(^AUPNVLAB(LIEN,12)),"^",1)
 ... I CLDTM="" S CLDTM=VSDTM
 ... S VSDTM=CLDTM
 ... ; quit if deleted flag
 ... I $P($G(^AUPNVSIT(VIEN,0)),U,11)=1 Q
 ... I $P($G(^AUPNVLAB(LIEN,11)),U,9)="D" Q
 ... ;I '$$POSITIVE^BQITRUTL(BVALUE) Q
 ... S @LTEMP@(VSDTM,VIEN,LIEN)=BVALUE_U_TIEN
 ;
 ; No labs found
 I $D(@LTEMP)=0 D CLN Q ""
 S FLAG="NO"
 D PLB I 'BPOS D CLN Q FLAG
 ; Check positive lab against completed immunizations
 D LCK
 Q FLAG
 ;
LCK ;
 ;14 days or more after completion of a series
 K MIMDT
 S CT=0
 S IMDT="" F  S IMDT=$O(@ITEMP@(IMDT)) Q:IMDT=""  D
 . S MIEN="" F  S MIEN=$O(@ITEMP@(IMDT,MIEN)) Q:MIEN=""  D
 .. I IJCT=1&(@ITEMP@(IMDT,MIEN)=313) S MIMDT=IMDT Q
 .. S CT=CT+1 I CT=2 S MIMDT=IMDT
 ;
 I $G(MIMDT)="" S FLAG="" Q
 S IMDT=$$FMADD^XLFDT(MIMDT,14)
 I PLBDT<IMDT S FLAG="NO"
 I PLBDT'<IMDT S FLAG="YES"
 Q
 ;
CLN ;Clean up
 I $G(LTEMP) K @LTEMP,LTEMP
 K LIEN,TIEN,EDT,BDT,BVALUE,VIEN,VSDTM,ICT,MIMDT,CT,BPOS,PLBDT,CLDTM
 K TAX,@TREF,TREF,IIEN,EDT,BDT,MIEN,VISIT,IDTM,JIEN,IJCT,LBDT,IMDT
 I $G(ITEMP) K @ITEMP,ITEMP
 Q
 ;
PLB ; Positive labs
 K LBDT,VIEN,LIEN
 S BPOS=0,PLBDT=""
 S LBDT="" F  S LBDT=$O(@LTEMP@(LBDT)) Q:LBDT=""  D
 . S VIEN="" F  S VIEN=$O(@LTEMP@(LBDT,VIEN)) Q:VIEN=""  D
 .. S LIEN="" F  S LIEN=$O(@LTEMP@(LBDT,VIEN,LIEN)) Q:LIEN=""  D
 ... S BVALUE=$P(@LTEMP@(LBDT,VIEN,LIEN),"^",1)
 ... I $$POSITIVE^BQITRUTL(BVALUE) S BPOS=1,PLBDT=LBDT\1
 K LBDT,VIEN,LIEN
 Q
 ;
MED(BQDFN,TAX) ;EP - Medications
 S TREF="BQICVMED" K @TREF
 D BLD^BQITUTL(TAX,.TREF)
 S RESULT=""
 I $D(@TREF)=0 Q RESULT
 I TAX["COVID" S DATE=3200101
 I TAX["IMMUNOSUP" S DATE=3140101
 ;I TAX["IMMUNOSUP" S DATE=$$DATE^BQIUL1("T-60M")
 S BDT=9999999-DT,EDT=9999999-DATE
 F  S BDT=$O(^AUPNVMED("AA",BQDFN,BDT)) Q:BDT=""!(BDT>EDT)  D
 . S MN="" F  S MN=$O(^AUPNVMED("AA",BQDFN,BDT,MN)) Q:MN=""  D
 .. S MDN=$P($G(^AUPNVMED(MN,0)),"^",1) I MDN="" Q
 .. I '$D(@TREF@(MDN)) Q
 .. S EVDT=$P($G(^AUPNVMED(MN,12)),"^",1) I EVDT'="" S EVDT=EVDT\1
 .. I EVDT="" D
 ... S VISIT=$P(^AUPNVMED(MN,0),"^",3),EVDT=$P(^AUPNVSIT(VISIT,0),"^",1)\1
 .. S RESULT=@TREF@(MDN)_" ("_$$FMTMDY^BQIUL1(EVDT)_") "_$C(10)_$C(13)
 Q $$TKO^BQIUL1(RESULT,$C(10)_$C(13))
 ;
DRUG ;EP - update taxonomy with drugs
 S TXN=$O(^ATXAX("B","BQI COVID DRUGS","")) I TXN="" Q
 K ^ATXAX(TXN,21) S ^ATXAX(TXN,21,0)="^9002226.02101A^^"
 S $P(^ATXAX(TXN,0),"^",13)=0,CT=0
 ;
 F BI=1:1 S TEXT=$P($T(MONO+BI),";;",2) Q:TEXT=""  D
 . S PSN=$O(^PSNDF(50.6,"B",TEXT,"")) I PSN="" Q
 . S DRN="" F  S DRN=$O(^PSDRUG("AND",PSN,DRN)) Q:DRN=""  D
 .. S CT=CT+1,^ATXAX(TXN,21,CT,0)=DRN_"^"_DRN
 S DIK="^ATXAX(",DA=TXN D IX^DIK
 K TXN,CT,BI,TEXT,PSN,DRN,DA,DIC,DIK
 Q
 ;
MONO ;EP - COVID Treatments
 ;;CASIRIVIMAB/IMDEVIMAB
 ;;SOTROVIMAB
 ;;CILGAVIMAB/TIXAGEVIMAB
 ;;BAMLANIVIMAB
 ;;ETESEVIMAB
 ;;CASIRIVIMAB
 ;;NIRMATRELVIR/RITONAVIR
 ;;MOLNUPIRAVIR
 ;;REMDESIVIR
 ;;BEBTELOVIMAB
