BQICAHIS ;GDIT/HS/ALA-Community Alert History Report ; 25 Mar 2022  3:39 PM
 ;;2.9;ICARE MANAGEMENT SYSTEM;**3**;Mar 01, 2021;Build 32
 ;
EN(DATA,TMFRAME,LTY) ;EP -- BQI GET COMM ALERTS HISTORY
 S UID=$S($G(ZTSK):"Z"_ZTSK,1:$J)
 K ^XTMP("BQICAHIS",UID)
 S DATA=$NA(^TMP("BQICAGRP",UID)) K @DATA
 S LTY=$G(LTY,"C")
 I LTY="C" S II=0,HDR="T00030COMMUNITY^T00045ALERT_TYPE^T00045DX_CAT^"
 I LTY="L" S II=0,HDR="T00030LOCATION^T00045ALERT_TYPE^T00045DX_CAT^"
 ;
 I $G(TMFRAME)'="" D
 . I TMFRAME="Ever" D  Q
 .. S RFROM=$O(^BQI(90507.7,"B","")),RTHRU=$O(^BQI(90507.7,"B",""),-1)
 . S TN="",ENT=""
 . F  S TN=$O(^BQI(90506.9,"B",TMFRAME,TN)) Q:TN=""  D
 .. S EXEC=$P(^BQI(90506.9,TN,0),U,5)
 .. I EXEC'="" D
 ... I EXEC["(" S NEXE=$P(EXEC,"(",1)_"^BQIDCAH1("_$P(EXEC,"(",2)
 ... I EXEC'["(" S NEXE=EXEC_"^BQIDCAH1"
 ... X NEXE
 .. I ENT="IPC" Q
 .. I $P(^BQI(90506.9,TN,0),U,4)'="" D
 ... S RFROM=$$DATE^BQIUL1($P(^BQI(90506.9,TN,0),U,3))
 ... S RTHRU=$$DATE^BQIUL1($P(^BQI(90506.9,TN,0),U,4))
 ;
 I $E(RFROM,1,3)=$E(RTHRU,1,3) S YR=$E(RFROM,1,3) D
 . F BQMON=1:1:12 S BQDTE=$P($T(MON+BQMON),";;",2),MON=YR_$P(BQDTE,"^",1)_"00",ZZ(MON)=0
 I $E(RFROM,1,3)'=$E(RTHRU,1,3) D
 . S YF=$E(RFROM,1,3),YT=$E(RTHRU,1,3),MF=+$E(RFROM,4,5),MT=+$E(RTHRU,4,5)
 . F YR=YF:1:YT D
 .. I YR=YF F BQMON=MF:1:12 S BQDTE=$P($T(MON+BQMON),";;",2),MON=YR_$P(BQDTE,"^",1)_"00",ZZ(MON)=0
 .. I YR'=YF,YR'=YT F BQMON=1:1:12 S BQDTE=$P($T(MON+BQMON),";;",2),MON=YR_$P(BQDTE,"^",1)_"00",ZZ(MON)=0
 .. I YR=YT F BQMON=1:1:MT S BQDTE=$P($T(MON+BQMON),";;",2),MON=YR_$P(BQDTE,"^",1)_"00",ZZ(MON)=0
 ;
 S DATE=RFROM-.01
 F  S DATE=$O(^BQI(90507.7,"B",DATE)) Q:DATE=""!(DATE>RTHRU)  D
 . S MON=$E(DATE,1,5)_"00"
 . S EN="" F  S EN=$O(^BQI(90507.7,"B",DATE,EN)) Q:EN=""  D
 .. S RN=0 F  S RN=$O(^BQI(90507.7,EN,10,RN)) Q:'RN  D
 ... S CDATA=^BQI(90507.7,EN,10,RN,0)
 ... S VISIT=$P(CDATA,"^",2)
 ... I VISIT'="" S LOC=$P($G(^AUPNVSIT(VISIT,0)),"^",6)
 ... I LOC="" S LOC=$P(^BQI(90508,1,0),"^",1)
 ... S TYP=$P(CDATA,"^",3),CDFN=$P(CDATA,"^",1)
 ... S DXN=$P(CDATA,"^",12),DXC=$S(DXN'="":$P(^BQI(90507.8,DXN,0),"^",1),1:$P(CDATA,"^",7))
 ... S COMM=$$GET1^DIQ(9000001,CDFN_",",1117,"I")
 ... I COMM="" S COMM=$$COMM^BQICALRE()
 ... S LCNM=$P(^DIC(4,LOC,0),"^",1),CMNM=$P(^AUTTCOM(COMM,0),"^",1)
 ... I LTY="C" S ^XTMP("BQICAHIS",UID,CMNM,TYP,DXC,MON)=$G(^XTMP("BQICAHIS",UID,CMNM,TYP,DXC,MON))+1
 ... I LTY="L" S ^XTMP("BQICAHIS",UID,LCNM,TYP,DXC,MON)=$G(^XTMP("BQICAHIS",UID,LCNM,TYP,DXC,MON))+1
 ;
 S DATE="" F  S DATE=$O(ZZ(DATE)) Q:DATE=""  D
 . D HH(DATE)
 I II=0 S @DATA@(II)=$$TKO^BQIUL1(HDR,"^")_$C(30)
 ;I II=0 S @DATA@(II)="T00030COMMUNITY"_$C(30)
 ;
 I LTY="L" S LOC="" D
 . F  S LOC=$O(^XTMP("BQICAHIS",UID,LOC)) Q:LOC=""  D
 .. S TYP="" F  S TYP=$O(^XTMP("BQICAHIS",UID,LOC,TYP)) Q:TYP=""  D
 ... S DXC="" F  S DXC=$O(^XTMP("BQICAHIS",UID,LOC,TYP,DXC)) Q:DXC=""  D
 .... S XX=LOC_"^"_TYP_"^"_DXC_"^"
 .... S DATE="" F  S DATE=$O(ZZ(DATE)) Q:DATE=""  D
 ..... I '$D(^XTMP("BQICAHIS",UID,LOC,TYP,DXC,DATE)) S XX=XX_0_"^"
 ..... I $D(^XTMP("BQICAHIS",UID,LOC,TYP,DXC,DATE)) S XX=XX_^XTMP("BQICAHIS",UID,LOC,TYP,DXC,DATE)_"^"
 .... S II=II+1,@DATA@(II)=$$TKO^BQIUL1(XX,"^")_$C(30)
 ;
 I LTY="C" S COMM="" D
 . F  S COMM=$O(^XTMP("BQICAHIS",UID,COMM)) Q:COMM=""  D
 .. S TYP="" F  S TYP=$O(^XTMP("BQICAHIS",UID,COMM,TYP)) Q:TYP=""  D
 ... S DXC="" F  S DXC=$O(^XTMP("BQICAHIS",UID,COMM,TYP,DXC)) Q:DXC=""  D
 .... S XX=COMM_"^"_TYP_"^"_DXC_"^"
 .... S DATE="" F  S DATE=$O(ZZ(DATE)) Q:DATE=""  D
 ..... I '$D(^XTMP("BQICAHIS",UID,COMM,TYP,DXC,DATE)) S XX=XX_0_"^"
 ..... I $D(^XTMP("BQICAHIS",UID,COMM,TYP,DXC,DATE)) S XX=XX_^XTMP("BQICAHIS",UID,COMM,TYP,DXC,DATE)_"^"
 .... S II=II+1,@DATA@(II)=$$TKO^BQIUL1(XX,"^")_$C(30)
 ;
 S II=II+1,@DATA@(II)=$C(31)
 K ZZ,LOC,COMM,TYP,DXC,XX,DATE,TIT,HDR,VISIT,CDATA,LCNM,CMNM,EN,RN,MON,RFROM,RTHRU,TMFRAME,YR,YF,YT,MF,MT
 K BQDTE,ENT,TN,EXEC,NEXE,TIT,BQMON,II,CDFN,LTY
 K ^XTMP("BQICAHIS",UID)
 Q
 ;
HH(DATE) ;EP
 S BQMON=$E(DATE,4,5)
 S TIT=$P($T(MON+BQMON^BQIIPUTL),";;",2)_"_"_(1700+$E(DATE,1,3))
 S HDR=HDR_"T00030"_TIT_"^"
 Q
 ;
MON ;EP
 ;;01^YR
 ;;02^YR
 ;;03^YR
 ;;04^YR
 ;;05^YR
 ;;06^YR
 ;;07^YR
 ;;08^YR
 ;;09^YR
 ;;10^YR
 ;;11^YR
 ;;12^YR
