BQICALRE ;GDIT/HS/ALA-Electronic Case Reporting ; 27 Oct 2021  10:58 AM
 ;;2.9;ICARE MANAGEMENT SYSTEM;**3,4,5,7**;Mar 01, 2021;Build 14
 ;
STRT ;EP - Start data mining for ECR
 S TDATA=$NA(^XTMP("BQIALRTTMP")),DATA=$NA(^XTMP("BQIALERT"))
 K @TDATA,@DATA
 S @DATA@(0)=$$FMADD^XLFDT(DT,2)_U_$$DT^XLFDT()_U_"Community Alerts"
 S @TDATA@(0)=$$FMADD^XLFDT(DT,2)_U_$$DT^XLFDT()_U_"Temporary Alerts"
 D SNO
 D DX
 D PROB
 D LAB
 D RXN
 ;
 ; Clear out existing Community Alerts before filing them
 S DA=0,DIK="^BQI(90507.6,"
 F  S DA=$O(^BQI(90507.6,DA)) Q:'DA  D ^DIK
 I $D(^BQI(90507.6,-1)) K ^BQI(90507.6,-1)
 K ^BQI(90507.6,"V")
 HANG 5
 ;
REP ;Repeating timeframe
 S ECR=0,CM=""
 F  S CM=$O(@DATA@(ECR,CM)) Q:CM=""  D
 . S TY="" F  S TY=$O(@DATA@(ECR,CM,TY)) Q:TY=""  D
 .. S DTY=$P(^BQI(90507.8,TY,0),U,1),ATY=$P($G(^BQI(90507.8,TY,2)),U,1)
 .. S REP=$P($G(^BQI(90507.8,TY,2)),U,5)
 .. S TME=$S(REP=1:61,REP=2:183,REP=3:365,1:"")
 .. S CDATE=$$DATE^BQIUL1("T-30")
 .. S PT="" F  S PT=$O(@DATA@(ECR,CM,TY,PT)) Q:PT=""  D
 ... S EXP=+$P($G(^BQI(90507.8,TY,2)),U,6) I EXP S ALRT=TY D EXP
 ... K BDZ S LDTE="",SDTE="",DDTE=""
 ... S LDTE=$O(@DATA@(ECR,CM,TY,PT,"LB",""),-1) I LDTE'="" S BDZ(LDTE)="L"
 ... S DDTE=$O(@DATA@(ECR,CM,TY,PT,"DX",""),-1) I DDTE'="" S BDZ(DDTE)="D"
 ... S SDTE=$O(@DATA@(ECR,CM,TY,PT,"SN",""),-1) I SDTE'="" S BDZ(SDTE)="S"
 ... S TYNM=$P(^BQI(90507.8,TY,0),"^",1)
 ... ;B
 ... I '$D(^BQI(90507.7,"AD",PT,TYNM)) D STOR Q
 ... S MDTE=$O(^BQI(90507.7,"AD",PT,TYNM,""),-1)
 ... I MDTE'<CDATE D STOR Q
 ... I TME=""&($D(^BQI(90507.7,"AD",PT,TYNM))) Q
 ... S DTE=$O(BDZ(""))
 ... S DDIF=$$FMDIFF^XLFDT(DTE,MDTE)
 ... I DDIF<TME D STOR Q
 ;
 S ECR=1,CM=""
 F  S CM=$O(@DATA@(ECR,CM)) Q:CM=""  D
 . S TY="" F  S TY=$O(@DATA@(ECR,CM,TY)) Q:TY=""  D
 .. S DTY=$P(^BQI(90507.8,TY,0),U,1),ATY=$P($G(^BQI(90507.8,TY,2)),U,1)
 .. S REP=$P($G(^BQI(90507.8,TY,2)),U,5)
 .. S TME=$S(REP=1:61,REP=2:183,REP=3:365,1:"")
 .. S CDATE=$$DATE^BQIUL1("T-30")
 .. S PT="" F  S PT=$O(@DATA@(ECR,CM,TY,PT)) Q:PT=""  D
 ... S EXP=+$P($G(^BQI(90507.8,TY,2)),U,6) I EXP S ALRT=TY D EXP
 ... K BDZ S LDTE="",SDTE="",DDTE=""
 ... S LDTE=$O(@DATA@(ECR,CM,TY,PT,"LB",""),-1) I LDTE'="" S BDZ(LDTE)="L"
 ... S DDTE=$O(@DATA@(ECR,CM,TY,PT,"DX",""),-1) I DDTE'="" S BDZ(DDTE)="D"
 ... S SDTE=$O(@DATA@(ECR,CM,TY,PT,"SN",""),-1) I SDTE'="" S BDZ(SDTE)="S"
 ... S TYNM=$P(^BQI(90507.8,TY,0),"^",1)
 ... ;B
 ... I '$D(^BQI(90507.7,"AE",PT,TYNM)) D STEC Q
 ... S MDTE=$O(^BQI(90507.7,"AE",PT,TYNM,""),-1)
 ... I MDTE'<CDATE D STEC Q
 ... I TME=""&($D(^BQI(90507.7,"AE",PT,TYNM))) Q
 ... S DTE=$O(BDZ(""))
 ... S DDIF=$$FMDIFF^XLFDT(DTE,MDTE)
 ... I DDIF<TME D STEC Q
 ;
 S DIK="^BQI(90507.6," D IXALL^DIK
 K AIEN,ALRT,ATIEN,ATY,BIEN,BQPT,BQQN,CA,CD,CIEN,CLDTM,CM,CN,COMM,CON,DA
 K CDATE,DIC,DIEN,DIK,DTY,DXCC,DXN,ECR,EVDT,I,IENS,L,LIEN,LTREF,N,PN,PQF,PT
 K PVN,QFL,REP,RIEN,SB,SUB,SYS,TAX,TIEN,TME,TXN,TY,TYNM,VISIT,VSDTM,Y,ZZ,ZNOW
 K BDT,BGDT,CT,DTE,EDT,ENDT,EXIEN,EXP,LBT,LTN,MDTE,OTREF,SEARCH,TREF
 K @TDATA,TDATA
 Q
 ;
STOR ;Store data
 I $G(DDTE)'=""!($G(SDTE)'="") D
 . I DDTE>SDTE D DXN Q
 . I SDTE>DDTE D SNN Q
 . I DDTE=SDTE I DDTE=SDTE D DXN:BDZ(DDTE)="D" D SNN:BDZ(SDTE)="S"
 ;
 I $G(LDTE)'="" D
 . S LBT=""
 . S LBT=$O(@DATA@(ECR,CM,TY,PT,"LB",LDTE,LBT),-1) Q:LBT=""  D
 .. S BIEN="" F  S BIEN=$O(@DATA@(ECR,CM,TY,PT,"LB",LDTE,LBT,BIEN)) Q:BIEN=""  D
 ... S VISIT=$P(@DATA@(ECR,CM,TY,PT,"LB",LDTE,LBT,BIEN),U,1),DTE=LDTE I VISIT="~" Q
 ... D NLAB^BQICALRT(CM,DTY,VISIT,PT,ATY,LBT,@DATA@(ECR,CM,TY,PT,"LB",LDTE,LBT,BIEN))
 ;
 K BDZ,DDTE,SDTE,LDTE
 S CDATE=$$DATE^BQIUL1("T-30")
 Q
 ;
STEC ; Store electronic case reporting cases
 I $G(DDTE)'=""!($G(SDTE)'="") D
 . I DDTE>SDTE D DXN Q
 . I SDTE>DDTE D SNN Q
 . I DDTE=SDTE D DXN:BDZ(DDTE)="D" D SNN:BDZ(SDTE)="S"
 ;
 I $G(LDTE)'="" D
 . S LBT=""
 . S LBT=$O(@DATA@(ECR,CM,TY,PT,"LB",LDTE,LBT),-1) Q:LBT=""  D
 .. S BIEN="" F  S BIEN=$O(@DATA@(ECR,CM,TY,PT,"LB",LDTE,LBT,BIEN)) Q:BIEN=""  D
 ... S VISIT=$P(@DATA@(ECR,CM,TY,PT,"LB",LDTE,LBT,BIEN),U,1),DTE=LDTE I VISIT="~" Q
 ... I 'ECR D NLAB^BQICALRT(CM,DTY,VISIT,PT,ATY,LBT,@DATA@(ECR,CM,TY,PT,"LB",LDTE,LBT,BIEN))
 ... I ECR D EFILE^BQICALRC(CM,DTY,$G(DXCC),LDTE,VISIT,PT,ATY,"LB",@DATA@(ECR,CM,TY,PT,"LB",LDTE,LBT,BIEN))
 ;
 K BDZ,DDTE,SDTE,LDTE
 S CDATE=$$DATE^BQIUL1("T-30")
 Q
 ;
DXN ;
 S DXN=""
 F  S DXN=$O(@DATA@(ECR,CM,TY,PT,"DX",DDTE,DXN)) Q:DXN=""  D
 . I $$VERSION^XPDUTL("BCSV") S DXCC=$$ICD9^BQIUL3(DXN,(DDTE\1),2) ; csv
 . I '$$VERSION^XPDUTL("BCSV") S DXCC=$$GET1^DIQ(80,DXN_",",.01,"E")
 . I DXCC="" Q
 . S BIEN="" F  S BIEN=$O(@DATA@(ECR,CM,TY,PT,"DX",DDTE,DXN,BIEN),-1) Q:BIEN=""  D
 .. S VISIT=$P(@DATA@(ECR,CM,TY,PT,"DX",DDTE,DXN,BIEN),U,1)
 .. I 'ECR D NFILE^BQICALRT(CM,DTY,DXCC,DDTE,VISIT,PT,ATY,@DATA@(ECR,CM,TY,PT,"DX",DDTE,DXN,BIEN))
 .. I ECR D EFILE^BQICALRC(CM,DTY,DXCC,DDTE,VISIT,PT,ATY,"DX",@DATA@(ECR,CM,TY,PT,"DX",DDTE,DXN,BIEN))
 Q
 ;
SNN ;
 S DXN=""
 F  S DXN=$O(@DATA@(ECR,CM,TY,PT,"SN",SDTE,DXN)) Q:DXN=""  D
 . S DXCC=DXN
 . S BIEN="" F  S BIEN=$O(@DATA@(ECR,CM,TY,PT,"SN",SDTE,DXN,BIEN)) Q:BIEN=""  D
 .. S VISIT=$P(@DATA@(ECR,CM,TY,PT,"SN",SDTE,DXN,BIEN),U,1)
 .. I 'ECR D NFILE^BQICALRT(CM,DTY,DXCC,SDTE,VISIT,PT,ATY,@DATA@(ECR,CM,TY,PT,"SN",SDTE,DXN,BIEN))
 .. I ECR D EFILE^BQICALRC(CM,DTY,DXCC,SDTE,VISIT,PT,ATY,"SN",@DATA@(ECR,CM,TY,PT,"SN",SDTE,DXN,BIEN))
 Q
 ;
PROB ;Problem
 S CDATE=$$DATE^BQIUL1("T-30")
 S CON="" F  S CON=$O(^AUPNPROB("ASCT",CON)) Q:CON=""  D
 . S CN=$O(^BSTS(9002318.4,"C",36,CON,"")) I CN="" Q
 . S SUB="PXRM BQI",SB=$O(^BSTS(9002318.4,CN,4,"B",SUB))
 . I $E(SB,1,$L(SUB))'=SUB Q
 . I '$D(^BQI(90507.8,"AB",SB)) Q
 . S CA=$O(^BQI(90507.8,"AB",SB,""))
 . S PN="" F  S PN=$O(^AUPNPROB("ASCT",CON,PN)) Q:PN=""  D
 .. S EVDT=$P(^AUPNPROB(PN,0),"^",8)
 .. I EVDT["." S EVDT=EVDT\1
 .. I EVDT<CDATE Q
 .. S BQPT=$P(^AUPNPROB(PN,0),"^",2),ZZ="SN",VSDTM=EVDT,TIEN=PN,ALRT=CA
 .. S ECR=+$P(^BQI(90507.8,ALRT,0),"^",7)
 .. S COMM=$$GET1^DIQ(9000001,BQPT_",",1117,"I")
 .. I COMM="" S COMM=$$COMM()
 .. S PVN="",PQF=0 F  S PVN=$O(^AUPNPROB(PN,14,"B",PVN)) Q:PVN=""  D
 ... I $D(@DATA@(ECR,COMM,ALRT,BQPT,ZZ,EVDT,CON,PVN)) S PQF=1
 ... S BIEN="" F  S BIEN=$O(@DATA@(ECR,COMM,ALRT,BQPT,ZZ,EVDT,CON,BIEN)) Q:BIEN=""  D
 .... I $P(@DATA@(ECR,COMM,ALRT,BQPT,ZZ,EVDT,CON,BIEN),"^",1)=PVN S PQF=1
 ... I $D(@DATA@(ECR,COMM,ALRT,BQPT,"DX",EVDT,CON,PVN)) S PQF=1
 ... S BIEN="" F  S BIEN=$O(@DATA@(ECR,COMM,ALRT,BQPT,"DX",EVDT,CON,BIEN)) Q:BIEN=""  D
 .... I $P(@DATA@(ECR,COMM,ALRT,BQPT,"DX",EVDT,CON,BIEN),"^",1)=PVN S PQF=1
 .. I 'PQF S @DATA@(ECR,COMM,ALRT,BQPT,ZZ,EVDT,CON,PN)=U_PN_U_9000011
 Q
 ;
SNO ;V POV
 S CDATE=$$DATE^BQIUL1("T-30")
 S CON="" F  S CON=$O(^AUPNVPOV("ASCI",CON)) Q:CON=""  D
 . S CN=$O(^BSTS(9002318.4,"C",36,CON,"")) I CN="" Q
 . S SUB="PXRM BQI",SB=$O(^BSTS(9002318.4,CN,4,"B",SUB))
 . I $E(SB,1,$L(SUB))'=SUB Q
 . I '$D(^BQI(90507.8,"AB",SB)) Q
 . S CA=$O(^BQI(90507.8,"AB",SB,""))
 . S PN="" F  S PN=$O(^AUPNVPOV("ASCI",CON,PN)) Q:PN=""  D
 .. S EVDT=$P($G(^AUPNVPOV(PN,12)),"^",1)\1
 .. S VISIT=$P(^AUPNVPOV(PN,0),"^",3) I VISIT="" Q
 .. S VSDTM=$P(^AUPNVSIT(VISIT,0),"^",1)\1
 .. I EVDT=0 S EVDT=VSDTM
 .. I EVDT<CDATE Q
 .. S BQPT=$P(^AUPNVPOV(PN,0),"^",2),ZZ="SN",VSDTM=EVDT,ALRT=CA
 .. S ECR=+$P(^BQI(90507.8,ALRT,0),"^",7)
 .. S COMM=$$GET1^DIQ(9000001,BQPT_",",1117,"I")
 .. I COMM="" S COMM=$$COMM()
 .. S @DATA@(ECR,COMM,ALRT,BQPT,ZZ,VSDTM,CON,PN)=VISIT_U_PN_"^9000010.07"
 Q
 ;
RXN ; RXNORM Prescriptions
 S CDATE=$$DATE^BQIUL1("T-30"),BGDT=CDATE,ENDT=DT,ECR=1
 F  S BGDT=$O(^PSRX("AL",BGDT)) Q:BGDT\1>ENDT!(BGDT="")  D
 . S RXN="" F  S RXN=$O(^PSRX("AL",BGDT,RXN)) Q:RXN=""  D
 .. S DRN=$P(^PSRX(RXN,0),"^",6),RNRM=$P($G(^PSDRUG(DRN,999999924)),"^",4) I RNRM="" Q
 .. S BQTS=$O(^BSTS(9002318.4,"C",1552,RNRM,"")) I BQTS="" Q
 .. S RSUB=$O(^BSTS(9002318.4,BQTS,4,"B","")) I RSUB="" Q
 .. S ALRT=$O(^BQI(90507.8,"AB",RSUB,"")) I ALRT="" Q
 .. S BQPT=$P(^PSRX(RXN,0),"^",2),ZZ="RX",VSDTM=BGDT\1
 .. S ECR=+$P(^BQI(90507.8,ALRT,0),"^",7) S ECR=1
 .. S COMM=$$GET1^DIQ(9000001,BQPT_",",1117,"I")
 .. I COMM="" S COMM=$$COMM()
 .. S RVDT=9999999-VSDTM
 .. S RIEN="" F  S RIEN=$O(^AUPNVMED("AA",BQPT,RVDT,RIEN)) Q:RIEN=""  D
 ... I $P(^AUPNVMED(RIEN,0),"^",1)=DRN D
 .... S PN=RIEN,VISIT=$P(^AUPNVMED(RIEN,0),"^",3),@DATA@(ECR,COMM,ALRT,BQPT,ZZ,VSDTM,RNRM,PN)=VISIT_U_PN_"^9000010.14"
 .. S ECR=+$P(^BQI(90507.8,ALRT,0),"^",7)
 Q
 ;
DX ;Diagnosis
 S CDATE=$$DATE^BQIUL1("T-30")
 S ALRT=0 F  S ALRT=$O(^BQI(90507.8,ALRT)) Q:'ALRT  D
 . S ECR=+$P(^BQI(90507.8,ALRT,0),"^",7)
 . I 'ECR&($P(^BQI(90507.8,ALRT,0),"^",5)=1) Q
 . S TREF=$NA(^XTMP("BQITAX",$J)) K @TREF
 . S TAX="" F  S TAX=$O(^BQI(90507.8,ALRT,11,"B",TAX)) Q:TAX=""  D BLD^BQITUTL(TAX,.TREF)
 . S ATIEN=0
 . F  S ATIEN=$O(@TREF@(ATIEN)) Q:ATIEN=""  D
 .. ;I ATIEN=500616!(ATIEN=500615) B
 .. ;I ATIEN=500624 B
 .. I $D(^AUPNVPOV("B",ATIEN)) D
 ... S PN="",QFL=0 F  S PN=$O(^AUPNVPOV("B",ATIEN,PN),-1) Q:PN=""!(QFL=1)  D
 .... S BQPT=$P($G(^AUPNVPOV(PN,0)),"^",2),VISIT=$P($G(^AUPNVPOV(PN,0)),"^",3)
 .... I BQPT=""!(VISIT="") Q
 .... S VSDTM=$P($G(^AUPNVSIT(VISIT,0)),"^",1)\1 I VSDTM=0 Q
 .... S EVDT=$P($G(^AUPNVPOV(PN,12)),"^",1)\1
 .... I EVDT=0 S EVDT=VSDTM
 .... I EVDT<CDATE S QFL=1 Q
 .... S COMM=$$GET1^DIQ(9000001,BQPT_",",1117,"I")
 .... I COMM="" S COMM=$$COMM()
 .... S @DATA@(ECR,COMM,ALRT,BQPT,"DX",EVDT,ATIEN,PN)=VISIT_U_PN_"^9000010.07"
 .. I $D(^AUPNPROB("B",ATIEN)) D
 ... S PN="",QFL=0 F  S PN=$O(^AUPNPROB("B",ATIEN,PN),-1) Q:PN=""!(QFL=1)  D
 .... S EVDT=$P(^AUPNPROB(PN,0),"^",8) I EVDT["." S EVDT=EVDT\1
 .... I EVDT<CDATE Q
 .... S BQPT=$P($G(^AUPNPROB(PN,0)),"^",2) I BQPT="" Q
 .... S COMM=$$GET1^DIQ(9000001,BQPT_",",1117,"I")
 .... I COMM="" S COMM=$$COMM()
 .... S PVN="",PQF=0 F  S PVN=$O(^AUPNPROB(PN,14,"B",PVN)) Q:PVN=""  D
 ..... S EVDT=$P($G(^AUPNVSIT(PVN,0)),"^",1)\1 I EVDT=0 Q
 ..... I $D(@DATA@(ECR,COMM,ALRT,BQPT,"DX",EVDT,ATIEN,PVN)) S PQF=1
 .... I 'PQF S @DATA@(ECR,COMM,ALRT,BQPT,"DX",EVDT,ATIEN,PN)=U_PN_U_9000011
 Q
 ;
COMM() ;EP - Get UNKNOWN community
 S COMM=$$FIND1^DIC(9999999.05,"","BX","UNKNOWN","","","ERROR4")
 I COMM=-1 S COMM="Not identified"
 Q COMM
 ;
LAB ;EP - Get labs
 D LTAX1^BQICALRC
 S CDATE=$$DATE^BQIUL1("T-30")
 S ALRT=0 F  S ALRT=$O(^BQI(90507.8,ALRT)) Q:'ALRT  D
 . ;I $P(^BQI(90507.8,ALRT,0),"^",5)=1 Q
 . S ECR=+$P(^BQI(90507.8,ALRT,0),"^",7)
 . D LTAX2^BQICALRC
 . S ATIEN=0 F  S ATIEN=$O(@TREF@(ATIEN)) Q:ATIEN=""  D
 .. I $P(^LAB(60,ATIEN,0),"^",4)'="MI" D
 ... S LIEN="" F  S LIEN=$O(^AUPNVLAB("B",ATIEN,LIEN)) Q:LIEN=""  D
 .... S VISIT=$P($G(^AUPNVLAB(LIEN,0)),"^",3) I VISIT="" Q
 .... S VSDTM=$P($G(^AUPNVSIT(VISIT,0)),"^",1)\1 I VSDTM=0 Q
 .... S CLDTM=$P($G(^AUPNVLAB(LIEN,12)),"^",1)\1
 .... I CLDTM=0 S CLDTM=VSDTM
 .... I CLDTM<CDATE Q
 .... I $P($G(^AUPNVLAB(LIEN,11)),"^",9)="D" Q
 .... S VALUE=$P(^AUPNVLAB(LIEN,0),"^",4) I VALUE="" Q
 .... I '$$POSITIVE^BQITRUTL(VALUE) S ECR=1
 .... K VALUE
 .... S BQPT=$P($G(^AUPNVLAB(LIEN,0)),"^",2) I BQPT="" Q
 .... S COMM=$$GET1^DIQ(9000001,BQPT_",",1117,"I")
 .... I COMM="" S COMM=$$COMM()
 .... S @DATA@(ECR,COMM,ALRT,BQPT,"LB",CLDTM,ATIEN,LIEN)=VISIT_U_LIEN_"^9000010.09^"_$P($G(^LAB(60,ATIEN,0)),"^",1)
 .... S ECR=+$P(^BQI(90507.8,ALRT,0),"^",7)
 .. I $P(^LAB(60,ATIEN,0),"^",4)="MI" D
 ... S LIEN="" F  S LIEN=$O(^AUPNVMIC("B",ATIEN,LIEN)) Q:LIEN=""  D
 .... S VISIT=$P($G(^AUPNVMIC(LIEN,0)),"^",3) I VISIT="" Q
 .... S VSDTM=$P($G(^AUPNVSIT(VISIT,0)),"^",1)\1 I VSDTM=0 Q
 .... S CLDTM=$P($G(^AUPNVMIC(LIEN,12)),"^",1)\1
 .... I CLDTM=0 S CLDTM=VSDTM
 .... I CLDTM<CDATE Q
 .... I $P($G(^AUPNVMIC(LIEN,11)),"^",9)="D" Q
 .... S VALUE=$P(^AUPNVMIC(LIEN,0),"^",7) I VALUE="" Q
 .... I '$$POSITIVE^BQITRUTL(VALUE) S ECR=1
 .... K VALUE
 .... S BQPT=$P($G(^AUPNVMIC(LIEN,0)),"^",2) I BQPT="" Q
 .... S COMM=$$GET1^DIQ(9000001,BQPT_",",1117,"I")
 .... I COMM="" S COMM=$$COMM()
 .... S @DATA@(ECR,COMM,ALRT,BQPT,"LB",CLDTM,ATIEN,LIEN)=VISIT_U_LIEN_"^9000010.25^"_$P($G(^LAB(60,ATIEN,0)),"^",1)
 .... S ECR=+$P(^BQI(90507.8,ALRT,0),"^",7)
 . ; Check ordered
 . S ATIEN=0,CDATE=$$DATE^BQIUL1("T-30"),ECR=1
 . F  S ATIEN=$O(@OTREF@(ATIEN)) Q:ATIEN=""  D
 .. S ORITM=ATIEN_";99LRT",ORTN=$O(^ORD(101.43,"ID",ORITM,"")) I ORTN="" Q
 .. S BDT=CDATE-.0001,EDT=DT
 .. F  S BDT=$O(^OR(100,"AF",BDT)) Q:BDT=""!(BDT\1>EDT)  D
 ... S OIEN="" F  S OIEN=$O(^OR(100,"AF",BDT,OIEN)) Q:OIEN=""  D
 .... I '$D(^OR(100,OIEN,.1,"B",ORTN)) Q
 .... S ODFN=$P(^OR(100,OIEN,0),"^",2)
 .... I ODFN["DPT(" S BQPT=$P(ODFN,";",1)
 .... I $G(BQPT)="" Q
 .... S CLDTM=BDT\1
 .... S COMM=$$GET1^DIQ(9000001,BQPT_",",1117,"I")
 .... I COMM="" S COMM=$$COMM()
 .... I $D(@DATA@(ECR,COMM,ALRT,BQPT,"LB",CLDTM,ATIEN)) Q
 .... S @DATA@(ECR,COMM,ALRT,BQPT,"LB",CLDTM,ATIEN,OIEN)=U_OIEN_"^100"
 . S ECR=+$P(^BQI(90507.8,ALRT,0),"^",7)
 Q
 ;
EXP ;expanded definition
 NEW CTY,BQIN,TMFRAME,DEXEC,EXEC,RES,DTY,ATY,B,SDATA,VISIT,VSDTM,IEN,FILE,TIEN,ZZ
 S CTY=$P($G(^BQI(90507.8,ALRT,2)),U,1)
 S BQIN=$O(^BQI(90508,1,15,"B",CTY,""))
 I BQIN'="" D
 . NEW DA,IENS
 . S DA(1)=1,DA=BQIN,IENS=$$IENS^DILF(.DA)
 . S TMFRAME="T-"_$$GET1^DIQ(90508.015,IENS,.03,"E")
 I BQIN="" S TMFRAME="T-30"
 S ECR=+$P(^BQI(90507.8,ALRT,0),"^",7)
 S DEXEC=$G(^BQI(90507.8,ALRT,31))
 I DEXEC'="" X DEXEC
 ; if EXPANDED DEFINITION has an executable
 ;S EXP=+$P($G(^BQI(90507.8,ALRT,2)),U,6) I EXP 
 S EXEC=$G(^BQI(90507.8,ALRT,30))
 X EXEC
 ; if no result returned from the executable, quit
 I $G(RES(1))=0 K @DATA@(ECR,COMM,ALRT,PT) Q
 S DTY=$P(^BQI(90507.8,ALRT,0),U,1),ATY=$P($G(^BQI(90507.8,ALRT,2)),U,1)
 ; save the result
 S N=0 F  S N=$O(RES(N)) Q:N=""  D
 . S SDATA=RES(N)
 . S VISIT=$P(SDATA,U,4),VSDTM=$P(SDATA,U,2),IEN=$P(SDATA,U,5),FILE=$P(SDATA,U,7),TIEN=$P(SDATA,U,6)
 . S ZZ=$S(FILE=9000010.01:"MS",FILE=9000010.12:"SK",1:"LB")
 . S @DATA@(ECR,COMM,ALRT,PT,ZZ,VSDTM,TIEN)=VISIT_U_IEN_U_FILE
 Q
 ;
ONE ; Only one alert type per patient per 30 day period should be included
 ; Check for community alerts first
 S ECR=0,CM="",CDATE=$$DATE^BQIUL1("T-30")
 F  S CM=$O(@DATA@(ECR,CM)) Q:CM=""  D
 . S TY="" F  S TY=$O(@DATA@(ECR,CM,TY)) Q:TY=""  D
 .. S PT="" F  S PT=$O(@DATA@(ECR,CM,TY,PT)) Q:PT=""  D
 ... S LDTE=$O(@DATA@(ECR,CM,TY,PT,"LB",""),-1)
 ... S SDTE=$O(@DATA@(ECR,CM,TY,PT,"SN",""),-1)
 ... S DDTE=$O(@DATA@(ECR,CM,TY,PT,"DX",""),-1)
 I DTE>LDTE K @DATA@(CM,TY,PT,"DX",DTE) Q
 S LDTE=$$FMADD^XLFDT(DTE,-30)
 S DTE=$O(@DATA@(CM,TY,PT,"LB",""),-1) Q:DTE=""
 S LDTE=$$FMADD^XLFDT(DTE,-30)
 F  S DTE=$O(@DATA@(CM,TY,PT,"LB",DTE),-1) Q:DTE=""  D
 . I DTE>LDTE K @DATA@(CM,TY,PT,"LB",DTE) Q
 . S LDTE=$$FMADD^XLFDT(DTE,-30)
 Q
