BQIDCA12 ;GDIT/HS/ALA-Ad Hoc Logic ; 25 Jul 2024  12:45 PM
 ;;2.9;ICARE MANAGEMENT SYSTEM;**7**;Mar 01, 2021;Build 14
 ;
CONS(FGLOB,TGLOB,FDT,TDT,CDTSRV,CDCAT,CDURG,CDPLAC,CDATTEN,CDSNOM,CDCFRM,CDOFAC,CDREQT,CDPFRM,CDSTAT,MPARMS) ;EP
 NEW CNGLOB
 S CNGLOB=$NA(^TMP("BQICONS",UID)) K @CNGLOB
 K @CRIT@("CONS")
 I $G(TGLOB)="" Q
 ;CDTSRV,CDCAT,CDURG,CDPLAC,CDATTEN,CDSNOM,CDCFRM,CDOFAC,CDREQT,CDPFRM,CDSTAT,
 ;
 S CCNT=0
 ; Determine populate count
 D
 . I $G(CDTSRV)'=""!($D(MPARMS("CDTSRV"))) S CCNT=CCNT+1
 . I $G(CDURG)'=""!($D(MPARMS("CDURG"))) S CCNT=CCNT+1
 . I $G(CDPLAC)'=""!($D(MPARMS("CDPLAC"))) S CCNT=CCNT+1
 . I $G(CDATTEN)'=""!($D(MPARMS("CDATTEN"))) S CCNT=CCNT+1
 . I $G(CDSNOM)'=""!($D(MPARMS("CDSNOM"))) S CCNT=CCNT+1
 . I $G(CDCFRM)'=""!($D(MPARMS("CDCFRM"))) S CCNT=CCNT+1
 . I $G(CDOFAC)'=""!($D(MPARMS("CDOFAC"))) S CCNT=CCNT+1
 . I $G(CDPFRM)'=""!($D(MPARMS("CDPFRM"))) S CCNT=CCNT+1
 . I $G(CDSTAT)'=""!($D(MPARMS("CDSTAT"))) S CCNT=CCNT+1
 . I $G(CDCAT)'="" S CCNT=CCNT+1
 . I $G(CDREQT)'="" S CCNT=CCNT+1
 . S CCNT=CCNT+1
 ;
 I $G(FGLOB)'="" D
 . S CDFN="" F  S CDFN=$O(@FGLOB@(CDFN)) Q:CDFN=""  D
 .. S FDT=$S(FDT'="":FDT-.0001,1:FDT),TDT=$S(TDT'="":TDT,1:DT)
 .. S BDT=9999999-TDT,EDT=9999999-FDT
 .. F  S BDT=$O(^GMR(123,"AD",CDFN,BDT)) Q:BDT=""!((BDT\1)>EDT)  D
 ... S CIEN="" F  S CIEN=$O(^GMR(123,"AD",CDFN,BDT,CIEN)) Q:CIEN=""  D
 .... D CFL(1)
 .... D CCHK
 ;
 I $G(FGLOB)="" D
 . S FDT=$S(FDT'="":FDT-.0001,1:FDT),TDT=$S(TDT'="":TDT,1:DT)
 . F  S FDT=$O(^GMR(123,"E",FDT)) Q:FDT=""!(FDT\1>TDT)  D
 .. S CIEN="" F  S CIEN=$O(^GMR(123,"E",FDT,CIEN)) Q:CIEN=""  D
 ... S CDFN=$P($G(^GMR(123,CIEN,0)),"^",2) I CDFN="" Q
 ... D CFL(1)
 ... D CCHK
 ;
 K @TGLOB
 S CDFN="" F  S CDFN=$O(@CRIT@("CONS",CDFN)) Q:CDFN=""  D
 . S CIEN="" F  S CIEN=$O(@CRIT@("CONS",CDFN,CIEN)) Q:CIEN=""  D
 .. S NCNT=0 F I=1:1:12 S:$P(@CRIT@("CONS",CDFN,CIEN),"^",I)=1 NCNT=NCNT+1
 .. I NCNT'=CCNT K @CRIT@("CONS",CDFN,CIEN) Q
 .. S @TGLOB@(CDFN)=""
 Q
 ;
CFL(POS) ;file record in temp global
 NEW DA,IENS
 I '$D(@CRIT@("CONS",CDFN,CIEN)) S @CRIT@("CONS",CDFN,CIEN)="0^0^0^0^0^0^0^0^0^0^0^0"
 S $P(@CRIT@("CONS",CDFN,CIEN),"^",POS)=1
 Q
 ;
CCHK ;Check for matching criteria
 I $G(CDTSRV)'="",$P(^GMR(123,CIEN,0),"^",5)=CDTSRV D CFL(2)
 I $D(MPARMS("CDTSRV")) S CV="" F  S CV=$O(MPARMS("CDTSRV",CV)) Q:CV=""  I $P(^GMR(123,CIEN,0),"^",5)=CV D CFL(2)
 I $G(CDURG)'="",$P(^GMR(123,CIEN,0),"^",9)=CDURG D CFL(3)
 I $D(MPARMS("CDURG")) S CV="" F  S CV=$O(MPARMS("CDURG",CV)) Q:CV=""  I $P(^GMR(123,CIEN,0),"^",9)=CV D CFL(3)
 I $G(CDPLAC)'="",$P(^GMR(123,CIEN,0),"^",10)=CDPLAC D CFL(4)
 I $D(MPARMS("CDPLAC")) S CV="" F  S CV=$O(MPARMS("CDPLAC",CV)) Q:CV=""  I $P(^GMR(123,CIEN,0),"^",10)=CV D CFL(4)
 I $G(CDATTEN)'="",$P(^GMR(123,CIEN,0),"^",11)=CDATTEN D CFL(5)
 I $D(MPARMS("CDATTEN")) S CV="" F  S CV=$O(MPARMS("CDATTEN",CV)) Q:CV=""  I $P(^GMR(123,CIEN,0),"^",11)=CV D CFL(5)
 I $G(CDSNOM)'="",$P($G(^GMR(123,CIEN,30.1)),"^",1)=CDSNOM D CFL(6)
 I $D(MPARMS("CDSNOM")) S CV="" F  S CV=$O(MPARMS("CDSNOM",CV)) Q:CV=""  I $P($G(^GMR(123,CIEN,30.1)),"^",1)=CV D CFL(6)
 I $G(CDCFRM)'="",$P(^GMR(123,CIEN,0),"^",6)=CDCFRM D CFL(7)
 I $D(MPARMS("CDCFRM")) S CV="" F  S CV=$O(MPARMS("CDCFRM",CV)) Q:CV=""  I $P(^GMR(123,CIEN,0),"^",6)=CV D CFL(7)
 I $G(CDOFAC)'="",$P(^GMR(123,CIEN,0),"^",21)=CDOFAC D CFL(8)
 I $D(MPARMS("CDOFAC")) S CV="" F  S CV=$O(MPARMS("CDOFAC",CV)) Q:CV=""  I $P(^GMR(123,CIEN,0),"^",21)=CV D CFL(8)
 I $G(CDPFRM)'="",$P(^GMR(123,CIEN,0),"^",14)=CDPFRM D CFL(9)
 I $D(MPARMS("CDPFRM")) S CV="" F  S CV=$O(MPARMS("CDPFRM",CV)) Q:CV=""  I $P(^GMR(123,CIEN,0),"^",14)=CV D CFL(9)
 I $G(CDSTAT)'="",$P(^GMR(123,CIEN,0),"^",12)=CDSTAT D CFL(10)
 I $D(MPARMS("CDSTAT")) S CV="" F  S CV=$O(MPARMS("CDSTAT",CV)) Q:CV=""  I $P(^GMR(123,CIEN,0),"^",12)=CV D CFL(10)
 I $G(CDCAT)'="" D
 . I CDCAT="I",$P(^GMR(123,CIEN,0),"^",18)=CDCAT D CFL(11) Q
 . I CDCAT="O",$P(^GMR(123,CIEN,0),"^",18)=CDCAT D CFL(11) Q
 . I CDCAT="B",$P(^GMR(123,CIEN,0),"^",18)'="" D CFL(11)
 I $G(CDREQT)'="" D
 . I CDREQT="C",$P(^GMR(123,CIEN,0),"^",17)=CDREQT D CFL(12) Q
 . I CDREQT="P",$P(^GMR(123,CIEN,0),"^",17)=CDREQT D CFL(12) Q
 . I CDREQT="B",$P(^GMR(123,CIEN,0),"^",17)'="" D CFL(12) Q
 Q
 ;
PFLG(FGLOB,TGLOB,FADT,TADT,FPDT,TPDT,PFSITE,PFFLAG,PFSTAT,MPARMS) ;EP
 Q
