BQIDCAHI ;GDIT/HCSD/ALA-Initialize Panel Def variables ; 16 Mar 2021  11:41 AM
 ;;2.9;ICARE MANAGEMENT SYSTEM;**1,3,5,6,7**;Mar 01, 2021;Build 14
 ;;
 ;
INIT ;EP - Initialize variables
 K IPARMS
 S SEX=$G(SEX,""),COMM=$G(COMM,""),TRIBE=$G(TRIBE,""),DMON=$G(DMON,"")
 S ETHN=$G(ETHN,""),RACE=$G(RACE,""),PLANG=$G(PLANG,""),PCOMM=$G(PCOMM,"")
 S DBFROM=$G(DBFROM,""),DBTHRU=$G(DBTHRU,"")
 S FROM=$G(FROM,""),THRU=$G(THRU,""),FGLOB=$G(FGLOB,""),VSFROM=$G(VSFROM,""),VSTHRU=$G(VSTHRU,"")
 S DXCAT=$G(DXCAT,""),PLIDEN=$G(PLIDEN,""),REMCODE=$G(REMCODE,"")
 S BEN=$G(BEN,"") ; Beneficiary
 S DXOP=$G(DXOP,"!"),VISOP=$G(VISOP,"!"),BPOP=$G(BPOP,"!"),ABPOP=$G(ABPOP,"!"),HFOP=$G(HFOP,"!"),VACOP=$G(VACOP,"!")
 S VAGOP=$G(VAGOP,"!"),HFCOP=$G(HFCOP,"!"),OROP=$G(OROP,"!")
 S RANGE=$G(RANGE,""),VSRANGE=$G(VSRANGE,"")
 S DEC=$G(DEC,"N"),DECCOD=$G(DECCOD,"") ; Deceased
 S LIV=$G(LIV,"Y") ; Living
 S DEMO=$G(DEMO,"E") ; Demo patients
 S INAC=$G(INAC,"N") ; Inactive patients
 S DECFDT=$G(DECFDT,""),DECTDT=$G(DECTDT,"") ;Deceased Date Range
 S DECCOD=$G(DECCOD,"")
 S HRNAC=$G(HRNAC,""),HRNIN=$G(HRNIN,""),HRNDL=$G(HRNDL,""),HRNDV=$G(HRNDV,"")
 S HRNFD=$G(HRNFD,""),HRNTD=$G(HRNTD,"")
 S ALLERGY=$G(ALLERGY,""),ALLOP=$G(ALLOP,"!"),ALNAS=$G(ALNAS,""),ALNKN=$G(ALNKN,"")
 S LAB=$G(LAB,""),MED=$G(MED,""),CPT=$G(CPT,""),POV=$G(POV,""),POVS=$G(POVS,""),MEAS=$G(MEAS,""),EXAM=$G(EXAM,"")
 S LABTX=$G(LABTX,""),MEDTX=$G(MEDTX,""),CPTTX=$G(CPTTX,""),POVTX=$G(POVTX,""),POVSB=$G(POVSB,""),PROBSB=$G(PROBSB,"")
 S LBOP=$G(LBOP,"!"),MDOP=$G(MDOP,"!"),CPOP=$G(CPOP,"!"),PROP=$G(PROP,"!"),EDUOP=$G(EDUOP,"!"),PVOP=$G(PVOP,"!"),MSOP=$G(MSOP,"!"),EXOP=$G(EXOP,"!")
 ;S EMPL=$G(EMPL,"")
 S RMOP=$G(RMOP,"!")
 S GPOP=$G(GPOP,"!"),GPMEAS=$G(GPMEAS,""),GPVAL=$G(GPVAL,"")
 S LNOT=$S($G(LNOT)="Y":1,1:0),MNOT=$S($G(MNOT)="Y":1,1:0),CNOT=$S($G(CNOT)="Y":1,1:0),EDUNOT=$S($G(EDUNOT)="Y":1,1:0),EXNOT=$S($G(EXNOT)="Y":1,1:0)
 S MSNOT=$S($G(MSNOT)="Y":1,1:0)
 S PROB=$G(PROB,""),PRSTAT=$G(PRSTAT,""),PRNDC=$G(PRNDC,""),PRNRV=$G(PRNRV,""),PRNAC=$G(PRNAC,""),PROBS=$G(PROBS,"")
 S PROBTX=$G(PROBTX,"")
 S EDUTX=$G(EDUTX,""),EDUC=$G(EDUC,""),EDUPICK=$G(EDUPICK,""),EDUTOP=$G(EDUTOP,"")
 S OVD=$G(OVD,0),FUT=$G(FUT,0)
 S HFNOT=$S($G(HFNOT)="Y":1,1:0),VACNOT=$S($G(VACNOT)="Y":1,1:0),NTNOT=$S($G(NTNOT)="Y":1,1:0)
 S VACGRP=$G(VACGRP,""),VACC=$G(VACC,""),VACTX=$G(VACTX,"")
 S HFTX=$G(HFTX,""),HFCAT=$G(HFCAT,""),HFACT=$G(HFACT,"")
 S HRISK=$G(HRISK,""),HRNUM=$G(HRNUM,""),HROP=$G(HROP,"!"),NTOP=$G(NTOP,"!")
 S ORITM=$G(ORITM,""),ORLOC=$G(ORLOC,""),ORPROV=$G(ORPROV),ORSTAT=$G(ORSTAT,""),ORCLO=$G(ORCLO,""),ORCLI=$G(ORCLI,"")
 S ORNOLOC=$S($G(ORNOLOC)="Y":1,1:0),ORNOSLOC=$S($G(ORNOSLOC)="Y":1,1:0)
 S ORCLO=$S(ORCLO="Y":1,1:0),ORCLI=$S(ORCLI="Y":1,1:0),ORSLOC=$G(ORSLOC,""),ORNAT=$G(ORNAT,"")
 S NTSTAT=$G(NTSTAT,""),NTHLOC=$G(NTHLOC,""),NTDIV=$G(NTDIV,""),NTAUTH=$G(NTAUTH,""),NTCOSI=$G(NTCOSI,""),NTTIT=$G(NTTIT,"")
 S WCLN=$G(WCLN,""),WPROV=$G(WPROV,""),WPRI=$G(WPRI,""),WAREAS=$G(WAREAS,""),WRREAS=$G(WRREAS,"")
 S WAUSR=$G(WAUSR,""),WRUSR=$G(WRUSR,""),WNOPROV=$S($G(WNOPROV)="Y":1,1:0)
 S VSPROV=$G(VSPROV,""),VSCLN=$G(VSCLN,""),VSSCAT=$G(VSSCAT,""),VSHLOC=$G(VSHLOC,""),VSLOC=$G(VSLOC,""),VSNUM=$G(VSNUM,"")
 S RFTYPE=$G(RFTYPE,""),RFPRI=$G(RFPRI,""),RFVIS=$G(RFVIS,""),RFFAC=$G(RFFAC,""),RFSTAT=$G(RFSTAT,""),RFPROV=$G(RFPROV,"")
 S RFICD=$G(RFICD,""),RFPAY=$G(RFPAY,""),RFSNOM=$G(RFSNOM,""),RFVEN=$G(RFVEN,"")
 S CDTSRV=$G(CDTSRV,""),CDCAT=$G(CDCAT,""),CDURG=$G(CDURG,""),CDPLAC=$G(CDPLAC,""),CDATTEN=$G(CDATTEN,"")
 S CDSNOM=$G(CDSNOM,""),CDCFRM=$G(CDCFRM,""),CDOFAC=$G(CDOFAC,""),CDREQT=$G(CDREQT,""),CDPFRM=$G(CDPFRM,""),CDSTAT=$G(CDSTAT,"")
 ;
 ; If timeframe is selected populate start and end dates
 I VSRANGE'="",$G(PPIEN)'="" D RANGE^BQIDCAH1(VSRANGE,PPIEN,"VSRANGE") S RFROM=$G(RFROM,""),RTHRU=$G(RTHRU,"")
 S VSFROM=$S($G(RFROM)'="":RFROM,1:$G(VSFROM))
 S VSTHRU=$S($G(RTHRU)'="":RTHRU,1:$G(VSTHRU))
 I RANGE'="",$G(PPIEN)'="" D RANGE^BQIDCAH1(RANGE,PPIEN,"RANGE") S RFROM=$G(RFROM,""),RTHRU=$G(RTHRU,"")
 S FROM=$S($G(RFROM)'="":RFROM,1:$G(FROM))
 S THRU=$S($G(RTHRU)'="":RTHRU,1:$G(THRU))
 K RFROM,RTHRU
 ;
 I $G(LRANGE)'="",$G(PPIEN)'="" D RANGE^BQIDCAH1(LRANGE,PPIEN,"LRANGE") S LRFROM=$G(RFROM,""),LRTHRU=$G(RTHRU,"")
 S LFROM=$S($G(LRFROM)'="":LRFROM,1:$G(LFROM))
 S LTHRU=$S($G(LRTHRU)'="":LRTHRU,1:$G(LTHRU))
 K RFROM,RTHRU
 ;
 I $G(MRANGE)'="",$G(PPIEN)'="" D RANGE^BQIDCAH1(MRANGE,PPIEN,"MRANGE") S MRFROM=$G(RFROM,""),MRTHRU=$G(RTHRU,"")
 S MFROM=$S($G(MRFROM)'="":MRFROM,1:$G(MFROM))
 S MTHRU=$S($G(MRTHRU)'="":MRTHRU,1:$G(MTHRU))
 K RFROM,RTHRU
 ;
 I $G(CRANGE)'="",$G(PPIEN)'="" D RANGE^BQIDCAH1(CRANGE,PPIEN,"CRANGE") S CPFROM=$G(RFROM,""),CPTHRU=$G(RTHRU,"")
 S CFROM=$S($G(CPFROM)'="":CPFROM,1:$G(CFROM))
 S CTHRU=$S($G(CPTHRU)'="":CPTHRU,1:$G(CTHRU))
 K RFROM,RTHRU
 ;
 I $G(PRANGE)'="",$G(PPIEN)'="" D RANGE^BQIDCAH1(PRANGE,PPIEN,"PRANGE") S PPFROM=$G(RFROM,""),PPTHRU=$G(RTHRU,"")
 S PFROM=$S($G(PPFROM)'="":PPFROM,1:$G(PRFROM))
 S PTHRU=$S($G(PPTHRU)'="":PPTHRU,1:$G(PRTHRU))
 K RFROM,RTHRU
 ;
 I $G(EDURANGE)'="",$G(PPIEN)'="" D RANGE^BQIDCAH1(EDURANGE,PPIEN,"EDURANGE") S EDFROM=$G(RFROM,""),EDTHRU=$G(RTHRU,"")
 S EFROM=$S($G(EDFROM)'="":EDFROM,1:$G(EDUFROM))
 S ETHRU=$S($G(EDTHRU)'="":EDTHRU,1:$G(EDUTHRU))
 K RFROM,RTHRU
 ;
 I $G(RMDRANGE)'="",$G(PPIEN)'="" D RANGE^BQIDCAH1(RMDRANGE,PPIEN,"RMDRANGE") S RDFROM=$G(RFROM,""),RDTHRU=$G(RTHRU,"")
 S RMFROM=$S($G(RDFROM)'="":RDFROM,1:$G(RMDFROM))
 S RMTHRU=$S($G(RDTHRU)'="":RDTHRU,1:$G(RMDTHRU))
 K RFROM,RTHRU,RDFROM,RDTHRU
 ;
 I $G(PVRANGE)'="",$G(PPIEN)'="" D RANGE^BQIDCAH1(PVRANGE,PPIEN,"PVRANGE") S RDFROM=$G(RFROM,""),RDTHRU=$G(RTHRU,"")
 S PVFROM=$S($G(RDFROM)'="":RDFROM,1:$G(PVFROM))
 S PVTHRU=$S($G(RDTHRU)'="":RDTHRU,1:$G(PVTHRU))
 K RFROM,RTHRU,RDFROM,RDTHRU
 ;
 I $G(MSRANGE)'="",$G(PPIEN)'="" D RANGE^BQIDCAH1(MSRANGE,PPIEN,"MSRANGE") S RDFROM=$G(RFROM,""),RDTHRU=$G(RTHRU,"")
 S MSFROM=$S($G(RDFROM)'="":RDFROM,1:$G(MSFROM))
 S MSTHRU=$S($G(RDTHRU)'="":RDTHRU,1:$G(MSTHRU))
 K RFROM,RTHRU,RDFROM,RDTHRU
 ;
 I $G(EXRANGE)'="",$G(PPIEN)'="" D RANGE^BQIDCAH1(EXRANGE,PPIEN,"EXRANGE") S RDFROM=$G(RFROM,""),RDTHRU=$G(RTHRU,"")
 S EXFROM=$S($G(RDFROM)'="":RDFROM,1:$G(EXFROM))
 S EXTHRU=$S($G(RDTHRU)'="":RDTHRU,1:$G(EXTHRU))
 K RFROM,RTHRU,RDFROM,RDTHRU
 ;
 I $G(HFRANGE)'="",$G(PPIEN)'="" D RANGE^BQIDCAH1(HFRANGE,PPIEN,"HFRANGE") S RDFROM=$G(RFROM,""),RDTHRU=$G(RTHRU,"")
 S HFFROM=$S($G(RDFROM)'="":RDFROM,1:$G(HFFROM))
 S HFTHRU=$S($G(RDTHRU)'="":RDTHRU,1:$G(HFTHRU))
 K RFROM,RTHRU,RDFROM,RDTHRU
 ;
 I $G(VACRANGE)'="",$G(PPIEN)'="" D RANGE^BQIDCAH1(VACRANGE,PPIEN,"VACRANGE") S RDFROM=$G(RFROM,""),RDTHRU=$G(RTHRU,"")
 S VACFROM=$S($G(RDFROM)'="":RDFROM,1:$G(VACFROM))
 S VACTHRU=$S($G(RDTHRU)'="":RDTHRU,1:$G(VACTHRU))
 K RFROM,RTHRU,RDFROM,RDTHRU
 ;
 I $G(ORRANGE)'="",$G(PPIEN)'="" D RANGE^BQIDCAH1(ORRANGE,PPIEN,"ORRANGE") S RDFROM=$G(RFROM,""),RDTHRU=$G(RTHRU,"")
 S ORFROM=$S($G(RDFROM)'="":RDFROM,1:$G(ORFROM))
 S ORTHRU=$S($G(RDTHRU)'="":RDTHRU,1:$G(ORTHRU))
 K RFROM,RTHRU,RDFROM,RDTHRU
 I $G(ORSRANGE)'="",$G(PPIEN)'="" D RANGE^BQIDCAH1(ORSRANGE,PPIEN,"ORSRANGE") S RDFROM=$G(RFROM,""),RDTHRU=$G(RTHRU,"")
 S ORSTARTF=$S($G(RDFROM)'="":RDFROM,1:$G(ORSTARTF))
 S ORSTARTT=$S($G(RDTHRU)'="":RDTHRU,1:$G(ORSTARTT))
 K RFROM,RTHRU,RDFROM,RDTHRU
 I $G(ORPRANGE)'="",$G(PPIEN)'="" D RANGE^BQIDCAH1(ORPRANGE,PPIEN,"ORPRANGE") S RDFROM=$G(RFROM,""),RDTHRU=$G(RTHRU,"")
 S ORSTOPF=$S($G(RDFROM)'="":RDFROM,1:$G(ORSTOPF))
 S ORSTOPT=$S($G(RDTHRU)'="":RDTHRU,1:$G(ORSTOPT))
 K RFROM,RTHRU,RDFROM,RDTHRU
 S IPARMS("ORFROM")=$G(ORFROM),IPARMS("ORTHRU")=$G(ORTHRU),IPARMS("ORSTOPF")=$G(ORSTOPF),IPARMS("ORSTOPT")=$G(ORSTOPT)
 S IPARMS("ORSTARTF")=$G(ORSTARTF),IPARMS("ORSTARTT")=$G(ORSTARTT)
 ;
 I $G(NTRANGE)'="",$G(PPIEN)'="" D RANGE^BQIDCAH1(NTRANGE,PPIEN,"NTRANGE") S RDFROM=$G(RFROM,""),RDTHRU=$G(RTHRU,"")
 S NTFROM=$S($G(RDFROM)'="":RDFROM,1:$G(NTFROM))
 S NTTHRU=$S($G(RDTHRU)'="":RDTHRU,1:$G(NTTHRU))
 K RFROM,RTHRU,RDFROM,RDTHRU
 ;
 I $G(WARANGE)'="",$G(PPIEN)'="" D RANGE^BQIDCAH1(WARANGE,PPIEN,"WARANGE") S WFROM=$G(RFROM,""),WTHRU=$G(RTHRU,"")
 S WAFROM=$S($G(WFROM)'="":WFROM,1:$G(WAFROM))
 S WATHRU=$S($G(WTHRU)'="":WTHRU,1:$G(WATHRU))
 K RFROM,RTHRU,WFROM,WTHRU
 ;
 I $G(WCRANGE)'="",$G(PPIEN)'="" D RANGE^BQIDCAH1(WCRANGE,PPIEN,"WCRANGE") S WFROM=$G(RFROM,""),WTHRU=$G(RTHRU,"")
 S WCFROM=$S($G(WFROM)'="":WFROM,1:$G(WCFROM))
 S WCTHRU=$S($G(WTHRU)'="":WTHRU,1:$G(WCTHRU))
 K RFROM,RTHRU,WFROM,WTHRU
 ;
 I $G(WRRANGE)'="",$G(PPIEN)'="" D RANGE^BQIDCAH1(WRRANGE,PPIEN,"WRRANGE") S WFROM=$G(RFROM,""),WTHRU=$G(RTHRU,"")
 S WRFROM=$S($G(WFROM)'="":WFROM,1:$G(WRFROM))
 S WRTHRU=$S($G(WTHRU)'="":WTHRU,1:$G(WRTHRU))
 K RFROM,RTHRU,WFROM,WTHRU
 ;
 I $G(RFRANGE)'="",$G(PPIEN)'="" D RANGE^BQIDCAH1(RFRANGE,PPIEN,"RFRANGE")
 S RFFROM=$S($G(RFFROM)'="":RFFROM,1:$G(RFROM))
 S RFTHRU=$S($G(RFTHRU)'="":RFTHRU,1:$G(RTHRU))
 ;
 I $G(CDRANGE)'="",$G(PPIEN)'="" D RANGE^BQIDCAH1(CDRANGE,PPIEN,"CDRANGE")
 S CDFROM=$S($G(CDFROM)'="":CDFROM,1:$G(RFROM))
 S CDTHRU=$S($G(CDTHRU)'="":CDTHRU,1:$G(RTHRU))
 K RFROM,RTHRU
 ;
 I $G(PFARANGE)'="",$G(PPIEN)'="" D RANGE^BQIDCAH1(PFARANGE,PPIEN,"PFARANGE")
 S PFAFROM=$S($G(PFAFROM)'="":PFAFROM,1:$G(RFROM))
 S PFATHRU=$S($G(PFATHRU)'="":PFATRHU,1:$G(RTHRU))
 I $G(PFRRANGE)'="",$G(PPIEN)'="" D RANGE^BQIDCAH1(PFRRANGE,PPIEN,"PFRRANGE")
 S PFRFROM=$S($G(PFRFROM)'="":PFRFROM,1:$G(RFROM))
 S PFRTHRU=$S($G(PFRTHRU)'="":PFRTHRU,1:$G(RTHRU))
 K RFROM,RTHRU
 Q
 ;
CLEAN ;EP - Clean up variables
 K JJ,KK,UID,TGLOB,SEX,COMM,PROV,FROM,THRU,AGE,CRIT1,MRANGE,MRFROM,MRTHRU
 K CRIT2,NM,DXCAT,PLIDEN,NUMVIS,COMMTX,BEN,VDATA,VNDATA,VODATA,EMPL,VISOP
 K CLIN,DXOP,RANGE,RFROM,RTHRU,DEC,DECCOD,BNEW,VCRIT1,VCRIT2,DECFDT,DECTDT
 K ALLERGY,ALLOP,LFROM,LTHRU,LRANGE,LRFROM,LRTHRU,LAB,MED,MFROM,MTHRU,VSDTM
 K VIS,MEDTX,LABTX,MDOP,LIV,LBOP,INAC,IEN,CPOP,CFROM,CTHRU,CRANGE,CPT,CPTX
 K PROB,PROP,PPFROM,PPTHRU,PRANGE,PRSTAT,NUMLAB,SETLAB,ETHN,RACE,PLANG,PCOMM
 K DBFROM,DBTHRU,PRNDC,PRNRV,PRNAC,CRIT,ALNAS,ALNKN,LNOT,MNOT,PFROM,PTHRU
 K CNOT,CPTTX,CPFROM,CPTHRU,MD,PRFROM,PRTHRU,PROBTX,EDUFROM,EDUTHRU,EDURANGE
 K EDUTX,EDUC,EDUPICK,EDUTOP,EDUNOT,EDUOP,EDFROM,EDTHRU,EFROM,ETHRU,MDNAC
 K MDNDC,MDNRV,REMCODE,RMDFROM,RMDTHRU,RMDRANGE,OVD,FUT,RMFROM,RDFROM,RMTHRU
 K RDTHRU,DEMO,POV,POVTX,PVFROM,PVTHRU,PVRANGE,POVS,POVSB,MEAS,MSNOT,MSFROM,MSTHRU
 K MSRANGE,MSOP,PVOP,BPOP,ABPOP,EXRANGE,EXAM,EXFROM,EXTHRU,EXNOT,SETEXAM,EXOP
 K ASN,ASSOC,ATYP,AVALUE,CDA,CTYP,GCNT,HFACT,HFCAT,HFFROM,HFNOT,HFOP,HFTHRU,HFTX
 K HRISK,HNUM,HROP,IGP,LIEN,MN,NGLOB,TCT,TN,TOT,VACC,VACFROM,VACGRP,VACNOT,VACOP
 K VACRANGE,VACTHRU,VACTX,VAGOP,VCGLOB,VGGLOB,NTSTAT,NTHLOC,NTDIV,NTAUTH,NTCOSI,NTTIT
 K ORITM,ORLOC,ORPROV,ORSTAT,ORCLO,ORCLI,ORNOLOC,ORNOSLOC,ORCLO,ORCLI,ORSLOC
 K IPARMS,NTFROM,NTNOT,NTOP,NTTHRU,ORFROM,OROP,ORTHRU,HFCOP,HRNUM,CTYP,BGRP,CCT,CNT,ED
 K FDFN,FMON,FND,GP,HC,HCGLOB,HFCOP,HFCT,HFGLOB,HFN,HFRANGE,HRIMUNO,LBRES,LBRSN,LBURNP
 K LCNT,LDFN,LURES,MLB,MSGLOB,NDFN,NDTM,NORES,NT,NTFROM,NTNOT,NTOP,NTRANGE,NTTHRU,OITN
 K OLC,OPRV,OSTT,REDT,RFDT,RV,RVDT,RVFDT,RVL,RVT,RVTDT,SLB,TTT,VGRP,VL,PROBS,PROBSB,PV
 K WAFROM,WATHRU,WCFROM,WCLN,WCTHRU,WPRI,WPROV,WREAS,VSRANGE,VSFROM,VSTHRU,VSSCAT,VSPROV
 K VSLOC,VSHLOC,VSCLN,WAUSR,WRUSR,WRFROM,WRTHRU,WARANGE,WCRANGE,WRRANGE,CRVAL,PRI,REAS,RVF
 K BUS,VSDP,VSPR,VSPS,WAREAS,WNOPROV,WRREAS,TRIBE,RFTYPE,RFPRI,RFVIS,RFFAC,RFSTAT,RFPROV
 K RFICD,RFPAY,RFSNOM,RFVEN,RFRANGE,RFFROM,RFTHRU,VSNUM,GPMEAS,GPOP,GPVAL,HRNAC,HRNIN
 K HRNDL,HRNDV,HRNFD,HRNTD,ORNAT,DMON,CDTSRV,CDCFRM,CDPFRM,CDURG,CDCAT,CDPLACE,CDATTEN
 K CDSNOM,CDOFAC,CDREQT,CDSTAT,CDFROM,CDTHRU,CDRANGE,PFAFROM,PFATHRU,PFRFROM,PFRTHRU
 K PFARANGE,PFRRANGE,PFSITE,PFFLAG,PFSTAT
 Q
