BQIETX ;GDIT/HS/ALA-CREATED BY ^ATXSTX ON APR 11, 2024;
 ;;2.9;ICARE MANAGEMENT SYSTEM;**7**;Mar 01, 2021;Build 14
 ;
 ; See referenced routines to see taxonomies being loaded.
 ;
START ;
 D ^BQIETXA ;   BQI ANAPLASMOSIS MICROSCO LNC
 D ^BQIETXB ;   BQI ANTHRAX DNA LOINC
 D ^BQIETXC ;   BQI ANTHRAX OTHER LOINC
 D ^BQIETXD ;   BQI ARBORVIRAL ANTIBODY LOINC
 D ^BQIETXE ;   BQI ARBORVIRAL ANTIGEN LOINC
 D ^BQIETXF ;   BQI ARBORVIRAL NUCLEIC LOINC
 D ^BQIETXG ;   BQI BLASTOMYCES ANTIBODY LOINC
 D ^BQIETXH ;   BQI BLASTOMYCES ANTIGEN LOINC
 D ^BQIETXI ;   BQI BLASTOMYCES NUCLEIC LOINC
 D ^BQIETXJ ;   BQI BLOOD LEAD LOINC
 D ^BQIETXK ;   BQI BRUCELLOSIS ANTIBODY LOINC
 D ^BQIETXL ;   BQI CALIF SEROGRP ANTIBODY LNC
 D ^BQIETXM ;   BQI CALIF SEROGRP NUCLEIC LNC
 D ^BQIETXN ;   BQI CAMPYLOBACTERIOSIS AG LNC
 D ^BQIETXO ;   BQI CAMPYLOBACTERIOSIS CULT LC
 D ^BQIETXP ;   BQI CAMPYLOBACTERIOSIS NUCL LC
 D ^BQIETXQ ;   BQI CARBON MONOXIDE BLOOD LNC
 D ^BQIETXR ;   BQI CHIKUNGUNYA ANTIBODY LNC
 D ^BQIETXS ;   BQI CHIKUNGUNYA NUCLEIC LOINC
 D ^BQIETXT ;   BQI CHLAMYDIA ANTIGEN LOINC
 D ^BQIETXU ;   BQI CHLAMYDIA NUCLEIC LOINC
 D ^BQIETXV ;   BQI COLORADO TICK ANTIBODY LNC
 D ^BQIETXW ;   BQI COVID ECR ANTIBODY LOINC
 D ^BQIETXX ;   BQI COVID ECR ANTIGEN LOINC
 D ^BQIETXY ;   BQI COVID ECR NUCLEIC LOINC
 D ^BQIETXZ ;   BQI COVID ECR PANELS GENOMIC
 Q
