BQIHEADR ;GDHS/HSD/ALA-Standard Display Header ; 05 Feb 2016  9:32 AM
 ;;2.9;ICARE MANAGEMENT SYSTEM;**3,5**;Mar 01, 2021;Build 20
 ;
 ;
 ; This is the standard display header for each patient
 ; where most of the information is hidden but translated
 ; by the GUI
 ;
HDR(OWNR,PLIEN,DFN,HHDR,HVAL) ;EP - Header
 NEW IEN,HDR,VALUE,HEADR,DORD,HDOB,Y,ORD
 S VALUE=""
 I DFN'="" S Y=$$GET1^DIQ(9000001,DFN_",",1102.2,"I"),HDOB=$$FMTE^BQIUL1(Y)
 I DFN'="" S VALUE=DFN_U_$$FLG^BTPWPPAT(DFN)_U_$$FLG^BQIULPT(OWNR,PLIEN,DFN)_U_$$SENS^BQIULPT(DFN)_U_$$CALR^BQIULPT(DFN)_U_$$MFLAG^BQIULPT(OWNR,PLIEN,DFN)_U_HDOB_U
 S HEADR="I00010DFN^T00001TICKLER_INDICATOR^T00001FLAG_INDICATOR^T00001SENS_FLAG^T00001COMM_FLAG^T00001HIDE_MANUAL^D00030HIDE_DOB^"
 S HVAL=VALUE,HHDR=HEADR
 Q
 ;
THDR(OWNR,PLIEN,DFN,HHDR,HVAL) ;EP - Non hidden header
 NEW IEN,HDR,VALUE,HEADR,SENS,HDOB,Y,STVW,TEXT,ORD,GMET,GHDR,RGIEN
 NEW GIEN,CIEN,ATAGN,ATAGNM,ATAGST,TYP,DIS,REMDESC
 S VALUE="",RGIEN=""
 I DFN'="" S Y=$$GET1^DIQ(9000001,DFN_",",1102.2,"I"),HDOB=$$FMTE^BQIUL1(Y)
 I DFN'="" S VALUE=DFN_U_$$FLG^BTPWPPAT(DFN)_U_$$FLG^BQIULPT(DUZ,PLIEN,DFN)_U_$$SENS^BQIULPT(DFN)_U_$$CALR^BQIULPT(DFN)_U_$$MFLAG^BQIULPT(OWNR,PLIEN,DFN)_U_HDOB_U
 S HEADR="I00010DFN^T00001TICKLER_INDICATOR^T00001FLAG_INDICATOR^T00001SENS_FLAG^T00001COMM_FLAG^T00001HIDE_MANUAL^D00030HIDE_DOB^"
 S HEADR=HEADR_"I00010HIDE_ASSOC_TAG_IEN^T00030HIDE_ASSOC_TAG_NAME^T00001HIDE_ASSOC_TAG_STATUS^"
 I CTYP="RE" S HEADR=HEADR_"T00010HIDE_REMCODE^T00015HIDE_REMMETH^"
 ;
 S RGIEN=$P(^BQI(90506.5,CRN,0),U,3) I RGIEN'="" S REG=$P(^BQI(90507,RGIEN,0),U,1)
 S ATAGN=$P(^BQI(90506.5,CRN,0),U,11),ATAGST=""
 I ATAGN="" S ATAGNM="{None}",ATAGST=""
 I ATAGN'="" S ATAGNM=$P(^BQI(90506.2,ATAGN,0),U,1)
 I DFN'="" S ATAGST=$$CTAG^BQITDUTL(DFN,ATAGNM)
 I ATAGST="" S ATAGN="",ATAGNM="{None}"
 S VALUE=VALUE_ATAGN_U_ATAGNM_U_ATAGST_U
 I CTYP="RE" D
 . S PRN=$O(^BQICARE(OWNR,1,PLIEN,15,"B","REMCODE",""))
 . S REMCODE=$P(^BQICARE(OWNR,1,PLIEN,15,PRN,0),U,2),REMDESC=$$VAL^BQIRMDR1(REMCODE)
 . S VALUE=VALUE_REMCODE_$C(29)_REMDESC_U_$$GET1^DIQ(9000001,DFN_",",4002,"E")_U
 ;
 ; Check for template
 NEW DA,IENS,TEMPL,LYIEN,QFL
 S TEMPL=""
 I OWNR'=DUZ D
 . S DA=$O(^BQICARE(OWNR,1,PLIEN,30,DUZ,4,"C",CTYP,""))
 . I DA="" Q
 . S DA(3)=OWNR,DA(2)=PLIEN,DA(1)=DUZ,IENS=$$IENS^DILF(.DA)
 . S TEMPL=$$GET1^DIQ(90505.34,IENS,.01,"E")
 I OWNR=DUZ D
 . S DA=$O(^BQICARE(OWNR,1,PLIEN,4,"C",CTYP,""))
 . I DA="" Q
 . S DA(2)=OWNR,DA(1)=PLIEN,IENS=$$IENS^DILF(.DA)
 . S TEMPL=$$GET1^DIQ(90505.14,IENS,.01,"E")
 ;
 ; If template, use it
 I TEMPL'="" S TQFL=0 D  G FIN:'TQFL
 . S LYIEN=$$TPN^BQILYUTL(DUZ,TEMPL)
 . I LYIEN="" S TQFL=1 Q
 . I $O(^BQICARE(OWNR,1,PLIEN,23,"B",CARE,""))'="" S TQFL=1 Q
 . S DOR=""
 . F  S DOR=$O(^BQICARE(DUZ,15,LYIEN,1,"C",DOR)) Q:DOR=""  D
 .. S IEN=""
 .. F  S IEN=$O(^BQICARE(DUZ,15,LYIEN,1,"C",DOR,IEN)) Q:IEN=""  D
 ... S CODE=$P(^BQICARE(DUZ,15,LYIEN,1,IEN,0),U,1)
 ... S GIEN=$O(^BQI(90506.1,"B",CODE,""))
 ... I GIEN'="" D
 .... S STVW=GIEN
 .... I $P($G(^BQI(90506.1,GIEN,0)),U,10)=1 Q
 .... D CVAL
 ... I GIEN="" S IFL=0 D  Q:IFL
 .... S STVCD=CODE
 .... D CKO
 ... S HEADR=HEADR_HDR_"^"
 ;
 ; If no template, check for customized
 I OWNR=DUZ D
 . S CIEN=$O(^BQICARE(OWNR,1,PLIEN,23,"B",CARE,""))
 . I CIEN'="" D
 .. S IEN=0
 .. I $O(^BQICARE(OWNR,1,PLIEN,23,CIEN,1,IEN))="" D DEF Q
 .. F  S IEN=$O(^BQICARE(OWNR,1,PLIEN,23,CIEN,1,IEN)) Q:'IEN  D
 ... S CODE=$P(^BQICARE(OWNR,1,PLIEN,23,CIEN,1,IEN,0),"^",1) Q:CODE=""
 ... S GIEN=$O(^BQI(90506.1,"B",CODE,""))
 ... I GIEN'="" D
 .... S STVW=GIEN
 .... I $P($G(^BQI(90506.1,GIEN,0)),U,10)=1 Q
 .... D CVAL
 ... I GIEN="" S IFL=0 D  Q:IFL
 .... S STVCD=CODE
 .... D CKO
 ... S HEADR=HEADR_HDR_"^"
 . ;
 . ; If no customized, use default
 . I CIEN="" D DEF
 ;
 I OWNR'=DUZ D
 . S CIEN=$O(^BQICARE(OWNR,1,PLIEN,30,DUZ,23,"B",CARE,""))
 . I CIEN'="" D
 .. S IEN=0
 .. I $O(^BQICARE(OWNR,1,PLIEN,30,DUZ,23,CIEN,1,IEN))="" D DEF Q
 .. F  S IEN=$O(^BQICARE(OWNR,1,PLIEN,30,DUZ,23,CIEN,1,IEN)) Q:'IEN  D
 ... S CODE=$P(^BQICARE(OWNR,1,PLIEN,30,DUZ,23,CIEN,1,IEN,0),"^",1) Q:CODE=""
 ... S GIEN=$O(^BQI(90506.1,"B",CODE,""))
 ... I GIEN'="" D
 .... S STVW=GIEN
 .... I $P($G(^BQI(90506.1,GIEN,0)),U,10)=1 Q
 .... K VAL
 .... D CVAL
 ... I GIEN="" S IFL=0 D  Q:IFL
 .... S STVCD=CODE
 .... D CKO
 ... S HEADR=HEADR_HDR_"^"
 . I CIEN="" D DEF
 ;
FIN ; Finish
 S HEADR=$$TKO^BQIUL1(HEADR,"^")
 S HVAL=VALUE,HHDR=HEADR
 Q
 ;
CVAL ; Get demographic values
 ;Parameters
 ;  FIL  = FileMan file number
 ;  FLD  = FileMan field number
 ;  EXEC = If an executable is needed to determine value
 ;  HDR  = Header value
 ;the executable expects the value to be returned in variable VAL
 NEW FIL,FLD,EXEC,RCODE,RGIEN,RIEN,RHDR,MVALUE,CODE,GIEN
 S VAL=""
 S GIEN=STVW
 S HDR=$$GET1^DIQ(90506.1,GIEN_",",.08,"E")
 ;
 S RCODE=$$GET1^DIQ(90506.1,GIEN_",",.01,"E")
 S RGIEN=$O(^BQI(90506.3,"AC",CRIEN,"")),VAL=""
 I RGIEN'="" D  Q:VAL'=""
 . S RIEN=$O(^BQI(90506.3,RGIEN,10,"AC",RCODE,""))
 . I RIEN'="",$P($G(^BQI(90506.3,RGIEN,10,RIEN,1)),U,1)="M" D  Q
 .. S RHDR=$P(^BQI(90506.3,RGIEN,10,RIEN,0),U,2),MVALUE=""
 .. NEW SNAME,SRIEN,SORD,SXREF,SIEN
 .. S SNAME=$P(^BQI(90506.3,RGIEN,10,RIEN,0),U,1)
 .. S SRIEN=$O(^BQI(90506.3,"B",SNAME,"")) I SRIEN="" Q
 .. S SORD="",SXREF=$S($D(^BQI(90506.3,SRIEN,10,"AF")):"AF",1:"C")
 .. F  S SORD=$O(^BQI(90506.3,SRIEN,10,SXREF,SORD)) Q:SORD=""  D
 ... S SIEN=""
 ... F  S SIEN=$O(^BQI(90506.3,SRIEN,10,SXREF,SORD,SIEN)) Q:SIEN=""  D
 .... I $P(^BQI(90506.3,SRIEN,10,SIEN,0),U,4)'="S" Q
 .... S CODE=$P(^BQI(90506.3,SRIEN,10,SIEN,0),U,7) I CODE="" Q
 .... S STVW=$O(^BQI(90506.1,"B",CODE,"")) I STVW="" Q
 .... I $$GET1^DIQ(90506.1,STVW_",",.1,"I")=1 Q
 .... S HDR=RHDR
 Q
 ;
ERR ;
 D ^%ZTER
 NEW Y,ERRDTM
 S Y=$$NOW^XLFDT() X ^DD("DD") S ERRDTM=Y
 S BMXSEC="Recording that an error occurred at "_ERRDTM
 I $D(II),$D(DATA) S II=II+1,@DATA@(II)=$C(31)
 Q
 ;
DEF ; Default list of fields
 NEW CRIEN,TYP,ORD,IEN,STVW,KEY,CODE
 ; Check for any alternate display order which trumps source display order
 S CRIEN=$$FIND1^DIC(90506.5,"","OB",CARE,"","","ERROR")
 S TYP=$P(^BQI(90506.5,CRIEN,0),U,2)
 S ORD=""
 F  S ORD=$O(^BQI(90506.1,"AF",TYP,ORD)) Q:ORD=""  D
 . S IEN=""
 . F  S IEN=$O(^BQI(90506.1,"AF",TYP,ORD,IEN)) Q:IEN=""  D
 .. I $$GET1^DIQ(90506.1,IEN_",",.1,"I")=1 Q
 .. S KEY=$$GET1^DIQ(90506.1,IEN_",",3.1,"E")
 .. I KEY'="",'$$KEYCHK^BQIULSC(KEY,DUZ) Q
 .. I $$GET1^DIQ(90506.1,IEN_",",3.04,"I")'="O" D
 ... S CODE=$P(^BQI(90506.1,IEN,0),U,1) Q:CODE=""
 ... I $P($G(^BQI(90506.1,IEN,0)),U,10)=1 Q
 ... S STVW=IEN
 ... D CVAL
 ... S HEADR=HEADR_HDR_"^"
 ;
 S CRIEN=$$FIND1^DIC(90506.5,"","OB","Patient","","","ERROR")
 S TYP=$P(^BQI(90506.5,CRIEN,0),U,2)
 S ORD=""
 F  S ORD=$O(^BQI(90506.1,"AD",TYP,ORD)) Q:ORD=""  D
 . S IEN=""
 . F  S IEN=$O(^BQI(90506.1,"AD",TYP,ORD,IEN)) Q:IEN=""  D
 .. I $$GET1^DIQ(90506.1,IEN_",",.1,"I")=1 Q
 .. S KEY=$$GET1^DIQ(90506.1,IEN_",",3.1,"E")
 .. I KEY'="",'$$KEYCHK^BQIULSC(KEY,DUZ) Q
 .. I $$GET1^DIQ(90506.1,IEN_",",3.04,"I")'="O" D
 ... S CODE=$P(^BQI(90506.1,IEN,0),U,1) Q:CODE=""
 ... I $P($G(^BQI(90506.1,IEN,0)),U,10)=1 Q
 ... S STVW=IEN
 ... D CVAL
 ... S HEADR=HEADR_HDR_"^"
 ;
 NEW CRIEN,TYP,ORD,IEN,STVW,KEY,CODE
 S CRIEN=$$FIND1^DIC(90506.5,"","OB",CARE,"","","ERROR")
 S TYP=$P(^BQI(90506.5,CRIEN,0),U,2),ATAGN=$P(^BQI(90506.5,CRIEN,0),U,11)
 S ORD=""
 F  S ORD=$O(^BQI(90506.1,"AD",TYP,ORD)) Q:ORD=""  D
 . S IEN=""
 . F  S IEN=$O(^BQI(90506.1,"AD",TYP,ORD,IEN)) Q:IEN=""  D
 .. I $$GET1^DIQ(90506.1,IEN_",",.1,"I")=1 Q
 .. S KEY=$$GET1^DIQ(90506.1,IEN_",",3.1,"E")
 .. I KEY'="",'$$KEYCHK^BQIULSC(KEY,DUZ) Q
 .. I $$GET1^DIQ(90506.1,IEN_",",3.04,"I")'="O" D
 ... S CODE=$P(^BQI(90506.1,IEN,0),U,1) Q:CODE=""
 ... I $P($G(^BQI(90506.1,IEN,0)),U,10)=1 Q
 ... S STVW=IEN
 ... D CVAL
 ... S HEADR=HEADR_HDR_"^"
 ;
 ; if additional fields
 NEW CSIEN,STVCD
 S CSIEN=0
 F  S CSIEN=$O(^BQI(90506.5,CRIEN,10,CSIEN)) Q:'CSIEN  D
 . S STVCD=$P(^BQI(90506.5,CRIEN,10,CSIEN,0),U,1)
 . I $P(^BQI(90506.5,CRIEN,10,CSIEN,0),U,9)=1 Q
 . I $P(^BQI(90506.5,CRIEN,10,CSIEN,0),U,6)'="O" D
 .. D CKO
 .. S HEADR=HEADR_HDR_"^"
 ; If there is a dx tag, check for additional locally added columns
 I ATAGN'="" D
 . NEW CSIEN,STVCD
 . S CSIEN=0
 . F  S CSIEN=$O(^BQI(90506.2,ATAGN,6,CSIEN)) Q:'CSIEN  D
 .. S STVCD=$P(^BQI(90506.2,ATAGN,6,CSIEN,0),U,1)
 .. I $P(^BQI(90506.2,ATAGN,6,CSIEN,0),U,9)=1 Q
 .. I $P(^BQI(90506.2,ATAGN,6,CSIEN,0),U,6)'="O" D
 ... D CKO
 ... S HEADR=HEADR_HDR_"^"
 Q
 ;
CKO ; Check other
 NEW BQDTFRM
 S GIEN=$O(^BQI(90506.5,CRN,10,"B",STVCD,""))
 I GIEN'="" D  Q
 . ;Set HEADR
 . S DIS=$P(^BQI(90506.5,CRN,10,GIEN,0),U,5)
 . I $P(^BQI(90506.5,CRN,10,GIEN,0),U,9)=1 S IFL=1 Q
 . S BQDTFRM=$P(^BQI(90506.5,CRN,10,GIEN,0),U,8) S:BQDTFRM="" BQDTFRM="S"
 . ;Get Value
 . I DIS="" S HDR="T00025"_STVCD
 . I DIS="D" D
 .. S HDR="D00030"_STVCD
 . I DIS="R" S HDR="T00025"_STVCD
 . I DIS="B" D
 .. S HDR="T00025"_STVCD
 I GIEN="",ATAGN'="" S GIEN=$O(^BQI(90506.2,ATAGN,6,"B",STVCD,""))
 I GIEN'="" D  Q
 . ;Set HEADR
 . S DIS=$P(^BQI(90506.2,ATAGN,6,GIEN,0),U,5)
 . I $P(^BQI(90506.2,ATAGN,6,GIEN,0),U,9)=1 S IFL=1 Q
 . S BQDTFRM=$P(^BQI(90506.2,ATAGN,6,GIEN,0),U,8) S:BQDTFRM="" BQDTFRM="S"
 . I DIS="D" S HDR="T00020"_STVCD
 . I DIS="R" S HDR="T00025"_STVCD
 . I DIS="B" S HDR="T00025"_STVCD
 Q
