BQIHTX ;GDIT/HS/ALA-CREATED BY ^ATXSTX ON APR 11, 2024;
 ;;2.9;ICARE MANAGEMENT SYSTEM;**7**;Mar 01, 2021;Build 14
 ;
 ; See referenced routines to see taxonomies being loaded.
 ;
START ;
 D ^BQIHTXA ;   BQI COVID ADDTL DOSE CPTS
 D ^BQIHTXB ;   BQI COVID ALL CPTS
 D ^BQIHTXC ;   BQI COVID SHOT1 CPTS
 D ^BQIHTXD ;   BQI COVID SHOT2 CPTS
 D ^BQIHTXE ;   BQI INFLUENZA A ANTIGEN
 D ^BQIHTXF ;   BQI INFLUENZA A CULTURE
 D ^BQIHTXG ;   BQI INFLUENZA A NUCLEIC
 D ^BQIHTXH ;   BQI INFLUENZA CULT ID LOINC
 D ^BQIHTXI ;   BQI INFLUENZA NUCLEIC LOINC
 D ^BQIHTXJ ;   BQI JAKOB CREUTZ PROTEIN LOINC
 D ^BQIHTXK ;   BQI JAPAN ENCEPH ANTIBODY LNC
 D ^BQIHTXL ;   BQI LEGIONNAIRE ANTIBODY LNC
 D ^BQIHTXM ;   BQI LEGIONNAIRE NUCLEIC LNC
 D ^BQIHTXN ;   BQI LEPTOSPIROSIS ANTIBODY LNC
 D ^BQIHTXO ;   BQI LISTERIOSIS MONOCYTOGENES
 D ^BQIHTXP ;   BQI LYME ANTIBODY LOINC
 D ^BQIHTXQ ;   BQI LYME NUCLEIC ACID LOINC
 D ^BQIHTXR ;   BQI MALARIA NUCLEIC LOINC
 D ^BQIHTXS ;   BQI MENINGITIDIS NUCLEIC LNC
 D ^BQIHTXT ;   BQI MERS NUCLEIC ACID LOINC
 D ^BQIHTXU ;   BQI MUMPS ANTIBODY LOINC
 D ^BQIHTXV ;   BQI MUMPS NUCLEIC LOINC
 D ^BQIHTXW ;   BQI MYCOBCT INF CULTURE LOINC
 D ^BQIHTXX ;   BQI MYCOBCT INF NUCLEIC LOINC
 D ^BQIHTXY ;   BQI NAEGELERIA PAM CULT LOINC
 D ^BQIHTXZ ;   BQI OPIOID QUALITATIVE LNC
 Q
