BQIIMINT ;GDIT/HCSD/ALA-Initialize Immunizations ; 23 Feb 2023  6:16 PM
 ;;2.9;ICARE MANAGEMENT SYSTEM;**5**;Mar 01, 2021;Build 20
 ;
BEG ;Begin data find
 K ^XTMP("BQIIMINT")
 S ^XTMP("BQIIMINT",0)=$$FMADD^XLFDT(DT,14)_U_DT_U_"Child/Adol Immunizations"
 S DOB=$$DATE^BQIUL1("T-216M")
 F  S DOB=$O(^DPT("ADOB",DOB)) Q:DOB=""  D
 . S DFN="" F  S DFN=$O(^DPT("ADOB",DOB,DFN)) Q:DFN=""  D
 .. S IEN="" F  S IEN=$O(^AUPNVIMM("AC",DFN,IEN)) Q:IEN=""  D
 ... S VIS=$P(^AUPNVIMM(IEN,0),"^",3),IMM=$P(^(0),"^",1)
 ... S VSDTM=$P(^AUPNVSIT(VIS,0),"^",1)\1 I VSDTM<DOB Q
 ... S ^XTMP("BQIIMINT",DFN,VSDTM,IEN)=IMM_"^"_$P(^AUTTIMM(IMM,0),"^",2)_"^"_$$GET1^DIQ(9999999.14,IMM_",",.09,"E")_"^"_$$AGE^BQIAGE(DFN,VSDTM,1)
 ;
EPT ; Each Patient
 S DFN="" F  S DFN=$O(^XTMP("BQIIMINT",DFN)) Q:DFN=""  D
 . S DATE="" F  S DATE=$O(^XTMP("BQIIMINT",DFN,DATE)) Q:DATE=""  D
 .. S IEN="" F  S IEN=$O(^XTMP("BQIIMINT",DFN,DATE,IEN)) Q:IEN=""  D
 ... S IMM=$P(^XTMP("BQIIMINT",DFN,DATE,IEN),"^",1),AGE=$$AGE^BQIAGE(DFN,DATE,1)
 ... S GRN=$P(^AUTTIMM(IMM,0),"^",9) I GRN="" Q
 ... S CMP=0 F I=21:1:26 I $P(^AUTTIMM(IMM,0),"^",I)'="" S CMP=1
 ... I 'CMP S ZZ(GRN,IMM,IEN)=DATE_"^"_$$AGE^BQIAGE(DFN,DATE,1),AZZ(AGE,GRN,IMM,IEN)=DATE
 ... I CMP F I=21:1:26 S CIMM=$P(^AUTTIMM(IMM,0),"^",I) I CIMM'="" D
 .... S GRN=$P(^AUTTIMM(CIMM,0),"^",9) I GRN="" Q
 .... S ZZ(GRN,CIMM,IEN)=DATE_"^"_$$AGE^BQIAGE(DFN,DATE,1),AZZ(AGE,GRN,IMM,IEN)=DATE
 . D IRPT(DFN)
 . K AZZ,BQWW,BQZZ,ZZ
 Q
 ;
IRPT(IDFN) ;EP - Parse Immun Forecaster Report
 NEW BDB,BDE,BFB,BFE,BIDATES,BIFFLU,BIVG0,C0LOGLOC,CODE,CT,DUE
 NEW EARL,FUT,GLOBAL,GN,GX,I,IMIEN,IMM,IMN,IN,INPLV,IZN,J,JJOHDID
 NEW OFF0,OFF1,OFF2,OFFS,OK,OUTPLV,OVD,REC,REMDUE,REMLAST,REMNEXT
 NEW STAT,VALUE,VPRCNT,SUB,RMDATE
 ;
 I $G(BIDUZ2)="" S BIDUZ2=$P(^BQI(90508,1,0),"^",1)
 ;
 S RMDATE=$S($$AGE^BQIAGE(IDFN,"")>3:365,1:7)
 D IMMPROF^BIRPC(.GLOBAL,IDFN,$$FMADD^XLFDT(DT,RMDATE))
 ;
 I @GLOBAL@(1)["not in the Immunization Register" D
 . D ADDPAT^BIPATE(IDFN,BIDUZ2,.BIERR,$G(DT),"n")
 . D IMMPROF^BIRPC(.GLOBAL,IDFN,$$FMADD^XLFDT(DT,RMDATE))
 ;
 S I="" F  S I=$O(@GLOBAL@(I)) Q:I=""  D
 . I @GLOBAL@(I)["IMM HISTORY EVALUATION" S BDB=I,BST=BDB+4
 . I @GLOBAL@(I)["FORECAST" S BFE=I-1
 ;
 I $G(BDB)="" Q
 K BQZZ,BQYY
 S CT=0 F I=BST:1:BFE D
 . S VALUE=$$TKO^BQIUL1(@GLOBAL@(I),$C(30))
 . I VALUE=" " Q
 . S CT=CT+1,BQZZ(CT)=VALUE
 ;
PARS ;
 S N="" F  S N=$O(BQZZ(N)) Q:N=""  D
 . S VALUE=BQZZ(N)
 . S IDATE=$E(VALUE,1,10),P=11 I IDATE="          " Q
 . I $$DATE^BQIUL1(IDATE)="" Q
 . F I=P:1 Q:$E(VALUE,I,I)'=" "
 . F J=I:1 Q:$E(VALUE,J,J)=" "
 . S CVX=+$E(VALUE,I,J)
 . S STAT=$E(VALUE,42,46) I STAT'="VALID" D
 .. F P=42:1 Q:$E(VALUE,P,P)=":"
 .. S STAT=$E(VALUE,42,P)
 . I STAT["INVALID" D
 .. S R1=$P(BQZZ(N),"INVALID:",2),R2=$G(BQZZ(N+1)),STAT=$P(STAT,":",1)
 .. F I=1:1:$L(R2) I $E(R2,I,I)'=" " Q
 .. S WHY=R1_$E(R2,I,$L(R2))
 . S BQWW(CVX,IDATE,STAT)=$G(WHY)
 . K WHY,R1,STAT,R2
 ;
 S CVX="" F  S CVX=$O(BQWW(CVX)) Q:CVX=""  D
 . S IZ=$O(^AUTTIMM("C",CVX,""))
 . S GRN=$P(^AUTTIMM(IZ,0),"^",9) I GRN="" Q
 . S GRP=$O(^BQIIMM("B",GRN,"")) I GRP="" Q
 . S NAM=$P(^BQIIMM(GRP,0),"^",2),ORD=$P(^BISERT(GRN,0),"^",2)
 . S IDATE="" F  S IDATE=$O(BQWW(CVX,IDATE)) Q:IDATE=""  D
 .. S FDATE=$$DATE^BQIUL1(IDATE),STAT=""
 .. F  S STAT=$O(BQWW(CVX,IDATE,STAT)) Q:STAT=""  D
 ... D STOR
 ;
 ;do count by group
 S GRN=0 F  S GRN=$O(^BQIPAT(IDFN,80,GRN)) Q:'GRN  D
 . S CNT=0,CN=0 F  S CN=$O(^BQIPAT(IDFN,80,GRN,1,CN)) Q:'CN  D
 .. I $P(^BQIPAT(IDFN,80,GRN,1,CN,0),"^",4)="VALID" S CNT=CNT+1
 . NEW DA,IENS
 . S DA(1)=IDFN,DA=GRN,IENS=$$IENS^DILF(.DA)
 . S BQIUPD(90507.59,IENS,.02)=CNT
 I $D(BQIUPD) D FILE^DIE("","BQIUPD","ERROR")
 ;
 K @GLOBAL,BQWW,BQZZ,BGRP,BIDUZ2,BIZN,BST,CN,CNT,CVX,FDATE,GRN,GRP,IDATE,IENS,N,NAM,ORD,P,Y
 Q
 ;
STOR ;
 NEW DIC,DLAYGO,DA
 I $G(^BQIPAT(IDFN,0))="" D NPT^BQITASK(IDFN)
 S DA(1)=IDFN
 S BGRP=$O(^BQIPAT(IDFN,80,"B",GRP,""))
 I BGRP="" D
 . S DIC(0)="L",DLAYGO=90507.59,X=GRP,DIC="^BQIPAT("_DA(1)_",80,"
 . K DO,DD D FILE^DICN S BGRP=+Y
 . ;I BGRP=-1 B
 S DA(2)=IDFN,DA(1)=BGRP
 S BIZN=$O(^BQIPAT(IDFN,80,BGRP,1,"B",FDATE,""))
 I BIZN="" D
 . NEW DIC,DLAYGO
 . S DIC(0)="L",DLAYGO=90507.591,X=FDATE,DIC="^BQIPAT("_DA(2)_",80,"_DA(1)_",1,"
 . K DO,DD D FILE^DICN S BIZN=+Y
 . ;I BIZN=-1 B
 . S DA=BIZN,IENS=$$IENS^DILF(.DA)
 . S BQIUPD(90507.591,IENS,.02)=IZ,BQIUPD(90507.591,IENS,.04)=STAT
 . S BQIUPD(90507.591,IENS,.03)=$$NOW^XLFDT()
 . I BQWW(CVX,IDATE,STAT)'="" S BQIUPD(90507.591,IENS,.04)=BQWW(CVX,IDATE,STAT)
 . D FILE^DIE("","BQIUPD","ERROR")
 Q
