BQIIPCYC ;GDIT/HCSD/ALA-Cycle Time Measure ; 22 Mar 2019  9:08 AM
 ;;2.9;ICARE MANAGEMENT SYSTEM;**5**;Mar 01, 2021;Build 20
 ;;
 ;
EN(BQDATE,BQFROM,BQTHRU) ;EP
 I $G(WEEK)=1 K ^XTMP("BQIPCYC","W")
 I $G(WEEK)="" K ^XTMP("BQIPCYC","M")
 S ^XTMP("BQIPCYC",0)=$$DATE^BQIUL1("T+1M")_"^"_DT_"^Cycle Type Measure"
 NEW BQMON,BQDTE,BEGDT,EDAY,ENDT,PYR,CYR,ID,FAC,BQITOTP,BQITOTR,DFN,BD,ED
 NEW BQGOTA,F,QFL,X,Y,CRST
 S QFL=0
 S CRST=$P($G(^BQI(90508,1,11)),U,2) S:CRST="" CRST=1
 S CRST="0"_CRST
 ;
 I $G(BQDATE)'="",$G(WEEK)="" D
 . S BGDT=$E(BQDATE,1,5)_"01",CYR=$E(BQDATE,1,3),BQMON=$E(BQDATE,4,5)
 . I $L(BQMON)=1 S BQMON="0"_BQMON
 . S EDAY="31^"_($$LEAP^XLFDT2(CYR)+28)_"^31^30^31^30^31^31^30^31^30^31"
 . S ENDT=$E(BQDATE,1,5)_$P(EDAY,U,+BQMON)
 ;
 I $G(BQDATE)="",$G(WEEK)="" D  Q:QFL
 . I $E(DT,6,7)'=CRST S QFL=1 Q
 . S BQMON=$E(DT,4,5)-1,CYR=$E(DT,1,3),PYR=CYR-1
 . S BQDTE=$P($T(BQM+BQMON),";;",2)
 . I $L(BQMON)=1 S BQMON="0"_BQMON
 . S BGDT=@($P(BQDTE,U,2))_$P(BQDTE,U,1)_"01"
 . S EDAY="31^"_($$LEAP^XLFDT2(CYR)+28)_"^31^30^31^30^31^31^30^31^30^31"
 . S ENDT=@($P(BQDTE,U,2))_$P(BQDTE,U,1)_$P(EDAY,U,+$P(BQDTE,U,1))
 . S BQDATE=$S(BQMON="01":PYR,1:CYR)_BQMON_"00"
 ;
 I $G(WEEK)=1 D
 . S BGDT=BQFROM-.9999,ENDT=BQTHRU
 ;
 S CLN=0
 F  S CLN=$O(^SC(CLN)) Q:'CLN  D
 . S STCD=$P(^SC(CLN,0),"^",7) I STCD="" Q
 . I $P(^SC(CLN,0),"^",3)'="C" Q
 . ; Inactivated clinic that is not reactivated
 . I $P($G(^SC(CLN,"I")),"^",1)'="",$P($G(^SC(CLN,"I")),"^",2)="" Q
 . S STCN=$P(^SC(CLN,0),"^",7) I STCN="" Q
 . I '$D(^BQI(90508,1,23,"B",STCN)) Q
 . S STRT=BGDT,TOT=0,CIN=0,COU=0,SEC=0,NS=0,CAN=0
 . F  S STRT=$O(^SC(CLN,"S",STRT)) Q:STRT=""!(STRT\1>ENDT)  D
 .. I $O(^SC(CLN,"S",STRT,1,0))="" D CA Q
 .. S PN=0 F  S PN=$O(^SC(CLN,"S",STRT,1,PN)) Q:'PN  D
 ... S DFN=$P(^SC(CLN,"S",STRT,1,PN,0),"^",1) I DFN="" Q
 ... S TOT=TOT+1
 ... S CKIN=$P($G(^SC(CLN,"S",STRT,1,PN,"C")),"^",1),CKOUT=$P($G(^SC(CLN,"S",STRT,1,PN,"C")),"^",3)
 ... I CKIN="",CKOUT="" D NS Q
 ... I CKIN'="" S CIN=CIN+1
 ... I CKOUT'="" S COU=COU+1
 ... I CKOUT=""!(CKIN="") Q
 ... S DIFF=$$FMDIFF^XLFDT(CKOUT,CKIN,2)
 ... S RVDT="" F  S RVDT=$O(^AUPNVSIT("AA",DFN,RVDT)) Q:RVDT=""!(RVDT<(9999999-ENDT))  D
 .... S VIEN="" F  S VIEN=$O(^AUPNVSIT("AA",DFN,RVDT,VIEN)) Q:VIEN=""  I $P(^AUPNVSIT(VIEN,0),"^",26)=STRT S VISIT=VIEN
 ... S BQIZZ(CLN)=$G(BQIZZ(CLN))+DIFF
 ... I $G(VISIT)'="" D
 .... S PR="",PR=$O(^AUPNVPRV("AD",VISIT,PR)) I PR'="" D
 ..... S PROV=$P(^AUPNVPRV(PR,0),"^",1),$P(BQIPRV(PROV),"^",1)=$P($G(BQIPRV(PROV)),"^",1)+DIFF
 ..... S $P(BQIPRV(PROV),"^",2)=$P($G(BQIPRV(PROV)),"^",2)+1
 . I $G(WEEK)=1 S ^XTMP("BQIPCYC","W",CLN)=$G(BQIZZ(CLN))_"^"_TOT_"^"_CIN_"^"_COU_"^"_NS_"^"_CAN M ^XTMP("BQIPCYC","W",CLN)=BQIPRV
 . I $G(WEEK)="" S ^XTMP("BQIPCYC","M",CLN)=$G(BQIZZ(CLN))_"^"_TOT_"^"_CIN_"^"_COU_"^"_NS_"^"_CAN M ^XTMP("BQIPCYC","M",CLN)=BQIPRV
 . K BQIZZ,BQIPRV
 ;
 S PRV="" F  S PRV=$O(^AUPNPAT("AK",PRV)) Q:PRV=""  D
 . I $P(^VA(200,PRV,0),U,13)="" S BQIPRV(PRV)="0^0"
 ;
 S FAC=$$HME^BQIGPUTL()
 ;
 I $G(WEEK)=1 D
 . S CLN="",ID="IPC_CYC",TTOT=0,TNAP=0
 . F  S CLN=$O(^XTMP("BQIPCYC","W",CLN)) Q:CLN=""  D
 .. D STORCW^BQIIPUT1(CLN,ID,BQFROM,BQTHRU)
 .. S PRV="" F  S PRV=$O(^XTMP("BQIPCYC","W",CLN,PRV)) Q:PRV=""  D
 ... F I=1,2 S $P(BQIPRV(PRV),"^",I)=$P($G(BQIPRV(PRV)),"^",I)+$P(^XTMP("BQIPCYC","W",CLN,PRV),"^",I)
 . S PRV="" F  S PRV=$O(BQIPRV(PRV)) Q:PRV=""  D
 .. S TOT=$P(BQIPRV(PRV),"^",1)/60,NAP=$P(BQIPRV(PRV),"^",2)
 .. S TTOT=TTOT+TOT,TNAP=TNAP+NAP
 .. D STORPW^BQIIPUTL(PRV,ID,BQFROM,BQTHRU,"","",TOT,NAP)
 . D STORFW^BQIIPUTL(FAC,ID,BQFROM,BQTHRU,"","",TTOT,TNAP)
 ;
 I $G(WEEK)="" D
 . S CLN="",ID="IPC_CYC",TTOT=0,TNAP=0
 . F  S CLN=$O(^XTMP("BQIPCYC","M",CLN)) Q:CLN=""  D
 .. D STORCM^BQIIPUT1(CLN,ID,BQDATE)
 .. S PRV="" F  S PRV=$O(^XTMP("BQIPCYC","M",CLN,PRV)) Q:PRV=""  D
 ... F I=1,2 S $P(BQIPRV(PRV),"^",I)=$P($G(BQIPRV(PRV)),"^",I)+$P(^XTMP("BQIPCYC","M",CLN,PRV),"^",I)
 . S PRV="" F  S PRV=$O(BQIPRV(PRV)) Q:PRV=""  D
 .. S TOT=$P(BQIPRV(PRV),"^",1)/60,NAP=$P(BQIPRV(PRV),"^",2)
 .. S TTOT=TTOT+TOT,TNAP=TNAP+NAP
 .. D STORP^BQIIPUTL(PRV,ID,BQDATE,"","",TOT,NAP)
 . D STORF^BQIIPUTL(FAC,ID,BQDATE,"","",TTOT,TNAP)
 K BQIPRV
 Q
 ;
RPT ; Report
 S CLN=0
 F  S CLN=$O(^XTMP("BQIPCYC",CLN)) Q:'CLN  D
 . S CNAM=$P(^SC(CLN,0),"^",1),SECON=$P(^XTMP("BQIPCYC",CLN),"^",1)
 . W !,CNAM,"|",$P(^XTMP("BQIPCYC",CLN),"^",2),"|",$P(^XTMP("BQIPCYC",CLN),"^",3),"|",$P(^XTMP("BQIPCYC",CLN),"^",4),"|",SECON/60
 Q
 ;
NS ;EP
 S STAT=$P($G(^DPT(DFN,"S",STRT,0)),"^",2) I STAT="" Q
 I STAT="N" S NS=NS+1 Q
 Q
 ;
CA ;EP
 S DFN=$O(^DPT("ASDCN",CLN,STRT,"")) I DFN="" Q
 S CAN=CAN+1
 Q
 ;
BQM ;
 ;;12^PYR
 ;;01^CYR
 ;;02^CYR
 ;;03^CYR
 ;;04^CYR
 ;;05^CYR
 ;;06^CYR
 ;;07^CYR
 ;;08^CYR
 ;;09^CYR
 ;;10^CYR
 ;;11^CYR
