BQIJA ;GDIT/HCSD/ALA-CREATED BY ^ATXSTX ON JAN 20, 2022;
 ;;2.9;ICARE MANAGEMENT SYSTEM;**3**;Mar 01, 2021;Build 32
 ;
 ; See referenced routines to see taxonomies being loaded.
 ;
START ;
 D ^BQIJAA ;    BQI ACANTHAMOEBA CULTURE LNC
 D ^BQIJAB ;    BQI ACANTHAMOEBA NUCLEIC LNC
 D ^BQIJAC ;    BQI ANAPLASMOSIS ANTIBODY LNC
 D ^BQIJAD ;    BQI ANAPLASMOSIS ANTIGEN LOINC
 D ^BQIJAE ;    BQI ANAPLASMOSIS CULTURE LNC
 D ^BQIJAF ;    BQI ANAPLASMOSIS MICROSCO LNC
 D ^BQIJAG ;    BQI ANAPLASMOSIS NUCLEIC LOINC
 D ^BQIJAH ;    BQI ANTHRAX ANTIBODY LOINC
 D ^BQIJAI ;    BQI ANTHRAX ANTIGEN LOINC
 D ^BQIJAJ ;    BQI ANTHRAX DNA LOINC
 D ^BQIJAK ;    BQI ANTHRAX OTHER LOINC
 D ^BQIJAL ;    BQI ARBORVIRAL ANTIBODY LOINC
 D ^BQIJAM ;    BQI ARBORVIRAL ANTIGEN LOINC
 D ^BQIJAN ;    BQI ARBORVIRAL CULT ID LOINC
 D ^BQIJAO ;    BQI ARBORVIRAL NUCLEIC LOINC
 D ^BQIJAP ;    BQI BABESIOSIS ANTIBODY LOINC
 D ^BQIJAQ ;    BQI BABESIOSIS MICROSCOPIC LNC
 D ^BQIJAR ;    BQI BABESIOSIS NUCLEIC LOINC
 D ^BQIJAS ;    BQI BLASTOMYCES ANTIBODY LOINC
 D ^BQIJAT ;    BQI BLASTOMYCES ANTIGEN LOINC
 D ^BQIJAU ;    BQI BLASTOMYCES CULT ID LOINC
 D ^BQIJAV ;    BQI BLASTOMYCES NUCLEIC LOINC
 D ^BQIJAW ;    BQI BLOOD LEAD CAPILLARY LNC
 D ^BQIJAX ;    BQI BLOOD LEAD LOINC
 D ^BQIJAY ;    BQI BLOOD LEAD UNSPEC LNC
 D ^BQIJAZ ;    BQI BLOOD LEAD VENOUS LOINC
 Q
