BQIJI ;GDIT/HCSD/ALA-CREATED BY ^ATXSTX ON JAN 20, 2022;
 ;;2.9;ICARE MANAGEMENT SYSTEM;**3**;Mar 01, 2021;Build 32
 ;
 ; See referenced routines to see taxonomies being loaded.
 ;
START ;
 D ^BQIJIA ;    BQI SALMONELLA NUCLEIC LOINC
 D ^BQIJIB ;    BQI SARS ANTIBODY LOINC
 D ^BQIJIC ;    BQI SARS CULTURE ID LOINC
 D ^BQIJID ;    BQI SARS NUCLEIC ACID LOINC
 D ^BQIJIE ;    BQI SARS UNSPECIFIED LOINC
 D ^BQIJIF ;    BQI SHIGA E COLI ANTIBODY LNC
 D ^BQIJIG ;    BQI SHIGA E COLI ANTIGEN LNC
 D ^BQIJIH ;    BQI SHIGA E COLI CULTURE LOINC
 D ^BQIJII ;    BQI SHIGA E COLI NUCLEIC LNC
 D ^BQIJIJ ;    BQI SHIGA E COLI UNSPEC LOINC
 D ^BQIJIK ;    BQI SHIGELLA CULTURE LOINC
 D ^BQIJIL ;    BQI SHIGELLA E COLI NUC LNC
 D ^BQIJIM ;    BQI SHIGELLA NUCLEIC LOINC
 D ^BQIJIN ;    BQI SMALLPOX NUCLEIC ACID LNC
 D ^BQIJIO ;    BQI ST LOUIS ENCEPH ANTIBODY
 D ^BQIJIP ;    BQI ST LOUIS ENCEPH ANTIGEN
 D ^BQIJIQ ;    BQI ST LOUIS ENCEPH NUCLEIC
 D ^BQIJIR ;    BQI STREP PNEUMO INV ANTIGEN
 D ^BQIJIS ;    BQI STREP PNEUMO INV CULTURE
 D ^BQIJIT ;    BQI TICKBORNE RELAPSE ANTIBODY
 D ^BQIJIU ;    BQI TICKBORNE RELAPSE CULT LNC
 D ^BQIJIV ;    BQI TICKBORNE RELAPSE NUCL LNC
 D ^BQIJIW ;    BQI TRICHINOSIS ANTIBODY LOINC
 D ^BQIJIX ;    BQI TRICHINOSIS DNA LOINC
 D ^BQIJIY ;    BQI TRICHINOSIS OTHER LOINC
 D ^BQIJIZ ;    BQI TUBERCULOSIS ASSAYS LOINC
 Q
