BQIJJ ;GDIT/HCSD/ALA-CREATED BY ^ATXSTX ON JAN 20, 2022;
 ;;2.9;ICARE MANAGEMENT SYSTEM;**3**;Mar 01, 2021;Build 32
 ;
 ; See referenced routines to see taxonomies being loaded.
 ;
START ;
 D ^BQIJJA ;    BQI TUBERCULOSIS CULTURE LOINC
 D ^BQIJJB ;    BQI TUBERCULOSIS NUCLEIC LOINC
 D ^BQIJJC ;    BQI TUBERCULOSIS SKIN TST LNC
 D ^BQIJJD ;    BQI TULAREMIA ANTIBODY LOINC
 D ^BQIJJE ;    BQI TULAREMIA ANTIGEN LOINC
 D ^BQIJJF ;    BQI TULAREMIA CELL WALL LOINC
 D ^BQIJJG ;    BQI TULAREMIA CULTURE ID LOINC
 D ^BQIJJH ;    BQI TULAREMIA NUCLEIC ACID LNC
 D ^BQIJJI ;    BQI TULAREMIA PANEL ANTIBODY
 D ^BQIJJJ ;    BQI TYPHOID ANTIBODY LOINC
 D ^BQIJJK ;    BQI TYPHOID CULTURE ID LOINC
 D ^BQIJJL ;    BQI TYPHOID NUCLEIC ACID LNC
 D ^BQIJJM ;    BQI VALLEY FEVER ANTIBODY LNC
 D ^BQIJJN ;    BQI VALLEY FEVER ANTIGEN LOINC
 D ^BQIJJO ;    BQI VALLEY FEVER CULTURE LOINC
 D ^BQIJJP ;    BQI VALLEY FEVER NUCLEIC LOINC
 D ^BQIJJQ ;    BQI VARICELLA ANTIBODY LOINC
 D ^BQIJJR ;    BQI VARICELLA ANTIGEN LOINC
 D ^BQIJJS ;    BQI VARICELLA CULTURE ID LNC
 D ^BQIJJT ;    BQI VARICELLA NUCLEIC LOINC
 D ^BQIJJU ;    BQI VIBRIOSIS DNA LOINC
 D ^BQIJJV ;    BQI VIBRIOSIS OTHER LOINC
 D ^BQIJJW ;    BQI VISA VRSA CULTURE ID LNC
 D ^BQIJJX ;    BQI VISA VRSA RESIST GENE LNC
 D ^BQIJJY ;    BQI VISA VRSA SUSCEPTIBILITY
 D ^BQIJJZ ;    BQI WEST EQUINE ANTIBODY LOINC
 Q
