BQIJH ;GDIT/HCSD/ALA-CREATED BY ^ATXSTX ON JAN 20, 2022;
 ;;2.9;ICARE MANAGEMENT SYSTEM;**3**;Mar 01, 2021;Build 32
 ;
 ; See referenced routines to see taxonomies being loaded.
 ;
START ;
 D ^BQIJHA ;    BQI PSITTACOSIS ANTIBODY LNC
 D ^BQIJHB ;    BQI PSITTACOSIS CULTURE ID LNC
 D ^BQIJHC ;    BQI PSITTACOSIS NUCLEIC LOINC
 D ^BQIJHD ;    BQI Q FEVER ANTIBODY LOINC
 D ^BQIJHE ;    BQI Q FEVER ANTIGEN LOINC
 D ^BQIJHF ;    BQI Q FEVER CULTURE ID LOINC
 D ^BQIJHG ;    BQI Q FEVER NUCLEIC LOINC
 D ^BQIJHH ;    BQI RABIES ANTIBODY LOINC
 D ^BQIJHI ;    BQI RABIES ANTIGEN LOINC
 D ^BQIJHJ ;    BQI RABIES CULTURE ID LOINC
 D ^BQIJHK ;    BQI RABIES NUCLEIC ACID LOINC
 D ^BQIJHL ;    BQI RICIN ANTIBODY LOINC
 D ^BQIJHM ;    BQI RICIN LOINC
 D ^BQIJHN ;    BQI ROCKY MTN FVR ANTIBODY
 D ^BQIJHO ;    BQI ROCKY MTN FVR ANTIGEN LNC
 D ^BQIJHP ;    BQI ROCKY MTN FVR CULTURE ID
 D ^BQIJHQ ;    BQI ROCKY MTN FVR NUCLEIC LNC
 D ^BQIJHR ;    BQI RSV ANTIGEN LOINC
 D ^BQIJHS ;    BQI RSV CULTURE ID LOINC
 D ^BQIJHT ;    BQI RSV NUCLEIC ACID LOINC
 D ^BQIJHU ;    BQI RUBELLA ANTIBODY LOINC
 D ^BQIJHV ;    BQI RUBELLA CULTURE ID LNC
 D ^BQIJHW ;    BQI RUBELLA NUCLEIC LOINC
 D ^BQIJHX ;    BQI RUBELLA PANEL ANTIBODY
 D ^BQIJHY ;    BQI RUBELLA PANEL NUCLEIC LNC
 D ^BQIJHZ ;    BQI SALMONELLA CULTURE ID LNC
 Q
