BQIOTX ;GDIT/HS/ALA-CREATED BY ^ATXSTX ON MAY 06, 2024;
 ;;2.9;ICARE MANAGEMENT SYSTEM;**7**;Mar 01, 2021;Build 14
 ;
 ; See referenced routines to see taxonomies being loaded.
 ;
START ;
 D ^BQIOTXA ;   BQI NOROVIRUS ANTIGEN STOOL
 D ^BQIOTXB ;   BQI ENTAMOEBA HIST ANTIGEN LNC
 D ^BQIOTXC ;   BQI ENTAMOEBA HIST ANTIGEN EIA
 D ^BQIOTXD ;   BQI ENTAMOEBA HIST ANTIBDY LNC
 D ^BQIOTXE ;   BQI ENTAMOEBA HIST ANTIBDY EIA
 D ^BQIOTXF ;   BQI ENTAMOEBA HIST NUCLEIC LNC
 D ^BQIOTXG ;   BQI C DIFF CULTURE ID LNC
 D ^BQIOTXH ;   BQI C DIFF CULTURE STOOL LNC
 D ^BQIOTXI ;   BQI C DIFF TOXIN BY EIA
 D ^BQIOTXJ ;   BQI C DIFF TOXIN STOOL EIA
 D ^BQIOTXK ;   BQI C DIFF TOXIN STOOL CELL
 D ^BQIOTXL ;   BQI C DIFF TOXIN NUCLEIC STOOL
 D ^BQIOTXM ;   BQI C DIFF TOXIN NUCLEIC ACID
 D ^BQIOTXN ;   BQI C DIFF ANTIGEN STOOL
 D ^BQIOTXO ;   BQI ARSENIC QUANT UNSPEC
 D ^BQIOTXP ;   BQI ARSENIC QUANT URINE
 D ^BQIOTXQ ;   BQI ARSENIC QUANT BLOOD
 D ^BQIOTXR ;   BQI CRYPTOCOCCUS SPEC CULT ID
 D ^BQIOTXS ;   BQI CRYPTOCOCCUS NEO CULT ID
 D ^BQIOTXT ;   BQI CRYPTOCOCCUS GAT CULT ID
 D ^BQIOTXU ;   BQI CRYPTOCOCCUS NUCLEIC
 D ^BQIOTXV ;   BQI CRYPTOCOCCUS ANTIGEN
 D ^BQIOTXW ;   BQI MERCURY QUANT BLOOD LOINC
 D ^BQIOTXX ;   BQI MERCURY QUANT URINE LOINC
 D ^BQIOTXY ;   BQI MERCURY QUANT UNSPEC LNC
 D ^BQIOTXZ ;   BQI NAEGLERIA PAM ANTIGEN LNC
 Q
