BQIQTX ;GDIT/HS/ALA-CREATED BY ^ATXSTX ON MAY 09, 2024;
 ;;2.9;ICARE MANAGEMENT SYSTEM;**7**;Mar 01, 2021;Build 14
 ;
 ; See referenced routines to see taxonomies being loaded.
 ;
START ;
 D ^BQIQTXA ;   BQI OVERDOSE NON OPIOID BLOOD
 D ^BQIQTXB ;   BQI OVERDOSE NON OPIOID URINE
 D ^BQIQTXC ;   BQI STREPTOCOCCUS GRP A CULT
 D ^BQIQTXD ;   BQI STREPTOCOCCUS GRP B CULT
 D ^BQIQTXE ;   BQI CADMIUM QUANT BLOOD
 D ^BQIQTXF ;   BQI CADMIUM QUANT URINE
 D ^BQIQTXG ;   BQI CADMIUM QUANT UNSPEC
 D ^BQIQTXH ;   BQI RICKETTSIA TYPHUS GRP NUCL
 D ^BQIQTXI ;   BQI RICKETTSIA TYPHUS GRP IGG
 D ^BQIQTXJ ;   BQI RICKETTSIA TYPHUS GRP IGM
 D ^BQIQTXK ;   BQI RICKETT TYPH GRP IGG QUAN
 D ^BQIQTXL ;   BQI RICKETT TYPH GRP IGM QUAN
 D ^BQIQTXM ;   BQI GLANDERS ANTIBODY
 D ^BQIQTXN ;   BQI GLANDERS CULTURE ID
 D ^BQIQTXO ;   BQI GLANDERS NUCLEIC ACID
 D ^BQIQTXP ;   BQI GLANDERS ANTIGEN
 D ^BQIQTXQ ;   BQI CHAGAS NUCLEIC ACID
 D ^BQIQTXR ;   BQI CHAGAS ANTIBODY
 D ^BQIQTXS ;   BQI CHAGAS IGG ANTIBODY
 D ^BQIQTXT ;   BQI CHAGAS IGM ANTIBODY
 D ^BQIQTXU ;   BQI ROTAVIRUS NUCLEIC LOINC
 D ^BQIQTXV ;   BQI ROTAVIRUS ANTIGEN LOINC
 D ^BQIQTXW ;   BQI FOOD POISON SEB LOINC
 D ^BQIQTXX ;   BQI FOOD POISON SEB NUCLEIC
 D ^BQIQTXY ;   BQI LOUSEBORNE LOINC
 D ^BQIQTXZ ;   BQI LOUSEBORNED BLOOD LNC
 Q
