BQIRGPG ;GDIT/HS/ALA-Pregnancy Care Mgmt ; 17 Jul 2013  7:49 AM
 ;;2.9;ICARE MANAGEMENT SYSTEM;**5,7**;Mar 01, 2021;Build 14
 ;
CURR(DFN) ;EP - Currently marked as pregnant
 NEW RESULT
 S RESULT="NO"
 I $$GET1^DIQ(9000017,DFN_",",1101,"E")'="" S RESULT=$$GET1^DIQ(9000017,DFN_",",1101,"E")
 Q RESULT
 ;
EDD(DFN) ;EP - Definitive Date of Delivery
 NEW RES,ARRAY,PI,PDATA,EDD
 S RES="",PDATA=$G(^AUPNREP(DFN,13))
 S PI=11
 I $P(PDATA,U,PI)'="" S EDD=$P(PDATA,U,PI)
 I $G(EDD)'="" S RES=$$FMTE^BQIUL1(EDD)
 Q RES
 ;
LMP(DFN) ;EP - Last Menstual Period
 NEW RES
 S RES=+$$GET1^DIQ(9000017,DFN_",",2,"I")
 I RES'="" S RES=$$FMTE^BQIUL1(RES)
 Q RES
 ;
EEDD(DFN) ; EP - Estimated Date of Delivery
 NEW RES,ARRAY,PI,PDATA,EDD
 S RES="",PDATA=$G(^AUPNREP(DFN,13))
 F PI=2,5,8,14 D
 . I $P(PDATA,U,PI)'="" S ARRAY($P(PDATA,U,PI))=PI
 S EDD=$O(ARRAY(""),-1) I EDD'="" S RES=$$FMTE^BQIUL1(EDD)
 Q RES
 ;
HGH(DFN) ;EP - High Risk Prenatal Problems
 NEW BQJN,OK
 S OK="NO",BQJN=""
 F  S BQJN=$O(^BJPNPL("D",DFN,BQJN)) Q:BQJN=""  D
 . I $P(^BJPNPL(BQJN,0),U,6)="H" S OK="YES"
 Q OK
 ;
EGA(DFN) ;EP - Estimated gestational age
 NEW VALL,RES,DATE
 S RES=""
 S VALL=$$MEAS^BQITUTL(DFN,"EGA")
 I VALL=0 Q RES
 S RES=$P(VALL,U,3)_" ("_$$FMTE^BQIUL1($P(VALL,U,2))_")"
 Q RES
 ;
GRAV(DFN) ;EP - Gravida Total # of pregnancies
 NEW RES
 S RES=+$$GET1^DIQ(9000017,DFN_",",1103,"E")
 Q RES
 ;
MUL(DFN) ;EP - Multiple births
 NEW RES
 S RES=+$$GET1^DIQ(9000017,DFN_",",1105,"E")
 Q RES
 ;
FULL(DFN) ;EP - Full Term births
 NEW RES
 S RES=+$$GET1^DIQ(9000017,DFN_",",1107,"E")
 Q RES
 ;
PREM(DFN) ;EP - Premature births
 NEW RES
 S RES=+$$GET1^DIQ(9000017,DFN_",",1109,"E")
 Q RES
 ;
ECT(DFN) ;EP - Ectopic pregancies
 NEW RES
 S RES=+$$GET1^DIQ(9000017,DFN_",",1111,"E")
 Q RES
 ;
LIV(DFN) ;EP - Living children
 NEW RES
 S RES=+$$GET1^DIQ(9000017,DFN_",",1113,"E")
 Q RES
 ;
MIS(DFN) ;EP - Miscarriages
 NEW RES
 S RES=+$$GET1^DIQ(9000017,DFN_",",1133,"E")
 Q RES
 ;
ABOR(DFN) ;EP - Abortions
 NEW RES
 S RES=+$$GET1^DIQ(9000017,DFN_",",1131,"E")
 Q RES
 ;
LAB ;EP - Pull out prenatal lab tests
 NEW LRES,RES
 S LRES=$$ITM^BQICMUTL("",BQDFN,FREF,RREF,ITM,TAX,.TREF)
 I $P(LRES,U,1)=0 S RESULT=0 Q
 S RES=$P(LRES,U,7) I RES="" S RES=$P(LRES,U,6)
 S RESULT=1_U_$P(LRES,U,2)_U_RES
 Q
 ;
LBT ;EP - Set up lab tests
 NEW TAX,TREF
 S TAX="BQI PRENATAL TAX"
 S TREF=$NA(^TMP("BQIPRENTL",$J)) K @TREF
 D BLD^BQITUTL(TAX,.TREF,"L")
 ; Clean up labs
 NEW DA,IENS,CIEN
 S CIEN=$O(^BQI(90506.5,"B","Prenatal","")) I CIEN="" Q
 S DA=0,DA(1)=CIEN
 F  S DA=$O(^BQI(90506.5,CIEN,10,DA)) Q:'DA  D
 . S IENS=$$IENS^DILF(.DA)
 . S BQIUPD(90506.51,IENS,.09)=1
 I $D(BQIUPD) D FILE^DIE("","BQIUPD","ERROR")
 ;
 ; Set up lab tests
 NEW BN,CT,CD,DA,IENS,DIC,DESC,PNL,DLAYGO,DIC,X,Y,NM,NAME
 S BN=0
 F  S BN=$O(@TREF@(BN)) Q:'BN  D
 . S NM=$P(^LAB(60,BN,.1),U,1),NAME=$P(^LAB(60,BN,0),"^",1)
 . S PNL=0 I $O(^LAB(60,BN,2,0))'="" S PNL=1
 . S IEN=$O(^BQI(90506.5,CIEN,10,"C",NM,""))
 . I IEN'="" D
 .. S DA(1)=CIEN,DA=IEN,IENS=$$IENS^DILF(.DA)
 .. S BQIUPD(90506.51,IENS,.09)="@"
 .. D FILE^DIE("","BQIUPD","ERROR")
 .. I PNL S DESC(1)="Most recent "_NAME_" panel from V Lab is displayed."
 .. I 'PNL S DESC(1)="Most recent "_NAME_" lab test from V Lab is displayed."
 .. D WP^DIE(90506.51,IENS,4,"","DESC")
 . I IEN="" D
 .. S CT=$P($G(^BQI(90506.5,CIEN,10,0)),U,3),CT=CT+1
 .. S CD="PG_"_$E("0000",$L(CT),2)_CT
 .. S DA(1)=CIEN,X=CD,DIC="^BQI(90506.5,"_DA(1)_",10,",DIC(0)="L",DLAYGO=90506.51
 .. K DO,DD D FILE^DICN S DA=+Y
 .. S IENS=$$IENS^DILF(.DA)
 .. S BQIUPD(90506.51,IENS,.02)=3,BQIUPD(90506.51,IENS,.03)=NM
 .. S BQIUPD(90506.51,IENS,.04)=BN,BQIUPD(90506.51,IENS,.05)="B"
 .. S BQIUPD(90506.51,IENS,.06)="D",BQIUPD(90506.51,IENS,.08)="A"
 .. S BQIUPD(90506.51,IENS,1)="D LAB^BQIRGPG"
 .. D FILE^DIE("","BQIUPD","ERROR")
 .. I PNL S DESC(1)="Most recent "_NAME_" panel from V Lab is displayed."
 .. I 'PNL S DESC(1)="Most recent "_NAME_" lab test from V Lab is displayed."
 .. D WP^DIE(90506.51,IENS,4,"","DESC")
 K @TREF
 Q
 ;
GLS(DATA,FAKE) ;EP - BQI GET PRENATAL GLOSSARY
 NEW UID,II,TRIEN,CAT,TIT,SORT,RMK,REMARK,CT,NXT,GLIEN,IEN
 ;
 S UID=$S($G(ZTSK):"Z"_ZTSK,1:$J)
 S DATA=$NA(^TMP("BQIRGPGLS",UID))
 K @DATA
 ;
 S II=0
 NEW $ESTACK,$ETRAP S $ETRAP="D ERR^BQIRGPG D UNWIND^%ZTER" ; SAC 2006 2.2.3.3.2
 ;
 S @DATA@(II)="T32767REPORT_TEXT"_$C(30)
 S GLIEN=$O(^BQI(90508.2,"B","Prenatal","")) I GLIEN="" S BMXSEC="Problem with Prenatal glossary in file 90508.2" G DONE
 S IEN=0 F  S IEN=$O(^BQI(90508.2,GLIEN,1,IEN)) Q:'IEN  D
 . S II=II+1,@DATA@(II)=$G(^BQI(90508.2,GLIEN,1,IEN,0))
 I II>0 S @DATA@(II)=@DATA@(II)_$C(30)
 ;
DONE S II=II+1,@DATA@(II)=$C(31)
 Q
 ;
ERR ;
 D ^%ZTER
 NEW Y,ERRDTM
 S Y=$$NOW^XLFDT() X ^DD("DD") S ERRDTM=Y
 S BMXSEC="Recording that an error occurred at "_ERRDTM
 I $D(II),$D(DATA) S II=II+1,@DATA@(II)=$C(31)
 Q
 ;
TRIM(DFN) ;EP - Current Trimester
 NEW EDD,RFROM,RTHRU
 S EDD=$P($G(^AUPNREP(DFN,13)),"^",11) I EDD="" Q ""
 D TRIM^BQIDCAH1(EDD,1)
 I DT'<RFROM,DT'>RTHRU Q "1"
 D TRIM^BQIDCAH1(EDD,2)
 I DT'<RFROM,DT'>RTHRU Q "2"
 D TRIM^BQIDCAH1(EDD,3)
 I DT'<RFROM,DT'>RTHRU Q "3"
 Q ""
 ;
TRIMD(DFN,TRIM) ;EP - Trimester dates
 NEW EDD,RFROM,RTHRU
 S EDD=$P($G(^AUPNREP(DFN,13)),"^",11) I EDD="" Q ""
 D TRIM^BQIDCAH1(EDD,TRIM)
 Q $$FMTE^BQIUL1(RFROM)_"-"_$$FMTE^BQIUL1(RTHRU)
 ;
RSV(DFN) ; EP - RSV Immunization Given
 NEW EDD,RFROM,RTHRU,TAX,TREF,RVF,RVT,IMN,DFLG,TXT,IMD
 S EDD=$P($G(^AUPNREP(DFN,13)),"^",11) I EDD="" Q ""
 S RFROM=$$FMADD^XLFDT(EDD,-56),RTHRU=$$FMADD^XLFDT(EDD,-28)
 S RVF=9999999-RTHRU,RVT=9999999-RFROM
 S TAX="BQI PREG IZ RSV CVX CODES",TREF="BQITAX" K @TREF
 D BLD^BQITUTL(TAX,.TREF)
 S DFLG=0,IMN="" F  S IMN=$O(@TREF@(IMN)) Q:IMN=""  D
 . S BG=RVF F  S BG=$O(^AUPNVIMM("AA",DFN,IMN,BG)) Q:BG=""  D
 .. S IMD=9999999-BG
 .. I IMD<RFROM!(IMD>RTHRU) Q
 .. S DFLG=1
 I 'DFLG S TXT="NO"
 I DFLG S TXT="YES"
 Q TXT
 ; 
BMI(DFN,TRIM) ;EP - BMI based on EDD
 ; If TRIM="I", BMI value from before 1st trimester
 NEW EDD,RFROM,THRU,VALUE
 S EDD=$P($G(^AUPNREP(DFN,13)),"^",11) I EDD="" Q ""
 I TRIM="I" D  Q VALUE
 . D TRIM^BQIDCAH1(EDD,1)
 . S VALUE=$$MEAS^BQIRGUT1(DFN,"BMI","",RFROM)
 ;
 D TRIM^BQIDCAH1(EDD,TRIM)
 S VALUE=$$MEAS^BQIRGUT1(DFN,"BMI",RFROM,RTHRU)
 Q VALUE
 ;
TRMT(DFN) ;EP - Treatment for Syphilis
 NEW REF,RSUB,BDN,RXD,TEDD,BEDD,RES,VIS,VSDTM,RDRUG
 S REF=$NA(^TMP("BQISYTR",$J)) K @REF
 F RSUB="RXNO BQI BICILLIN (PCN G BENZ)","RXNO BQI PCN G AQ CRYST INJ","RXNO BQI PCN G PROCAINE INJ" D RXNM^BQITUTL(RSUB,.REF)
 ;D RXNM^BQITUTL("RXNO BQI BICILLIN (PCN G BENZ)",.REF)
 I '$D(@REF) Q ""
 S RES=""
 S BDN="" F  S BDN=$O(^AUPNVMED("AC",DFN,BDN)) Q:BDN=""  D
 . S RXD=$P($G(^AUPNVMED(BDN,0)),"^",1) I RXD="" Q
 . I '$D(@REF@(RXD)) Q
 . S TEDD=$P($G(^AUPNREP(DFN,13)),"^",11) I TEDD="" Q
 . S BEDD=$$FMADD^XLFDT(TEDD,-280)
 . S VIS=$P(^AUPNVMED(BDN,0),"^",3) I VIS="" Q
 . S VSDTM=$P($G(^AUPNVSIT(VIS,0)),"^",1)\1 I VSDTM=0 Q
 . I VSDTM'<BEDD,VSDTM'>DT S RDRUG(VSDTM,BDN)=RXD
 S RES=$O(RDRUG(""),-1)
 Q $$FMTE^BQIUL1(RES)
 ;
RPR(DFN,TYP) ;EP - RPR by trimester
 ; TYP="I", Initial prenatal
 ; TYP="T", Third Trimester
 ; TYP="P", Postpartum
 S DEDD=$P($G(^AUPNREP(DFN,13)),"^",11) I DEDD="" Q ""
 ;
 I TYP="I" D  Q RESULT
 . ; If no prenatal note title, look at cpt code, then first trimester
 . NEW RVDT,RFROM,RTHRU,RF,RT,NTZ,PNTE,TIN,NFLG
 . D TRIM^BQIDCAH1(DEDD,"")
 . ; If prenatal note title, get date of first one in the DEDD timeframe
 . S PNTE="",NFLG=0 F  S PNTE=$O(^BQI(90508,1,26,"B",PNTE)) Q:PNTE=""  D
 .. S RF=9999999-RTHRU,RT=9999999-RFROM,RVDT=RF
 .. F  S RVDT=$O(^TIU(8925,"AA",DFN,PNTE,RVDT)) Q:RVDT=""!(RVDT>RT)  D
 ... S TIN="" F  S TIN=$O(^TIU(8925,"AA",DFN,PNTE,RVDT,TIN)) Q:TIN=""  S NTZ(RVDT)="",NFLG=1
 . I NFLG S RF=9999999-$O(NTZ("")),RFROM=$$FMADD^XLFDT(RF,-7),RTHRU=$$FMADD^XLFDT(RF,7)
 . I 'NFLG D CP("I") I CPRES S NFLG=1
 . D RLB(DFN,RFROM,RTHRU)
 . I $G(RESULT)="" D TRIM^BQIDCAH1(DEDD,1) D RLB(DFN,RFROM,RTHRU)
 ;
 I TYP="T" D  Q RESULT
 . ; Third trimester date range
 . NEW RFROM,RTHRU
 . D TRIM^BQIDCAH1(DEDD,3)
 . D RLB(DFN,RFROM,RTHRU)
 ;
 I TYP="P" D  Q RESULT
 . ; Postpartum from definitive EDD to 60 days after
 . NEW PRFROM,PRTHRU,CURR
 . S PRFROM=DEDD,PRTHRU=$$FMADD^XLFDT(PRFROM,60)
 . ; If today is past the 60 days postpartum, OR patient not marked as Pregnant anymore
 . I DT>PRTHRU S RESULT="" Q
 . S CURR=$$GET1^DIQ(9000017,DFN_",",1101,"I")
 . D RLB(DFN,PRFROM,PRTHRU)
 ;
 Q RESULT
 ;
RLB(DFN,FRFROM,FRTHRU) ;
 NEW TREF,TAX,TEMP,LIEN,RDAT
 S TREF="BQITAX" K @TREF
 S TEMP="BQITMP" K @TEMP
 S TAX="BQI SYPHILIS REAGIN LOINC" D BLD^BQITUTL(TAX,.TREF)
 S TAX="BQI SYPHILIS REAGIN TEST TAX" D BLD^BQITUTL(TAX,.TREF,"L")
 D LABS^BQIRGUT1(DFN,"",.TREF,FRFROM,FRTHRU,"RPR",.TEMP)
 S RESULT=""
 S RDAT=$O(@TEMP@(""),-1) I RDAT="" Q
 S LIEN=$O(@TEMP@(RDAT,"RPR",""))
 S RESULT=$$FMTMDY^BQIUL1(RDAT)_" ("_@TEMP@(RDAT,"RPR",LIEN)_")"
 Q
 ;
TLB(DFN,FRFROM,FRTHRU) ;
 NEW TREF,TAX,TEMP,LIEN,RDAT
 S TREF="BQITAX" K @TREF
 S TEMP="BQITMP" K @TEMP
 S TAX="BQI SYPHILIS TP-AB LOINC" D BLD^BQITUTL(TAX,.TREF)
 S TAX="BQI SYPHILIS TP-AB TEST TAX" D BLD^BQITUTL(TAX,.TREF,"L")
 D LABS^BQIRGUT1(DFN,"",TREF,FRFROM,FRTHRU,"TPA",TEMP)
 S RESULT=""
 S RDAT=$O(@TEMP@(""),-1) I RDAT="" Q
 S LIEN=$O(@TEMP@(RDAT,"TPA",""))
 S RESULT=$$FMTMDY^BQIUL1(RDAT)_" ("_@TEMP@(RDAT,"TPA",LIEN)_")"
 Q
 ;
TPA(DFN,TYP) ;EP - TPA by trimester
 ; TYP="I", Initial prenatal
 ; TYP="T", Third Trimester
 ; TYP="P", Postpartum
 S DEDD=$P($G(^AUPNREP(DFN,13)),"^",11) I DEDD="" Q ""
 ;
 I TYP="I" D  Q RESULT
 . ; If no prenatal note title, look at cpt code, then first trimester
 . NEW RVDT,RFROM,RTHRU,RF,RT,NTZ,PNTE,TIN,NFLG
 . D TRIM^BQIDCAH1(DEDD,"")
 . ; If prenatal note title, get date of first one in the DEDD timeframe
 . S PNTE="",NFLG=0 F  S PNTE=$O(^BQI(90508,1,26,"B",PNTE)) Q:PNTE=""  D
 .. S RF=9999999-RTHRU,RT=9999999-RFROM,RVDT=RF
 .. F  S RVDT=$O(^TIU(8925,"AA",DFN,PNTE,RVDT)) Q:RVDT=""!(RVDT>RT)  D
 ... S TIN="" F  S TIN=$O(^TIU(8925,"AA",DFN,PNTE,RVDT,TIN)) Q:TIN=""  S NTZ(RVDT)="",NFLG=1
 . I NFLG S RF=9999999-$O(NTZ("")),RFROM=$$FMADD^XLFDT(RF,-7),RTHRU=$$FMADD^XLFDT(RF,7)
 . I 'NFLG D CP("I") I CPRES S NFLG=1
 . D TLB(DFN,RFROM,RTHRU)
 . I $G(RESULT)="" D TRIM^BQIDCAH1(DEDD,1) D TLB(DFN,RFROM,RTHRU)
 ;
 I TYP="T" D  Q RESULT
 . ; Third trimester date range
 . NEW RFROM,RTHRU
 . D TRIM^BQIDCAH1(DEDD,3)
 . D TLB(DFN,RFROM,RTHRU)
 ;
 I TYP="P" D  Q RESULT
 . ; Postpartum from definitive EDD to 60 days after
 . NEW PRFROM,PRTHRU,CURR
 . S PRFROM=DEDD,PRTHRU=$$FMADD^XLFDT(PRFROM,60)
 . ; If today is past the 60 days postpartum, OR patient not marked as Pregnant anymore
 . I DT>PRTHRU S RESULT="" Q
 . S CURR=$$GET1^DIQ(9000017,DFN_",",1101,"I")
 . D TLB(DFN,PRFROM,PRTHRU)
 ;
 Q RESULT
 ;
CP(TY) ;
 NEW BQCD,CN,COD
 K BQCD
 I TY="I" D
 . F COD="0500F ","0501F" S CN=$O(^ICPT("BA",COD,"")) I CN'="" S BQCD(CN)=""
 I TY="P" D
 . S CN=$O(^ICPT("BA","0503F ","")) I CN'="" S BQCD(CN)=""
 S FREF=9000010.18
 S CPRES=$$ITM^BQICAUT2(RFROM,RTHRU,$G(TAX),DFN,FREF,.BQCD)
 Q
 ;
NOT(DFN) ;EP - Prenatal Note Title
 NEW RVDT,RFROM,RTHRU,RF,RT,DATE,PNTE,NTC,NTZ
 S RESULT="",RVDT=""
 S PNTE="",NTC=0 F  S PNTE=$O(^BQI(90508,1,26,"B",PNTE)) Q:PNTE=""  D
 . F  S RVDT=$O(^TIU(8925,"AA",DFN,PNTE,RVDT)) Q:RVDT=""  D
 .. S RF=9999999-RVDT
 .. S NTZ(RF)=""
 S RVDT=$O(NTZ(""),-1)
 S RESULT=$$FMTMDY^BQIUL1(RVDT)
 Q RESULT
