BQIRMIZ ;GDIT/HCSD/ALA-Update IZ Forecaster ; 02 Sep 2015  12:28 PM
 ;;2.9;ICARE MANAGEMENT SYSTEM;**1,3**;Mar 01, 2021;Build 32
 ;
 ;
EN(DFN) ;EP
 NEW VALUE,FRN,IMN,BSR,LIDT,TEXT
 S $P(^BIPDUE(0),U,3)=0
 S BIDFN=DFN,BIFDT=DT,BIDUZ2=$P(^BQI(90508,1,0),"^",1)
 D FOR(DFN)
 S FRN=""
 F  S FRN=$O(^BIPDUE("B",DFN,FRN)) Q:FRN=""  D
 . I $G(^BIPDUE(FRN,0))="" K ^BIPDUE("B",DFN,FRN) Q
 . S IMN=$P($G(^BIPDUE(FRN,0)),"^",2)
 . S RCDUE=$P(^BIPDUE(FRN,0),"^",4),OVDUE=$P(^(0),"^",5)
 . S REMDUE=$S(RCDUE'="":RCDUE,1:OVDUE)
 . S BSR=$P(^AUTTIMM(IMN,0),"^",9)
 . S NIM=0,LIDT=""
 . F  S LIDT=$O(^AUPNVIMM("AA",DFN,IMN,LIDT)) Q:LIDT=""  S NIM=NIM+1
 . S LIDT=$O(^AUPNVIMM("AA",DFN,IMN,LIDT)) I LIDT'="" S REMLAST=9999999-LIDT
 . Q
 Q
 ;
IMM(BIDFN) ;EP - Expand immunization reminders
 S $P(^BIPDUE(0),U,3)=0
 NEW BIDUZ2,BIFORCST,BIPDSS,RMDATE
 S RMDATE=$S($$AGE^BQIAGE(BIDFN,"")>3:365,1:7)
 S BIDUZ2=$P(^BQI(90508,1,0),"^",1),BIFDT=$$FMADD^XLFDT(DT,RMDATE)
 D IMMFORC^BIRPC(.BIFORCST,BIDFN,BIFDT,,$G(BIDUZ2),.BIPDSS)
 Q
 ;
NX ;
 S BQDFN=0,ERRCNT=0
 F  S BQDFN=$O(^AUPNPAT(BQDFN)) Q:'BQDFN  D
 . ; If deceased, don't include
 . I $P($G(^DPT(BQDFN,.35)),U,1)'="" Q
 . ; If no active HRN, don't include
 . I '$$HRN^BQIUL1(BQDFN) Q
 . ; If no visit in last 3 years, quit
 . I '$$VTHR^BQIUL1(BQDFN) Q
 . ; If no visit in last 2 years, quit
 . ;I '$$VTWR^BQIUL1(BQDFN) Q
 . S BIFDT=DT
 . S ^ARLREM(BQDFN,$$NOW^XLFDT(),"W")="NX"
 . D IRPT(BQDFN,"W")
 Q
 ;
PTLS ;EP - Run patient list
 NEW DFN,BIFDT
 S BIFDT=DT,DFN=0
 F  S DFN=$O(^XTMP("BQINIGHT",DFN)) Q:DFN=""  D IRPT(DFN,"N") S ^ARLREM(DFN,"N")=""
 ;F  S DFN=$O(^XTMP("BQINIGHT",DFN)) Q:DFN=""  D FOR(DFN,BIFDT)
 Q
 ;
APT ;EP - check appointments
 NEW NXDAY,PTN,APTD
 S NXDAY=$$FMADD^XLFDT(DT,1)
 S PTN=0
 F  S PTN=$O(^DPT(PTN)) Q:'PTN  D
 . S APTD=$O(^DPT(PTN,"S",NXDAY)) I APTD="" Q
 . I APTD\1'=NXDAY Q
 . D FOR(PTN,APTD)
 Q
 ;
FOR(BIDFN,BIFDT) ;EP - Forecaster
 NEW BIDUZ2,BIFORCST,BIPDSS,RMDATE
 S RMDATE=$S($$AGE^BQIAGE(BIDFN,"")>3:365,1:7)
 S BIDUZ2=$P(^BQI(90508,1,0),"^",1),BIFDT=$$FMADD^XLFDT(DT,RMDATE)
 D IMMFORC^BIRPC(.BIFORCST,BIDFN,BIFDT,,$G(BIDUZ2),.BIPDSS)
 ;D IZ^BQIRMDR2(BIDFN)
 Q
 ;
IRPT(DFN,BQIIJB) ;EP - Parse Immun Forecaster Report
 NEW BDB,BDE,BFB,BFE,BIDATES,BIFFLU,BIVG0,C0LOGLOC,CODE,CT,DUE
 NEW EARL,FUT,GLOBAL,GN,GX,I,IMIEN,IMM,IMN,IN,INPLV,IZN,J,JJOHDID
 NEW OFF0,OFF1,OFF2,OFFS,OK,OUTPLV,OVD,REC,REMDUE,REMLAST,REMNEXT
 NEW STAT,VALUE,VPRCNT,SUB,RMDATE
 ;
 S SUB=$S(BQIIJB="N":"BQIRMFORN",1:"BQIRMFORW")
 K ^XTMP(SUB,DFN)
 I $G(BIDUZ2)="" S BIDUZ2=$P(^BQI(90508,1,0),"^",1)
 ;
 S RMDATE=$S($$AGE^BQIAGE(DFN,"")>3:365,1:7)
 D IMMPROF^BIRPC(.GLOBAL,DFN,$$FMADD^XLFDT(DT,RMDATE))
 ;
 I @GLOBAL@(1)["not in the Immunization Register" D
 . D ADDPAT^BIPATE(DFN,BIDUZ2,.BIERR,$G(DT),"n")
 . D IMMPROF^BIRPC(.GLOBAL,DFN,$$FMADD^XLFDT(DT,RMDATE))
 ;
 S I="" F  S I=$O(@GLOBAL@(I)) Q:I=""  D
 . I $E(@GLOBAL@(I),1,3)="DUE" S BDB=I+3
 . I $E(@GLOBAL@(I),1,6)="FUTURE" S BFB=I+3,BDE=I-2
 . I $E(@GLOBAL@(I),1,8)="COMPLETE" S BFE=I-2
 ;
 I $G(BDB)="" Q
 S CT=0 F I=BDB:1:BDE S CT=CT+1,DUE(CT)=$$TKO^BQIUL1($P(@GLOBAL@(I)," | ",2),$C(30))
 S CT=0 F I=BFB:1:BFE S CT=CT+1,FUT(CT)=$$TKO^BQIUL1($P(@GLOBAL@(I)," | ",2),$C(30))
 ;
 S IN="" F  S IN=$O(^BIPDUE("B",DFN,IN)) Q:IN=""  D
 . I $G(^BIPDUE(IN,0))="" Q
 . S IZN=$P(^BIPDUE(IN,0),"^",2),IMN(IZN)=$P(^AUTTIMM(IZN,0),"^",2)
 S I="" F  S I=$O(DUE(I)) Q:I=""  D PDUE(I)
 S I="" F  S I=$O(FUT(I)) Q:I=""  D PFUT(I)
 ;
 K @GLOBAL
 Q
 ;
PDUE(N) ;
 S (REMDUE,REMLAST,REMNEXT)=""
 S VALUE=DUE(N)
 S IMM=$$STRIP^BQIUL1($E(VALUE,1,13)," "),STAT=$$STRIP^BQIUL1($E(VALUE,14,29)," ")
 S EARL=$$STRIP^BQIUL1($E(VALUE,30,42)," "),REC=$$STRIP^BQIUL1($E(VALUE,43,56)," ")
 S OVD=$$STRIP^BQIUL1($E(VALUE,57,66)," ")
 S CODE="IZ_"_IMM
 I $$UP^XLFSTR(STAT)'="DUE NOW" Q
 I OVD'="NO DATE" S REMDUE=OVD
 I OVD="NO DATE" S REMDUE=REC
 S REMDUE=$$DATE^BQIUL1(REMDUE)
 ;
 S IMIEN=$O(^BITN("D",IMM,"")) I IMIEN="" Q
 S REMLAST=$$LIMM^BQIREM(DFN,IMIEN)
 I REMLAST'="" S REMLAST=$P(REMLAST,"^",1)
 S REMNEXT=STAT
 ;File record
 S SUB=$S(BQIIJB="N":"BQIRMFORN",1:"BQIRMFORW")
 S ^XTMP(SUB,DFN,IMIEN)=REMLAST_"^"_REMDUE_"^"_REMNEXT
 Q
 ;
PFUT(N) ;
 S (REMDUE,REMLAST,REMNEXT)=""
 S VALUE=FUT(N)
 S IMM=$$STRIP^BQIUL1($E(VALUE,1,13)," "),STAT=$$STRIP^BQIUL1($E(VALUE,14,29)," ")
 S EARL=$$STRIP^BQIUL1($E(VALUE,30,42)," "),REC=$$STRIP^BQIUL1($E(VALUE,43,56)," ")
 S CODE="IZ_"_IMM
 I $$UP^XLFSTR(STAT)'="DUE IN FUTURE" Q
 S IMIEN=$O(^BITN("D",IMM,"")) I IMIEN="" Q
 S REMDUE=REC,REMDUE=$$DATE^BQIUL1(REMDUE)
 S REMNEXT=STAT
 S REMLAST=$$LIMM^BQIREM(DFN,IMIEN)
 I REMLAST'="" S REMLAST=$P(REMLAST,"^",1)
 S SUB=$S(BQIIJB="N":"BQIRMFORN",1:"BQIRMFORW")
 S ^XTMP(SUB,DFN,IMIEN)=REMLAST_"^"_REMDUE_"^"_REMNEXT
 Q
