BQIRGUT1 ;GDHD/HS/ALA-Register Utility ; 27 Apr 2016  7:40 AM
 ;;2.9;ICARE MANAGEMENT SYSTEM;**5**;Mar 01, 2021;Build 20
 ;
 ;
ITM(TMFRAME,BQDFN,FREF,RREF,TIEN,TAX,TREF) ;EP - Find the value
 ; Find visits for a request item
 ; Input
 ;   TMFRAME - Time frame to search data for
 ;   BQDFN   - Patient internal entry number
 ;   FREF    - File to search in
 ;   RREF    - Search file table file
 ;   TIEN    - Item to search on
 ;   TAX     - Taxonomy
 ;   TREF    - Reference array
 ;
 NEW GREF,ENDT,IEN,QFL,RESULT,VISIT,VSDTM,RES,DTM,ITIEN,EDT,BDT,VFL
 NEW SRCTYP,BQRES
 S TMFRAME=$G(TMFRAME,"")
 ;I $G(TREF)'="" B
 I $G(TAX)'="" D
 . S TREF=$NA(^TMP($J,"BQITAX")) K @TREF
 . I $G(RREF)=60 D BLD^BQITUTL(TAX,TREF,"L") Q
 . D BLD^BQITUTL(TAX,TREF)
 I $G(TAX)="" D
 . I $G(TIEN)="" Q
 . S TREF="BQITAX" K @TREF
 . S @TREF@(TIEN)=""
 S GREF=$$ROOT^DILFD(FREF,"",1)
 S VFL=$O(^BQI(90508.6,"B",FREF,""))
 I VFL'="" S SRCTYP=$P(^BQI(90508.6,VFL,0),U,3)
 S ENDT=$$DATE^BQIUL1(TMFRAME)
 S IEN="",QFL=0,RESULT=0
 I $G(TMFRAME)'="" D
 . S EDT=9999999-ENDT,BDT=""
 . I SRCTYP'=2 D  Q
 .. F  S BDT=$O(@GREF@("AA",BQDFN,BDT)) Q:BDT=""!(BDT>EDT)  D  Q:QFL
 ... S IEN=""
 ... F  S IEN=$O(@GREF@("AA",BQDFN,BDT,IEN)) Q:IEN=""  D  Q:QFL
 .... S ITIEN=$$GET1^DIQ(FREF,IEN,.01,"I") I ITIEN="" Q
 .... S RES=$$GET1^DIQ(FREF,IEN,.04,"I")
 .... I $G(TIEN)'="",ITIEN'=TIEN Q
 .... I $G(TIEN)="",'$D(@TREF@(ITIEN)) Q
 .... S VISIT=$$GET1^DIQ(FREF,IEN,.03,"I") I VISIT="" Q
 .... I $P($G(^AUPNVSIT(VISIT,0)),"^",11)=1 Q
 .... S VSDTM=$P($G(^AUPNVSIT(VISIT,0)),"^",1)\1 I VSDTM=0 Q
 .... S BQRES(VSDTM,VISIT,IEN)=RES
 . ;
 . F  S BDT=$O(@GREF@("AA",PTDFN,TIEN,BDT)) Q:BDT=""!(BDT>EDT)  D
 .. S IEN=""
 .. F  S IEN=$O(@GREF@("AA",PTDFN,TIEN,BDT,IEN)) Q:IEN=""  D
 ... S ITIEN=$$GET1^DIQ(FREF,IEN,.01,"I") I ITIEN="" Q
 ... S RES=$$GET1^DIQ(FREF,IEN,.04,"I")
 ... I $G(TIEN)'="",ITIEN'=TIEN Q
 ... I $G(TIEN)="",'$D(@TREF@(ITIEN)) Q
 ... S VISIT=$$GET1^DIQ(FREF,IEN,.03,"I") I VISIT="" Q
 ... I $P($G(^AUPNVSIT(VISIT,0)),"^",11)=1 Q
 ... S VSDTM=$P($G(^AUPNVSIT(VISIT,0)),"^",1)\1 I VSDTM=0 Q
 ... S BQRES(VSDTM,VISIT,IEN)=RES
 . ; check for refusal
 . I $O(^AUPNPREF("AA",BQDFN,RREF,""))'="" D
 .. I $D(TREF) S TIEN="" F  S TIEN=$O(@TREF@(TIEN)) Q:TIEN=""  D
 ... S EDT=9999999-ENDT,BDT=""
 ... F  S BDT=$O(^AUPNPREF("AA",BQDFN,RREF,TIEN,BDT)) Q:BDT=""!(BDT>EDT)  D
 .... S IEN="" F  S IEN=$O(^AUPNPREF("AA",BQDFN,RREF,TIEN,BDT,IEN)) Q:IEN=""  D
 ..... S DTM=$P(^AUPNPREF(IEN,0),U,3)
 ..... I $P(RESULT,U,2)'="",DTM<$P(RESULT,U,2) Q
 ..... S BQRES(DTM,"~","~")="refusal"
 ;
 I $G(TMFRAME)="" D
 . S IEN=""
 . F  S IEN=$O(@GREF@("AC",BQDFN,IEN),-1) Q:IEN=""  D  Q:QFL
 .. S ITIEN=$$GET1^DIQ(FREF,IEN,.01,"I") I ITIEN="" Q
 .. I $G(TIEN)'="",ITIEN'=TIEN Q
 .. I $G(TIEN)="",'$D(@TREF@(ITIEN)) Q
 .. S RES=$$GET1^DIQ(FREF,IEN,.04,"I")
 .. S VISIT=$$GET1^DIQ(FREF,IEN,.03,"I") I VISIT="" Q
 .. I $P($G(^AUPNVSIT(VISIT,0)),"^",11)=1 Q
 .. S VSDTM=$P($G(^AUPNVSIT(VISIT,0)),"^",1)\1 I VSDTM=0 Q
 .. S BQRES(VSDTM,VISIT,IEN)=RES
 . ; check for refusal
 . I $O(^AUPNPREF("AA",BQDFN,RREF,""))'="" D
 .. I $D(TREF) S TIEN="" F  S TIEN=$O(@TREF@(TIEN)) Q:TIEN=""  D
 ... ;S EDT=(9999999-DT)+.001,BDT=""
 ... S BDT="",STOP=0
 ... F  S BDT=$O(^AUPNPREF("AA",BQDFN,RREF,TIEN,BDT)) Q:BDT=""  D  Q:STOP
 .... S IEN="" F  S IEN=$O(^AUPNPREF("AA",BQDFN,RREF,TIEN,BDT,IEN)) Q:IEN=""  D  Q:STOP
 ..... S DTM=$P(^AUPNPREF(IEN,0),U,3)
 ..... I $P(RESULT,U,2)'="",DTM<$P(RESULT,U,2) Q
 ..... S BQRES(DTM,"~","~")="refusal"
 ;
 I '$D(BQRES) S RESULT=0
 I $D(BQRES) D
 . S DTM=$O(BQRES(""),-1),VISIT=$O(BQRES(DTM,""),-1),IEN=$O(BQRES(DTM,VISIT,""),-1)
 . S RES=BQRES(DTM,VISIT,IEN)
 . S RESULT=1_U_DTM_U_U_VISIT_U_IEN_U_RES
 Q RESULT
 ;
LABS(BQDFN,TAX,TREF,START,END,TYP,TEMP) ;EP
 ; Check for a lab test result
 ;
 NEW EDATE,BDATE,LIEN,QFL,RES,CT,VALUE,VIEN,VSDTM
 S BDATE=$G(START),EDATE=$G(END)
 S TAX=$G(TAX,"")
 I TAX'="" D
 . S TREF=$NA(^TMP("BQITAX",UID))
 . K @TREF
 . I $G(RREF)'=60 D BLD^BQITUTL(TAX,TREF)
 . I $G(RREF)=60 D BLD^BQITUTL(TAX,TREF,"L")
 ;
 S QFL=0,CT=0
 S TIEN=""
 F  S TIEN=$O(@TREF@(TIEN)) Q:TIEN=""  D
 . S EDT=9999999-BDATE,BDT=(9999999-EDATE)-.001
 . F  S BDT=$O(^AUPNVLAB("AA",BQDFN,TIEN,BDT)) Q:BDT=""!(BDT\1>EDT)  D
 .. S LIEN=""
 .. F  S LIEN=$O(^AUPNVLAB("AA",BQDFN,TIEN,BDT,LIEN)) Q:LIEN=""  D
 ... S VALUE=$P(^AUPNVLAB(LIEN,0),U,4) I VALUE="" Q
 ... S VALUE=$$UP^XLFSTR(VALUE)
 ... I VALUE["COMMENT"!(VALUE["FOOTNOTE")!(VALUE["CANC")!(VALUE["PENDING") Q
 ... I VALUE["NORESULT" Q
 ... S VSDTM=9999999-BDT
 ... S @TEMP@(VSDTM,TYP,LIEN)=VALUE
 Q
 ;
MEAS(BQDFN,MEAS,START,END) ;EP
 ; Check for a measurement during a date range
 NEW VALUE,BDT,EDT,QFL,RESULT,VDATE,RES,IEN
 I MEAS'?.N S MEAS=$$FIND1^DIC(9999999.07,,"MX",MEAS)
 S VALUE="",EDT="",BDT=""
 S EDT=$S($G(START)'="":9999999-START,1:"")
 S BDT=$S($G(END)'="":9999999-END,1:"")
 S QFL=0
 F  S BDT=$O(^AUPNVMSR("AA",BQDFN,MEAS,BDT)) Q:BDT=""  D  Q:QFL
 . I EDT'="",(BDT>EDT) Q
 . S IEN=""
 . F  S IEN=$O(^AUPNVMSR("AA",BQDFN,MEAS,BDT,IEN)) Q:IEN=""  D  Q:QFL
 .. ; if the new ENTERED IN ERROR field exists, exclude the record if it is marked as an error
 .. I $$VFIELD^DILFD(9000010.01,2) Q:$$GET1^DIQ(9000010.01,IEN_",",2,"I")=1
 .. S RES=$G(^AUPNVMSR(IEN,0)),RESULT=$P(RES,U,4),VDATE="",RESULT=$J(RESULT,3,2)
 .. I $P($G(^AUPNVMSR(IEN,2)),U,1)=1 Q
 .. S VDATE=9999999-BDT
 .. S VALUE=RESULT_" ("_$$FMTE^BQIUL1(VDATE)_")",QFL=1
 Q VALUE
