BQITRIBE ;GDIT/HS/ALA - Check location ; 10 Mar 2022  2:36 PM
 ;;2.9;ICARE MANAGEMENT SYSTEM;**3**;Mar 01, 2021;Build 32
 ;
IS(DATA,FAKE) ;EP - BQI GET LOCATION
 ; Is master location a tribe or non-IHS
 S II=0,DATA=$NA(^TMP("BQIISLOC"))
 S @DATA@(II)="I00010RESULT^T01024ERROR"_$C(30)
 S DA=$O(^BQI(90508,0)) I 'DA S RESULT=-1,ERROR="No site defined. Create a SNow ticket."
 I DA D
 . S RESULT=0
 . S LOCN=$P(^BQI(90508,DA,0),"^",1)
 . S AREA=$$GET1^DIQ(9999999.06,LOCN_",",.04,"E")
 . I AREA["TRIBE/638"!(AREA["NON-IHS") S RESULT=1
 S II=II+1,@DATA@(II)=RESULT_U_$G(ERROR)_$C(30)
 S II=II+1,@DATA@(II)=$C(31)
 K II,DA,LOCN,AREA,RESULT
 Q
 ;
FLAG(DATA,EFLG) ;EP - BQI SET EXPORT FLAG
 S II=0,DATA=$NA(^TMP("BQILFLAG"))
 S @DATA@(II)="I00010RESULT^T01024ERROR"_$C(30)
 S EFLG=$G(EFLG,0) I EFLG=0 S EFLAG="@"
 S UPD(90508,"1,",.05)=EFLG
 D FILE^DIE("","UPD","ERROR")
 S RESULT=1
 I $D(ERROR) S RESULT=-1,ERROR=$G(ERROR("DIERR",1,"TEXT",1))
 S II=II+1,@DATA@(II)=RESULT_"^"_$G(ERROR)_$C(30)
 S II=II+1,@DATA@(II)=$C(31)
 K II,EFLG,RESULT
 Q
 ;
GFLG(DATA,FAKE) ;EP - BQI GET EXPORT FLAG
 S II=0,DATA=$NA(^TMP("BQILFLAG")) K @DATA
 S @DATA@(II)="I00010STATUS"_$C(30)
 S RESULT=$$GET1^DIQ(90508,"1,",.05,"I")
 I RESULT="" S RESULT=0
 S II=II+1,@DATA@(II)=RESULT_$C(30)
 S II=II+1,@DATA@(II)=$C(31)
 K II,RESULT
 Q
 ;
EXPF(DATA,FAKE) ;EP - BQI GET EXPORT FORMAT
 S II=0,DATA=$NA(^TMP("BQICAEXF")) K @DATA
 S @DATA@(II)="T00020STATUS"_$C(30)
 S VALUE=$$GET1^DIQ(90508,"1,",.06,"I")
 S RESULT=$S(VALUE=1:"Both HL7 and CCDA",VALUE=2:"CCDA Only",1:"HL7 Only")
 S II=II+1,@DATA@(II)=RESULT_$C(30)
 S II=II+1,@DATA@(II)=$C(31)
 K II,RESULT,VALUE
 Q
 ;
SEXP(DATA,FORMAT) ;EP - BQI SET EXPORT FORMAT
 S II=0,DATA=$NA(^TMP("BQCAEXF"))
 S @DATA@(II)="I00010RESULT^T01024ERROR"_$C(30)
 S EFLG=$S(FORMAT="Both HL7 and CCDA":1,FORMAT="CCDA Only":2,1:"@")
 S UPD(90508,"1,",.06)=EFLG
 D FILE^DIE("","UPD","ERROR")
 S RESULT=1
 I $D(ERROR) S RESULT=-1,ERROR=$G(ERROR("DIERR",1,"TEXT",1))
 S II=II+1,@DATA@(II)=RESULT_"^"_$G(ERROR)_$C(30)
 S II=II+1,@DATA@(II)=$C(31)
 K II,EFLG,RESULT
 Q
