BQITASK5 ;GDIT/HCSD/ALA-Nightly Job Tasks ; 19 Apr 2018  6:03 PM
 ;;2.7;ICARE MANAGEMENT SYSTEM;**2**;Dec 19, 2017;Build 10
 ;;
 ;
JBFL ;EP - job off Flags
 NEW ZTDTH,ZTDESC,ZTRTN,ZTIO,ZTSAVE
 S ZTDTH=$$FMADD^XLFDT($$NOW^XLFDT(),,,2)
 S ZTDESC="Update iCare Nightly Flags",ZTIO=""
 S ZTRTN="FLG^BQITASK5"
 D ^%ZTLOAD
 ;S ^XTMP("ARLIS","JBFL")=ZTSK
 K ZTSK
 Q
 ;
FLG ;EP - Job off Flags
 NEW $ESTACK,$ETRAP S $ETRAP="D ERR^BQI1POJB D UNWIND^%ZTER"
 ;
 ;  Set the DATE/TIME FLAG STARTED field
 NEW DA
 S DA=$O(^BQI(90508,0)) I 'DA Q
 S BQIUPD(90508,DA_",",3.01)=$$NOW^XLFDT()
 S BQIUPD(90508,DA_",",3.03)=1
 D FILE^DIE("","BQIUPD","ERROR")
 K BQIUPD
 ;
 ; Find all flags for patients
 D FND^BQIFLG
 ;
 ;  Set the DATE/TIME FLAG STOPPED field
 NEW DA
 S DA=$O(^BQI(90508,0)) I 'DA Q
 S BQIUPD(90508,DA_",",3.02)=$$NOW^XLFDT()
 S BQIUPD(90508,DA_",",3.03)="@"
 D FILE^DIE("","BQIUPD","ERROR")
 K BQIUPD
 Q
 ;
JCMA ;EP - Job off Community Alerts
 NEW ZTDTH,ZTDESC,ZTRTN,ZTIO,ZTSAVE
 S ZTDTH=$$FMADD^XLFDT($$NOW^XLFDT(),,,2)
 S ZTDESC="Update iCare Community Alerts",ZTIO=""
 S ZTRTN="CMA^BQINIGH2"
 D ^%ZTLOAD
 ;S ^XTMP("ARLIS","JCMA")=ZTSK
 K ZTSK
 Q
 ;
JIMF ;EP -  Job off Immunization Forecaster
 NEW ZTDTH,ZTDESC,ZTRTN,ZTIO,ZTSAVE
 S ZTDTH=$$FMADD^XLFDT($$NOW^XLFDT(),,,2)
 S ZTDESC="Update Immunization Forecaster",ZTIO=""
 S ZTRTN="IMF^BQITASK5"
 D ^%ZTLOAD
 ;S ^XTMP("ARLIS","JIMF")=ZTSK
 K ZTSK
 Q
 ;
IMF ;EP - Immunization Forecaster
 K ^XTMP("BQIIZF")
 S ^XTMP("BQIIZF",0)=$$FMADD^XLFDT(DT,7)_U_DT_U_"Immunization Forecaster"
 S ^XTMP("BQIIZF",1)=0
 S BQIUPD(90508,"1,",4.19)=$$NOW^XLFDT()
 D FILE^DIE("","BQIUPD","ERROR")
 D PTLS^BQIRMIZ
 S BQIUPD(90508,"1,",4.2)=$$NOW^XLFDT()
 D FILE^DIE("","BQIUPD","ERROR")
 S ^XTMP("BQIIZF",1)=1
 Q
 ;
JGP ;EP - Job GPRA Compile
 NEW ZTDTH,ZTDESC,ZTRTN,ZTIO,ZTSAVE
 S ZTDTH=$$FMADD^XLFDT($$NOW^XLFDT(),,,2)
 S ZTDESC="Update CRS Compile",ZTIO=""
 S ZTRTN="COMP^BQIGPRA5"
 D ^%ZTLOAD
 ;S ^XTMP("ARLIS","JGP")=ZTSK
 K ZTSK
 Q
 ;
JCMG ;EP - Job Care Mgnt Groups
 NEW ZTDTH,ZTDESC,ZTRTN,ZTIO,ZTSAVE
 S ZTDTH=$$FMADD^XLFDT($$NOW^XLFDT(),,,2)
 S ZTDESC="Update Care Mgmt Groups",ZTIO=""
 S ZTRTN="AST^BQINIGH1"
 D ^%ZTLOAD
 ;S ^XTMP("ARLIS","JCMG")=ZTSK
 K ZTSK
 Q
