BQIULP1 ;GDIT/HCSD/ALA-Patient Demographic Utilities ; 31 Aug 2022  11:23 AM
 ;;2.9;ICARE MANAGEMENT SYSTEM;**4,7**;Mar 01, 2021;Build 14
 ;
NAM(DFN,NTYP) ;Patient Names
 ; DFN=Patient IEN
 ; NTYP="F" Full Name
 ; NTYP="P" Preferred Name only
 ;
 ;NEW PPN
 S PPN=+$$GET^XPAR("SYS","AUPN DISPLAY PPN")
 I $G(NTYP)="F" D
 . I 'PPN S RES=$$GETPREF^AUPNSOGI(DFN,"E",1) Q
 . S RES=$$GETPREF^AUPNSOGI(DFN,"E",PPN)
 ;
 I $G(NTYP)="P" D
 . I 'PPN S RES=$$GETPREF^AUPNSOGI(DFN,"I",1) Q
 . S RES=$$GETPREF^AUPNSOGI(DFN,"I",PPN)
 Q $G(RES)
 ;
PRON(DFN) ;EP - Pronouns
 S RES=$$GETPRN^AUPNSOGI(DFN,"B")
 I RES="UNK"!(RES="ASKU") S RES=$$GETPRN^AUPNSOGI(DFN,"E")
 Q RES
 ;
LSEX(DFN) ;EP - Legal Sex
 S RES=$$GETLSEX^AUPNSOGI(DFN,"E",0,"")
 Q $P(RES,"^",2)
 ;
SEXO(DFN) ;EP - Sexual Orientation
 S RES=$$GETSO^AUPNSOGI(DFN,"E",0,"")
 Q $P(RES,"^",2)
 ;
GENID(DFN) ;EP - Gender Identification
 S RES=$$GETGI^AUPNSOGI(DFN,"E",0,"")
 Q $P(RES,"^",2)
 ;
LEGL(DFN) ;EP - List of Legal Names
 NEW EEN
 S RES=""
 I '$D(^AUPNNAMC("C",DFN)) Q RES
 S EEN="" F  S EEN=$O(^AUPNNAMC("C",DFN,EEN)) Q:EEN=""  D
 . S DAT=$P(^AUPNNAMC(EEN,0),"^",1),NAM=$P(^AUPNNAMC(EEN,0),"^",3)
 . S RES=RES_NAM_" ("_$$FMTE^XLFDT(DAT)_")"_$C(13)_$C(10)
 I RES'="" S RES=$$TKO^BQIUL1(RES,$C(13)_$C(10))
 Q RES
 ;
ALIAS(DFN) ;EP - List of Alias Names
 NEW AEN
 S RES=""
 I $O(^DPT(DFN,.01,0))="" Q RES
 S AEN=0 F  S AEN=$O(^DPT(DFN,.01,AEN)) Q:'AEN  D
 . S RES=RES_$P(^DPT(DFN,.01,AEN,0),"^",1)_$C(13)_$C(10)
 I RES'="" S RES=$$TKO^BQIUL1(RES,$C(13)_$C(10))
 Q RES
 ;
PHNV(DFN) ;EP - Last visit with PHN
 NEW PHNN,RES,RVD,QFL,VIS
 S RES=""
 S PHNN=$O(^DIC(40.7,"C",45,""))
 I PHNN'="" D
 . S RVD="",QFL=0 F  S RVD=$O(^AUPNVSIT("AA",DFN,RVD)) Q:RVD=""!(QFL=1)  D
 .. S VIS="" F  S VIS=$O(^AUPNVSIT("AA",DFN,RVD,VIS)) Q:VIS=""  D
 ... I $P(^AUPNVSIT(VIS,0),"^",8)=PHNN S RES=$P(^AUPNVSIT(VIS,0),"^",1),QFL=1 Q
 I RES'="" S RES=$$FMTE^BQIUL1(RES)
 Q RES
 ;
IMDUE(DFN) ;EP Immunizations Due
 NEW BGLOB,X,BID,BVAL
 S BGLOB=$NA(^TMP("BQIIMDUE",$J)) K @BGLOB
 S X=$$IMMDUE^BTIULO2(+$G(DFN),.BGLOB)
 S RESULT=""
 S BID="" F  S BID=$O(@BGLOB@(BID)) Q:BID=""  D
 . S BVAL=@BGLOB@(BID,0)
 . I BID=1 S BVAL=$P(BVAL,":",2)
 . S BVAL=$$TRIM^BQIUL1(BVAL," ")
 . S RESULT=RESULT_BVAL_$C(13)_$C(10)
 K %I,BIDATE,BIFFLU,BIFSUP,BIFSUPV,BIRP,C0LOGLOC,BIVG0,INPLV,JJOHDID,OUTPLV
 K OK,OFF0,OFF1,OFF2,OFFS,VPRCNT,BIDATES,GN,GX
 Q $$TKO^BQIUL1(RESULT,$C(13)_$C(10))
