BQIUSRLK ;GDIT/HCSD/ALA-User Lookup ; 13 Apr 2023  9:05 AM
 ;;2.9;ICARE MANAGEMENT SYSTEM;**5**;Mar 01, 2021;Build 20
 ;
EN(DATA,TYPE,VALUE) ;EP -- BQI LOOKUP USER
 NEW UID,II,X,DDATA
 S UID=$S($G(ZTSK):"Z"_ZTSK,1:$J)
 S TYPE=$$UP^XLFSTR(TYPE)
 I TYPE["PROVIDER" S SCREEN="I +$P($G(~(0)),U,11)'>0,$P(~(0),U,11)'>DT,$D(~VA(200,""AK.PROVIDER"",$P($G(~(0)),U),+Y))"
 I TYPE'["PROVIDER" S SCREEN="I $$ACTIVE~XUSER(Y)>0"
 D LKP^BQIVFTLK(.DATA,200,VALUE,SCREEN)
 K SCREEN,C
 Q
