BQIUTB4 ;GDIT/HS/ALA-Tables ; 05 Dec 2012  12:40 PM
 ;;2.9;ICARE MANAGEMENT SYSTEM;**5**;Mar 01, 2021;Build 20
 ;
ACM(DATA) ;EP - ACM Registers
 NEW RN
 S II=0,RN=0
 S @DATA@(II)="T00010REGIEN^T00030"_$C(30)
 F  S RN=$O(^ACM(41.1,RN)) Q:'RN  D
 . I $G(^ACM(41.1,RN,0))="" Q
 . ;I $P(^ACM(41.1,RN,0),U,14)'=1 Q
 . I '$D(^ACM(41.1,RN,"AU",DUZ)) Q
 . S II=II+1,@DATA@(II)=RN_U_$P(^ACM(41.1,RN,0),U,1)_$C(30)
 S II=II+1,@DATA@(II)=$C(31)
 Q
 ;
WARD(DATA) ;EP - Ward
 NEW RN
 S II=0,RN=0
 S @DATA@(II)="T00010IEN^T00030"_$C(30)
 F  S RN=$O(^DIC(42,RN)) Q:'RN  D
 . S II=II+1,@DATA@(II)=RN_U_$P(^DIC(42,RN,0),U,1)_$C(30)
 S II=II+1,@DATA@(II)=$C(31)
 Q
 ;
FSPEC(DATA) ;EP - Treating Specialty
 NEW RN,N
 S II=0,RN=0
 S @DATA@(II)="T00010IEN^T00030"_$C(30)
 F  S RN=$O(^DIC(45.7,RN)) Q:'RN  D
 . I '$D(^DIC(45.7,RN,"E")) Q
 . S N=0
 . F  S N=$O(^DIC(45.7,RN,"E",N)) Q:'N  D
 .. I $P(^DIC(45.7,RN,"E",N,0),"^",2)'=1 Q
 .. S II=II+1,@DATA@(II)=RN_U_$P(^DIC(45.7,RN,0),U,1)_$C(30)
 S II=II+1,@DATA@(II)=$C(31)
 Q
 ;
IATYP(DATA) ; EP - Admit Type
 NEW RN
 S II=0,RN=0
 S @DATA@(II)="T00010IEN^T00030"_$C(30)
 F  S RN=$O(^DG(405.1,RN)) Q:'RN  D
 . I $$GET1^DIQ(405.1,RN_",",.02,"E")'="ADMISSION" Q
 . I $P(^DG(405.1,RN,0),U,4)'=1 Q
 . S II=II+1,@DATA@(II)=RN_U_$P(^DG(405.1,RN,0),U,1)_$C(30)
 S II=II+1,@DATA@(II)=$C(31)
 Q
 ;
IDTYP(DATA) ; EP - Discharge type
 NEW RN
 S II=0,RN=0
 S @DATA@(II)="T00010IEN^T00030"_$C(30)
 F  S RN=$O(^DG(405.1,RN)) Q:'RN  D
 . I $$GET1^DIQ(405.1,RN_",",.02,"E")'="DISCHARGE" Q
 . I $P(^DG(405.1,RN,0),U,4)'=1 Q
 . S II=II+1,@DATA@(II)=RN_U_$P(^DG(405.1,RN,0),U,1)_$C(30)
 S II=II+1,@DATA@(II)=$C(31)
 Q
 ;
EDTYP(DATA) ; EP - ER Disposition type
 NEW RN,ETY
 S II=0,RN=""
 S @DATA@(II)="T00010IEN^T00030"_$C(30)
 S ETY=$$FIND1^DIC(9009082,"","MOX","DISPOSITION","","","ERROR")
 F  S RN=$O(^AMER(3,"AC",ETY,RN)) Q:RN=""  D
 . S II=II+1,@DATA@(II)=RN_U_$P(^AMER(3,RN,0),U,1)_$C(30)
 S II=II+1,@DATA@(II)=$C(31)
 Q
 ;
EVTYP(DATA) ; EP - ER Visit type
 NEW RN,ETY
 S II=0,RN=""
 S @DATA@(II)="T00010IEN^T00030"_$C(30)
 S ETY=$$FIND1^DIC(9009082,"","MOX","VISIT TYPE","","","ERROR")
 F  S RN=$O(^AMER(3,"AC",ETY,RN)) Q:RN=""  D
 . S II=II+1,@DATA@(II)=RN_U_$P(^AMER(3,RN,0),U,1)_$C(30)
 S II=II+1,@DATA@(II)=$C(31)
 Q
 ;
EDACU(DATA) ;EP - ER Acuity
 S II=0,@DATA@(II)="T00010IEN^T00060"_$C(30)
 F I=1:1:5 S II=II+1,@DATA@(II)=I_U_"Acuity Level "_I_$C(30)
 S II=II+1,@DATA@(II)=$C(31)
 Q
 ;
PRFC(DATA) ; EP - Preferred Communication
 NEW FLAG,VALUE,BJ,CODE,TEXT
 S II=0
 S @DATA@(II)="T00001CODE^T00030"_$C(30)
 S VALUE=$P(^DD(9000001,4002,0),U,3)
 F BJ=1:1:$L(VALUE,";") D
 . S CODE=$P(VALUE,";",BJ) Q:CODE=""
 . S TEXT=$P(CODE,":",2)
 . S II=II+1,@DATA@(II)=$P(CODE,":",1)_"^"_TEXT_$C(30)
 S II=II+1,@DATA@(II)=$C(31)
 Q
 ;
ETOP(DATA) ; EP - Education Topics
 NEW LN,VALUE,TOP
 S II=0,LN=0
 S @DATA@(II)="T00030IEN^T00060"_$C(30)
 F  S LN=$O(^AUTTEDMT(LN)) Q:'LN  D
 . S II=II+1,@DATA@(II)=LN_U_$P(^AUTTEDMT(LN,0),U,1)_$C(30)
 S II=II+1,@DATA@(II)=$C(31)
 Q
 ;
EDUC(DATA) ;EP - Education
 NEW LN
 S II=0,LN=0
 S @DATA@(II)="T00010IEN^T00060"_$C(30)
 F  S LN=$O(^AUPNVPED("B",LN)) Q:LN=""  D
 . I $G(^AUTTEDT(LN,0))="" Q
 . I $P(^AUTTEDT(LN,0),U,3)'="" Q
 . S II=II+1,@DATA@(II)=LN_U_$P(^AUTTEDT(LN,0),U,1)_$C(30)
 S II=II+1,@DATA@(II)=$C(31)
 Q
 ;
TMFRAM(DATA,PARM) ;EP - List of timeframes by parameter
 NEW LN,BZ
 K BZ
 S II=0,LN=""
 S @DATA@(II)="T00010IEN^T00060"_$C(30)
 S II=II+1,@DATA@(II)="0^"_$C(30)
 S ORD=""
 F  S ORD=$O(^BQI(90506.9,"D",PARM,ORD)) Q:ORD=""  D
 . S LN=$O(^BQI(90506.9,"D",PARM,ORD,""))
 . S II=II+1,@DATA@(II)=LN_U_$P(^BQI(90506.9,LN,0),U,1)_$C(30)
 S II=II+1,@DATA@(II)=$C(31)
 Q
 ;
EPICK(DATA) ;EP - EHR Education Picklists
 NEW RET,INP,LN
 S $P(INP,U,3)=DUZ,$P(INP,U,5)=0
 D GETCATS^BGOEDTPR(.RET,INP)
 S II=0,@DATA@(II)="T00010IEN^T00060"_$C(30)
 S LN=0
 F  S LN=$O(@RET@(LN)) Q:LN=""  D
 . S II=II+1,@DATA@(II)=$P(@RET@(LN),U,2)_U_$P(@RET@(LN),U,1)_$C(30)
 S II=II+1,@DATA@(II)=$C(31)
 K @RET
 Q
 ;
PKIT(DATA,PICK) ;EP - BQI GET PICKLIST ITEMS
 NEW UID,II,LN,RET
 S UID=$S($G(ZTSK):"Z"_ZTSK,1:$J)
 S DATA=$NA(^TMP("BQIUTB4P",UID))
 K @DATA
 S II=0
 NEW $ESTACK,$ETRAP S $ETRAP="D ERR^BQIUTB1 D UNWIND^%ZTER" ; SAC 2006 2.2.3.3.2
 S @DATA@(II)="I00010IEN^T00030ED_ITEM"_$C(30)
 D GETITEMS^BGOEDTPR(.RET,PICK)
 S LN=0
 F  S LN=$O(@RET@(LN)) Q:LN=""  D
 . S II=II+1,@DATA@(II)=$P(@RET@(LN),U,1)_U_$P(@RET@(LN),U,2)_$C(30)
 S II=II+1,@DATA@(II)=$C(31)
 K @RET
 Q
 ;
MTIT(DATA,TOP) ;EP - BQI GET ED TOPIC ITEMS
 NEW UID,II,LN,RET,ZZ,TEXT,TOPN
 S UID=$S($G(ZTSK):"Z"_ZTSK,1:$J)
 S DATA=$NA(^TMP("BQIUTB4T",UID))
 K @DATA,ZZ
 S II=0
 NEW $ESTACK,$ETRAP S $ETRAP="D ERR^BQIUTB1 D UNWIND^%ZTER" ; SAC 2006 2.2.3.3.2
 S @DATA@(II)="I00010IEN^T00060"_$C(30)
 S TOPN=TOP,TOP=$P(^AUTTEDMT(TOPN,0),U,2)
 S LN=0
 F  S LN=$O(^AUTTEDT(LN)) Q:'LN  D
 . S RET=$G(^AUTTEDT(LN,0))
 . I RET="" Q
 . I $P(RET,U,3)'="" Q
 . I $P(RET,U,6)'=TOP Q
 . S TEXT=$P($P(RET,U,1),"-",2,99),ZZ(TEXT)=LN
 S TEXT=""
 F  S TEXT=$O(ZZ(TEXT)) Q:TEXT=""  D
 . S LN=ZZ(TEXT)
 . S II=II+1,@DATA@(II)=LN_U_TEXT_$C(30)
 S II=II+1,@DATA@(II)=$C(31)
 Q
 ;
CRM(DATA) ;EP - Care Management Layout Sources
 NEW CIEN,TGIEN,RGIEN,REG,TAG,FMIEN,FORM,VIEW,REM,REPORT,KEY,PNDROP,PTDROP,MTDROP
 S @DATA@(II)="I00010IEN^T00030LAYOUT^T00030FORM^T00030TAG^I00010TAG_IEN^T00030REGISTER^T00001PAT_VIEW^T00001REMINDERS^T00030REPORT^T00001PAT_DROPDOWN^T00001PAN_DROPDOWN^T00001MAT_DROPDOWN"_$C(30)
 S CIEN=0
 F  S CIEN=$O(^BQI(90506.5,CIEN)) Q:'CIEN  D
 . NEW TGIEN,RGIEN,REG,TAG,FMIEN,FORM,VIEW,REM,REPORT,KEY,PNDROP,PTDROP
 . I $P(^BQI(90506.5,CIEN,0),U,4)'=1 Q
 . I $P(^BQI(90506.5,CIEN,0),U,10)=1 Q
 . S KEY=$P(^BQI(90506.5,CIEN,0),U,12)
 . I KEY'="",'$$KEYCHK^BQIULSC(KEY,DUZ) Q
 . S RGIEN=$P(^BQI(90506.5,CIEN,0),U,3)
 . I RGIEN'="" S REG=$$GET1^DIQ(90507,RGIEN_",",.01,"E")
 . I RGIEN'="" S TGIEN=$O(^BQI(90506.2,"AD",RGIEN,""))
 . I $G(TGIEN)'="" S TAG=$$GET1^DIQ(90506.2,TGIEN_",",.01,"E")
 . I $G(TAG)="" S TAG=$$GET1^DIQ(90506.5,CIEN_",",.11,"E"),TGIEN=$$GET1^DIQ(90506.5,CIEN_",",.11,"I")
 . S FMIEN=$O(^BQI(90506.3,"AC",CIEN,""))
 . I FMIEN'="",$P(^BQI(90506.3,FMIEN,0),U,3)'=1 S FORM=$$GET1^DIQ(90506.3,FMIEN_",",.01,"E")
 . ;S VIEW=$S($P(^BQI(90506.5,CIEN,0),U,7)'="":"Y",1:"N")
 . S REM=$S($P(^BQI(90506.5,CIEN,0),U,5)'="":"Y",1:"N")
 . S REPORT=$P(^BQI(90506.5,CIEN,0),U,8)
 . S VIEW=$S($G(FORM)'="":"F",$G(REPORT)'="":"R",1:"")
 . I $G(REG)="" S REG=$P(^BQI(90506.5,CIEN,0),U,1)
 . S PTDROP=$S($P(^BQI(90506.5,CIEN,0),U,13)'="":"Y",1:"")
 . S PNDROP=$S($P(^BQI(90506.5,CIEN,0),U,14)'="":"Y",1:"")
 . S MTDROP=$S($P(^BQI(90506.5,CIEN,0),U,15)'="":"Y",1:"")
 . ;
 . S II=II+1,@DATA@(II)=CIEN_U_$P(^BQI(90506.5,CIEN,0),U,1)_U_$G(FORM)_U_$G(TAG)_U_$G(TGIEN)_U_$G(REG)_U_$G(VIEW)_U_$G(REM)_U_$G(REPORT)_U_$G(PTDROP)_U_$G(PNDROP)_U_$G(MTDROP)_$C(30)
 . K REG,TGIEN,TAG,FMIEN,FORM,VIEW,RGIEN
 S II=II+1,@DATA@(II)=$C(31)
 Q
 ;
VENC(DATA) ;EP - Visit Locations of Encounter
 NEW IEN,LNAME,LVAL,TY,ORD,LNM,II,SU,AR,DSP,DSPNM
 S II=0
 S @DATA@(II)="I00010IEN^T00030LOCATION^T00030SERVUNIT^T00030AREA^T00060DISPLAY_NAME^I00010SORTORD"_$C(30)
 S IEN=0
 F  S IEN=$O(^XTMP("BQIVLENC",IEN)) Q:IEN=""  D
 . I $G(^DIC(4,IEN,0))="" Q
 . S LNAME=$P(^DIC(4,IEN,0),"^",1)
 . S SU=$$GET1^DIQ(9999999.06,IEN_",",.05,"E")
 . S AR=$$GET1^DIQ(9999999.06,IEN_",",.04,"E")
 . S DSP=LNAME_" ("_SU_")"
 . ; If the location is inactive, show it with a '*'
 . I $P($G(^AUTTLOC(IEN,0)),U,21)'="" S LVAL("[",LNAME,IEN)=IEN_"^"_SU_"^"_AR_"^"_DSP Q
 . S LVAL(1,LNAME,IEN)=IEN_"^"_SU_"^"_AR_"^"_DSP
 ;
 S TY="",ORD=0 F  S TY=$O(LVAL(TY)) Q:TY=""  D
 . S LNM="" F  S LNM=$O(LVAL(TY,LNM)) Q:LNM=""  D
 .. S IEN="" F  S IEN=$O(LVAL(TY,LNM,IEN)) Q:IEN=""  D
 ... S IEN=$P(LVAL(TY,LNM,IEN),"^",1),LNAME=LNM,SU=$P(LVAL(TY,LNM,IEN),"^",2)
 ... S AR=$P(LVAL(TY,LNM,IEN),"^",3),DSPNM=$P(LVAL(TY,LNM,IEN),"^",4)
 ... I TY="[" S LNAME="*"_LNAME
 ... S ORD=ORD+1
 ... S II=II+1,@DATA@(II)=IEN_"^"_LNAME_"^"_SU_"^"_AR_"^"_DSPNM_"^"_ORD_$C(30)
 S II=II+1,@DATA@(II)=$C(31)
 Q
 ;
VSERV(DATA) ;EP - Visit Service Categories
 NEW II,VALUE,VAL
 S II=0
 S @DATA@(II)="T00010IEN^T00030DESCRIPTION"_$C(30)
 S VALUE=$P(^DD(9000010,.07,0),"^",3)
 F I=1:1:$L(VALUE,";") D
 . S VAL=$P(VALUE,";",I) Q:VAL=""
 . S II=II+1,@DATA@(II)=$P(VAL,":",1)_"^"_$P(VAL,":",2)_$C(30)
 S II=II+1,@DATA@(II)=$C(31)
 Q
 ;
OVCLN(DATA) ;EP - Visit Clinics
 NEW II,IEN,LNAME,LVAL,TY,ORD,LNM,CIEN,CNAME
 S II=0
 S @DATA@(II)="I00010IEN^T00030HLOC^I00010IENCLINIEN^T00030CLIN^I00010SORTORD"_$C(30)
 S IEN=0
 F  S IEN=$O(^XTMP("BQIVHLOC",IEN)) Q:IEN=""  D
 . I $G(^SC(IEN,0))="" Q
 . S LNAME=$P(^SC(IEN,0),"^",1)
 . ; If the clinic is inactive, show it with a '*'
 . I $P($G(^SC(IEN,"I")),U,1)'="",$P($G(^SC(IEN,"I")),U,1)'>DT,$P($G(^SC(IEN,"I")),U,2)="" S LVAL("[",LNAME)=IEN Q
 . I $P($G(^SC(IEN,"I")),U,1)'="",$P($G(^SC(IEN,"I")),U,1)'>DT,$P($G(^SC(IEN,"I")),U,2)="" S LVAL(1,LNAME)=IEN Q
 . S LVAL(1,LNAME)=IEN
 ;
 S TY="",ORD=0 F  S TY=$O(LVAL(TY)) Q:TY=""  D
 . S LNM="" F  S LNM=$O(LVAL(TY,LNM)) Q:LNM=""  D
 .. S IEN=LVAL(TY,LNM),LNAME=LNM_" ("_^XTMP("BQIVHLOC",IEN)_")"
 .. S CIEN=$P(^SC(IEN,0),"^",7)
 .. I CIEN'="" S CNAME=$P(^DIC(40.7,CIEN,0),"^",1)_" ["_$P(^DIC(40.7,CIEN,0),"^",2)_"]"
 .. I TY="[" S LNAME="*"_LNAME
 .. S ORD=ORD+1
 .. S II=II+1,@DATA@(II)=IEN_"^"_LNAME_"^"_CIEN_"^"_$G(CNAME)_"^"_ORD_$C(30)
 .. K CNAME
 S II=II+1,@DATA@(II)=$C(31)
 Q
 ;
VCLN(DATA) ;
 NEW II,IEN,LNAME,LVAL,TY,ORD,LNM,CIEN,CNAME
 S II=0
 S @DATA@(II)="I00010IEN^T00030CLIN^I00010SORTORD"_$C(30)
 S IEN=0
 F  S IEN=$O(^XTMP("BQIVHLOC",IEN)) Q:IEN=""  D
 . I $G(^SC(IEN,0))="" Q
 . S CIEN=$P(^SC(IEN,0),"^",7) I CIEN="" Q
 . I CIEN'="" S CNAME=$P(^DIC(40.7,CIEN,0),"^",1)_" ["_$P(^DIC(40.7,CIEN,0),"^",2)_"]"
 . S LVAL(1,CNAME)=CIEN
 ;
 S LNM="",ORD=0 F  S LNM=$O(LVAL(1,LNM)) Q:LNM=""  D
 . S ORD=ORD+1,CIEN=LVAL(1,LNM)
 . S II=II+1,@DATA@(II)=CIEN_"^"_LNM_"^"_ORD_$C(30)
 S II=II+1,@DATA@(II)=$C(31)
 Q
 ;
VPROV(DATA) ;EP - Visit Providers
 NEW II,IEN,LNAME,LVAL,TY,ORD,LNM,TRMDT
 S II=0
 S @DATA@(II)="I00010IEN^T00040PROVIDER^I00010SORTORD"_$C(30)
 S IEN="" F  S IEN=$O(^AUPNVPRV("B",IEN)) Q:IEN=""  D
 . S TRMDT=+$P($G(^VA(200,IEN,0)),U,11),LNAME=$P(^VA(200,IEN,0),"^",1)
 . I TRMDT=0 S LVAL(1,LNAME,IEN)=IEN Q
 . I TRMDT'>DT S LVAL("[",LNAME,IEN)=IEN Q
 . I TRMDT>DT S LVAL(1,LNAME,IEN)=IEN Q
 . S LVAL(1,LNAME,IEN)=IEN
 ;
 S TY="",ORD=0 F  S TY=$O(LVAL(TY)) Q:TY=""  D
 . S LNM="" F  S LNM=$O(LVAL(TY,LNM)) Q:LNM=""  D
 .. S IEN="" F  S IEN=$O(LVAL(TY,LNM,IEN)) Q:IEN=""  D
 ... S IEN=$P(LVAL(TY,LNM,IEN),"^",1),LNAME=LNM
 ... I TY="[" S LNAME="*"_LNAME
 ... S ORD=ORD+1
 ... S II=II+1,@DATA@(II)=IEN_"^"_LNAME_"^"_ORD_$C(30)
 S II=II+1,@DATA@(II)=$C(31)
 Q
 ;
OVHLOC(DATA) ;EP - Visit Hosp Locations
 NEW II,HN,HTY
 S II=0
 S @DATA@(II)="I00010IEN^T00040HLOC^T00030TYPE^I00010SORTORD"_$C(30)
 S HN="" F  S HN=$O(^AUPNVSIT("AHL",HN)) Q:HN=""  D
 . I $G(^SC(HN,0))="" Q
 . S HTY=$P($G(^SC(HN,0)),"^",3),HNAM=$P($G(^SC(HN,0)),"^",1)
 . I HNAM="" S HNAM="DELETED CLINIC ENTRY"
 . I HTY'="" S HTY=$$GET1^DIQ(44,HN_",",2,"E")
 . S:HTY="" HTY="OTHER LOCATION"
 . S II=II+1,@DATA@(II)=HN_"^"_HNAM_"^"_HTY_$C(30)
 S II=II+1,@DATA@(II)=$C(31)
 Q
 ;
VHLOC(DATA) ;EP
 NEW II,IEN,LNAME,LVAL,TY,ORD,LNM,HTY,HNAM
 S II=0
 S @DATA@(II)="I00010IEN^T00030HLOC^T00030TYPE^I00010SORTORD"_$C(30)
 S IEN=0
 F  S IEN=$O(^XTMP("BQIVHLOC",IEN)) Q:IEN=""  D
 . I $G(^SC(IEN,0))="" Q
 . S LNAME=$P(^SC(IEN,0),"^",1)
 . ; If the clinic is inactive, show it with a '*'
 . I $P($G(^SC(IEN,"I")),U,1)'="",$P($G(^SC(IEN,"I")),U,1)'>DT,$P($G(^SC(IEN,"I")),U,2)="" S LVAL("[",LNAME)=IEN Q
 . I $P($G(^SC(IEN,"I")),U,1)'="",$P($G(^SC(IEN,"I")),U,1)'>DT,$P($G(^SC(IEN,"I")),U,2)="" S LVAL(1,LNAME)=IEN Q
 . S LVAL(1,LNAME)=IEN
 ;
 S TY="",ORD=0 F  S TY=$O(LVAL(TY)) Q:TY=""  D
 . S LNM="" F  S LNM=$O(LVAL(TY,LNM)) Q:LNM=""  D
 .. S IEN=LVAL(TY,LNM),LNAME=LNM_" ("_^XTMP("BQIVHLOC",IEN)_")"
 .. I TY="[" S LNAME="*"_LNAME
 .. S HTY=$P($G(^SC(IEN,0)),"^",3),HNAM=$P($G(^SC(IEN,0)),"^",1)
 .. I HNAM="" S HNAM="DELETED CLINIC ENTRY"
 .. I HTY'="" S HTY=$$GET1^DIQ(44,IEN_",",2,"E")
 .. S:HTY="" HTY="OTHER LOCATION"
 .. S ORD=ORD+1
 .. S II=II+1,@DATA@(II)=IEN_"^"_LNAME_"^"_HTY_"^"_ORD_$C(30)
 S II=II+1,@DATA@(II)=$C(31)
 Q
