BLRLNKU2 ;IHS/OIT/MKK - IHS LABORATORY PCC Utilities 2; 29-Mar-2023 12:55 ; MKK
 ;;5.2;IHS LABORATORY;**1039,1052,1054**;NOV 01, 1997;Build 20
 ;
 ; IHS/MSC/MKK - LR*5.2*1052 - 01-Jul-2022 - Item 86507 - File 9009022 Fix
 ; IHS/MSC/MKK - LR*5.2*1054 - 23-May-2023 - Item 95356 - Ord Loc to V Files
 ;
ADDORDL(BLRLOGDA,APCDALVR) ; EP - Add ORDERING LOCATION to APCDALVR array if missing
 NEW (BLRLOGDA,APCDALVR,BLRSS,DILOCKTM,DISYS,DT,DTIME,DUZ,IO,IOBS,IOF,IOM,ION,IOS,IOSL,IOST,IOT,IOXY,U,XPARSYS,XQXFLG)
 S ORDLOC=$$GET1^DIQ(9009022,BLRLOGDA,1106,"I")
 Q:ORDLOC<1
 ;
 S LRAS=$$GET1^DIQ(9009022,BLRLOGDA,1202)
 Q:$L(LRAS)<1
 ;
 Q:$$GETACCCP^BLRUTIL3(LRAS,.LRAA,.LRAD,.LRAN)<1
 Q:LRAA<1!(LRAD<1)!(LRAN<1)
 ;
 S ORDLOC=$$GET1^DIQ(68.02,LRAN_","_LRAD_","_LRAA,94,"I")
 Q:ORDLOC<1
 ;
 ; S:BLRSS="CH" APCDALVR("APCDTCOL")="`"_ORDLOC
 S APCDALVR("APCDTOL")="`"_ORDLOC    ; IHS/MSC/MKK - LR*5.2*1054 - Add Ord Loc to other than "CH" tests
 ;
 S FDA(9009022,BLRLOGDA_",",1106)=ORDLOC
 D UPDATE^DIE("","FDA",,"ERRS")
 Q
 ;
 ;
RDINF63(BLRLOGDA,LRAS,F60IEN,COMPDATE) ; EP - Determine if Result Date is in File 63
 ;      LRAS = Accession
 ;      F60IEN = File 60 IEN
 ;      COMPDATE is date returned, if possible.  Passed by reference.
 ;
 NEW (BLRLOGDA,LRAS,F60IEN,COMPDATE,DILOCKTM,DISYS,DT,DTIME,DUZ,IO,IOBS,IOF,IOM,ION,IOS,IOSL,IOST,IOT,IOXY,U,XPARSYS,XQXFLG)
 ; 
 Q:+$G(F60IEN)<1 0                ; Skip if no File 60 IEN
 Q:$$ISPANEL^BLRPOC(F60IEN) 0     ; Skip if Cosmic Test
 ;
 S LRSB=+$$GET1^DIQ(60,F60IEN,400,"I")
 Q:LRSB<1 0                       ; Skip if no DataName
 ;
 ; Skip if cannot break down Accession Number
 Q:$$GETACCCP^BLRUTIL3(LRAS,.LRAA,.LRAD,.LRAN)<1 0
 ;
 S LRAAIEN=LRAN_","_LRAD_","_LRAA
 S LRDFN=$$GET1^DIQ(68.02,LRAAIEN,.01,"I")
 S LRIDT=$$GET1^DIQ(68.02,LRAAIEN,13.5,"I")
 S LRSS=$$GET1^DIQ(68,LRAA,.02,"I")
 S LRSBSTR=$G(^LR(LRDFN,LRSS,LRIDT,LRSB))
 Q:$L(LRSBSTR)<1 0      ; Skip if no data in Lab Data file
 ;
 S RESULTDT=$P(LRSBSTR,U,6)
 Q:+RESULTDT<1 0     ; Skip if no LEDI IV Result Date
 ;
 S COMPDATE=RESULTDT
 ;
 ; Ignore next 2 lines -- IHS/MSC/MKK - LR*5.2*1052
 ; Q:$$GET1^DIQ(9009022,BLRLOGDA,1309,"I")
 ; Complete Date not in ^BLRTXLOG, set it
 ;
 ; ----- BEGIN IHS/MSC/MKK - LR*5.2*1052 -- Set ^BLRTXLOG Complete Date -- 
 K FDA,ERRS
 S FDA(9009022,BLRLOGDA_",",1309)=RESULTDT
 D UPDATE^DIE("","FDA",,"ERRS")
 Q 1
 ; ----- END IHS/MSC/MKK - LR*5.2*1052
