BLRPAMGE ; IHS/MSC/MKK - BLR Parameters And Mail Group Edits  ; 13-Oct-2017 14:04 ;  MKK
 ;;5.2;IHS LABORATORY;**1041,1051**;NOV 01, 1997;Build 19
 ;
 ; LR*5.2*1051 - Item CR10382 - Lab Director
 ;
EEP ; Ersatz EP
 D EEP^BLRGMENU
 Q
 ;
EP ; EP
PEP ; EP
 NEW (DILOCKTM,DISYS,DT,DTIME,DUZ,IO,IOBS,IOF,IOM,ION,IOS,IOSL,IOST,IOT,IOXY,U,XPARSYS,XQXFLG)
 ;
 D SETBLRVS
 ;
 D ADDTMENU^BLRGMENU("PARAMS^BLRPAMGE","Edit RPMS Lab Parameters ...")
 D ADDTMENU^BLRGMENU("PARADESC^BLRPAMGE","RPMS Lab Parameter's Description ...")
 D ADDTMENU^BLRGMENU("MGRPS^BLRPAMGE","Edit RPMS Lab Mail Groups ...")
 D ADDTMENU^BLRGMENU("MGRPDESC^BLRPAMGE","Mail Group's Description ...")
 ;
 D MENUDRFM^BLRGMENU("RPMS Lab","Parameters/Mail Groups")
 Q
 ;
 ; ============================= PARAMETERS MENU ==============================
 ; 
PARAMS ; EP - Edit RPMS Lab Parameters
 NEW (DILOCKTM,DISYS,DT,DTIME,DUZ,IO,IOBS,IOF,IOM,ION,IOS,IOSL,IOST,IOT,IOXY,U,XPARSYS,XQXFLG)
 ;
 D SETBLRVS
 ;
 D ADDTMENU^BLRGMENU("BLRCCMNU^BLRPAMGE","Edit BLR CC DATA parameter")
 D ADDTMENU^BLRGMENU("DETAGE^BLRPAMGE","Edit BLR AGE DETAIL parameter")
 D ADDTMENU^BLRGMENU("PEP^BLREMERA","Edit BLR EMERGENCY ALERT parameter")
 D ADDTMENU^BLRGMENU("COLDTACC^BLREMERA","Edit BLR COLL DT PCC VISIT CREATION parameter")
 D ADDTMENU^BLRGMENU("CDOBONLY^BLRPAMGE","Edit BLR DOB ONLY parameter")
 D ADDTMENU^BLRGMENU("CHRESCNG^BLRPAMGE","Edit BLR LAB RESULTS CHANGED NOTIFY parameter")
 D ADDTMENU^BLRGMENU("CHQUALRT^BLRPAMGE","Edit BLR QUALITATIVE ALERT parameter")
 D ADDTMENU^BLRGMENU("CHDYSACC^BLRPAMGE","Edit BLR DAYS TO ACCESSION parameter")
 D ADDTMENU^BLRGMENU("CHPTCONF^BLRPAMGE","Edit BLR PT CONFIRM parameter")
 D ADDTMENU^BLRGMENU("EHR80COL^BLRPAMGE","Edit BLR EHR ALL LAB TESTS COL parameter")
 D ADDTMENU^BLRGMENU("ELABDIR^BLRPAMGE","Edit IHS RPMS LAB DIRECTOR parameter")
 ;
 D MENUDRFM^BLRGMENU("RPMS Lab","Parameters")
 Q
 ;
 ; ============================= PARAMETERS EDIT ==============================
 ; 
DETAGE ; EP - Edit 'BLR AGE DETAIL' parameter
 D CHANGE^BLREMERA("BLR AGE DETAIL")
 Q
 ;
CDOBONLY ; EP - 'Change' BLR DOB ONLY parameter
 D CHANGE^BLREMERA("BLR DOB ONLY")
 Q
 ;
CHRESCNG ; EP - 'Change' BLR LAB RESULTS CHANGED NOTIFY parameter
 D CHANGE^BLREMERA("BLR LAB RESULTS CHANGED NOTIFY")
 Q
 ;
CHQUALRT ; EP - 'Change' BLR QUALITATIVE ALERT parameter
 D CHANGE^BLREMERA("BLR QUALITATIVE ALERT")
 Q
 ;
CHDYSACC ; EP - 'Change' BLR DAYS TO ACCESSION parameter
 D CHANGEN^BLRPAMGE("BLR DAYS TO ACCESSION","SYS")
 Q
 ;
CHPTCONF ; EP - 'Change' BLR PT CONFIRM parameter
 D CHANGEWE^BLRPAMGE("BLR PT CONFIRM")
 Q
 ;
BLRCCMNU ; EP - 'Change' BLR CC DATA parameter
 D CHANGEWE^BLRPAMGE("BLR CC DATA","PKG")
 Q
 ;
 ; ----- BEGIN IHS/MSC/MKK - LR*5.2*1051
EHR80COL ; EP - 'Change' BLR EHR ALL LAB TESTS COL parameter
 D CHANGEWE^BLRPAMGE("BLR EHR ALL LAB TESTS COL","PKG")
 Q
 ;
ELABDIR ; EP - 'Change' IHS RPMS LAB DIRECTOR parameter
 D CHANGEP^BLRPAMGE("IHS RPMS LAB DIRECTOR",200)
 Q
 ; ----- END IHS/MSC/MKK - LR*5.2*1051
 ;
 ; ========================= PARAMETERS DESCRIPTIONS ==========================
 ;
PARADESC ; EP - RPMS Lab Parameter's Description
 NEW (DILOCKTM,DISYS,DT,DTIME,DUZ,IO,IOBS,IOF,IOM,ION,IOS,IOSL,IOST,IOT,IOXY,U,XPARSYS,XQXFLG)
 ;
 D SETBLRVS
 ;
 D ADDTMENU^BLRGMENU("BCCDDESC^BLRPAMGE","BLR CC DATA parameter")
 D ADDTMENU^BLRGMENU("BADDESC^BLRPAMGE","BLR AGE DETAIL parameter")
 D ADDTMENU^BLRGMENU("BEADESC^BLRPAMGE","BLR EMERGENCY ALERT parameter")
 D ADDTMENU^BLRGMENU("BCDPVCDE^BLRPAMGE","BLR COLL DT PCC VISIT CREATION parameter")
 D ADDTMENU^BLRGMENU("BDOBODES^BLRPAMGE","BLR DOB ONLY parameter")
 D ADDTMENU^BLRGMENU("BLRCNDES^BLRPAMGE","BLR LAB RESULTS CHANGED NOTIFY parameter")
 D ADDTMENU^BLRGMENU("BQADESC^BLRPAMGE","BLR QUALITATIVE ALERT parameter")
 D ADDTMENU^BLRGMENU("BDTADESC^BLRPAMGE","BLR DAYS TO ACCESSION parameter")
 D ADDTMENU^BLRGMENU("BPTCDESC^BLRPAMGE","BLR PT CONFIRM parameter")
 D ADDTMENU^BLRGMENU("BLRCDESC^BLRPAMGE","BLR EHR ALL LAB TESTS COL parameter")    ; IHS/MSC/MKK - LR*5.2*1051
 D ADDTMENU^BLRGMENU("LABDDESC^BLRPAMGE","IHS RPMS LAB DIRECTOR parameter")        ; IHS/MSC/MKK - LR*5.2*1051
 ;
 D MENUDRFM^BLRGMENU("RPMS Lab","Parameter's Description")
 Q
 ;
BCCDDESC ; EP - BLR CC DATA parameter
 D SHOWDESC("BLR CC DATA",8989.51)
 Q
 ;
BADDESC ; EP - BLR AGE DETAIL parameter
 D SHOWDESC("BLR AGE DETAIL",8989.51)
 Q
 ;
BEADESC ; EP - BLR EMERGENCY ALERT parameter
 D SHOWDESC("BLR EMERGENCY ALERT",8989.51)
 Q
 ;
BCDPVCDE ; EP - BLR COLL DT PCC VISIT CREATION parameter
 D SHOWDESC("BLR COLL DT PCC VISIT CREATION",8989.51)
 Q
 ;
BDOBODES ; EP - BLR DOB ONLY parameter
 D SHOWDESC("BLR DOB ONLY",8989.51)
 Q
 ;
BLRCNDES ; EP - BLR LAB RESULTS CHANGED NOTIFY parameter
 D SHOWDESC("BLR LAB RESULTS CHANGED NOTIFY",8989.51)
 Q
 ;
BQADESC ; EP - BLR QUALITATIVE ALERT parameter
 D SHOWDESC("BLR QUALITATIVE ALERT",8989.51)
 Q
 ;
BDTADESC ; EP - BLR DAYS TO ACCESSION parameter
 D SHOWDESC("BLR DAYS TO ACCESSION",8989.51)
 Q
 ;
BPTCDESC ; EP - BLR PT CONFIRM parameter
 D SHOWDESC("BLR PT CONFIRM",8989.51)
 Q
 ;
 ; ----- BEGIN IHS/MSC/MKK - LR*5.2*1051
BLRCDESC ; EP - BLR EHR ALL LAB TESTS COL parameter
 D SHOWDESC("BLR EHR ALL LAB TESTS COL",8989.51)
 Q
 ;
LABDDESC ; EP - IHS RPMS LAB DIRECTOR parameter
 D SHOWDESC("IHS RPMS LAB DIRECTOR",8989.51)
 Q
 ; ----- END IHS/MSC/MKK - LR*5.2*1051
 ;
 ;
 ; ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ MAIL GROUPS MENU ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 ;
MGRPS ; EP - Edit RPMS Lab Mail Groups
 NEW (DILOCKTM,DISYS,DT,DTIME,DUZ,IO,IOBS,IOF,IOM,ION,IOS,IOSL,IOST,IOT,IOXY,U,XPARSYS,XQXFLG)
 ;
 D SETBLRVS
 ;
 D ADDTMENU^BLRGMENU("EDITMGRP^BLREMERA","Edit LAB HIGH URGENCY NOTIFICATION Mail Group")
 D ADDTMENU^BLRGMENU("EDITLRCM^BLRPAMGE","Edit LAB RESULTS CHANGED Mail Group")
 D ADDTMENU^BLRGMENU("EDITQALT^BLRPAMGE","Edit LAB QUALITATIVE ALERT Mail Group")
 D ADDTMENU^BLRGMENU("EDITEMRN^BLRPAMGE","Edit LAB EMERENCY ROOM NOTIFICATION Mail Group")
 D ADDTMENU^BLRGMENU("EDITLMI^BLRPAMGE","Edit LMI Mail Group")
 D ADDTMENU^BLRGMENU("EDITEROW^BLRPAMGE","Edit BLR ERROR OVERFLOW WARNING Mail Group")
 D ADDTMENU^BLRGMENU("EDITLPMR^BLRPAMGE","Edit BLR LAB PATIENT MERGE Mail Group")
 D ADDTMENU^BLRGMENU("EDITLINK^BLRPAMGE","Edit BLRLINK Mail Group")
 D ADDTMENU^BLRGMENU("EDITLMSG^BLRPAMGE","Edit LAB MESSAGING Mail Group")
 D ADDTMENU^BLRGMENU("EDITAPW^BLRPAMGE","Edit BLR APPLICATION PLUGIN WARNING Mail Group")
 D ADDTMENU^BLRGMENU("EDITLAB^BLRPAMGE","Edit LAB Mail Group")
 D ADDTMENU^BLRGMENU("EDITLABT^BLRPAMGE","Edit LAB TECHS Mail Group")
 ;
 D MENUDRFM^BLRGMENU("RPMS Lab","Mail Groups")
 Q
 ;
 ; ~~~~~~~~~~~~~~~~~~~~~~~~~~~~ MAIL GROUPS EDITS ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 ;
EDITLRCM ; EP - Edit the LAB RESULTS CHANGED Mail Group
 D MAILGRPE^BLREMERA("LAB RESULTS CHANGED")
 Q
 ;
EDITQALT ; EP - Edit the LAB QUALITATIVE ALERT Mail Group
 D MAILGRPE^BLREMERA("LAB QUALITATIVE ALERT")
 Q
 ;
EDITEMRN ; EP - Edit the LAB EMERENCY ROOM NOTIFICATION Mail Group
 D MAILGRPE^BLREMERA("LAB EMERENCY ROOM NOTIFICATION")
 Q
 ;
EDITLMI ; EP - Edit the LMI Mail Group
 D MAILGRPE^BLREMERA("LMI")
 Q
 ;
EDITAPW ; EP - Edit the BLR APPLICATION PLUGIN WARNING Mail Group
 D MAILGRPE^BLREMERA("BLR APPLICATION PLUGIN WARNING")
 Q
 ;
EDITEROW ; EP - Edit the BLR ERROR OVERFLOW WARNING Mail Group
 D MAILGRPE^BLREMERA("BLR ERROR OVERFLOW WARNING")
 Q
 ;
EDITLPMR ; EP - Edit the BLR LAB PATIENT MERGE Mail Group
 D MAILGRPE^BLREMERA("BLR LAB PATIENT MERGE")
 Q
 ;
EDITLINK ; EP - Edit the BLRLINK Mail Group
 D MAILGRPE^BLREMERA("BLRLINK")
 Q
 ;
EDITLMSG ; EP - Edit the LAB MESSAGING Mail Group
 D MAILGRPE^BLREMERA("LAB MESSAGING")
 Q
 ;
EDITLAB ; EP 0 Edit the LAB Mail Group
 D MAILGRPE^BLREMERA("LAB")
 Q
 ;
EDITLABT ; EP - Edit the LAB TECHS Mail Group
 D MAILGRPE^BLREMERA("LAB TECHS")
 Q
 ;
 ; ~~~~~~~~~~~~~~~~~~~~~~~~~ MAIL GROUPS DESCRIPTIONS ~~~~~~~~~~~~~~~~~~~~~~~~~
 ;
MGRPDESC ; EP - Mail Groups Descriptions
 NEW (DILOCKTM,DISYS,DT,DTIME,DUZ,IO,IOBS,IOF,IOM,ION,IOS,IOSL,IOST,IOT,IOXY,U,XPARSYS,XQXFLG)
 ;
 D ADDTMENU^BLRGMENU("LHUNDESC^BLRPAMGE","LAB HIGH URGENCY NOTIFICATION Mail Group")
 D ADDTMENU^BLRGMENU("LRCDESC^BLRPAMGE","LAB RESULTS CHANGED Mail Group")
 D ADDTMENU^BLRGMENU("LQADESC^BLRPAMGE","LAB QUALITATIVE ALERT Mail Group")
 D ADDTMENU^BLRGMENU("LERNDESC^BLRPAMGE","LAB EMERENCY ROOM NOTIFICATION Mail Group")
 D ADDTMENU^BLRGMENU("LMIDESC^BLRPAMGE","LMI Mail Group")
 D ADDTMENU^BLRGMENU("BEOWDESC^BLRPAMGE","BLR ERROR OVERFLOW WARNING Mail Group")
 D ADDTMENU^BLRGMENU("BLPMDESC^BLRPAMGE","BLR LAB PATIENT MERGE Mail Group")
 D ADDTMENU^BLRGMENU("LINKDESC^BLRPAMGE","BLRLINK Mail Group")
 D ADDTMENU^BLRGMENU("LMESDESC^BLRPAMGE","LAB MESSAGING Mail Group")
 D ADDTMENU^BLRGMENU("BAPWDESC^BLRPAMGE","BLR APPLICATION PLUGIN WARNING Mail Group")
 D ADDTMENU^BLRGMENU("LABDESC^BLRPAMGE","LAB Mail Group")
 D ADDTMENU^BLRGMENU("LABTDESC^BLRPAMGE","LAB TECHS Mail Group")
 ;
 D MENUDRFM^BLRGMENU("RPMS Lab","Mail Group's Description")
 Q
 ;
LHUNDESC ; EP - LAB HIGH URGENCY NOTIFICATION Mail Group
 D SHOWDESC("LAB HIGH URGENCY NOTIFICATION",3.8)
 Q
 ;
LRCDESC ; EP - LAB RESULTS CHANGED Mail Group
 D SHOWDESC("LAB RESULTS CHANGED",3.8)
 Q
 ;
LQADESC ; EP LAB QUALITATIVE ALERT Mail Group
 D SHOWDESC("LAB QUALITATIVE ALERT",3.8)
 Q
 ;
LERNDESC ; EP - LAB EMERENCY ROOM NOTIFICATION Mail Group
 D SHOWDESC("LAB EMERENCY ROOM NOTIFICATION",3.8)
 Q
 ;
LMIDESC ; EP - LMI Mail Group
 D SHOWDESC("LMI",3.8)
 Q
 ;
BEOWDESC ; EP - BLR ERROR OVERFLOW WARNING Mail Group
 D SHOWDESC("BLR ERROR OVERFLOW WARNING",3.8)
 Q
 ;
BLPMDESC ; EP - BLR LAB PATIENT MERGE Mail Group
 D SHOWDESC("BLR LAB PATIENT MERGE",3.8)
 Q
 ;
LINKDESC ; EP - BLRLINK Mail Group
 D SHOWDESC("BLRLINK",3.8)
 Q
 ;
LMESDESC ; EP - LAB MESSAGING Mail Group
 D SHOWDESC("LAB MESSAGING",3.8)
 Q
 ;
BAPWDESC ; EP - BLR APPLICATION PLUGIN WARNING Mail Group
 D SHOWDESC("BLR APPLICATION PLUGIN WARNING",3.8)
 Q
 ;
LABDESC ; EP - LAB Mail Group
 D SHOWDESC("LAB",3.8)
 Q
 ;
LABTDESC ; EP - LAB TECHS Mail Group
 D SHOWDESC("LAB TECHS",3.8)
 Q
 ;
 ;
 ; ++++++++++++++++++++++++++++++++ Procedures ++++++++++++++++++++++++++++++++
 ;
CHANGEN(PARAMETER,ENTITY) ; EP - Modify Numeric Parameter
 NEW (PARAMETER,ENTITY,DILOCKTM,DISYS,DT,DTIME,DUZ,IO,IOBS,IOF,IOM,ION,IOS,IOSL,IOST,IOT,IOXY,U,XPARSYS,XQXFLG)
 ;
 D SETBLRVS
 ;
 S HEADER(1)="RPMS Laboratory"
 S HEADER(2)=PARAMETER_" Parameter"
 S HEADER(3)=$$CJ^XLFSTR("Modify Value",IOM)
 ;
 S:$G(ENTITY)="" ENTITY="PKG"
 S RESULT=$$GET^XPAR(ENTITY,PARAMETER,1,"Q")
 ;
 D HEADERDT^BLRGMENU
 ;
 D ^XBFMK
 S DIR(0)="NO"
 S DIR("A")=PARAMETER_" Value"
 S:$L(RESULT) DIR("B")=RESULT
 D ^DIR
 ;
 I +$G(DIRUT)!($G(Y)="") D  Q
 . W !!,?4,"Invalid/No Entry/Quit. Routine Ends."
 . D PRESSKEY^BLRGMENU(9)
 ;
 S ANSWER=+$G(X)
 ;
 D EN^XPAR(ENTITY,PARAMETER,,ANSWER,.ERRS)
 ;
 I +$G(ERRS)<1 D
 . S RESULT=$$GET^XPAR(ENTITY,PARAMETER,1,"Q")
 . W !!,?4,PARAMETER," Parameter is currently ",RESULT
 . D PRESSKEY^BLRGMENU(9)
 ;
 D:+$G(ERRS)>0 RPTERR^BLREMERA(.ERRS,PARAMETER)
 ;
 Q
 ;
CHANGEWE(PARAMETER,ENTITY) ; EP - Modify Yes/No Parameter With ENTITY passed in
 NEW (PARAMETER,ENTITY,DILOCKTM,DISYS,DT,DTIME,DUZ,IO,IOBS,IOF,IOM,ION,IOS,IOSL,IOST,IOT,IOXY,U,XPARSYS,XQXFLG)
 ;
 D SETBLRVS
 ;
 S HEADER(1)="RPMS Laboratory"
 S HEADER(2)=PARAMETER_" Parameter"
 S HEADER(3)=$$CJ^XLFSTR("Modify Value",IOM)
 ;
 S:$G(ENTITY)="" ENTITY="PKG"
 S RESULT=$$GET^XPAR(ENTITY,PARAMETER,1,"Q")
 S RESULT=$S(RESULT:"YES",RESULT=0:"NO",1:"")
 ;
 D HEADERDT^BLRGMENU
 ;
 D ^XBFMK
 S DIR(0)="YO"
 S DIR("A")=PARAMETER_" (YES/NO)"
 S:$L(RESULT) DIR("B")=RESULT
 D ^DIR
 ;
 I +$G(DIRUT)!($G(Y)="") D  Q
 . W !!,?4,"Invalid/No Entry/Quit. Routine Ends."
 . D PRESSKEY^BLRGMENU(9)
 ;
 S ANSWER=$S($E($$UP^XLFSTR(X))="Y":"YES",1:"NO")
 ;
 D EN^XPAR(ENTITY,PARAMETER,,ANSWER,.ERRS)
 ;
 I +$G(ERRS)<1 D
 . S RESULT=$$GET^XPAR(ENTITY,PARAMETER,1,"Q")
 . W !!,?4,PARAMETER," Parameter is currently ",$S(RESULT:"YES",RESULT=0:"NO",1:"")
 . D PRESSKEY^BLRGMENU(9)
 ;
 D:+$G(ERRS)>0 RPTERR^BLREMERA(.ERRS,PARAMETER)
 ;
 Q
 ;
 ; ----- BEGIN IHS/MSC/MKK - LR*5.2*1051
CHANGEP(PARAMETER,FILE) ; EP - Modify Pointer Parameter
 NEW (PARAMETER,FILE,DILOCKTM,DISYS,DT,DTIME,DUZ,ENTITY,IO,IOBS,IOF,IOM,ION,IOS,IOSL,IOST,IOT,IOXY,PARAMETER,U,XPARSYS,XQXFLG)
 ;
 D SETBLRVS
 ;
 S HEADER(1)="RPMS Laboratory"
 S HEADER(2)=PARAMETER_" Parameter"
 S HEADER(3)=$$CJ^XLFSTR("Modify Value",IOM)
 ;
 D HEADERDT^BLRGMENU
 ;
 S RESULTI=$$GET^XPAR("ALL",PARAMETER)
 S RESULTE=$$GET1^DIQ(FILE,RESULTI,.01)
 ;
 D ^XBFMK
 S DIR(0)="PO^"_FILE_":MZ"
 S DIR("A")=PARAMETER_" Value"
 S:$L(RESULTE) DIR("B")=RESULTE
 D ^DIR
 ;
 I +$G(DIRUT)!($G(Y)="") D  Q
 . W !!,?4,"Invalid/No Entry/Quit. Routine Ends."
 . D PRESSKEY^BLRGMENU(9)
 ;
 S ANSWERI=+Y
 S ANSWERE=$P(Y,U,2)
 ;
 I ANSWERI=RESULTI D  Q
 . W !!,?4,"Input same as previous entry.  Routine Ends."
 . D PRESSKEY^BLRGMENU(9)
 ;
 D EN^XPAR("SYS",PARAMETER,,ANSWERE,.ERRS)
 ;
 I +$G(ERRS)<1 D
 . S RESULT=$$GET^XPAR("SYS",PARAMETER,1,"E")
 . W !!,?4,"Parameter ",PARAMETER," has been changed.",!!
 . W ?9,"Parameter is currently ",RESULT
 . D PRESSKEY^BLRGMENU(4)
 ;
 D:+$G(ERRS)>0 RPTERR^BLREMERA(.ERRS,PARAMETER)
 ;
 Q
 ; ----- END IHS/MSC/MKK - LR*5.2*1051
 ;
SHOWDESC(WOT,DICN) ; EP - Display Description
 NEW (WOT,DICN,DILOCKTM,DISYS,DT,DTIME,DUZ,IO,IOBS,IOF,IOM,ION,IOS,IOSL,IOST,IOT,IOXY,U,XPARSYS,XQXFLG)
 ;
 D SETBLRVS("SHOWDESC")
 S HEADER(1)=$S(DICN=3.8:"Mail Group Description",DICN=8989.51:"Parameter Description")
 S HEADER(2)=WOT
 S HEADER(3)=""
 D HEADERDT^BLRGMENU
 D ^XBFMK
 S DA=+$$FIND1^DIC(DICN,,"O",WOT)
 S DIC=$$GET1^DIQ(1,DICN,"GL")
 S DR=$S(DICN=3.8:2,DICN=8989.51:20)
 D EN^DIQ
 D PRESSKEY^BLRGMENU(4)
 Q
 ;
 ;
 ; ******************************** Utilities *********************************
 ;
JUSTNEW ; EP - NEW example
 NEW (DILOCKTM,DISYS,DT,DTIME,DUZ,IO,IOBS,IOF,IOM,ION,IOS,IOSL,IOST,IOT,IOXY,U,XPARSYS,XQXFLG)
 ;
 Q
 ;
SETBLRVS(TWO) ; EP - Set the BLRVERN variable(s)
 K BLRVERN,BLRVERN2
 ;
 S BLRVERN=$TR($P($T(+1),";")," ")
 S:$L($G(TWO)) BLRVERN2=TWO
 Q
