BLRP49P3 ; IHS/MSC/MKK - RPMS LOINC UPDATE Lab Patch LR*5.2*1049 Post Install Part 3 ; 19-Jan-2021 07:20 ; MKK
 ;;5.2;IHS LABORATORY;**1049**;NOV 01, 1997;Build 4
 ;
 Q
 ;
 ;
COVID19 ; EP - LOINC Data
 ;;LOINC_NUM;Shortname;Component;Property;Time_Aspct;System;Scale_Typ;Method_Typ;Class;ClassType;Long Common Name;Shortname;External_Copyright_Notice;Status;VersionFirstReleased;VersionLastChanged
 ;;82159-5;Resp path DNA+RNA Pnl Nph NAA+non-probe;Respiratory pathogens DNA & RNA panel;-;Pt;Nph;-;Non-probe.amp.tar;PANEL.MICRO;1;Respiratory pathogens DNA and RNA panel - Nasopharynx by NAA with non-probe detection;Resp path DNA+RNA Pnl Nph NAA+non-probe;;ACTIVE;2.56;2.69
 ;;94640-0;SARS-CoV-2 S gene Resp Ql NAA+probe;SARS coronavirus 2 S gene;PrThr;Pt;Respiratory;Ord;Probe.amp.tar;MICRO;1;SARS-CoV-2 (COVID-19) S gene [Presence] in Respiratory specimen by NAA with probe detection;SARS-CoV-2 S gene Resp Ql NAA+probe;;ACTIVE;2.68;
 ;;94756-4;SARS-CoV-2 N gene Resp Ql NAA N1;SARS coronavirus 2 N gene;PrThr;Pt;Respiratory;Ord;Probe.amp.tar.CDC primer-probe set N1;MICRO;1;SARS-CoV-2 (COVID-19) N gene [Presence] in Respiratory specimen by Nucleic acid amplification using CDC primer-probe set N1;SARS-CoV-2 N gene Resp Ql NAA N1;;ACTIVE;2.68;
 ;;94757-2;SARS-CoV-2 N gene Resp Ql NAA N2;SARS coronavirus 2 N gene;PrThr;Pt;Respiratory;Ord;Probe.amp.tar.CDC primer-probe set N2;MICRO;1;SARS-CoV-2 (COVID-19) N gene [Presence] in Respiratory specimen by Nucleic acid amplification using CDC primer-probe set N2;SARS-CoV-2 N gene Resp Ql NAA N2;;ACTIVE;2.68;
 ;;94761-4;SARS-CoV-2 IgG DBS Ql IA;SARS coronavirus 2 Ab.IgG;PrThr;Pt;Bld.dot;Ord;IA;MICRO;1;SARS-CoV-2 (COVID-19) IgG Ab [Presence] in DBS by Immunoassay;SARS-CoV-2 IgG DBS Ql IA;;ACTIVE;2.68;
 ;;94767-1;SARS-CoV-2 S gene SerPl Ql NAA+probe;SARS coronavirus 2 S gene;PrThr;Pt;Ser/Plas;Ord;Probe.amp.tar;MICRO;1;SARS-CoV-2 (COVID-19) S gene [Presence] in Serum or Plasma by NAA with probe detection;SARS-CoV-2 S gene SerPl Ql NAA+probe;;ACTIVE;2.68;
 ;;94822-4;SARS-CoV-2 RNA Sal Ql Seq;SARS coronavirus 2 RNA;PrThr;Pt;Saliva;Ord;Sequencing;MICRO;1;SARS-CoV-2 (COVID-19) RNA [Presence] in Saliva (oral fluid) by Sequencing;SARS-CoV-2 RNA Sal Ql Seq;;ACTIVE;2.68;
 ;;95125-1;SARS-CoV-2 IgA+IgM SerPl Ql IA;SARS coronavirus 2 Ab.IgA+IgM;PrThr;Pt;Ser/Plas;Ord;IA;MICRO;1;SARS-CoV-2 (COVID-19) IgA+IgM [Presence] in Serum or Plasma by Immunoassay;SARS-CoV-2 IgA+IgM SerPl Ql IA;;ACTIVE;2.68;
 ;;95209-3;SARS-CoV+SARS-CoV-2 Ag Resp Ql IA.rapid;SARS coronavirus+SARS coronavirus 2 Ag;PrThr;Pt;Respiratory;Ord;IA.rapid;MICRO;1;SARS-CoV+SARS-CoV-2 (COVID-19) Ag [Presence] in Respiratory specimen by Rapid immunoassay;SARS-CoV+SARS-CoV-2 Ag Resp Ql IA.rapid;;ACTIVE;2.68;
 ;;95380-2;FluAB+SARS-CoV-2+SARSr-CoV Resp NAA+prb;Influenza virus A & Influenza virus B & SARS coronavirus 2 & SARS-related coronavirus RNA panel;-;Pt;Respiratory;-;Probe.amp.tar;PANEL.MICRO;1;Influenza virus A and B and SARS-CoV-2 (COVID-19) and SARS-related CoV RNA panel - Respiratory specimen by NAA with probe detection;FluAB+SARS-CoV-2+SARSr-CoV Resp NAA+prb;;ACTIVE;2.69;
 ;;95406-5;SARS-CoV-2 RNA Nose Ql NAA+probe;SARS coronavirus 2 RNA;PrThr;Pt;Nose;Ord;Probe.amp.tar;MICRO;1;SARS-CoV-2 (COVID-19) RNA [Presence] in Nose by NAA with probe detection;SARS-CoV-2 RNA Nose Ql NAA+probe;;ACTIVE;2.68;
 ;;95409-9;SARS-CoV-2 N gene Nose Ql NAA+probe;SARS coronavirus 2 N gene;PrThr;Pt;Nose;Ord;Probe.amp.tar;MICRO;1;SARS-CoV-2 (COVID-19) N gene [Presence] in Nose by NAA with probe detection;SARS-CoV-2 N gene Nose Ql NAA+probe;;ACTIVE;2.68;
 ;;95410-7;SARS-CoV-2 NAb Titr Ser pVNT;SARS coronavirus 2 Ab.neut;Titr;Pt;Ser;Qn;pVNT;MICRO;1;SARS-CoV-2 (COVID-19) neutralizing antibody [Titer] in Serum by pVNT;SARS-CoV-2 NAb Titr Ser pVNT;;ACTIVE;2.68;
 ;;95411-5;SARS-CoV-2 NAb Ser Ql pVNT;SARS coronavirus 2 Ab.neut;PrThr;Pt;Ser;Ord;pVNT;MICRO;1;SARS-CoV-2 (COVID-19) neutralizing antibody [Presence] in Serum by pVNT;SARS-CoV-2 NAb Ser Ql pVNT;;ACTIVE;2.68;
 ;;95416-4;SARS-CoV-2 IgM DBS Ql IA;SARS coronavirus 2 Ab.IgM;PrThr;Pt;Bld.dot;Ord;IA;MICRO;1;SARS-CoV-2 (COVID-19) IgM Ab [Presence] in DBS by Immunoassay;SARS-CoV-2 IgM DBS Ql IA;;ACTIVE;2.68;
 ;;95422-2;FLUABV + SARS-CoV-2 Pnl Resp NAA+prb;Influenza virus A & Influenza virus B & SARS coronavirus 2 RNA panel;-;Pt;Respiratory;-;Probe.amp.tar;PANEL.MICRO;1;Influenza virus A and B and SARS-CoV-2 (COVID-19) RNA panel - Respiratory specimen by NAA with probe detection;FLUABV + SARS-CoV-2 Pnl Resp NAA+prb;;ACTIVE;2.69;
 ;;95423-0;FLUABV + SARS-CoV-2 Resp NAA+probe;Influenza virus A & Influenza virus B & SARS coronavirus 2 identified;Prid;Pt;Respiratory;Nom;Probe.amp.tar;MICRO;1;Influenza virus A and B and SARS-CoV-2 (COVID-19) identified in Respiratory specimen by NAA with probe detection;FLUABV + SARS-CoV-2 Resp NAA+probe;;ACTIVE;2.69;
 ;;95424-8;SARS-CoV-2 RNA Resp Ql Seq;SARS coronavirus 2 RNA;PrThr;Pt;Respiratory;Ord;Sequencing;MICRO;1;SARS-CoV-2 (COVID-19) RNA [Presence] in Respiratory specimen by Sequencing;SARS-CoV-2 RNA Resp Ql Seq;;ACTIVE;2.69;
 ;;95425-5;SARS-CoV-2 N gene Sal Ql NAA+probe;SARS coronavirus 2 N gene;PrThr;Pt;Saliva;Ord;Probe.amp.tar;MICRO;1;SARS-CoV-2 (COVID-19) N gene [Presence] in Saliva (oral fluid) by NAA with probe detection;SARS-CoV-2 N gene Sal Ql NAA+probe;;ACTIVE;2.69;
 ;;95427-1;SARS-CoV-2 IgA Titr SerPl IF;SARS coronavirus 2 Ab.IgA;Titr;Pt;Ser/Plas;Qn;IF;MICRO;1;SARS-CoV-2 (COVID-19) IgA Ab [Titer] in Serum or Plasma by Immunofluorescence;SARS-CoV-2 IgA Titr SerPl IF;;ACTIVE;2.69;
 ;;95428-9;SARS-CoV-2 IgM Titr SerPl IF;SARS coronavirus 2 Ab.IgM;Titr;Pt;Ser/Plas;Qn;IF;MICRO;1;SARS-CoV-2 (COVID-19) IgM Ab [Titer] in Serum or Plasma by Immunofluorescence;SARS-CoV-2 IgM Titr SerPl IF;;ACTIVE;2.69;
 ;;95429-7;SARS-CoV-2 IgG Titr SerPl IF;SARS coronavirus 2 Ab.IgG;Titr;Pt;Ser/Plas;Qn;IF;MICRO;1;SARS-CoV-2 (COVID-19) IgG Ab [Titer] in Serum or Plasma by Immunofluorescence;SARS-CoV-2 IgG Titr SerPl IF;;ACTIVE;2.69;
 ;;95521-1;SARS-CoV-2 N gene # Resp NAA+probe;SARS coronavirus 2 N gene;NCnc;Pt;Respiratory;Qn;Probe.amp.tar;MICRO;1;SARS-CoV-2 (COVID-19) N gene [#/volume] (viral load) in Respiratory specimen by NAA with probe detection;SARS-CoV-2 N gene # Resp NAA+probe;;ACTIVE;2.69;
 ;;95522-9;SARS-CoV-2 N gene Resp NAA+probe-Log#;SARS coronavirus 2 N gene;LnCnc;Pt;Respiratory;Qn;Probe.amp.tar;MICRO;1;SARS-CoV-2 (COVID-19) N gene [Log #/volume] (viral load) in Respiratory specimen by NAA with probe detection;SARS-CoV-2 N gene Resp NAA+probe-Log#;;ACTIVE;2.69;
 ;;95542-7;SARS-CoV-2 IgG+IgM SerPlBld Ql IA.rapid;SARS coronavirus 2 Ab.IgG+IgM;PrThr;Pt;Ser/Plas/Bld;Ord;IA.rapid;MICRO;1;SARS-CoV-2 (COVID-19) IgG+IgM Ab [Presence] in Serum, Plasma or Blood by Rapid immunoassay;SARS-CoV-2 IgG+IgM SerPlBld Ql IA.rapid;;ACTIVE;2.69;
 ;;95608-6;SARS-CoV-2 RNA Resp Ql NAA+non-probe;SARS coronavirus 2 RNA;PrThr;Pt;Respiratory;Ord;Non-probe.amp.tar;MICRO;1;SARS-CoV-2 (COVID-19) RNA [Presence] in Respiratory specimen by NAA with non-probe detection;SARS-CoV-2 RNA Resp Ql NAA+non-probe;;ACTIVE;2.69;
 ;;95609-4;SARS-CoV-2 S gene Resp Ql Seq;SARS coronavirus 2 S gene;PrThr;Pt;Respiratory;Ord;Sequencing;MICRO;1;SARS-CoV-2 (COVID-19) S gene [Presence] in Respiratory specimen by Sequencing;SARS-CoV-2 S gene Resp Ql Seq;;ACTIVE;2.69;
 ;;95823-1;SARS-rel CoV E gene Sal Ql NAA+probe;SARS-related coronavirus E gene;PrThr;Pt;Saliva;Ord;Probe.amp.tar;MICRO;1;SARS-related coronavirus E gene [Presence] in Saliva (oral fluid) by NAA with probe detection;SARS-rel CoV E gene Sal Ql NAA+probe;;ACTIVE;2.69;
 ;;95824-9;SARS-CoV-2 ORF1ab Sal Ql NAA+probe;SARS coronavirus 2 ORF1ab region;PrThr;Pt;Saliva;Ord;Probe.amp.tar;MICRO;1;SARS-CoV-2 (COVID-19) ORF1ab region [Presence] in Saliva (oral fluid) by NAA with probe detection;SARS-CoV-2 ORF1ab Sal Ql NAA+probe;;ACTIVE;2.69;
 ;;95825-6;SARS-CoV-2 Ab DBS Ql IA;SARS coronavirus 2 Ab;PrThr;Pt;Bld.dot;Ord;IA;MICRO;1;SARS-CoV-2 (COVID-19) Ab [Presence] in DBS by Immunoassay;SARS-CoV-2 Ab DBS Ql IA;;ACTIVE;2.69;
 ;;95826-4;SARS-CoV-2 RNA Pnl Sal NAA+probe;SARS coronavirus 2 RNA panel;-;Pt;Saliva;-;Probe.amp.tar;PANEL.MICRO;1;SARS-CoV-2 (COVID-19) RNA panel - Saliva (oral fluid) by NAA with probe detection;SARS-CoV-2 RNA Pnl Sal NAA+probe;;ACTIVE;2.69;
 ;;95941-1;FLUABV+SARS-CoV-2+RSV Pnl Resp NAA+probe;Influenza virus A & Influenza virus B & SARS coronavirus 2 & Respiratory syncytial virus RNA panel;-;Pt;Respiratory;-;Probe.amp.tar;PANEL.MICRO;1;Influenza virus A and B and SARS-CoV-2 (COVID-19) and Respiratory syncytial virus RNA panel - Respiratory specimen by NAA with probe detection;FLUABV+SARS-CoV-2+RSV Pnl Resp NAA+probe;;ACTIVE;2.69;
 ;;95942-9;FLUABV+SARS-CoV Ag Pnl Up resp IA.rapid;Influenza virus A & Influenza virus B & SARS coronavirus+SARS coronavirus 2 Ag panel;-;Pt;Respiratory.upper;-;IA.rapid;PANEL.MICRO;1;Influenza virus A and B and SARS-CoV+SARS-CoV-2 (COVID-19) Ag panel - Upper respiratory specimen by Rapid immunoassay;FLUABV+SARS-CoV Ag Pnl Up resp IA.rapid;;ACTIVE;2.69;
 ;;95970-0;SARS-CoV-2 TCRB Bld Ql Seq;SARS coronavirus 2 specific TCRB gene rearrangements;PrThr;Pt;Bld;Ord;Sequencing;MICRO;1;SARS-CoV-2 (COVID-19) specific TCRB gene rearrangements [Presence] in Blood by Sequencing;SARS-CoV-2 TCRB Bld Ql Seq;;ACTIVE;2.69;
 ;;95971-8;SARS-CoV-2 IFN-g Bld Ql;SARS coronavirus 2 stimulated gamma interferon;PrThr;Pt;Bld;Ord;;MICRO;1;SARS CoV-2 stimulated gamma interferon [Presence] in Blood;SARS-CoV-2 IFN-g Bld Ql;;ACTIVE;2.69;
 ;;95972-6;SARS CoV-2 IFN-g Tcel bkgrd cor Bld-aCnc;SARS coronavirus 2 stimulated gamma interferon release by T-cells (corrected for background);ACnc;Pt;Bld;Qn;;MICRO;1;SARS CoV-2 stimulated gamma interferon release by T-cells [Units/volume] corrected for background in Blood;SARS CoV-2 IFN-g Tcel bkgrd cor Bld-aCnc;;ACTIVE;2.69;
 ;;95973-4;SARS CoV-2 IFN-g T cells Bld-aCnc;SARS coronavirus 2 stimulated gamma interferon release by T-cells;ACnc;Pt;Bld;Qn;;MICRO;1;SARS CoV-2 stimulated gamma interferon release by T-cells [Units/volume] in Blood;SARS CoV-2 IFN-g T cells Bld-aCnc;;ACTIVE;2.69;
 ;;95974-2;SARS-CoV-2 IFN-g Pnl Bld;SARS coronavirus 2 stimulated gamma interferon panel;-;Pt;Bld;-;;PANEL.MICRO;1;SARS CoV-2 stimulated gamma interferon panel - Blood;SARS-CoV-2 IFN-g Pnl Bld;;ACTIVE;2.69;
 ;;96091-4;SARS-CoV-2 RdRp Sal Ql NAA+probe;SARS coronavirus 2 RdRp gene;PrThr;Pt;Saliva;Ord;Probe.amp.tar;MICRO;1;SARS-CoV-2 (COVID-19) RdRp gene [Presence] in Saliva (oral fluid) by NAA with probe detection;SARS-CoV-2 RdRp Sal Ql NAA+probe;;ACTIVE;2.69;
 ;;96094-8;SARS-CoV-2+SARSr-CoV pnl Resp NAA+probe;SARS coronavirus 2 & SARS-related coronavirus RNA panel;-;Pt;Respiratory;-;Probe.amp.tar;PANEL.MICRO;1;SARS-CoV-2 (COVID-19) and SARS-related CoV RNA panel - Respiratory specimen by NAA with probe detection;SARS-CoV-2+SARSr-CoV pnl Resp NAA+probe;;ACTIVE;2.69;
 ;;96118-5;SARS-CoV-2 Ab Pnl DBS IA;SARS coronavirus 2 Ab panel;-;Pt;Bld.dot;-;IA;PANEL.MICRO;1;SARS-CoV-2 (COVID-19) Ab panel - DBS by Immunoassay;SARS-CoV-2 Ab Pnl DBS IA;;ACTIVE;2.69;
 ;;96119-3;SARS-CoV-2 Ag Upper resp Ql IA;SARS coronavirus 2 Ag;PrThr;Pt;Respiratory.upper;Ord;IA;MICRO;1;SARS-CoV-2 (COVID-19) Ag [Presence] in Upper respiratory specimen by Immunoassay;SARS-CoV-2 Ag Upper resp Ql IA;;ACTIVE;2.69;
 ;;96120-1;SARS-CoV-2 RdRp Lower resp Ql NAA+probe;SARS coronavirus 2 RdRp gene;PrThr;Pt;Respiratory.lower;Ord;Probe.amp.tar;MICRO;1;SARS-CoV-2 (COVID-19) RdRp gene [Presence] in Lower respiratory specimen by NAA with probe detection;SARS-CoV-2 RdRp Lower resp Ql NAA+probe;;ACTIVE;2.69;
 ;;96121-9;SARS-rel CoV E gene Low resp Ql NAA+prb;SARS-related coronavirus E gene;PrThr;Pt;Respiratory.lower;Ord;Probe.amp.tar;MICRO;1;SARS-related coronavirus E gene [Presence] in Lower respiratory specimen by NAA with probe detection;SARS-rel CoV E gene Low resp Ql NAA+prb;;ACTIVE;2.69;
 ;;96122-7;SARS-rel CoV E gene Upper resp Ql NAA+prb;SARS-related coronavirus E gene;PrThr;Pt;Respiratory.upper;Ord;Probe.amp.tar;MICRO;1;SARS-related coronavirus E gene [Presence] in Upper respiratory specimen by NAA with probe detection;SARS-rel CoV E gene Upper resp Ql NAA+prb;;ACTIVE;2.69;
 ;;96123-5;SARS-CoV-2 RdRp Upper resp Ql NAA+probe;SARS coronavirus 2 RdRp gene;PrThr;Pt;Respiratory.upper;Ord;Probe.amp.tar;MICRO;1;SARS-CoV-2 (COVID-19) RdRp gene [Presence] in Upper respiratory specimen by NAA with probe detection;SARS-CoV-2 RdRp Upper resp Ql NAA+probe;;ACTIVE;2.69;
 ;;96448-6;SARS-CoV-2 N gene Sal Ql NAA N1;SARS coronavirus 2 N gene;PrThr;Pt;Saliva;Ord;Probe.amp.tar.CDC primer-probe set N1;MICRO;1;SARS-CoV-2 (COVID-19) N gene [Presence] in Saliva (oral fluid) by Nucleic acid amplification using CDC primer-probe set N1;SARS-CoV-2 N gene Sal Ql NAA N1;;ACTIVE;2.69;
 ;;96603-6;SARS-CoV-2 S RBD NAb SerPl Ql IA;SARS coronavirus 2 spike protein RBD Ab.neut;PrThr;Pt;Ser/Plas;Ord;IA;MICRO;1;SARS-CoV-2 (COVID-19) S protein RBD neutralizing antibody [Presence] in Serum or Plasma by Immunoassay;SARS-CoV-2 S RBD NAb SerPl Ql IA;;ACTIVE;2.69;
 ;;96741-4;SARS-CoV-2 variant Spec Seq;SARS coronavirus 2 variant;Type;Pt;XXX;Nom;Sequencing;MICRO;1;SARS-CoV-2 (COVID-19) variant [Type] in Specimen by Sequencing;SARS-CoV-2 variant Spec Seq;;ACTIVE;;
 ;;96742-2;SARS-CoV-2 IgG SerPl IA-mCnc;SARS coronavirus 2 Ab.IgG;MCnc;Pt;Ser/Plas;Qn;IA;MICRO;1;SARS-CoV-2 (COVID-19) IgG Ab [Mass/volume] in Serum or Plasma by Immunoassay;SARS-CoV-2 IgG SerPl IA-mCnc;;ACTIVE;;
 ;;$$END
