BMCRPC5 ; IHS/CAS/AU - GUI REFERRED CARE INFO SYSTEM (4/4);     
 ;;4.0;REFERRED CARE INFO SYSTEM;**11,12,31**;JAN 09, 2006;Build 168
 ;
 ;GDIT/HS/BEE 10/19/17 - p12 CR#5450:Added BMC PRINT REFERRAL RPC call (tag PRINT)
 ;GDIT/HS/BEE 10/19/17 - p12 - Address XINDEX/SAC issues
 ;
 ; RPC code for RCIS GUI Application
 ; Routines contains code for saving Business office and Medical History/Finding in RCIS Referral table.
 ;SETWP(FN,WPFN,IEN,NOTES,ISAPPEND,ISDELETE) ;Set WordProcessing Data based on file, field and IEN information!
 ;S FileNumber=$G(FN),WpFieldNumber=$G(WPFN),RowId=$G(IEN),Notes=$G(NOTES),IsAppend=$G(ISAPPEND),IsDelete=$G(ISDELETE)
 ;I +$G(RowId)<1,+$G(FileNumber)<1,+$G(WpFieldNumber)<1,$L($G(Notes))<1 Q "0^Required Data missing"
 ;I $G(Notes)["2@%Library.GlobalBinaryStream" Q "-2^GlobalBinaryStream error"
 ;N err,wproot,wp,i,OrigCharCount,RunningCharCount
 ;S OrigCharCount=$L($G(Notes))
 ;I IsDelete S wproot="@"
 ;I 'IsDelete  D
 ;. S Notes=$LISTFROMSTRING(Notes,$c(13))
 ;. S wproot="wp",i=0,RunningCharCount=0
 ;. F i=1:1:$ll(Notes) S wp(i)=$lg(Notes,i)
 ;I IsAppend D WP^DIE(FileNumber,RowId_",",WpFieldNumber,"AK",wproot,"err")
 ;I 'IsAppend D WP^DIE(FileNumber,RowId_",",WpFieldNumber,"K",wproot,"err")
 ;I $D(err) Q "-1^"_$G(err("DIERR",1,"TEXT",1))
 ;K err,wproot,wp,i,OrigCharCount,RunningCharCount,Notes,RowId,FileNumber,WpFieldNumber
 ;Q "1"
SETWP(FILENUM,WPFLDNM,ROWID,NOTES,ISAPPEND,ISDELETE) ;EP Set WordProcessing Data based on file, field and IEN information
 ;
 NEW ERR,WPROOT,WP,II
 ;
 S ISAPPEND=$G(ISAPPEND),ISDELETE=$G(ISDELETE)
 ;
 ;Input checking
 I (+$G(ROWID)<1)!(+$G(FILENUM)<1)!(+$G(WPFLDNM)<1)!($L($G(NOTES))<1) Q "0^Required Data missing"
 I NOTES["2@%Library.GlobalBinaryStream" Q "-2^GlobalBinaryStream error"
 ;
 ;Deletes
 I ISDELETE S WPROOT="@"
 ;
 ;Format Add/Appends
 I 'ISDELETE  D
 . S WPROOT="WP"
 . F II=1:1:$L(NOTES,"~") S WP(II)=$P(NOTES,"~",II)
 ;
 ;Add/Append/Delete
 I ISAPPEND D WP^DIE(FILENUM,ROWID_",",WPFLDNM,"AK",WPROOT,"ERR")
 I 'ISAPPEND D WP^DIE(FILENUM,ROWID_",",WPFLDNM,"K",WPROOT,"ERR")
 I $D(ERR) Q "-1^"_$G(ERR("DIERR",1,"TEXT",1))
 Q "1"
 ;
 ;GDIT/HS/BEE 10/19/17 - p12 CR#5450;Added PRINT and GETRPT tags
PRINT(ROOT,BMCREF,BMCPCSE) ;EP RPC - BMC PRINT REFERRAL
 ;
 ;This tag is called by the BMC PRINT REFERRAL RPC call - It returns a formatted
 ;STANDARD IHS REFERRAL LETTER for a passed in referral number
 ;
 ;Input: BMCREF - Pointer to RCIS REFERRAL entry
 ;
 ;Reset output and define root
 K ^TMP("BMCDATA",$J)
 S ROOT=$NA(^TMP("BMCDATA",$J,1))
 ;
 ;Compile the report
 S:$G(BMCPCSE)="" BMCPCSE=""
 D GETRPT(.ROOT,BMCREF,BMCPCSE)
 Q
 ;
UPENVREF(VREFIEN,SNMDCT,ENTEREDBY,PROBLEM) ;Updating V_Referral file
 N OUT,FDA,ERR1,RSLT
 I '$D(VREFIEN) S RSLT="~`0^V Referral Ien is not provided" Q RSLT
 I VREFIEN'>0 S RSLT="~`0^V Referral Ien is not provided" Q RSLT
 I '$D(SNMDCT) S RSLT="~`0^SNOMED CT is not provided" Q RSLT
 I SNMDCT'>0 S RSLT="~`0^SNOMED CT is not provided" Q RSLT
 I ($$GET1^DIQ(9000010.59,VREFIEN_",",.01,"")=$G(SNMDCT))&($$GET1^DIQ(9000010.59,VREFIEN_",",.04,"I")=$G(PROBLEM)) S RSLT="~`1^" Q RSLT
 S FDA(9000010.59,VREFIEN_",",.01)=$G(SNMDCT)
 I $G(PROBLEM)'="" S FDA(9000010.59,VREFIEN_",",.04)=$G(PROBLEM)
 I $G(PROBLEM)="" S FDA(9000010.59,VREFIEN_",",.04)="@"
 S FDA(9000010.59,VREFIEN_",",1218)=$$NOW^XLFDT
 S FDA(9000010.59,VREFIEN_",",1219)=$G(ENTEREDBY)
 D FILE^DIE("","FDA","ERR1")
 I $D(ERR1("DIERR")) S RSLT="~`0^Error updating referral:"_$G(ERR1("DIERR","1","TEXT",1)) Q RSLT
 S RSLT="~`1^"
 Q RSLT
 ;
GETRPT(DATA,BMCREF,BMCPCSE) ;Retrieve the referral letter
 NEW II
 S DATA=$$TMPGBL^CIAVMRPC
 I '$G(BMCREF) S @DATA@(1)="A referral has not been selected." Q
 D CAPTURE^CIAUHFS("D GPRINT^BMCFPRN(BMCREF,BMCPCSE)",DATA,80)
 S:'$D(@DATA) @DATA@(1)="No referral information was found."
 ;
 ;Append CR/LF to end of each line
 S II="" F  S II=$O(@DATA@(II)) Q:II=""  S @DATA@(II)=@DATA@(II)_$C(13)_$C(10)
 Q
 ;
SAVERD(RST,CODE,DESC,PATIEN,REFIEN,TYPE,PRISEC) ;EP - Save RCIS Diagnosis
 ;Test Call: W $$SAVERD^BMCRPC5("C7A.094","Microaneurysm of right retinal artery1","18896","135286")
 N PNIEN,RDARRAY,OUT,ICDIEN
 I $G(DESC)="" S RST="~`0^Provider Narrative is missing!" Q RST
 S PNIEN=$$INSRTPN(DESC),CODE=$P($G(CODE),"|",1)
 I +PNIEN=0 S RST="~`0^Error in saving Provider Narrative!" Q RST
 I $G(CODE)="" S RST="~`0^ICD Code is missing" Q RST
 D LIST^DIC(80,"","@;.01","Q",1,$E(CODE,1,$L(CODE)-1),CODE,,,,"OUT")
 S ICDIEN=$G(OUT("DILIST",2,1))
 I +ICDIEN'>0 S RST="~`0^ICD DIAGNOSIS:"_CODE_" not found!" Q RST
 S TYPE=$S($G(TYPE)="FINAL":"F",$G(TYPE)="PROVISIONAL":"P",1:"P")
 S PRISEC=$S($G(PRISEC)="SECONDARY":"S",$G(PRISEC)="PRIMARY":"P",1:"P")
 S RDARRAY(.01)=ICDIEN,RDARRAY(.02)=PATIEN,RDARRAY(.03)=REFIEN,RDARRAY(.04)=TYPE,RDARRAY(.05)=PRISEC,RDARRAY(.06)=PNIEN
 D DXA^BMCAPI2(REFIEN,.RDARRAY) ;Add Diagnosis API
 Q "~`1^"
 ;
EDITRD(RST,PATIEN,REFIEN,DXS,RDCODE,RDNAR) ;EP - Edit RCIS Diagnosis
 N RDIEN,DX,LOOP,K,SAVE,C,D,T,PS
 S RDIEN=$O(^BMCDX("AD",REFIEN,""))
 ;Delete all existing Dxs
 I +RDIEN>0 F  D  Q:(+RDIEN'>0)
 .S DIK="^BMCDX(",DA=RDIEN
 .D ^DIK
 .S RDIEN=$O(^BMCDX("AD",REFIEN,RDIEN))
 S LOOP=$P(DXS,"`~",1),SAVE=1
 I +LOOP<=0 D SAVERD(.RST,$G(RDCODE),$G(RDNAR),PATIEN,REFIEN,"","") Q "~`1"
 S DXS=$P(DXS,"`~",2)
 F K=1:1:LOOP  D
 .S DX=$P(DXS,"~",K),C=$P(DX,"^",2),D=$P(DX,"^",3),T=$P(DX,"^",4),PS=$P(DX,"^",5)
 .I $G(RDCODE)=C S SAVE=0 ;New Dx
 .D SAVERD(.RST,C,D,PATIEN,REFIEN,T,PS)
 I SAVE D SAVERD(.RST,RDCODE,RDNAR,PATIEN,REFIEN,"","")
 I $P($G(RST),"^")="~`0" Q RST
 Q "~`1"
 ;
INSRTPN(DESC) ;EP - Save/Return Provider Narrative
 N NFDA,NFDAIEN,NERR1,NRTIVIEN,DESCIDX
 K OUT,ERR
 ;S NRTIVIEN=$$FIND1^DIC(9999999.27,"","BQX",DESC,"B") ;Check if PN exists already
 ;I +NRTIVIEN>0 Q NRTIVIEN
 ;S DESC="Paroxysmal atrial fibrillation"
 S SCR="I 1"_" & (($P($G("_"^"_"(0)),""^"",1))="""_$G(DESC)_""")",DESCIDX=$E(DESC,1,30)
 D LIST^DIC(9999999.27,"","@;.01","QK","*",$E(DESCIDX,1,($L(DESCIDX)-1)),$E(DESCIDX,1,30),"B",SCR,,"OUT","ERR")
 I $G(OUT("DILIST",2,1))'="" Q OUT("DILIST",2,1)
 S NFDA(9999999.27,"+1,",.01)=DESC
 D UPDATE^DIE("","NFDA","NFDAIEN","NERR1")
 I $D(NERR1("DIERR")) Q "~`0^Error adding Diagnosis Narrative: "_$G(NERR1("DIERR","1","TEXT",1))
 S NRTIVIEN=$G(NFDAIEN(1))
 Q NRTIVIEN
 ;
CRENVREF(RTN,SNMDCT,SNMDPT,PATIENT,VISIT,PROBLEM,RREFIEN,EVENTDT,OPROVIDER,CLINIC,ENCPROVIDER,PARENT,OUTSIDEPROV,ORDERINGLOC,DTENTERED,ENTEREDBY) ;;Create Entry in V_Referral 
 ; RRIEN = RCIS Feferral IEN
 ; PRTXDATE = DATE TIME PRINTED OR TRANSMITTED FILE for example May 16, 2013
 ; PRTXBY = PRINTED-TRANSMITTED BY (IEN of NEW PERSON (200) File)
 ; DOCTYPE = Accept Set Of Code Internal Format only C32, CP or CT
 ; CCDADOCID = Free text
 ; RSLT=IEN of entry created in 600 (TRANSITION OF CARE DOCUMENT) multiple
 K FDA,FDAMSG1,FDAIEN1
 N FDADA1
 S FDA(9000010.59,"+1,",.01)=$G(SNMDCT)
 S FDA(9000010.59,"+1,",.02)=$G(PATIENT)
 S FDA(9000010.59,"+1,",.03)=$G(VISIT)
 S FDA(9000010.59,"+1,",.04)=$G(PROBLEM)
 S FDA(9000010.59,"+1,",.06)=$G(RREFIEN)
 S FDA(9000010.59,"+1,",1201)=$G(EVENTDT)
 S FDA(9000010.59,"+1,",1202)=$G(OPROVIDER)
 S FDA(9000010.59,"+1,",1204)=$G(ENCPROVIDER)
 S FDA(9000010.59,"+1,",1208)=$G(PARENT)
 S FDA(9000010.59,"+1,",1210)=$G(OUTSIDEPROV)
 S FDA(9000010.59,"+1,",1215)=$G(ORDERINGLOC)
 S FDA(9000010.59,"+1,",1216)=DTENTERED
 S FDA(9000010.59,"+1,",1217)=$G(ENTEREDBY)
 S FDA(9000010.59,"+1,",1218)=DTENTERED
 S FDA(9000010.59,"+1,",1219)=$G(ENTEREDBY)
 D UPDATE^DIE("","FDA","FDAIEN1","FDAMSG1")
 S FDADA1=+$G(FDAIEN1(1))
 I $D(FDAMSG1) D
 . W !!,"The following error message was returned:",!!
 . S FDAMSG1="" F  S FDAMSG1=$O(FDAMSG1("DIERR",1,"TEXT",FDAMSG1)) Q:FDAMSG1=""  W FDAMSG1("DIERR",1,"TEXT",FDAMSG1),!
 I $G(FDADA1)=""  S RTN=$G(FDAMSG1) Q
 S RTN=$G(FDADA1)
 Q RTN
 ;
CHKDUP(NRPAT,NRTYPE,NRPRV,NRVEN,NRIO,NRPRI) ;EP FR BMCADD;CHECKDUP PATIENT ;BMC*4.0*16
 ;CRITERIA:PATIENT-.03,REF TYPE-.04(BMCRTYPE),REF PROV-.06,VENDOR-.07,PRIORITY-.32,VISIT TYPE-.14(BMCRIO)
 N BMCTPRV,BMCTVEN,BMCTPRI,BMCRTYPE,BMCRIO,BMCDUP,BMCTDT,BMCDFN,BMCTIEN,BMCREFN
 S BMCDUP=0,X1=DT,X2=-365 D C^%DTC S BMCTDT=X
 S BMCTPRV=NRPRV,BMCTVEN=NRVEN,BMCTPRI=NRPRI,BMCRTYPE=NRTYPE,BMCRIO=NRIO,BMCDFN=NRPAT
 F  S BMCTDT=$O(^BMCREF("AA",BMCDFN,BMCTDT)) Q:BMCTDT'?1N.N  D
 .S BMCTIEN=0 F  S BMCTIEN=$O(^BMCREF("AA",BMCDFN,BMCTDT,BMCTIEN)) Q:BMCTIEN'?1N.N  D
 ..;Q:BMCTIEN=BMCRIEN
 ..S BMCREFN=$P(^BMCREF(BMCTIEN,0),U,2)
 ..Q:BMCRTYPE'=$P(^BMCREF(BMCTIEN,0),U,4)
 ..Q:BMCTPRV'=$P(^BMCREF(BMCTIEN,0),U,6)
 ..Q:BMCTVEN'=$P(^BMCREF(BMCTIEN,0),U,7)
 ..Q:BMCRIO'=$P(^BMCREF(BMCTIEN,0),U,14)
 ..Q:BMCTPRI'=$P(^BMCREF(BMCTIEN,0),U,32)
 ..;S BMCDUP(BMCTIEN)="",
 ..S BMCDUP=BMCDUP+1
 I $G(BMCDUP)>=1 Q $G(BMCREFN)
 Q 0
 ;
SETACKDT(RSLT,REFIEN,ACKDT) ;BMC ACKNOWLEDGE DT UPDATE
 N ACKDATE,RRIEN
 I $G(REFIEN)="" S RSLT="~`0^Manadatory Data Missing!"
 I $O(^BMCREF(REFIEN,6,"B","")) S RRIEN=$O(^BMCREF(REFIEN,6,"B",$O(^BMCREF(REFIEN,6,"B",""),-1),""))
 K FDA,ERR1
 ;S ACKDT="02/02/2024@12:07"
 S ACKDATE=$P($G(ACKDT),"@",1)
 D DT^DILF("",ACKDATE,.ACKDATE) I ACKDATE="-1" S ACKDATE=""
 I $G(ACKDATE)="" S RSLT="~`0^Manadatory Data Missing!"
 I $G(ACKDATE)'="" S ACKDATE=$G(ACKDATE)_"."_$TR($P($G(ACKDT),"@",2),":","")
 S FDA(90001.6,RRIEN_","_REFIEN_",",.03)=$G(ACKDATE) D FILE^DIE("","FDA","ERR1")
 I $D(ERR1("DIERR")) S RSLT="~`0^Error updating Acknowledge Date: "_$G(ERR1("DIERR","1","TEXT",1)) Q RSLT
 S RSLT="~`1^"
 Q RSLT
 ;
GTREFDT ;Moving code from BMCRPC1 to BMCRPC5 due to XINDEX size restriction
 K ^TMP($J)
 N OUT,OUT1,OUT2,OUT3,OUT4,ICDIEN,ICDCAT,ICDACTDT,ICDINADT,CPTIEN,CPTCAT,PRPIEN,PRPTXT,I,PIECE,RSCODE,RSDESC,SCR,MPIEN,PRIORITY
 S ^TMP($J,"PRNRCRF",1)="~`" ;; RCIS ICD DIAGNOSTIC CATEGORY
 S ^TMP($J,"PRNRCRF",2)="~`" ;; RCIS CPT PROCEDURE CATEGORY
 S ^TMP($J,"PRNRCRF",3)="~`" ;; RCIS PURPOSE TEXT LIST
 S ^TMP($J,"PRNRCRF",4)="~`" ;; RCIS STATUS OF REFERRAL LIST
 S ^TMP($J,"PRNRCRF",5)="~`" ;; RCIS PRIORITY LIST
 D LIST^DIC(90001.51,"","@;.01","","*",,,"",,"","OUT")
 S INDEX=$O(OUT("DILIST","ID",0))
 I +INDEX>0 F  D  Q:(+INDEX'>0)
 .S ICDIEN=$G(OUT("DILIST",2,INDEX))
 .S ICDCAT=$G(OUT("DILIST","ID",INDEX,".01"))
 .S ICDACTDT=$$GET1^DIQ(90001.51,$G(ICDIEN)_",",.02,"")
 .S ICDINADT=$$GET1^DIQ(90001.51,$G(ICDIEN)_",",.03,"")
 .S ^TMP($J,"PRNRCRF",1)=$G(^TMP($J,"PRNRCRF",1))_ICDIEN_"^"_ICDCAT_"^"_ICDACTDT_"^"_ICDINADT_"~"
 .S INDEX=$O(OUT("DILIST","ID",INDEX))
 D LIST^DIC(90001.52,"","@;.01","","*",,,"",,"","OUT1")
 S INDEX=$O(OUT1("DILIST","ID",0))
 I +INDEX>0 F  D  Q:(+INDEX'>0)
 .S CPTIEN=$G(OUT1("DILIST",2,INDEX))
 .S CPTCAT=$G(OUT1("DILIST","ID",INDEX,".01"))
 .S ^TMP($J,"PRNRCRF",2)=$G(^TMP($J,"PRNRCRF",2))_CPTIEN_"^"_CPTCAT_"~"
 .S INDEX=$O(OUT1("DILIST","ID",INDEX))
 D LIST^DIC(90001.58,"","@;.01","","*",,,"",,"","OUT2")
 S INDEX=$O(OUT2("DILIST","ID",0))
 I +INDEX>0 F  D  Q:(+INDEX'>0)
 .S PRPIEN=$G(OUT2("DILIST",2,INDEX))
 .S PRPTXT=$G(OUT2("DILIST","ID",INDEX,".01"))
 .S ^TMP($J,"PRNRCRF",3)=$G(^TMP($J,"PRNRCRF",3))_PRPIEN_"^"_PRPTXT_"~"
 .S INDEX=$O(OUT2("DILIST","ID",INDEX))
 S OUT3=$P($G(^DD(90001,.15,0)),"^",3)
 S PIECE=$P($G(OUT3),";"),I=1
 I PIECE'="" F  D  Q:(PIECE="")
 .S RSCODE=$P($G(PIECE),":",1)
 .S RSDESC=$P($G(PIECE),":",2)
 .S ^TMP($J,"PRNRCRF",4)=$G(^TMP($J,"PRNRCRF",4))_RSCODE_"^"_RSDESC_"~"
 .S I=I+1,PIECE=$P($G(OUT3),";",I)
 S SCR="I 1"_" & (($P($G("_"^"_"(0)),""^"",2))="""")"
 D LIST^DIC(90001.84,"","@;.01E;.03","","*",,,"",SCR,"","OUT4")
 S INDEX=$O(OUT4("DILIST","ID",0))
 I +INDEX>0 F  D  Q:(+INDEX'>0)
 .S MPIEN=$G(OUT4("DILIST",2,INDEX))
 .S PRIORITY=$G(OUT4("DILIST","ID",INDEX,".01"))_" "_$G(OUT4("DILIST","ID",INDEX,".03"))
 .S ^TMP($J,"PRNRCRF",5)=$G(^TMP($J,"PRNRCRF",5))_MPIEN_"^"_$G(PRIORITY)_"~"
 .S INDEX=$O(OUT4("DILIST","ID",INDEX))
 Q
 ;
