BMCRRSP1 ; IHS/PHXAO/TMJ - PROCESS REFERRAL LIST ;  [ 11/18/2003  11:38 AM ]
 ;;2.0;REFERRED CARE INFO SYSTEM;**2**;JAN 20, 2004
 ;;2.0*2 11.12.03 IHS/ITSC/FCJ  ADDED TEST OF REFERRAL TYPES
 ;;2.0*2 11.14.03 IHS/ITSC/FCJ UNCOMMENTED LINE FOR SORT BY USER
 ;
 ;Patch #1 Process Routine
START ;
 S (BMCBT,BMCBTH)=$H,BMCJOB=$J,BMCRCNT=0
 D PROCESS,END
 Q
 ;
PROCESS ;
 S BMCODAT=$O(^BMCPROV("B",BMCSD)) I BMCODAT="" S BMCET=$H Q
 S BMCODAT=BMCSD_".9999" F  S BMCODAT=$O(^BMCPROV("B",BMCODAT)) Q:BMCODAT=""!((BMCODAT\1)>BMCED)  D R1
 Q
 ;
R1 ;
 S BMCRDT="" F  S BMCRDT=$O(^BMCPROV("B",BMCODAT,BMCRDT)) Q:BMCRDT'=+BMCRDT  S BMCRREC=^BMCPROV(BMCRDT,0) D PROC
 Q
END ;
 S BMCET=$H
 Q
PROC ;
 Q:'$D(^BMCPROV(BMCRDT,0))
 S BMCRREC=^BMCPROV(BMCRDT,0),DFN=$P(BMCRREC,U,2),BMCDATE=$P(BMCRREC,U,1)
 S BMCREF=$P(BMCRREC,U,3)
 S BMCREVP=$P(BMCRREC,U,4)
 S BMCSPRV=$P(BMCRREC,U,5) ;Provider/Vendor IEN
 ;S BMCSPRV=$P(^AUTTVNDR(BMCSPRV,0),U) ;Vendor Name
 S:BMCSPRV'="" BMCSPRV=$P(^AUTTVNDR(BMCSPRV,0),U)
 S BMCAPPT=$P(BMCRREC,U,6) ;Exp Appt Date
 S BMCPUR=$P(BMCRREC,U,7) ; Purpose
 S BMCIHSP=$P(BMCRREC,U,8) ;IHS Provider
 ;
 Q:$P(^BMCREF(BMCREF,0),U,4)="N"
 ;BMC*2.0*2 11.12.03 IHS/ITSC/FCJ ADD NXT LINE TO TEST OF REF TYPES
 I BMCCTYP'="A",$P(^BMCREF(BMCREF,0),U,4)'=BMCCTYP Q  ;BMC*2.02*2 11.12.03
 Q:$P(^BMCREF(BMCREF,0),U,5)'=BMCFAC
 ;BMC*2.0*2 11.12.03 IHS/ITSC/FCJ UNCOMMENTED NXT LINE FOR USER REPORT
 I BMCCREV'=0,(BMCCREV'=BMCREVP) Q  ;BMC*2.0*2 11.12.03
 ;S BMCDATE=$S($$AVDOS^BMCRLU(BMCRDT,"I")]"":$$AVDOS^BMCRLU(BMCRDT,"I"),1:"<none>")
 S ^XTMP("BMCRRSP",BMCJOB,BMCBTH,"DATA HITS",BMCDATE,$P(^DPT(DFN,0),U),BMCRDT)="",BMCRCNT=BMCRCNT+1
 Q
