GMRAPEM0 ;HISC/WAA-ALLERGY/ADVERSE REACTION PATIENT EDIT DRIVER ; 8/27/93 [ 07/02/98  1:55 PM ]
 ;;3.0;Allergy Tracking System;**15**;09/03/97
EN1 ; EDIT PATIENT A/AR (DFN UNK.)
 S GMRAOUT=0 K ^TMP($J,"SF") W ! S DIC="^DPT(",DIC(0)="AEQM" D ^DIC G:+Y'>0 Q
Q I Y'=-1 S DFN=+Y D EN21 G:'GMRAOUT EN1
 ;K DFN,DIC,GMRAOUT D KILL^XUSCLEAN
 K DIC,GMRAOUT D:$P($G(XQY0),"^")'="PSO NEW" KILL^XUSCLEAN ;IHS/OKCAO/POC DONT BE KILLING DFN AND DOING KILL^XUSCLEAN!!
 Q
EN2 ; EDIT PATIENT A/AR (DFN KNOWN)
 D EN21 K GMRACNT,GMRADFN,GMRAES,GMRADRG,GMRAFLG,GMRAG,GMRAGOUT,GMRAI,GMRALOC,GMRALRCG,GMRALRCV,GMRAM1,GMRAM2,GMRAMARK,GMRANAM,GMRANAME,GMRANEW,GMRANKA
 K GMRANULL,GMRAOTH,GMRAOUT,GMRAPA,GMRAPS,GMRARNG,GMRASEX,GMRASING,GMRASITE,GMRATYPE,GMRAXX,GMRAVIP,GMRAYY
 Q
EN21 ; ENTRY POINT FOR ATS
 Q:'$D(DFN)  S GMRAOUT=0,GMRAFLG=1,GMRANKA=$O(^GMR(120.8,"ANKA",DFN,""))
 I '($$NKA(DFN)) F  D  Q:%'=0  Q:GMRAOUT
 .S %=$F("yn",GMRANKA)-1 W !,"Does this patient have any known allergies" D YN^DICN
 .I %=0 W !?4,"ANSWER YES IF THIS PATIENT HAS KNOW ALLERGIES, ELSE ANSWER NO."
 .I %=-1 S GMRAOUT=1
 .I %=2 D
 ..S Y=0 F X=0:0 S X=$O(^GMR(120.8,"B",DFN,X)) Q:X'>0  S Y=$G(^GMR(120.8,X,0)),Y=($P(Y,U,2)]""&'+$G(^GMR(120.8,X,"ER"))) Q:Y
 ..I Y W !?4,"THIS PATIENT HAS ALLERGIES ENTERED IN THE DATABASE, YOU CANNOT ANSWER NO." S %=0
 ..Q
 .Q
 G Q2:GMRAOUT S GMRAX=$S($G(%)'="":%,1:1) K %
 S DA=$S(GMRANKA]"":$O(^GMR(120.8,"ANKA",DFN,GMRANKA,"")),1:"")
 S DR="" I DA'>0 S X=DFN,DIC="^GMR(120.8,",DIC(0)="L",DLAYGO=120.8 K DINUM,DD,DO D FILE^DICN K DIC,DLAYGO G:+Y'>0 Q1 S DA=+Y,DR="4///N;5////"_DUZ
 S DIE=120.8,DR=DR_$S($L(DR):";",1:"")_".03////"_$E("yn",(GMRAX=2)+1) D ^DIE
 I GMRAX=2 S GMRAOUT=2 G Q2
 K ^TMP($J,"SF") S GMRAFLG=0,GMRACNT=0
EN3 ; PATIENT KNOW PATIENT AND NKA QUESTION ASKED
 D 1^VADPT S GMRALOC=$P(VAIN(4),U,2),GMRANAM=VADM(1),GMRASEX=VADM(5),GMRAOUT=0,GMRAOTH=$O(^GMRD(120.83,"B","OTHER REACTION",0)) D KVAR^VADPT K VA,VAROOT
 S GMRAPA=0 D EN1^GMRADSP0 G:GMRAOUT Q1
SELECT K GMRADUP,GMRAERR S GMRALAGO=1 D EN1^GMRAPES0
 I GMRAOUT=2,'GMRACNT G Q3
 I GMRAOUT=2,GMRACNT D SIGNOFF^GMRASIGN  G:GMRAOUT Q2 G Q3
 G Q1:GMRAOUT,EN3:GMRAPA'>0
 G:'$$LOCK^GMRAUTL(120.8,GMRAPA,1) SELECT
 D SITE^GMRAUTL S GMRADRUG=$S($P(GMRAPA(0),U,20)["D":1,1:0),GMRACNT=GMRACNT+1
 G:GMRANEW NEW
 I '$P(GMRAPA(0),"^",12),$P(GMRAPA(0),"^",5)'=DUZ,'$D(^XUSEC("GMRA-SUPERVISOR",DUZ)),'$D(^XUSEC("GMRA-ALLERGY VERIFY",DUZ)) D  G EN3
 .W !,$C(7),"THE PERSON INITIALLY ENTERING THIS ALLERGY/ADVERSE REACTION HAS NOT",!,"FINISHED ENTERING THE MANDATORY FIELDS, YOU CANNOT EDIT"
 .D UNLOCK^GMRAUTL(120.8,GMRAPA)
 .Q
 N GMRADFN D EN1^GMRAPEE0 I GMRAERR!GMRAOUT D  D UNLOCK^GMRAUTL(120.8,GMRAPA) G Q2
 .N GMRACNT S GMRACNT=$O(^TMP($J,"SF","B",GMRAPA,0)) Q:GMRACNT<1
 .K ^TMP($J,"SF",GMRACNT),^TMP($J,"SF","B",GMRAPA,GMRACNT)
 .Q
 I $P(GMRAPA(0),"^",12) D UNLOCK^GMRAUTL(120.8,GMRAPA) G EN3
NEW S DR="6(O)bserved or (H)istorical Allergy/Adverse Reaction",DIE="^GMR(120.8,",DA=GMRAPA D ^DIE I $D(Y) S GMRAOUT=1 G Q1
 S GMRANEW(0)=$S($D(^GMR(120.8,GMRAPA,0)):^(0),1:"") W:$P(GMRANEW(0),"^",6)']"" $C(7),"  Required??"
 G NEW:$P(GMRANEW(0),"^",6)']"",EDAT:$P(GMRANEW(0),"^",6)=$P(GMRAPA(0),"^",6)
YNNW I $P(GMRAPA(0),"^",6)]"" W !,"Are you sure you want to make that change" S %=1 D YN^DICN I '% W !?4,$C(7),"ANSWER YES IF THE CHANGE IS OK, ELSE ANSWER NO." G YNNW
 I $P(GMRAPA(0),"^",6)]"" I %'=1 S GMRAOUT=(%=-1),DIE="^GMR(120.8,",DR="6////"_$P(GMRAPA(0),"^",6),DA=GMRAPA D ^DIE G NEW:%=2,Q1:%=-1
 S $P(GMRAPA(0),"^",6)=$P(GMRANEW(0),"^",6)
EDAT I $P(GMRAPA(0),"^",6)="o" D EN1^GMRAPEO0 G:GMRAOUT Q1
 I $P(GMRAPA(0),"^",6)="h" D EN1^GMRAPEH0 G:GMRAOUT Q1
 K GMRAVER
 I '$$VFY^GMRASIGN(.GMRAPA),$D(^XUSEC("GMRA-ALLERGY VERIFY",DUZ)) S GMRAVER=0 D  G:GMRAVER QVER
 .N GMRAPRNT
 .D EN1^GMRAVFY K GMRALLER,GMRAMEC,GMRAY
 .Q
Q1 ;Unlock global and prep for next allergy
 I $G(GMRAERR)=1 D  G Q11
 .N GMRACNT Q:'$D(^TMP($J,"SF","B",GMRAPA))
 .S GMRACNT=0 S GMRACNT=$O(^TMP($J,"SF","B",GMRAPA,GMRACNT)) Q:GMRACNT<1
 .K ^TMP($J,"SF",GMRACNT,GMRAPA),^TMP($J,"SF","B",GMRAPA,GMRACNT)
 .Q
 I '$G(GMRAVER),'GMRAFLG,'$D(^TMP($J,"SF","B",GMRAPA)) S ^TMP($J,"SF","B",GMRAPA,GMRACNT)="",^TMP($J,"SF",GMRACNT,GMRAPA)=""
QVER I $G(GMRAVER) S GMRASLL(GMRAPA)=""
 ;This is to let the program know that this reaction has been verified.
Q11 K %,DA,DIC,DIE,DIK,DR,GMRACHC,GMRAERR,GMRADRUG,GMRAIV,GMRALOC,GMRANEW,GMRAOTH,GMRAPG,GMRAPRNT,GMRAREQ,GMRASEX,GMRASWH,GMRATYPE,GMRAVEDT,X,Y,GMRAVER
Q2 I GMRAOUT S GMRAOUT=2-GMRAOUT D:GMRAOUT&($D(^TMP($J,"SF"))) ALERT^GMRASIGN K ^TMP($J,"SF"),GMRACNT,GMRANAM,GMRAPA G Q3
 K GMRANAM,GMRAPA
 G EN3
Q3 S GMRAPA=0 F  S GMRAPA=$O(^TMP($J,"SF","C",GMRAPA)) Q:GMRAPA<1  D UNLOCK^GMRAUTL(120.8,GMRAPA)
 K ^TMP($J,"SF")
 Q
NKA(GMRADFN) ;This routine will tell if patient has allergy
 N GMRAOUT,GMRAIEN,GMRAX S GMRAOUT=0
 I GMRANKA="n"!(GMRANKA="") Q GMRAOUT
 S GMRAIEN=0 F  S GMRAIEN=$O(^GMR(120.8,"B",GMRADFN,GMRAIEN)) Q:GMRAIEN<1!GMRAOUT  D
 .S GMRAX=$G(^GMR(120.8,GMRAIEN,0)) Q:$P(GMRAX,U,2)=""
 .I '$G(^GMR(120.8,GMRAIEN,"ER")) S GMRAOUT=1
 .Q
 K GMRADFN Q GMRAOUT
