BHSIANDO ;IHS/MSC/MGH - Health Summary FOR I&O;14-Jun-2024 11:05;MR
 ;;1.0;HEALTH SUMMARY COMPONENTS;**19,20**;Mar 17, 2006;Build 42
IOCUM ; Print I&O Cumulative Report
 N BHSSTRT,BHSFIN,BHSADM,NOW,FROM,TO
 K ^TMP("BHSIO",$J)
 Q:'$D(^GMR(126,"B",DFN))
 S BHSSTRT=$G(GMTS2),BHSFIN=$G(GMTS1),NOW=$$NOW^XLFDT
 S FROM=9999999-BHSSTRT,TO=9999999-BHSFIN S:TO>NOW TO=NOW
 D TIMETBL(FROM,TO)    ; Creation of multiple stay timetable (Admission/ER) based on the period
 N LOCAT,IVINPUT,IVTPARR,IVTPARR1
 D TYPEABBR
 D SAVE,REPORT
 Q
SAVE ;Put type of IO into tmp global
 N LP,LP1,GIEN,IVIEN,SDATE,EDATE
 S SDATE=BHSSTRT,EDATE=BHSFIN-.000001
 S LP=EDATE F  S LP=$O(^GMR(126,DFN,"IO",LP)) Q:LP>SDATE!'LP  D
 .S LP1="" F  S LP1=$O(^GMR(126,DFN,"IO",LP,LP1)) Q:LP1=""  D
 ..S GIEN="" F  S GIEN=$O(^GMR(126,DFN,"IO",LP,LP1,GIEN)) Q:'GIEN  D
 ...I LP1="IN"!(LP1="OUT") D GETFLDS(DFN,LP,LP1,GIEN)
 ...I LP1="IV" D
 ....S IVIEN="" F  S IVIEN=$O(^GMR(126,DFN,"IO",LP,LP1,GIEN,IVIEN)) Q:'IVIEN  D GETIV(DFN,LP,LP1,GIEN,IVIEN)
 Q
GETFLDS(DFN,INDT,LP1,GIEN) ;Get the I and O fields
 N IENS,ITYPE,ITYPED,LOC,COM,TYP,INDTE,AMT,IOFILE,OF,DTM,ADMDT,LOCDSC
 I LP1="IN" S IOFILE=126.01,TYP="I"
 I LP1="OUT" S IOFILE=126.02,TYP="O"
 S IENS=GIEN_","_DFN_","
 S INDTE=9999999-INDT,OF=(LP1="OUT"),DTM=$$ENTRY^CIAUDT(INDTE,2)
 S:$L($P(DTM," ",2))<5 $P(DTM," ",2)="00:00"
 ;Quit if EIE
 Q:$$GET1^DIQ(IOFILE,IENS,9999999.01,"I")   ; entered in error
 S ITYPE=$$GET1^DIQ(IOFILE,IENS,1,"I"),ITYPED=$$GET1^DIQ(IOFILE,IENS,1)
 S LOC=$$GET1^DIQ(IOFILE,IENS,7-OF,"I"),LOCDSC=$$GET1^DIQ(IOFILE,IENS,7-OF)
 S ADMDT=$O(BHSADM1(INDTE+.000001),-1) I ADMDT,INDTE'>BHSADM1(ADMDT) S LOC=$P(BHSADM1(ADMDT),U,2),LOCDSC=$P(BHSADM1(ADMDT),U,3)
 S LOC=LOC_";"_LOCDSC
 S AMT=$$GET1^DIQ(IOFILE,IENS,4-OF,"I")
 S COM=$$GET1^DIQ(IOFILE,IENS,5-OF)
 I '$D(LOCAT(LOC)) S LOCAT(LOC)=INDTE_U_INDTE
 E  S:INDTE<$P(LOCAT(LOC),U) $P(LOCAT(LOC),U)=INDTE S:INDTE>$P(LOCAT(LOC),U,2) $P(LOCAT(LOC),U,2)=INDTE
 S ^TMP("BHSIO",$J,LOC,INDTE,TYP,GIEN)=AMT_U_ITYPE
 S ^TMP("BHSIO",$J,LOC,"COMM",+$E(INDTE,1,12),TYP,ITYPED_";"_GIEN)=AMT_U_COM_U_DTM
 S IVINPUT(TYP,ITYPE)=ITYPED
 Q
GETIV(DFN,INDT,LP1,GIEN,IVIEN) ;Get the IV fields
 N IENS,IENS2,ITYPE,ITYPED,LOC,COM,INDTE,ORD,ABBR,AMT,DTM,ADMDT,LOCDSC
 S IENS2=IVIEN_","_GIEN_","_DFN_","
 S IENS=GIEN_","_DFN_","
 S INDTE=9999999-INDT,DTM=$$ENTRY^CIAUDT(INDTE,2)
 S:$L($P(DTM," ",2))<5 $P(DTM," ",2)="00:00"
 ;Quit if EIE
 Q:+$$GET1^DIQ(126.313,IENS2,9999999.11,"I")   ; entered in error
 S ITYPE=$$GET1^DIQ(126.03,IENS,3,"I"),ITYPED=$$GET1^DIQ(126.03,IENS,3)
 S LOC=$$GET1^DIQ(126.313,IENS2,4,"I"),LOCDSC=$$GET1^DIQ(126.313,IENS2,4)
 S ADMDT=$O(BHSADM1(INDTE+.000001),-1) I ADMDT,INDTE'>BHSADM1(ADMDT) S LOC=$P(BHSADM1(ADMDT),U,2),LOCDSC=$P(BHSADM1(ADMDT),U,3)
 S LOC=LOC_";"_LOCDSC
 S COM=$$GET1^DIQ(126.313,IENS2,9999999.01),AMT=$$GET1^DIQ(126.313,IENS2,2)
 I '$D(LOCAT(LOC)) S LOCAT(LOC)=INDTE_U_INDTE
 E  S:INDTE<$P(LOCAT(LOC),U) $P(LOCAT(LOC),U)=INDTE S:INDTE>$P(LOCAT(LOC),U,2) $P(LOCAT(LOC),U,2)=INDTE
 S ^TMP("BHSIO",$J,LOC,INDTE,LP1,GIEN_";"_IVIEN)=AMT_U_ITYPE
 S ^TMP("BHSIO",$J,LOC,"COMM",+$E(INDTE,1,12),LP1,ITYPED_";"_GIEN_";"_IVIEN)=AMT_U_COM_U_DTM
 S ORD=$O(IVTPARR(ITYPE,"")),ABBR=IVTPARR(ITYPE,ORD)
 S IVINPUT(ORD)=ABBR
 Q
REPORT ;Write out the report
 N BHSDT1,BHSDT2,BHSX,BHS,BHSLN,BHSCOL,BHSCNT,BHSARR,LOC,LOC1,LOCS,REC,LOCAT1
 S BHSX="",$P(BHSX,"-",120)="" D TITLE
 S LOC="" F  S LOC=$O(LOCAT(LOC)) Q:'LOC  D
 .S FROM=$P(LOCAT(LOC),U),TO=$P(LOCAT(LOC),U,2)
 .S LOC1=$P(LOC,";",2) I '$D(BHSADM(LOC1)) S BHSADM(LOC1)=$$FLBAL(FROM,TO,LOC1,"")
 .S LOCAT1(FROM,LOC)=""
 N DTBEG,BAL24,BAL12,BAL8,ADMBAL,ADMBAL1,ADMDT,DISDT
 S DTBEG="" F  S DTBEG=$O(LOCAT1(DTBEG)) Q:'DTBEG  D
 .S LOC="" F  S LOC=$O(LOCAT1(DTBEG,LOC)) Q:'LOC  D
 ..S FROM=$P(LOCAT(LOC),U),TO=$P(LOCAT(LOC),U,2)
 ..S LOC1=$P(LOC,";",2),REC=BHSADM(LOC1)
 ..S BAL24=$P(REC,U),BAL12=$P(REC,U,2),BAL8=$P(REC,U,3),ADMBAL=$P(REC,U,4),LOCS=$P(REC,U,5)
 ..S ADMDT=$P(REC,U,6),DISDT=$P(REC,U,7)
 ..S ADMBAL1=$S(ADMBAL'="":"",1:" An inpatient encounter has not been selected")
 ..S BHSDT1=$$ENTRY^CIAUDT($S(ADMDT<FROM&ADMDT:ADMDT,1:FROM),2),BHSDT2=$$ENTRY^CIAUDT($S(DISDT>TO:DISDT,1:TO),2)
 ..D HEADER,BODY
 Q
 ;
TITLE ;CREATE HEADER FOR I/O SUMMARY REPORT,GTYPI(TYPE)=ORDER,GTYP(O)=ORDER
 N BHSBLNK,BHSN,BHSITYP,BHSOR,SIGN1,SIGN2,ITYPE,ORD K BHSLN
 S BHSBLNK=$J("",80),BHSLN(3)=$E(BHSBLNK,1,5)_"|",(SIGN1,SIGN2,BHSCNT)=0
 S ITYPE="" F  S ITYPE=$O(IVINPUT("I",ITYPE)) Q:ITYPE=""  D
 .S BHSLN(3)=BHSLN(3)_$E(IVINPUT("I",ITYPE)_BHSBLNK,1,5)_"|"
 .S BHSCNT=BHSCNT+1,BHSARR(1,BHSCNT)=ITYPE
 S BHSLN(1)="TIME |" I BHSCNT S BHSLN(1)=BHSLN(1)_"INTAKE"_$E(BHSBLNK,1,BHSCNT-1*6-1)_"|"
 I BHSCNT=1 S BHSLN(3)=$E(BHSLN(3),1,11)_" |",SIGN1=1
 S ORD=0 F I=0:1 S ORD=$O(IVINPUT(ORD)) Q:'ORD  D
 .S BHSLN(3)=BHSLN(3)_$E(IVINPUT(ORD)_BHSBLNK,1,5)_"|",BHSARR(2,I+1+BHSCNT)=IVTPARR1(ORD)
 I I S BHSLN(1)=BHSLN(1)_"IV INTAKE"_$E(BHSBLNK,1,I-1*6-4)_"|",BHSCNT=BHSCNT+I
 I I=1 S BHSLN(3)=$E(BHSLN(3),1,$L(BHSLN(3))-1)_"    |",SIGN2=4
 I $D(IVINPUT("O"))>1 S BHSLN(1)=BHSLN(1)_"OUTPUT"
 S ITYPE="" F  S ITYPE=$O(IVINPUT("O",ITYPE)) Q:ITYPE=""  D
 .S BHSLN(3)=BHSLN(3)_$E(IVINPUT("O",ITYPE)_BHSBLNK,1,5)_"|"
 .S BHSCNT=BHSCNT+1,BHSARR(3,BHSCNT)=ITYPE
 S BHSCOL=6*BHSCNT+8+SIGN1+SIGN2
 Q
HEADER ;write out header for report
 W !?23,"PATIENT INTAKE/OUTPUT SUMMARY"
 N TXT S TXT="LOCATION: "_LOC1,STR=37-($L(TXT)\2) W !?STR,TXT
 I LOCS'="" F I=1:1 Q:$P(LOCS,";",I)=""  S TXT="UNIT: "_$P(LOCS,";",I) W !?STR,TXT
 S TXT=BHSDT1_" - "_BHSDT2 W !?37-($L(TXT)\2),TXT,!! Q:'BHSCNT
 W BHSLN(1),!,BHSLN(3),!
 W $E(BHSX,1,BHSCOL),!
 Q
BODY ;write out the body of the report
 N BHSDATE,BHSTYPE,BHSNUM,BHSIEN,BHSDATA,BHSAMT,BHSNAME,BHSOUT,DTOTI,STOTI,STOTIV,STOTO
 N OUTDATE,BLANK,BTIME,BTIME2,STRING,MATCH,STRING2,MCNT,XTRA,BHSLEN,OUTTIME,DAY
 S BHSDATE=0 F  S BHSDATE=$O(^TMP("BHSIO",$J,LOC,BHSDATE)) Q:'BHSDATE  D
 .S BHSTYPE="" F  S BHSTYPE=$O(^TMP("BHSIO",$J,LOC,BHSDATE,BHSTYPE)) Q:BHSTYPE=""  D
 ..S BHSNUM=$S(BHSTYPE="I":1,BHSTYPE="IV":2,1:3)
 ..S BHSIEN="" F  S BHSIEN=$O(^TMP("BHSIO",$J,LOC,BHSDATE,BHSTYPE,BHSIEN)) Q:'BHSIEN  D
 ...S BHSDATA=$G(^TMP("BHSIO",$J,LOC,BHSDATE,BHSTYPE,BHSIEN))
 ...S BHSAMT=$P(BHSDATA,U)
 ...S BHSNAME=$P(BHSDATA,U,2) Q:$P(BHSNAME,";")=""
 ...S BHSOUT(+$E(BHSDATE,1,12),BHSNUM,BHSNAME)=$G(BHSOUT(+$E(BHSDATE,1,12),BHSNUM,BHSNAME))+BHSAMT
 ;Output data for one date/time
 K DTOTI S OUTDATE="",BLANK=$J("",10)
 S (STOTI,STOTO,STOTIV)=0
 S BTIME="" F  S BTIME=$O(BHSOUT(BTIME)) Q:BTIME=""  D
 .S BTIME2=$$ENTRY^CIAUDT(BTIME,2)
 .I $P(BTIME2," ")'=OUTDATE W:OUTDATE ! S OUTDATE=$P(BTIME2," ") W OUTDATE
 .S STRING=""
 .S BHSTYPE="" F  S BHSTYPE=$O(BHSOUT(BTIME,BHSTYPE)) Q:BHSTYPE=""  D
 ..S BHSNAME="" F  S BHSNAME=$O(BHSOUT(BTIME,BHSTYPE,BHSNAME)) Q:BHSNAME=""  D
 ...S BHSAMT=$G(BHSOUT(BTIME,BHSTYPE,BHSNAME))
 ...S MATCH=0 F  S MATCH=$O(BHSARR(BHSTYPE,MATCH)) Q:'MATCH  I $G(BHSARR(BHSTYPE,MATCH))=BHSNAME D  Q
 ....S $P(STRING,U,MATCH)=$P(STRING,U,MATCH)+BHSAMT
 ....;Add up the totals
 ....S $P(DTOTI(OUTDATE),U,BHSTYPE)=$P($G(DTOTI(OUTDATE)),U,BHSTYPE)+BHSAMT
 ....S SUMVAR="STOT"_$S(BHSTYPE=1:"I",BHSTYPE=2:"IV",1:"O"),@SUMVAR=@SUMVAR+BHSAMT
 .S STRING2=""
 .F MCNT=1:1:BHSCNT D
 ..S BHSLEN=$L($P(BHSLN(3),"|",MCNT+1))
 ..S BHSAMT=$P(STRING,U,MCNT)
 ..S XTRA=$E(BLANK,1,BHSLEN-$L(BHSAMT))
 ..S STRING2=STRING2_BHSAMT_XTRA_"|"
 .S OUTTIME=$P(BTIME2," ",2)
 .S:$L(OUTTIME)<5 OUTTIME=$S(OUTTIME:OUTTIME_":00",1:"00:00")
 .W !,$E(OUTTIME,1,5)_"|"_STRING2
 W !!,"DAILY TOTALS"
 S DAY="" F  S DAY=$O(DTOTI(DAY)) Q:DAY=""  D
 .W !,DAY,?12,"Intake:",$J(+$P(DTOTI(DAY),U),5),"ml"
 .W ?27,"IV Intake:",$J(+$P(DTOTI(DAY),U,2),5),"ml"
 .W ?45,"Output:",$J($S($P(DTOTI(DAY),U,3):-$P(DTOTI(DAY),U,3),1:+$P(DTOTI(DAY),U,3)),6),"ml"
 .W ?61,"Fluid balance:",$J($P(DTOTI(DAY),U,1)+$P(DTOTI(DAY),U,2)-$P(DTOTI(DAY),U,3),5),"ml"
 W !!,"TOTAL SUMMARY"
 W !?12,"Intake:",$J(STOTI,5),"ml",?27,"IV Intake:",$J(STOTIV,5),"ml"
 W ?45,"Output:",$J($S(STOTO:-STOTO,1:STOTO),6),"ml"
 W ?61,"Fluid Balance:",$J(STOTI+STOTIV-STOTO,5),"ml"
 W !!,"FLUID BALANCE"
 W !?12,"LAST 24 HOURS:",$J(+$G(BAL24),5),"ml"
 W !?12,"LAST 12 HOURS:",$J(+$G(BAL12),5),"ml"
 W !?12,"LAST  8 HOURS:",$J(+$G(BAL8),5),"ml"
 W !?12,"Admission    :",$J(+$G(ADMBAL),5),"ml",$G(ADMBAL1)
 Q:'$D(^TMP("BHSIO",$J,LOC,"COMM"))
 W !!,"Itemized List including COMMENTS:",!,"Date/Time",?17,"Type",?30,"Amount",?37,"Comment",!
 N DATM,LP,TP,ITP S DATM="" F  S DATM=$O(^TMP("BHSIO",$J,LOC,"COMM",DATM)) Q:'DATM  D
 .S LP="" F  S LP=$O(^TMP("BHSIO",$J,LOC,"COMM",DATM,LP)) Q:LP=""  D
 ..S TP=$S(LP="I":"Intake",LP="O":"Output",1:"IV Intake")
 ..S ITP="" F  S ITP=$O(^TMP("BHSIO",$J,LOC,"COMM",DATM,LP,ITP)) Q:ITP=""  D
 ...N REC,AMT,COM,DTM S REC=^TMP("BHSIO",$J,LOC,"COMM",DATM,LP,ITP)
 ...S AMT=$P(REC,U),COM=$P(REC,U,2),DTM=$P(REC,U,3)
 ...W DTM,?17,TP,?31,AMT,?37,$P(ITP,";"),": ",COM,!
 Q
 ;
FLBAL(FROM,TO,LOC,ADMDT) ; Defines an Admission Fluid Balance and Balance for 24, 12 and 8 hours
 N BHSDAT,SDATE,VAIP,NUMHRS,ADMBAL,ADM
 S BHSDAT=9999999-TO-0.000001,ADM=0
 I ADMDT S ADMDT=9999999-ADMDT,ADM=1,ADMBAL=$$ADMBAL(9999999-BHSDAT)
 F NUMHRS=24,12,8 S ADMDT=9999999-$$FMADD^XLFDT(NOW,,-NUMHRS),@("BAL"_NUMHRS)=$$ADMBAL(9999999-BHSDAT)
 Q BAL24_U_BAL12_U_BAL8_U_$G(ADMBAL)
 ;
ADMBAL(SDATE) ; Calculate Fluid Balance
 N ADMBAL S ADMBAL=0
 S LP=SDATE F  S LP=$O(^GMR(126,DFN,"IO",LP)) Q:LP>ADMDT!'LP  D
 .S LP1="" F  S LP1=$O(^GMR(126,DFN,"IO",LP,LP1)) Q:LP1=""  D
 ..S GIEN="" F  S GIEN=$O(^GMR(126,DFN,"IO",LP,LP1,GIEN)) Q:'GIEN  D
 ...I LP1="IN"!(LP1="OUT") D
 ....S IOFILE=$S(LP1="IN":126.01,1:126.02)
 ....S IENS=GIEN_","_DFN_","
 ....Q:$$GET1^DIQ(IOFILE,IENS,9999999.01,"I")      ; entered in error
 ....S OF=(LP1="OUT")
 ....I 'ADM Q:$$GET1^DIQ(IOFILE,IENS,7-OF)'=LOC    ; entered for another location
 ....S AMT=$$GET1^DIQ(IOFILE,IENS,4-OF)
 ....S ADMBAL=ADMBAL+$S(LP1="IN":AMT,1:-AMT)
 ...I LP1="IV" D 
 ....S IVIEN="" F  S IVIEN=$O(^GMR(126,DFN,"IO",LP,LP1,GIEN,IVIEN)) Q:'IVIEN  D
 .....S IENS2=IVIEN_","_GIEN_","_DFN_","
 .....Q:$$GET1^DIQ(126.313,IENS2,9999999.11,"I")   ; entered in error
 .....I 'ADM Q:$$GET1^DIQ(126.313,IENS2,4)'=LOC    ; entered for another location
 .....S AMT=$$GET1^DIQ(126.313,IENS2,2)
 .....S ADMBAL=ADMBAL+AMT
 Q ADMBAL
 ;
TIMETBL(START,END) ; Creation of multiple stay timetable (Admission/ER) based on the period
 N ADMDT,TRNDT,TRNNM,DISDT,FIND,LOC,FIND,TRNTP,MOVE,LOCNM,ADMLOC K BHSADM,BHSADM1
 S FIND=0,TRNDT=END+.000001 F  S TRNDT=$O(^DGPM("ADFN"_DFN,TRNDT),-1) Q:'TRNDT  D  Q:FIND
 .S TRNNM=$O(^DGPM("ADFN"_DFN,TRNDT,"")),TRNTP=$$GET1^DIQ(405,TRNNM,.04,"I"),TRNTP=$$GET1^DIQ(405.1,TRNTP,.02)
 .I TRNTP="DISCHARGE" S:TRNDT<START FIND=1 Q:FIND  S MOVE(TRNDT,"Z")=0
 .I TRNTP="ADMISSION"!(TRNTP="TRANSFER") S MOVE(TRNDT,TRNTP)=TRNNM I TRNTP="ADMISSION" S:TRNDT<START FIND=1
 S TRNDT="" F  S TRNDT=$O(MOVE(TRNDT)) Q:'TRNDT  D:$O(MOVE(TRNDT,""))'="Z"
 .S TRNTP=$O(MOVE(TRNDT,"")),TRNNM=MOVE(TRNDT,TRNTP),LOC=$$GET1^DIQ(405,TRNNM,.06,"I")
 .S LOCNM=$$GET1^DIQ(42,LOC,44,"I"),LOC=$$GET1^DIQ(44,LOCNM,.01)
 .I TRNTP="TRANSFER" S $P(BHSADM(ADMLOC),U,5)=$P(BHSADM(ADMLOC),U,5)_LOC_";" Q
 .S DISDT=TRNDT F  S DISDT=$O(MOVE(DISDT)) Q:'DISDT  Q:$O(MOVE(DISDT,""))="Z"  
 .S:DISDT DISDT=DISDT-.000001 S:'DISDT DISDT=END
 .S NEWBAL=$$FLBAL(TRNDT,DISDT,LOC,TRNDT) I '$D(BHSADM(LOC)) S BHSADM(LOC)=NEWBAL_U_U_TRNDT_U_DISDT
 .E  F I=1:1:4 S $P(BHSADM(LOC),U,I)=$P(BHSADM(LOC),U,I)+$P(NEWBAL,U,I)
 .S ADMLOC=LOC,BHSADM1(TRNDT)=DISDT_U_LOCNM_U_LOC
 Q
 ;
TYPEABBR ; Create an array of IV Types
 K IVTPARR
 F I=1:1 S LN=$T(ABBR+I) Q:LN=""  D
 .S TP=$P(LN,";",2),ABBR=$P(LN,";",3)
 .S IVTPARR(TP,I)=ABBR,IVTPARR1(I)=TP
 Q
ABBR ;
 ;A;ADMIX
 ;P;IVPB
 ;H;HYPER
 ;B;BLOOD
 ;I;LIPID
 ;L;LOCK
