AMQQATSQ ; OHPRD/DG - OVERRUN FROM AMQQATL ;  [ 01/31/2008   5:08 PM ]
 ;;2.0;PCC QUERY UTILITY;**14,18,20,21**;FEB 07, 2007
 ;IHS/CMI/LAB - patch 14 WH
SQ ; - ENTRY POINT - from AMQQATL
 ;I '$D(AMQQGVF),"GL"[$P(AMQQQ,U,3) S Z="" D ZSET^AMQQATL1 S AMQQILIN=AMQQILIN+1,^UTILITY("AMQQ",$J,"LIST",AMQQILIN)="W ?"_(3*AMQQUSQL+3)_","""_$P(AMQQQ,U,2)_Z_"  [SER = "_+$P(AMQQQ,U,11)_"]""" ; IHS/CMI/GIS 11/19/98
 I '$D(AMQQGVF),"GL"[$P(AMQQQ,U,3) S Z="" D ZSET^AMQQATL1 S AMQQILIN=AMQQILIN+1,^UTILITY("AMQQ",$J,"LIST",AMQQILIN)="W ?"_(3*AMQQUSQL+3)_","""_$P(AMQQQ,U,2)_Z_"""" ;IHS/CIM/THL PATCH 18
 I $D(AMQQLSQF) D SQ1^AMQQATL K ^UTILITY("AMQQ",$J,"SQL"),^UTILITY("AMQQ",$J,"SQXL"),AMQQLSQF,AMQQSQLN Q
 I '$D(AMQQLSQF),$D(^UTILITY("AMQQ",$J,"SQL",0,1)) S AMQQILIN=AMQQILIN+1,^UTILITY("AMQQ",$J,"LIST",AMQQILIN)="W ?9,""(INVERSE SET)""" K ^UTILITY("AMQQ",$J,"SQL")
 I $P(AMQQQ,U,3)="I" N % S %=$P($P(AMQQQ,U,9),";",4) S:"A"[$E(%) %="ALL" S AMQQILIN=AMQQILIN+1,^UTILITY("AMQQ",$J,"LIST",AMQQILIN)="W ?"_(3*AMQQUSQL+3)_",""IMMUNIZED WITH "_$P(AMQQQ,U,2)_" ("_%_")"""
 ;I  S %=$P(AMQQQ,U,11) I +% S ^UTILITY("AMQQ",$J,"LIST",AMQQILIN)=^UTILITY("AMQQ",$J,"LIST",AMQQILIN)_",""  [SER = "_+%_"]"""
 I  S %=$P(AMQQQ,U,11) I +% S ^UTILITY("AMQQ",$J,"LIST",AMQQILIN)=^UTILITY("AMQQ",$J,"LIST",AMQQILIN) ;IHS/CIM/THL  PATCH 18
 Q
 ;
