AMQQSQIM ; OHPRD/DG - IMMUNIZATION INFO ;  [ 01/31/2008   5:08 PM ]
 ;;2.0;PCC QUERY UTILITY;**10,15,18,20,21**;FEB 07, 2007
RUN D SER I $D(AMQQQUIT) G EXIT
 S X=AMQQSQSJ,AMQQCOMP=";;;"_$G(AMQQISR)
 I $D(AMQQRECV) S $P(AMQQRECV,U,11)=$G(AMQQISR)
EXIT K AMQQISR,AMQQIMMS,Y,AMQQIV1,AMQQIV2,AMQQIMDT,%
 Q
 ;
SER I AMQQSQSJ'["MR",AMQQSQSJ'["DTP",AMQQSQSJ'["VAR",AMQQSQSJ'["HIB V",AMQQSQSJ'["HEPATITIS",AMQQSQSJ'["OPV",AMQQSQSJ'["IPV",AMQQSQSJ'["DPT",AMQQSQSJ'["DT",AMQQSQSJ'["Td",AMQQSQSJ'["TD",AMQQSQSJ'["TETANUS TOXOID" S AMQQISR="A" Q
 ;IHS/OHPRD/TMJ
 ;IHS/CMI/THL - PATCH 15
 I '$D(AMQQIMMS) S AMQQIMMS=AMQQSQSJ
 S %=$E(AMQQIMMS,$L(AMQQIMMS)) K AMQQISR
 I "12345BA"[% S AMQQISR=% K AMQQIMMS
 I '$D(AMQQISR) D SERIES
 Q
 ;
SERIES ;IHS/CIM/THL PATCH 18
 ;W !!,"Select series (1-5, BOOSTER, COMPLETE, ALL, UNSPECIFIED): ALL// "
 ;R X:DTIME E  S X=U
 ;I X=U S AMQQQUIT="" Q
 ;I X="" S X="ALL"
 ;I X?1."?" D SHELP G SERIES
 ;S X=$E(X) I "12345ABCU"'[X W " ??",*7 G SERIES
 ;S AMQQISR=X
 S AMQQISR="A"
 Q
 ;
SHELP W !!,"Select from one of the following =>",!!
 W ?3,"1-5  Primary series number",!
 W ?3,"A    Display ALL immunizations in the series",!
 W ?3,"B    BOOSTER",!
 W ?3,"C    Series COMPLETED",!
 W ?3,"U    Series number UNSPECIFIED",!!!
 Q
 ;
