APCL8X ;IHS/CMI/LAB-CREATED BY ^ATXSTX ON FEB 04, 2008;
 ;;3.0;IHS PCC REPORTS;**21**;FEB 05, 1997
 ;
 ; See referenced routines to see taxonomies being loaded.
 ;
START ;
 D ^APCL8XA ;   DM AUDIT FLU CPTS
 D ^APCL8XB ;   DM AUDIT TD CPTS
 D ^APCL8XC ;   DM AUDIT P/C RATIO LOINC
 D ^APCL8XD ;   DM AUDIT FASTING GLUC LOINC
 D ^APCL8XE ;   DM AUDIT ESTIMATED GFR LOINC
 D ^APCL8XF ;   DM AUDIT A/C RATIO LOINC
 Q
