APCL3034 ; IHS/CMI/LAB - environment check ; 13 Aug 2014  11:54 AM
 ;;3.0;IHS PCC REPORTS;**34**;FEB 05, 1997;Build 43
 ;
 ;
 ; The following line prevents the "Disable Options..." and "Move
 ; Routines..." questions from being asked during the install.
 I $G(XPDENV)=1 S (XPDDIQ("XPZ1"),XPDDIQ("XPZ2"))=0
 F X="XPO1","XPZ1","XPZ2","XPI1" S XPDDIQ(X)=0
 I '$$INSTALLD("XU*8.0*1018") D SORRY(2)
 I '$$INSTALLD("DI*22.0*1018") D SORRY(2)
 I '$$INSTALLD("APCL*3.0*33") D SORRY(2)
 I '$$INSTALLD("ATX*5.1*39") D SORRY(2)
 ;
 Q
 ;
PRE ;
 Q
POST ;
 S X=$G(XPDQUES("POS Q1"))
 S DA=1,DIE="^APCLILIC(",DR=".05///"_X_";.07///1" D ^DIE K DIE,DA,DR
 ;D CLTAX
 ;D ERTAX
 D ^APCLSY
 Q
 ;
CLTAX ;
 S ATXFLG=1
 ;Q:$D(^ATXAX("B","SURVEILLANCE ILI CLINICS"))
 W !,"Updating Surveillance ILI Clinics taxonomy..."
 S APCLDA=0 S APCLDA=$O(^ATXAX("B","SURVEILLANCE ILI CLINICS",APCLDA)) I 'APCLDA D
 .S X="SURVEILLANCE ILI CLINICS",DIC="^ATXAX(",DIC(0)="L",DIADD=1,DLAYGO=9002226 D ^DIC K DIC,DA,DIADD,DLAYGO,I
 .I Y=-1 W !!,"ERROR IN CREATING SURVEILLANCE ILI CLINICS TAX" Q
 .S APCLTX=+Y,$P(^ATXAX(APCLTX,0),U,2)="SURVEILLANCE ILI CLINICS",$P(^(0),U,5)=DUZ,$P(^(0),U,8)=0,$P(^(0),U,9)=DT,$P(^(0),U,12)=172,$P(^(0),U,13)=0,$P(^(0),U,15)=40.7,^ATXAX(APCLTX,21,0)="^9002226.02101A^0^0"
 S APCLTX=$O(^ATXAX("B","SURVEILLANCE ILI CLINICS",0))
 K ^ATXAX(APCLTX,21)
 D ^XBFMK K DIADD,DLAYGO S APCLTEXT="CLINICS" F APCLX=1:1 S X=$P($T(@APCLTEXT+APCLX),";;",2) Q:X=""  S Y=$O(^DIC(40.7,"C",X,0)) I Y D
 .S ^ATXAX(APCLTX,21,APCLX,0)=+Y,$P(^ATXAX(APCLTX,21,0),U,3)=APCLX,$P(^(0),U,4)=APCLX,^ATXAX(APCLTX,21,"AA",+Y,+Y)=""
 .Q
 S DA=APCLTX,DIK="^ATXAX(" D IX1^DIK
 Q
ERTAX ;
 S ATXFLG=1
 ;Q:$D(^ATXAX("B","SURVEILLANCE ILI ER CLINICS"))
 W !,"Updating Surveillance ILI ER Clinics taxonomy..."
 S APCLDA=0 S APCLDA=$O(^ATXAX("B","SURVEILLANCE ILI ER CLINICS",APCLDA)) I 'APCLDA D
 .S X="SURVEILLANCE ILI ER CLINICS",DIC="^ATXAX(",DIC(0)="L",DIADD=1,DLAYGO=9002226 D ^DIC K DIC,DA,DIADD,DLAYGO,I
 .I Y=-1 W !!,"ERROR IN CREATING SURVEILLANCE ILI ER CLINICS TAX" Q
 .S APCLTX=+Y,$P(^ATXAX(APCLTX,0),U,2)="SURVEILLANCE ILI ER CLINICS",$P(^(0),U,5)=DUZ,$P(^(0),U,8)=0,$P(^(0),U,9)=DT,$P(^(0),U,12)=172,$P(^(0),U,13)=0,$P(^(0),U,15)=40.7,^ATXAX(APCLTX,21,0)="^9002226.02101A^0^0"
 S APCLTX=$O(^ATXAX("B","SURVEILLANCE ILI ER CLINICS",0))
 K ^ATXAX(APCLTX,21)
 D ^XBFMK K DIADD,DLAYGO S APCLTEXT="ERCLINIC" F APCLX=1:1 S X=$P($T(@APCLTEXT+APCLX),";;",2) Q:X=""  S Y=$O(^DIC(40.7,"C",X,0)) I Y D
 .S ^ATXAX(APCLTX,21,APCLX,0)=+Y,$P(^ATXAX(APCLTX,21,0),U,3)=APCLX,$P(^(0),U,4)=APCLX,^ATXAX(APCLTX,21,"AA",+Y,+Y)=""
 .Q
 S DA=APCLTX,DIK="^ATXAX(" D IX1^DIK
 Q
INSTALLD(APCLSTAL) ;EP - Determine if patch APCLSTAL was installed, where
 ; APCLSTAL is the name of the INSTALL.  E.g "AG*6.0*11".
 ;
 NEW APCLY,DIC,X,Y
 S X=$P(APCLSTAL,"*",1)
 S DIC="^DIC(9.4,",DIC(0)="FM",D="C"
 D IX^DIC
 I Y<1 D IMES Q 0
 S DIC=DIC_+Y_",22,",X=$P(APCLSTAL,"*",2)
 D ^DIC
 I Y<1 D IMES Q 0
 S DIC=DIC_+Y_",""PAH"",",X=$P(APCLSTAL,"*",3)
 D ^DIC
 S APCLY=Y
 D IMES
 Q $S(APCLY<1:0,1:1)
IMES ;
 D MES^XPDUTL($$CJ^XLFSTR("Patch """_APCLSTAL_""" is"_$S(Y<1:" *NOT*",1:"")_" installed.",IOM))
 Q
SORRY(X) ;
 KILL DIFQ
 I X=3 S XPDQUIT=2 Q
 S XPDQUIT=X
 W *7,!,$$CJ^XLFSTR("Sorry....FIX IT!",IOM)
 Q
CLINICS ;
 ;;30
 ;;10
 ;;12
 ;;13
 ;;20
 ;;24
 ;;28
 ;;57
 ;;70
 ;;80
 ;;89
 ;;01
 ;;06
 ;;90
 ;;E8
 ;;
ERCLINIC ;
 ;;30
 ;;80
 ;;
