ABSPOSRE  ;IHS/OIT/RAM - EXTENDED REJECTION REPORT BY REJECTION REASON
 ;;1.0;PHARMACY POINT OF SALE;**52,54**;JUN 01, 2001;Build 131
 ; IHS/OIT/RAM ; THIS IS A COPY OF ABSPOSRZ, DURING P52 TESTING IT WAS DECIDED TO RETAIN THE ORIGINAL
 ; RCR REPORT AND CALL THIS REPORT "EXTENDED RCR."
 ; IHS/OIT/AEF - Add queueing code to print to chosen printer, patch 54
 ; N Y,I X ^%ZOSF("SIZE") W Y,!
 Q
EN ; EP
 N ABSPQUIT,ABSPSTRT,ABSPEND,ABSPLCNT,ABSPREJ,ABSPRJ,ABSPRDAT,ZEROSUPP,REGOUT
 S ABSPOUT=0,REGOUT=1
 I $D(ZTQPARAM) D START  ;what does this do?
 S ABSPRDAT=$$RDATE
 ; W ABSPRDAT,!
 Q:ABSPRDAT=-1
 S (ABSPQUIT,ZEROSUPP)=0
 F  Q:ABSPQUIT  D
 . S ABSPSTRT=$$BDT^ABSPOSRU($$DATECMIX(ABSPRDAT))
 . I ABSPSTRT=-1 S ABSPQUIT=1 Q
 . S ABSPEND=$$EDT^ABSPOSRU($$DATECMIX(ABSPRDAT))
 . I ABSPEND=-1 S ABSPQUIT=1 Q
 . I ABSPSTRT<0!(ABSPEND<0) S ABSPQUIT=1 Q
 . S X2=ABSPSTRT,X1=ABSPEND D ^%DTC
 . I X<0 D EN^DDIOL("Ending Date is BEFORE Beginning Date Please enter new dates","","!!,*7")
 . I X>=0 S ABSPQUIT=2
 . ; Q
 Q:ABSPQUIT=1
 S ABSPQUIT=$$CLNC^ABSPOSRU() Q:ABSPQUIT=-1
 S ABSPQUIT=$$INS^ABSPOSUU() Q:ABSPQUIT=-1
 S ABSPQUIT=$$CODE^ABSPOSUU() Q:ABSPQUIT=-1  ; IHS/OIT/SCR 092109 patch 34 - screen by selected reject code
 S ABSPRTYP=$$RTYPE() Q:ABSPRTYP=-1  ; SET REPORT TYPE
 S:ABSPRTYP="D" ZEROSUPP=$$ZEROSUPP()
 ; W ABSPRTYP,!
 Q:ZEROSUPP=-1
 ;BEGIN NEW CODE - IHS/GDIT/AEF - ABSP*1.0*54 - FID77369
 ;S ABSPQUIT=$$DEVSEL() Q:ABSPQUIT=-1  ; SELECT DEVICE, INCLUDING HFS FILE IF NEEDED.
 ;
 ;D ^XBCLS
 ;Queueing code:
 N ZTDESC,ZTRTN,ZTSAVE,ZTSK
 S ZTRTN="DQ^ABSPOSRE"
 S ZTDESC="Extended Rejection Report by Rejected Reason"
 S ZTSAVE("ABSPRDAT")=""
 S ZTSAVE("ABSPSTRT")=""
 S ZTSAVE("ABSPEND")=""
 S ZTSAVE("ABSPPPHM")=""
 S ZTSAVE("ABSPINS")=""
 S ZTSAVE("ABSPREJ")=""
 S ZTSAVE("ABSPRTYP")=""
 S ZTSAVE("ZEROSUPP")=""
 S %ZIS="Q"
 D ^%ZIS
 Q:POP
 I $D(IO("Q")) D  Q
 . K IO("Q")
 . S ZTIO=ION_";"_IOST_";"_IOM_";"_IOSL
 . D ^%ZTLOAD
 . I $G(ZTSK) W !,"Task #",$G(ZTSK)," queued"
 D @ZTRTN
 Q
DQ ;Queued job starts here
 ;
 U IO
 ;END NEW CODE - IHS/GDIT/AEF - ABSP*1.0*54 - FID77369
 S STARTIME=$H
 D @$S(ABSPRDAT="F":"FINDFILL",ABSPRDAT="F":"FINDTRAN",1:"FINDREL")
 S STOPTIME=$H
 S ^TMP("ABSPOSRZ-RUNLOG",$J,STARTIME)=ABSPSTRT_"^"_$P(ABSPEND,".")_"^"_($P(STOPTIME,",",2)-$P(STARTIME,",",2))
 I $D(IO("HFSIO")) D USE^%ZISUTL("ABSP")
 I $O(^TMP("ABSPOSRZ",$J,""))="" D
 . I ABSPRTYP'="T" D PRHDR ; /IHS/OIT/RAM ; P52 ; ONLY PRINT HEADER IF NOT TEXT DELIMITED.
 . W !!," NO REJECTIONS FOUND FOR THE SELECTED DATE(S)"
 . D ZEND
 . S ABSPQUIT=-1
 Q:ABSPQUIT=-1
 I ABSPRTYP'="T" D SUM ; /IHS/OIT/RAM ; P52 ; ONLY PRINT SUMMARIES IF NOT TEXT DELIMITED.
 I ABSPRTYP'="T" D PRNTSUM ; /IHS/OIT/RAM ; P52 ; ONLY PRINT SUMMARIES IF NOT TEXT DELIMITED.
 I ABSPOUT D ZEND  Q
 I ABSPRTYP["D"!(ABSPRTYP["T") D PRNTDTL^ABSPOSRF ; /IHS/OIT/RAM ; P52 ; add text delimited to detail report;
 D ZEND
 Q
RDATE()  ; SELECT TYPE OF SORT DATE;
 N DIR,STARTIME,STOPTIME,X,Y,DIRUT
 S DIR(0)="S^F:FILL DATE;T:TRANSMIT DATE;R:RELEASE DATE"
 S DIR("B")="R"
 S DIR("A")="Please select F for Fill Date, T for Transmit Date, or R for Release Date."
 D ^DIR
 I $D(DTOUT)!$D(DUOUT)!$D(DIRUT)!$D(DIROUT) Q -1
 ; S ABSPRDAT=X ; SET REPORT TYPE
 Q X
RTYPE()  ; SELECT IF YOU WANT SUMMARY, OR DETAILED
 N DIR,STARTIME,STOPTIME
 S DIR(0)="S^S:SUMMARY;D:DETAILED;T:TEXT"
 S DIR("B")="D"
 S DIR("A")="Please select S for Summary, D for Detailed, or T for Text Delimited"
 D ^DIR
 I $D(DTOUT)!$D(DUOUT)!$D(DIRUT)!$D(DIROUT) Q -1
 Q $TR(X,"sdt","SDT")
 ;
ZEROSUPP()  ; SELECT IF YOU WANT TO SUPPRESS $0.00 VALUE SUMMARIES.
 N DIR,STARTIME,STOPTIME
 S DIR(0)="Y"
 S DIR("B")="NO"
 S DIR("A")="Would you like to suppress zero-value footers? "
 D ^DIR
 I $D(DTOUT)!$D(DUOUT)!$D(DIRUT)!$D(DIROUT)!(Y="^") Q -1
 Q Y
 ;
DEVSEL() ; SELECT DEVICE TYPE ; NOW SUPPORTS HFS FILES.
 N I,I2,I3,POP S POP=0
 S I=$$DEVSEL^ABSPOSRU
 I I="^" D ZEND Q -1
 I I=0 D ZEND Q -1 ; /IHS/OIT/RAM ; I KNOW THIS SEEMS REDUNDANT, SOME DOX NOTED IO MIGHT BE 'EMPTY.' PLACEHOLDER FOR 'EMPTY.'
 I $D(IO("HFSIO")) D
 . S POP=$$FILEOPEN("W","ABSP",IO("HFSIO"))
 . I POP W "Unable to open text file. Exiting.",! D CLOSE^%ZISUTL("ABSP") Q
 I POP D ZEND Q -1
 Q 1
 ;
FINDREL ; FIND REJECTIONS BY RELEASE DATE "AL" CROSS REFERENCE
 N ABSPDONE,ABSPRDT,ABSPPRMI,ABSPIRME,ABSPTRNS,STATUS
 K ^TMP($J,"ABSPCLMS") ;OIT/CAS/RCS 081213 Patch 46
 S ABSPRDT=ABSPSTRT
 S ABSPEND=ABSPEND_".99999999"
 S ABSPDONE=0
 F  S ABSPRDT=$O(^PSRX("AL",ABSPRDT)) Q:(ABSPRDT="")!(ABSPDONE)!(+ABSPRDT=0)  D
 . I ABSPRDT>ABSPEND S ABSPDONE=1 Q
 . S ^TMP("ABSPOSRZ",$J,$P(ABSPRDT,"."))=""
 . S ABSPPRMI=""
 . F  S ABSPPRMI=$O(^PSRX("AL",ABSPRDT,ABSPPRMI)) Q:ABSPPRMI=""  D
 . . S ABSPIRME=ABSPPRMI
 . . S ABSPIRMI=ABSPPRMI_".99999999"
 . . F  S ABSPIRMI=$O(^ABSPTL("B",ABSPIRMI),-1) Q:(ABSPIRMI<ABSPIRME)!(ABSPIRMI="")  D
 . . . S ABSPTRNS="",ABSPTRNS=$O(^ABSPTL("B",ABSPIRMI,ABSPTRNS),-1)
 . . . S:ABSPTRNS'="" STATUS=$$GETTRANS^ABSPOSRF(ABSPTRNS)
 ;
 Q
 ;
FINDFILL ; FIND REJECTIONS BY FILL DATE "AD" CROSS REFERENCE
 N ABSPDONE,ABSPRDT,ABSPPRMI,ABSPIRME,ABSPTRNS,STATUS
 K ^TMP($J,"ABSPCLMS") ;OIT/CAS/RCS 081213 Patch 46
 S ABSPRDT=ABSPSTRT
 S ABSPEND=ABSPEND_".99999999"
 S ABSPDONE=0
 F  S ABSPRDT=$O(^PSRX("AD",ABSPRDT)) Q:(ABSPRDT="")!(ABSPDONE)!(+ABSPRDT=0)  D
 . I ABSPRDT>ABSPEND S ABSPDONE=1 Q
 . S ^TMP("ABSPOSRZ",$J,$P(ABSPRDT,"."))=""
 . S ABSPPRMI=""
 . F  S ABSPPRMI=$O(^PSRX("AD",ABSPRDT,ABSPPRMI)) Q:ABSPPRMI=""  D
 . . S ABSPIRME=ABSPPRMI
 . . S ABSPIRMI=ABSPPRMI_".99999999"
 . . F  S ABSPIRMI=$O(^ABSPTL("B",ABSPIRMI),-1) Q:(ABSPIRMI<ABSPIRME)!(ABSPIRMI="")  D
 . . . S ABSPTRNS="",ABSPTRNS=$O(^ABSPTL("B",ABSPIRMI,ABSPTRNS),-1)
 . . . S:ABSPTRNS'="" STATUS=$$GETTRANS^ABSPOSRF(ABSPTRNS)
 ;
 Q
 ;
FINDTRAN ; FIND REJECTIONS BY TRANSMISSION DATE "AE" CROSS REFERENCE
 N ABSPDONE,ABSPRDT,ABSPPRMI,ABSPIRME,ABSPTRNS,STATUS,CLAIMIEN,TLIEN
 K ^TMP($J,"ABSPCLMS") ;OIT/CAS/RCS 081213 Patch 46
 S ABSPRDT=ABSPSTRT
 S ABSPEND=ABSPEND_".99999999"
 S ABSPDONE=0
 F  S ABSPRDT=$O(^ABSPC("AE",ABSPRDT)) Q:(ABSPDONE)!(+ABSPRDT=0)  D
 . I ABSPRDT>ABSPEND S ABSPDONE=1 Q
 . S ^TMP("ABSPOSRZ",$J,$P(ABSPRDT,"."))=""
 . S CLAIMIEN=""
 . F  S CLAIMIEN=$O(^ABSPC("AE",ABSPRDT,CLAIMIEN)) Q:CLAIMIEN=""  D
 . . ; OK, we have the claim #. This is a standard IEN and not in date format, so we have to go get that from ^ABSPTL.
 . . ; UNFORCH, almost nothing from ^ABSPC is a pointer to anything else, so we have to use ^ABSPTL's xrefs to find things. :-/
 . . S TLIEN=$O(^ABSPTL("AE",CLAIMIEN,0)) ; NOW WE SHOULD HAVE THE TRANSACTION LOG IEN HERE.
 . . ; S ABSPPRMI=$$GET1^DIQ(9002313.57,TLIEN,.01) ; MOVED TO GETTRANS... NOW WE HAVE THE TRANSACTION LOG ENTRY #.
 . . S STATUS=$$GETTRANS^ABSPOSRF(TLIEN)
 ;
 Q
 ;
PRHDR ;PRINT HEADER
 N ABSPFEDT,ABSPFBDT,Y
 I +$G(IOM)=0 S IOM=80
 ; U IO W:$D(ABSPSUM) @IOF
 S Y=ABSPSTRT
 D DD^%DT
 S ABSPFBDT=Y
 S Y=$P(ABSPEND,".")
 D DD^%DT
 S ABSPFEDT=Y
 I '$D(IO("HFSIO")) W @IOF
 W $$CTR^ABSPMHDR("Pharmacy POS Rejection Report, Claims sorted by Rejection Reason",IOM),!
 ; W $$CTR^ABSPMHDR("Claims sorted by Rejection Reason",IOM),!
 W $$CTR^ABSPMHDR($$DATECMIX(ABSPRDAT)_" From "_ABSPFBDT_" TO "_ABSPFEDT,IOM),!
 W $$CTR^ABSPMHDR("***SUMMARY REPORT***",IOM),!!
 Q
 ;
PRNTDHD ; /IHS/OIT/RAM ; NEW PRINT DETAIL HEADER ROUTINE WITH PATCH 52; UPDATED TO HANDLE BOTH 80, 132 & 160 COLS.
 I ABSPRTYP'["D" D ZEND^ABSPOSRE Q
 N WIDTH,ROUTINE,HDR,I,I2,I3,J,J2,J3,K
 S WIDTH=$S($G(IOM)>159:160,$G(IOM)>131:132,1:80)
 S ROUTINE="D HDR"_WIDTH_"^ABSPOSRF(.HDR)"
 X ROUTINE
 W !!
 S ABSPOUT=$$WRITE^ABSPOSUU("!!,$$CTR^ABSPMHDR(""********** Detailed Report **********"",WIDTH),!!")
 Q:ABSPOUT
 ; ZW HDR
 S I=0 F  S I=$O(HDR(I)) Q:+I=0  D
 . S J=0 F  S J=$O(HDR(I,J)) Q:+J=0  S ABSPOUT=$$WRITE^ABSPOSUU("?+$P(HDR(I,J),""^""),$P(HDR(I,J),""^"",2)") Q:ABSPOUT
 . S ABSPOUT=$$WRITE^ABSPOSUU("!") Q:ABSPOUT
 Q
 ;
DATECMIX(ZDATE) ; /IHS/OIT/RAM ; Return full text of report search date, mixed case.
 Q $S(ZDATE="F":"Filled",ZDATE="T":"Transmitted",1:"Released")
 ;
DATECUPR(ZDATE) ; /IHS/OIT/RAM ; Return full text of report search date, upper case.
 Q $S(ZDATE="F":"FILLED",ZDATE="T":"TRANSMITTED",1:"RELEASED")
 ;
SUM ;PRINT SUMMARY PAGE AND TOTAL AMT PER EACH THAT WAS REJECTED
 N ABSPPCNT,ABSPTMP
 S ABSPSRDT=""
 F  S ABSPSRDT=$O(^TMP("ABSPOSRZ",$J,ABSPSRDT)) Q:ABSPSRDT=""  D
 .M ABSPTMP=^TMP("ABSPOSRZ",$J,ABSPSRDT)
 .S ABSPSPHM=""
 .F  S ABSPSPHM=$O(ABSPTMP(ABSPSPHM)) Q:ABSPSPHM=""  D
 ..S ABSPSTIN=""
 ..F  S ABSPSTIN=$O(ABSPTMP(ABSPSPHM,ABSPSTIN)) Q:ABSPSTIN=""  D
 ...S ABSPSRNM=""
 ...F  S ABSPSRNM=$O(ABSPTMP(ABSPSPHM,ABSPSTIN,ABSPSRNM)) Q:ABSPSRNM=""  D
 ....S ABSPSTTL=0,ABSPSRMI="",ABSPSTL1=0
 ....F  S ABSPSRMI=$O(ABSPTMP(ABSPSPHM,ABSPSTIN,ABSPSRNM,ABSPSRMI)) Q:ABSPSRMI=""  D
 .....S ABSPSREA=ABSPTMP(ABSPSPHM,ABSPSTIN,ABSPSRNM,ABSPSRMI,"REJECTTXT")
 .....S ABSPPCNT=$P($G(ABSPREAS(""_ABSPSRNM_"",ABSPSPHM)),U)
 .....S ABSPSTTL=ABSPSTTL+ABSPTMP(ABSPSPHM,ABSPSTIN,ABSPSRNM,ABSPSRMI,"COST")
 ....S ABSPSTL1=ABSPSTTL+$P($G(ABSPSUM(ABSPSPHM,ABSPSRNM)),U,2)
 ....S ABSPSUM(ABSPSPHM,ABSPSRNM)=ABSPSRNM_":"_ABSPSREA_U_ABSPSTL1_U_ABSPSTIN_U_ABSPPCNT
 ....; W "SUMMARYSTUFF",!
 .K ABSPTMP
 Q
 ;
PRNTSUM ;PRINT THE SUMMARY REPORT
 N ABSPGCNT,ABSPPCNT,ABSPTMP
 S (ABSPRTOT,ABSPPCNT,ABSPGTOT,ABSPGCNT,ABSPBTOT,ABSPQUIT,ABSPOUT)=0
 S ABSPPPHM=""
 D PRHDR
 F  S ABSPPPHM=$O(ABSPSUM(ABSPPPHM)) Q:(ABSPPPHM="")!(ABSPOUT)  D
 . ; I ABSPOUT Q
 . I ABSPPPHM=0 S ABSPPPHM=1
 . S ABSPPHMN=$P(^ABSP(9002313.56,ABSPPPHM,0),U,1)
 . ;IHS/OIT/CNI/RAN 04272010 patch 39 - When printing to screen use paging.
 . S ABSPOUT=$$WRITE^ABSPOSUU("!!,""PHARMACY: "",ABSPPHMN")
 . Q:ABSPOUT
 . S ABSPPRNM=""
 . S (ABSPRTOT,ABSPPCNT)=0  ;IHS/OIT/SCR 110309 this is pharmacy count
 . ;IHS/OIT/CNI/RAN 05042010 patch 39 - When printing to screen use paging.
 . S ABSPOUT=$$WRITE^ABSPOSUU("!?2,""REJECTION CODE: "",?57,""AMT BILLED:"",?68,""  RX COUNT: """)
 . Q:ABSPOUT
 . F  S ABSPPRNM=$O(ABSPSUM(ABSPPPHM,ABSPPRNM)) Q:(ABSPPRNM="")!(ABSPOUT)  D
 . . ; I ABSPOUT Q
 . . S ABSPDRTR=$P(ABSPSUM(ABSPPPHM,ABSPPRNM),U,1)
 . . I ABSPDRTR'="" D
 . . . ;IHS/OIT/CNI/RAN 04272010 patch 39 - When printing to screen, use paging.
 . . . S ABSPOUT=$$WRITE^ABSPOSUU("!?0,$E($P(ABSPSUM(ABSPPPHM,ABSPPRNM),U,1),1,56),?57,$J($FN($P(ABSPSUM(ABSPPPHM,ABSPPRNM),U,2),"","",2),10),?72,$J($P(ABSPSUM(ABSPPPHM,ABSPPRNM),U,4),4)")
 . . . Q:ABSPOUT
 . . . S ABSPRTOT=ABSPRTOT+$P(ABSPSUM(ABSPPPHM,ABSPPRNM),U,2)
 . . . S ABSPPCNT=ABSPPCNT+$P(ABSPSUM(ABSPPPHM,ABSPPRNM),U,4)
 . . Q:ABSPOUT
 . Q:ABSPOUT
 . S ABSPGTOT=ABSPGTOT+ABSPRTOT
 . S ABSPGCNT=ABSPGCNT+ABSPPCNT
 .;IHS/OIT/CNI/RAN 04272010 patch 39 - When printing to screen use paging
 .W:$Y<3 ! S ABSPOUT=$$WRITE^ABSPOSUU("!!,?48,""TOTAL: $"",?57,$J($FN(ABSPRTOT,"","",2),10)")
 .Q:ABSPOUT
 .W:$Y<3 ! S ABSPOUT=$$WRITE^ABSPOSUU("!,?40,""# RX REJECTED:"",?72,$J(ABSPPCNT,4)")
 .Q:ABSPOUT
 Q:ABSPOUT
 ;IHS/OIT/CNI/RAN 04272010 patch 39 - When printing to screen, use paging
 W:$Y<3 ! S ABSPOUT=$$WRITE^ABSPOSUU("!!,?42,""GRAND TOTAL: $"",?57,$J($FN(ABSPGTOT,"","",2),10)")
 Q:ABSPOUT
 W:$Y<3 ! S ABSPOUT=$$WRITE^ABSPOSUU("!,?40,""# RX REJECTED:"",?72,$J(ABSPGCNT,4)")
 ;W:$Y<3 ! W !!,"P - Preventable, N - Non-recoverable, B - Both"
 Q
 ;
DETREJ(VAR,H) ; /IHS/OIT/RAM ; P52 ; NEW ROUTINE TO 'PRELOAD' DETAIL COLUMNS FOR REJECTS.
 S:$G(VAR)="" VAR="ONELINE"
 N I,ABSPLINE S ABSPLINE=$S($G(WIDTH)=160:2,$G(WIDTH)=132:3,1:4)
 I $G(REGOUT) F I=1:1:@VAR@("REJNUM") S H(I+ABSPLINE,1)="0^"_VAR_"(""REJ"","_I_")"
 Q
DELIMHDR() ; /IHS/OIT/RAM ; P52 ; NEW ROUTINE TO 'PRELOAD' HEADER COLUMNS FOR A TEXT OUTPUT FILE.
 N H,I,I2
 S H(1)="FILL DATE",H(2)="RELEASE DATE",H(3)="TRANS. DATE",H(4)="RX IEN#"
 S H(5)="RX #",H(6)="NDC #",H(7)="GROUP #",H(8)="DRUG NAME"
 S H(9)="CLAIM #",H(10)="INSURER",H(11)="HELPDESK #",H(12)="BILLED AMT:"
 S H(13)="CHART#",H(14)="NAME:",H(15)="CARDHOLDER ID:",H(16)="INS DOB:"
 W H(1) S I=1
 F  S I=$O(H(I)) Q:+I=0  W "^",H(I)
 F I=1:1:4 W "^","REJ #"_I
 F I=1:1:4 W "^","ADD. INFO #"_I
 W !
 Q
DELIMOUT(VAR,H) ; /IHS/OIT/RAM ; P52 ; NEW ROUTINE TO 'PRELOAD' DETAIL COLUMNS FOR TEXT OUTPUT FILE.
 N I ; K H
 S:$G(VAR)="" VAR="ONELINE"
 S H(1)=VAR_"(""FILL DATE"")"
 S H(2)=VAR_"(""RELEASE DATE"")"
 S H(3)=VAR_"(""TRANS DATE"")"
 S H(4)=VAR_"(""RXIEN"")"
 S H(5)=VAR_"(""RX #"")"
 S H(6)=VAR_"(""NDC"")"
 S H(7)=VAR_"(""GROUPID"")"
 S H(8)=VAR_"(""DRUG NAME"")"
 S H(9)=VAR_"(""CLAIM #"")"
 S H(10)=VAR_"(""INSURER NAME"")"
 S H(11)=VAR_"(""INSURER HELP"")"
 S H(12)=VAR_"(""COST"")"
 S H(13)=VAR_"(""CHART#"")"
 S H(14)=VAR_"(""PATIENTNAME"")"
 S H(15)=VAR_"(""CARDID"")"
 S H(16)=VAR_"(""DOB"")"
 I $G(REGOUT) F I=1:1:4 S H(I+16)=$S(I<=(@VAR@("REJNUM")):VAR_"(""REJ"","_I_")",1:"""""")
 I $G(REGOUT) F I=1:1:4 S H(I+20)=$S($G(@VAR@("ADDINFO",I))'="":VAR_"(""ADDINFO"","_I_")",1:"""""")
 ; I $G(REGOUT) F I=@VAR@("REJNUM"):1:3 S H(I+16)=VAR_"(""REJ"","_I_")"
 ; 
 Q
 ;
FIT80 ; 
 S P=@VAR@("REJNUM")+4,P2=1,I2=0
 F I=1:1:4 D
 . I $G(@VAR@("ADDINFO",I))="" Q
 . S L(I)=$L($G(@VAR@("ADDINFO",I)))
 I $G(L(1))="" Q
 S H(P+P2,1)="0^"_VAR_"(""ADDINFO"",1)"
 I $G(L(2))="" Q
 I $G(L(1))+$G(L(2))<80 S H(P+P2,2)=$G(L(1))+1_"^"_VAR_"(""ADDINFO"",2)",P2=P2+1,LP=0
 E  S P2=P2+1,H(P+P2,1)="0^"_VAR_"(""ADDINFO"",2)",LP=1
 I $G(L(3))="" Q
 I LP&($G(L(2))+$G(L(3))<80) S H(P+P2,2)=$G(L(2))+1_"^"_VAR_"(""ADDINFO"",3)",P2=P2+1,LP=0
 E  S P2=P2+1,H(P+P2,1)="0^"_VAR_"(""ADDINFO"",3)",LP=1
 I $G(L(4))="" Q
 I LP&($G(L(3))+$G(L(4))<80) S H(P+P2,2)=$G(L(3))+1_"^"_VAR_"(""ADDINFO"",4)"
 E  S P2=P2+1,H(P+P2,1)="0^"_VAR_"(""ADDINFO"",4)"
 ;
 Q
ZEND ;END AND KILL VARIABLES
 D ^%ZISC
 D CLOSE^ZISUTL("ABSP")
 K ^TMP("ABSPOSRZ",$J),^TMP($J,"ABSPCLMS")
 D KILL^ABSPUTL   ;ABSP*1.0*54
 Q
START  ;
 N X,Y,ABSPJ,ABSPRJC,ABSPPAT,ABSPPIEN
 I $D(ZTQPARAM) D
 .I $P(ZTQPARAM,";",1)["T-1" S ABSPSTRT=DT-1
 .I $P(ZTQPARAM,";",2)["T-1" S ABSPEND=DT-1
 .S ABSPINS="ALL"
 .S ABSPPPHM="ALL"
 .S ABSPRTYP="D"
 .D FINDREL
 .D ZEND
 .Q
 Q
FILEOPEN(MODE,HANDLE,FILENAME) ; opens a file to read using the OPEN^%ZISUTL utility.
 ;
 Q $$FILEOPEN^ABSPUTL(MODE,HANDLE,FILENAME)  ;ABSP*1.0*54
HUMDATE(FMDATE) ; /IHS/OIT/RAM ; P52 ; EXTRINSIC FUNCTION TO MAKE FM DATE HUMAN READABLE.
 ;
 Q $$HUMDATE^ABSPUTL(FMDATE)   ;ABSP*1.0*54
HUMDTIME(FMDATE) ; /IHS/OIT/RAM ; P52 ; EXTRINSIC FUNCTION TO MAKE FM DATE & TIME HUMAN READABLE.
 ;
 Q $$HUMDTIME^ABSPUTL(FMDATE)  ;ABSP*1.0*54
