ABSPVDF ; IHS/SD/SDR - VIDEO DISPLAY FEATURES ;
 ;;1.0;PHARMACY POINT OF SALE;**55**;01 JUN 2001;Build 131
 ;IHS/SD/SDR 1.0*55 ADO115325 New routine
 ;
EN(X) ; EP
 S ABSP1("X")=$X
 I '$G(IOST(0)) S IOP=0 D ^%ZIS
 I '$D(ABSPVDF(+IOST(0),X)) D
 .S ABSP1("LN")=$T(@X)
 .S ABSP1(1)=$P(ABSP1("LN"),";;",2)
 .S ABSP1(2)=$P(ABSP1("LN"),";;",3)
 .S ABSP1(3)=$P(ABSP1("LN"),";;",4)
 .S ABSPVDF(+IOST(0),X)=$P($G(^%ZIS(2,+IOST(0),ABSP1(1))),"^",ABSP1(2),ABSP1(3))
 .I ABSPVDF(+IOST(0),X)="" S ABSPVDF(+IOST(0),X)="*0"
 W @ABSPVDF(+IOST(0),X)
 S $X=ABSP1("X")
 S X=""
 K ABSP1
 Q X
 ; *********************************************************************
 ;GLOBAL LOCATIONS TO FOLLOW
 ;
HIN ;;7;;1;;1;;HI INTENSITY ON
HIF ;;7;;2;;2;;HI INTENSITY OFF
RVN ;;5;;4;;4;;REVERSE VIDEO ON
RVF ;;5;;5;;5;;REVERSE VIDEO OFF
ULN ;;6;;4;;4;;UNDERLINE ON
ULF ;;6;;5;;5;;UNDERLINE OFF
DTP ;;17;;1;;1;;DOUBLE HIGH TOP HALF
DTB ;;17;;2;;2;;DOUBLE HIGH BOTTOM HALF
BLN ;;5;;8;;8;;BLINK ON
BLF ;;5;;9;;9;;BLINK OFF
CUP ;;8;;1;;1;;CURSOR UP
IOF ;;1;;2;;2;;FORM FEED/CLEAR SCREEN
10 ;;5;;1;;1;;TEN PITCH
12 ;;5;;2;;2;;TWELVE PITCH
16 ;;12.1;;1;;250;;SIXTEEN PITCH
GRF ;;C;;1;;1;;GREEN FOREGROUND
YEF ;;C;;2;;2;;YELLOW FOREGROUND
CYB ;;C;;3;;3;;CYAN BACKGROUND
REB ;;C;;5;;5;;RED BACKGROUND
WHF ;;C;;4;;4;;WHITE FOREGROUND
CLR ;;6;;1;;1;;RESET
HOM ;;5;;3;;3;;HOME CURSOR
