ABSPUTL ;IHS/GDIT/AEF - PHARMACY POINT OF SALE UTILITIES
 ;;1.0;PHARMACY POINT OF SALE;**54,55,56**;JUN 01, 2001;Build 131
 ;NEW ROUTINE; IHS/GDIT/AEF 3231011 ABSP*1.0*54 FID 77888
 ;IHS/SD/SDR 1.0*55 ADO115325 Added date format MM/DD/CCYY
 ;IHS/SD/SDR 1.0*56 ADO122824 Added dots
 ;
PPN1(DFN) ;----- RETURNS THE "NAME* - PPN"
 ;
 ;      INPUT:
 ;      DFN  =  PATIENT'S IEN IN VA PATIENT FILE
 ;
 ;
 N Y
 S Y=""
 ;
 ;Get PPN if the PPN parameter is turned on:
 I DFN]"" D
 . I $$GETPREF^AUPNSOGI(DFN,"I",1)'="" S Y=" - "_$$GETPREF^AUPNSOGI(DFN,"I",1)_"*"
 ;
 Q Y
BDT()  ; ENTER BEGINING DATE
 N ABSPBDT,DIR,X1,X
 W !
 K DIR
 S DIR(0)="DEX"
 S DIR("A")="Enter Beginning Prescription Release Date"
 D ^DIR
 I $D(DIRUT) Q -1
 S ABSPBDT=+Y
 S X1=ABSPBDT D C^%DTC
 Q X
EDT()  ; ENTER END DATE
 N ABSPEDT,DIR,X1,X
 W !
 K DIR
 S DIR(0)="DEX"
 S DIR("A")="Enter Ending Prescription Release Date"
 D ^DIR
 I $D(DIRUT) Q -1
 S ABSPEDT=+Y
 S X1=ABSPEDT D C^%DTC
 Q X
FILEOPEN(MODE,HANDLE,FILENAME) ; opens a file to read using the OPEN^%ZISUTL utility.
 ;
 N IOP,A,POP
 S:'$D(IOM) IOM=80
 S:'$D(IOSL) IOM=64
 S IOP="HFS"_";"_IOM_";"_IOSL
 S A("HFSMODE")=MODE
 S A("HFSNAME")=FILENAME
 D OPEN^%ZISUTL(HANDLE,IOP,.A)
 Q POP
 ;
HUMDATE(FMDATE) ; /IHS/OIT/RAM ; P52 ; EXTRINSIC FUNCTION TO MAKE FM DATE HUMAN READABLE.
 ;
 N Y,CENTURY,REST
 S CENTURY=$E(FMDATE,1,2),REST=$E(FMDATE,3,$L(FMDATE))
 I $L(FMDATE)=8&((CENTURY>18)&(CENTURY<27)) S FMDATE=(CENTURY-17)_REST
 S Y=$P(FMDATE,".") D DD^%DT
 Q Y   ; FORMATTED RELEASE DATE
 ;
HUMDTIME(FMDATE) ; /IHS/OIT/RAM ; P52 ; EXTRINSIC FUNCTION TO MAKE FM DATE & TIME HUMAN READABLE.
 ;
 N Y S Y=FMDATE D DD^%DT
 Q Y   ; FORMATTED RELEASE DATE
KILL ; KILL VARIABLES
 K ABSPTMP,ABSPSUM,ABSBPRTT,ABSPBTOT,ABSPGTOT,ABSPRTOT,ABSPINS,ABSPPTP,ABSPPAT,ABSPPCHT,ABSPINSN,ABSPPRX,ABSPPRMI,ABSPPRXR,ABSPPDIV,ABSPOPS,ABSPPATN,ABSPPPHM,ABSPPRDT
 K ABSPREAS,ABSPRMI,ABSPSRDT,ABSPSTTL,ABSPSRMI,ABSPSPHM,ABSPSRNM,RNUM,ABSPSTIN,ABSPFBDT,ABSPFEDT,ABSPBDT,ABSPEDT,ABSPTINS,ABSPTRNS,ABSPJ,ABSPRTYP,ABSPDRT,ABSPDRTR,ABSPRJCD
 K ABSPPHM1,ABSPPHMN,ABSPPINS,ABSPPRNM,ABSPRCD,ABSPRDTL,ABSPREA,ABSPSREA,ABSPSTL1,ABSPSTRT
 Q
 ;start new absp*1.0*55 IHS/SD/SDR ADO115325
Y2KDT(X) ;EP - Y is set to the printable date ##/##/#### from X (fileman date)
 N Y
 S Y=$S(+X>0:$E(X,4,5)_"/"_$E(X,6,7)_"/"_($E(X,1,3)+1700),1:"")
 Q Y
 ;end new absp*1.0*55 IHS/SD/SDR ADO115325
 ;
 ;start new absp*1.0*56 IHS/SD/SDR ADO122824
DOTS(X) ;EP - WRITE OUT A DOT EVERY HUNDRED
 U IO(0)
 W:'(X#100) "."
 Q
 ;end new absp*1.0*56 IHS/SD/SDR ADO122824
