ABSPOSRF  ;IHS/OIT/RAM - EXTENDED REJECTION REPORT BY REJECTION REASON
 ;;1.0;PHARMACY POINT OF SALE;**52**;JUN 01, 2001;Build 131
 ; IHS/OIT/RAM ; MOVED SOME ROUTINES FROM ABSPOSRE AS IT GOT *WAY* TOO BIG.
 ; N Y,I X ^%ZOSF("SIZE") W Y,!
 Q
 ;
GETTRANS(ABSPTRNS) ; /IHS/OIT/RAM ; GET AN INDIVIDUAL TRANSACTION.
 ; ABSPTRNS == ABSP LOG OF TRANSACTIONS IEN
 N ABSPCARD,ABSPGRP,ABSPCLMI,ABSPRCNT,ABSPRNUM,ABSPTRTM,ABSPRSMI,TLENTRY,TLPART
 N ABSPTLTP,ABSPRESC,DO,ABSPIDTS,ABSPIDTE,ABSPIRME,STATUS,ABSPTL,TMPARRAY,NDCDRG,DOB,X,Y,%DT
 S TLENTRY=$$GET1^DIQ(9002313.57,ABSPTRNS,.01),TLPART=$P(TLENTRY,".")
 M ABSPTL=^ABSPTL(ABSPTRNS)
 ; DONT REPORT CLOSED CLAIMS
 I +$P($G(ABSPTL(9)),"^") S ^TMP($J,"ABSPCLMS",TLPART)="" Q 0  ;OIT/CAS/RCS - Patch 46, S ABSPCLMS($P(ABSPIRMI,"."))="" Q
 S ABSPTLTP=ABSPTL(0)
 S ABSPRSMI=$P(ABSPTLTP,U,5) ;Response reference
 S ABSPCLMI=$P(ABSPTLTP,U,4) ;Claim Reference
 Q:(ABSPRSMI="")!(ABSPCLMI="") 0
 S DO=$P(ABSPTLTP,U,9)  ;Position on claim(and response)
 I '$D(^ABSPR(ABSPRSMI,1000,DO)) S DO=$$GETDO^ABSPOSUU(ABSPRSMI,TLPART)
 Q:DO="" 0
 ;IHS/OIT/CASSEVERN/RAN 03/02/2011 patch 41 If there is a corrupted response just skip it rather than err out
 Q:'$D(^ABSPR(ABSPRSMI,1000,DO,500)) 0
 I $P(^ABSPR(ABSPRSMI,1000,DO,500),U)'="R" S ^TMP($J,"ABSPCLMS",TLPART)="" ;OIT/CAS/RCS - Patch 46, S ABSPCLMS($P(ABSPIRMI,"."))="" ;We only care about rejects in this report
 Q:$D(^TMP($J,"ABSPCLMS",TLPART)) 0  ;OIT/CAS/RCS - Patch 46, Q:$D(ABSPCLMS($P(ABSPIRMI,".")))
 S ABSPTINS=$P(ABSPTL(1),U,6)
 S ABSPPHM1=""
 I ABSPINS'="ALL" Q:ABSPTINS'=ABSPINS 0  ;NOT SELECTED INSURER
 I (ABSPPPHM'="ALL")&&($P(ABSPTL(1),U,7)'=ABSPPPHM) Q 0  ;NOT SELECTED PHARMACY
 S ABSPPHM1=ABSPPPHM
 I ABSPPPHM="ALL" S ABSPPHM1=$P(ABSPTL(1),U,7) ;SET PHARMACY
 I ABSPPHM1="" Q 0
 ;IHS/OIT/SCR 082109 START changes patch 34
 I '$D(^ABSPR(ABSPRSMI,1000,DO,511)) S (ABSPRNUM,ABSPREA)="UKN" ;Added to skip junk data in PMAA test area
 E  D  ;IHS/OIT/RCS 080913 patch 46 If Reject code missing, create unkown Reject description
 . S ABSPRNUM=$P(^ABSPR(ABSPRSMI,1000,DO,511,1,0),U)
 . I '$D(^ABSPF(9002313.93,"B",ABSPRNUM)) S ABSPREA="Reject Code description not entered,See NCPDP Rejects" Q  ;IHS/OIT/RCS PATCH 46
 . S ABSPREA=$P(^ABSPF(9002313.93,$O(^ABSPF(9002313.93,"B",ABSPRNUM,"")),0),U,2)
 I (ABSPREJ'="ALL")&&(ABSPREJX'=ABSPRNUM) S ABSPQUIT=1 Q 0
 S TMPARRAY("PHARMACY IEN")=ABSPPHM1
 S TMPARRAY("INSURER IEN")=ABSPTINS
 S TMPARRAY("INSURER NAME")=$$GET1^DIQ(9002313.4,ABSPTINS,.01)
 S TMPARRAY("INSURER HELP")=$$GET1^DIQ(9002313.4,ABSPTINS,100.05)
 S TMPARRAY("REJECTNUM")=ABSPRNUM
 S TMPARRAY("REJECTTXT")=ABSPREA
 S TMPARRAY("TRANSLOG ENTRY")=TLENTRY
 S (ABSPGRP,ABSPCARD)=""
 S ABSPCARD=$P($G(^ABSPC(ABSPCLMI,300)),U,2) ;TRANSACTION:CLAIM:Cardholder ID Number
 S TMPARRAY("CARDID")=$E(ABSPCARD,3,$L(ABSPCARD)) ;STRIP THE 2 CHARACTER QUALIFIER
 S ABSPGRP=$P($G(^ABSPC(ABSPCLMI,300)),U,1) ;TRANSACTION:CLAIM:Group Number
 S TMPARRAY("GROUPID")=$E(ABSPGRP,3,$L(ABSPGRP)) ;STRIP THE 2 CHARACTER QUALIFIER
 S ABSPRCNT=$P($G(ABSPREAS(ABSPRNUM,ABSPPHM1)),U)+1
 S ^TMP($J,"ABSPCLMS",TLPART)="" ;OIT/CAS/RCS - Patch 46, S ABSPCLMS($P(ABSPIRMI,"."))=""
 S ABSPREAS(ABSPRNUM,ABSPPHM1)=ABSPRCNT_U_ABSPRNUM_":"_ABSPREA
 S TMPARRAY("COST")=$$GET1^DIQ(9002313.57,ABSPTRNS,505)
 S TMPARRAY("AMT")="$"_$J($FN($$GET1^DIQ(9002313.57,ABSPTRNS,505),",",2),9)
 ; S TMPARRAY("AMT")=$$GET1^DIQ(9002313.57,ABSPTRNS,505)
 ; S TMPARRAY("AMT")=$P(ABSPTL(5),U,5)
 S TMPARRAY("CLAIM #")=$$GET1^DIQ(9002313.02,ABSPCLMI,.01)
 S TMPARRAY("PATIENTIEN")=$P(ABSPTLTP,U,6),TMPARRAY("CLAIMIEN")=ABSPCLMI
 S TMPARRAY("PATIENTNAME")=$$GET1^DIQ(9002313.57,ABSPTRNS,5)
 S TMPARRAY("FILL DATE")=$$HUMDATE^ABSPOSRE($$GET1^DIQ(9002313.57,ABSPTRNS,10401))
 S TMPARRAY("RELEASE DATE")=$$HUMDATE^ABSPOSRE($$GET1^DIQ(9002313.57,ABSPTRNS,9999.95))
 S TMPARRAY("TRANS DATE")=$P($$GET1^DIQ(9002313.02,ABSPCLMI,.05),"@")
 S TMPARRAY("RXIEN")=$$GET1^DIQ(9002313.57,ABSPTRNS,1.1199) ; ,ABSPRX ; RX IEN
 S ABSPRXR=$P($P(^ABSPC(ABSPCLMI,400,$P(^ABSPC(ABSPCLMI,400,0),U,3),400),U,3),"D3",2)  ;Refill Number
 S ABSPRX=$$GET1^DIQ(9002313.57,ABSPTRNS,1.11),TMPARRAY("RX #")=ABSPRX
 S NDCDRG=$$GTNDCDRG^ABSPOSUU(ABSPCLMI,$$GET1^DIQ(9002313.57,ABSPTRNS,1.1199))
 S TMPARRAY("NDC")=$P(NDCDRG,U,1)
 S TMPARRAY("DRUG NAME")=$P(NDCDRG,U,2)
 S TMPARRAY("CHART#")=$P($$GET1^DIQ(9002313.57,ABSPTRNS,9999.92)," ")
 S TMPARRAY("REJNUM")=+$$GET1^DIQ(9002313.57,ABSPTRNS,10510)
 S:TMPARRAY("REJNUM")>4 TMPARRAY("REJNUM")=4
 ; W TMPARRAY("REJNUM"),*9,ABSPTRNS,!
 F I=1:1:TMPARRAY("REJNUM") D
 . S TMPARRAY("REJ",I)=$P($$GET1^DIQ(9002313.57,ABSPTRNS,10511),",",I)_":"
 . S TMPARRAY("REJ",I)=TMPARRAY("REJ",I)_$$GET1^DIQ(9002313.57,ABSPTRNS,+("10511.0"_I))
 F I=1:1:4 S TMPARRAY("ADDINFO",I)=$G(^ABSPR(ABSPRSMI,1000,DO,526,I,0)) ; /IHS/OIT/RAM ; RETREIVE ANY ADDITIONAL INFO, UP TO 4.
 ; ZW TMPARRAY("REJ")
 S DOB=+$$GET1^DIQ(9002313.57,ABSPTRNS,10304)
 S X=DOB,%DT="T" D ^%DT
 I Y=-1 S DOB=$$GET1^DIQ(2,TMPARRAY("PATIENTIEN"),.03,"I"),X=DOB,%DT="T" D ^%DT S:Y=-1 DOB="INVALID DATE"
 S TMPARRAY("DOB")=$$HUMDATE^ABSPOSRE(DOB)
 M ^TMP("ABSPOSRZ",$J,$P(ABSPRDT,"."),ABSPPHM1,ABSPTINS,ABSPRNUM,TLENTRY)=TMPARRAY
 ; zw ^TMP("ABSPOSRZ",$J,$P(ABSPRDT,"."),ABSPPHM1,ABSPTINS,ABSPRNUM,ABSPIRMI)
 Q 1
 ;
HDR80(H) ; /IHS/OIT/RAM ; P52 ; NEW ROUTINE TO 'PRELOAD' HEADER COLUMNS FOR AN 80 COL. SCREEN.
 S H(1,1)="0^FILL DATE",H(1,2)="14^RELEASE DATE",H(1,3)="28^TRANS. DATE"
 S H(1,4)="42^RX IEN#",H(1,5)="53^RX #",H(1,6)="65^NDC #"
 S H(2,1)="0^CLAIM #",H(2,2)="19^DRUG NAME"
 S H(3,1)="0^GROUP #",H(3,2)="17^INSURER",H(3,3)="51^HELPDESK #",H(3,4)="66^BILLED AMT:"
 S H(4,1)="0^CHART#",H(4,2)="8^NAME:",H(4,3)="40^CARDHOLDER ID:",H(4,4)="62^INS DOB:"
 Q
HDR132(H) ; /IHS/OIT/RAM ; P52 ; NEW ROUTINE TO 'PRELOAD' HEADER COLUMNS FOR A 132 COL. SCREEN.
 S H(1,1)="0^FILL DATE",H(1,2)="14^RELEASE DATE",H(1,3)="28^TRANS. DATE"
 S H(1,4)="42^RX IEN#",H(1,5)="53^RX #",H(1,6)="65^NDC #",H(1,7)="78^DRUG NAME"
 S H(2,1)="0^CLAIM #",H(2,2)="19^GROUP #",H(2,3)="36^INSURER",H(2,4)="70^HELPDESK #",H(2,5)="86^BILLED AMT:"
 S H(3,1)="0^CHART#",H(3,2)="8^NAME:",H(3,3)="40^CARDHOLDER ID:",H(3,4)="62^INS DOB:"
 Q
HDR160(H) ; /IHS/OIT/RAM ; P52 ; NEW ROUTINE TO 'PRELOAD' HEADER COLUMNS FOR A 160 COL. SCREEN.
 S H(1,1)="0^FILL DATE",H(1,2)="14^RELEASE DATE",H(1,3)="28^TRANS. DATE",H(1,4)="42^RX IEN#"
 S H(1,5)="53^RX #",H(1,6)="65^NDC #",H(1,7)="78^DRUG NAME",H(1,8)="130^CLAIM #"
 S H(2,1)="0^GROUP #",H(2,2)="17^INSURER",H(2,3)="51^HELPDESK #",H(2,4)="66^BILLED AMT:"
 S H(2,5)="79^CHART#",H(2,6)="87^NAME:",H(2,7)="119^CARDHOLDER ID:",H(2,8)="141^INS DOB:"
 Q
DET80(VAR,H) ; /IHS/OIT/RAM ; P52 ; NEW ROUTINE TO 'PRELOAD' DETAIL COLUMNS FOR AN 80 COL. SCREEN.
 N I,I2,I3,J,L,P,P2,LP
 S LP=1
 S:$G(VAR)="" VAR="ONELINE"
 S H(1,1)="0^"_VAR_"(""FILL DATE"")",H(1,2)="14^"_VAR_"(""RELEASE DATE"")",H(1,3)="28^"_VAR_"(""TRANS DATE"")"
 S H(1,4)="42^"_VAR_"(""RXIEN"")",H(1,5)="53^"_VAR_"(""RX #"")",H(1,6)="65^"_VAR_"(""NDC"")"
 S H(2,1)="0^"_VAR_"(""CLAIM #"")",H(2,2)="19^"_VAR_"(""DRUG NAME"")"
 S H(3,1)="0^"_VAR_"(""GROUPID"")",H(3,2)="17^"_VAR_"(""INSURER NAME"")",H(3,3)="51^"_VAR_"(""INSURER HELP"")",H(3,4)="66^"_VAR_"(""AMT"")"
 S H(4,1)="0^"_VAR_"(""CHART#"")",H(4,2)="8^"_VAR_"(""PATIENTNAME"")",H(4,3)="40^"_VAR_"(""CARDID"")",H(4,4)="62^"_VAR_"(""DOB"")"
 I $G(REGOUT) F I=1:1:@VAR@("REJNUM") S H(I+4,1)="0^"_VAR_"(""REJ"","_I_")"
 D FIT80^ABSPOSRE ; AS THE DET80 & DET132 USE THE SAME LOGIC FOR THE ADDITIONAL INFO, MAKE SINGLE SUBROUTINE.
 ;
 Q
DET132(VAR,H) ; /IHS/OIT/RAM ; P52 ; NEW ROUTINE TO 'PRELOAD' DETAIL COLUMNS FOR A 132 COL. SCREEN.
 N I,I2,I3,J,L,P,P2,LP
 S LP=1
 S:$G(VAR)="" VAR="ONELINE"
 S H(1,1)="0^"_VAR_"(""FILL DATE"")",H(1,2)="14^"_VAR_"(""RELEASE DATE"")",H(1,3)="28^"_VAR_"(""TRANS DATE"")"
 S H(1,4)="42^"_VAR_"(""RXIEN"")",H(1,5)="53^"_VAR_"(""RX #"")",H(1,6)="65^"_VAR_"(""NDC"")",H(1,7)="78^"_VAR_"(""DRUG NAME"")"
 S H(2,1)="0^"_VAR_"(""CLAIM #"")",H(2,2)="19^"_VAR_"(""GROUPID"")",H(2,3)="36^"_VAR_"(""INSURER NAME"")",H(2,4)="70^"_VAR_"(""INSURER HELP"")",H(2,5)="86^"_VAR_"(""AMT"")"
 S H(3,1)="0^"_VAR_"(""CHART#"")",H(3,2)="8^"_VAR_"(""PATIENTNAME"")",H(3,3)="40^"_VAR_"(""CARDID"")",H(3,4)="62^"_VAR_"(""DOB"")"
 I $G(REGOUT) F I=1:1:@VAR@("REJNUM") S H(I+3,1)="0^"_VAR_"(""REJ"","_I_")"
 D FIT80^ABSPOSRE ; AS THE DET80 & DET132 USE THE SAME LOGIC FOR THE ADDITIONAL INFO, MAKE SINGLE SUBROUTINE.
 ;
 Q
 ;
DET160(VAR,H) ; /IHS/OIT/RAM ; P52 ; NEW ROUTINE TO 'PRELOAD' DETAIL COLUMNS FOR A 160 COL. SCREEN.
 N I,I2,I3,J,L,P,P2,LP
 S LP=1
 S:$G(VAR)="" VAR="ONELINE"
 S H(1,1)="0^"_VAR_"(""FILL DATE"")",H(1,2)="14^"_VAR_"(""RELEASE DATE"")",H(1,3)="28^"_VAR_"(""TRANS DATE"")",H(1,4)="42^"_VAR_"(""RXIEN"")"
 S H(1,5)="53^"_VAR_"(""RX #"")",H(1,6)="65^"_VAR_"(""NDC"")",H(1,7)="78^"_VAR_"(""DRUG NAME"")",H(1,8)="130^"_VAR_"(""CLAIM #"")"
 S H(2,1)="0^"_VAR_"(""GROUPID"")",H(2,2)="17^"_VAR_"(""INSURER NAME"")",H(2,3)="51^"_VAR_"(""INSURER HELP"")",H(2,4)="66^"_VAR_"(""AMT"")"
 S H(2,5)="79^"_VAR_"(""CHART#"")",H(2,6)="87^"_VAR_"(""PATIENTNAME"")",H(2,7)="119^"_VAR_"(""CARDID"")",H(2,8)="141^"_VAR_"(""DOB"")"
 I $G(REGOUT) F I=1:1:@VAR@("REJNUM") S H(I+2,1)="0^"_VAR_"(""REJ"","_I_")"
 ; S I=I+1 ; /IHS/OIT/RAM INCREMENT I TO CONTINUE AS A LINE COUNTER.
 S P=@VAR@("REJNUM")+4,P2=1,I2=0
 F I=1:1:4 D
 . I $G(@VAR@("ADDINFO",I))="" Q
 . S L(I)=$L($G(@VAR@("ADDINFO",I)))
 . S I2=I2+L(I)
 I $G(L(1))="" Q
 S H(P+P2,1)="0^"_VAR_"(""ADDINFO"",1)"
 I $G(L(2))="" Q
 ;
 I I2<156 D  Q
 . S H(P+P2,2)=$G(L(1))+1_"^"_VAR_"(""ADDINFO"",2)"
 . I +$G(L(3))>0 S H(P+P2,3)=$G(L(1))+$G(L(2))+2_"^"_VAR_"(""ADDINFO"",3)"
 . I +$G(L(4))>0 S H(P+P2,4)=$G(L(1))+$G(L(2))+$G(L(3))+3_"^"_VAR_"(""ADDINFO"",4)"
 ;
 I $G(L(1))+$G(L(2))<80 S H(P+P2,2)=$G(L(1))+1_"^"_VAR_"(""ADDINFO"",2)",P2=P2+1,LP=0
 E  S P2=P2+1,H(P+P2,1)="0^"_VAR_"(""ADDINFO"",2)",LP=1
 I $G(L(3))="" Q
 I LP&($G(L(2))+$G(L(3))<80) S H(P+P2,2)=$G(L(2))+1_"^"_VAR_"(""ADDINFO"",3)",P2=P2+1,LP=0
 E  S P2=P2+1,H(P+P2,1)="0^"_VAR_"(""ADDINFO"",3)",LP=1
 I $G(L(4))="" Q
 I LP&($G(L(3))+$G(L(4))<80) S H(P+P2,2)=$G(L(3))+1_"^"_VAR_"(""ADDINFO"",4)"
 E  S P2=P2+1,H(P+P2,1)="0^"_VAR_"(""ADDINFO"",4)"
 ;
 Q
 ;
PRNTDTL  ;PRINT DETAILED REPORT
 N ABSPCARD,ABSPFRDT,ABSPGRP,ABSPNDC,ABSPDRNM,ABSPQUIT
 N ABSPWRIT,ABSPOUT,NDCDRG,ABSPCLMI,Y,ABSPTMP,I,I2,J,J2,J3,K,K2,ONELINE,VAR,OUT,L1
 S (ABSPPRDT,ABSPPPHM,ABSPPRNM,ABSPNDC,ABSPDRNM)=""
 ;IHS/OIT/CNI/RAN 04282010 patch 39 - Add NDC # and Drug name on next two lines and New line above
 S (ABSPRTOT,ABSPGTOT,ABSPRDTL,ABSPQUIT,ABSPOUT)=0
 I ABSPRTYP="S" D ZEND^ABSPOSRE Q
 N WIDTH,ROUTINE,HDR,I,I2,I3,J,J2,J3,K
 S WIDTH=$S($G(IOM)>159:160,$G(IOM)>131:132,1:80)
  I ABSPRTYP="T" D DELIMHDR^ABSPOSRE
 E  D
 . S ROUTINE="D HDR"_WIDTH_"(.HDR)"
 . X ROUTINE
 ; S ROUTINE="D DET"_WIDTH_"(.HDR)"
 ; X ROUTINE
 S ABSPWRIT=$$DATECUPR^ABSPOSRE(ABSPRDAT)
 F  S ABSPPRDT=$O(^TMP("ABSPOSRZ",$J,ABSPPRDT)) Q:(ABSPPRDT="")!(ABSPOUT)  D
 .N ABSPTMP
 .M ABSPTMP=^TMP("ABSPOSRZ",$J,ABSPPRDT)
 .S ABSPPPHM=""
 .S Y=ABSPPRDT
 .D DD^%DT
 .S ABSPFRDT=Y   ; FORMATTED RELEASE DATE
 .S ABSPRDTL=0
 .F  S ABSPPPHM=$O(ABSPTMP(ABSPPPHM)) Q:(ABSPPPHM="")!(ABSPOUT)  D
 ..S ABSPPINS=""
 ..S ABSPPHMN=$P(^ABSP(9002313.56,ABSPPPHM,0),U,1)
 ..I ABSPRTYP="D" D PRNTDHD^ABSPOSRE ;; /IHS/OIT/RAM ; ONLY PRINT HEADERS IF DETAILED REPORT, NOT DELIMITED.
 ..Q:ABSPOUT
 ..;IHS/OIT/CNI/RAN 04272010 patch 39 - When printing to screen, use paging
 ..; /IHS/OIT/RAM ; ONLY PRINT HEADERS IF DETAILED REPORT, NOT DELIMITED.
 ..I ABSPRTYP="D" S ABSPOUT=$$WRITE^ABSPOSUU("!!,?5,""PHARMACY: "",ABSPPHMN,"" "",ABSPWRIT,"" DATE: "",ABSPFRDT")
 ..Q:ABSPOUT
 ..S ABSPBTOT=0
 ..F  S ABSPPINS=$O(ABSPTMP(ABSPPPHM,ABSPPINS)) Q:(ABSPPINS="")!(ABSPOUT)  D
 ...S ABSPPRNM=""
 ...F  S ABSPPRNM=$O(ABSPTMP(ABSPPPHM,ABSPPINS,ABSPPRNM)) Q:(ABSPPRNM="")!(ABSPOUT)  D
 ....S ABSPPRMI=""
 ....S ABSPRJCD=$P($G(ABSPREAS(""_ABSPPRNM_"",ABSPPPHM)),U,2)
 ....;IHS/OIT/CNI/RAN 04272010 patch 39 - When printing to screen, use paging
 ....I ABSPRTYP="D" S ABSPOUT=$$WRITE^ABSPOSUU("!!,?15,""REJECTION CODE: "",$E(ABSPRJCD,1,48)") ;; /IHS/OIT/RAM ; ONLY PRINT HEADERS IF DETAILED REPORT, NOT DELIMITED.
 ....Q:ABSPOUT
 ....F  S ABSPPRMI=$O(ABSPTMP(ABSPPPHM,ABSPPINS,ABSPPRNM,ABSPPRMI)) Q:(ABSPPRMI="")!(ABSPOUT)  D
 .....S (ABSPPCHT,ABSPPDIV,ABSPOPS)=""
 .....K ONELINE M ONELINE=ABSPTMP(ABSPPPHM,ABSPPINS,ABSPPRNM,ABSPPRMI)
 .....; ZW ONELINE
 .....S ABSPPTP=ONELINE("COST"),REJNUM=ONELINE("REJNUM")
 .....S VAR="ONELINE"
 .....I ABSPRTYP="T" D
 ...... K OUT
 ...... D DELIMOUT^ABSPOSRE(VAR,.OUT)
 ...... S I=0 F  S I=$O(OUT(I)) Q:+I=0  D
 ....... I I'=1 W "^"
 ....... S J3="S J2="_OUT(I) X J3 S ABSPOUT=$$WRITE^ABSPOSUU("J2") Q:ABSPOUT
 ...... S ABSPOUT=$$WRITE^ABSPOSUU("!") Q:ABSPOUT
 .....E  D  Q:ABSPOUT
 ...... K OUT
 ...... S ROUTINE="D DET"_WIDTH_"(VAR,.OUT)"
 ...... X ROUTINE
 ...... ; W !!
 ...... ; S ABSPOUT=$$WRITE^ABSPOSUU("!!,$$CTR^ABSPMHDR(""** Place Holder - what should this read? **"",WIDTH),!!")
 ...... S ABSPOUT=$$WRITE^ABSPOSUU("!!")
 ...... Q:ABSPOUT
 ...... ; ZW OUT
 ...... S I=0 F  S I=$O(OUT(I)) Q:+I=0!(ABSPOUT)  D
 ....... S J=0 F  S J=$O(OUT(I,J)) Q:+J=0!(ABSPOUT)  D
 ........ S J3="S J2="_$P(OUT(I,J),"^",2) X J3 S ABSPOUT=$$WRITE^ABSPOSUU("?+$P(OUT(I,J),""^""),J2") Q:ABSPOUT
 ....... Q:ABSPOUT
 ....... S ABSPOUT=$$WRITE^ABSPOSUU("!") Q:ABSPOUT
 .....S ABSBPRTT=ABSPRTOT+ABSPPTP
 .....S ABSPBTOT=ABSPBTOT+ABSPPTP
 .....S ABSPRDTL=ABSPRDTL+ABSPPTP
 ...Q:ABSPOUT
 ..Q:ABSPOUT
 ..;IHS/OIT/CNI/RAN 04272010 patch 39 - When printing to screen, use paging
 ..;  /IHS/OIT/RAM ; ONLY PRINT FOOTERS IF DETAILED REPORT, NOT DELIMITED.
 ..I ABSPRTYP="D" S ABSPOUT=$$WRITE^ABSPOSUU("!!,""TOTAL FOR "",ABSPPHMN,"": $"",$J($FN(ABSPBTOT,"","",2),6),!")
 . Q:ABSPOUT
 .;IHS/OIT/CNI/RAN 04272010 patch 39 - When printing to screen, use paging
 .; /IHS/OIT/RAM ; ONLY PRINT FOOTERS IF DETAILED REPORT, NOT DELIMITED.
 . I '((ABSPRDTL=0)&ZEROSUPP) D
 . . I ABSPRTYP="D" S ABSPOUT=$$WRITE^ABSPOSUU("!!,""TOTAL FOR "",ABSPWRIT,"" DATE "",ABSPFRDT,"": $"",$J($FN(ABSPRDTL,"","",2),6)")
 . Q:ABSPOUT
 . S ABSPGTOT=ABSPGTOT+ABSPRDTL
 Q:ABSPOUT
 ;IHS/OIT/CNI/RAN 04272010 patch 39 - When printing to screen, use paging
 ;  /IHS/OIT/RAM ; ONLY PRINT FOOTERS IF DETAILED REPORT, NOT DELIMITED.
 I $G(ABSPRTYP)="D" S ABSPOUT=$$WRITE^ABSPOSUU("!!,""TOTAL AMOUNT REJECTED: $"",$J($FN(ABSPGTOT,"","",2),6),!!")
 Q
 ;
