BRAPCC2 ;IHS/CMI/DAY - RADIOLOGY PCC LINK - Part 2 ; 25 Jan 2017  11:08 AM
 ;;5.0;Radiology/Nuclear Medicine;**1007,1009**;Mar 16, 1998;Build 21
 ;
 Q
 ;
 ;
EN ;EP - Called from BRAPCC
 ;
 I $G(PCCVRAD)="" Q
 ;
 ;IHS/CMI/LAB - patch 1009 04/12/21 CR #10047, lets fix visit ien in Radiology if it doesn't match PCC
 NEW V,VRADV,RAFDA,ERR
 S V=$P($G(^AUPNVRAD(PCCVRAD,0)),U,3)  ;V RAD VISIT IEN
 S VRADV=$P($G(^RADPT(RADFN,"DT",RADTI,"P",RAXM,"PCC")),U,3)
 I V'=VRADV D
 .S RAFDA($J,70.03,""_RAXM_","_RADTI_","_RADFN_",",197)=V
 .D FILE^DIE("E","RAFDA($J)","RAFDA($J,""ERR"")")
 ;
 ;IHS/BJI/DAY - Patch 1007 - Update V Rad procedure if changed
 ;
 N DIE,DA,DR,DQ,DO
 ;
 N BRAPRCR,BRAPRCV
 S BRAPRCR=$P($G(^RADPT(RADFN,"DT",RADTI,"P",RAXM,0)),U,2)
 S BRAPRCV=$P($G(^AUPNVRAD(PCCVRAD,0)),U)
 I +BRAPRCR,+BRAPRCV,BRAPRCR'=BRAPRCV D
 .;
 .K DIE,DA,DR,DQ,DO
 .S DIE="^AUPNVRAD(",DA=PCCVRAD,DR=".01///`"_BRAPRCR_";1218////"_$$NOW^XLFDT
 .L +^AUPNVRAD(PCCVRAD):0 I '$T Q
 .D ^DIE
 .L -^AUPNVRAD(PCCVRAD)
 .K DIE,DA,DR,DQ,DO
 .;
 .S AUPNVSIT=$P($G(^AUPNVRAD(PCCVRAD,0)),U,3)
 .I +AUPNVSIT D MOD^AUPNVSIT
 .K AUPNVSIT
 ;
 ;End Patch
 ;
 ;IHS/CMI/DAY - Patch 1007 - Update CPT Modifiers in V Radiology
 ;
 ;IHS/BJI//LAB 04/12/2021 - Patch 1009 CR# 8970 - update procedure modifiers in V RAD
 ;before we do this we really should wipe out the existing ones in case 1 was deleted
 K DIE,DA,DR,DQ,D0,DO
 S DIE="^AUPNVRAD(",DA=PCCVRAD,DR=".07///@;.08///@;.11///@;.12///@"_";1218////"_$$NOW^XLFDT
 L +^AUPNVRAD(PCCVRAD):0 I '$T Q
 D ^DIE
 L -^AUPNVRAD(PCCVRAD)
 K DIE,DIR,DA,DR,DQ,DO
 ;
 NEW BRAMCTR,BRAMIEN,BRACPTM,BRACPTI
 ;
 S BRACPTM(1)="",BRACPTM(2)=""
 S BRAMCTR=0
 S BRAMIEN=0
 F  S BRAMIEN=$O(^RADPT(RADFN,"DT",RADTI,"P",RAXM,"CMOD",BRAMIEN)) Q:'BRAMIEN  D
 .;
 .S BRACPTI=$P($G(^RADPT(RADFN,"DT",RADTI,"P",RAXM,"CMOD",BRAMIEN,0)),U)
 .I BRACPTI="" Q
 .S BRAMCTR=BRAMCTR+1
 .I BRAMCTR>2 Q
 .S BRACPTM(BRAMCTR)=BRACPTI
 ;
 I +BRACPTM(1) D
 .;
 .K DIE,DA,DR,DQ,DO
 .S DIE="^AUPNVRAD(",DA=PCCVRAD,DR=".07///`"_BRACPTM(1)_";1218////"_$$NOW^XLFDT
 .L +^AUPNVRAD(PCCVRAD):0 I '$T Q
 .D ^DIE
 .L -^AUPNVRAD(PCCVRAD)
 .K DIR,DIE,DA,DR,DQ,DO
 .;
 .S AUPNVSIT=$P($G(^AUPNVRAD(PCCVRAD,0)),U,3)
 .I +AUPNVSIT D MOD^AUPNVSIT
 .K AUPNVSIT
 ;
 I +BRACPTM(2) D
 .;
 .K DIE,DA,DR,DQ,DO
 .S DIE="^AUPNVRAD(",DA=PCCVRAD,DR=".08///`"_BRACPTM(2)_";1218////"_$$NOW^XLFDT
 .L +^AUPNVRAD(PCCVRAD):0 I '$T Q
 .D ^DIE
 .L -^AUPNVRAD(PCCVRAD)
 .K DIE,DA,DR,DQ,DO
 .;
 .S AUPNVSIT=$P($G(^AUPNVRAD(PCCVRAD,0)),U,3)
 .I +AUPNVSIT D MOD^AUPNVSIT
 .K AUPNVSIT
 ;
 ;End Patch
 ;ADD PROCEDURE MODIFIERS IHS/CMI/LAB - 04/12/21 patch 1009 cr# 8970
 S BRACPTM(1)="",BRACPTM(2)=""
 S BRAMCTR=0
 S BRAMIEN=0
 F  S BRAMIEN=$O(^RADPT(RADFN,"DT",RADTI,"P",RAXM,"M",BRAMIEN)) Q:'BRAMIEN  D
 .;
 .S BRACPTI=$P($G(^RADPT(RADFN,"DT",RADTI,"P",RAXM,"M",BRAMIEN,0)),U)
 .I BRACPTI="" Q
 .S BRAMCTR=BRAMCTR+1
 .I BRAMCTR>2 Q
 .S BRACPTM(BRAMCTR)=BRACPTI
 ;
 I +BRACPTM(1) D
 .;
 .K DIE,DA,DR,DQ,DO
 .S DIE="^AUPNVRAD(",DA=PCCVRAD,DR=".11///`"_BRACPTM(1)_";1218////"_$$NOW^XLFDT
 .L +^AUPNVRAD(PCCVRAD):0 I '$T Q
 .D ^DIE
 .L -^AUPNVRAD(PCCVRAD)
 .K DIE,DIR,DA,DR,DQ,DO
 .;
 .S AUPNVSIT=$P($G(^AUPNVRAD(PCCVRAD,0)),U,3)
 .I +AUPNVSIT D MOD^AUPNVSIT
 .K AUPNVSIT
 ;
 I +BRACPTM(2) D
 .;
 .K DIE,DA,DR,DQ,DO
 .S DIE="^AUPNVRAD(",DA=PCCVRAD,DR=".12///`"_BRACPTM(2)_";1218////"_$$NOW^XLFDT
 .L +^AUPNVRAD(PCCVRAD):0 I '$T Q
 .D ^DIE
 .L -^AUPNVRAD(PCCVRAD)
 .K DIE,DA,DR,DQ,DO
 .;
 .S AUPNVSIT=$P($G(^AUPNVRAD(PCCVRAD,0)),U,3)
 .I +AUPNVSIT D MOD^AUPNVSIT
 .K AUPNVSIT
 ;
 Q
 ;
FIXVP(BRADPT,BRAD,BRAI,VRAD) ;EP - CALLED TO FIX VISIT POINTER
 ;IHS/CMI/LAB - patch 1009 04/12/21 CR #10047, lets fix visit ien in Radiology if it doesn't match PCC
 ;BRADPT = PATIENT DFN
 ;BRAD = DATE/TIME
 ;BRAI = IEN OF EXAM IN MULTIPLE
 ;VRAD  - PCC V RAD IEN
 ;
 NEW V,RADV,RAFDA,ERR
 S V=$P($G(^AUPNVRAD(VRAD,0)),U,3)  ;V RAD VISIT IEN
 S RADV=$P($G(^RADPT(BRADPT,"DT",BRAD,"P",BRAI,"PCC")),U,3)
 I V'=RADV D
 .S RAFDA($J,70.03,""_BRAI_","_BRAD_","_BRADPT_",",197)=V
 .D FILE^DIE("E","RAFDA($J)","RAFDA($J,""ERR"")")
 Q
TEST ;
 S P=5387
 S D="6789587.8767"
 S I=2
 S VR=1096
 D FIXVP(P,D,I,VR)
 Q
