BDMDI10 ; IHS/CMI/LAB -IHS -GETS DATA FOR DIABETES QA REPORT 19 Dec 2016 1:31 PM ; 17 Jan 2021  1:34 PM
 ;;2.0;DIABETES MANAGEMENT SYSTEM;**14**;JUN 14, 2007;Build 80
 ;
 ;
EN ; - ENTRY POINT - from ^BDMASK
 ;
 D BUILDSML^BDMUTL(2021)
 K ^BDMDATA("BDMEPI",$J)
 S ^XTMP("BDMDM21",0)=$$FMADD^XLFDT(DT,14)_"^"_DT_"^DM AUDIT 2021"
 S ^XTMP("BDMDM21 ERRORS",0)=$$FMADD^XLFDT(DT,14)_"^"_DT_"^DM AUDIT 2021 DATA QUALITY CHECK"
 S BDMEPIN=0,BDMECNT=0
 I BDMTYPE="E" G EAUDIT
 S BDMPD=0 F  S BDMPD=$O(^XTMP("BDMDM21",BDMJOB,BDMBTH,"PATS",BDMPD)) Q:'BDMPD  D
 .I BDMTYPE'="P" I $$DEMO^BDMUTL(BDMPD,$G(BDMDEMO)) Q
 .I BDMPREP=2 D EPIREC Q
 .I BDMPREP=6 D EPICHK^BDMDI1J Q
 .D GATHER
 I BDMPREP=2 D WRITEF^BDMDI1 Q
 I BDMPREP=3!(BDMPREP=4) D CUML^BDMDI15
 I BDMPREP=5 D SDPI16^BDMDI1R
 Q
S(P,I,V) ;
 S ^XTMP("BDMDM21",BDMJOB,BDMBTH,"AUDIT",P,I)=V
 Q
REC(DFN,BDMRTYP,BDMRBD,BDMRED,BDMED,BDMDMRG,BDMBDAT) ;EP - called to send back a visit record as
 NEW BDMX,BDMREC
 S BDMREC=""
 S BDMRTYP("IEN")=$O(^BDMRECD("B",BDMRTYP,0))
 I 'BDMRTYP("IEN") Q BDMREC
PROC ;
 S BDMEPIX=0
 F  S BDMEPIX=$O(^BDMRECD(BDMRTYP("IEN"),11,"AC",BDMEPIX)) Q:BDMEPIX'=+BDMEPIX!(BDMREC=-1)  S BDMTTT=$O(^BDMRECD(BDMRTYP("IEN"),11,"AC",BDMEPIX,0))  D
 .S X="" X:$D(^BDMRECD(BDMRTYP("IEN"),11,BDMTTT,11)) ^BDMRECD(BDMRTYP("IEN"),11,BDMTTT,11)
 .I X="" S X=" "
 .S $P(BDMREC,U,$P(^BDMRECD(BDMRTYP("IEN"),11,BDMTTT,0),U,2))=X  ;I DUZ=2881 W !,BDMTTT,?5,$P(^BDMRECD(BDMRTYP("IEN"),11,BDMTTT,0),U),?40,X
 ;W !!,BDMREC
 Q BDMREC
EPIREC ;create epi info record in ^BDMDATA("BDMEPI",$J,n)
 ;skip this patient if dodx is greater than the audit date
 S X=$$DODX^BDMDI16(BDMPD,BDMDMRG,"I",$G(BDMMULTR),.BDMREGLT)
 I X>BDMADAT Q
 S BDMEPIR="",BDMTHER=""
 S BDMEPIR=$$REC(BDMPD,"DM AUDIT 2021 EXPORT RECORD",BDMRBD,BDMRED,BDMADAT,BDMDMRG,BDMBDAT),BDMEPIN=BDMEPIN+1,^BDMDATA("BDMEPI",$J,BDMEPIN)=BDMEPIR
 Q
GATHER ;gather data for 1 patient
 S BDMER=0
HEADER ; Set node with report header info
 ;set report dates
 S ^XTMP("BDMDM21",BDMJOB,BDMBTH,"AUDIT",BDMPD,1)=BDMRBD_" - "_BDMRED
 ;set audit date to DT
 S ^XTMP("BDMDM21",BDMJOB,BDMBTH,"AUDIT",BDMPD,2)=$$FMTE^XLFDT(DT)
 ;reviewer
 S ^XTMP("BDMDM21",BDMJOB,BDMBTH,"AUDIT",BDMPD,14)=$P(^VA(200,DUZ,0),U,2)  ;reviewer initials
 S ^XTMP("BDMDM21",BDMJOB,BDMBTH,"AUDIT",BDMPD,122)=$$COMM(BDMPD)
 S ^XTMP("BDMDM21",BDMJOB,BDMBTH,"AUDIT",BDMPD,121)=$S($P($G(^DPT(BDMPD,.11)),U,5):$P($G(^DIC(5,$P(^DPT(BDMPD,.11),U,5),0)),U,2),1:"")  ;state of residence
 S ^XTMP("BDMDM21",BDMJOB,BDMBTH,"AUDIT",BDMPD,15)=$$VAL^XBDIQ1(9000001,BDMPD,.14)  ;primary care provider
DEMO ;pat demographics
 S ^XTMP("BDMDM21",BDMJOB,BDMBTH,"AUDIT",BDMPD,16)=$$HRN^AUPNPAT(BDMPD,$S($G(BDMDUZ2):BDMDUZ2,1:DUZ(2)))  ;hrn
 S ^XTMP("BDMDM21",BDMJOB,BDMBTH,"AUDIT",BDMPD,18)=$$DOB^AUPNPAT(BDMPD,"E")  ;dob
 S ^XTMP("BDMDM21",BDMJOB,BDMBTH,"AUDIT",BDMPD,20)=$$VAL^XBDIQ1(2,BDMPD,.02)  ;sex
DXDT ;dates of and dm dxs
 S ^XTMP("BDMDM21",BDMJOB,BDMBTH,"AUDIT",BDMPD,22)=$$CMSFDX^BDMDI13(BDMPD,BDMDMRG,"D",$G(BDMMULTR),.BDMREGLT)
 S ^XTMP("BDMDM21",BDMJOB,BDMBTH,"AUDIT",BDMPD,24)=$$CMSFDX^BDMDI13(BDMPD,BDMDMRG,"DX",$G(BDMMULTR),.BDMREGLT)
 S ^XTMP("BDMDM21",BDMJOB,BDMBTH,"AUDIT",BDMPD,23)=$$PLDMDOO^BDMDI13(BDMPD)
 D S(BDMPD,25,$$PLDMDXS^BDMDI13(BDMPD))
 D S(BDMPD,21,$$FRSTDMDX^BDMDI13(BDMPD))
 D S(BDMPD,26,$$LASTDMDX^BDMDI13(BDMPD,BDMRED))
 I $$DODX^BDMDI16(BDMPD,BDMDMRG,"I",$G(BDMMULTR),.BDMREGLT)>BDMADAT D S(BDMPD,26.5,"*** Patient's Date of Onset is after the audit date.") D
 .D S(BDMPD,26.6,"**** This patient will not be included in the cumulative audit.")
 S BDMTYDM="" D TYPEDM,S(BDMPD,29,BDMTYDM)
 D S(BDMPD,27,$$TOBACCO^BDMDI1T(BDMPD,$$DOB^AUPNPAT(BDMPD),BDMADAT))
 D S(BDMPD,215,$$TOBACCO^BDMDI1T(BDMPD,BDMBDAT,BDMADAT))
 D S(BDMPD,28,$$CESS^BDMDI11(BDMPD,BDMBDAT,BDMADAT))
 D S(BDMPD,31,$$ENDS^BDMDI1T(BDMPD,BDMBDAT,BDMADAT))   ;LORI
 D S(BDMPD,33,$$LASTENDS^BDMDI1T(BDMPD,$$DOB^AUPNPAT(BDMPD),BDMADAT))  ;;LORI
 ;
VITAL ;
 D S(BDMPD,30,$$LASTHT^BDMDI13(BDMPD,BDMRED))
 D S(BDMPD,32,$$LASTWT^BDMDI13(BDMPD,BDMBDAT,BDMADAT))
 D S(BDMPD,112,$$BMI^BDMDI18(BDMPD,BDMRBD,BDMRED))
 ;htn dx
 D S(BDMPD,34,$$HTNDX^BDMDI13(BDMPD,BDMADAT))
 ;last 3 BPs
 D S(BDMPD,36,$$BPS^BDMDI13(BDMPD,BDMRBD,BDMRED))
EXAMS ;
 D S(BDMPD,38,$$DFE^BDMDI17(BDMPD,BDMBDAT,BDMADAT))
 D S(BDMPD,40,$$EYE^BDMDI17(BDMPD,BDMBDAT,BDMADAT))
 D S(BDMPD,42,$$DENTAL^BDMDI17(BDMPD,BDMBDAT,BDMADAT))
MH ;MH
 D S(BDMPD,200,$$DEPDX^BDMDI12(BDMPD,BDMBDAT,BDMADAT))
 S BDMDIP=$E($G(^XTMP("BDMDM21",BDMJOB,BDMBTH,"AUDIT",BDMPD,200)))
 D S(BDMPD,210,$S(BDMDIP="1":"",1:$$DEPSCR^BDMDI12(BDMPD,BDMBDAT,BDMADAT)))
 ;EDUC
 D S(BDMPD,44,$$DIETEDUC^BDMDI17(BDMPD,BDMRBD,BDMRED))
 D S(BDMPD,46,$$EXEDUC^BDMDI17(BDMPD,BDMRBD,BDMRED))
 D S(BDMPD,48,$$OTHEDUC^BDMDI17(BDMPD,BDMRBD,BDMRED))
THERAPY ;
 S BDM6MBD=$$FMADD^XLFDT(BDMADAT,-(6*31)) ;,BDM6MBD=$$FMTE^XLFDT(BDM6MBD)
 D S(BDMPD,52,$$INSULIN^BDMDI12(BDMPD,BDM6MBD,BDMRED))
 D S(BDMPD,53,$$SULF^BDMDI12(BDMPD,BDM6MBD,BDMRED))
 D S(BDMPD,98,$$SULFLIKE^BDMDI12(BDMPD,BDM6MBD,BDMRED))  ;REPAG
 D S(BDMPD,54,$$MET^BDMDI12(BDMPD,BDM6MBD,BDMRED))
 D S(BDMPD,55,$$ACAR^BDMDI12(BDMPD,BDM6MBD,BDMRED))
 D S(BDMPD,56,$$TROG^BDMDI12(BDMPD,BDM6MBD,BDMRED))
 ;D S(BDMPD,58,$$INCR^BDMDI12(BDMPD,BDM6MBD,BDMRED))
 D S(BDMPD,59,$$DPP4^BDMDI12(BDMPD,BDM6MBD,BDMRED))
 D S(BDMPD,99,$$AMYLIN^BDMDI12(BDMPD,BDM6MBD,BDMRED))
 D S(BDMPD,100,$$GLP1^BDMDI12(BDMPD,BDM6MBD,BDMRED))
 D S(BDMPD,101,$$BROM^BDMDI12(BDMPD,BDM6MBD,BDMRED))
 D S(BDMPD,102,$$COLE^BDMDI12(BDMPD,BDM6MBD,BDMRED))
 D S(BDMPD,103,$$SGLT2^BDMDI12(BDMPD,BDM6MBD,BDMRED))
 S Z="" F X=52:1:56,59,98,99,100,101,102,103 I $E($G(^XTMP("BDMDM21",BDMJOB,BDMBTH,"AUDIT",BDMPD,X)))="X" S Z=1  ;ANY MED AT ALL?
 ;S Y=$$REFMED^BDMDI12(BDMPD,BDMRBD,BDMRED) S Y=$S(Z:"",Y="":"",1:"X"_U_$P(Y,U,2)) D S(BDMPD,57,Y)  ;REFUSAL OF A MED
 S Y="" F X=52:1:56,59,98,99,100,101,102,103 I $E($G(^XTMP("BDMDM21",BDMJOB,BDMBTH,"AUDIT",BDMPD,X)))="X" S Y=1  ;cmi/maw 6/17/2014 per gary
 D S(BDMPD,51,$S(Y:"",1:"X"))
 D S(BDMPD,60,$$ACE^BDMDI16(BDMPD,BDM6MBD,BDMADAT))
 D S(BDMPD,62,$$ASPIRIN^BDMDI16(BDMPD,BDM6MBD,BDMADAT))
 D S(BDMPD,300,$$STATIN^BDMDI16(BDMPD,BDM6MBD,BDMADAT))
 D S(BDMPD,116,$$CVD^BDMDI12(BDMPD,BDMADAT))
 ;
PPD ;
 D S(BDMPD,71,$$TBDX^BDMDI18(BDMPD,BDMADAT))   ;1^DISPLAY VALUE
 ;I DUZ=2881,$E($$TBDX^BDMDI18(BDMPD,BDMADAT))=1 S LORITBC=$G(LORITBC)+1 W LORITBC,"."
 D S(BDMPD,70,$$PPD^BDMDI18(BDMPD,BDMADAT))    ;LAST TB TEST 
 D S(BDMPD,114,$$LASTNP^BDMDI18(BDMPD,BDMADAT))
 I $E($G(^XTMP("BDMDM21",BDMJOB,BDMBTH,"AUDIT",BDMPD,71)))=1!($E($P($G(^XTMP("BDMDM21",BDMJOB,BDMBTH,"AUDIT",BDMPD,70)),"||",2))=1) D S(BDMPD,72,$$TBTX^BDMDI12(BDMPD,BDMADAT))
HEPC ;
 D S(BDMPD,222,$$HEPCDX^BDMDI1D(BDMPD,BDMADAT))
 D S(BDMPD,223,$$HEPSCR^BDMDI1D(BDMPD,BDMADAT))
 D S(BDMPD,224,$$DMRETDX^BDMDI1D(BDMPD,BDMADAT))
 ;amputation new in dm19
 D S(BDMPD,230,$$LEAMP^BDMDI1D(BDMPD,BDMADAT))
 ;
IMM ;
 D S(BDMPD,64,$$FLU^BDMDI13(BDMPD,BDMBDAT,BDMADAT))
 D S(BDMPD,66,$$PNEU^BDMDI13(BDMPD,BDMADAT))
 D S(BDMPD,68,$$TD^BDMDI1B(BDMPD,BDMADAT))
 D S(BDMPD,216,$$TDAP^BDMDI1B(BDMPD,BDMADAT,,1))
 D S(BDMPD,115,$$HEP^BDMDI13(BDMPD,BDMADAT,1))
 D S(BDMPD,73,$$SHINGRIX^BDMDI19(BDMPD,$$DOB^AUPNPAT(BDMPD),BDMADAT,1))
LABS ;
 D S(BDMPD,78,$$HGBA1C^BDMDI18(BDMPD,BDMBDAT,BDMADAT))
 D S(BDMPD,79,$$GFR^BDMDI1C(BDMPD,BDMBDAT,BDMADAT))
 D S(BDMPD,84,$$CREAT^BDMDI18(BDMPD,BDMBDAT,BDMADAT))
 D S(BDMPD,86,$$CHOL^BDMDI18(BDMPD,BDMBDAT,BDMADAT))
 D S(BDMPD,88,$$LDL^BDMDI18(BDMPD,BDMBDAT,BDMADAT))
 D S(BDMPD,89,$$HDL^BDMDI18(BDMPD,BDMBDAT,BDMADAT))
 D S(BDMPD,90,$$TRIG^BDMDI18(BDMPD,BDMBDAT,BDMADAT))
 ;D S(BDMPD,117,$$NONHDL^BDMDI1C(BDMPD,BDMBDAT,BDMADAT))
 D S(BDMPD,92,$$URIN^BDMDI18(BDMPD,BDMBDAT,BDMADAT))
 D S(BDMPD,118,$$COMBINED^BDMDI1C(BDMPD,BDMBDAT,BDMADAT,BDM6MBD))
 D S(BDMPD,119,$$EGFRUACR^BDMDI1C(BDMPD,BDMBDAT,BDMADAT))
 ;
 Q
TYPEDM ;return type of DM in BDMTYDM
 NEW X
 I ^XTMP("BDMDM21",BDMJOB,BDMBTH,"AUDIT",BDMPD,24)="NIDDM" S BDMTYDM="2  Type 2" Q
 I ^XTMP("BDMDM21",BDMJOB,BDMBTH,"AUDIT",BDMPD,24)="TYPE II" S BDMTYDM="2  Type 2" Q
 I ^XTMP("BDMDM21",BDMJOB,BDMBTH,"AUDIT",BDMPD,24)[2 S BDMTYDM="2  Type 2" Q
 I ^XTMP("BDMDM21",BDMJOB,BDMBTH,"AUDIT",BDMPD,24)="IDDM" S BDMTYDM="1  Type 1" Q
 I ^XTMP("BDMDM21",BDMJOB,BDMBTH,"AUDIT",BDMPD,24)[1 S BDMTYDM="1  Type 1" Q
 I ^XTMP("BDMDM21",BDMJOB,BDMBTH,"AUDIT",BDMPD,24)="TYPE I" S BDMTYDM="1  Type 1" Q
 S X=^XTMP("BDMDM21",BDMJOB,BDMBTH,"AUDIT",BDMPD,25)
 F I=1:1 S C=$P(X,";",I) Q:C=""!(BDMTYDM]"")  S J=$P($$CODEN^BDMUTL(C,80),"~") I J>0,$$ICD^BDMUTL(J,"DM AUDIT TYPE II DXS",9) S BDMTYDM="2  Type 2"
 Q:BDMTYDM]""
 F I=1:1 S C=$P(X,";",I) Q:C=""!(BDMTYDM]"")  S J=$P($$CODEN^BDMUTL(C,80),"~") I J>0,$$ICD^BDMUTL(J,"DM AUDIT TYPE I DXS",9) S BDMTYDM="1  Type 1"
 Q:BDMTYDM]""
 S X=^XTMP("BDMDM21",BDMJOB,BDMBTH,"AUDIT",BDMPD,26)
 I X[2 S BDMTYDM="2  Type 2" Q
 I X[1 S BDMTYDM="1  Type 1" Q
 Q
DATE(D) ;EP
 I $G(D)="" Q ""
 Q $E(D,4,5)_"/"_$E(D,6,7)_"/"_(1700+($E(D,1,3)))
TRIBE(P) ;EP
 I '$G(P) Q ""
 I '$D(^AUPNPAT(P,11)) Q ""
 Q $$TRIBE^AUPNPAT(P,"C")_"^"_$$TRIBE^AUPNPAT(P,"E")
COMM(P) ;EP
 I '$G(P) Q ""
 I '$D(^AUPNPAT(P,11)) Q ""
 Q $$COMMRES^AUPNPAT(P,"E")
EAUDIT ;EP
 ;D UNFOLDTX^BDMUTL(2017)  ;cmi/maw 05/14/2014 patch 8 lets store all tax up front for checking call
 K ^BDMDATA("BDMEPI",$J)
 S ^XTMP("BDMDM21",0)=$$FMADD^XLFDT(DT,14)_"^"_DT_"^DM AUDIT 2021"
 S BDMEPIN=0
 S BDMBEGD=$$FMADD^XLFDT(BDMADAT,-365)
 S BDM3YE=$$FMADD^XLFDT(BDMADAT,-1096)
 I BDMACTI=1 D
 .S BDMEAUT=0 F  S BDMEAUT=$O(^ACM(41,"B",BDMDMRG,BDMEAUT)) Q:BDMEAUT'=+BDMEAUT  D
 ..I $P($G(^ACM(41,BDMEAUT,"DT")),U,1)'="A" Q
 ..S BDMPD=$P(^ACM(41,BDMEAUT,0),U,2)
 ..Q:$$DEMO^BDMUTL(BDMPD,$G(BDMDEMO))
 ..S BDMX=$$ACTDMPT^BDMDI1G(BDMPD,BDMBEGD,BDMADAT,BDMTAXI,BDMBEN,BDM3YE)
 ..I 'BDMX Q  ;not active diabetic
 ..I BDMPREG,$$PREG^BDMDI1B(P,BDMBDAT,BDMADAT,1,1) Q
 ..I BDMPREP=2 D EPIREC Q
 ..I BDMPREP=6 D EPICHK^BDMDI1J Q
 ..D GATHER
 .Q
 I BDMACTI=0 S BDMPD=0 F  S BDMPD=$O(^AUPNPAT(BDMPD)) Q:'BDMPD  D
 .Q:$$DEMO^BDMUTL(BDMPD,$G(BDMDEMO))
 .S BDMX=$$ACTDMPT^BDMDI1G(BDMPD,BDMBEGD,BDMADAT,BDMTAXI,BDMBEN,BDM3YE)
 .I 'BDMX Q  ;not active diabetic
 .I BDMACTI,'$$ACTONREG(BDMPD,BDMDMRG) Q
 .I BDMPREG,$$PREG^BDMDI1B(P,BDMBDAT,BDMADAT,1,1) Q
 .I BDMPREP=2 D EPIREC Q
 .I BDMPREP=6 D EPICHK^BDMDI1J Q
 .D GATHER
 I BDMPREP=2 D WRITEF^BDMDI1 Q
 I BDMPREP=3!(BDMPREP=4) D CUML^BDMDI15
 I BDMPREP=5 D SDPI16^BDMDI1R
 Q
ACTONREG(P,R) ;
 I $G(R)="" Q ""
 I $G(P)="" Q ""
 I '$D(^ACM(41,"AC",P,R)) Q 0
 S X=^ACM(41,"AC",P,R)
 I $P($G(^ACM(41,X,"DT")),U,1)'="A" Q 0
 Q 1
 ;
LOCN(P,R) ;EP
 I $G(R)="" Q ""
 I $G(P)="" Q ""
 I '$D(^ACM(41,"AC",P,R)) Q ""
 S X=^ACM(41,"AC",P,R)
 I 'X Q ""
 Q $$VAL^XBDIQ1(9002241,X,1101)
 ;
LOCT(P,R) ;EP
 I $G(R)="" Q ""
 I $G(P)="" Q ""
 I '$D(^ACM(41,"AC",P,R)) Q ""
 S X=^ACM(41,"AC",P,R)
 I 'X Q ""
 Q $$VAL^XBDIQ1(9002241,X,1102)
 ;
FLAT ;EP
 W !!,"The file generated will be in a ""^"" delimited format.  You can use",!,"this file to review your data in EXCEL if you so choose.",!!
 S BDMFILE=""
 S DIR(0)="F^3:20",DIR("A")="Enter the name of the FILE to be Created (3-20 characters)" K DA D ^DIR K DIR
 I $D(DIRUT) S BDMSTP=1 Q
 I Y["/" W !!,"You cannot use '/' in the filename." G FLAT
 I Y["\" W !!,"You cannot use '\' in the filename." G FLAT
 S BDMFILE=$$LOW^XLFSTR(Y)_".txt"
 W !!,"I am going to create a file called ",BDMFILE," which will reside in ",!,"the "
 W $S($P($G(^APCCCTRL($S($G(BDMDUZ2):BDMDUZ2,1:DUZ(2)),0)),U,11)]"":$P(^APCCCTRL($S($G(BDMDUZ2):BDMDUZ2,1:DUZ(2)),0),U,11),$P($G(^AUTTSITE(1,1)),U,2)]"":$P(^AUTTSITE(1,1),U,2),$P(^AUTTSITE(1,0),U,21)=1:"/usr/spool/uucppublic",1:"C:\EXPORT")
 W " directory on your RPMS server. ",!
 W "It is the same directory that the data export globals are placed."
 W !,"See your site manager for assistance in finding the file",!,"after it is created.  PLEASE jot down and remember the following file name:",!?15,"**********    ",BDMFILE,"    **********",!
 W "It may be several hours (or overnight) before your report and flat file are ",!,"finished.",!
 W !,"The records that are generated and placed in file ",BDMFILE
 W !,"are in a format readable by Excel.  For a definition of the format",!,"please see your user manual.",!
 S DIR(0)="Y",DIR("A")="Is everything ok?  Do you want to continue",DIR("B")="Y" K DA D ^DIR K DIR
 I $D(DIRUT) S BDMSTP=1 Q
 I 'Y S BDMSTP=1 Q
 Q
