BDMDKZ ;IHS/CMI/LAB-CREATED BY ^ATXSTX ON NOV 07, 2022;
 ;;2.0;DIABETES MANAGEMENT SYSTEM;**16**;JUN 14, 2007;Build 122
 ;
 ; See referenced routines to see taxonomies being loaded.
 ;
START ;
 D ^BDMDKZA ;   DM AUDIT TOBACCO USER CPTS
 D ^BDMDKZB ;   DM AUDIT TD CPTS
 D ^BDMDKZC ;   DM AUDIT PREDIABETES DXS
 D ^BDMDKZD ;   DM AUDIT PRE-DIABETES DXS
 Q
