BDMDO1B ; IHS/CMI/LAB - get dm audit values ;
 ;;2.0;DIABETES MANAGEMENT SYSTEM;**18**;JUN 14, 2007;Build 147
 ;
TD(P,EDATE) ;EP
 NEW BDM1
 S BDM1=$$TD^BDMS9B3(P,$$DOB^AUPNPAT(P),EDATE,,1)
 NEW D,X S D=$P(BDM1,"  ",2),X=""
 I D]"" NEW X S X=D D ^%DT S X=$$DATE^BDMS9B1(Y)
 I $E(BDM1)="Y" Q "1  "_$P(BDM1,"  ",1)_"  "_X
 I $E(BDM1)'="Y" Q "2  "_$P(BDM1,"  ",1)_"  "_X
 Q ""
TDAP(P,BDMSED,F,NR) ;EP
 NEW BDMY,X,E,B,%DT,Y,TDD,BDMCVX,BDMREF,S,G,T,R
 S TDD=$$LASTTDAP(P,BDMSED)
 I TDD Q "1  Yes  "_$S($G(F)="A":$$DATE^BDMS9B1(TDD),1:$$DATE^BDMS9B1(TDD))
 I $G(NR) Q "2  No"
 S S(115)=""
 ;CONTRAINDICATION
 K BDMREF
 S G="",Z="" F  S Z=$O(S(Z)) Q:Z=""  S X=0,Y=$O(^AUTTIMM("C",Z,0)) I Y F  S X=$O(^BIPC("AC",P,Y,X)) Q:X'=+X!(G)  D
 .S S=$P(^BIPC(X,0),U,3)
 .Q:S=""
 .Q:'$D(^BICONT(S,0))
 .Q:$P(^BICONT(S,0),U,1)["Refusal"
 .S T=$P(^BIPC(X,0),U,4)
 .Q:T=""
 .S BDMREF(9999999-T)=1_U_$$DATE^BDMS9B1(T)_U_$$VAL^XBDIQ1(9002084.11,X,.03)
 ;NMI, PROV DISCONTINUED, CONSIDERED AND NOT DONE 
 S BDMCVX="",G="" F  S BDMCVX=$O(S(BDMCVX)) Q:BDMCVX=""  D
 .S G=$$REFUSAL^BDMDO17(P,9999999.14,$O(^AUTTIMM("C",BDMCVX,0)),$$DOB^AUPNPAT(P),DT,"N")
 .I G I '$D(BDMREF(9999999-$P(G,U,7))) S BDMREF((9999999-$P(G,U,7)))=1_U_$P(G,U,3)_U_$P(G,U,5)
 .S G=$$REFUSAL^BDMDO17(P,9999999.14,$O(^AUTTIMM("C",BDMCVX,0)),$$DOB^AUPNPAT(P),DT,"P")
 .I G I '$D(BDMREF(9999999-$P(G,U,7))) S BDMREF((9999999-$P(G,U,7)))=1_U_$P(G,U,3)_U_$P(G,U,5)
 .S G=$$REFUSAL^BDMDO17(P,9999999.14,$O(^AUTTIMM("C",BDMCVX,0)),$$DOB^AUPNPAT(P),DT,"U")
 .I G I '$D(BDMREF(9999999-$P(G,U,7))) S BDMREF((9999999-$P(G,U,7)))=1_U_$P(G,U,3)_U_$P(G,U,5)
 S X=$O(BDMREF(0)) I X Q "  Contraindication: "_$P(BDMREF(X),U,3)_" "_$P(BDMREF(X),U,2)
 ;NOW CHECK REFUSAL IN PAST YEAR ONLY
 S BD=$$FMADD^XLFDT(DT,-365)
 S ED=DT
 S G="",Z="" F  S Z=$O(S(Z)) Q:Z=""  S X=0,Y=$O(^AUTTIMM("C",Z,0)) I Y F  S X=$O(^BIPC("AC",P,Y,X)) Q:X'=+X!(G)  D
 .S S=$P(^BIPC(X,0),U,3)
 .Q:S=""
 .Q:'$D(^BICONT(S,0))
 .Q:$P(^BICONT(S,0),U,1)'["Refusal"
 .S T=$P(^BIPC(X,0),U,4)
 .Q:T<BD
 .Q:T>ED
 .S BDMREF(9999999-T)=1_U_$$DATE^BDMS9B1(T)_U_$$VAL^XBDIQ1(9002084.11,X,.03)
 ;NMI, PROV DISCONTINUED, CONSIDERED AND NOT DONE 
 S BDMCVX="",G="" F  S BDMCVX=$O(S(BDMCVX)) Q:BDMCVX=""  D
 .S G=$$REFUSAL^BDMDO17(P,9999999.14,$O(^AUTTIMM("C",BDMCVX,0)),BD,DT,"R")
 .I G I '$D(BDMREF(9999999-$P(G,U,7))) S BDMREF((9999999-$P(G,U,7)))=1_U_$P(G,U,3)_U_$P(G,U,5)
 S X=$O(BDMREF(0)) I X Q "  "_$P(BDMREF(X),U,3)_" "_$P(BDMREF(X),U,2)
 Q "2  No  "_$S($G(F)="A":$$DATE^BDMS9B1(TDD),1:$$DATE^BDMS9B1(TDD))
LASTTDAP(BDMPDFN,BDMED) ;PEP - date of last TD
 ; 
 I $G(BDMPDFN)="" Q ""
 S BDMBD=$$DOB^AUPNPAT(BDMPDFN)
 I $G(BDMED)="" S BDMED=DT
 NEW BDMLAST,BDMVAL,BDMX,R,X,Y,V,E,T,G,BDMY,BDMF
 S BDMLAST=""
 S BDMVAL=$$LASTITEM^APCLAPIU(BDMPDFN,"115","IMMUNIZATION",$S($P(BDMLAST,U)]"":$P(BDMLAST,U),1:BDMBD),BDMED,"A")
 S BDMF=$$LASTCPTI^BDMSMU2(BDMPDFN,90715,BDMBD,BDMED)
 I BDMF,$P(BDMF,U,3)>$P(BDMVAL,U,1) Q $P(BDMF,U,3)
 Q $P(BDMVAL,U,1)
PREG(P,BDATE,EDATE,NORXCHR,NORX,CPBD,CPED) ;EP
 I $P(^DPT(P,0),U,2)'="F" Q ""
 NEW B,E,A,CNT,BDMD,BDMG,X,Y,BDMDX,C,D,G,T,%,CTR,VIEN,DXT,PXT,CPTT,BDMV,H
 I '$G(FORM) S FORM=""
 I $G(CPBD)="" S CPBD=BDATE
 I $G(CPED)="" S CPED=EDATE
 S A=""
 I $P($G(^AUPNREP(P,11)),U,1)="Y" D  I A S BDMD=B G MA
 .S B=$P($G(^AUPNREP(P,11)),U,2) Q:B=""
 .Q:B<CPBD
 .Q:B>CPED
 .S A=1
 .Q
 S BDMD=""
 S DXT="BGP PREGNANCY DIAGNOSES 2"
 S PXT="BGP PREGNANCY ICD PROCEDURES"
 S CPTT="BGP PREGNANCY CPT CODES"
 D ALLV^APCLAPIU(P,BDATE,EDATE,"BDMV")
 S B=0
 I '$D(BDMV) G PROBX
 S B=0,CNT=0,BDMD=""  ;if there is one before time frame set this to 1
 S NORXCHR=$G(NORXCHR)
 S NORX=$G(NORX)
 K BDMG
 ;CHECK DX, PROCS, CPTS for 2 separate visits
 S B=0,CTR=0 F  S CTR=$O(BDMV(CTR)) Q:CTR'=+CTR  D
 .;get visit into VIEN
 .S VIEN=$P(BDMV(CTR),U,5)
 .S D=$$VD^APCLV(VIEN)
 .S C=$$CLINIC^APCLV(VIEN,"C")
 .I NORXCHR,C=39 Q
 .I NORX,C=39 Q
 .S C=$$PRIMPROV^APCLV(VIEN,"D")
 .I NORXCHR,C=53 Q  ;no chr as primary provider
 .;now check for dx
 .S Y=0,H="" F  S Y=$O(^AUPNVPOV("AD",VIEN,Y)) Q:Y'=+Y  D
 ..S %=+^AUPNVPOV(Y,0)
 ..I $$ICD^BDMUTL(%,DXT,9) S BDMDX(D)="",CNT=CNT+1,H=1 I D>$$FMADD^XLFDT(EDATE,-365) S B=1
 .Q:H
 .;NOW GO THROUGH CPTS
 .S Y=0,H="" F  S Y=$O(^AUPNVCPT("AD",VIEN,Y)) Q:Y'=+Y  D
 ..S %=+^AUPNVCPT(Y,0)
 ..I $$ICD^BDMUTL(%,CPTT,1) I '$D(BDMDX(D)) S BDMDX(D)="",CNT=CNT+1,H=1 I D>$$FMADD^XLFDT(EDATE,-365) S B=1
 .Q:H
 .;NOW PROCEDURES
 .S Y=0,H="" F  S Y=$O(^AUPNVPRC("AD",VIEN,Y)) Q:Y'=+Y  D
 ..S %=+^AUPNVPRC(Y,0)
 ..I $$ICD^BDMUTL(%,PXT,0) I '$D(BDMDX(D)) S BDMDX(D)="",CNT=CNT+1,H=1 I D>$$FMADD^XLFDT(EDATE,-365) S B=1
 .Q:H
 .Q
 I CNT>1,B D  G MA
 .;SET BDMD TO SECOND VISIT DATE
 .S X=0,C=0 F  S X=$O(BDMDX(X)) Q:X'=+X!(C>1)  S C=C+1 I C=2 S BDMD=X
 ;
PROB ;
 I '$G(B) Q ""  ;no pregnancy visit during time period  ;-Lori fix in 09
 S T=$O(^ATXAX("B","BGP PREGNANCY DIAGNOSES 2",0))
 S (X,G)=0 F  S X=$O(^AUPNPROB("AC",P,X)) Q:X'=+X!(G)  D
 .Q:$P(^AUPNPROB(X,0),U,12)="D"
 .Q:$P(^AUPNPROB(X,0),U,12)="I"
 .Q:$P(^AUPNPROB(X,0),U,8)>EDATE
 .Q:$P(^AUPNPROB(X,0),U,8)<BDATE
 .S Y=$P(^AUPNPROB(X,0),U)
 .Q:'$$ICD^BDMUTL(Y,"BGP PREGNANCY DIAGNOSES 2",9)
 .S G=$P(^AUPNPROB(X,0),U,8)
 .Q
 I G=0,BDMD="" Q 0
 S BDMD=G
MA ;now check for abortion or miscarriage
 K BDMG S Y="BDMG(" S X=P_"^LAST DX [BGP MISCARRIAGE/ABORTION DXS;DURING "_$$FMTE^XLFDT(BDMD)_"-"_$$FMTE^XLFDT(EDATE) S E=$$START1^APCLDF(X,Y)
 I $D(BDMG(1)) Q 0  ;HAD MIS/AB
 S BDMG=$$LASTPRCT^BDMAPIU(P,BDATE,EDATE,"BGP ABORTION PROCEDURES","A")
 I BDMG Q 0
 S T=$O(^ATXAX("B","BGP MISCARRIAGE/ABORTION DXS",0))
 S (X,G)=0 F  S X=$O(^AUPNPROB("AC",P,X)) Q:X'=+X!(G)  D
 .Q:$P(^AUPNPROB(X,0),U,12)="D"
 .Q:$P(^AUPNPROB(X,0),U,12)="I"
 .Q:$P(^AUPNPROB(X,0),U,8)<BDMD
 .Q:$P(^AUPNPROB(X,0),U,8)>EDATE
 .S Y=$P(^AUPNPROB(X,0),U)
 .Q:'$$ICD^ATXAPI(Y,T,9)
 .S G=1
 .Q
 I G Q 0
 S T=$O(^ATXAX("B","BGP CPT ABORTION",0))
 S %=$$CPT^BDMDODU(P,BDMD,EDATE,T,3)
 I %]"" Q 0
 S T=$O(^ATXAX("B","BGP CPT MISCARRIAGE",0))
 S %=$$CPT^BDMDODU(P,BDMD,EDATE,T,3)
 I %]"" Q 0
 S T=$O(^ATXAX("B","BGP CPT ABORTION",0))
 S %=$$TRAN^BDMDODU(P,BDMD,EDATE,T,3)
 I %]"" Q 0
 S T=$O(^ATXAX("B","BGP CPT MISCARRIAGE",0))
 S %=$$TRAN^BDMDODU(P,BDMD,EDATE,T,3)
 I %]"" Q 0
 I FORM="" Q 1
 Q 1_U_$$DATE^BDMS9B1(BDMD)
PREGX(P,BDATE,EDATE,NORXCHR,NORX,RPBD) ;EP
 NEW BDMDX,B,CNT,BDMD,BDMG,Y,X,D,C,T,G,%
 I $P(^DPT(P,0),U,2)'="F" Q ""
 S B=0,CNT=0,BDMD=""
 S NORXCHR=$G(NORXCHR)
 S NORX=$G(NORX)
 K BDMG
 S Y="BDMG("
 S X=P_"^ALL DX [BGP PREGNANCY DIAGNOSES 2;DURING "_$$DATE^BDMS9B1(BDATE)_"-"_$$DATE^BDMS9B1(EDATE) S E=$$START1^APCLDF(X,Y)
 I '$D(BDMG) G PROB  ;no diagnoses
 S B=0,X=0 F  S X=$O(BDMG(X)) Q:X'=+X  D
 .;get date
 .S D=$P(BDMG(X),U,1)
 .S C=$$CLINIC^APCLV($P(BDMG(X),U,5),"C")
 .I NORXCHR,C=39 Q
 .I NORX,C=39 Q
 .S C=$$PRIMPROV^APCLV($P(BDMG(X),U,5),"D")
 .I NORXCHR,C=53 Q  ;no chr as primary provider
 .S BDMDX(D)="",CNT=CNT+1 I CNT=2 S BDMD=D
 .Q
 I CNT>1 Q 1
PROBX ;
 I '$G(B) Q ""
 S T=$O(^ATXAX("B","BGP PREGNANCY DIAGNOSES 2",0))
 S (X,G)=0 F  S X=$O(^AUPNPROB("AC",P,X)) Q:X'=+X!(G)  D
 .Q:$P(^AUPNPROB(X,0),U,12)="D"
 .Q:$P(^AUPNPROB(X,0),U,12)="I"
 .Q:$P(^AUPNPROB(X,0),U,8)>EDATE
 .Q:$P(^AUPNPROB(X,0),U,8)<BDATE
 .S Y=$P(^AUPNPROB(X,0),U)
 .Q:'$$ICD^BDMUTL(Y,"BGP PREGNANCY DIAGNOSES 2",9)
 .S G=$P(^AUPNPROB(X,0),U,8)
 .Q
 I G Q 1
 Q 0
STATE(P) ;EP - STATE OF PATIENT1)
 I '$G(P) Q ""
 NEW X,C
 S X=$$GET1^DIQ(2,P,.115,"I")
 I 'X Q ""
 I +$$GET1^DIQ(5,X,2)>69 Q ""
 Q $$GET1^DIQ(5,X,1)
CESS ;EP - find any cessation hf in 12 months before
 NEW X,BDMLPED,BDMALLED,BDMOPED
 I '$G(P) Q ""
 S X=$$TOBACCO^BDMDO1T(P,BDATE,EDATE)
 I +$P(X,U,2)'=1 Q ""
 S BDMLPED=$$PED(P,BDATE,EDATE)
 I BDMLPED]"" Q "1  Yes "_$$DATE^BDMS9B1($P(BDMLPED,U,1))_" "_$P(BDMLPED,U,2)
 Q "2  No"
PED(P,BDATE,EDATE) ;EP
 NEW BDMALLED,X,Y,%,T,G,A,B,E,Z,BDMOPED,SN,W,J
 K BDMALLED
 S BDMOPED=""
 S Y="BDMALLED("
 S X=P_"^ALL EDUC;DURING "_$$FMTE^XLFDT(BDATE)_"-"_$$FMTE^XLFDT(EDATE) S E=$$START1^APCLDF(X,Y)
 I $D(BDMALLED(1)) S %="" D  I %]"" S BDMOPED=%
 .S (X,D)=0,T="" F  S X=$O(BDMALLED(X)) Q:X'=+X  D
 ..S T=$P(^AUPNVPED(+$P(BDMALLED(X),U,4),0),U)
 ..Q:'T
 ..Q:'$D(^AUTTEDT(T,0))
 ..S T=$P(^AUTTEDT(T,0),U,2)
 ..I $G(BDMRTYPE)=3,T="TO-M" Q
 ..I $P(T,"-")]"",$$SNOMED^BDMUTL(2025,"PXRM BGP TOBACCO SCREENED",$P(T,"-")),$P(BDMOPED,U)<$P(BDMALLED(X),U) S %=$P(BDMALLED(X),U)_U_T Q
 ..I $P(T,"-")="TO",$P(BDMOPED,U)<$P(BDMALLED(X),U) S %=$P(BDMALLED(X),U)_U_T Q
 ..I $P(T,"-",2)="TO",$P(BDMOPED,U)<$P(BDMALLED(X),U) S %=$P(BDMALLED(X),U)_U_T Q
 ..I $P(T,"-",2)="SHS",$P(BDMOPED,U)<$P(BDMALLED(X),U) S %=$P(BDMALLED(X),U)_U_T Q
 ..S S=$P(T,"-",1)
 ..S S=$$ICDDX^ICDEX(S)
 ..I $P(S,U,1)'="-1",$$ICD^ATXCHK($P(S,U,1),$O(^ATXAX("B","BGP TOBACCO DXS",0)),9) S %=$P(BDMALLED(X),U)_U_T Q
 ..K W
 ..F J="D1320",99406,99407,"4000F","G9016","G9458","G0030" S W(J)=""
 ..I $P(T,"-",1)]"",$D(W($P(T,"-",1))),$P(BDMOPED,U)<$P(BDMALLED(X),U) S %=$P(BDMALLED(X),U)_U_T Q
 K ^TMP($J,"A")
 S A="^TMP($J,""A"",",B=P_"^ALL VISITS;DURING "_$$FMTE^XLFDT(BDATE)_"-"_$$FMTE^XLFDT(EDATE),E=$$START1^APCLDF(B,A)
 S X=0,G="" F  S X=$O(^TMP($J,"A",X)) Q:X'=+X  S V=$P(^TMP($J,"A",X),U,5) D
 .Q:'$D(^AUPNVSIT(V,0))
 .Q:'$P(^AUPNVSIT(V,0),U,9)
 .Q:$P(^AUPNVSIT(V,0),U,11)
 .S B=$$CLINIC^APCLV(V,"C")
 .I B=94,$P(BDMOPED,U)<$P($P(^AUPNVSIT(V,0),U),".") S BDMOPED=$P($P(^AUPNVSIT(V,0),U),".")_U_"Cl 94" Q
 .S Z=0 F  S Z=$O(^AUPNVDEN("AD",V,Z)) Q:Z'=+Z!(G)  S B=$P($G(^AUPNVDEN(Z,0)),U) I B S B=$P($G(^AUTTADA(B,0)),U) D
 ..I B=1320,$P(BDMOPED,U)<$P($P(^AUPNVSIT(V,0),U),".") S BDMOPED=$P($P(^AUPNVSIT(V,0),U),".")_U_"ADA 1320" Q
 ..I B="D1320",$P(BDMOPED,U)<$P($P(^AUPNVSIT(V,0),U),".") S BDMOPED=$P($P(^AUPNVSIT(V,0),U),".")_U_"ADA D1320" Q
 .Q
 ;I G]"" Q G
 S G=$$LASTDXI^BDMUTL(P,"Z71.6",BDATE,EDATE) I G,$P(BDMOPED,U)<$P(G,U,3) S BDMOPED=$P(G,U,3)_U_"DX Z71.6"
 S G=$$CPTI^BDMUTL(P,BDATE,EDATE,+$$CODEN^ICPTCOD("D1320")) I G,$P(BDMOPED,U)<$P(G,U,2) S BDMOPED=$P(G,U,2)_U_"CPT D1320"
 S G=$$TRANI^BDMUTL(P,BDATE,EDATE,+$$CODEN^ICPTCOD("D1320")) I G,$P(BDMOPED,U)<$P(G,U,2) S BDMOPED=$P(G,U,2)_U_"TRAN D1320"
 S G=$$CPTI^BDMUTL(P,BDATE,EDATE,+$$CODEN^ICPTCOD(99406)) I G,$P(BDMOPED,U)<$P(G,U,2) S BDMOPED=$P(G,U,2)_U_"CPT 99406"
 S G=$$TRANI^BDMUTL(P,BDATE,EDATE,+$$CODEN^ICPTCOD(99406)) I G,$P(BDMOPED,U)<$P(G,U,2) S BDMOPED=$P(G,U,2)_U_"TRAN 99406"
 S G=$$CPTI^BDMUTL(P,BDATE,EDATE,+$$CODEN^ICPTCOD(99407)) I G,$P(BDMOPED,U)<$P(G,U,2) S BDMOPED=$P(G,U,2)_U_"CPT 99407"
 S G=$$TRANI^BDMUTL(P,BDATE,EDATE,+$$CODEN^ICPTCOD(99407)) I G,$P(BDMOPED,U)<$P(G,U,2) S BDMOPED=$P(G,U,2)_U_"TRAN 99407"
 S G=$$CPTI^BDMUTL(P,BDATE,EDATE,+$$CODEN^ICPTCOD("G0030")) I G,$P(BDMOPED,U)<$P(G,U,2) S BDMOPED=$P(G,U,2)_U_"CPT G0030"
 S G=$$TRANI^BDMUTL(P,BDATE,EDATE,+$$CODEN^ICPTCOD("G0030")) I G,$P(BDMOPED,U)<$P(G,U,2) S BDMOPED=$P(G,U,2)_U_"TRAN G0030"
 S G=$$CPTI^BDMUTL(P,BDATE,EDATE,+$$CODEN^ICPTCOD("4000F")) I G,$P(BDMOPED,U)<$P(G,U,2) S BDMOPED=$P(G,U,2)_U_"CPT 4000F"
 S G=$$TRANI^BDMUTL(P,BDATE,EDATE,+$$CODEN^ICPTCOD("4000F")) I G,$P(BDMOPED,U)<$P(G,U,2) S BDMOPED=$P(G,U,2)_U_"TRAN 4000F"
 S G=$$CPTI^BDMUTL(P,BDATE,EDATE,+$$CODEN^ICPTCOD("G9016")) I G,$P(BDMOPED,U)<$P(G,U,2) S BDMOPED=$P(G,U,2)_U_"CPT G9016"
 S G=$$TRANI^BDMUTL(P,BDATE,EDATE,+$$CODEN^ICPTCOD("G9016")) I G,$P(BDMOPED,U)<$P(G,U,2) S BDMOPED=$P(G,U,2)_U_"TRAN G9016"
 S G=$$CPTI^BDMUTL(P,BDATE,EDATE,+$$CODEN^ICPTCOD("G9458")) I G,$P(BDMOPED,U)<$P(G,U,2) S BDMOPED=$P(G,U,2)_U_"CPT G9458"
 S G=$$TRANI^BDMUTL(P,BDATE,EDATE,+$$CODEN^ICPTCOD("G9458")) I G,$P(BDMOPED,U)<$P(G,U,2) S BDMOPED=$P(G,U,2)_U_"TRAN G9458"
 ;now check meds - new in 8.0
 K BDMMEDS1
 D GETMEDS^BDMSMU1(P,BDATE,EDATE,,,,,.BDMMEDS1)
 S T=$O(^ATXAX("B","BGP CMS SMOKING CESSATION MEDS",0))
 S T1=$O(^ATXAX("B","BGP CMS SMOKING CESSATION VAPI",0))
 S T2=$O(^ATXAX("B","BGP ECQM TOB CESSATION MEDS",0))
 S (X,G,M,E)=0,D="" F  S X=$O(BDMMEDS1(X)) Q:X'=+X  S V=$P(BDMMEDS1(X),U,5),Y=+$P(BDMMEDS1(X),U,4) D
 .Q:'$D(^AUPNVSIT(V,0))
 .Q:$$UP^XLFSTR($P($G(^AUPNVMED(Y,11)),U))["RETURNED TO STOCK"  ;new in v11.0
 .S Z=$P($G(^AUPNVMED(Y,0)),U) ;get drug ien
 .Q:'Z
 .S N=$P($G(^PSDRUG(Z,0)),U)
 .I $D(^ATXAX(T,21,"B",Z))!(N["NICOTINE PATCH")!(N["NICOTINE POLACRILEX")!(N["NICOTINE INHALER")!(N["NICOTINE NASAL SPRAY") D
 ..I $P(BDMOPED,U)<$P($P(^AUPNVSIT(V,0),U),".") S BDMOPED=$P($P(^AUPNVSIT(V,0),U),".")_U_"CESSATION MED - "_N
 .I T2,$D(^ATXAX(T2,21,"B",Z)) D
 ..I $P(BDMOPED,U)<$P($P(^AUPNVSIT(V,0),U),".") S BDMOPED=$P($P(^AUPNVSIT(V,0),U),".")_U_"CESSATION MED - "_N
 .S C=$P($G(^PSDRUG(Z,2)),U,4)
 .I $$VAPI(Z,T1) I $P(BDMOPED,U)<$P($P(^AUPNVSIT(V,0),U),".") S BDMOPED=$P($P(^AUPNVSIT(V,0),U),".")_U_"CESSATION MED - "_N
 Q BDMOPED
VAPI(A,B) ;EP
 ;a is drug ien
 ;b is taxonomy ien
 NEW Z,Y
 S Z=$$GET1^DIQ(50,A,22,"I")  ;INTERNAL
 I 'Z Q 0
 S Y=$$GET1^DIQ(50.68,Z,6)
 I Y="" Q 0
 I $D(^ATXAX(B,21,"B",Y)) Q 1
 Q 0
