BDMDO1S ; IHS/CMI/LAB - 2023 DIABETES AUDIT ;
 ;;2.0;DIABETES MANAGEMENT SYSTEM;**18**;JUN 14, 2007;Build 147
 ;
 ;
TOBACCO(P,BDATE,EDATE) ;EP
 I '$G(P) Q ""
 NEW BDMTOB,BDMSDX,BDMXPND,BDM1320,BDMSCPT,BDMALL,D,%,F,BDMTOBS,BDMSBD,BDMTOBC,G,Z,Y,X
 S BDMSBD=BDATE
 K BDMTOBS,BDMTOBC
 ;get last hf in BDMTOBS, BDMTOBC
 S X=$$LASTHF(P,"TOBACCO (SMOKING)",BDATE,EDATE) K O,D,H
 I $P(X,U,3) S BDMTOBS(9999999-$P(X,U,3))=X
 S X=$$LASTHF(P,"TOBACCO (SMOKELESS - CHEWING/DIP)",BDATE,EDATE) K O,D,H
 I $P(X,U,3) S BDMTOBC(9999999-$P(X,U,3))=X
 ;now get date of latest health factor and check for any of these next things after the HF
 ;S BDMSBD=$P(BDMTOBS,U,3)
 ;IS THERE A SMOKING RELATED DX AFTER THE HF
 D DXS
 ;S BDMSDX=$$DXS(P,$S(BDMSBD:BDMSBD,1:BDATE),EDATE)  ;get last dx in format code^date and compare to bdmdob
 ;I BDMSDX]"",$P(BDMSDX,U,3)>BDMSBD S BDMTOBS=BDMSDX
 S BDM1320=$$DENT(P,BDATE,EDATE)
 I BDM1320]"",'$D(BDMTOBS(9999999-$P(BDM1320,U,3))) S BDMTOBS(9999999-$P(BDM1320,U,3))=BDM1320
 S BDMSCPT=$$CPTSM(P,BDATE,EDATE)
 I BDMSCPT]"",'$D(BDMTOBS(9999999-$P(BDMSCPT,U,3))) S BDMTOBS(9999999-$P(BDMSCPT,U,3))=BDMSCPT
 ;SET BDMTOBS EQUAL TO WHICHEVER IS A 1, IF NONE ARE A 1 SET IT TO THE FIRST IN BDMTOBS, IF NONE SET TO FIRST IN BDMTOBC
 ;ZW BDMTOBS
 ;W !
 ;ZW BDMTOBC
 ;H 2
 S X=$O(BDMTOBS(0))
 S Y=$O(BDMTOBC(0))
 I X,Y,$E(BDMTOBS(X))=1,$E(BDMTOBC(Y))=1 Q $S(X=Y!(X<Y):BDMTOBS(X),1:BDMTOBC(Y))
 I X,$E(BDMTOBS(X))=1 Q BDMTOBS(X)
 I Y,$E(BDMTOBC(Y))=1 Q BDMTOBC(Y)
 I X,$E(BDMTOBS(X))=3,Y Q BDMTOBC(Y)
 I Y,$E(BDMTOBC(Y))=3,X Q BDMTOBS(X)
 I X,X=Y!(X<Y) Q BDMTOBS(X)
 I Y,X,Y<X Q BDMTOBC(Y)
 I X Q BDMTOBS(X)
 I Y Q BDMTOBC(Y)
 Q "3^3  Not Documented"
 ;
DXS ;EP
 NEW BDMG,T,X,G,Y,F,I,Z,H,S,BDMDK,B
 S G=""
 K BDMG
 S Y="BDMG("
 S D=BDATE
 S X=P_"^ALL DX [BGP TOBACCO DXS;DURING "_$$DATE^BDMS9B1(D)_"-"_$$DATE^BDMS9B1(EDATE) S E=$$START1^APCLDF(X,Y)
 I $D(BDMG(1)) D
 .;SET ALL EXCEPT F21.22 IN BDMTOBS, SET F21.22 IN BDMTOBS
 .S X=0 F  S X=$O(BDMG(X)) Q:X'=+X  D
 ..S Y=$P(BDMG(X),U,2)  ;DX CODE
 ..S (BDMDK,I)=+$P(BDMG(X),U,4)  ;V POV IEN
 ..S C=$P($G(^AUPNVPOV(I,0)),U,1)
 ..Q:C=""
 ..S B=(9999999-$P(BDMG(X),U,1))
 ..I $E(Y,1,6)="F17.22" D  Q
 ...I $$ICD^ATXAPI(C,$O(^ATXAX("B","BGP GPRA SMOKELESS DXS",0)),9),'$D(BDMTOBC(B)) S BDMTOBC((B))="1^1  Current user DX: "_$P(BDMG(X),U,2)_" "_$$VAL^XBDIQ1(9000010.07,BDMDK,.04)_" "_$$DATE^BDMS9B1($P(BDMG(X),U,1))_U_$P(BDMG(X),U,1) Q
 ...I '$D(BDMTOBS(B)) S BDMTOBC(B)="2^2  Not a Current user DX: "_$P(BDMG(X),U,2)_" "_$$VAL^XBDIQ1(9000010.07,BDMDK,.04)_" "_$$DATE^BDMS9B1($P(BDMG(X),U,1))_U_$P(BDMG(X),U,1) Q
 ..I $$ICD^ATXAPI(C,$O(^ATXAX("B","BGP TOBACCO USER DXS",0)),9),'$D(BDMTOBS(B)) S BDMTOBS(B)="1^1  Current user DX: "_$P(BDMG(X),U,2)_" "_$$VAL^XBDIQ1(9000010.07,BDMDK,.04)_" "_$$DATE^BDMS9B1($P(BDMG(X),U,1))_U_$P(BDMG(X),U,1) Q
 ..I '$D(BDMTOBS(B)) S BDMTOBS(B)="2^2  Not a Current user DX: "_$P(BDMG(X),U,2)_" "_$$VAL^XBDIQ1(9000010.07,BDMDK,.04)_" "_$$DATE^BDMS9B1($P(BDMG(X),U,1))_U_$P(BDMG(X),U,1) Q
 ;CHECK V POV SNOMED USING A
 S I=""
 S S="" F  S S=$O(^AUPNVPOV("ASNC",P,S)) Q:S=""  D
 .S I=0
 .I $$SNOMED^BDMUTL(2023,"PXRM BGP TOBACCO SCREENED",S) S I=1
 .I $$SNOMED^BDMUTL(2023,"PXRM BGP CURRENT TOBACCO",S) S I=1
 .Q:'I
 .S D=0 F  S D=$O(^AUPNVPOV("ASNC",P,S,D)) Q:D=""  D
 ..S Y=9999999-D
 ..Q:Y>EDATE
 ..Q:Y<BDATE
 ..I $$SNOMED^BDMUTL(2023,"PXRM BGP TOBACCO SMOKELESS",S),'$D(BDMTOBC(9999999-Y)) S BDMTOBC(9999999-Y)="1^1  Current user "_S_" POV SNOMED "_" "_$$DATE^BDMS9B1(Y)_U_Y Q
 ..I $$SNOMED^BDMUTL(2023,"PXRM BGP CURRENT TOBACCO",S),'$D(BDMTOBS(9999999-Y)) S BDMTOBS(9999999-Y)="1^1  Current user "_S_" POV SNOMED "_" "_$$DATE^BDMS9B1(Y)_U_Y Q
 ..I '$D(BDMTOBS(9999999-Y)) S BDMTOBS(9999999-Y)="2^2  Not a Current user "_S_" POV SNOMED "_" "_$$DATE^BDMS9B1(Y)_U_Y Q
 ;
 S T=$O(^ATXAX("B","BGP TOBACCO DXS",0))
 S X=0 F  S X=$O(^AUPNPROB("AC",P,X)) Q:X'=+X  D
 .Q:$P(^AUPNPROB(X,0),U,12)="D"
 .Q:$P(^AUPNPROB(X,0),U,12)="I"
 .Q:$P(^AUPNPROB(X,0),U,3)>EDATE
 .Q:$P(^AUPNPROB(X,0),U,3)<BDATE
 .S I=$P(^AUPNPROB(X,0),U,13)
 .I I,I>EDATE Q  ;date of onset after report period
 .S H=0
 .S D=$P(^AUPNPROB(X,0),U,3)
 .S Y=$P(^AUPNPROB(X,0),U) D
 ..I '$$ICD^BDMUTL(Y,$P(^ATXAX(T,0),U),9),'$$ICD^ATXAPI(Y,$O(^ATXAX("B","BGP GPRA SMOKELESS DXS",0)),9),'$$ICD^ATXAPI(Y,$O(^ATXAX("B","BGP TOBACCO USER DXS",0)),9) Q   ;NOT A TOBACCO DX
 ..I $$ICD^ATXAPI(Y,$O(^ATXAX("B","BGP GPRA SMOKELESS DXS",0)),9),'$D(BDMTOBC(9999999-D)) S BDMTOBC(9999999-D)="1^1  Current user "_$P($$ICDDX^BDMUTL(Y),U,2)_" PROBLEM LIST "_" "_$$DATE^BDMS9B1($P(^AUPNPROB(X,0),U,3))_U_$P(^AUPNPROB(X,0),U,3) Q
 ..I '$$ICD^BDMUTL(Y,"BGP TOBACCO USER DXS",9),'$D(BDMTOBS(9999999-D)) S BDMTOBS(9999999-D)="2^2  Not a Current user "_$P($$ICDDX^BDMUTL(Y),U,2)_" PROBLEM LIST "_" "_$$DATE^BDMS9B1($P(^AUPNPROB(X,0),U,3))_U_$P(^AUPNPROB(X,0),U,3) Q
 ..I '$D(BDMTOBS(9999999-D)) S BDMTOBS(9999999-D)="1^1  Current user "_$P($$ICDDX^BDMUTL(Y),U,2)_" PROBLEM LIST "_" "_$$DATE^BDMS9B1($P(^AUPNPROB(X,0),U,3))_U_$P(^AUPNPROB(X,0),U,3)
 .S S=$$VAL^XBDIQ1(9000011,X,80001)
 .I S]"",$$SNOMED^BDMUTL(2023,"PXRM BGP TOBACCO SCREENED",S)!($$SNOMED^BDMUTL(2023,"PXRM BGP CURRENT TOBACCO",S))!($$SNOMED^BDMUTL(2023,"PXRM BGP TOBACCO SMOKELESS",S)) D
 ..I $$SNOMED^BDMUTL(2023,"PXRM BGP TOBACCO SMOKELESS",S),'$D(BDMTOBC(9999999-D)) S BDMTOBC(9999999-D)="1^1  Current user "_S_" PROBLEM LIST "_" "_$$DATE^BDMS9B1($P(^AUPNPROB(X,0),U,3))_U_$P(^AUPNPROB(X,0),U,3) Q
 ..I $$SNOMED^BDMUTL(2023,"PXRM BGP CURRENT TOBACCO",S),'$D(BDMTOBS(9999999-D)) S BDMTOBS(9999999-D)="1^1  Current user "_S_" PROBLEM LIST "_" "_$$DATE^BDMS9B1($P(^AUPNPROB(X,0),U,3))_U_$P(^AUPNPROB(X,0),U,3) Q
 ..I '$D(BDMTOBS(9999999-D)) S BDMTOBS(9999999-D)="2^2  Not a Current user "_S_" PROBLEM LIST "_" "_$$DATE^BDMS9B1($P(^AUPNPROB(X,0),U,3))_U_$P(^AUPNPROB(X,0),U,3) Q
 Q
TOBACCOS ;EP
 K BDM
 S BDMTOBS="",BDMTOBC=""
 S BDMTOBS=$$LASTHF(P,"TOBACCO (SMOKING)",BDATE,EDATE) K O,D,H
 S BDMTOBC=$$LASTHF(P,"TOBACCO (SMOKELESS - CHEWING/DIP)",BDATE,EDATE) K O,D,H
 ;if have both then take the one that indicates tobacco use
 I $P(BDMTOBS,U)=1 Q
 I $P(BDMTOBC,U)=1 S BDMTOBS=BDMTOBC Q
 I $P(BDMTOBC,U,1)=2,$P(BDMTOBC,U,3)>$P(BDMTOBS,U,3) S BDMTOBS=BDMTOBC Q
 I $P(BDMTOBS,U,1)=2 Q
 I $P(BDMTOBC,U,1)=2 S BDMTOBS=BDMTOBC Q
 Q
 ;
LASTHF(P,C,BDATE,EDATE) ;EP - get last factor in category C for patient P
 S C=$O(^AUTTHF("B",C,0)) ;ien of category passed
 I '$G(C) Q ""
 NEW H,D,O,F,Z
 S (H,D)=0 K O
 F  S H=$O(^AUTTHF("AC",C,H))  Q:'+H  D
 .Q:'$D(^AUPNVHF("AA",P,H))
 .S D="" F  S D=$O(^AUPNVHF("AA",P,H,D)) Q:D'=+D  D
 ..Q:(9999999-D)>EDATE  ;after time frame
 ..Q:(9999999-D)<BDATE  ;before time frame
 ..S Z=$O(^AUPNVHF("AA",P,H,D,0))
 ..S F=$$VAL^XBDIQ1(9000010.23,Z,.01)
 ..I F="SMOKER IN HOME"!(F="SMOKE FREE HOME")!(F["CEREMONIAL")!(F["EXPOSURE TO") Q
 ..S O(D)=$O(^AUPNVHF("AA",P,H,D,""))
 .Q
 S D=$O(O(0))
 I D]"" D  Q Z
 .S Z=$$TUHF($$VAL^XBDIQ1(9000010.23,O(D),.01))
 .S Z=Z_U_$S(Z=1:"1  Current user ",1:"2  Not a Current user ")_$$VAL^XBDIQ1(9000010.23,O(D),.01)_"  "_$$DATE^BDMS9B1(9999999-D)_"^"_(9999999-D)
 S (H,D)=0 K O
 F  S H=$O(^AUTTHF("AC",C,H))  Q:'+H  D
 .Q:'$D(^AUPNVHF("AA",P,H))
 .S D="" F  S D=$O(^AUPNVHF("AA",P,H,D)) Q:D'=+D  D
 ..Q:(9999999-D)>EDATE  ;after time frame
 ..Q:(9999999-D)<BDATE  ;before time frame
 ..S Z=$O(^AUPNVHF("AA",P,H,D,0))
 ..S F=$$VAL^XBDIQ1(9000010.23,Z,.01)
 ..I F="SMOKER IN HOME"!(F="SMOKE FREE HOME")!(F["CEREMONIAL")!(F["EXPOSURE TO") S O(D)=$O(^AUPNVHF("AA",P,H,D,""))
 .Q
 S D=$O(O(0))
 I D Q 2_"^2  Not a Current user "_$$VAL^XBDIQ1(9000010.23,O(D),.01)_"  "_$$DATE^BDMS9B1(9999999-D)_"^"_(9999999-D)
 Q "3^3  Not Documented"
 ;
TUHF(V) ;
 I V="" Q 3
 I V["CURRENT" Q 1
 I V["CESSATION" Q 2  ;LAB - p13 remove cessation as a user
 I V["HEAVY TOBACCO" Q 1
 I V["LIGHT TOBACCO" Q 1
 I V="SMOKELESS TOBACCO, STATUS UNKNOWN" Q 3
 I V["STATUS UNKNOWN" Q 3
 Q 2
 ;
DENT(P,BDATE,EDATE) ;EP
 ;K ^TMP($J,"A")
 NEW A,B,E,X,G,Z,%,BDMD,BDMX
 S BDMX=""
 S %=P_"^LAST ADA 1320;DURING "_BDATE_"-"_EDATE,E=$$START1^APCLDF(%,"BDMD(")
 ;S A="^TMP($J,""A"",",B=P_"^ALL VISITS;DURING "_$$DATE^BDMS9B1(BDATE)_"-"_$$DATE^BDMS9B1(EDATE),E=$$START1^APCLDF(B,A)
 ;I '$D(^TMP($J,"A",1)) Q ""
 ;S (X,G)=0 F  S X=$O(^TMP($J,"A",X)) Q:X'=+X!(G)  S V=$P(^TMP($J,"A",X),U,5) D
 ;.Q:'$D(^AUPNVSIT(V,0))
 ;.Q:'$P(^AUPNVSIT(V,0),U,9)
 ;.Q:$P(^AUPNVSIT(V,0),U,11)
 ;.S Z=0 F  S Z=$O(^AUPNVDEN("AD",V,Z)) Q:Z'=+Z!(G)  S B=$P($G(^AUPNVDEN(Z,0)),U) I B S B=$P($G(^AUTTADA(B,0)),U) I B=1320 S G=1_U_$P($P(^AUPNVSIT(V,0),U),".")
 ;.Q
 ;K ^TMP($J,"A")
 I $D(BDMD(1)) S BDMX=$P(BDMD(1),U,1)_U_"ADA 1320"
 K BDMD
 S %=P_"^LAST ADA D1320;DURING "_BDATE_"-"_EDATE,E=$$START1^APCLDF(%,"BDMD(")
 I $D(BDMD(1)) S %=$P(BDMD(1),U,1) I %>$P(BDMX,U,1) S BDMX=%_U_"ADA D1320"
 I BDMX="" Q ""
 Q "1^1  Current user "_$P(BDMX,U,2)_" "_$$DATE^BDMS9B1($P(BDMX,U,1))_U_$P(BDMX,U,1)
 ;
CPTSM(P,BDATE,EDATE) ;EP - did pat have smoking cpt?
 NEW X,G,Z
 S G=""
 S X=$$LASTCPTT^BDMAPIU(P,BDATE,EDATE,"BGP TOBACCO SCREEN CPTS","E")
 I X="" Q ""
 S Z=$$VALI^XBDIQ1(9000010.18,$P(X,U,6),.01)
 I '$$ICD^BDMUTL(Z,"DM AUDIT TOBACCO USER CPTS",1) Q "2^2  Not a Current user "_$P(X,U,2)_" "_$$DATE^BDMS9B1($P(X,U,1))_U_$P(X,U,1)
 Q "1^1  Current user "_$P(X,U,2)_" "_$$DATE^BDMS9B1($P(X,U,1))_U_$P(X,U,1)
ENDS(P,BD,ED) ;EP
 I $G(P)="" Q ""
 NEW X
 S X=$$LASTHF^BDMSMU(P,"C019","A",BD,ED)
 I X="" Q "2  No"
 Q "1  Yes "_$P(X,U,2)_"  "_$$DATE^BDMS9B1($P(X,U,3))
LASTENDS(P,BD,ED) ;EP - DON'T COUNT NON NICOTINE ONE
 I $G(P)="" Q ""
 NEW X,CIG,D,G
 I $G(BD)="" S BD=$$DOB^AUPNPAT(P)
 D ALLHF(P,BD,ED,"C019","CIG")
 ;FIND LAST ONE THAT IS NOT THE OTHER SUBSTANCES ONE
 S D=0,X=0,G=""
 F  S D=$O(CIG(D)) Q:D'=+D!(G)  D
 .S C=0 F  S C=$O(CIG(D,C)) Q:C'=+C!(G)  D
 ..Q:$P(CIG(D,C),U,3)="F155"
 ..S Y=$P(CIG(D,C),U,3)  ;code
 ..I Y="F124" S G="1  Current user "_$$DATE^BDMS9B1(9999999-D) Q
 ..S G="2  Not a current user "_$$DATE^BDMS9B1(9999999-D) Q
 I G]"" Q G
 Q "3  Not documented"
ALLHF(P,BD,ED,CAT,RETVAL) ;
 NEW H,D,C,N
 S (H,D,C)=0
 S N=CAT
 I N="" Q ""
 S CAT=$O(^AUTTHF("B",CAT,0))
 I 'CAT S CAT=$O(^AUTTHF("C",N,0))
 I 'CAT Q ""
 F  S H=$O(^AUTTHF("AC",CAT,H))  Q:'+H  D
 .Q:'$D(^AUPNVHF("AA",P,H))
 .S D="" F  S D=$O(^AUPNVHF("AA",P,H,D)) Q:D'=+D  D
 ..Q:(9999999-D)>ED  ;after time frame
 ..Q:(9999999-D)<BD  ;before time frame
 ..S C=C+1
 ..S @RETVAL@(D,C)=(9999999-$P(D,"."))_"^"_$P(^AUTTHF(H,0),U,1)_"^"_$P(^AUTTHF(H,0),U,2)
 .Q
 Q
