BDMDJZ ;IHS/CMI/LAB-CREATED BY ^ATXSTX ON DEC 14, 2021;
 ;;2.0;DIABETES MANAGEMENT SYSTEM;**15**;JUN 14, 2007;Build 95
 ;
 ; See referenced routines to see taxonomies being loaded.
 ;
START ;
 D ^BDMDJZA ;   DM AUDIT TOBACCO USER CPTS
 D ^BDMDJZB ;   DM AUDIT TD CVX CODES
 D ^BDMDJZC ;   DM AUDIT TD CPTS
 D ^BDMDJZD ;   BGP DEPRESSION SCREEN DXS
 Q
