BDMECGM ; IHS/CMI/LAB - GCM ENTRY ;
 ;;2.0;DIABETES MANAGEMENT SYSTEM;**19**;JUN 14, 2007;Build 159
 ;
 ;
START ;
 D EN^XBVK("BDM")
 W !!
 W $$CTR("Enter/Edit Continuous Glucose Monitoring (CGM) patient reported data.",80),!!
GETPAT ;
 S (BDMPAT,DFN)=""
 S DIC="^AUPNPAT(",DIC(0)="AEMQ" D ^DIC K DIC,DA,DR,DLAYGO,DIADD
 I Y<0 D EOJ Q
 S (DFN,BDMPAT)=+Y
 W !?25,"Ok" S %=1 D YN^DICN I %'=1 S DFN="",BDMPAT="" G GETPAT
 D EN
END ;
 D EOJ
 Q
 ;
EN ;EP
 NEW BDMLEAP
 D EN^VALM("BDM VIEW/UPDATE CGM DATA")
 K BDMCASE,BDMX,BDMD,BDMRCNT,BDMLINE,BDMCDATE,BDMF,BDMECGM,BDMDP,BDMIISFE,BDMRCNT,BDMCGMI
 Q
 ;
HDR ; -- header code
 S VALMHDR(1)="CGM Data on File for: "_IORVON_$$GETPREF^AUPNSOGI(DFN,"E",1)_IOINORM
 S VALMHDR(2)="HRN: "_$$HRN^AUPNPAT(DFN,DUZ(2))_"    "_$$VAL^XBDIQ1(2,DFN,.02)_"   DOB: "_$$DOB^AUPNPAT(DFN,"E")
 Q
 ;
CTR(X,Y) ;EP - Center X in a field Y wide.
 Q $J("",$S($D(Y):Y,1:IOM)-$L(X)\2)_X
 ;----------
INIT ; 
 S VALMSG="?? for more actions  + next screen  - prev screen"
 D GATHER
 S VALMCNT=BDMLINE
 Q
 ;
GATHER ;
 K BDMECGM
 S BDMRCNT=0,BDMLINE=0
 I '$D(^AUPNPRDI("AC",DFN)) S BDMECGM(1,0)="No CGM Data currently on file for "_$P(^DPT(DFN,0),U),BDMECGM("IDX",1,1)="" S BDMRCNT=1 Q
 S BDMSD=0 F  S BDMSD=$O(^AUPNPRDI("AA",DFN,BDMSD)) Q:BDMSD'=+BDMSD  S BDMCGMI=0 F  S BDMCGMI=$O(^AUPNPRDI("AA",DFN,BDMSD,BDMCGMI)) Q:BDMCGMI'=+BDMCGMI  I $P(^AUPNPRDI(BDMCGMI,0),U,9)="" D
 .S BDMRCNT=BDMRCNT+1
 .S X=BDMRCNT_") Report Date: "_$$VAL^XBDIQ1(9000090,BDMCGMI,.04),$E(X,32)="Report Date Range: "_$$VAL^XBDIQ1(9000090,BDMCGMI,1101)_"-"_$$VAL^XBDIQ1(9000090,BDMCGMI,1102)
 .S BDMLINE=BDMLINE+1,BDMECGM(BDMLINE,0)=X,BDMECGM("IDX",BDMLINE,BDMRCNT)=BDMCGMI
 .S X="   Duration (Days): "_$$VAL^XBDIQ1(9000090,BDMCGMI,1103),$E(X,32)="GMI: "_$$VAL^XBDIQ1(9000090,BDMCGMI,1104)_"%",$E(X,50)="Time in Range (TIR): "_$$VAL^XBDIQ1(9000090,BDMCGMI,1105)_"%"
 .S BDMLINE=BDMLINE+1,BDMECGM(BDMLINE,0)=X,BDMECGM("IDX",BDMLINE,BDMRCNT)=BDMCGMI
 .S X="   Target Range: "_$$VAL^XBDIQ1(9000090,BDMCGMI,1107)_"-"_$$VAL^XBDIQ1(9000090,BDMCGMI,1108)_" mg/dL",BDMLINE=BDMLINE+1,BDMECGM(BDMLINE,0)=X,BDMECGM("IDX",BDMLINE,BDMRCNT)=BDMCGMI
 Q
EDIT ;EP
 D EN^VALM2(XQORNOD(0),"OS")
 I '$D(VALMY) W !,"No records selected." G EXIT
 S R=$O(VALMY(0)) I 'R K R,VALMY,XQORNOD W !,"No record selected." G EXIT
 S BDMCGMI=0,(X,Y)=0 F  S X=$O(BDMECGM("IDX",X)) Q:X'=+X!(BDMCGMI)  I $O(BDMECGM("IDX",X,0))=R S Y=$O(BDMECGM("IDX",X,0)),BDMCGMI=BDMECGM("IDX",X,Y)
 I '$D(^AUPNPRDI(BDMCGMI,0)) W !,"Not a valid CGM RECORD." K BDMRDEL,R,BDMCGMI,R1 D PAUSE D EXIT Q
 D FULL^VALM1
EDIT1 ;
 S DA=BDMCGMI,DIE="^AUPNPRDI(",DR=".07////"_$$NOW^XLFDT_";.08////"_DUZ D ^DIE K DIE,DA,DR
 S DA=BDMCGMI,DIE="^AUPNPRDI(",DR="[BDM CGM EDIT]" D ^DIE K DA,DIE,DR
 ;CHECK
 S BDMERR=""
 F F=.04,1101,1102,1103,1104,1105 I $$VAL^XBDIQ1(9000090,BDMCGMI,F)="" W !!,$P(^DD(9000090,F,0),U,1)," is a required data element." S BDMERR=1
 I 'BDMERR G BUSAE
 W !!,"One or more required data elements are missing.",!! D
 .S DIR(0)="S^E:Edit and Complete the data;D:Delete the Entry",DIR("A")="What do you want to do",DIR("B")="E" KILL DA D ^DIR KILL DIR
 .I $D(DIRUT) S Y="D"
 I Y="E" G EDIT1
 I Y="D" S DA=BDMCGMI,DIE="^AUPNPRDI(",DR=".09////"_$$NOW^XLFDT()_";.11////"_DUZ_";.12R;.13" D ^DIE K DIE,DA,DR
BUSAE ;BUSA
 ;BUSA LOG THAT USER UPDATED USING CGM
 K BDMDETAL
 S BDMDETAL(1)=BDMPAT_"^"_BDMCGMI
 D LOG^BUSAAPI("O","O","A",$S($G(XQY0)]"":$P(XQY0,U),1:"BDMECGM"),"UPDATED PATIENT CGM DATA","BDMDETAL")
 D EXIT
 Q
DEL ;EP - called from protocol
 D EN^VALM2(XQORNOD(0),"OS")
 I '$D(VALMY) W !,"No records selected." G EXIT
 S R=$O(VALMY(0)) I 'R K R,VALMY,XQORNOD W !,"No record selected." G EXIT
 S BDMCGMI=0,(X,Y)=0 F  S X=$O(BDMECGM("IDX",X)) Q:X'=+X!(BDMCGMI)  I $O(BDMECGM("IDX",X,0))=R S Y=$O(BDMECGM("IDX",X,0)),BDMCGMI=BDMECGM("IDX",X,Y)
 I '$D(^AUPNPRDI(BDMCGMI,0)) W !,"Not a valid CGM RECORD." K BDMRDEL,R,BDMCGMI,R1 D PAUSE D EXIT Q
 D FULL^VALM1
 S DIR(0)="Y",DIR("A")="Are you sure you want to delete this CGM entry",DIR("B")="N" KILL DA D ^DIR KILL DIR
 I $D(DIRUT) D EXIT Q
 I 'Y D EXIT Q
 S DA=BDMCGMI,DIE="^AUPNPRDI(",DR=".09////"_$$NOW^XLFDT()_";.11////"_DUZ_";.12R;.13" D ^DIE K DIE,DA,DR
 G BUSAE
 Q
DPCS ;EP
 D FULL^VALM1
 ;D REG^BDMFUTIL
 G:$D(BDMQUIT) EXIT
 D CLEAR^VALM1
 W @IOF
 W !?5,"Display Diabetes Patient Care Summary for: ",$$VAL^XBDIQ1(2,BDMPAT,.01),!!
 D VIEWR^XBLM("PRINT^BDMDMSP")
 ;LOG DPSC print in BUSA
 NEW BDMDETAL
 S BDMDETAL(1)=DFN_U_U
 D LOG^BUSAAPI("O","P","P",$S($G(XQY0)]"":$P(XQY0,U),1:"DPSC~BDMVRL"),"DM DPSC HEALTH SUMMARY","BDMDETAL")
 D EXIT
 Q
ADDCGM(BDMPAT) ;EP
 D FULL^VALM1
 S BDMERR=0
 W:$D(IOF) @IOF
 D ^XBFMK
 K DD,D0,DO,DINUM,DIC,DA,DR S DIC(0)="EL",DIC="^AUPNPRDI(",DLAYGO=9000090,DIADD=1,X=$O(^AUTTPRDT("C","CGM",0))
 S DIC("DR")=".02////"_BDMPAT_";.05////"_$$NOW^XLFDT()_";.06////"_DUZ_";.07////"_$$NOW^XLFDT()_";.08////"_DUZ
 D FILE^DICN K DIC,DR,DIE,DIADD,DLAYGO,X,D0
 I Y=-1 W !!,$C(7),$C(7),"Error creating CGM entry...Deleting entry.",! D PAUSE,EXIT Q
 S BDMCGMI=+Y
ADD1 ;
 S DA=BDMCGMI,DIE="^AUPNPRDI(",DR="[BDM CGM EDIT]" D ^DIE K DA,DIE,DR
 ;CHECK
 S BDMERR=""
 F F=.04,1101,1102,1103,1104,1105 I $$VAL^XBDIQ1(9000090,BDMCGMI,F)="" W !!,$P(^DD(9000090,F,0),U,1)," is a required data element." S BDMERR=1
 I 'BDMERR G BUSAA
 W !!,"One or more required data elements are missing.",!! D
 .S DIR(0)="S^E:Edit and Complete the data;D:Delete the Entry;L:Leave the Incomplete Data as is and Finish it Later",DIR("A")="What do you want to do",DIR("B")="E" KILL DA D ^DIR KILL DIR
 .I $D(DIRUT) S Y="L"
 I Y="E" G ADD1
 I Y="D" S DA=BDMCGMI,DIE="^AUPNPRDI(",DR=".09////"_$$NOW^XLFDT()_";.11////"_DUZ_";.12R;.13" D ^DIE K DIE,DA,DR
BUSAA ;BUSA
 ;BUSA LOG THAT USER UPDATED USING CGM
 K BDMDETAL
 S BDMDETAL(1)=BDMPAT_"^"_BDMCGMI
 D LOG^BUSAAPI("O","O","A",$S($G(XQY0)]"":$P(XQY0,U),1:"BDMECGM"),"UPDATED PATIENT CGM DATA","BDMDETAL")
 D EXIT
 Q
HELP ;
 S X="?" D DISP^XQORM1 W !!
 Q
EXIT ; -- exit code
 D TERM^VALM0
 S VALMBCK="R"
 D GATHER
 S VALMCNT=BDMLINE
 D HDR
 K X,Y,Z,I
 Q
EOJ ;
 D EN^XBVK("BDM")
 K DFN
 K DDSFILE,DIPGM,Y
 K X,Y,%,DR,DDS,DA,DIC
 D:$D(VALMWD) CLEAR^VALM1
 K VALM,VALMHDR,VALMKEY,VALMMENU,VALMSGR,VALMUP,VALMWD,VALMLST,VALMVAR,VALMLFT,VALMBCK,VALMCC,VALMAR,VALMBG,VALMCAP,VALMCOFF,VALMCNT,VALMCON,BALMON,VALMEVL,VALMIOXY
 D KILL^AUPNPAT
 Q
 ;
EXPND ;
 Q
 ;
PAUSE ;EP
 S DIR(0)="EO",DIR("A")="Press enter to continue...." D ^DIR K DIR S:$D(DUOUT) DIRUT=1
 Q
