BDMPL10 ; IHS/CMI/LAB -IHS -GETS DATA FOR DIABETES QA REPORT ; 15 Dec 2016  3:48 PM
 ;;2.0;DIABETES MANAGEMENT SYSTEM;**19**;JUN 14, 2007;Build 159
 ;
 ;
EN ; - ENTRY POINT - from ^BDMASK
 S ^XTMP("BDMPL1",0)=$$FMADD^XLFDT(DT,14)_"^"_DT_"^PRE DM AUDIT 2026"
 S BDMEPIN=0
 S BDMPD=0 F  S BDMPD=$O(^XTMP("BDMPL1",BDMJOB,BDMBTH,"PATS",BDMPD)) Q:'BDMPD  D
 .I BDMTYPE'="P",BDMTYPE'="S" Q:$$DEMO^BDMUTL(BDMPD,$G(BDMDEMO))
 .D GATHER
 I BDMPREP=2!(BDMPREP=3) D CUML^BDMPL15
 Q
S(P,I,V) ;
 S ^XTMP("BDMPL1",BDMJOB,BDMBTH,"AUDIT",P,I)=V
 Q
GATHER ;gather data for 1 patient
 S BDMER=0
HEADER ; Set node with report header info
 ;set report dates
 ;set report dates
 S ^XTMP("BDMPL1",BDMJOB,BDMBTH,"AUDIT",BDMPD,1)=BDMRBD_" - "_BDMRED
 ;set audit date to DT
 S ^XTMP("BDMPL1",BDMJOB,BDMBTH,"AUDIT",BDMPD,2)=$$FMTE^XLFDT(DT)
 ;reviewer
 S ^XTMP("BDMPL1",BDMJOB,BDMBTH,"AUDIT",BDMPD,14)=$P(^VA(200,DUZ,0),U,2)  ;reviewer initials
 S ^XTMP("BDMPL1",BDMJOB,BDMBTH,"AUDIT",BDMPD,122)=$$COMM(BDMPD)
 S ^XTMP("BDMPL1",BDMJOB,BDMBTH,"AUDIT",BDMPD,121)=$S($P($G(^DPT(BDMPD,.11)),U,5):$P($G(^DIC(5,$P(^DPT(BDMPD,.11),U,5),0)),U,2),1:"")  ;state of residence
 S ^XTMP("BDMPL1",BDMJOB,BDMBTH,"AUDIT",BDMPD,15)=$$VAL^XBDIQ1(9000001,BDMPD,.14)  ;primary care provider
DEMO ;pat demographics
 S ^XTMP("BDMPL1",BDMJOB,BDMBTH,"AUDIT",BDMPD,16)=$$HRN^AUPNPAT(BDMPD,$S($G(BDMDUZ2):BDMDUZ2,1:DUZ(2)))  ;hrn
 S ^XTMP("BDMPL1",BDMJOB,BDMBTH,"AUDIT",BDMPD,18)=$$DOB^AUPNPAT(BDMPD,"E")  ;dob
 S ^XTMP("BDMPL1",BDMJOB,BDMBTH,"AUDIT",BDMPD,20)=$$VAL^XBDIQ1(2,BDMPD,.02)  ;sex
 ;
DXDT ;dates of and dm dxs
 K BDMDITA S X=$$IFG^BDMS9D1(BDMPD,BDMADAT)
 S ^XTMP("BDMPL1",BDMJOB,BDMBTH,"AUDIT",BDMPD,200)=X
 S X=$$IGT^BDMS9D1(BDMPD,BDMADAT)
 S ^XTMP("BDMPL1",BDMJOB,BDMBTH,"AUDIT",BDMPD,210)=X
 S X=$$PREDM^BDMS9D1(BDMPD,BDMADAT)
 S ^XTMP("BDMPL1",BDMJOB,BDMBTH,"AUDIT",BDMPD,220)=X
 I $$PLDMDXS^BDMDL13(BDMPD)]"" D S(BDMPD,25,"PLEASE NOTE:  Diabetes is on the Problem list for this patient")
 S X=$$FRSTDMDX^BDMDL13(BDMPD,"E") I X]"" D S(BDMPD,26,"PLEASE NOTE:  Diabetes has been used as a diagnosis in PCC: "_X)
 D S(BDMPD,27,$$TOBACCO^BDMDL1T(BDMPD,BDMBDAT,BDMADAT))
 D S(BDMPD,215,$$TOBACCO^BDMDL1T(BDMPD,BDMBDAT,BDMADAT))
 D S(BDMPD,28,$$CESS^BDMDL11(BDMPD,BDMBDAT,BDMADAT))
VITAL ;
 D S(BDMPD,30,$$LASTHT^BDMDL13(BDMPD,BDMADAT))
 D S(BDMPD,32,$$LASTWT^BDMDL13(BDMPD,BDMBDAT,BDMADAT))
 D S(BDMPD,112,$$BMI^BDMDL18(BDMPD,BDMRBD,BDMRED))
 ;htn dx
 S X=$$HTNDX^BDMDL13(BDMPD,BDMADAT) D S(BDMPD,34,$S($E(X)=1:"Yes",1:"No"))
 ;last 3 BPs
 D S(BDMPD,36,$$BPS^BDMDL13(BDMPD,BDMRBD,BDMRED))
EXAMS ;
 S X=$$DIETEDUC^BDMDL17(BDMPD,BDMRBD,BDMRED),X=$P(X,U),X=$P(X,"  ",2) D S(BDMPD,44,X)
 S X=$$EXEDUC^BDMDL17(BDMPD,BDMBDAT,BDMADAT),X=$P(X,"  ",2,99) D S(BDMPD,46,X)
 S X=$$OTHEDUC^BDMDL17(BDMPD,BDMRBD,BDMRED),X=$P(X,"  ",2,99) D S(BDMPD,48,X)
THERAPY ;
 S BDM6MBD=$$FMADD^XLFDT(BDMADAT,-(6*31))
 D S(BDMPD,54,$$MET^BDMDL12(BDMPD,BDM6MBD,BDMRED))
 D S(BDMPD,103,$$SGLT2^BDMDL12(BDMPD,BDM6MBD,BDMRED))
 D S(BDMPD,100,$$GLP1^BDMDL12(BDMPD,BDM6MBD,BDMRED))
 D S(BDMPD,58,$$TIRZ^BDMDL12(BDMPD,BDM6MBD,BDMRED))
 D S(BDMPD,56,$$TROG^BDMDL12(BDMPD,BDM6MBD,BDMRED))
 D S(BDMPD,55,$$ACAR^BDMDL12(BDMPD,BDM6MBD,BDMRED))
 S Z="" F X=54:1:56,58,100,103 I $E($G(^XTMP("BDMPL1",BDMJOB,BDMBTH,"AUDIT",BDMPD,X)))="X" S Z=1  ;ANY MED AT ALL?
 S Y="" F X=54:1:56,58,100,103 I $E($G(^XTMP("BDMPL1",BDMJOB,BDMBTH,"AUDIT",BDMPD,X)))="X" S Y=1
 D S(BDMPD,51,$S(Y:"",1:"X"))
 D S(BDMPD,300,$$STATIN^BDMDL16(BDMPD,BDM6MBD,BDMADAT))
LABS ;
 D S(BDMPD,98,$$FGLUCOSE^BDMDL18(BDMPD,$P(^DPT(BDMPD,0),U,3),BDMADAT))
 D S(BDMPD,99,$$G75^BDMDL18(BDMPD,$P(^DPT(BDMPD,0),U,3),BDMADAT))
 S H=$$HGBA1C^BDMDL18(BDMPD,BDMBDAT,BDMADAT)
 S HD=$P(H,U,1)
 D S(BDMPD,78,H)
 D S(BDMPD,79,$S(H:$$HGBA1C^BDMDL18(BDMPD,$$DOB^AUPNPAT(BDMPD),$$FMADD^XLFDT(HD,-1)),1:""))
 D S(BDMPD,90,$$FGLUCOSE^BDMDL18(BDMPD,$P(^DPT(BDMPD,0),U,3),BDMADAT))
 D S(BDMPD,91,$$G75^BDMDL18(BDMPD,$P(^DPT(BDMPD,0),U,3),BDMADAT))
 D S(BDMPD,86,$$CHOL^BDMDL18(BDMPD,BDMBDAT,BDMADAT))
 D S(BDMPD,88,$$LDL^BDMDL18(BDMPD,BDMBDAT,BDMADAT))
 D S(BDMPD,89,$$HDL^BDMDL18(BDMPD,BDMBDAT,BDMADAT))
 D S(BDMPD,90,$$TRIG^BDMDL18(BDMPD,BDMBDAT,BDMADAT))
 D S(BDMPD,92,$$URIN^BDMDL18(BDMPD,BDMBDAT,BDMADAT))
 ;
 Q
DATE(D) ;EP
 I $G(D)="" Q ""
 Q $E(D,4,5)_"/"_$E(D,6,7)_"/"_(1700+($E(D,1,3)))
TRIBE(P) ;EP
 I '$G(P) Q ""
 I '$D(^AUPNPAT(P,11)) Q ""
 Q $$TRIBE^AUPNPAT(P,"C")_"^"_$$TRIBE^AUPNPAT(P,"E")
COMM(P) ;EP
 I '$G(P) Q ""
 I '$D(^AUPNPAT(P,11)) Q ""
 Q $$COMMRES^AUPNPAT(P,"C")_"^"_$$COMMRES^AUPNPAT(P,"E")
