AUM2106A ;IHS/SET/GTH - SCB UPDATE 2002 APR 02 ; [ 04/05/2002  11:37 AM ]
 ;;02.1;TABLE MAINTENANCE;**6**;SEP 28,2001
 ;
UPDATE ;;IHS STANDARD CODE BOOK MODIFICATIONS   FEB/MAR 2002  04/02/2002
 ;
SUNEW ;;A.  NEW SERVICE UNIT CODES (SECTION VIII-B): AREA^S.U.^NAME
 ;;20^29^TAOS-PICURIS
 ;;END
 ;
SUMOD ;;B.  SERVICE UNIT CHANGES (SECTION VIII-B): AREA^S.U.^NAME
 ;;FROM^66^36^BERRY CREEK/MOORETOWN
 ;;  TO^66^36^FEATHER RIVER TRIBAL HEALTH
 ;;END
 ;
LOCNEW ;;C.  NEW FACILITY CODES (SECTION VIII-C): AREA^S.U.^FAC.^NAME^PSEUDO
 ;;09^02^11^EL RIO @ YAQUI^SBR
 ;;35^31^34^CHICKALOON VILLAGE CLINIC^ABX
 ;;END
 ;
LOCMOD ;;D.  FACILITY CODE CHANGES (SECTION VIII-C): AREA^S.U.^FAC.^NAME^PSEUDO
 ;;FROM^20^24^12^TAOS-PICURIS HEALTH CENTER^QDD
 ;;  TO^20^29^12^TAOS-PICURIS HEALTH CENTER^QBR
 ;;END
 ;
CLINNEW ;;E.  NEW CLINIC CODES (SECTION XIX): CODE^NAME^ABBRV
 ;;A2^DIABETIC RETINOPATHY^DE-RET
 ;;A3^AMBULANCE^AMB
 ;;A4^PERINATOLOGY^PERI
 ;;A5^COMPLEMENTARY MEDICINE^COMP
 ;;END
 ;
TRIBMOD ;;F.  REACTIVATED TRIBE CODES (SECTION XVIII): CODE^NAME^INACTIVE^LONG NAME
 ;;FROM^040^COWLITZ TRIBE^Y^COWLITZ INDIAN TRIBE
 ;;  TO^040^COWLITZ TRIBE^N^COWLITZ INDIAN TRIBE
 ;;END
 ;
 ;
PCLASNEW ;;-.  NEW SERVICES RENDERED BY (PROVIDER CODES) (SECTION XV): CODE^NAME^ABBREV^PCP FACILITY PLANNING^WORKLOAD REPORTING
 ;;00^MD^MD^Y^Y
 ;;01^CLINIC RN^RN^N^Y
 ;;02^ENVIRONMENTAL HEALTH^SAN^N^Y
 ;;03^HEALTH AIDE^HA^N^Y
 ;;04^HEALTH EDUCATOR^HE^N^Y
 ;;05^LICENSED PRACTICAL NURSE^LPN^N^Y
 ;;06^MEDICAL SOCIAL WORKER^MSW^N^Y
 ;;07^NUTRITIONIST^NTN^N^Y
 ;;08^OPTOMETRIST^OPT^N^Y
 ;;09^PHARMACIST^PHR^N^Y
 ;;10^PHYSICAL THERAPIST^PT^N^Y
 ;;11^PHYSICIAN ASSISTANT^CHM^Y^Y
 ;;12^PSYCHOLOGIST^PSY^N^Y
 ;;13^PUBLIC HEALTH NURSE^PHN^N^Y
 ;;14^SCHOOL NURSE^SRN^N^Y
 ;;15^OTHER^OTH^N^Y
 ;;16^PEDIATRIC NURSE PRACTITIONER^PNP^Y^Y
 ;;17^NURSE MIDWIFE^MID^Y^Y
 ;;18^CONTRACT PHYSICIAN^CPH^Y^Y
 ;;19^MENTAL HEALTH^MHW^N^Y
 ;;20^MEDICAL STUDENT^MST^N^Y
 ;;21^NURSE PRACTITIONER^NPR^Y^Y
 ;;22^NURSE ASSISTANT^NAS^N^Y
 ;;23^LABORATORY TECHNICIAN^LAB^N^Y
 ;;24^CONTRACT OPTOMETRIST^COP^N^Y
 ;;25^CONTRACT PODIATRIST^CPO^Y^Y
 ;;26^INHALATION THERAPIST^ITH^N^Y
 ;;27^STUDENT NURSES^STN^N^Y
 ;;28^AUDIOLOGIST^AUD^N^Y
 ;;29^DIETITIAN^DTN^N^Y
 ;;30^PHARMACY PRACTITIONERS^PHP^N^Y
 ;;31^OPTOMETRIC ASSISTANT^OPA^N^Y
 ;;32^CONTRACT PUBLIC HEALTH NURSE^CPN^N^Y
 ;;33^PODIATRIST^POD^Y^Y
 ;;34^TRIBAL/CONTRACT NUTRITIONIST^TCN^N^Y
 ;;35^OUTREACH WORKER^OUT^N^Y
 ;;36^EYE CARE SPECIALIST^EYE^N^Y
 ;;37^FAMILY PLANNING COUNSELOR^FPC^N^Y
 ;;38^EMT/PARAMEDIC^EMT^N^Y
 ;;39^SPEECH THERAPIST^SPT^N^Y
 ;;40^AMBULANCE DRIVER^AMB^N^Y
 ;;41^CONTRACT OB/GYN^COB^Y^Y
 ;;42^SPEECH/LANGUAGE PATH^SLP^N^Y
 ;;43^AUDIOMETRIC TECHNICIAN^AMT^N^Y
 ;;44^TRIBAL PHYSICIAN^TPH^Y^Y
 ;;45^OSTEOPATHIC MEDICINE^OST^Y^Y
 ;;46^DENTAL HYGIENIST^DHY^N^Y
 ;;47^CRNA^CRN^N^Y
 ;;48^ALCOHOLISM/SUB ABUSE COUNSELOR^ALC^N^Y
 ;;49^CONTRACT PSYCHIATRIST^CPY^Y^Y
 ;;50^CONTRACT PSYCHOLOGIST^CPC^N^Y
 ;;51^PAPAGO NUTRITION PROGRAM^NTR^N^Y
 ;;52^DENTIST^DEN^N^Y
 ;;53^COMMUNITY HEALTH REPRESENTATIVE^CHR^N^Y
 ;;54^DENTAL ASSISTANT (PRENATAL)^DAP^N^Y
 ;;55^DISEASE CONTROL PROGRAM^DCP^N^Y
 ;;56^HEALTH RECORDS^HR^N^N
 ;;57^ADMINISTRATIVE^ADM^N^N
 ;;58^SPEECH THER-DISCONTINUE^SPT^N^N
 ;;59^XRAY TECHNICIAN^XRY^N^Y
 ;;60^DENTAL ASSISTANT^DAS^N^Y
 ;;61^DENTAL LAB^DLA^N^Y
 ;;62^LICENSED MEDICAL SOCIAL WORKER^LMS^N^Y
 ;;63^CONTRACT SOCIAL WORKER^CSW^N^Y
 ;;64^NEPHROLOGIST^NPH^Y^Y
 ;;65^OPTOMETRY STUDENT^OPS^N^Y
 ;;66^CASE MANAGERS^CSM^N^Y
 ;;67^CLINICAL PHARMACY SPECIALIST^CPS^N^Y
 ;;68^EMERGENCY ROOM PHYSICIAN^ERP^Y^Y
 ;;69^CHIROPRACTOR^CHI^Y^Y
 ;;70^CARDIOLOGIST^CAR^Y^Y
 ;;71^INTERNAL MEDICINE^INT^Y^Y
 ;;72^OB/GYN^GYN^Y^Y
 ;;73^ORTHOPEDIST^ORT^Y^Y
 ;;74^OTOLARYNGOL^OTO^Y^Y
 ;;75^PEDIATRICIAN^PED^Y^Y
 ;;76^RADIOLOGIST^RAD^Y^Y
 ;;77^SURGEON^SUR^Y^Y
 ;;78^UROLOGIST^URO^Y^Y
 ;;79^OPHTHALMOLOGIST^OPH^Y^Y
 ;;80^FAMILY PRACTICE^FP^Y^Y
 ;;81^PSYCHIATRIST^PSC^Y^Y
 ;;82^ANESTHESIOLOGIST^ANE^Y^Y
 ;;83^PATHOLOGIST^PAT^Y^Y
 ;;84^PEDORTHIST^PDO^Y^Y
 ;;85^NEUROLOGIST^NEU^Y^Y
 ;;86^DERMATOLOGIST^DER^Y^Y
 ;;87^ULTRASOUND TECHNICIAN^ULT^N^Y
 ;;88^CODING/DATA ENTRY^CDE^N^N
 ;;89^AUDIOLOGY HEALTH TECHNICIAN^AHT^N^Y
 ;;90^OCCUPATIONAL THERAPIST^OCC^N^Y
 ;;91^PHN DRIVER/INTERPRETER^PDR^N^N
 ;;92^PSYCHOTHERAPIST^PST^N^Y
 ;;93^TRADITIONAL MEDICINE PRACTITIONER^TMP^N^Y
 ;;94^MENTAL HEALTH (BA/BS ONLY)^MHB^N^Y
 ;;95^MENTAL HEALTH (MASTER ONLY)^MHA^N^Y
 ;;96^FAMILY THERAPIST^FMT^N^Y
 ;;97^NUTRITION TECHNICIAN^NTC^N^Y
 ;;98^FOOD SERVICE SUPERVISOR^FSS^N^N
 ;;99^DIETETIC TECHNICIAN^DTC^N^Y
 ;;A1^SPORTS MEDICINE PHYSICIAN^SMP^Y^Y
 ;;A2^MEDICAL TECHNOLOGIST^MTC^N^Y
 ;;END
 ;
