AUM2109A ;IHS/SET/GTH - SCB UPDATE 2002 AUG 01 ; [ 08/13/2002   9:03 AM ]
 ;;02.1;TABLE MAINTENANCE;**9**;SEP 28,2001
 ;
UPDATE ;;IHS STANDARD CODE BOOK MODIFICATIONS  MAY/JUN/JUL 2002  08/01/2002
 ;
LOCNEW ;;A.  NEW FACILITY CODES (SECTION VIII-C): AREA^S.U.^FAC.^NAME^PSEUDO
 ;;00^01^62^SANTA ROSA RANCH DAY SCHOOL^SBS
 ;;55^52^21^CHER NTN BARTLESVILLE HLTH CLN^OBX
 ;;55^52^22^CHER NTN VINITA HEALTH CLINIC^OBY
 ;;END
 ;
LOCMOD ;;B.  FACILITY CODE CHANGES (SECTION VIII-C): AREA^S.U.^FAC.^NAME^PSEUDO
 ;;FROM^35^31^23^MT SANFORD TRB HLTH CONSORTIUM^ASU
 ;;  TO^35^31^37^MT SANFORD TRB HLTH CONSORTIUM^ASX
 ;;FROM^47^49^30^NATIVE AMERICAN CENTER INC^BKE
 ;;  TO^47^49^30^INDIAN FAMILY HEALTH CLINIC^BKE
 ;;FROM^64^85^10^CLOVIS INDIAN H.C.^LWI
 ;;  TO^64^85^10^FRESNO CLINIC^LWI
 ;;FROM^75^79^32^LOWER ELWAH CLINIC^PPN
 ;;  TO^75^79^32^LOWER ELWHA CLINIC^PPN
 ;;FROM^75^85^31^COEUR DALENE^PRC
 ;;  TO^75^85^31^BENEWAH MEDICAL CENTER^PRC
 ;;END
 ;
LOCINACT ;;C.  INACTIVATED FACILITY CODES (SECTION VIII-C): AREA^S.U.^FAC.^NAME^PSEUDO
 ;;60^62^31^SECOND MESA HS^XCE
 ;;60^63^50^DUCKWATER^XEU
 ;;END
 ;
COMMNEW ;;D.  NEW COMMUNITY CODES (SECTION V-C): STATE^CNTY^COMM^NAME^AREA^S.U.
 ;;16^40^113^CALDER^70^00
 ;;END
 ;
CLINNEW ;;E.  NEW CLINIC CODES (SECTION XIX): CODE^NAME^ABBRV^PRIMARY CARE CLINIC^1A WORKLOAD^MEDICARE^MEDICAID
 ;;A7^RYAN WHITE EARLY INTERVENTION^RWEI^^Y^^
 ;;A8^WELLNESS^WELL^^Y^^
 ;;END
 ;
ICD9MOD ;;-- RENAME ICD DIAGNOSIS CODE 305.1: CODE^DIAGNOSIS^MAJOR DIAGNOSTIC CATEGORY^DESCRIPTION
 ;;305.1^TOBACCO USE DISORDER^MENTAL DISEASES & DISORDERS^TOBACCO USE DISORDER
 ;;END
 ;
CLINMOD ;;-- POPULATE CLINIC CODE 1A REPORT FIELD: CODE^NAME^ABBRV^PRIMARY CARE CLINIC^1A WORKLOAD^MEDICARE^MEDICAID
 ;;01^GENERAL^GEN^Y^Y^Y^Y
 ;;02^CARDIAC^^^Y^Y^Y
 ;;03^CHEST AND TB^^^Y^Y^Y
 ;;04^CRIPPLED CHILDREN^^^Y^Y^Y
 ;;05^DERMATOLOGY^^^Y^Y^Y
 ;;06^DIABETIC^DE^Y^Y^Y^Y
 ;;07^ENT^^^Y^Y^Y
 ;;08^FAMILY PLANNING^^^Y^Y^Y
 ;;09^GROUP SERVICES^^^N^Y^Y
 ;;10^GYNECOLOGY^^^Y^Y^Y
 ;;11^HOME CARE^^^N^N^Y
 ;;12^IMMUNIZATION^^^Y^Y^Y
 ;;13^INTERNAL MEDICINE^INT^Y^Y^Y^Y
 ;;14^MENTAL HEALTH^^^Y^Y^Y
 ;;15^OBESITY^^^Y^Y^Y
 ;;16^OBSTETRICS^^^Y^Y^Y
 ;;17^OPHTHALMOLOGY^^^Y^Y^Y
 ;;18^OPTOMETRY^^^Y^Y^Y
 ;;19^ORTHOPEDIC^^^Y^Y^Y
 ;;20^PEDIATRIC^PED^Y^Y^Y^Y
 ;;21^REHABILIATION^^^Y^Y^Y
 ;;22^SCHOOL^^^Y^N^Y
 ;;23^SURGICAL^^^Y^Y^Y
 ;;24^WELL CHILD^WC^Y^Y^Y^Y
 ;;25^OTHER B/^^^Y^Y^Y
 ;;26^HIGH RISK^^^Y^Y^Y
 ;;27^GENERAL PREVENTIVE^^^Y^Y^Y
 ;;28^FAMILY PRACTICE^FAMPRA^Y^Y^Y^Y
 ;;29^PLASTIC SURGERY^^^Y^Y^Y
 ;;30^EMERGENCY MEDICINE^^^Y^Y^Y
 ;;31^HYPERTENSIVE^^^Y^Y^Y
 ;;32^POSTPARTUM^^^Y^Y^Y
 ;;33^INHALATION THERAPY^^^Y^Y^Y
 ;;34^PHYSICAL THERAPY^^^Y^Y^Y
 ;;35^AUDIOLOGY^^^Y^Y^Y
 ;;36^W. I. C.^^^N^Y^Y
 ;;37^NEUROLOGY^^^Y^Y^Y
 ;;38^RHEUMAOLOGY^^^Y^Y^Y
 ;;39^PHARMACY^^^Y^Y^Y
 ;;40^INFANT STIMULATION^^^Y^Y^Y
 ;;41^INDIRECT^^^N^N^N
 ;;42^MAIL^^^N^N^N
 ;;43^ALCOHOL AND SUBSTANCE^A/S^^Y^Y^Y
 ;;44^DAY SURGERY^DS^^Y^Y^Y
 ;;45^PHN CLINIC VISIT^PHN^^Y^Y^Y
 ;;46^NIH CLINIC^NIHC^^Y^Y^N
 ;;47^FETAL ALCOHOL SYNDROME^FAS^^Y^Y^Y
 ;;48^MEDICAL SOCIAL SERVICES^MED SS^^Y^Y^Y
 ;;49^NEPHROLOGY^NEPH^^Y^Y^Y
 ;;50^CHRONIC DISEASE^CD^^Y^Y^Y
 ;;51^TELEPHONE CALL^^^N^N^N
 ;;52^CHART REV/REC MOD^^^N^N^N
 ;;53^FOLLOW-UP LETTER^^^N^N^N
 ;;54^RADIO CALL^^^N^N^N
 ;;55^CAST ROOM^^^Y^Y^Y
 ;;56^DENTAL^^^N^Y^Y
 ;;57^EPSDT^^^Y^Y^Y
 ;;58^CANCER SCREENING^^^Y^Y^Y
 ;;59^VENEREAL DISEASE^VD^^Y^Y^Y
 ;;60^EDUCATION CLASSES^^^N^Y^Y
 ;;61^DEVEL. ASSESSMENT^^^Y^Y^Y
 ;;62^CANCER CHEMOTHERAPY^^^Y^Y^Y
 ;;63^RADIOLOGY^^^Y^Y^Y
 ;;64^RETINOPATHY^^^Y^Y^Y
 ;;65^PODIATRY^POD^^Y^Y^Y
 ;;66^ULTRASOUND^ULT^^Y^Y^Y
 ;;67^DIETARY^DIA^^Y^Y^Y
 ;;68^EMPLOYEE HEALTH UNIT^EHU^^Y^Y^Y
 ;;69^ENDOCRINOLOGY^END^^Y^Y^Y
 ;;70^WOMEN'S HEALTH SCREENING^WHS^^Y^Y^Y
 ;;71^COMPUTED TOMOGRAPHY^TOMO^^Y^Y^Y
 ;;72^MAMMOGRAPHY^MAMM^^Y^Y^Y
 ;;73^GENETICS^GENETI^^Y^Y^Y
 ;;74^SPEECH PATHOLOGY^PATHOL^^Y^Y^Y
 ;;75^UROLOGY^UROLOG^^Y^Y^Y
 ;;76^LABORATORY SERVICES^LAB^^Y^Y^Y
 ;;77^CASE MANAGEMENT SERVICES^^^Y^Y^Y
 ;;78^OTC MEDICATIONS^^^Y^Y^Y
 ;;79^TRIAGE^^^Y^Y^Y
 ;;80^URGENT CARE^^^Y^Y^Y
 ;;81^MEN'S HEALTH SCREENING^^^Y^Y^Y
 ;;82^DAY TREATMENT PROG^^^Y^Y^Y
 ;;83^LABOR AND DELIVERY^^^Y^Y^Y
 ;;84^PAIN REDUCTION^^^Y^Y^Y
 ;;85^TEEN CLINIC^^^Y^Y^Y
 ;;86^TRADITIONAL MEDICINE^^^Y^N^N
 ;;87^OBSERVATION^^^Y^^
 ;;88^SPORTS MEDICINE^^^Y^^
 ;;89^EVENING^^^Y^^
 ;;90^TELEMEDICINE^^^Y^^
 ;;91^TELERADIOLOGY^^^Y^^
 ;;92^DIALYSIS^^^Y^^
 ;;93^OCCUPATIONAL THERAPY^OCCT^^Y^Y^Y
 ;;94^TOBACCO CESSATION CLINIC^TCC^^Y^N^
 ;;95^DIALYSIS LABORATORY SERVICES^DLS^^Y^Y^Y
 ;;96^PEDIAT OUTP USE OF INP TRTM RM^POT^^Y^N^N
 ;;97^SURG OUTP USE OF INP TRTMNT RM^SOT^^Y^N^N
 ;;98^DIABETES EDUCATION-GROUP^DE-G^^Y^^
 ;;99^THIRD PARTY DENTAL^3RDD^^N^Y^Y
 ;;A1^DIABETES EDUCATION-INDIVIDUAL^DE-I^^Y^^
 ;;A2^DIABETIC RETINOPATHY^DE-RET^^Y^Y^Y
 ;;A3^AMBULANCE^AMB^^Y^Y^Y
 ;;A4^PERINATOLOGY^PERI^^Y^Y^Y
 ;;A5^COMPLEMENTARY MEDICINE^COMP^^Y^Y^Y
 ;;A6^CHIROPRACTIC^CHIRO^^Y^Y^Y
 ;;END
 ;
