AUM3101A ;IHS/SET/GTH - SCB UPDATE 2002 SEP 10 ; [ 10/04/2002  11:09 AM ]
 ;;3.1;TABLE MAINTENANCE;**1**;SEP 23,2002
 ;
UPDATE ;;IHS STANDARD CODE BOOK MODIFICATIONS - AUG 2002  09/10/2002
 ;
AREANEW ;;A.  NEW AREA CODES (SECTION VIII-A):  AREA^NAME^PREFIX/REGION^CAN PREFIX
 ;;27^ALBUQUERQUE URBAN^Q^J53
 ;;END
 ;
SUNEW ;;B.  NEW SERVICE UNIT CODES (SECTION VIII-B): AREA^S.U.^NAME
 ;;27^00^NON SERVICE UNIT
 ;;27^21^ALBUQUERQUE
 ;;85^88^WINSLOW
 ;;END
 ;
LOCNEW ;;C.  NEW FACILITY CODES (SECTION VIII-C): AREA^S.U.^FAC.^NAME^PSEUDO
 ;;60^69^19^RENO/SPARKS IHS^XDX
 ;;65^63^89^HOME^XEC
 ;;75^75^76^SNOQUALMIE TRIBAL PROGRAMS^PDQ
 ;;85^87^01^TUBA CITY INDIAN MEDICAL CTR^NLZ
 ;;85^88^11^WINSLOW HEALTH CENTER^NLU
 ;;END
 ;
LOCMOD ;;D.  FACILITY CODE CHANGES (SECTION VIII-C): AREA^S.U.^FAC.^NAME^PSEUDO
 ;;FROM^25^00^66^DENVER IND HLTH & FAMILY SVCS^QJW
 ;;  TO^27^00^66^DENVER IND HLTH & FAMILY SVCS^QCT
 ;;FROM^25^21^66^FIRST NATIONS COMM HLTH SOURCE^QJV
 ;;  TO^27^21^66^FIRST NATIONS COMM HLTH SOURCE^QCU
 ;;FROM^35^34^62^NAKNEK^APQ
 ;;  TO^35^34^62^CAMAI HEALTH CLINIC^APQ
 ;;FROM^80^87^30^DINNEBITO HEALTH STATION^NGC^*
 ;;  TO^85^87^30^DINNEBITO HEALTH STATION^NNW
 ;;FROM^80^87^51^TUBA CITY/MUNGUPI WELLNESS CTR^NIU^*
 ;;  TO^85^87^51^TUBA CITY/MUNGUPI WELLNESS CTR^NNY
 ;;FROM^80^87^52^GREYHILLS HIGH SCHOOL^NLC^*
 ;;  TO^85^87^54^GREYHILLS HIGH SCHOOL^NPS
 ;;FROM^80^87^53^TUBA CITY HIGH SCHOOL^NLD^*
 ;;  TO^85^87^53^TUBA CITY HIGH SCHOOL^NNZ
 ;;FROM^80^88^33^DILKON HEALTH STATION^NHJ
 ;;  TO^85^88^33^DILKON HEALTH STATION^NLW
 ;;FROM^80^88^34^LEUPP HEALTH STATION^NHK
 ;;  TO^85^88^34^LEUPP HEALTH STATION^NLX
 ;;FROM^80^88^67^WINSLOW MOBILE CLINIC^NHZ
 ;;  TO^85^88^67^WINSLOW MOBILE CLINIC^NLY
 ;;END
 ;
 ;Note: The above changes marked with an asterisk will become effective
 ;      09/30/2002.
 ;
MEASMOD ;; -- MEASUREMENT TYPE Modification: TYPE^DESCRIPTION^CODE
 ;;FROM^AG^ABDOMIAL GIRTH^50
 ;;  TO^AG^ABDOMINAL GIRTH^50
 ;;FROM^AUD^AUDIOMETREY^10
 ;;  TO^AUD^AUDIOMETRY^10
 ;;FROM^EF^EFACEMENT^58
 ;;  TO^EF^EFFACEMENT^58
 ;;END
 ;
HFMOD ;; -- HEALTH FACTORS Modification: FACTOR^CATEGORY^ENTRY TYPE
 ;;FROM^CURRENT SMOKER & SMOKELESS
 ;;  TO^CURRENT SMOKER & SMOKELESS^TOBACCO^FACTOR
 ;;FROM^EXPOSURE TO ENVIRONMENTAL TOBACCO SMOKE
 ;;  TO^EXPOSURE TO ENVIRONMENTAL TOBACCO SMOKE^TOBACCO^FACTOR
 ;;END
 ;
CLINMOD ;;-- CLINIC STOP Modification: CODE^NAME^ABBRV^PRIMARY CARE CLINIC^1A WORKLOAD^MEDICARE^MEDICAID
 ;;FROM^09^GROUPED SERVICES A/^^N
 ;;  TO^09^GROUPED SERVICES^^N
 ;;FROM^25^OTHER B/^^Y
 ;;  TO^25^OTHER^^Y
 ;;END
 ;
STATEMOD ;; -- STATE Modification: CODE^NAME^ABBREVIATION^CAPITAL
 ;;FROM^99^UNKNOWN^UK^
 ;;  TO^99^UNKNOWN^XX^
 ;;END
 ;
DOMNEW ;; -- DOMAIN Addition:
 ;;SNOQUALMI-HS.PRT.IHS.GOV
 ;;END
 ;
