BSDX25 ; IHS/OIT/HMW - WINDOWS SCHEDULING RPCS ;
 ;;1.0;IHS WINDOWS SCHEDULING;**1**;AUG 24, 2005
 ;
 ;
CHECKIND(BSDXY,BSDXAPTID,BSDXCDT,BSDXCC,BSDXPRV,BSDXROU,BSDXVCL,BSDXVFM,BSDXOG) ;EP
 ;Entry point for debugging
 ;
 ;I +$G(^BSDXDBUG("BREAK","CHECKIN")),+$G(^BSDXDBUG("BREAK"))=DUZ D DEBUG^%Serenji("CHECKIN^BSDX25(.BSDXY,BSDXAPTID,BSDXCDT,BSDXCC,BSDXPRV,BSDXROU,BSDXVCL,BSDXVFM,BSDXOG)",$P(^BSDXDBUG("BREAK"),U,2))
 ;E  G ENDBG
 Q
 ;
CHECKIN(BSDXY,BSDXAPTID,BSDXCDT,BSDXCC,BSDXPRV,BSDXROU,BSDXVCL,BSDXVFM,BSDXOG) ;EP Check in appointment
 ;
ENDBG ;
 N BSDXNOD,BSDXPATID,BSDXSTART,DIK,DA,BSDXID,BSDXI,BSDXZ,BSDXIENS,BSDXVEN
 N BSDXNOEV
 S BSDXNOEV=1 ;Don't execute protocol
 ;
 D ^XBKVAR S X="ERROR^BSDX25",@^%ZOSF("TRAP")
 S BSDXI=0
 K ^BSDXTMP($J)
 S BSDXY="^BSDXTMP("_$J_")"
 S ^BSDXTMP($J,0)="T00020ERRORID"_$C(30)
 I '+BSDXAPTID D ERR("BSDX25: Invalid Appointment ID") Q
 I '$D(^BSDXAPPT(BSDXAPTID,0)) D ERR("BSDX08: Invalid Appointment ID") Q
 ;
 S:BSDXCDT["@0000" BSDXCDT=$P(BSDXCDT,"@")
 S %DT="T",X=BSDXCDT D ^%DT S BSDXCDT=Y
 I BSDXCDT=-1 D ERR(70) Q
 I BSDXCDT>$$NOW^XLFDT S BSDXCDT=$$NOW^XLFDT
 ;Checkin BSDX APPOINTMENT entry
 D BSDXCHK(BSDXAPTID,BSDXCDT)
 S BSDXNOD=^BSDXAPPT(BSDXAPTID,0)
 S BSDXPATID=$P(BSDXNOD,U,5)
 S BSDXSTART=$P(BSDXNOD,U)
 ;
 S BSDXSC1=$P(BSDXNOD,U,7) ;RESOURCEID
 I BSDXSC1]"",$D(^BSDXRES(BSDXSC1,0)) D  I +$G(BSDXZ) D ERR($P(BSDXZ,U,2)) Q
 . S BSDXNOD=^BSDXRES(BSDXSC1,0)
 . S BSDXSC1=$P(BSDXNOD,U,4) ;HOSPITAL LOCATION
 . I BSDXSC1]"",$D(^SC(BSDXSC1,0)) D APCHK(.BSDXZ,BSDXSC1,BSDXPATID,BSDXCDT,BSDXSTART)
 ;
 S BSDXI=BSDXI+1
 ;S ^BSDXTMP($J,BSDXI)="-1"_$C(30)
 S ^BSDXTMP($J,BSDXI)="0"_$C(30)
 S BSDXI=BSDXI+1
 S ^BSDXTMP($J,BSDXI)=$C(31)
 Q
 ;
BSDXCHK(BSDXAPTID,BSDXCDT) ;
 ;
 S BSDXIENS=BSDXAPTID_","
 S BSDXFDA(9002018.4,BSDXIENS,.03)=BSDXCDT
 D FILE^DIE("","BSDXFDA","BSDXMSG")
 Q
 ;
APCHK(BSDXZ,BSDXSC1,BSDXDFN,BSDXCDT,BSDXSTART)         ;
 ;Checkin appointment for patient BSDXDFN in clinic BSDXSC1
 ;at time BSDXSD
 N BSDXC
 ;  BSDR("PAT") = ien of patient in file 2
 ;  BSDR("CLN") = ien of clinic in file 44
 ;  BSDR("ADT") = appt date/time
 ;  BSDR("CDT") = checkin date/time
 ;  BSDR("USR") = checkin user
 S BSDXC("PAT")=BSDXPATID
 ;S BSDXC("CLN")=BSDXSC1
 S BSDXC("HOS LOC")=BSDXSC1
 ;S BSDXC("CC")=BSDXCC
 S BSDXC("CLINIC CODE")=BSDXCC
 ;S BSDXC("PRV")=BSDXPRV
 S BSDXC("PROVIDER")=BSDXPRV
 ;S BSDXC("ADT")=BSDXSTART
 S BSDXC("APPT DATE")=BSDXSTART
 S BSDXC("CDT")=BSDXCDT
 S BSDXC("USR")=DUZ
 ;
 ;Required by NEW API:
 S BSDXC("SRV CAT")="A"
 S BSDXC("TIME RANGE")=-1
 S BSDXC("VISIT DATE")=BSDXCDT ;IHS/HMW **1** 20060419
 S BSDXC("SITE")=$G(DUZ(2))
 S BSDXC("VISIT TYPE")="I"
 ;TELL LINDA ABOUT THESE 2 -- SAME VARIABLES WITH DIFFERENT NAMES
 S BSDXC("CLN")=BSDXC("HOS LOC")
 S BSDXC("ADT")=BSDXC("APPT DATE")
 ;
 ;Set up BSDXVEN array containing VEN EHP CLINIC, VEN EHP FORM, OUTGUIDE FLAG
 ;These values come from input param
 S BSDXVEN("CLINIC")=BSDXVCL
 S BSDXVEN("FORM")=BSDXVFM
 S BSDXVEN("OUTGUIDE")=BSDXOG
 ;
 ;S BSDXZ=$$CHECKIN^BSDAPI(.BSDXC)
 N BSDXOUT
 D GETVISIT^BSDAPI4(.BSDXC,.BSDXOUT)
 Q
 ;
CHKEVT(BSDXPAT,BSDXSTART,BSDXSC) ;EP Called by BSDX CHECKIN APPOINTMENT event
 ;when appointments CHECKIN via PIMS interface.
 ;Propagates CHECKIN to BSDXAPPT and raises refresh event to running GUI clients
 ;
 Q:+$G(BSDXNOEV)
 Q:'+$G(BSDXSC)
 N BSDXSTAT,BSDXFOUND,BSDXRES
 S BSDXSTAT=""
 S:$G(SDATA("AFTER","STATUS"))["CHECKED IN" BSDXSTAT=$P(SDATA("AFTER","STATUS"),"^",4)
 S BSDXFOUND=0
 I $D(^BSDXRES("ALOC",BSDXSC)) S BSDXRES=$O(^BSDXRES("ALOC",BSDXSC,0)) S BSDXFOUND=$$CHKEVT1(BSDXRES,BSDXSTART,BSDXPAT,BSDXSTAT)
 I BSDXFOUND D CHKEVT3(BSDXRES) Q
 I $D(^BXDXRES("ASSOC",BSDXSC)) S BSDXRES=$O(^BSDXRES("ASSOC",BSDXSC,0)) S BSDXFOUND=$$CHKEVT1(BSDXRES,BSDXSTART,BSDXPAT,BSDXSTAT)
 I BSDXFOUND D CHKEVT3(BSDXRES)
 Q
 ;
CHKEVT1(BSDXRES,BSDXSTART,BSDXPAT,BSDXSTAT) ;
 ;Get appointment id in BSDXAPT
 ;If found, call BSDXNOS(BSDXAPPT) and return 1
 ;else return 0
 N BSDXFOUND,BSDXAPPT
 S BSDXFOUND=0
 Q:'+$G(BSDXRES) BSDXFOUND
 Q:'$D(^BSDXAPPT("ARSRC",BSDXRES,BSDXSTART)) BSDXFOUND
 S BSDXAPPT=0 F  S BSDXAPPT=$O(^BSDXAPPT("ARSRC",BSDXRES,BSDXSTART,BSDXAPPT)) Q:'+BSDXAPPT  D  Q:BSDXFOUND
 . S BSDXNOD=$G(^BSDXAPPT(BSDXAPPT,0)) Q:BSDXNOD=""
 . I $P(BSDXNOD,U,5)=BSDXPAT,$P(BSDXNOD,U,12)="" S BSDXFOUND=1 Q
 I BSDXFOUND,+$G(BSDXAPPT) D BSDXCHK(BSDXAPPT,BSDXSTAT)
 Q BSDXFOUND
 ;
CHKEVT3(BSDXRES) ;
 ;Call RaiseEvent to notify GUI clients
 ;
 N BSDXRESN
 S BSDXRESN=$G(^BSDXRES(BSDXRES,0))
 Q:BSDXRESN=""
 S BSDXRESN=$P(BSDXRESN,"^")
 ;D EVENT^BSDX23("SCHEDULE-"_BSDXRESN,"","","")
 D EVENT^BMXMEVN("BSDX SCHEDULE",BSDXRESN)
 Q
 ;
ERROR ;
 D ERR("RPMS Error")
 Q
 ;
ERR(ERRNO) ;Error processing
 I +ERRNO S BSDXERR=ERRNO+134234112 ;vbObjectError
 E  S BSDXERR=ERRNO
 S BSDXI=BSDXI+1
 S ^BSDXTMP($J,BSDXI)=BSDXERR_$C(30)
 S BSDXI=BSDXI+1
 S ^BSDXTMP($J,BSDXI)=$C(31)
 Q
