AZZZEOB1 ; IHS/ADC/GTH - PROCESS EOBRS (2/6) - READ IN, PROCESS ; [ 05/20/1999  9:49 AM ]
 ;;3.0;CONTRACT HEALTH MGMT SYSTEM;**10**;SEP 17, 1997
 ;
 KILL ^TMP("ACHSEOB",$J)
 D NOW^ACHS
 S ACHSTIME=$$C^XBFUNC(ACHSTIME,80)
 S (ACHSTERR,ACHSZRC,ACHSCTR,ACHSEFL9)=0,(ACHSOLD,ACHSZFLC)=""
 D ^AZZZEOBM
 I $D(ACHSAEND) S ACHSTERR=1 Q
MAIN ;
 U IO
 R ACHSEOBR:300
 U IO(0)
 I ACHSEOBR="" S ACHSTERR=1 W !,"Unexpected End Of FIle!  This file is incomplete." G TERR
 I ACHSISAO=1 S ACHSEOBR=$E(ACHSEOBR,3,85)
 I ACHSEOBR=""!($E(ACHSEOBR,1,2)="**") D M1^AZZZEOBB G END
 I ACHSOLD="" S ACHSOLD=$E(ACHSEOBR,1,18)
 I ACHSOLD'=$E(ACHSEOBR,1,18) D M1^AZZZEOBB
 Q:ACHSTERR
 D REC^AZZZEOBB
 G TERR:ACHSTERR
 I ACHSZFLC=$E(ACHSEOBR,1,6) S ACHSZFLC=$E(ACHSEOBR,1,6) G WRITE
 S ACHSZZ=$E(ACHSEOBR,1,6),ACHSZFPT="",ACHSZFPT=$O(^AUTTLOC("C",ACHSZZ,ACHSZFPT))
 S ACHSZ3=$E(ACHSEOBR,55,57)
 I +ACHSZFPT=0 S ACHSZFPT="",ACHSZFPT=$O(^AUTTLOC("CTOO",ACHSZZ,ACHSZFPT))
 S ACHSZPT3="",ACHSZPT3=$O(^AUTTLOC("FLC",ACHSZ3,ACHSZPT3))
 I +ACHSZPT3>0,ACHSZFPT=ACHSZPT3 G CONT
 I +ACHSZPT3>0 U IO(0) W !,"FACILITY CODE PROBLEM -- USING DOCUMENT LOCATION" S ACHSZFPT=ACHSZPT3 G CONT
 I 'ACHSZFPT S ACHSZFPT=$$FLC(ACHSZ3)
 I +ACHSZFPT=0 U IO(0) W *7,!!,"Invalid Facility Code ",$E(ACHSEOBR,1,6)," in EOBR Data -- JOB CANCELLED" S ACHSTERR=1 Q
CONT ;
 S:$D(^DIC(4,ACHSZFPT,0)) ACHSZFNM=$P(^DIC(4,ACHSZFPT,0),U,1)
 U IO(0)
 W !!?10,"Processing EOBR Data for: ",ACHSZFNM,!!
 S ACHSZFLC=$E(ACHSEOBR,1,6)
WRITE ;
 S ACHSCTR=ACHSCTR+1,^ACHSEOBR(ACHSZFPT,ACHSCTR)=ACHSEOBR
 I $E(ACHSEOBR,19)="H" D SUMM:$S(ACHSISAO:$$AOP^ACHS(2,6)="Y",1:$$PARM^ACHS(2,14)="Y")
 I $E(ACHSEOBR,19)'="A" G MAIN
 S:'$D(ACHSZFCT(ACHSZFPT)) ACHSZFCT(ACHSZFPT)=0
 S ACHSZFCT(ACHSZFPT)=ACHSZFCT(ACHSZFPT)+1
 S ACHSCTR(1)=ACHSCTR
 S ACHSZRC=ACHSZRC+1
 I ACHSZRC#10=0 U IO(0) W $J(ACHSZRC,8)
 G MAIN
 ;
GBLD ;EP - Build ACHSEOBR("M") from "F" records.
 S:'$D(ACHSEOBR("M","ACHSMSEQ")) ACHSEOBR("M","ACHSMSEQ")=0
 S ACHSMSG=""
 S:$D(ACHSEOBR("F",14)) ACHSMSG=ACHSEOBR("F",14)
 Q:ACHSMSG=""!("RM"'[$E(ACHSMSG,1,1))
 S ACHSMSEQ=ACHSEOBR("M","ACHSMSEQ")+1,ACHSEOBR("M","ACHSMSEQ")=ACHSMSEQ
 S:'$D(ACHSEOBR("M","B",ACHSMSG)) ACHSEOBR("M",ACHSMSEQ)=ACHSMSG,ACHSEOBR("M","B",ACHSMSG)=""
 Q
 ;
SIGN ;EP - Extract the Sign of the field from the last character in
 ;     the field.
 ;S Y=$E(ACHSEOBR,$P(X,".",3))
 S Y=$E(ACHSREC,$P(X,".",3)) ;ACHS*3*9
 ;I "}JKLMNOPQR"[Y S ACHSEOBR=$E(ACHSEOBR,1,$P(X,".",2)-1)_"-"_$E(ACHSEOBR,$P(X,".",2)+1,$P(X,".",3)-1)_$S(Y="}":0,1:$C($A(Y)-25))_$E(ACHSEOBR,$P(X,".",3)+1,80) Q
 I "}JKLMNOPQR"[Y S ACHSREC=$E(ACHSREC,1,$P(X,".",2)-1)_"-"_$E(ACHSREC,$P(X,".",2)+1,$P(X,".",3)-1)_$S(Y="}":0,1:$C($A(Y)-25))_$E(ACHSREC,$P(X,".",3)+1,80) Q  ;ACHS*3*9
 ;I "{ABCDEFGHI"[Y S ACHSEOBR=$E(ACHSEOBR,1,$P(X,".",3)-1)_$S(Y="{":0,1:$C($A(Y)-16))_$E(ACHSEOBR,$P(X,".",3)+1,80)
 I "{ABCDEFGHI"[Y S ACHSREC=$E(ACHSREC,1,$P(X,".",3)-1)_$S(Y="{":0,1:$C($A(Y)-16))_$E(ACHSREC,$P(X,".",3)+1,80) ;ACHS*3*9
 Q
 ;
SUMM ;
 D REC1^AZZZEOBB
 U ACHSEOIO
 W @IOF,!!?24,"--- SUMMARY OF EOBR PROCESSED ---",!!,$$C^XBFUNC(ACHSTIME,80),!!!
 W ?5,"INDIAN HEALTH SERVICE",?40,"CONTRACT HEALTH SERVICES",!!,"AO: ",$P(^AUTTAREA($O(^AUTTAREA("C",ACHSEOBR("H",1),0)),0),U)
 W !!,"SU: ",$P(^AUTTSU($O(^AUTTSU("C",ACHSEOBR("H",1)_ACHSEOBR("H",2),0)),0),U)
 W !!!?23,"FISCAL YEAR:  ",ACHSEOBR("H",4)
 W !!!!!?15,"AUTHORIZING FACILITY:  ",$S($O(^AUTTLOC("C",ACHSEOBR("H",8),0)):$P(^AUTTLOC($O(^AUTTLOC("C",ACHSEOBR("H",8),0)),0),U,2),1:ACHSEOBR("H",8)),!!
 W ?20,"PERIOD COVER(S):  "
 I +ACHSEOBR("H",9) W $$FMTE^XLFDT($S(+$E(ACHSEOBR("H",9),1,2)>50:2,1:3)_"000000"+ACHSEOBR("H",9))
 I +ACHSEOBR("H",10) W !?38,$$FMTE^XLFDT($S(+$E(ACHSEOBR("H",10),1,2)>50:2,1:3)_"000000"+ACHSEOBR("H",10))
 W !!?21,"TYPE 43 CLAIMS:",$J(+ACHSEOBR("H",11),13),!!?21,"TYPE 57 CLAIMS:",$J(+ACHSEOBR("H",12),13),!!?21,"TYPE 64 CLAIMS:",$J(+ACHSEOBR("H",13),13)
 W !!?18,"TOTAL OF PAYMENTS: $"
 S X=$E(ACHSEOBR("H",14),1,7)_"."_$E(ACHSEOBR("H",14),8,9)
 KILL X1,X2
 D COMMA^%DTC
 W X,!!," NET ADJ. OF PAYMENT VS. OBLIGATION: $"
 S X=$E(ACHSEOBR("H",15),1,7)_"."_$E(ACHSEOBR("H",15),8,9)
 D COMMA^%DTC
 W X,@IOF
 Q
 ;
END ;
 I ACHSZRC>0 U IO(0) W !!,"Total EOBR Records Processed = ",ACHSZRC,!!
 G CDSM:^%ZOSF("OS")["DSM"
K ; Close device, kill vars, quit.
 I (IO(0)'=IO)!($D(IO("S"))) D ^%ZISC
 I $D(ACHSEOIO),ACHSEOIO'=IO S IO=ACHSEOIO D ^%ZISC
 D CLOSEALL^ACHS
 KILL ACHSEOBR,ACHSEOIO,ACHSERRA,ACHSOLD,ACHSTIME,ACHSX
 Q
 ;
ERR ;
 U IO(0)
 W *7,*7,!!,"AN ERROR HAS BEEN DETECTED IN THE",!,"FINANCE PARAMETERS OR DATA GLOBAL STRUCTURE.",!!,"PLEASE CONTACT YOUR SITEMANAGER FOR ASSISANTANCE",!!
 S X=$$DIR^XBDIR("E","Press <RETURN> To Continue....")
 G K
 ;
TERR ;
 U IO(0)
 W *7,!!,"EOBR PROCESSING ERROR.",!!,"Notify your supervisor.",!
 S X=$$DIR^XBDIR("E","Press <RETURN> To Continue....")
 G END
 ;
END1 ;EP.
 U IO(0)
 W !!,"No CHS EOBR Data Processed"
 S X=$$DIR^XBDIR("E","Press <RETURN> To Continue....")
 G K
 ;
CDSM ; Close DSM magtape.
 X ^%ZOSF("MAGTAPE")
 U IO
 W @%MT("REW")
 KILL %MT
 U IO(0)
 W !!,"Rewinding tape. <WAIT>"
 F L=1:1:150 U IO X ^%ZOSF("MTBOT") G:Y K U IO(0) W "." H 2
 U IO(0)
 W !!,"Tape not rewound",*7
 G K
 ;
FLC(ACHSZ3) ;
 ; Attempt to find Location based on FLC of EOBR.
 ; The ASUFAC code for any given facility may have changed since
 ;  the document left the facility, and the EOBR created.
 ; Assume the ^AUTTLOC("FLC" x-ref has a bug, if you get this far,
 ;  (that's why you got this far) and use the ^AUTTLOC("FL" x-ref
 ;  and the single-character code from the AREA file.
 ; Once the "FLC" x-ref is corrected, this code not needed.
 ;
 NEW X,Y
 S (X,Y)=0
 F  S X=$O(^AUTTLOC("FL",X)) Q:'$L(X)!Y  S Y=0 F  S Y=$O(^AUTTLOC("FL",X,Y)) Q:'Y  I Y,$P(^AUTTAREA($P(^AUTTLOC(Y,0),U,4),0),U,3)_$E(X,2,3)=ACHSZ3 Q
 Q Y
 ;
