AZZZEOBS ; IHS/ADC/GTH - SELECT EOBR FILE FOR PROCESSING ; [ 09/17/97   9:12 AM ]
 ;;3.0;CONTRACT HEALTH MGMT SYSTEM;**10**;SEP 17, 1997
 ;
 W @IOF,$$REPEAT^XLFSTR("*",79),!,$$C^XBFUNC("***   SELECT EOBR FILE FOR PROCESSING   ***")
 I ACHSISAO W !,$$C^XBFUNC("LAST AREA OFFICE SEQUENCE NUMBER = "_$$AOP^ACHS(2,9)),!,$$C^XBFUNC("FI/EOBR Files Archive Directory = '"_$$AOP^ACHS(2,7)_"'.")
 W !,$$REPEAT^XLFSTR("*",79),!
 D ^AZZZEOBY
 I $D(ACHSJFLG) G ABEND
D0 ;
 S (ACHSI,ACHSII)="",ACHSISEQ=0
 KILL ACHSSEL
 U IO(0)
 W !!,"NUMB   FILE NAME       FI PROCESS DATE  # RCDS  SEQ #"
 W !,"-----  -------------   ---------------  ------  ------"
D1 ;
 S ACHSII=$O(ACHSUFLS("C",ACHSII))
 G DEND:+ACHSII=0
D2 ;
 S ACHSI=$O(ACHSUFLS("C",ACHSII,ACHSI))
 G D1:+ACHSI=0
 G D1:$P(ACHSUFLS(ACHSI),U,2)'="OK"
 S ACHSISEQ=ACHSISEQ+1
 W !,$J(ACHSISEQ,5),?7,$P(ACHSUFLS(ACHSI),U,1)
 S X=$P(ACHSUFLS(ACHSI),U,3),X=$E(X,5,6)_$E(X,1,4),X=$S($E(X,1,2)>50:2,1:3)_X
 W ?23,$$FMTE^XLFDT(X),?40,$J($FN($P(ACHSUFLS(ACHSI),U,4),",",0),6),?51,$J($P(ACHSUFLS(ACHSI),U,5),3)
 S ACHSSEL(ACHSISEQ)=ACHSI
 G D2
 ;
DEND ;
 S X=$$DIR^XBDIR("NO^1:"_ACHSISEQ,"Enter NUMB of EOBR FILE to Process From Above List")
 I $D(DTOUT)!$D(DUOUT)!('X) S ACHSAEND=2 Q 
 I '$D(ACHSSEL(X)) G ABEND
 S ACHSFILE=+ACHSSEL(X),ACHSZFN=$P(ACHSUFLS(ACHSFILE),U,1),ACHSEOBD=$P(ACHSUFLS(ACHSFILE),U,3)
 I ACHSISAO S X=ACHSEOBD,X=$E(X,5,6)_$E(X,1,4),ACHSEOBD=$S($E(X,1,2)>50:2,1:3)_X
 S ACHSLEOB=$P(^ACHSAOP(DUZ(2),2),U,11)
 I 'ACHSISAO G CONT
 I +$P(^ACHSAOP(DUZ(2),2),U,9)=0 G SEQOK
 I +$P(^ACHSAOP(DUZ(2),2),U,9)=999 S $P(^ACHSAOP(DUZ(2),2),U,9)=0
 I $P(^ACHSAOP(DUZ(2),2),U,9)+1=$P(ACHSUFLS(ACHSFILE),U,5) G SEQOK
 KILL DIR
 U IO(0)
 W !,*7,"Wrong BCBS Report (Sequence) Number Selected ",!
 S DIR(0)="E"
 D ^DIR
 G D0:Y=1,ABEND:Y=0,D0:Y=""
SEQOK ;
 I '$D(^ACHSAOP(DUZ(2),17,"B",ACHSEOBD)) G CONT
 U IO(0)
 W *7,!
 I $$DIR^XBDIR("E","FI EOBR FILE has already been PROCESSED -- Enter <RETURN> to Continue")
 G ABEND
 ;
CONT ;
 S ACHSMEDA=ACHSZFN
 Q
 ;
ABEND ;
 S ACHSAEND=1
VKILL ; Kill vars, quit.
 KILL ACHSZDEV,ACHSZFN,ACHSZFO,ACHSZIN,ACHSCMD,ACHSERDT,ACHSERR,ACHSERRC,ACHSLMT,ACHSRCT,ACHSCMD,ACHSFILE,ACHSFNAM,ACHSFSIZ,ACHSHFS1,ACHSI,ACHSISEQ,ACHSSEL,ACHSUFLS,ACHSLCTR,DIR,X,Y,ACHSXX,ACHSLEOB
 Q
 ;
