ORRCYPRE ; SLC/KCM - Alpha/Beta Site Conversions ; 29 AUG 2003 16:59
 ;;1.0;HEALTHEVET DESKTOP;;Jul 15, 2003
SET2XHD ; Rename ORRC NURSE PT SELECT LIST parameter for Care Management
 D RENAME(8989.51,"ORRC NURSE PT SELECT LIST","ORRC DASHBOARD PT SELECT LIST")
 Q
RENAME(FILENUM,OLDNAME,NEWNAME) ; rename .01 entry in a file
 N IEN,FDA,ERR,DIERR
 S IEN=$$FIND1^DIC(FILENUM,"","X",OLDNAME)
 Q:'IEN
 S FDA(FILENUM,IEN_",",.01)=NEWNAME
 D FILE^DIE("","FDA","ERR")
 I $D(DIERR) D BMES^XPDUTL("Unable to rename "_OLDNAME)
 Q
