XPARBUSA ;IHS/OIT/FBD - Kernel Toolkit Parameter activity/support calls to BUSA; 03/20/2020
 ;;7.3;TOOLKIT;**1019**;Apr 3, 1995;Build 5
 ;
 ;This routine is custom to IHS and is not an original VHA routine. 
 ;It is being released in patch XT*7.3*1019 as part of the suite
 ;of changes relating to 2015 CHIT certification
 ;
 Q
 ;
PAREDIT(PARIEN) ;LOG A PARAMETER RECORD CREATION / FIELD EDIT
 ;CALLED BY 'SET' LOGIC OF PARAMETERS FILE (#8989.5) 'ABUSA' INDEX
 N CODE,DESC,ENTFILE,ENTRCD,PARAM,INST,VALUE
 S CODE="PAR01"
 S ENTFILE="^"_$P(DIKCX2(1),";",2)_"0)",ENTFILE=$P(@ENTFILE,U,1)  ;ENTITY FILE NAME
 S ENTRCD="^"_$P(DIKCX2(1),";",2)_$P(DIKCX2(1),";",1)_",0)",ENTRCD=$P(@ENTRCD,U,1)  ;ENTITY RECORD NAME
 S PARAM=$P(^XTV(8989.51,DIKCX2(2),0),U,1)  ;PARAMETER NAME
 S INST=DIKCX2(3)  ;PARAMETER INSTANCE
 S VALUE=DIKCX2(4)  ;PARAMETER VALUE
 S DESC="Parameter "_PARAM_" instance "_INST_" value set to "_VALUE_" for "_ENTFILE_" file record #"_ENTRCD
 D PAR(CODE,DESC,PARIEN,DUZ)
 Q
 ;
PARDEL(PARIEN) ;LOG A PARAMETER RECORD DELETION
 ;CALLED BY 'KILL' LOGIC OF PARAMETERS FILE (#8989.5) 'ABUSA' INDEX
 N CODE,DESC,ENTFILE,ENTRCD,PARAM,INST,VALUE
 S CODE="PAR02"
 S ENTFILE="^"_$P(DIKCX1(1),";",2)_"0)",ENTFILE=$P(@ENTFILE,U,1)  ;ENTITY FILE NAME
 S ENTRCD="^"_$P(DIKCX1(1),";",2)_$P(DIKCX1(1),";",1)_",0)",ENTRCD=$P(@ENTRCD,U,1)  ;ENTITY RECORD NAME
 S PARAM=$P(^XTV(8989.51,DIKCX1(2),0),U,1)  ;PARAMETER NAME
 S INST=DIKCX1(3)  ;PARAMETER INSTANCE
 S VALUE=DIKCX1(4)  ;PARAMETER VALUE
 S DESC="Parameter "_PARAM_" instance "_INST_" value "_VALUE_" deleted for "_ENTFILE_" file record #"_ENTRCD
 D PAR(CODE,DESC,PARIEN,DUZ)
 Q
 ;
PAR(CODE,DESC,RECORD,USER) ;MAIN PARAMETER EVENT BUSA FILER
 ;INPUT PARAMETERS:
 ; - CODE   = PARAMETER EVENT CODE
 ; - DESC   = BASE DESCRIPTION
 ; - RECORD = PARAMETERS FILE (#8989.5) IEN FOR SOURCE-AFFECTED RECORD
 ; - USER   = NEW PERSON FILE (#200) IEN FOR USER INITIATING ACTION
 ;
 N DO,DD  ;ADDED TO AVOID BUSA CAUSING PROBLEMS WITH NESTED FILE^DICN CALLS FURTHER DOWNSTREAM
 N CALL,TYPE,ACTION
 S CALL="XPAR"
 S TYPE="TYPE~NP"
 I +$L($T(FAUD^BUSAAPI)) S ACTION="U"  ;IF BUSA V1.0 PATCH 3 IS INSTALLED, SET ACTION TO "U" (CHANGE TO USER PRIVILEGE)
 E  S ACTION=""                        ;IF NOT, LEAVE ACTION NULL
 ;D DEBUG  ;DEBUG
 D FILER^XUSBUSA2(CODE,ACTION,CALL,DESC,TYPE,RECORD,USER)
 Q
 ;
DEBUG ;DEBUG VARIABLE DUMP TO SCREEN
 W !!,"FILER:"
 W !,?5,"CODE:   ",CODE
 W !,?5,"ACTION: ",ACTION
 W !,?5,"CALL:   ",CALL
 W !,?5,"DESC:   ",DESC
 W !,?5,"TYPE:   ",TYPE
 W !,?5,"RECORD: ",RECORD
 W !,?5,"USER:   ",USER
 Q
