XT73P98 ;OAK/BP - POST INIT OF XT*7.3*98; [8/15/05 4:25am]
 ;;7.3;TOOLKIT;**98**; Apr 25, 1995
 Q
 ;
EN ; 
 D REMOFILE,DISOPT,REMORTN,SETOPT
 Q
 ;
MERGE ; merge files
 Q:$O(^XPD(9.9,0))>0
 Q:$D(^AWC(177100.6,0))'>0
 M ^XPD(9.9)=^AWC(177100.6)
 Q:$O(^XPD(9.95,0))>0
 Q:$D(^AWC(177100.7,0))'>0
 M ^XPD(9.95)=^AWC(177100.7)
 Q
 ;
REMOFILE ; remove files
 Q:$D(^AWC(177100.6,0))'>0
 N DA,DIK S DIK="^DIC(",DA=177100.6 D ^DIK
 K ^AWC(177100.6)
 Q:$D(^AWC(177100.7,0))'>0
 N DA,DIK S DIK="^DIC(",DA=177100.7 D ^DIK
 K ^AWC(177100.7)
 ;
 Q
DISOPT ; remove options
 N XTI,XTJ,XTTEXT
 F XTI=1:1:19 S XTTEXT=$T(OPT+XTI),XTTEXT=$P(XTTEXT,";;",2) D
 . S XTJ=+$$FIND1^DIC(19,"","MX",XTTEXT,"","","ERR")
 . I XTJ N DA,DIK S DIK="^DIC(19,",DA=XTJ D ^DIK
 ;
OPT ;
 ;;AWB COMPLETE A NON-KIDS PATCH
 ;;AWB COMPLETE PATCH HISTORY
 ;;AWB EDIT PATCH
 ;;AWB EDIT PATCH MONITOR PARAMS
 ;;AWB NIGHTLY PATCH MONITOR
 ;;AWB PAST DUE PATCH REPORT
 ;;AWB PATCH INQUIRY
 ;;AWB PATCH MANAGEMENT
 ;;AWB PATCH MONITOR MAIN MENU
 ;;AWB PATCH PROCESSING
 ;;AWB PATCH REPORTS
 ;;AWB PATCH SERVER
 ;;AWB PATCH STATISTICS
 ;;AWB PATCH STATS BY COMPLIANCE
 ;;AWB PATCHES DUE NEXT 7 DAYS
 ;;AWB RERUN NIGHTLY
 ;;AWB UNINSTALLED BY COMPLIANCE
 ;;AWB UNINSTALLED PATCH BULLETIN
 ;;AWB UNINSTALLED PATCHES
 Q
REMORTN ;remove the routines
 N X
 F X="AWBCKPTC","AWBCKPP","AWBCKPCF","AWBPSTAT","AWBNEX7","AWBPSTA2" X ^%ZOSF("DEL")
 Q
SETOPT ;put the option under KIDS menu
 N XTI,XTY S XTI="XPD MAIN",XTY="XTPM PATCH MONITOR MAIN MENU"
 S X=$$ADD^XPDMENU(XTI,XTY,"","")
 Q
