XUCMVPM ;SFISC/JC - VPM FILE DATA/INITIATE NEW COLLECTION ;06/26/96  14:47 [ 04/02/2003   8:47 AM ]
 ;;7.3;TOOLKIT;**1001**;APR 1, 2003
 ;;7.3;TOOLKIT;**17**;Apr 25, 1995
 ;
EN ;
 S U="^",XUCMPARM=$$PARM^XUCMVPU,XUCMDIR=$P(XUCMPARM,U,3),XUCMIOP=$P(XUCMPARM,U,4)
 I '$P(XUCMPARM,U,10) G EXIT
 I ^%ZOSF("OS")'["DSM" G EXIT
EN1 ;
 S %SPAWN="@"_XUCMDIR_"XUCMVPM.COM" D ^%SPAWN
 H 30 ;Give VMS time to rename files.
 D DIR Q:'Y
 D HFS
 G EXIT
DIR ;
 K XUCMFIL,XUCMF,XUCMF1,Y
 S XUCMDIR=$P($$PARM^XUCMVPU,U,3),XUCMF("MONITOR*.TMP.*")=""
 S Y=$$LIST^%ZISH(XUCMDIR,"XUCMF","XUCMF1")
 Q
HFS ;COLLECT HOST FILE DATA, MOVE TO ^TMP
 ;
1 S XUCMND="",FILE=""
 F  S FILE=$O(XUCMF1(FILE)) Q:FILE=""  D
 .S XUCMND=$P($E(FILE,9,99),".")
 .S Y=$$FTG^%ZISH(XUCMDIR,FILE,$NA(^TMP($J,XUCMND,0)),3)
 .Q:'Y
 .D TMP^XUCMVPM1
 .D STF^XUCMVPM1
 .K ^TMP($J)
 I $D(XUCMF1) S Y=$$DEL^%ZISH(XUCMDIR,$NA(XUCMF1))
 Q
 ;
EXIT ;
 ;
 S ZTREQ="@"
 K XUCMISTK,XUCMKRM,XUCMUSR,XUCMIDLE,XUCMPRC,XUCMPGFR,XUCMPGIO,XUCMFREL,XUCMMODL,XUCMDIO,XUCMBIO,XUCMAVE,XUCMDIR,XUCMDRV,XUCMDT,XUCMDT1,XUCMIOP,XUCMIPRC,XUCMMET,XUCMND,XUCMPARM,XUHFS,XUCMSTR
 K XUCMFIL,C,XUCMIO,XUCMQUE,XUHFN
 K DIC,DIADD,DA,DR
 K XUCMSIT,XUCMND1,^TMP($J)
 Q
CHK(XUCM1,XUCM2,XUCM3) ;Is an alert required?
 ;XUCM1=NODE, XUCM2=METRIC, XUCM3=DATA
 N TIME,HW,MET,MEAN,SD S U="^" I '$D(XUCMPARM) S XUCMPARM=$$PARM^XUCMVPU
 S TIME=$S($G(XUCMDT)'="":$$HTE^XLFDT($$FMTH^XLFDT(XUCMDT)),1:$$HTE^XLFDT($H))
 I XUCM1'[":" D
 .S DIC=8986.3,DIC(0)="MQZ",X=XUCM1 D ^DIC K DIC,DA I Y=-1 Q
 .S HW=$P(^XUCM(8986.3,+Y,0),"^",2)
 I XUCM1[":" D
 .S DIC=8986.35,DIC(0)="MQZ",X=XUCM1 D ^DIC K DIC,DA I Y=-1 Q
 .S HW=$P(^XUCM(8986.35,+Y,0),U,2)
 S DIC=8986.4,DIC(0)="MQZ",X=XUCM2 D ^DIC K DIC,DA I Y=-1 Q
 I '+$P(^XUCM(8986.4,+Y,0),"^",3) Q
 S MET=$P(Y,U,2)
 S DA(1)=+Y,DIC="^XUCM(8986.4,DA(1),1,",DIC(0)="MQZ",X=HW D ^DIC I Y=-1 Q
 S SD=+$P(^XUCM(8986.4,DA(1),1,+Y,0),"^",5),MEAN=$P(^(0),"^",4),SD3=3*SD I 'SD3 Q
 I (XUCM3>(MEAN+SD3)) D
 .Q:+$P(TIME,"@",2)'>8
 .Q:+$P(TIME,"@",2)'<17
 .S XQAMSG="<VPM 3-SD WARNING> "_TIME_"/"_XUCM1_"/"_MET_"="_XUCM3_" ("_$S((MEAN-SD3)<0:0,1:(MEAN-SD3))_"-"_(MEAN+SD3)_")/"
 .S XQA("G."_$P(XUCMPARM,U,5))=""
 .D SETUP^XQALERT
 Q
