XUCMVPI ;SFISC/JC - VA Performance Monitor setup ;10/15/96  09:56 [ 04/02/2003   8:47 AM ]
 ;;7.3;TOOLKIT;**1001**;APR 1, 2003
 ;;7.3;TOOLKIT;**17,25**;Aug 01, 1997
VAX ;
 I $G(DUZ)="" W !,$C(7),"NEED A DUZ..." Q
 I ^%ZOSF("OS")'["DSM" G OTHER
 W !,"This routine allows you to define the site file parameters"
 W !,"needed to run VPM, then instructs taskman to create the"
 W !,"host system directories for data files and system-specific"
 W !,"command procedures."
 D SITE^XUCMVPU Q:X["^"!($D(DUOUT))!($D(DTOUT))  D NODE^XUCMVPU Q:$D(DUOUT)!($D(DTOUT))  S XUCMPARM=$$PARM^XUCMVPU
 S XUCMND=$$ND^XUCMVPU,U="^"
 S X=0 K ND F  S X=$O(^XUCM(8986.3,X)) Q:X<1  D
 .S XUCMND1=$P(^XUCM(8986.3,X,0),U),XUCMQUE=$P(^(0),U,4)
 .I XUCMQUE'="" S ND(XUCMND1)=XUCMQUE
 S XUCMDIR=$P(XUCMPARM,U,3),XUCMIOP=$P(XUCMPARM,U,4)
 I XUCMDIR="" W !,$C(7),"HOST FILE DIRECTORY UNDEFINED!" G VX1
 I XUCMIOP="" W !,$C(7),"HFS DEVICE UNDEFINED!" G VX1
 I XUCMND="" W !,$C(7),"CM NODENAME FILE IS INCOMPLETE!" G VX1
 S ZTRTN="TSK^XUCMVPI",ZTDESC="VPM INSTALL",ZTIO=""
 W !!,"This final step will queue a task to install/rebuild the VPM com files."
 S %=2 I '$D(ZTSK) D
 .W !,"Do you wish to continue"
 .D YN^DICN
 Q:%'=1
 S ZTREQ="@",ZTSAVE("*")="" D ^%ZTLOAD
 I $D(ZTSK) W !,"This installation has been queued to task number: ",ZTSK
 I $D(ZTSK) K XUCMDIR,XUCMIOP,XUCMND,XUCMPARM,ZTSK Q
TSK ;Create directories and load VAX files
 S ZTREQ="@"
 S %SPAWN="CREATE/DIR "_XUCMDIR_"/PROT=(S:RWED,O:RWED,G:RWED,W:RWED)"
 D ^%SPAWN
1 ;LOAD COM FILES
 D 2,MON,RTH,EXIT
 Q
2 ;BUILD XUCMVPM (DRIVER) USING QUEUES DEFINED IN 8986.3
 S %ZIS("HFSNAME")=XUCMDIR_"XUCMVPM.COM",%ZIS("HFSMODE")="N",IOP=XUCMIOP
 D ^%ZIS I POP S XQAMSG="UNABLE TO OPEN FILE"_$G(IO("ERROR")) D ALERT Q
 U IO
 W !,"$!XUCMVPM - VA PERFORMANCE MONITOR DATA COLLECTION"
 W !,"$!THIS VERSION CREATED "_$$HTE^XLFDT($H)
 W !,"$ SET NOON"
 W !,"$ RENAME "_XUCMDIR_"*.DAT.* *.TMP;/NEW"
 S ND="" F  S ND=$O(ND(ND)) Q:ND=""  D
 .S Q=ND(ND)
 .W !,"$ SUBMIT/QUE="_Q_" "_XUCMDIR_"XUCMMONITOR.COM/NOPRINT"
 W !,"$ EXIT"
 D ^%ZISC
 Q
MON ;XUCMMONITOR.COM
 S %ZIS("HFSNAME")=XUCMDIR_"XUCMMONITOR.COM",%ZIS("HFSMODE")="N",IOP=XUCMIOP
 D ^%ZIS I POP S XQAMSG="XUCMMONITOR.COM<POP>-"_$G(IO("ERROR")) D ALERT
 U IO
 W !,"$!XUCMMONITOR.COM - MONITOR VAX METRICS"
 W !,"$!TOOLKIT 7.3"
 W !,"$!THIS VERSION CREATED ON "_$$HTE^XLFDT($H)
 W !,"$ NODE=F$GETSYI(""NODENAME"")"
 W !,"$ TYPE=F$GETSYI(""HW_NAME"")"
 W !,"$ MONITOR DISK/ITEM=ALL,SYSTEM,STATE,LOCK,DLOCK -"
 W !,"  /SUMMARY="_XUCMDIR_"MONITOR_'NODE'.DAT/NODISP/INT=10/END=""+00:15:00"""
 W !,"$ OPEN/APPEND MON "_XUCMDIR_"MONITOR_'NODE'.DAT"
 W !,"$     SHOW USER/INTERACTIVE/NODE='NODE'/OUT=MON"
 W !,"$ CLOSE MON"
 W !,"$ SHOW MEMORY/OUT="_XUCMDIR_"MISC_'NODE'.TMP"
 W !,"$ OPEN/APPEND MEM "_XUCMDIR_"MISC_'NODE'.TMP"
 W !,"$     WRITE MEM ""HARDWARE TYPE=''TYPE'"""
 W !,"$     SHOW DEVICE D/FULL/OUT=MEM"
 W !,"$ CLOSE MEM"
 W !,"$ PURGE "_XUCMDIR_"MISC*.TMP"
 D ^%ZISC
 Q
RTH ;RTHIST DRIVER
 S XUCMPARM=$$PARM^XUCMVPU
 S E=0 F  S E=$O(^XUCM(8986.3,E)) Q:E<1  S X1=$G(^XUCM(8986.3,E,0)),XUCMND=$P(X1,U) D
 .S XUCMMGR=$P(X1,U,6),XUCMQ=$P(X1,U,4),XUCMUSER=$P(X1,U,5)
 .S XUCMDIR=$P(XUCMPARM,U,3)
 .S FILE=XUCMDIR_"XUCMRTH"_XUCMND_".COM"
 .S %ZIS("HFSNAME")=FILE,%ZIS("HFSMODE")="N",IOP=$P(XUCMPARM,U,4) D ^%ZIS
 .Q:POP
 .U IO
 .W "$!XUCMRTH.COM *TOOLKIT VPM*",!
 .W "$DSM/E="_XUCMMGR_"/MAN RTH^%ZOSV2",!
 .W "$EXIT",!
 .D ^%ZISC
 Q
EXIT ;
 S XQAMSG="VPM INSTALL COMPLETED "_$$HTE^XLFDT($H) D ALERT
 D ^%ZISC
 S ZTREQ="@"
 Q
ALERT ;
 S XQA(DUZ)="" D SETUP^XQALERT
 Q
VX1 ;
 S %=1 W !,"Would you like to start over" D YN^DICN
 I %=1 G VAX
 Q
OTHER ;
 Q
