XUCMNIT2 ;SFISC/JC - Compile previous date's stats (CONT) ;07/10/96  11:57 [ 04/02/2003   8:47 AM ]
 ;;7.3;TOOLKIT;**1001**;APR 1, 2003
 ;;7.3;TOOLKIT;**17,25**;Aug 01, 1997
EXIT ;
 D KILL^XUSCLEAN
 Q
SYS ;GATHER NODE SPECIFIC METRICS
 S X="T-1",%DT="" D ^%DT S XUCMDT=Y N H,I,J,K,L
 S X="T-1@0759",%DT="XT" D ^%DT S XUCMSDT=Y
 S X="T-1@1630",%DT="XT" D ^%DT S XUCMEDT=Y
SYS1 ;RESPONSE TIME (FROM 8986.098)
 S XUCMPARM=$$PARM^XUCMVPU
 S (X,XUCMST)=$P(XUCMPARM,U,2),DIC=8986.098,DIC(0)="LMZ" D ^DIC S SITIEN=+Y K DIC,DA
 I SITIEN'>0 G SYS2
 S XUCMND=0 F  S XUCMND=$O(^XUCM(8986.3,XUCMND)) Q:XUCMND<1  S XUCMNODE=$P(^XUCM(8986.3,XUCMND,0),U),XUCMHW=$P(^(0),U,2) D
 .S X=XUCMNODE,DA(1)=SITIEN,DIC="^XUCM(8986.098,DA(1),1,",DIC(0)="LMZ" D ^DIC Q:Y=-1  S NDIEN=+Y
 .S H=XUCMSDT,(CNT,NDCNT,NDET,ET,R,ACTET)=0
 .F  S H=$O(^XUCM(8986.098,SITIEN,1,NDIEN,1,"B",H)) Q:H<1!(H>XUCMEDT)  D
 ..S I=$O(^XUCM(8986.098,SITIEN,1,NDIEN,1,"B",H,0))
 ..S K=$G(^XUCM(8986.098,SITIEN,1,NDIEN,1,I,0)) Q:K=""
 ..S NDET=$G(NDET)+$P(K,U,2),NDCNT=$G(NDCNT)+$P(K,U,3),ACTET=$G(ACTET)+600
 ..D CHK^XUCMNIT1(H,XUCMND,XUCMHW,"RTM",$P(K,U,4))
 .S NDRT=$S(NDCNT:NDET/NDCNT,1:0),NDRT=$J(NDRT,0,2)
 .;compute event rate based on sum of session length (600 seconds)
 .S NDEPS=$S(ACTET:NDCNT/ACTET,1:0),NDEPS=$J(NDEPS,0,1)
 .D FIL4^XUCMNIT1 S XUCMMET="RTM",XUCMAVE=NDRT,XUCMC=NDCNT
 .D FIL7^XUCMNIT1
 .S XUCMMET="RSP",XUCMAVE=NDEPS,XUCMC=NDCNT D FIL7^XUCMNIT1
SYS2 ;SYSTEM METRICS (8986.51)
 S H=XUCMSDT F  S H=$O(^XUCM(8986.51,"C",H)) Q:H<1!(H>XUCMEDT)  D
 .S C=0 F  S C=$O(^XUCM(8986.51,"C",H,C)) Q:C<1  D
 ..S I=$G(^XUCM(8986.51,C,0)),XUCMND=$P(I,U,3),XUCMHW=$P(^XUCM(8986.3,XUCMND,0),U,2)
 ..S J=$G(XUCM("ISTK",XUCMND)) I $P(I,U,5)'="" S $P(J,U)=1+$P(J,U),$P(J,U,2)=$P(I,U,5)+$P(J,U,2),$P(J,U,3)=XUCMHW,XUCM("ISTK",XUCMND)=J D CHK^XUCMNIT1(H,XUCMND,XUCMHW,"ISTK",$P(I,U,5))
 ..S J=$G(XUCM("KRM",XUCMND)) I $P(I,U,6)'="" S $P(J,U)=1+$P(J,U),$P(J,U,2)=$P(I,U,6)+$P(J,U,2),$P(J,U,3)=XUCMHW,XUCM("KRM",XUCMND)=J D CHK^XUCMNIT1(H,XUCMND,XUCMHW,"KRM",$P(I,U,6))
 ..S J=$G(XUCM("USR",XUCMND)) I $P(I,U,7)'="" S $P(J,U)=1+$P(J,U),$P(J,U,2)=$P(I,U,7)+$P(J,U,2),$P(J,U,3)=XUCMHW,XUCM("USR",XUCMND)=J D CHK^XUCMNIT1(H,XUCMND,XUCMHW,"USR",$P(I,U,7))
 ..S J=$G(XUCM("IDLE",XUCMND)) I $P(I,U,8)'="" S $P(J,U)=1+$P(J,U),$P(J,U,2)=$P(I,U,8)+$P(J,U,2),$P(J,U,3)=XUCMHW,XUCM("IDLE",XUCMND)=J D CHK^XUCMNIT1(H,XUCMND,XUCMHW,"IDLE",$P(I,U,8))
 ..S J=$G(XUCM("PRC",XUCMND)) I $P(I,U,9)'="" S $P(J,U)=1+$P(J,U),$P(J,U,2)=$P(I,U,9)+$P(J,U,2),$P(J,U,3)=XUCMHW,XUCM("PRC",XUCMND)=J D CHK^XUCMNIT1(H,XUCMND,XUCMHW,"PRC",$P(I,U,9))
 ..S J=$G(XUCM("PGFR",XUCMND)) I $P(I,U,10)'="" S $P(J,U)=1+$P(J,U),$P(J,U,2)=$P(I,U,10)+$P(J,U,2),$P(J,U,3)=XUCMHW,XUCM("PGFR",XUCMND)=J D CHK^XUCMNIT1(H,XUCMND,XUCMHW,"PGFR",$P(I,U,10))
 ..S J=$G(XUCM("PGIO",XUCMND)) I $P(I,U,11)'="" S $P(J,U)=1+$P(J,U),$P(J,U,2)=$P(I,U,11)+$P(J,U,2),$P(J,U,3)=XUCMHW,XUCM("PGIO",XUCMND)=J D CHK^XUCMNIT1(H,XUCMND,XUCMHW,"PGIO",$P(I,U,11))
 ..S J=$G(XUCM("FREL",XUCMND)) I $P(I,U,12)'="" S $P(J,U)=1+$P(J,U),$P(J,U,2)=$P(I,U,12)+$P(J,U,2),$P(J,U,3)=XUCMHW,XUCM("FREL",XUCMND)=J D CHK^XUCMNIT1(H,XUCMND,XUCMHW,"FREL",$P(I,U,12))
 ..S J=$G(XUCM("MODL",XUCMND)) I $P(I,U,13)'="" S $P(J,U)=1+$P(J,U),$P(J,U,2)=$P(I,U,13)+$P(J,U,2),$P(J,U,3)=XUCMHW,XUCM("MODL",XUCMND)=J D CHK^XUCMNIT1(H,XUCMND,XUCMHW,"MODL",$P(I,U,13))
 ..S J=$G(XUCM("DIO",XUCMND)) I $P(I,U,14)'="" S $P(J,U)=1+$P(J,U),$P(J,U,2)=$P(I,U,14)+$P(J,U,2),$P(J,U,3)=XUCMHW,XUCM("DIO",XUCMND)=J D CHK^XUCMNIT1(H,XUCMND,XUCMHW,"DIO",$P(I,U,14))
 ..S J=$G(XUCM("BIO",XUCMND)) I $P(I,U,15)'="" S $P(J,U)=1+$P(J,U),$P(J,U,2)=$P(I,U,15)+$P(J,U,2),$P(J,U,3)=XUCMHW,XUCM("BIO",XUCMND)=J D CHK^XUCMNIT1(H,XUCMND,XUCMHW,"BIO",$P(I,U,15))
 ..S J=$G(XUCM("RLD",XUCMND)) I $P(I,U,16)'="" S $P(J,U)=1+$P(J,U),$P(J,U,2)=$P(I,U,16)+$P(J,U,2),$P(J,U,3)=XUCMHW,XUCM("RLD",XUCMND)=J D CHK^XUCMNIT1(H,XUCMND,XUCMHW,"RLD",$P(I,U,16))
 ..S J=$G(XUCM("MPRL",XUCMND)) I $P(I,U,17)'="" S $P(J,U)=1+$P(J,U),$P(J,U,2)=$P(I,U,17)+$P(J,U,2),$P(J,U,3)=XUCMHW,XUCM("MPRL",XUCMND)=J D CHK^XUCMNIT1(H,XUCMND,XUCMHW,"MPRL",$P(I,U,17))
 ..D ^XUCMNI2A K XUCMND,XUCMHW
 D FIL4^XUCMNIT1
 S XUCMMET="" F  S XUCMMET=$O(XUCM(XUCMMET)) Q:XUCMMET=""  D
 .S XUCMND=0 F  S XUCMND=$O(XUCM(XUCMMET,XUCMND)) Q:XUCMND<1  D
 ..S I=$G(^XUCM(8986.3,XUCMND,0)) Q:I=""  S XUCMNODE=$P(I,U),XUCMHW=$P(I,U,2)
 ..S J=$G(XUCM(XUCMMET,XUCMND)),XUCMC=$P(J,U),XUCMT=$P(J,U,2)
 ..S XUCMAVE=$S(XUCMC:(XUCMT/XUCMC),1:0),XUCMAVE=$J(XUCMAVE,0,2),XUCMC=$J(XUCMC,0,0)
 ..D FIL7^XUCMNIT1
 Q
