XUCMXDR ;SFISC/HVB - COMPACT SUMMARY for VMS SITES ;4/11/97  13:17 [ 04/02/2003   8:47 AM ]
 ;;7.3;TOOLKIT;**1001**;APR 1, 2003
 ;;7.3;TOOLKIT;**25**;Aug 01, 1997
A S U="^" S:'$D(DT) DT=$$HTFM^XLFDT($H,1) S:'$D(DTIME) DTIME=300
 S XUCMEND=0 D A3^XUCMXUTL G XIT:XUCMEND
 S DIR("A")="Mail report",DIR("B")="NO",DIR(0)="Y" D ^DIR Q:$D(DIRUT)  I Y K XMY S XUCMAIL=2,IOM=132 G DQ
 S %ZIS="Q" D ^%ZIS I POP S POP=0 G XIT
 I $D(IO("Q")) D  G XIT
 . S ZTSAVE("XUCM*")="",ZTRTN="DQ^XUCMXST",ZTDESC="VPM COMPACT SITE SUMMARY",ZTIO=ION
 . S %DT="AEFRX",%DT("A")="Queue for what DATE/TIME? ",%DT("B")="NOW",%DT(0)="NOW" D ^%DT K %DT
 . I +Y'<0 S ZTDTH=Y D ^%ZTLOAD,HOME^%ZIS
 . K IO("Q")
 U IO W:$E(IOST)="C" # G DQ
DR ;Daily report in mail message - noninteractive
 S U="^" K XMY S XUCMAIL=1,X=$$PARM^XUCMVPU,MG=$P(X,U,5) G NOT:MG="" S XMY(MG)="",(XUCMBD,XUCMED)=$$YDT^XUCMVPU
DQ ; Dequeue entry point
 S Y=XUCMBD D DD^%DT S BD=Y,Y=XUCMED D DD^%DT S ED=Y K:$D(XUCMAIL) ^TMP($J,"XUCM")
 F METRIC="DKIO","DKQ" S @METRIC=$O(^XUCM(8986.4,"B",METRIC,"")) I @METRIC="" W METRIC," metric not in file!",! G XIT
 F METPT=DKIO,DKQ S HWTPP=0 F  S HWTPP=$O(^XUCM(8986.4,METPT,1,HWTPP)) Q:HWTPP]"@"!(HWTPP="")  S X=^(HWTPP,0) D
 . S (Y,HWTYP)=$P(X,U),HWTYPF=$S(Y["DEC":$P(Y,"DEC",2),1:$TR(Y,"nrsk")),HL=$P(X,U,6),HL=$S(HL:HL,1:$P(X,U,4)+($P(X,U,5)*2)),DSKMET(METPT,HWTYP)=HWTYPF_U_$P(X,U,2,5)_U_HL
SITL S SPARDA=$S($D(XUCMUN):XUCMUN-1,1:0),FF=0,LN=1 F  S SPARDA=$O(^XUCM(8986.6,"B",SPARDA)) Q:SPARDA=""  S STATDA=$O(^(SPARDA,0)) I STATDA D  Q:$D(XUCMUN)
ADDL . S FMDT=XUCMBD-1 F  S FMDT=$O(^XUCM(8986.6,STATDA,1,"B",FMDT)) Q:FMDT>XUCMED!(FMDT="")  S IEN=0 F  S IEN=$O(^XUCM(8986.6,STATDA,1,"B",FMDT,IEN)) Q:IEN=""  S X=^XUCM(8986.6,STATDA,1,IEN,0) D
 . . S METPT=$P(X,U,2),NODPT=$P(X,U,3),DSKPT=$P(X,U,5),MEAN=$P(X,U,7),CNT=$P(X,U,8),DEVOL=$P(X,U,10)
 . . I NODPT S HWTYP=$P(X,U,4),NDRAM=$P(X,U,9),Y=$G(DATA(1,NODPT,METPT)),Y1=HWTYP_U_($P(Y,U,2)+MEAN)_U_($P(Y,U,3)+CNT)_U_($P(Y,U,4)+1)_U_NDRAM,DATA(1,NODPT,METPT)=Y1 Q
 . . I DSKPT S HWTYP=$P(X,U,6) S:HWTYP="" HWTYP="UNKN" S Y=$G(DATA(2,DSKPT,METPT)),Y1=HWTYP_U_($P(Y,U,2)+MEAN)_U_($P(Y,U,3)+CNT)_U_($P(Y,U,4)+1),DATA(2,DSKPT,METPT)=Y1 Q
 . . I DEVOL S VOL=$E($P(DEVOL,"]",2),1,3) D:VOL]""
 . . . S $P(DATA(3,VOL),U)=$P($G(DATA(3,VOL)),U)+$P(X,U,11),$P(DATA(3,VOL),U,2)=$P(DATA(3,VOL),U,2)+$P(X,U,12) S:FMDT'=$P(DATA(3,VOL),U,4) $P(DATA(3,VOL),U,3)=$P(DATA(3,VOL),U,3)+1 S $P(DATA(3,VOL),U,4)=FMDT Q
 . Q:'$D(DATA)  S DIC4P=$P($G(^XUCM(8986.095,SPARDA,0)),U) I DIC4P S SITNM=$P($G(^DIC(4,DIC4P,0)),U) D:SITNM]""  K STR,HDR
NODL . . S NODPT=0 F  S NODPT=$O(DATA(1,NODPT)) Q:NODPT=""  S NODE=^XUCM(8986.3,NODPT,0),NODNM=$P(NODE,U) D
 . . . S METPT=0 F  S METPT=$O(DATA(1,NODPT,METPT)) Q:METPT=""  S X=DATA(1,NODPT,METPT),METPAR=^XUCM(8986.4,METPT,0) D
 . . . . S HWTYP=$P(X,U) I HWTYP]"" S HWTPP=$O(^XUCM(8986.4,METPT,1,"B",HWTYP,0)) I HWTPP S $P(METPAR,U,7,10)=$P(^XUCM(8986.4,METPT,1,HWTPP,0),U,4,7)
 . . . . S HWTYPF=$TR($P(HWTYP," ",2,4),"Model "),HWTYPF=$P(HWTYPF,"000")_"K"_$TR($P(HWTYPF,"000",2),"A")
 . . . . S NDRAM=$P(X,U,5),NDRAM=$S(NDRAM]"":NDRAM,1:$P(NODE,U,3))
 . . . . S METRIC=$P(METPAR,U),ORD=$P(METPAR,U,6),AV=$P(METPAR,U,7),SD=$P(METPAR,U,8),HL=$P(METPAR,U,9),LL=$P(METPAR,U,10),X=DATA(1,NODPT,METPT)
 . . . . S Y=$P(X,U,2)/$P(X,U,4),Y=$S(METRIC="RTM":$J(Y,0,2),(METRIC="COM")!(METRIC="RSP"):$J(Y,0,1),1:$J(Y,0,0)) D
 . . . . . I HL,Y>HL S Y=$S($L(Y)<5:"*"_Y,1:$E(Y,1,4)_"*") Q
 . . . . . I LL,Y<LL S Y="*"_Y Q
 . . . . . I METRIC="IDLE"!(METRIC="FREL")!(METRIC="MODL") S LL=AV-(SD*2),Y=$S(LL<Y:Y,LL=Y:Y,1:"*"_Y) Q
 . . . . . E  S HL=AV+(SD*2),Y=$S(HL>Y:Y,HL=Y:Y,$L(Y)<5:"*"_Y,1:$E(Y,1,4)_"*") Q
 . . . . S $P(STR(NODNM),U,ORD+2)=$J(Y,6),$P(HDR(NODNM),U,ORD)=$J(METRIC,6)
 . . . S $P(STR(NODNM),U,1,2)=$E(HWTYPF_"    ",1,7)_U_$J(NDRAM,6)
PSIT . . S L=1 S ARAY(L)=$E(SITNM_"                                ",1,33)_" VPM Summary for "_BD_$S(ED'=BD:" to "_ED,1:"") D LF D:$D(HDR)
 . . . S NODNM=$O(HDR("")) D LF S ARAY(L)="       "_$J("RAM",6) F I=1:1:19 S ARAY(L)=ARAY(L)_$P(HDR(NODNM),U,I)
 . . . S NODNM="" F  S NODNM=$O(STR(NODNM)) Q:NODNM=""  D
 . . . . D LF S ARAY(L)=ARAY(L)_$E(NODNM_"       ",1,7) F I=2:1:21 S ARAY(L)=ARAY(L)_$P(STR(NODNM),U,I)
 . . . S NODNM=$O(HDR("")) D LF,LF S ARAY(L)="       " F I=20:1:39 S ARAY(L)=ARAY(L)_$P(HDR(NODNM),U,I)
 . . . S NODNM="" F  S NODNM=$O(STR(NODNM)) Q:NODNM=""  D
 . . . . D LF F I=1,22:1:41 S ARAY(L)=ARAY(L)_$P(STR(NODNM),U,I)
DSKL . . S DSKPT=0 F  S (HDR1,HDR2)="",STR1="DKIO",STR2="DKQ " D  Q:DSKPT=""
 . . . F I=1:1:15 S DSKPT=$O(DATA(2,DSKPT)) Q:DSKPT=""  D
 . . . . S DSK=$P(^XUCM(8986.35,DSKPT,0),":"),DSKNM=$S($P(DSK,"$",2):$E($P($P(DSK,"$",2,3),"$D")_$P($P(DSK,"$",2,3),"$D",2),1,6),1:$E(DSK,4,9)),HDR1=HDR1_$J(DSKNM,7)
 . . . . S X1=DATA(2,DSKPT,DKIO),HWTYP=$P(X1,U),Y=DSKMET(DKIO,HWTYP),HWTYPF=$P(Y,U),HDR2=HDR2_$J(HWTYPF,7),HL=$P(Y,U,6),AV=$P(X1,U,2)/$P(X1,U,4),ZIP=($J(AV,0,1)=0),AVF=$J($S(ZIP:"     ",AV<HL:$J(AV,0,0),1:"*"_$J(AV,0,0))_"  ",7),STR1=STR1_AVF
 . . . . S X2=DATA(2,DSKPT,DKQ),Y=DSKMET(DKQ,HWTYP),HL=$P(Y,U,6),AV=$P(X2,U,2)/$P(X2,U,4),AVF=$S(ZIP:"       ",AV<HL:$J(AV,7,1),1:$J("*"_$J(AV,0,1),7)),STR2=STR2_AVF
 . . . D LF,LF S ARAY(L)="    "_HDR1,L=L+1,ARAY(L)="    "_HDR2,L=L+1,ARAY(L)=STR1,L=L+1,ARAY(L)=STR2
 . D LF,LF S ARAY(L)="VolSet"_$J("Total MB",12)_$J("MB Free",11)_$J("%Free",9),L=L+1
 . S VOL="" F  S VOL=$O(DATA(3,VOL)) Q:VOL=""  S X=DATA(3,VOL),X1=$P(X,U)/$P(X,U,3),X2=$P(X,U,2)/$P(X,U,3) S ARAY(L)=$J(VOL,6)_$J(X1/1000,12,0)_$J(X2/1000,11,0) D:X1  D LF
 . . S PCFR=X2/X1*100 S ARAY(L)=ARAY(L)_$J(PCFR,9,0)_$S(PCFR<2:"  <<<<<<<<  Only 1% Free!  >>>>>>>>",PCFR<4.5:"  *****",PCFR<9.5:"  ***",PCFR<14.5:"  *",1:"")
 . I $D(XUCMAIL) D LF S L=0 F  S L=$O(ARAY(L)) Q:L=""  S ^TMP($J,"XUCM",LN)=ARAY(L),LN=LN+1
 . E  W:FF @IOF S L=0,Z=$O(ARAY(""),-1) F  S L=$O(ARAY(L)) Q:L=""  W:ARAY(L)["VolSet"&(Z-L>(IOSL-$Y)) @IOF W ARAY(L),!
 . K ARAY,DATA S FF=1
 I $D(XUCMAIL) S XMCHAN=1,XMDUZ="VPM",XMTEXT="^TMP($J,""XUCM""," S XMSUB=$S(XUCMAIL=1:"VPM Compact Summary for "_+$E(XUCMBD,4,5)_"/"_+$E(XUCMBD,6,7)_"/"_$E(XUCMBD,2,3),1:"VPM Compact Summary") D ^XMD
XIT K AV,AVF,BD,CNT,DEVOL,DIC4P,DISYS,DKIO,DKQ,DSK,DSKMET,DSKNM,DSKPT
 K ED,FF,FMDT,G,H,HDR1,HDR2,HL,HWTPP,HWTYP,HWTYPF,I,IEN,L,LL,LN
 K MEAN,METPAR,METPT,METRIC,MG,NDRAM,NODE,NODNM,NODPT,PCFR,ORD
 K SD,SITNM,SPARDA,STATDA,STR1,STR2,VOL
 K X,X1,X2,XUCMAIL,XUCMBD,XUCMED,XUCMEND,XUCMUN,Y,Y1,Z,ZIP
 D ^%ZISC Q
LF S L=L+1,ARAY(L)="" Q
ONE ; One site only
 S U="^",DT=$$HTFM^XLFDT($H,1),DIR("A")="Select VPM Site",DIR(0)="P^4:EMZ" D ^DIR Q:$D(DIRUT)  S XUCMUN=$O(^XUCM(8986.095,"B",$P(Y,U),0)) G A:XUCMUN
 W !?17,$P(Y,U,2)," is not a VPM site." G ONE
NOT I $G(DUZ)\1 S XQA(DUZ)="",XQAMSG="No mailgroup defined in VPM site parameter file, no VPM daily report" D SETUP^XQALERT K XQA,XQAMSG G XIT
