XUCS1RB ;CLARKSBURG/SO RPT R-CMDS/R-GBL ACC BY DATE/VG - MAIN ;2/9/96  13:10 [ 04/02/2003   8:47 AM ]
 ;;7.3;TOOLKIT;**1001**;APR 1, 2003
 ;;7.3;TOOLKIT;**13**;Apr 25, 1995
 Q:'$$CHKF^XUCSUTL
 S XUCSEND=0,(XUCSX,XUCSX1)="" F XUCSX="A1","A3","A5" S XUCSX1=XUCSX_"^XUCSUTL3" D @XUCSX1 Q:XUCSEND
 G XIT:XUCSEND S %ZIS="MQ" D ^%ZIS I POP S POP=0 D HOME^%ZIS G XIT
 I $D(IO("Q")) D  G XIT
 . S ZTSAVE("XUCS*")="",ZTRTN="DEQUE^XUCS1RB",ZTDESC="COMMANDS VS GLOBAL REFERENSES REPORT",ZTIO=ION
 . S %DT="AEFRX",%DT("A")="Queue for what DATE/TIME? ",%DT("B")="NOW",%DT(0)="NOW" D ^%DT K %DT
 . I +Y'<0 S ZTDTH=Y D ^%ZTLOAD,HOME^%ZIS
 . K IO("Q")
 . Q
 U IO D:$E(IOST)="C" WAIT^DICD
DEQUE ;
 K ^TMP($J,2) D SORT,PRINT^XUCS1RBA
XIT ; Common Xit Point
 I $E(IOST)'="C",'$D(ZTQUEUED) D ^%ZISC
 K ^TMP($J,2)
 K XUCSAOC,XUCSAOG,XUCSAP,XUCSDT,XUCSEND,XUCSFS,XUCSI,XUCSHSW,XUCSPG,XUCSRDT,XUCSROU,XUCSROUW,XUCSTC,XUCSTG,XUCSXRC,XUCSXRG,XUCSRNEG
 K XUCSRL,XUCSS1C,XUCSS1G,XUCSSY,XUCSTH,XUCSUCI,XUCSVG,XUCSX,XUCSX1,XUCSX2,XUCSY,XUCSY1,XUCSY2,XUCSITE,XUCSITEH,XUCSDBUG
 Q
SORT ; Sort Report Data
 ; Sort Data into ^TMP($J,2,..."CMDS") & ^TMP($J,2,..."RGBL")
 ; "CMDS" = $P#1=Elapse Time in Sec.; $P#2=Routine Command Count
 ; $P#3= Negative Command count = 1
 ; "RGBL" = $P#1=Elapse Time in Sec.; $P#2=Global References by Routine
 S XUCSBDX=(XUCSBD-1)_".999999" F  S XUCSBDX=$O(^XUCS(8987.2,"C",XUCSBDX)) Q:XUCSBDX=""!($P(XUCSBDX,".")>XUCSED)  D
SL1 . I $E($P(XUCSBDX,".",2),1,2)<12,XUCSRT="P" Q  ; PM Records Only
 . I $E($P(XUCSBDX,".",2),1,2)>11,XUCSRT="A" Q  ; AM Records Only
 . S XUCSX1=0 F  S XUCSX1=$O(^XUCS(8987.2,"C",XUCSBDX,XUCSX1)) Q:+XUCSX1<1  D
SL2 .. S XUCSX2=0 F  S XUCSX2=$O(^XUCS(8987.2,"C",XUCSBDX,XUCSX1,XUCSX2)) Q:+XUCSX2<1  D
SL3 ... S XUCSVG=^XUCS(8987.2,XUCSX1,0) I $D(XUCSFS),'$D(XUCSFS(XUCSVG)) Q
 ... S XUCSET=^XUCS(8987.2,XUCSX1,1,XUCSX2,0),XUCSRDT=$P(XUCSET,"^"),XUCSAJ=$P(XUCSET,"^",5),XUCSET=$P(XUCSET,"^",3)
 ... S XUCSX3=0 F  S XUCSX3=$O(^XUCS(8987.2,XUCSX1,1,XUCSX2,1,XUCSX3)) Q:+XUCSX3<1  S XUCSX=^(+XUCSX3,0) D
SL4 .... S XUCSAP=$E($P(XUCSBDX,".",2),1,2),XUCSAP=$S(XUCSAP<12:"AM",1:"PM")
 .... K XUCSXR
 .... I XUCSRL<8,$L($P(XUCSX,"^"))>XUCSRL,$P(XUCSX,"^")'="~TBLOVF~" S XUCSXR=$E($P(XUCSX,"^"),1,XUCSRL)_"*"
 .... S:'$D(XUCSXR) XUCSXR=$P(XUCSX,"^")
 .... S XUCSUCI=$P(XUCSX,"^",2)_"~"_$P(XUCSX,"^",3)
 .... I '$D(^TMP($J,2,XUCSBDX\1,XUCSVG,XUCSAP,XUCSUCI,XUCSXR,"CMDS")) S ^TMP($J,2,XUCSBDX\1,XUCSVG,XUCSAP,XUCSUCI,XUCSXR,"CMDS")=XUCSET_"^0^0"
 .... I '$D(^TMP($J,2,XUCSBDX\1,XUCSVG,XUCSAP,XUCSUCI,XUCSXR,"RGBL")) S ^TMP($J,2,XUCSBDX\1,XUCSVG,XUCSAP,XUCSUCI,XUCSXR,"RGBL")=XUCSET_"^0"
 .... S:'$D(XUCSTC) XUCSTC=0 S XUCSTC=XUCSTC+$P(XUCSX,"^",4)
 .... S:'$D(XUCSTG) XUCSTG=0 S XUCSTG=XUCSTG+$P(XUCSX,"^",5)
 .... S $P(^TMP($J,2,XUCSBDX\1,XUCSVG,XUCSAP,XUCSUCI,XUCSXR,"CMDS"),"^",2)=$P(^TMP($J,2,XUCSBDX\1,XUCSVG,XUCSAP,XUCSUCI,XUCSXR,"CMDS"),"^",2)+$P(XUCSX,"^",4)
 .... I $P(XUCSX,U,4)<0 S XUCSRNEG=1,$P(^TMP($J,2,XUCSBDX\1,XUCSVG,XUCSAP,XUCSUCI,XUCSXR,"CMDS"),U,3)=1 ; Turn On Neg. Cmd. Encountered
 .... S $P(^TMP($J,2,XUCSBDX\1,XUCSVG,XUCSAP,XUCSUCI,XUCSXR,"RGBL"),"^",2)=$P(^TMP($J,2,XUCSBDX\1,XUCSVG,XUCSAP,XUCSUCI,XUCSXR,"RGBL"),"^",2)+$P(XUCSX,"^",5)
 .... Q
 ... I $D(XUCSAP) S ^TMP($J,2,XUCSBDX\1,XUCSVG,XUCSAP,"ZZZTRC")=XUCSET_"^"_XUCSTC_"^"_XUCSRDT_"^"_XUCSAJ
 ... I $D(XUCSAP) S ^TMP($J,2,XUCSBDX\1,XUCSVG,XUCSAP,"ZZZTRG")=XUCSET_"^"_XUCSTG_"^"_XUCSRDT_"^"_XUCSAJ,(XUCSTC,XUCSTG)=0 K XUCSAP,XUCSRDT,XUCSAJ
 ... Q
 .. Q
 . Q
 K XUCSAP,XUCSBD,XUCSBDX,XUCSCMDS,XUCSED,XUCSET,XUCSRGBL,XUCSRT,XUCSUCI,XUCSVG,XUCSX,XUCSX1,XUCSX2,XUCSX3,XUCSAP,XUCSXR,XUCSRDT,XUCSAJ
 I $D(XUCSDBUG),'$D(ZTQUEUED) W !,$J D ^%GL K XUCSDBUG
 Q
