XUCSCDR ;CLARKSBURG/SO CPU/DISK UTILIZATION REPORT BY VG/DATE ;2/9/96  13:23 [ 04/02/2003   8:47 AM ]
 ;;7.3;TOOLKIT;**1001**;APR 1, 2003
 ;;7.3;TOOLKIT;**6,13**;Apr 25, 1995
 Q:'$$CHKF^XUCSUTL
 S XUCSEND=0,(XUCSX,XUCSX1)="" F XUCSX="A3","A5" S XUCSX1=XUCSX_"^XUCSUTL3" D @XUCSX1 Q:XUCSEND
 G XIT:XUCSEND S %ZIS="MQ" D ^%ZIS I POP S POP=0 D HOME^%ZIS G XIT
 I $D(IO("Q")) D  G XIT
 . S ZTSAVE("XUCS*")="",ZTRTN="DEQUE^XUCSCDR",ZTDESC="CPU/DISK UTILIZATION REPORT",ZTIO=ION
 . S %DT="AEFRX",%DT("A")="Queue for what DATE/TIME? ",%DT("B")="NOW",%DT(0)="NOW" D ^%DT K %DT
 . I +Y'<0 S ZTDTH=Y D ^%ZTLOAD,HOME^%ZIS
 . K IO("Q")
 . Q
 U IO D:$E(IOST)="C" WAIT^DICD
DEQUE ;
 K ^TMP($J,7) D SORT,PRINT
XIT ; Common Exit Point
 I $E(IOST)'="C",'$D(ZTQUEUED) D ^%ZISC
 K ^TMP($J,7)
 K XUCSAP,XUCSAVC,XUCSAVD,XUCSAVJ,XUCSBD,XUCSBDX,XUCSDT,XUCSED,XUCSEND,XUCSET,XUCSHSW,XUCSPG,XUCSRDT
 K XUCSRT,XUCSSITE,XUCST,XUCSVG,XUCSX,XUCSX1,XUCSX2,XUCSX3,XUCSITE,XUCSITEH,XUCSDBUG
 Q
SORT ; Sort CPU - DISK Data
 S XUCSBDX=(XUCSBD-1)_".999999" F  S XUCSBDX=$O(^XUCS(8987.2,"C",XUCSBDX)) Q:XUCSBDX=""!($P(XUCSBDX,".")>XUCSED)  D
SL1 . I $E($P(XUCSBDX,".",2),1,2)<12,XUCSRT="P" Q  ; PM Records Only
 . I $E($P(XUCSBDX,".",2),1,2)>11,XUCSRT="A" Q  ; AM Records Only
 . S XUCSX1=0 F  S XUCSX1=$O(^XUCS(8987.2,"C",XUCSBDX,XUCSX1)) Q:+XUCSX1<1  D
SL2 .. S XUCSX2=0 F  S XUCSX2=$O(^XUCS(8987.2,"C",XUCSBDX,XUCSX1,XUCSX2)) Q:+XUCSX2<1  D
SL3 ... S XUCSVG=^XUCS(8987.2,XUCSX1,0) I $D(XUCSFS),'$D(XUCSFS(XUCSVG)) Q
 ... S XUCSET=^XUCS(8987.2,XUCSX1,1,XUCSX2,0),XUCSRDT=$P(XUCSET,"^"),XUCSET=$P(XUCSET,"^",3)
 ... S XUCSX3=0 F  S XUCSX3=$O(^XUCS(8987.2,XUCSX1,1,XUCSX2,6,XUCSX3)) Q:+XUCSX3<1  S XUCSX=^(+XUCSX3,0) D
SL4 .... S XUCSAP=$E($P(XUCSBDX,".",2),1,2),XUCSAP=$S(XUCSAP<12:"AM",1:"PM")
 .... S ^TMP($J,7,XUCSVG,XUCSBDX\1,XUCSAP,$P(XUCSX,"^"))=$P(XUCSX,"^",2,99)_"~"_XUCSRDT_"^"_XUCSET
 .... Q
 ... Q
 .. Q
 . Q
 I $D(XUCSDBUG),'$D(ZTQUEUED) W !,$J D ^%GL K XUCSDBUG
 Q
PRINT ; Print the Report
 S XUCSVG="" F  S XUCSVG=$O(^TMP($J,7,XUCSVG)) Q:XUCSVG=""!(XUCSEND)  D SITEH^XUCSUTL3 D
PL1 . S XUCSDT=0 F  S XUCSDT=$O(^TMP($J,7,XUCSVG,+XUCSDT)) Q:+XUCSDT<1!(XUCSEND)  D
PL2 .. S XUCSAP="" F  S XUCSAP=$O(^TMP($J,7,XUCSVG,+XUCSDT,XUCSAP)) Q:XUCSAP=""!(XUCSEND)  S (XUCSAVC,XUCSAVD,XUCSAVJ)=0 D HDR D
 ... S XUCST="",XUCST=$O(^TMP($J,7,XUCSVG,+XUCSDT,XUCSAP,XUCST)) Q:XUCST=""  S XUCSX=^(XUCST),XUCSX=$P(XUCSX,"~",2) D SHDR
PL3 ... S XUCST="" F I1=1:1 S XUCST=$O(^TMP($J,7,XUCSVG,+XUCSDT,XUCSAP,XUCST)) Q:XUCST=""!(XUCSEND)  S XUCSX=^(XUCST) D
PL4 .... S XUCSX1=$P(XUCSX,"^",2)/$P(XUCSX,"^")*100 ; % CPU Used
 .... S XUCSX2=$P(XUCSX,"^",3)/$P(XUCSX,"^")*100 ; % DISK Used
 .... S XUCSAVC=XUCSAVC+XUCSX1,XUCSAVD=XUCSAVD+XUCSX2,XUCSAVJ=XUCSAVJ+$P(XUCSX,"^",4)
 .... S Y=XUCST D DD^%DT W !,$P($P(Y,":",1,2),"@",2),?7,$J($P(XUCSX,"^",4),3,0),?15,$J(XUCSX1,5,1)_"%",?21,"|" D WLD
 .... W ?67,"|",$J(XUCSX2,5,1)_"%"
 .... Q
PL3C ... S I1=I1-1,XUCSX1=(XUCSAVC/I1),XUCSX2=(XUCSAVD/I1) W !!,"Ave.",?7,$J(XUCSAVJ/I1,3,0),?15,$J(XUCSX1,5,1)_"%",?21,"|" D WLD
 ... W ?67,"|",$J(XUCSX2,5,1)_"%"
 ... D PAUSE^XUCSUTL S (XUCSAVC,XUCSAVD,XUCSAVJ)=0
 ... Q
 .. Q
 . Q
 Q
HDR ; Header Sub-Routine
 I $D(XUCSHSW),$E(IOST)="P",$Y>2,$Y<(IOSL-18) DO  Q
 . N X
 . W !
 . S X="",$P(X,"-",IOM)="" W !,X
 . Q
 W:$D(XUCSHSW) @IOF
 I '$D(XUCSHSW) S XUCSHSW=1,XUCSPG=0 D NOW^%DTC S Y=% D DD^%DT S XUCSRDT=$P(Y,"@")_"@"_$P($P(Y,":",1,2),"@",2) W:$E(IOST)="C" @IOF
 S XUCSPG=XUCSPG+1 W !,"CPU/DISK Utilization Report  ",XUCSRDT,?(IOM-10),"Page: ",XUCSPG
 N X
 S X="",$P(X,"-",IOM)="" W !,X K X
 Q
SHDR ; Sub-Header Sub Routine
 S Y=$P(XUCSX,"^") D DD^%DT W !!,$P(Y,"@")," (",$P($P(Y,":",1,2),"@",2),"-" S X=$P(XUCSX,"^") D H^%DTC
 S %T=%T+$P(XUCSX,"^",2),%H=%H_","_%T D YMD^%DTC S Y=DT+% D DD^%DT W $P($P(Y,":",1,2),"@",2),")",?30,XUCSITEH
 W !,"Time",?7,"Jobs",?16,"%CPU",?69,"%DISK"
 Q
WLD ; Draw picture
 W ?(44-(XUCSX1\5)) F I2=1:1:(XUCSX1\5) W "+"
 W ?44 F I2=1:1:(XUCSX2\5) W "-"
 Q
