XUCS8RB ;CLARKSBURG/SO RESPONSE TIME REPORT BY DATE/VG ;2/9/96  13:19 [ 04/02/2003   8:47 AM ]
 ;;7.3;TOOLKIT;**1001**;APR 1, 2003
 ;;7.3;TOOLKIT;**6,13**;Apr 25, 1995
 Q:'$$CHKF^XUCSUTL
 S XUCSEND=0,(XUCSX,XUCSX1)="" F XUCSX="A3","A5" S XUCSX1=XUCSX_"^XUCSUTL3" D @XUCSX1 Q:XUCSEND
 G XIT:XUCSEND S %ZIS="MQ" D ^%ZIS I POP S POP=0 D HOME^%ZIS G XIT
 I $D(IO("Q")) D  G XIT
 . S ZTSAVE("XUCS*")="",ZTRTN="DEQUE^XUCS8RB",ZTDESC="RESPONSE TIME REPORT",ZTIO=ION
 . S %DT="AEFRX",%DT("A")="Queue for what DATE/TIME? ",%DT("B")="NOW",%DT(0)="NOW" D ^%DT K %DT
 . I +Y'<0 S ZTDTH=Y D ^%ZTLOAD,HOME^%ZIS
 . K IO("Q")
 . Q
 U IO D:$E(IOST)="C" WAIT^DICD
DEQUE ;
 K ^TMP($J,6) D SORT,PRINT
XIT ; Common Exit Point
 I $E(IOST)'="C",'$D(ZTQUEUED) D ^%ZISC
 K ^TMP($J,6)
 K XUCS30P,XUCSAP,XUCSAR,XUCSAT,XUCSBD,XUCSBDX,XUCSBI,XUCSDT,XUCSED,XUCSEI,XUCSEND,XUCSET,XUCSHSW
 K XUCSITE,XUCSPG,XUCSR,XUCSRDT,XUCSRT,XUCSRTOT,XUCSVG,XUCSX,XUCSX1,XUCSX2,XUCSX3,XUCSITE,XUCSITEH,XUCSDBUG
 Q
SORT ; Sort Responce Time Data
 S XUCSBDX=(XUCSBD-1)_".999999" F  S XUCSBDX=$O(^XUCS(8987.2,"C",XUCSBDX)) Q:XUCSBDX=""!($P(XUCSBDX,".")>XUCSED)  D
SL1 . I $E($P(XUCSBDX,".",2),1,2)<12,XUCSRT="P" Q  ; PM Records Only
 . I $E($P(XUCSBDX,".",2),1,2)>11,XUCSRT="A" Q  ; AM Records Only
 . S XUCSX1=0 F  S XUCSX1=$O(^XUCS(8987.2,"C",XUCSBDX,XUCSX1)) Q:+XUCSX1<1  D
SL2 .. S XUCSX2=0 F  S XUCSX2=$O(^XUCS(8987.2,"C",XUCSBDX,XUCSX1,XUCSX2)) Q:+XUCSX2<1  D
SL3 ... S XUCSVG=^XUCS(8987.2,XUCSX1,0) I $D(XUCSFS),'$D(XUCSFS(XUCSVG)) Q
 ... S XUCSET=^XUCS(8987.2,XUCSX1,1,XUCSX2,0),XUCSRDT=$P(XUCSET,"^"),XUCSAJ=$P(XUCSET,"^",5),XUCSET=$P(XUCSET,"^",3)
 ... S (XUCSRTOT,XUCSX3)=0 F I1=1:1 S XUCSX3=$O(^XUCS(8987.2,XUCSX1,1,XUCSX2,5,XUCSX3)) Q:+XUCSX3<1  S XUCSX=^(+XUCSX3,0) D
SL4 .... S XUCSAP=$E($P(XUCSBDX,".",2),1,2),XUCSAP=$S(XUCSAP<12:"AM",1:"PM")
 .... S ^TMP($J,6,XUCSBDX\1,XUCSVG,XUCSAP,I1)=XUCSET_"^"_$P(XUCSX,"^",1,99)_"~"_XUCSRDT_"^"_XUCSET_"^"_XUCSAJ,XUCSRTOT=XUCSRTOT+$P(XUCSX,"^",4)
 .... Q
 ... Q
 .. Q
 . Q
 I $D(XUCSDBUG) W !,$J D ^%GL K XUCSDBUG
 Q
PRINT ; Print the Report
 S XUCSDT=0 F  S XUCSDT=$O(^TMP($J,6,+XUCSDT)) Q:+XUCSDT<1!(XUCSEND)  D
PL1 . S XUCSVG="" F  S XUCSVG=$O(^TMP($J,6,+XUCSDT,XUCSVG)) Q:XUCSVG=""!(XUCSEND)  D SITEH^XUCSUTL3 D
PL2 .. S XUCSAP="" F  S XUCSAP=$O(^TMP($J,6,+XUCSDT,XUCSVG,XUCSAP)) Q:XUCSAP=""!(XUCSEND)  D HDR^XUCS8R D
PL3 ... S (XUCSBI,XUCSEI,XUCSR,XUCSAR,XUCSAT,XUCS30L,XUCS30P,XUCSX,I1)=0
 ... S XUCSX=0,XUCSX=$O(^TMP($J,6,+XUCSDT,XUCSVG,XUCSAP,+XUCSX)) Q:+XUCSX<1  S XUCSX=^(+XUCSX),XUCSX=$P(XUCSX,"~",2) D SHDR^XUCS8R
 ... S XUCSX=0 F   S XUCSX=$O(^TMP($J,6,+XUCSDT,XUCSVG,XUCSAP,+XUCSX)) S:+XUCSX>0 XUCSX1=^(XUCSX) Q:+XUCSX<1!(XUCSEND)  D SETVAR D
PL4A .... I XUCSEI'>30,XUCSEI'=0 S XUCS30L=XUCS30L+XUCSR
 .... I XUCSEI'<30 S XUCS30P=XUCS30P+XUCSR
 .... I XUCSEI'>30,XUCSEI'=0 S XUCSAT=XUCSAT+$S(XUCSEI=1:XUCSR*.3,XUCSEI=2:XUCSR*1.4,1:XUCSR*(XUCSBI-(XUCSEI-XUCSBI)/2))
 .... Q
PL3C1 ... S XUCSX=0 F   S XUCSX=$O(^TMP($J,6,+XUCSDT,XUCSVG,XUCSAP,+XUCSX)) S:+XUCSX>0 XUCSX1=^(XUCSX) Q:+XUCSX<1!(XUCSEND)  D SETVAR D
PL4B .... I XUCSEI'>30,XUCSEI'=0 W !,$J(XUCSBI,2,0),"-",$S(XUCSEI>0:$J(XUCSEI-.01,5,2),1:"")," Sec. ",$J(XUCSR,6,0),?20,$S(XUCS30L=0:0,1:$J((XUCSR/XUCS30L)*100,5,1)),"%"
 .... Q
PL3C2 ... W !!,"total<30 Sec. ",$J(XUCS30L,6,0)
 ... W !,"total>30 Sec. ",$J(XUCS30P,6,0)
 ... I XUCS30L>0 W !,"Average RT for Responses between 0 and 30 Sec.: ",$J(XUCSAT/XUCS30L,6,2)
 ... D PAUSE^XUCSUTL
 ... Q
 .. Q
 . Q
 Q
SETVAR ;
 S XUCSBI=$P(XUCSX1,"^",2) ; Get Beginning of Interval
 S XUCSEI=$P(XUCSX1,"^",3) ; Get Ending of Interval
 S XUCSR=$P(XUCSX1,"^",4) ; Get Number of Responses for Interval
 Q
