XUCSPRG ;CLARKSBURG/SO PURGE OF DATA COLLECTION ENTRIES ;9/993 [ 04/02/2003   8:47 AM ]
 ;;7.3;TOOLKIT;**1001**;APR 1, 2003
 ;;7.3;TOOLKIT;**15**;Apr 25, 1995
M ; Manual Entry Point
 S XUCSEND=0 D  I XUCSEND K XUCSEND Q
 . N X
 . I +$$OSTYPE^%ZOSV>2 S XUCSEND=1 Q  ; Not PC or NT OS
 . I +$E($$VERSION^%ZOSV)'=4 S XUCSEND=1 Q  ; Not Version 4+ MSM
 . Q
 . Q
 S DIC="^XUCS(8987.1,",DIC(0)="MNZ",X=1 D ^DIC K DIC I +Y<1 K XUCSEND Q
 S XUCSDAYS=$P(Y(0),"^",4) S:'$L(XUCSDAYS) XUCSDAYS=45
 K DIR S DIR(0)="N^7:90",DIR("A")="Enter Number of Days to keep",DIR("B")=XUCSDAYS,DIR("?")="HELP - HELP" D ^DIR K DIR I $D(DIRUT) K DTOUT,DUOUT,DIRUT,XUCSEND,XUCSDAYS Q
 S XUCSDAYS=X
 S ZTRTN="DEQUE^XUCSPRG",ZTDESC="Purge Daily Entries File #8987.2",ZTSAVE("XUCSDAYS")="",ZTIO=""
  K %DT S %DT="AEFRTX",%DT("A")="Queue for what Date/Time? ",%DT("B")="NOW",%DT(0)="NOW" D ^%DT K %DT I +Y<0 K DTOUT,ZTRTN,ZTDESC,ZTSAVE,XUCSEND,XUCSDAYS Q
 S ZTDTH=Y D ^%ZTLOAD,HOME^%ZIS K ZTRTN,ZTDESC,ZTSAVE,ZTDTH,XUCSEND,XUCSDAYS
 Q
 ;
DEQUE ; Deque Entry Point
 S XUCSEND=0 D  I XUCSEND K XUCSEND Q
 . N X
 . I +$$OSTYPE^%ZOSV>2 S XUCSEND=1 Q  ; Not PC or NT OS
 . I +$E($$VERSION^%ZOSV) S XUCSEND=1 Q  ; Not Version 4+ MSM
 . Q
 ;
 I '$D(XUCSDAYS) S DIC="^XUCS(8987.1,",DIC(0)="MNZ",X=1 D ^DIC K DIC Q:+Y<1  S XUCSDAYS=$P(Y(0),"^",4) S:'$L(XUCSDAYS) XUCSDAYS=45
 S X1=DT,X2=-XUCSDAYS D C^%DTC S XUCSED=X
KL1 ;Begin Looping thru ^XUCS(8987.2,"C",FM Date/Time, xref.
 ; stop when $P(XUCSD,".")=XUCSED
 S XUCSD=0 F  S XUCSD=$O(^XUCS(8987.2,"C",+XUCSD)) Q:(+XUCSD<1!($P(XUCSD,".")'<XUCSED))  D
KL2 . ; Loop On DA(1) Value
 . S XUCSDA1=0 F  S XUCSDA1=$O(^XUCS(8987.2,"C",+XUCSD,+XUCSDA1)) Q:+XUCSDA1<1  D
KL3 .. ; Loop on DA Value
 .. S XUCSDA=0 F  S XUCSDA=$O(^XUCS(8987.2,"C",+XUCSD,+XUCSDA1,+XUCSDA)) Q:+XUCSDA<1  D
KE ... ; Kill Entry in Multiple # 8987.2.01
 ... K DIK S DA(1)=XUCSDA1,DA=XUCSDA,DIK="^XUCS(8987.2,"_DA(1)_",1," D ^DIK K DA,DIK
 ... Q
 .. Q
 . Q
 K XUCSDAYS,XUCSED,XUCSD,XUCSDA,XUCSDA1
 Q
