XUCS2RB ;CLARKSBURG/SO REPORT FOR GLOBAL REFERENSES BY DATE/VG - MAIN ;2/9/96  13:12 [ 04/02/2003   8:47 AM ]
 ;;7.3;TOOLKIT;**1001**;APR 1, 2003
 ;;7.3;TOOLKIT;**13**;Apr 25, 1995
 Q:'$$CHKF^XUCSUTL
 S XUCSEND=0,(XUCSX,XUCSX1)="" F XUCSX="A4","A3","A5" S XUCSX1=XUCSX_"^XUCSUTL3" D @XUCSX1 Q:XUCSEND
 G XIT:XUCSEND S %ZIS="MQ" D ^%ZIS I POP S POP=0 D HOME^%ZIS G XIT
 I $D(IO("Q")) D  G XIT
 . S ZTSAVE("XUCS*")="",ZTRTN="DEQUE^XUCS2RB",ZTDESC="GLOBAL REFERENSES REPORT",ZTIO=ION
 . S %DT="AEFRX",%DT("A")="Queue for what DATE/TIME? ",%DT("B")="NOW",%DT(0)="NOW" D ^%DT K %DT
 . I +Y'<0 S ZTDTH=Y D ^%ZTLOAD,HOME^%ZIS
 . K IO("Q")
 . Q
 U IO D:$E(IOST)="C" WAIT^DICD
DEQUE ;
 K ^TMP($J,3) D SORT,PRINT^XUCS2RBA
XIT ; Common Xit Point
 I $E(IOST)'="C" D ^%ZISC
 K ^TMP($J,3)
 K XUCSAOC,XUCSAOG,XUCSAP,XUCSDT,XUCSEND,XUCSFS,XUCSI,XUCSHSW,XUCSPG,XUCSRDT,XUCSROU,XUCSROUW,XUCSTC,XUCSTG,XUCSXRC,XUCSXRG
 K XUCSRL,XUCSS1C,XUCSS1G,XUCSSY,XUCSTH,XUCSUCI,XUCSVG,XUCSX,XUCSX1,XUCSX2,XUCSY,XUCSY1,XUCSY2,XUCSITE,XUCSITEH,XUCSDBUG
 Q
SORT ; Sort Report Data
 S XUCSBDX=(XUCSBD-1)_".999999" F  S XUCSBDX=$O(^XUCS(8987.2,"C",XUCSBDX)) Q:XUCSBDX=""!($P(XUCSBDX,".")>XUCSED)  D
SL1 . I $E($P(XUCSBDX,".",2),1,2)<12,XUCSRT="P" Q  ; PM Records Only
 . I $E($P(XUCSBDX,".",2),1,2)>11,XUCSRT="A" Q  ; AM Records Only
 . S XUCSX1=0 F  S XUCSX1=$O(^XUCS(8987.2,"C",XUCSBDX,XUCSX1)) Q:+XUCSX1<1  D
SL2 .. S XUCSX2=0 F  S XUCSX2=$O(^XUCS(8987.2,"C",XUCSBDX,XUCSX1,XUCSX2)) Q:+XUCSX2<1  D
SL3 ... S XUCSVG=^XUCS(8987.2,XUCSX1,0) I $D(XUCSFS),'$D(XUCSFS(XUCSVG)) Q
 ... S XUCSET=^XUCS(8987.2,XUCSX1,1,XUCSX2,0),XUCSRDT=$P(XUCSET,"^"),XUCSAJ=$P(XUCSET,"^",5),XUCSET=$P(XUCSET,"^",3)
 ... S XUCSX3=0 F  S XUCSX3=$O(^XUCS(8987.2,XUCSX1,1,XUCSX2,2,XUCSX3)) Q:+XUCSX3<1  S XUCSX=^(+XUCSX3,0) D
SL4 .... S XUCSAP=$E($P(XUCSBDX,".",2),1,2),XUCSAP=$S(XUCSAP<12:"AM",1:"PM")
 .... K XUCSXG
 .... I XUCSGL<8,$L($P(XUCSX,"^"))>XUCSGL S XUCSXG=$E($P(XUCSX,"^"),1,XUCSGL)_"*"
 .... S:'$D(XUCSXG) XUCSXG=$P(XUCSX,"^")
 .... S XUCSUCI=$P(XUCSX,"^",2)_"~"_$P(XUCSX,"^",3)
 .... I '$D(^TMP($J,3,XUCSBDX\1,XUCSVG,XUCSAP,XUCSUCI,XUCSXG)) S ^TMP($J,3,XUCSBDX\1,XUCSVG,XUCSAP,XUCSUCI,XUCSXG)=XUCSET_"^"_0
 .... S:'$D(XUCSTGR) XUCSTGR=0 S XUCSTGR=XUCSTGR+$P(XUCSX,"^",4)
 .... S $P(^TMP($J,3,XUCSBDX\1,XUCSVG,XUCSAP,XUCSUCI,XUCSXG),"^",2)=$P(^TMP($J,3,XUCSBDX\1,XUCSVG,XUCSAP,XUCSUCI,XUCSXG),"^",2)+$P(XUCSX,"^",4)
 .... Q
 ... I $D(XUCSAP) S ^TMP($J,3,XUCSBDX\1,XUCSVG,XUCSAP,"ZZZTGR")=XUCSET_"^"_XUCSTGR_"^"_XUCSRDT_"^"_XUCSAJ,XUCSTGR=0 K XUCSAP,XUCSRDT,XUCSAJ
 ... Q
 .. Q
 . Q
 I $D(XUCSDBUG),'$D(ZTQUEUED) W !,$J D ^%GL K XUCSDBUG
 K XUCSAP,XUCSBD,XUCSBDX,XUCSCMDS,XUCSED,XUCSET,XUCSRGBL,XUCSRT,XUCSUCI,XUCSVG,XUCSX,XUCSX1,XUCSX2,XUCSX3,XUCSAP,XUCSXR,XUCSRDT,XUCSAJ
 Q
