XUCS8RG ;CLARKSBURG/SO GRAPH RESPONSE TIME BY VG/DATE ;2/9/96  13:20 [ 04/02/2003   8:47 AM ]
 ;;7.3;TOOLKIT;**1001**;APR 1, 2003
 ;;7.3;TOOLKIT;**13**;Apr 25, 1995
 Q:'$$CHKF^XUCSUTL
 S XUCSEND=0 D A5^XUCSUTL3
 G XIT:XUCSEND S %ZIS="MQ" D ^%ZIS I POP S POP=0 D HOME^%ZIS G XIT
 I $D(IO("Q")) D  G XIT
 . S ZTSAVE("XUCS*")="",ZTRTN="DEQUE^XUCS8RG",ZTDESC="GRAPH RESPONSE TIME REPORT",ZTIO=ION
 . S %DT="AEFRX",%DT("A")="Queue for what DATE/TIME? ",%DT("B")="NOW",%DT(0)="NOW" D ^%DT K %DT
 . I +Y'<0 S ZTDTH=Y D ^%ZTLOAD,HOME^%ZIS
 . K IO("Q")
 . Q
 U IO D:$E(IOST)="C" WAIT^DICD
DEQUE ;
 K ^TMP($J,6) D SORT,PRINT^XUCS8RGA
XIT ; Common Exit Point
 I $E(IOST)'="C",'$D(ZTQUEUED) D ^%ZISC
 K ^TMP($J,6)
 K XUCSAP,XUCSAT,XUCSW,XUCSBDX,XUCSD0,XUCSD1,XUCSD2,XUCSDBUG,XUCSEND,XUCSFS,XUCSH,XUCSHSW
 K XUCSPG,XUCSR,XUCSRDT,XUCSVG,XUCSX,XUCSX1,XUCSITEH,XUCSPD,XUCSS,XUCSS1,XUCSITE,XUCSITEN
 Q
SORT ; Sort Ave. Responce Time Data
 S X1=DT,X2=-60 D C^%DTC S XUCSBDX=X F  S XUCSBDX=$O(^XUCS(8987.2,"C",XUCSBDX)) Q:+XUCSBDX<1  DO
SL1 . S XUCSD0=0 F  S XUCSD0=$O(^XUCS(8987.2,"C",XUCSBDX,XUCSD0)) Q:+XUCSD0<1  DO
SL2 .. S XUCSD1=0 F  S XUCSD1=$O(^XUCS(8987.2,"C",XUCSBDX,XUCSD0,XUCSD1)) Q:+XUCSD1<1  DO
SL3 ... S XUCSVG=^XUCS(8987.2,XUCSD0,0) I $D(XUCSFS),'$D(XUCSFS(XUCSVG)) Q
 ... ;S XUCSET=^XUCS(8987.2,XUCSD0,1,XUCSD1,0),XUCSET=$P(XUCSET,"^",3)
 ... S (XUCSAT,XUCSR,XUCSD2)=0 F  S XUCSD2=$O(^XUCS(8987.2,XUCSD0,1,XUCSD1,5,XUCSD2)) Q:+XUCSD2<1  S XUCSX=^(+XUCSD2,0) Q:$P(XUCSX,"^",1)'<30  DO
SL4 .... S XUCSR=XUCSR+$P(XUCSX,"^",3),XUCSAT=XUCSAT+$S($P(XUCSX,"^",2)=1:$P(XUCSX,"^",3)*.3,$P(XUCSX,"^",2)=2:$P(XUCSX,"^",3)*1.4,1:$P(XUCSX,"^",3)*($P(XUCSX,"^",2)-$P(XUCSX,"^",1)/2))
 .... Q
 ... S XUCSAP=$E($P(XUCSBDX,".",2),1,2),XUCSAP=$S(XUCSAP<12:"AM",1:"PM")
 ... S XUCSX=$S(XUCSR=0:0,1:$J((XUCSAT/XUCSR),0,3)),^TMP($J,6,XUCSVG,XUCSAP,$P(XUCSBDX,"."))=XUCSX,(XUCSAT,XUCSR)=0
 ... Q
 .. Q
 . Q
 I $D(XUCSDBUG) W !,$J D ^%GL K XUCSDBUG
 Q
