ATXFV ;IHS/CMI/LAB-CREATED BY ^ATXSTX ON APR 05, 2022;
 ;;5.1;TAXONOMY;**42**;FEB 04, 1997;Build 93
 ;
 ; See referenced routines to see taxonomies being loaded.
 ;
START ;
 D ^ATXFVA ;    BGP BMI DXS
 D ^ATXFVB ;    BGP ECQM ADV ILLNESS DXS
 D ^ATXFVC ;    BGP ECQM FRAILTY DXS
 D ^ATXFVD ;    BGP ECQM STATIN ADV DXS
 D ^ATXFVE ;    BGP HIV/AIDS DXS
 D ^ATXFVF ;    BGP HR PNEUMO CFL
 D ^ATXFVG ;    BGP HR PNEUMO IMMUNO
 D ^ATXFVH ;    BGP HR PNEUMO MED COND
 D ^ATXFVI ;    BGP HR ZOSTER
 D ^ATXFVJ ;    BGP IPC BIPOLAR DIAG DXS
 D ^ATXFVK ;    BGP IPC DEPRESSION DIAG DXS
 D ^ATXFVL ;    BGP TOBACCO DXS
 D ^ATXFVM ;    BGP TOBACCO USER DXS
 Q
