ATXFS ;IHS/CMI/LAB-CREATED BY ^ATXSTX ON DEC 07, 2021;
 ;;5.1;TAXONOMY;**40**;FEB 04, 1997;Build 89
 ;
 ; See referenced routines to see taxonomies being loaded.
 ;
START ;
 D ^ATXFSA ;    BQI ANTHRAX DXS
 D ^ATXFSB ;    BQI CHOLERA DXS
 D ^ATXFSC ;    BQI HANTAVIRUS DXS
 D ^ATXFSD ;    BQI DIPHTHERIA DXS
 D ^ATXFSE ;    BQI LEGIONNAIRE DXS
 D ^ATXFSF ;    BQI LISTERIOSIS DXS
 D ^ATXFSG ;    BUD 21 T6A LINE 24B
 D ^ATXFSH ;    BQI LYME DXS
 D ^ATXFSI ;    BQI MALARIA DXS
 D ^ATXFSJ ;    BQI POWASSEN DXS
 D ^ATXFSK ;    BQI SARS DXS
 D ^ATXFSL ;    BQI SHIGELLA DXS
 D ^ATXFSM ;    BQI ROCKY MTN FEVER DXS
 D ^ATXFSN ;    BQI PARATYPHOID DXS
 D ^ATXFSO ;    BQI PARKINSONS DXS
 D ^ATXFSP ;    BQI ARBOVIRUS DXS
 D ^ATXFSQ ;    BQI BLASTOMYCOSIS DXS
 D ^ATXFSR ;    BQI CAMPYLOBACTERIOSIS DXS
 D ^ATXFSS ;    BQI CHIKUNGUNYA DXS
 D ^ATXFST ;    BQI COLORADO TICK DXS
 D ^ATXFSU ;    BQI DENGUE DXS
 D ^ATXFSV ;    BQI HISTOPLASMOSIS DXS
 D ^ATXFSW ;    BQI ACANTHAMOEBA DXS
 D ^ATXFSX ;    BQI JAPAN ENCEPH DXS
 D ^ATXFSY ;    BQI LEPTOSPIROSIS DXS
 D ^ATXFSZ ;    BQI MELIOIDOSIS DXS
 Q
