ATXHF ;IHS/CMI/LAB-CREATED BY ^ATXSTX ON JAN 07, 2025;
 ;;5.1;TAXONOMY;**60**;FEB 04, 1997;Build 126
 ;
 ; See referenced routines to see taxonomies being loaded.
 ;
START ;
 D ^ATXHFA ;    BQI ALPHA GAL SYNDROME DXS
 D ^ATXHFB ;    BQI AMEBIASIS DXS
 D ^ATXHFC ;    BQI MYELITIS DXS
 D ^ATXHFD ;    BQI ANAPLASMOSIS DXS
 D ^ATXHFE ;    BQI ANENCEPHALY DXS
 D ^ATXHFF ;    BQI C DIFF DXS
 D ^ATXHFG ;    BQI POST COVID-19 DXS
 D ^ATXHFH ;    BQI MRSA DXS
 D ^ATXHFI ;    BQI STAPH AUREUS INFECT DXS
 D ^ATXHFJ ;    BQI STREP GROUP A DXS
 D ^ATXHFK ;    BQI STREP GROUP B DXS
 D ^ATXHFL ;    BQI ARSENIC EXPOS & TOXI DXS
 D ^ATXHFM ;    BQI MERCURY EXPOS & TOX DXS
 D ^ATXHFN ;    BQI TOXOPLASMOSIS DXS
 D ^ATXHFO ;    BQI TYPHUS FEVER DXS
 D ^ATXHFP ;    BQI ENCEPHALITIS BACT DXS
 D ^ATXHFQ ;    BQI ENCEPHALITIS FUNGI DXS
 D ^ATXHFR ;    BQI ENCEPHALITIS PARAS DXS
 D ^ATXHFS ;    BI RZV IMMUNOSUPPRESS RXNORM
 D ^ATXHFT ;    BQI ENCEPHALITIS VIRUS DXS
 Q
