ATXH2 ;IHS/CMI/LAB-CREATED BY ^ATXSTX ON DEC 05, 2022;
 ;;5.1;TAXONOMY;**47**;FEB 04, 1997;Build 99
 ;
 ; See referenced routines to see taxonomies being loaded.
 ;
START ;
 D ^ATXH2A ;    BQI HEAD INJURY DXS
 D ^ATXH2B ;    BQI TBI DXS
 D ^ATXH2C ;    BQI GUNSHOT DXS
 D ^ATXH2D ;    BQI NEONATAL CONJUNCTIVITIS DX
 D ^ATXH2E ;    BQI REYES SYNDROME DXS
 D ^ATXH2F ;    BQI LOUSEBORNE DXS
 D ^ATXH2G ;    BQI CAUTI DXS
 D ^ATXH2H ;    BQI TOXOPLASMOSIS DXS
 D ^ATXH2I ;    BQI OVERDOSE STIMULANTS DXS
 D ^ATXH2J ;    BQI OVERDOSE DEPRESSANTS DXS
 D ^ATXH2K ;    BQI OVERDOSE HALLUCINOGEN DXS
 D ^ATXH2L ;    BQI OVERDOSE CANNABINOID DXS
 D ^ATXH2M ;    BQI OVERDOSE ANALGESIC DXS
 D ^ATXH2N ;    BQI OVERDOSE OTHER DRUG DXS
 D ^ATXH2O ;    BQI SURGICAL SITE INFECT DXS
 Q
