ATXHA ;IHS/CMI/LAB-CREATED BY ^ATXSTX ON JUL 05, 2024;
 ;;5.1;TAXONOMY;**55**;FEB 04, 1997;Build 119
 ;
 ; See referenced routines to see taxonomies being loaded.
 ;
START ;
 D ^ATXHAA ;    BQI AGRICULTURE POISON DXS
 D ^ATXHAB ;    BQI DOG BITE DXS
 D ^ATXHAC ;    BQI MAMMAL BITE DXS
 D ^ATXHAD ;    BQI NON MAMMAL BITE DXS
 D ^ATXHAE ;    BQI NONTUBERCULOUS MYCOBACT
 D ^ATXHAF ;    BQI COALWORKER'S PNEUMOCON DXS
 D ^ATXHAG ;    BQI INTERSTITIAL LUNG DISEASE
 D ^ATXHAH ;    BQI INTERSTITIAL PULM FIBROSIS
 D ^ATXHAI ;    BQI CYTOMEGALOVIRUS DXS
 D ^ATXHAJ ;    BQI DIPHYLLOBOTHRIASIS DXS
 D ^ATXHAK ;    BQI TOXIC PNEUMONITIS DXS
 D ^ATXHAL ;    BQI PHENYLKETONURIA DXS
 D ^ATXHAM ;    BQI NONGONOCOCCAL URETHRITIS
 D ^ATXHAN ;    BQI PRION DISEASE DXS
 D ^ATXHAO ;    BQI ASEPTIC MENINGITIS DXS
 D ^ATXHAP ;    BQI BACTERIAL MENINGITIS DXS
 D ^ATXHAQ ;    BQI FUNGAL MENINGITIS DXS
 D ^ATXHAR ;    BQI PARASITIC MENINGITIS DXS
 D ^ATXHAS ;    BQI OTHER MENINGITIS DXS
 D ^ATXHAT ;    BQI COVID ECR EXPOSURE
 D ^ATXHAU ;    BQI MULTI INFLAM SYNDROME DXS
 Q
