ATXH4 ;IHS/CMI/LAB-CREATED BY ^ATXSTX ON MAR 01, 2023;
 ;;5.1;TAXONOMY;**48**;FEB 04, 1997;Build 101
 ;
 ; See referenced routines to see taxonomies being loaded.
 ;
START ;
 D ^ATXH4A ;    BGP SEXUAL ACTIVITY DXS
 D ^ATXH4B ;    BGP SUBSTANCE PROC
 D ^ATXH4C ;    BGP SUBSTANCE USE POS DXS
 D ^ATXH4D ;    BGP TOBACCO DXS
 D ^ATXH4E ;    BGP TOBACCO USER DXS
 D ^ATXH4F ;    BGP TOPICAL FLUORIDE DXS
 D ^ATXH4G ;    BGP DENTAL VISIT DXS
 D ^ATXH4H ;    BGP DEPRESSION SCRN DXS
 Q
