ATXH1 ;IHS/CMI/LAB-CREATED BY ^ATXSTX ON NOV 04, 2022;
 ;;5.1;TAXONOMY;**46**;FEB 04, 1997;Build 97
 ;
 ; See referenced routines to see taxonomies being loaded.
 ;
START ;
 D ^ATXH1A ;    BQI KAWASAKI DXS
 D ^ATXH1B ;    BQI RHEUMATIC FEVER DXS
 D ^ATXH1C ;    BQI ADVERSE REACTION DXS
 D ^ATXH1D ;    BQI ASBESTOSIS DXS
 D ^ATXH1E ;    BQI BYSSINOSIS DXS
 D ^ATXH1F ;    BQI CADMIUM POISON DXS
 D ^ATXH1G ;    BQI HERPES CONGENITAL DXS
 D ^ATXH1H ;    BQI VENTILATION CMPLCTN DXS
 D ^ATXH1I ;    BQI CRYPTOCOCCOSIS DXS
 D ^ATXH1J ;    BQI CYSTICERCOSIS DXS
 D ^ATXH1K ;    BQI COWPOX DXS
 D ^ATXH1L ;    BQI ORTHOPOX DXS
 D ^ATXH1M ;    BQI VACCINIA DXS
 D ^ATXH1N ;    BQI ENTEROVIRUS DXS
 D ^ATXH1O ;    BQI ENCEPHALITIS DXS
 D ^ATXH1P ;    BQI GLANDERS DXS
 D ^ATXH1Q ;    BQI GUILLAIN-BARRE DXS
 D ^ATXH1R ;    BQI SCABIES DXS
 Q
