ATXHD ;IHS/CMI/LAB-CREATED BY ^ATXSTX ON OCT 29, 2024;
 ;;5.1;TAXONOMY;**58**;FEB 04, 1997;Build 124
 ;
 ; See referenced routines to see taxonomies being loaded.
 ;
START ;
 D ^ATXHDA ;    BQI ACANTH KERATITIS DXS
 D ^ATXHDB ;    BQI EBSTEIN ANOMALY DXS
 D ^ATXHDC ;    BQI HYPOPLASTIC LEFT HEART DXS
 D ^ATXHDD ;    BQI INTERRUPTED AORTIC ARCH DX
 D ^ATXHDE ;    BQI TETRALOGY OF FALLOT DXS
 D ^ATXHDF ;    BQI TOT ANOMAL PULMON VENOUS
 Q
