ATXH3 ;IHS/CMI/LAB-CREATED BY ^ATXSTX ON MAR 01, 2023;
 ;;5.1;TAXONOMY;**48**;FEB 04, 1997;Build 101
 ;
 ; See referenced routines to see taxonomies being loaded.
 ;
START ;
 D ^ATXH3A ;    BGP ABNORMAL GAIT OR MOBILITY
 D ^ATXH3B ;    BGP ABORTION PROCEDURES
 D ^ATXH3C ;    BGP ALCOHOL DXS
 D ^ATXH3D ;    BGP ALCOHOL HEPATITIS DXS
 D ^ATXH3E ;    BGP AMI DXS PAMT
 D ^ATXH3F ;    BGP CMS CARDIAC CATH/LV PROCS
 D ^ATXH3G ;    BGP CMS ECHOCARDIOGRAM PROCS
 D ^ATXH3H ;    BGP CMS EJECTION FRACTION PROC
 D ^ATXH3I ;    BGP CRS LVAD/HEART TRANS PROC
 D ^ATXH3J ;    BGP DEPRESSION SCREEN DXS
 D ^ATXH3K ;    BGP DV DXS
 D ^ATXH3L ;    BGP BREASTFEEDING DXS
 D ^ATXH3M ;    BGP ECQM CABG PROCS
 D ^ATXH3N ;    BGP FALL RELATED E-CODES
 D ^ATXH3O ;    BGP GPRA SMOKING DXS
 D ^ATXH3P ;    BGP HEART FAILURE DXS
 D ^ATXH3Q ;    BGP HISTORY OF FALL DXS
 D ^ATXH3R ;    BGP IPV/DV COUNSELING ICDS
 D ^ATXH3S ;    BGP MAJOR DEPRESSION (ADM)
 D ^ATXH3T ;    BGP MISCARRIAGE/ABORTION DXS
 D ^ATXH3U ;    BGP MOOD DISORDERS
 D ^ATXH3V ;    BGP MYOPATHY/MYALGIA
 D ^ATXH3W ;    BGP OPEN ANGLE GLAUCOMA DXS
 D ^ATXH3X ;    BGP PALLIATIVE CARE DXS
 D ^ATXH3Y ;    BGP PQA CANCER DXS
 D ^ATXH3Z ;    BGP PREGNANCY DIAGNOSES 2
 Q
