ATXHB ;IHS/CMI/LAB-CREATED BY ^ATXSTX ON AUG 05, 2024;
 ;;5.1;TAXONOMY;**56**;FEB 04, 1997;Build 120
 ;
 ; See referenced routines to see taxonomies being loaded.
 ;
START ;
 D ^ATXHBA ;    BQI METHEMOGLOBINEMIA NONCONG
 D ^ATXHBB ;    BQI METHEMOGLOBINEMIA DXS
 D ^ATXHBC ;    BQI GASTROSCHISIS DXS
 D ^ATXHBD ;    BQI FARMERS LUNG DXS
 D ^ATXHBE ;    BQI GRANULOMA INGUINALE DXS
 D ^ATXHBF ;    BQI LYMPHOCYTIC CHORIOMENINGIT
 D ^ATXHBG ;    BQI CLABSI DXS
 D ^ATXHBH ;    BQI LIMB REDUCTION DXS
 D ^ATXHBI ;    BQI FEMALE PELVIC INFLAMM DXS
 D ^ATXHBJ ;    BQI CLOSTRIDIUM PERF ENTEROTOX
 D ^ATXHBK ;    BQI CLOSTRIDIUM PERF INFEC
 D ^ATXHBL ;    BQI DROWNING/SUBMERSION DXS
 D ^ATXHBM ;    BQI FISH POISONING DXS
 D ^ATXHBN ;    BQI SHELLFISH POISONING DXS
 D ^ATXHBO ;    BQI MULTISYSTEM INFLAMM DXS
 D ^ATXHBP ;    BGP ECQM FRAILTY SYMPTOM DXS
 D ^ATXHBQ ;    BGP ECQM FRAILTY DXS
 D ^ATXHBR ;    BGP IPC HEP B DXS
 D ^ATXHBS ;    BGP IPC DIABETES DXS
 D ^ATXHBT ;    BGP IPC COLON CANCER DXS
 D ^ATXHBU ;    BGP IPC BIPOLAR DIAG DXS
 D ^ATXHBV ;    BGP IPC BELOW NORMAL FU DXS
 Q
