ATXLTV ; IHS/CMI/LAB - DISPLAY IND LISTS ;
 ;;5.1;TAXONOMY;**61**;FEB 04, 1997;Build 133
 ;; ;
EP ;EP - CALLED FROM OPTION
 D EN
 Q
EOJ ;EP
 D EN^XBVK("ATX")
 K ^TMP($J)
 Q
 ;; ;
EN ;EP -- main entry point for 
 D EN^VALM("ATXL TAXONOMY VIEW")
 D CLEAR^VALM1
 D FULL^VALM1
 W:$D(IOF) @IOF
 D EOJ
 Q
 ;
PAUSE ;EP
 Q:$E(IOST)'="C"!(IO'=IO(0))
 W ! S DIR(0)="EO",DIR("A")="Press enter to continue...." D ^DIR K DIR S:$D(DUOUT) DIRUT=1
 Q
HDR ; -- header code
 S VALMHDR(1)="View A Taxonomy Contents"
 Q
 ;
INIT ;EP -- init variables and list array
 K ^TMP($J) S ATXHIGH="",C=0,J=0
 S ATXT=""
 F  S ATXT=$O(^ATXAX("B",ATXT)) Q:ATXT=""  D
 .S ATXY=0 F  S ATXY=$O(^ATXAX("B",ATXT,ATXY)) Q:ATXY'=+ATXY  D
 ..Q:'$D(^ATXAX(ATXY,0))
 ..;Q:$P(^ATXAX(ATXY,0),U,15)=""
 ..I $P(^ATXAX(ATXY,0),U)'["RXNORM" Q:$P(^ATXAX(ATXY,0),U,15)=""  ;P60
 ..Q:$P(^ATXAX(ATXY,0),U,15)=6
 ..Q:$P(^ATXAX(ATXY,0),U,15)=16
 ..Q:$P(^ATXAX(ATXY,0),U,15)=9999999.88
 ..S ^TMP($J,"ATXALL",ATXT,ATXY)=1
 S ATXT=""
 F  S ATXT=$O(^ATXLAB("B",ATXT)) Q:ATXT=""  D
 .S ATXY=0 F  S ATXY=$O(^ATXLAB("B",ATXT,ATXY)) Q:ATXY'=+ATXY  D
 ..S ^TMP($J,"ATXALL",ATXT,ATXY)=2
 S ATXT="" F  S ATXT=$O(^TMP($J,"ATXALL",ATXT)) Q:ATXT=""  D
 .S ATXY=0 F  S ATXY=$O(^TMP($J,"ATXALL",ATXT,ATXY)) Q:ATXY'=+ATXY  D
 ..S Z=^TMP($J,"ATXALL",ATXT,ATXY)
 ..I Z=1 S ATXFILE=$P(^ATXAX(ATXY,0),U,15),ATXDESC=$P(^ATXAX(ATXY,0),U,2),J=J+1
 ..I Z=2 S ATXFILE=60,ATXDESC=$P(^ATXLAB(ATXY,0),U,2),J=J+1
 ..S ^TMP($J,"ATXTAX",J,0)=J_")  "_ATXT
 ..I Z=1 S $E(^TMP($J,"ATXTAX",J,0),38)=$E($$VAL^XBDIQ1(9002226,ATXY,.15),1,15)
 ..I Z=2 S $E(^TMP($J,"ATXTAX",J,0),38)="LABORATORY TEST"
 ..S $E(^TMP($J,"ATXTAX",J,0),55)=ATXDESC
 ..S ^TMP($J,"ATXTAX","IDX",J,J)=ATXY_U_$S(Z'=2:"T",1:"L") ;U_ATXY
 ..S C=C+1
 .Q
 S (VALMCNT,ATXHIGH)=C
 Q
 ;
HELP ; -- help code
 S X="?" D DISP^XQORM1 W !!
 Q
 ;
EXIT ; -- exit code
 Q
 ;
EXPND ; -- expand code
 Q
 ;
BACK ;go back to listman
 D TERM^VALM0
 S VALMBCK="R"
 D INIT
 D HDR
 K DIR
 K X,Y,Z,I
 Q
 ;
DISP ;EP - add an item to the selected list - called from a protocol
 W !
 S DIR(0)="NO^1:"_ATXHIGH,DIR("A")="Which Taxonomy"
 D ^DIR K DIR S:$D(DUOUT) DIRUT=1
 I Y="" W !,"No taxonomy selected." G DISPX
 I $D(DIRUT) W !,"No taxonomy selected." G DISPX
 S ATXTAXI=$P(^TMP($J,"ATXTAX","IDX",Y,Y),U,1),ATXTAXT=$P(^TMP($J,"ATXTAX","IDX",Y,Y),U,2)
 ;BROWSE OR PRINT
 D FULL^VALM1
 W ! S DIR(0)="S^P:PRINT Taxonomy Output;B:BROWSE Taxonomy Output on Screen",DIR("A")="Do you wish to",DIR("B")="B" K DA D ^DIR K DIR
 I $D(DIRUT) D XIT Q
 S ATXLOPT=Y
 I Y="B" D BROWSE,XIT Q
ZIS ;call to XBDBQUE
 K IOP,%ZIS W !! S %ZIS="PM" D ^%ZIS
 I POP W !,"Report Aborted"
 U IO
 D PRINT
 D ^%ZISC
 X ^%ZIS("C")
 D HOME^%ZIS
 U IO
 D DISPX
 Q
BROWSE ;
 S XBRP="VIEWR^XBLM(""PRINT^ATXLTV"")"
 S XBRC="",XBRX="XIT^ATXLTV",XBIOP=0 D ^XBDBQUE
 Q
PHDR ;
 I 'ATXLPG G HEAD1
 I $E(IOST)="C",IO=IO(0) W ! S DIR(0)="EO" D ^DIR K DIR I Y=0!(Y="^")!($D(DTOUT)) S ATXLQ="" Q
HEAD1 ;
 I ATXLPG W:$D(IOF) @IOF
 S ATXLPG=ATXLPG+1
 I $G(ATXLGUI),ATXLPG'=1 W !,"ZZZZZZZ"
 W !,$P(^VA(200,DUZ,0),U,2),?72,"Page ",ATXLPG,!
 W ?(80-$L($P(^DIC(4,DUZ(2),0),U))/2),$P(^DIC(4,DUZ(2),0),U),!
 W $$CTR("Listing of the "_ATXTAXN_" taxonomy",80),!,ATXL80D,!
 Q
PRINT ;
 S ATXLPG=0
 K ATXLQ
 I ATXTAXT="L" S ATXTAXN=$P(^ATXLAB(ATXTAXI,0),U,1)
 I ATXTAXT="T" S ATXTAXN=$P(^ATXAX(ATXTAXI,0),U,1)
 S ATXL80D="-------------------------------------------------------------------------------"
 D PHDR
 I ATXTAXT'="L" S ATXLFILE=$P(^ATXAX(ATXTAXI,0),U,15)
 I ATXTAXT="L" S ATXLFILE=60
P1 K ^TMP($J,"ATXTAXDSP")
 I ATXTAXT="L" D  G P11
 .S X="" F  S X=$O(^ATXLAB(ATXTAXI,21,"B",X)) Q:X=""  D
 ..S ^TMP($J,"ATXTAXDSP",X)=""
 S F=$NA(^TMP($J,"ATXTAXDSP"))
 I $$F(ATXLFILE) D BLDTAX^ATXAPI(ATXTAXN,F,ATXTAXI,ATXTAXT) I 1
 E  S ATXLX="" F  S ATXLX=$O(^ATXAX(ATXTAXI,21,"B",ATXLX)) Q:ATXLX=""  S ^TMP($J,"ATXTAXDSP",ATXLX)=""
 S ATXLFILE=$P(^ATXAX(ATXTAXI,0),U,15)
P11 S ATXLX="" F  S ATXLX=$O(^TMP($J,"ATXTAXDSP",ATXLX)) Q:ATXLX=""  D
 .S (ATXL1,ATXL2,ATXLF,ATXL3,ATXLC2,ATXLC3)=""
 .I ATXLFILE="" S ATXL1=ATXLX S:ATXTAXN["RXNORM" ATXC1="RXNORM" S:ATXTAXN'["RXNORM" ATXC1="ITEM"
 .S ATXLC2=35,ATXLC3=65
 .I ATXLFILE=44 S ATXL1=$$GET1^DIQ(ATXLFILE,ATXLX,.01),ATXL2=$$GET1^DIQ(ATXLFILE,ATXLX,2),ATXLC2=50
 .I ATXLFILE=4 S ATXL1=$$GET1^DIQ(ATXLFILE,ATXLX,.01)
 .I ATXLFILE=9999999.18 S ATXL1=$$GET1^DIQ(ATXLFILE,ATXLX,.01)
 .I ATXLFILE=9999999.11 S ATXL1=$$GET1^DIQ(ATXLFILE,ATXLX,.01)
 .I ATXLFILE=9999999.22 S ATXL1=$$GET1^DIQ(ATXLFILE,ATXLX,.01)
 .I ATXLFILE=9999999.03 S ATXL1=$$GET1^DIQ(ATXLFILE,ATXLX,.01)
 .I ATXLFILE=9002010.03 S ATXL1=$$GET1^DIQ(ATXLFILE,ATXLX,.01),ATXL2=$$GET1^DIQ(ATXLFILE,ATXLX,.02),ATXLC2=15
 .I ATXLFILE=9999999.31 S ATXL1=$$GET1^DIQ(ATXLFILE,ATXLX,.01),ATXL2=$$GET1^DIQ(ATXLFILE,ATXLX,.02),ATXLC2=15
 .I ATXLFILE=50.68 S ATXL1=ATXLX,ATXLC2=50,Y=$O(^PSNDF(50.68,"C",ATXL1,0)) I Y S ATXL2=$$VAL^XBDIQ1(ATXLFILE,Y,.01),ATXLC2=15
 .I ATXLFILE=50.605 S ATXL1=ATXLX,ATXLC2=50,Y=$O(^PS(50.605,"B",ATXL1,0)) I Y S ATXL2=$$VAL^XBDIQ1(ATXLFILE,Y,1),ATXLC2=30
 .I ATXLFILE=7 S ATXL1=$$GET1^DIQ(ATXLFILE,ATXLX,.01),ATXLC2=50,ATXL2=$$VAL^XBDIQ1(7,ATXLX,9999999.01)
 .I ATXLFILE=200 S ATXL1=$$GET1^DIQ(ATXLFILE,ATXLX,.01),ATXLC2=50,ATXL2=$$VAL^XBDIQ1(200,ATXLX,53.5)
 .I ATXLFILE=80 S D=$$ICDDX^ICDEX(ATXLX,DT,,"I") S ATXL1=$P(D,U,2),ATXL2=$E($P(D,U,4),1,50),ATXL3=$P(D,U,20),ATXL3=$P(^ICDS(ATXL3,0),U,1),ATXLC2=15,ATXLC3=65
 .I ATXLFILE=80.1 S D=$$ICDOP^ICDEX(ATXLX,DT,,"I") S ATXL1=$P(D,U,2),ATXL2=$E($P(D,U,5),1,50),ATXL3=$P(D,U,15),ATXL3=$P(^ICDS(ATXL3,0),U,1),ATXLC2=15,ATXLC3=65
 .I ATXLFILE=81 S D=$$CPT^ICPTCOD(ATXLX) S ATXL1=$P(D,U,2),ATXL2=$P(D,U,3),ATXLC2=15
 .I ATXLFILE=50.67 S ATXL1=ATXLX,ATXL2=$O(^PSNDF(50.67,"NDC",$$STRIP^XLFSTR(ATXL1,"-"),0)) I ATXL2 S ATXL2=$$GET1^DIQ(50.67,ATXL2,4)
 .I ATXLFILE=9999999.64,ATXLX S ATXL1=$$GET1^DIQ(ATXLFILE,ATXLX,.01)
 .I ATXLFILE=9999999.64,'ATXLX S ATXL1=ATXLX
 .I ATXLFILE=9999999.09 S ATXL1=$$GET1^DIQ(ATXLFILE,ATXLX,.01),ATXL2=$$GET1^DIQ(ATXLFILE,ATXLX,1),ATXLC2=50
 .I ATXLFILE=9999999.14 S ATXL1=ATXLX S %=$O(^AUTTIMM("C",ATXLX,0)) I % S ATXL2=$$GET1^DIQ(ATXLFILE,%,.01),ATXLC2=15
 .I ATXLFILE=95.3 S ATXL1=ATXLX S %=$O(^LAB(95.3,"B",$P(ATXLX,"-"),0)) I % S ATXL2=$$GET1^DIQ(95.3,%,80),ATXLC2=15
 .I ATXL1="" D
 ..S ATXLF=".01"
 ..S ATXL1=$$GET1^DIQ(ATXLFILE,ATXLX,.01)
 .I $Y>(IOSL-3) D PHDR Q:$D(ATXLQ)
 .W ATXL1,?ATXLC2,$E(ATXL2,1,40),?ATXLC3,ATXL3,!
 D XIT
 Q
DISPX ;
 D BACK
 Q
XIT ;
 K ^TMP($J,"ATXTAXDSP")
 Q
CTR(X,Y) ;EP - Center X in a field Y wide.
 Q $J("",$S($D(Y):Y,1:IOM)-$L(X)\2)_X
 ;----------
F(F) ;
 I F="" Q 0
 I F=4 Q 0
 I F=9999999.18 Q 0
 I F=44 Q 0
 I F=50.67 Q 0
 I F=9999999.64 Q 0
 I F=95.3 Q 0
 I F=60 Q 0
 I F=9999999.14 Q 0
 I F=200 Q 0
 I F=7 Q 0
 I F=50.605 Q 0
 I F=50.68 Q 0
 I F=9999999.31 Q 0
 I F=9002010.03 Q 0
 I F=9999999.22 Q 0
 I F=9999999.11 Q 0
 I F=9999999.03 Q 0
 Q 1
