XUSBUSA2 ;GDIT/HS/BEE - Supplemental Kernel activity calls to BUSA; 11/29/2011
 ;;8.0;KERNEL;**1020**;Jan 28, 1997;Build 8
 ;
 ;This routine is custom to IHS and is not an original VHA routine. 
 ;It is being released in patch XUS*8.0*1020 as part of the suite
 ;of changes relating to 2015 CHIT certification
 ;
 Q
 ;
UCM01(USER,CLASS,RECORD) ;RECORD EVENT CODE UCM01 - USER DESIGNATED AS MEMBER OF A USER CLASS
 ;INPUT PARAMETERS:
 ; - USER   = NEW PERSON FILE (#200) IEN FOR ASSOCIATED RECORD
 ; - CLASS  = USER CLASS FILE (#8930) IEN FOR ASSOCIATED RECORD
 ; - RECORD =  USER CLASS MEMBERSHIP FILE (#8930.3) IEN FOR ASSOCIATED RECORD
 ;
 N EVENT,DESC,CLASSNM,CLASSUSR,CLASSUNM,U,CALL
 S U="^"
 S EVENT="UCM01"
 S CALL="8930.3/.02 XREF AUCM02"
 S CLASSNM=$P(^USR(8930,CLASS,0),U,1)
 S CLASSUSR=$P(^USR(8930.3,RECORD,0),U,1)
 S CLASSUNM=$$NPNAME(CLASSUSR)
 S DESC="UCM - user "_CLASSUNM_" designated user class "_CLASSNM
 D UCM(EVENT,CALL,DESC,RECORD,USER)
 Q
 ;
UCM02(USER,CLASS,RECORD) ;RECORD EVENT CODE UCM02 - USER CLASS MEMBERSHIP RECORD DELETED FOR A USER
 ;INPUT PARAMETERS:
 ; - USER   = NEW PERSON FILE (#200) IEN FOR ASSOCIATED RECORD
 ; - CLASS  = USER CLASS FILE (#8930) IEN FOR ASSOCIATED RECORD
 ; - RECORD =  USER CLASS MEMBERSHIP FILE (#8930.3) IEN FOR ASSOCIATED RECORD
 ;
 N EVENT,DESC,CLASSNM,CLASSUSR,CLASSUNM,U,CALL
 S U="^"
 S EVENT="UCM02"
 S CALL="8930.3/.02 XREF AUCM02"
 S CLASSNM=$P(^USR(8930,CLASS,0),U,1)
 S CLASSUSR=$P(^USR(8930.3,RECORD,0),U,1)
 S CLASSUNM=$$NPNAME(CLASSUSR)
 S DESC="UCM - "_CLASSUNM_"/"_CLASSNM_" record deleted"
 D UCM(EVENT,CALL,DESC,RECORD,USER)
 Q
 ;
UCM03(USER,EFFDATE,RECORD) ;RECORD EVENT CODE UCM03 - USER CLASS MEMBERSHIP EFFECTIVE DATE SET
 ;INPUT PARAMETERS:
 ; - USER     = NEW PERSON FILE (#200) IEN FOR ASSOCIATED RECORD
 ; - EFFDATE  = EFFECTIVE DATE (FILEMAN FORMAT)
 ; - RECORD   = USER CLASS MEMBERSHIP FILE (#8930.3) IEN FOR ASSOCIATED RECORD
 ;
 N EVENT,DESC,CLASS,CLASSNM,CLASSUSR,CLASSUNM,U,CALL
 S U="^"
 S EVENT="UCM03"
 S CALL="8930.3/.03 XREF AUCM03"
 S CLASS=$P(^USR(8930.3,RECORD,0),U,2)
 S CLASSNM=$P(^USR(8930,CLASS,0),U,1)
 S CLASSUSR=$P(^USR(8930.3,RECORD,0),U,1)
 S CLASSUNM=$$NPNAME(CLASSUSR)
 S DESC="UCM - "_CLASSUNM_"/"_CLASSNM_" effective date set to "_$$FDATE(EFFDATE)
 D UCM(EVENT,CALL,DESC,RECORD,USER)
 Q
 ;
UCM04(USER,EFFDATE,RECORD) ;RECORD EVENT CODE UCM04 - USER CLASS MEMBERSHIP EFFECTIVE DATE DELETED
 ;INPUT PARAMETERS:
 ; - USER     = NEW PERSON FILE (#200) IEN FOR ASSOCIATED RECORD
 ; - EFFDATE  = EFFECTIVE DATE (FILEMAN FORMAT)
 ; - RECORD   = USER CLASS MEMBERSHIP FILE (#8930.3) IEN FOR ASSOCIATED RECORD
 ;
 N EVENT,DESC,CLASS,CLASSNM,CLASSUSR,CLASSUNM,U,CALL
 S U="^"
 S EVENT="UCM04"
 S CALL="8930.3/.03 XREF AUCM03"
 S CLASS=$P(^USR(8930.3,RECORD,0),U,2)
 S CLASSNM=$P(^USR(8930,CLASS,0),U,1)
 S CLASSUSR=$P(^USR(8930.3,RECORD,0),U,1)
 S CLASSUNM=$$NPNAME(CLASSUSR)
 S DESC="UCM - "_CLASSUNM_"/"_CLASSNM_" effective date "_$$FDATE(EFFDATE)_" deleted"
 D UCM(EVENT,CALL,DESC,RECORD,USER)
 Q
 ;
UCM05(USER,EXPDATE,RECORD) ;RECORD EVENT CODE UCM05 - USER CLASS MEMBERSHIP EXPIRATION DATE SET
 ;INPUT PARAMETERS:
 ; - USER     = NEW PERSON FILE (#200) IEN FOR ASSOCIATED RECORD
 ; - EXPDATE  = EFFECTIVE DATE (FILEMAN FORMAT)
 ; - RECORD   = USER CLASS MEMBERSHIP FILE (#8930.3) IEN FOR ASSOCIATED RECORD
 ;
 N EVENT,DESC,CLASS,CLASSNM,CLASSUSR,CLASSUNM,U,CALL
 S U="^"
 S EVENT="UCM05"
 S CALL="8930.3/.04 XREF AUCM04"
 S CLASS=$P(^USR(8930.3,RECORD,0),U,2)
 S CLASSNM=$P(^USR(8930,CLASS,0),U,1)
 S CLASSUSR=$P(^USR(8930.3,RECORD,0),U,1)
 S CLASSUNM=$$NPNAME(CLASSUSR)
 S DESC="UCM - "_CLASSUNM_"/"_CLASSNM_" expiration date set to "_$$FDATE(EXPDATE)
 D UCM(EVENT,CALL,DESC,RECORD,USER)
 Q
 ;
UCM06(USER,EXPDATE,RECORD) ;RECORD EVENT CODE UCM06 - USER CLASS MEMBERSHIP EXPIRATION DATE DELETED
 ;INPUT PARAMETERS:
 ; - USER     = NEW PERSON FILE (#200) IEN FOR ASSOCIATED RECORD
 ; - EXPDATE  = EFFECTIVE DATE (FILEMAN FORMAT)
 ; - RECORD   = USER CLASS MEMBERSHIP FILE (#8930.3) IEN FOR ASSOCIATED RECORD
 ;
 N EVENT,DESC,CLASS,CLASSNM,CLASSUSR,CLASSUNM,U,CALL
 S U="^"
 S EVENT="UCM06"
 S CALL="8930.3/.04 XREF AUCM04"
 S CLASS=$P(^USR(8930.3,RECORD,0),U,2)
 S CLASSNM=$P(^USR(8930,CLASS,0),U,1)
 S CLASSUSR=$P(^USR(8930.3,RECORD,0),U,1)
 S CLASSUNM=$$NPNAME(CLASSUSR)
 S DESC="UCM - "_CLASSUNM_"/"_CLASSNM_" expiration date "_$$FDATE(EXPDATE)_" deleted"
 D UCM(EVENT,CALL,DESC,RECORD,USER)
 Q
 ;
UCM(EVENT,CALL,DESC,RECORD,USER) ;MAIN UCM EVENT BUSA FILER
 ;INPUT PARAMETERS:
 ; - EVENT  = UCM EVENT CODE
 ; - CALL   = SOURCE INITIATING THE CALL TO THIS API SET
 ; - DESC   = BASE DESCRIPTION
 ; - RECORD = ASSOCIATED USER CLASS MEMBERSHIP FILE (#8930.3) RECORD IEN
 ; - USER   = NEW PERSON FILE (#200) IEN FOR ASSOCIATED USER
 ;
 N TYPE,ACTION
 S TYPE="TYPE~UCM"
 I +$L($T(FAUD^BUSAAPI)) S ACTION="U"  ;IF BUSA V1.0 PATCH 3 IS INSTALLED, SET ACTION TO "U" (CHANGE TO USER PRIVILEGE)
 E  S ACTION=""                        ;IF NOT, LEAVE ACTION NULL
 D FILER(EVENT,ACTION,CALL,DESC,TYPE,RECORD,USER)
 Q
 ;
NP01(USER,RECORD) ;ADD OF NEW PERSON RECORD
 ; - USER   = NEW PERSON FILE (#200) IEN FOR USER INITIATING ACTION
 ; - RECORD = NEW PERSON FILE (#200) IEN FOR SOURCE-AFFECTED RECORD
 N CALL,CODE,DESC
 S CALL="200/.01 XREF ANP01"
 S CODE="NP01"
 S DESC="NEW PERSON record added - "_$$NPNAME(RECORD)
 D NP(CODE,CALL,DESC,RECORD,USER)
 Q
 ;
NP02(USER,RECORD,VALUE) ;DISUSER FLAG SET ON NEW PERSON RECORD
 ; - USER   = NEW PERSON FILE (#200) IEN FOR USER INITIATING ACTION
 ; - RECORD = NEW PERSON FILE (#200) IEN FOR SOURCE-AFFECTED RECORD
 N CALL,CODE,DESC
 S CALL="200/7 XREF ANP07"
 S CODE="NP02"
 S DESC="DISUSER field set '"_VALUE_"' for "_$$NPNAME(RECORD)
 D NP(CODE,CALL,DESC,RECORD,USER)
 Q
 ;
NP03(USER,RECORD,VALUE) ;DISUSER FLAG CLEARED ON NEW PERSON RECORD
 ; - USER   = NEW PERSON FILE (#200) IEN FOR USER INITIATING ACTION
 ; - RECORD = NEW PERSON FILE (#200) IEN FOR SOURCE-AFFECTED RECORD
 N CALL,CODE,DESC
 S CALL="200/7 XREF ANP07"
 S CODE="NP03"
 S DESC="DISUSER field value '"_VALUE_"' cleared for "_$$NPNAME(RECORD)
 D NP(CODE,CALL,DESC,RECORD,USER)
 Q
 ;
NP04(USER,RECORD,TDATE) ;TERMINATION DATE SET ON NEW PERSON RECORD
 ; - USER   = NEW PERSON FILE (#200) IEN FOR USER INITIATING ACTION
 ; - RECORD = NEW PERSON FILE (#200) IEN FOR SOURCE-AFFECTED RECORD
 N CALL,CODE,DESC
 S CALL="200/9.2 XREF ANP92"
 S CODE="NP04"
 S DESC="TERMINATION DATE "_$$FDATE(TDATE)_" set for "_$$NPNAME(RECORD)
 D NP(CODE,CALL,DESC,RECORD,USER)
 Q
 ;
NP05(USER,RECORD,TDATE) ;TERMINATION DATE DELETED ON NEW PERSON RECORD
 ; - USER   = NEW PERSON FILE (#200) IEN FOR USER INITIATING ACTION
 ; - RECORD = NEW PERSON FILE (#200) IEN FOR SOURCE-AFFECTED RECORD
 N CALL,CODE,DESC
 S CALL="200/9.2 XREF ANP92"
 S CODE="NP05"
 S DESC="TERMINATION DATE "_$$FDATE(TDATE)_" cleared for "_$$NPNAME(RECORD)
 D NP(CODE,CALL,DESC,RECORD,USER)
 Q
 ;
NP06(USER,RECORD,FLAG) ;'DELETE ALL MAIL ACCESS' SET ON NEW PERSON RECORD
 ; - USER   = NEW PERSON FILE (#200) IEN FOR USER INITIATING ACTION
 ; - RECORD = NEW PERSON FILE (#200) IEN FOR SOURCE-AFFECTED RECORD
 ; - FLAG   = VALUE SET IN DELETE ALL MAIL ACCESS FIELD (#9.21) OF NEW PERSON FILE (#200)
 N CALL,CODE,DESC
 S CALL="200/9.21 XREF ANP921"
 S CODE="NP06"
 S DESC="Mail Access Deletion flag set '"_FLAG_"' for "_$$NPNAME(RECORD)
 D NP(CODE,CALL,DESC,RECORD,USER)
 Q
 ;
NP07(USER,RECORD,FLAG) ;'DELETE ALL MAIL ACCESS' CLEARED ON NEW PERSON RECORD
 ; - USER   = NEW PERSON FILE (#200) IEN FOR USER INITIATING ACTION
 ; - RECORD = NEW PERSON FILE (#200) IEN FOR SOURCE-AFFECTED RECORD
 ; - FLAG   = VALUE SET IN DELETE ALL MAIL ACCESS FIELD (#9.21) OF NEW PERSON FILE (#200)
 N CALL,CODE,DESC
 S CALL="200/9.21 XREF ANP921"
 S CODE="NP07"
 S DESC="Mail Access Deletion flag '"_FLAG_"' cleared for "_$$NPNAME(RECORD)
 D NP(CODE,CALL,DESC,RECORD,USER)
 Q
 ;
NP08(USER,RECORD,FLAG) ;'DELETE KEYS AT TERMINATION' SET ON NEW PERSON RECORD
 ; - USER   = NEW PERSON FILE (#200) IEN FOR USER INITIATING ACTION
 ; - RECORD = NEW PERSON FILE (#200) IEN FOR SOURCE-AFFECTED RECORD
 ; - FLAG   = VALUE SET IN DELETE KEYS AT TERMINATION FIELD (#9.22) OF NEW PERSON FILE (#200)
 N CALL,CODE,DESC
 S CALL="200/9.22 XREF ANP922"
 S CODE="NP08"
 S DESC="Key Deletion flag set '"_FLAG_"' for "_$$NPNAME(RECORD)
 D NP(CODE,CALL,DESC,RECORD,USER)
 Q
 ;
NP09(USER,RECORD,FLAG) ;'DELETE KEYS AT TERMINATION' CLEARED ON NEW PERSON RECORD
 ; - USER   = NEW PERSON FILE (#200) IEN FOR USER INITIATING ACTION
 ; - RECORD = NEW PERSON FILE (#200) IEN FOR SOURCE-AFFECTED RECORD
 ; - FLAG   = VALUE SET IN DELETE KEYS AT TERMINATION FIELD (#9.22) OF NEW PERSON FILE (#200)
 N CALL,CODE,DESC
 S CALL="200/9.22 XREF ANP922"
 S CODE="NP09"
 S DESC="Key Deletion flag '"_FLAG_"' cleared for "_$$NPNAME(RECORD)
 D NP(CODE,CALL,DESC,RECORD,USER)
 Q
 ;
NP10(USER,RECORD,VALUE) ;'Termination Reason' SET ON NEW PERSON RECORD
 ; - USER   = NEW PERSON FILE (#200) IEN FOR USER INITIATING ACTION
 ; - RECORD = NEW PERSON FILE (#200) IEN FOR SOURCE-AFFECTED RECORD
 ; - VALUE  = TEXT ENTERED IN Termination Reason FIELD (#9.4) OF NEW PERSON FILE (#200)
 N CALL,CODE,DESC
 S CALL="200/9.4 XREF ANP94"
 S CODE="NP10"
 S DESC="Termination Reason '"_VALUE_"' set for "_$$NPNAME(RECORD)
 D NP(CODE,CALL,DESC,RECORD,USER)
 Q
 ;
NP11(USER,RECORD,VALUE) ;'Termination Reason' CLEARED ON NEW PERSON RECORD
 ; - USER   = NEW PERSON FILE (#200) IEN FOR USER INITIATING ACTION
 ; - RECORD = NEW PERSON FILE (#200) IEN FOR SOURCE-AFFECTED RECORD
 ; - VALUE  = TEXT ENTERED IN Termination Reason FIELD (#9.4) OF NEW PERSON FILE (#200)
 N CALL,CODE,DESC
 S CALL="200/9.4 XREF ANP94"
 S CODE="NP11"
 S DESC="Termination Reason '"_VALUE_"' cleared for "_$$NPNAME(RECORD)
 D NP(CODE,CALL,DESC,RECORD,USER)
 Q
 ;
NP(CODE,CALL,DESC,RECORD,USER) ;MAIN NEW PERSON EVENT BUSA FILER
 ;INPUT PARAMETERS:
 ; - CODE   = NEW PERSON EVENT CODE
 ; - CALL   = SOURCE INITIATING THE CALL TO THIS API SET
 ; - DESC   = BASE DESCRIPTION
 ; - RECORD = NEW PERSON FILE (#200) IEN FOR SOURCE-AFFECTED RECORD
 ; - USER   = NEW PERSON FILE (#200) IEN FOR USER INITIATING ACTION
 ;
 N TYPE,ACTION
 S TYPE="TYPE~NP"
 I +$L($T(FAUD^BUSAAPI)) S ACTION="U"  ;IF BUSA V1.0 PATCH 3 IS INSTALLED, SET ACTION TO "U" (CHANGE TO USER PRIVILEGE)
 E  S ACTION=""                        ;IF NOT, LEAVE ACTION NULL
 D FILER(CODE,ACTION,CALL,DESC,TYPE,RECORD,USER)
 Q
 ;
FILER(EVENT,ACTION,CALL,DESC,TYPE,RECORD,USER) ;ASSEMBLE CALL PARAMETERS AND SEND TO KERNEL'S BUSA FILER
 N DO,DD  ;ADDED TO AVOID BUSA CAUSING PROBLEMS WITH NESTED FILE^DICN CALLS FURTHER DOWNSTREAM
 N CALLTYPE,CAT,FS,NAMESP,RESULT
 S CALLTYPE="A"  ;API call
 S CAT="S"  ;System event
 S FS="|"  ;Description's internal field separator
 S NAMESP="XU"
 S RESULT="RSLT~S"  ;Success assumed if FileMan executes the MUMPS cross-references
 ;Assemble full description:
 ;"|"-piece 1 = Base description
 ;"|"-piece 2 = Type
 ;"|"-piece 3 = Result
 ;"|"-piece 7 = Event Code
 S $P(DESC,FS,2)=TYPE
 S $P(DESC,FS,3)=RESULT
 S $P(DESC,FS,4)=NAMESP
 S $P(DESC,FS,7)=EVENT
 D LOG^XUSBUSA(TYPE,CAT,ACTION,CALL,DESC,"",USER)
 Q
 ;
FDATE(DATE) ;FORMAT FILEMAN DATE FOR MM/DD/YYYY OUTPUT
 N PRDATE
 S PRDATE=$E(DATE,4,5)_"/"_$E(DATE,6,7)_"/"_(1700+$E(DATE,1,3))
 Q PRDATE
 ;
NPNAME(RECORD) ;RETURN PRINTABLE NAME ASSOCIATED WITH SPECIFIED NEW PERSON FILE (#200) POINTER
 N NAME
 S NAME=$P(^VA(200,RECORD,0),U,1)
 Q NAME
