%ZTER1 ;ISC-SF.SEA/JLI - ERROR TRAP TO LOG ERRORS (VAX LOCAL SYMBOL TABLE) ;03/27/2003  12:26
 ;;8.0;KERNEL;**18,24,36,49,112,162,275**;JUL 10, 1995
VXD ;Record VAX DSM variables
 S @%ZTERRT@("J")=$J_"^"_$ZC(%GETJPI,0,"PRCNAM")_"^"_$ZC(%GETJPI,0,"USERNAME")_"^"_%ZTER11I_"^"_$ZC(%SYSFAO,"!XL",$J),@%ZTERRT@("I")=$IO_"^"_$ZA_"^"_$ZB_"^"_$ZIO K %ZTER11I
 S @%ZTERRT@("ZH")=$TR($ZH,",","^")
 S %ZTER111="%" F  D  S %ZTER111=$ZSORT(@%ZTER111) Q:%ZTER111=""  ;Code from DEC
 . Q:$E(%ZTER111,1,5)="%ZTER"
 . I $D(@%ZTER111)#2 D VNXT2
 . I $D(@%ZTER111)>9 D VNXT3
 . Q
 Q
 ;
VNXT2 S %ZTERCNT=%ZTERCNT+1,@%ZTERRT@("ZV",%ZTERCNT,0)=%ZTER111,^("D")=$E(@%ZTER111,1,255)
 Q
VNXT3 S %ZTER11Q=%ZTER111
 F  S %ZTER11Q=$Q(@%ZTER11Q) Q:%ZTER11Q=""  S %ZTERCNT=%ZTERCNT+1,@%ZTERRT@("ZV",%ZTERCNT,0)=%ZTER11Q,^("D")=$E(@%ZTER11Q,1,255)
 Q
 ;
STACK ;Record the new $STACK variable
 I $ECODE]"" S $ZE=""
 N %ZTER35 S %ZTER35=$S($D(^TMP("$ZE",$J,2)):^(2),1:$ETRAP)
 S %ZTERCNT=%ZTERCNT+1,@%ZTERRT@("ZV",%ZTERCNT,0)="$ECODE",^("D")=$E($ECODE,1,255)
 S %ZTERCNT=%ZTERCNT+1,@%ZTERRT@("ZV",%ZTERCNT,0)="$ESTACK",^("D")=$ESTACK
 S %ZTERCNT=%ZTERCNT+1,@%ZTERRT@("ZV",%ZTERCNT,0)="$ETRAP",^("D")=%ZTER35
 S %ZTERCNT=%ZTERCNT+1,@%ZTERRT@("ZV",%ZTERCNT,0)="$STACK",^("D")=$STACK
 S %ZTERCNT=%ZTERCNT+1,@%ZTERRT@("ZV",%ZTERCNT,0)="$QUIT",^("D")=$QUIT
 N %,%1,%2 S %2=$ST
 F %=0:1:$ST S %1=$E(1000+%,2,4) Q:$ST(%,"PLACE")["^%ZTER"  D
 . S %ZTERCNT=%ZTERCNT+1,@%ZTERRT@("ZV",%ZTERCNT,0)="$STACK("_%1_")",^("D")=$STACK(%)
 . S %ZTERCNT=%ZTERCNT+1,@%ZTERRT@("ZV",%ZTERCNT,0)="$STACK("_%1_",""ECODE"")",^("D")=$STACK(%,"ECODE")
 . S %ZTERCNT=%ZTERCNT+1,@%ZTERRT@("ZV",%ZTERCNT,0)="$STACK("_%1_",""PLACE"")",^("D")=$STACK(%,"PLACE")
 . S %ZTERCNT=%ZTERCNT+1,@%ZTERRT@("ZV",%ZTERCNT,0)="$STACK("_%1_",""MCODE"")",^("D")=$STACK(%,"MCODE")
 . S:$STACK(%,"ECODE")]"" %2=%
 S @%ZTERRT@("LINE")=$STACK(%2,"MCODE")
 S $ECODE=""
 Q
 ;
VERR ;
 S @%ZTERRT@("ZE2")="%DSM-E-ET, Error occurred in %ZTER, "_$ECODE
 HALT
