ADE6P373 ;IHS/OIT/GAB - ADE V6.0 PATCH 37 [ 12/06/2022 10:51 AM ]
 ;;6.0;ADE IHS DENTAL;**37**;March 25, 1999;Build 6
 ;IHS/OIT/GAB 12/2022 Patch 37 ADA-CDT code updates for 2023
 ;Deactivated ADA-CDT Codes - 2 deactivated codes
 ;
DELCDT37 ;EP
 D DELETES^ADEUPD37("DELADA^ADE6P373","SETX^ADE6P373","^AUTTADA(")
 Q
 ;
SETX ;EP
 S ADEX=$P($P(ADEX,U),"D",2),ADEX=$O(^AUTTADA("B",ADEX,""))
 Q
 ;
DELADA ;  CODE & NOMENCLATURE
 ;;D0351^3D PHOTOGRAPHIC IMAGE
 ;;D0704^3-D PHOTOGRAPHIC IMAGE - IMAGE CAPTURE ONLY
 ;;***END***
MODADA ;
 Q
ZAPINA ;REMOVE INACTIVE DATE
 ;/IHS/OIT/GAB COMMENTED OUT NEXT THREE LINES, NO REACTIVATED CODES
 ;S ADEIRN=""
 ;S ADEIRN=$O(^AUTTADA("B","0191",0)) I +ADEIRN D ZAPIT
 ;S ADEIRN=$O(^AUTTADA("B","1208",0)) I +ADEIRN D ZAPIT
 Q
ZAPIT ;
 ;/IHS/OIT/GAB COMMENTED OUT BELOW - NO REACTIVATED CODES
 ;S DIE="^AUTTADA(",DA=ADEIRN
 ;S DR=".08////@" D ^DIE
 ;S ADEIRN=""
 Q
ZAP K D,DA,DR,DIE,D0,DIC,ADEIRN
 Q
