ADE6P353 ;IHS/OIT/GAB - ADE V6.0 PATCH 35 [ 11/22/2020  10:51 AM ]
 ;;6.0;ADE*6.0*35;;March 25, 1999;Build 82
 ;IHS/OIT/GAB 11/2020 Patch 35 ADA-CDT code updates for 2021
 ;Deactivated ADA-CDT Codes
 ;
DELCDT35 ;EP
 D DELETES^ADEUPD35("DELADA^ADE6P353","SETX^ADE6P353","^AUTTADA(")
 Q
 ;
SETX ;EP
 S ADEX=$P($P(ADEX,U),"D",2),ADEX=$O(^AUTTADA("B",ADEX,""))
 Q
 ;
DELADA ;  CODE & NOMENCLATURE
 ;;D3427^PERIRADICULAR SURGERY WITHOUT APICOECTOMY
 ;;D5994^PERIODONTAL MEDICAMENT CARRIER WITH PERIPHER
 ;;D6052^SEMI-PRECISION ATTACHMENT ABUTMENT
 ;;D7960^FRENULECTOMY - ALSO KNOWN AS FRENECTOMY OR F
 ;;***END***
MODADA ;
 Q
ZAPINA ;REMOVE INACTIVE DATE
 ;/IHS/OIT/GAB COMMENTED OUT NEXT THREE LINES, NO REACTIVATED CODES
 ;S ADEIRN=""
 ;S ADEIRN=$O(^AUTTADA("B","0191",0)) I +ADEIRN D ZAPIT
 ;S ADEIRN=$O(^AUTTADA("B","1208",0)) I +ADEIRN D ZAPIT
 Q
ZAPIT ;
 ;/IHS/OIT/GAB COMMENTED OUT BELOW - NO REACTIVATED CODES
 ;S DIE="^AUTTADA(",DA=ADEIRN
 ;S DR=".08////@" D ^DIE
 ;S ADEIRN=""
 Q
ZAP K D,DA,DR,DIE,D0,DIC,ADEIRN
 Q
