ADERVW1 ; IHS/HQT/MJL  - DENTAL CHART REVIEW PT 3 ;  [ 03/24/1999   9:04 AM ]
 ;;6.0;ADE;**38,39**;MAR 25, 1999;Build 7
 ;;IHS/OIT/GAB 11.2022 File 3,6,16 Removal - ADE Patch 38
 ;;IHS/GDIT/AEF 7.2023 Use V Dental file rather than Dental Procedure file - ADE Patch 39
 ;Q:'$D(^ADEPCD("DATE",ADEPAT))
 ;X ADECKP Q:$D(APCHSQIT)  X:'APCHSNPG ADEBRK
 ;I '$D(^ADEPCD("DATE",ADEPAT)) S ADETXT="<No Services on Record>",ADENRQ="",ADEICL=0 X ADEPRT Q   ;/IHS/GDIT/AEF PATCH 39 COMMENTED OUT LINE REPLACED BY LINE BELOW
 I '$D(^AUPNVDEN("AC",ADEPAT)) S ADETXT="<No Services on Record>",ADENRQ="",ADEICL=0 X ADEPRT Q   ;IHS/GDIT/AEF PATCH 39 MODIFIED CODE TO USE V DENTAL FILE
 S ADETXT="SERVICES PROVIDED: ",ADENRQ="",ADEICL=20 X ADEPRT
 K ^ADEUTL("DENTAA",$J)
 S ADEDAT=(9999999-ADEDLM)-1
 ;BEGIN PATCH 39 MODS REWRITE CODE IHS/GDIT/AEF
 ;COMMENTED OUT BELOW LINE REPLACED BY LINES BELOW IHS/GDIT/AEF
 ;F ADEQ=0:0 S ADEDAT=$O(^ADEPCD("DATE",ADEPAT,ADEDAT)) Q:'ADEDAT  S ADEDFN="" F ADEQ=0:0 S ADEDFN=$O(^ADEPCD("DATE",ADEPAT,ADEDAT,ADEDFN)) Q:'ADEDFN  S ^ADEUTL("DENTAA",$J,ADEPAT,9999999-(ADEDAT\1),ADEDFN)=""
 ;
 ;Build scratch global:
 S ADEDFN=0 F  S ADEDFN=$O(^AUPNVDEN("AC",ADEPAT,ADEDFN)) Q:'ADEDFN  D
 . S ADEDAT=$P($G(^AUPNVDEN(ADEDFN,0)),U,3)
 . I ADEDAT S ADEDAT=$P($G(^AUPNVSIT(ADEDAT,0)),U)
 . S ^ADEUTL("DENTAA",$J,ADEPAT,9999999-(ADEDAT\1),ADEDFN)=""
 ;
 ;Loop through scratch global ADEDAT subscript:
 S ADENDMS=ADENDM
 S ADEODT=""
 S ADEDAT="" F  S ADEDAT=$O(^ADEUTL("DENTAA",$J,ADEPAT,ADEDAT)) Q:ADEDAT=""!(ADEDAT>ADEDLM)!(ADENDMS<1)  S Y=-ADEDAT+9999999 X ADECVD S ADEDTD=Y S ADEDTU=0 D  Q:$D(APCHSQIT)  S ADENDMS=ADENDMS-1
 . D ONEDATE
 ;
 ;Clean up:
 D DENTALX
 Q
ONEDATE ;
 ;Loop thru scratch global ADEDFN subscript: 
 S ADEDFN="" F  S ADEDFN=$O(^ADEUTL("DENTAA",$J,ADEPAT,ADEDAT,ADEDFN)) Q:ADEDFN=""  D  Q:$D(APCHSQIT)
 . D DNTCHK
 Q
DNTCHK ;
 ;Check if should quit, set site variables:
 S ADESITE=""
 S ADESITE=$P($G(^AUPNVDEN(ADEDFN,0)),U,3)
 I ADESITE S ADESITE=$P($G(^AUPNVSIT(ADESITE,0)),U,6)
 I '$D(ADENSH) D GETSITE^ADERVW0
 X ADECKP Q:$D(APCHSQIT)  S:APCHSNPG ADEDTU=0
 I 'ADEDTU S ADEFO=""
 I ADENSH=ADEFO S ADESFN=""
 E  S (ADESFN,ADEFO)=ADENSH
 I ADEDTD'=ADEODT D
 . W ADEDTD_"   "_ADESFN,!
 . S ADEODT=ADEDTD
 D DSVC
 Q
DSVC ;
 ;Check if should quit, call code to print data:
 X ADECKP Q:$D(APCHSQIT)  W:APCHSNPG !,ADEDTD,?10,ADESFN," (Cont'd)",!
 D MOD0
 D LINE
 Q
MOD0 ;
 ;Set ADETXT variable to print:
 S ADEOP=$P($G(^AUPNVDEN(ADEDFN,0)),U,5) ;OPERATIVE SITE
 I ADEOP S ADEOP=$P($G(^ADEOPS(ADEOP,88)),U) ;OPERATIVE SITE MNEMONIC
 S ADESFC=$P($G(^AUPNVDEN(ADEDFN,0)),U,6) ;TOOTH SURFACE
 I ADESFC]"" S ADESFC="["_ADESFC_"]"
 S ADECOD=$P($G(^AUPNVDEN(ADEDFN,0)),U)
 I ADECOD S ADECODE=$P(^AUTTADA(ADECOD,0),U)
 S ADEDESC=$P(^AUTTADA(ADECOD,0),U,6)
 S ADEPROV=$P($G(^AUPNVDEN(ADEDFN,12)),U,4)
 I ADEPROV S ADEPROV=$P(^VA(200,ADEPROV,0),U)
 S X=""
 S $E(X,1,5)=ADECODE
 S $E(X,8,22)=$E(ADEDESC,1,20)
 S $E(X,25,27)=ADEOP
 S $E(X,29,35)=ADESFC
 S $E(X,38,57)=$E(ADEPROV,1,20)
 S ADETXT=X
 Q
LINE ;
 ;Print the line of data:
 S ADEFLG=0
 X ADECKP Q:$D(APCHSQIT)  W:APCHSNPG !,ADEDTD,?10,ADESFN," (Cont'd)",!
 S ADEICL=$S(ADEFLG:35,1:4),ADENRQ="" X ADEPRT
 Q
DENTALX ;
 ;Clean up:
 K ADETXT,ADENRQ,ADEICL,ADEDAT,ADEDFN,ADENDMS,ADEODT,Y,ADEDTD,ADETU,ADESITE
 K ADEFO,ADEOP,ADESFC,ADECOD,ADECODE,ADEDESC,ADEPROV,XADEFLG
 K ADECKP,ADECVD,ADEDLM,ADEDTU,ADEFLG,ADENDM,ADENSH,ADEPAT,ADEPRT,ADESFN
 K APCHSNPG,APCHSQIT,X
 K ^ADEUTL("DENTAA",$J)
 Q
 ;END PATCH 39 MODS REWRITE CODE IHS/GDIT/AEF
