AMEREDPV ; GDIT/HS/BEE - Edit AMER provider related fields 
 ;;3.0;ER VISIT SYSTEM;**13**;MAR 03, 2009;Build 36
 ;
 Q
 ;
PROV(PTYPE,AMERVSIT,AMERAIEN) ;Update nurse/provider indicated
 ;
 I $G(PTYPE)="" Q 0
 I +AMERVSIT=0 Q 0
 ;
 NEW PN,PABBV,PFIELD,PTFIELD,CPROV,DIC,PKEY,AMERNEW,AMEROLD,Y,X,AMERSKIP,DIR
 NEW AMEREDTS,AMERSTRG,DR,AMERSKIP,AUPNVSIT,DNURSE,DPROV
 S (AMEROLD,AMERNEW,AMEREDTS,AMERSTRG,DR)=""
 ;
 Q:'$D(^XUSEC("AMERZ9999",DUZ)) $$ERSEDTT^AMEREDTT(AMERVSIT,AMERAIEN)  ; PROGRAMATICALLY locking fields that pass to PCC
 ;
 S AMERSKIP=0
 S AUPNVSIT=$$GET1^DIQ(9009080,AMERVSIT_",",.03,"I")
