ACHSEOB0 ; IHS/ITSC/TPF/PMF - CONTINUATION OF ACHSEOB ;  
 ;;3.1;CONTRACT HEALTH MGMT SYSTEM;**28**;JUN 11, 2001;Build 86
 ;
REPORT ;EP
 S ACHSERPT=$$DIR^XBDIR("S^N:NO REPORT;S:SUMMARY REPORT - Total # of EOBR's by Facility;D:DETAILED REPORT - Listing of each EOBR plus Summary Report","Enter Type Of Report To Print","SUMMARY")
 Q:$D(DUOUT)!$D(DTOUT)!(ACHSERPT="N")
 W !!
 K %ZIS
 S %ZIS="OP",%ZIS("A")="Enter Printer For Report:"
 D ^%ZIS
 K %ZIS
 I POP S ACHSQUIT=1 D HOME^%ZIS Q     ;ACHS*3.1*28 ADDED ACHSQUIT
 S:$D(IO("Q")) ACHSIO("Q")=IO("Q")
 S ZTIO=ION_";"_IOST_";"_IOM_";"_IOSL
 D HOME^%ZIS
 U IO
 Q
 ;
