ACHSAI ; IHS/ITSC/PMF - GENERATE INITIAL CHS DOCUMENTS ;  [ 10/16/2001   8:16 AM ]
 ;;3.1;CONTRACT HEALTH MGMT SYSTEM;**32**;JUN 11, 2001;Build 39
 ;ACHS*3.1*32 6.20.24 IHS.OIT.FCJ ADD MED PRI VAR;TEST FOR ACTIVE EXPORT/EOBR JOBS
 ;
 ;CALLED FROM OPTION [ACHSAI]
A1 ;
 I $$MENU^ACHSJCHK() Q  ;ACHS*3.1*32 TEST FOR ACTIVE EXPORT/EOBR JOBS
 S (ACHSTYP,ACHSPROV,ACHSCONP,ACHSCAN,ACHSSCC,ACHSCOPT,ACHSESDA,ACHSESDO,ACHSFDT,ACHSTDT,ACHSHON,ACHSHONN,ACHSEDOS,ACHSRMP)=""
 S (ACHSORDN,ACHSDES,ACHSRALR,ACHSRCOI,ACHSRDXN,ACHSRMPC,ACHSRPHY,ACHSRPXN,ACHSRECT,ACHSRDXN,ACHSSVDT,ACHSWKLD,ACHSDEST,ACHSDCR,ACHSAGRP,ACHSAGRN)=""
 K DFN,ACHSRDX,ACHSRPX,ACHSREF
 D ^ACHSA                      ;ENTER DOCUMENTS (1/8)
 I '$D(DUOUT),'$D(DTOUT) G A1
 D EN^XBVK("ACHS"),^ACHSVAR
 K DUOUT,DTOUT ; 3*17  6/12/00  PMF
 Q
 ;
