ACHSZZ03 ; IHS/ADC/DJM - FIX DB CHR<-->RCIS ; [ 03/12/1999  2:05 PM ]
 ;;3.0;CONTRACT HEALTH MGMT SYSTEM;**2**;
 ;;ACHS*3*2 FIX CHS/RCIS POINTER PROBLEM
 K ^ACHSZZ03
 S U="^"
 S RIEN=0,ECNT=0
 F  S RIEN=$O(^BMCREF(RIEN)) Q:RIEN'=+RIEN  D
 . ;GET THE RCIS PATIENT DEMOGRAPHICS
 . S BMCR=$P(^BMCREF(RIEN,0),U,1)    ;.01
 . S BMCRNUM=$P(^BMCREF(RIEN,0),U,2) ;.02
 . S BMCRPAT=$P(^BMCREF(RIEN,0),U,3) ;.03
 . S RCIEN=0,EFLG=0
 . F  S RCIEN=$O(^BMCREF(RIEN,41,RCIEN)) Q:RCIEN'=+RCIEN  D
 . . ;DO WE HAVE A CHS ENTRY?
 . . I '$D(^ACHSF(DUZ(2),"D",RCIEN)) D  Q  ;NO FURTHUR CHECKS ALLOWED
 . . . S EFLG=1,^ACHSZZ03("MISSING.PO",RCIEN,RIEN)=""
 . . . S ^ACHSZZ03("DELETE",RCIEN,RIEN)=""
 . . . S ^ACHSZZ03("PO",RCIEN,RIEN)=""
 . . ;GET THE CHS PATIENT IEN
 . . S ACHSPAT=$P(^ACHSF(DUZ(2),"D",RCIEN,0),U,22)
 . . ;DO WE HAVA A CHS LINK VALUE (IEN OF REFERRAL)
 . . I '$D(^ACHSF(DUZ(2),"D",RCIEN,2)) D  Q  ;NO FURTHUR CHECKS ALLOWED
 . . . S EFLG=1,^ACHSZZ03("MISSING.LINK",RCIEN,RIEN)=""
 . . . S ^ACHSZZ03("DELETE",RCIEN,RIEN)=""
 . . . S ^ACHSZZ03("PO",RCIEN,RIEN)=""
 . . ;GET THE CHS LINK TO RCIS
 . . S ACHSRIEN=$P(^ACHSF(DUZ(2),"D",RCIEN,2),U,7)
 . . I ACHSRIEN="" D  ; NO BACK POINTER FROM CHS TO REFERRAL
 . . . S EFLG=1,^ACHSZZ03("DELETE",RCIEN,RIEN)=""
 . . ;DOES CHS POINT TO THE CORRECT REFERRAL?
 . . I ACHSPAT=BMCRPAT D
 . . . I $D(^ACHSZZ03("DUP",RCIEN)) D  Q
 . . . . S ^ACHSZZ03("DUP",RCIEN,RIEN)=""
 . . . I $D(^ACHSZZ03("OK",RCIEN)) D  Q
 . . . . S ^ACHSZZ03("DUP",RCIEN,RIEN)=""
 . . . . M ^ACHSZZ03("DUP",RCIEN)=^ACHSZZ03("OK",RCIEN)
 . . . . K ^ACHSZZ03("OK",RCIEN)
 . . . S ^ACHSZZ03("OK",RCIEN,RIEN)=""
 . . I RIEN'=ACHSRIEN D
 . . . S EFLG=1
 . . . S ^ACHSZZ03("PO",RCIEN,RIEN)=""
 . . . S:ACHSRIEN]"" ^ACHSZZ03("PO",RCIEN,ACHSRIEN)=""
 . . . S ^ACHSZZ03("R",RIEN,RCIEN)=""
 . . . S:ACHSRIEN]"" ^ACHSZZ03("R",ACHSRIEN,RCIEN)=""
 . I EFLG S ECNT=ECNT+1
 S ^ACHSZZ03("ECNT")=ECNT
 W !,"ERRORS FOUND: ",ECNT
 QUIT
FIX ;FIX THE ^ACHSF AND ^BMCREF,^BMCDX,^BMCPX DATABASES
 ;
 ; OK -- HERE IS THE PLAN:
 ;
 ;   1) DELETE ALL BAD PO'S FROM THE REFERRALS
 ;   2) REPOINT RCIS DX&PX TO THE CORRECT REFERRAL
 ;   3) FIX THE CHS PO REFERRAL POINTER
 ;   4) USE AUTH^ACHSBMC TO UPDATE REFERRALS W/ CORRECT DOLLARS
 ;   5) DELETE STRAY POINTERS FROM RCIS TO CHS PO'S
 ;
 S U="^"
 R !,"START WITH PO#: ",CIEN S CIEN=$O(^ACHSZZ03("PO",CIEN),-1)
 F  S CIEN=$O(^ACHSZZ03("PO",CIEN)) Q:CIEN=""  D
 . I $D(^ACHSZZ03("FIXED",CIEN)) Q  ; ALREADY FIXED
 . I $$ASK("DO FIXES FOR "_CIEN)="Y" D  ; YES FIX THIS ONE
 . . D RDELPO(CIEN)  ; STEP 1
 . . D TSTDXPX(CIEN) ; STEP 2
 . . D FIXRIEN(CIEN) ; STEP 3
 . . D FIXAUTH(CIEN) ; STEP 4
 . . D DELETE(CIEN)  ; STEP 5
 . . S ^ACHSZZ03("FIXED",CIEN)=""
 QUIT
RDELPO(CIEN)       ;PHASE 1 CLEAN UP, REMOVE ALL MISS LINKED PO'S
 ; FROM THE RCIS DATABASE
 ;
 ; CIEN = CHS PO IEN
 S RIEN=""
 F  S RIEN=$O(^ACHSZZ03("PO",CIEN,RIEN)) Q:RIEN=""  D
 . D AUTH^BMCCHS(RIEN,CIEN,"D")
 QUIT
TSTDXPX(CIEN)      ;PHASE 2 CORRECT THE DX & PX ITEMS
 ; TEST THE DX AND PX ENTRIES FOR CORRECTNESS
 ;
 ; CIEN = CHS PO IEN
 ;
 S ACHSPAT=$P(^ACHSF(DUZ(2),"D",CIEN,0),U,22)
 S BMCRIEN=$O(^ACHSZZ03("OK",CIEN,"")) ; CORRECT REFERRAL
 I BMCRIEN="" D  Q  ; PANIC, THERE IS NO CORRECT REFERRAL LOGGED
 . S ^ACHSZZ03("PANIC",CIEN)=""
 . W !,"***** PANIC: ",CIEN," DOES NOT HAVE A CORRECT REFERRAL"
 S WRIEN=""
 F  S WRIEN=$O(^ACHSZZ03("PO",CIEN,WRIEN)) Q:WRIEN=""  D
 . I $D(^ACHSZZ03("OK",CIEN,WRIEN)) Q        ; DOES NOT NEED FIXING
 . I $D(^ACHSZZ03("FIXED.DX",CIEN,WRIEN)) Q  ; FIXED
 . I $D(^ACHSZZ03("FIXED.PX",CIEN,WRIEN)) Q  ; FIXED
 . D FIXDXPX(CIEN,WRIEN,BMCRIEN,ACHSPAT)
 QUIT
FIXDXPX(CIEN,WRIEN,RIEN,CPAT)      ;
 ; OK ... THIS IS THE PLAN FOR THE DX'S AND PX'S
 ; JUST RESET THE ^BMCDX(DXIEN,0) POINTER AND THE ^BMCPX(PXIEN,0)
 ; POINTER.
 ;
 ; CIEN = CHS PO IEN
 ; WRIEN = WRONG REFERRAL IEN
 ; RIEN  = CORRECT REFERRAL IEN
 ; CPAT  = CHS PATIENT IEN
 ;
 ; FIX THE ^BMCDX GLOBAL (PATIENT DIAGNOSIS'S)
 S DXIEN=""
 F  S DXIEN=$O(^BMCDX("AD",WRIEN,DXIEN)) Q:DXIEN=""  D
 . S DXPAT=$P(^BMCDX(DXIEN,0),U,2) Q:CPAT'=DXPAT
 . S ^ACHSZZ03("FIXED.DX",CIEN,DXIEN)=WRIEN_U_RIEN
 . S ^BMCDX("AD",RIEN,DXIEN)="" ; CORRECT THE XREF
 . K ^BMCDX("AD",WRIEN,DXIEN)   ; REMOVE THE WRONG XREF
 . S $P(^BMCDX(DXIEN,0),U,3)=RIEN ; CORRECT THE REFERRAL LINK
 ;
 ; FIX THE ^BMCPX GLOBAL (PATIENT PROCEDURES'S)
 S PXIEN=""
 F  S PXIEN=$O(^BMCPX("AD",WRIEN,PXIEN)) Q:PXIEN=""  D
 . S PXPAT=$P(^BMCPX(PXIEN,0),U,2) Q:CPAT'=PXPAT
 . S ^ACHSZZ03("FIXED.PX",CIEN,PXIEN)=WRIEN_U_RIEN
 . S ^BMCPX("AD",RIEN,PXIEN)="" ; CORRECT THE XREF
 . K ^BMCPX("AD",WRIEN,PXIEN)   ; REMOVE THE WRONG XREF
 . S $P(^BMCPX(PXIEN,0),U,3)=RIEN ; CORRECT THE REFERRAL LINK
 QUIT
FIXRIEN(CIEN)      ;PHASE 3 FIX THE CHS TO RCIS LINK
 S RIEN=$O(^ACHSZZ03("OK",CIEN,""))
 I RIEN="" D  Q  ; PANIC, NO CORRECT REFERRAL LOGGED
 . S ^ACHSZZ03("PANIC",CIEN)=""
 . W !,"***** PANIC: ",CIEN," DOES NOT HAVE A CORRECT REFERRAL"
 S $P(^ACHSF(DUZ(2),"D",CIEN,2),U,7)=RIEN
 S ^ACHSZZ03("FIXED",CIEN)=""
 QUIT
FIXAUTH(CIEN)      ;PHASE 4 FIX THE AUTHORIZATION DOLLARS
 S ACHSREF=$O(^ACHSZZ03("OK",CIEN,""))
 S ACHSDIEN=CIEN
 D AUTH^ACHSBMC
 QUIT
DELETE(CIEN)       ;PHASE 5 DELETE STRAY RCIS PO POINTERS
 I '$D(^ACHSZZ03("DELETE",CIEN)) Q  ; NOT A STRAY POINTER
 S RIEN=""
 F  S RIEN=$O(^ACHSZZ03("DELETE",CIEN,RIEN)) Q:RIEN=""  D
 . D AUTH^BMCCHS(RIEN,CIEN,"D")
 QUIT
ASK(MSG) ;YES/NO PROMPTING
 I $G(ANS)="ALL" Q "Y" ; DO THEM ALL
 F  W !,MSG R ": ",ANS Q:ANS?1(1"Y",1"N",1"ALL")
 I ANS="ALL" Q "Y"
 Q ANS
