ACHSNEW ; IHS/ITSC/PMF - SET UP A NEW FISCAL YEAR FOR A FACILITY ;   [ 10/16/2001   8:16 AM ]
 ;;3.1;CONTRACT HEALTH MGMT SYSTEM;**28,29**;JUN 11, 2001;Build 86
 ;ACHS*3.1*28 11.19.2019 IHS.OIT.FCJ MOD TO CLEAN UP EOBR ERROR FILE
 ;ACHS*3.1*29 7.1.2021 IHS.OIT.FCJ ADD EP FOR EOBR AND NEW FY CAN SETUP
 ;
 S ACHS("SETNEW")=""
 D ^ACHSVAR
 I $D(ACHSXQT) G K
 D FY^ACHSUF,C0SUB^ACHSUF
 I $D(ACHSERR),ACHSERR=1 G GLOBERR^ACHSUF
 S ACHS("FYX")=$O(ACHSFYWK(DUZ(2),9999),-1)
 S ACHS("ACWKX")=ACHSFYWK(DUZ(2),ACHS("FYX"))
 G GLOBERR^ACHSUF:'$D(^ACHS(9,DUZ(2),"FY",ACHS("FYX"),"W",ACHS("ACWKX")))
BD ;
 W !!,"Which fiscal year? ("
 S ACHS("YR")=1700+$E(DT,1,3)
 W ACHS("YR")-2," to ",ACHS("YR")+1,") "
 D READ^ACHSFU
 G K:$D(DTOUT)!$D(DUOUT)!(Y="")
 I $L(Y)'=4!(+Y>(ACHS("YR")+1))!(+Y<(ACHS("YR")-2)) W !!,"Enter a four-digit fiscal year - see listed examples." D SB1^ACHSFU G BD
 S ACHS("YR")=+Y
 I $D(^ACHS(9,DUZ(2),"FY",ACHS("YR"))) W *7,!!,"This fiscal year is already on file and cannot be reset.",!! G BD
 I $E($O(^ACHSF(DUZ(2),"D","B","1"_$E(ACHS("YR"),4)_"00000")),2)=$E(ACHS("YR"),4) D  G BD
 . W *7,!!,"P.O.s still exist for FY ",ACHS("YR")-10," that will interfere with ",ACHS("YR")," P.O. entry.",!,"Use the ^ACHSYFYD programmer utility to delete P.O.'s for FY ",ACHS("YR")-10,"."
 .Q
 D WAIT^DICD
AUTO ;EP - For automatic setup of new FY.
 I $D(ACHSFYWK(DUZ(2),ACHS("YR")-1)),ACHSFYWK(DUZ(2),ACHS("YR")-1),$P(^ACHS(9,DUZ(2),"FY",ACHS("YR")-1,"W",ACHSFYWK(DUZ(2),ACHS("YR")-1),0),U,2) W !!,"Registers Already Closed....",!! G AUTO1
 ; S ACHSACY=ACHS("YR")-1,ACHSASK=1,R=+ACHSFYWK(DUZ(2),ACHSACY),ACHS("DCR")="",ACHSNUM=1
 S ACHSACY=ACHS("YR")-1,ACHSASK=1,ACHS("DCR")="",ACHSNUM=1
 G DCR3^ACHSODQ
 ;
AUTO1 ;EP
 I $D(ACHSERR),ACHSERR=1 G K
 U IO(0)
 W !!,"Initializing New Registers.  Please Wait...",!
 D INIT^ACHSUF
AUTO2 ;
 K ^ACHS(9,DUZ(2),"FY",ACHS("YR"))
 S:'$D(^ACHS(9,DUZ(2),0)) ^ACHS(9,DUZ(2),0)=DUZ(2)_"^^"_DUZ(2)_"^1^1"
 S ^ACHS(9,DUZ(2),"FY",ACHS("YR"),0)=ACHS("YR")_"^0^0",^ACHS(9,DUZ(2),"FY",ACHS("YR"),1)="0^0^0^0^0^0^0",^ACHS(9,"B",DUZ(2),DUZ(2))=""
 S:'$D(^ACHS(9,DUZ(2),"FY",0)) ^ACHS(9,DUZ(2),"FY",0)=$$ZEROTH^ACHS(9002069,10)
 S X=$G(^ACHS(9,DUZ(2),"FY",0))
 S $P(^ACHS(9,DUZ(2),"FY",0),U,3)=ACHS("YR")
 S $P(^ACHS(9,DUZ(2),"FY",0),U,4)=+$P(X,U,4)+1
 S ^ACHS(9,DUZ(2),"FY",ACHS("YR"),"C")="0^0^0"
 S:'$D(^ACHS(9,DUZ(2),"FY",ACHS("YR"),"W",0)) ^ACHS(9,DUZ(2),"FY",ACHS("YR"),"W",0)="^9002069.02A^1^1",^(1,0)=1
 I '$D(ACHSAUTO) S DA=DUZ(2),DR="10///"_ACHS("YR"),DR(2,9002069.01)="1",DIE="^ACHS(9," D ^DIE
 I '$D(ACHSAUTO) K DR S DA=DUZ(2),DR="10///"_ACHS("YR"),DR(2,9002069.01)="2//1" D ^DIE
 I '$D(ACHSAUTO) S DIE="^ACHS(9,"_DUZ(2)_","_"""FY"""_",",DR="3//0",DA=ACHS("YR") D ^DIE
 I '$D(^ACHS(9,DUZ(2),"FY",ACHS("YR"),"W",$O(^ACHS(9,DUZ(2),"FY",ACHS("YR"),"W",0)),1)) S ^(1)="0^0^0^0^0^0^0"
 W !!,"FINISHED....",!!
 ;D EOBR  ;ACHS*3.1*28;CHANGED TO EP
 G K
 ;
EOBR ;EP;CLEAN UP OF OLD EOBR ERROR FILE; KEEP 10 YEARS OF DATA;ACHS*3.1*28 NEW SUB;ACHS*3.1*29 CHANGED TO EP
 ;^ACHSEOBE("EOBD",
 S ACHSTMP=(17000000+DT)-100001,L=0
 F  S L=$O(^ACHSEOBE("EOBD",L)) Q:(L'?1N.N)!(L>ACHSTMP)  D
 .S DA=0 F  S DA=$O(^ACHSEOBE("EOBD",L,DA)) Q:DA'?1N.N  D
 ..W !!,"Cleaning up EOBR Error file"
 ..S DIK="^ACHSEOBE(" D ^DIK
 K L,ACHSTMP
 Q
 ;
 ;ACHS*3.1*29 IHS.OIT.FCJ START OF NEW SECTION
CANS ;EP;SET UP CANS FOR NEW FY
 W !!,"CAN's set up for New FY."
 N ACHSCIEN,ACHSCAN
 S ACHSF638=$$PARM^ACHS(0,8)
 S ACHSPFY=ACHSCFY-1,ACHSCAN=""
 F  S ACHSCAN=$O(^ACHS(2,"B",ACHSCAN)) Q:ACHSCAN=""  D
 .I ACHSF638="N" Q:$E(ACHSCAN,5)'?1(1"H",1"K")
 .S ACHSCIEN=0
 .F  S ACHSCIEN=$O(^ACHS(2,"B",ACHSCAN,ACHSCIEN)) Q:ACHSCIEN'?1N.N  D
 ..Q:$P(^ACHS(2,ACHSCIEN,0),U,3)'=DUZ(2)
 ..Q:'$D(^ACHS(2,ACHSCIEN,1))
 ..S DA(1)=ACHSCIEN
 ..S (DIC,DIE)="^ACHS(2,"_DA(1)_",1,"
 ..S DIC("P")=$P(^DD(9002062,4,0),U,2)
 ..I ACHSF638="N" D  Q
 ...;FED CANS-"K" CURRENT YR;"H" PRIOR YEAR;"K" Update prior FY to current FY;"H" ADD PRIOR FY
 ...I $E(ACHSCAN,5)="K" D  Q
 ....S X=ACHSPFY D ^DIC
 ....I +Y S DA=+Y,DR=".01////"_ACHSCFY D ^DIE Q  ;UPDATE ENTRY
 ....E  S DIC(0)="LX" S X=ACHSCFY D ^DIC Q       ;ADD NEW ENTRY
 ...I $E(ACHSCAN,5)="H" D  Q
 ....S X=ACHSPFY D ^DIC Q:+Y>0                   ;TEST FOR PREV FY ALREADY SET
 ....S DIC(0)="LX" S X=ACHSPFY D ^DIC            ;SET PREV FY
 ..I ACHSF638="Y" D
 ...;TRIBAL CANS ADD NEW FY IF PRIOR FY SET
 ...;S X=ACHSCFY D ^DIC Q:+Y>0                    ;TEST FOR CURRENT FY ALREADY SET
 ...S X=ACHSPFY D ^DIC Q:+Y<1                    ;TEST FOR PREV FY SET NEW FY
 ...S DIC(0)="LX" S X=ACHSCFY D ^DIC
 ..K DIC,DIE,DA,DR,Y,X
 K DIC,DIE,DA,DR
 ; 
 Q
 ;
 ;ACHS*3.1*29 IHS.OIT.FCJ END OF CHANGES
CANNOT ;
 W *7,!!,"Cannot Add New Fiscal Year Until After ",$$FMTE^XLFDT(ACHSFYDT),".",!
 I $$DIR^XBDIR("E")
K ;
 K DA,DIC,DIE,DR,DIK,L,ACHSTMP
 I $D(ACHSAUTO) K ACHS,ACHSAUTO
 Q
 ;
