ACHSDNI ; IHS/ITSC/PMF - DENIAL LIST BY ISSUE DATE ;     [ 10/31/2003  11:43 AM ]
 ;;3.1;CONTRACT HEALTH MGMT SYSTEM;**6,31**;JUNE 11, 2001;Build 39
 ;;ACHS*3.1*6 3/31/2003 - ADD Date of Service to Report
 ;ACHS*3.1*31 6.23.2023 IHS.OIT.FCJ ADDED ESIG STAFF AND ESIG DATE
 ;            Rewrote routine to add new sort by e-signature modifications to print including signer and date
 ;            Removed the All option
 K X2,X3
 ;
A1 ;ENTER BEGIN DATE OR ALL
 W !!,"Enter the BEGINNING DATE for this report: " D READ^ACHSFU G EXIT:$D(DTOUT)!(Y="") G A2:$D(DUOUT) S:Y?1"?".E Y="?" S X=Y,%DT="XEP" D ^%DT G A1:Y<1 S ACHSBDT=Y
 S X=Y,%DT="XEP" D ^%DT G A1:Y<1 S ACHSBDT=Y I Y>DT D FUDT^ACHS G A1
 ;
A2 ;END DATE
 W !!,"Enter the ENDING DATE for this report: " D READ^ACHSFU G EXIT:$D(DTOUT)!(Y="") G A1:$D(DUOUT) S:Y?1"?".E Y="?" S X=Y,%DT="XEP" D ^%DT G A2:Y<1 S ACHSEDT=Y I Y>DT D FUDT^ACHS G A2
 I ACHSEDT<ACHSBDT W !!,*7,"The END is before the BEGINNING." G A1
 ;
A3 ;Signature status ;ACHS*3.1*31 New section
 W !!
 S DIR(0)="SA^S:SIGNED;U:UNSIGNED;A:ALL^"
 S DIR("A")="Include (S)IGNED Denials or (U)NSIGNED Denials or (A)LL Denials: "
 S DIR("?")="Enter type of report S for Signed Denials"
 S DIR("?",1)="Enter type of report U for Unsigned Denials"
 S DIR("?",2)="Enter type of report A for BOTH Signed and Unsigned Denials"
 D ^DIR K DIR
 W !
 G:$D(DUOUT)!$D(DTOUT) EXIT
 S ACHSRTY=Y
 S ACHSIO=IO
 ;
DEV ;
 W !
 S %=$$PB^ACHS
 I $D(DTOUT)!$D(DUOUT) S ACHSQ1=1 Q
 I %="B" D VIEWR^XBLM("START^ACHSDNI"),EN^XBVK("VALM") S ACHSQP=1 Q
 S %ZIS="OPQ" D ^%ZIS I POP D HOME^%ZIS G EXIT
 G:'$D(IO("Q")) START K IO("Q") I $D(IO("S"))!($E(IOST)'="P") W *7,!,"Please queue to system printers." D ^%ZISC G DEV
 X ^%ZOSF("UCI") S ZTRTN="START^ACHSDNI",ZTUCI=Y,ZTDESC="CHS Denial Documents"_$E(ACHSBDT,2,7)_" to "_$E(ACHSEDT,2,7) F ACHS="ACHSBDT","ACHSEDT","DUZ(2)" S ZTSAVE(ACHS)=""
 D ^%ZTLOAD G:'$D(ZTSK) DEV
 K ZTSK
 G EXIT
 ;
START ; EP - TaskMan.
 S ACHSISU=ACHSBDT-1,Y=ACHSBDT X ^DD("DD") S ACHS("BDT")=Y,Y=ACHSEDT X ^DD("DD") S ACHS("EDT")=Y,(ACHSTOT("$"),ACHSTOT)=0
 S ACHST1=$$C^XBFUNC($S(ACHSBDT=1:"***   ALL DENIALS   ***",1:"For the period "_ACHS("BDT")_" through "_ACHS("EDT")),80)
 D BRPT^ACHSFU
 D HDR
 ;
LOOP ;
 K DUOUT,DTOUT
 F  S ACHSISU=$O(^ACHSDEN(DUZ(2),"D","AISSUE",ACHSISU)) Q:+ACHSISU=0!(ACHSISU>ACHSEDT)  D  Q:$D(DUOUT)!$D(DTOUT)
 .S DA="" F  S DA=$O(^ACHSDEN(DUZ(2),"D","AISSUE",ACHSISU,DA)) Q:DA=""  D  Q:$D(DUOUT)!$D(DTOUT)
 ..S ACHS(0)=$G(^ACHSDEN(DUZ(2),"D",DA,0))
 ..Q:ACHS(0)=""
 ..I $P(ACHS(0),U,6)="N" Q:$P($G(^ACHSDEN(DUZ(2),"D",DA,10)),U)=""  S ACHSNAME=$P(^ACHSDEN(DUZ(2),"D",DA,10),U)
 ..I $P(ACHS(0),U,6)="Y" Q:$P(ACHS(0),U,7)=""  S ACHSNAME=$P($G(^DPT($P(ACHS(0),U,7),0)),U) Q:ACHSNAME=""
 ..S ACHS("$")="" I $D(^ACHSDEN(DUZ(2),"D",DA,100)) D DOLLARS^ACHSDNU1(DUZ(2))
 ..S Y=$P(ACHS(0),U,4) S ACHSDOS=$E(Y,4,5)_"/"_$E(Y,6,7)_"/"_$E(Y,2,3)
 ..S ACHSESG=$P(ACHS(0),U,9) S:$G(ACHSESG) ACHSESG=$P(^VA(200,ACHSESG,0),U)
 ..S:ACHSESG="" ACHSESG="A"
 ..S ACHSESGD="",Y=$P(ACHS(0),U,11) S:Y?1N.N ACHSESGD=$E(Y,4,5)_"/"_$E(Y,6,7)_"/"_$E(Y,2,3)
 ..S Y=ACHSISU S Y=$E(Y,4,5)_"/"_$E(Y,6,7)_"/"_$E(Y,2,3)
 ..S ^TMP($J,"ACHSDNI",ACHSESG,ACHSISU,DA)=Y_U_$P(ACHS(0),U)_U_ACHSNAME_U_ACHSDOS_U_ACHS("$")_U_ACHSESGD
 I '$D(^TMP($J,"ACHSDNI")) W !!?10,"There are not any Denials in this time frame." G EXIT
 D PRINT G:ACHSQ EXIT
 D PTOT
 ;
EXIT ;
 K ACHSISU,ACHSNAME,ACHSTOT,DA,ACHSESG,ACHSESGDT
 D ERPT^ACHS
 K ^TMP($J,"ACHSDNI")
 Q
 ;
PRINT ;PRINT REPORT
 S ACHSESG="",ACHSSAV="",ACHSPESG=0,ACHSQ=0
 S:ACHSRTY="S" ACHSESG="A"             ;SIGNED DENIALS
 F  S ACHSESG=$O(^TMP($J,"ACHSDNI",ACHSESG)) Q:ACHSESG=""  D  Q:ACHSQ
 .S ACHSISU=""  F  S ACHSISU=$O(^TMP($J,"ACHSDNI",ACHSESG,ACHSISU)) Q:ACHSISU'?1N.N  D  Q:ACHSQ
 ..S DA=""  F  S DA=$O(^TMP($J,"ACHSDNI",ACHSESG,ACHSISU,DA)) Q:DA'?1N.N  D  Q:ACHSQ  S ACHSSAV=ACHSESG
 ...I ACHSRTY="U" Q:ACHSESG'="A"       ;UNSIGNED DENIALS
 ...S REC=^TMP($J,"ACHSDNI",ACHSESG,ACHSISU,DA)
 ...I (ACHSSAV'=ACHSESG)!(ACHSPESG=1) D PESIG S ACHSPESG=0
 ...S (ACHS("$"),X)=$P(REC,U,5),X2="2$",X3=13 D COMMA^%DTC
 ...W !,$P(REC,U),?9,$P(REC,U,2),?22,$P(REC,U,3),?47,$P(REC,U,4),?57,X,?70,$P(REC,U,6)
 ...S ACHSTOT=ACHSTOT+1,ACHSTOT("$")=ACHSTOT("$")+ACHS("$")
 ...I $Y>ACHSBM D RTRN^ACHS S:$D(DUOUT)!$D(DTOUT) ACHSQ=1  Q:ACHSQ  D HDR S ACHSPESG=1
 Q
PESIG ;PRINT ESIG LINE
 Q:ACHSRTY="U"
 W !,"E-Signature: "
 I ACHSESG="A" W "<UNSIGNED>"
 E  W ACHSESG
 Q
 ;
HDR ; Print header.
 S ACHSPG=ACHSPG+1
 W @IOF,!,$$C^XBFUNC("***  CONTRACT HEALTH CARE SYSTEM REPORT  ***",80),!!
 W ACHSLOC,!?25,"DENIAL DOCUMENTS BY ISSUE DATE",?71,"Page",$J(ACHSPG,3),!,ACHSTIME,!,ACHST1
 W !!,$$C^XBFUNC("***   "_$S(ACHSRTY="A":"ALL",ACHSRTY="S":"SIGNED",1:"UNSIGNED")_" DENIALS   ***",80)
 W !!!,"ISSUE DATE",?12,"DENIAL #",?25,"PATIENT",?49,"DOS",?60,"DOLLARS",?70,"e-Signed",!,ACHS("=")
 Q
PTOT ;
 S X=ACHSTOT("$"),X2="2$",X3=16 D COMMA^%DTC
 W !,ACHS("="),!,"TOTALS FOR THIS REPORT: ",ACHSTOT," DENIAL",$S(ACHSTOT=1:"",1:"S"),?50,X,!
 D RTRN^ACHS W @IOF
 Q
 ;
