ACHSEOBG ; IHS/ADC/GTH - PROCESS EOBRS (6/6) CONT. - SUMMARY/ERROR REPORT ; [ 02/18/2000  11:42 AM ]
 ;;3.0;CONTRACT HEALTH MGMT SYSTEM;**14,15,16**;SEP 17, 1997
 ;;IHS/ASDST/MRS ACHS*3*16 ADDED NEW MESSAGES
 ;
 Q:'$D(ACHSERRE)!'$D(ACHSEDAT)
 ;
 I $P($T(@ACHSERRE),";",4)="E" D ^ACHSEOBD
 ;
 I $D(^ACHSEOBR("ER",ACHSZFPT,ACHSCTR(1),ACHSERRE)) S ^(ACHSERRE)=^(ACHSERRE)_"^"_ACHSEDAT Q
 S ^ACHSEOBR("ER",ACHSZFPT,ACHSCTR(1),ACHSERRE)=ACHSEDAT
 Q
 ;
1 ;;P.O. NOT FOUND;E
2 ;;NO FILE FROM CR-REF;E
3 ;;P.O. NUMBER MISMATCH;E
4 ;;AUTH DATE MISMATCH;W
5 ;;BLANKET IND MISMATCH;E
6 ;;DOC TYPE MISMATCH;E
7 ;;FIN LOC CODE MISMATCH;E
8 ;;EOBR ALREADY PROCESSED;E
9 ;;DOCUMENT CANCELLED;E
10 ;;OBJECT CLASS MISMATCH;W
11 ;;CAN NUMBER MISMATCH;W
12 ;;ZERO DOCUMENT AMOUNT;E
13 ;;REGISTERS OUT OF BAL;E
14 ;;CONTRACT NOT FOUND;W
15 ;;VENDOR NOT FOUND;E
16 ;;ICD9 DX CODE ERROR;W
17 ;;ICD0 PROC CODE ERR;W
 ;ACHS*3*14 CHANGED W TO E FOR LINES 18 & 19
 ;ACHS*3*15 CHANG THEM BACK, E TO W FOR LINES 18 & 19
18 ;;CPT CODE ERROR;W
19 ;;REVENUE CODE ERROR;W
20 ;;DRG CODE NOT FOUND;W
21 ;;FAC NOT IN LOC FILE;E
22 ;;NO LOC FINANCIAL INFO;E
 ;ACHS*3*16 ADDED DX FOR 23
23 ;;DUPLICATE DX CODE;W
24 ;;FAIL ENTRY TO PCC;W
25 ;;NEG ADJ > PAY AMOUNT;E
26 ;;ADJ ERR-DCR ACCT ERR;E
27 ;;FUNDS NOT AVAIL;E
28 ;;NO EOBR AMOUNT ERROR;E
29 ;;MULTIPLE PAYMT;W
30 ;;HEAL REC # MISMATCH;W
31 ;;INTERIM DENIAL;E
32 ;;DOC CANCELLED BY FI;W
 ;ACHS*3*14 CHANGED W TO E IN LINE 33
 ;ACHS*3*15 CHANGE IT BACK, E TO W IN LINE 33  
33 ;;ADA Code Err;W
34 ;;OBL LIMIT EXCEEDED;E
35 ;;DOC AUTH DATE GONE;E
36 ;;VENDOR MIS-MATCH;W
37 ;;INTEREST DATA FAILED DIE;W
38 ;;INTEREST CAN NOT FOUND;W
39 ;;INTEREST OCC NOT FOUND;W
40 ;;CAN'T PROCESS HCPCS CODE;W
 ;ACHS*3*15 ADDED CODE 41 AND 42
41 ;;DUPLICATE CHS CHECK NUMBER;E
42 ;;DUPLICATE FI CHECK # W/DIF DATE;E
 ;ACHS*3*16 ADDED DUP PROC #43
43 ;;DUPLICATE PROC CODE;W
