ACHSAA ; IHS/ITSC/PMF - DOCUMENT GENERATION, KILL VARS ;  [ 10/16/2001   8:16 AM ]
 ;;3.1;CONTRACT HEALTH MGMT SYSTEM;**32**;JUN 11, 2001;Build 39
 ;ACHS*3.1*32 6.20.24 IHS.OIT.FCJ MED PRI
 ;
 S (ACHSEDOS,ACHSRMPC,ACHSRMP)=""
 K ACHSRATE,ACHSAGR,ACHSRA,ACHSBDES,ACHSDRG,ACHSRTAG,ACHSBTYP,ACHSPROV,ACHSCONP,ACHSCAN,ACHSSCC,ACHSCOPT,ACHSESDA,ACHSESDO,ACHSFDT,ACHSHONN,ACHSTDT,ACHSHON,ACHSORDN,ACHSBLKF,ACHSDES
 Q
 ;
