ACHSTX8 ; IHS/ITSC/PMF - EXPORT DATA (9/9) - EOJ ;JUL 10, 2008
 ;;3.1;CONTRACT HEALTH MGMT SYSTEM;**5,6,11,13,14,19,23,25,28,32**;JUN 11,2001;Build 39
 ;IHS/SET/GTH ACHS*3.1*5 12/06/2002 - Capture number of individual records.
 ;IHS/SET/JVK ACHS*3.1*6 4/23/2003 - If site acts as area don't que file
 ;ACHS*3.1*13 6.16.2007 IHS/OIT/FCJ Added new rec type of "U" and trans to Export status file
 ;ACHS*3.1*14 2.28.2008 IHS/OIT/FCJ Added test for OCC and Re-export option
 ;ACHS*3.1*28 4.1.2020 IHS.OIT.FCJ Mod to add dt/time to tx file and clean up vars
 ;ACHS*3.1*32 8.13.2024 IHS.OIT.FCJ ADDED TOTALS FOR PO, version change for NDW-ADA codes
 ;
 U IO(0)
 W !!?5,".....EXPORT CHS DATA",!!
 I ACHSROUT<1 G NORECDS
 ;ACHS*3.1*13 IHS/OIT/FCJ ADDED UFMS REC 8 TO NXT LINE
 F ACHSY=2:1:7,8 S ACHSTYP(ACHSY)=$$REC^ACHSACO1(ACHSY)
 D R1
 ;ACHS*3.1*28 ALLOW EXIT
 ;I $$DIR^XBDIR("E","Enter <RETURN> to Continue")
 I $$DIR^XBDIR("E")
 I $D(DUOUT) G JOBABEND
 I '$D(ACHSCRTN) S ACHSCRTN=""
 I '$D(ACHSMDAT) S ACHSMDAT=DT
 ;ITSC/SET/JVK ACHS*3.1*11 LOOK FOR VERSION AND PATCH
 S (ACHSVDA,ACHSPA)=""
 S ACHSVDA=$O(^DIC(9.4,"B","CONTRACT HEALTH MGMT SYSTEM",ACHSVDA))
 S ACHSVER=$P(^DIC(9.4,ACHSVDA,"VERSION"),U)
 S ACHSPA=$O(^DIC(9.4,ACHSVDA,22,"B",ACHSVER,ACHSPA))
 ;S ACHSPA=$P(^DIC(9.4,119,22,3,"PAH",0),U,4)
 ;S ACHSPA=$P(^DIC(9.4,ACHSVDA,22,ACHSPA,"PAH",0),U,4)  ;ACHS*3.1*23
 S ACHSPA=$P(^DIC(9.4,ACHSVDA,22,ACHSPA,"PAH",0),U,4) S:ACHSPA>10 ACHSPA=11  ;ACHS
 ;ITSC/SET/JVK ACHS*3.1*11 ADD VERSION OF CHS TO ZERO NODE
 ;S ^ACHSDATA(0)=$P($G(^AUTTLOC(DUZ(2),0)),U,10)_U_$$LOC^ACHS_U_DT_U_ACHSFDT_U_ACHSLDAT_"^^"_ACHSRTYP_U_ACHSCRTN_U_ACHSMDAT_U_$P($G(^ACHS(9,DUZ(2),"FY",ACHSCFY,0)),U,2)_U_$P($G(^ACHS(9,DUZ(2),"FY",ACHSCFY,0)),U,3)
 ;S ^ACHSDATA(0)=$P($G(^AUTTLOC(DUZ(2),0)),U,10)_U_$$LOC^ACHS_U_DT_U_ACHSFDT_U_ACHSLDAT_"^^"_ACHSRTYP_U_ACHSCRTN_U_ACHSMDAT_U_$P($G(^ACHS(9,DUZ(2),"FY",ACHSCFY,0)),U,2)_U_$P($G(^ACHS(9,DUZ(2),"FY",ACHSCFY,0)),U,3)_U_ACHSVER_"*"_ACHSPA
 ;ACHS*3.1*23 CHG NXT LN TO TEST FOR ICD9 OR ICD10 FORMAT
 I DT<$$PARM^ACHS(0,18) D SETR1
 E  D SETR2
 ; Set up Qed report.
 I ACHSIO=IO G NOQUE
 S ZTRTN="REPORT^ACHSTX8",ZTDTH=$H,ZTIO=ACHSION,ZTDESC="REPORT OF EXPORT RECORDS, for "_$P($G(^AUTTLOC(DUZ(2),0)),U,2)_"."
 F %="ACHSFDT","ACHSRTYP","ACHSRTYP(","ACHSLDAT","ACHSTYP(" S ZTSAVE(%)=""
 D ^%ZTLOAD
NOQUE ; Report not q'd.
 ;I ACHSREEX D REPORT G WRITETP  ;ACHS*3.1*28 ADD RE-EXPORT TO TX FILE
 ;I $D(ACHSPPO) D REPORT
 I ACHSREEX S ACHSROUT=$S(ACHSREXT="F":ACHSRTYP(5),ACHSREXT="U":ACHSRTYP(8),1:ACHSROUT)   ;ACHS*3.1*28
 S DIE="^ACHSTXST("
 I '$D(^ACHSTXST("B",DUZ(2))) S $P(^ACHSTXST(0),U,3)=DUZ(2),^ACHSTXST(DUZ(2),0)=DUZ(2),$P(^ACHSTXST(0),U,4)=$P(^ACHSTXST(0),U,4)+1,^ACHSTXST("B",DUZ(2),DUZ(2))=""
 ;S DA=DUZ(2),DR="1///"_DT,DR(2,9002070.01)=".01///"_DT
 S DA=DUZ(2),DR="1///"_ACHSDTX,DR(2,9002070.01)=".01///"_ACHSDTX  ;ACHS*3.1*28
 D ^DIE
 S DA(1)=1
 F ACHS=0:0 S ACHS=$O(^ACHSTXST(DUZ(2),1,ACHS)) Q:ACHS<1  S DA(1)=ACHS
 S:ACHSFDT=0 ACHSFDT=ACHSLDAT  ;ACHS*3.1*28
 S ^ACHSTXST(DUZ(2),1,DA(1),0)=ACHSDTX_U_ACHSFDT_U_ACHSLDAT_"^^"_ACHSROUT_U_ACHSCRTN_U_ACHSMDAT_"^^^N"  ;ACHS*3.1*28 CHG DT TO ACHSDTX
 D NUMRECS(DA(1)) ;IHS/SET/GTH ACHS*3.1*5 12/06/2002
 ;
WRITETP ; Save global for export. 
 ;ACHS*3.1*28;TEST TO SEND FILE TO UFMS OR FI BYPASSING THE AREA OFFICE
 S (ACHSFN,ACHSFIFN,ACHSXFN)=""  ;ACHS*3.1*28
 I $$PARM^ACHS(0,19)="Y" D FIUFMS G WRITETP1
 S XBGL="ACHSDATA",XBNAR="CONTRACT HEALTH export data",XBMED="F"
 ;IHS/SET/JVK ACHS*3.1*6 FOR THOSE SITES SENDING DIRECT TO FI
 I $$GET1^DIQ(9002079,DUZ(2),1412,"I")="N" S XBQTO=""
 ;
 S (ACHSFN,XBFN)="ACHS"_$P($G(^AUTTLOC(DUZ(2),0)),U,10)     ;ACHS*3.1*19 ;ACHS*3.1 ADDED ACHSFN
 D NOW^%DTC S (ACHSFN,XBFN)=XBFN_"."_(%I(3)+1700)_$E(%,4,7)_"_"_$P(%,".",2)  ;ACHS*3.1*19
 I $P(^AUTTSITE(1,0),U,14)'="",$D(^%ZIB(9888888.93,"B",$P(^AUTTSITE(1,0),U,14))) S XBS1=$P(^AUTTSITE(1,0),U,14) ;ACHS*3.1*25
 D ^XBGSAVE    ;Saves and sends global
 I XBFLG G JOBABEND
WRITETP1 ;ACHS*3.1*28  NEW LINE LABLE
 I 'ACHSREEX S $P(^ACHSTXST(DUZ(2),1,DA(1),0),U,10)="Y"
 I $D(ACHSPPO) D REPORT
 D TXFN  ;ACHS*3.1*28
 G ENTRETRN
 ;
JOBABEND ;EP.
 W !!?10,"ABNORMAL END OF CHS EXPORT"
 I $D(XBFLG),XBFLG W !!,XBFLG(1),! K XBFLG
 G ENTRETRN
 ;
TXFEF ;EP.
 W !!,"EXPORT PROGRAM ALREADY RUN THIS DATE FOR THIS FACILITY",*7
 ;TPF;FOR CLEARING: EDIT 'CHS TX STATUS' FILE ENTER FACILITY NAME AND DELETE
ENTRETRN ;
 W !
 I $$DIR^XBDIR("E","Press RETURN...")
KILL ;EP - Kill vars, close device, quit.
 I '$$LOCK^ACHS("^ACHSF(DUZ(2),""D"")","-")
 K %DT,X1,XBDT,XBF,XBGL,XBTIT,XBPAFN,XBFLG,ACHSCRTN,DA,DIC,DIE,DR,DUOUT,DX,DY,TST
 ;ACHS*3.1*28 MODIFIED NEXT LINES ALL VARS NOT BEING KILLED CAUSED ERROR IN SEL DOCS
 K DI,DI(1),DIADD,D1,DFN,P,T
 K ^TMP("ACHSTX",$J)
 D EN^XBVK("ACHS"),^%ZISC,^ACHSVAR
 Q
 ;
NORECDS ;EP
 W !!,*7,?10,"NO RECORDS GENERATED FOR EXPORT",!!
 G ENTRETRN
 ;
REPORT ;EP - From TaskMan.
 U IO
 D LINES^ACHSFU,NOW^ACHS
 S ACHSTIME=$$C^XBFUNC(ACHSTIME,80),X=$$C^XBFUNC($$LOC^ACHS,80)
 X:$D(ACHSPPO) ACHSPPO
 W @IOF,!,ACHS("*"),!,"*",?25,"CONTRACT HEALTH MANAGEMENT SYSTEM",?78,"*",!,"*",?30,"EXPORTED RECORDS BY TYPE",?78,"*",!,"*",$E(X,2,80),?78,"*",!,"*",$E(ACHSTIME,2,80),?78,"*",!,ACHS("*"),!!!
 D R1
 W @IOF
 X:$D(ACHSPPC) ACHSPPC
 D ERPT^ACHS
 Q
 ;
R1 ; Print basic info for the report.
 W ?20,"BEGINNING ADD/UPD DATE",?45,"=",?50,$$FMTE^XLFDT(ACHSFDT),!!?20,"ENDING ADD/UPD DATE",?45,"=",?50,$$FMTE^XLFDT(ACHSLDAT),!!?15,$$REPEAT^XLFSTR("-",47),!?15,"T Y P E   O F   R E C O R D",?55,"NUMBER",!?15,$$REPEAT^XLFSTR("-",47),!!
 S ACHSRTYP=0
 ;ACHS*3.1*13 IHS/OIT/FCJ CHG 7 TO 8 TO NXT LINE
 F ACHS=2:1:8 W ?10,ACHS,".",?15,ACHSTYP(ACHS),?55,$J(ACHSRTYP(ACHS),6),! S ACHSRTYP=ACHSRTYP+ACHSRTYP(ACHS)
 W !?20,"TOTAL ALL TYPES",?55,$J(ACHSRTYP,6),!!
 W !?20,"TOTAL FI Purchase Orders:  " W ?50,$S(ACHSRTYP(5)>0:$J((ACHSRTYP(5)/3),6),1:$J(ACHSRTYP(5),6))  ;ACHS*3.1*32
 W !?20,"Total UFMS Purchase Orders:  " W ?50,$J(ACHSRTYP(8),6)     ;ACHS*3.1*32
 Q
 ;
CANOBJ ;EP - Set CAN, ObjClass, & SCC into ACHSCAN, ACHSOBJC, ACHSSCC.
 S (ACHSCAN,ACHSSCC,ACHSOBJC)=""
 S:$P(ACHSDOCR,U,6)'="" ACHSCAN=$P($G(^ACHS(2,$P(ACHSDOCR,U,6),0)),U)
 S:$P(ACHSDOCR,U,7)'="" ACHSSCC=$P($G(^ACHS(3,DUZ(2),1,$P(ACHSDOCR,U,7),0)),U)
 ;ACHS*3.1*14 2.28.2008 IHS/OIT/FCJ ADDED NXT LINE TO TEST FOR OCC IF NOT IN FILE USES SCC DEFAULT
 I $P(ACHSDOCR,U,10)'="",$G(^ACHSOCC($P(ACHSDOCR,U,10),0))="" S ACHSOBJC=$P(ACHSDOCR,U,10) Q
 S:$P(ACHSDOCR,U,10)'="" ACHSOBJC=$P($G(^ACHSOCC($P(ACHSDOCR,U,10),0)),U)
 Q
 ;
IPA ;EP - Set IHS pay amt into ACHSIPA.
 S X=$P(ACHSTRAN,U,4),X=$P(X,".")_$E($P(X,".",2)_"00",1,2),ACHSIPA=$E(X+1000000000000,2,13)
 Q
 ;
TOS ;EP - Set document type into ACHSTOS2.
 S X=$P(ACHSDOCR,U,4),ACHSTOS2=$S(X=1:43,X=2:57,X=3:64,1:"  ")
 Q
 ;
TRIB ;EP - Set patient's tribe into ACHSTRIB.
 S ACHSTRIB="999"
 I $D(^AUPNPAT(DFN,11)),$P($G(^(11)),U,8),$D(^AUTTTRI($P(^(11),U,8),0)),$L($P(^(0),U,2))=3 S ACHSTRIB=$P(^(0),U,2)
 Q
 ; 
 ;Begin New Code;IHS/SET/GTH ACHS*3.1*5 12/06/2002
NUMRECS(DA) ;
 NEW DIE,DR
 S DA(1)=DUZ(2),DIE="^ACHSTXST("_DA(1)_",1,",DR=""
 F %=11:1:17 S DR=DR_";"_%_"///"_$G(ACHSRTYP(%-10),"0")
 S DR=$E(DR,2,99999)
 ;ACHS*3.1*13 IHS/OIT/FCJ Rec type-UFMS;ACHS*3.1*28 type RE-EXPORT TYPE
 ;S DR=DR_";18///"_ACHSRTYP(8)_";19///"_ACHSTXTY_";20///"_ACHSREXT                    ;ACHS*3.1*32
 S DR=DR_";18///"_ACHSRTYP(8)_";19///"_$S(ACHSREEX:"R",1:ACHSTXTY)_";20///"_ACHSREXT  ;ACHS*3.1*32 SET RE-EXPORT
 D ^DIE
 S ACHSXIEN=DA  ;ACHS*3.1*28
 ;End New Code;IHS/SET/GTH ACHS*3.1*5 12/06/2002
TXREC ;ADD EXPORT RECS TO CHS TX STATUS FILE
 Q:'$D(^TMP("ACHSTX",$J))
 S DA(2)=DUZ(2),DA(1)=DA
 S (DIC,DIE)="^ACHSTXST("_DA(2)_",1,"_DA(1)_",2,"
 S DIC("P")=$P(^DD(9002070.01,201,0),U,2),DIC(0)="L",DLAYGO=9002070,DIADD=1
 S P=0 F  S P=$O(^TMP("ACHSTX",$J,P)) Q:P'?1N.N  D
 .S T=0 F  S T=$O(^TMP("ACHSTX",$J,P,T)) Q:T'?1N.N  D
 ..S X=P D ^DIC S DA=+Y
 ..S DR=".02////"_T
 ..D ^DIE
 ..;ACHS*3.1*28 ADD EXPORT DATE TO TRANSACTION
 ..I 'ACHSREEX S $P(^ACHSF(DUZ(2),"D",P,"T",T,0),U,32)=ACHSDTX
 ;Update export date in Facility file
 ;ACHS*3.1*14 11/1/2008 IHS/OIT/FCJ TEST FOR REEXPORT
 ;ACHS*3.1*28 TEST FOR UFMS EXPORT AND SET WITH DATE-TIME
 I 'ACHSREEX,ACHSTXTY="U" S $P(^ACHSF(DUZ(2),0),U,14)=ACHSDTX
 K DIE,DIC,DA,DR,DIADD
 Q
TXFN ;ADD EXPORT FN TX STATUS; ACHS*3.1*28 NEW SUB
 S DA(1)=DUZ(2),DA=ACHSXIEN
 S (DIC,DIE)="^ACHSTXST("_DA(1)_",1,"
 S DR="101///"_ACHSFN_";102///"_ACHSFIFN_";103///"_ACHSXFN
 D ^DIE
 K DIE,DIC,DA,DR
 Q
SETR1 ;ICD-9 FORMAT;ACHS*3.1*23
 S ^ACHSDATA(0)=$P($G(^AUTTLOC(DUZ(2),0)),U,10)_U_$$LOC^ACHS_U_DT_U_ACHSFDT_U_ACHSLDAT_"^^"_ACHSRTYP_U_ACHSCRTN_U_ACHSMDAT_U_$P($G(^ACHS(9,DUZ(2),"FY",ACHSCFY,0)),U,2)_U_$P($G(^ACHS(9,DUZ(2),"FY",ACHSCFY,0)),U,3)_U_ACHSVER_"*"_ACHSPA
 Q
SETR2 ;ICD-10 FORMAT;ACHS*3.1*23
 ;S ^ACHSDATA(0)=$P($G(^AUTTLOC(DUZ(2),0)),U,10)_U_$$LOC^ACHS_U_DT_U_ACHSFDT_U_ACHSLDAT_"^^"_ACHSRTYP_U_ACHSCRTN_U_ACHSMDAT_U_$P($G(^ACHS(9,DUZ(2),"FY",ACHSCFY,0)),U,2)_U_$P($G(^ACHS(9,DUZ(2),"FY",ACHSCFY,0)),U,3)_U_"CRV003"  ;ACHS*3.1*32
 S ^ACHSDATA(0)=$P($G(^AUTTLOC(DUZ(2),0)),U,10)_U_$$LOC^ACHS_U_DT_U_ACHSFDT_U_ACHSLDAT_"^^"_ACHSRTYP_U_ACHSCRTN_U_ACHSMDAT_U_$P($G(^ACHS(9,DUZ(2),"FY",ACHSCFY,0)),U,2)_U_$P($G(^ACHS(9,DUZ(2),"FY",ACHSCFY,0)),U,3)_U_"CRV004"   ;ACHS*3.1*32
 Q
FIUFMS ;ACHS*3.1*28 AUTO SEND UFMS AND FI
 S X=$P(^AUTTLOC(DUZ(2),0),U,4),ACHSPFX=$P(^AUTTAREA(X,0),U,4)
 I ACHSREEX D:ACHSREXT="U" UFMS D:ACHSREXT="F" FI D:ACHSREXT="B" FI,UFMS Q
 D FI Q:$$PARM^ACHS(0,8)="Y"
 D UFMS
 Q
 ;TEST PARAMETERS..D FI,UFMS
FI ;EXPORT FI FILE; ACHS*3.1*28
  Q:$$PARM^ACHS(2,11)="N"
  I ACHSBCBS("COUNT")=0 W !!,*7,?10,"NO FI RECORDS GENERATED FOR EXPORT",!! Q
  K XBS1
  S ACHSBCBS("TOT")=$E(ACHSBCBS("TOT")+1000000000000,2,13),ACHSBCBS("COUNT")=$E(ACHSBCBS("COUNT")+10000,2,5)
  F I=.01,.02,0 S ^ACHSBCBS(I)="//"_$J("",78)
  S ^ACHSBCBS(.04)="1BATCH"_$E(DT,4,7)_$E(DT,2,3)_"Z3"_$J("",25)_ACHSPFX
  S ^ACHSBCBS("B")="4BATCH"_$E(DT,4,7)_$E(DT,2,3)_"Z3"_ACHSBCBS("COUNT")_$J("",21)_ACHSPFX_$J("",9)_ACHSBCBS("TOT")_$J("",17)
  S X="",$P(X,"9",21)="",^ACHSBCBS("C")=$J("",60)_X
  S ^ACHSBCBS("D")="/*"
  S X=$E(DT,4,7)_$E(DT,2,3)
  S ^ACHSBCBS("A")="AA"_ACHSAFAC_" "_X_" "_X_" "_X_$J("",51)
  D NOW^%DTC S X=(%I(3)+1700)_$E(%,4,7)_"_"_$P(%,".",2)
  S (ACHSFIFN,XBFN)="chsbcs."_X
  S XBGL="ACHSBCBS"
  S XBMED="F",XBFLT=1,XBQ="N"
  S XBUF=$S($$OS^ACHS=2:"c:\usr\spool\chsdata",1:"/usr/spool/chsdata")
  D ^XBGSAVE
  Q
  ;
UFMS ;EXPORT UFMS FILE; ACHS*3.1*28
 ;^ACHSUFMS;records for UFMS
 ;ACHSUFMS("COUNT") TOTAL UFMS RECS
 ;ACHSUFMS("TOT") TOTAL UFMS $'S
 I ACHSUFMS("COUNT")=0 W !!,*7,?10,"NO UFMS RECORDS GENERATED FOR EXPORT",!! Q
 S ACHSGLBL="^ACHSUFMS",ACHSDESC="DHR records for UFMS",ACHSSUF="IHS"
 S X=$E(DT,4,7)_$E(DT,2,3)
 S ^ACHSUFMS("COUNT")="4BATCH"_X_"Z3"_$E(10000+ACHSUFMS("COUNT"),2,5)_$J("",21)_"J"_$P(^AUTTSITE(1,0),U,2)_$J("",6)_$E(10000000000+ACHSUFMS("TOT"),2,11)_$J("",78)
 S ^ACHSUFMS(0)="1BATCH"_X_"Z3"_$J("",121)
 D UFMS^ACHSPCC3
 Q
