CIAVIP32 ;MSC/IND/PLS - EHR v1.1p32 Inits;18-Nov-2021 12:09;PLS
 ;;1.1;VUECENTRIC FRAMEWORK;**32**;23-Oct-2006
 ;;Copyright 2000-2021, Medsphere Systems Corporation
 ;=================================================================
EC ;EP - Environment check
 D CHKINS^CIAOINIT("EHR*1.1*31",2)
 Q
PRE ;EP - Preinit
 ;Prenatal ProblemList
 D DELUSES("IHS.PN.EHR.PRENATALPROBLEMLIST.PIPCOMPONENT","FILE:INFRAGISTICS2.EXCEL.V10.3.DLL")
 D DELUSES("IHS.PN.EHR.PRENATALPROBLEMLIST.PIPCOMPONENT","FILE:INFRAGISTICS2.SHARED.V10.3.DLL")
 D DELUSES("IHS.PN.EHR.PRENATALPROBLEMLIST.PIPCOMPONENT","FILE:INFRAGISTICS2.WIN.MISC.V10.3.DLL")
 D DELUSES("IHS.PN.EHR.PRENATALPROBLEMLIST.PIPCOMPONENT","FILE:INFRAGISTICS2.WIN.ULTRAWINGRID.EXCELEXPORT.V10.3.DLL")
 D DELUSES("IHS.PN.EHR.PRENATALPROBLEMLIST.PIPCOMPONENT","FILE:INFRAGISTICS2.WIN.ULTRAWINGRID.V10.3.DLL")
 D DELUSES("IHS.PN.EHR.PRENATALPROBLEMLIST.PIPCOMPONENT","FILE:INFRAGISTICS2.WIN.ULTRAWINPRINTPREVIEWDIALOG.V10.3.DLL")
 D DELUSES("IHS.PN.EHR.PRENATALPROBLEMLIST.PIPCOMPONENT","FILE:INFRAGISTICS2.WIN.ULTRAWINSTATUSBAR.V10.3.DLL")
 D DELUSES("IHS.PN.EHR.PRENATALPROBLEMLIST.PIPCOMPONENT","FILE:INFRAGISTICS2.WIN.ULTRAWINTOOLBARS.V10.3.DLL")
 D DELUSES("IHS.PN.EHR.PRENATALPROBLEMLIST.PIPCOMPONENT","FILE:INFRAGISTICS2.WIN.V10.3.DLL")
 D DELUSES("IHS.PN.EHR.PRENATALPROBLEMLIST.PIPCOMPONENT","FILE:RICHTEXTBOXPRINTCONTROL.DLL")
 D DELUSES("IHS.PN.EHR.PRENATALPROBLEMLIST.PIPCOMPONENT","FILE:INFRAGISTICS2.WIN.ULTRAWINTABCONTROL.V10.3.DLL")
 D DELUSES("IHS.PN.EHR.PRENATALPROBLEMLIST.PIPCOMPONENT","FILE:INFRAGISTICS2.WIN.ULTRAWINEDITORS.V10.3.DLL")
 ;Prenatal PickList
 D DELUSES("IHS.PN.EHR.PRENATALPICKLIST.PRENATALPICKLISTCOMPONENT","FILE:INFRAGISTICS2.SHARED.V10.3.DLL")
 D DELUSES("IHS.PN.EHR.PRENATALPICKLIST.PRENATALPICKLISTCOMPONENT","FILE:INFRAGISTICS2.WIN.ULTRAWINLISTBAR.V10.3.DLL")
 D DELUSES("IHS.PN.EHR.PRENATALPICKLIST.PRENATALPICKLISTCOMPONENT","FILE:INFRAGISTICS2.WIN.ULTRAWINLISTVIEW.V10.3.DLL")
 D DELUSES("IHS.PN.EHR.PRENATALPICKLIST.PRENATALPICKLISTCOMPONENT","FILE:INFRAGISTICS2.WIN.V10.3.DLL")
 Q
PRED ;D  ;CLEANUP SOME FILES
 ;.N DIU
 ;.F DIU=90460.1,90460.11,90460.13,90460.14 D
 ;..S DIU(0)="DST"
 ;..D EN^DIU2
 ;.F DIU=90460.12,90460.15 D
 ;..S DIU(0)="ST"
 ;..D EN^DIU2
 Q
POST ;EP - Postinit
 N VER,FDA,PID,IEN,X,TYPE
 D BMES^XPDUTL("Updating version numbers...")
 F VER=0:1 S X=$P($T(VER+VER),";;",2) Q:'$L(X)  D
 .S PID=$$PRGID^CIAVMCFG($P(X,";"))
 .S:PID FDA(19930.2,PID_",",2)=$P(X,";",2),FDA(19930.2,PID_",",7)=$P(X,";",3)
 D:$D(FDA) FILE^DIE(,"FDA")
 W !!!
 ;Update help file references
 D UPDCHM
 ;Add alias
 ;D ADDALIAS
 ;Mark menu out of order
 ;Change friendly names of objects
 ;Prompt to enable logins
 I $L($$GETLOGIN^CIAVUTIL),$$ASK^CIAU("Do you want to enable EHR logins","Y") D
 .D SDABORT^CIAVUTIL(,1),BMES^XPDUTL("Application logins have been enabled.")
 D ADDUSES("IHS.PN.EHR.PRENATALPROBLEMLIST.PIPCOMPONENT","FILE:BEHPOVCVG.DLL")
 ;Update RPC registration
 D REGRPC
 Q
 ;Register RPCs to context
REGRPC ;EP-
 Q
 ; Update the friendly name of an existing object
UPDOBJNM(OBJ,NAME) ;EP-
 N PID,FDA
 S PID=$$PRGID^CIAVMCFG(OBJ)
 Q:'PID
 S FDA(19930.2,PID_",",1)=NAME
 D FILE^DIE(,"FDA")
 Q
 ; Attach Event Protocols to Event Types
EVTPRTL(TYPE) ;
 N EVTNM,PRT,EVT,FDA
 S EVTNM="CIAV "_TYPE_" EVENT"
 S EVT=$$EVENTIEN^CIANBEVT(TYPE)
 Q:'EVT
 S PRT=$$FIND1^DIC(101,,,EVTNM)
 Q:'PRT
 S FDA(19941.21,EVT_",",7)=PRT
 D FILE^DIE(,"FDA")
 Q
 ; Add a USES Item
ADDUSES(PARENT,ITM) ;EP-
 N PID,ITMIEN,FDA,CID
 S PID=$$PRGID^CIAVMCFG(PARENT)
 S CID=$$PRGID^CIAVMCFG(ITM)
 I PID,CID D
 .S ITMIEN=$$FIND1^DIC(19930.221,","_PID_",","B",ITM)
 .I 'ITMIEN D
 ..S FDA(19930.221,"+1"_","_PID_",",.01)=CID
 ..D UPDATE^DIE(,"FDA","ERR")
 Q
 ; Delete a USES item
DELUSES(PARENT,ITM) ;EP-
 N PID,ITMIEN,FDA
 S PID=$$PRGID^CIAVMCFG(PARENT)
 I PID D
 .S ITMIEN=$$FIND1^DIC(19930.221,","_PID_",","B",ITM)
 .I ITMIEN D
 ..S FDA(19930.221,ITMIEN_","_PID_",",.01)="@"
 ..D FILE^DIE(,"FDA")
 Q
 ;
UPDCHM ;EP-
 N CHM,PID
 F CHM=0:1 S X=$P($T(CHM+CHM),";;",2) Q:'$L(X)  D
 .S PID=$$PRGID^CIAVMCFG($P(X,";"))
 .D AECHM(PID,$P(X,";",2,99))
 W !!
 Q
 ;
AECHM(PID,VAL) ;EP-
 N LN,FN,IDX,TXT,ARY,CNT,IENS
 S FN=$P(VAL,";"),CNT=0
 S LN=0 F  S LN=$O(^CIAVOBJ(19930.2,PID,6,LN)) Q:'LN  D  Q:$G(IDX)
 .S TXT=^CIAVOBJ(19930.2,PID,6,LN,0)
 .S ARY(LN,0)=TXT,CNT=CNT+1
 .I $$UP^XLFSTR(TXT)[$$UP^XLFSTR($P(VAL,";")) S IDX=LN
 I $G(IDX) D
 .S ^CIAVOBJ(19930.2,PID,6,IDX,0)=VAL
 E  D
 .S ARY($S('CNT:1,1:CNT+1),0)=VAL
 .S IENS=PID_","
 .S FDA(19930.2,IENS,10)="ARY"
 .D FILE^DIE(,"FDA")
 Q
 ; Rename .01 field of BEH Measurement file
BEHMSR(X,Y) ;
 N IEN,FDA
 S IEN=$O(^BEHOVM(90460.01,"B",X,0))
 Q:'IEN
 S FDA(90460.01,IEN_",",.01)=Y
 D FILE^DIE(,"FDA")
 Q
 ;Add Alias values
ADDALIAS ;
 N IEN,FDA,ERR,ARY
 S IEN=$$GETIEN^CIAVMCFG(19930.2,"INDIANHEALTHSERVICE.BEH.IBH.SUICIDE.CTLSUICIDE_FORM")
 I IEN D
 .S ARY(1)="INDIANHEALTHSERVICE.BEH.IBH.SUICIDE.CONTROLS.CTLSUICIDE_FORM"
 .S FDA(19930.2,IEN_",",23)="ARY"
 .D FILE^DIE("","FDA","ERR")
 Q
VER ;;BEHCIR.CIRCTRL;1.1.7989.21723;724B51CA786C5040B7DE9E8511DFB03C
 ;;BEHCCDA.CCDACTRL;1.1.7982.40666;6EFAED96A52DF0826F8E55F1C7554599
 ;;FILE:CDACOMMON.DLL;1.1.7977.29580;548984D15FA291578305FA1BDBB77042
CHM ;;
 ;;
