XMC1 ;(WASH ISC)/THM-SCRIPT INTERPRETER ;02/11/99  09:57
 ;;7.1;MailMan;**4,13,20,27,50**;Jun 02, 1994
 S XMINST=XMSCR
ENT I '$D(XMSDOM) S (XMSDOM,XMRDOM)=XMINST
 I '$D(XMR0) D ENT1^XMR
 I $$NEWERR^%ZTER N $ETRAP,$ESTACK S $ETRAP="D C^XMCTRAP"
 E  S X="C^XMCTRAP",@^%ZOSF("TRAP")
 K ^TMP("XMY",$J),^TMP("XMY0",$J)
 N XMHELO,XMTURN,XMLER,XMLIN,XMLINE,XMCNT
 S XMBF=1,(ER,XMCI,XMSTK)=0,XMBUF="RT",XMERC=0,XMERMSG=""
 I '$D(XMTALKER) L +^DIC(4.2,XMINST,"XMNETSEND"):0 E  S ER=1,XMTRAN="Netmail transmission in progress on another channel. (XMC1)" D TRAN Q
 D IN
 I '$D(XMINST) S XMINST=$S($D(XMSDOM):XMSDOM,$D(XMSCR):XMSCR,$D(XMB("XMSCR")):XMB("XMSCR"),1:0)
 I XMINST L -^DIC(4.2,XMINST,"XMNETSEND") Q
 E  L  Q
IN S %=$G(XMDUZ) N XMDUZ S XMDUZ=$S($G(%):%,1:.5)
 S XMTRAN="Script: "_XMSCRN_" from "_^XMB("NAME")_" beginning "_$E(DT,4,5)_"-"_$E(DT,6,7)_"-"_$E(DT,2,3) D TRAN
 D STAT(XMSCR):'$D(^XMBS(4.2999,XMSCR,0)) S %=$S($D(^XMBS(4.2999,XMSCR,3))#10:^(3),1:""),$P(%,U)=$H,^(3)=$P(%,U,1,20)
 D EN Q:$D(XMTALKER)
 I ER S XMB(4)=XMTRAN,XMTRAN=$G(XMERMSG) I XMTRAN'="" D TRAN
 S XMTRAN="Script Complete !!" D TRAN S XMER=ER
 G CLOSE^XMC3
EN I $$NEWERR^%ZTER N $ETRAP,$ESTACK S $ETRAP="D C^XMCTRAP"
 E  S X="C^XMCTRAP",@^%ZOSF("TRAP")
 D NXT Q:+XMCI<1  D INT Q:ER  G EN
INT S ER=0 S:$E(X)?1L X=$C($A(X)-32)_$E(X,2,999) I "EFCXOHMDLTSW"'[$E(X)!(X="") S ER=1,XMTRAN="Error-Invalid script command '"_X_"' at line "_XMCI_"." D TRAN Q
 S XMC1=$P(X," ",2,999),ER=0 D @$E(X) S:'$D(ER) ER=0 Q
L ;LOOK FOR STRING
 G LOOK^XMC1A
W ;WAIT FOR XMC1 SECONDS
 S XMTRAN="Waiting "_XMC1_" seconds" D TRAN H +XMC1
 Q
M ;SEND MAIL
 I '$G(XMRDOM) S (XMSDOM,XMRDOM)=XMINST
 S XMSITE=$P(^DIC(4.2,XMINST,0),U),XMTRAN="Beginning sender-SMTP service"
 D TRAN D ^XMS
 I $G(ER) S XMTRAN="ER="_$G(ER)_" - Y="_$G(Y)
 Q
D G D^XMC11
T I $D(XMTALKER) S XMCI=999999 S XMTRAN="Entering Talk mode" D TRAN Q
 Q
F S XMTRAN="Flushing buffer" D TRAN G BUFLUSH^XML ;FLUSH BUFFER
E S XMERMSG=XMC1,XMTRAN="Error message set to '"_XMERMSG_"'" D TRAN Q  ; SET ERROR MESSAGE TO BE DISPLAYED.
H G H^XMC11
S ;SEND LINE
 G SEND^XMC1A
O ;OPEN DEVICE, PROTOCOL, AND HOST
 G OPEN^XMC1A
X S XMTRAN="Xecuting "_XMC1 D TRAN X XMC1 Q
NXT S XMCI=$O(@(XMDIC_XMCI_")")) Q:+XMCI<1  S X=@(XMDIC_XMCI_",0)") Q
TRAN D TIME S:'$D(XMBF) XMBF=0
 S %=$E(XMC_" ",1,$L(XMTRAN)<245*99),%=%_$E(XMTRAN,1,245-$L(%)),XMBF=XMBF+1
 ;TRACE / DEBUG TRANSMISSION PROBLEMS
 I $D(XMS0C) S ^TMP("XMC",XMR0,XMBF,0)=%
 I $G(XM)["D" U IO(0) W !,% W:$D(XMLER) $S('XMLER:"",1:"("_XMLER_")") I IO'="",IOT'="RES" U IO
 K % Q
TIME N %,I S %=$P($H,",",2),XMC=%\3600_":"_$J(%#3600\60,2)_":"_$J(%#60,2) F I=1:1 Q:XMC'[" "  S XMC=$P(XMC," ")_0_$P(XMC," ",2,4)
 Q
INDIR ;GET INDIRECT REFERENCE
 S XMC2=$P(XMC1,"@",2,99) I '$D(@XMC2) S XMTRAN="Undefined reference to "_XMC2,ER=1 D TRAN Q
 S XMC1=@XMC2 Q
C ;CALL A SUBROUTINE
 G CALL^XMC1A
STAT(X) ;Set up zero node for 4.2999 file
 I '$D(^XMBS(4.2999,X,0)) N % S ^(0)=X,^XMBS(4.2999,"B",X,X)="",%=^XMBS(4.2999,0),$P(^(0),U,3,4)=X_U_($P(%,U,4)+1) Q
 Q
SCRIPT ;API for script processing
 I '$D(XMDUZ) S XMDUZ=$S($G(DUZ):DUZ,1:.5)
 S Y=XMSCR,XMINST=XMSCR,XMSITE=XMSCRN D ENT,KL1^XMC
 K DIC,X,Y,XMSCRN,XMSITE,XMINST,XMB,XMQ,XMUT,XMDIC,ZTPAR
 Q
