XMC3 ;(WASH ISC)/THM-SCRIPT PROCESSOR OPEN/CLOSE COMMANDS ;02/19/99  15:06
 ;;7.1;MailMan;**20,50**;Jun 02, 1994
OPEN ;OPEN COMMAND
 S (XMSITE,XMREC,XMSEN,XMPROT,XMSEC,XMDEV,XMMOD)="",XMC1=XMC1_","
 I '$G(XMINST) S XMINST=$S($G(XMSCR):XMSCR,1:0)
 S XMCC=1,(XMSSQ,XMRSQ,ER)=1,XMER=0,(XMDIAL,XMHANG)="S ER=1"
1 S Z="=" D NXT
 G A1:Y'="",2:'$D(XMINST),2:'XMINST,2:'$D(^DIC(4.2,+XMINST,0))
 S X=$S($D(ZTQUEUED)&$L($G(ZTIO)):ZTIO,$D(ZTQUEUED)&$L($G(ION)):ION,$L($G(XMIO)):XMIO,1:$P(^DIC(4.2,+XMINST,0),U,17))
 I $L(X) D D G 2:'ER,ER:'$D(ZTIO)!'$D(XMIO),ER:ZTIO'=XMIO S X=XMIO D D G ER:ER G 2
 G 2:Y=""
A1 S A=$E(Y) I "HPD"'[A S ER=1,Y="Invalid parameter "_Y D ER Q
 I A="D" S Y="'D' COMMAND no longer valid.  Use physical link fields.",ER=1 D ER Q
 S Z="),",ER=0,DIC(0)="Z" D NXT S X=Y D @A I ER D ER Q
 G 1
2 I XMPROT="" S X="SCP" D P ;Default to SCP communications protocol
 Q
H ;HOST PARAMETER PARSING
 S DIC=4.2 D ^DIC I Y<0 S ER=1,Y="Invalid Host name '"_X_"'" Q
 S XMHOST=$P(Y(0),U,12),XMSITE=$P(Y(0),U),XMINST=+Y
 N % S %=$P($G(XMB("SCRIPT")),U,6) I $L(%) S XMHOST=%
 Q
P ;PROTOCOL PARAMETER PARSING
 S DIC=3.4 D ^DIC I Y<0 S ER=1,Y="Invalid protocol name '"_X_"'" Q
 S XMPROT=$P(Y(0),U),XMSEN=^DIC(3.4,+Y,1),XMREC=^(2) S XMOPEN=$S($D(^(3)):^(3),1:""),XMCLOSE=$S($D(^(4)):^(4),1:"") Q
 Q
D ;DEVICE SPECIFICATION PARSING
 S ER=0 I $D(ZTQUEUED),IO'="" U IO G D1
 I X="" S ER=1 Q
 S %ZIS="R",IOP=X D ^%ZIS K IOP
 I POP S ER=1,Y="Device '"_X_"' could not be opened by %ZIS." Q
 S XMHANG("OPEN")=9
D1 S Y=^%ZIS(1,IOS,0),XMMOD=$P(Y,U,6),XMDEV=$P(Y,U) I $L(XMMOD),$D(^%ZIS(2,XMMOD,50)) S XMDIAL=^(50),XMHANG=^(51),XMSTAT="" S:$D(^(52)) XMSTAT=^(52)
 I IOT'="RES" U IO X ^%ZOSF("EOFF") S X=255 X ^%ZOSF("RM") X ^%ZOSF("TYPE-AHEAD")
 ;I $D(ZTQUEUED) S ZTIO(1)="D",ZTIO=ION D REQ^%ZTLOAD
 Q
ER S XMTRAN="Open error: "_Y,XMER=1 D TRAN^XMC1 Q
 Q
NXT S XMC2=XMCC F XMCC=XMCC:1:$L(XMC1) Q:Z[$E(XMC1,XMCC)
 S Y=$E(XMC1,XMC2,XMCC-1),XMCC=XMCC+1 Q
DSP F I=1:1 S J=$P("XMSITE^XMINST^XMPROT^XMSEC^XMDEV^XMREC^XMSEN^XMMOD^ER",U,I) Q:J=""  W !,J,?10,"=",@J
 W:ER !,"Error: ",Y Q
CLOSE ;CLOSE CHANNEL
 I $D(XMHANG),$L(XMHANG) X XMHANG D:$L(IO) FLUSH^XMC1A
 S XMTRAN=$S($D(XMCNT("S")):XMCNT("S"),1:0)_" sent, "_$S($D(XMCNT("R")):XMCNT("R"),1:0)_" received"_$S('$D(XMTLER):"",1:"  "_XMTLER_" retransmissions.") D TRAN^XMC1
 I '$D(ZTQUEUED),$G(XMHANG("OPEN"))=9 D ^%ZISC
 I '$D(ZTQUEUED) D HOME^%ZIS
 I $D(ZTQUEUED) S IO("C")=1 D ^%ZISC
 S %=$S($D(XMINST):XMINST,$D(XMSCR):XMSCR,1:0) I %,$D(^XMBS(4.2999,%,3)) S $P(^(3),U,1,6)="^^^^^"
 Q
