XMCTLK0 ;(WASH ISC)/CAP-TALKMAN TALK-MODE (INIT) ;4/12/93  17:23 ;
 ;;7.1;Mailman;**1003**;OCT 27, 1998
 ;;7.1;MailMan;;Jun 02, 1994
 D INIT:'$D(XMDUZ)!'$D(XMDUN)
 S DIR(0)="Y",DIR("A")="Do you want help",DIR("B")="NO" D ^DIR K DIRUT
 I $S($D(DTOUT):1,$D(DUOUT):1,'Y:1,1:0) Q
 S XQH="XMTALK-USER",%=$S($D(DUZ(0)):DUZ(0),1:"") S:$S(%="@":1,$D(^XUSEC("XMMGR",DUZ)):1,1:0) XQH="XMTALK"
 D EN^XQH Q
INIT Q:'$D(DUZ)  S Y=1 D EN^XM
 K XMA0,XMB0,XMC0,XMD0,XME0,XMF0
 G H^XUS:'$D(XMDUZ),H^XUS:'$D(XMDUN) K XMZ
 Q
