XMD ;(WASH ISC)/THM/CAP-ENTRY POINTS FOR MESSAGE SENDING ;07/18/96  13:18 [ 04/02/2003   8:29 AM ]
 ;;8.0;KERNEL;**1002,1003,1004,1005,1007**;APR 1, 2003
 ;;7.1;MailMan;**33**;Jun 02, 1994
 ;XMDF=FLAG that programmer interface is in use.  Set & killed here only.
 ;     Therefore do not check for Security Keys on domains.
 ;XMSUB=HEADER
 ;XMTEXT=@LOCATION OF MESSAGE
 ;XMSTRIP=CHARACTERS THAT USER WANTS STRIPPED FROM TEXT OF MESSAGE
 ;XMDTEST=Testing Flag / in test mode if $G(XMDTEST)=1
 ;XMDUZ=SENDER #
 ;I $D(XMMG),'$D(XMY) XMMG WILL BE THE DEFAULT FOR THE FIRST SEND TO:
 ;XMY I '$D(XMY) RECIPIENTS WILL BE PROMPTED FOR
 ;
 S XMDR=0 G T
0 K XMDR I '$D(XMSUB) S XMDR=1,XMMG="Error = No subject !" Q
 I '$D(XMTEXT) S XMDR=1,XMMG="Error = No message text !" Q
 I $G(XMDTEST)=1,$L(XMSUB)<3!($L(XMSUB)>65) S XMDR=1,XMMG="Error = Message subject too long or too short" Q
 I $G(XMDTEST)=1 S I=$O(@(XMTEXT_"0)")) I 'I S XMDR=1,XMMG="Error = No message text" Q
 I '$D(DIFROM) S XMDF=1,XMN=0
 S:'$D(XMDUZ) XMDUZ=DUZ D QQ
 S XMSUB=$$ENCODEUP^XMCU1(XMSUB)
XMZ D GET^XMA2 G OK:XMZ>0 I $D(ZTQUEUED) H 1 G XMZ
 W !!,"Waiting for access to the Message File",*7,! F %=1:1:10 H 1 W "."
 G XMZ
OK S XMQF=""
 ;
 ;Add BLOBS to message
 I $D(XMYBLOB)>9 S X=$$MULTI^XMBBLOB(XMZ) I X D KILL^XMA3 K XMZ G Q
 ;
EN1 S X=0
 I $D(XMROU)>9,'$O(^XMB(3.9,XMZ,2,0)) D NEW^XMP S X=1
EN2 S I=0,Y=XMTEXT_"0)" I '$D(XMSTRIP) S XMSTRIP=""
E0 S I=$O(@Y) G EA:'I S Y=XMTEXT_I_",0)"
 I '$D(@Y) S Y=XMTEXT_I_")" G EQ:'$D(@Y)
 S Y=@Y I Y?.E1C.E F J=1:1:$L(Y) I $E(Y,J)?1C S Y=$E(Y,1,J-1)_$E(Y,J+1,$L(Y)),J=J-1 Q:Y'?.E1C.E
 I $D(XMSTRIP) S %=XMSTRIP F  Q:'$L(%)  S A=$E(%),%=$E(%,2,99) I $L(A) S Y=$TR(Y,A,"")
 S X=X+1,^XMB(3.9,XMZ,2,X,0)=Y
EQ S Y=XMTEXT_I_")" G E0
EA S ^XMB(3.9,XMZ,2,0)="^3.92A^"_X_U_X,XCNP=X K XMSTRIP
 I $D(DIFROM)!$D(XMDSTOP) Q
 I $D(XMROU)>9 D XMROU^XMPH,^XMASEC
 K XMTEXT
EN3 ;called from XPDTP
 I $S($D(XMY)'<9:0,$D(^TMP("XMY",$J))'<9:0,1:1) D DESXM^XMA21 G QUIT:$S($D(XMY)'<9:0,$D(^TMP("XMY",$J))'<9:0,1:1)
 D REDO^XMA21,ENT1^XMAD1 G QUIT
EN ;ENTRY POINT FOR FILEGRAM PROCESS
 S XMFG=1 D SEND^XMA2 K XMFG Q
 ;
ENT ;ENTRY FOR OUTSIDE USERS
 I '$D(DUZ) W "  User ID needed (DUZ) !!" Q
 D EN^XM,SEND^XMA2
QUIT K XMDF,XMQF,XMN,%,%H,%I,A,C,ER,I,K,X,X1,X2,Y S Y=-1
 I $D(XMZ),XMZ>0,$D(^XMB(3.9,XMZ)) S Y=XMZ,Y(0)=^(XMZ,0)
 N XMKS,XMKN D ^XMAK S XMZ=Y G QQ
INIT ;FROM DIFROM
 D XMZ^XMA2 Q:XMZ<1  S $P(^XMB(3.9,XMZ,0),U,7)="X" D NEW^XMP Q
ENT1 ;FORWARD (NEED XMY, DUZ or XMDUZ,XMDUN,XMZ)
 N XMCHAN S XMCHAN=1,XMDF=1,XMQF=1
 D QQ,XMR,REDO^XMA21,D2X^XMA2 K XMDF G Q
ENT2 ;FORWARD MESSAGE / ASK RCPTS
 D QQ,XMR,DESXM^XMA21,REDO^XMA21,D2X^XMA2:$S($L($O(XMY(0))):1,$L($O(^TMP("XMY",$J,0))):1,1:0)
 G Q
 ;Get Message Zero Node
XMR S XMR=^XMB(3.9,XMZ,0) I '$D(XMDUZ) S XMDUZ=DUZ
 I $S('$D(XMDUN):1,$L(XMDUN)<3:1,$L(XMDUN)>30:1,XMDUN?1.N:1,1:0) S XMDUN=$P(^VA(200,$S(XMDUZ:XMDUZ,DUZ:DUZ,1:.5),0),U)
 Q
Q K Y,%,%0,%1,I,J,K,X1,X2,X3,X9
 K XMDUZ,XMF0,XMQ,XMANS,XMLOC,XMA0,XMDUN,XMN,XMR,XMY,XMY0,XMYBLOB
 I '$G(XMDR) K XMMG,XMDR
QQ K ^TMP("XMY",$J),^TMP("XMY0",$J)
 Q
ENX ;FROM MAILMAN
 S %=XMDUZ N XMDUZ,XMK S XMDUZ=% D XMD K % Q
 ;Binary Large OBjectss
ENL ;Add line(s)
 S XMDR="L" G T
L N XMDSTOP S X=$P($G(^XMB(3.9,XMZ,2,0)),U,3),XMDSTOP=1
 G EN2
T ;Save Text
 G TQ:$E(XMTEXT,2)'="("!'$D(XMTEXT)
 S %X=XMTEXT,(%Y,XMTEXT)="XMTEXT(" D %XY^%RCR
TQ N %,A,B,C,D,DA,DIC,DIE,DR,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T,V,W,X,Y,Z
 G @XMDR
