XMDOC ;(WASH ISC)/CAP-MAILMAN DOCUMENTATION ; 12/2/87  4:55 PM ;
 ;;7.1;Mailman;**1003**;OCT 27, 1998
 ;;7.1;MailMan;;Jun 02, 1994
 ;XM    TOP LEVEL DRIVER
 ;XMA*  LOCAL MAIL DELIVERY
 ;XMB*  BULLETINS AND TASK MANAGER INTERFACE
 ;XMC*  COMMUNICATIONS SUPPORT
 ;XMD*  FILEMAN INTERFACE MODULES
 ;XME*  ENCRYPTION LOGIC
 ;XMM*  MODEM CONTROL
 ;XMP*  PACKAGE MANAGEMENT
 ;XMR*  SMTP RECEIVER
 ;XMS*  SMTP SENDER
 ;XML*  PHYSICAL LINK COMMUNICATIONS
 ;
VAR ;VARIABLES
 ;
 ;XMA0=SCRATCH
 ;XM0=^XMB(3.7,XMDUZ,0)
 ;XMCHAN=PROTOCOL FOR NETWORK MAIL / FLAG THAT NETWORK MAIL GOING/COMING
 ;XMHOLD=ORIGINAL XMK^ORIGINAL XMDUZ
 ;XMK=MAIL BASKET
 ;XMKN=MESSAGE BASKET NAME
 ;XMKS=LAST MESSAGE IN BASKET
 ;XMOUT=FLAG FOR ABORT / TIME-OUT OR ^ ENTRY
 ;XMPRT=FLAG THAT PRINTING IS OCCURING
 ;XMR=^XMB(3.0,XMZ,0) * FROM XMA1
 ;XMRC=RECIPIENT# OF MESSAGE [^XMB(3.9,MESSAGE#,1,XMRC...]
 ;XMRL=# RESPONSES TO MESSAGE BEFORE READING/RESPONDING
 ;XMS=SCRAMBLED FLAG - IN ^TMP("XMS",$J,"S"...)
 ;XMZ*=MESSAGE NUMBERS
