XMJMC ;ISC-SF/GMB-Copy message ;06/14/99  13:35
 ;;7.1;MailMan;**50**;Jun 02, 1994
 ; Replaces ^XMA2C,^XMA2C0 (ISC-WASH/CAP)
COPY(XMDUZ,XMK,XMZ,XMFROM) ;
 N XMABORT,XMWHICH,XMLR,XMSAME,XMZREC
 D INIT(XMDUZ,XMK,XMZ,XMFROM,.XMZREC,.XMWHICH,.XMLR,.XMSAME,.XMABORT) Q:XMABORT
 D COPYIT(XMDUZ,XMZ,$P(XMZREC,U,1),XMFROM,$P(XMZREC,U,3),XMWHICH,XMLR,XMSAME)
 W *7,!,"You are now BACK at the message you were reading",!,"before invoking the copy function."
 Q
INIT(XMDUZ,XMK,XMZ,XMFROM,XMZREC,XMWHICH,XMLR,XMSAME,XMABORT) ;
 S XMZREC=^XMB(3.9,XMZ,0)
 S XMABORT=0
 D INIT^XMJMS(XMDUZ,.XMABORT) Q:XMABORT
 S XMWHICH=0
 D WHICH(XMZ,"copy",.XMWHICH,.XMABORT) Q:XMABORT
 I '$$COPYRECP^XMXSEC1(XMZ) D  Q
 . S (XMLR,XMSAME)=0
 . D SHOW^XMJERR
 D LISTR(.XMLR,.XMABORT) Q:XMABORT
 D TOSAME(.XMSAME,.XMABORT)
 Q
WHICH(XMZ,XMVERB,XMWHICH,XMABORT) ;
 N XMRESPS
 S XMRESPS=+$P($G(^XMB(3.9,XMZ,3,0)),U,4)
 I XMRESPS=0 S XMWHICH=0
 E  D WHICH^XMJMP(XMZ,XMRESPS,XMVERB,.XMWHICH,.XMABORT) Q:XMABORT!'$D(XMWHICH)
 Q:$$COPYAMT^XMXSEC1(XMZ,XMWHICH)
 S XMABORT=1
 D SHOW^XMJERR
 W !,"You may use the 'Transfer' option of the FileMan Editor"
 W !,"to move text from this message or its responses into a new message."
 Q
LISTR(XMLR,XMABORT) ;
 N DIR,Y
 S DIR("A")="List original recipients in text"
 S DIR("B")="NO",DIR(0)="Y",DIR("??")="XM-U-M-COPY-2"
 D ^DIR I $D(DIRUT) S XMABORT=1 Q
 S XMLR=Y
 Q
TOSAME(XMSAME,XMABORT) ;
 N DIR,Y
 S DIR("A")="Deliver to the same recipients"
 S DIR("B")="NO",DIR(0)="Y",DIR("??")="XM-U-M-COPY-2"
 D ^DIR I $D(DIRUT) S XMABORT=1 Q
 S XMSAME=Y
 I XMSAME W !!,"LOCAL recipients (NOT Recipients on remote network nodes) will be copied."
 Q
COPYIT(XMDUZ,XMZO,XMSUBJO,XMFROM,XMDATEO,XMWHICH,XMLR,XMSAME) ;
 ; XMWHICH   List of responses to copy
 ; XMLR     1=list original recipients in msg; 0=don't
 ; XMSAME   1=deliver to the original recipients; 0=don't
 N XMZ,XMSUBJ,XMC,XMINSTR,XMABORT
 S XMABORT=0
 D INIT^XMXADDR
 S XMSUBJ="Copy of: "_$E(XMSUBJO,1,56)
 D SUBJ^XMJMS(.XMSUBJ,.XMABORT) Q:XMABORT
 D CRE8XMZ^XMXSEND(XMSUBJ,.XMZ,1) I XMZ<1 S XMABORT=1 Q
 D:'$G(XMPAKMAN) EDITON^XMJMS(XMDUZ,XMZ)
 D CPROCESS(XMDUZ,XMZO,XMSUBJO,XMFROM,XMDATEO,XMWHICH,XMLR,XMSAME,XMZ,XMSUBJ,.XMINSTR,.XMABORT)
 D:XMABORT=DTIME HALT^XMJMS("copying")
 D:'$G(XMPAKMAN) EDITOFF^XMJMS(XMDUZ)
 D:XMABORT KILLMSG^XMXUTIL(XMZ)
 Q
CPROCESS(XMDUZ,XMZO,XMSUBJO,XMFROM,XMDATEO,XMWHICH,XMLR,XMSAME,XMZ,XMSUBJ,XMINSTR,XMABORT) ;
 N XMRESTR,XMC
 D COPYTEXT(XMZO,XMSUBJO,XMFROM,XMDATEO,XMZ,XMWHICH,.XMC)
 D:XMLR!XMSAME COPYRECP(XMLR,XMSAME,XMZO,XMZ,.XMINSTR,.XMC)
 S ^XMB(3.9,XMZ,2,0)="^3.92A^"_XMC_U_XMC_U_DT
 D BODY^XMJMS(XMDUZ,XMZ,XMSUBJ,.XMRESTR,.XMABORT) Q:XMABORT
 D TOWHOM^XMJMT(XMDUZ,"Send",.XMINSTR,.XMRESTR,.XMABORT) Q:XMABORT  ; add'l recipients
 D SENDMSG^XMJMSO(XMDUZ,XMZ,XMSUBJ,.XMINSTR,.XMRESTR,.XMABORT) Q:XMABORT  ; transmit prompt
 Q
COPYTEXT(XMZO,XMSUBJO,XMFROM,XMDATEO,XMZ,XMWHICH,XMC) ;
 N I,XMRESP,XMRANGE
 W !,"Copying text"
 S ^XMB(3.9,XMZ,2,1,0)="Original message: """_XMSUBJO_""" [#"_XMZO_"]"
 S ^XMB(3.9,XMZ,2,2,0)="From: "_$$NAME^XMXUTIL(XMFROM)
 S ^XMB(3.9,XMZ,2,3,0)="Sent: "_$$MMDT^XMXUTIL1(XMDATEO)
 S XMC=3
 F I=1:1:$L(XMWHICH,",") D
 . S XMRANGE=$P(XMWHICH,",",I)
 . Q:XMRANGE=""  ; (XMWHICH can end with a ",", giving us a null piece.)
 . F XMRESP=$P(XMRANGE,"-",1):1:$S(XMRANGE["-":$P(XMRANGE,"-",2),1:XMRANGE) D
 . . I XMRESP=0 D COPYRESP(XMRESP,XMZO,XMZ,.XMC) Q
 . . D COPYRESP(XMRESP,+$G(^XMB(3.9,XMZO,3,XMRESP,0)),XMZ,.XMC)
 Q
COPYRESP(XMRESP,XMZR,XMZ,XMC) ;
 N XMF,XMFROM,XMDT,XMZREC
 S XMC=XMC+1
 S ^XMB(3.9,XMZ,2,XMC,0)=""
 I XMRESP D
 . S XMZREC=$G(^XMB(3.9,XMZR,0))
 . S XMFROM=$$NAME^XMXUTIL($P(XMZREC,U,2))
 . S XMDT=$P(XMZREC,U,3)
 . S XMC=XMC+1
 . S ^XMB(3.9,XMZ,2,XMC,0)="Response #"_XMRESP_": "_XMFROM_"    "_$$MMDT^XMXUTIL1(XMDT)
 S XMF=.999999
 F  S XMF=$O(^XMB(3.9,XMZR,2,XMF)) Q:XMF=""  D
 . S XMC=XMC+1
 . W:XMC#50=0 "."
 . S ^XMB(3.9,XMZ,2,XMC,0)=^XMB(3.9,XMZR,2,XMF,0)
 Q
COPYRECP(XMLR,XMSAME,XMZO,XMZ,XMINSTR,XMC) ;
 N XMTO,XMNAME
 W !,"Copying recipients"
 I XMLR D
 . W " into text"
 . S XMC=XMC+1,^XMB(3.9,XMZ,2,XMC,0)=""
 . S XMC=XMC+1,^XMB(3.9,XMZ,2,XMC,0)="Original Recipients"
 . S XMC=XMC+1,^XMB(3.9,XMZ,2,XMC,0)="-------------------"
 I XMLR,XMSAME W " and"
 I XMSAME W " onto message"
 S XMTO=""
 F  S XMTO=$O(^XMB(3.9,XMZO,1,"C",XMTO)) Q:XMTO=""  D
 . I XMSAME,XMTO=+XMTO W ! D ADDR^XMXADDR(XMDUZ,"`"_XMTO,.XMINSTR)
 . Q:'XMLR
 . I +XMTO=XMTO S XMNAME=$$NAME^XMXUTIL(XMTO)
 . E  I $L(XMTO)<30 S XMNAME=XMTO
 . E  S XMNAME=$P($G(^XMB(3.9,XMZO,1,$O(^XMB(3.9,XMZO,1,"C",XMTO,0)),0)),U,1)
 . S XMC=XMC+1,^XMB(3.9,XMZ,2,XMC,0)=XMNAME
 Q
