XMJMBULL ;ISC-SF/GMB-Manual Bulletin ;06/30/98  06:31
 ;;7.1;MailMan;**50**;Jun 02, 1994
 ; Replaces BULL^XMB (ISC-WASH/THM/RWF/CAP)
 ; Entry points used by MailMan options (not covered by DBIA):
 ; BULLETIN  XMPOST
BULLETIN ; Manually post a bulletin
 N XMBIEN,XMBNAME,XMPARM,XMINSTR,XMABORT
 S XMABORT=0
 D WHICH(.XMBIEN,.XMBNAME,.XMABORT) Q:XMABORT
 D GETPARMS(XMBIEN,.XMPARM,.XMINSTR,.XMABORT) Q:XMABORT
 D BULLETIN^XMKPO(XMDUZ,XMBNAME,XMBIEN,.XMPARM,"","",.XMINSTR)
 Q
WHICH(XMBIEN,XMBNAME,XMABORT) ;
 N DIC
 S DIC(0)="AEQM",DIC="^XMB(3.6,"
 D ^DIC I Y=-1 S XMABORT=1 Q
 S XMBIEN=+Y
 S XMBNAME=$P(Y,U,2)
 Q
GETPARMS(XMBIEN,XMPARM,XMINSTR,XMABORT) ;
 N I,XMREC,XMI,DIR,Y,X,DIRUT
 S I=0
 F  S I=$O(^XMB(3.6,XMBIEN,1,I)) Q:'I  D  Q:XMABORT
 . S XMREC=^XMB(3.6,XMBIEN,1,I,0)
 . W !,XMREC
 . F  Q:XMREC'?.E1"|".N1"|".E  D  Q:XMABORT
 . . S XMI=+$P(XMREC,"|",2)
 . . S XMREC=$P(XMREC,"|",1)_$P(XMREC,"|",3,999)
 . . I XMI<0!(XMI>100) D  Q
 . . . S XMABORT=1
 . . . W !,"Aborting!  '",XMI,"' is not a valid parameter."
 . . Q:$D(XMPARM(XMI))
 . . S DIR("A")="Enter parameter "_XMI
 . . S DIR(0)="F^1:30"
 . . D ^DIR I $D(DIRUT) S XMABORT=1 Q
 . . S XMPARM(XMI)=Y
 Q:XMABORT
 S DIR("A")="Enter posting date/time"
 S DIR("B")="NOW"
 S DIR(0)="D^NOW::EFTX"
 D ^DIR I $D(DIRUT) S XMABORT=1 Q
 S:X'="NOW" XMINSTR("LATER")=$$FMTH^XLFDT(Y)
 Q
