XMSM ;(WASH ISC)/CAP-SMTP ERROR MESSAGE(S) ;06/01/99  14:23
 ;;7.1;MailMan;**4,6,13,20,50**;Jun 02, 1994
ENTR(XMNOW,XMERRMSG,XMZ,XMSUBJ,XMNVFROM,XMRCPTO,XMRCPT,XMIEN) ; NON-DELIVERY TO RECIPIENT (XMS)
 N XMTO,XMPARM,XMINSTR,XMFDA,XMIENS
 Q:XMERRMSG["554"  ; 554 reject
 S XMIENS=XMIEN_","_XMZ_","
 S XMFDA(3.91,XMIENS,3)="@"                     ; remote msg id
 S XMFDA(3.91,XMIENS,4)=XMNOW                   ; xmit date/time
 S XMFDA(3.91,XMIENS,5)=$E($P(XMERRMSG," ",2,999),1,30)  ; status
 S XMFDA(3.91,XMIENS,6)="@"                     ; path
 D FILE^DIE("","XMFDA")
 S XMTO=$$SENDER(XMZ,XMNVFROM,XMIEN,1,XMERRMSG) Q:"<>"[XMTO
 S XMINSTR("FROM")=.5
 S XMPARM(1)=XMSUBJ
 S XMPARM(2)=XMRCPTO
 S XMPARM(3)=$P(XMERRMSG," ",2,999)
 S XMPARM(4)=XMRCPT
 S XMPARM(5)=XMZ
 D TASKBULL^XMXBULL(.5,"XM SEND ERR RECIPIENT",.XMPARM,"",XMTO,.XMINSTR)
 Q
ENTE(XMSITE,XMB,XMR0) ; POSTMASTER MESSAGE ON QUEUE FAILURE (XMS0)
 N XMTEXT,XMZ,XMINSTR,XMI
 S XMINSTR("FROM")=.5,XMINSTR("ADDR FLAGS")="R"
 D STARTMSG^XMXSEND("Transmission Failure to "_XMSITE,.XMZ)
 D BODYLINE^XMXSEND(XMZ,"Transmission has failed to "_XMSITE_" a number of times.")
 D BODYLINE^XMXSEND(XMZ,"The following errors occurred:")
 D BODYLINE^XMXSEND(XMZ," ")
 S XMI=0
 F  S XMI=$O(XMB("TRIES",XMI)) Q:'XMI  D BODYLINE^XMXSEND(XMZ,XMB("TRIES",XMI))
 D BODYLINE^XMXSEND(XMZ," ")
 D BODYLINE^XMXSEND(XMZ,"A transcript of the last delivery attempt follows:")
 D BODYLINE^XMXSEND(XMZ," ")
 S XMI=0
 F  S XMI=$O(^TMP("XMC",XMR0,XMI)) Q:'XMI  D BODYLINE^XMXSEND(XMZ,^(XMI,0))
 D ENDMSG^XMXSEND(.5,XMZ,.5,.XMINSTR)
 Q
ENTS(XMTASK,XMSERVER) ; NO SERVER MESSAGE
 N XMPARM,XMINSTR
 S XMINSTR("FROM")=.5
 S XMPARM(1)=XMSERVER
 S XMPARM(2)=XMTASK
 D TASKBULL^XMXBULL(.5,"XM SEND ERR SERVER MSG",.XMPARM,"",.5,.XMINSTR)
 Q
ENTM(XMZ) ; NILL NODE FOR MESSID
 N XMPARM,XMINSTR
 S XMINSTR("FROM")=.5
 S XMTRAN="Message transmission aborted - remote message with no remote-message ID" D TRAN^XMC1
 S XMPARM(1)=XMZ
 D TASKBULL^XMXBULL(.5,"XM SEND ERR REMOTE MSG ID",.XMPARM,"",.5,.XMINSTR)
 Q
ENT(XMSITE,XMINST,XMNOW,XMERRMSG,XMZ,XMSUBJ,XMNVFROM,XMRCPT) ;
 ;If a message is rejected at a site for any reason (the whole message,
 ;not just one recipient), then this message may be sent.
 ;Currently used for 551 reject...
 ;Create new message
 N XMTO,XMPARM,XMIEN,XMNAME,XMCNT,XMINSTR
 S XMERRMSG=$P(XMERRMSG," ",2,999)
 K ^TMP("XM",$J,"REJECT")
 S XMIEN=""
 ;F  S XMIEN=$O(^XMB(3.9,XMZ,1,"AQUEUE",XMINST,XMIEN)) Q:XMIEN=""  D
 F  S XMIEN=$O(XMRCPT(XMIEN)) Q:XMIEN=""  D
 . N XMFDA,XMIENS
 . S XMIENS=XMIEN_","_XMZ_","
 . S XMFDA(3.91,XMIENS,3)="@"                ; remote msg id
 . S XMFDA(3.91,XMIENS,4)=XMNOW              ; xmit date/time
 . S XMFDA(3.91,XMIENS,5)=$E(XMERRMSG,1,30)  ; status
 . S XMFDA(3.91,XMIENS,6)="@"                ; path
 . S XMFDA(3.91,XMIENS,9)="@"                ; xmit time
 . D FILE^DIE("","XMFDA")
 . S XMNAME=$P($G(^XMB(3.9,XMZ,1,XMIEN,0)),U,1) Q:XMNAME=""
 . S XMTO=$$SENDER(XMZ,XMNVFROM,XMIEN) Q:"<>"[XMTO
 . S (XMCNT,^(XMTO))=$G(^TMP("XM",$J,"REJECT",XMTO))+1
 . S ^TMP("XM",$J,"REJECT",XMTO,XMCNT)=XMNAME
 S XMINSTR("FROM")=.5
 S XMPARM(1)=XMSUBJ
 S XMPARM(2)=XMSITE
 S XMPARM(3)=XMERRMSG
 S XMTO=""
 F  S XMTO=$O(^TMP("XM",$J,"REJECT",XMTO)) Q:XMTO=""  D TASKBULL^XMXBULL(.5,"XM SEND ERR MSG",.XMPARM,"^TMP(""XM"",$J,""REJECT"",XMTO)",XMTO,.XMINSTR)
 K ^TMP("XM",$J,"REJECT")
 Q
SENDER(XMZ,XMNVFROM,XMIEN,XMDELETE,XMERRMSG) ; Function returns 'to whom to send error message'
 N XMFWDREC,XMFWDR
 S XMFWDREC=$G(^XMB(3.9,XMZ,1,XMIEN,"F")) ; Try to find forwarder
 S XMFWDR=$P(XMFWDREC,U,2)
 I XMFWDR'="" D  Q XMFWDR  ; Forwarder is local
 . I $G(XMDELETE) D DELFWD(XMZ,XMIEN,XMFWDR,XMERRMSG)
 I $E($P(XMFWDREC,U,1))="<" Q $E($P($P(XMFWDREC,U,1),">",1),2,999)  ; Forwarder is remote
 Q:$D(^XMB(3.9,XMZ,.7)) XMNVFROM  ; Sender is remote
 N XMZREC,XMFROM
 S XMZREC=$G(^XMB(3.9,XMZ,0))
 S XMFROM=$P(XMZREC,U,2)
 I +XMFROM=XMFROM Q XMFROM  ; Sender is local
 Q ""  ; Sender is ficticious local, no notification
DELFWD(XMZ,XMIEN,XMFWDR,XMERRMSG) ; Delete user's forwarding address
 Q:+XMFWDR'=XMFWDR
 N XMFWD
 S XMFWD=$P(^XMB(3.7,XMFWDR,0),U,2) Q:XMFWD=""
 N XMINSTR,XMADDR,XMFULL,XMERROR,XMFDA,XMTXT
 S XMINSTR("ADDR FLAGS")="X" ; do not create ^TMP(, just check.
 S XMADDR=$P(^XMB(3.9,XMZ,1,XMIEN,0),U,1)
 D ADDRESS^XMXADDR(DUZ,XMFWD,.XMFULL,.XMERROR)
 I '$D(XMERROR),XMADDR'=$G(XMFULL) Q
 D DELFWD^XMVVITA(XMFWDR,XMFWD,XMERRMSG)
 Q
