XMXADDR2 ;ISC-SF/GMB- XMXADDRG (continued) ;07/06/99  07:11
 ;;7.1;MailMan;**50**;Jun 02, 1994
DISTR(XMDUZ,XMG,XMSTRIKE,XMPREFIX,XMLATER) ;
 ; XMGN     Distribution group name
 N XMGM,XMGN
 S XMGM=""
 F  S XMGM=$O(^XMB(3.8,XMG,7,"B",XMGM)) Q:'XMGM  D  I XMLATER,'$G(XMIA) Q
 . I '$D(^XMB(3.816,XMGM)) D DELETE1(XMG,7,XMGM) Q
 . S XMGN=$P(^XMB(3.816,XMGM,0),U,1) Q:XMGN=""
 . I ".S.s.D.d.G.g."'[("."_$E(XMGN,1,2)) S XMGN="G."_XMGN
 . W:$G(XMIA) !,"Distribution List: ",XMGN
 . D:'XMLATER EXPDISTR(XMDUZ,XMGM,XMGN,XMSTRIKE,XMPREFIX,XMLATER)
 Q
EXPDISTR(XMDUZ,XMG,XMGN,XMSTRIKE,XMPREFIX,XMLATER) ;
 N XMI,XMDOMAIN
 ;S:".G.g."'[("."_$E(XMG,1,2)) XMLATER=""  ; XMLATER not appropriate for Servers or Devices.
 S XMI=0
 F  S XMI=$O(^XMB(3.816,XMG,1,"B",XMI)) Q:'XMI  D
 . S XMDOMAIN=$P($G(^DIC(4.2,XMI,0)),U,1) Q:XMDOMAIN=""
 . N XMERROR,XMIA,XMVIA
 . D DNS^XMXADDRD(XMDUZ,XMDOMAIN,.XMVIA)
 . I $D(XMERROR) S ^TMP("XM",$J,"GRPERR",XMG,"D",XMGN_"@"_XMDOMAIN)=XMERROR Q
 . D SETEXP^XMXADDR(XMGN_"@"_XMDOMAIN,XMVIA,XMSTRIKE,XMPREFIX,XMLATER)
 Q
FAXGROUP(XMDUZ,XMG,XMSTRIKE,XMPREFIX,XMLATER) ;
 N XMGM,XMI
 S XMGM=""
 F  S XMGM=$O(^XMB(3.8,XMG,9,"B",XMGM)) Q:XMGM=""  D  I XMLATER,'$G(XMIA) Q
 . S XMGN=$P($G(^AKF("FAXG",XMGM,0)),U)
 . I XMGN="" D DELETE1(XMG,9,XMGM) Q
 . W:$G(XMIA) !,"Fax Group: ",XMGN
 . S XMI=""
 . F  S XMI=$O(^AKF("FAXG",XMGM,2,"B",XMI)) Q:XMI=""  D FAX(XMDUZ,XMI,XMSTRIKE,XMPREFIX,XMLATER)
 Q
FAX(XMDUZ,XMG,XMSTRIKE,XMPREFIX,XMLATER) ;
 N XMGN
 S XMGN=$P($G(^AKF("FAXR",XMG,0)),U)
 Q:XMGN=""
 W:$G(XMIA) !,"Fax Recipient: ",XMGN
 ;D SETEXP^XMXADDR("F."_XMGN,XMG,XMSTRIKE,XMPREFIX,"")  ; XMLATER not appropriate
 D:'XMLATER SETEXP^XMXADDR("F."_XMGN,XMG,XMSTRIKE,XMPREFIX,XMLATER)
 Q
FAXINDIV(XMDUZ,XMG,XMSTRIKE,XMPREFIX,XMLATER) ;
 ; XMGM     Group member
 N XMGM,XMCNT
 S XMGM="",XMCNT=0
 F  S XMGM=$O(^XMB(3.8,XMG,8,"B",XMGM)) Q:XMGM=""  D  I XMLATER,'$G(XMIA) Q
 . I '$D(^AKF("FAXR",XMGM)) D DELETE1(XMG,8,XMGM) Q
 . D FAX(XMDUZ,XMGM,XMSTRIKE,XMPREFIX,XMLATER)
 Q
DELETE1(XMGIEN,XMNODE,XMGM) ;
 N DIK,DA
 L +^XMB(3.8,XMGIEN,XMNODE):0 E  Q
 S DA=$O(^XMB(3.8,XMG,XMNODE,"B",XMGM,0))
 S DA(1)=XMGIEN
 S DIK="^XMB(3.8,"_DA(1)_","_XMNODE_","
 D ^DIK
 L -^XMB(3.8,XMGIEN,XMNODE)
 Q
DELETE2(XMGIEN,XMNODE,DA) ;
 N DIK
 L +^XMB(3.8,XMGIEN,XMNODE):0 E  Q
 S DA(1)=XMGIEN
 S DIK="^XMB(3.8,"_DA(1)_","_XMNODE_","
 D ^DIK
 L -^XMB(3.8,XMGIEN,XMNODE)
 Q
GRPERR(XMDUZ,XMG,XMGN) ; Send a bulletin about errors in groups.
 N XMGIEN,XMPARM,XMINSTR
 S XMINSTR("FROM")=.5
 S XMPARM(1)=XMGN
 S XMGIEN=0
 F  S XMGIEN=$O(^TMP("XM",$J,"GRPERR",XMGIEN)) Q:'XMGIEN  D
 . N XMTXT,XMI,XMTO
 . S XMI=0
 . I XMGIEN'=XMG D
 . . S XMI=XMI+1,XMTXT(XMI)=""
 . . S XMI=XMI+1,XMTXT(XMI)="Problems in member group: "_$P($G(^XMB(3.8,XMGIEN,0)),U,1)_" (IEN="_XMGIEN_")"
 . I $D(^TMP("XM",$J,"GRPERR",XMGIEN,"L")) D GRPTXT(XMGIEN,"L","Local Member",.XMTXT,.XMI)
 . I $D(^TMP("XM",$J,"GRPERR",XMGIEN,"R")) D GRPTXT(XMGIEN,"R","Remote Member",.XMTXT,.XMI)
 . I $D(^TMP("XM",$J,"GRPERR",XMGIEN,"D")) D GRPTXT(XMGIEN,"D","Distribution List Domain",.XMTXT,.XMI)
 . I $D(^TMP("XM",$J,"GRPERR",XMGIEN,"C")) D GRPTXT(XMGIEN,"C","Circular Group Reference",.XMTXT,.XMI)
 . S XMTO(XMDUZ)=""  ; Person sending the message
 . D GRPADDR(XMG,.XMTO)
 . I XMG'=XMGIEN D GRPADDR(XMGIEN,.XMTO)
 . D TASKBULL^XMXBULL(XMDUZ,"XM GROUP ERROR",.XMPARM,"XMTXT",.XMTO,.XMINSTR)
 Q
GRPTXT(XMGIEN,XMTYPE,XMPROB,XMTXT,XMI) ;
 N XMNAME,XMERROR
 S XMNAME=""
 F  S XMNAME=$O(^TMP("XM",$J,"GRPERR",XMGIEN,XMTYPE,XMNAME)) Q:XMNAME=""  D
 . S XMI=XMI+1,XMTXT(XMI)=""
 . S XMI=XMI+1,XMTXT(XMI)=XMPROB_": "_XMNAME
 . S XMI=XMI+1,XMTXT(XMI)="Error: "_^TMP("XM",$J,"GRPERR",XMGIEN,XMTYPE,XMNAME)
 Q
GRPADDR(XMGIEN,XMTO) ;
 N I
 S I=$P($G(^XMB(3.8,XMGIEN,3)),U,1)  ; Organizer
 S:I XMTO(I)=""
 S I=$P($G(^XMB(3.8,XMGIEN,0)),U,7)  ; Coordinator
 S:I XMTO(I)=""
 Q:'$D(^XMB(3.8,XMGIEN,4,"B"))
 S I=0
 F  S I=$O(^XMB(3.8,XMGIEN,4,"B",I)) Q:'I  D
 . S XMTO(I)=""  ; Authorized sender
 Q
