XMYPOSTA ;SFISC/GMB - Post-patch stuff ;07/06/99  07:01
 ;;7.1;MailMan;**50**;Jun 02, 1994
MEDSYN ;
 D INIT
 D SYNONYM^XMUDNC
 Q
INIT ; Load table into global
 N DIK,I,X
 K ^DOPT("XMSYN",$J)
 S DIK="^DOPT(""XMSYN"",$J,"
 S ^DOPT("XMSYN",$J,0)="Domain Synonyms^1N^"
 F I=1:1 S X=$T(T+I) Q:X=" ;;"  S ^DOPT("XMSYN",$J,I,0)=$E(X,4,255)
 D IXALL^DIK
 Q
T ;;current site name^new site name
 ;;ALLEN-PARK.VA.GOV^DETROIT.MED.VA.GOV
 ;;AMARILLO.VA.GOV
 ;;BATH.VA.GOV
 ;;BATTLE-CREEK.VA.GOV
 ;;BECKLEY.VA.GOV
 ;;BILOXI.VA.GOV
 ;;BONHAM.VA.GOV
 ;;BOSTON.VA.GOV
 ;;BROCKTON.VA.GOV
 ;;BRONX.VA.GOV
 ;;CHAMPVA.DENVER.VA.GOV^HAC.MED.VA.GOV
 ;;CHEYENNE.VA.GOV
 ;;CHICAGO-LAKE.VA.GOV
 ;;CHICAGO-WEST.VA.GOV       
 ;;CHILLICOTHE.VA.GOV
 ;;CLEVELAND.VA.GOV
 ;;COLUMBIA-MO.VA.GOV
 ;;COLUMBUS.VA.GOV
 ;;DALLAS.VA.GOV
 ;;DANVILLE.VA.GOV
 ;;DAYTON.VA.GOV
 ;;ERIE.VA.GOV
 ;;FARGO.VA.GOV
 ;;FAYETTVL-AR.VA.GOV
 ;;FAYETTVL-NC.VA.GOV
 ;;FORT-MEADE.VA.GOV^BLACK-HILLS.MED.VA.GOV
 ;;FT-HARRISON.VA.GOV^MONTANA.MED.VA.GOV
 ;;GAINESVILLE.VA.GOV^NORTH-FLORIDA.MED.VA.GOV
 ;;GRAND-ISLAND.VA.GOV
 ;;HAMPTON.VA.GOV
 ;;HOT-SPRINGS.VA.GOV
 ;;HUNTINGTON.VA.GOV
 ;;IMMUNOLOGY.VA.GOV
 ;;IOWA-CITY.VA.GOV
 ;;IRON-MTN.VA.GOV
 ;;ISC-ALBANY.VA.GOV^CIOFO-ALBANY.MED.VA.GOV
 ;;ISC-BAYPINES.VA.GOV^CIOFO-BAYPINES.MED.VA.GOV
 ;;ISC-BIRM.VA.GOV^CIOFO-BIRM.MED.VA.GOV
 ;;ISC-CHICAGO.VA.GOV^CIOFO-HINES.MED.VA.GOV
 ;;ISC-DALLAS.VA.GOV^CIOFO-DALLAS.MED.VA.GOV
 ;;ISC-SF.VA.GOV^CIOFO-SF.MED.VA.GOV
 ;;ISC-SLC.VA.GOV^CIOFO-SLC.MED.VA.GOV
 ;;ISC-WASH.VA.GOV^CIOFO-WASH.MED.VA.GOV
 ;;JACKSON.VA.GOV
 ;;KANSAS-CITY.VA.GOV
 ;;LEBANON.VA.GOV
 ;;LEXINGTON.VA.GOV
 ;;LINCOLN.VA.GOV
 ;;MANCHESTER.VA.GOV
 ;;MARION-IL.VA.GOV
 ;;MARION-IN.VA.GOV^NORTHERN-INDIANA.MED.VA.GOV
 ;;MARTINEZ.VA.GOV
 ;;MIAMI.VA.GOV
 ;;MILES-CITY.VA.GOV
 ;;MILWAUKEE.VA.GOV
 ;;MTN-HOME.VA.GOV
 ;;N-CHICAGO.VA.GOV
 ;;NASHVILLE.VA.GOV
 ;;NEW-ORLEANS.VA.GOV
 ;;NORTHPORT.VA.GOV
 ;;PHILADELPHIA.VA.GOV
 ;;POPLAR-BLUFF.VA.GOV
 ;;PORTLAND.VA.GOV
 ;;PRESCOTT.VA.GOV
 ;;RENO.VA.GOV
 ;;RICHMOND.VA.GOV
 ;;SAGINAW.VA.GOV
 ;;SALISBURY.VA.GOV
 ;;SAN-JUAN.VA.GOV
 ;;SANFRANCISCO.VA.GOV
 ;;SPOKANE.VA.GOV
 ;;ST-CLOUD.VA.GOV
 ;;TEMPLE.VA.GOV^CENTRAL-TEXAS.MED.VA.GOV
 ;;TOMAH.VA.GOV
 ;;TUCSON.VA.GOV
 ;;WALLA-WALLA.VA.GOV
 ;;WEST-PALM.VA.GOV
 ;;WILMINGTON.VA.GOV
 ;;
