BAR50P4B ; IHS/DIT/CPC - MATCH REASONS AND CLAIMS PART3; 20200205
 ;;1.8;IHS ACCOUNTS RECEIVABLE;**29,31**;OCT 26,2005;Build 90
 ;;IHS/DIT/CPC NEW ROUTINE - OVERFLOW CODE FROM BAR50P04
 ;BAR*1.8*31;OIT.IHS.FCJ CR#6984 REQ 2 add test to prt detail
 Q
 ;
SETREA ;EP SET CAT & REA INTO E-CLM
 K DIC,DIE,DR,DA
 S DIE=$$DIC^XBDIQ1(90056.0208)
 S DA(2)=IMPDA
 S DA(1)=CLMDA,DA=ADJDA
 S DR=".04////^S X=ACAT;.05////^S X=AREA"
 D ^DIE
 Q
 ;
HIPAAR2 ;Match HIPAA std codes to RPMS
 S REA=$P($G(^BAREDI("I",DUZ(2),IMPDA,30,CLMDA,30,ADJDA,0)),U,3)
 I REA="" D  ;
 .W !,"Standard adjustment reason not sent on RA."
 .S REAFLG=0
 .S REATYP="RF"
 .S ERRORS("RF")=""
 S ACAT=$P($G(^BAREDI("I",DUZ(2),IMPDA,30,CLMDA,30,ADJDA,0)),U,4)
 S AREA=$P($G(^BAREDI("I",DUZ(2),IMPDA,30,CLMDA,30,ADJDA,0)),U,5)
 K DIC,DR,DA
 S DIC="^BARADJ("
 S X=$P(REA," ")
 S DIC(0)="XZ"
 D ^DIC
 I +Y<1 D  Q
 .W !,"Standard adjustment reason ",X," not in standard table."
 .S REAFLG=0
 .S REATYP="RT"
 .S ERRORS("RT")=""
 S READA=+Y
 ;No RPMS cat/type in table
 I $P(Y(0),U,3)=""!($P(Y(0),U,4)="") D  ;
 .W !,"Can't map standard adjustment reason ",X," to RPMS."
 .S REAFLG=0
 .S REATYP="RU"
 .S ERRORS("RU")="" ;BAR*1.8*5 SRS-80 TPF
 K DIC,DA,DR,DIE
 S DIE=$$DIC^XBDIQ1(90056.0208)
 S DA(2)=IMPDA
 S DA(1)=CLMDA
 S DA=ADJDA
 S DR=".04////^S X=$P(Y(0),U,3)"
 S DR=DR_";.05////^S X=$P(Y(0),U,4)"
 D ^DIE
 Q
 ;
RABILL ;Write RA data
 ;W !,$$EN^BARVDF("RVN")  ;bar*1.8*20
 ;W "ERA"  ;bar*1.8*20
 ;W ?4,$E($$GET1^DIQ(90056.0205,BAREIENS,.01),1,15)  ;BILL/RX  ;bar*1.8*20 REQ4
 S X=$$GET1^DIQ(90056.0205,BAREIENS,.08)
 D ^%DT
 S BARRADT=Y  ;DOS begin
 W !,$$EN^BARVDF("RVN")
 W "ERA"  ;
 W ?4,$E($$GET1^DIQ(90056.0205,BAREIENS,.01),1,15)  ;BILL/RX
 W ?20,$$SDT^BARDUTL(BARRADT)  ;DOS begin
 W ?31,$E($$GET1^DIQ(90056.0205,BAREIENS,.06),1,25)  ;Pt name
 W ?57,$J($FN($$GET1^DIQ(90056.0205,BAREIENS,.05),",",2),10)  ;Billed
 W $$EN^BARVDF("RVF")
 Q
 ;
ARBILL ;Loop & write AR data
 N BARBILL,BARBIEN
 S (BARBILL,BARCNT2)=0
 F  S BARBILL=$O(BARTEMP(BARBILL)) Q:'+BARBILL  D
 .S BARBIEN=0
 .F  S BARBIEN=$O(BARTEMP(BARBILL,BARBIEN)) Q:'+BARBIEN  D
 ..S BARBDT=$$GET1^DIQ(90050.01,BARBIEN,102,"I")
 ..I $$GET1^DIQ(90050.01,BARBIEN,15)']0,(BARBDT'=BARRADT) Q  ;ONLY DISPLAY 0 BALANCE WHEN DOS MATCHES BAR*1.8*29 CPC
 ..S BARCNT2=BARCNT2+1
 ..W !,$J(BARCNT2,2),")"
 ..W ?4,$E($$GET1^DIQ(90050.01,BARBIEN,.01),1,20)  ;expanded ck# to 20 chars  bar*1.8*22 SDR
 ..W ?20,$$SDT^BARDUTL(BARBDT)
 ..W ?31,$E($$GET1^DIQ(90050.01,BARBIEN,101),1,25)
 ..W ?52,$J($FN($$GET1^DIQ(90050.01,BARBIEN,13),",",2),10)
 ..W ?68,$J($FN($$GET1^DIQ(90050.01,BARBIEN,15),",",2),10)
 ..S BARTMP2(BARCNT2)=BARBIEN
 Q
 ;
CHOOSE ;Choose bill from AR
 K DIR
 S DIR(0)="SABO^B:Bill Inquire;H:History;M:Match to Item;N:Not Matched;Q:Quit"
 S DIR("A")="Enter (B)ill Inquire,(H)istory,(M)atch to Item,(N)ot Matched,(Q)uit: "
 D ^DIR
 I $D(DTOUT)!$D(DUOUT)!$D(DIRUT)!$D(DIROUT) S BARANS=0,BARSEL="" Q
 S BARSEL=Y  ;bar*1.8*28 IHS/SD/SDR CR9572 HEAT258378
 I BARSEL="N"!(BARSEL="Q") S BARANS=0 Q  ;not matched
 K DIR
 S DIR(0)="NAO^1:"_BARCNT2
 S DIR("A")="Which Entry: "
 S DIR("?")="Enter a number between 1 and "_BARCNT2
 D ^DIR
 I $D(DIROUT)!$D(DUOUT)!$D(DIRUT)!$D(DTOUT) S BARANS=0 Q
 S BARANS1=$G(BARTMP2(Y)),BARANS=Y
 I BARSEL="H" D
 .D EN^BARPST5(BARANS1)
 I BARSEL="B" D
 .D DIQ^XBLM(90050.01,BARANS1)
 Q
 ;
ADDREAS(IMPDA,CLMDA,ERRORS,SHOWMSG) ;EP - ADD RSN NOT SENT TO 'RSN NOT TO POST MULTIPLE'
 ;ADDREAS(IMPDA,CLMDA,ERRORS) ;EP (private)  ;BAR*1.8*29
 S SHOWMSG=$G(SHOWMSG)
 N REASON,STAT,ERRDA,CURSTAT
 S REASON=""
 F  S REASON=$O(ERRORS(REASON)) Q:REASON=""  D
 .I REASON="CT" D STAT(IMPDA,CLMDA)
 .I SHOWMSG D
 ..S ERRDA=$O(^BARERR("B",REASON,""))
 ..S BARMSG=$J("",7)_$$GET1^DIQ(90056.21,ERRDA_",",.02,"E")
 ..;W !,BARMSG  ;BAR*1.8*31
 ..W:$G(BARDSP) !,BARMSG ;BAR*1.8*31;OIT.IHS.FCJ CR#6984 REQ 2
 ..I SHOWMSG D INS^BAR50DET(BARMSG,0)
 .K DIC,DIE,DR,DA,DIR
 .S DIC("P")=$P(^DD(90056.0205,401,0),U,2)
 .S DA(2)=IMPDA
 .S DA(1)=CLMDA
 .S DIC(0)="L"
 .S DIC="^BAREDI(""I"",DUZ(2),"_DA(2)_",30,"_DA(1)_",4,"
 .S X=REASON
 .D ^DIC
 .K ERRORS(REASON)
 Q
 ;
DELREAS(IMPDA,CLMDA,RMVMM) ;EP -CLR 'RSN NOT TO POST' MULTIPLES IN ERA FILE
 ;RMVMM = Remove manual matching codes too
 N REASDA,BARIENS,BARREAMM,BARREABM,BARREADM,BARMAT
 K DA,DIR,DIC,DIE,DR
 S REASDA=0,BARREAMM=0,BARREABM=0,BARREADM=0,BARMMTCH=0,RMVMM=$G(RMVMM)
 F  S REASDA=$O(^BAREDI("I",DUZ(2),IMPDA,30,CLMDA,4,REASDA)) Q:'REASDA  D
 .;IHS/DIT/CPC BAR*1.8*29 CR 6982 & 10777 Quit if manual match reason codes are present.
 .S BARMAT=0
 .I ('RMVMM)&($$MMRSN^BAR50P4C(^BAREDI("I",DUZ(2),IMPDA,30,CLMDA,4,REASDA,0))) S BARMAT=1,BARMMTCH=1
 .I BARMAT=1 Q
 .S DA(2)=IMPDA
 .S DA(1)=CLMDA
 .S DIE="^BAREDI(""I"","_DUZ(2)_","_DA(2)_",30,"_DA(1)_",4,"
 .S DA=REASDA
 .S DR=".01///@"
 .D ^DIE
 Q:$G(BARMAT)=1  ;Quit if manually matched IHS/DIT/CPC BAR*1.8*29 CR 6982 & 1077
 K DA,DR,DIE,DIC,DIR
 S DIE=$$DIC^XBDIQ1(90056.0205)
 S DR=""  ;REQ4
 S IENS=CLMDA_","_IMPDA_","  ;REQ4
 ;I $$GET1^DIQ(90056.0205,IENS,71)="" S DR=".02///C"  ;'STATUS' FLD CLM UNMATCHED ;REQ4
 I $$GET1^DIQ(90056.0205,IENS,.02)=""!($$GET1^DIQ(90056.0205,IENS,.02,"I")="B") S DR=".02///C"  ;'STATUS' FLD CLM UNMATCHED IHS/DIT/CPC - BAR*1.8*28
 S DR=DR_";501///@"  ;'POST CLM AS TYPE'
 S DR=DR_";601///@"  ;'PYMT CRDT APPLIED TO'
 S DR=DR_";602///@"  ;'PYMT CRDT APPLIED FROM'
 S DA(1)=IMPDA
 S DA=CLMDA
 D ^DIE
 K DA,DR,DIE,DIC,DIR
 Q
 ;
STAT(IMPDA,CLMDA) ;EP private
 K DR,DIE,DA
 S DIE=$$DIC^XBDIQ1(90056.0205)
 S STAT="C"
 S DR=".02///^S X=STAT"
 S DA(1)=IMPDA
 S DA=CLMDA
 D ^DIE
 Q
 ;
INDEX ;EP
 S QFLG=0
 W !,"Processing Claim Status"   ; using claim Index ",INDEX,!
 K ^XTMP("BAR-LIST_DETAIL",$J,DUZ(2))
 K ^XTMP("BAR-LIST",$J,DUZ(2))
 S BARDBG=1  ;1=build detail matching report  ;IHS/DIT/CPC - BAR*1.8*28
 S BARMSG="PERFORMING TRADITIONAL HIPAA CHECKS...("_$$FTYPE()_")" W !,BARMSG
 I $G(BARDBG) D INS^BAR50DET(BARMSG,0)
 K BARFLG
 S CLMDA=0 F  S CLMDA=$O(^BAREDI("I",DUZ(2),IMPDA,30,CLMDA)) Q:'CLMDA  S ^XTMP("BAR-LIST",$J,DUZ(2),$P($G(^BAREDI("I",DUZ(2),IMPDA,30,CLMDA,0)),U),CLMDA)=""
 S CLMCNT=0,BARBL=""
 ;F  S BARBL=$O(^XTMP("BAR-LIST",$J,DUZ(2),BARBL)) Q:BARBL=""  D  Q:QFLG=1  ;bar*1.8*26 IHS/SD/SDR HEAT170856
 F  S BARBL=$O(^XTMP("BAR-LIST",$J,DUZ(2),BARBL)) Q:BARBL=""!($G(QFLG))  D  ;bar*1.8*26 IHS/SD/SDR HEAT170856
 .S CLMDA=0
 .Q:$G(QFLG)=1
 .;F  S CLMDA=$O(^XTMP("BAR-LIST",$J,DUZ(2),BARBL,CLMDA)) Q:'CLMDA  K ERRS D CLMFLG(CLMDA,.ERRORS)  Q:$G(QFLG)=1  ;bar*1.8*26 IHS/SD/SDR HEAT170856
 .F  S CLMDA=$O(^XTMP("BAR-LIST",$J,DUZ(2),BARBL,CLMDA)) Q:'CLMDA!($G(QFLG))  K ERRS D CLMFLG^BAR50P04(CLMDA,.ERRORS)  ;bar*1.8*26 IHS/SD/SDR HEAT170856
 Q:$G(QFLG)=1  ;bar*1.8*29 IHS/SD/SDR HEAT170856
 S BARFLG=$$EN^BAR50P0Z(IMPDA)  ;PLB/Pymt Rev/Neg pymt amt chks
 ;old D:$$IHS^BARUFUT(DUZ(2)) NEGBAL^BAR50EB(IMPDA,"ERA") ;CHK FOR NEG BAL IN RPMS BILLS
 D NEGBAL^BAR50EB(IMPDA,"ERA")  ;note:IHS/TRIBAL CHK INSIDE BAR50EB CHK FOR NEG BAL IN RPMS BILLS HEAT147572 MOD: 2/5/2014
 ;NOTE: MATCHED PYMTS & CREDITS W/HAVE THE 'POST THIS CLM AS TYPE' FLD = TO 20=PYMT CREDIT
 ;D:$$IHS^BARUFUT(DUZ(2)) NONPAYCH^BAR50EP1(IMPDA) ;CHK PYMTS NOT MATCHED TO REV TO SEE IF BEING POSTED TO 'NONPYMT' BATCH ;bar*1.8*26 IHS/SD/POT HEAT170856
 ;D:$$IHSNEGB^BARUFUT(DUZ(2)) NONPAYCH^BAR50EP1(IMPDA)  ;bar*1.8*26 IHS/SD/POT HEAT170856
 D:$$IHSNEGB^BARUFUT(DUZ(2)) NONPAYCH^BAR50EP1(IMPDA)  ;bar*1.8*26 IHS/SD/POT HEAT170856 ;BAR*1.8*29 IHSNEGB returns false if neg posting is allowed
 ;K ERRORS
 Q
 ;
FTYPE() ;
 Q "5010"
