BARCHKU1 ; IHS/SD/CPC - Check Number utilities;07/05/2020
 ;;1.8;IHS ACCOUNTS RECEIVABLE;**30**;OCT 26, 2005;Build 55
 ;;New routine BAR*1.8*30 - IHS/SD/CPC
 ;
 Q
PRTFMT(NMBR,LENGTH)  ;EP GIVEN NMBR TRUNCATE TO LENGTH-1 AND APPEND ASTERISK
 S:$L(NMBR)>LENGTH NMBR=$E(NMBR,1,LENGTH-1)_"*"
 Q NMBR
 ;
PRTFMTEX(NMBR,LENGTH) ;EP GIVEN NMBR EXPAND TO LENGTH WITH SPACES
 N X
 S X=0
 F X=$L(NMBR):1:LENGTH S NMBR=NMBR_" "
 Q NMBR
 ;
CHKLIST  ;?? HELP LISTER CALLED BY BARCHKLU
 N CHKNO,BATCH,BATCHID,BATNM,COLPTNM,DIR,TDN,ESC,Z
 S CHKNO="",ESC=0,Z=0
 W !,"Choose from:",!
 F  S CHKNO=$O(^BARCOL(DUZ(2),"D",CHKNO)) Q:CHKNO']""!(ESC)  D
 .S BATCHID=""
 .F  S BATCHID=$O(^BARCOL(DUZ(2),"D",CHKNO,BATCHID)) Q:BATCHID']""!(ESC)  D
 ..S BATCH=$G(^BARCOL(DUZ(2),BATCHID,0))
 ..S COLPTNM=$P($G(^BAR(90051.02,DUZ(2),$P(BATCH,U,2),0)),U,1)
 ..S BATNM=$P(BATCH,U,1)
 ..S TDN=$P(BATCH,U,28)
 ..W CHKNO,"  ",BATNM,"  ",COLPTNM,"  ",TDN,!
 ..S Z=Z+1
 ..I (Z#10)=0 N DIR S DIR(0)="Y",DIR("B")="YES",DIR("A")="Continue" D ^DIR K DIR W ! S:'Y!$G(DIROUT)!$G(DUOUT)!$G(DTOUT)!$G(DROUT) ESC=1 Q
 ..;I $Y>(IOSL-2) D EOP^BARUTL(0) W @IOF S Z=0
 ..S:$G(DIROUT)!$G(DUOUT)!$G(DTOUT)!$G(DROUT) ESC=1
 Q
