BARRASME ; IHS/SD/LSL - Age Summary Report Print Logic ;7/28/2020
 ;;1.8;IHS ACCOUNTS RECEIVABLE;**30**;OCT 26, 2005;Build 55
 ;NEW ROUTINE BAR*1.8*30
 ;BAR*1.8*30 CR4968 - MODIFY UFMS REPORT SUMMARIZED BY BILL W/IN PAYER W/IN ALLOW CAT
 ;
 Q
 ; *********************************************************************
DELIM  ;
 N FY,PFAC,ALLCAT,ARACCT,BILLNUM,C,VSTLOC,VSUFAC
 N PSUFAC,TPIEN,UFMSINV,CURR,THIRTY,SIXTY,NINETY,OVER,BAL
 I '$D(BARA),(XQY0'["UFMS") Q
 I '(($G(BARY("RTYP"))=3)&($G(BARY("STCR"))=5)) Q
 I $G(BARDELIM)="CSV" W "FISCAL YEAR,ALLOWANCE CATEGORY,VISIT LOCATION,VISIT LOCATION ASUFAC,BILLING LOCATION,BILLING LOCATION ASUFAC,3P IEN,UFMS INVOICE NUMBER,A/R ACCOUNT,BILL NUMBER,CURRENT,30-60,61-90,91-120,120+,BALANCE",!
 I $G(BARDELIM)="XML" D XML
 S C=","
 S FY=""   ;FY
 F  S FY=$O(^TMP($J,"BAR-ASMFY",FY)) Q:FY']""  D
 .S PFAC=""  ;FACILITY
 .F  S PFAC=$O(^TMP($J,"BAR-ASMFY",FY,PFAC)) Q:PFAC']""  D
 ..S ALLCAT=""  ;ALLOWANCE CATEGORY
 ..F  S ALLCAT=$O(^TMP($J,"BAR-ASMFY",FY,PFAC,ALLCAT)) Q:ALLCAT']""  D
 ...S ARACCT="" ;A/R ACCOUNT
 ...F  S ARACCT=$O(^TMP($J,"BAR-ASMFY",FY,PFAC,ALLCAT,ARACCT)) Q:ARACCT']""  D
 ....S BILLNUM=""
 ....F  S BILLNUM=$O(^TMP($J,"BAR-ASMFY",FY,PFAC,ALLCAT,ARACCT,BILLNUM)) Q:BILLNUM']""  D
 .....S VSTLOC=$P(^TMP($J,"BAR-DEMFY",FY,PFAC,ALLCAT,ARACCT,BILLNUM,1),U,4)
 .....S PSUFAC=$E($P(^TMP($J,"BAR-DEMFY",FY,PFAC,ALLCAT,ARACCT,BILLNUM,1),U,1),1,6)
 .....;S VSUFAC=$E($P(^TMP($J,"BAR-DEMFY",FY,PFAC,ALLCAT,ARACCT,BILLNUM,1),U,2),1,6)
 .....;S TPIEN=$P($P(^TMP($J,"BAR-DEMFY",FY,PFAC,ALLCAT,ARACCT,BILLNUM,1),U,2),"-",2)
 .....;FOUND IN BETA TESTING ;IHS\SD\CPC ;BAR*1.8*30 CR4976/11205
 .....S VSUFAC=$E($P(^TMP($J,"BAR-DEMFY",FY,PFAC,ALLCAT,ARACCT,BILLNUM),U,2),7,12)
 .....S TPIEN=$E($P(^TMP($J,"BAR-DEMFY",FY,PFAC,ALLCAT,ARACCT,BILLNUM),U,2),13,$L($P(^TMP($J,"BAR-DEMFY",FY,PFAC,ALLCAT,ARACCT,BILLNUM),U,2)))
 .....S UFMSINV="'"_$P(^TMP($J,"BAR-DEMFY",FY,PFAC,ALLCAT,ARACCT,BILLNUM),U,2)
 .....S UFMSINV="'"_$P(^TMP($J,"BAR-DEMFY",FY,PFAC,ALLCAT,ARACCT,BILLNUM),U,2)
 .....S CURR=$P(^TMP($J,"BAR-ASMFY",FY,PFAC,ALLCAT,ARACCT,BILLNUM),U,4)    ;0-30
 .....S THIRTY=$P(^TMP($J,"BAR-ASMFY",FY,PFAC,ALLCAT,ARACCT,BILLNUM),U,5)  ;31-60
 .....S SIXTY=$P(^TMP($J,"BAR-ASMFY",FY,PFAC,ALLCAT,ARACCT,BILLNUM),U,6)   ;61-90
 .....S NINETY=$P(^TMP($J,"BAR-ASMFY",FY,PFAC,ALLCAT,ARACCT,BILLNUM),U,7)  ;91-120
 .....S OVER=$P(^TMP($J,"BAR-ASMFY",FY,PFAC,ALLCAT,ARACCT,BILLNUM),U,8)    ;120+
 .....S BAL=$P(^TMP($J,"BAR-ASMFY",FY,PFAC,ALLCAT,ARACCT,BILLNUM),U,9)     ;BAL
 .....I $G(BARDELIM)="CSV" W FY_C_""""_ALLCAT_""""_C_""""_VSTLOC_""""_C_VSUFAC_C_""""_PFAC_""""_C_PSUFAC_C_TPIEN_C_UFMSINV_C_""""_ARACCT_""""_C_BILLNUM_C_CURR_C_THIRTY_C_SIXTY_C_NINETY_C_OVER_C_BAL,!
 .....I $G(BARDELIM)="XML" D XLDETDAT^BARRAXL1
 I $G(BARDELIM)="XML" D XMLEND
 Q
 ;
XML  ;
 D XMLHDR^BARRAXL1
 D XMLWRKBK^BARRAXL1
 D STYLEBEG^BARXML4
 D S16^BARXML4
 D S102^BARXML10
 D S103^BARXML10
 D S104^BARXML10
 D S105^BARXML10
 D S113^BARXML11
 D S114^BARXML11
 D S115^BARXML11
 W "</Styles>",!
 D XLDETWSB^BARRAXL1
 Q
XMLROW  ;
 Q
XMLEND   ;
 D XLDETWSE^BARRAXL1
 W "</Workbook>",!
 Q
