BARRMKU1 ;IHS/SD/CPC - REMARK CODE UTILITIES ;08/05/2020
 ;;1.8;IHS ACCOUNTS RECEIVABLE;**30**;OCT 26, 2005;Build 55
 ;
 ;IHS/SD/CPC - BAR*1.8*30 New Routine to process A/R EDI REMARK CODES updates
 ;
 Q
LOADFIL  ;EP Pulls in txt file
 ;with row format of CODE^SHORT DESCRIPTION^LONG DESCRIPTION<CR>
 K ^BARTMP("BARMKCD"),^BARTMP("BARMKCDA"),^BARTMP("BARMKCDB")
 S DIR(0)="F"
 S DIR("A")="Enter the directory path for the remark code update file"
 S BARPATH=$P($G(^BAR(90052.06,DUZ(2),DUZ(2),0)),U,17)
 S DIR("B")=BARPATH
 S DIR("?")="For example enter '/usr/mydir/'"
 D ^DIR
 K DIR
 Q:$D(DIRUT)
 ; Path
 S XBDIR=X
 D FNAME^BAREDIUT
 S HSTFILE=$G(XBFN)
 Q:HSTFILE=""
 W !!,"CHECKING FILE FORMAT....."
 S BARCTRL=0
 S POP=0 D READ(XBDIR,HSTFILE) I POP QUIT
 Q
 ;
READ(BARPATH,BARFILE)   ; EP
 ; Read host file into ^BARTMP("BARMKCD")
 Q:BARPATH=""
 Q:BARFILE=""
 K ^BARTMP("BARMKCD")
 N BARCNT,BARTXT,BARDONE
 S (BARCNT,BARDONE)=0
 D OPEN^%ZISH("BARMKCD"_$J,BARPATH,BARFILE,"R")
 I POP D  Q
 .W !!,"Error opening file....please verify filename and directory and try again"
 .S BARDONE=1
 .D EOP^BARUTL(1)
 D READTST
 D CLOSE^%ZISH("BARMKCD"_$J)
 H 5
 D OPEN^%ZISH("BARMKCD"_$J,BARPATH,BARFILE,"R")
 I BARFTYP="STREAM" F  D STREAM Q:+BARDONE
 I BARFTYP'="STREAM" F  D CRLF Q:+BARDONE
 D CLOSE^%ZISH("BARMKCD"_$J)
 Q
 ; ********************************************************************
 ;
READTST   ;
 ; Test file type
 U IO
 R BARTXT#200:300          ;Direct read of flat file
 I $L(BARTXT)>120 S BARFTYP="STREAM" Q
 S BARFTYP="CR/LF"
 Q
 ; ********************************************************************
 ;
STREAM   ;
 U IO
 R BARTXT#1024:300           ;Direct read of flat file
 I $$STATUS^%ZISH D
 .S BARCNT=BARCNT+1
 .S:BARTXT]"" ^BARTMP("BARMKCD",BARCNT)=BARTXT
 .S BARTXT=""
 .S BARDONE=1 Q
 S BARCNT=BARCNT+1
 S:BARTXT]"" ^BARTMP("BARMKCD",BARCNT)=BARTXT
 Q
 ; ********************************************************************
 ;
CRLF   ;
 U IO
 R BARTXT:300
 I $$STATUS^%ZISH!'+$L(BARTXT) S BARDONE=1 Q
 S BARCNT=BARCNT+1
 S ^BARTMP("BARMKCD",BARCNT)=BARTXT
 Q
 ;
PROC  ;CREATE BARTMP ENTRIES TO USE LATER IN MERGE
 K ^BARTMP("BARMKCDA"),^BARTMP("BARMKCDB"),CODE,LDESC,LN1,LN2,ROW1,RPMSDT,SDESC,V,WP,WRCBEGDT,WRCENDDT,WRCMODDT
 S (ROW1,LN1,LN2,V)=0
 F  S ROW1=$O(^BARTMP("BARMKCD",ROW1)) Q:ROW1']""  D
 .S LN1=^BARTMP("BARMKCD",ROW1)
 .I '(($F(LN1,"~")<6)&($F(LN1,"~")>0)) D
 ..D LDESC(LN1,CODE,.WP)
 ..S NODE="BARMKCDA"
 ..D WLDESC(NODE,CODE,RPMSDT,.WP)
 .;
 .I ($F(LN1,"~")<6)&($F(LN1,"~")>0) D
 ..K WP S WP=""
 ..S (RPMSDT,WRCBEGDT,WRCENDDT,WRCMODDT)=""
 ..S LN1=$P(LN1,"~",2)
 ..S X=$P(LN1,U,1),Y=0 D ^%DT I Y>0 S RPMSDT=Y
 ..S X=$P(LN1,U,2),Y=0 D ^%DT I Y>0 S WRCBEGDT=Y
 ..S X=$P(LN1,U,3),Y=0 D ^%DT I Y>0 S WRCENDDT=Y
 ..S X=$P(LN1,U,4),Y=0 D ^%DT I Y>0 S WRCMODDT=Y
 ..S CODE=$P(LN1,U,5)
 ..S SDESC=$E($P(LN1,U,6),1,80)
 ..D LDESC($P(LN1,U,7),CODE,.WP)
 ..S ^BARTMP("BARMKCDA",CODE,0)=CODE_U_SDESC_U_WRCBEGDT_U_WRCENDDT_U_WRCMODDT_U_RPMSDT
 ..S NODE="BARMKCDA"
 ..D WLDESC(NODE,CODE,RPMSDT,.WP)
 Q
 ;
LDESC(LDESC,CODE,WP)  ;PARSE LONG DESCRIPTION
 N X
 S V=$O(WP(999999999999999),-1)
 S X=0
 F X=1:1:$L(LDESC) D
 .S WP=WP_$E(LDESC,X)
 .I $L(WP)>65,($E(LDESC,X)=" ") S V=V+1,WP(V)=WP,WP=""
 .I ($L(WP)=$L(LDESC))!($L(LDESC)=X) S V=V+1,WP(V)=WP,WP=""
 Q
 ;
WLDESC(NODE,CODE,RPMSDT,WP)  ;SETS LONG DESCRIPTION
 N X,Y
 S X="",Y=0
 F  S X=$O(WP(X)) Q:X']""  D
 .S Y=Y+1,^BARTMP(NODE,CODE,1,0)=U_U_Y_U_Y_U_RPMSDT
 .S ^BARTMP(NODE,CODE,1,Y,0)=WP(X)
 Q
 ;
CONDES    ;CONSOLIDATE LONG DESCRIPTION
 N X,Y
 S X="",CODE="",V=1
 F  S CODE=$O(^BARTMP("BARMKCDA",CODE)) Q:CODE']""  D
 .S RPMSDT=$P($G(^BARTMP("BARMKCDA",CODE,0)),U,5)
 .S X="",Y="",Z=1
 .F  S X=$O(^BARTMP("BARMKCDA",CODE,X)) Q:X']""  D
 ..S Y=Y+1
 .S ^BARTMP("BARMKCDA",CODE,1,0)=U_U_Y_U_Y_U_RPMSDT
 Q
 ;
MERGE     ;REPLACE OLD WITH NEW
 N CODE,OLDIEN,X,Y
 S CODE=""
 F  S CODE=$O(^BARTMP("BARMKCDA",CODE)) Q:CODE']""  D
 .S OLDIEN=$O(^BARMKCD("B",CODE,0))
 .I OLDIEN>0 D
 ..K ^BARMKCD(OLDIEN)
 ..M ^BARMKCD(OLDIEN)=^BARTMP("BARMKCDA",CODE)
 .I OLDIEN="" D
 ..K DO,DIC
 ..S DIC="^BARMKCD("
 ..S DIC(0)="FZ"
 ..S X=CODE
 ..D FILE^DICN
 ..M ^BARMKCD(+Y)=^BARTMP("BARMKCDA",CODE)
 Q
