BARUP2 ; IHS/SD/LSL - 3P UPLOAD CONTINUED DEC 5,1996 ; 
 ;;1.8;IHS ACCOUNTS RECEIVABLE;**1,19,21,24,29,33,34**;OCT 26,2005;Build 139
 ;
 ;IHS/SD/SDR 1.8*34 ADO80817 split from BARUP1; Updated to include more data from 3P Bill that's passed to BAR
 ;************************
 Q
SETITM  ;EP
 ;Create ITEM multiple for A/R Bill
 N BARCNT,DR,DA,DIC,J,I
 I '$D(BAR3PUP) D S3PUP^BARUP1
 S DA(1)=BARBLDA
 S DIC="^BARBL(DUZ(2),"_DA(1)_",3,"
 S DIC(0)="LX"
 S DIC("P")=$P(^DD(90050.01,301,0),U,2)
 S DIC("DR")=""
 ;F I=1:1 S J=$T(TXT+I) Q:J=""  S $P(DIC("DR"),";",I)=$P(J,"~",2)
 ;IHS/SD/TPF FIX ERROR IN CODE WHEN MSGTXT WAS ADDED IN PATCH 19
 ;ALSO ADDED ;;END TO END OF TXT TAG BAR*1.8*21
 F I=1:1 S J=$T(TXT+I) Q:J[("END")  S $P(DIC("DR"),";",I)=$P(J,"~",2)
 S BARCNT=0
 F  S BARCNT=$O(@BAR3PUP@(BARCNT)) Q:'+BARCNT  D
 .S X=$G(@BAR3PUP@(BARCNT,"ITNM"))
 .I '$L(X),$G(@BAR3PUP@(BARCNT,"BLSRV"))="REVENUE CODE" S (X,@BAR3PUP@(BARCNT,"ITNM"))="REVENUE CODE"
 .Q:'$L(X)
 .S X=""""_X_""""
 .S @BAR3PUP@(BARCNT,"DOS")=$S(@BAR3PUP@(BARCNT,"DOS"):@BAR3PUP@(BARCNT,"DOS"),1:@BAR3PUP@("DOSB"))
 .S Y=$G(@BAR3PUP@(BARCNT,"BLSRV"))
 .S BARBLSRV=89            ; Default
 .S:Y="PHARMARCY" BARBLSRV=83
 .S:Y="ROOM & BOARD" BARBLSRV=84
 .S:Y="REVENUE CODE" BARBLSRV=84
 .S:Y="MED/SURG PROCEDURE" BARBLSRV=82
 .S:Y="MEDICAL PROCEDURES" BARBLSRV=85
 .S:Y="DENTAL" BARBLSRV=86
 .S:Y="RADIOLOGY" BARBLSRV=87
 .S:Y="LABORATORY" BARBLSRV=91
 .S:Y="ANESTHESIA" BARBLSRV=88
 .K DD,DO
 .D FILE^DICN
 .K BARBLSRV
 K DLAYGO
 D SETITM2^BARUP3  ;bar*1.8*34 IHS/SD/SDR ADO80817
 Q
 ;************************
SETCOLL  ;EP
 ;Create COLLECTION STATUS multiple for A/R Bill
 N DR,DA,DIC,J,I
 S DA(1)=BARBLDA
 S DIC="^BARBL(DUZ(2),"_DA(1)_",9,"
 S DIC(0)="LX"
 S DIC("P")=$P(^DD(90050.01,901,0),U,2)
 S DIC("DR")=""
 S X=$G(@BAR3PUP@("DTAP"))_U_$G(@BAR3PUP@("BLAMT"))_U_"INITIAL BILL"_U_"0"
 K DD,DO
 D FILE^DICN
 K DLAYGO
 Q
 ;************************
DELITM  ;EP - For the reload of an A/R Bill from the 3P Bill,
 ;deleting all existing items 
 N DIK,DA
 S DA(1)=BARBLDA
 S DA=0
 S DIK=$$DIC^XBDIQ1(90050.01)
 S DIK=DIK_DA(1)_",3,"
 F  S DA=$O(^BARBL(DUZ(2),DA(1),"3",DA)) Q:'+DA  D ^DIK
 Q
 ;************************
 ;
SETTX   ;**create transaction
 K DR
 N DIC
 S BARTT=$O(^BARTBL("B","BILL NEW",""))
 I '+BARTT D NOTX(BARBLDA,"BILL NEW")
 I +BARTT D
 .S DR="3////^S X=@BAR3PUP@(""BLAMT"")"
 .D NEWTX
 ;start old IHS/SD/SDR bar*1.8*24 HEAT118656 belcourt
 ;I @BAR3PUP@("CREDIT") D
 ;.S BARTT=$O(^BARTBL("B","3P CREDIT",""))
 ;.I '+BARTT D NOTX(BARBLDA,"3P CREDIT")
 ;.I +BARTT D
 ;..S DR="2////^S X=$G(@BAR3PUP@(""CREDIT""))"
 ;..D NEWTX
 ;end old start new IHS/SD/SDR bar*1.8*24 HEAT118656
 I @BAR3PUP@("CREDIT")&'$D(@BAR3PUP@("TRNS")) D
 .S BARTT=$O(^BARTBL("B","3P CREDIT",""))
 .I '+BARTT D NOTX(BARBLDA,"3P CREDIT")
 .I +BARTT D
 ..S DR="2////^S X=$G(@BAR3PUP@(""CREDIT""))"
 ..D NEWTX
 ;
 I $P($G(BAROPT)," ")="Upload" D
 .K BARTT
 .S DR="7////^S X=1"
 .S DR=DR_";1001///^S X=BAROPT_"" ""_DT"
 .D NEWTX
 I $D(@BAR3PUP@("TRNS")) D
 .K BARTT
 .S BARTTYP=""
 .F  S BARTTYP=$O(@BAR3PUP@("TRNS",BARTTYP)) Q:$G(BARTTYP)=""  D
 ..S BARTCNT=0
 ..F  S BARTCNT=$O(@BAR3PUP@("TRNS",BARTTYP,BARTCNT)) Q:'BARTCNT  D
 ...S BARTAC=$O(^BAR(90052.01,"B",BARTTYP,0))
 ...I '+BARTAC D NOTX(BARBLDA,BARTTYP)
 ...I +BARTAC D
 ....;I BARTTYP'="PAYMENT CREDIT"&(BARTTYP'="GROUPER ALLOWANCE") S BARTT=$O(^BARTBL("B",BARTTYP,0))
 ....S BARAMT=+$G(@BAR3PUP@("TRNS",BARTTYP,BARTCNT))
 ....S (BARTRTYP,BARTT)=43
 ....S DR="2////^S X=+$G(@BAR3PUP@(""TRNS"",BARTTYP,BARTCNT))"
 ....S DR=DR_";101////^S X=BARTRTYP"
 ....S DR=DR_";102////^S X=BARTAC"
 ....I $P($G(@BAR3PUP@("TRNS",BARTTYP,BARTCNT)),U,5)'="" S DR=DR_";109////^S X=$P(@BAR3PUP@(""TRNS"",BARTTYP,BARTCNT),U,5)"
 ....I $P($G(@BAR3PUP@("TRNS",BARTTYP,BARTCNT)),U,4)'="" S DR=DR_";103////^S X=$P(@BAR3PUP@(""TRNS"",BARTTYP,BARTCNT),U,4)"
 ....D NEWTX
 ....;D 43^BARTDO
 ;end new IHS/SD/SDR bar*1.8*24 HEAT118656 belcourt
 Q
 ;*************************
 ;
NEWTX  ;
 ;Create A/R transaction
 S BARTRIEN=$$NEW^BARTR()
 S BARTT=$G(BARTT)  ;
 ;I BARTRIEN<1 D NOTX(BARBLDA,BARTT) Q  ;IHS/SD/SDR bar*1.8*24 10/10/13 HEAT135708
 I BARTRIEN<1 D NOTX(BARBLDA,"") Q  ;IHS/SD/SDR bar*1.8*24 10/10/13 HEAT135708
 S DIE="^BARTR(DUZ(2),"
 S DA=BARTRIEN
 S DR=DR_";4////^S X=BARBLDA"
 S DR=DR_";5////^S X=@BAR3PUP@(""PTNM"")"
 S DR=DR_";6////^S X=BARACEIN"
 S DR=DR_";8////^S X=BARPAR"
 S DR=DR_";10////^S X=BARSERV"
 S DR=DR_";11////^S X=BARSAT"
 ;S DR=DR_";12////^S X=$P(BARTRIEN,""."")"  ;bar*1.8*33 IHS/SD/SDR ADO60817
 S BARTDT=$P($P($G(^BARTR(DUZ(2),BARTRIEN,0)),U,18),".")  ;bar*1.8*33 IHS/SD/SDR ADO60817
 S DR=DR_";12////^S X=BARTDT"  ;bar*1.8*33 IHS/SD/SDR ADO60817
 S DR=DR_";101////^S X=BARTT"
 ;start old IHS/SD/SDR belcourt HEAT118656
 ;I $P($G(BAROPT)," ")="Upload" D
 ;.S DR=DR_";7////^S X=1"
 ;.S DR=DR_";1001///^S X=BAROPT_"" ""_DT"
 ;new old HEAT118656
 S DIDEL=90050
 D ^DIE
 K DIDEL
 D TR^BARTDO(BARTRIEN)  ;Update other files
 Q
 ;*************************
 ;
NOTX(X,BARTYP)  ;
 ; Couldn't create transaction.
 N XVAL
 I BARTYP="" S BARTYP="<UNK MSG>" ; P.OTT
 S XVAL=$$GET1^DIQ(900501.01,X,.01)
 W *7,$$CJ^XLFSTR("Could not create a "_BARTYP_" transaction.",IOM)
 W $$CJ^XLFSTR("Please contact IT support.",IOM)
 Q
 ;************************
 ;
 ;This is a new section to build the DIC("DR") string
 ;IHS/SD/TPF bar*1.8*21 ADDED LICN FOR 5010 SPEC PAGE 16
 ;IHS/SD/SDR bar*1.8*34 ADO80817 added fields .11, .12, 13, 14, 15, 21, 22, 23 below
TXT  ;
 ;;~2////^S X=$G(@BAR3PUP@(BARCNT,"DOS"))
 ;;~3////^S X=$G(@BAR3PUP@(BARCNT,"ITCODE"))
 ;;~4////^S X=$G(@BAR3PUP@(BARCNT,"OTIT"))
 ;;~5////^S X=$G(@BAR3PUP@(BARCNT,"OTUC"))
 ;;~6////^S X=$G(BARBLSRV)
 ;;~7////^S X=$G(@BAR3PUP@(BARCNT,"ITQT"))
 ;;~8////^S X=$G(@BAR3PUP@(BARCNT,"ITUI"))
 ;;~9////^S X=$G(@BAR3PUP@(BARCNT,"ITUC"))
 ;;~11////^S X=$G(BARCNT)
 ;;~12////^S X=$G(@BAR3PUP@(BARCNT,"LICN"))
 ;;~.11////^S X=$G(@BAR3PUP@(BARCNT,"CPT"))
 ;;~.12////^S X=$G(@BAR3PUP@(BARCNT,"NDC"))
 ;;~13////^S X=$G(@BAR3PUP@(BARCNT,"MOD1"))
 ;;~14////^S X=$G(@BAR3PUP@(BARCNT,"MOD2"))
 ;;~15////^S X=$G(@BAR3PUP@(BARCNT,"MOD3"))
 ;;~17////^S X=$G(@BAR3PUP@(BARCNT,"CPTNARR"))
 ;;~21////^S X=$G(@BAR3PUP@(BARCNT,"ICLIA"))
 ;;~22////^S X=$G(@BAR3PUP@(BARCNT,"RCLIA"))
 ;;~23////^S X=$G(@BAR3PUP@(BARCNT,"TSTR"))
 ;;~Q;10////^S X=$G(@BAR3PUP@(BARCNT,"ITTOT"))
 ;;END
 ;IHS/SD/AR BAR*1.8*19 06.17.2010
MSGTX  ;
 ;Create A/R message transaction
 N BARSCODE,BARGCN,BARSAT,BARCKEX,BARDATE
 S BARGCN=$G(@BAR3PUP@(74,BARMIEN,"GCN"))
 S BARSAT=$G(@BAR3PUP@("VSLC"))
 S BARSCODE=$G(@BAR3PUP@(74,BARMIEN,"STAT"))
 S BARUSER=$G(@BAR3PUP@(74,BARMIEN,"USR"))
 S BARDATE=$G(@BAR3PUP@(74,BARMIEN,"DT"))
 S BARRSN=$S($D(@BAR3PUP@(74,BARMIEN,"RSN")):@BAR3PUP@(74,BARMIEN,"RSN"),1:"NO MESSAGE")
 D CKEXIST
 Q:$G(BARCKEX)=1
 D STATCODE
 S BARTRIEN=$$NEW^BARTR()
 ;I BARTRIEN<1 D NOTX(BARBLDA,BARTT) Q      ;IHS/DIT/CPC CR10754 Eliminate BARTT undefined error.
 I BARTRIEN<1 D NOTX(BARBLDA,$G(BARTT)) Q   ;IHS/DIT/CPC CR10754
 S DIE="^BARTR(DUZ(2),"
 S DA=BARTRIEN
 S DR=DR_";7////^S X=1"
 S DR=DR_";4////^S X=BARBLDA"
 S DR=DR_";10////^S X=""BUSINESS OFFICE"""
 S DR=DR_";11////^S X=BARSAT"
 ;S DR=DR_";12////^S X=$P(BARTRIEN,""."")"  ;bar*1.8*33 IHS/SD/SDR ADO60817
 S DR=DR_";12////^S X=$P($P($G(^BARTR(DUZ(2),BARTRIEN,0)),U,18),""."")"  ;bar*1.8*33 IHS/SD/SDR ADO60817
 S DR=DR_";13////^S X=BARUSER"
 S DR=DR_";16////^S X=""PRIMARY"""
 S Y=BARTRIEN X ^DD("DD")
 K ^TMP($J,"WP")
 S ^TMP($J,"WP",1)=BARSCODE_" ON "_BARDATE_", GCN: "_BARGCN
 S ^TMP($J,"WP",2)="REASON: "_BARRSN
 S DIDEL=90050
 D ^DIE
 K DIDEL
 D WP^DIE(90050.03,BARTRIEN_",",1001,"","^TMP($J,""WP"")")
 K ^TMP($J,"WP")
 D TR^BARTDO(BARTRIEN)   ;Update other files
 Q
 ;*************************
 ;
STATCODE  ;
 ;TRANSLATE STATUS CODE TO VALUE
 S:BARSCODE="O" BARSCODE="ORIGINAL"
 S:BARSCODE="S" BARSCODE="RESENT"
 S:BARSCODE="F" BARSCODE="REFILE"
 S:BARSCODE="C" BARSCODE="RECREATED"
 Q
RSTATCOD  ;
 ;TRANSLATE STATUS CODE TO VALUE
 S:BARSCODE="ORIGINAL" BARSCODE="O"
 S:BARSCODE="RESENT" BARSCODE="S"
 S:BARSCODE="REFILE" BARSCODE="F"
 S:BARSCODE="RECREATED" BARSCODE="C"
 Q
CKEXIST  ;
 ;LOOK FOR EXISTING ENTRIES
 N BARWP,BARWP2
 S BARWP="",BARCKEX=0,BARTRIEN=0,BARWP2=""
 F  S BARTRIEN=$O(^BARTR(DUZ(2),"AM4",BARBLDA,BARTRIEN)) Q:('+BARTRIEN)!(BARCKEX)  D
 .S BARWP=$$GET1^DIQ(90050.03,BARTRIEN,1001,,"BARWP")
 .S:$D(BARWP(1))&($G(BARWP(1))["GCN") BARWP2=$P(BARWP(1)," ",5)
 .S:$D(BARWP2)&(BARWP2?1.N)&(BARWP2=BARGCN) BARCKEX=1
 Q  ;-EOR-
