BPXRHTI1 ; IHS/MSC/MIR - Computed Findings for HTI Reminders ;30-Jan-2025 17:26
 ;;2.0;CLINICAL REMINDERS;**1001,1002,1003,1008,1014,1016**;Feb 04, 2005;Build 32
 ;============================================================================
DIAGDT(DFN,NGET,BDT,EDT,NFOUND,TEST,DATE,VALUE,TEXT) ; data contains Problems Dates
 ;This computed finding will check the Active Patient Problems file to find
 ;Diagnosis and Resolution Dates
 N STAT,PRIEN,DFL,REQTEST,REQCODE S REQTEST=0
 I $L($G(TEST)) S REQTEST=TEST S:'REQTEST REQTEST=$O(^PXD(811.2,"B",REQTEST,""))
 I REQTEST D CDARRCRT(REQTEST)
 K TEST S TEST(1)=0,DFL=9000011
 S DATE=$$NOW^PXRMDATE,NFOUND=0 K VALUE,TEXT
 S STAT="" F  S STAT=$O(^AUPNPROB("ACTIVE",DFN,STAT)) Q:STAT=""  D:STAT'="D"
 .S PRIEN="" F  S PRIEN=$O(^AUPNPROB("ACTIVE",DFN,STAT,PRIEN)) Q:'PRIEN  D
 ..N ARRAY,KEY,DIAGDT,RESOLVDT,DIAG S KEY=PRIEN_","
 ..D GETS^DIQ(DFL,PRIEN,".01;.24;1.07;.08","I","ARRAY")
 ..I '$G(ARRAY(DFL,KEY,.24,"I")),'$G(ARRAY(DFL,KEY,1.07,"I")) Q
 ..S DIAG=$$GET1^DIQ(DFL,PRIEN,.01) I REQTEST Q:'$D(REQCODE(DIAG))
 ..S DIAGDT=$$FMTE^XLFDT(ARRAY(DFL,KEY,.24,"I"),"5D")
 ..S RESOLVDT=$$FMTE^XLFDT(ARRAY(DFL,KEY,1.07,"I"),"5D")
 ..S NFOUND=NFOUND+1,TEST(NFOUND)=1
 ..S (DATE(NFOUND),DTDG)=$$FMTE^XLFDT(ARRAY(DFL,KEY,.08,"I"),"5D") ;Entry Date
 ..S VALUE(NFOUND,"DATE")=DTDG
 ..S VALUE(NFOUND,"PROBLEM")=DIAG                                 ;Problem
 ..S VALUE(NFOUND,"DIAGDT")=DIAGDT                                ;Date of Diagnosis
 ..S VALUE(NFOUND,"RESOLVDT")=RESOLVDT                            ;Date of Resolution
 ..S TEXT(NFOUND)="THE PROBLEM "_DIAG_" GOT DIAGNOSED ON "_$S(DIAGDT:DIAGDT,1:DTDG)_" AND RESOLVED ON "_RESOLVDT
 Q
LABSTAT1(DFN,NGET,BDT,EDT,NFOUND,TEST,DATE,VALUE,TEXT) ; data contains Lab Results
 ;This computed finding will check the OR file to find
 N ORIEN,STAT,ORDT,TO,DFNKEY,LRPCK,REQTEST S REQTEST=0
 I $L($G(TEST)) S REQTEST=TEST I 'REQTEST S REQTEST=$O(^ORD(101.43,"B",REQTEST,""))
 K TEST S TEST(1)=0
 S DATE=$$NOW^PXRMDATE,NFOUND=0 K VALUE,TEXT
 S DFNKEY=DFN_";DPT(",EDT=$G(EDT,DATE)
 S ORDT=9999999-EDT,BDT=9999999-$G(BDT)
 F  S ORDT=$O(^OR(100,"AR",DFNKEY,ORDT)) Q:ORDT>BDT!'ORDT  D
 .S ORIEN="" F  S ORIEN=$O(^OR(100,"AR",DFNKEY,ORDT,ORIEN)) Q:'ORIEN  D
 ..Q:$$GET1^DIQ(100,ORIEN,12)'="LAB SERVICE"
 ..N ORIN,FOUND S ORIN=0
 ..F  S ORIN=$O(^OR(100,ORIEN,.1,ORIN)) Q:'ORIN  D
 ...S FOUND=$S(REQTEST:0,1:1)
 ...I REQTEST,^OR(100,ORIEN,.1,ORIN,0)=REQTEST S FOUND=1
 ...Q:'FOUND
 ...S NFOUND=NFOUND+1,TEST(NFOUND)=1
 ...S (DATE(NFOUND),VALUE(NFOUND,"DATE"))=$$FMTE^XLFDT(ORDT\1,"D") ;Test Date
 ...S VALUE(NFOUND,"TEST")=$$GET1^DIQ(100.001,ORIN_","_ORIEN,.01) ;Test
 ...S VALUE(NFOUND,"STATUS")=$$GET1^DIQ(100,ORIEN,5)              ;Status
 ...S TEXT(NFOUND)="THE TEST "_VALUE(NFOUND,"TEST")_" HAS A STATUS "_VALUE(NFOUND,"STATUS")
 Q
LABSTAT(DFN,NGET,BDT,EDT,NFOUND,TEST,DATE,VALUE,TEXT) ; data contains Lab Results
 ;This computed finding will check the V LAB file to find
 N LIEN,REQTERM,REQCODE S REQTERM=0
 I $L($G(TEST)) S REQTERM=TEST I 'REQTERM S REQTERM=$O(^PXRMD(811.5,"B",REQTERM,""))
 I REQTERM K REQCODE D CDARRCR1(REQTERM,60)
 K TEST S TEST(1)=0
 S DATE=$$NOW^PXRMDATE,NFOUND=0 K VALUE,TEXT
 S LIEN="" F  S LIEN=$O(^AUPNVLAB("AC",DFN,LIEN)) Q:'LIEN  D
 .I REQTERM Q:'$D(REQCODE($P(^AUPNVLAB(LIEN,0),U)_";LAB(60,"))
 .N NDATE S NDATE=$P(^AUPNVLAB(LIEN,12),U)                        ;Collection Date & Time
 .Q:NDATE<BDT  I EDT,NDATE>EDT Q                                  ;Out of Range
 .S NFOUND=NFOUND+1,TEST(NFOUND)=1
 .S DATE(NFOUND)=$$FMTE^XLFDT($P(^AUPNVLAB(LIEN,12),U),4)         ;Collection Date & Time
 .S VALUE(NFOUND,"DATE")=DATE(NFOUND)                             ;Collection Date & Time
 .S VALUE(NFOUND,"TEST")=$$GET1^DIQ(9000010.09,LIEN,.01)          ;Test
 .S VALUE(NFOUND,"STATUS")=$$GET1^DIQ(9000010.09,LIEN,1109)       ;Status
 .S TEXT(NFOUND)="THE TEST "_VALUE(NFOUND,"TEST")_" HAS A STATUS "_VALUE(NFOUND,"STATUS")
 Q
VITALOX(DFN,NGET,BDT,EDT,NFOUND,TEST,DATE,VALUE,TEXT) ; data contains Vitals O2 Qualifiers
 K TEST N TYP S TYP=$O(^AUTTMSR("B","O2","")),TEST(1)=0 Q:'TYP
 N DT,MSRIEN,MSRIN
 S DATE=$$NOW^PXRMDATE,NFOUND=0 K VALUE,TEXT
 S DT="" F  S DT=$O(^AUPNVMSR("AA",DFN,TYP,DT)) Q:'DT  D:(9999999-DT)'<$G(BDT)  Q:NFOUND
 .I $G(EDT) Q:(9999999-DT)>EDT
 .S MSRIEN="" F  S MSRIEN=$O(^AUPNVMSR("AA",DFN,TYP,DT,MSRIEN),-1) Q:'MSRIEN  D  Q:NFOUND
 ..S MSRIN="A" F  S MSRIN=$O(^AUPNVMSR(MSRIEN,5,MSRIN),-1) Q:'MSRIN  D  Q:NFOUND
 ...S NFOUND=NFOUND+1,TEST(NFOUND)=1
 ...S DATE(NFOUND)=$$FMTE^XLFDT(9999999-DT,"5D")                         ;Entry Date
 ...S (DATE(NFOUND,"LAST DONE"),VALUE(NFOUND,"DATE"))=DATE(NFOUND)
 ...S VALUE(NFOUND,"QUAL")=$$GET1^DIQ(9000010.015,MSRIN_","_MSRIEN,.01)  ;Qualifier
 ...S VALUE(NFOUND,"RESULT")=$$GET1^DIQ(9000010.01,MSRIEN,.04)           ;Value
 ...S VALUE(NFOUND,"SUPPLEMENTAL O2")=$$SUPL($$GET1^DIQ(9000010.01,MSRIEN,1.4))  ;Supplemental O2 
 S:NFOUND TEXT(NFOUND)="Vitals O2 data of "_DATE(NFOUND)
 Q
SUPL(VAL) ; Possible adding .0
 I $P(VAL," ")'["." S VAL=$P(VAL," ")_".0 "_$P(VAL," ",2,99)
 Q VAL
DEMDET(DFN,NGET,BDT,EDT,NFOUND,TEST,DATE,VALUE,TEXT) ; data contains Demographic details
 K TEST S TEST(1)=0
 N LNGIN,PRLANG
 S LNGIN=$O(^AUPNPAT(DFN,86,"A"),-1)
 S PRLANG="" I LNGIN S PRLANG=$$GET1^DIQ(9000001.86,LNGIN_","_DFN,.02)
 N SEXDT,SEXIN,SEXORIEN S SEXDT=$O(^AUPNPAT(DFN,93,"A"),-1),SEXORIEN=""
 I SEXDT S SEXIN=$O(^AUPNPAT(DFN,93,SEXDT,1,"A"),-1) I SEXIN D
 .S SEXORIEN=$$GET1^DIQ(9000001.93011,SEXIN_","_SEXDT_","_DFN,.01)
 N GNDRDT,GNDRIDEN,GNDRID S GNDRDT=$O(^AUPNPAT(DFN,94,"A"),-1),GNDRIDEN=""
 I GNDRDT S GNDRID=$O(^AUPNPAT(DFN,94,GNDRDT,1,"A"),-1) I GNDRID D
 .S GNDRIDEN=$$GET1^DIQ(9000001.94011,GNDRID_","_GNDRDT_","_DFN,.01)
 N RACE S RACE=$$GET1^DIQ(2,DFN,.06)
 N ETHNIN,ETHNIC S ETHNIC="",ETHNIN=$O(^DPT(DFN,.06,"A"),-1)
 I ETHNIN S ETHNIC=$$GET1^DIQ(2.06,ETHNIN_","_DFN,.01)
 S DATE=$$NOW^PXRMDATE,NFOUND=0 K VALUE,TEXT
 I $O(^DPT(DFN,.02,0)) N RACEIN S RACEIN=$P(^DPT(DFN,.02,0),U,3) Q:'RACEIN  D
 .S RACE=$$GET1^DIQ(2.02,RACEIN_","_DFN,.01)
 S NFOUND=NFOUND+1,TEST(NFOUND)=1
 S (VALUE(NFOUND,"DATE"),DATE(NFOUND))=$$HTE^XLFDT(+$H,5)   ;Entry Date
 S VALUE(NFOUND,"RACE")=RACE                  ;Race
 S VALUE(NFOUND,"ETHNICITY")=ETHNIC           ;Ethnicity
 S VALUE(NFOUND,"PREFLANG")=PRLANG            ;Preferred Language
 ;S VALUE(NFOUND,"SEXORIENT")=SEXORIEN         ;Sexual Orientation
 ;S VALUE(NFOUND,"GENDER IDENT")=GNDRIDEN      ;Gender Identity
 S TEXT(NFOUND)="Demographic details as of "_DATE(NFOUND)
 I $D(RACE)>1 N I F I=1:1 Q:'$D(RACE(I))  D
 .S NFOUND=NFOUND+1,DATE(NFOUND)=DATE(1),TEXT(NFOUND)=TEXT(1),TEST(NFOUND)=1
 .M VALUE(NFOUND)=VALUE(1)
 .S VALUE(NFOUND,"RACE")=RACE(I)
 Q
MEDS(DFN,NGET,BDT,EDT,NFOUND,TEST,DATE,VALUE,TEXT) ; data contains medications
 N REQTERM S REQTERM=0
 I $L($G(TEST)) S REQTERM=TEST S:'REQTERM REQTERM=$O(^PXRMD(811.5,"B",REQTERM,""))
 I REQTERM K REQCODE D CDARRCR1(REQTERM,50.6),CDARRCR1(REQTERM,50.605),CDARRCR1(REQTERM,50)
 K TEST S TEST(1)=0,NFOUND=0 Q:'$D(^PS(55,DFN,"P","A"))
 N STDT,FNDT,PIEN,INDIC,DOSEUN,DOSE,DRUG K VALUE,TEXT,DATE
 S STDT=$S($G(BDT):BDT-.01,1:""),FNDT=$S($G(EDT):EDT,1:9999999)
 F  S STDT=$O(^PS(55,DFN,"P","A",STDT)) Q:'STDT  D
 .S PIEN="" F  S PIEN=$O(^PS(55,DFN,"P","A",STDT,PIEN)) Q:'PIEN  D:$D(^PSRX(PIEN,0))
 ..N FILLDT S FILLDT=$P($G(^PSRX(PIEN,2)),U,2) I FILLDT<$G(BDT)!(FILLDT>FNDT) Q
 ..S DRUG=$P(^PSRX(PIEN,0),U,6) Q:'DRUG
 ..N NDDRUG S NDDRUG=$P($G(^PSDRUG(DRUG,"ND")),U)
 ..N DRUGCL S DRUGCL=$P($G(^PSDRUG(DRUG,"ND")),U,6)
 ..I REQTERM,'$D(REQCODE(NDDRUG_";PS(50.6,")),'$D(REQCODE(DRUG_";PSDRUG(")),'$D(REQCODE(DRUGCL_";PS(50.605,")) Q
 ..N PSIEN S PSIEN=$O(^PSRX(PIEN,6,0)) Q:'PSIEN
 ..S DOSE=$$GET1^DIQ(52.0113,PSIEN_","_PIEN,.01),DOSEUN=$$GET1^DIQ(52.0113,PSIEN_","_PIEN,2)
 ..I DOSEUN="",DOSE'=+DOSE S DOSEUN=$P(DOSE," ",$L(DOSE," "))
 ..S NFOUND=NFOUND+1,TEST(NFOUND)=1
 ..S (VALUE(NFOUND,"DATE"),DATE(NFOUND))=$$FMTE^XLFDT(FILLDT,"5D")    ;Entry Date
 ..S VALUE(NFOUND,"DRUG")=$$GET1^DIQ(50,DRUG,.01)
 ..S VALUE(NFOUND,"DOSAGE")=DOSE
 ..S VALUE(NFOUND,"DOSE UNIT")=DOSEUN
 ..S VALUE(NFOUND,"INDICATION")=$$GET1^DIQ(52,PIEN,9999999.22)
 Q
CDARRCRT(REQTEST) ; Array of Diag codes creation
 N I,J,K K REQCODE Q:'REQTEST
 S I=0 F  S I=$O(^PXD(811.2,REQTEST,20,I)) Q:'I  D
 .S J=0 F  S J=$O(^PXD(811.2,REQTEST,20,I,1,J)) Q:'J  D
 ..S K=0 F  S K=$O(^PXD(811.2,REQTEST,20,I,1,J,1,K)) Q:'K  S REQCODE(^PXD(811.2,REQTEST,20,I,1,J,1,K,0))=""
 Q
CDARRCR1(REQTERM,FLNM) ; Array of Med codes creation
 N I Q:'REQTERM  N FL S FL=$G(^DIC(FLNM,0,"GL")),FL=$E(FL,2,$L(FL))
 S I=0 F  S I=$O(^PXRMD(811.5,REQTERM,20,I)) Q:'I  D
 .N CODE S CODE=$P(^PXRMD(811.5,REQTERM,20,I,0),U) Q:$P(CODE,";",2)'=FL
 .S REQCODE(CODE)=""
 Q
 
