BPXRMHTI ; IHS/MSC/MIR - Computed Findings for HTI Reminders ;10-May-2024 17:26
 ;;2.0;CLINICAL REMINDERS;**1001,1002,1003,1008,1014**;Feb 04, 2005;Build 21
 ;============================================================================
 ;This routine is designed to bring an implanted devices with a certain status
 ;data to determine if status is Active/Inactive with Date and Reason
 ;============================================================================
STATUS(DFN,NGET,BDT,EDT,NFOUND,TEST,DATE,VALUE,TEXT) ; data contains Date and Reason
 ;This computed finding will check the Patient Implanted Device file to find
 ;device with an ACTIVE status
 N BEHODEIN K TEST S TEST(1)=0
 S DATE=$$NOW^PXRMDATE,NFOUND=0 K VALUE,TEXT
 S BEHODEIN="" F  S BEHODEIN=$O(^AUPNPDEV("AC",DFN,BEHODEIN),-1) Q:'BEHODEIN  D
 .S BEHOCAT=$$GET1^DIQ(9000091,BEHODEIN,.01) ;Q:BEHOCAT'="Contraceptive/GYN"
 .N LASTDT,LAST,STATUS,EIN S LASTDT=$O(^AUPNPDEV(BEHODEIN,3,"B",""),-1) Q:'LASTDT
 .S LAST=$O(^AUPNPDEV(BEHODEIN,3,"B",LASTDT,""),-1) Q:'LAST
 .S EIN=LAST_","_BEHODEIN,STATUS=$$GET1^DIQ(9000091.3,EIN,.02)
 .S NFOUND=NFOUND+1,TEST(NFOUND)=1,DATE(NFOUND)=DATE
 .S VALUE(NFOUND,"CATEGORY")=BEHOCAT
 .S VALUE(NFOUND,"STATUS")=STATUS
 .S VALUE(NFOUND,"REASON")=$$UP^XLFSTR($$GET1^DIQ(9000091.3,EIN,.04))
 .S VALUE(NFOUND,"CHANGED ON")=$$GET1^DIQ(9000091.3,EIN,.01,"I")
 .S VALUE(NFOUND,"CHANGED BY")=$$UP^XLFSTR($$GET1^DIQ(9000091.3,EIN,.03))
 .S TEXT(NFOUND)="THE DEVICE "_BEHOCAT_" BECAME "_STATUS_" ON "_$$ENTRY^CIAUDT(VALUE(1,"CHANGED ON"),1)
 Q
OCAACT(DFN,NGET,BDT,EDT,NFOUND,TEST,DATE,VALUE,TEXT) ; IHS/OCA/JTC - 2024.08.08 - fix for pxrm 1014
 N BEHOPAR ; PARAMETER VALUE SENT
 S BEHOPAR=TEST
 I BEHOPAR="" S BEHOPAR="Contraceptive/GYN" ; reminder computed parameter - default to contra/gyn, cant use $Get because test="" if blank
 N BEHODEIN,FND K TEST S TEST(1)=0
 S DATE=$$NOW^PXRMDATE
 N PXRMA
 K VALUE,TEXT,PXRMA
 S BEHODEIN="" F  S BEHODEIN=$O(^AUPNPDEV("AC",DFN,BEHODEIN),-1) Q:'BEHODEIN  D
 .S BEHOCAT=$$GET1^DIQ(9000091,BEHODEIN,.01) Q:BEHOCAT'=BEHOPAR
 .Q:$$GET1^DIQ(9000091,BEHODEIN,"CURRENT STATUS")'="ACTIVE"
 .; make array by date DATE IMPLANTED
 .N PXRMDT S PXRMDT=$$GET1^DIQ(9000091,BEHODEIN,"DATE IMPLANTED","I")
 .Q:'PXRMDT  ; protection for bad data - this is a required field now
 .S PXRMA(PXRMDT,BEHODEIN)=""
 ; loop array and populate values with most recent as nfound=1
 S NFOUND=0
 S PXRMDT="" F  S PXRMDT=$O(PXRMA(PXRMDT),-1) Q:'PXRMDT  D
 .S BEHODEIN="" F  S BEHODEIN=$O(PXRMA(PXRMDT,BEHODEIN)) Q:'BEHODEIN  D
 ..S NFOUND=NFOUND+1 S TEST(NFOUND)=1
 ..S DATE(NFOUND)=PXRMDT
 ..S TEXT(NFOUND)="THE DEVICE WAS IMPLANTED "_$$ENTRY^CIAUDT(DATE(NFOUND),1)
 ..N BEHODES S BEHODES=$$GET1^DIQ(9000091,BEHODEIN,"DESCRIPTION") I BEHODES'="" S TEXT(NFOUND)=TEXT(NFOUND)_" ("_BEHODES_")"
 ..S VALUE(NFOUND,"IEN")=BEHODEIN
 ..S VALUE(NFOUND,"CAT")=BEHOPAR
 ..S VALUE(NFOUND,"EFF UNTIL")=$$GET1^DIQ(9000091,BEHODEIN,"EFFECTIVE UNTIL","I")
 ..S VALUE(NFOUND,"STATUS")=$$GET1^DIQ(9000091,BEHODEIN,"CURRENT STATUS","I")
 ..N LASTDT,LAST,STATUS,EIN S LASTDT=$O(^AUPNPDEV(BEHODEIN,3,"B",""),-1) Q:'LASTDT
 ..S LAST=$O(^AUPNPDEV(BEHODEIN,3,"B",LASTDT,""),-1) Q:'LAST
 ..S EIN=LAST_","_BEHODEIN,STATUS=$$GET1^DIQ(9000091.3,EIN,.02,"I")
 ..S VALUE(NFOUND,"REASON")=$$UP^XLFSTR($$GET1^DIQ(9000091.3,EIN,.04))
 ..S VALUE(NFOUND,"CHANGED ON")=$$GET1^DIQ(9000091.3,EIN,.01,"I")
 ..S VALUE(NFOUND,"CHANGED BY")=$$UP^XLFSTR($$GET1^DIQ(9000091.3,EIN,.03))
 I $G(DATE(1))'="" S DATE=DATE(1)
 Q
DEVACT(DFN,NGET,BDT,EDT,NFOUND,TEST,DATE,VALUE,TEXT) ; data contains Date and Reason
 ;This computed finding will check the Patient Implanted Device file to find
 ;device with an ACTIVE status
 N BEHODEIN,FND K TEST S TEST(1)=0
 S DATE=$$NOW^PXRMDATE,(NFOUND,FND)=0 K VALUE,TEXT
 S BEHODEIN="" F  S BEHODEIN=$O(^AUPNPDEV("AC",DFN,BEHODEIN),-1) Q:'BEHODEIN  D  Q:FND
 .S BEHOCAT=$$GET1^DIQ(9000091,BEHODEIN,.01) Q:BEHOCAT'="Contraceptive/GYN"
 .N LASTDT,LAST,STATUS,EIN S LASTDT=$O(^AUPNPDEV(BEHODEIN,3,"B",""),-1),FND=1 Q:'LASTDT
 .S LAST=$O(^AUPNPDEV(BEHODEIN,3,"B",LASTDT,""),-1) Q:'LAST
 .S EIN=LAST_","_BEHODEIN,STATUS=$$GET1^DIQ(9000091.3,EIN,.02,"I") Q:STATUS'="A"
 .S NFOUND=NFOUND+1,TEST(NFOUND)=1,DATE(NFOUND)=DATE
 .S VALUE(NFOUND,"REASON")=$$UP^XLFSTR($$GET1^DIQ(9000091.3,EIN,.04))
 .S VALUE(NFOUND,"CHANGED ON")=$$GET1^DIQ(9000091.3,EIN,.01,"I")
 .S VALUE(NFOUND,"CHANGED BY")=$$UP^XLFSTR($$GET1^DIQ(9000091.3,EIN,.03))
 .S TEXT(NFOUND)="THE DEVICE BECAME ACTIVE ON "_$$ENTRY^CIAUDT(VALUE(1,"CHANGED ON"),1)
 Q
OCAEFUNT(DFN,NGET,BDT,EDT,NFOUND,TEST,DATE,VALUE,TEXT) ; IHS/OCA/JTC - 2024.08.08 - fix for pxrm 1014
 ;This computed finding will check the Patient Implanted Device file to find
 ;devices and return the Effective Until dates
 ;D APPERROR^ZTER("PXRM DEBUG 3")
 S BEHOPAR=TEST
 I BEHOPAR="" S BEHOPAR="Contraceptive/GYN" ; reminder computed parameter - default to contra/gyn, cant use $Get because test="" if blank
 N BEHODEIN,FND K TEST S TEST(1)=0
 S DATE=$$NOW^PXRMDATE
 N PXRMA
 K VALUE,TEXT,PXRMA
 S BEHODEIN="" F  S BEHODEIN=$O(^AUPNPDEV("AC",DFN,BEHODEIN),-1) Q:'BEHODEIN  D
 .S BEHOCAT=$$GET1^DIQ(9000091,BEHODEIN,.01) Q:BEHOCAT'=BEHOPAR
 .Q:$$GET1^DIQ(9000091,BEHODEIN,"CURRENT STATUS")'="ACTIVE"
 .; make array by date: EFFECTIVE UNTIL
 .N PXRMDT S PXRMDT=$$GET1^DIQ(9000091,BEHODEIN,"EFFECTIVE UNTIL","I")
 .Q:'PXRMDT
 .S PXRMA(PXRMDT,BEHODEIN)=""
 ; loop array and populate values with the EARLIEST date (quickest to expire) as nfound=1
 S NFOUND=0
 S PXRMDT="" F  S PXRMDT=$O(PXRMA(PXRMDT)) Q:'PXRMDT  D
 .S BEHODEIN="" F  S BEHODEIN=$O(PXRMA(PXRMDT,BEHODEIN)) Q:'BEHODEIN  D
 ..S NFOUND=NFOUND+1 S TEST(NFOUND)=1
 ..S DATE(NFOUND)=PXRMDT ; EFFECTIVE UNTIL DATE
 ..S TEXT(NFOUND)="THE DEVICE IS EFFECTIVE UNTIL "_$$ENTRY^CIAUDT(DATE(NFOUND),1)
 ..N BEHODES S BEHODES=$$GET1^DIQ(9000091,BEHODEIN,"DESCRIPTION")
 ..I BEHODES'="" S TEXT(NFOUND)=TEXT(NFOUND)_" ("_BEHODES_")"
 ..S VALUE(NFOUND,"IEN")=BEHODEIN
 ..S VALUE(NFOUND,"CAT")=BEHOPAR
 ..S VALUE(NFOUND,"EFF UNTIL")=$$GET1^DIQ(9000091,BEHODEIN,"EFFECTIVE UNTIL","I")
 ..S VALUE(NFOUND,"IMPL DT")=$$GET1^DIQ(9000091,BEHODEIN,"DATE IMPLANTED","I")
 ..S VALUE(NFOUND,"STATUS")=$$GET1^DIQ(9000091,BEHODEIN,"CURRENT STATUS","I")
 ..N LASTDT,LAST,STATUS,EIN S LASTDT=$O(^AUPNPDEV(BEHODEIN,3,"B",""),-1) Q:'LASTDT
 ..S LAST=$O(^AUPNPDEV(BEHODEIN,3,"B",LASTDT,""),-1) Q:'LAST
 ..S EIN=LAST_","_BEHODEIN,STATUS=$$GET1^DIQ(9000091.3,EIN,.02,"I")
 ..S VALUE(NFOUND,"REASON")=$$UP^XLFSTR($$GET1^DIQ(9000091.3,EIN,.04))
 ..S VALUE(NFOUND,"CHANGED ON")=$$GET1^DIQ(9000091.3,EIN,.01,"I")
 ..S VALUE(NFOUND,"CHANGED BY")=$$UP^XLFSTR($$GET1^DIQ(9000091.3,EIN,.03))
 I $G(DATE(1))'="" S DATE=DATE(1)
 Q
DEVEFUNT(DFN,NGET,BDT,EDT,NFOUND,TEST,DATE,VALUE,TEXT) ; data contains Effective Until Date
 ;This computed finding will check the Patient Implanted Device file to find
 ;device with an Effective Until Date
 N BEHODEIN,EFFUNTIL,FND K TEST S TEST(1)=0
 S DATE=$$NOW^PXRMDATE,(NFOUND,FND)=0 K VALUE,TEXT
 S BEHODEIN="" F  S BEHODEIN=$O(^AUPNPDEV("AC",DFN,BEHODEIN),-1) Q:'BEHODEIN  D  Q:FND
 .S BEHOCAT=$$GET1^DIQ(9000091,BEHODEIN,.01) Q:BEHOCAT'="Contraceptive/GYN"
 .S EFFUNTIL=$$GET1^DIQ(9000091,BEHODEIN,.13,"I"),FND=1 Q:'EFFUNTIL
 .S NFOUND=NFOUND+1,TEST(NFOUND)=1,DATE(NFOUND)=DATE
 .S VALUE(NFOUND,"EFF UNTIL")=EFFUNTIL  ;,VALUE(NFOUND)=EFFUNTIL
 .S TEXT(NFOUND)="THE DEVICE IS EFFECTIVE UNTIL "_$$ENTRY^CIAUDT(VALUE(1,"EFF UNTIL"),1)
 Q
OCAINACT(DFN,NGET,BDT,EDT,NFOUND,TEST,DATE,VALUE,TEXT) ; IHS/OCA/JTC - 2024.08.08 - fix for pxrm 1014
 ;This computed finding will check the Patient Implanted Device file to find
 ;devices and return the Inactive dates.
 ; return true only if ALL devices in the category are inactive
 ;D APPERROR^ZTER("PXRM DEBUG 3")
 S BEHOPAR=TEST
 I BEHOPAR="" S BEHOPAR="Contraceptive/GYN" ; reminder computed parameter - default to contra/gyn, cant use $Get because test="" if blank
 N BEHODEIN,FND K TEST S TEST(1)=0
 S DATE=$$NOW^PXRMDATE
 N PXRMA,PXRMAA
 K VALUE,TEXT,PXRMA,PXRMAA
 S BEHODEIN="" F  S BEHODEIN=$O(^AUPNPDEV("AC",DFN,BEHODEIN),-1) Q:'BEHODEIN  D
 .S BEHOCAT=$$GET1^DIQ(9000091,BEHODEIN,.01) Q:BEHOCAT'=BEHOPAR
 .I $$GET1^DIQ(9000091,BEHODEIN,"CURRENT STATUS")="ACTIVE" S PXRMAA(BEHODEIN)="" Q
 .; make array by last updated for the non-actives:
 .N PXRMDT S PXRMDT=$$GET1^DIQ(9000091,BEHODEIN,"DATE LAST MODIFIED","I")
 .I 'PXRMDT S PXRMDT=$$GET1^DIQ(9000091,BEHODEIN,"DATE IMPLANTED","I")
 .Q:'PXRMDT
 .S PXRMA(PXRMDT,BEHODEIN)=""
 ; loop array and populate values with the NEWEST date as nfound=1
 S NFOUND=0
 S PXRMDT="" F  S PXRMDT=$O(PXRMA(PXRMDT),-1) Q:'PXRMDT  D
 .S BEHODEIN="" F  S BEHODEIN=$O(PXRMA(PXRMDT,BEHODEIN)) Q:'BEHODEIN  D
 ..S NFOUND=NFOUND+1 S TEST(NFOUND)=1
 ..S DATE(NFOUND)=PXRMDT ; last modified date
 ..S TEXT(NFOUND)="THE DEVICE WAS LAST MODIFIED "_$$ENTRY^CIAUDT(DATE(NFOUND),1)
 ..S TEXT(NFOUND)=TEXT(NFOUND)_". Current Status: "_$$GET1^DIQ(9000091,BEHODEIN,"CURRENT STATUS","I")
 ..N BEHODES S BEHODES=$$GET1^DIQ(9000091,BEHODEIN,"DESCRIPTION") I BEHODES'="" S TEXT(NFOUND)=TEXT(NFOUND)_" ("_BEHODES_")"
 ..S VALUE(NFOUND,"IEN")=BEHODEIN
 ..S VALUE(NFOUND,"CAT")=BEHOPAR
 ..S VALUE(NFOUND,"EFF UNTIL")=$$GET1^DIQ(9000091,BEHODEIN,"EFFECTIVE UNTIL","I")
 ..S VALUE(NFOUND,"IMPL DT")=$$GET1^DIQ(9000091,BEHODEIN,"DATE IMPLANTED","I")
 ..S VALUE(NFOUND,"STATUS")=$$GET1^DIQ(9000091,BEHODEIN,"CURRENT STATUS","I")
 ..N LASTDT,LAST,STATUS,EIN S LASTDT=$O(^AUPNPDEV(BEHODEIN,3,"B",""),-1) Q:'LASTDT
 ..S LAST=$O(^AUPNPDEV(BEHODEIN,3,"B",LASTDT,""),-1) Q:'LAST
 ..S EIN=LAST_","_BEHODEIN,STATUS=$$GET1^DIQ(9000091.3,EIN,.02,"I")
 ..S VALUE(NFOUND,"REASON")=$$UP^XLFSTR($$GET1^DIQ(9000091.3,EIN,.04))
 ..S VALUE(NFOUND,"CHANGED ON")=$$GET1^DIQ(9000091.3,EIN,.01,"I")
 ..S VALUE(NFOUND,"CHANGED BY")=$$UP^XLFSTR($$GET1^DIQ(9000091.3,EIN,.03))
 I $D(PXRMAA) S NFOUND=0 F  S NFOUND=$O(TEST(NFOUND)) Q:'NFOUND  S TEST(NFOUND)=0
 I $G(DATE(1))'="" S DATE=DATE(1)
 Q
DEVINACT(DFN,NGET,BDT,EDT,NFOUND,TEST,DATE,VALUE,TEXT) ; data contains Date and Reason
 ;This computed finding will check the Patient Implanted Device file to find
 ;device with an INACTIVE status
 N BEHODEIN,FND K TEST S TEST(1)=0
 S DATE=$$NOW^PXRMDATE,(NFOUND,FND)=0 K VALUE,TEXT
 S BEHODEIN="" F  S BEHODEIN=$O(^AUPNPDEV("AC",DFN,BEHODEIN),-1) Q:'BEHODEIN  D  Q:FND
 .S BEHOCAT=$$GET1^DIQ(9000091,BEHODEIN,.01) Q:BEHOCAT'="Contraceptive/GYN"
 .N LASTDT,LAST,STATUS,EIN S LASTDT=$O(^AUPNPDEV(BEHODEIN,3,"B",""),-1),FND=1 Q:'LASTDT
 .S LAST=$O(^AUPNPDEV(BEHODEIN,3,"B",LASTDT,""),-1) Q:'LAST
 .S EIN=LAST_","_BEHODEIN,STATUS=$$GET1^DIQ(9000091.3,EIN,.02,"I") Q:STATUS'="I"
 .S NFOUND=NFOUND+1,TEST(NFOUND)=1,DATE(NFOUND)=DATE
 .S VALUE(NFOUND,"REASON")=$$UP^XLFSTR($$GET1^DIQ(9000091.3,EIN,.04))
 .S VALUE(NFOUND,"CHANGED ON")=$$GET1^DIQ(9000091.3,EIN,.01,"I")
 .S VALUE(NFOUND,"CHANGED BY")=$$UP^XLFSTR($$GET1^DIQ(9000091.3,EIN,.03))
 .S TEXT(NFOUND)="THE DEVICE BECAME INACTIVE ON "_$$ENTRY^CIAUDT(VALUE(1,"CHANGED ON"),1)
 Q
DEVEFUN1(DFN,TEST,DATE,VALUE,TEXT) ; data contains Effective Until Date
 ;This computed finding will check the Patient Implanted Device file to find
 ;device with an Effective Until Date
 N BEHODEIN,EFFUNTIL,FND K TEST S TEST=0
 S DATE=$$NOW^PXRMDATE,(NFOUND,FND)=0 K VALUE,TEXT
 S BEHODEIN="" F  S BEHODEIN=$O(^AUPNPDEV("AC",DFN,BEHODEIN),-1) Q:'BEHODEIN  D  Q:FND
 .S BEHOCAT=$$GET1^DIQ(9000091,BEHODEIN,.01) Q:BEHOCAT'="Contraceptive/GYN"
 .S EFFUNTIL=$$GET1^DIQ(9000091,BEHODEIN,.13,"I"),FND=1 Q:'EFFUNTIL
 .S TEST=1,VALUE=EFFUNTIL
 .S TEXT="THE DEVICE IS EFFECTIVE UNTIL "_$$ENTRY^CIAUDT(VALUE,1)
 Q
PXRMLAD(DFN,TEST,DATE,VALUE,TEXT) ; Last Admission Date
 S DATE=$$NOW^PXRMDATE,TEXT=""
 ;N VAIN D INP^VADPT
 ;S VALUE=$P(VAIN(7),U,1),TEST=(VALUE>0)
 S VALUE=$O(^DGPM("APTT1",DFN,""),-1),TEST=''VALUE
 I TEST S TEXT="Patient has an admission date/time: "_$$FMTE^XLFDT(VALUE,"5Z")
 I VALUE S VALUE=+$E(VALUE,1,12)
 Q
