LRXO11 ; IHS/DIR/AAB - Setup order & accession for OE/RR 3/29/90 16:40 ; [ 07/13/1998 10:18 AM ]
 ;;5.2;LR;**1002,1003,1006,1018**;Nov 18, 2004
 ;;5.2;LAB SERVICE;**12,100,121,128,189**;Sep 27, 1994
 ;THIS ROUTINE IS CALL TO MAKE THE ORDERS AND ACCESSION FROM THE LOCAL ARAY
EN D DT K ZTSK S LRORDR=LRXZ
 F LRSAMP=-1:0 S LRSAMP=$O(^XUTL("OR",$J,"LROT",LRSDT,LRXZ,LRSAMP)) Q:LRSAMP=""  F LRSPEC=-1:0 S LRSPEC=$O(^XUTL("OR",$J,"LROT",LRSDT,LRXZ,LRSAMP,LRSPEC)) Q:LRSPEC=""  D ZX
 K ZTSK Q
ZX ;;
 N GOT,LRNSN S GOT=0
 I $D(^LRO(69,"C",LRORD,LRODT)) S LRSN=0 F  S LRSN=$O(^LRO(69,"C",LRORD,LRODT,LRSN)) Q:LRSN<1  D  Q:GOT
 . I $D(^LRO(69,LRODT,1,LRSN,0)),$P(^(0),"^",3)=LRSAMP,$D(^(4,1,0)),+^(0)=LRSPEC S GOT=1,LRNSN=LRSN,X=$P($G(^LRO(69,LRODT,1,LRSN,2,0)),"^",3),^(0)="^69.03PA^"_X_U_X
 I GOT S J=0,LRSN=LRNSN G SKIP
 S (LRSXN,I)=0 F  S I=$O(^XUTL("OR",$J,"LROT",LRSDT,LRXZ,LRSAMP,LRSPEC,I)) Q:I<1  S LRSXN=LRSXN+1
 S:'$D(^LRO(69,LRODT,0)) ^(0)=$P(^LRO(69,0),U,1,2)_U_LRODT_U_(1+$P(^(0),U,4)),^LRO(69,LRODT,0)=LRODT,^LRO(69,"B",LRODT,LRODT)=""
 L ^LRO(69,LRODT,1) S LRSN=1+$S($D(^LRO(69,LRODT,1,0)):$P(^(0),U,3),1:0),LRSUM=1+$S($D(^LRO(69,LRODT,1,0)):$P(^(0),U,4),1:0)
ZSN IF $D(^LRO(69,LRODT,1,LRSN,0)) S LRSN=LRSN+1 G ZSN
 I '$D(LRGUY) S LRGUY=$G(DUZ)
 S ^LRO(69,LRODT,1,LRSN,0)=LRDFN_"^"_LRGUY_"^"_(+LRSAMP)_"^"_LRORDR_"^"_LRNT_"^"_LRPRAC_"^"_LRLLOC_"^"_LRSDT_"^"_LROLLOC,^(2,0)="^69.03PA^"_LRSXN_U_LRSXN,^LRO(69,LRODT,1,0)="^69.01PA^"_LRSN_U_LRSUM L
 S ^LRO(69,LRODT,1,"AA",LRDFN,LRSN)="",^LRO(69,LRODT,1,"AC",LRLLOC,LRSN)="",^XUTL("OR",$J,"LROT",LRSDT,LRXZ,LRSAMP,LRSPEC,"SN")=LRSN,^LRO(69,"D",LRDFN,LRODT,LRSN)=""
 I $L(LRSPEC) S ^LRO(69,LRODT,1,LRSN,4,0)="^69.02PA^1^1",^(1,0)=LRSPEC
 S ^LRO(69,LRODT,1,LRSN,.1)=LRORD,^LRO(69,"C",+LRORD,LRODT,LRSN)=""
SKIP D
 . N CNT,CTR,I,X,J S J=0,CTR=1
 . F LRJ=1:1 S J=$O(^XUTL("OR",$J,"LROT",LRSDT,LRXZ,LRSAMP,LRSPEC,J)) Q:J<1  D ZSN1 D
 .. Q  N LRCSX S LRCSX=0 F  S LRCSX=$O(^XUTL("OR",$J,"COM",LRSDT,LRXZ,LRSAMP,LRSPEC,LRCSX)) Q:LRCSX<1  D
 ... S I=0 F  S I=$O(^XUTL("OR",$J,"COM",LRSDT,LRXZ,LRSAMP,LRSPEC,LRCSX,I)) Q:I<1  S X=^(I) I $O(^(I,0))=LRTSTS D
 .... F  Q:'$D(^LRO(69,LRODT,1,LRSN,6,CTR))  S CTR=CTR+1
 .... S ^LRO(69,LRODT,1,LRSN,6,CTR,0)=X
 . S (CTR,I)=0 F  S I=$O(^LRO(69,LRODT,1,LRSN,6,I)) Q:I<1  S CTR=CTR+1
 . I CTR>0 S ^LRO(69,LRODT,1,LRSN,6,0)="^69.04W^"_CTR_U_CTR
 I LRORDR="LC" S ION=$P(^LAB(69.9,1,3),U,4) I ION]"" D ^LROW2P
 I LRXZ["I" S ION=$P(^LAB(69.9,1,7,DUZ(2),0),U,3) D ^LROW2P
 Q
ZSN1 S LRTSTS=+^XUTL("OR",$J,"LROT",LRSDT,LRXZ,LRSAMP,LRSPEC,J),LRORIFN=^XUTL("OR",$J,"LROT",LRSDT,LRXZ,LRSAMP,LRSPEC,J,0),LRURG=$S($G(^(1)):^(1),1:LROUTINE)
 F  Q:'$D(^LRO(69,LRODT,1,LRSN,2,LRJ))  S LRJ=LRJ+1
 S ^LRO(69,LRODT,1,LRSN,2,LRJ,0)=LRTSTS_"^"_LRURG_$S($D(LRORIFN):"^^^^^"_LRORIFN,1:"")
 S ^LRO(69,LRODT,1,LRSN,2,"B",LRTSTS,LRJ)="",ORIFN=LRORIFN,ORETURN("ORPK")=LRODT_"^"_LRSN_"^"_LRJ,ORETURN("ORSTS")=5
 N LRCSX S LRCSX=0,CNT=2
 F  S LRCSX=$O(^XUTL("OR",$J,"COM",LRSDT,LRXZ,LRSAMP,LRSPEC,LRCSX)) Q:LRCSX<1  D
 . S X=^XUTL("OR",$J,"COM",LRSDT,LRXZ,LRSAMP,LRSPEC,LRCSX)+$S($P($G(^LRO(69,LRODT,1,LRSN,2,LRJ,1,0)),"^",4):$P(^(0),"^",4),1:0),^LRO(69,LRODT,1,LRSN,2,LRJ,1,0)="^69.399^"_X_"^"_X
 . N TCNT,C S TCNT=+$O(^LRO(69,LRODT,1,LRSN,2,LRJ,1,99999),-1)
 . S (C,I)=0 F  S I=$O(^XUTL("OR",$J,"COM",LRSDT,LRXZ,LRSAMP,LRSPEC,LRCSX,I)) Q:I<1  S X=^(I) I $O(^(I,0))=LRTSTS S C=C+1,^LRO(69,LRODT,1,LRSN,2,LRJ,1,C+TCNT,0)=X I X'["~For" S ORETURN("ORTX",CNT)=X,CNT=CNT+1
 ;BEGIN IHS MODIFICATIONS LR*5.2*1018
 ;RESTORE CALL TO ORX
 D SET2^LROR(LRTSTS,LRSAMP,LRSPEC,LRURG,LRXZ,LRORD) S ORETURN("ORTX",1)=ORTX(1),LRX=ORTX(1) K LRLWC D RETURN^ORX
 ;D SET2^LROR(LRTSTS,LRSAMP,LRSPEC,LRURG,LRXZ,LRORD) S ORETURN("ORTX",1)=ORTX(1),LRX=ORTX(1) K LRLWC D RETURN^BLRORX  ;IHS/DIR TUC/AAB 06/15/98
 ;END IHS MODIFICATIONS
 I $S('$D(^XUSEC("ORES",DUZ)):1,$P($G(^ORD(100.99,1,0)),"^",18):1,1:0) D
 . I $Y>(IOSL-3) D READ^ORUTL W @IOF
 . W !?2,$E(LRX,1,58) S Y=LRSDT D DD^%DT W ?60,Y
 S ^LRO(69,"AT",LRDFN,LRTSTS,LRSPEC,LRODT)="",^(-LRODT)=""
 Q
DT S %H=+$H D YMD^%DTC S DT=X
 S LRNT=$P($H,",",2),LRNT=LRNT\3600*100+(LRNT\60#60)/10000+DT
 Q
