BDW10P8 ;ihs/cmi/maw - BDW Patch 8
 ;;1.0;IHS DATA WAREHOUSE;**8**;JAN 24, 2006;Build 84
 ;
ENV ;-- environment check
 I '$$INSTALLD("XU*8.0*1018") D SORRY(2)
 I '$$INSTALLD("DI*22.0*1018") D SORRY(2)
 I '$$INSTALLD("GIS*3.01*16") D SORRY(2)
 I '$$INSTALLD("BDW*1.0*7") D SORRY(2)
 ;I '$$INSTALLD("AG*7.1*13") D SORRY(2)
 Q
 ;
PRE ;
 Q
INSTALLD(BDGSTAL) ;EP - Determine if patch BDGSTAL was installed, where
 ; BDGSTAL is the name of the INSTALL.  E.g "AG*6.0*11".
 ;
 NEW BDGY,DIC,X,Y
 S X=$P(BDGSTAL,"*",1)
 S DIC="^DIC(9.4,",DIC(0)="FM",D="C"
 D IX^DIC
 I Y<1 D IMES Q 0
 S DIC=DIC_+Y_",22,",X=$P(BDGSTAL,"*",2)
 D ^DIC
 I Y<1 D IMES Q 0
 I $P(BDGSTAL,"*",3)="" D IMES Q 1
 S DIC=DIC_+Y_",""PAH"",",X=$P(BDGSTAL,"*",3)
 D ^DIC
 S BDGY=Y
 D IMES
 Q $S(BDGY<1:0,1:1)
IMES ;
 D MES^XPDUTL($$CJ^XLFSTR("Patch """_BDGSTAL_""" is"_$S(Y<1:" *NOT*",1:"")_" Present.",IOM))
 Q
SORRY(X) ;
 KILL DIFQ
 I X=3 S XPDQUIT=2 Q
 S XPDQUIT=X
 W *7,!,$$CJ^XLFSTR("Sorry....FIX IT!",IOM)
 Q
 ;
POST ;post init
 S KFM="K DIE,DR,DIC,DA,DD,DO,DIK"
 D ZVP  ;update ZVP segment
 D XAM  ;update OBX exam
 D PED  ;update ped
 D ZP2  ;update ZP2
 D ZWH  ;update ZWH
 D RXD  ;add segment to message
 D ZMD  ;update ZMD
 D PV1HOPE ;update pv1 hope
 D WH
 D ZDX
 D ZV1
 D PID
 D ZPL
 D ZPT
 S MESS=$O(^INTHL7M("B","HL IHS DW1 A08",0))
 D COMPILE^BHLU(MESS)
 S MESS=$O(^INTHL7M("B","HL IHS DW1ALPMR A08",0))
 D COMPILE^BHLU(MESS)
 S MESS=$O(^INTHL7M("B","HL IHS DW1HOPE O13",0))
 D COMPILE^BHLU(MESS)
 S MESS=$O(^INTHL7M("B","HL IHS DW1 A31",0))
 D COMPILE^BHLU(MESS)
 S MESS=$O(^INTHL7M("B","HL IHS DW1 A40",0))
 D COMPILE^BHLU(MESS)
 K KFM
 Q
ZV1 ;
 ;add fields
 ;
ZV1FLD N I,FLD01,FLD02,FLD03,FLD3,FLD5,ADD
 F I="HL IHS DW1 ZV1-39" D
 . S FLD01=I
 . S FLD02="STRING"
 . S FLD03=999
 . S FLD3="""OUTPUT TRANSFORM"""
 . S FLD5="S X=$$WS^BDWUTIL1(BHLVIEN)"
 . S ADD=$$CHKF^INMPORT(FLD01,FLD02,FLD03,FLD3,FLD5)
 F I="HL IHS DW1 ZV1-40" D
 . S FLD01=I
 . S FLD02="STRING"
 . S FLD03=999
 . S FLD3="""OUTPUT TRANSFORM"""
 . S FLD5="S X=$$FTF^BDWUTIL1(BHLVIEN)"
 . S ADD=$$CHKF^INMPORT(FLD01,FLD02,FLD03,FLD3,FLD5)
ZV1SEG ;-- add the fields to the segment
 N J,SEGI,SEGA,SEGF
 S SEGI=$O(^INTHL7S("B","HL IHS DW1 ZV1",0))
 Q:'SEGI
 F J="HL IHS DW1 ZV1-39","HL IHS DW1 ZV1-40" D
 . S SEGF=$O(^INTHL7F("B",J,0))
 . Q:'SEGF
 . Q:$O(^INTHL7S(SEGI,1,"B",SEGF,0))
 . S SEGA=$$SFADD^INMPORT(SEGI,SEGF,$P(J,"-",2),"")
 Q
ZDX ;
 ;add fields
 ;
ZDXFLD N I,FLD01,FLD02,FLD03,FLD3,FLD5,ADD
 F I="HL IHS DW1 ZDX-8","HL IHS DW1 ZDX-9","HL IHS DW1 ZDX-10","HL IHS DW1 ZDX-11","HL IHS DW1 ZDX-12","HL IHS DW1 ZDX-13","HL IHS DW1 ZDX-14" D
 . S FLD01=I
 . S FLD02="STRING"
 . S FLD03=999
 . S FLD3="@BDW1ZDX"_$P(I,"-",2)
 . S FLD5=""
 . S ADD=$$CHKF^INMPORT(FLD01,FLD02,FLD03,FLD3,FLD5)
ZDXSEG ;-- add the fields to the segment
 N J,SEGI,SEGA,SEGF
 S SEGI=$O(^INTHL7S("B","HL IHS DW1 ZDX",0))
 Q:'SEGI
 F J="HL IHS DW1 ZDX-8","HL IHS DW1 ZDX-9","HL IHS DW1 ZDX-10","HL IHS DW1 ZDX-11","HL IHS DW1 ZDX-12","HL IHS DW1 ZDX-13","HL IHS DW1 ZDX-14" D
 . S SEGF=$O(^INTHL7F("B",J,0))
 . Q:'SEGF
 . Q:$O(^INTHL7S(SEGI,1,"B",SEGF,0))
 . S SEGA=$$SFADD^INMPORT(SEGI,SEGF,$P(J,"-",2),"")
 Q
WH ;add field
 N I,FLD01,FLD02,FLD03,FLD3,FLD5,ADD
 F I="HL IHS DW1ALPMR OBX WH-16" D
 . S FLD01=I
 . S FLD02="STRING"
 . S FLD03=999
 . S FLD3="@BDW1WH16"
 . S FLD5=""
 . S ADD=$$CHKF^INMPORT(FLD01,FLD02,FLD03,FLD3,FLD5)
 Q
PV1HOPE ;
 ;add pv1-3
 ;FIX PV1-3 FIELD
 N J,SEGI,SEGA,SEGF,F
 S F=$O(^INTHL7F("B","HL IHS DW1 PV1-3",0))
 I F S ^INTHL7F(F,5)="S X=$$LOCENC^BDWUTIL2(BHLVIEN,""C"")"
 S SEGI=$O(^INTHL7S("B","HL IHS DW1HOPE PV1",0))
 Q:'SEGI
 F J="HL IHS DW1 PV1-3" D
 . S SEGF=$O(^INTHL7F("B",J,0))
 . Q:'SEGF
 . Q:$O(^INTHL7S(SEGI,1,"B",SEGF,0))
 . S SEGA=$$SFADD^INMPORT(SEGI,SEGF,$P(J,"-",2),"")
 Q
RXD ;
 ;-add the RXD segment to the message
 N MESS,SEG
 S MESS=$O(^INTHL7M("B","HL IHS DW1 A08",0))
 Q:'MESS
 S SEG=$O(^INTHL7S("B","HL IHS DW1 RXD",0))
 Q:'SEG
 Q:$O(^INTHL7M(MESS,1,"B",SEG,0))
 N FDA,FIENS,FERR
 S FIENS="+2,"_MESS_","
 S FDA(4011.01,FIENS,.01)=SEG
 S FDA(4011.01,FIENS,.02)=240
 S FDA(4011.01,FIENS,.03)=1
 S FDA(4011.01,FIENS,.07)="P"
 S FDA(4011.01,FIENS,.12)="RXD"
 D UPDATE^DIE("","FDA","FIENS","FERR(1)")
 ;D COMPILE^BHLU(MESS)
 Q
ZVP ;
 ;add fields
 ;
ZVPFLD N I,FLD01,FLD02,FLD03,FLD3,FLD5,ADD
 F I="HL IHS DW1 ZVP-8","HL IHS DW1 ZVP-9","HL IHS DW1 ZVP-10","HL IHS DW1 ZVP-11" D
 . S FLD01=I
 . S FLD02="STRING"
 . S FLD03=999
 . S FLD3="@BDW1ZVP"_$P(I,"-",2)
 . S FLD5=""
 . S ADD=$$CHKF^INMPORT(FLD01,FLD02,FLD03,FLD3,FLD5)
ZVPSEG ;-- add the fields to the segment
 N J,SEGI,SEGA,SEGF
 S SEGI=$O(^INTHL7S("B","HL IHS DW1 ZVP",0))
 Q:'SEGI
 F J="HL IHS DW1 ZVP-8","HL IHS DW1 ZVP-9","HL IHS DW1 ZVP-10","HL IHS DW1 ZVP-11" D
 . S SEGF=$O(^INTHL7F("B",J,0))
 . Q:'SEGF
 . Q:$O(^INTHL7S(SEGI,1,"B",SEGF,0))
 . S SEGA=$$SFADD^INMPORT(SEGI,SEGF,$P(J,"-",2),"")
 Q
ZMD ;
 ;add fields
 ;
ZMDFLD N I,FLD01,FLD02,FLD03,FLD3,FLD5,ADD
 F I="HL IHS DW1 ZMD-7","HL IHS DW1 ZMD-10","HL IHS DW1 ZMD-11","HL IHS DW1 ZMD-12","HL IHS DW1 ZMD-13","HL IHS DW1 ZMD-20" D
 . S FLD01=I
 . S FLD02="STRING"
 . S FLD03=999
 . S FLD3="@BDW1ZMD"_$P(I,"-",2)
 . S FLD5=""
 . S ADD=$$CHKF^INMPORT(FLD01,FLD02,FLD03,FLD3,FLD5)
ZMDSEG ;-- add the fields to the segment
 N J,SEGI,SEGA,SEGF
 S SEGI=$O(^INTHL7S("B","HL IHS DW1 ZMD",0))
 Q:'SEGI
 F J="HL IHS DW1 ZMD-7","HL IHS DW1 ZMD-10","HL IHS DW1 ZMD-11","HL IHS DW1 ZMD-12","HL IHS DW1 ZMD-13","HL IHS DW1 ZMD-20" D
 . S SEGF=$O(^INTHL7F("B",J,0))
 . Q:'SEGF
 . Q:$O(^INTHL7S(SEGI,1,"B",SEGF,0))
 . S SEGA=$$SFADD^INMPORT(SEGI,SEGF,$P(J,"-",2),"")
 Q
 ;
ZWH ;
 ;add fields
 ;
ZWHSEGA ;-- add the segment
 N SEG
 S SEG="HL IHS DW1 ZWH"
 Q:$O(^INTHL7S("B",SEG,0))
 S SEGADD=$$CHKS^INMPORT(SEG,"ZWH")
 ;
ZWHFLD N I,FLD01,FLD02,FLD03,FLD3,FLD5,ADD
 F I="HL IHS DW1 ZWH-1","HL IHS DW1 ZWH-2","HL IHS DW1 ZWH-3","HL IHS DW1 ZWH-4" D
 . S FLD01=I
 . S FLD02="STRING"
 . S FLD03=999
 . S FLD3="@BDW1ZWH"_$P(I,"-",2)
 . S FLD5=""
 . S ADD=$$CHKF^INMPORT(FLD01,FLD02,FLD03,FLD3,FLD5)
ZWHSEG ;-- add the fields to the segment
 N J,SEGI,SEGA,SEGF
 S SEGI=$O(^INTHL7S("B","HL IHS DW1 ZWH",0))
 Q:'SEGI
 F J="HL IHS DW1 ZWH-1","HL IHS DW1 ZWH-2","HL IHS DW1 ZWH-3","HL IHS DW1 ZWH-4" D
 . S SEGF=$O(^INTHL7F("B",J,0))
 . Q:'SEGF
 . Q:$O(^INTHL7S(SEGI,1,"B",SEGF,0))
 . S SEGA=$$SFADD^INMPORT(SEGI,SEGF,$P(J,"-",2),"")
 ;-add the ZWH segment to the message
 N MESS,SEG
 S MESS=$O(^INTHL7M("B","HL IHS DW1 A08",0))
 Q:'MESS
 S SEG=$O(^INTHL7S("B","HL IHS DW1 ZWH",0))
 Q:'SEG
 Q:$O(^INTHL7M(MESS,1,"B",SEG,0))
 N FDA,FIENS,FERR
 S FIENS="+2,"_MESS_","
 S FDA(4011.01,FIENS,.01)=SEG
 S FDA(4011.01,FIENS,.02)=250
 S FDA(4011.01,FIENS,.03)=0
 ;S FDA(4011.01,FIENS,.07)="P"
 ;S FDA(4011.01,FIENS,.12)="ZWH"
 D UPDATE^DIE("","FDA","FIENS","FERR(1)")
 ;D COMPILE^BHLU(MESS)
 Q
ZP2 ;
 ;add fields
 ;
ZP2FLD N I,FLD01,FLD02,FLD03,FLD3,FLD5,ADD
 F I="HL IHS DW1 ZP2-36","HL IHS DW1 ZP2-37","HL IHS DW1 ZP2-38","HL IHS DW1 ZP2-39","HL IHS DW1 ZP2-40","HL IHS DW1 ZP2-41" D
 . S FLD01=I
 . S FLD02="STRING"
 . S FLD03=999
 . S FLD3="@BDW1ZP2"_$P(I,"-",2)
 . S FLD5=""
 . S ADD=$$CHKF^INMPORT(FLD01,FLD02,FLD03,FLD3,FLD5)
ZP2SEG ;-- add the fields to the segment
 N J,SEGI,SEGA,SEGF
 S SEGI=$O(^INTHL7S("B","HL IHS DW1 ZP2",0))
 Q:'SEGI
 F J="HL IHS DW1 ZP2-36","HL IHS DW1 ZP2-37","HL IHS DW1 ZP2-38","HL IHS DW1 ZP2-39","HL IHS DW1 ZP2-40","HL IHS DW1 ZP2-41" D
 . S SEGF=$O(^INTHL7F("B",J,0))
 . Q:'SEGF
 . Q:$O(^INTHL7S(SEGI,1,"B",SEGF,0))
 . S SEGA=$$SFADD^INMPORT(SEGI,SEGF,$P(J,"-",2),"")
 Q
XAM ;
 ;add fields
 ;
 S KFM="K DIE,DR,DIC,DA,DD,DO,DIK"
XAMFLD N I,FLD01,FLD02,FLD03,FLD3,FLD5,ADD
 F I="HL IHS DW1 OBX XAM-4" D
 . S FLD01=I
 . S FLD02="STRING"
 . S FLD03=999
 . S FLD3="@BDW1XAM"_$P(I,"-",2)
 . S FLD5=""
 . S ADD=$$CHKF^INMPORT(FLD01,FLD02,FLD03,FLD3,FLD5)
 Q
PED ;
 ;add fields
 ;
 S KFM="K DIE,DR,DIC,DA,DD,DO,DIK"
PEDFLD N I,FLD01,FLD02,FLD03,FLD3,FLD5,ADD
 F I="HL IHS DW1 OBX PED-6" D
 . S FLD01=I
 . S FLD02="STRING"
 . S FLD03=999
 . S FLD3="@BDW1PED"_$P(I,"-",2)
 . S FLD5=""
 . S ADD=$$CHKF^INMPORT(FLD01,FLD02,FLD03,FLD3,FLD5)
 Q
MES ;-add the ifc segment to the message
 N MESS,SEG
 S MESS=$O(^INTHL7M("B","HL IHS DW1 A08",0))
 Q:'MESS
 S SEG=$O(^INTHL7S("B","HL IHS DW1ALPMR OBX IFC",0))
 Q:'SEG
 Q:$O(^INTHL7M(MESS,1,"B",SEG,0))
 N FDA,FIENS,FERR
 S FIENS="+2,"_MESS_","
 S FDA(4011.01,FIENS,.01)=SEG
 S FDA(4011.01,FIENS,.02)=230
 S FDA(4011.01,FIENS,.03)=1
 S FDA(4011.01,FIENS,.07)="P"
 S FDA(4011.01,FIENS,.12)="IFC"
 D UPDATE^DIE("","FDA","FIENS","FERR(1)")
 ;D COMPILE^BHLU(MESS)
 Q
PID ;
 ;-- populate the PID-15 field of GIS, then recompile
 S KFM="K DIE,DR,DIC,DA,DD,DO,DIK"
 F I="HL IHS DW1 PID-15" D
 . S FLD01=I
 . S FLD02="STRING"
 . S FLD03=999
 . S FLD3="""OUTPUT TRANSFORM"""
 . S FLD5="S X=$$PRIMLANG^BDWUTIL2(DFN)"
 . S ADD=$$CHKF^INMPORT(FLD01,FLD02,FLD03,FLD3,FLD5)
 Q
ZPL ;
 ;add fields
 S KFM="K DIE,DR,DIC,DA,DD,DO,DIK"
 ;
ZPLFLD N I,FLD01,FLD02,FLD03,FLD3,FLD5,ADD
 F I="HL IHS DW1ALPMR ZPL-12","HL IHS DW1ALPMR ZPL-13","HL IHS DW1ALPMR ZPL-14","HL IHS DW1ALPMR ZPL-15" D
 . S FLD01=I
 . S FLD02="STRING"
 . S FLD03=999
 . S FLD3="@BDW1ZPB"_$P(I,"-",2)
 . S FLD5=""
 . S ADD=$$CHKF^INMPORT(FLD01,FLD02,FLD03,FLD3,FLD5)
ZPLSEG ;-- add the fields to the segment
 N J,SEGI,SEGA,SEGF
 S SEGI=$O(^INTHL7S("B","HL IHS DW1ALPMR ZPL",0))
 Q:'SEGI
 F J="HL IHS DW1ALPMR ZPL-12","HL IHS DW1ALPMR ZPL-13","HL IHS DW1ALPMR ZPL-14","HL IHS DW1ALPMR ZPL-15" D
 . S SEGF=$O(^INTHL7F("B",J,0))
 . Q:'SEGF
 . Q:$O(^INTHL7S(SEGI,1,"B",SEGF,0))
 . S SEGA=$$SFADD^INMPORT(SEGI,SEGF,$P(J,"-",2),"")
 Q
ZPT ;
 ;add fields
 ;
ZPTSEGA ;-- add the segment
 N SEG
 S SEG="HL IHS DW1 ZPT"
 Q:$O(^INTHL7S("B",SEG,0))
 S SEGADD=$$CHKS^INMPORT(SEG,"ZPT")
 ;
ZPTFLD N I,FLD01,FLD02,FLD03,FLD3,FLD5,ADD
 F I="HL IHS DW1 ZPT-1","HL IHS DW1 ZPT-2","HL IHS DW1 ZPT-3","HL IHS DW1 ZPT-4","HL IHS DW1 ZPT-5" D
 . S FLD01=I
 . S FLD02="STRING"
 . S FLD03=999
 . S FLD3="@BDW1ZPT"_$P(I,"-",2)
 . S FLD5=""
 . S ADD=$$CHKF^INMPORT(FLD01,FLD02,FLD03,FLD3,FLD5)
ZPTSEG ;-- add the fields to the segment
 N J,SEGI,SEGA,SEGF
 S SEGI=$O(^INTHL7S("B","HL IHS DW1 ZPT",0))
 Q:'SEGI
 F J="HL IHS DW1 ZPT-1","HL IHS DW1 ZPT-2","HL IHS DW1 ZPT-3","HL IHS DW1 ZPT-4","HL IHS DW1 ZPT-5" D
 . S SEGF=$O(^INTHL7F("B",J,0))
 . Q:'SEGF
 . Q:$O(^INTHL7S(SEGI,1,"B",SEGF,0))
 . S SEGA=$$SFADD^INMPORT(SEGI,SEGF,$P(J,"-",2),"")
 ;-add the ZPT segment to the message
 N MESS,SEG
 S MESS=$O(^INTHL7M("B","HL IHS DW1 A08",0))
 Q:'MESS
 S SEG=$O(^INTHL7S("B","HL IHS DW1 ZPT",0))
 Q:'SEG
 Q:$O(^INTHL7M(MESS,1,"B",SEG,0))
 N FDA,FIENS,FERR
 S FIENS="+2,"_MESS_","
 S FDA(4011.01,FIENS,.01)=SEG
 S FDA(4011.01,FIENS,.02)=260
 S FDA(4011.01,FIENS,.03)=1
 S FDA(4011.01,FIENS,.07)="P"
 S FDA(4011.01,FIENS,.12)="ZPT"
 D UPDATE^DIE("","FDA","FIENS","FERR(1)")
 ;D COMPILE^BHLU(MESS)
 Q
