BDWUTIL2 ; IHS/CMI/LAB - Data Warehouse Utilities ; 05 Dec 2022  5:32 PM
 ;;1.0;IHS DATA WAREHOUSE;**4,8,9,10,11**;JAN 24, 2006;Build 14
 ;
 ;
 ;
PRB(RETVAL,BDWP) ;EP
 N PRB,DX,DXS,DXI,DXD,DXT,DTA,DLM,PN,FAC,POVN,SC,ST,DTDL,DTO,CNT
 K RETVAL
 I '$D(^AUPNPROB("AC",BDWP)) Q
 S CNT=0
 N PDA,DATA
 S PDA=0 F  S PDA=$O(^AUPNPROB("AC",BDWP,PDA)) Q:'PDA  D
 . S CNT=CNT+1
 . S DATA=$G(^AUPNPROB(PDA,0))
 . S DXI=$P(DATA,U)
 . I $D(^ICDS(0)) S DXS=$$ICDDX^ICDEX(DXI)
 . I '$D(^ICDS(0)) S DXS=$$ICDDX^ICDCODE(DXI)
 . S DX=$TR($P(DXS,U,2),"|","")
 . ;S DXD=$TR($P(DXS,U,4),"|","")  ;IHS/CMI/LAB COMMENTED OUT
 . S DXD=""   ;IHS/CMI/LAB REMOVE DX NARRATIVE
 . S DXT=$P(DXS,U,20)
 . S DXT=$S(DXT=30:"I10",1:"I9")
 . S DTA=$$FMTHL7^XLFDT($E($P(DATA,U,8),1,7))
 . S DLM=$$FMTHL7^XLFDT($E($P(DATA,U,3),1,7))
 . S PN=$P(DATA,U,7)
 . S FAC=$$GET1^DIQ(9999999.06,$P(DATA,U,6),.12)
 . S POVN=$$GET1^DIQ(9000011,PDA,.05)
 . S POVN=$TR(POVN,"|","")
 . S SC=$P(DATA,U,12)
 . S ST=$$GET1^DIQ(9000011,PDA,.12)
 . S DTDL=$$FMTHL7^XLFDT($E($P($G(^AUPNPROB(PDA,2)),U,2),1,7))
 . S DTO=$$FMTHL7^XLFDT($E($P(DATA,U,13),1,7))
 . S RETVAL(CNT)=DX_U_DXD_U_DXT_U_DTA_U_DLM_U_PN_U_FAC_U_POVN_U_SC_U_ST_U_DTDL_U_DTO
 . ;P8
 . S $P(RETVAL(CNT),U,13)=$$VALI^XBDIQ1(9000011,PDA,80001)  ;SNOMED CONCEPT ID
 . S $P(RETVAL(CNT),U,14)=$TR($$VALI^XBDIQ1(9000011,PDA,.22),"|","*")  ;LATERALITY
 . NEW I,V,Y
 . ;SEVERITY
 . S I=0,V="" F  S I=$O(^AUPNPROB(PDA,13,I)) Q:I'=+I  D
 .. S Y=$P($G(^AUPNPROB(PDA,13,I,0)),U,1)
 .. I V]"" S V=V_"~"
 .. S V=V_Y
 . S $P(RETVAL(CNT),U,15)=V
 . ;CLINICAL COURSE
 . S I=0,V="" F  S I=$O(^AUPNPROB(PDA,18,I)) Q:I'=+I  D
 .. S Y=$P($G(^AUPNPROB(PDA,18,I,0)),U,1)
 .. I V]"" S V=V_"~"
 .. S V=V_Y
 . S $P(RETVAL(CNT),U,16)=V
 Q
 ;
REF(RETVAL,BDWP) ;EP
 N REF,RFT,RFI,DTR,RFRC,RFRT,DLM,FL,RFIMM,RFN
 K RETVAL
 I '$D(^AUPNPREF("AC",BDWP)) Q
 S CNT=0
 N PDA,DATA
 S PDA=0 F  S PDA=$O(^AUPNPREF("AC",BDWP,PDA)) Q:'PDA  D
 . S RFIMM=""
 . S CNT=CNT+1
 . S DATA=$G(^AUPNPREF(PDA,0))
 . S RFT=$$GET1^DIQ(9000022,PDA,.01)
 . S FL=$P(DATA,U,5)
 . S RFI=$P(DATA,U,6)
 . S RFN=$$GET1^DIQ(FL,RFI,.01)
 . I FL=9999999.14 S RFIMM=$$GET1^DIQ(FL,RFI,.03)  ;special for immunization refusals patch 8
 . S DTR=$$FMTHL7^XLFDT($P(DATA,U,3))
 . S RFRC=$P(DATA,U,7)
 . S RFRT=$$GET1^DIQ(9000022,PDA,.07)
 . S DLM=$$FMTHL7^XLFDT($E($P(DATA,U,8),1,7))
 . S V="|"
 . I FL'=9999999.14 S RETVAL(CNT)=RFT_V_RFN_V_DTR_V_RFRC_V_RFRT_V_DLM
 . I FL=9999999.14 S RETVAL(CNT)=RFT_V_RFIMM_"^"_RFN_"^CVX"_V_DTR_V_RFRC_V_RFRT_V_DLM
 Q
 ;
IMC(RETVAL,BDWP) ;EP
 N VAC,RC,DTN,VACI
 K RETVAL
 I '$D(^BIPC("B",BDWP)) Q
 S CNT=0
 N PDA,DATA
 S PDA=0 F  S PDA=$O(^BIPC("B",BDWP,PDA)) Q:'PDA  D
 . S CNT=CNT+1
 . S VACI=$$GET1^DIQ(9002084.11,PDA,.02,"I")
 . S VAC=$$GET1^DIQ(9999999.14,VACI,.03)
 . S RC=$$GET1^DIQ(9002084.11,PDA,.03)
 . S DTN=$$FMTHL7^XLFDT($$GET1^DIQ(9002084.11,PDA,.04,"I"))
 . S RETVAL(CNT)=VAC_U_RC_U_DTN
 Q
 ;
WH(RETVAL,BDWP) ;EP
 N WHP,RS,PDT
 K RETVAL
 I '$D(^BWPCD("C",BDWP)) Q
 S CNT=0
 N PDA,DATA
 S PDA=0 F  S PDA=$O(^BWPCD("C",BDWP,PDA)) Q:'PDA  D
 . S CNT=CNT+1
 . S WHP=$$GET1^DIQ(9002086.1,PDA,.04)
 . S RS=$$GET1^DIQ(9002086.1,PDA,.05)
 . S PDT=$$FMTHL7^XLFDT($$GET1^DIQ(9002086.1,PDA,.12,"I"))
 . S RETVAL(CNT)=WHP_U_RS_U_PDT_U_$$VAL^XBDIQ1(9002086.1,PDA,.08)
 Q
 ;
PRIMLANG(BDWP) ;
 I '$G(BDWP) Q ""
 NEW LDA,A,B
 S LDA=$O(^AUPNPAT(BDWP,86,"B"),-1)
 I 'LDA Q ""
 S A=$P($G(^AUPNPAT(BDWP,86,LDA,0)),U,2)  ;primary language
 I 'A Q ""
 S B=$P($G(^AUTTLANG(A,0)),U,3)
 Q B_"^"_$P($G(^AUTTLANG(A,0)),U,1)_"^"_"ISO 639"
PREFLANG(BDWP) ;
 I '$G(BDWP) Q ""
 NEW LDA,A,B
 S LDA=$O(^AUPNPAT(BDWP,86,"B"),-1)
 I 'LDA Q ""
 S A=$P($G(^AUPNPAT(BDWP,86,LDA,0)),U,4)  ;preferred language
 I 'A Q ""
 S B=$P($G(^AUTTLANG(A,0)),U,3)
 Q B_"^"_$P($G(^AUTTLANG(A,0)),U,1)_"^"_"ISO 639"
OTHLANG(BDWP) ;
 I '$G(BDWP) Q ""
 NEW LDA,A,B,Z
 S LDA=$O(^AUPNPAT(BDWP,86,"B"),-1)
 I 'LDA Q ""
 S Z=""
 S A=0 F  S A=$O(^AUPNPAT(BDWP,86,LDA,5,"B",A)) Q:A=""  D
 .S B=$P($G(^AUTTLANG(A,0)),U,3)
 .I Z]"" S Z=Z_"~"
 .S Z=Z_B_"^"_$P($G(^AUTTLANG(A,0)),U,1)_"^"_"ISO 639"
 Q Z
ENGPROF(BDWP) ;
 I '$G(BDWP) Q ""
 NEW LDA,A,B
 S LDA=$O(^AUPNPAT(BDWP,86,"B"),-1)
 I 'LDA Q ""
 S A=$P($G(^AUPNPAT(BDWP,86,LDA,0)),U,6)  ;english proficiency
 I A="" Q ""
 S B=LDA_","_BDWP_","
 Q $$GET1^DIQ(9000001.86,B,.06,"E")
ZPT(RETVAL,BDWP) ;
 I '$G(BDWP) Q ""
 NEW PCP,PDA,TDA,P,PNPI,PN,PDISC,TN
 K RETVAL
 S PCP=$$VALI^XBDIQ1(9000001,BDWP,.14)  ;get PCP
 I 'PCP Q  ;NO PCP SO NO TEAMS
 S CNT=0
 S PDA=0 F  S PDA=$O(^BSDPCT("AB",PCP,PDA)) Q:'PDA  D    ;teams the PCP is on
 . ;S CNT=CNT+1
 . ;get all providers on this team
 . S TN=$$VAL^XBDIQ1(9009017.5,PDA,.01)
 . S TDA=0 F  S TDA=$O(^BSDPCT(PDA,1,TDA)) Q:TDA'=+TDA  D
 .. S CNT=CNT+1
 .. S P=$P($G(^BSDPCT(PDA,1,TDA,0)),U,1)
 .. S PN=$$HLNAME^HLFNC($P($G(^VA(200,P,0)),U,1),"^")
 .. S PNPI=$$VAL^XBDIQ1(200,P,41.99)
 .. S PDISC=$$CLS^BDWUTIL(P)
 .. S RETVAL(CNT)=TN_"|"_PN_"|"_PNPI_"|"_PDISC
 Q
LOCENC(V,F) ;EP - given visit ien V, return loc. of encounter in format F
 I 'V Q ""
 I '$D(^AUPNVSIT(V)) Q ""
 NEW Y
 S Y=$P(^AUPNVSIT(V,0),U,6)
 I Y="" Q Y
 I '$D(^AUTTLOC(Y)) Q ""
 Q $S($G(F)="E":$P(^DIC(4,Y,0),U),$G(F)="C":$P(^AUTTLOC(Y,0),U,10),1:Y)
 ;
ESCAPE(VALUE) ;EP
 ;Replaces the HL7 encoding characters with the corresponding escape sequences and returns the result as the function value
 ;
 N ESC,CHARS,I,NEWVALUE,LEN,CUR,FLD
 ;S CHARS=HLMSTATE("HDR","ENCODING CHARACTERS")   ;IHS/CMI/LAB COMMENTED OUT
 S CHARS="^~\&"  ;IHS/CMI/LAB - ADDED
 S ESC=$E(CHARS,3)
 S FLD="|"
 S NEWVALUE="",LEN=$L(VALUE)
 F I=1:1:LEN D
 .S CUR=$E(VALUE,I)
 .;IHS/MSC/MGH The following line from HL patch 132 was added for E-prescribing
 .;S NEWVALUE=NEWVALUE_$S(CUR=ESC:ESC_"E"_ESC,CUR=$E(CHARS,1):ESC_"S"_ESC,CUR=$E(CHARS,4):ESC_"T"_ESC,CUR=$E(CHARS,2):ESC_"R"_ESC,1:CUR)
 .;S NEWVALUE=NEWVALUE_$S(CUR=HLMSTATE("HDR","FIELD SEPARATOR"):ESC_"F"_ESC,CUR=ESC:ESC_"E"_ESC,CUR=$E(CHARS,1):ESC_"S"_ESC,CUR=$E(CHARS,4):ESC_"T"_ESC,CUR=$E(CHARS,2):ESC_"R"_ESC,1:CUR)  ;IHS/CMI/LAB COMMENTED
 .S NEWVALUE=NEWVALUE_$S(CUR=FLD:ESC_"F"_ESC,CUR=ESC:ESC_"E"_ESC,CUR=$E(CHARS,1):ESC_"S"_ESC,CUR=$E(CHARS,4):ESC_"T"_ESC,CUR=$E(CHARS,2):ESC_"R"_ESC,1:CUR)  ;IHS/CMI/LAB ADDED
 .;end mod
 Q NEWVALUE
AL(RETVAL,BDWP) ;EP
 ;returns
 ;RETVAL(CNT)=UNIQUE ID^ALLERY TYPE^ORIGINATION DATE/TIME^REACTANT^OBSERVED/HISTORICAL^VERIFIED^VERIFICATION DATE/TIME^ENTERED IN ERROR^DATE/TIME ENTRED IN ERROR
 ;RETVAL(CNT,"D",C)=DRUG INGREDIENT
 ;RETVAL(CNT,"C",C)=VA DRUG CLASS
 ;RETVAL(CNT,"R",C)=REACTION^OTHER REACTION^DATE ENTERED^INFO SOURCE^SNOMED^
 N ALDA,CNT,DIEN,X,C,%
 K RETVAL
 I '$D(^GMR(120.8,"B",BDWP)) Q
 S CNT=0
 S ALDA=0 F  S ALDA=$O(^GMR(120.8,"B",BDWP,ALDA)) Q:'ALDA  D
 . S CNT=CNT+1
 . S $P(RETVAL(CNT),U,1)=$$UIDAL(ALDA)
 . S $P(RETVAL(CNT),U,2)=$$VAL^XBDIQ1(120.8,ALDA,3.1)
 . S $P(RETVAL(CNT),U,3)=$$FMTHL7^XLFDT($$VALI^XBDIQ1(120.8,ALDA,4))
 . S $P(RETVAL(CNT),U,4)=$$VAL^XBDIQ1(120.8,ALDA,.02)
 . S $P(RETVAL(CNT),U,5)=$$VAL^XBDIQ1(120.8,ALDA,6)
 . S $P(RETVAL(CNT),U,6)=$$VAL^XBDIQ1(120.8,ALDA,19)
 . S $P(RETVAL(CNT),U,7)=$$FMTHL7^XLFDT($$VALI^XBDIQ1(120.8,ALDA,20))
 . S $P(RETVAL(CNT),U,8)=$$VAL^XBDIQ1(120.8,ALDA,22)
 . S $P(RETVAL(CNT),U,9)=$$FMTHL7^XLFDT($$VALI^XBDIQ1(120.8,ALDA,23))
 . ;DRUG INGREDIENTS
 . S C=0
 . S DIEN=0
 . F  S DIEN=$O(^GMR(120.8,ALDA,2,DIEN)) Q:DIEN'=+DIEN  D
 .. S X=$P($G(^GMR(120.8,ALDA,2,DIEN,0)),U,1)
 .. Q:'X
 .. S C=C+1
 .. S X=$$VAL^XBDIQ1(50.416,X,.01)
 .. S $P(RETVAL(CNT,"D",C),U,1)=X
 . ;DRUG CLASS
 . S C=0
 . S DIEN=0
 . F  S DIEN=$O(^GMR(120.8,ALDA,3,DIEN)) Q:DIEN'=+DIEN  D
 .. S X=$P($G(^GMR(120.8,ALDA,3,DIEN,0)),U,1)
 .. Q:'X
 .. S C=C+1
 .. S X=$$VAL^XBDIQ1(50.605,X,.01)_U_$$VAL^XBDIQ1(50.605,X,1)
 .. S $P(RETVAL(CNT,"C",C),U,1)=X
 . ;REACTION
 . S C=0
 . S DIEN=0
 . F  S DIEN=$O(^GMR(120.8,ALDA,10,DIEN)) Q:DIEN'=+DIEN  D
 .. S X=$P($G(^GMR(120.8,ALDA,10,DIEN,0)),U,1)
 .. S C=C+1
 .. I X S X=$$VAL^XBDIQ1(120.83,X,.01)
 .. S $P(RETVAL(CNT,"R",C),U,1)=X
 .. S $P(RETVAL(CNT,"R",C),U,2)=$P(^GMR(120.8,ALDA,10,DIEN,0),U,2)
 .. S $P(RETVAL(CNT,"R",C),U,3)=$$FMTHL7^XLFDT($P(^GMR(120.8,ALDA,10,DIEN,0),U,4))
 .. S X=$P($G(^GMR(120.8,ALDA,10,DIEN,9999999.11)),U,1)
 .. I X S X=$$VAL^XBDIQ1(90460.05,X,.01) S $P(RETVAL(CNT,"R",C),U,4)=X
 .. S $P(RETVAL(CNT,"R",C),U,5)=$P($G(^GMR(120.8,ALDA,10,DIEN,9999999.11)),U,2)
 . ;INACTIVE
 . S C=0
 . S DIEN=0
 . F  S DIEN=$O(^GMR(120.8,ALDA,9999999.12,DIEN)) Q:DIEN'=+DIEN  D
 .. S X=$P($G(^GMR(120.8,ALDA,9999999.12,DIEN,0)),U,1)
 .. S C=C+1
 .. S $P(RETVAL(CNT,"I",C),U,1)=$$FMTHL7^XLFDT(X)
 .. S X=$P($G(^GMR(120.8,ALDA,9999999.12,DIEN,0)),U,2)
 .. I X S $P(RETVAL(CNT,"I",C),U,2)=$P($G(^BEHOAR(90460.05,X,0)),U,1)
 .. S X=$P($G(^GMR(120.8,ALDA,9999999.12,DIEN,0)),U,4)
 .. I X S $P(RETVAL(CNT,"I",C),U,3)=$$FMTHL7^XLFDT(X)
 Q
UIDAL(I) ;EP - generate unique ID for visit
 I '$G(I) Q ""
 NEW X
 S X=$$GET1^DIQ(9999999.06,$P(^AUTTSITE(1,0),U),.32)
 Q X_$$LZERO(I,10)
 ;
LZERO(V,L) ;EP - left zero fill
 NEW %,I
 S %=$L(V),Z=L-% F I=1:1:Z S V="0"_V
 Q V
 ;
HLNAME(FL,FLD,IEN) ;-- return the name string from file 20
 N TIEN,TIENS,DATA,LN,FN,MI,SFX,DEG,RET
 S TIENS=IEN_","
 S TIEN=$O(^VA(20,"BB",FL,FLD,TIENS,0))
 I 'TIEN Q ""
 S DATA=$G(^VA(20,TIEN,1))
 S LN=$P(DATA,U)
 S FN=$P(DATA,U,2)
 S MI=$P(DATA,U,3)
 S SFX=$P(DATA,U,5)
 S DEG=$P(DATA,U,6)
 S RET=LN_U_FN_U_MI_U_SFX_U_DEG
 Q $G(RET)
 ;
RACE(P) ;EP
 NEW X,Y,Z,C,A,V,G,B,N
 S G=""
 S X=0 F  S X=$O(^DPT(P,.02,X)) Q:X'=+X  D
 .S Y=$P($G(^DPT(P,.02,X,0)),U,1)
 .Q:'Y
 .Q:'$D(^DIC(10,Y,0))
 .S N=$P(^DIC(10,Y,0),U)
 .S:G]"" G=G_"~"
 .S G=G_$P(^DIC(10,Y,0),U,3)_"^"_N_"^HL0189"
 Q G
 ;
ETHN(P) ;EP
 NEW X,Y,Z,C,A,V,G,B,N
 S G=""
 S X=0 F  S X=$O(^DPT(P,.06,X)) Q:X'=+X  D
 .S Y=$P($G(^DPT(P,.06,X,0)),U,1)
 .Q:'Y
 .Q:'$D(^DIC(10.2,Y,0))
 .S N=$P(^DIC(10.2,Y,0),U)
 .S:G]"" G=G_"~"
 .S G=G_$P(^DIC(10.2,Y,0),U,3)_"^"_N_"^HL0189"
 Q G
OTHTRIBE(P) ;EP
 NEW X,Y,Z,C,A,V,G,B,N
 S G=""
 I '$D(^AUPNPAT(P,43)) Q ""
 S X=0 F  S X=$O(^AUPNPAT(P,43,X)) Q:X'=+X  D
 .S B=$P($G(^AUPNPAT(P,43,X,0)),U,1)  ;tribe ien
 .Q:B=""
 .Q:'$D(^AUTTTRI(B,0))
 .S C=$P(^AUTTTRI(B,0),U,2)  ;IHS CODE
 .S:G]"" G=G_"~"
 .S G=G_C
 Q G
