BKMVTAX4 ;PRXM/HC/BWF - TAXONOMY SYSTEM CON'T ;  [ 04/15/03  5:05 PM ]
 ;;1.0;HIV MANAGEMENT SYSTEM;**2**;Sep 08, 2006
 ;;
LABLINIT ;EP - TO SET UP LAB LIST ARRAY
 D TAXINIT^BKMVTAX0
 Q
 ;
Z(X) ;SET TMP NODE
 S VALMCNT=$G(VALMCNT)+1
 S ^TMP("BKMVVR",$J,VALMCNT,0)=X
 Q
 ;
TAXTEXT ;EP;TO LIST CURRENT TAXONOMIES
DX ;EP;DIAGNOSES
 ;;BKMV AIDS DEF ILL DXS
 ;;BKM CHLAMYDIA DXS
 ;;BKM GONORRHEA DXS
 ;;BKM HEP A DXS
 ;;BKM HEP B DXS
 ;;BKM HEP C DXS
 ;;BGP HIV/AIDS DXS
 ;;BGP NON TOBACCO USER FACTORS
 ;;BKMV HIV OPP INF DXS
 ;;BKM OTHER STD DXS
 ;;BGP GPRA PREGNANCY DIAGNOSES
 ;;BKM STATE REPORTABLE DXS
 ;;BKM SYPHILIS DXS
 ;;BGP GPRA SMOKING DXS
 ;;BGP TOBACCO USER HLTH FACTORS
 ;;BKM TRICHOMONIASIS DXS
 ;;DM AUDIT PROBLEM TB DXS
 ;;BKM CHANCROID DXS
 ;;BKM GENITAL HERPES DXS
 ;;BKM GENITAL WARTS DXS
 ;;BKM HPV DXS
 ;;BKM LGV DXS
 ;;
ED ;EP;EDUCATION
 ;;BKM FAMILY PLANNING POV
 ;;BKMV HIV ED DXS
 ;;BKM SAFE SEX ED CODES
 ;;BKMV STD ED DXS
 ;;BKM STD ED CODES
 ;;BGP TOBACCO CESS DENTAL CODE
 ;;
IZ ;EP;IMMUNIZATIONS
 ;;BKM BCG IZ CPTS
 ;;BKM BCG IZ PROCEDURE
 ;;BKM BCG IZ CVX CODES
 ;;BKM CMV IZ CPTS
 ;;BKM CMV IZ CVX CODES
 ;;BKM HEP A IZ CPTS
 ;;BKM HEP A IZ CVX CODES
 ;;BKM HEP B IZ CPTS
 ;;BKM HEP B IZ CVX CODES
 ;;BGP CPT FLU
 ;;BGP FLU IZ DXS
 ;;BGP FLU IZ PROCEDURES
 ;;BGP FLU IZ CVX CODES
 ;;BGP PNEUMO IZ CPTS
 ;;BGP PNEUMO IZ DXS
 ;;BGP PNEUMO IZ PROCEDURES
 ;;BKM PNEUMO IZ CVX CODES
 ;;BKM TETANUS IZ CPTS
 ;;BKM TETANUS IZ DXS
 ;;BKM TETANUS IZ PROCEDURES
 ;;BKM TETANUS IZ CVX CODES
 ;;
M ;EP;MEDICATIONS
 ;;BKMV FI MED NDCS
 ;;BKMV FI MEDS
 ;;BKMV MAC PROPH MED NDCS
 ;;BKMV MAC PROPH MEDS
 ;;BKMV NNRTI MED NDCS
 ;;BKMV NNRTI MEDS
 ;;BKMV NRTI MED NDCS
 ;;BKMV NRTI MEDS
 ;;BKMV PCP PROPH MED NDCS
 ;;BKMV PCP PROPH MEDS
 ;;BKMV PI MED NDCS
 ;;BKMV PI MEDS
 ;;BKM TB MED NDCS
 ;;BKM TB MEDS
 ;;
P ;EP;PROCEDURES
 ;;BGP MASTECTOMY PROCEDURES
 ;;BKM DENTAL EXAMINATION
 ;;BGP DENTAL EXAM DENTAL CODE
 ;;BGP EYE EXAM CPTS
 ;;BGP HYSTERECTOMY CPTS
 ;;BGP HYSTERECTOMY PROCEDURES
 ;;BGP CPT MAMMOGRAM
 ;;BGP MAMMOGRAM ICDS
 ;;BGP MAMMOGRAM PROCEDURES
 ;;
S ;EP;SCREENING
 ;;BGP ALCOHOL SCREEN ICDS
 ;;BGP ALCOHOL DXS
 ;;BGP ALCOHOL HLTH FACTOR
 ;;BGP MOOD DISORDERS
 ;;BKM OTHER SUBSTANCE ABUSE DXS
 ;;BGP GPRA SMOKING DXS
 ;;BGP TOBACCO SCREEN HLTH FACTOR
 ;;BGP TOBACCO CESS DENTAL CODE
 ;;
T ;EP;LAB TESTS
 ;;BGP CD4 CPTS
 ;;BGP CD4 LOINC CODES
 ;;BGP CD4 TAX
 ;;BGP CHLAMYDIA CPTS
 ;;BGP CHLAMYDIA TEST PROCEDURES
 ;;BGP CHLAMYDIA LOINC CODES
 ;;BGP CHLAMYDIA TESTS TAX
 ;;BKM CMV TEST CPTS
 ;;BKM CMV LOINC CODES
 ;;BKM CMV TEST TAX
 ;;BKM COCCI ANTIBODY CPTS
 ;;BKM COCCI ANTIBODY LOINC CODES
 ;;BKM COCCI ANTIBODY TAX
 ;;BKM FTA-ABS CPTS
 ;;BKM FTA-ABS LOINC CODES
 ;;BKM FTA-ABS TEST TAX
 ;;BKM GONORRHEA TESTS CPTS
 ;;BKM GONORRHEA LOINC CODES
 ;;BKM GONORRHEA TEST TAX
 ;;BKM HEPATITIS PANEL CPTS
 ;;BKM HEP PANEL LOINC CODES
 ;;BKM HEPATITIS PANEL TAX
 ;;BKM HEP B TESTS CPTS
 ;;BKM HEP B LOINC CODES
 ;;BKM HEP B TAX
 ;;BKM HEP C EIA TESTS CPTS
 ;;BKM HEP C EIA LOINC CODES
 ;;BKM HEP C EIA TAX
 ;;BKM HEP C RIBA TESTS CPTS
 ;;BKM HEP C RIBA LOINC CODES
 ;;BKM HEP C RIBA TAX
 ;;BKMV HIV GENOTYPE CPTS
 ;;BKMV HIV GENOTYPE TESTS TAX
 ;;BKMV HIV PHENOTYPE CPTS
 ;;BKMV HIV PHENOTYPE TESTS TAX
 ;;BGP CPT HIV TESTS
 ;;BGP HIV TEST LOINC CODES
 ;;BGP HIV TEST TAX
 ;;BGP CPT PAP
 ;;BGP PAP ICDS
 ;;BGP PAP PROCEDURES
 ;;BGP PAP LOINC CODES
 ;;BGP PAP SMEAR TAX
 ;;BKM PPD CPTS
 ;;BKM PPD ICDS
 ;;BKM PPD LOINC CODES
 ;;BKM PPD TAX
 ;;BKM PPD CVX CODES
 ;;BKM RPR CPTS
 ;;BKM RPR LOINC CODES
 ;;BKM RPR TAX
 ;;BKM TOXOPLASMOSIS CPTS
 ;;BKM TOXOPLASMOSIS LOINC CODES
 ;;BKM TOXOPLASMOSIS TESTS TAX
 ;;BGP HIV VIRAL LOAD CPTS
 ;;BGP VIRAL LOAD LOINC CODES
 ;;BGP HIV VIRAL LOAD TAX
 ;;BKMV CD4 ABS CPTS
 ;;BKMV CD4 ABS LOINC CODES
 ;;BKM CD4 ABS TESTS TAX
 ;;
O ;EP;OTHER
 ;;BGP DV DXS
 ;;BGP IPV/DV COUNSELING ICDS
 ;;
RX ;EP;MEDICATIONS (SITE-POPULATED)
 ;;BKMV FI MEDS
 ;;BKMV MAC PROPH MEDS
 ;;BKMV NNRTI MEDS
 ;;BKMV NRTI MEDS
 ;;BKMV PCP PROPH MEDS
 ;;BKMV PI MEDS
 ;;BKM TB MEDS
 ;;
LAB ;EP;LAB TESTS (SITE-POPULATED)
 ;;BGP CD4 TAX
 ;;BGP CHLAMYDIA TESTS TAX
 ;;BKM CMV TEST TAX
 ;;BKM COCCI ANTIBODY TAX
 ;;BKM FTA-ABS TEST TAX
 ;;BKM GONORRHEA TEST TAX
 ;;BKM HEPATITIS PANEL TAX
 ;;BKM HEP B TAX
 ;;BKM HEP C EIA TAX
 ;;BKM HEP C RIBA TAX
 ;;BKMV HIV GENOTYPE TESTS TAX
 ;;BKMV HIV PHENOTYPE TESTS TAX
 ;;BGP HIV TEST TAX
 ;;BGP PAP SMEAR TAX
 ;;BKM PPD TAX
 ;;BKM RPR TAX
 ;;BKM TOXOPLASMOSIS TESTS TAX
 ;;BGP HIV VIRAL LOAD TAX
 ;;BKM CD4 ABS TESTS TAX
 ;;
 Q
 ;
LDLAB(ARRAY) ;EP;Load site-populated Lab tests
 N I,TEXT
 F I=1:1 S TEXT=$P($T(LAB+I),";;",2) Q:TEXT=""  S ARRAY(I)=TEXT
 Q
 ;
PROCESS(X,BKMVTAX) ;EP - TO PROCESS AND DISPLAY DIFFERENT GROUPS OF HMS TAXONOMIES
 K BKMVTAX
 N EP,J,Y,Z
 S EP=$S(X="DIAGNOSIS":"DX",X="HMS IMMUNIZATION":"IZ",1:X)
 ; Valid values for EP are: "DX","ED","IZ","M","P","S","T","O", or "ALL"
 ; These are tag names earlier in the routine. (Except for "ALL" which is handled with a loop below.)
 I EP="ALL" D  Q
 . F EP="DX","ED","IZ","M","P","S","T","O" D
 .. F J=1:1 S Y=$P($T(@EP+J),";;",2) Q:Y=""  D
 ... S Z=$O(^ATXAX("B",Y,0))
 ... I Z="" S Z=$O(^ATXLAB("B",Y,0))
 ... I Z S BKMVTAX(Y)=Z
 ... Q
 .. Q
 . Q
 ;
 F J=1:1 S Y=$P($T(@EP+J),";;",2) Q:Y=""  D
 . S Z=$O(^ATXAX("B",Y,0))
 . I Z="" S Z=$O(^ATXLAB("B",Y,0))
 . I Z S BKMVTAX(Y)=Z
 . Q
 Q
 ;
LABINIT ;EP;INITIALIZE ARRAY FOR TAXONOMY DISPLAY
 K ^TMP("BKMVVR",$J),BKMVJ
 S VALMCNT=0
 Q:'$G(BKMVTDA)
 ;S X="     "_$P(^ATXLAB(BKMVTDA,0),U)
 ;D Z(X)
 ;S X="     No. Lab                             Site/Specimen"
 ;D Z(X)
 ;S X="     --- ------------------------------  --------------"
 ;D Z(X)
 N A,B,X,Y,Z,BKMVX,BKMVY,BKMVLAB,BKMVB,BKMVK,BKMVSITE,TEXT
 S Z=3
 S (BKMVX,B,BKMVB)=0
 F  S BKMVX=$O(^ATXLAB(BKMVTDA,21,BKMVX)) Q:'BKMVX  D
 .S Y=$P($G(^ATXLAB(BKMVTDA,21,BKMVX,0)),U)
 .Q:'Y
 .;S Y=$P($G(^LAB(60,Y,0)),U)
 .S BKMVLAB=$$GET1^DIQ(60,Y,".01","E")
 .;S B=B+1
 .S BKMVB=BKMVB+1
 .S A="    "_B
 .S:$L(A)=5 A=" "_A
 .S A=A_"   "
 .S A=A_Y
 .S A=A_$E("                               ",1,32-$L(Y))
 .;D Z(A)
 .;S BKMVJ(BKMVTDA,B)=BKMVX
 .S BKMVJ(BKMVTDA,BKMVB)=BKMVX
 .;S (J,BKMVY)=0
 .S (BKMVK,BKMVY)=0
 .F  S BKMVY=$O(^ATXLAB(BKMVTDA,21,BKMVX,11,BKMVY)) Q:'BKMVY  D:$D(^ATXLAB(BKMVTDA,21,BKMVX,11,BKMVY,0))
 ..S A=$P(^ATXLAB(BKMVTDA,21,BKMVX,11,BKMVY,0),U)
 ..Q:'A
 ..;S J=J+1
 ..S BKMVK=BKMVK+1
 ..;S A=$P($G(^LAB(61,A,0)),U)
 ..S BKMVSITE=$$GET1^DIQ(61,A,".01","E")
 ..;I J=1 D
 ..;.S ^TMP("BKMVVR",$J,VALMCNT,0)=^TMP("BKMVVR",$J,VALMCNT,0)_A
 ..;I J>1 D
 ..;.S X="                                         "_A
 ..;.D Z(X)
 ..S VALMCNT=$G(VALMCNT)+1
 ..S TEXT=""
 ..S TEXT=$$SETFLD^VALM1($$PAD^BKMIXX4($S(BKMVK=1:BKMVB,1:""),"<"," ",4),TEXT,"Item")
 ..S TEXT=$$SETFLD^VALM1($S(BKMVK=1:BKMVLAB,1:""),TEXT,"Lab")
 ..S TEXT=$$SETFLD^VALM1(BKMVSITE,TEXT,"Site")
 ..D SET^VALM10(VALMCNT,TEXT)
 .; Contingency when Specimen is undefined
 .I BKMVK=0 D
 ..S VALMCNT=$G(VALMCNT)+1
 ..S TEXT=""
 ..S TEXT=$$SETFLD^VALM1($$PAD^BKMIXX4(BKMVB,"<"," ",4),TEXT,"Item")
 ..S TEXT=$$SETFLD^VALM1(BKMVLAB,TEXT,"Lab")
 ..S TEXT=$$SETFLD^VALM1("",TEXT,"Site")
 ..D SET^VALM10(VALMCNT,TEXT)
 ;I '$D(^TMP("BKMVVR",$J)) D
 ;.S ^TMP("BKMVVR",$J,1,0)="NO TAXONOMIES ON FILE FOR "_$G(BKMVX)
 ;.S Z=1
 ;S BKMVJ=B
 S BKMVJ=BKMVB
 ;S VALMCNT=Z
 Q
