BYIMIMM8 ;IHS/CIM/THL - IMMUNIZATION DATA EXCHANGE;
 ;;3.0;BYIM IMMUNIZATION DATA EXCHANGE;**1,2,3,4,5,6,7**;AUG 20, 2020;Build 747
 ;
HFSA(DEST,BYIMHDIR,BYIMHFNM) ;EP; - export batch
 ;V3.0 PATCH 5 - FID-85649 - DON'T SET EXPFAIL IF OUTBOUND PATH
 ;(BYIMHDIR) IS NULL
 I $G(BYIMHDIR)="" D  Q
 .D NOW^%DTC
 .S ^BYIMTMP("EXP FAIL",%,"NO DIR")=$G(DEST)_U_BYIMHDIR_U_BYIMHFNM_U_DUZ
 ;V3.0 PATCH 5 - FID-85649 END
 ;PATCH 3 CR-12419 CHANGE FILE CREATON TIMING AND GIS FILE CREATION
 I '$G(DEST) D  Q
 .D NOW^%DTC
 .S ^BYIMTMP("EXP FAIL",%,"NO DEST")=BYIMHDIR_U_BYIMHFNM_U_DUZ
 .S BYIMFAIL=$G(BYIMFAIL)+1
 I '$D(^BYIMTMP("SEND",DEST)) D  Q:'$D(^BYIMTMP("SEND",DEST))
 .H 2
 .Q:$D(^BYIMTMP("SEND",DEST))
 .D NOW^%DTC
 .S ^BYIMTMP("EXP FAIL",%,DEST,"NO MESSAGE")=BYIMHDIR_U_BYIMHFNM_U_DUZ
 .S BYIMFAIL=$G(BYIMFAIL)+1
 S BYIMDUZ=$$DUZ^BYIMIMM()
 ;CREATE TEMP ARRAY OF ^INTHU ENTRIES THAT ARE BEING EVALUATED
 ;PATCH 2 CR-12280 REMOVE EXTRANEOUS ENTRY FROM BATCH EXPORT QUEUE
 F X="DEST","ORIG","BYIMU" K ^BYIMTMP(X)
 N H,X,Y,Z,UIF,FAC
 S X=0
 F  S X=$O(^BYIMTMP("SEND",DEST,X)) Q:'X  S H=$G(^INTHU(X,3,1,0)) D:H]""
 .I H["QBP^" K ^BYIMTMP("SEND",DEST,X) Q
 .M ^BYIMTMP("ORIG",X)=^INTHU(X)
 .S ^BYIMTMP("DEST",BYIMDUZ,DEST,X)=""
 .S ^BYIMTMP("BYIMU",$J,X)=""
 ;V3.0 PATCH 6 - FID 83363 EXPORT FOR SELECTED STATES
 S FAC=0
 F  S FAC=$O(^BYIMPARA(BYIMDUZ,3,FAC)) Q:'FAC  D:BYIMEXST=""!(BYIMEXST[(","_FAC_","))
 .M ^BYIMTMP("DEST",FAC)=^BYIMTMP("DEST",BYIMDUZ)
 N BYIMH,BYIMU
 S ZSTAT=0
 F  S ZSTAT=$O(^BYIMTMP("DEST",ZSTAT)) Q:'ZSTAT  D:BYIMEXST=""!(BYIMEXST[(","_ZSTAT_","))
 .D HFSA1(DEST,ZSTAT,BYIMHFNM)
 ;V3.0 PATCH 6 - FID 83363 END
 K ^BYIMTMP("SEND",DEST)
 S X=""
 F  S X=$O(^BYIMU(X)) Q:'X  I $D(^BYIMTMP("BYIMU",$J,X)) K ^BYIMU(X)
 F X="DEST","ORIG","BYIMU" K ^BYIMTMP(X)
 K ^INLHDEST(+$$VDEST^BYIMIMM())
 K ^BYIMTMP($J,"NUM")
 ;PATCH 2 CR-12280 END
 Q
 ;=====
 ;
HFSA1(DEST,STATE,BYIMHFNM) ;PROCESS EACH MESSAGE
 N XX,X0,X1,X6,PATH,FE,PI,ESSN,BYIMU,BYIMRT,BYIMHIST,CTRL
 ;V3.0 PATCH 7 - FID-92804 STRIP NON-READABLE ASCII characters
 S CTRL=$$CTRL()
 S BYIMRT=$S($E(BYIMHFNM,1,4)="izrt":1,1:"")
 I BYIMRT,STATE'=BYIMDUZ,$G(^BYIMPARA(BYIMDUZ,3,STATE,0))["COVID" Q
 D ASSET^BYIMIMM7(STATE)
 ;PATCH 4 - FID-76102/CR-12017 Insure patient DFN renewed
 N BYIMU,DFN
 ;PATCH 4 - FID-76102/CR-12017 END
 S BYIMU=0
 F  S BYIMU=$O(^BYIMTMP("DEST",STATE,DEST,BYIMU)) Q:'BYIMU  D
 .K ^BYIMU(BYIMU)
 .M ^BYIMU(BYIMU)=^BYIMTMP("ORIG",BYIMU)
 .I $G(^BYIMU(BYIMU,3,1,0))["VXU^V04" D  Q:'DFN
 ..S DFN=""
 ..I BYIMRT S DFN=+$P(BYIMHFNM,"_",3)
 ..I 'BYIMRT S DFN=+$$DFN(BYIMU)
 ..I 'DFN D  Q
 ...K ^BYIMTMP("DEST",STATE,DEST,BYIMU)
 ...S ^BYIMTMP("NO DFN",STATE,DEST,BYIMU)=""
 ...K ^BYIMU(BYIMU)
 ..D COMPILE^BYIMSEG1(DFN,BYIMU,STATE)
 ..;CHECK IF EXPORT LIMITED TO SPECIFIC FACILITIES
 ..I $O(^BYIMPARA(BYIMDUZ,8,0))!$O(^BYIMPARA(BYIMDUZ,3,STATE,8,0)) D
 ...D FEXP(BYIMU,STATE)
 ...Q:'$D(^BYIMU(BYIMU))
 ...D FDFN(BYIMU,DFN,STATE)
 ;MAKE SURE EACH VXU MESSAGE HAS VALID RXA
 D RXA
 Q:'RXA
 D WRITE(STATE,DEST)
 Q
 ;=====
 ;
WRITE(STATE,DEST) ;EP;FINAL MESSAGE CONFIGURATION
 K STOP
 S STOP=0
 S (X1,X2)=""
 S BYIMUX=+$O(^BYIMTMP("DEST",STATE,DEST,0))
 S BYIMUY=+$O(^BYIMTMP("DEST",STATE,DEST,BYIMUX))
 S X1=$G(^BYIMU(BYIMUX,3,1,0))
 S X2=$G(^BYIMU(BYIMUY,3,1,0))
 ;PATCH 4 - FID-76218 CR-12291
 I STATE'=BYIMDUZ S FE=$P($G(^BYIMPARA(BYIMDUZ,3,+STATE,0)),U,8)
 ;PATCH 4 - FID-76218 CR-12291 END
 I X1["FHS|",X2["BTS|" S STOP=1
 Q:STOP
 K ^BYIMTMP($J,"NUM")
 D:BYIMRT
 .S BYIMDUZ=$$DUZ^BYIMIMM()
 .S SIEN=$S(BYIMDUZ=STATE:$P(^BYIMPARA(BYIMDUZ,0),U,14),1:$P($G(^BYIMPARA(BYIMDUZ,3,STATE,0)),U,14))
 .S ACT=$S($P(BYIMHFNM,"_",2)="vxu":"VXU",1:"QBP")
 .I BYIMHFNM["vxu",$G(DFN) S $P(BYIMHFNM,"_",3)=DFN
 .I BYIMHFNM["vxu"!(BYIMHFNM["qbp"),'$G(DFN) S DFN=$P(BYIMHFNM,"_",3)
 .S:$P(BYIMHFNM,"_",4)="xx" $P(BYIMHFNM,"_",4)=SIEN
 .S RTLDA=$$RTLOG^BYIMRT(BYIMHFNM,ACT,PATH,DFN,BYIMU,MID,1,SIEN)
 ;OPEN HOST FILE AND SEND BULLETIN IF HOST FILE DOESN'T OPEN
 S BYIMHFNM=$P(BYIMHFNM,".")_"."_$S($G(FE)]"":FE,1:"dat")
 S Y=$$OPEN^%ZISH(PATH,BYIMHFNM,"W")
 I Y D  Q
 .D EXPBULL^BYIMIMM4(BYIMHFNM,DEST,PATH)
 .D NOW^%DTC
 .S ^BYIMTMP("EXP FAIL",%,DEST,"NO OPEN")=PATH_U_BYIMHFNM_U_DUZ
 .S BYIMFAIL=$G(BYIMFAIL)+1
 S LPQUIT=""
 N BYIMU
 S BYIMU=0
 F  S BYIMU=$O(^BYIMTMP("DEST",STATE,DEST,BYIMU)) Q:'BYIMU!LPQUIT  D
 .;V3.0 PATCH 7 - FID-97512 MISSING OR OUT-OF ORDER SEGMENTS
 .I $G(^BYIMU(BYIMU,3,2,0))["NK1|" K ^BYIMU(BYIMU) Q
 .;V3.0 PATCH 7 - FID-97512 END
 .D LP(BYIMU,STATE,BYIMHFNM)
 .K ^BYIMU(BYIMU)
 .K ^BYIMTMP("DEST",STATE,DEST,BYIMU)
 K ^BYIMTMP($J,"NUM")
 D CLOSE^%ZISH()
 Q
 ;=====
 ;
LP(UIEN,AS,BYIMHFNM) ;EP - write each message to file
 K SEGM
 K ^BYIMTMP($J,"LP")
 N UDA,SEGX,SEGM,DFN,HRN,ASU,FAC,LP,LAST
 S UDA=0
 F  S UDA=$O(^BYIMU(UIEN,3,UDA)) Q:'UDA  S SEGX=$G(^(UDA,0)) D:SEGX]"" LP1
 Q:'$D(^BYIMTMP($J,"LP"))
 ;ONLY CHECK OBX SEGS WHEN VXU MESSAGE
 D OBX^BYIMIMM7(AS):$G(^BYIMTMP($J,"LP",1))["VXU^V04^"
 S LP=0
 F  S LP=$O(^BYIMTMP($J,"LP",LP)) Q:'LP  S SEGX=^(LP) D:SEGX]""
 .I SEGX["FHS|",$G(^BYIMTMP($J,"LP",3))["BTS|" S LP=999999 Q
 .S:SEGX["BTS|" $P(SEGX,"|",2)=$G(^BYIMTMP($J,"NUM"))
 .;V3.0 PATCH 7 - FID-92804 STRIP NON-READABLE ASCII characters
 .S SEGX=$TR(SEGX,CTRL)
 .;V3.0 PATCH 7 - FID-92804 END
 .U IO W SEGX,!
 .I SEGX["MSH|" S ^BYIMTMP($J,"NUM")=$G(^BYIMTMP($J,"NUM"))+1
 .S:"|FTS|RCP|"[$E(SEGX,1,4) LPQUIT=1
 I BYIMRT,$G(RTLDA) D RTCOPY(RTLDA)
 K ^BYIMTMP($J,"LP")
 Q
 ;=====
 ;
LP1 ;LP CON'T
 ;PATCH 4 - FID 83075
 ;
 ;CONCATENATE SEGMENTS STORED AT SEPARATE LINES IN INTHU
 I $E(SEGX,$L(SEGX)-2,$L(SEGX))="|CR",$E(SEGX,$L(SEGX))'="|" D
 .S SEGX=SEGX_"|"
 S:UDA=1 SEGM=SEGX
 I SEGX'["|CR|" D  Q:SEGX'["|CR|"
 .S UDA=UDA+1
 .S SEGX=SEGX_$G(^BYIMU(UIEN,3,UDA,0))
 .Q:SEGX["|CR|"
 .S UDA=UDA+1
 .S SEGX=SEGX_$G(^BYIMU(UIEN,3,UDA,0))
 I "|BTS|FTS|"'[$E(SEGX,1,4) D SET
 S:"|MSH|FHS|BTS|"[("|"_$E(SEGX,1,4)) SEGM=SEGX
 ;INCLUDE/EXCLUDE SSN
 I SEGM["VXU^"&(SEGX["PID|")!(SEGM["QBP^"&(SEGX["QPD|")) D  Q:'DFN
 .I $G(BYIMRT) S DFN=$P($G(BYIMHFNM),"_",3)
 .E  S DFN=$$DFN(UIEN)
 .Q:'DFN
 .;REMOVE SSN FROM PID-4 AND PID-19 IF NOT ALLOWED
 .;PATCH 1 INCLUDE SSN FOR COVID REPORTING
 .I $G(ESSN)=""!$G(ESSN),SEGX["SSA^SS"!($P(SEGX,"|",20)]"") D
 ..S SEGX=$$ESSN^BYIMIMM7(SEGX)
 .;REMOVE SSN AS MEDICARE IDENTIFIER IF NOT ALLOWED
 .I SEGX["IN1|",SEGX["MEDICARE"!(SEGX["MCR^MC")!(SEGX["MCD^MA") D
 ..S SEGX=$$MCR^BYIMIMM7(SEGX)
 .;PATCH 1 END
 I SEGX["PV1|",'$G(BYIMPV1) Q
 I SEGX["ORC|" S ORC=SEGX
 I SEGX["RXA|",SEGX'["decision",SEGX'["|998^No" D
 .S IEN=+$P(ORC,"|",3)
 .D:$G(CPT)]"" CPT^BYIMIMM7(CPT)
 .D:$P(SEGX,"|",22)="D" CPNA^BYIMIMM7
 .;PATCH 4 - FID-76877
 .;Add RXA-10.7 Field to HL7 Export
 .I SEGX["|00^NEW" S SEGX=$$DEGREE^BYIMIMM7(SEGX)
 .;PATCH 4 - FID-76877 END
 .I $G(IEN),$G(DFN),'$G(BYIMTEST) D
 .D LOG^BYIMIMM7(DFN,+IEN,AS)
 I SEGX["FHS|" S $P(SEGX,"|",9)=BYIMHFNM,$P(SEGX,"|",11)=$E($TR($H,","),1,7)
 I SEGX["BHS|" S $P(SEGX,"|",11)=$E($TR($H,","),1,7)
 I '$G(IN1),"|IN1|IN2|"[$E(SEGX,1,4) Q
 S:"|MSH|FHS|BHS|BTS|FTS|RCP|"'[$E(SEGX,1,4) SEGX=$TR(SEGX,"\<>")
 Q:$E(SEGX,1,4)'?2U1UN1"|"
 ;PATCH 4
 ;I "|BTS|FTS|"'[$E(SEGX,1,4) D SET
 I SEGX["MSH|" D
 .S MID=$P(SEGX,"|",10)
 .;PATCH 4 - FID 83075
 .;MSH-22 is value of PARAMETER MSH-22
 .;S SEGM=SEGX
 .;PATCH 4 - FID 83075 END
 I SEGX["OBX|1|CE|64994" S FS=$E($P(SEGX,"|",6),2,3)
 I SEGX["PID|"!(SEGX["QPD|") D
 .;V3.0 PATCH 6 - FID 96332 CHECK BIRTH ORDER CONTROL FOR MSH-25
 .S SEGX=$$PID25^BYIMIMM9(SEGX,AS)
 .;V3.0 PATCH 6 - FID 96332 END
 .S SEGX=$$PID^BYIMIMM7(SEGX,SEGM,+$G(DFN),AS)
 I $G(IEN),SEGX["RXA|",$P($P(SEGX,"|",12),U,4)]"" D
 .S SEGX=$$IISX^BYIMIMM7(SEGX)
 I 'LPQUIT S ^BYIMTMP($J,"LP",UDA)=$P(SEGX,"|CR|")
 S:"|FTS|RCP|"[$E(SEGX,1,4) LPQUIT=1
 Q
 ;=====
 ;
SET ;CUSTOMIZE SEGMENT
 D SET^BYIMIMM7
 Q
 ;=====
 ;
PI(DFN,STATE) ;EP;ELIMINATE MESSAGE IF PATIENT PRIVACY NOT ON FILE
 ;IF '0' RETURNED IF PRIVACY CRITERIA NOT MET
 ;IF '1' RETURNED IF PRIVACY CRITERIA MET
 N HRN,LOC,X,Y,Z,XX
 Q:'DFN!'STATE 0
 S Z=0
 S X=$P($G(^BIP(DFN,0)),U,24)
 S BYIMDUZ=$$DUZ^BYIMIMM()
 S:BYIMDUZ=STATE Y=$P($G(^BYIMPARA(BYIMDUZ,0)),U,10)
 S:BYIMDUZ'=STATE Y=$P($G(^BYIMPARA(BYIMDUZ,3,STATE,0)),U,10)
 ;Y WILL BE '0' IF STATE PRIVACY NOT ENFORCED
 I 'Y S Z=1
 ;Y WILL BE '1' IF STATE PRIVACY IS ENFORCED
 ;IF PRIVACY ENFORCED, X MUST BE '1' TO INDICATE PAT. PRIVACY ON FILE
 I Y,X S Z=1
 Q Z
 ;=====
 ;
DFN(UIF) ;FIND PATIENT DFN
 N X,Y,Z,LOC,HRN,DFN
 S DFN=""
 S X=$G(^BYIMU(UIF,3,2,0))
 I X'["PID|",X'["QPD|" S X=$G(^BYIMU(UIF,3,3,0))
 D:X["PID|"!(X["QPD|")
 .S LOC=$E($P($P(X,"|",4),U),1,6)
 .S HRN=+$E($P($P(X,"|",4),U),7,99)
 .I $L(LOC) D
 ..S LOC=$O(^AUTTLOC("C",LOC,0))
 ..Q:'LOC
 ..S X=0
 ..F  S X=$O(^AUPNPAT("D",HRN,X)) Q:'X!DFN  D
 ...I $D(^AUPNPAT("D",HRN,X,LOC)) S DFN=X
 D:'DFN
 .S X=0
 .F  S X=$O(^BYIMU(UIF,3,X)) Q:'X!DFN  I ^(X,0)["ORC|" S Y=^(0) D
 ..S Z=$G(^BYIMU(BYIMU,3,X+1,0))
 ..I Z'["RXA|" S Z=$G(^BYIMU(BYIMU,3,X+2,0))
 ..Q:Z'["RXA|"
 ..Q:Z["decision"!(Y["998^No")
 ..S IEN=+$$IIEN(Y)
 ..S Y=+$P($G(^AUPNVIMM(IEN,0)),U,2)
 ..S:$D(^DPT(Y,0)) DFN=Y
 Q DFN
 ;=====
 ;
FEXP(BYIMU,STATE) ;SCREEN EXPORT FOR SPECIFIC STATE FACILITIES
 ;
 ;When exporting for SPECIFIED FACILITY(IES), remove RXA segments
 ;for other facilities.
 ;
 ;Set XX array of specified facilities for additional export states
 ;
 N X,Y,Z,XX,YY
 D:BYIMDUZ=STATE
 .S X=0
 .F  S X=$O(^BYIMPARA(STATE,8,X)) Q:'X  S XX(X)=""
 D:BYIMDUZ'=STATE
 .S X=0
 .F  S X=$O(^BYIMPARA(BYIMDUZ,3,STATE,8,X)) Q:'X  S XX(X)=""
 Q:'$O(XX(0))
 ;
 ;Check RXA's for 'administered at' included as export facilities
 ;If not found in the XX array, remove the immunization
 ;
 S X=0
 F  S X=$O(^BYIMU(BYIMU,3,X)) Q:'X  S Y=$G(^(X,0)) D:Y["ORC|"
 .S SEG0=X
 .I Y'["|CR|" S X=X+1,Y=Y_$G(^BYIMU(BYIMU,3,X,0))
 .S Z=$G(^BYIMU(BYIMU,3,X+1,0))
 .Q:Z'["RXA|"
 .I Z["decision"!(Y["998^No") Q
 .S IEN=+$$IIEN(Y)
 .S V=+$P($G(^AUPNVIMM(IEN,0)),U,3)
 .S L=+$P($G(^AUPNVSIT(V,0)),U,6)
 .;PATCH 2 CR-12279 CORRECT EVALUATION OR RXA-11.4
 .I L,'$D(XX(L)) D DRXA^BYIMIMM7(BYIMU,SEG0)
 .;PATCH 2 CR-12279 END
 ;
 ;Check for remaining RXA segments. If there are still RXA's
 ;continue processing the message for export
 ;
 S (X,Y)=0
 F  S X=$O(^BYIMU(BYIMU,3,X)) Q:'X!Y  I ^(X,0)["RXA|" S Y=1
 Q:Y
 ;
 ;If no remaining RXA segments, remove the message completely
 ;
 K ^BYIMU(BYIMU),XX,YY
 Q
 ;=====
 ;
RXA ;EP;ENSURE ALL MESSAGES HAVE RXA SEGMENT
 D RXA^BYIMIMM7
 Q
 ;=====
 ;
FDFN(BYIMU,DFN,STATE) ;Screen export message by specified facility
 ;INCLUDE IMM'S FROM OTHER FACILITIES
 ;THAT HAVEN'T BEEN EXPORT BECAUSE OF FACILITY SPECIFIC EXPORT
 Q:'$G(BYIMU)!'$G(DFN)!'$G(STATE)
 N X,XX,FAC,IMM
 D:BYIMDUZ=STATE
 .S X=0
 .F  S X=$O(^BYIMPARA(BYIMDUZ,8,X)) Q:'X  S FAC(X)=""
 D:BYIMDUZ'=STATE
 .S X=0
 .F  S X=$O(^BYIMPARA(BYIMDUZ,3,STATE,8,X)) Q:'X  S FAC(X)=""
 Q:'$O(FAC(0))
 S X=0
 F  S X=$O(^BYIMU(BYIMU,3,X)) Q:'X  I ^(X,0)["ORC|" S Y=^(0) D
 .I Y'["|CR|" S X=X+1,Y=Y_$G(^BYIMU(BYIMU,3,X,0))
 .S Z=$G(^BYIMU(BYIMU,3,X+1,0))
 .Q:Z'["RXA|"
 .I Z["decision"!(Y["998^No") Q
 .S Z=+$$IIEN(Y)
 .S:Z IMM(Z)=""
 N INDA
 S INDA=9999999999
 F  S INDA=$O(^AUPNVIMM("AC",DFN,INDA),-1) Q:'INDA  D:'$D(IMM(INDA))
 .S V=$P($G(^AUPNVIMM(INDA,0)),U,3)
 .Q:'V
 .S X=+$P($G(^AUPNVSIT(V,0)),U,6)
 .Q:'X
 .Q:$D(FAC(X))
 .I '$D(^BYIMEXP("DD",INDA,STATE)),$G(^BYIMU(BYIMU,3,1,0))["MSH|" D FDFN1(INDA)
 Q
 ;=====
 ;
FDFN1(INDA) ;
 K INA
 S CS=U
 D ORC^BYIMSEGS
 S XX="ORC|"
 S X=""
 F  S X=$O(INA(X)) Q:X=""  D
 .S J=+$E(X,4,99)+1
 .S $P(XX,"|",J)=INA(X,INDA)
 S LINE=+$O(^BYIMU(BYIMU,3,9999999999),-1)+1
 S ^BYIMU(BYIMU,3,LINE,0)=XX_"|CR|"
 K INA
 D RXA^BYIMSEGS
 S XX="RXA|0|"
 S X=""
 F  S X=$O(INA(X)) Q:X=""  D
 .S J=+$E(X,4,99)+1
 .S $P(XX,"|",J)=INA(X,INDA)
 S LINE=LINE+1
 S ^BYIMU(BYIMU,3,LINE,0)=XX_"|CR|"
 Q:XX["|01^H"
 K INA
 D RXR^BYIMSEG1
 S XX="RXR|"
 S X=""
 F  S X=$O(INA(X)) Q:X=""  D
 .S J=+$E(X,4,99)+1
 .S $P(XX,"|",J)=INA(X,INDA)
 S LINE=LINE+1
 S ^BYIMU(BYIMU,3,LINE,0)=XX_"|CR|"
 K INA
 D OBXCE^BYIMSEG2
 S XX="OBX|"
 S X=""
 F  S X=$O(INA(X)) Q:X=""  D
 .S J=+$E(X,6,99)+1
 .S $P(XX,"|",J)=INA(X,INDA)
 S LINE=LINE+1
 S ^BYIMU(BYIMU,3,LINE,0)=XX_"|CR|"
 K INA
 D OBXFS^BYIMSEG1
 S XX="OBX|"
 S X=""
 F  S X=$O(INA(X)) Q:X=""  D
 .S J=+$E(X,6,99)+1
 .S $P(XX,"|",J)=INA(X,INDA)
 S LINE=LINE+1
 S ^BYIMU(BYIMU,3,LINE,0)=XX_"|CR|"
 K INA
 D OBXTY^BYIMSEG1
 S XX="OBX|"
 S X=""
 F  S X=$O(INA(X)) Q:X=""  D
 .S J=+$E(X,6,99)+1
 .S $P(XX,"|",J)=INA(X,INDA)
 S LINE=LINE+1
 S ^BYIMU(BYIMU,3,LINE,0)=XX_"|CR|"
 K INA
 D OBXPB^BYIMSEG1
 S XX="OBX|"
 S X=""
 F  S X=$O(INA(X)) Q:X=""  D
 .S J=+$E(X,6,99)+1
 .S $P(XX,"|",J)=INA(X,INDA)
 S $P(XX,"|",12)="F"
 S LINE=LINE+1
 S ^BYIMU(BYIMU,3,LINE,0)=XX_"|CR|"
 K INA
 D OBXPR^BYIMSEG1
 S XX="OBX|"
 S X=""
 F  S X=$O(INA(X)) Q:X=""  D
 .S J=+$E(X,6,99)+1
 .S $P(XX,"|",J)=INA(X,INDA)
 S $P(XX,"|",12)="F"
 S LINE=LINE+1
 S ^BYIMU(BYIMU,3,LINE,0)=XX_"|CR|"
 Q
 ;=====
 ;
FS ;DETERMINE FUNDING SOURCE
 S BYIMDUZ=$$DUZ^BYIMIMM()
 I BYIMDUZ=AS S REL=$P(^BYIMPARA(BYIMDUZ,0),U,11)
 I BYIMDUZ'=AS S REL=$P(^BYIMPARA(BYIMDUZ,3,AS,0),U,11)
 D:REL<4
 .S X=+$P($G(^AUPNVIMM(IEN,0)),U,5)
 .S X=$P($G(^AUTTIML(X,0)),U,13)
 .S Y=$S(X="v":"VXC1",X="o":"VXC2",X="i":"VXC3",1:"VXC1")
 .S Y=Y_U_$S(X="v":"Federal funds",X="o":"State funds",X="i":"Tribal funds",1:"Federal funds")
 .S $P(SEGX,"|",6)=Y_U_"CDCPHINVS"
 ;V3.0 PATCH 6 - CR-75238 FUNDING SOURCE
 ;D:REL>3
 ;.S X=$S("|02|03|04|05|"[("|"_FS_"|"):"VXC51",1:"PHC70")
 ;.S X=X_U_$S("|02|03|04|05|"[("|"_FS_"|"):"Federal funds",1:"Private Funds")
 ;.S $P(SEGX,"|",6)=X_U_"CDCPHINVS"
 ;V3.0 PATCH 6 - CR-75238 END
 Q
 ;=====
 ;
IIEN(ORC) ;EP;FIND IMMUNIZATION IEN FROM ORC SEGMENT
 ;  ORC = ORC SEGMENT FROM HL7 MESSAGE
 ;
 S (IEN,IEN3,IEN4)=0
 I $E($G(ORC),1,4)'="ORC|" S IEN=0,ORC=""
 S I3=$P(ORC,"|",3)
 S I4=$P(ORC,"|",4)
 I I3["^IHS",$P(I3,U)'["R" S IEN3=+$P(I3,U)
 I I4["^IHS" D
 .S IEN4=$P(I4,U)
 .S:IEN4?16N IEN4=+$O(^AUPNVIMM("ASTID",IEN4,0))
 I $D(^AUPNVIMM(IEN3,0)) S IEN=IEN3
 I 'IEN,IEN4,$D(^AUPNVIMM(IEN4,0)) S IEN=IEN4
 Q +IEN
 ;=====
 ;
RTCOPY(RTLDA) ;COPY RT FILE TO ^BYIMRT(
 S J=0
 S LP=0
 F  S LP=$O(^BYIMTMP($J,"LP",LP)) Q:'LP  S SEGX=^(LP) D:SEGX]""
 .S J=J+1
 .S ^BYIMRT(RTLDA,1,J,0)=$E(SEGX,1,250)
 .I $L(SEGX)>250 S J=J+1,^BYIMRT(RTLDA,1,J,0)=$E(SEGX,251,999)
 .I SEGX["MSH|",SEGX["QBP^" S ^BYIMTMP("MID",$J)=MID
 S ^BYIMRT(RTLDA,1,0)="^90480.21"_U_J_J
 Q:$P($G(^BYIMRT(RTLDA,0)),U,10)=$P(BYIMHFNM,"_",4)
 S DIE="^BYIMRT("
 S DR=".1////"_$P(BYIMHFNM,"_",4)
 D ^DIE
 Q
 ;=====
 ;
CTRL() ;ASCII CTRL CHARACTERS
 ;V3.0 PATCH 7 - FID-92804 STRIP NON-READABLE ASCII characters
 K CTRL
 S CTRL=""
 F J=1:1:31 S CTRL=CTRL_$C(J)
 Q CTRL
 ;=====
 ;
