BYIMIMM4 ;IHS/CIM/THL - IMMUNIZATION DATA EXCHANGE;
 ;;3.0;BYIM IMMUNIZATION DATA EXCHANGE;**2,4,6,7**;AUG 20, 2020;Build 747
 ;
 ;=====
MULT ;EP;PROCESS MULTIPLE INBOUND MESSAGES
 K BYIMQUIT
 N AUTOIMP,AUTOADD,DIR,FILE
 S AUTOIMP=1
 S AUTOADD=0
 D PATH^BYIMIMM6
 Q:IPATH=""
 S DIR=$$LIST^%ZISH(IPATH,"*",.DIR)
 S FILE=""
 S XX=0
 F  S XX=$O(DIR(XX)) Q:'XX  S:DIR(XX)]"" FILE(DIR(XX))=""
 S XX=""
 F  S XX=$O(FILE(XX)) Q:XX=""  D
 .S:XX["izdata"&(XX[".dat"!(XX[".hl7")) FILE=XX
 .Q:FILE=""
 .N DA
 .S DA=0
 .F  S DA=$O(^BYIMPARA("FILE",FILE,$$DUZ^BYIMIMM(),DA)) Q:'DA  I $P($G(^BYIMPARA($$DUZ^BYIMIMM(),2,+DA,0)),U,3)="I" S BYIMQUIT=""
 .I $D(BYIMQUIT) K BYIMQUIT Q
 .D I1^BYIMIMM1
 Q
 ;=====
ASITE(BYIMDUZ) ;EP;ADDITIONAL EXPORT STATES
 Q:'$G(BYIMDUZ)
 N ASNAM
 I $O(^BYIMPARA(BYIMDUZ,3,0)) D AS Q
 K DIR
 S DIR(0)="YO"
 S DIR("A")="Add export information for additional states"
 S DIR("B")="NO"
 W !!
 D ^DIR
 K DIR
 Q:'Y
AS N BYIMAS
 S BYIMQUIT=0
 F  D ASACT Q:BYIMQUIT
 Q
 ;=====
ASACT ;ADDITIONAL STATE ACTION
 I '$O(^BYIMPARA(BYIMDUZ,3,0)) D ASADD
 I '$O(^BYIMPARA(BYIMDUZ,3,0)) S BYIMQUIT=1 Q
 D ASD
 K DIR
 S DIR(0)="SO^1:Edit state;2:Add state;3:Delete state"
 W !
 D ^DIR
 K DIR
 I 'Y S BYIMQUIT=1 Q
 I Y=1 D ASEDIT Q
 I Y=2 D ASADD Q
 I Y=3 D ASDEL
 Q
 ;=====
ASSEL ;SELECT ADDITIONAL STATE
 K DA,DIR
 I J=1 S Y=1 D ASSEL1 Q
 K DIR
 S DIR(0)="NO^1:"_J
 S DIR("A")="Which state"
 W !!
 D ^DIR
 K DIR
ASSEL1 Q:'Y
 Q:'$G(BYIMAS(Y))
 S DA=+BYIMAS(Y)
 S ASNAM=$P(BYIMAS(Y),U,2)
 Q
 ;=====
ASD ;DISPLAY STATES
 W @IOF
 W !!?10,"Additional EXPORT State Directories"
 W !!?5,"NUM",?10,"STATE"
 W !?5,"---",?10,"--------------------------------------------------"
 N X0,X1
 S J=0
 S BYIMAS=0
 F  S BYIMAS=$O(^BYIMPARA(BYIMDUZ,3,BYIMAS)) Q:'BYIMAS  D
 .S X0=$G(^BYIMPARA(BYIMDUZ,3,BYIMAS,0))
 .S X1=$G(^BYIMPARA(BYIMDUZ,3,BYIMAS,1))
 .S J=J+1
 .S BYIMAS(J)=BYIMAS_U_$P(X0,U)
 .W !?5,J,?10,$P(X0,U)
 .W !?15,"OUTBOUND: ",$P(X0,U,2)
 .W !?15," INBOUND: ",$P(X0,U,3)
 .I '$O(^BYIMPARA(BYIMDUZ,3,BYIMAS,8,0)) W ! Q
 .W !?10,"Export to ",$P(X0,U)," Only immunizations given at:"
 .S X=0
 .F  S X=$O(^BYIMPARA(BYIMDUZ,3,BYIMAS,8,X)) Q:'X  D
 ..W !?15,"FACILITY:",?25,$P($G(^DIC(4,X,0)),U)," (",X,")"
 ..W:$P($G(^BYIMPARA(BYIMDUZ,3,BYIMAS,5,X,0)),U,2)]"" ?50,"IIS CODE: ",$P(^(0),U,2)
 Q
 ;=====
ASADD ;ADD STATES
 N BYIMQUIT
 S BYIMQUIT=0
 S J=0
 N BYIMAS
 S J=J+1
 K DIR
 S DIR(0)="FO^1:10"
 S DIR("A")="NEW interface state name"
 S DIR("?")="Enter a name to identify the additional interface state, 3-10 characters"
 W !!
 D ^DIR
 K DIR
 K DIE,DIC,DINUM,DR,DA,DD,DO,DIK,DLAYGO
 I X=""!(X[U) S BYIMQUIT=1 Q
 S (NSITE,BYIMAS(J))=X
 S DA(1)=BYIMDUZ
 S DIC="^BYIMPARA("_BYIMDUZ_",3,"
 S DIC(0)="L"
 S:'$D(^BYIMPARA(BYIMDUZ,3,0)) ^BYIMPARA(BYIMDUZ,3,0)="^90480.03"
 D FILE^DICN
 I Y<0 S BYIMQUIT=1 Q
 K DIE,DIC,DINUM,DR,DA,DD,DO,DIK,DLAYGO
 N NSDA
 S (NSDA,DA)=+Y
 N V,X,Y,Z
 S X=$P(^BYIMPARA(BYIMDUZ,0),U,2)
 S Y=$P(^BYIMPARA(BYIMDUZ,0),U,3)
 S V=$S(X["\":"\",1:"/")
 S Z=""
 S:X["SMM" Z="SMM"
 S:X["smm" Z="smm"
 S $P(^BYIMPARA(BYIMDUZ,3,NSDA,0),U,2)=X
 S $P(^BYIMPARA(BYIMDUZ,3,NSDA,0),U,3)=Y
 S $P(^BYIMPARA(BYIMDUZ,3,NSDA,0),U,4,6)=$P(^BYIMPARA(BYIMDUZ,0),U,4,6)
 S $P(^BYIMPARA(BYIMDUZ,3,NSDA,0),U,8,13)=$P(^BYIMPARA(BYIMDUZ,0),U,8,13)
 S ^BYIMPARA(BYIMDUZ,3,NSDA,9)="Z22^CDCPHINVS"
 S DA=NSDA
 D ASE1(NSDA)
 Q
 ;=====
ASEDIT ;EDIT
 N DA
 D ASSEL
 Q:'$G(DA)
 D ASE(DA)
 Q
 ;=====
ASE(DA) ;EP;FOR PRIMARY FACILITY EDIT
 N QUIT
 S QUIT=0
 F  D ASE2 Q:QUIT
 Q
 ;=====
ASE2 ;EDIT ADDITIONAL STATE
 D ASDISP(DA)
 S DIR(0)="SO^1:Edit parameters for "_ASNAM_";2:Add specific FACILITY(IES) for "_ASNAM_" export;3:Add "_ASNAM_" specific IIS code(s)"
 S DIR("A")="Which ADDITIONAL export function for "_ASNAM
 D ^DIR
 K DIR
 I 'X S QUIT=1 Q
 I X=1 D ASE1(DA) Q
 I X=2 S:DA'=BYIMDUZ BYIMAS=DA D FAC^BYIMIMM7
 I X=3 S:DA'=BYIMDUZ BYIMAS=DA D RXA^BYIMIMM5
 Q
 ;=====
ASE1(DA) ;EDIT ADDITIONAL STATE PARAMETERS
 ;PATCH 4 - FID-76204/CR-12244
 ;Remove Obsolete Parameters
 ;V3.0 PATCH 6 - FID-96332 CHECK BIRTH ORDER CONTROL FOR MSH-25
 ;V3.0 PATCH 7 - FID-107593 PARAMETER FOR RXA-5 SEPARATOR
 S DA(1)=BYIMDUZ
 S DR=".01T;.02T;.03T;.06T;1.03T;1.04T;1.05T;.07T;1.06T;1.07T;6.03T;6.04T;6.05T;1.08T;9.06T;9.07T;6.11T;.11T;9.01T;9.02T;6.12T;9.13T;9.09T;9.1T;9.11T"
 S DR=DR_";10.01T;10.02T;10.03T;10.04T;10.06T;6.01T;6.02T;6.09T;.17T;9.14T;6.1T;9.12T;.08T;.1T;6.06T;.16T;9.04T;9.05T;10.05T;.14T"
 S DR=DR_";11.01T;11.02T;11.03T;11.04T;11.05T"
 ;PATCH 4 - FID-76204/CR-12244 END
 ;V3.0 PATCH 6 - FID-96332 END
 ;V3.0 PATCH 7 - FID-107593 END
 I DA=BYIMDUZ S DIE="^BYIMPARA(",DR=$P(DR,";",2,99)
 E  S DIE="^BYIMPARA("_BYIMDUZ_",3,",DR=$P(DR,";6.06T")_$P(DR,";6.06T",2,99)
 W !!
 D ^DIE
 K DA,DR,DIE
 Q
 ;=====
ASDEL ;DELETE
 N DA
 D ASSEL
 Q:'$G(DA)
 S X=^BYIMPARA(BYIMDUZ,3,DA,0)
 W !?10,$P(X,U)
 K DIR
 S DIR(0)="YO"
 S DIR("A")="Delete export state: "_$P(X,U)
 S DIR("B")="NO"
 W !
 D ^DIR
 K DIR
 Q:Y'=1
 S DA(1)=BYIMDUZ
 S DIK="^BYIMPARA("_BYIMDUZ_",3,"
 D ^DIK
 K DA,DIK
 Q
 ;=====
CP(DFN) ;EP;DETERMINE VARICELLA EXPOSURE
 ;DFN = PATIENT DFN
 Q:'$D(^BIPC("B",+DFN))
 N BIX,VDAT
 S BIX=0
 F  S BIX=$O(^BIPC("B",DFN,BIX)) Q:'BIX  S:$P($G(^BIPC(BIX,0)),U,3)=12 VDAT=$P(^(0),U,4)
 Q:$L($G(VDAT))'=7
 S VDAT=VDAT+17000000
 S RXA="RXA|0|1|"_VDAT_"|"_VDAT_"|998^No vaccine administered^CVX|999"
 S OBX="OBX|1|CE|59784-9^Disease with presumed immunity ^LN|1|38907003^Varicella infection^SCT||||||F|CR|"
 N LINE
 S LINE=$O(^UTILITY("INH",$J,9999999999),-1)+1
 S X=U_"UTILITY(""INH"","_$J_","_LINE_")"
 S @X=RXA
 S X=U_"UTILITY(""INH"","_$J_","_(LINE+1)_")"
 S @X=OBX
 Q
 ;=====
IMMDUP ;EP;DEDUP IMMUNIZATIONS
 S DIK="^AUPNVIMM("
 S DFN=0
 F  S DFN=$O(^AUPNVIMM("AC",DFN)) Q:'DFN  D
 .K TMP
 .S IEN=0
 .F  S IEN=$O(^AUPNVIMM("AC",DFN,IEN)) Q:'IEN  D
 ..S X=$P($G(^AUPNVIMM(IEN,0)),U,1,3)
 ..S VIS=$P(X,U,3)
 ..Q:'$P(X,U,2)!'X!'VIS
 ..S DAT=$P($G(^AUPNVSIT(VIS,0)),".")
 ..Q:'DAT
 ..S X=$P(X,U,1,2)_U_DAT
 ..I +X=242 S $P(X,U)=148
 ..I +X=243 S $P(X,U)=148
 ..S TMP(X,IEN)=""
 .S X=""
 .F  S X=$O(TMP(X)) Q:X=""  D
 ..S J=0
 ..S IEN=0
 ..F  S IEN=$O(TMP(X,IEN)) Q:'IEN  D
 ...S J=J+1
 ...Q:J<2
 ...W:'$D(ZTQUEUED) !,DFN,?10,J,?15,IEN,?25,X,?45,$P(^AUTTIMM(+X,0),U,3)
 ...M ^BYIMTMP("BYIM IMM DUPS",DA)=^AUPNVIMM(DA)
 ...S DA=IEN
 ...;D ^DIK
 Q
 ;=====
DEXIT ;EP;CLEAN UP AFTER IZAD
 K ^BYIMTMP($J,"BYIM DISP")
 Q
 ;=====
ALOT(LDA,IVDA) ;EP;ACTIVATE LOT NUMBER
 Q:'LDA
 Q:'$D(^AUTTIML(LDA,0))
 S NEWLOT(LDA)=^AUTTIML(LDA,0)
 I '$P(NEWLOT(LDA),U,4) D
 .S $P(NEWLOT(LDA),U,4)=IVDA
 .S ^AUTTIML("C",IVDA,LDA)=""
 S $P(^AUTTIML(LDA,0),U,3)=0
 S $P(^AUTTIML(LDA,0),U,4)=IVDA
 Q
 ;=====
ILOT(LDA) ;EP;INACTIVATE LOT NUMBER
 Q:'LDA
 Q:'$D(^AUTTIML(LDA,0))
 S:$G(NEWLOT(LDA))]"" ^AUTTIML(LDA,0)=$G(NEWLOT(LDA))
 K NEWLOT
 Q
 ;=====
LV(DFN,IVDA,LOTDA) ;EP;CALCULATE LAST V IMM FOR PAT
 Q:'$G(DFN)!'$G(IVDA)!'$G(LOTDA)
 N XX,YY,ZZ
 S XX=$O(^AUPNVIMM("AC",DFN,9999999999),-1)
 Q:'XX
 S XX0=$G(^AUPNVIMM(XX,0))
 Q:+XX0'=IVDA
 Q:$P(XX0,U,5)
 S $P(^AUPNVIMM(XX,0),U,5)=LOTDA
 Q
 ;=====
MAN(MAN) ;EP;CHECK IMMUNIZATION MAN.
 Q:MAN=""
 S:MAN["\T\" MAN=$P(MAN,"\T\")_"&"_$P(MAN,"\T\",2)
 N X,Y,Z
 S X=MAN
 X ^%ZOSF("UPPERCASE")
 S MAN=Y
 S MANA=$P(MAN,U)
 S MANN=$P(MAN,U,2)
 S MANDA=$O(^AUTTIMAN("B",MANN,0))
 Q:MANDA
 S X=MANN
 S DIC="^AUTTIMAN("
 S DIC(0)="L"
 S DIC("DR")=".02////"_MANA
 D FILE^DICN
 I Y>0 S MANDA=+Y
 Q
 ;=====
LOT(LOT,MAN,IVDA) ;EP;EVALUATE LOT AND MANUFACTURER DATA
 S LOTDA=""
 S MANDA=""
 Q:$G(LOT)=""
 D:MAN]"" MAN^BYIMIMM4(MAN)
 S X=LOT
 X ^%ZOSF("UPPERCASE")
 S LOT=Y
 S LOTDA=$O(^AUTTIML("B",LOT,0))
 I LOTDA D ALOT(LOTDA,IVDA) Q
 S X=LOT
 S DIC="^AUTTIML("
 S DIC(0)="L"
 S DIC("DR")=".02////"_$G(MANDA)_";.03////1;.04////"_IVDA
 D FILE^DICN
 Q:Y<0
 S LOTDA=+Y
 D ALOT(LOTDA,IVDA)
 Q
 ;=====
LOG(FILE,ACT,DFNCNT,IMMCNT,NODFNCNT,NEWIMCNT,ADDIMCNT,PATH,DFN) ;EP;LOG AUTO IMPORT FILES THAT HAVE BEEN PROCESSED
 ;FILE     = NAME OF FILE IMPORTED OR EXPORTED
 ;ACT      = ACTION - 'I'MPORT OR 'E'XPORT
 ;DFNCNT   = NUMBER OF PATIENTS
 ;IMMCNT   = NUMBER OF IMMUNIZATIONS
 ;NODFNCNT = NUMBER OF PATIENTS FOR WHOM THERE IS NO PATIENT MATCH
 ;NEWIMCNT = NUMBER OF NEW IMMUNIZATIONS
 ;ADDIMCNT = NUMBER OF NEW IMMUNIZATIONS ADDED TO V IMMUNIZATIONS
 ;PATH     = DRIVE/DIRECTORY FILE SENT TO
 Q:$G(FILE)=""!($G(ACT)="")
 S X=FILE
 K DIE,DIC,DINUM,DR,DA,DD,DO,DIK,DLAYGO
 S DA(1)=$$DUZ^BYIMIMM()
 S DIC="^BYIMPARA("_DA(1)_",2,"
 S DIC(0)="L"
 S DIC("DR")=".02////"_DT_";.03////"_ACT_";.04////"_$G(DFNCNT)_";.05////"_$G(IMMCNT)
 S:$G(NODFNCNT) DIC("DR")=DIC("DR")_";.06////"_NODFNCNT
 S:$G(NEWIMCNT) DIC("DR")=DIC("DR")_";.07////"_NEWIMCNT
 S:$G(ADDIMCNT) DIC("DR")=DIC("DR")_";.08////"_ADDIMCNT
 S:$G(PATH)]"" DIC("DR")=DIC("DR")_";.09////"_PATH
 D FILE^DICN
 K DIE,DIC,DINUM,DR,DA,DD,DO,DIK,DLAYGO
 N BYIMACT
 S BYIMACT=$S(ACT="I":"imported from",1:"exported to")
 ;=====
BULLETIN ;EP;CREATE EXPORT/IMPORT BULLETIN
 N %X,%Y,X,XMB,XMDT,XMDUZ,Y1
 S XMB="BYIM EXPORT/IMPORT MESSAGE"
 S XMB(1)="The file '"_FILE_"' was "_BYIMACT_" the State Immunization Registry on "_$$HTE^XLFDT($H)
 S XMDUZ=.5
 D ^XMB
 Q
 ;=====
EXPBULL(BYIMHFNM,DEST,BYIMHDIR) ;EP;EXPORT FILE CREATION FAILED
 N %X,%Y,X,XMB,XMDT,XMDUZ,Y1
 S XMB="BYIM EXPORT FILE FAILED"
 S XMB(1)=BYIMHFNM
 S XMB(2)=$P($G(^INRHD(+DEST,0)),U)
 S XMB(3)=BYIMHDIR
 S XMDUZ=.5
 D ^XMB
 Q
 ;=====
LC(X) ;LOWERCASE
 S X=$TR(X,"ABCDEFGHIJKLMNOPQRSTUVWXYZ ","abcdefghijklmnopqrstuvwxyz_")
 Q X
 ;=====
QPATH(BYIMDUZ) ;EP;QUERY DIRECTORIES
 Q
 Q:'$G(BYIMDUZ)
 N V,X,Y,Z
 S X=$P($G(^BYIMPARA(BYIMDUZ,0)),U,2)
 S X=$$LC(X)
 S V=$S(X["\":"\",1:"/")
 I X["hl7bridge" D  I 1
 .S X=$P(X,"hl7bridge")
 .S:$E(X,$L(X))'=V X=X_V
 .S Y=X_"hl7bridge"_V_"queries"
 .S Z=X_"hl7bridge"_V_"qresponses"
 E  D
 .S X=$P(X,"requests")
 .S:$E(X,$L(X))'=V X=X_V
 .S Y=X_"queries"
 .S Z=X_"qresponses"
 S $P(^BYIMPARA(BYIMDUZ,1),U)=Y
 S $P(^BYIMPARA(BYIMDUZ,1),U,2)=Z
 Q
 ;=====
LOGDFN ;EP;LOG PATIENTS INCLUDED IN EXPORT
 N DFN,TYPE
 S TYPE="E"
 S DFN=0
 F  S DFN=$O(^BYIMTMP("LOG",DFN)) Q:'DFN  D
 .D LOGD(DFN,TYPE)
 .K ^BYIMTMP("LOG",DFN)
 Q
 ;=====
LOGD(DFN,TYPE) ;EP;LOG EACH EXPORTED OR IMPORTED IMM
 N IMM,X,Y,Z
 S:$G(TYPE)="" TYPE="E"
 S IMM=0
 F  S IMM=$O(^BYIMTMP("LOG",DFN,IMM)) Q:'IMM  D
 .I $G(BYIMALL)'=2,$D(^BYIMEXP("D",IMM)) Q
 .Q:$G(BYIMMU2)
 .K DIE,DIC,DINUM,DR,DA,DD,DO,DIK,DLAYGO
 .S DIC="^BYIMEXP("
 .S DIC(0)="L"
 .S DIC("DR")=".02////"_DT_";.03////"_IMM_";.04////"_TYPE_";.05////"_$G(XQY)_";.06////"_$G(BYIMALL)
 .S X=DFN
 .D FILE^DICN
 .K DIE,DIC,DINUM,DR,DA,DD,DO,DIK,DLAYGO
 Q
 ;=====
ASDISP(AS) ;EP;DISPLAY ADDITIONAL STATE SETUP PARAMETERS
 D ASVARS
 W @IOF
 W !?3,"Site: ",$P(X0,U)
 ;W !,"Path...: ",$E($P(X0,U,2),1,24),"  ",$E($P(X0,U,3),1,24)
 W !,"PathOUT: ",$P(X0,U,2)
 W ?55,"Ages...: " S:'$P(X0,U,6) $P(X0,U,6)=0 W $E($P($P($P(^DD(90480,.06,0),U,3),$P(X0,U,6)_":",2),";"),1,16)
 W !,"Path IN: ",$P(X0,U,3)
 W !,"MSH-3.1: ",$P(X1,U,3)
 W ?21,"MSH-3.2: ",$P(X1,U,4)
 W ?55,"MSH-3.3: ",$P(X1,U,5)
 W !,"MSH-4.1: ",$E($P(X0,U,7),1,16)
 W ?21,"MSH-4.2: ",$P(X1,U,6)
 W ?55,"MSH-4.3: ",$P(X1,U,7)
 W !,"MSH-5.1: ",$P(X6,U,3)
 W ?21,"MSH-5.2: ",$P(X6,U,4)
 W ?55,"MSH-5.3: ",$P(X6,U,5)
 W !,"MSH-6.1: ",$P(X1,U,8)
 W ?21,"MSH-6.2: ",$P(X9,U,6)
 W ?40,"MSH-6.3: ",$P(X9,U,7)
 W ?55,"Version: " S:'$P(X0,U,11) $P(X0,U,11)=3 W $E($P($P($P(^DD(90480,.11,0),U,3),+$P(X0,U,11)_":",2),";"),1,16)
 W !,"MSH21.1: ",$P(X9,U)
 W ?21,"MSH21.2: ",$P(X9,U,2)
 W !,"MSH22.1: ",$P(X6,U,12)
 W ?21,"MSH22.6: ",$P(X9,U,9)
 W ?40,"MSH22.7: ",$P(X9,U,10)
 W ?55,"MSH22.10: ",$E($P(X9,U,11),1,23)
 W !,"MSH23.1: ",$P(X10,U,1)
 W ?21,"MSH23.6: ",$P(X10,U,2)
 W ?40,"MSH23.7: ",$E($P(X10,U,3),1,18)
 W ?55,"MSH23.10: ",$E($P(X10,U,4),1,23)
 W !,"PID11.7: " I $P(X6,U,8)]"" W $P($P($P(^DD(90480,6.08,0),U,3),$P(X6,U,8)_":",2),";")
 ;PATCH 2 CR-12326 COVID FUNDING SOURCE
 W ?21,"RXA-5.1: " W:$P(X0,U,17)]"" $P($P($P(^DD(90480,.17,0),U,3),+$P(X0,U,17)_":",2),";")
 W ?55,"RXA-6.1 : ",$P(X6,U,10)
 W !,"File Extension...........: ",$P(X0,U,8)
 W ?40,"Protection Indicator: " W:$P(X0,U,10)]"" $P($P($P(^DD(90480,.1,0),U,3),+$P(X0,U,10)_":",2),";")
 ;W !,"Include/Exclude SSN.: " W:$P(X6,U,7)]"" $P($P($P(^DD(90480,6.07,0),U,3),$P(X6,U,7)_":",2),";")
 W !,"Purge Messages after.....: ",$S($P(X9,U,5):$P(X9,U,5),1:90)," days"
 W ?40,"Include Insurance...: " W:$P(X0,U,16)]"" $P($P($P(^DD(90480,.16,0),U,3),+$P(X0,U,16)_":",2),";")
 ;W !,"Include/Exclude PV1.: " W:$P(X9,U,3)]"" $P($P($P(^DD(90480,9.03,0),U,3),+$P(X9,U,3)_":",2),";")
 W !,"Barcode/Vac type Seg.....: " W:$P(X10,U,5)]"" $P($P($P(^DD(90480,10.05,0),U,3),+$P(X10,U,5)_":",2),";")
 W ?40,"Auto Query Mode.....: " W:$P(X9,U,4)]"" $P($P($P(^DD(90480,9.04,0),U,3),+$P(X9,U,4)_":",2),";")
 ;W !,"Purge Messages after: ",$S($P(X9,U,5):$P(X9,U,5),1:90)," days"
 W !,"Use Loc of Enc for MSH-22: " W:$P(X9,U,13)]"" $P($P($P(^DD(90480,9.13,0),U,3),+$P(X9,U,13)_":",2),";")
 W ?40,"Exchange State......: ",$P($G(^DIC(5,+$P(X0,U,14),0)),U)
 ;PATCH 2 END CR-12326
 Q
 ;=====
ASVARS ;SET AS VARS
 I AS=BYIMDUZ D
 .F J=0,1,6,9,10 S X="X"_J,@X=$G(^BYIMPARA(BYIMDUZ,J))
 .S $P(X0,U)=$P(^DIC(4,AS,0),U)
 .I $P(X0,U,14) S ASNAM=$P(^DIC(5,$P(X0,U,14),0),U)
 .E  S ASNAM=$P(^DIC(4,AS,0),U)
 I AS'=BYIMDUZ D
 .F J=0,1,6,9,10 S X="X"_J,@X=$G(^BYIMPARA(BYIMDUZ,3,AS,J))
 S $P(X6,U,6)=$P($G(^BYIMPARA(BYIMDUZ,6)),U,6)
 Q
 ;=====
