BYIMRT1 ;IHS/CIM/THL - IMMUNIZATION DATA EXCHANGE;
 ;;3.0;BYIM IMMUNIZATION DATA EXCHANGE;**3,4,5,6,7**;AUG 20, 2020;Build 747
 ;
 ;REAL-TIME HL7 MESSAGE PROCESSING - CONTINUED
 ;
 ;=====
 ;
DISP(RSPDA,DTYP,QRYDA,IND) ;EP;DISPLAY RESPONSE FILE
 ;V3.0 PATCH 7 - FID-106212 SELECT DISPLAY OF COMBO OR INDIVIDUAL VAX
 ;RSPDA     = RESPONSE DA
 ;QRYDA     = QUERY DA
 ;DTYP      = DISPLAY TYPE
 ;        1 = IMMUNIZATIONS
 ;        2 = HL7 MESSAGE
 ;        3 = ACK MESSAGE
 ;IND       = Compound Vaccine Display
 ;        1 = Display only the Compound Vaccine
 ;        2 = Display each component of Compound Vaccines
 ;
 Q:'$G(RSPDA)!'$G(QRYDA)
 K ^BYIMTMP("ARR",$J)
 N X,Y,Z,XX,ERR,DISP,DISF,DISE,HDR,HDE
 S:'$G(DTYP) DTYP=1
 D HDR^BYIMRT3(RSPDA,QRYDA)
 I DTYP=2 D  Q
 .I $G(ACK0)["izrt_vxu" D
 ..N AS
 ..S AS=+$P(ACK0,U,10)
 ..S QRYDA=$O(^BYIMRT("ACT",$P($P(ACK0,U),"."),"VXU",AS,0))
 .D DHL7^BYIMRT3(RSPDA,QRYDA)
 N ERR,ERR1
 S (ERR,ERR1)=""
 F J=4,5 S ERR=$G(^BYIMRT(RSPDA,1,J,0)) D:ERR]""
 .I ERR["ERR|" S ERR1=ERR
 .I ERR["QAK","NFTM"[$P(ERR,"|",3) S ERR1=ERR
 I ERR1]""!(DTYP=3) D ERR(RSPDA,DTYP,ERR1,QRYDA) Q:DTYP=3
 S X0=$G(^BYIMRT(RSPDA,1,1,0))
 S X2=$G(^BYIMRT(RSPDA,1,2,0))
 I X2["MSA|AA|",'$D(^BYIMRT(RSPDA,1,3,0)) D MSA Q
 I X0["MSH|",X0["|RSP^K11"!(X0["|VXU^V04") D DVXU(X0)
 I X0["MSH|",X0["QBP^Q11" D DQPD(RSPDA)
 K ^BYIMTMP("ARR",$J)
 Q
 ;=====
 ;
DVXU(X0) ;DISPLAY RESPONSE MESSAGE
 I '$D(^BYIMRT(RSPDA,2)),'$D(^BYIMRT(RSPDA,3)),'$D(^BYIMRT(RSPDA,4)),'$D(^BYIMRT(RSPDA,5)) D DHL7^BYIMRT3(RSPDA) Q
 N X,Y,Z,X2,XR,XF,XX,YY,DISP,HDR,JJ,RXA,DISF,DISE,DISW,BYIMQUIT,BYIMPAUS
 S JJ=0
 S XX=0
 F  S XX=$O(^BYIMRT(RSPDA,1,XX)) Q:'XX!$G(BYIMQUIT)  S X=^(XX,0) D
 .S X2=$G(^BYIMRT(RSPDA,1,XX+1,0))
 .I "|MSH|MSA|PID|NK1|IN1|IN2|ORC|RXA|RXR|OBX|QAK|QPD|"[$E(X,1,4),"|MSH|MSA|PID|NK1|IN1|IN2|ORC|RXA|RXR|OBX|QAK|QPD|"'[$E(X2,1,4) S X=X_X2,XX=XX+1
 .I X'["|30956-7","|QPD|PID|RXA|QAK|OBX|"'[$E(X,1,4) Q
 .I X["QPD|" S DOB=$E($P(X,"|",7),1,8)
 .I X["PID|" S DOB=$E($P(X,"|",8),1,8)
 .I "|QPD|PID|"[$E(X,1,4) S:X["QPD|" X="|"_X D PID^BYIMRT4(X)
 .;I X["RXA|",X'["|998" D RXA^BYIMRT2(X,XX)
 .I X["|30956-7" D
 ..S Y=$P($P($G(^BYIMRT(RSPDA,1,XX+1,0)),"|",4),U)
 ..S:Y="" Y="NONE"
 ..S Z=$P($P($G(^BYIMRT(RSPDA,1,XX+2,0)),"|",4),U)
 ..S:Z="" Z="NONE"
 ..S ZZ=$P($P($G(^BYIMRT(RSPDA,1,XX+3,0)),"|",4),U)
 ..S:ZZ="" ZZ="NONE"
 ..S CHK="|30973-2|30980-7|30981-5|"
 ..I Y'="29768-9",CHK[Y!(CHK[Z)!(CHK[ZZ) D FORE(X,XX)
 S JJ=0
 S XR=0
 F  S XR=$O(^BYIMRT(RSPDA,2,XR)) Q:'XR  S X0=^(XR,0) D
 .I IND,XR["." Q
 .I 'IND,XR'["." Q:$G(^BYIMRT(RSPDA,2,XR+.1,0))]""
 .D RXA1^BYIMRT2(X0)
 S J=0
 S XF=0
 F  S XF=$O(^BYIMRT(RSPDA,3,XF)) Q:'XF  S X0=^(XF,0) D FOR1^BYIMRT3(X0)
 S J=0
 S X=0
 F  S X=$O(^BYIMRT(RSPDA,4,X)) Q:'X  S J=J+1,DISE(J)=^(X,0)
 S J=0
 S X=0
 F  S X=$O(^BYIMRT(RSPDA,5,X)) Q:'X  S J=J+1,DISW(J)=^(X,0)
 D DISP^BYIMRT4
 I $G(BYIMPAUS) K BYIMPAUS Q
 Q
 ;=====
 ;
MSH ;DISPLAY RT MSH SEGMENT
 D MSH^BYIMRT4
 Q
 ;=====
 ;
ERR(RSPDA,DTYP,ERR,QRYDA) ;EP;DISPLAY ERROR AND WARNINGS
 D ERR^BYIMRT4(RSPDA,DTYP,ERR1,QRYDA)
 Q
 ;=====
 ;
ERR11 ;ERROR DISPLAY
 D ERR11^BYIMRT4
 Q
 ;=====
 ;
NFTM ;DISPLAY NOT FOUND/TOO MANY
 Q:DTYP'=1
 S X0=$G(^BYIMRT(RSPDA,0))
 W !,$P($G(^DIC(5,+$P(X0,U,10),0)),U)," reports "
 S X=+$O(^BYIMRT(RSPDA,4,0))
 W $P($G(^BYIMRT(RSPDA,4,X,0)),U,2)
 D PAUSE
 Q
 ;=====
 ;
MSA ;ACCEPT ACKNOWLEDGEMENT
 Q:DTYP'=1
 S X0=$G(^BYIMRT(RSPDA,0))
 W !,$P($G(^DIC(5,+$P(X0,U,10),0)),U)," reports that "
 W $G(^BYIMRT(RSPDA,4,2,0))
 D PAUSE
 Q
 ;=====
 ;
AGE(X1,X2) ;EP;PATIENT AGE IN YEARS, MONTHS OR DAYS
 ;V3.0 PATCH 5 - FID-83076 AGE VALUE FIX
 ;X1 = VISIT DATE YYYYMMDD FORMAT
 ;X2 = DOB YYYYMMDD FORMAT
 N X,Y,Z,Y1,M1,D1,Y2,M2,D2,YR
 S:$L(X1)=7 X1=X1+17000000
 S:$L(X2)=7 X2=X2+17000000
 Q:$L(X1)'=8!($L(X2)'=8) ""
 S Y1=$E(X1,1,4)
 S M1=$E(X1,5,6)
 S D1=$E(X1,7,8)
 S Y2=$E(X2,1,4)
 S M2=$E(X2,5,6)
 S D2=$E(X2,7,8)
 S X=$S(M2>M1:1,1:0)
 S YR=Y1-Y2-X
 S X=$S(M2>M1:12,1:0)
 S MN=M1+X-M2
 S X=$S(D2>D1:$S(M2="02":28,"09040611"[M2:30,1:31),1:0)
 S DY=D1+X-D2
 ;PATCH 4 - FID-76113 insure message display is complete, not truncated
 S X=$S(YR>4:YR_" yrs",MN>-1:(YR*12)+(MN+$S(DY>25:1,1:0))_" mts",1:DY_" dys")
 ;PATCH 4 - FID-76113 END
 ;V3.0 PATCH 5 - FID-83076  END
 Q X
 ;=====
 ;
PAUSE D PAUSE^BYIMIMM6
 Q
 ;=====
 ;
X2(RSPDA) ;EP;CREATE ^BYIMRT NODES
 ;
 ;NODE 1 = COPY OF HL7 MESSAGE
 ;NODE 2 = IMMUNIZATION INFO FOR DISPLAY
 ;NODE 3 = FORECAST INFO FOR DISPLAY
 ;NODE 4 = ERROR INFO FOR DISPLAY
 ;NODE 5 = WARNING INFO FOR DISPLAY
 ;
 ;RSPDA =  IEN OF QUERY RESPONSE
 ;
 N XX,JJ,X,Y,Z,DOB,BYIMUIF,X0
 S X0=$G(^BYIMRT(RSPDA,0))
 S X1=$G(^BYIMRT(RSPDA,1,1,0))
 S X9=$P($P(X1,"|",9),U)
 Q:"RSPACKVXU"'[X9
 I X0["izdata",X0["ACK" D ACK(RSPDA) Q
 S MID=""
 S JJ=0
 S KK=0
 S XX=0
 F  S XX=$O(^BYIMRT(RSPDA,1,XX)) Q:'XX  S X=^(XX,0) D
 .I X["QPD|" S DOB=$E($P(X,"|",7),1,8) Q
 .I X["PID|" S DOB=$E($P(X,"|",8),1,8) Q
 .I X["MSA|" D
 ..S MID=$P(X,"|",3)
 ..S:MID["IHS-" BYIMUIF=$O(^INTHU("C",MID,0))
 ..I $P(X,"|",2)="AA",'$O(^BYIMRT(RSPDA,1,XX)) D
 ...S ^BYIMRT(RSPDA,4,0)="^90480.24^1^1"
 ...S ^BYIMRT(RSPDA,4,2,0)="Message "_MID_" was accepted and processed."
 .I $G(DOB),'$D(^BYIMRT(RSPDA,2,XX,0)),X["RXA|",X'["|998" D RXA^BYIMRT2(X,XX)
 .I X["|30956-7",'$D(^BYIMRT(RSPDA,3,XX,0)) D
 .I X["|30956-7"!(X["30979-9"),'$D(^BYIMRT(RSPDA,3,XX,0)) D
 ..S Y=$P($P($G(^BYIMRT(RSPDA,1,XX+1,0)),"|",4),U)
 ..S Z=$P($P($G(^BYIMRT(RSPDA,1,XX+2,0)),"|",4),U)
 ..S ZZ=$P($P($G(^BYIMRT(RSPDA,1,XX+3,0)),"|",4),U)
 ..S CHK="|30973-2|30980-7|30981-5|"
 ..I Y'="29768-9",CHK[Y!(CHK[Z)!(CHK[ZZ) D FORE(X,XX)
 .I X["QAK|","NFTM"[$P(X,"|",3),'$D(^BYIMRT(RSPDA,4,XX,0)) D NF(X) Q
 .I X["ERR|" D ERROR(X,XX,MID,KK)
 D DUP
 Q
 ;=====
 ;
LOC(IEN,LNAM) ;EP;DETERMINE LOC OF ENCOUNTER NAME
 ;   IEN = IEN ENTRY IN V IMM
 ;   LNAM = RXA-11.4 ADMINISTERED AT
 ;
 N X,Y,Z
 S X=""
 I LNAM="" S LNAM="OTHER"
 I IEN S X=$P($G(^DIC(4,+$P($G(^AUPNVSIT(+$P($G(^AUPNVIMM(IEN,0)),U,3),0)),U,6),0)),U)
 I X="",'$D(^BYIMPARA("RXA",LNAM)) D
 .S X=+$O(^DIC(4,"B",LNAM,0))
 .S X=$S(X:$P($G(^DIC(4,X,0)),U),1:"OTHER")
 I X="",$D(^BYIMPARA("RXA",LNAM)) D
 .S X=+$O(^BYIMPARA("RXA",LNAM,0))
 .S Y=+$O(^BYIMPARA("RXA",LNAM,X,0))
 .S Z=+$O(^BYIMPARA("RXA",LNAM,X,Y,0))
 .I Z S X=$P($G(^DIC(4,Z,0)),U) S:X="" X="OTHER"
 .I Y,'Z S X=$P($G(^DIC(4,Y,0)),U) S:X="" X="OTHER"
 Q X
 ;=====
 ;
FORE(X1,XX) ;EVALUATE FORECAST RESPONSE SEGMENT AND SET ^BYIMRT(RSPDA,3 NODE
 ;X1 =    original HL7 message line
 ;XX =    IEN of the original message line
 I XX,$G(^BYIMRT(RSPDA,3,XX,0))]"" S X0=^(0) D FOR1^BYIMRT3(X0) Q
 F J=3:1:14 D
 .S Y="X"_J
 .S:J>2 @Y=""
 S QUIT=""
 F J=1:1:7 D:'QUIT
 .S X=$G(^BYIMRT(RSPDA,1,XX+J,0))
 .I X=""!(X["30956-7") S QUIT=1 Q
 .I X["59783-1" S X3=$P($P(X,"|",6),U)
 .I X["30981-5" S X4=$P(X,"|",6)
 .I X["30980-7" S X5=$P(X,"|",6)
 .I X["59777-3" S X6=$P(X,"|",6)
 .I X["59779-9" S X7=$P($P(X,"|",6),U),X8=$P($P(X,"|",6),U,2)
 .I X["59780-7" S X9=$P(X,"|",6)
 .I X["30973-2" S X10=$P(X,"|",6)
 .I X["59781-5" S X11=$P($P(X,"|",6),U)
 .I X["59782-3" S X12=$P($P(X,"|",6),U)
 .I X["59778-1" S X13=$P($P(X,"|",6),U)
 .I X["30982-3" S X14=$P($P(X,"|",6),U)
 S CVX=+$P($P(X1,"|",6),U)
 S CVXDA=+$S(CVX]"":$O(^AUTTIMM("C",+CVX,0)),1:"")
 S NAM=$P($G(^AUTTIMM(CVXDA,0)),U,2)
 S:NAM="" NAM=$P($P(X1,"|",6),U,2)
 S X1=CVX
 S X2=NAM
 D FOR2^BYIMRT3
 S ^BYIMRT(RSPDA,3,XX,0)=CVX_U_NAM_U_X3_U_X4_U_X5_U_X6_U_X7_U_X8_U_X9_U_X10_U_X11_U_X12_U_X13_U_X14
 S ^BYIMRT(RSPDA,3,0)="^90480.23^"_XX_U_XX
 Q
 ;=====
 ;
NF(X) ;PATIENT NOT FOUND
 N Y,Z
 I $D(^BYIMRT(RSPDA,4,XX,0)) S JJ=JJ+1,Y=^(0),Z=$G(^(1)) D  Q
 .S DISE(JJ)=Y
 .S:Z]"" DISE(JJ,1)=Z
 S (QAK,Y)=$P(X,"|",3)
 S DFN=+$P(X0,"_",3)
 S DFN=$P($G(^DPT(DFN,0)),U)
 ;PATCH 4 - FID-76113/CR-12047
 ;Insure message display is complete, not truncated
 S:Y="NF" Z="NF^NO MATCH for"_$S(DFN]"":": "_DFN,1:" this patient.")
 S:Y="TM" Z="TM^Multiple matches for"_$S(DFN]"":": "_DFN,1:" this patient ID")
 ;PATCH 4 - FID-76113/CR-12047 END
 S ^BYIMRT(RSPDA,4,XX,0)=Z,JJ=JJ+1,DISE(JJ)=^(0)
 S ^BYIMRT(RSPDA,4,0)="^90480.24^1^1"
 Q
 ;=====
 ;
ERROR(LINE,LNUM,MID,KK) ;EP;CREATE ERROR NODE 4 OR WARNING NODE 5
 N X,Y,Z,J,STT,SEG,SEGX,SNUM,FIELD,ERROR,TYP,EXP
 ;
 ;LINE = HL7 MESSAGE ERROR SEGMENT
 ;LNUM = HL7 MESSAGE SEGMENT LINE NUMBER
 ;
 Q:LINE["No patient found"
 S X0=$G(^BYIMRT(RSPDA,0))
 S ETYP=$P(LINE,"|",5)
 S ENOD=$S(ETYP="E":4,ETYP="W":5,1:"")
 Q:'ENOD
 S STT=$S($P($G(^DIC(5,+$P(X0,U,10),0)),U)]"":$P(^DIC(5,+$P(X0,U,10),0),U),1:"The SIIS")_" reports "_$S(ENOD=4:"an ERROR",1:"a WARNING")_" in Message "_MID_" "
 S SEG=$P(LINE,"|",3)
 S SEGN=$P(SEG,U)
 S:SEGN="" SEGN="ERR"
 S OCN=$P(SEG,U,2)
 I 'OCN,SEGN'["OBX" S OCN=1
 I 'OCN,SEGN["OBX" S OCN=99
 S SN=$$SC(SEG,OCN,$P(LINE,"|",9))
 Q:SN=""
 S:"|PID|PD1|NK1|RXR|"[SEGN OCN=1
 S X=$E(OCN,$L(OCN))
 S OCC=OCN_$S(X=1:"st",X=2:"nd",X=3:"rd",X="":"",1:"th")
 S:OCC="99th" OCC=""
 S SFLD=$S($P(SEG,U,5):$P(SEG,U,5),1:1)
 S RPT=$P(SEG,U,4)
 S FLD=$S($P(SEG,U,3):$P(SEG,U,3),1:1)
 S SEGX=SEGN_"-"_FLD_"."_SFLD
 S SEGDA=+$O(^BYIMSEG("B",SEGX,0))
 S FNAM=$P($G(^BYIMSEG(SEGDA,0)),U,4)
 S FIELD="Component name: '"_FNAM_"' "
 S SEG=$S("|PID|PD1|NK1|"[SEGN:"",1:OCC_$S(OCC]"":" ",1:""))_"'"_SEGN_"' Segment, "_SEGX_" '"_FNAM_"'"
 S ERROR="ERROR: "_$P($P(LINE,"|",4),U,2)
 S NOTE=$S(ETYP="E":"ERROR: ",1:"WARNING: ")_$P(LINE,"|",9)
 S TYP="in the "_SEG
 S X=STT_TYP_FIELD_NOTE
 S X1=$E(X,251,999)
 S X=$E(X,1,250)
 S ^BYIMRT(RSPDA,ENOD,SN,OCN,0)=X,KK=KK+1,DISE(KK)=X
 S:X1]"" ^BYIMRT(RSPDA,ENOD,SN,OCN,0,1)=X1,DISE(KK,0)=X1
 S ^BYIMRT(RSPDA,ENOD,SN,+OCN,.5)=SEGN_U_OCN_U_FLD_U_SFLD
 S ^BYIMRT(RSPDA,ENOD,SN,+OCN,2)=STT,DISE(KK,1)=STT
 S ^BYIMRT(RSPDA,ENOD,SN,+OCN,3)=TYP,DISE(KK,2)=TYP
 S ^BYIMRT(RSPDA,ENOD,SN,+OCN,4)=NOTE,DISE(KK,4)=NOTE
 S ^BYIMRT(RSPDA,ENOD,SN,+OCN,99)=LINE
 Q
 ;=====
 ;
DUP ;CHECK FOR DUPLICATE RXA'S
 N X,Y,Z,XX,L1,L2
 S X=""
 F  S X=$O(^BYIMTMP("DUP CHK",RSPDA,X)) Q:X=""  D
 .S L1=$O(^BYIMTMP("DUP CHK",RSPDA,X,"LINE",0))
 .Q:'L1
 .Q:'$D(^BYIMRT(RSPDA,2,L1,0))
 .S L2=$O(^BYIMTMP("DUP CHK",RSPDA,X,"LINE",L1))
 .Q:'L2
 .Q:'$D(^BYIMRT(RSPDA,2,L2,0))
 .S $P(^BYIMRT(RSPDA,2,L2,0),U,13)=L1
 N DFN,IEN,IDA,IDT,CVX
 S DFN=$P(X0,"_",3)
 S IEN=0
 F  S IEN=$O(^AUPNVIMM("AC",DFN,IEN)) Q:'IEN  D
 .S I0=$G(^AUPNVIMM(IEN,0))
 .S I12=$G(^AUPNVIMM(IEN,12))
 .S IDA=+I0
 .S IDT=$P($P(I12,U),".")
 .S:'IDT IDT=$P($P($G(^AUPNVSIT(+$P(I0,U,3),0)),U),".")
 .Q:'IDA!'IDT
 .S CVX=$P($G(^AUTTIMM(IDA,0)),U,3)
 .Q:CVX=""
 .S X=CVX_"_"_(IDT+17000000)
 .Q:'$D(^BYIMTMP("DUP CHK",RSPDA,X))
 .S L1=$O(^BYIMTMP("DUP CHK",RSPDA,X,"LINE",9999),-1)
 .Q:'L1
 .;PATCH 3 CR-12045 ENSURE EACH RESPONSE ENTRY FOR EACH COMPONENT
 .;FOR COMPOUND IMM HAS IEN IF APPLICABLE
 .F J=12,17 S $P(^BYIMRT(RSPDA,2,L1,0),U,J)=IEN
 .Q:$G(^BYIMRT(RSPDA,2,L1+.1,0))=""
 .F J=.1:.1:.4 D
 ..I $P($G(^BYIMRT(RSPDA,2,L1+J,0)),U,3,4)=$P(^BYIMRT(RSPDA,2,L1,0),U,3,4) D
 ...F K=12,17 S $P(^BYIMRT(RSPDA,2,L1+J,0),U,K)=IEN ;,^BYIMTMP("DUP",RSPDA,1,L1+J,0)=^(0)
 .;PATCH 3 END
 K ^BYIMTMP("DUP CHK",RSPDA)
 Q
 ;
DETAIL ;DISPLAY RESPONSE/ERROR DETAILS
 S X0=$G(^BYIMRT(RSPDA,0))
 W !,$P($G(^DIC(5,+$P(X0,U,10),0)),U)," reports an ERROR in the "
 W OCC," ",$P(ERRN,U)," segment:",!
 W !?8,"Field: ",SEGN,"-",$P(ERRN,U,3),".",$S($P(ERRN,U,5):$P(ERRN,U,5),1:"1")
 I FNAM]"" W !?3,"Field Name: ",FNAM
 W !,"has the value: "
 S X=$P(QPD,"|",$P(ERRN,U,3)+1)
 W $S(X="":"<BLANK>",1:X)
 W !,"Error Message: ",$P(RESP,U,2)
 W !?5,"Note: ",NOTE
 D PAUSE
 Q
 ;
DQPD(RSPDA) ;DISPLAY ORIGINAL QUERY MESSAGE
 N X,Y,Z
 S X=0
 F  S X=$O(^BYIMRT(RSPDA,1,X)) Q:'X  S Y=^(X,0) W !,Y
 D PAUSE
 Q
 ;
SC(SEGX,N,L) ;EP;TO SET SEQUENCING NUMBER
 ;SEGX = ERR-2 which specifies the SEGMENT, OCCURRENCE NUMBER AND
 ;       COMPONENT NUMBER WHICH HAS THE ERROR
 ;N    = SEQUENTIAL OCCURRENCE NUMBER OF THE SEGMENT
 ;L    = ERR-8 DESCRIPTION OF THE ERROR
 S SC=""
 S SN=$E(SEGX,1,3)
 S:SN="MSH" SC=.1_N
 S:SN="MSA" SC=.15_N
 S:SN="QPD" SC=.19_N
 S:SN="PID" SC=.2_N
 S:SN="PD1" SC=.3_N
 S:SN="NK1" SC=.4_N
 S:SN="IN1" SC=2_"."_N_1
 S:SN="IN2" SC=2_"."_N_2
 S:SN="ORC" SC=5_"."_N_1
 S:SN="RXA" SC=5_"."_N_2
 S:SN="RXR" SC=5_"."_N_3
 S:SN="OBX"&($P(SEGX,"|",2)=1) SC=90.1_N
 S:SN="OBX"&($P(SEGX,"|",2)=2) SC=90.2_N
 S:SN="OBX"&($P(SEGX,"|",2)=3) SC=90.3_N
 S:SN="OBX"&($P(SEGX,"|",2)=4) SC=90.4_N
 S:SN="OBX"&($P(SEGX,"|",2)=5) SC=90.5_N
 S:SN="OBX"&($P(SEGX,"|",2)=6) SC=90.6_N
 S:SN="OBX"&($P(SEGX,"|",2)=7) SC=90.7_N
 S:SN="OBX"&($P(SEGX,"|",2)=8) SC=90.8_N
 S:SN="OBX"&($P(SEGX,"|",2)=9) SC=90.9_N
 S:SN="OBX"&($P(SEGX,"|",2)=10) SC=90.91_N
 S:SN="OBX"&($P(SEGX,"|",2)=11) SC=90.92_N
 S:SN="OBX"&($P(SEGX,"|",2)=12) SC=90.93_N
 S:SN="OBX"&($P(SEGX,"|",2)=13) SC=90.94_N
 S:SN="OBX"&($P(SEGX,"|",2)=14) SC=90.95_N
 S:SN="OBX"&($P(SEGX,"|",2)=15) SC=90.96_N
 S:SN="OBX"&(N=99) SC=99_" "_$G(L)
 Q SC
 ;=====
 ;
ACK(RSPDA) ;EP;PROCESS IZDATA ACK'S
 S (JJ,KK)=0
 S MID=$P($G(^BYIMRT(RSPDA,0)),U,6)
 S:MID["IHS-" BYIMUIF=$O(^INTHU("C",MID,0))
 S XX=0
 F  S XX=$O(^BYIMRT(RSPDA,2,XX)) Q:'XX  S X=^(XX,0) D
 .I X["ERR|" D ERROR(X,XX,MID,KK)
 Q
 ;=====
 ;
