BYIMPATC ;IHS/CIM/THL - IMMUNIZATION DATA EXCHANGE; [ 06/19/2024  10:22 PM ]
 ;;3.0;BYIM IMMUNIZATION DATA EXCHANGE;**1,2,3,4,5,6,7,8**;AUG 20, 2020;Build 747
 ;;CONTINUATION OF BYIMIMM
 ;;NEW ENTRY ROUTINE FOR PATCH INSTALL ENTRY/EXIT ACTIONS
 ;
 ;=====
P2 ;EP;FOR PATCH 2 POST INSTALL PROCESSING
 ;PATCH 2
 D LOC^BYIMIMM3
 I $P($G(^DIC(9.4,+$O(^DIC(9.4,"C","BYIM",0)),"VERSION")),U)=2.01 S $P(^("VERSION"),U)="2.0"
 N TMP
 S TMP=0
 F  S TMP=$O(^BYIMTMP(TMP)) Q:'TMP  K ^(TMP,"NUM")
 S NAME=""
 F  S NAME=$O(^BYIMPARA("NMNAME",NAME)) Q:NAME=""  D
 .S DA(1)=0
 .F  S DA(1)=$O(^BYIMPARA("NMNAME",NAME,DA(1))) Q:'DA(1)  D
 ..S J=0
 ..S DA=0
 ..F  S DA=$O(^BYIMPARA("NMNAME",NAME,DA(1),DA)) Q:'DA  S J=J+1 D:J>1
 ...S DIK="^BYIMPARA("_DA(1)_",4,"
 ...D ^DIK
 Q
 ;=====
 ;
P4 ;EP;FOR VERSION 2.0 PATCH 4
 Q
 ;=====
 ;
P5 ;EP;FOR VERSION 2.0 PATCH 5
 ;IMPROVED IZFS DISPLAY
 ;CORRECT HFSA^BYIMIMM6 CALL
 ;CORRECT SCRN^BYIMIMMT BYIMALL VARIABLE
 ;RE-COMPILE 'HL IHS IZV04 OUT'
 ;SET ALL 'LAST EXPORT' PIECE 2 $H
 S MESS=$O(^INTHL7M("B","HL IHS IZV04 OUT",0))
 Q:'MESS
 S SEG=""
 S X=0
 F  S X=$O(^INTHL7M(MESS,1,X)) Q:'X  I $G(^(X,4))["$$SCRN" S ^(4)="I $$SCRN^BYIMIMM6(.INDA)",SEG=X
 Q:'SEG
 S SCR=$O(^INRHS("B","Generated: HL IHS IZV04 OUT-O",0))
 Q:SCR'=$P($G(^INTHL7M(MESS,"S")),U,2)
 S Y=MESS
 S INGALL=1
 S INSS=SCR
 D EN^INHSGZ
 N X
 S X=0
 F  S X=$O(^BYIMPARA($$DUZ^BYIMIMM(),"LAST EXPORT",X)) Q:'X  I X'=DT,$G(^(X)),'$P(^(X),U,2) S $P(^BYIMPARA($$DUZ^BYIMIMM(),"LAST EXPORT",X),U,2)=$P(^BYIMPARA($$DUZ^BYIMIMM(),"LAST EXPORT",X),U)
 Q
 ;=====
 ;
P6 ;EP;FOR VERSION 2.0 PATCH 6
 N X,Y,Z
 S X=+$O(^INTHL7F("B","HL IHS IZV04 MSH-05 RECEIVING APP",0))
 K ^INTHL7F(X,5)
 Q
 ;=====
 ;
P7 ;EP;FOR VERSION 2.0 PATCH 7
 Q
 ;=====
 ;
P8 ;EP;FOR VERSION 2.0 PATCH 8
 Q
 ;=====
P9 ;EP;FOR VERSION 2.0 PATCH 9
 F X="XPO1","XPZ1","XPZ2","XPI1" S XPDDIQ(X)=0
 Q
 ;=====
 ;
P10 ;EP;
 N X,Y,Z,J,HIS,SC
 D SCREEN
 S BYIMDUZ=+$$DUZ^BYIMIMM()
 S:$P($G(^BYIMPARA(BYIMDUZ,9)),U)="" $P(^BYIMPARA(BYIMDUZ,9),U)="Z22"
 S:$P($G(^BYIMPARA(BYIMDUZ,9)),U,2)="" $P(^BYIMPARA(BYIMDUZ,9),U,2)="CDCPHINVS"
 S X=0
 F  S X=$O(^BYIMPARA(BYIMDUZ,3,X)) Q:'X  D
 .S $P(^BYIMPARA(BYIMDUZ,3,X,9),U)="Z22"
 .S $P(^BYIMPARA(BYIMDUZ,3,X,9),U,2)="CDCPHINVS"
 S X=0
 F  S X=$O(^BYIMPARA(BYIMDUZ,5,X)) Q:'X  S Y=^(X,0) I Y,X'=+Y D
 .I '$D(^BYIMPARA(BYIMDUZ,5,+Y,0)) D
 ..S ^BYIMPARA(BYIMDUZ,5,+Y,0)=Y
 ..S ^BYIMPARA(BYIMDUZ,5,"B",+Y,+Y)=""
 .K ^BYIMPARA(BYIMDUZ,5,X,0)
 .K ^BYIMPARA(BYIMDUZ,5,"B",+Y,X)
 S X=0
 F  S X=$O(^BYIMPARA(BYIMDUZ,3,X)) Q:'X  D
 .S Y=0
 .F  S Y=$O(^BYIMPARA(BYIMDUZ,3,X,5,Y)) Q:'Y  S Z=^(Y,0) D
 ..I Z,Y'=+Z D  Q
 ...S ^BYIMPARA(BYIMDUZ,5,+Z,0)=Z
 ...S ^BYIMPARA(BYIMDUZ,5,"B",+Z,+Z)=""
 ...K ^BYIMPARA(BYIMDUZ,3,X,5,Y,0)
 ...K ^BYIMPARA(BYIMDUZ,3,5,"B",+Z,Y)
 ..I '$P(Z,U),$P(Z,U,2)]"" D
 ...S $P(^BYIMPARA(BYIMDUZ,3,X,5,Y,0),U)=Y
 Q
 ;=====
 ;
P10X ;EP;XREF CHECK ONLY
 Q:'$O(^BYIMPARA(BYIMDUZ,3,0))
 I '$D(ZTQUEUED) D
 .W !!,"Please standby while immunization export status is evaluated."
 .W !,"This could take several minutes..."
 S J=0
 S X=9999999999
 F  S X=$O(^BYIMEXP(X),-1) Q:'X!(J>999999)  S I=$P($G(^(X,0)),U,3) D:I
 .S J=J+1
 .I '$D(ZTQUEUED) W:J#100000=0 "E"
 .S Y=0
 .F  S Y=$O(^BYIMPARA(BYIMDUZ,3,Y)) Q:'Y  D:'$D(^BYIMEXP("DD",I,Y))
 ..I '$D(ZTQUEUED) W:J#100000=0 "D"
 ..S ^BYIMEXP("DD",I,Y,X,Y)=""
 D IMM
 Q
 ;=====
 ;
P3 ;EP;FOR VERSION 2.0 PATCH 3
 Q
 ;=====
 ;
V3 ;EP;FOR VERSION 3.0 POST INSTALL
 D P10
 S:'$P($G(^BYIMPARA(BYIMDUZ,9)),U,5) $P(^BYIMPARA(BYIMDUZ,9),U,5)=90
 N X,Y,Z,BYIMX,X1,X2,NOW,DIFROM
 S X=$O(^DIC(9.4,"C","BYIM",0))
 S:X $P(^DIC(9.4,X,"VERSION"),U)="3.0"
V3AI ;START 'AUTO IMPORT' IN OPTION SCHEDULING
 S BYIMX=+$O(^DIC(19,"B","BYIM IZ AUTO IMPORT",0))
 K DIC,DA,DR,DIK
 S DA=0
 F  S DA=$O(^DIC(19.2,"B",BYIMX,DA)) Q:'DA  D
 .S DIK="^DIC(19.2,"
 .D ^DIK
 N T,T1,T2
 D NOW^%DTC
 S T1=$P(%,".",2)
 S TM=$E(T1,3,4)
 S TH=$E(T1,1,2)
 S L=$L(TH)
 I 'L S TH="00",L=2
 I L=1 S TH=TH_"0"
 S L=$L(TM)
 I 'L S TM="05",L=2
 I L=1 S TM=TM_"0"
 S:TM<55 TM=TM+5
 I TH=23,TM>54 S TH=00,TM="05"
 S T=TH_TM
 I T="0005" S X1=DT,X2=1 D C^%DTC S NOW=X_"."_"0005" I 1
 E  S NOW=DT_"."_T
 S DIC="^DIC(19.2,"
 S DIC(0)="L"
 S DIC("DR")="2////"_NOW_";6////15S;9////P"
 S X=BYIMX
 D FILE^DICN
 K DIC,DA,DR,DIK
 ;
V3QP ;START 'AUTO PURGE' OF OLD QUERY/RESPONSE MESSAGES IN OPTION SCHEDULING
 S BYIMX=+$O(^DIC(19,"B","BYIM IZ PURGE OLD QUERY/RESP",0))
 S DA=0
 F  S DA=$O(^DIC(19.2,"B",BYIMX,DA)) Q:'DA  D
 .S DIK="^DIC(19.2,"
 .D ^DIK
 S X1=DT
 S X2=1
 D C^%DTC
 S NOW=X_".01"
 S DIC="^DIC(19.2,"
 S DIC(0)="L"
 S DIC("DR")="2////"_NOW_";6////1D;9////P"
 S X=BYIMX
 D FILE^DICN
 K DIC,DA,DR,DIK
 ;
V3AQ ;START 'AUTO QUERY' IN OPTION SCHEDULING
 S BYIMX=+$O(^DIC(19,"B","BYIM IZ SCHEDULED APPT QUERY",0))
 S DA=0
 F  S DA=$O(^DIC(19.2,"B",BYIMX,DA)) Q:'DA  D
 .S DIK="^DIC(19.2,"
 .D ^DIK
 D NOW^%DTC
 S T1=$P(%,".",2)
 S TM=$E(T1,3,4)
 S TH=$E(T1,1,2)
 S L=$L(TH)
 I 'L S TH="00",L=2
 I L=1 S TH=TH_"0"
 S L=$L(TM)
 I 'L S TM="05",L=2
 I L=1 S TM=TM_"0"
 S:TM<55 TM=TM+5
 I TH=23,TM>54 S TH=00,TM="05"
 S T=TH_TM
 I T="0005" S X1=DT,X2=1 D C^%DTC S NOW=X_"."_"0005" I 1
 E  S NOW=DT_"."_T
 S DIC="^DIC(19.2,"
 S DIC(0)="L"
 S DIC("DR")="2////"_NOW_";6////300S;9////P"
 S X=BYIMX
 D FILE^DICN
 K DIC,DA,DR,DIK
 Q
 ;=====
 ;
V3P2 ;EP;VERSION 3.0 PATCH 2
 S CVDDA=$$CVDDA^BYIMCOVD()
 S X=$$ADD^XPDMENU("BYIM IZ SETUP MENU","BYIM IZ FLAG COVID IMMS","FLCV",40)
 I CVDDA D
 .D RXA114^BYIMCOVD
 .D BCOM^BYIMCOV2
DEST S DEST=$O(^INRHD("B","HL IHS IZV04 QBP FRAMEWORK",0))
 S DA=$O(^INRHT("B","HL IHS IZV04 QBP OUT CHILD",0))
 I DEST,DA,$P($G(^INRHT(DA,0)),U,2)'=DEST D
 .S DIE="^INRHT("
 .S DR=".02////"_DEST
 .D ^DIE
 F XX="HL IHS IZV04 FRAMEWORK","HL IHS IZV04 QBP FRAMEWORK" D
 .S DA=$O(^INRHD("B",XX,0))
 .Q:'DA
 .S DR=".12////1"
 .S DIE="^INRHD("
 .D ^DIE
LED D LED^BYIMIMM7
 I $P($G(LE),U)?5N1",".N D
 .S $P(LE,U)=$$HTFM^XLFDT($P(LE,U))
 .S $P(LE,U,2)=$$HTFM^XLFDT($P(LE,U,2))
 .S ^BYIMPARA($$DUZ^BYIMIMM(),"LAST EXPORT",BYIMLEDT)=LE
 Q
 ;=====
 ;
SCREEN ;EP;ADD SCREEN CALL TO HL7 MESSAGE
 N X,Y,Z
 S X=$O(^INTHL7M("B","HL IHS IZV04 OUT",0))
 Q:'X
 S Y=$O(^INTHL7S("B","HL IHS IZV04 ORC",0))
 Q:'Y
 S Z=$O(^INTHL7M(X,1,"B",Y,0))
 Q:'Z
 Q:$G(^INTHL7M(X,1,Z,4))="I $$SCRN^BYIMIMM6(.INDA)"
 S ^INTHL7M(X,1,Z,4)="I $$SCRN^BYIMIMM6(.INDA)"
 S Y=X
 S INGALL=1
 D EN^INHSGZ
 Q
 ;=====
 ;
IMM ;EP;CHECK IMMS FOR EXPORT
 S BYIMDUZ=+$$DUZ^BYIMIMM()
 S HIS=$P($G(^BYIMPARA(BYIMDUZ,6)),U,6)
 S:'HIS HIS=3151231
 S J=0
 S IEN=9999999999
 F  S IEN=$O(^AUPNVIMM(IEN),-1) Q:'IEN!(J>999999)  S J=J+1
 S J=0
 S IEN=+IEN
 F  S IEN=$O(^AUPNVIMM(IEN),-1) Q:'IEN!(J>999999)  S X=$G(^(IEN,0)) D
 .S J=J+1
 .I '$D(ZTQUEUED) W:J#10000=0 "I"
 .S DFN=$P(X,U,2)
 .S V=$P(X,U,3)
 .S VD=$P($P($G(^AUPNVSIT(V,0)),U),"."),SC=$P($G(^(0)),U,7)
 .Q:'DFN!'VD!(SC="")
 .I VD>HIS&("AHI"[SC) Q
 .S BYIMALL=1
 .S STATE=BYIMDUZ
 .D LOG^BYIMIMM7(DFN,IEN,STATE)
 .S STATE=0
 .F  S STATE=$O(^BYIMPARA(BYIMDUZ,3,STATE)) Q:'STATE  D
 ..D LOG^BYIMIMM7(DFN,IEN,STATE)
 Q
 ;=====
 ;
V3P1 ;EP;Version 3.0 Patch 1
 K DA,DR,DIE,DIC,DINUM
 S DIE="^BYIMRT("
 S DA=0
 F  S DA=$O(^BYIMRT(DA)) Q:'DA  S X=$G(^(DA,0)) D
 .S DR=""
 .S DFN=$P($P(X,U),"_",3)
 .S Y=$P(X,U,4)
 .S Z=$P(X,U,5)
 .S ZZ=$P(Z,".",2)
 .S Z=$P(Z,".")
 .I $E(X,1,4)="izrt",DFN'=Y S DR=".04////"_DFN
 .I $L(ZZ)<6 D
 ..S ZZ=$E("000000",1,6-$L(ZZ))_ZZ
 ..S DR=$S(DR]"":DR_";",1:"")_".05////"_Z_"."_ZZ
 .Q:DR=""
 .W !,DA,?10,DR D ^DIE
 K DA,DR,DIE,DIC,DINUM
 Q
 ;=====
 ;
V3P3 ;EP;VERSION 3.0 PATCH 3
 N X,Y,Z,BX,X0,NOW,DFN,VDA
 D PREF
 D IC
 Q
 ;=====
 ;
PREF ;EP;TO RESEND REFUSAL AFTER 5/17/2021    
 ;PATCH 3 CR-12432 HX REFUSALS AFTER MAY 17
 ;FIND REFUSALS SINCE 5/17/21 AND SET TO RESEND
 N ADLM,BX,NOW
 S BYIMDUZ=$$DUZ^BYIMIMM()
 D NOW^%DTC
 S NOW=%
 S ADLM=3210516.999
 F  S ADLM=$O(^AUPNPREF("ADLM",ADLM)) Q:'ADLM  D
 .S BX=0
 .F  S BX=$O(^AUPNPREF("ADLM",ADLM,BX)) Q:'BX  D PREF1
 Q
 ;=====
 ;
PREF1 ;
 S X0=$G(^AUPNPREF(BX,0)),X12=$G(^(12))
 Q:+X0'=3
 K DA,DIE,DR
 S DIE="^AUPNPREF("
 S DA=BX
 S DR=".08////"_NOW_";1218////"_NOW
 D ^DIE
 K ^BYIMEXP("REF",BX)
 K ^BYIMEXP("REF"_BYIMDUZ,BX)
 S X=0
 F  S X=$O(^BYIMPARA(BYIMDUZ,3,X)) Q:'X  K ^BYIMEXP("REF"_X,BX)
 ;PATCH 3 CR-12432 END
 Q
 ;=====
 ;
IC ;EP;Patch 3 CR-79469 re-send COVID immunizations for
 ;immunocompromised patients.
 ;
 ;TAXONOMY LOOK BACK
 ;   DX - 1 YEAR
 ;   RX - 3 MONTHS
 ;   EVALUATE ALL WITH COVID VAX STARTING 8/12/2021
 ;
 K TMP("IC")
 ;
 D ICSET
 ;
 ;CHECK PATIENTS WITH COVID V IMM'S SINCE 8/12/21
 ;AND RE-SEND THOSE WITH IC DX OR RX
 S X=0
 F  S X=$O(COV(X)) Q:'X  D
 .S IEN=9999999999
 .F  S IEN=$O(^AUPNVIMM("B",X,IEN),-1) Q:'IEN  D
 ..S I0=$G(^AUPNVIMM(IEN,0)),I12=$G(^(12))
 ..S DFN=+$P(I0,U,2)
 ..S V=+$P(I0,U,3)
 ..Q:'DFN!'V
 ..S IDT=$P($P(I12,U),".")
 ..I 'IDT S IDT=$P($P($G(^AUPNVSIT(V,0)),U),".")
 ..Q:IDT<3210812
 ..;RETURN RISK STATUS EITHER FROM BIDX CALL OR BYIM CALCULATION
 ..Q:'$$RISK(DFN)
 ..;SET EACH COVID V IMM TO BE RE-SENT DUE TO IMMUNO-COMPROMISED STATUS
 ..S TMP("IC",IEN)=""
 ..S ^BYIMTMP("IC",DFN,V,IEN,"BIDX",DT)=IDT
 D NOW^%DTC
 S NOW=%
 S IEN=0
 F  S IEN=$O(TMP("IC",IEN)) Q:'IEN  D SIMM(IEN)
 K TMP("IC"),DA,DX,RX,RXN
 Q
 ;=====
 ;
DFN(DFN) ;EP;CHECK PT FOR IS DX/DRX
 S RISK=0
 S PDT=0
 F  S PDT=$O(^AUPNVPOV("AA",DFN,PDT)) Q:PDT>DDT!'PDT!RISK  D
 .S PIEN=0
 .F  S PIEN=$O(^AUPNVPOV("AA",DFN,PDT,PIEN)) Q:'PIEN!RISK  D
 ..S DX=+$G(^AUPNVPOV(PIEN,0))
 ..Q:'$D(DX(DX))
 ..S RISK=1
 Q:RISK
 S PDT=0
 F  S PDT=$O(^AUPNVMED("AA",DFN,PDT)) Q:PDT>RDT!'PDT!RISK  D
 .S PIEN=0
 .F  S PIEN=$O(^AUPNVMED("AA",DFN,PDT,PIEN)) Q:'PIEN!RISK  D
 ..S RX=+$G(^AUPNVMED(PIEN,0))
 ..Q:'$D(RX(RX))
 ..S RISK=1
 ;Patch 3 CR-79469 END
 Q
 ;=====
 ;
ICARRAY ;EP;CREATE IMMUNOCOMPROMISED ARRAY
 ;CREATE 'DX' ARRAY OF DX'S FROM DX TAXOMOMIES
 ;
 N X,Y,Z
 K DA,DX,RX,RXN
 ;
 F X="BQI CANCER DXS","BQI IMMUNE DEFICIENCY DXS","BQI TRANSPLANT DXS" D
 .S Y=+$O(^ATXAX("B",X,0))
 .Q:'Y
 .S Z=0
 .F  S Z=$O(^ATXAX(Y,21,Z)) Q:'Z  S ZZ=$P($G(^(Z,0)),U) D:ZZ]""
 ..S DA=$O(^ICD9("AB",ZZ,0))
 ..S:DA DX(DA)=ZZ
 ;
 ;CREATE 'RX' ARRAY OF RX'S FROM RX TAXOMOMIES
 ;TRANSFORM RXCUI IN RXNORM TAXOMOMY TO RX ARRAY OF DRUG POINTERS
 ;
 S X=+$O(^ATXAX("B","ATX IMMUNOSUPPRESS RXNORM",0))
 S Y=0
 F  S Y=$O(^ATXAX(X,21,Y)) Q:'Y  S Z=$P($G(^(Y,0)),U) S:Z]"" RXN(Z)=Z
 ;
 S X=0
 F  S X=$O(^PSDRUG(X)) Q:'X  S Y=$P($G(^PSDRUG(X,999999924)),U,4) I Y]"",$D(RXN(Y)) S RX(X,Y)=Y
 ;
 ;ADD TO RX ARRAY WITH DRUG POINTERS FROM DRUG TAXONOMY
 ;
 S X=+$O(^ATXAX("B","ATX IMMUNOSUPPRESS DRUGS",0))
 S Y=0
 F  S Y=$O(^ATXAX(X,21,Y)) Q:'Y  S Z=$P($G(^(Y,0)),U) S:Z]"" RX(Z,+$P($G(^PSDRUG(Z,999999924)),U,4))=""
 Q
 ;=====
 ;
COV ;CREATE COVID IMMUNIZATIONS IEN ARRAY
 S X=309
 F  S X=$O(^AUTTIMM(X)) Q:'X  I ^(X,0)["COVID" S COV(X)="",COVX($P(^(0),U,3))=""
 Q
 ;=====
 ;
LBDATE ;EP;SET DX LOOK BACK DATE
 S X1=DT
 S X2=-365
 D C^%DTC
 S:$E(X,5,7)=229 X=$E(X,1,6)_8
 S DDT=9999999-X
 ;
 ;SET RX LOOK BACK DATE
 S X1=DT
 S X2=-90
 D C^%DTC
 S:$E(X,5,7)=229 X=$E(X,1,6)_8
 S RDT=9999999-X
 Q
 ;=====
 ;
SIMM(IMDA) ;SET COVID IMM TO BE RESENT
 Q:'$G(IMDA)
 D SIMM^BYIMRFCV(IMDA)
 Q
 ;=====
 ;
ICSET ;
 ;CREATE IMMUNOCOMPROMISED TAXONOMY ARRAYS
 D ICARRAY
 ;
 ;SET LOOK BACK DATES
 D LBDATE
 ;
 ;CREATE COVID IMMUNIZATIONS ARRAY
 D COV
 ;
 Q
 ;=====
 ;
RISK(DFN) ;EP;RETURN RISK STATUS
 I $T(RISKC^BIDX)]"" D RISKC^BIDX(DFN,,,.RISK) I 1
 E  D DFN(DFN)
 Q RISK
 ;=====
 ;
V3P4 ;EP;VERSION 3.0 PATCH 4
 S BYIMDUZ=$$DUZ^BYIMIMM()
 S $P(^BYIMPARA(BYIMDUZ,0),U,11)=4
 S:$P($G(^BYIMPARA(BYIMDUZ,10)),U,5)="" $P(^BYIMPARA(BYIMDUZ,10),U,5)=1
 N X,Y,Z
 S X=0 F  S X=$O(^BYIMPARA(BYIMDUZ,3,X)) Q:'X  S $P(^BYIMPARA(BYIMDUZ,3,X,0),U,11)=4 S:$P($G(^BYIMPARA(BYIMDUZ,3,X,10)),U,5)="" $P(^(10),U,5)=1
 Q
 ;=====
 ;
V3P5 ;EP;VERSION 3.0 PATCH 5
 N DIE,DA,DR
 S DIE="^BIELIG("
 S DR=".04///@"
 F DA=1:1:8 D
 .S E0=$G(^BIELIG(DA,0))
 .S DESC=$P(E0,U,2)
 .S LOCAL=$P(E0,U,4)
 .Q:LOCAL=""
 .Q:LOCAL'=DESC
 .D ^DIE
 Q
 ;=====
 ;
V3P6 ;EP;VERSION 3.0 PATCH 6
 Q
 ;=====
 ;
V3P7 ;EP;VERSION 3.0 PATCH 7
 ;V3.0 PATCH 7 - FID-101056 SHUT DOWN CAS EXPORT
 S X=$$ADD^XPDMENU("BYIMMENU","BYIM IZ EXPORT SELECT PATIENTS","IZEP",99)
 D BCOM^BYIMCOV7
 N DA,DIK
 S DA(1)=$$DUZ^BYIMIMM()
 S DA=0
 F  S DA=$O(^BYIMPARA(DA(1),3,DA)) Q:'DA  S X=$G(^(DA,0)) D:X["COVID"
 .S DIK="^BYIMPARA("_DA(1)_",3,"
 .D ^DIK
 S XX="BYIM IZ SETUP MENU"
 S DA(1)=$O(^DIC(19,"B",XX,0))
 Q:'DA(1)
 S YY="BYIM IZ FLAG COVID IMMS"
 S ZZ=$O(^DIC(19,"B",YY,0))
 Q:'ZZ
 S DA=$O(^DIC(19,DA(1),10,"B",ZZ,0))
 Q:'DA
 S DIK="^DIC(19,"_DA(1)_",10,"
 D ^DIK
 Q
 ;=====
 ;
V3P8 ;EP;VERSION 3.0 PATCH 8
 Q
 ;=====
 ;
