BYIMIMM ;IHS/CIM/THL - IMMUNIZATION DATA EXCHANGE;
 ;;3.0;BYIM IMMUNIZATION DATA EXCHANGE;**1,2,3,4,5,6,7**;AUG 20, 2020;Build 747
 ;
 ;----
ENV ;EP;ENVIRONMENT CHECK
 I $$VERSION^XPDUTL("BYIM")'="3.0" D BMES^XPDUTL("BYIM 3.0 is required.") S XPDQUIT=2
 I $$VERSION^XPDUTL("BCOM")'="1.0" D BMES^XPDUTL("BCOM 1.0 is required.") S XPDQUIT=2
 I $G(XPDQUIT)=2 Q
 ;
 F X="XPO1","XPZ1","XPZ2","XPI1" S XPDDIQ(X)=0
 N BYIMDA
 S BYIMDA=+^AUTTSITE(1,0)
 I '$D(^BYIMPARA(+BYIMDA,0)) D
 .K DIE,DIC,DINUM,DR,DA,DD,DO,DIK,DLAYGO
 .S DIC="^BYIMPARA("
 .S DIC(0)="L"
 .S (X,DINUM)=+^AUTTSITE(1,0)
 .D FILE^DICN
 .K DIE,DIC,DINUM,DR,DA,DD,DO,DIK,DLAYGO
 .S BYIMDA=+Y
 I $D(^BYIMPARA(BYIMDA)),'$D(^BYIMPARA(BYIMDA,0)) D
 .S ^BYIMPARA(BYIMDA,0)=BYIMDA
 .S ^BYIMPARA("B",BYIMDA,BYIMDA)=""
 Q
 ;=====
 ;
DE ;EP;IMMUNIZATION EXPORT
 ;PATCH 3 CR-12383 SPECIFY IMMUNIZATIONS TO SEND
 N BYIMJOB,BYIMY,BYIMRMSG,BYIMY,BYIMX,DA,DIC,DIE,DIK,DR,DIR,D19,DD19,DATE,DDATE,BYIMLEDT,DATE19,DEST,ENC,EVDT,FACILITY,BYIMFILE,INA,MSG,NUM,OPATH,IPATH,ZTDESC,ZTDTC,ZTIO,ZTQUEUED,ZTRTN,ZTSAVE,VALMBCK,XPDDIQ,BYIMCNT
 N AGE,AGE19,MSGCNT,DFNCNT,BYIMQUIT,BYIMLEDS,BYIMLEDE,BYIMHX,BYIMDATE
 D PATH
 I OPATH="" D NOPATH Q
 K BYIMQUIT
DATE ;EP;SELECT EXPORT DATE
 ;V3.0 PATCH 5 - FID-83630 ALLOW TERMINATION OF EXISTING EXPORT
 K ^BYIMTMP("SEND","LOC")
 K ^BYIMTMP("LOC")
 I $D(^BYIMTMP("PREP"))!$D(^BYIMTMP("SEND")),$D(ZTQUEUED) D  G DATE
 .S:'$G(CNT) CNT=1
 .S CNT=CNT+1
 .Q:CNT<4
 .D RESET
 I $D(^BYIMTMP("PREP"))!$D(^BYIMTMP("SEND")),'$D(ZTQUEUED) D  Q:$G(BYIMQUIT)
 .W !!?5,"A batch immunization export is currently in progress."
 .W !?5,"Please check back in several minutes to try again."
 .W !!?5,"or do you want to terminate the current export?"
 .K DIR
 .S DIR(0)="YO"
 .S DIR("A")="     Terminate the current export"
 .S DIR("B")="NO"
 .W !
 .D ^DIR
 .K DIR
 .I Y'=1 S BYIMQUIT=1 Q
 .D RESET
 ;V3.0 PATCH 5 - FID-83630 END
 K BYIMQUIT,BYIMTEST,^BYIMTMP("SCRN")
 N BYIMLEDT,X,Y,Z,BYIMDUZ
 S BYIMDUZ=$$DUZ()
 ;V3.0 PATCH 6 - FID-83363 EXPORT FOR SELECTED STATES
 I $G(BYIMEXST)="" S BYIMEXST=$S($G(^BYIMTMP("EXST"))]"":^("EXST"),1:"") ;ID STATES FOR EXPORT
 S Y=2,BYIMDUZ(Y)=DUZ(2),BYIMALL=1,BYIMADM=1,BYIMHX=0
 D DATE19
 D LED^BYIMIMM7
 I BYIMLEDT D D1^BYIMIMM9 Q:$D(BYIMQUIT)
 I 'BYIMLEDT D
 .S (BYIMLEDT,D19)=$S(YEARS=19:DATE19,1:DATE99)
 .Q:$D(ZTQUEUED)
 .W !!,"The date of the last Immunization export is not on file."
 .W !,"The export will include all Children 0-18 years of age."
 I '$D(ZTQUEUED) D  Q:$D(BYIMQUIT)
 .D ALL^BYIMRT3
 .D EXPST^BYIMRT3
 .;V3.0 PATCH 6 - FID-83363 END
 .W !!,"Evaluation of immunizations for export to the State Immunization"
 .W !,"registry may take several minutes."
 .S DIR(0)="YO"
 .S DIR("A")="Do you want to proceed"
 .S DIR("B")="NO"
 .W !
 .D ^DIR
 .K DIR
 .I Y'=1 S BYIMQUIT=""
 K ^BYIMTMP($J,"BYIM EXP")
 N X,Y,Z,ZZ,MSGCNT,DFN,BYIMQUIT,XX
 S XX=$P($H,",",2)
 D PATH
 I OPATH="" D NOPATH Q
 S:'$G(BYIMFAIL) BYIMFAIL=""
 D:$G(BYIMFILE)="" FN
 S ^BYIMTMP("BYIMFILE")=BYIMFILE
 I $D(^BYIMPARA(BYIMDUZ,"LAST EXPORT")) D LE^BYIMIMM9 Q
 I '$D(^BYIMPARA(BYIMDUZ,"LAST EXPORT")) D NLE^BYIMIMM9 Q
 Q
 ;=====
 ;
DEX ;EP;CREATE HL7 MESSAGES
 ;PATCH 3 CR-12419 CHANGE FILE CREATON TIMING AND GIS FILE CREATION
 K ^BYIMTMP("SCRN")
 D NOW^%DTC
 N NOW
 S NOW=%
 N BYIMU
 S BYIMJ=0
 D HEADER^BYIMIMM7
 S:'$G(BYIMALL) BYIMALL=1
 S:'$G(BYIMADM) BYIMADM=1
 S:'$G(BYIMLEDT) BYIMLEDT=""
 S:'$G(BYIMLEDS) BYIMLEDS=""
 S:'$G(BYIMLEDE) BYIMLEDE=""
 S:'$G(BYIMHX) BYIMHX=""
 K ^BYIMTMP("LOG")
 ;V3.0 PATCH 5 - FID-84367 IZTE export <UNDEF> error
 S (MSGCNT,DFN,LDFN,DFNCNT)=0
 ;V3.0 PATCH 5 - FID-84367 END
 F  S DFN=$O(^BYIMTMP($J,"BYIM EXP",DFN)) Q:'DFN  D
 .S DA=$O(^BYIMTMP($J,"BYIM EXP",DFN,0))
 .Q:'DA
 .S LDFN=DFN
 .S MSG=$$V04(DA,BYIMALL,BYIMADM,BYIMLEDT,BYIMLEDS,BYIMLEDE,BYIMHX)
 .Q:MSG'["Message Created Successfully"
 .W:'$D(ZTQUEUED) "/"
 .S MSGCNT=MSGCNT+1
 .S DFNCNT=DFNCNT+1
 S BYIMNUM=MSGCNT_U_DFNCNT_U_U_LDFN
 S BYIMJOB=$J
 K ^BYIMTMP($J,"BYIM EXP")
 S BYIMPAR=$O(^INRHT("B","HL IHS IZV04 OUT PARENT",0))
 F J=1:1 Q:'$D(^INLHFTSK("B",BYIMPAR))  H 1 W:'$D(ZTQUEUED) "\"
 D FOOTER
 ;PATCH 3 CR-12419 END
 N JJ S JJ=0 F  S JJ=$O(^BYIMTMP(JJ)) Q:'JJ  K ^BYIMTMP(JJ,"BYIM EXP")
 S XX=$P($H,",",2)-$S($G(XX):XX,1:$P($H,",",2))
 S BYIMNOW=NOW
 D SEND(NOW)
ZIS S ZTRTN="HFSA^BYIMIMM"
 S ZTDESC="IMMUNIZATION INTERFACE"
 ;PATCH 3 CR-12383 SPECIFY IMMUNIZATIONS TO SEND
 F X="BYIM*","DFN*","MSG*","IMM*" S ZTSAVE(X)=""
 S ZTIO=""
 S ZTDTC=$H
 D ^%ZTLOAD
 I $G(X)[U D  Q
 .W !!,"The export has been terminated."
 .D PAUSE
 .S BYIMQUIT=""
 .D RES1
OUT I '$D(ZTQUEUED) D
 .W !!?10,"Immunizations for ",MSGCNT," Patients were evaluated."
 .D PATH
 .I OPATH="" D NOPATH Q
 .W !!?10,"The file '",BYIMFILE,"' will be created in:"
 .;V3.0 PATCH 6 - FID-83363 EXPORT FOR SELECTED STATES
 .D EXST
 .;V3.0 PATCH 6 - FID 83363 END
 .W !!?10,"File creation may take several minutes."
 .W !?10,"Check for the file in the directory(ies) listed above."
 .W !!?10,"If SMM is running and data exchange established with the state,"
 .W !?10,"the file should transfer to the State registry automatically."
 .D PAUSE
 Q
 ;=====
 ;
HFSA ;EP;TO PROCESS EXPORT
 ;PATCH 3 CR-12419 CHANGE FILE CREATON TIMING AND GIS FILE CREATION
 ;PATCH 2 CR-12280 REMOVE EXTRANEOUS ENTRY FROM BATCH EXPORT QUEUE
 Q:'$D(^BYIMTMP("SEND",BYIMNOW))
 S BYIMDUZ=$$DUZ()
 ;V3.0 PATCH 7 - FID-91807  EXPORT SELECTED PATIENTS
 ;PATCH 3 CR-12383 SPECIFY IMMUNIZATIONS TO SEND
 I '$D(BYIMLEDT),'$D(BYIMLEDS) D LED^BYIMIMM7
 I '$D(BYIMLEDT),'$D(BYIMLEDS),'$G(BYIMTEST) D
 .S BYIMLEDT=DT
 .S BYIMLEDS=$S($G(BYIMLEDS):BYIMLEDS,1:%)
 I '$G(BYIMTEST),'$G(BYIMSPE),BYIMLEDT,BYIMLEDS>BYIMLEDT D
 .D NOW^%DTC
 .S ^BYIMPARA(BYIMDUZ,"LAST EXPORT",DT)=%
 H 10
 D:$G(BYIMTEST) CLEAN^BYIMIMM5
 D CLEAN
HFSARES ;EP;RESTART EXPORT WHEN FILE NOT CREATED 
 ;V3.0 PATCH 6 - FID-83363 EXPORT FOR SELECTED STATES
 I $G(^BYIMTMP("EXST"))]"" S BYIMEXST=^("EXST") K ^("EXST")
 I $G(BYIMEXST)="" D EXST
 ;V3.0 PATCH 6 - FID-83363 END
 S BYIMDUZ=$$DUZ()
 I '$G(BYIMNOW) D  Q:'BYIMNOW
 .S BYIMNOW=$O(^BYIMTMP("SEND",9999999999),-1)
 .S BYIMEXST=""
 S DEST=BYIMNOW
 N PRI
 S PRI=+$O(^INLHDEST(DEST,""))
 S NUM=$G(BYIMNUM)
 K ^BYIMTMP("NUM"),^("BYIMFILE")
 S DFNCNT=$P(NUM,U,2)
 S IMMCNT=$P(NUM,U,3)
 S NUM=+NUM
 D PATH
 I OPATH="" D NOPATH Q
 S:'$G(BYIMFAIL) BYIMFAIL=""
 D:$G(BYIMFILE)="" FN
 D HFSA^BYIMIMM8(DEST,OPATH,BYIMFILE)
 I $G(BYIMFAIL)=1 H 10 G HFSARES
 ;V3.0 PATCH 5 - FID-85649 - DON'T SET EXPFAIL IF OUTBOUND PATH (BYIMHDIR)
 ;IS NULL
 ;Q:$G(BYIMFAIL)>1  ;S:'$G(BYIMTEST) $P(^BYIMPARA(BYIMDUZ,"LAST EXPORT",DT),U,2)="ExportFail" Q
 ;V3.0 PATCH 5 - FID-85649 - END
 I '$G(BYIMTEST),'$D(BYIMSPE),BYIMLEDT,BYIMLEDS>BYIMLEDT D
 .D NOW^%DTC
 .S $P(^BYIMPARA(BYIMDUZ,"LAST EXPORT",DT),U,2)=%
 ;V3.0 PATCH 7 - FID-91807 END
 D LOG^BYIMIMM4(BYIMFILE,"E",DFNCNT,IMMCNT,,,,OPATH)
 K ^BYIMTMP("NUM")
 K ^BYIMTMP("BYIMFILE")
 K ^BYIMTMP("SEND",DEST)
 K ^BYIMTMP("FOOT")
 K ^BYIMTMP("MID")
 K BYIMFILE
 Q
 ;=====
 ;
V04(BYIMVST,BYIMALL,BYIMADM,BYIMLEDT,BYIMLEDS,BYIMLEDE,BYIMHX) ;CREATE MESSAGE
 ;this is the unsolicited Imm record
 ;
 ;BYIMVST  = IEN OF VISIT
 ;BYIMALL  = 1 EXPORT NEW or EDITED ONLY
 ;           2 EXPORT ALL IMMS FOR PATIENT
 ;BYIMADM  = 1 EXPORT ONLY ADMINISTERED IMMUNIZATIONS
 ;           2 EXPORT ADMINISTERED AND HISTORIC
 ;BYIMLEDT = LAST EXPORT DATE
 ;BYIMLEDS = SELECTED EXPORT START DATE
 ;BYIMLEDE = SELECTED EXPORT END DATE
 ;BYIMHX   = 0 EXCLUDE HISTORIC IF BYIMALL=1
 ;           1 INCLUDE HISTORIC IF BYIMALL=1
 ;             & START DATE LESS THAN LAST EXPORT DATE
 ;
 I 'BYIMVST Q $$MSG("VST")
 D PATH
 S BYIMPAT=$P($G(^AUPNVSIT(BYIMVST,0)),U,5)
 K INDA
 S INDA=BYIMPAT
 S INDA(9000010,1)=BYIMVST
 S INDA(2,1)=BYIMPAT
 F J=1,3,4,5,6 S INDA((9000000+J),1)=BYIMPAT
 S INDA("BYIMALL")=$G(BYIMALL)
 S INDA("BYIMADM")=$G(BYIMADM)
 S INDA("BYIMLEDT")=$G(BYIMLEDT)
 S INDA("BYIMLEDS")=$G(BYIMLEDS)
 S INDA("BYIMLEDE")=$G(BYIMLEDE)
 S INDA("BYIMTEST")=$G(BYIMTEST)
 S INDA("BYIMHX")=$G(BYIMHX)
 S BYIMPAR="HL IHS IZV04 OUT PARENT"
 S INHF=0
 D ^INHF(BYIMPAR,.INDA)
 S BYIMJ=$G(BYIMJ)+1
 F J=1:1 Q:$G(INHF)  H 1 W:'$D(ZTQUEUED) "W"
 S ^BYIMTMP("PREP",NOW,+$G(INHF),BYIMJ)=""
 D EOJ
 Q $$MSG(INHF)
 ;=====
 ;
FOOTER ;this is the file termination record
 ;PATCH 3 CR-12419 CHANGE FILE CREATON TIMING AND GIS FILE CREATION
 S INHF=0
 S INDA=$P(^INTHU(0),U,3)+1
 D ^INHF("HL IHS IZV04 OUT FOOTER PARENT",.INDA,.INA)
 S BYIMPAR=+$O(^INRHT("B","HL IHS IZV04 OUT FOOTER PARENT",0))
 F J=1:1 Q:'$D(^INLHFTSK("B",BYIMPAR))  H 1 W:'$D(ZTQUEUED) "\"
 S BYIMJ=BYIMJ+1
 F J=1:1 Q:$G(INHF)  H 1 W:'$D(ZTQUEUED) "W"
 S ^BYIMTMP("PREP",NOW,+$G(INHF),9999999)="FOOTER"
 S ^BYIMTMP("FOOT",NOW,+$G(INHF),9999999)="FOOTER"
 D EOJ
 Q
 ;=====
 ;
EOJ ;EP;kills variables
 K INDA,BYIMPAT,BYIMVST,BYIMADT
 Q
 ;=====
 ;
MSG(BYIMMVAR)        ;-- return message defining status
 I BYIMMVAR="PAT" S BYIMRMSG="Patient Not Passed In, Message Not Created"
 I BYIMMVAR="VST" S BYIMRMSG="Visit Not Passed In, Message Not Created"
 I BYIMMVAR="VLAB" S BYIMRMSG="VLAB Not Passed In, Message Not Created"
 I BYIMMVAR="MFL" S BYIMRMSG="Mstr File Not Passed In, Message Not Created"
 I BYIMMVAR=0 S BYIMRMSG="Message Not Created, problem with GIS call"
 I BYIMMVAR S BYIMRMSG=BYIMMVAR_U_"Message Created Successfully"
 Q $G(BYIMRMSG)
 ;=====
 ;
IMZIS ;
 D IMZIS^BYIMIMM6
 Q
 ;=====
 ;
STRIP(Z) ;REMOVE CONTROLL CHARACTERS
 N I
 F I=1:1:$L(Z) I (32>$A($E(Z,I))) S Z=$E(Z,1,I-1)_" "_$E(Z,I+1,999)
 Q Z
 ;=====
 ;
BACK S VALMBCK="R"
 Q
 ;=====
 ;
RESTART ;EP;
 D RESTART^BYIMIMM7
 Q
 ;=====
 ;
RES1 ;CLEAR CURRENT EXPORT QUEUE
 D RES1^BYIMIMM9
 Q
 ;=====
 ;
DATE19 ;SET AGE FOR EXPORT
 N Y
 S BYIMDUZ=$$DUZ()
 S Y=$P($G(^BYIMPARA(BYIMDUZ,0)),U,6)
 S YEARS=$S('Y:19,Y=1:65,1:99)
 S CHILD=$S('Y:"Children",1:"Patients")
 S (AGE,AGE19)=19*10000
 S DATE19=DT-(19*10000)
 S AGE65=65*10000
 S DATE65=DT-(65*10000)
 S AGE99=99*10000
 S DATE99=DT-(99*10000)
 S D19=$S(YEARS=19:DATE19,YEARS=65:DATE65,1:DATE99)
 Q:'$O(^BYIMPARA(BYIMDUZ,3,0))
 S YEARS=99
 S CHILD="Patients"
 S D19=DATE99
 Q
 ;=====
 ;
LE ;PROCESS SEQUENTIAL EXPORT
 D LE^BYIMIMM9
 Q
 ;=====
 ;
NLE ;PROCESS FIRST EXPORT
 ;PATCH 3 CR-12383 SPECIFY IMMUNIZATIONS TO SEND
 D NLE^BYIMIMM9
 Q
 ;=====
D1 ;PROCESS WHEN DATE IDENTIFIED
 D D1^BYIMIMM9
 ;=====
 ;
PATH ;EP;SET PATH
 D PATH^BYIMIMM6
 Q
 ;=====
 ;
NOPATH ;EP;NO PATH MESSAGE
 D NOPATH^BYIMIMM6
 Q
 ;=====
 ;
PAUSE ;EP;FOR PAUSE READ
 D PAUSE^BYIMIMM6
 Q
 ;=====
 ;
CLEAN ;CLEAN OUT MESSAGES WITH NO RXA SEGMENT
 D CLEAN^BYIMIMM6
 Q
 ;=====
 ;
IMMCNT(DFN) ;COUNT PT IMMS TO BE EXPORTED
 N X,Y,Z,BYIMLEDT,EDATE
 S Y=0
 S X=0
 F  S X=$O(^AUPNVIMM("AC",DFN,X)) Q:'X  D
 .I $G(BYIMALL)=2 S Y=Y+1 Q
 .Q:$G(BYIMALL)'=1
 .I '$D(^BYIMEXP("D",X)) S Y=Y+1 Q
 .S EDATE=+$P($G(^AUPNVIMM(X,12)),U,18)
 .I BYIMLEDT,EDATE,EDATE>BYIMLEDS,EDATE<BYIMLEDE S Y=Y+1
 Q Y
 ;=====
 ;
FN ;EP;SET FILE NAME
 D NOW^%DTC
 S:$L($G(ASUFAC))'=6 ASUFAC=$P($G(^AUTTLOC($$DUZ(),0)),U,10)
 S BYIMFILE="izdata_"_$G(ASUFAC)_"_"_(DT+17000000)_"_"_$P(%,".",2)_$S($G(BYIMTEST):"_test",1:"")_"."_$S($G(BYIMEXT)]"":BYIMEXT,1:"dat")
 Q
 ;=====
 ;
DUZ() ;EP;PRIMARY PARAM SITE
 N X,Y,Z
 S Y=0
 S X=0
 F  S X=$O(^BYIMPARA(X)) Q:'X  I X=+^AUTTSITE(1,0) S Y=X
 I 'Y S X=0 F  S X=$O(^BYIMPARA(X)) Q:'X  I $D(^BYIMPARA(X,0)) S Y=X
 I 'Y D
 .S (DINUM,X)=+^AUTTSITE(1,0)
 .S DIC="^BYIMPARA("
 .S DIC(0)="L"
 .D FILE^DICN
 .S Y=+Y
 Q Y
 ;=====
 ;
VDEST() ;EP;FIND VXU MESSAGE DESTINATION
 ;PATCH 2 CR-12280 REMOVE EXTRANEOUS ENTRY FROM BATCH EXPORT QUEUE
 Q +$O(^INRHD("B","HL IHS IZV04 FRAMEWORK",0))
 ;PATCH 2 CR-12280 END
 ;=====
 ;
QDEST() ;EP;FIND QBP MESSAGE DESTINATION
 ;PATCH 2 CR-12280 REMOVE EXTRANEOUS ENTRY FROM BATCH EXPORT QUEUE
 S DEST=+$O(^INRHD("B","HL IHS IZV04 QBP FRAMEWORK",0))
 S DA=+$O(^INRHT("B","HL IHS IZV04 QBP OUT CHILD",0))
 I DEST,DA,$P($G(^INRHT(DA,0)),U,2)'=DEST D
 .S DIE="^INRHT("
 .S DR=".02////"_DEST
 .D ^DIE
 Q +$O(^INRHD("B","HL IHS IZV04 QBP FRAMEWORK",0))
 ;PATCH 2 CR-12280 END
 ;=====
 ;
RXACNT(UIF) ;
 N X,Y,Z
 S Y=0
 S X=0
 F  S X=$O(^INTHU(UIF,3,X)) Q:'X  S:^(X,0)["RXA|" Y=Y+1
 I 'Y S DIK="^INTHU(",DA=UIF D ^DIK
 Q Y
 ;=====
 ;
REFUSE(DFN) ;DETERMINE IF PATIENT HAS REFUSALS THAT HAVEN'T BEEN EXPORTED
 N REF,R0,R12,RDT,RDT12,QUIT
 S QUIT=0
 ;PATCH 2 CR-12280 REMOVE EXTRANEOUS ENTRY FROM BATCH EXPORT QUEUE
 S REF=9999999999
 F  S REF=$O(^AUPNPREF("AC",DFN,REF),-1) Q:'REF!QUIT  D
 .S R0=$G(^AUPNPREF(REF,0)),R12=$G(^(12))
 .Q:+R0'=3
 .Q:$D(^BYIMEXP("REF"_BYIMDUZ,REF))
 .S RDT=$P($P(R0,U,3),".")
 .S RDT12=$P(R12,U,18)
 .S:RDT12>RDT RDT=RDT12
 .S:RDT>(BYIMLEDT-.01) QUIT=1
 .;PATCH 2 CR-12280 END
 Q QUIT
 ;=====
 ;
SEND(NOW) ;QUEUE ALL MESSAGES
 N X,Y,Z,BYIMU
 S X=0
 F  S X=$O(^BYIMTMP("PREP",NOW,X)) Q:'X  D
 .S Y=0
 .F  S Y=$O(^BYIMTMP("PREP",NOW,X,Y)) Q:'Y  D
 ..S BYIMU=+$O(^INTHU("AT",X,0))
 ..S ^BYIMTMP("SEND",NOW,BYIMU,Y,$J)=""
 K ^BYIMTMP("PREP")
 Q
 ;=====
 ;
READY ;EP;TO CHECK BATCH EXPORT STATUS
 S ON=$G(^%ZIS(1,+$G(IO("HOME")),"SUBTYPE"))
 S:ON ON=$G(^%ZIS(2,ON,5))
 S RVON=$P(ON,U,4)
 S RVOFF=$P(ON,U,5)
 S BON=$P(ON,U,8)
 S BOFF=$P(ON,U,9)
 I $D(^BYIMTMP("PREP"))!$D(^BYIMTMP("SEND")) D
 .W !!?10
 .W:RVON]"" @RVON W:BON]"" @BON
 .W "Batch BYIM export in progress..."
 .W:RVOFF]"" @RVOFF W:BOFF]"" @BOFF
 .W !!
 I '$D(^BYIMTMP("PREP"))&'$D(^BYIMTMP("SEND")) D
 .W !!?10,"Batch BYIM export has completed...",!!
 H 4
 Q
 ;=====
 ;
RESET ;RESET FOR EXISTING EXPORT WHICH HASN'T PROCESSED
 ;V3.0 PATCH 5 - FID-83630 ALLOW TERMINATION OF EXISTING EXPORT
 N REF
 S REF=$O(^BYIMTMP("PREP",0))
 S:'REF REF=+$O(^BYIMTMP("SEND",0))
 I REF D
 .S REF=$P(REF,".")
 .Q:REF'?7N
 .S REF=REF-.01
 .F  S REF=$O(^BYIMPARA($$DUZ(),"LAST EXPORT",REF)) Q:'REF  D
 ..K ^BYIMPARA($$DUZ(),"LAST EXPORT",REF)
 K ^BYIMTMP("SEND"),^("PREP")
 N BYIMPAR
 S BYIMPAR=$O(^INRHT("B","HL IHS IZV04 OUT PARENT",0))
 K DIK,DA
 S DA=0
 S DIK="^INLHFTSK("
 F  S X=$O(^INLHFTSK("B",BYIMPAR,DA)) Q:'DA  D ^DIK
 K DIK,DA
 S BYIMPAR=+$O(^INRHD("B","HL IHS IZV04 FRAMEWORK",0))
 K ^INLHDEST(BYIMPAR)
 Q
 ;V3.0 PATCH 5 - FID-83630 END
 ;=====
 ;
EXST ;EP;SETUP EXTERIOR STATE EXPORT LIST
 ;V3.0 PATCH 6 - FID-83363 EXPORT FOR SELECTED STATES
 D EXST^BYIMIMM9
 Q
 ;=====
 ;
