BYIMIMM6 ;IHS/CIM/THL - IMMUNIZATION DATA EXCHANGE;
 ;;3.0;BYIM IMMUNIZATION DATA EXCHANGE;**2,3,5**;AUG 20, 2020;Build 644
 ;
MENU ;EP;HEADER DISPLAY
 W @IOF
 N PAC,PAH,VER,EXP,IMP,LOC,OUTPUT,FORMAT
 D M1
 D M2
 Q
 ;=====
 ;
M1 ;MENU DISPLAY
 D PATH
 S (PAC,PAH,VER)=""
 S PAC=+$O(^DIC(9.4,"C","BYIM",0))
 S VER=$P($G(^DIC(9.4,PAC,"VERSION")),U)
 S:VER PAH=$O(^DIC(9.4,PAC,22,"B",VER,0))
 S:PAH PAH=$O(^DIC(9.4,PAC,22,PAH,"PAH","B",99999),-1)
 S:PAH]"" VER=VER_" P "_PAH
 S VER="BYIM VERSION: "_VER
 S HL7=" HL7 VERSION: "_BYIMVER
 S LOC=$P($G(^DIC(4,$$DUZ^BYIMIMM(),0)),U)
 N X
 S X="Immunization Data Exchange"
 S EXP=$O(^DIC(19,"B","BYIM IZ AUTO EXPORT",0))
 S EXP=$O(^DIC(19.2,"B",+EXP,0))
 S EXP=$P($G(^DIC(19.2,+EXP,0)),U,2)
 I EXP S Y=EXP D DD^%DT S EXP=$P(Y,",")_"@"_$P(Y,"@",2)
 S EXP="NEXT AUTO EXPORT: "_$S(EXP="":"NOT SCHED",1:EXP)
 S IMP=$O(^DIC(19,"B","BYIM IZ AUTO IMPORT",0))
 S IMP=$O(^DIC(19.2,"B",+IMP,0))
 S IMP=$P($G(^DIC(19.2,+IMP,0)),U,2)
 I IMP S Y=IMP D DD^%DT S IMP=$P(Y,",")_"@"_$P(Y,"@",2)
 S IMP="NEXT AUTO IMPORT: "_$S(IMP="":"NOT SCHED",1:IMP)
 S QRY=$O(^DIC(19,"B","BYIM IZ SCHEDULED APPT QUERY",0))
 S QRY=$O(^DIC(19.2,"B",+QRY,0))
 S QRY=$P($G(^DIC(19.2,+QRY,0)),U,2)
 I QRY S Y=QRY D DD^%DT S QRY=$P(Y,",")_"@"_$P(Y,"@",2)
 S QRY="NEXT AUTO QUERY.: "_$S(QRY="":"NOT SCHED",1:QRY)
 S PRG=$O(^DIC(19,"B","BYIM IZ PURGE OLD QUERY/RESP",0))
 S PRG=$O(^DIC(19.2,"B",+PRG,0))
 S PRG=$P($G(^DIC(19.2,+PRG,0)),U,2)
 I PRG S Y=PRG D DD^%DT S PRG=$P(Y,",")_"@"_$P(Y,"@",2)
 S PRG="NEXT AUTO PURGE.: "_$S(PRG="":"NOT SCHED",1:PRG)
 Q
 ;=====
 ;
ADDLOT(DFN,IVDA,LOTDA,VDATE) ;EP;TO ADD LOT NUMBER
 ;DFN     - PATIENT DFN
 ;IVDA    - IMMUNIZATION FILE IEN
 ;LOTDA   - LOT NUMBER FILE IEN
 ;VDATE   - VISIT DATE
 H 1
 N X,Y,Z
 S X=$O(^AUPNVIMM("AC",DFN,9999999999),-1)
 Q:'X
 Q:+$G(^AUPNVIMM(X,0))'=IVDA
 Q:$P($G(^AUPNVIMM(X,0)),U,5)
 S Y=+$P($G(^AUPNVIMM(X,0)),U,3)
 Q:$P($G(^AUPNVSIT(Y,0)),".")'=$P(VDATE,".")
 N DIE,DIC,DINUM,DR,DA,DD,DO,DIK,DLAYGO
 S DA=X
 S DR=".05////"_LOTDA
 S DIE="^AUPNVIMM("
 D ^DIE
 K DIE,DIC,DINUM,DR,DA,DD,DO,DIK,DLAYGO
 Q
 ;=====
 ;
M2 ;VERSION 2.0 HEADER
 N X
 S X="Immunization Data Exchange"
 W !?80-$L(X)\2,X
 W !?80-$L(LOC)\2,LOC
 W !!?7,VER,?45,EXP
 W !?7,HL7,?45,IMP
 S ON=$G(^%ZIS(1,+$G(IO("HOME")),"SUBTYPE"))
 S:ON ON=$G(^%ZIS(2,ON,5))
 S RVON=$P(ON,U,4)
 S RVOFF=$P(ON,U,5)
 S BON=$P(ON,U,8)
 S BOFF=$P(ON,U,9)
 W !?2,"OUTPUT CONTROLLER: "
 I '$$VER^INHB(1) W:RVON]"" @RVON W:BON]"" @BON
 W $S($$VER^INHB(1):"RUNNING",1:"NOT RUNNING-Contact IT support")
 W @RVOFF
 W @BOFF
 W ?45,QRY
 W !?2,"FORMAT CONTROLLER: "
 I '$$VER^INHB(2) W:RVON]"" @RVON W:BON]"" @BON
 W $S($$VER^INHB(2):"RUNNING",1:"NOT RUNNING-Contact IT support")
 W @BOFF
 W @RVOFF
 W ?45,PRG
 Q
 ;=====
 ;
SCRN(INDA) ;EP;TO SCREEN IMM'S TO INCLUDE IN EXPORT
 ;
 ;INDA = V IMMUNIZATION IEN
 ;T=1 INCLUDE IMM IN EXPORT
 ;T=0 EXCLUDE IMM FROM EXPORT
 ;
 S T=0
 I '$G(INDA) G SOUT
 N I0,I12,V0,BYIMALL,BYIMADM,BYIMLEDT,DFN,VIEN
 S BYIMDUZ=$$DUZ^BYIMIMM()
 S I0=$G(^AUPNVIMM(INDA,0))
 S I12=$G(^AUPNVIMM(INDA,12))
 S DFN=+$P(I0,U,2)
 S VIEN=+$P(I0,U,3)
 S V0=$G(^AUPNVSIT(VIEN,0))
 S VDT=$P($P(V0,U),".")
 S IDT=$P($P(I12,U),".")
 S ADT=$P(I12,U,16)
 S EDT=$P(I12,U,18)
 S:'IDT IDT=VDT
 S:'ADT ADT=IDT
 S:'EDT EDT=IDT
 I 'DFN!'V0!'I0!$P(I0,U,15) S T=0 G SOUT
 S BYIMALL=$G(INDA("BYIMALL"))
 S BYIMADM=$G(INDA("BYIMADM"))
 ;PATCH 3 CR-12383 SPECIFY IMMUNIZATIONS TO SEND
 S BYIMLEDT=$G(INDA("BYIMLEDT"))
 S BYIMLEDS=$G(INDA("BYIMLEDS"))
 S BYIMLEDE=$G(INDA("BYIMLEDE"))
 S BYIMHX=$G(INDA("BYIMHX"))
 S NOW=$G(INDA("NOW"))
 S:'$G(BYIMDATE) BYIMDATE=""
 ;PATCH 2 CR-12280 REMOVE EXTRANEOUS ENTRY FROM BATCH EXPORT QUEUE
 I 'BYIMLEDT!'BYIMLEDS D LED^BYIMIMM7
 ;PATCH 2 CR-12280 END
 ;IF IMPORTED FROM OUTSIDE OR IMM POINTS TO UNKNOWN OR NOT ADMINISTERED
 ;ENTRY IN ^AUTTIMM THEN FLAG AS EXPORTED AND DON'T EXPORT
 ;D NOW^%DTC S NOW=%
 ;S ^BYIMTMP("SCRN",INDA,VIEN,1,+NOW)=T_U_$D(^BYIMEXP("D",INDA))_U_$P(I0,U,15)_U_$P($G(^AUTTIMM(+$G(^AUPNVIMM(+$G(INDA),0)),0)),U,3)
 I '$D(^BYIMEXP("D",INDA)),$P(I0,U,15)!($P($G(^AUTTIMM(+$G(^AUPNVIMM(+$G(INDA),0)),0)),U,3)=999) S ^BYIMEXP("D",INDA)="",T=0 G SOUT
 ;IF EXPORTING NEW AND OLD AND ADMIN'D AND HISTORIC THEN EXPORT
 ;S ^BYIMTMP("SCRN",INDA,VIEN,2,+NOW)=T_U_BYIMALL_U_BYIMADM
 I BYIMALL=2,BYIMADM=2 S T=1 G SOUT
 ;IF EXPORTING NEW AND OLD BUT ONLY ADMINISTERED IMM'S THEN EXPORT
 ;S ^BYIMTMP("SCRN",INDA,VIEN,3,+NOW)=T_U_BYIMALL_U_BYIMADM_U_$P(V0,U,7)
 I BYIMALL=2,BYIMADM=1,"CTNOEDXM"'[$P(V0,U,7) S T=1 G SOUT
 ;IF NOT PREVIOUSLY EXPORTED THEN EXPORT
 ;S ^BYIMTMP("SCRN",INDA,VIEN,4,+NOW)=T_U_BYIMALL_U_BYIMADM_U_$P(V0,U,7)_U_$D(^BYIMEXP("D",INDA))
 I BYIMALL=1,BYIMADM=1,"CTNOEDXM"'[$P(V0,U,7),'$D(^BYIMEXP("D",INDA)) S T=1
 I BYIMALL=1,BYIMADM=1,"CTNOEDXM"[$P(V0,U,7),'BYIMHX S T=0 G SOUT
 I BYIMALL=1,BYIMADM=1,$P(V0,U,7)="E",BYIMHX S T=1
 ;S ^BYIMTMP("SCRN",INDA,VIEN,5,+NOW)=T_U_BYIMALL_U_BYIMADM_U_$D(^BYIMEXP("D",INDA))
 I BYIMALL=1,BYIMADM=2,'$D(^BYIMEXP("D",INDA)) S T=1
 ;IF IMM WAS EDITED AFTER LAST EXPORT THEN RE-EXPORT
 ;S ^BYIMTMP("SCRN",INDA,VIEN,6,+NOW)=T_U_BYIMLEDT_U_EDT
 I EDT>BYIMLEDT S T=1
 ;CHECK EACH ADDITIONAL STATE WHETHER IMM SHOULD BE SENT
 ;S ^BYIMTMP("SCRN",INDA,VIEN,8,+NOW)=T_U_BYIMALL_U_BYIMADM_U_$D(^BYIMXP("D",INDA))_U_$O(^BYIMPARA(BYIMDUZ,3,0))
 I BYIMALL=1,BYIMADM=1,$D(^BYIMEXP("D",INDA)),'$O(^BYIMPARA(BYIMDUZ,3,0)) S T=0
 I 'T,BYIMLEDT=$P(BYIMLEDS,"."),$O(^BYIMPARA(BYIMDUZ,3,0)) D
 .S X=0
 .F  S X=$O(^BYIMPARA(BYIMDUZ,3,X)) Q:'X  D
 ..Q:$D(^BYIMEXP("DD",INDA,X))
 ..;CHECK IF AGE, PRIVACY AND FACILITY PARAM'S FOR THIS STATE
 ..S AGEP=$$AGECHK^BYIMIMM5(DFN,X)
 ..S PI=$$PI^BYIMIMM8(DFN,X)
 ..S LOC=$$LOC(INDA,X)
 ..;S ^BYIMTMP("SCRN",INDA,VIEN,9,+NOW)=T_U_AGEP_U_PI_U_LOC
 ..I AGEP,PI,LOC S T=1
 I BYIMLEDS<BYIMLEDT,BYIMALL=1 D
 .I BYIMHX,$P(V0,U,7)="E" D  Q
 ..I IDT>(BYIMLEDS-.01),IDT<BYIMLEDE S T=1
 ..E  S T=0
 .I 'BYIMHX,"CTNOEDXM"[$P(V0,U,7) S T=0 Q
 .I IDT>(BYIMLEDS-.01)!(EDT>(BYIMLEDS-.01)),IDT<BYIMLEDE!(EDT<BYIMLEDE) S T=1
 .E  S T=0
SOUT ;S ^BYIMTMP("SCRN",INDA,$J)=T_U_IDT_U_EDT_U_BYIMLEDT_U_BYIMLEDS_U_BYIMLEDE_U_BYIMHX Q T
 Q T
 ;PATCH 3 CR-12383 END
 ;=====
 ;
HFSA(DEST,PRI) ;EP;TO FIND HL7 MESSAGE THAT HAVEN'T BEEN EXPORTED
 S BYIMDUZ=$$DUZ^BYIMIMM()
 Q:PRI=""!'DEST
 K ^BYIMTMP("LE")
 K ^BYIMTMP("OF")
 N X,Y,Z,XX
 S X=""
 F  S X=$O(^INLHDEST(DEST,PRI,X)) Q:X=""  D
 .S Y=0
 .F  S Y=$O(^INLHDEST(DEST,PRI,X,Y)) Q:'Y  S ^BYIMTMP("OF",Y)="" S:$G(^INTHU(Y,3,1,0))["FHS|" XX=$P(X,",")_","_($P(X,",",2)+1)
 S X=0
 F  S X=$O(^BYIMPARA(BYIMDUZ,"LAST EXPORT",X)) Q:'X  I X'=DT,'$P(^(X),U,2) S ^BYIMTMP("LE",X+17000000)="",$P(^BYIMPARA(BYIMDUZ,"LAST EXPORT",X),U,2)=$P(^BYIMPARA(BYIMDUZ,"LAST EXPORT",X),U)
 S:$G(BYIM("MSH3.1"))="" BYIM("MSH3.1")=$P($G(^BYIMPARA(BYIMDUZ,1)),U,3)
 S:$G(BYIM("MSH3.1"))="" BYIM("MSH3.1")="RPMS"
 S:'$G(XX) XX=$H
 S X=0
 F  S X=$O(^INTHU(X)) Q:'X  S Z=$G(^(X,3,1,0)) I Z["VXU^V04",Z["MSH|" D
 .Q:$P($P(Z,"|",3),U)'=BYIM("MSH3.1")
 .Q:$P(Z,"|",10)=""
 .Q:$D(^BYIMTMP("OF",X))
 .Q:$D(^BYIMMM("MID",$P(Z,"|",10)))
 .S Y=$E($P(Z,"|",7),1,8)
 .Q:'$D(^BYIMTMP("LE",Y))
 .S ^BYIMMM("MID",$P(Z,"|",10))=""
 .S ^INLHDEST(DEST,PRI,XX,X)=""
 .S ^BYIMTMP("OF",X)=""
 .S $P(^BYIMTMP("NUM"),U,2)=$P($G(^BYIMTMP("NUM")),U,2)+1
 .S Y=0
 .F  S Y=$O(^INTHU(X,3,Y)) Q:'Y  S:^(Y,0)["RXA|" $P(^BYIMTMP("NUM"),U,3)=$P($G(^BYIMTMP("NUM")),U,3)+1
 K ^BYIMTMP("LE")
 K ^BYIMTMP("OF")
 Q
 ;=====
 ;
RLSH ;EP;TO DISPLAY AND EDIT RELATIONSHIP
 K BYIMQUIT
 D RUPD
 D RDISPLAY
 F  D REDIT Q:$D(BYIMQUIT)
 Q
 ;=====
 ;
RUPD ;EP;TO UPDATE IZ RELATIONSHIP FILE FROM RELATIONSHIP FILE
 N X,Y,Z,XX,YY,ZZ
 S XX=0
 F  S XX=$O(^AUTTRLSH(XX)) Q:'XX  S Y=$P(^(XX,0),U) D:'$D(^BYIMREL(XX))
 .S Z=$O(^BYIMCDC("C",Y,0))
 .S X=XX
 .K DIC,DINUM,DR,DA
 .S DINUM=X
 .S DIC="^BYIMREL("
 .S DIC(0)="L"
 .S:Z DIC("DR")=".02////"_Z
 .D FILE^DICN
 .K DIC,DINUM,DR,DA
 .Q:$D(ZTQUEUED)
 .W !,XX,?10,$P(^AUTTRLSH(XX,0),U)," added to BYIM Relationship Table."
 Q
 ;=====
 ;
RDISPLAY ;EP;TO DISPLAY BYIM/CDC RELATIONSHIP CROSS OVER
 D RDHEAD
 D PAUSE
 D RD
 N X,Y,Z,XX,YY,ZZ,JJ,BYIMPAUS
 S BYIMPAUS=""
 S JJ=0
 S XX=0
 F  S XX=$O(^BYIMREL(XX)) Q:'XX!$L(BYIMPAUS)  S Y=^(XX,0) D
 .S Z=^AUTTRLSH(XX,0)
 .S Z21=$G(^AUTTRLSH(XX,21))
 .W !,$J(XX,4)
 .W:$P(Y,U,2) ?10,$P(^BYIMCDC($P(Y,U,2),0),U)
 .W ?20,$P(Z,U),?52,$P(Z21,U,4)
 .S JJ=JJ+1
 .I JJ#15=0 D PAUSE
 Q
 ;=====
 ;
REDIT ;EP;TO EDIT RELATIONSHIP CROSS OVER
 W !!,"Select No. to Edit"
 K DIR
 S DIR(0)="NO^1:"_$O(^BYIMREL(9999999999),-1)
 S DIR("A")="LOCAL Relationship No. (or '^' to exit)"
 W !
 D ^DIR
 K DIR
 I X[U S BYIMQUIT="" Q
 Q:X=""
 S BYIMJ=X
 I '$D(^BYIMREL(BYIMJ,0)) W !!,"No. ",BYIMJ," isn't defined." H 2 Q
 W !!?10,"RPMS - RELATIONSHIP entry selected: ",$P($G(^AUTTRLSH(BYIMJ,0)),U)
 S DA=BYIMJ
 S DR=".02T"
 S DIE="^BYIMREL("
 D ^DIE
 Q
 ;=====
 ;
RDHEAD ;
 W @IOF
 W !!?10,"CDC HL7 Table 0063 Codes and Descriptions"
 W !!,"Code",?10,"Description"
 W !,"-------",?10,"------------------------------"
 N X,Y,Z
 S X=0
 F  S X=$O(^BYIMCDC(X)) Q:'X  S Y=^(X,0) D
 .W !,$P(Y,U),?10,$P(Y,U,2)
 Q
 ;=====
 ;
RD ;RELATIONSHIP LIST DISPLAY
 W @IOF
 W !?10,"BYIM Immunization Data Exchange"
 W !?10,"Local RELATIONSHIP entry and CDC HL7 Table 0063 Code"
 W !?10,"(NOTE: Local RELATIONSHIP without CDC HL7 code will be sent as 'OTH')"
 W !!,?10,"CDC HL7",?52,"Local HL7"
 W !,"No.",?10,"Code",?20,"Local RELATIONSHIP Description",?52,"Code"
 W !,"----",?10,"---",?20,"------------------------------",?52,"---------"
 Q
 ;=====
 ;
PATH ;EP;SET PATH
 S BYIMDUZ=$$DUZ^BYIMIMM()
 N X,X0
 S X0=$G(^BYIMPARA(BYIMDUZ,0))
 S X1=$G(^BYIMPARA(BYIMDUZ,1))
 S X6=$G(^BYIMPARA(BYIMDUZ,6))
 S X9=$G(^BYIMPARA(BYIMDUZ,9))
 S X10=$G(^BYIMPARA(BYIMDUZ,10))
 S OPATH=$P(X0,U,2)
 S OPATH=$$SLASH(OPATH)
 S IPATH=$P(X0,U,3)
 S IPATH=$$SLASH(IPATH)
 S QPATH=$P(X1,U)
 S QPATH=$$SLASH(QPATH)
 S RPATH=$P(X1,U,2)
 S RPATH=$$SLASH(RPATH)
 S BYIMEXT=$P(X0,U,8)
 S:BYIMEXT="" BYIMEXT="dat"
 S BYIMIN1=$P(X0,U,16)
 S BYIMCVX=$P(X0,U,17)
 S X=$P(X0,U,11)
 S BYIMADDV=X
 S Y=$P(^DD(90480,.11,0),U,3)
 S BYIMVER=$P($P(Y,X_":",2),";")
 S BYIMBDG=$P(X0,U,12)
 S BYIMQT=$P(X0,U,13)
 S BYIMPES=+$P(X0,U,14)
 S OPATH(BYIMPES)=OPATH
 S IPATH(BYIMPES)=IPATH
 S BYIMMSH8=$P(X0,U,15)
 S BYIM("MSH4.1")=$P(X0,U,7)
 S BYIM("MSH3.1")=$P(X1,U,3)
 S BYIM("MSH3.2")=$P(X1,U,4)
 S BYIM("MSH3.3")=$P(X1,U,5)
 S BYIM("MSH4.2")=$P(X1,U,6)
 S BYIM("MSH4.3")=$P(X1,U,7)
 S BYIM("MSH6.1")=$P(X1,U,8)
 S BYIM("PD13.1")=$P(X6,U)
 S BYIM("PD13.2")=$P(X6,U,2)
 S BYIM("MSH5.1")=$P(X6,U,3)
 S BYIM("MSH5.2")=$P(X6,U,4)
 S BYIM("MSH5.3")=$P(X6,U,5)
 S BYIM("MSH211")=$S($P(X9,U)]"":$P(X9,U),1:"Z22")
 S BYIM("MSH212")=$S($P(X9,U,2)]"":$P(X9,U,2),1:"CDCPHINVS")
 ;PATCH 2 CR-12279 CORRECT EVALUATION OF RXA-11.4
 S BYIM("MSH221")=$P(X6,U,12)
 S BYIM("MSH226")=$P(X9,U,9)
 S BYIM("MSH227")=$P(X9,U,10)
 S BYIM("MSH2210")=$P(X9,U,11)
 S BYIM("MSH231")=$P(X10,U)
 S BYIM("MSH236")=$P(X10,U,2)
 S BYIM("MSH237")=$P(X10,U,3)
 S BYIM("MSH2310")=$P(X10,U,4)
 ;PATCH 2 CR-12279 END
 S BYIMVSNS=$P(X10,U,5)
 S BYIMPV1=$P(X9,U,3)
 S QUERY=$P(X9,U,4)
 S QPURGE=$P(X9,U,5)
 S BYIMHIST=$P(X6,U,6)
 S BYIMESSN=$P(X6,U,7)
 S BYIMATYP=$P(X6,U,8)
 S BYIMDVOL=$P(X6,U,10)
 S ASUFAC=$P($G(^AUTTLOC(BYIMDUZ,0)),U,10)
 N X
 S X=0
 F  S X=$O(^BYIMPARA(BYIMDUZ,3,X)) Q:'X  S X0=^(X,0) D
 .S ES=+$P(X0,U,14)
 .S OPATH=$P(X0,U,2)
 .S OPATH=$$SLASH(OPATH)
 .S IPATH=$P(X0,U,3)
 .S IPATH=$$SLASH(IPATH)
 .S OPATH(ES)=OPATH
 .S IPATH(ES)=IPATH
 ;V3.0 PATCH 5 - FID-85649 - DON'T SET EXPFAIL IF OUTBOUND PATH (BYIMHDIR)
 ;IS NULL
 D:OPATH=""
 .N X,Y,Z
 .S X=0
 .F  S X=$O(OPATH(X)) Q:'X!(OPATH]"")  S:X]"" OPATH=OPATH(X)
 ;V3.0 PATCH 5 - FID-85649 - END
 Q
 ;=====
 ;
NOPATH ;EP;NO PATH MESSAGE
 I $D(ZTQUEUED) S BYIMQUIT="" Q
 S BYIMDUZ=BYIMDUZ
 W @IOF
 W !!,"You are logged into site: ",$P($G(^AUTTLOC(BYIMDUZ,0)),U,2)
 W !!,"Directory path information was missing."
 W !,"Please contact your Site Manager.  There must be entries in the"
 W !!?10,"PATH FOR OUTNBOUND MESSAGES field and the"
 W !?10,"PATH FOR INBOUND MESSAGES field of the"
 W !?10,"IZ PARAMETERS file for ",$P($G(^AUTTLOC(BYIMDUZ,0)),U,2)
 D PAUSE
 Q
 ;=====
 ;
PAUSE ;EP;FOR PAUSE READ
 N X,Y,Z
 Q:$D(ZTQUEUED)
 Q:$E($G(IOST),1,2)'="C-"
 W !
 K DIR
 S DIR(0)="E"
 S:'$D(DIR("A")) DIR("A")="Press <ENTER> to continue or '^' to exit..."
 D ^DIR
 K DIR
 S BYIMPAUS=X
 Q
 ;=====
 ;
SLASH(PATH) ;ENSURE PATH HAS TERMINATING SLASH
 N X
 S X=PATH
 Q:"/\"[$E(X,$L(X)) PATH
 S:X["/" PATH=PATH_"/"
 S:X["\" PATH=PATH_"\"
 Q PATH
 ;=====
 ;
NEW(DFN,BYIMALL,BYIMADM,BYIMLEDT,BYIMLEDS,BYIMLEDE,BYIMHX) ;EP;DETERMINE IF PATIENT HAS IMMS THAT HAVEN'T BEEN EXPORTED
 ;
 ;DFN        = PATIENT DFN
 ;BYIMALL  1 = NEW/EDITED ONLY
 ;         2 = SEND ALL
 ;BYIMADM  1 = ADMINISTERED ONLY
 ;         2 = ADMINISTERED AND HISTORIC
 ;BYIMLEDT   = LAST EXPORT DATE
 ;BYIMLEDS   = SELECTED EXPORT START
 ;BYIMLEDE   = SELECTED EXPORT END ;
 ;
 S BYIMDUZ=$$DUZ^BYIMIMM()
 K INDA,Y
 S INDA("BYIMALL")=$G(BYIMALL)
 S INDA("BYIMADM")=$G(BYIMADM)
 S INDA("BYIMLEDT")=$G(BYIMLEDT)
 S INDA("BYIMLEDS")=$G(BYIMLEDS)
 S INDA("BYIMLEDE")=$G(BYIMLEDE)
 S INDA("BYIMHX")=$G(BYIMHX)
 S Y=0
 S INDA=9999999999
 F  S INDA=$O(^AUPNVIMM("AC",DFN,INDA),-1) Q:'INDA!Y  D
 .S Y=$$SCRN(.INDA)
 Q Y
 ;=====
 ;
LOC(INDA,STATE) ;DETERMINE IF INDA NAS BEEN EXPORTED TO STATE
 N X,Y,Z
 S Z=0
 S X=+$P($G(^AUPNVIMM(+$G(INDA),0)),U,3)
 S Y=+$P($G(^AUPNVSIT(X,0)),U,6)
 ;DETERMINE IF ADDITIONAL STATE EXPORT IS FOR ALL FACILITIES OR
 ;IF SELECTED FACILITY WHETHER THAT FACILITY IS SELECTED FOR THIS
 ;PRIMARY EXPORT OR ADDITIONAL STATE EXPORT
 I BYIMDUZ=STATE,'$O(^BYIMPARA(BYIMDUZ,8,0))!$D(^BYIMPARA(BYIMDUZ,8,Y)) S Z=1
 I BYIMDUZ'=STATE,'$O(^BYIMPARA(BYIMDUZ,3,STATE,8,0))!$D(^BYIMPARA(BYIMDUZ,3,STATE,8,Y)) S Z=1
 Q Z
 ;=====
 ;
IMZIS ;EP;
 S ZTRTN="HFSARES^BYIMIMM"
 S ZTDESC="IMMUNIZATION INTERFACE"
 S ZTIO=""
 S ZTSAVE("BYIMJOB")=""
 S ZTDTC=$H
 D ^%ZTLOAD
 Q
 ;=====
 ;
CLEAN ;EP;CLEAN OUT MESSAGES WITH NO RXA SEGMENT, BLANK RXR AND OBX SEGMENTS
 N DEST,QUIT,X,Y,Z,XX,YY,ZZ
 S DEST=+$$VDEST^BYIMIMM()
 Q:'DEST
 S X=""
 F  S X=$O(^INLHDEST(DEST,X)) Q:'X  D
 .S Y=""
 .F  S Y=$O(^INLHDEST(DEST,X,Y)) Q:Y=""  D
 ..S Z=0
 ..F  S Z=$O(^INLHDEST(DEST,X,Y,Z)) Q:'Z  D
 ...S QUIT=0
 ...S YY=0
 ...F  S YY=$O(^INTHU(Z,3,YY)) Q:'YY!QUIT  S XX=$G(^(YY,0)) D
 ....I XX["FHS|" S QUIT=1
 ....I XX["RXA|" S QUIT=1
 ....I XX["BTS|" S QUIT=1
 ...Q:QUIT
 ...K ^INLHDEST(DEST,X,Y,Z)
 Q
 ;=====
 ;
