AMH40P12 ; IHS/CMI/LAB - POST INIT BH 4.0 P12 ; 19 Sep 2018  4:15 PM
 ;;4.0;IHS BEHAVIORAL HEALTH;**12**;JUN 02, 2010;Build 46
 ;
ENV ;EP 
 F X="XPO1","XPZ1","XPZ2","XPI1" S XPDDIQ(X)=0
 I '$$INSTALLD("XU*8.0*1018") D SORRY(2)
 I '$$INSTALLD("DI*22.0*1018") D SORRY(2)
 I $E($$VERSION^XPDUTL("AMH"),1,3)'="4.0" D MES^XPDUTL($$CJ^XLFSTR("Version 4.0 of AMH is required.  Not installed.",80)) D SORRY(2) I 1
 E  D MES^XPDUTL($$CJ^XLFSTR("Requires AMH v4.0....Present.",80))
 I '$$INSTALLD("AMH*4.0*11") D SORRY(2)
 Q
 ;
PRE ;
 ;
 S AMHX=0 F  S AMHX=$O(^AMHTPCAD(AMHX)) Q:AMHX'=+AMHX  S DA=AMHX,DIK="^AMHTPCAD(" D ^DIK K DA,DIK
 S AMHX=0 F  S AMHX=$O(^AMHPCIN(AMHX)) Q:AMHX'=+AMHX  S DA=AMHX,DIK="^AMHPCIN(" D ^DIK K DA,DIK
 Q
 ;
POST ;EP
 ;add option to menu
 S X=$$ADD^XPDMENU("AMH M DATA ENTRY MENU","AMH INTAKE LIST","INTL",85)
 S X=$$ADD^XPDMENU("AMH MENU SCREENING REPORTS","AMH SDOH REPORTS","SOC",32)
 S X=$$ADD^XPDMENU("AMH MENU SCREENING REPORTS","AMHR DU SCREENING MENU","DRU",33)
 ;S X=$$ADD^XPDMENU("AMH MENU SCREENING REPORTS","AMHR AD SCREENING MENU","DRU",22)
 S X=$$ADD^XPDMENU("AMH MENU SCREENING REPORTS","AMHR TAPS SCREENING REPORT","TAPS",38)
 S X=$$ADD^XPDMENU("AMH MENU SCREENING REPORTS","AMHR TAPS POSITIVE SCREENING","TAPP",39)
 D INACTPC
 K DA,DR,DIE
 S DA=$O(^AMHPROB("B","F50.22",0))
 I DA S DR=".02///BULIMIA NERVOSA, MODERATE",DIE="^AMHPROB(" D ^DIE K DA,DIE,DR
 S DA=$O(^AMHPROB("B","F50.23",0))
 I DA S DR=".02///BULIMIA NERVOSA, SEVERE",DIE="^AMHPROB(" D ^DIE K DA,DIE,DR
 D ADDDSMV
 D BMXPO
 Q
 ;
ADDDSMV ;add all new dsm v codes
 D MES^XPDUTL($$CJ^XLFSTR("Adding codes.",IOM))
 S AMHX=0 F  S AMHX=$O(^AMHTPCAD(AMHX)) Q:AMHX'=+AMHX  D
DSM5 .;ADD DSM5 CODES
 .S AMHCODE=$P(^AMHTPCAD(AMHX,0),U,1)
 .Q:AMHCODE=""
 .S AMHNARR=$P(^AMHTPCAD(AMHX,0),U,2)
 .S AMHPC=$P(^AMHTPCAD(AMHX,0),U,3)
 .S AMHPCC=$O(^AMHPROBC("B",AMHPC,0))
 .I 'AMHPCC D MES^XPDUTL("PROBLEM CODE MISSING: "_AMHPC_" CODE "_AMHCODE_" NOT UPLOADED") Q
 .S AMHICD=$P(^AMHTPCAD(AMHX,0),U,17)
 .S AMHEHR=$P(^AMHTPCAD(AMHX,0),U,15)
 .S AMHNOBH=$P(^AMHTPCAD(AMHX,0),U,18)
 .S AMHCS=$P(^AMHTPCAD(AMHX,0),U,10)
 .;FIND EXISTING AND OVERLAY
 .K DIE,DA,DR
 .S DA=""
 .S AMHY=0 F  S AMHY=$O(^AMHPROB("B",AMHCODE,AMHY)) Q:AMHY'=+AMHY!(DA)  D
 ..Q:$$UP^XLFSTR($P(^AMHPROB(AMHY,0),U,2))'=$$UP^XLFSTR(AMHNARR)
 ..S DA=AMHY
 .I DA D EDITC Q
 .;ADD THEN EDIT
 .K DIC,DLAYGO,DIADD,DD,D0,DA
 .S DITC=1
 .S X=AMHCODE,DIC="^AMHPROB(",DLAYGO=9002012.2,DIADD=1,DIC(0)="EMQ"
 .S DIC("DR")=".02///"_AMHNARR_";.03////"_AMHPCC_";.17///"_AMHICD_";.1///"_AMHCS_";.15///"_AMHEHR_";.18///"_AMHNOBH_";.16////"_$P($G(^AMHTPCAD(AMHX,11)),U,1)
 .D FILE^DICN
 .I Y=-1 W !,"ERROR ON ",AMHX," ",AMHCODE," ",DIC("DR") K DA,DIC,DIADD,DLAYGO,DR,DD,D0,DO,DITC Q
 .K DA,DIC,DIADD,DLAYGO,DR,DD,D0,DO,DITC
 .D MES^XPDUTL("."_$P(^AMHPROB(+Y,0),U,1))
 .Q
 Q
EDITC ;
 S DIE="^AMHPROB(",DR=".02///"_AMHNARR_";.03////"_AMHPCC_";.17///"_AMHICD_";.1///"_AMHCS_";.15///"_AMHEHR_";.18///"_AMHNOBH_";.16////"_$P($G(^AMHTPCAD(AMHX,11)),U,1)
 D ^DIE
 I $D(Y) D MES^XPDUTL("DSM CODE FAILED UPDATING: "_AMHCODE) K DIE,DA,DR Q
 D MES^XPDUTL("."_$P(^AMHPROB(DA,0),U,1))
 K DIE,DA,DR
 Q
INACTPC ;
 D MES^XPDUTL($$CJ^XLFSTR("Inactivating codes.",IOM))
 S AMHX=0 F  S AMHX=$O(^AMHPCIN(AMHX)) Q:AMHX'=+AMHX  D
 .Q:$P(^AMHPCIN(AMHX,0),U,3)'=1
 .S AMHC=$P(^AMHPCIN(AMHX,0),U,1)
 .;loop through "B" on AMHPROB and flag all that are not already flagged
 .S AMHY=0 F  S AMHY=$O(^AMHPROB("B",AMHC,AMHY)) Q:AMHY'=+AMHY  D
 ..I '$D(^AMHPROB(AMHY,0)) Q
 ..Q:$P(^AMHPROB(AMHY,0),U,10)'=5  ;only inactivate DSM V codes
 ..Q:$P(^AMHPROB(AMHY,0),U,16)>3220930  ;don't inactvate newly added
 ..I $P(^AMHPCIN(AMHX,0),U,4)]"",$$UP^XLFSTR($P(^AMHPCIN(AMHX,0),U,4))'=$$UP^XLFSTR($P(^AMHPROB(AMHY,0),U,2)) Q  ;narratives must match
 ..S DA=AMHY,DIE="^AMHPROB(",DR=".13///1;.14////"_$P(^AMHPCIN(AMHX,0),U,5) D ^DIE K DA,DIE,DR
 ..D MES^XPDUTL("."_$P(^AMHPROB(AMHY,0),U,1)_" "_$P(^AMHPROB(AMHY,0),U,4))
 ..Q
 .Q
 Q
SETABU ;
 ;loop codes in ABUSE and set .19 field
 NEW AMHTEXT,AMHX,AMHC,AMHIEN
 S AMHTEXT="ABUSE" F AMHX=1:1 S AMHC=$P($T(@AMHTEXT+AMHX),";;",2) Q:AMHC=""  D
 .S AMHIEN=0 F  S AMHIEN=$O(^AMHPROB("B",AMHC,AMHIEN)) Q:AMHIEN'=+AMHIEN  D
 ..S DA=AMHIEN,DR=".19///1",DIE="^AMHPROB(" D ^DIE K DIE,DA,DR
 Q
 ;
BMXPO ;-- update the RPC file
 N AMHRPC
 S AMHRPC=$O(^DIC(19,"B","AMHGRPC",0))
 Q:'AMHRPC
 D CLEAN(AMHRPC)
 D GUIEP^BMXPO(.RETVAL,AMHRPC_"|AMH")
 Q
 ;
CLEAN(APP) ;-- clean out the RPC multiple first
 S DA(1)=APP
 S DIK="^DIC(19,"_DA(1)_","_"""RPC"""_","
 N AMHDA
 S AMHDA=0 F  S AMHDA=$O(^DIC(19,APP,"RPC",AMHDA)) Q:'AMHDA  D
 . S DA=AMHDA
 . D ^DIK
 K ^DIC(19,APP,"RPC","B")
 Q
 ; 
INSTALLD(AMHSTAL) ;EP - Determine if patch AMHSTAL was installed, where
 ; APCLSTAL is the name of the INSTALL.  E.g "AG*6.0*11".
 ;
 NEW AMHY,DIC,X,Y
 S X=$P(AMHSTAL,"*",1)
 S DIC="^DIC(9.4,",DIC(0)="FM",D="C"
 D IX^DIC
 I Y<1 D IMES Q 0
 S DIC=DIC_+Y_",22,",X=$P(AMHSTAL,"*",2)
 D ^DIC
 I Y<1 D IMES Q 0
 S DIC=DIC_+Y_",""PAH"",",X=$P(AMHSTAL,"*",3)
 D ^DIC
 S AMHY=Y
 D IMES
 Q $S(AMHY<1:0,1:1)
IMES ;
 D MES^XPDUTL($$CJ^XLFSTR("Patch """_AMHSTAL_""" is"_$S(Y<1:" *NOT*",1:"")_" Present.",IOM))
 Q
SORRY(X) ;
 KILL DIFQ
 I X=3 S XPDQUIT=2 Q
 S XPDQUIT=X
 W *7,!,$$CJ^XLFSTR("Sorry....FIX IT!",IOM)
 Q
ABUSE ;ABUSE CODES TO FLAG
 ;;42
 ;;42.1
 ;;42.11
 ;;42.2
 ;;42.3
 ;;42.4
 ;;43
 ;;43.1
 ;;43.2
 ;;43.3
 ;;44
 ;;44.1
 ;;44.2
 ;;44.3
 ;;44.4
 ;;995.5
 ;;995.53
 ;;995.54
 ;;995.81
 ;;V61.11
 ;;V61.21
 ;;T74.32XA
 ;;T74.32XD
 ;;T76.32XA
 ;;T76.32XD
 ;;T74.02XA
 ;;T74.02XD
 ;;T76.02XA
 ;;T76.02XD
 ;;T74.22XA
 ;;T74.22XD
 ;;T76.22XA
 ;;T76.22XD
 ;;T74.12XA
 ;;T74.12XD
 ;;T76.12XA
 ;;T76.12XD
 ;;T74.11XA
 ;;T74.11XD
 ;;T76.11XA
 ;;T76.11XD
 ;;T74.11XA
 ;;T74.11XD
 ;;T76.11XA
 ;;T76.11XD
 ;;T74.31XA
 ;;T74.31XD
 ;;T76.31XA
 ;;T76.31XD
 ;;T74.31XA
 ;;T74.31XD
 ;;T76.31XA
 ;;T76.31XD
 ;;T74.21XA
 ;;T74.21XD
 ;;T76.21XA
 ;;T76.21XD
 ;;T74.21XA
 ;;T74.21XD
 ;;T76.21XA
 ;;T76.21XD
 ;;T74.01XA
 ;;T74.01XD
 ;;T76.01XA
 ;;T76.01XD
 ;;Z62.810
 ;;Z62.810
 ;;Z91.410
 ;;Z91.410
 ;;Z62.812
 ;;Z62.811
 ;;Z91.411
 ;;Z91.412
 ;;Z69.010
 ;;Z69.020
 ;;Z69.010
 ;;Z69.020
 ;;Z69.010
 ;;Z60.020
 ;;Z69.010
 ;;Z69.020
 ;;Z69.11
 ;;Z69.81
 ;;Z69.11
 ;;Z69.11
 ;;Z69.81
 ;;
