AMHPCCL2 ; IHS/CMI/LAB - CONTINUATION OF AMHPCCL ; 19 Sep 2014  8:37 AM
 ;;4.0;IHS BEHAVIORAL HEALTH;**12**;JUN 02, 2010;Build 46
 ;
 ;
KILL ;
 K APCDALVR,APCDPAT,APCDLOC,APCDTYPE,APCDCAT,APCDCLN,APCDTPRO,APCDTPS,APCDTPOV,APCDTNQ,APCDTTOP,APCDTLOU,APCDTPRV,APCDTAT,APCDATMP,APCDAFLG,APCDAUTO,APCDANE,AUPNTALK,AMHPOVP,AMHICDP
 Q
MORE ;
SDOHF I $P($G(^AMHREC(AMHR,22)),U,3)]"" D
 .Q:$O(^AUTTEXAM("C",46,0))=""
 .S AMHRES=$$VAL^XBDIQ1(9002011,AMHR,2203) I AMHRES["NEG" S AMHRES="N"
 .S AMHP=$P(^AMHREC(AMHR,22),U,4),AMHCOM=$P($G(^AMHREC(AMHR,24)),U) ;,AMHCOM=$TR(AMHCOM,";",":")
 .I AMHRES["REFUSED"!(AMHRES["UNABLE") S AMHEXCDE=46 D REF K AMHEXCDE Q
 .D KILL S APCDALVR("APCDVSIT")=AMHVSIT
 .S APCDALVR("APCDATMP")="[APCDALVR 9000010.13 (ADD)]"
 .S APCDALVR("APCDTEX")=46
 .S APCDALVR("APCDPAT")=$P(AMHR0,U,8)
 .S APCDALVR("APCDTRES")=AMHRES
 .S APCDALVR("APCDTCOM")=AMHCOM
 .S APCDALVR("APCDTEPR")="" I AMHP S APCDALVR("APCDTEPR")="`"_AMHP
 .D ^APCDALVR
 .I $D(APCDALVR("APCDAFLG")) S AMHBN="VFILE",AMHVFILE="V EXAM" D @("E"_APCDALVR("APCDAFLG"))
 .Q
SDOHH I $P($G(^AMHREC(AMHR,22)),U,5)]"" D
 .Q:$O(^AUTTEXAM("C",47,0))=""
 .S AMHRES=$$VAL^XBDIQ1(9002011,AMHR,2205) I AMHRES["NEG" S AMHRES="N"
 .S AMHP=$P(^AMHREC(AMHR,22),U,6),AMHCOM=$P($G(^AMHREC(AMHR,25)),U) ;,AMHCOM=$TR(AMHCOM,";",":")
 .I AMHRES["REFUSED"!(AMHRES["UNABLE") S AMHEXCDE=47 D REF K AMHEXCDE Q
 .D KILL S APCDALVR("APCDVSIT")=AMHVSIT
 .S APCDALVR("APCDATMP")="[APCDALVR 9000010.13 (ADD)]"
 .S APCDALVR("APCDTEX")=47
 .S APCDALVR("APCDPAT")=$P(AMHR0,U,8)
 .S APCDALVR("APCDTRES")=AMHRES
 .S APCDALVR("APCDTCOM")=AMHCOM
 .S APCDALVR("APCDTEPR")="" I AMHP S APCDALVR("APCDTEPR")="`"_AMHP
 .D ^APCDALVR
 .Q
SDOHT ;
 I $P($G(^AMHREC(AMHR,22)),U,7)]"" D
 .Q:$O(^AUTTEXAM("C",48,0))=""
 .S AMHRES=$$VAL^XBDIQ1(9002011,AMHR,2207) I AMHRES["NEG" S AMHRES="N"
 .S AMHP=$P(^AMHREC(AMHR,22),U,8),AMHCOM=$P($G(^AMHREC(AMHR,26)),U) ;,AMHCOM=$TR(AMHCOM,";",":")
 .I AMHRES["REFUSED"!(AMHRES["UNABLE") S AMHEXCDE=48 D REF K AMHEXCDE Q
 .D KILL S APCDALVR("APCDVSIT")=AMHVSIT
 .S APCDALVR("APCDATMP")="[APCDALVR 9000010.13 (ADD)]"
 .S APCDALVR("APCDTEX")=48
 .S APCDALVR("APCDPAT")=$P(AMHR0,U,8)
 .S APCDALVR("APCDTRES")=AMHRES
 .S APCDALVR("APCDTCOM")=AMHCOM
 .S APCDALVR("APCDTEPR")="" I AMHP S APCDALVR("APCDTEPR")="`"_AMHP
 .D ^APCDALVR
 .Q
SDOHU ;
 I $P($G(^AMHREC(AMHR,22)),U,9)]"" D
 .Q:$O(^AUTTEXAM("C",49,0))=""
 .S AMHRES=$$VAL^XBDIQ1(9002011,AMHR,2209)
 .S AMHP=$P(^AMHREC(AMHR,22),U,10),AMHCOM=$P($G(^AMHREC(AMHR,27)),U) ;,AMHCOM=$TR(AMHCOM,";",":")
 .I AMHRES["REFUSED"!(AMHRES["UNABLE") S AMHEXCDE=49 D REF K AMHEXCDE Q
 .D KILL S APCDALVR("APCDVSIT")=AMHVSIT
 .S APCDALVR("APCDATMP")="[APCDALVR 9000010.13 (ADD)]"
 .S APCDALVR("APCDTEX")=49
 .S APCDALVR("APCDPAT")=$P(AMHR0,U,8)
 .S APCDALVR("APCDTRES")=AMHRES
 .S APCDALVR("APCDTCOM")=AMHCOM
 .S APCDALVR("APCDTEPR")="" I AMHP S APCDALVR("APCDTEPR")="`"_AMHP
 .D ^APCDALVR
 .Q
SDOHS ;
 I $P($G(^AMHREC(AMHR,22)),U,11)]"" D
 .Q:$O(^AUTTEXAM("C",50,0))=""
 .S AMHRES=$$VAL^XBDIQ1(9002011,AMHR,2211) I AMHRES["NEG" S AMHRES="N"
 .S AMHP=$P(^AMHREC(AMHR,22),U,12),AMHCOM=$P($G(^AMHREC(AMHR,28)),U) ;,AMHCOM=$TR(AMHCOM,";",":")
 .I AMHRES["REFUSED"!(AMHRES["UNABLE") S AMHEXCDE=50 D REF K AMHEXCDE Q
 .D KILL S APCDALVR("APCDVSIT")=AMHVSIT
 .S APCDALVR("APCDATMP")="[APCDALVR 9000010.13 (ADD)]"
 .S APCDALVR("APCDTEX")=50
 .S APCDALVR("APCDPAT")=$P(AMHR0,U,8)
 .S APCDALVR("APCDTRES")=AMHRES
 .S APCDALVR("APCDTCOM")=AMHCOM
 .S APCDALVR("APCDTEPR")="" I AMHP S APCDALVR("APCDTEPR")="`"_AMHP
 .D ^APCDALVR
 .Q
 Q
REF ;
 S X=$O(^AUTTREFT("B","EXAM",0))
 Q:X=""
 S AMHTIDI=$O(^AUTTEXAM("C",AMHEXCDE,0)) Q:AMHTIDI=""  S AMHTID=$P(^AUTTEXAM(AMHTIDI,0),U)
 K DIC,DLAYGO,DIADD
 S DIC(0)="L",DIC="^AUPNPREF(",DIC("DR")=".02////"_$P(AMHR0,U,8)_";.03////"_$P($P(AMHR0,U),".")_";.04////"_AMHTID_";.05////9999999.15;.06////"_AMHTIDI_";.07////"_$S($E(AMHRES)["UNABLE":"U",AMHRES["REFUSED":"R",1:"")_";1101///"_AMHCOM
 K DD,D0 D FILE^DICN
 I Y=-1 W !!,"Creating refusal failed...." H 2 D ^XBFMK K DIADD,DLAYGO Q
 D ^XBFMK
 K DIADD,DLAYGO
 Q
V2 S AMHERROR="inability to create visit" G LBULL
V3 S AMHERROR="invalid visit parameters (date, location etc.)" G LBULL
 ;
E1 S AMHERROR="incorrect template specification" G LBULL
E2 S AMHERROR="invalid values being passed to "_AMHVFILE G LBULL
E8 S AMHERROR="Provider specific link not complete in site file "_$$PPNAME^AMHUTIL(AMHR) G LBULL
 ;
LBULL ;
 K XMB
 S XMDUZ="BEHAVIORAL HEALTH"
 S XMB(1)=AMHR,XMB(2)=$P(^DPT($P(AMHR0,U,8),0),U)_" (DFN "_$P(AMHR0,U,8)_")",Y=$P(AMHR0,U) D DD^%DT S XMB(3)=Y,XMB(4)=AMHERROR,XMB(5)=$G(AMHVFILE),XMB="AMH PCC LINK FAIL "_AMHBN ;,AMHDUZ=DUZ,DUZ=.5
 D ^XMB K XMB,AMHERROR,AMHBN,AMHVFILE,XMDUZ
 Q
