AMHRSD1P ; IHS/CMI/LAB - list refusals ;
 ;;4.0;IHS BEHAVIORAL HEALTH;**12**;JUN 02, 2010;Build 46
 ;
 ;
PRINT ;EP - called from xbdbque
 D PRINT1
 D DONE
 Q
PRINT1 ;
 S AMHRPG=0 K AMHRQUIT
 K AMHRLSTP
 I '$D(^XTMP("AMHRSD1",AMHRJ,AMHRH)) D HEADER W !!,"No data to report.",! G DONE
 D HEADER
 S AMHRTOT=$$TOT
 W !,"Total Number of Patients screened",?40,$J($$COM(AMHRTOT,0),8)
 D RES
 Q:$$END
 ;tally food
 I AMHEXTYP=1!(AMHEXTYP=2) D  Q:$$END
 .S AMHS="FOOD" D TALLIES
 Q:$D(AMHRQUIT)
 I AMHEXTYP=1!(AMHEXTYP=3) D  Q:$$END
 .S AMHS="HOUSING" D TALLIES
 Q:$D(AMHRQUIT)
 I AMHEXTYP=1!(AMHEXTYP=4) D  Q:$$END
 .S AMHS="TRANSPORTATION" D TALLIES
 Q:$D(AMHRQUIT)
 I AMHEXTYP=1!(AMHEXTYP=5) D  Q:$$END
 .S AMHS="UTILITIES" D TALLIES
 Q:$D(AMHRQUIT)
 I AMHEXTYP=1!(AMHEXTYP=6) D  Q:$$END
 .S AMHS="INTERPERSONAL SAFETY" D TALLIES
 Q:$D(AMHRQUIT)
 Q
TALLIES ;
 Q:'$D(AMHRTALL)
 W !!!,$$CTR("SDOH "_AMHS_" SCREENING")
 S D=+$P($G(^XTMP("AMHRSD1",AMHRJ,AMHRH,AMHS)),U,1)
 I 'D W !!,$$CTR("No "_AMHS_" Screenings done."),! Q
 I $D(AMHRTALL(1)) S AMHLABEL="By Gender",AMHT="GENDER" D T1
 Q:$D(AMHRQUIT)
 I $D(AMHRTALL(2)) S AMHLABEL="By Age Grouping",AMHT="AGE" D T1
 Q:$D(AMHRQUIT)
 I $D(AMHRTALL(3)) S AMHLABEL="By Clinic",AMHT="CLINIC" D T1
 Q:$D(AMHRQUIT)
 I $D(AMHRTALL(5)) S AMHLABEL="By Ethnicity",AMHT="ETHNICITY" D T1
 Q:$D(AMHRQUIT)
 I $D(AMHRTALL(6)) S AMHLABEL="By Race",AMHT="RACE" D T1
 Q:$D(AMHRQUIT)
 I $D(AMHRTALL(7)) S AMHLABEL="By Patient Community",AMHT="COMMUNITY" D T1
 Q
RES ;
 F AMHS="FOOD","HOUSING","TRANSPORTATION","UTILITIES","INTERPERSONAL SAFETY" Q:$$END  D
 .I AMHS="FOOD",AMHEXTYP'=1,AMHEXTYP'=2 Q  ;no food
 .I AMHS="HOUSING",AMHEXTYP'=1,AMHEXTYP'=3 Q
 .I AMHS="TRANSPORTATION",AMHEXTYP'=1,AMHEXTYP'=4 Q
 .I AMHS="UTILITIES",AMHEXTYP'=1,AMHEXTYP'=5 Q
 .I AMHS="INTERPERSONAL SAFETY",AMHEXTYP'=1,AMHEXTYP'=6 Q
 .S AMHV=""
 .S AMHV=$G(^XTMP("AMHRSD1",AMHRJ,AMHRH,AMHS))
 .W !!,"SDOH Exam ",AMHS,?34,"Total number screened (denominator): ",$$COM($P(AMHV,U,1),0,8),!
 .I 'AMHV Q  ;no denominator so don't tally
 .W ?35,"#",?45,"%",!
 .W ?5,"POSITIVE",?35,$$COM(+$P(AMHV,U,2),0,8),?45,$$PER($P(AMHV,U,2),$P(AMHV,U,1)),!!
 .W ?5,"NEGATIVE",?35,$$COM(+$P(AMHV,U,3),0,8),?45,$$PER($P(AMHV,U,3),$P(AMHV,U,1)),!!
 .W ?5,"PATIENT REFUSED SCREENING",?35,$$COM(+$P(AMHV,U,4),0,8),?45,$$PER($P(AMHV,U,4),$P(AMHV,U,1)),!!
 .W ?5,"UNABLE TO SCREEN",?35,$$COM(+$P(AMHV,U,5),0,8),?45,$$PER($P(AMHV,U,5),$P(AMHV,U,1)),!!
 .W ?5,"REFERRAL NEEDED",?35,$$COM(+$P(AMHV,U,6),0,8),?45,$$PER($P(AMHV,U,6),$P(AMHV,U,1)),!!
 .Q
 Q
T1 ;
 ;S J=$L(AMHLABEL)
 ;W !!,?(38-J),AMHLABEL,!
 W !!,$$CTR(AMHLABEL),!
 S AMHX="" F  S AMHX=$O(^XTMP("AMHRSD1",AMHRJ,AMHRH,AMHS,AMHT,AMHX)) Q:AMHX=""!($D(AMHRQUIT))  D
 .Q:$$END
 .S V=^XTMP("AMHRSD1",AMHRJ,AMHRH,AMHS,AMHT,AMHX)
 .S D=+$P($G(^XTMP("AMHRSD1",AMHRJ,AMHRH,AMHS)),U,1)
 .S Y=$L(AMHX),Y=38-Y W !?Y,AMHX,?40,$J($$COM(V,0),8),?55,$$PER(V,D)
 .Q
 Q
AGE ;
 Q:'$D(AMHRTALL(3))
 ;TALLY BY age OF PATIENT
 K AMHRRES S X=0 F  S X=$O(^XTMP("AMHRSD1",AMHRJ,AMHRH,"PATS",X)) Q:X'=+X  D
 .S AMHRY=^XTMP("AMHRSD1",AMHRJ,AMHRH,"PATS",X)  ;S D=$O(^XTMP("AMHRSD1",AMHRJ,AMHRH,"PATS",X,""),-1) S AMHRY=^XTMP("AMHRSD1",AMHRJ,AMHRH,"PATS",X,D)
 .S R=$P(AMHRY,U,4) S AMHRRES(R)=$G(AMHRRES(R))+1
 W !
 W !,"                                By Age",!
 S AMHRX="" F  S AMHRX=$O(AMHRRES(AMHRX)) Q:AMHRX=""!($D(AMHRQUIT))  D
 .Q:$$END
 .S Y=$L(AMHRX_" yrs"),Y=38-Y W !?Y,AMHRX," yrs",?40,$J($$COM($G(AMHRRES(AMHRX)),0),8),?55,$$PER(AMHRRES(AMHRX),AMHRTOT) K AMHRRES(AMHRX)
 Q
PRVSC ;
 Q:'$D(AMHRTALL(4))
 ;TALLY BY PRIMARY provider OF service
 K AMHRRES S X=0 F  S X=$O(^XTMP("AMHRSD1",AMHRJ,AMHRH,"PATS",X)) Q:X'=+X  D
 .S AMHRY=^XTMP("AMHRSD1",AMHRJ,AMHRH,"PATS",X)  ;S D=$O(^XTMP("AMHRSD1",AMHRJ,AMHRH,"PATS",X,""),-1) S AMHRY=^XTMP("AMHRSD1",AMHRJ,AMHRH,"PATS",X,D)
 .S R=$P(AMHRY,U,5) S:R="" R="UNKNOWN" S AMHRRES(R)=$G(AMHRRES(R))+1
 W !
 W !,"              By Provider who screened",!
 S AMHRX="" F  S AMHRX=$O(AMHRRES(AMHRX)) Q:AMHRX=""!($D(AMHRQUIT))  D
 .Q:$$END
 .S Y=$L(AMHRX),Y=38-Y W !?Y,AMHRX,?40,$J($$COM($G(AMHRRES(AMHRX)),0),8),?55,$$PER(AMHRRES(AMHRX),AMHRTOT) K AMHRRES(AMHRX)
 Q
PRVV ;
 Q:'$D(AMHRTALL(7))
 K AMHRRES S X=0 F  S X=$O(^XTMP("AMHRSD1",AMHRJ,AMHRH,"PATS",X)) Q:X'=+X  D
 .S AMHRY=^XTMP("AMHRSD1",AMHRJ,AMHRH,"PATS",X)  ;S D=$O(^XTMP("AMHRSD1",AMHRJ,AMHRH,"PATS",X,""),-1) S AMHRY=^XTMP("AMHRSD1",AMHRJ,AMHRH,"PATS",X,D)
 .S R=$P(AMHRY,U,7) S:R="" R="UNKNOWN" S AMHRRES(R)=$G(AMHRRES(R))+1
 W !
 W !,"           By Primary Provider of Visit",!
 S AMHRX="" F  S AMHRX=$O(AMHRRES(AMHRX)) Q:AMHRX=""!($D(AMHRQUIT))  D
 .Q:$$END
 .S Y=$L(AMHRX),Y=38-Y W !?Y,AMHRX,?40,$J($$COM($G(AMHRRES(AMHRX)),0),8),?55,$$PER(AMHRRES(AMHRX),AMHRTOT) K AMHRRES(AMHRX)
 Q
DESPRV ;
 Q:'$D(AMHRTALL(11))
 K AMHRRES S X=0 F  S X=$O(^XTMP("AMHRSD1",AMHRJ,AMHRH,"PATS",X)) Q:X'=+X  D
 .S AMHRY=^XTMP("AMHRSD1",AMHRJ,AMHRH,"PATS",X)  ;S D=$O(^XTMP("AMHRSD1",AMHRJ,AMHRH,"PATS",X,""),-1) S AMHRY=^XTMP("AMHRSD1",AMHRJ,AMHRH,"PATS",X,D)
 .S R=$P(AMHRY,U,11) S:R="" R="UNKNOWN" S AMHRRES(R)=$G(AMHRRES(R))+1
 W !
 W !,"     By Designated Primary Care Provider",!
 S AMHRX="" F  S AMHRX=$O(AMHRRES(AMHRX)) Q:AMHRX=""!($D(AMHRQUIT))  D
 .Q:$$END
 .S Y=$L(AMHRX),Y=38-Y W !?Y,AMHRX,?40,$J($$COM($G(AMHRRES(AMHRX)),0),8),?55,$$PER(AMHRRES(AMHRX),AMHRTOT) K AMHRRES(AMHRX)
 Q
MH ;
 Q:'$D(AMHRTALL(8))
 K AMHRRES S X=0 F  S X=$O(^XTMP("AMHRSD1",AMHRJ,AMHRH,"PATS",X)) Q:X'=+X  D
 .S AMHRY=^XTMP("AMHRSD1",AMHRJ,AMHRH,"PATS",X)  ;S D=$O(^XTMP("AMHRSD1",AMHRJ,AMHRH,"PATS",X,""),-1) S AMHRY=^XTMP("AMHRSD1",AMHRJ,AMHRH,"PATS",X,D)
 .S R=$P(AMHRY,U,8) S:R="" R="UNKNOWN" S AMHRRES(R)=$G(AMHRRES(R))+1
 W !
 W !,"     By Designated Mental Health Provider",!
 S AMHRX="" F  S AMHRX=$O(AMHRRES(AMHRX)) Q:AMHRX=""!($D(AMHRQUIT))  D
 .Q:$$END
 .S Y=$L(AMHRX),Y=38-Y W !?Y,AMHRX,?40,$J($$COM($G(AMHRRES(AMHRX)),0),8),?55,$$PER(AMHRRES(AMHRX),AMHRTOT) K AMHRRES(AMHRX)
 Q
SS ;
 Q:'$D(AMHRTALL(9))
 K AMHRRES S X=0 F  S X=$O(^XTMP("AMHRSD1",AMHRJ,AMHRH,"PATS",X)) Q:X'=+X  D
 .S AMHRY=^XTMP("AMHRSD1",AMHRJ,AMHRH,"PATS",X)  ;S D=$O(^XTMP("AMHRSD1",AMHRJ,AMHRH,"PATS",X,""),-1) S AMHRY=^XTMP("AMHRSD1",AMHRJ,AMHRH,"PATS",X,D)
 .S R=$P(AMHRY,U,9) S:R="" R="UNKNOWN" S AMHRRES(R)=$G(AMHRRES(R))+1
 W !
 W !,"    By Designated Social Services Provider",!
 S AMHRX="" F  S AMHRX=$O(AMHRRES(AMHRX)) Q:AMHRX=""!($D(AMHRQUIT))  D
 .Q:$$END
 .S Y=$L(AMHRX),Y=38-Y W !?Y,AMHRX,?40,$J($$COM($G(AMHRRES(AMHRX)),0),8),?55,$$PER(AMHRRES(AMHRX),AMHRTOT) K AMHRRES(AMHRX)
 Q
CD ;
 Q:'$D(AMHRTALL(10))
 K AMHRRES S X=0 F  S X=$O(^XTMP("AMHRSD1",AMHRJ,AMHRH,"PATS",X)) Q:X'=+X  D
 .S AMHRY=^XTMP("AMHRSD1",AMHRJ,AMHRH,"PATS",X)  ;S D=$O(^XTMP("AMHRSD1",AMHRJ,AMHRH,"PATS",X,""),-1) S AMHRY=^XTMP("AMHRSD1",AMHRJ,AMHRH,"PATS",X,D)
 .S R=$P(AMHRY,U,10) S:R="" R="UNKNOWN" S AMHRRES(R)=$G(AMHRRES(R))+1
 W !
 W !,"     By Designated A/SA Provider",!
 S AMHRX="" F  S AMHRX=$O(AMHRRES(AMHRX)) Q:AMHRX=""!($D(AMHRQUIT))  D
 .Q:$$END
 .S Y=$L(AMHRX),Y=38-Y W !?Y,AMHRX,?40,$J($$COM($G(AMHRRES(AMHRX)),0),8),?55,$$PER(AMHRRES(AMHRX),AMHRTOT) K AMHRRES(AMHRX)
 Q
CLINIC ;
 Q:'$D(AMHRTALL(5))
 ;TALLY BY clinic
 K AMHRRES S X=0 F  S X=$O(^XTMP("AMHRSD1",AMHRJ,AMHRH,"PATS",X)) Q:X'=+X  D
 .S AMHRY=^XTMP("AMHRSD1",AMHRJ,AMHRH,"PATS",X)  ;S D=$O(^XTMP("AMHRSD1",AMHRJ,AMHRH,"PATS",X,""),-1) S AMHRY=^XTMP("AMHRSD1",AMHRJ,AMHRH,"PATS",X,D)
 .S R=$P(AMHRY,U,6) S:R="" R="UNKNOWN" S AMHRRES(R)=$G(AMHRRES(R))+1
 W !
 W !,"                              By Clinic",!
 S AMHRX="" F  S AMHRX=$O(AMHRRES(AMHRX)) Q:AMHRX=""!($D(AMHRQUIT))  D
 .Q:$$END
 .S Y=$L(AMHRX),Y=38-Y W !?Y,AMHRX,?40,$J($$COM($G(AMHRRES(AMHRX)),0),8),?55,$$PER(AMHRRES(AMHRX),AMHRTOT) K AMHRRES(AMHRX)
 Q
DATE ;
 Q:'$D(AMHRTALL(6))
 ;TALLY BY date OF service
 K ^TMP($J) S X=0 F  S X=$O(^XTMP("AMHRSD1",AMHRJ,AMHRH,"PATS",X)) Q:X'=+X  D
 .S AMHRY=^XTMP("AMHRSD1",AMHRJ,AMHRH,"PATS",X)  ;S D=$O(^XTMP("AMHRSD1",AMHRJ,AMHRH,"PATS",X,""),-1) S AMHRY=^XTMP("AMHRSD1",AMHRJ,AMHRH,"PATS",X,D)
 .S R=$P(AMHRY,U,1) S ^TMP($J,R)=$G(^TMP($J,R))+1
 W !
 W !,"                               By Date",!
 S AMHRX="" F  S AMHRX=$O(^TMP($J,AMHRX)) Q:AMHRX=""!($D(AMHRQUIT))  D
 .Q:$$END
 .S Y=$L($$FMTE^XLFDT(AMHRX)),Y=38-Y W !?Y,$$FMTE^XLFDT(AMHRX),?40,$J($$COM($G(^TMP($J,AMHRX)),0),8),?55,$$PER(^TMP($J,AMHRX),AMHRTOT) K ^TMP($J,AMHRX)
 Q
RACE ;
 Q:'$D(AMHRTALL(12))
 ;TALLY BY RACE
 K AMHRRES S X=0 F  S X=$O(^XTMP("AMHRSD1",AMHRJ,AMHRH,"PATS",X)) Q:X'=+X  D
 .S AMHRY=^XTMP("AMHRSD1",AMHRJ,AMHRH,"PATS",X)
 .S R=$P(AMHRY,U,25) S AMHRRES(R)=$G(AMHRRES(R))+1
 W !
 W !,"                            By Race",!
 S AMHRX="" F  S AMHRX=$O(AMHRRES(AMHRX)) Q:AMHRX=""!($D(AMHRQUIT))  D
 .Q:$$END
 .S Y=$L(AMHRX),Y=38-Y W !?Y,AMHRX,?40,$J($$COM($G(AMHRRES(AMHRX)),0),8),?55,$$PER(AMHRRES(AMHRX),AMHRTOT) K AMHRRES(AMHRX)
 .Q
 Q
ETHN ;
 Q:'$D(AMHRTALL(13))
 ;TALLY BY RACE
 K AMHRRES S X=0 F  S X=$O(^XTMP("AMHRSD1",AMHRJ,AMHRH,"PATS",X)) Q:X'=+X  D
 .S AMHRY=^XTMP("AMHRSD1",AMHRJ,AMHRH,"PATS",X)
 .S R=$P(AMHRY,U,26) S AMHRRES(R)=$G(AMHRRES(R))+1
 W !
 W !,"                            By Ethnicity",!
 S AMHRX="" F  S AMHRX=$O(AMHRRES(AMHRX)) Q:AMHRX=""!($D(AMHRQUIT))  D
 .Q:$$END
 .S Y=$L(AMHRX),Y=38-Y W !?Y,AMHRX,?40,$J($$COM($G(AMHRRES(AMHRX)),0),8),?55,$$PER(AMHRRES(AMHRX),AMHRTOT) K AMHRRES(AMHRX)
 .Q
 Q
 ;
PER(N,D) ;return % of n/d
 I 'D Q "0%"
 NEW Z
 S Z=N/D,Z=Z*100,Z=$J(Z,5,1)
 Q $$STRIP^XLFSTR(Z," ")_"%"
COM(X,X2,X3) ;
 D COMMA^%DTC
 Q $$STRIP^XLFSTR(X," ")
END() ;
 I $Y<(IOSL-3) Q 0
 D HEADER
 I $D(AMHRQUIT) Q 1
 Q 0
ENDL() ;
 I $Y<(IOSL-8) Q 0
 D HEADER
 I $D(AMHRQUIT) Q 1
 Q 0
TOT() ;
 NEW C,X
 S C=0
 S X=0 F  S X=$O(^XTMP("AMHRSD1",AMHRJ,AMHRH,"PATS",X)) Q:X'=+X  S C=C+1
 Q C
HEADER ;EP
 G:'AMHRPG HEADER1
 K DIR I $E(IOST)="C",IO=IO(0) W ! S DIR(0)="EO" D ^DIR K DIR I Y=0!(Y="^")!($D(DTOUT)) S AMHRQUIT="" Q
HEADER1 ;
 W:$D(IOF) @IOF S AMHRPG=AMHRPG+1
 W !?3,$P(^VA(200,DUZ,0),U,2),?35,$$FMTE^XLFDT(DT),?70,"Page ",AMHRPG,!
 W !,$$CTR("***  SDOH SCREENINGS PATIENT TALLY"_"  ***",80),!
 S X="Screening Dates: "_$$FMTE^XLFDT(AMHRBD)_" to "_$$FMTE^XLFDT(AMHRED) W $$CTR(X,80),!
 I AMHREXPC S X="This report includes data from the PCC Clinical database." W $$CTR(X,80),!
 I 'AMHREXPC S X="This report excludes data from the PCC Clinical database." W $$CTR(X,80),!
 W !,$TR($J("",80)," ","-")
 ;I '$G(AMHRLSTP) W !?46,"#",?53,"% of patients"
 Q
DONE ;
 K ^TMP($J)
 K ^XTMP("AMHRSD1",AMHRJ,AMHRH)
 D EOP
 Q
CTR(X,Y) ;EP - Center X in a field Y wide.
 Q $J("",$S($D(Y):Y,1:IOM)-$L(X)\2)_X
 ;----------
EOP ;EP - End of page.
 Q:$E(IOST)'="C"
 Q:IO'=IO(0)
 Q:$D(ZTQUEUED)!'(IOT="TRM")!$D(IO("S"))
 NEW DIR
 K DIRUT,DFOUT,DLOUT,DTOUT,DUOUT
 W !
 S DIR("A")="End of Report.  Press Enter",DIR(0)="E" D ^DIR
 Q
 ;----------
USR() ;EP - Return name of current user from ^VA(200.
 Q $S($G(DUZ):$S($D(^VA(200,DUZ,0)):$P(^(0),U),1:"UNKNOWN"),1:"DUZ UNDEFINED OR 0")
 ;----------
LOC() ;EP - Return location name from file 4 based on DUZ(2).
 Q $S($G(DUZ(2)):$S($D(^DIC(4,DUZ(2),0)):$P(^(0),U),1:"UNKNOWN"),1:"DUZ(2) UNDEFINED OR 0")
 ;----------
DT(D) ;EP
 I D="" Q ""
 Q $E(D,4,5)_"/"_$E(D,6,7)_"/"_$E(D,2,3)
 ;
