AMHRDU31 ; IHS/CMI/LAB - list ALCOHOL screenings ; 24 Apr 2023  3:00 PM
 ;;4.0;IHS BEHAVIORAL HEALTH;**6,11,12**;JUN 02, 2010;Build 46
 ;
 ;
PROC ;
 S AMHRCNT=0
 S AMHRH=$H,AMHRJ=$J
 K ^XTMP("AMHRDU3",AMHRJ,AMHRH)
 D XTMP^AMHUTIL("AMHRDU3","DRUG USE SCREENING REPORT")
 ;go through exam ALCOHOL, then through AUPNPREF for refusals
 S DFN=0 F  S DFN=$O(^AUPNPAT(DFN)) Q:DFN'=+DFN  D
 .Q:'$D(^DPT(DFN,0))
 .Q:$P(^DPT(DFN,0),U,19)  ;merged away
 .Q:'$$ALLOWP^AMHUTIL(DUZ,DFN)
 .Q:$$DEMO^AMHUTIL1(DFN,$G(AMHDEMO))
 .;I DUZ=6295 Q:DFN'=6266
 .I AMHRSEX'[$P(^DPT(DFN,0),U,2) Q  ;not right gender
 .D GETSCRNS
 .Q
 Q
GETSCRNS ;gather up all screens in ^XTMP("AMHRDU3",AMHRJ,AMHRH,"SCREENS",$$SORTV,DFN,DATE,TYPE,RESULT,BH/PCC)=""
 NEW SDATE,X,V,D,R,M,E
 S R=""
 S SDATE=9999999-$$FMADD^XLFDT(AMHRED,1),SDATE=SDATE_".9999"
 F  S SDATE=$O(^AMHREC("AE",DFN,SDATE)) Q:SDATE'=+SDATE!($P(SDATE,".")>(9999999-AMHRBD))  D
 .S AMHVSIT=0 F  S AMHVSIT=$O(^AMHREC("AE",DFN,SDATE,AMHVSIT)) Q:AMHVSIT'=+AMHVSIT  D
 ..Q:'$D(^AMHREC(AMHVSIT,0))
 ..Q:'$$ALLOWVI^AMHUTIL(DUZ,AMHVSIT)
 ..S AMHRDATE=$P($P(^AMHREC(AMHVSIT,0),U),".")
 ..S X=$$AGE^AUPNPAT(DFN,AMHRDATE)
 ..I $D(AMHRAGET),X>$P(AMHRAGET,"-",2) Q
 ..I $D(AMHRAGET),X<$P(AMHRAGET,"-",1) Q
 ..;clinic check
 ..I $D(AMHRCLNT) S X=$P(^AMHREC(AMHVSIT,0),U,25) Q:X=""  Q:'$D(AMHRCLNT(X))
 ..;S AMHRSORV="" D @AMHRSORT I AMHRSORV="" S AMHRSORV="UNKNOWN"
 ..;get measurements DAST-10
 ..S AMHVF=0 F  S AMHVF=$O(^AMHRMSR("AD",AMHVSIT,AMHVF)) Q:AMHVF'=+AMHVF  D
 ...S M=$$VAL^XBDIQ1(9002011.12,AMHVF,.01)
 ...I M="DA10" D
 ....S E=$P($G(^AMHRMSR(AMHVF,12)),U,4)
 ....S R=$$VAL^XBDIQ1(9002011.12,AMHVF,.04)
 ....S S=$S(R>1:"POSITIVE",1:"NEGATIVE")
 ....S ^XTMP("AMHRDU3",AMHRJ,AMHRH,"SCREENS",DFN,$P($$VALI^XBDIQ1(9002011,AMHVSIT,.01),"."),"DAST-10 (Score: "_R_")",S,"BH")=$$VAL^XBDIQ1(9002011.12,AMHVF,1204)_U_$$VAL^XBDIQ1(9002011,AMHVSIT,.25)_U_AMHRDATE_U_$$AGE^AUPNPAT(DFN,AMHRDATE)
 ..;get exam
 ..S E=$P($G(^AMHREC(AMHVSIT,22)),U,1)
 ..I E="" G BHHF
 ..S E=$P($G(^AMHREC(AMHVSIT,22)),U,4)
 ..S AMH1=$$VAL^XBDIQ1(9002011,AMHVSIT,2204)_U_$$VAL^XBDIQ1(9002011,AMHVSIT,.25)_U_AMHRDATE_U_$$AGE^AUPNPAT(DFN,AMHRDATE)
 ..S ^XTMP("AMHRDU3",AMHRJ,AMHRH,"SCREENS",DFN,$P($$VALI^XBDIQ1(9002011,AMHVSIT,.01),"."),"UNHEALTHY DRUG SCREEN EXAM",$$VAL^XBDIQ1(9002011,AMHVSIT,2201),"BH")=AMH1
BHHF ..;
 ..S AMHVF=0 F  S AMHVF=$O(^AMHRHF("AD",AMHVSIT,AMHVF)) Q:AMHVF'=+AMHVF  D
 ...;check screening provider
 ...S E=$P($G(^AMHRHF(AMHVF,12)),U,4)
 ...S M=$$VALI^XBDIQ1(9002011.08,AMHVF,.01)
 ...S AMH1=$$VAL^XBDIQ1(9002011,AMHVSIT,2204)_U_$$VAL^XBDIQ1(9002011,AMHVSIT,.25)_U_AMHRDATE_U_$$AGE^AUPNPAT(DFN,AMHRDATE)
 ...I $P(^AUTTHF($P(^AUTTHF(M,0),U,3),0),U,2)="C001" S ^XTMP("AMHRDU3",AMHRJ,AMHRH,"SCREENS",DFN,$P($$VALI^XBDIQ1(9002011,AMHVSIT,.01),"."),$$VAL^XBDIQ1(9002011.08,AMHVF,.01),$$PN(M),"BH")=AMH1 Q
 ...I $P(^AUTTHF($P(^AUTTHF(M,0),U,3),0),U,2)="C023" S ^XTMP("AMHRDU3",AMHRJ,AMHRH,"SCREENS",DFN,$P($$VALI^XBDIQ1(9002011,AMHVSIT,.01),"."),$$VAL^XBDIQ1(9002011.08,AMHVF,.01),$$PN(M),"BH")=AMH1 Q
 ...I $P(^AUTTHF($P(^AUTTHF(M,0),U,3),0),U,2)="C024" S ^XTMP("AMHRDU3",AMHRJ,AMHRH,"SCREENS",DFN,$P($$VALI^XBDIQ1(9002011,AMHVSIT,.01),"."),$$VAL^XBDIQ1(9002011.08,AMHVF,.01),$$PN(M),"BH")=AMH1 Q
 ...I $P(^AUTTHF($P(^AUTTHF(M,0),U,3),0),U,2)="C036" S ^XTMP("AMHRDU3",AMHRJ,AMHRH,"SCREENS",DFN,$P($$VALI^XBDIQ1(9002011,AMHVSIT,.01),"."),$$VAL^XBDIQ1(9002011.08,AMHVF,.01),$$PN(M),"BH")=AMH1 Q
 ...I $P(^AUTTHF($P(^AUTTHF(M,0),U,3),0),U,2)="C030" S ^XTMP("AMHRDU3",AMHRJ,AMHRH,"SCREENS",DFN,$P($$VALI^XBDIQ1(9002011,AMHVSIT,.01),"."),$$VAL^XBDIQ1(9002011.08,AMHVF,.01),$$PN(M),"BH")=AMH1 Q
 ...I $P(^AUTTHF($P(^AUTTHF(M,0),U,3),0),U,2)="C031" S ^XTMP("AMHRDU3",AMHRJ,AMHRH,"SCREENS",DFN,$P($$VALI^XBDIQ1(9002011,AMHVSIT,.01),"."),$$VAL^XBDIQ1(9002011.08,AMHVF,.01),$$PN(M),"BH")=AMH1 Q
 ...I $P(^AUTTHF($P(^AUTTHF(M,0),U,3),0),U,2)="C032" S ^XTMP("AMHRDU3",AMHRJ,AMHRH,"SCREENS",DFN,$P($$VALI^XBDIQ1(9002011,AMHVSIT,.01),"."),$$VAL^XBDIQ1(9002011.08,AMHVF,.01),$$PN(M),"BH")=AMH1 Q
 ...I $P(^AUTTHF($P(^AUTTHF(M,0),U,3),0),U,2)="C033" S ^XTMP("AMHRDU3",AMHRJ,AMHRH,"SCREENS",DFN,$P($$VALI^XBDIQ1(9002011,AMHVSIT,.01),"."),$$VAL^XBDIQ1(9002011.08,AMHVF,.01),$$PN(M),"BH")=AMH1 Q
 ...I $P(^AUTTHF($P(^AUTTHF(M,0),U,3),0),U,2)="C034" S ^XTMP("AMHRDU3",AMHRJ,AMHRH,"SCREENS",DFN,$P($$VALI^XBDIQ1(9002011,AMHVSIT,.01),"."),$$VAL^XBDIQ1(9002011.08,AMHVF,.01),$$PN(M),"BH")=AMH1 Q
 ..;dx Z02.83
 ..S AMHVF=0 F  S AMHVF=$O(^AMHRPRO("AD",AMHVSIT,AMHVF)) Q:AMHVF'=+AMHVF  D
 ...;check screening provider
 ...Q:$$VAL^XBDIQ1(9002011.01,AMHVF,.01)'="Z02.83"
 ...S ^XTMP("AMHRDU3",AMHRJ,AMHRH,"SCREENS",DFN,$P($$VALI^XBDIQ1(9002011,AMHVSIT,.01),"."),"DX: Z02.83","UNKNOWN","BH")="UNKNOWN"_U_$$VAL^XBDIQ1(9002011,AMHVSIT,.25)_U_AMHRDATE_U_$$AGE^AUPNPAT(DFN,AMHRDATE)
 ;now get pcc if they want PCC
 I 'AMHREXPC Q
PCC ;
 NEW R,V,AMHRDATE,SDATE
 S R=""
 S SDATE=9999999-$$FMADD^XLFDT(AMHRED,1),SDATE=SDATE_".9999"
 F  S SDATE=$O(^AUPNVSIT("AA",DFN,SDATE)) Q:SDATE'=+SDATE!($P(SDATE,".")>(9999999-AMHRBD))  D
 .S AMHVSIT=0 F  S AMHVSIT=$O(^AUPNVSIT("AA",DFN,SDATE,AMHVSIT)) Q:AMHVSIT'=+AMHVSIT  D
 ..Q:'$D(^AUPNVSIT(AMHVSIT,0))
 ..Q:$D(^AMHREC("AVISIT",AMHVSIT))  ;this visit is in BH so we already counted it and it's screenings
 ..Q:'$$ALLOWPCC^AMHUTIL(DUZ,AMHVSIT)
 ..S AMHRDATE=$P($P(^AUPNVSIT(AMHVSIT,0),U),".")
 ..Q:'$$ALLOWP^AMHUTIL(DUZ,DFN)
 ..S X=$$AGE^AUPNPAT(DFN,AMHRDATE)
 ..I $D(AMHRAGET),X>$P(AMHRAGET,"-",2) Q
 ..I $D(AMHRAGET),X<$P(AMHRAGET,"-",1) Q
 ..;clinic check
 ..I $D(AMHRCLNT) S X=$P(^AUPNVSIT(AMHVSIT,0),U,8) Q:X=""  Q:'$D(AMHRCLNT(X))
 ..;DAST-10
 ..S AMHVF=0 F  S AMHVF=$O(^AUPNVMSR("AD",AMHVSIT,AMHVF)) Q:AMHVF'=+AMHVF  D
 ...S M=$$VAL^XBDIQ1(9000010.01,AMHVF,.01) Q:M'="DA10"
 ...;check screening provider
 ...S E=$P($G(^AUPNVMSR(AMHVF,12)),U,4)
 ...S R=$$VAL^XBDIQ1(9000010.01,AMHVF,.04)
 ...S S=$S(R>1:"POSITIVE",1:"NEGATIVE")
 ...S D=AMHRDATE,T="DAST-10 (Score: "_R_")"
 ...I '$D(^XTMP("AMHRDU3",AMHRJ,AMHRH,"SCREENS",DFN,D,T,S)) S ^XTMP("AMHRDU3",AMHRJ,AMHRH,"SCREENS",DFN,D,T,S,"PCC")=$$VAL^XBDIQ1(9000010.01,AMHVF,1204)_U_$$VAL^XBDIQ1(9000010,AMHVSIT,.08)_U_AMHRDATE_U_$$AGE^AUPNPAT(DFN,AMHRDATE)
 ..;EXAM 45
 ..S AMHVF=0 F  S AMHVF=$O(^AUPNVXAM("AD",AMHVSIT,AMHVF)) Q:AMHVF'=+AMHVF  D
 ...S M=$$VALI^XBDIQ1(9000010.13,AMHVF,.01) S C=$P($G(^AUTTEXAM(M,0)),U,2) Q:C'=45
 ...;check screening provider
 ...S E=$P($G(^AUPNVXAM(AMHVF,12)),U,4)
 ...S D=AMHRDATE,T=$$VAL^XBDIQ1(9000010.13,AMHVF,.01),R=$$VAL^XBDIQ1(9000010.13,AMHVF,.04) I R="NORMAL/NEGATIVE" S R="NEGATIVE"
 ...I '$D(^XTMP("AMHRDU3",AMHRJ,AMHRH,"SCREENS",DFN,D,T,R)) S ^XTMP("AMHRDU3",AMHRJ,AMHRH,"SCREENS",DFN,D,T,R,"PCC")=$$VAL^XBDIQ1(9000010.13,AMHVF,1204)_U_$$VAL^XBDIQ1(9000010,AMHVSIT,.08)_U_AMHRDATE_U_$$AGE^AUPNPAT(DFN,AMHRDATE)
 ..;HEATLH FACTORS
 ..S AMHVF=0 F  S AMHVF=$O(^AUPNVHF("AD",AMHVSIT,AMHVF)) Q:AMHVF'=+AMHVF  D
 ...S M=$$VALI^XBDIQ1(9000010.23,AMHVF,.01)
 ...Q:'M
 ...S F=$$VALI^XBDIQ1(9999999.64,M,.02)  ;factor code
 ...S C=$$VALI^XBDIQ1(9999999.64,M,.03)
 ...S C=$$VAL^XBDIQ1(9999999.64,C,.02)  ;category of code
 ...I C'="C001",C'="C023",C'="C024",C'="C036",C'="C030",C'="C031",C'="C032",C'="C033",C'="C034" Q  ;not correct category
 ...;check screening provider
 ...S E=$P($G(^AUPNVHF(AMHVF,12)),U,4)
 ...S D=AMHRDATE,T=$$VAL^XBDIQ1(9000010.23,AMHVF,.01),R=$$PN(M)
 ...I '$D(^XTMP("AMHRDU3",AMHRJ,AMHRH,"SCREENS",DFN,D,T,R)) S ^XTMP("AMHRDU3",AMHRJ,AMHRH,"SCREENS",DFN,D,T,R,"PCC")=$$VAL^XBDIQ1(9000010.23,AMHVF,1204)_U_$$VAL^XBDIQ1(9000010,AMHVSIT,.08)_U_AMHRDATE_U_$$AGE^AUPNPAT(DFN,AMHRDATE)
 ..;POV
 ..S AMHVF=0 F  S AMHVF=$O(^AUPNVPOV("AD",AMHVSIT,AMHVF)) Q:AMHVF'=+AMHVF  D
 ...;check screening provider
 ...Q:$$VAL^XBDIQ1(9000010.07,AMHVF,.01)'="Z02.83"
 ...S D=AMHRDATE,T="Z02.83",R="UNKNOWN"
 ...I '$D(^XTMP("AMHRDU3",AMHRJ,AMHRH,"SCREENS",DFN,D,T,R)) S ^XTMP("AMHRDU3",AMHRJ,AMHRH,"SCREENS",DFN,D,T,R,"PCC")="UNKNOWN"_U_$$VAL^XBDIQ1(9000010,AMHVSIT,.08)_U_AMHRDATE_U_$$AGE^AUPNPAT(DFN,AMHRDATE)
 ;refusal of 45 in pcc
 S AMHREFS="" I AMHREXPC S AMHREFS=$$REFUSAL(DFN,9999999.15,$O(^AUTTEXAM("C",45,0)),AMHRBD,AMHRED)
 Q:AMHREFS=""
 S D=$P(AMHREFS,U),T="UNHEALTHY DRUG SCREEN EXAM",R=$P(AMHREFS,U,2)
 I '$D(^XTMP("AMHRDU3",AMHRJ,AMHRH,"SCREENS",DFN,D,T,R)) S ^XTMP("AMHRDU3",AMHRJ,AMHRH,"SCREENS",DFN,D,T,R,"PCC")=$P(AMHREFS,U,5)_U_U_D_U_$$AGE^AUPNPAT(DFN,D)
 ;:$D(^XTMP("AMHRDU3",AMHRJ,AMHRH,"SCREENS",DFN)) ^XTMP("AMHRDU3",AMHRJ,AMHRH,"PATS",DFN)=""
 Q
PN(X) ;is this health factor positive or negative
 I '$G(X) Q "UNKNOWN"
 NEW H
 S H=$P($G(^AUTTHF(X,0)),U,2)  ;CODE
 I H="" Q "UNKNOWN"
 I H="F019" Q "POSITIVE"
 I H="F020" Q "POSITIVE"
 I H="F021" Q "POSITIVE"
 I H="F022" Q "POSITIVE"
 I H="F211" Q "POSITIVE"
 I H="F212" Q "POSITIVE"
 I H="F213" Q "POSITIVE"
 I H="F214" Q "POSITIVE"
 I H="F145" Q "POSITIVE"
 I H="F146" Q "POSITIVE"
 I H="F147" Q "POSITIVE"
 I H="F148" Q "POSITIVE"
 I H="F154" Q "POSITIVE"
 ;CANNABIS
 I H="F186" Q "POSITIVE"
 I H="F187" Q "POSITIVE"
 I H="F189" Q "POSITIVE"
 ;sedative
 I H="F181" Q "POSITIVE"
 I H="F182" Q "POSITIVE"
 I H="F184" Q "POSITIVE"
 ;sTIMULANT
 I H="F191" Q "POSITIVE"
 I H="F192" Q "POSITIVE"
 I H="F194" Q "POSITIVE"
 ;OPIOID
 I H="F196" Q "POSITIVE"
 I H="F197" Q "POSITIVE"
 I H="F199" Q "POSITIVE"
 ;HEROIN
 I H="F201" Q "POSITIVE"
 I H="F202" Q "POSITIVE"
 I H="F204" Q "POSITIVE"
 Q "NEGATIVE"
REFUSAL(PAT,F,I,B,E) ;EP
 I '$G(PAT) Q ""
 I '$G(F) Q ""
 I '$G(I) Q ""
 I $G(B)="" Q ""
 I $G(E)="" Q ""
 NEW T,X,Y,%DT S X=B,%DT="P" D ^%DT S B=Y
 S X=E,%DT="P" D ^%DT S E=Y
 S (X,T)="" F  S X=$O(^AUPNPREF("AA",PAT,F,I,X)) Q:X'=+X!(T]"")  S Y=0 F  S Y=$O(^AUPNPREF("AA",PAT,F,I,X,Y)) Q:Y'=+Y  S D=$P(^AUPNPREF(Y,0),U,3) I D'<B&(D'>E) D
 .S T=D
 .S R=$$VALI^XBDIQ1(9000022,Y,.07)
 .I R'="R",R'="U" Q
 .S $P(T,U,2)=$S(R="R":"PATIENT REFUSED SCREENING",1:"UNABLE TO SCREEN")
 .S $P(T,U,3)=$P(^DPT(PAT,0),U,2)
 .S $P(T,U,4)=$$AGE^AUPNPAT(PAT,D)
 .S $P(T,U,5)=$$VAL^XBDIQ1(9000022,Y,1204) I $P(T,U,5)="" S $P(T,U,5)="UNKNOWN"
 .S $P(T,U,6)="UNKNOWN"
 .S $P(T,U,7)="UNKNOWN"
 .S $P(T,U,8)=$$VAL^XBDIQ1(9002011.55,PAT,.02)
 .S $P(T,U,9)=$$VAL^XBDIQ1(9002011.55,PAT,.03)
 .S $P(T,U,10)=$$VAL^XBDIQ1(9002011.55,PAT,.04)
 .S $P(T,U,11)=$$VAL^XBDIQ1(9000001,PAT,.14)
 Q T
SCRNPCC(T) ;get screening provider based on v file
 NEW S,F
 S F=1202
 I $P(T,U,5)=9000010.16!($P(T,U,5)=9000010.23) S F=".05"
 S S=$$VAL^XBDIQ1($P(T,U,5),$P(T,U,6),F)
 I S]"" Q S
 Q "UNKNOWN"
BHPPIN(R) ;
 NEW %,%1
 S %=0,%1="" F  S %=$O(^AMHRPROV("AD",AMHVSIT,%)) Q:%'=+%  I $P(^AMHRPROV(%,0),U,4)="P" S %1=$P(^AMHRPROV(%,0),U)
 Q %1
BHPPNAME(R) ;EP primary provider internal # from 200
 NEW %,%1
 S %=0,%1="" F  S %=$O(^AMHRPROV("AD",R,%)) Q:%'=+%  I $P(^AMHRPROV(%,0),U,4)="P" S %1=$P(^AMHRPROV(%,0),U),%1=$P($G(^VA(200,%1,0)),U)
 I %1]"" Q %1
 Q "UNKNOWN"
SPRV(E) ;
 I $P($G(^AUPNVXAM(E,12)),U,4) Q $$VAL^XBDIQ1(9000010.13,E,1204)
 Q "UNKNOWN"
PRVREF(R) ;
 I $P($G(^AUPNPREF(R,12)),U,4)]"" Q $$VAL^XBDIQ1(9000022,R,1204)
 Q "UNKNOWN"
PPV(V) ;
 NEW %
 S %=$$PRIMPROV^APCLV(V,"N")
 I %]"" Q %
 Q "UNKNOWN"
CTR(X,Y) ;EP - Center X in a field Y wide.
 Q $J("",$S($D(Y):Y,1:IOM)-$L(X)\2)_X
 ;----------
EOP ;EP - End of page.
 Q:$E(IOST)'="C"
 Q:IO'=IO(0)
 Q:$D(ZTQUEUED)!'(IOT="TRM")!$D(IO("S"))
 NEW DIR
 K DIRUT,DFOUT,DLOUT,DTOUT,DUOUT
 W !
 S DIR("A")="End of Report.  Press Enter",DIR(0)="E" D ^DIR
 Q
 ;----------
USR() ;EP - Return name of current user from ^VA(200.
 Q $S($G(DUZ):$S($D(^VA(200,DUZ,0)):$P(^(0),U),1:"UNKNOWN"),1:"DUZ UNDEFINED OR 0")
 ;----------
LOC() ;EP - Return location name from file 4 based on DUZ(2).
 Q $S($G(DUZ(2)):$S($D(^DIC(4,DUZ(2),0)):$P(^(0),U),1:"UNKNOWN"),1:"DUZ(2) UNDEFINED OR 0")
 ;----------
H ;
 S AMHRSORV=$$HRN^AUPNPAT(DFN,DUZ(2))
 Q
N ;
 S AMHRSORV=$P(^DPT(DFN,0),U)
 Q
P ;
 S AMHRSORV=$P(AMHRY,U,5)
 Q
R ;
 S AMHRSORV=$P($P(AMHRY,U,2),";")_"  "_$P($P(AMHRY,U,2),";",2)
 Q
D ;
 S AMHRSORV=$P(AMHRY,U,1)
 Q
A S AMHRSORV=$P(AMHRY,U,4)
 Q
G ;
 S AMHRSORV=$P(AMHRY,U,3)
 Q
C ;
 S AMHRSORV=$P(AMHRY,U,6)
 Q
T ;
 S %=$$HRN^AUPNPAT(DFN,DUZ(2))
 S %=%+10000000,%=$E(%,7,8)_"-"_+$E(%,2,8)
 S AMHRSORV=%
 Q
Q ;
 S AMHRSORV=$$RACE^AMHUTIL2(DFN)
 Q
E ;
 S AMHRSORV=$$ETHN^AMHUTIL2(DFN)
 Q
