AMHRTAPD ; IHS/CMI/LAB - list TAPSS SCREENING ; 01 Oct 2024  11:07 AM
 ;;4.0;IHS BEHAVIORAL HEALTH;**12**;JUN 02, 2010;Build 46
 ;
 ;
INFORM ;
 W !,$$CTR($$USR)
 W !,$$CTR($$LOC())
 W !,$$CTR("TOBACCO, ALCOHOL, PRESCRIPTION MEDICATION, AND OTHER SUBSTANCES (TAPS)",80)
 W !,$$CTR("TALLY AND LISTING OF PATIENTS SCREENED FOR ALCOHOL AND DRUG USE W/RESULTS",80)
 W !,$$CTR("AND POSITIVE RESULT TALLLIES FOR EACH SUBSTANCE",80)
 W !!,"This report will tally and optionally list all patients who have had TAPS "
 W !,"screening documented in the time frame specified by the user.  TAPS Screening "
 W !,"is defined as ALL 8 of the following documented on the SAME DATE:"
 W !?5,"- TAPS-ALCOHOL"
 W !?5,"- TAPS-CANNABIS"
 W !?5,"- TAPS-HEROIN"
 W !?5,"- TAPS-OPIOID"
 W !?5,"- TAPS-OTHER SUBSTANCES"
 W !?5,"- TAPS-SEDATIVE"
 W !?5,"- TAPS-STIMULANT"
 W !?5,"- TAPS-TOBACCO"
 D PAUSE^AMHLEA
 W !!,"This report will tally the patients by age groups, gender, clinic, race, "
 W !,"and result of the screen."
 W !,"- If a patient had all 8 screenings more than once in the time period, only the"
 W !,"- latest date where all 8 TAPS health factores were documented is used in this "
 W !,"  report."
 W !,"- All TAPS health factors results must be completed."
 W !!,"- This report will optionally, look at both PCC and the Behavioral Health"
 W !,"   databases, for evidence of screening."
 W !,"- A positive screening result is defined as Problem Use, High Risk, and "
 W !,"  In Early Remission for each specific substance."
 W !
 D PAUSE^AMHLEA,DBHUSR^AMHUTIL
 D XIT
 ;
DATES K AMHRED,AMHRBD
 W !,"Please enter the date range during which the screening was done.",!,"To get all screenings ever put in a long date range like 01/01/1980 ",!,"to the present date.",!
 K DIR W ! S DIR(0)="DO^::EXP",DIR("A")="Enter Beginning Date for Screening"
 D ^DIR
 I $D(DIRUT) D XIT Q
 S AMHRBD=Y
 K DIR S DIR(0)="DO^:DT:EXP",DIR("A")="Enter Ending Date for Screening"
 D ^DIR
 G:$D(DIRUT) DATES
 S AMHRED=Y
 ;
 I AMHRED<AMHRBD D  G DATES
 . W !!,$C(7),"Sorry, Ending Date MUST not be earlier than Beginning Date."
AGEGRP ;GET AGE GROUPS
 W !!
 D SETBIN
BIN ;
 W !,"Below are the age categories for this report:",! D LIST
 S DIR(0)="YO",DIR("A")="Do you wish to modify these Patient age ranges",DIR("B")="NO" D ^DIR K DIR
 I $D(DIRUT) G DATES
 I Y=0 G NEXT
RUN ;
 K AMHQUIT S AMHRY="",AMHRA=-1 W ! F  D AGE Q:AMHRX=""  I $D(AMHQUIT) G BIN
 D CLOSE I $D(AMHQUIT) G BIN
 D LIST
 G BIN
 ;
AGE ;
 S AMHRX=""
 S DIR(0)="NO^0:150:0",DIR("A")="Enter the starting age of the "_$S(AMHRY="":"first",1:"next")_" age group" D ^DIR K DIR S:$D(DUOUT) DIRUT=1
 I $D(DUOUT)!($D(DTOUT)) S AMHQUIT="" Q
 S AMHRX=Y
 I Y="" Q
 I AMHRX?1.3N,AMHRX>AMHRA D SET Q
 W $C(7) W !,"Make sure the age is higher the beginning age of the previous group.",! G RUN
 ;
SET S AMHRA=AMHRX
 I AMHRY="" S AMHRY=AMHRX Q
 S AMHRY=AMHRY_"-"_(AMHRX-1)_";"_AMHRX
 Q
 ;
CLOSE I AMHRY="" Q
GC ;
 S DIR(0)="NO^0:150:0",DIR("A")="Enter the highest age for the last group" D ^DIR K DIR S:$D(DUOUT) DIRUT=1
 I $D(DUOUT)!($D(DTOUT)) S AMHQUIT="" Q
 S AMHRX=Y I Y="" S AMHRX=199
 I AMHRX?1.3N,AMHRX'<AMHRA S AMHRY=AMHRY_"-"_AMHRX,AMHRBIN=AMHRY Q
 W "  ??",$C(7) G CLOSE
 Q
 ;
LIST ;
 S %=AMHRBIN
 F I=1:1 S X=$P(%,";",I) Q:X=""  W !,$P(X,"-")," - ",$P(X,"-",2)
 W !
 Q
 ;
SETBIN ;
 S AMHRBIN="0-12;13-17;18-64;65-125"
 Q
NEXT ;
 K AMHRPLST
 K AMHRBINA
 I '$D(AMHRBIN) D SETBIN
 F I=1:1 S J=$P(AMHRBIN,";",I) Q:J=""  S AMHRBINA(J)=$P(J,"-",1)_U_$P(J,"-",2)
PLIST ;
 K AMHRPLST
 K DIR
 S DIR(0)="S^1:Those with a Positive Screening in any substance;2:Those with a Positive Screening in a specific substance;0:No Lists"
 S DIR("A")="Patient Lists",DIR("B")="0" KILL DA D ^DIR KILL DIR
 I $D(DIRUT) G BIN
 S AMHRES=Y
 I 'AMHRES G EXCL
 I AMHRES=1 F X=1:1:8 S AMHRPLST(X)=""
 I AMHRES=1 G SORT
PLIST1 ;
 K AMHRPLST
 S DIR(0)="S^1:Tobacco;2:Alcohol;3:Sedative;4:Cannabis;5:Stimulant;6:Opioid;7:Heroin;8:Other Substance",DIR("A")="Which Substance would you like to include" KILL DA D ^DIR KILL DIR
 I $D(DIRUT) G PLIST
 S AMHRPLST(Y)=""
SORT ;
 S AMHRSORT=""
 W !
 S DIR(0)="S^H:Health Record Number;N:Patient Name;C:Clinic;D:Date Screened;A:Age of Patient at Screening;T:Terminal Digit HRN"
 S DIR("A")="How would you like the list to be sorted",DIR("B")="H"
 KILL DA D ^DIR KILL DIR
 I $D(DIRUT) G LIST
 S AMHRSORT=Y
EXCL ; ;
PCC ;
 S AMHREXPC=""
 W !!,"Would you like to include TAPS assessments documented in the PCC clinical"
 ;W !,""
 S DIR(0)="Y",DIR("A")="database",DIR("B")="Y" KILL DA D ^DIR KILL DIR
 I $D(DIRUT) G NEXT
 S AMHREXPC=Y
 ;
DEMO ;
 D DEMOCHK^AMHUTIL1(.AMHDEMO)
 I AMHDEMO=-1 G EXCL
ZIS ;CALL TO XBDBQUE
 S DIR(0)="S^P:PRINT Output;B:BROWSE Output on Screen",DIR("A")="Do you wish to ",DIR("B")="P" K DA D ^DIR K DIR
 I $D(DIRUT) G XIT
 I $G(Y)="B" D BROWSE,XIT Q
 S XBRP="PRINT^AMHRTAPP",XBRC="PROC^AMHRTAPD",XBRX="XIT^AMHRTAPD",XBNS="AMH"
 D ^XBDBQUE
 D XIT
 Q
BROWSE ;
 S XBRP="VIEWR^XBLM(""^AMHRTAPP"")"
 S XBNS="AMH",XBRC="PROC^AMHRTAPD",XBRX="XIT^AMHRTAPD",XBIOP=0 D ^XBDBQUE
 Q
XIT ;
 D EN^XBVK("AMHR")
 D ^XBFMK
 Q
PROC ;
 S AMHRCNT=0
 S AMHRH=$H,AMHRJ=$J
 K ^XTMP("AMHRTAPD",AMHRJ,AMHRH)
 D XTMP^AMHUTIL("AMHRTAPD","TAPS SCREENING REPORT")
 ;now go through each patient
 K AMHHF,AMHGEND,AMHAGE,AMHCLN,AMHRACE,AMHETHN,AMHTOB,AMHALC,AMHSED,AMHCANNA,AMHSTIM,AMHOPI,AMHHERO,AMHOTHS
 S (AMHPTOT,AMHTOPO)=0
 F X=1:1:8 S AMHTOPO(X)=0
 F X="UNDETERMINED RISK","MINIMAL USE","PROBLEM USE","HIGH RISK","IN EARLY REMISSION" S (AMHTOB(X),AMHALC(X),AMHSED(X),AMHCANNA(X),AMHOPI(X),AMHHERO(X),AMHOTHS(X),AMHSTIM(X))=0
 S AMHPAT=0 F  S AMHPAT=$O(^AUPNPAT(AMHPAT)) Q:AMHPAT'=+AMHPAT  D
 .Q:'$$ALLOWP^AMHUTIL(DUZ,AMHPAT)  ;allowed to see this patient?
 .Q:$$DEMO^AMHUTIL1(AMHPAT,$G(AMHDEMO))
 .;GET EACH OF THE 8 SCREENS AND PUT IN ^XTMP
 .D GATHER
 Q
GATHER ;
 K AMHHF
 S AMHSDATE=9999999-$$FMADD^XLFDT(AMHRED,1),AMHSDATE=AMHSDATE_".9999"
 F  S AMHSDATE=$O(^AMHREC("AE",AMHPAT,AMHSDATE)) Q:AMHSDATE'=+AMHSDATE!($P(AMHSDATE,".")>(9999999-AMHRBD))  D
 .S AMHVSIT=0 F  S AMHVSIT=$O(^AMHREC("AE",AMHPAT,AMHSDATE,AMHVSIT)) Q:AMHVSIT'=+AMHVSIT  D
 ..Q:'$D(^AMHREC(AMHVSIT,0))
 ..Q:'$$ALLOWVI^AMHUTIL(DUZ,AMHVSIT)
 ..;HEALTH FACTORS TAPS
 ..S X=0 F  S X=$O(^AMHRHF("AD",AMHVSIT,X)) Q:X'=+X  D
 ...S M=$$VALI^XBDIQ1(9002011.08,X,.01) D
 ...I $P(^AUTTHF($P(^AUTTHF(M,0),U,3),0),U,2)="C028" S AMHHF($P(AMHSDATE,"."),1)=$$BHRT(AMHVSIT,$$VAL^XBDIQ1(9002011.08,X,.01),AMHPAT,$$VALI^XBDIQ1(9002011.08,X,.01)) Q
 ...I $P(^AUTTHF($P(^AUTTHF(M,0),U,3),0),U,2)="C029" S AMHHF($P(AMHSDATE,"."),2)=$$BHRT(AMHVSIT,$$VAL^XBDIQ1(9002011.08,X,.01),AMHPAT,$$VALI^XBDIQ1(9002011.08,X,.01)) Q
 ...I $P(^AUTTHF($P(^AUTTHF(M,0),U,3),0),U,2)="C030" S AMHHF($P(AMHSDATE,"."),3)=$$BHRT(AMHVSIT,$$VAL^XBDIQ1(9002011.08,X,.01),AMHPAT,$$VALI^XBDIQ1(9002011.08,X,.01)) Q
 ...I $P(^AUTTHF($P(^AUTTHF(M,0),U,3),0),U,2)="C031" S AMHHF($P(AMHSDATE,"."),4)=$$BHRT(AMHVSIT,$$VAL^XBDIQ1(9002011.08,X,.01),AMHPAT,$$VALI^XBDIQ1(9002011.08,X,.01)) Q
 ...I $P(^AUTTHF($P(^AUTTHF(M,0),U,3),0),U,2)="C032" S AMHHF($P(AMHSDATE,"."),5)=$$BHRT(AMHVSIT,$$VAL^XBDIQ1(9002011.08,X,.01),AMHPAT,$$VALI^XBDIQ1(9002011.08,X,.01)) Q
 ...I $P(^AUTTHF($P(^AUTTHF(M,0),U,3),0),U,2)="C033" S AMHHF($P(AMHSDATE,"."),6)=$$BHRT(AMHVSIT,$$VAL^XBDIQ1(9002011.08,X,.01),AMHPAT,$$VALI^XBDIQ1(9002011.08,X,.01)) Q
 ...I $P(^AUTTHF($P(^AUTTHF(M,0),U,3),0),U,2)="C034" S AMHHF($P(AMHSDATE,"."),7)=$$BHRT(AMHVSIT,$$VAL^XBDIQ1(9002011.08,X,.01),AMHPAT,$$VALI^XBDIQ1(9002011.08,X,.01)) Q
 ...I $P(^AUTTHF($P(^AUTTHF(M,0),U,3),0),U,2)="C035" S AMHHF($P(AMHSDATE,"."),8)=$$BHRT(AMHVSIT,$$VAL^XBDIQ1(9002011.08,X,.01),AMHPAT,$$VALI^XBDIQ1(9002011.08,X,.01)) Q
 ;PCC??
 I 'AMHREXPC G CHECK
 ;
 S AMHSDATE=9999999-$$FMADD^XLFDT(AMHRED,1),AMHSDATE=AMHSDATE_".9999"
 F  S AMHSDATE=$O(^AUPNVSIT("AA",AMHPAT,AMHSDATE)) Q:AMHSDATE'=+AMHSDATE!($P(AMHSDATE,".")>(9999999-AMHRBD))  D
 .S AMHVSIT=0 F  S AMHVSIT=$O(^AUPNVSIT("AA",AMHPAT,AMHSDATE,AMHVSIT)) Q:AMHVSIT'=+AMHVSIT  D
 ..Q:'$D(^AUPNVSIT(AMHVSIT,0))
 ..Q:'$$ALLOWPCC^AMHUTIL(DUZ,AMHVSIT)
 ..S AMHRDATE=$P($P(^AUPNVSIT(AMHVSIT,0),U),".")
 ..Q:'$$ALLOWP^AMHUTIL(DUZ,AMHPAT)
 ..Q:$D(^AMHREC("AVISIT",AMHVSIT))  ;visit is in BH - already counted
 ..S X=0 F  S X=$O(^AUPNVHF("AD",AMHVSIT,X)) Q:X'=+X  D
 ...S M=$$VALI^XBDIQ1(9000010.23,X,.01)
 ...I $P(^AUTTHF($P(^AUTTHF(M,0),U,3),0),U,2)="C028" S AMHHF($P(AMHSDATE,"."),1)=$$PCRT(AMHVSIT,$$VAL^XBDIQ1(9000010.23,X,.01),AMHPAT,$$VALI^XBDIQ1(9000010.23,X,.01)) Q
 ...I $P(^AUTTHF($P(^AUTTHF(M,0),U,3),0),U,2)="C029" S AMHHF($P(AMHSDATE,"."),2)=$$PCRT(AMHVSIT,$$VAL^XBDIQ1(9000010.23,X,.01),AMHPAT,$$VALI^XBDIQ1(9000010.23,X,.01)) Q
 ...I $P(^AUTTHF($P(^AUTTHF(M,0),U,3),0),U,2)="C030" S AMHHF($P(AMHSDATE,"."),3)=$$PCRT(AMHVSIT,$$VAL^XBDIQ1(9000010.23,X,.01),AMHPAT,$$VALI^XBDIQ1(9000010.23,X,.01)) Q
 ...I $P(^AUTTHF($P(^AUTTHF(M,0),U,3),0),U,2)="C031" S AMHHF($P(AMHSDATE,"."),4)=$$PCRT(AMHVSIT,$$VAL^XBDIQ1(9000010.23,X,.01),AMHPAT,$$VALI^XBDIQ1(9000010.23,X,.01)) Q
 ...I $P(^AUTTHF($P(^AUTTHF(M,0),U,3),0),U,2)="C032" S AMHHF($P(AMHSDATE,"."),5)=$$PCRT(AMHVSIT,$$VAL^XBDIQ1(9000010.23,X,.01),AMHPAT,$$VALI^XBDIQ1(9000010.23,X,.01)) Q
 ...I $P(^AUTTHF($P(^AUTTHF(M,0),U,3),0),U,2)="C033" S AMHHF($P(AMHSDATE,"."),6)=$$PCRT(AMHVSIT,$$VAL^XBDIQ1(9000010.23,X,.01),AMHPAT,$$VALI^XBDIQ1(9000010.23,X,.01)) Q
 ...I $P(^AUTTHF($P(^AUTTHF(M,0),U,3),0),U,2)="C034" S AMHHF($P(AMHSDATE,"."),7)=$$PCRT(AMHVSIT,$$VAL^XBDIQ1(9000010.23,X,.01),AMHPAT,$$VALI^XBDIQ1(9000010.23,X,.01)) Q
 ...I $P(^AUTTHF($P(^AUTTHF(M,0),U,3),0),U,2)="C035" S AMHHF($P(AMHSDATE,"."),8)=$$PCRT(AMHVSIT,$$VAL^XBDIQ1(9000010.23,X,.01),AMHPAT,$$VALI^XBDIQ1(9000010.23,X,.01)) Q
 ;DOES THIS PATIENT HAVE ALL 8 ON ANY DATE?
CHECK ;check for all 8 on any one date
 S AMHGOT=""
 S D=0,C=0 F  S D=$O(AMHHF(D)) Q:D'=+D!(AMHGOT)  D
 .S X=0 F  S X=$O(AMHHF(D,X)) Q:X'=+X  S C=C+1
 .I C'=8 Q
 .S AMHGOT=D
 I 'AMHGOT Q
 S AMHPTOT=AMHPTOT+1
TALLIES ;
 ;now all tallies
 ;GENDER
 S AMHNMPO=0
 S X=0 F  S X=$O(AMHHF(AMHGOT,X)) Q:X'=+X  D
 .S AMHGOTP=0
 .I X=1 D
 ..S G=$P(AMHHF(AMHGOT,X),U,2),AMHGEND(G)=$G(AMHGEND(G))+1
 ..S G=$P(AMHHF(AMHGOT,X),U,3),AMHAGE(G)=$G(AMHAGE(G))+1
 ..S G=$P(AMHHF(AMHGOT,X),U,4),AMHCLN(G)=$G(AMHCLN(G))+1
 ..S G=$P(AMHHF(AMHGOT,X),U,5),AMHRACE(G)=$G(AMHRACE(G))+1
 ..S G=$P(AMHHF(AMHGOT,X),U,6),AMHETHN(G)=$G(AMHETHN(G))+1
 .S G=$P($P(AMHHF(AMHGOT,X),U,1),"-",2)
 .I G="PROBLEM USE " S G="PROBLEM USE"
 .I G="EARLY REMISSION, BUT AT RISK" S G="IN EARLY REMISSION"
 .I X=1 S AMHTOB(G)=$G(AMHTOB(G))+1
 .I X=2 S AMHALC(G)=$G(AMHALC(G))+1
 .I X=3 S AMHSED(G)=$G(AMHSED(G))+1
 .I X=4 S AMHCANNA(G)=$G(AMHCANNA(G))+1
 .I X=5 S AMHSTIM(G)=$G(AMHSTIM(G))+1
 .I X=6 S AMHOPI(G)=$G(AMHOPI(G))+1
 .I X=7 S AMHHERO(G)=$G(AMHHERO(G))+1
 .I X=8 S AMHOTHS(G)=$G(AMHITHS(G))+1
 .S R=$P(AMHHF(AMHGOT,X),U,7)
 .I R="POSITIVE" S AMHGOTP=1
 .I R="POSITIVE",$D(AMHRPLST(X)) D
 ..S AMHSORV="" D @AMHRSORT S:AMHRSORV="" AMHRSORV="??" S ^XTMP("AMHRTAPD",AMHRJ,AMHRH,"LIST",AMHRSORV,AMHPAT,$P(AMHHF(AMHGOT,X),U,1))=AMHHF(AMHGOT,X)
 .I AMHGOTP,'AMHNMPO S AMHTOPO=AMHTOPO+1,AMHNMPO=1
 .I AMHGOTP S AMHTOPO(X)=AMHTOPO(X)+1
 Q
 ;
 ;
GETAGE(A) ;
 NEW R,L,H,I
 S R=""
 S I="" F  S I=$O(AMHRBINA(I)) Q:I=""!(R]"")  D
 .S L=$P(AMHRBINA(I),U,1)
 .S H=$P(AMHRBINA(I),U,2)
 .I A'<L,A'>H S R=I
 I R="" Q "???"
 Q R
 ;
BHRT(V,HF,PAT,HFIEN) ;EP
 NEW T,D,A
 S T=""
 S D=$P($P(^AMHREC(V,0),U),".")
 S $P(T,U,8)=D
 S $P(T,U,1)=HF
 S $P(T,U,2)=$$VAL^XBDIQ1(2,PAT,.02)
 S A=$$GETAGE($$AGE^AUPNPAT(PAT,D))
 S $P(T,U,3)=A
 S $P(T,U,4)=$$VAL^XBDIQ1(9002011,V,.25) I $P(T,U,3)="" S $P(T,U,3)="???"
 S $P(T,U,5)=$$RACE^AMHUTIL2(PAT)
 S $P(T,U,6)=$$ETHN^AMHUTIL2(PAT)
 S $P(T,U,7)=$$PN($P(^AUTTHF(HFIEN,0),U,2))
 Q T
PN(H) ;
 ;ALCOHOL
 I H="F176" Q "POSITIVE"
 I H="F177" Q "POSITIVE"
 I H="F179" Q "POSITIVE"
 ;OTHER
 I H="F206" Q "POSITIVE"
 I H="F207" Q "POSITIVE"
 I H="F209" Q "POSITIVE"
 ;TOBACCO
 I H="F171" Q "POSITIVE"
 I H="F172" Q "POSITIVE"
 I H="F174" Q "POSITIVE"
 ;CANNABIS
 I H="F186" Q "POSITIVE"
 I H="F187" Q "POSITIVE"
 I H="F189" Q "POSITIVE"
 ;sedative
 I H="F181" Q "POSITIVE"
 I H="F182" Q "POSITIVE"
 I H="F184" Q "POSITIVE"
 ;sTIMULANT
 I H="F191" Q "POSITIVE"
 I H="F192" Q "POSITIVE"
 I H="F194" Q "POSITIVE"
 ;OPIOID
 I H="F196" Q "POSITIVE"
 I H="F197" Q "POSITIVE"
 I H="F199" Q "POSITIVE"
 ;HEROIN
 I H="F201" Q "POSITIVE"
 I H="F202" Q "POSITIVE"
 I H="F204" Q "POSITIVE"
 Q "NEGATIVE"
 ;
 ;
PCRT(V,HF,PAT,HFIEN) ;EP
 NEW T,D,A
 S T=""
 S D=$$VD^APCLV(V)
 S $P(T,U,8)=D
 S $P(T,U,1)=HF
 S $P(T,U,2)=$$VAL^XBDIQ1(2,PAT,.02)
 S A=$$GETAGE($$AGE^AUPNPAT(PAT,D))
 S $P(T,U,3)=A
 S $P(T,U,4)=$$VAL^XBDIQ1(9000010,V,.08) I $P(T,U,3)="" S $P(T,U,3)="???"
 S $P(T,U,5)=$$RACE^AMHUTIL2(PAT)
 S $P(T,U,6)=$$ETHN^AMHUTIL2(PAT)
 S $P(T,U,7)=$$PN($P(^AUTTHF(HFIEN,0),U,2))
 Q T
CLINIC(V) ;
 NEW Y
 S Y=$$CLINIC^APCLV(V,"E")
 I Y]"" Q Y
 Q "UNKNOWN"
CTR(X,Y) ;EP - Center X in a field Y wide.
 Q $J("",$S($D(Y):Y,1:IOM)-$L(X)\2)_X
 ;----------
EOP ;EP - End of page.
 Q:$E(IOST)'="C"
 Q:IO'=IO(0)
 Q:$D(ZTQUEUED)!'(IOT="TRM")!$D(IO("S"))
 NEW DIR
 K DIRUT,DFOUT,DLOUT,DTOUT,DUOUT
 W !
 S DIR("A")="End of Report.  Press Enter",DIR(0)="E" D ^DIR
 Q
 ;----------
USR() ;EP - Return name of current user from ^VA(200.
 Q $S($G(DUZ):$S($D(^VA(200,DUZ,0)):$P(^(0),U),1:"UNKNOWN"),1:"DUZ UNDEFINED OR 0")
 ;----------
LOC() ;EP - Return location name from file 4 based on DUZ(2).
 Q $S($G(DUZ(2)):$S($D(^DIC(4,DUZ(2),0)):$P(^(0),U),1:"UNKNOWN"),1:"DUZ(2) UNDEFINED OR 0")
H ;
 S AMHRSORV=$$HRN^AUPNPAT(AMHPAT,DUZ(2))
 Q
N ;
 S AMHRSORV=$P(^DPT(AMHPAT,0),U)
 Q
D ;
 S %=9999999-D
 S AMHRSORV=%
 Q
A S D=$P(AMHHF(AMHGOT,X),U,8)
 S AMHRSORV=$$AGE^AUPNPAT(AMHPAT,D)
 Q
C ;
 S AMHRSORV=$P(AMHHF(AMHGOT,X),U,4)
 Q
T ;
 S %=$$HRN^AUPNPAT(AMHPAT,DUZ(2))
 S %=%+10000000,%=$E(%,7,8)_"-"_+$E(%,2,8)
 S AMHRSORV=%
 Q
