APSPESC2 ;IHS/MSC/PLS - SureScripts HL7 interface  ;05-May-2021 14:08;DU
 ;;7.0;IHS PHARMACY MODIFICATIONS;**1024,1026,1027,1028**;Sep 23, 2004;Build 50
 ;====================================================================
 Q
 ; EP - Change request callback
 ;Build response to Change Request
DENYCHG(RR,MSGTXT) ; Build the deny change response
 N DATA,HLMSGIEN,HLMSTATE,ARY,SEG,ACT,HLECH,HLFS
 N PARMS,ACK,ERR,I,FLG,LP,LOG,DNYC,DNYR,DFN,ACTUSR
 S ACT=$$GET1^DIQ(9009033.91,RR,.08,"I")
 S ACTUSR=$$GET1^DIQ(9009033.91,RR,.09,"I")
 S DFN=$$GET1^DIQ(9009033.91,RR,1.2,"I")
 S OCC="UX"
 S HLMSGIEN=$$GET1^DIQ(9009033.91,RR,.05)  ; Message ID
 ; TODO- Add logic to use the HL7 message text in the RR entry if HL7 message has been purged.
 Q:'HLMSGIEN
 S PARMS("ACK CODE")="AA"
 S PARMS("MESSAGE TYPE")="RRE"
 S PARMS("EVENT")="O12"
 S PARMS("VERSION")=2.5
 S PARMS("ACCEPT ACK TYPE")="AL"
 I $L($G(MSGTXT)) D
 .;IHS/GDIT/MSC/MGH EPCS trim spaces
 .S MSGTXT=$$TRIM^XLFSTR(MSGTXT)
 .I $L($P(MSGTXT,"-",2)) S DNYC=$P(MSGTXT,"-",1),MSGTXT=$$TRIM^XLFSTR($P(MSGTXT,"-",2,10))
 .E  S DNYC="ZZ"
 I $L($G(MSGTXT))=0 S MSGTXT="Change not appropriate"
 S MSGTXT=$G(MSGTXT,"Change not appropriate")
 D PARSE^APSPES2(.DATA,HLMSGIEN,.HLMSTATE)
 K FDA,ERR
 S:+$$GET1^DIQ(9009033.91,RR,.08,"I")'=3 FDA(9009033.91,RR_",",.02)="@"  ; Remove order ien
 I $$GET1^DIQ(9009033.91,RR,.03,"I")'=8 S FDA(9009033.91,RR_",",.03)=$S($G(STA):STA,1:3)  ; Set status to processed-denied
 S FDA(9009033.91,RR_",",.07)=$$NOW^XLFDT()
 S FDA(9009033.91,RR_",",4)=$G(DNYC)_"-"_$G(MSGTXT)
 I ACTUSR="" S FDA(9009033.91,RR_",",.09)=DUZ
 D FILE^DIE(,"FDA","ERR")
 K FDA,ERR
 ;IHS/GDIT/MSC/MGH EPCS QUIT IF NO MESSAGE
 I HLMSTATE("ID")="" D UPTRRACT^APSPES3(RR,$G(ERR,"Message no longer exists in HLO file.  Cannot process."))
 Q:HLMSTATE("ID")=""
 S HLFS=$G(DATA("HDR","FIELD SEPARATOR"))
 S HLECH=HLMSTATE("HDR","ENCODING CHARACTERS")
 I $$ACK^HLOAPI2(.HLMSTATE,.PARMS,.ACK,.ERR) D
 .D SETACK
 .I '$$SENDACK^HLOAPI2(.ACK,.ERR) D UPTRRACT^APSPES3(RR,$G(ERR,"There was a problem sending the HL7 message."))
 E  D UPTRRACT^APSPES3(RR,$G(ERR,"There was a problem generating the HL7 message."))
 ; Get original order prescription IEN
 S RXIEN=+$$GET1^DIQ(9009033.91,RR,.06,"I")
 I 'RXIEN D
 .N SEGIEN,SEGORC
 .D PARSE^APSPES2(.DATA,HLMSGIEN,.HLMSTATE)
 .S SEGIEN=$$FSEGIEN^APSPES1(.DATA,"ORC")
 .I SEGIEN D
 ..M SEGORC=DATA(SEGIEN)
 ..S RXIEN=$$GET^HLOPRS(.SEGORC,2,1)
 ; Update activity log
 I RXIEN D
 .N LOG,RET,ACT,LACT
 .S LOG("REASON")="X"
 .S LOG("RX REF")=0
 .S LACT=$$LASTACT^APSPFNC6(RXIEN,"X")
 .S ACT=$S(LACT="F":"X",1:"T")
 .S ARY("TYPE")=ACT
 .S LOG("COM")="eRx denial change response sent to "_$$PHMINFO^APSPES2A(RXIEN)
 .D UPTLOG^APSPFNC2(.RET,RXIEN,0,.LOG)
 I '$D(DUPDENY) D CHKDUP^APSPES11(RR)
 Q
SETACK ;Get original message to include in ack
 N PRV,ACT,NM,LP,VAL,INST,MRN,DFN,CHGTYP,NTEDATA,ZDUDATA,ZCSDATA
 ;Get PID information as for a new order
 S DFN=$$GET1^DIQ(9009033.91,RR,1.2,"I")
 S CHGTYP=$$GET1^DIQ(9009033.91,RR,7.4)
 D PREPARY^APSPES1(.DATA,"PID",.ARY)
 S SEG=$$ADDSEG^HLOAPI(.ACK,.ARY)
 ;D PID^APSPES1(DFN)
 D PREPARY^APSPES1(.DATA,"ORC",.ARY)
 D SET^APSPES2(.ARY,OCC,1)  ; Order Control Code
 D SET^APSPES2(.ARY,$$HLDATE^HLFNC($$NOW^XLFDT()),9)  ; Written Date/Time
 I OCC="UX" D
 .D SET^APSPES2(.ARY,DNYC,16,1)  ; Order Control Code Reason Identifier
 .D SET^APSPES2(.ARY,$E(MSGTXT,1,70),16,2)  ; Order Control Code Reason Text
 .D SET^APSPES2(.ARY,"NCPDP1131",16,3)  ; Order Control Code Reason System
 D SET^APSPES2(.ARY,$$GET1^DIQ(4,+$G(DUZ(2)),.01),21)  ; Institution Name
 S PRV=$$GET1^DIQ(9009033.91,RR,1.3,"I")
 S ACT=$$GET1^DIQ(9009033.91,RR,.09,"I")
 I +PRV'=+ACT D
 .D SET^APSPES2(.ARY,ACT,19,1)
 .S NM=$$HLNAME^HLFNC($$GET1^DIQ(200,ACT,.01),HLECH)
 .F LP=1:1:$L(NM,$E(HLECH)) S VAL=$P(NM,$E(HLECH),LP) D
 ..D SET^APSPES2(.ARY,VAL,19,LP+1)  ; Acting provider
 S SEG=$$ADDSEG^HLOAPI(.ACK,.ARY)
 D PREPARY^APSPES1(.DATA,"RXE",.ARY)
 D SET^APSPES2(.ARY,CHGTYP,31,1)   ;Type of change request
 S SEG=$$ADDSEG^HLOAPI(.ACK,.ARY)
 D PREPARY^APSPES1(.DATA,"ZCS",.ARY)
 S ZCSDATA=$$GETVAL^APSPES2(HLMSGIEN,"ZCS",1,1) ;ZCS segment data
 I ZCSDATA'="" S SEG=$$ADDSEG^HLOAPI(.ACK,.ARY)
 S LP=0
 S FLG=0 F I=1:1 D  Q:FLG
 .S LP=$$FSEGIEN^APSPES1(.DATA,"DG1",LP)
 .I LP=0 S FLG=1 Q
 .D PREPARY^APSPES1(.DATA,"DG1",.ARY,LP-1)
 .S SEG=$$ADDSEG^HLOAPI(.ACK,.ARY)
 S LP=0
 S FLG=0 F I=1:1 D  Q:FLG
 .S LP=$$FSEGIEN^APSPES1(.DATA,"AL1",LP)
 .I LP=0 S FLG=1 Q
 .D PREPARY^APSPES1(.DATA,"AL1",.ARY,LP-1)
 .S SEG=$$ADDSEG^HLOAPI(.ACK,.ARY)
 S LP=0
 S FLG=0 F I=1:1 D  Q:FLG
 .S LP=$$FSEGIEN^APSPES1(.DATA,"OBX",LP)
 .I LP=0 S FLG=1 Q
 .D PREPARY^APSPES1(.DATA,"OBX",.ARY,LP-1)
 .S SEG=$$ADDSEG^HLOAPI(.ACK,.ARY)
 S LP=0
 S FLG=0 F I=1:1 D  Q:FLG
 .S LP=$$FSEGIEN^APSPES1(.DATA,"ZMR",LP)
 .I LP=0 S FLG=1 Q
 .D PREPARY^APSPES1(.DATA,"ZMR",.ARY,LP-1)
 .S SEG=$$ADDSEG^HLOAPI(.ACK,.ARY)
 I CHGTYP="U" D
 .D PREPARY^APSPES1(.DATA,"ZSF",.ARY)
 .S SEG=$$ADDSEG^HLOAPI(.ACK,.ARY)
 D PREPARY^APSPES1(.DATA,"ZDU",.ARY)
 S ZDUDATA=$$GETVAL^APSPES2(HLMSGIEN,"ZDU",1,1) ;ZDU segment data
 I ZDUDATA'="" S SEG=$$ADDSEG^HLOAPI(.ACK,.ARY)
 D PREPARY^APSPES1(.DATA,"NTE",.ARY)
 S NTEDATA=$$GETVAL^APSPES2(HLMSGIEN,"NTE",3,1) ;NTE segment data
 I NTEDATA'="" S SEG=$$ADDSEG^HLOAPI(.ACK,.ARY)
 Q
 ; Send accept,accept w/change or replace message
 ; Input:  ORID - ^OR(100 IEN
ACCCHG(RXIEN,ORID,MSGTXT) ;
 N RR,DATA,HLMSGIEN,HLMSTATE,ARY,SEG,SEGIEN,SEGRXO,DFN,PROV,RELATES
 N PARMS,HLST,ERR,PRN,REF,REFILLS,I,FLG,LP,DISP,OCC,ACT,CHGTYP,NTEDATA,ZDUDATA
 N RX0,RX2,HLFS,HLECH,SSNUM,RRPRV,COMMENTS,CHG,LOC,ORDER,SAVRXIEN
 S SAVRXIEN=RXIEN
 S REFILLS=$$GET1^DIQ(52,RXIEN,9,"I")
 S DFN=$$GET1^DIQ(52,RXIEN,2,"I")
 S RX0=^PSRX(RXIEN,0)
 S PROV=$P(RX0,U,4)
 S LOC=$P(RX0,U,5)
 S RX2=^PSRX(RXIEN,2)
 S DISP=REFILLS    ; Number of refills
 S COMMENTS=$$GETPRC^APSPES1()
 S RR=$$VALUE^ORCSAVE2(+ORID,"SSRREQIEN")
 Q:'RR
 S HLMSGIEN=$$GET1^DIQ(9009033.91,RR,.05)  ; Message ID
 Q:'HLMSGIEN
 S CHGTYP=$$GET1^DIQ(9009033.91,RR,7.4)
 S PARMS("ACK CODE")="AA"
 S PARMS("MESSAGE TYPE")="RRE"
 S PARMS("EVENT")="O12"
 S PARMS("VERSION")=2.5
 S PARMS("ACCEPT ACK TYPE")="AL"
 S MSGTXT=$G(MSGTXT,"")
 D PARSE^APSPES2(.DATA,HLMSGIEN,.HLMSTATE)
 S HLFS=$G(DATA("HDR","FIELD SEPARATOR"))
 S HLECH=$G(DATA("HDR","ENCODING CHARACTERS"))
 I $$ACK^HLOAPI2(.HLMSTATE,.PARMS,.HLST,.ERR) D
 .S PRN=$$GETVAL^APSPES2(HLMSGIEN,"ORC",7,7)="PRN"  ; Check for PRN value
 .S REF=+$$GETVAL^APSPES2(HLMSGIEN,"RXO",13,1)  ; incoming Refill count
 .S NTEDATA=$$GETVAL^APSPES2(HLMSGIEN,"NTE",3,1) ;NTE segment data
 .S ZDUDATA=$$GETVAL^APSPES2(HLMSGIEN,"ZDU",1,1) ;ZDU segment
 .;Get PID information as for a new order
 .D PID^APSPES1(DFN)
 .S ACT=$$GET1^DIQ(9009033.91,RR,.08,"I")
 .;IHS/MSC/MGH Check for changes; Accept is not allowed if supervisor and provider changes were made
 .I ACT=1 D
 ..S CHG=$$RECHK^APSPES11(HLMSGIEN,PROV,RX2)
 ..I +CHG S ACT=2
 .S OCC=$S(ACT=1:"XR",ACT=2:"XC",1:"XR")
 .D ORCNW^APSPES1(OCC,0)
 .S SSNUM=$$GET1^DIQ(9009033.91,RR,.1)
 .D SET^APSPES2(.ARY,SSNUM,3,1)   ;Set the surescripts number into ORC3
 .I OCC="XR" D
 ..N NM,LP,VAL
 ..S RRPRV=$$GET1^DIQ(9009033.91,RR,1.3,"I")
 ..I PROV'=RRPRV D
 ...S OCC="XC"
 ...D SET^APSPES2(.ARY,PROV,19,1)
 ...S NM=$$HLNAME^HLFNC($$GET1^DIQ(200,PROV,.01),HLECH)
 ...F LP=1:1:$L(NM,$E(HLECH)) S VAL=$P(NM,$E(HLECH),LP) D
 ....D SET^APSPES2(.ARY,VAL,19,LP+1)  ; Acting provider
 ...D SET^APSPES2(.ARY,$$SPI^APSPES1(RRPRV),12,1)
 ...S NM=$$HLNAME^HLFNC($$GET1^DIQ(200,RRPRV,.01),HLECH)
 ...F LP=1:1:$L(NM,$E(HLECH)) S VAL=$P(NM,$E(HLECH),LP) D
 ....D SET^APSPES2(.ARY,VAL,12,LP+1)  ;Original Provider
 .S SEG=$$ADDSEG^HLOAPI(.HLST,.ARY)
 .D RXO^APSPES1(0,OCC)
 .D SET^APSPES2(.ARY,DISP,13,1)  ; Set refill count to # of dispenses
 .D SET^APSPES2(.ARY,COMMENTS,6,2)  ;Provider Comments Patch 1023
 .D SET^APSPES2(.ARY,CHGTYP,16,1)   ;change type
 .S SEG=$$ADDSEG^HLOAPI(.HLST,.ARY)
 .D RXR^APSPES1
 .;D PREPARY^APSPES1(.DATA,"RXE",.ARY)
 .;S SEG=$$ADDSEG^HLOAPI(.HLST,.ARY)
 .D ZCS^APSPES1(RX0,RXIEN),ZSL^APSPES1(RXIEN),RXC^APSPES1,DG1^APSPES1(.HLST,.ARY),AL1^APSPES1(.HLST,.ARY),OBX^APSPES1(.HLST,.ARY)
 .I CHGTYP="U" D ZSF^APSPESC3(RR,.HLST,.ARY)
 .D PREPARY^APSPES1(.DATA,"ZDU",.ARY)
 .I ZDUDATA'="" S SEG=$$ADDSEG^HLOAPI(.HLST,.ARY)
 .D PREPARY^APSPES1(.DATA,"NTE",.ARY)
 .I NTEDATA'="" S SEG=$$ADDSEG^HLOAPI(.HLST,.ARY)
 .I '$$SENDACK^HLOAPI2(.HLST,.ERR) D UPTRRACT^APSPES3(RR,$G(ERR,"There was a problem sending the HL7 message."))
 .E  D UPTRRACT^APSPES3(RR,$G(ERR,"There was a problem with generation the HL7 message."))
 K FDA,ERR
 S FDA(9009033.91,RR_",",.03)=2  ; Set Status to processed-accepted
 S FDA(9009033.91,RR_",",.07)=$$NOW^XLFDT()
 D FILE^DIE("","FDA","ERR")
 I $D(ERR) D UPTRRACT^APSPES3(RR,$G(ERR(1),"Error updating status"))
 ; Update activity log
 I RXIEN D
 .N LOG,RET,LACT,ACT
 .S LOG("REASON")="X"
 .S LOG("RX REF")=0
 .S LACT=$$LASTACT^APSPFNC6(RXIEN,"X")
 .S ACT=$S(LACT="F":"X",1:"T")
 .S LOG("TYPE")=ACT
 .S LOG("COM")="eRx "_$$GET1^DIQ(9009033.91,RR,.08)_" response sent to "_$$PHMINFO^APSPES2A(RXIEN)
 .D UPTLOG^APSPFNC2(.RET,RXIEN,0,.LOG)
 .D ERX^APSPCSA(RXIEN,"TO")  ;Add call to update log for EPCS
 I '$D(DUPDENY) D CHKDUP^APSPES11(RR)
 ;IHS/MSC/MGH Patch 1024 Discontinue the original order
 I CHGTYP'="U"&(CHGTYP'="P") D
 .D DCORIG^APSPES6(SAVRXIEN)
 Q
ACCEPTPA(RR,NUMBER,NTEXT,NCNT) ;Send return message for subtype U and P
 N DATA,HLMSGIEN,HLMSTATE,DFN,ARR,CODE
 N PARMS,HLST,HLFS,HLECH,ERR,PRN,REF,I,FLG,LP,DISP,OCC,ACT
 Q:'RR
 S HLMSGIEN=$$GET1^DIQ(9009033.91,RR,.05)  ; Message ID
 Q:'HLMSGIEN
 S CODE=$$GET1^DIQ(9009033.91,RR,7.4)
 S NUMBER=$G(NUMBER)
 S PARMS("ACK CODE")="AA"
 S PARMS("MESSAGE TYPE")="RRE"
 S PARMS("EVENT")="O12"
 S PARMS("VERSION")=2.5
 S PARMS("ACCEPT ACK TYPE")="AL"
 D PARSE^APSPES2(.DATA,HLMSGIEN,.HLMSTATE)
 S HLFS=$G(DATA("HDR","FIELD SEPARATOR"))
 S HLECH=$G(DATA("HDR","ENCODING CHARACTERS"))
 I $$ACK^HLOAPI2(.HLMSTATE,.PARMS,.ACK,.ERR) D
 .S ACT=$$GET1^DIQ(9009033.91,RR,.08,"I")
 .S OCC="XR"
 .D SETPRACK^APSPESC5(RR,NUMBER,NTEXT,.NCNT)
 K FDA,ERR
 S FDA(9009033.91,RR_",",.03)=2  ; Set Status to processed-accepted
 S FDA(9009033.91,RR_",",.07)=$$NOW^XLFDT()
 D FILE^DIE("","FDA","ERR")
 I $D(ERR) D UPTRRACT^APSPES3(RR,$G(ERR(1),"Error updating status"))
 I '$D(DUPDENY) D CHKDUP^APSPES11(RR)
 Q
