APSPESC3 ;IHS/MSC/PLS - SureScripts Change Request;02-Jun-2021 13:19;DU
 ;;7.0;IHS PHARMACY MODIFICATIONS;**1024,1026,1027,1028**;Sep 23, 2004;Build 50
 Q
RESPONSE(RET,RRIEN) ;Find the type of change it is and then return the data to create the order
 N CODE,SEQID,DFN,PROV,NCNT
 S SEQID=0,NCNT=0
 S MSGIEN=$$GET1^DIQ(9009033.91,RRIEN,.05,"I")
 S CODE=$$GET1^DIQ(9009033.91,RRIEN,7.4,"I")
 S DFN=$$GET1^DIQ(9009033.91,RRIEN,1.2,"I")
 S PROV=$$GET1^DIQ(9009033.91,RRIEN,1.3,"I")
 I CODE="P" S RET=$$PRIOR(RRIEN,DFN,PROV,MSGIEN,.NCNT)
 E  D
 .I CODE="U" S RET=$$PRVAU(RRIEN,DFN,PROV,CODE,.NCNT)
 .E  S RET=$$REQORD(RRIEN,DFN,PROV,MSGIEN,CODE)
 Q
 ;
REQORD(IEN,DFN,PROV,MSGIEN,CODE) ;EP to return data
 K HLMSTATE,HLSEGS,SEGIEN,SEQID,SEL,FOUND,NEWORD
 S NEWORD=0
 S SEL=$$FNDMED(IEN)
 Q:'+SEL 0
 S FOUND=0
 D PARSE^APSPES2(.HLSEGS,$G(MSGIEN),.HLMSTATE)
 S SEGIEN="" F  S SEGIEN=$$FSEGIEN^APSPES1(.HLSEGS,"ZMR",SEGIEN) Q:'+SEGIEN!(FOUND=1)  D
 .K SEGZMR
 .M SEGZMR=HLSEGS(SEGIEN)
 .S SEQID=$$GET^HLOPRS(.SEGZMR,1,1)
 .I SEQID=SEL S FOUND=1 S NEWORD=$$MAKEOR(IEN,CODE,.SEGZMR)
 Q NEWORD
MAKEOR(IEN,CODE,SEGZMR) ;EP Create the new order
 N ROOT,CHKDOSE,DOSE,INST,ILST,I,ID,DLG,VAL,J,LIST,ORVP,ORNP,Y,RXNORM,NDC,DAYS,REFILL,QUANT
 N ITEM,OI,EXT,INT,DATA,DRUG,DRCL,DIALOG,ITM,LOC,NORIFN,SCH,RTE,ORITM,MCODE,DSP,DAW,NEW
 N ORDIALOG,IFN,DLG
 S DLG=$G(DLG,"PSO OERR")
 S IFN=$O(^ORD(101.41,"B",DLG,""))
 Q:'IFN
 D GETDLG1^ORCD(IFN)
 D GETS^DIQ(9009033.91,IEN,".01:1.9;2*;3*;4.1;4.2;7.1;7.2;7.3;7.6","I","INT")
 S LOC=$G(INT(9009033.91,IEN_",",1.6,"I"))
 I CODE="U" D
 .S ORITM=$G(INT(9009033.91,IEN_",",1.1,"I"))
 .S DSP=$G(INT(9009033.91,IEN_",",1.8,"I"))
 E  D
 .S RXNORM=$$GET^HLOPRS(.SEGZMR,2,4)
 .S ORITM=$$DTSLK^APSPES4(RXNORM)  ;Try DTS lookup
 .S NDC=$$GET^HLOPRS(.SEGZMR,2,1)
 .I ORITM="" S ORITM=$$FNDDRG^APSPES4(NDC)
 S ITEM="" F  S ITEM=$O(ORDIALOG(ITEM)) Q:'+ITEM  D
 .S DATA=$G(ORDIALOG(ITEM))
 .Q:DATA=""
 .S DLG=ITEM,INST=1,ID=$P(DATA,U,2)
 .I ID="ORDERABLE" D
 ..S ORDIALOG(DLG,1)=+ORITM
 .I ID="URGENCY" S ORDIALOG(DLG,1)=9
 .I ID="DRUG" D
 ..I CODE="U" S ORDIALOG(DLG,1)=DSP
 ..E  S ORDIALOG(DLG,1)=$P(ORITM,U,2)
 .I ID="PICKUP" S ORDIALOG(DLG,1)="E"
 .I ID="QTY" D
 ..I CODE="U" S QUANT=$G(INT(9009033.91,IEN_",",1.4,"I"))
 ..E  S QUANT=$$GET^HLOPRS(.SEGZMR,3,1)
 ..S ORDIALOG(DLG,1)=QUANT
 .I ID="REFILLS" D
 ..I CODE="U" S REFILL=$G(INT(9009033.91,IEN_",",1.9,"I"))
 ..E  S REFILL=$$GET^HLOPRS(.SEGZMR,5,1)
 ..S ORDIALOG(DLG,1)=REFILL
 .I ID="SCHEDULE" D
 ..S ORDIALOG(DLG,1)="AS WRITTEN"        ;Not a pointer
 .I ID="INSTR" S ORDIALOG(DLG,1)="SEE SIG"
 .I ID="ROUTE" D
 ..S RTE=$O(^PS(51.2,"B","SEE SIG",""))
 ..S ORDIALOG(DLG,1)=RTE
 .I ID="DAW" D
 ..I CODE="U" S DAW=$G(INT(9009033.91,IEN_",",1.12,"I"))
 ..E  D
 ...S DAW=$$GET^HLOPRS(.SEGZMR,8,1)
 ...S DAW=$S(DAW="G":0,DAW="T":0,1:1)
 ..S ORDIALOG(DLG,1)=DAW
 .I ID="CLININD" S ORDIALOG(DLG,1)=$G(INT(9009033.91,IEN_",",7.1,"I"))
 .I ID="CLININD2" S ORDIALOG(DLG,1)=$G(INT(9009033.91,IEN_",",7.2,"I"))
 .I ID="SNMDCNPTID" S ORDIALOG(DLG,1)=$G(INT(9009033.91,IEN_",",7.3,"I"))
 .I ID="SSRREQIEN" S ORDIALOG(DLG,1)=IEN
 .I ID="PHARMACY" S ORDIALOG(DLG,1)=$G(INT(9009033.91,IEN_",",1.7,"I"))
 .I ID="STRENGTH" Q
 .I ID="SIG" D SIGTXT(DLG,INST,ID,CODE)
 .I ID="SUPPLY" D
 ..I CODE="U" S DAYS=$G(INT(9009033.91,IEN_",",1.5,"I"))
 ..E  S DAYS=$$GET^HLOPRS(.SEGZMR,4,1)
 ..S ORDIALOG(DLG,1)=DAYS
 .I ID="CMF" S ORDIALOG(DLG,1)=$G(INT(9009033.91,IEN_",",7.6,"I"))
 .I ID="DOSE" S ORDIALOG(DLG,1)="SEE SIG"
 .I ID="PI" D PI(DLG,1,ID)
 .I ID="COMMENT" S ORDIALOG(DLG,1)=$G(INT(9009033.9,IEN_",",4.2,"I"))
 S DIALOG=$O(^ORD(101.41,"B","PSO OERR",0))
 S ORVP=DFN_";DPT(",ORNP=PROV
 ;IHS/MSC/MGH P1026 Changed code to only store order on a u type
 I CODE="U" D
 .D SAVE^ORWD(.Y,DFN,PROV,$G(LOC),DIALOG,"N",.ORDIALOG)
 .I $G(Y) S NORIFN=$P($P($P(Y(1),U),";"),"~",2)
 .I '$G(NORIFN) S NEW="-1^Order not filed. Check data and try again."
 .I +$G(NORIFN) D
 ..S NEW=NORIFN_"^Order created."
 ..D EN^OCXOERR(DFN_U_+NORIFN_U_PROV_"^^^^^1")
 ..S FDA(9009033.91,IEN_",",.02)=+NORIFN
 ..S FDA(9009033.91,IEN_",",.03)=1
 ..S FDA(9009033.91,IEN_",",.07)=$$NOW^XLFDT()
 ..;IHS/MSC/MGH add check for controlled substances
 ..S MCODE=$$CHKMED^APSPES5(PROV,+NORIFN,"",ITEM)
 ..I MCODE=3 S FDA(9009033.91,IEN_",",1.11)=3
 ..D FILE^DIE(,"FDA") K FDA
 E  D
 .D RESPUPD^APSPESG2(.ORDIALOG,IEN)
 .S NEW="0^Request Updated"
 Q NEW
FNDMED(IEN) ;Find the medication that the provider selected from the mailbox
 N NODE,HANDLE,MATCH,CHOICE,NAME,TXT,RESP
 K ^TMP("APSPC",$J)
 S CHOICE=0
 S MATCH=0
 S HANDLE=$$XMLHANDL(IEN)
 Q:'+HANDLE 0
 S NODE=1
 ;Work down the XML in the field until it finds the correct node
 F  S NAME=$$NAME^MXMLDOM(HANDLE,NODE) Q:NAME=""!(MATCH=1)  D
 .I NAME="SeqID" D
 ..N TXT
 ..S MATCH=1
 ..S RESP=$$TEXT^MXMLDOM(HANDLE,NODE,"TXT")
 ..S CHOICE=$G(TXT(1))
 .E  S NODE=NODE+1
 Q CHOICE
XMLHANDL(RRIEN) ;Use XML parser to get the handle of the XML data in the field
 N ARR1
 K ^TMP("APSPC",$J)
 M ARR1=^APSPRREQ(RRIEN,8)
 K ARR1(0)
 M ^TMP("APSPC",$J)=ARR1
 S HANDLE=$$EN^MXMLDOM($NA(^TMP("APSPC",$J)))
 Q HANDLE
PRIOR(RRIEN,DFN,PROV,MSGIEN,NCNT) ;Process a prior authorization response
 N NODE,HANDLE,RESP,NAME,PA,AIEN,DONE,NTEXT
 S DONE=0,NTEXT=""
 S HANDLE=$$XMLHANDL(RRIEN)
 Q:'+HANDLE 0
 S PA=""
 S NODE=1
 F  S NAME=$$NAME^MXMLDOM(HANDLE,NODE) Q:NAME=""!(PA'="")!(+DONE)  D
 .I NAME="PriorAuthID" D
 ..S RESP=$$TEXT^MXMLDOM(HANDLE,NODE,"TXT")
 ..S PA=$G(TXT(1))
 ..I NAME="PriorAuthID"&(PA="") S DONE=1
 .E  S NODE=NODE+1
 S NODE=1
 F  S NAME=$$NAME^MXMLDOM(HANDLE,NODE) Q:NAME=""  D
 .I NAME="Note" D
 ..S RESP=$$TEXT^MXMLDOM(HANDLE,NODE,"TXT")
 ..S NTEXT=$G(TXT(1)),NCNT=NCNT+1
 .S NODE=NODE+1
 S FDA(9009033.91,RRIEN_",",7.5)=PA
 S FDA(9009033.91,RRIEN_",",.08)=1
 S AIEN=RRIEN_","
 D FILE^DIE("","FDA","ERR")
 K FDA,ERR
 D ACCEPTPA^APSPESC2(RRIEN,PA,NTEXT,.NCNT)
 Q PA
 ;Process a validate provider authorization request
PRVAU(IEN,DFN,PROV,CODE,NCNT) ;EP
 N FDA,AIEN,ERR
 S NCNT=0
 S FDA(9009033.91,IEN_",",.08)=1
 D FILE^DIE("","FDA","ERR")
 K FDA,ERR
 D ACCEPTPA^APSPESC2(IEN,"","",.NCNT)
 Q IEN
SIGTXT(DLG,INST,ID,CODE) ; Do sig
 N SIG,TXT
 S TXT="ORDIALOG(""WP"","_DLG_",1)"
 S ORDIALOG(DLG,1)=TXT
 I CODE="U"!(CODE="P") D
 .S SIG=0 F  S SIG=$O(^APSPRREQ(IEN,3,SIG)) Q:'+SIG  D
 ..S ORDIALOG("WP",DLG,1,SIG,0)=$G(^APSPRREQ(IEN,3,SIG,0))
 E  D
 .N LEN,CNTP,LEFT,STR
 .S CNTP=0
 .S SIG=$$GET^HLOPRS(.SEGZMR,6,1)
 .;S LEN=$L(SIG)
 .;I LEN<201 D
 .;.S ORDIALOG("WP",DLG,1,1,0)=SIG
 .;E  D
 .;.F  D  Q:$L(SIG)=0
 .;..S STR=$E(SIG,1,200)
 .;..S CNTP=CNTP+1
 .;..S ORDIALOG("WP",DLG,1,CNTP,0)=STR
 .;..S LEFT=$E(SIG,201,$L(SIG))
 .;..S SIG=LEFT
 K SIGARR
 D FORMAT^APSPES6(SIG,.SIGARR)
 S CNTP=0
 F  S CNTP=$O(SIGARR(CNTP)) Q:'+CNTP  D
 .S ORDIALOG("WP",DLG,1,CNTP,0)=$G(SIGARR(CNTP,0))
 Q
PI(DLG,INST,ID) ; Do PI
 N PI,TXT
 S TXT="ORDIALOG(""WP"","_DLG_",1)"
 S ORDIALOG(DLG,1)=TXT
 S PI=$G(INT(9009033.91,IEN_",",4.1,"I"))
 S ORDIALOG("WP",DLG,1,1,0)=PI
 Q
ZSF(IEN,HLST,ARY,NCNT) ;Process a provider response segment
 N NODE,HANDLE,RESP,NAME,TEXT,CHILD,AIEN,NTE,CNT,STRING,ZSF,PIECE,SUBP,TXT,NTEXT,SAVNODE
 S HANDLE=$$XMLHANDL(IEN)
 Q:'+HANDLE
 S NODE=1,CNT=0,STRING="",NTEXT=""
 F  S NAME=$$NAME^MXMLDOM(HANDLE,NODE) Q:NAME=""  D
 .I NAME="ProvAuth" S SAVNODE=NODE
 .I NAME="PVAType" D
 ..D CHILD(HANDLE,NODE,.STRING)
 ..S NODE=$$SIBLING^MXMLDOM(HANDLE,NODE)
 .E  S NODE=NODE+1
 S NODE=SAVNODE
 F  S NAME=$$NAME^MXMLDOM(HANDLE,NODE) Q:NAME=""  D
 .I NAME="Note" D
 ..S RESP=$$TEXT^MXMLDOM(HANDLE,NODE,"TXT")
 ..S NTEXT=$G(TXT(1))
 ..S NCNT=NCNT+1
 .S NODE=NODE+1
 D SET^APSPES1(.ARY,"ZSF",0)
 F I=1:1 S PIECE(I)=$P(STRING,"~",I) Q:PIECE(I)=""  D
 .I $G(PIECE(I))'="" F J=1:1:5 S SUBP(I,J)=$P(PIECE(I),"^",J)
 S I=0 F  S I=$O(SUBP(I)) Q:'+I  D
 .S J=0 F  S J=$O(SUBP(I,J)) Q:'+J  D
 ..S DATA=$G(SUBP(I,J))
 ..I J=4&(DATA'="") S DATA=$$FMTHL7^XLFDT(DATA)
 ..D SET^APSPES1(.ARY,DATA,1,J,,I)
 S ZSF=$$ADDSEG^HLOAPI(.HLST,.ARY)
 I NTEXT'=""  D
 .D SET^APSPES1(.ARY,"NTE",0)
 .D SET^APSPES1(.ARY,1,1,1)
 .D SET^APSPES1(.ARY,NTEXT,3,1)
 .S NTE=$$ADDSEG^HLOAPI(.HLST,.ARY)
 Q
CHILD(HANDLE,NODE,STRING) ;Handle the child nodes
 S CHILD=0,FOUND=0
 S CHILD=$$CHILD^MXMLDOM(HANDLE,NODE,CHILD) Q:'CHILD!(FOUND=1)
 S NAME=$$NAME^MXMLDOM(HANDLE,CHILD)
 I NAME="Code" D
 .S CNT=CNT+1,FOUND=1
 .S RESP=$$TEXT^MXMLDOM(HANDLE,CHILD,"TXT")
 .S TEXT=$G(TXT(1))
 .S CODE=TEXT
 .D NEXT(HANDLE,CHILD,.CODE)
 .I CNT=1 S STRING=CODE
 .E  S STRING=STRING_"~"_CODE
 E  S CHILD=CHILD+1
 Q
NEXT(HANDLE,CHILD,CODE) ;State License
 N CHILD2,NAME,RESP,TEXT
 S CHILD2=CHILD
 F  S CHILD2=$$SIBLING^MXMLDOM(HANDLE,CHILD) Q:CHILD2=0  D
 .S NAME=$$NAME^MXMLDOM(HANDLE,CHILD2)
 .S RESP=$$TEXT^MXMLDOM(HANDLE,CHILD2,"TXT")
 .S TEXT=$G(TXT(1))
 .I NAME="State" S $P(CODE,U,2)=TEXT
 .I NAME="Value" S $P(CODE,U,3)=TEXT
 .I NAME="Date" S $P(CODE,U,4)=TEXT
 .I NAME="ResponseCode" S $P(CODE,U,5)=TEXT
 .S CHILD=CHILD+1
 Q
 ; Checks status of Prescription
 ; if Active returns 0, otherwise 1
DCRXCHK(RET,REQIEN) ;Check for DC'd medication patch 1028
 N RXRNEW
 S RET=0
 S RXRNEW=$$GET1^DIQ(9009033.91,REQIEN,.06,"I")
 I +RXRNEW D
 .S STAT=$$GET1^DIQ(52,RXRNEW,100,"I")
 .I STAT'=0 S RET=1
 Q RET
GETORD(RXIEN) ;Get the orderable item from the original order Patch 1028
 N DRG,OI,RET2
 S RET2=""
 S DRG=$$GET1^DIQ(52,RXIEN,6,"I")
 S OI=$$FNDOI^APSPES4(DRG)
 S RET2=OI_U_DRG
 Q RET2
