APSPESG3 ;IHS/MSC/PLS - SureScripts Refill Request;26-Mar-2025 14:33;DU
 ;;7.0;IHS PHARMACY MODIFICATIONS;**1023,1024,1026,1027,1028,1035**;Sep 23, 2004;Build 39
 Q
 ;
 ;Input: IEN - IEN to file 9009033.91
 ;Output: Value representing number of related requests linked to parent
DUPCNT(DATA,IEN) ;EP-
 S DATA=$$DUPS^APSPESG(+IEN)
 Q
 ;Input: IEN - IEN to file 9009033.91
 ;Output: Array of detail text for each linked request
DUPDTL(DATA,IEN) ;EP-
 N NIEN,LN,CNT,SSNUM,CTYPE,NTYPE,OLDMSG,ORGIEN,DUPMSG,DETAIL
 S DATA=$$TMPGBL^CIAVMRPC("ALL")
 K @DATA
 D ADDDTL(DATA,"Related medication requests")
 ;IHS/MSC/MGH 07/12/2019 modified to find latest request, not first
 S SSNUM=$$GET1^DIQ(9009033.91,IEN,.1)
 I SSNUM="" D ADDDTL(DATA,"No requests found")
 S CTYPE=$$GET1^DIQ(9009033.91,IEN,7.4)
 S MSGIEN=$$GET1^DIQ(9009033.91,IEN,.01)
 S NIEN=0 F  S NIEN=$O(^APSPRREQ("G",SSNUM,NIEN)) Q:'+NIEN  D
 .;S NIEN=0 F  S NIEN=$O(^APSPRREQ(IEN,9,"B",NIEN)) Q:'NIEN  D
 .I NIEN'=IEN D
 ..S DUPMSG=0
 ..I CTYPE="" S DUPMSG=1
 ..I CTYPE'="" D
 ...S DTYPE=$$GET1^DIQ(9009033.91,NIEN,7.4)
 ...I CTYPE=DTYPE D
 ....I CTYPE="U" D
 .....S ORGIEN=$$VALCHK^APSPES11(IEN,NIEN,OLDMSG)
 .....I +ORGIEN S DUPMSG=1
 ....E  S DUPMSG=1
 ...E  S DUPMSG=1
 ..I DUPMSG=1 D
 ...D ADDDTL(DATA,"IEN: "_NIEN_"   Message #: "_$$GET1^DIQ(9009033.91,NIEN,.05)_"       Message Date: "_$$FMTDT($$GET1^DIQ(9009033.91,NIEN,.04,"I")))
 ...D DETAIL^APSPESG1(.DETAIL,NIEN)
 ...S LN=0 F  S LN=$O(@DETAIL@(LN)) Q:'LN  D
 ....D ADDDTL(DATA,@DETAIL@(LN))
 ....D ADDDTL(DATA," ")
 D ADDDTL(DATA,"<End of report>")
 Q
 ;
ADDDTL(DATA,STR) ;EP-
 S CNT=$G(CNT)+1
 S @DATA@(CNT)=STR
 Q
 ;Format Date/Time
FMTDT(VAL) ;EP-
 Q $P($TR($$FMTE^XLFDT(VAL,"5Z"),"@"," "),":",1,2)
 ;
PATNAME(PIDSEG) ; Get patient name
 N PAT,PATLN,PATFN,PATNAME,GENDER
 S PAT=$$GET1^DIQ(9009033.91,IEN,1.2,"I")
 S GENDER=$$GET1^DIQ(2,PAT,.02)
 I PAT,$$GET1^DIQ(9009033.91,IEN,1.2)="" S PAT=0,GENDER=""
 Q:PAT>0 PAT_";"_$$GET1^DIQ(9009033.91,IEN,1.2)_";"_$$FMTE^XLFDT($$DOB^AUPNPAT(PAT),"5Z")_";"_GENDER
 S PAT=$$DESCAPE^APSPESG($P(PIDSEG,"|",6)) I '$L(PAT) Q ";"
 S PAT=$TR(PAT,";",":")
 S PATLN=$P(PAT,U),PATFN=$P(PAT,U,2)
 S PATNAME=PATLN_","_PATFN
 Q ";"_PATNAME_";"_$$GETPDOB(IEN)_";"_$$GETPGEN(IEN)
 ; Return patient DOB from HL7 content
GETPDOB(IEN) ;EP-
 N DLM,HLECH,I,HLMSG
 D HL7INIT^APSPESG(IEN)
 S HLMSG=$$GHLDAT^APSPESLP(IEN) D SHLVARS^APSPESLP
 Q $$FMTE^XLFDT($$FMDATE^HLFNC($$DESCAPE^APSPESG($P(APSPPID,DLM,8))),"5Z")
 ; Return patient Gender from HL7 context
GETPGEN(IEN) ;EP-
 N DLM,HLECH,I,HLMSG,G
 D HL7INIT^APSPESG(IEN)
 S G=$$DESCAPE^APSPESG($P(APSPPID,DLM,9))
 Q $S(G="M":"MALE",G="F":"FEMALE",G="O":"OTHER",1:"UNKNOWN")
 ;
CHANGE(LST,RSPID) ;Load responses on a change message. Get data from 4.5 node
 I '$D(^APSPRREQ(RSPID,4.6)) D
 .D BLDORSP^APSPESG3(RSPID)    ;p1026 Generate original responses
 S ROOT="^APSPRREQ("_+RSPID_",4.5)"
 D XROOT^ORWDX2
 Q
 ; Return details of the SureScript Request
 ; Input: IEN - IEN to APSP REFILL REQUEST file
DETAIL(DATA,IEN) ; EP-
 N HLMSG,DLM,APSPMSH,APSPPID,APSPORC,APSPRXO,APSPRXE,APSPRXR
 N PAT,QTY,PROVDAT,PROV,DRUG,INST,STR,UNITS,ROUTE,NOUN,CONJ
 N USCHDUR,MEDUNITS,REFILLS,PHARM,SIGDAT,HLECH,DONE,DUR
 N SCHITEM,SCHUPD,SCHARY,INTERVAL,TOTDUR
 S HLECH=$P($G(APSPMSH),"|",2) I '$L(HLECH) S HLECH="^~\&"
 F I=1:1:4 D
 .S HLECH(I)=$E(HLECH,I)
 S HLMSG=$$GHLDAT^APSPESLP(IEN)
 D SHLVARS^APSPESLP
 S DLM="|"
 S PAT=$$PATNAME^APSPESLP(APSPPID) I '$L(PAT) S PAT="**UNKNOWN**"
 S QTY=+$P(APSPRXO,DLM,12),PROVDAT=$P(APSPORC,DLM,13),PROV=$P(PROVDAT,HLECH(1),2)_","_$P(PROVDAT,HLECH(1),3)
 S DRUG=$P($P($G(APSPRXO),DLM,2),U,2),INST=$P($P($G(APSPRXO),DLM,7),U,2)
 S STR=$P($G(APSPRXO),DLM,3),UNITS=$P($P($G(APSPRXO),DLM,5),HLECH(1),2),ROUTE=$P($G(APSPRXR),DLM,2)
 S NOUN=$P($G(APSPRXO),DLM,6) I $L(NOUN) S NOUN=$O(^APSPNCP(9009033.7,"B",NOUN,0)),NOUN=$$GET1^DIQ(9009033.7,NOUN,1,"E")
 S USCHDUR=$P($G(APSPORC),DLM,8),MEDUNITS=$P($P($G(APSPRXO),DLM,20),HLECH(1),2)
 S REFILLS=0
 S PHARM=$$GET1^DIQ(9009033.91,IEN,1.7,"E")
 S SIGDAT=$P($P(APSPRXO,"|",8),"^",2)
 S DONE=0
 F I=1:1 D  Q:DONE
 .S SCHITEM=$P(USCHDUR,HLECH(2),I)
 .I '$L(SCHITEM) S DONE=1 Q
 .S SCHUPD=$P(SCHITEM,HLECH(1)) I 'SCHUPD S SCHUPD=1
 .S INTERVAL=$P(SCHITEM,HLECH(1),2),DUR=$P(SCHITEM,HLECH(1),3),CONJ=$P(SCHITEM,HLECH(1),9)
 .S SCHARY(I)=SCHUPD_U_INTERVAL_U_DUR_U_CONJ
 .S TOTDUR=$G(TOTDUR)+DUR
 S DATA=$$TMPGBL^CIAVMRPC
 D CAPTURE^CIAUHFS("D DISPHL7^APSPESLP(PAT,QTY,PROV,DRUG,INST,STR,UNITS,ROUTE,NOUN,.SCHARY,MEDUNITS,REFILLS,PHARM,SIGDAT)",DATA)
 Q
 ;Build response list in Order Response format
LOADRSP(LST,IEN) ;EP to return data
 N ROOT,CHKDOSE,DOSE,INST,ILST,I,ID,DLG,VAL,J,LIST,CTYPE
 N EN,IARY
 K LST
 S EN=0
 S CTYPE=$$GET1^DIQ(9009033.91,IEN,.12,"I")
 I '$D(^APSPRREQ(IEN,4.6)) D
 .N ITEM,OI,EXT,INT,DATA,CNT
 .S ILST=0,CNT=0
 .D DLGDEF^ORWDX1(.LIST,"PSO OERR")
 .D GETS^DIQ(9009033.91,IEN,".01:1.9;2*;3*;4.1;4.2;7.1;7.2;7.3;7.6","I","INT")
 .S IARY=$NA(INT(9009033.91,IEN_","))
 .S ITEM="" F  S ITEM=$O(LIST(ITEM)) Q:'+ITEM  D
 ..S DATA=$G(LIST(ITEM))
 ..Q:DATA=""
 ..S EN=EN+1,CNT=CNT+1
 ..S DLG=$P(DATA,U,2),INST=1,ID=$P(DATA,U,1)
 ..I ID="ORDERABLE" D
 ...S LST(1,EN,0)=ITEM_U_DLG_U_1_U_ID
 ...S LST(1,EN,1)=@IARY@(1.1,"I")
 ..I ID="URGENCY" D
 ...S LST(1,EN,0)=ITEM_U_DLG_U_1_U_ID
 ...S LST(1,EN,1)=9
 ..I ID="DRUG" D
 ...S LST(1,EN,0)=ITEM_U_DLG_U_1_U_ID
 ...S LST(1,EN,1)=@IARY@(1.8,"I")
 ..I ID="PICKUP" D
 ...S LST(1,EN,0)=ITEM_U_DLG_U_1_U_ID
 ...S LST(1,EN,1)="E"
 ..I ID="QTY" D
 ...S LST(1,EN,0)=ITEM_U_DLG_U_1_U_ID
 ...S LST(1,EN,1)=@IARY@(1.4,"I")
 ..I ID="CMF" D
 ...S LST(1,EN,0)=ITEM_U_DLG_U_1_U_ID
 ...S LST(1,EN,1)=@IARY@(7.6,"I")
 ..I ID="REFILLS" D
 ...N R
 ...S LST(1,EN,0)=ITEM_U_DLG_U_1_U_ID
 ...S R=@IARY@(1.9,"I")
 ...S LST(1,EN,1)=$S(R>0:R-1,1:0)
 ..I ID="SCHEDULE" D
 ...N LP
 ...S LP=0 F  S LP=$O(^APSPRREQ(IEN,2,LP)) Q:'LP  D
 ....S:LP>1 EN=EN+1
 ....S LST(1,EN,0)=ITEM_U_DLG_U_LP_U_ID
 ....S LST(1,EN,1)=$G(INT(9009033.912,LP_","_IEN_",",1.8,"I"))
 ..I ID="INSTR" D
 ...N LP
 ...S LP=0 F  S LP=$O(^APSPRREQ(IEN,2,LP)) Q:'LP  D
 ....S:LP>1 EN=EN+1
 ....N I
 ....S I=$P($G(^APSPRREQ(IEN,2,LP,0)),"&",5)
 ....I I="" S I=$P($G(^APSPRREQ(IEN,2,LP,0)),"&",1)  ;IHS/MSC/MGH Patch 1023
 ....S LST(1,EN,0)=ITEM_U_DLG_U_LP_U_ID  ; INSTR(DLG,INST,ID)
 ....S LST(1,EN,1)=I
 ..I ID="ROUTE" D
 ...N LP
 ...S LP=0 F  S LP=$O(^APSPRREQ(IEN,2,LP)) Q:'LP  D
 ....S:LP>1 EN=EN+1
 ....S LST(1,EN,0)=ITEM_U_DLG_U_LP_U_ID
 ....S LST(1,EN,1)=$G(INT(9009033.912,LP_","_IEN_",",1.7,"I"))
 ..I ID="CONJ" D
 ...N LP,VAL
 ...S LP=0 F  S LP=$O(^APSPRREQ(IEN,2,LP)) Q:'LP  D
 ....S:LP>1 EN=EN+1
 ....S VAL=$G(INT(9009033.912,LP_","_IEN_",",1.6,"I"))
 ....I VAL'="" D
 .....S LST(1,EN,0)=ITEM_U_DLG_U_LP_U_ID
 .....S LST(1,EN,1)=VAL
 ..I ID="DAYS" D
 ...N LP,VAL
 ...S LP=0 F  S LP=$O(^APSPRREQ(IEN,2,LP)) Q:'LP  D
 ....S:LP>1 EN=EN+1
 ....S VAL=$G(INT(9009033.912,LP_","_IEN_",",1.5,"I"))
 ....I VAL'="" D
 .....S LST(1,EN,0)=ITEM_U_DLG_U_LP_U_ID
 .....S LST(1,EN,1)=VAL
 ..I ID="SUPPLY" D
 ...S LST(1,EN,0)=ITEM_U_DLG_U_1_U_ID
 ...S LST(1,EN,1)=@IARY@(1.5,"I")
 ..I ID="DAW" D
 ...S LST(1,EN,0)=ITEM_U_DLG_U_1_U_ID
 ...S LST(1,EN,1)=@IARY@(1.12,"I")
 ..I ID="CLININD" D
 ...S LST(1,EN,0)=ITEM_U_DLG_U_1_U_ID
 ...S LST(1,EN,1)=@IARY@(7.1,"I")
 ..I ID="CLININD2" D
 ...S LST(1,EN,0)=ITEM_U_DLG_U_1_U_ID
 ...S LST(1,EN,1)=@IARY@(7.2,"I")
 ..I ID="SNMDCNPTID" D
 ...S LST(1,EN,0)=ITEM_U_DLG_U_1_U_ID
 ...S LST(1,EN,1)=@IARY@(7.3,"I")
 ..I ID="SSREQIEN" D
 ...S LST(1,EN,0)=ITEM_U_DLG_U_1_U_ID
 ...S LST(1,EN,1)=IEN
 ..I ID="SSDENYRSN" D
 ...S LST(1,EN,0)=ITEM_U_DLG_U_1_U_ID
 ...S LST(1,EN,1)=""
 ..I ID="PHARMACY" D
 ...S LST(1,EN,0)=ITEM_U_DLG_U_1_U_ID
 ...S LST(1,EN,1)=@IARY@(1.7,"I")
 ..I ID="STRENGTH" D
 ...S LST(1,EN,0)=ITEM_U_DLG_U_1_U_ID
 ...S LST(1,EN,1)=""
 ..I ID="SIG" D
 ...S LST(1,EN,0)=ITEM_U_DLG_U_1_U_ID
 ...N LP
 ...S LP=0 F  S LP=$O(^APSPRREQ(IEN,3,LP)) Q:'LP  D
 ....S LST(1,EN,2,LP,0)=^APSPRREQ(IEN,3,LP,0)
 ..I ID="DOSE" D
 ...N LP
 ...S LP=0 F  S LP=$O(^APSPRREQ(IEN,2,LP)) Q:'LP  D
 ....S:LP>1 EN=EN+1
 ....S LST(1,EN,0)=ITEM_U_DLG_U_LP_U_ID
 ....S LST(1,EN,1)=$G(INT(9009033.912,LP_","_IEN_",",.01,"I"))
 ..I ID="PI" D
 ...S LST(1,EN,0)=ITEM_U_DLG_U_1_U_ID
 ...S LST(1,EN,2,1,0)=@IARY@(4.1,"I")
 ..I ID="COMMENT" D
 ...S LST(1,EN,0)=ITEM_U_DLG_U_1_U_ID
 ...S LST(1,EN,2,1,0)=@IARY@(4.2,"I")
 .S ^APSPRREQ(IEN,4.6,0)="^9009033.9146^"_CNT_U_CNT
 Q
 ;
BLDORSP(IEN) ;EP- Build response list for original values and store in 4.6
 N ARY
 D LOADRSP(.ARY,IEN)
 M ^APSPRREQ(IEN,4.6)=ARY(1)
 Q
 ;
UPDFLDS(IEN) ;-Called from APSPES6
 N LIST,RET
 D GETRPLST(.LIST,IEN)
 D UPDATE^APSPESG2(.RET,IEN,0,0,0,-1,.LIST)
 Q
 ;Build response list in UI format
GETRPLST(RET,ROOT) ;-
 N ORI,ID,PTR,INST,TYPE,DA,X,ORTXT,LP,WP,ORDIALOG
 D GETDLG^ORCD($$PTR^ORCD("PSO OERR"))
 I +ROOT=ROOT S ROOT="^APSPRREQ("_ROOT_",4.6)" ; assume SS Request file IFN
 S ORI=0 F  S ORI=$O(@ROOT@(ORI)) Q:ORI'>0  S ID=$G(@ROOT@(ORI,0)) D
 .S DA=$P(ID,U),PTR=$P(ID,U,2),INST=$P(ID,U,3) S:'INST INST=1
 .S:'PTR PTR=$P($G(^ORD(101.41,+ORDIALOG,10,DA,0)),U,2) Q:'PTR
 .Q:'$D(ORDIALOG(PTR))  S TYPE=$E($G(ORDIALOG(PTR,0))) Q:'$L(TYPE)
 .I TYPE'="W" D  Q
 ..S X=$G(@ROOT@(ORI,1))
 ..S:$L(X) LIST(PTR,INST)=X
 .S ORTXT=$NA(WP)
 .S LP=0 F  S LP=$O(@ROOT@(ORI,2,LP)) Q:'LP  D
 ..S WP(LP,0)=@ROOT@(ORI,2,LP,0)
 .M LIST("WP",PTR,INST)=@ORTXT
 .S LIST(PTR,INST)=$NA(ORDIALOG("WP",PTR,INST))
 .K @ORTXT
 Q
 ; Moved from APSPESG - Patch 1035 FID 106476
 ; Return count and patient flag - used by REFREQ CIA EVENT
QUECHECK(DFN) ;EP-
 N IEN,CNT,PFLG,FILTER
 S DFN=$G(DFN,$$GETVAR^CIANBUTL("PATIENT.ID.MRN",,"CONTEXT.PATIENT"))
 S FILTER="45" ;IHS/PLS - 5/13/2020 was "014"
 S PFLG=0
 S (IEN,CNT)=0 F  S IEN=$O(^APSPRREQ(IEN)) Q:'IEN  D
 .Q:'$$CANSHOW^APSPESG(IEN,FILTER)
 .I 'PFLG S PFLG=''$D(^APSPRREQ("E",+DFN,IEN))
 .S CNT=CNT+1
 ;IHS/MSC/PLS - 01/29/2024 - FID 106476
 ;Q +$G(CNT)_U_$S(DFN>0:$O(^APSPRREQ("E",DFN,0))>0,1:0)
 Q +$G(CNT)_U_+PFLG
 ;
