APSPESC5 ;IHS/MSC/PLS - SureScripts Interface Support;05-May-2021 14:09;DU
 ;;7.0;IHS PHARMACY MODIFICATIONS;**1028**;Sep 23, 2004;Build 50
 Q
 ;
SETPRACK(RR,NUMBER,NTEXT,NCNT) ;Get original message to include in ack
 N PRV,ACT,NM,LP,VAL,INST,MRN,DFN,CHGTYP,NTEDATA,ZDUDATA,ZCSDATA
 ;Get PID information as for a new order
 S DFN=$$GET1^DIQ(9009033.91,RR,1.2,"I")
 S CHGTYP=$$GET1^DIQ(9009033.91,RR,7.4)
 D PREPARY^APSPES1(.DATA,"PID",.ARY)
 S SEG=$$ADDSEG^HLOAPI(.ACK,.ARY)
 D PREPARY^APSPES1(.DATA,"ORC",.ARY)
 D SET^APSPES2(.ARY,OCC,1)  ; Order Control Code
 D SET^APSPES2(.ARY,$$HLDATE^HLFNC($$NOW^XLFDT()),9)  ; Written Date/Time
 I OCC="UX" D
 .D SET^APSPES2(.ARY,DNYC,16,1)  ; Order Control Code Reason Identifier
 .D SET^APSPES2(.ARY,$E(MSGTXT,1,70),16,2)  ; Order Control Code Reason Text
 .D SET^APSPES2(.ARY,"NCPDP1131",16,3)  ; Order Control Code Reason System
 D SET^APSPES2(.ARY,$$GET1^DIQ(4,+$G(DUZ(2)),.01),21)  ; Institution Name
 S PRV=$$GET1^DIQ(9009033.91,RR,1.3,"I")
 S ACT=$$GET1^DIQ(9009033.91,RR,.09,"I")
 I +PRV'=+ACT D
 .D SET^APSPES2(.ARY,ACT,19,1)
 .S NM=$$HLNAME^HLFNC($$GET1^DIQ(200,ACT,.01),HLECH)
 .F LP=1:1:$L(NM,$E(HLECH)) S VAL=$P(NM,$E(HLECH),LP) D
 ..D SET^APSPES2(.ARY,VAL,19,LP+1)  ; Acting provider
 S SEG=$$ADDSEG^HLOAPI(.ACK,.ARY)
 D PREPARY^APSPES1(.DATA,"RXE",.ARY)
 D SET^APSPES2(.ARY,CHGTYP,31,1)   ;Type of change request
 S SEG=$$ADDSEG^HLOAPI(.ACK,.ARY)
 D PREPARY^APSPES1(.DATA,"ZCS",.ARY)
 S ZCSDATA=$$GETVAL^APSPES2(HLMSGIEN,"ZCS",1,1) ;ZCS segment data
 I ZCSDATA'="" S SEG=$$ADDSEG^HLOAPI(.ACK,.ARY)
 S LP=0
 S FLG=0 F I=1:1 D  Q:FLG
 .S LP=$$FSEGIEN^APSPES1(.DATA,"DG1",LP)
 .I LP=0 S FLG=1 Q
 .D PREPARY^APSPES1(.DATA,"DG1",.ARY,LP-1)
 .S SEG=$$ADDSEG^HLOAPI(.ACK,.ARY)
 S LP=0
 S FLG=0 F I=1:1 D  Q:FLG
 .S LP=$$FSEGIEN^APSPES1(.DATA,"AL1",LP)
 .I LP=0 S FLG=1 Q
 .D PREPARY^APSPES1(.DATA,"AL1",.ARY,LP-1)
 .S SEG=$$ADDSEG^HLOAPI(.ACK,.ARY)
 S LP=0
 S FLG=0 F I=1:1 D  Q:FLG
 .S LP=$$FSEGIEN^APSPES1(.DATA,"OBX",LP)
 .I LP=0 S FLG=1 Q
 .D PREPARY^APSPES1(.DATA,"OBX",.ARY,LP-1)
 .S SEG=$$ADDSEG^HLOAPI(.ACK,.ARY)
 S LP=0
 S FLG=0 F I=1:1 D  Q:FLG
 .S LP=$$FSEGIEN^APSPES1(.DATA,"ZMR",LP)
 .I LP=0 S FLG=1 Q
 .D PREPARY^APSPES1(.DATA,"ZMR",.ARY,LP-1)
 .S SEG=$$ADDSEG^HLOAPI(.ACK,.ARY)
 I CODE="P" D
 .S SEGIEN=$$FSEGIEN^APSPES1(.DATA,"IN1")
 .I 'SEGIEN D
 ..D SET^APSPES2(.ARY,"IN1",0)
 ..D SET^APSPES2(.ARY,NUMBER,14,1)
 ..S SEG=$$ADDSEG^HLOAPI(.ACK,.ARY)
 .I +SEGIEN D
 ..D PREPARY^APSPES1(.DATA,"IN1",.ARY)
 ..D SET^APSPES2(.ARY,NUMBER,14,1)     ;Set the prior authorization number in
 ..S SEG=$$ADDSEG^HLOAPI(.ACK,.ARY)
 .I NTEXT'="" D
 ..D SET^APSPES1(.ARY,"NTE",0)
 ..D SET^APSPES1(.ARY,NCNT,1,1)
 ..D SET^APSPES1(.ARY,NTEXT,3,1)
 ..S NTE=$$ADDSEG^HLOAPI(.ACK,.ARY)
 I CODE="U" D             ;This was a provider authorization request
 .D ZSF^APSPESC3(RR,.ACK,.ARY,.NCNT)
 D PREPARY^APSPES1(.DATA,"ZDU",.ARY)
 S ZDUDATA=$$GETVAL^APSPES2(HLMSGIEN,"ZDU",1,1) ;ZDU segment data
 I ZDUDATA'="" S SEG=$$ADDSEG^HLOAPI(.ACK,.ARY)
 D PREPARY^APSPES1(.DATA,"NTE",.ARY)
 S NTEDATA=$$GETVAL^APSPES2(HLMSGIEN,"NTE",3,1) ;NTE segment data
 I NTEDATA'="" D
 .S NCNT=NCNT+1
 .D SET^APSPES1(.ARY,NCNT,1,1)
 .S SEG=$$ADDSEG^HLOAPI(.ACK,.ARY)
 I '$$SENDACK^HLOAPI2(.ACK,.ERR) D UPTRRACT^APSPES3(RR,$G(ERR,"There was a problem sending the HL7 message."))
 E  D UPTRRACT^APSPES3(RR,$G(ERR,"There was a problem generating the HL7 message."))
 Q
