APSPES2A ;IHS/MSC/PLS - SureScripts HL7 interface - con't;18-Mar-2020 12:32;DU
 ;;7.0;IHS PHARMACY MODIFICATIONS;**1024,1025**;Sep 23, 2004;Build 33
 ;Continuation of APSPES2 due to size constraints
DSP ;
 N HLMSGIEN,HLMSTATE,PARMS
 S HLMSGIEN=200000000001
 D PARSE^APSPES2(.DATA,HLMSGIEN,.HLMSTATE)
 S PARMS("ACK CODE")="AA"
 I '$$ACK^HLOAPI2(.HLMSTATE,.PARMS,.ACK,.ERR) W !,ERR Q
 I '$$SENDACK^HLOAPI2(.ACK,.ERR) W !,ERR Q
 Q
 ; Send bulletin
BULL(XMSUB,XMDUZ,WHO,MSG) ;EP
 N XMY,XMTEXT
 M XMY=WHO
 S XMTEXT="MSG("
 D ^XMD
 Q
 ;
DEA(DRUG) ; Return DEA value
 N DEA
 S DEA=+$$GET1^DIQ(50,DRUG,3)
 Q DEA
DEACLS(DEA,CLS) ; Return boolean value for comparison
 Q CLS[DEA
 ; Return Pharmacy Info for Activity Log
 ; Input - RXIEN - Prescription IEN
PHMINFO(RXIEN) ; EP -
 N PHM
 S PHM=$$GPHM^APSPES1(RXIEN)
 Q:'PHM "UNKNOWN"
 Q $$GET1^DIQ(9009033.9,PHM,.01)_"  "_$$HLPHONE^HLFNC($$GET1^DIQ(9009033.9,PHM,2.1))
 ;
 ; Check status of APSP REFIIL REQUEST entry
 ; Input: IEN - IEN
 ;        STA - Status to check (if not passed, set to -1 and return status value)
RREQSTAT(DATA,IEN,STA) ; EP -
 N RES
 S RES=$P($G(^APSPRREQ(IEN,0)),U,3)
 S:'$L($G(STA)) STA=-1
 S DATA=$S(STA=-1:RES,1:RES=STA)
 Q
 ; Return external text for diagnosis
GETDIAG(MSG) ; EP -
 N TXT,DATA,ARY,SEG,HLMSTATE,HDR,SEGIEN,SEGDG1,C,DX
 S TXT=""
 I '$$STARTMSG^HLOPRS(.HLMSTATE,MSG,.HDR) Q
 F  Q:'$$NEXTSEG^HLOPRS(.HLMSTATE,.SEG)  D
 .I $$GET^HLOPRS(.SEG,0)="DG1" D
 ..S TXT=$$GET^HLOPRS(.SEG,3,1)_" ("_$$GET^HLOPRS(.SEG,3,3)_")"
 ..I $L(TXT) S C=C+1,@RET@(C)=TXT
 Q DX
EFF(PRV) ;See if SPI is ACTIVE
 N EFF,IN
 S IN=1
 S EFF=9999999 F  S EFF=$O(^VA(200,PRV,"SPISTATUS",EFF),-1) Q:'+EFF  D
 .S IN=$P($G(^VA(200,PRV,"SPISTATUS",EFF,0)),U,2)
 Q IN
 ;SIG moved from APSPES2 for space issues
SIG(IEN,MTYP) ;Store SIG
 N FN,FDA,AIEN,ERR,X,SL,X2,SEGDATA,SEGIEN,DATA
 S X2=""
 S FN=9009033.913
 I MTYP="R" S SEG="RXD",FLD=9
 E  S SEG="RXE",FLD=7
 D PARSE^APSPES2(.DATA,HLMSGIEN,.HLMSTATE)
 S SEGIEN=$$FSEGIEN^APSPES1(.DATA,SEG)
 Q:'SEGIEN
 M SEGDAT=DATA(SEGIEN)
 ;S X=$S(MTYP="R":$$GETVAL^APSPES2(MSGIEN,"RXD",9,X1),1:$$GETVAL^APSPES2(MSGIEN,"RXE",7,X1))  Q:X=""  D         ; SIG
 S CNT=1
 F  S SL=$$GET^HLOPRS(.SEGDAT,FLD,"","",CNT) Q:SL=""  D
 .S AIEN="+"_CNT_","_IEN_","
 .S FDA(FN,AIEN,.01)=SL
 .S CNT=CNT+1
 D UPDATE^DIE(,"FDA","AIEN","ERR")
 K ERR
 Q
GETVAL2 ;Get the value of a segment
 N DATA,HLMSTATE,ARY,SEGIEN,SEGARY
 S OFF=$G(OFF,1)
 D PARSE^APSPES2(.DATA,MSG,.HLMSTATE)
 Q:'$D(DATA) ""
 S SEGIEN=$$FSEGIEN^APSPES1(.DATA,SEG)
 Q:'SEGIEN ""
 M SEGARY=DATA(SEGIEN)
 Q $$GET^HLOPRS(.SEGARY,FLD,OFF)
 ;Diagnosis data moved here for space issues
DIAG(MSGIEN,RXIEN) ;Store the Diagnosis
 S DXCODE=$$GETVAL^APSPES2(MSGIEN,"DG1",3,1)
 S DX=$$GETVAL^APSPES2(MSGIEN,"DG1",3,2)
 ;IHS/MSC/MGH add DX from RX if RX exists and not in msg
 I +RXIEN&(DXCODE="") S DXCODE=$$GET1^DIQ(52,+RXIEN,9999999.22)
 ;Patch 1023 IHS/MSC/MGH REPLACE DECIMALS FROM ICD10 CODES
 I DXCODE'["."&(DXCODE'="") D
 .N FIRST,SECOND
 .S FIRST=$E(DXCODE,1,3),SECOND=$E(DXCODE,4,$L(DXCODE))
 .S DXCODE=FIRST_"."_SECOND
 I DX=""&(DXCODE'="") D
 .I $$AICD^BGOUTL2 S DX=$P($$ICDDX^ICDEX(DXCODE,DT),U,4)
 .E  S DX=$P($$ICDDX^ICDCODE(DXCODE,DT),U,4)
 S FDA(FN,I,7.1)=DX
 S FDA(FN,I,7.2)=DXCODE
 ;Add in SNOMED code
 I +RXIEN D
 .S ORIFN=$$GET1^DIQ(52,+RXIEN,39.3)
 .I +ORIFN S FDA(FN,I,7.3)=$$VALUE^ORCSAVE2(+ORIFN,"SNMDCNPTID")
 Q
SHIFT(I,J) ;
 I '$D(SEG(I)) S I=$O(SEG(0)) Q:'I
 I $L(LINE(J))<255 D
 .N LEN
 .S LEN=$L(LINE(J))
 .S LINE(J)=LINE(J)_$E(SEG(I),1,255-LEN)
 .S SEG(I)=$E(SEG(I),256-LEN,9999)
 .I SEG(I)="" K SEG(I)
 E  D
 .S J=J+1
 .S LINE(J)="-"
 D SHIFT(.I,.J)
 Q
 ; Returns Pharmacy related to request
 ; If not found to exist in APSP PHARMACY LIST a
 ; temporary entry will be made.
GETPHM() ;-
 N P1,P2,P5,FDA,IENS,IEN,ERR,PHM
 S P1=0
 S P1=$$GETVAL^APSPES2(MSGIEN,"RXE",40,1)
 S P1(2)=$$GETVAL^APSPES2(MSGIEN,"RXE",40,2)
 S P1(4)=$$GETVAL^APSPES2(MSGIEN,"RXE",40,4)
 S P2=$$GETVAL^APSPES2(MSGIEN,"RXE",41,1)
 S P2(2)=$$GETVAL^APSPES2(MSGIEN,"RXE",41,2)
 S P2(3)=$$GETVAL^APSPES2(MSGIEN,"RXE",41,3)
 S P2(4)=$$GETVAL^APSPES2(MSGIEN,"RXE",41,4)
 S P2(5)=$$GETVAL^APSPES2(MSGIEN,"RXE",41,5)
 S P5=$$BLDPHN(MSGIEN,"RXE",45)
 S:P1 PHM=+$$FIND1^DIC(9009033.9,,"O",P1,"C")
 Q:PHM PHM
 N PNUM,FNUM
 S (PNUM,FNUM)=""
 S IENS="+1,"
 S FDA(9009033.9,IENS,.01)=P1(2)  ;NAME
 S FDA(9009033.9,IENS,.02)=P1    ;NCPDPID
 S FDA(9009033.9,IENS,.04)=P1(4)  ;NPI
 S FDA(9009033.9,IENS,.11)="YES"  ;Temporary entry
 S FDA(9009033.9,IENS,1.1)=P2     ;Address1
 S FDA(9009033.9,IENS,1.2)=P2(2)  ;Address2
 S FDA(9009033.9,IENS,1.3)=P2(3)  ;City
 S FDA(9009033.9,IENS,1.4)=P2(4)  ;State
 S FDA(9009033.9,IENS,1.5)=P2(5)  ;Zipcode
 S FDA(9009033.9,IENS,2.1)=$$GETPHN(P5,"PH")    ;Primary Phone Number
 S FDA(9009033.9,IENS,2.2)=$$GETPHN(P5,"FX")    ;Fax Number
 D UPDATE^DIE("E","FDA","IEN","ERR")
 Q:$D(ERR) ""
 Q +$G(IEN(1))
GETPHN(STR,TYPE) ;-
 N PHN,RES
 S RES=""
 F LP=1:1:$L(STR,"~") S PHN=$P(STR,"~",LP) Q:'$L(PHN)  D  Q:RES'=""
 .I $P(PHN,U,3)=TYPE S RES=$P(PHN,U)
 Q $S(TYPE="FX"&(RES=""):"5555555555",1:RES)
BLDPHN(MSGIEN,SEG,FLD) ;-
 N LP,VAL
 S VAL="",RET=""
 F LP=0:1 S VAL=$$GETVAL^APSPES2(MSGIEN,SEG,FLD,1,LP) Q:VAL=""  D
 .S RET=RET_VAL_U_$$GETVAL^APSPES2(MSGIEN,SEG,FLD,2,LP)_U_$$GETVAL^APSPES2(MSGIEN,SEG,FLD,3,LP)_"~"
 Q RET
