APSPESG ;IHS/MSC/MGH - Process entries from APSP REFILL REQUEST file ;16-May-2024 09:08;DU
 ;;7.0;IHS PHARMACY MODIFICATIONS;**1016,1023,1024,1026,1027,1028,1035**;Sep 23,2004;Build 39
 ;==================================================================
 ;RPC calls for refill request component
 ;Input: FILTER - string containing status values
 ;         TCHK - Flag indicating type of date check
 ;                0 - no date check (default)
 ;                1 - Message Date
 ;                2 - Last Updated Date ( used for denied entries)
 ;        START - Start date (earliest date)
 ;         STOP - Stop date (most recent date)
 ;        RTYPE - Request Type (defaults to RENEW)
GETLIST(RET,FILTER,TCHK,START,STOP,RTYPE) ; -- Return list of unprocessed refills
 N IEN,CNT,RRDATE,X1,X2,X,STAT,XREF
 S RET=$$TMPGBL()
 S FILTER=$G(FILTER,"01456")
 S RTYPE=$G(RTYPE,"R")  ;P1024
 S START=$G(START),STOP=$G(STOP)
 S XREF=""
 S CNT=0
 I ((START=0)&(STOP=0))!(TCHK=2) D
 .S XREF="F"
 .F I=1:1:$L(FILTER) D
 ..S STAT=$E(FILTER,I,I)
 ..S IEN=0 F  S IEN=$O(^APSPRREQ(XREF,STAT,IEN)) Q:'+IEN  D SEARCH(IEN)
 E  D
 .I '+START S X1=DT,X2=-90 D C^%DTC S START=X
 .I '+STOP S STOP=DT
 .S STOP=STOP+.9
 .S XREF="D"
 .S RRDATE=START-.0001 F  S RRDATE=$O(^APSPRREQ(XREF,RRDATE)) Q:'RRDATE!(RRDATE>STOP)  D
 ..Q:RRDATE<START
 ..; do not display if the status is 'processed', there is an OERR order number, or the HL7 data is misisng
 ..;I $P(^APSPRREQ(IEN,0),U,2)!('$O(^APSPRREQ(IEN,5,0))) Q
 ..S IEN=0 F  S IEN=$O(^APSPRREQ("D",RRDATE,IEN)) Q:'+IEN  D SEARCH(IEN)
 Q
SEARCH(IEN) ;Add if criteria met
 Q:'$$TYPE(IEN,RTYPE)
 Q:'$$CANSHOW(IEN,FILTER)
 I XREF="F" Q:'$$MATCHDT(IEN,TCHK,START,STOP)  ;Not needed since looping on D X-ref
 S CNT=CNT+1
 S @RET@(CNT)=$$GETITM(IEN,FILTER)
 Q
 ; Return string containing data for a single item
GETITM(IEN,FILTER) ;EP-
 ;Array will include IEN [1] ^ MESSAGE ID;STATUS [2] ^ IEN;PATIENT NAME  (DOB)[3] ^ DRUG NAME[4] ^ DATE [5] ^ PHARMACY [6] ^ PHARMACY ZIP [7] ^
 ;   PROVIDER ID (IEN;NAME) [8] ^ LOCATION ID (IEN;NAME) [9] ^
 ;IEN_U_MSGID_";"_IND_U_PATNAME_U_DRUG_U_ITMDATE_U_PHARMNM_U_PHARMZIP_U_PRVID_U_LOCID
 N LINE,MSGID,SEG,HLDATA,APSPMSH,APSPPID,APSPORC,APSPRX0,APSPRXE,APSPZSF,APSPRXO,APSPRXD,DRUG,PAT,PATLN,PATFN,LINEVAR,ITMDATE
 N PATNAME,STAT,PIEN,PNAM,PPHN,PADDR,IND,PTID,PRVID,PTPHN,DNYDT,DNYDTF,DNYUSR,DNYRSN,MATCH,REQTYPE,PADD,PFAX
 N HLECH,CS,REP,ESCAPE,SUBCOMP,DEL,RET,PTNAM,ORIFN,CHGTYP,ITMDTFMT,LOCID,NTPHM,ORDINFO,CHGTYPE,RXIENOID
 S STAT=+$$GET1^DIQ(9009033.91,IEN,.03,"I")
 S MSGID=$$GET1^DIQ(9009033.91,IEN,.01,"E"),HLMSG=$$GHLDAT(IEN)
 S DEL="|"
 D SHLVARS
 S HLECH=$P(APSPMSH,DEL,2) I '$L(HLECH) S HLECH="^~\&"
 S CS=$E(HLECH,1)
 S REP=$E(HLECH,2)
 S ESCAPE=$E(HLECH,3)
 S SUBCOMP=$E(HLECH,4)
 S PATNAME=$$PATNAME^APSPESG3(APSPPID)  ; From HL7 Message content
 S PTPHN=$$GETPPHN(IEN)
 S DRUG=$$DRGNAME(APSPRXE,IEN)
 S ORIFN=$$GET1^DIQ(9009033.91,IEN,.02,"I")  ;P24
 S ITMDATE=$$GET1^DIQ(9009033.91,IEN,.04,"I")
 S ITMDTFMT=$$FMTE^XLFDT(ITMDATE,"5Z")
 S ITMDTFMT=$TR(ITMDTFMT,"@"," ")
 S (DNYDT,DNYDTF,DNYUSR,DNYRSN)=""
 I STAT=3 D
 .S DNYDT=$$GET1^DIQ(9009033.91,IEN,.07,"I")
 .S DNYDTF=$$FMTE^XLFDT(DNYDT,"5Z")
 .S DNYDTF=$TR(DNYDTF,"@"," ")
 .S DNYUSR=$$GET1^DIQ(9009033.91,IEN,.09)
 .S DNYRSN=$$GET1^DIQ(9009033.91,IEN,4)
 S PIEN=$$GET1^DIQ(9009033.91,IEN,1.7,"I")
 S PNAM=$$GET1^DIQ(9009033.9,PIEN,.01)
 S PTNAM=$$GET1^DIQ(9009033.91,IEN,1.2)
 S PPHN=$$FMTPHN^APSPES2($$GET1^DIQ(9009033.9,PIEN,2.1))  ;Pharmacy Phone
 S PFAX=$$FMTPHN^APSPES2($$GET1^DIQ(9009033.9,PIEN,2.2))  ;Pharmacy Fax
 S PADD=$$PADDR^APSPESG1(PIEN)
 S IND=$S(STAT=6:5,STAT=4:4,STAT=1:13,1:3)
 S PTID=$$GET1^DIQ(9009033.91,IEN,1.2,"I")_";"_$$GET1^DIQ(9009033.91,IEN,1.2)
 S PRVID=$$GET1^DIQ(9009033.91,IEN,1.3,"I")_";"_$$GET1^DIQ(9009033.91,IEN,1.3)
 S LOCID=$$GET1^DIQ(9009033.91,IEN,1.6,"I")_";"_$$GET1^DIQ(9009033.91,IEN,1.6)
 S MATCH=$$GET1^DIQ(9009033.91,IEN,.11)
 S ORDINFO=$$ORD(IEN)  ;Order details D:30 QTY:30 RF:2 DAW:No  Indication: 401.9
 S NTPHM=$$GET1^DIQ(9009033.91,IEN,4.1)  ;Notes to Pharmacist
 S REQTYPE=$$GET1^DIQ(9009033.91,IEN,.12,"I")
 S CHGTYPE=$$GET1^DIQ(9009033.91,IEN,7.4,"I")
 S RXIENOID=$$GET1^DIQ(9009033.91,IEN,.06,"I")
 S:RXIENOID RXIENOID=RXIENOID_";"_$$GET1^DIQ(52,RXIENOID,39.3,"I")_";"_$$GET1^DIQ(52,RXIENOID,2,"I")
 S RET=IEN_U_MSGID_";"_IND_U_PATNAME_U_DRUG_U_ITMDATE_";"_ITMDTFMT_U_PIEN_";"_PNAM_U_PPHN_";"_PFAX
 Q RET_U_PTID_U_PRVID_U_LOCID_U_$$GETSIG(IEN)_U_PTPHN_U_PADD_U_DNYDT_";"_DNYDTF_U_DNYUSR_U_DNYRSN_U_MATCH_U_ORDINFO_U_NTPHM_U_$$GMATCHI(IEN)_U_REQTYPE_U_CHGTYPE_U_$S($L(PTNAM):PTNAM,1:$P(PATNAME,";",2))_U_STAT_U_ORIFN_U_RXIENOID
 ;
SHLVARS ; Set up HL segment data
 N SEGTYP,VAR
 F SEGTYP="MSH","PID","ORC","RXO","RXE","RXR","RXD","RXC","DG1","ZSF" S VAR="APSP"_SEGTYP,@VAR="",@VAR=$$GETSEG(.HLDATA,SEGTYP)
 Q
 ; Input:  DATA - HL7 data from APSP REFILL REQUEST file
 ;         TYPE - Message segment requested
GETSEG(DATA,TYPE) ;
 N X,RET,DAT,Q
 S RET="",(X,Q)=0 F  S X=$O(DATA(X)) Q:'X!(Q)  D
 .S DAT=$G(DATA(X)) I DAT="" S RET="" Q
 .I $P(DAT,"|")=TYPE S RET=$$PACKSEG(),Q=1 Q
 Q RET
PACKSEG() ;
 N RES,LP,STOP
 S STOP=0
 S RES=DAT
 S LP=X F  S LP=$O(DATA(LP)) Q:'LP!(STOP=1)  D
 .Q:DATA(LP)=""
 .I $E(DATA(LP),1,4)?1U2UN1"|" S STOP=1 Q  ;Found next segment
 .S RES=RES_DATA(LP)
 Q RES
 ; Return Drug Name or mapped Orderable Item
DRGNAME(APSPRXE,IEN) ;EP-
 N RET
 S RET=$$GET1^DIQ(9009033.91,IEN,1.1,"I")
 Q:RET>0 RET_";"_$$DESCAPE($P($P(APSPRXE,"|",3),U,2))
 S RET=$$DESCAPE($P($P(APSPRXE,"|",3),U,2)) I '$L(RET) Q ";"
 Q ";"_$TR(RET,";",":")
ORD(IEN) ;Order details D:30 QTY:30 RF:2 DAW:No  Indication: 401.9
 N SUP,QTY,REF,DAW,IND,SNO
 S SUP=+$$GET1^DIQ(9009033.91,IEN,1.5)
 S QTY=+$$GET1^DIQ(9009033.91,IEN,1.4)
 S REF=+$$GET1^DIQ(9009033.91,IEN,1.9)
 S DAW=$$GET1^DIQ(9009033.91,IEN,1.12)
 S IND=$$GET1^DIQ(9009033.91,IEN,7.3)
 S SNO=$P($$CONC^BSTSAPI(IND),U,4)
 Q "D:"_SUP_" QTY:"_QTY_" RF:"_REF_" DAW:"_DAW_" Indication: "_SNO
DUPS(IEN) ;Return if there are duplicate entries
 N CNT,SSNUM,NIEN,OLDVAL,NEWVAL,TYPE,HLMSG
 S CNT=0
 ;IHS/MSC/MGH 7/12/2019 changed to find most recent request
 S SSNUM=$$GET1^DIQ(9009033.91,IEN,.1)
 Q:SSNUM="" 0
 S NIEN=0 F  S NIEN=$O(^APSPRREQ("G",SSNUM,NIEN)) Q:'+NIEN  D
 .I NIEN'=IEN D
 ..S TYPE=$$GET1^DIQ(9009033.91,IEN,7.4)
 ..I TYPE'="" D
 ...S OTYPE=$$GET1^DIQ(9009033.91,NIEN,7.4)
 ...I OTYPE=TYPE D
 ....I TYPE="U" D
 .....;Get the data from the new message
 .....S HLMSG=$$GHLDAT^APSPESG1(IEN)
 .....D SHLVARS^APSPESG
 .....S NEWVAL=$P(APSPZSF,"|",2)
 .....;get the data from the old message
 .....S HLMSG=$$GHLDAT^APSPESG1(NIEN)
 .....D SHLVARS^APSPESG
 .....S OLDVAL=$P(APSPZSF,"|",2)
 .....;its a dup if they match
 .....I OLDVAL=NEWVAL S CNT=CNT+1
 ....E  S CNT=CNT+1
 ..E  S CNT=CNT+1
 Q CNT
GHLDAT(IEN) ; Get HL7 message data from APSP REFILL REQUEST FILE
 N HLMSG
 S HLMSG=$$GET1^DIQ(9009033.91,IEN,5,"","HLDATA")
 Q HLMSG
TMPGBL() ;EP
 K ^TMP("APSPESG",$J) Q $NA(^($J))
 ; Return boolean flag if a match on request type
TYPE(IEN,TYPE) ;EP-
 N TYP
 S TYP=$P($G(^APSPRREQ(IEN,0)),U,12)
 Q $S(TYP="":1,TYPE[TYP:1,1:0)
 ; Return boolean flag if a match on request change type
CHGTYP(IEN,TYPE) ;EP-
 Q $P($G(^APSPRREQ(IEN,7)),U,4)=TYPE
 ; Return boolean flag if entry matches status filter
CANSHOW(IEN,FILTER) ;EP -
 N STA
 S STA=+$P(^APSPRREQ(IEN,0),U,3)
 Q $S(FILTER[STA:1,1:0)
 ; Return boolean flag if entry matches date range criteria
MATCHDT(IEN,TYPE,START,STOP) ;EP-
 Q:'TYPE 1  ; date check not requested
 N RES,N0,LD,MD,ACT
 S STOP=STOP+.99
 S N0=^APSPRREQ(IEN,0),MD=$P(N0,U,4),LD=$P(N0,U,7),ACT=$P(N0,U,8)
 S RES=1
 I TYPE=1 D  ; Message Date
 .I (MD<START)!(MD>STOP) S RES=0
 E  I TYPE=2 D  ; Last Updated (.07) and Activity Action is either a 3 or 4
 .I (LD<START)!(LD>STOP)!("34"'[ACT) S RES=0
 Q RES
 ; Return Match Details
GMATCHI(IEN) ;EP-
 N MATCH,TXT,CNT,STRING,X
 S STRING="",CNT=0,TXT=""
 S X=$$DUPS(IEN)   ;Check for duplicate entries
 I X>0 D
 .S TXT="Duplicate Request ("_X_")" D ADD(TXT,.STRING)
 S MATCH=$$GET1^DIQ(9009033.91,IEN,.11)
 I MATCH["Z" S TXT="This order can only be denied. Invalid order number." D ADD(TXT,.STRING)
 I MATCH'["O" S TXT="Failed to map Order Number" D ADD(TXT,.STRING)
 I MATCH'["D" S TXT="Failed to map Prescriber" D ADD(TXT,.STRING)
 I MATCH'["M" S TXT="Failed to map Med" D ADD(TXT,.STRING)
 I MATCH'["P" S TXT="Failed to map Patient" D ADD(TXT,.STRING)
 I $$GET1^DIQ(9009033.91,IEN,.12,"I")="C" D  ;RxChange
 .N STATUS
 .S STATUS=$$GET1^DIQ(9009033.91,IEN,.03,"I")
 .S TXT=$S(STATUS=1:"Unsigned",STATUS=0:"Pending review",STATUS=6:"Pending review",1:"")  ;p1026 - pls
 .D:$L(TXT) ADD(TXT,.STRING)
 .I MATCH["Z"!(MATCH'["D") D ADD("[DENY ONLY]",.STRING)
 .E  I "45"[STATUS D ADD("[MAP OR DENY]",.STRING)
 E  I FILTER'=16 D
 .I MATCH["Z"!(MATCH'["D") S TXT="[DENY ONLY]" D ADD(TXT,.STRING)
 .E  S TXT="[MAP OR DENY]" D ADD(TXT,.STRING)
 Q STRING
ADD(TXT,STRING) ;EP-
 S CNT=CNT+1
 I CNT>1 S STRING=STRING_";"_TXT
 E  S STRING=TXT
 Q
 ; Return details of the SureScript Request
 ; Input: IEN - IEN to APSP REFILL REQUEST file
DETAIL(DATA,IEN) ; EP-
 D DETAIL^APSPESG3(.DATA,IEN)
 Q
 ; Supports the mapping process
 ; Update entry
 ; Input: IEN - IEN to APSP Refil Request File
 ;        FLD - Field number
 ;        VAL - Value to set
 ;      NOSTS - Do not update status
STORE(DATA,IEN,FLD,VAL,NOSTS) ;EP-
 N FDA,ERR,FILTER,STAT
 S FILTER=$G(FILTER,0)
 S NOSTS=+$G(NOSTS)
 S FDA(9009033.91,IEN_",",FLD)=VAL
 I FLD=1.2!(FLD=1.3) D
 .S STAT=$$STATCHK^APSPESG1(IEN)  ;See if status is now complete
 .S FDA(9009033.91,IEN_",",.03)=STAT
 S:FLD=".08" FDA(9009033.91,IEN_",",.09)=$G(DUZ)
 I 'NOSTS D
 .Q:(FLD=1.2)!(FLD=1.3)  ;p1026
 .S:$P($G(^APSPRREQ(IEN,0)),U,3)'=4 FDA(9009033.91,IEN_",",.03)=4
 D FILE^DIE("K","FDA","ERR")
 I '$D(ERR) S DATA=$$GETITM(IEN,FILTER)
 E  S DATA="0^Unable to update log"
 Q
 ; Return value for file/field
GETVAL(DATA,FIL,IEN,FLD,FLG) ;EP-
 S DATA=$$GET1^DIQ(FIL,IEN,FLD,.FLG)
 Q
 ; Update entry with medication dosing information
STOREDOS(DATA,IEN,FLDARY) ;EP-
 N FDA,ERR
 I 'IEN!'$D(FLDARY) S DATA="1^INSUFFICIENT DATA TO STORE"
 D FILE^DIE("K","FDA","ERR")
 I '$D(ERR) S DATA=1
 E  S DATA="0^"_$G(ERR)
 Q
 ; Returns subset of active providers having a SPI number.
NPSPI(DATA,FROM,DIR,MAX,RTYP) ;EP-
 N IEN,CNT,LEVEL
 S FROM=$G(FROM),DIR=$G(DIR,1),MAX=$G(MAX,44),CNT=0
 F  S FROM=$O(^VA(200,"B",FROM),DIR),IEN="" Q:FROM=""  D:$E(FROM)'="*"  Q:CNT'<MAX
 .F  S IEN=$O(^VA(200,"B",FROM,IEN),DIR) Q:'IEN  D
 ..I $G(RTYP)="C" S LEVEL=$O(^APSPNCP(9009033.75,"B","Change",""))
 ..I $G(RTYP)="R" S LEVEL=$O(^APSPNCP(9009033.75,"B","Refill",""))
 ..I RTYP'="" D
 ...I $D(^XUSEC("PROVIDER",IEN)),$$ACTIVE^XUSER(IEN),$$AUTH(IEN),$$SPI^APSPES1(IEN),$$ACTLVL^APSPES9(IEN,LEVEL) S CNT=CNT+1,DATA(CNT)=IEN_U_FROM
 ..E  D
 ...I $D(^XUSEC("PROVIDER",IEN)),$$ACTIVE^XUSER(IEN),$$AUTH(IEN),$$SPI^APSPES1(IEN) S CNT=CNT+1,DATA(CNT)=IEN_U_FROM
 Q
 ; Return authorization of user to write meds
AUTH(PRV) ;EP-
 N RES
 D AUTH^ORWDPS32(.RES,PRV)
 Q 'RES
 ; Return mapping details for a given entry
GETREC(DATA,IEN) ;EP-
 N REC,TXT,CNT
 S DATA=$$TMPGBL,CNT=1
 I '$D(^APSPRREQ(IEN,0)) S DATA(0)="1^RECORD NOT FOUND"
 S REC=$G(^APSPRREQ(IEN,1))
 S @DATA@(0)=0
 S @DATA@(CNT)=$P(REC,U)_";"_$$GET1^DIQ(101.43,+$P(REC,U),.01)_U_$P(REC,U,4)_U_$P(REC,U,5)_U_$$GETDRUG(IEN)
 S CNT=CNT+1
 D ADDMISIG(2)
 D ADDMISIG(3)
 Q
 ; Adds Medication Instructions and SIG to output array
ADDMISIG(NODE) ;EP-
 N LP
 S LP=0 F  S LP=$O(^APSPRREQ(IEN,NODE,LP)) Q:'LP  D
 .S TXT=$G(^APSPRREQ(IEN,NODE,LP,0))
 .Q:'$L(TXT)
 .S CNT=CNT+1
 .S @DATA@(CNT)=$S(NODE=2:"d~",NODE=3:"s~",1:"")_TXT
 Q
 ;
GETDRUG(IEN) ;EP-
 N DLM,HLECH,I,HLMSG,TYPE,DRG
 D HL7INIT(IEN)
 Q $P($P($G(APSPRXE),DLM,3),U,2)
 ; Return Patient Phone Number from HL7 context
GETPPHN(IEN) ;EP-
 N DLM,HLECH,I,HLMSG
 D HL7INIT(IEN)
 Q $$FMTPHN^APSPES2($$DESCAPE($P($P(APSPPID,DLM,14),HLECH(1),1)))
 ; Return SIG from Request entry
GETSIG(IEN) ;-
 N SIGI,SIGDAT
 S SIGI=0
 S SIGDAT=""
 F  S SIGI=$O(^APSPRREQ(IEN,3,SIGI)) Q:'+SIGI  D
 .I SIGDAT="" S SIGDAT=$G(^APSPRREQ(IEN,3,SIGI,0))
 .E  S SIGDAT=SIGDAT_" "_$G(^APSPRREQ(IEN,3,SIGI,0))
 Q SIGDAT
 N DLM,HLECH,I,HLMSG,SIG,PIECE,SIGX,X1
 S SIG=""
 D HL7INIT(IEN)
 ;S SIG=$$DESCAPE($P($P(APSPRXE,DLM,8),HLECH(1),1))
 S PIECE=$P(APSPRXE,DLM,8)
 S X1=1
 F  S SIGX=$P(PIECE,"~",X1) Q:SIGX=""  D
 .I SIG="" S SIG=SIGX
 .E  S SIG=SIG_" "_SIGX
 .S X1=X1+1
 Q SIG
 ;
 ; Return count and patient flag - used by REFREQ CIA EVENT
 ; IHS/MSC/PLS - Patch 1035 Moved block to APSPESG3 FID 106476
QUECHECK(DFN) ;EP-
 Q $$QUECHECK^APSPESG3($G(DFN))
 ;
QUEVWCNT(DATA,DFN) ;EP-
 S DATA=$$QUECHECK(DFN)
 Q
 ; Return data for a given IEN to refresh the ListView
GETIDATA(DATA,IEN,FILTER) ;EP-
 S FILTER=$G(FILTER,0)
 I $G(IEN) S DATA=$$GETITM(IEN,FILTER)
 E  S DATA="0^Unable to obtain information"
 Q
 ; Init HL7 variables
HL7INIT(IEN) ;EP--
 S DLM="|"
 S HLECH="^~\&"
 F I=1:1:4 D
 .S HLECH(I)=$E(HLECH,I)
 S HLMSG=$$GHLDAT^APSPESLP(IEN) D SHLVARS^APSPESLP
 Q
 ;Change provider on a refill request that has been processed
CHGPRV(DATA,IEN,PRVIEN) ;EP
 N ORID,ORNP,ORL,ORVP,REASON,REC,DATA,PRMT,FDA,ORDUZ
 S REASON="" S REASON=$O(^ORD(100.03,"B","Obsolete Order",REASON))
 S ORID=$$GET1^DIQ(9009033.91,IEN,.02,"I")
 S ORNP=$$GET1^DIQ(9009033.91,IEN,1.3,"I")
 S ORL=$$GET1^DIQ(9009033.91,IEN,1.6,"I")
 S ORVP=$$GET1^DIQ(9009033.91,IEN,1.2,"I")
 S ORDUZ=DUZ
 S PRMT="OR GTX SSRREQIEN"
 ;IHS/MSC/MGH with patch 1026, the order is now being created later in the process so this code is not needed
 ;D RESP^ORCSAVE2(ORID,PRMT,"ZZ")
 ;Delete the old order
 ;D DC^ORWDXA(.REC,ORID,ORNP,ORL,REASON,0,1)
 ;Kill the alert
 ;N XQAKILL,ORNIFN
 ;S ORNIFN=$O(^ORD(100.9,"B","SS REFILL REQUEST SIGNATURE",0))
 ;S XQAKILL=$$XQAKILL^ORB3F1(ORNIFN) ; unsigned orders notif
 ;S XQAID=$P($G(^ORD(100.9,ORNIFN,0)),U,2)_","_+ORVP_","_ORNIFN D DELETEA^XQALERT K XQAID
 ;S ORNIFN=$O(^ORD(100.9,"B","ORDER REQUIRES ELEC SIGNATURE",0))
 ;S XQAKILL=$$XQAKILL^ORB3F1(ORNIFN) ; unsigned orders notif
 ;S XQAID=$P($G(^ORD(100.9,ORNIFN,0)),U,2)_","_+ORVP_","_ORNIFN D DELETEA^XQALERT K XQAID
 ;Update the APSP Refill request file
 S FDA(9009033.91,IEN_",",.02)="@"
 S FDA(9009033.91,IEN_",",.07)=$$NOW^XLFDT()
 S FDA(9009033.91,IEN_",",1.3)=PRVIEN
 S FDA(9009033.91,IEN_",",1.11)=1
 D FILE^DIE("","FDA","ERR")
 ;Redo the order
 ;D PROCESS^APSPESG2(.DATA,IEN)
 Q
DESCAPE(VALUE) ;remove escape characters from value
 N STRING
 S STRING=$$DESCAPE^HLOPRS1(VALUE,DEL,CS,SUBCOMP,REP,ESCAPE)
 Q STRING
