APSPLBL1 ; IHS/DSD/ENM - PRINTS LABEL ;  [ 01/13/2003  11:09 AM ]
 ;;6.0;IHS PHARMACY MODIFICATIONS;**1,3,4**;11/11/2002
 ;NOTE: VA Patches 31,66,60,59 not installed in this rtn IHS/DSD/ENM 3.9.94
EP ;      This IHS routine is a rewrite of and not the same as the 
 ;      VA PSOLBL1 rtn.
 ;SWITCH FOR NDC NUMBER PRINTING IHS/OKCAO/POC 11/11/2002
Z S L=$L(PSZRM) I $L(SGY(SGC))+L+1<PSZW S SGY(SGC)=SGY(SGC)_$E("                              ",1,PSZW-L-1-$L(SGY(SGC)))_PSZRM
 E  S SGC=SGC+1,SGY(SGC)=$E("                                        ",1,PSZW-L-2)_PSZRM
START S N="",COPIES=COPIES-1 F I=1:1:PSZB W !
 S PSZZL=4 I $D(LEXDT),LEXDT]"" S PSZZL=5  ;IHS/BAO/JCM 7/21/88 SETS #OF PRINTABLE LINES AVAILABLE FOR SIG TO PRINT ON
 S:APSPMAN=1!(APSPMAN=2) PSZZL=PSZZL+1
 S PSZLA=PSZL-PSZZL
 W !,?PSZTAB,$E(PNM,1,PSZW-8),?(PSZW+PSZTAB)-6 I $D(^AUPNPAT(DFN,41,+$P(PS,"^",6),0)) W $P(^(0),"^",2)
SIG ;
 G CON:PSZLA<SGC F DR=1:1:PSZLA D SIG1
 G NEXT
CON S (DR,F)=0
C1 F I=1:1:PSZL-2 S DR=DR+1 D SIG1 Q:'$D(SGY(DR+1))
 I '$D(SGY(DR+1))&(I>PSZLA) F II=1:1:(PSZL-2-I) W !
 I '$D(SGY(DR+1)) G NEXT:F&(I'>PSZLA)
 W !,?PSZTAB,"****  CONTINUED  ****" S F=1
 F I=1:1:PSZE+PSZB W !
 W !,?PSZTAB,"****  CONTINUED  ****" S PSZM=$S(PSZLA-(SGC-DR)'<0:PSZLA-(SGC-DR),1:0) F I=1:1:PSZM W !
 G C1:DR<SGC
 ;IHS/BAO/JCM;8/30/88 ABOVE SETS # OF PRINTABLE LINES FOR FORM FEED
NEXT W !,?PSZTAB,DRUG S PSZQ="#"_$P(RXY,"^",7)_" "_APS("DISP UNITS") I $X+$L(PSZQ)+2<PSZW W "  ",PSZQ S PSZQ=""
 ;W !,?PSZTAB,"Rx ",RXN,?(PSZTAB+10),TECH,?(PSZTAB+16),PSZQ
 ;BEGIN CHANGES FOR NDC NUMBER TO BE DISPLAYED IHS/OKCAO/POC 9/17/2001
 ;W !,?PSZTAB,"Rx ",RXN,?$X+1,TECH,?(PSZTAB+16),PSZQ ;IHS/OKCAO/POC 8/18/2000 ALWAYS HAVE A SPACE BETWEEN RX# AND CLERK CODE
 I +$G(APSQDNDC)=0 W !,?PSZTAB,"Rx ",RXN,?$X+1,TECH,?(PSZTAB+16),PSZQ  ;IHS/OKCAO/POC 8/18/2000 ALWAYS HAVE A SPACE BETWEEN RX# AND CLERK CODE
 E  D
 .S APSPZREF=+$O(^PSRX(RX,1,"A"),-1)
 .S APSPZNDC=$S(APSPZREF:$P($G(^PSRX(RX,1,APSPZREF,0)),U,13),1:$P($G(^PSRX(RX,2)),U,7))  ;IHS/OKCAO/POC 9/17/2001 NEED NDC NUMBER
 .W !,?PSZTAB,"Rx ",RXN," ["_APSPZNDC_"]",?$X+1,TECH,?(PSZTAB+16),PSZQ  ;IHS/OKCAO/POC 8/18/2000 ALWAYS HAVE A SPACE BETWEEN RX# AND CLERK CODE 9/17/2001 NEED NDC NUMBER
 .K APSPZNDC,APSPZREF  ;IHS/OKCAO/POC 9/17/2001 NEED NDC NUMBER
 ;END OF CHANGES FOR NDC NUMBER TO BE DISPLAYED IHS/OKCAO/POC 9/17/2001
 W !,?PSZTAB,$E(PHYS,1,17),?(PSZTAB+18),+$E(FDT,4,5),"-",$E(FDT,6,7),"-",$E(FDT,2,3)
 ;I $D(LEXDT),LEXDT]"" W !,?PSZTAB,"EXPIRES: "_LEXDT  ;PRINT LABEL EXPIRATION DATE
 I APSPMAN=1!(APSPMAN=2) W !,?PSZTAB,APSPMF_" "_APSPLOT_" Exp "_APSPDY  ;IHS/DSD/ENM 12/16/96 Manufacturer data for label 8/18/2000 IHS/OKCAO/POC
 F I=1:1:PSZE W !
 ;THE NEXT FEW LINE TESTS IF THE PRESCRIPTION IS A REFILL,RENEW OR
 ;A PARTIAL FOR USE IN PRINTING SUMMARY LABELS TO BE PLACED IN THE
 ;PATIENTS CHART.
 I $P(^APSPCTRL(PSOSITE,0),U,12)=1,COPIES=0 D SUMMARY
 ;
 I COPIES>0 S SIDE=1 G START
ZZE ;IHS/DSD/ENM NEXT 6 LINES ADDED FOR LBL NODE 12/1/95
 ;STORE LABEL PRINT NODE
 D NOW^%DTC S NOW=% K %,%H,%I S RXF=0 F I=0:0 S I=$O(^PSRX(RX,1,I)) Q:'I  S RXF=I
 S IR=0 F FDA=0:0 S FDA=$O(^PSRX(RX,"L",FDA)) Q:'FDA  S IR=FDA
 S IR=IR+1,^PSRX(RX,"L",0)="^52.032A^"_IR_"^"_IR
 S ^PSRX(RX,"L",IR,0)=NOW_"^"_$S($G(RXP):99-RXPI,1:RXF)_"^"_$S($G(PCOMX)]"":$G(PCOMX),1:"From RX number "_$P(^PSRX(RX,0),"^"))_$S($G(RXP):" (PARTIAL)",1:"")_$S($D(REPRINT):" (REPRINT)",1:"")_"^"_DUZ
 S ^PSRX(RX,"TYPE")=0 K RXF,IR,FDA,NOW,I
 ;I $P(PS1,"^",2) S ^PIM("I",RX,$S($D(RXP):6,1:RXF))=RX,^(0)=$P(^PSRX(RX,0),"^",1,14)_"^"_$S(RXF:2,1:1)_"^"_$P(^(0),"^",16,99)
END K %DT,ADDR,DEA,DR,DR1,DRX,DRUG,FDT,SGY,RXY,RXZ,RYY,RFLMSG,RFL,%H,COPIES,DOB,DRUG,LIM,LMI,LINE,PS,PS1,PS2,PSZZL,PSZLA,II,PSZM,INT,ISD,I1,MW,MAIL,STATE,SIDE,SSNP,SS,ST,ST1,PATST,PRTFL,PHYS,PNM,S,SL,SGC,APS("DISP UNITS") Q
 Q
 ;
SIG1 S X=$S($D(SGY(DR)):SGY(DR),1:"") W !,?PSZTAB,X
 Q
SUMMARY ;IHS/BAO/JCM;FEB 15,1988
 ;THESE LINES BUILD THE ARRAY FOR PRINTING A SUMMARY LABEL TO
 ;PLACE IN THE CHART OF REFILLS AND PARTIAL PRESCRIPTIONS.
 ;
 ;$E(PNM,1,PSZW-8) = THE PATIENTS NAME
 ;
 ;FDT = THE FILL DATE FOR THE PARTIAL OR REFILL
 ;
 ;THE NEXT THREE LINES SET UP THE DRUG NAME TAKING OFF
 ;ANY TAB,CAP,SOLN ABBREVIATIONS TO SAVE LENGTH
 F FIND=" TAB"," CAP"," SUSP"," SOLN"," SYRUP" I DRUG[FIND S END=$F(DRUG,FIND)-($L(FIND)+1) Q
 S:'$D(END) END=99
 S PSZDRUG=$E(DRUG,1,END)  ; = THE DRUG NAME
 S APSHRN=$S($G(^AUPNPAT(DFN,41,DUZ(2),0)):$P(^(0),U,2),1:"")
 ;
 ;RXN = THE PRESCRIPTION NUMBER
 ;
 ;$P(RXY,"^",10) = THE DIRECTIONS FOR THE
 ;PRESCRIPTION BEFORE EXPANSION FROM THE QUICK CODE
 ;
 ;$P(RXY,"^",7) = THE QUANTITY ISSUED
 ;
 S:'$D(ARRAY) N=0,APSPZZN=0
 S N=N+1,APSPZZN=APSPZZN+1
 ;S ARRAY(N)=$E(PNM,1,PSZW-8)_"^"_RXN_"^"_PSZDRUG_"^"_$P(RXY,"^",10)_"^"_+$P(RXY,"^",7)_"^"_+FDT_"^"_APSHRN
 S ARRAY(APSPZZN)=$E(PNM,1,PSZW-8)_"^"_RXN_"^"_PSZDRUG_"^"_$P(RXY,"^",10)_"^"_+$P(RXY,"^",7)_"^"_+FDT_"^"_APSHRN
 ;
 K FIND,END,PSZDRUG
 Q
