APSPES7 ;IHS/MSC/MGH - SureScripts HL7 interface - con't;17-May-2021 18:54;DU
 ;;7.0;IHS PHARMACY MODIFICATIONS;**1024,1026,1028**;Sep 23, 2004;Build 50
 ; Create a new RX from the dispensed medication
 ; Generate new Order
NEWORD(IEN,DFN,PROV,LOC) ;EP to return data
 N ROOT,CHKDOSE,DOSE,INST,ILST,I,ID,DLG,VAL,J,LIST,ORVP,ORNP,Y
 N ITEM,OI,EXT,INT,DATA,DRUG,CODE,DRCL,DIALOG,ITM,NORIFN,OLD
 ;N LOC
 K LST
 D DLGDEF^ORWDX1(.LIST,"PSO OERR")
 D GETS^DIQ(9009033.91,IEN,".01:1.9;2*;3*;4.1;4.2;7.1;7.2;7.3;7.6","I","INT")
 ;S LOC=$G(INT(9009033.91,IEN_",",1.6,"I"))
 S ILST=0
 S ITEM="" F  S ITEM=$O(LIST(ITEM)) Q:'+ITEM  D
 .S DATA=$G(LIST(ITEM))
 .Q:DATA=""
 .S DLG=$P(DATA,U,2),INST=1,ID=$P(DATA,U,1)
 .I ID="ORDERABLE" D
 ..S ITM=$$GET1^DIQ(9009033.91,IEN,1.1,"I")
 ..S LST(DLG,1)=ITM
 .I ID="URGENCY" S LST(DLG,1)=9
 .I ID="DRUG" D
 ..S DRUG=$G(INT(9009033.91,IEN_",",1.8,"I"))
 ..S LST(DLG,1)=DRUG
 .I ID="PICKUP" S LST(DLG,1)="E"
 .I ID="QTY" S LST(DLG,1)=$G(INT(9009033.91,IEN_",",1.4,"I"))
 .I ID="REFILLS" S LST(DLG,1)=$G(INT(9009033.91,IEN_",",1.9,"I"))-1
 .I ID="SCHEDULE" D SUB(1.8,DLG,INST,ID)
 .I ID="INSTR" D INSTR(DLG,INST,ID)
 .I ID="ROUTE" D SUB(1.7,DLG,INST,ID)
 .I ID="DAYS" D SUB(1.5,DLG,INST,ID)
 .I ID="DAW" S LST(DLG,1)=$G(INT(9009033.91,IEN_",",1.12,"I"))
 .I ID="CLININD" S LST(DLG,1)=$G(INT(9009033.91,IEN_",",7.1,"I"))
 .I ID="CLININD2" S LST(DLG,1)=$G(INT(9009033.91,IEN_",",7.2,"I"))
 .I ID="SNMDCNPTID" S LST(DLG,1)=$G(INT(9009033.91,IEN_",",7.3,"I"))
 .I ID="SSRREQIEN" S LST(DLG,1)=IEN
 .;I ID="SSDENYRSN" D NEW(DLG,INST,ID)
 .I ID="PHARMACY" S LST(DLG,1)=$G(INT(9009033.91,IEN_",",1.7,"I"))
 .I ID="STRENGTH" Q
 .I ID="SIG" D SIGTXT(DLG,INST,ID)
 .I ID="CONJ" D SUB(1.6,DLG,INST,ID)
 .I ID="SUPPLY" S LST(DLG,1)=$G(INT(9009033.91,IEN_",",1.5,"I"))
 .I ID="CMF" S LST(DLG,1)=$G(INT(9009033.91,IEN_",",7.6,"I"))
 .I ID="DOSE" D DOSE(DLG,INST,ID)
 .I ID="PI" D PITXT(DLG,INST,ID)
 .;S LST(DLG,1)=$G(INT(9009033.91,IEN_",",4.1,"I"))
 .I ID="COMMENT" D NOTES(DLG,INST,ID)   ;S LST(DLG,1)=$G(INT(9009033.91,IEN_",",4.2,"I"))
 S DIALOG=$O(^ORD(101.41,"B","PSO OERR",0))
 S ORVP=DFN_";DPT(",ORNP=PROV
 D SAVE^ORWD(.Y,DFN,PROV,$G(LOC),DIALOG,"N",.LST)
 I $G(Y) S NORIFN=$P($P($P(Y(1),U),";"),"~",2)
 I '$G(NORIFN) Q "0^Order not filed. Check data and try again."
 D EN^OCXOERR(DFN_U_+NORIFN_U_PROV_"^^^^^1")
 S FDA(9009033.91,IEN_",",.02)=NORIFN
 S FDA(9009033.91,IEN_",",.03)=1
 S FDA(9009033.91,IEN_",",.07)=$$NOW^XLFDT()
 S OLD=$$GET1^DIQ(9009033.91,IEN,1.11,"I")
 I OLD="" S FDA(9009033.91,IEN_",",1.11)=2
 ;IHS/MSC/MGH add check for controlled substances
 S CODE=$$CHKMED^APSPES5(PROV,+NORIFN,"",ITEM)
 I CODE=3 S FDA(9009033.91,ITEM_",",1.11)=3
 I +DRUG D
 .S DRCL=+$P($G(^PSDRUG(DRUG,0)),U,3)
 .I $E(DRCL,1,1)=2 S FDA(9009033.91,IEN_",",1.11)=6
 D FILE^DIE(,"FDA") K FDA
 Q NORIFN_"^Order created."
SUB(SFIELD,DLG,INST,ID) ;
 N I,E,IENS,AIEN
 S IENS=0 F  S IENS=$O(^APSPRREQ(IEN,2,IENS)) Q:'+IENS  D
 .S AIEN=IENS_","_IEN_","
 .S I=$G(INT(9009033.912,AIEN,SFIELD,"I"))
 .S LST(DLG,IENS)=I
 Q
SIGTXT(DLG,INST,ID) ; Do sig
 N SIG,TXT
 S TXT="ORDIALOG(""WP"","_DLG_",1)"
 S LST(DLG,1)=TXT
 S SIG=0 F  S SIG=$O(^APSPRREQ(IEN,3,SIG)) Q:'+SIG  D
 .S LST("WP",DLG,1,SIG,0)=$G(^APSPRREQ(IEN,3,SIG,0))
 Q
PITXT(DLG,INST,ID) ; Do Patient instructions
 N TXT
 S TXT="ORDIALOG(""WP"","_DLG_",1)"
 S LST(DLG,1)=TXT
 S LST("WP",DLG,1,1,0)=$G(INT(9009033.91,IEN_",",4.1,"I"))
 Q
NOTES(DLG,INST,ID) ; Do Notes to pharmacist
 N TXT
 S TXT="ORDIALOG(""WP"","_DLG_",1)"
 S LST(DLG,1)=TXT
 S LST("WP",DLG,1,1,0)=$G(INT(9009033.91,IEN_",",4.2,"I"))
 Q
INSTR(DLG,INST,ID) ;Do instr
 N I,E,IENS,AIEN
 S IENS=0 F  S IENS=$O(^APSPRREQ(IEN,2,IENS)) Q:'+IENS  D
 .S I=$P($G(^APSPRREQ(IEN,2,IENS,0)),"&",5)
 .I I="" S I=$P($G(^APSPRREQ(IEN,2,IENS,0)),"&",1)
 .S LST(DLG,IENS)=I
 Q
DOSE(DLG,INST,ID) ;Do dosing
 N CHKDOSE,INSTR,DOSE,PSOI,DFN,CONJ,ORWDOSES,IENS
 S IENS=0 F  S IENS=$O(^APSPRREQ(IEN,2,IENS)) Q:IENS=""  D
 .S I=$G(^APSPRREQ(IEN,2,IENS,0))
 .S LST(DLG,IENS)=I
 Q
CHKVITL(DFN,MSGIEN) ;Check for vitals matching last recorded
 N MSG,DATA,SEGIEN,SEGOBX,HT,WT,VALUE,UNITS,MATCH,AGE
 S AGE=$$PTAGE(DFN)
 Q:AGE>17 0
 S MATCH=0
 D PARSE^APSPES2(.DATA,$G(MSGIEN),.HLMSTATE)
 Q:'$D(DATA) ""
 S SEGIEN=""
 F  S SEGIEN=$$FSEGIEN^APSPES1(.DATA,"OBX",SEGIEN) Q:'+SEGIEN  D
 .K SEGOBX
 .M SEGOBX=DATA(SEGIEN)
 .S VALUE=$$GET^HLOPRS(.SEGOBX,5,1)
 .S UNITS=$$GET^HLOPRS(.SEGOBX,6,2)
 .I $$GET^HLOPRS(.SEGOBX,3,1)="29463-7" D
 ..S WT=$$VITAL^APSPFUNC(DFN,"WT")
 ..I UNITS="kg" S WT=$$VITCWT^APSPFUNC($P(WT,U,2))
 ..I WT'=VALUE S MATCH=1
 .I $$GET^HLOPRS(.SEGOBX,3,2)="8302-2" D
 ..S HT=$$VITAL^APSPFUNC(DFN,"HT")
 ..I UNITS="cm" S HT=$$VITCHT^APSPFUNC($P(HT,U,2))
 ..I HT'=VALUE S MATCH=1
 Q MATCH
PTAGE(DFN,DAT) ;EP
 N DOB
 S DOB=+$P($G(^DPT(+DFN,0)),U,3)
 S:'$G(DAT) DAT=DT
 Q $S(DAT:$$FMDIFF^XLFDT(DT,DOB)/365.25\1,1:"")
SETDUP(SSNUM,OLDIEN,NIEN,CTYP,MSGIEN) ;EP - handle followups and duplicates
 ;IHS/MSC/MGH 7/12/2019
 ;Delete any existing order based on this SS number
 ;Use the new IEN to create a new order if possible
 ;Mark other requests as duplicates
 ;First loop through the IENs attached to this SSNUM
 N ORDER,ORNP,ORL,REASON,REC,ORVP,FDA,ERR,STAT,OLDTYP,OLDMSG,DUP
 S OLDTYP=$$GET1^DIQ(9009033.91,OLDIEN,7.4)
 Q:OLDTYP'=CTYP
 I CTYP="U" D  Q:'+DUP
 .S OLDMSG=$$GET1^DIQ(9009033.91,OLDIEN,.01)
 .S DUP=$$VALCHK^APSPES11(OLDMSG,OLDIEN,MSGIEN)
 S ORDER=$$GET1^DIQ(9009033.91,OLDIEN,.02)
 S STAT=$$GET1^DIQ(9009033.91,OLDIEN,.03)
 ;If a previous entry has an order attached, delete it
 I +ORDER D
 .S ORVP=$$GET1^DIQ(9009033.91,OLDIEN,1.2,"I")
 .S ORNP=$$GET1^DIQ(9009033.91,OLDIEN,1.3,"I")
 .S ORL=$$GET1^DIQ(9009033.91,OLDIEN,1.6,"I")
 .S REASON="" S REASON=$O(^ORD(100.03,"B","Obsolete Order",REASON))
 .D DC^ORWDXA(.REC,ORDER,ORNP,ORL,REASON,0,1)
 .S FDA(9009033.91,OLDIEN_",",.02)="@"
 .;D KILLALRT(ORNP,ORDER)
 ;Update the APSP Refill request file
 S FDA(9009033.91,OLDIEN_",",.07)=$$NOW^XLFDT()
 S FDA(9009033.91,OLDIEN_",",.03)=8
 S FDA(9009033.91,OLDIEN_",",.08)=4
 D FILE^DIE("","FDA","ERR")
 Q
KILLALRT(ORNP,ORVP,OLDIEN) ;Kill the alert
 N XQAKILL,ORNIFN,XQAID,ORNIFN
 S ORNIFN=$O(^ORD(100.9,"B","SS REFILL REQUEST SIGNATURE",0))
 S XQAKILL=$$XQAKILL^ORB3F1(ORNIFN) ; unsigned orders notif
 S XQAID=$P($G(^ORD(100.9,ORNIFN,0)),U,2)_","_+ORVP_","_ORNIFN D DELETEA^XQALERT K XQAID
 S ORNIFN=$O(^ORD(100.9,"B","ORDER REQUIRES ELEC SIGNATURE",0))
 S XQAKILL=$$XQAKILL^ORB3F1(ORNIFN) ; unsigned orders notif
 S XQAID=$P($G(^ORD(100.9,ORNIFN,0)),U,2)_","_+ORVP_","_ORNIFN D DELETEA^XQALERT K XQAID
 Q
COMPOUND(RET,OITM) ;Get the data for the compounds in a drug
 N ING,NODE,CNT,CDRUG,AMT,UNIT,CNAME,ID
 S RET=$$TMPGBL
 S CNT=0
 S ID=$P($P($G(^ORD(101.43,OITM,0)),U,2),";",1)
 I '+ID S @RET@(0)="Orderable Item not found." Q
 S DRG=0 F  S DRG=$O(^PSDRUG("ASP",ID,DRG)) Q:'+DRG  D
 .S ING=0 F  S ING=$O(^PSDRUG(DRG,999999936,ING)) Q:'+ING  D
 ..S NODE=$G(^PSDRUG(DRG,999999936,ING,0))
 ..S CDRUG=$P(NODE,U,1)
 ..S AMT=$P(NODE,U,2)
 ..S UNIT=$P($G(^PS(50.607,$P(NODE,U,3),0)),U,1)
 ..S CNAME=$$GET1^DIQ(50,CDRUG,.01)
 ..S CNT=CNT+1
 ..S @RET@(CNT)=CNAME_" "_AMT_UNIT
 I CNT=0 S @RET@(0)="Compound information not available."
 Q
 ; APSPES7 NEWORD RPC entry point
NWORDRPC(RET,REQIEN,DFN,PROV,LOC) ;-
 N VAL,FN,FDA
 S VAL=$$NEWORD(REQIEN,DFN,PROV,+$G(LOC))
 I +VAL>0 D
 .S FN=9009033.91
 .S FDA(FN,REQIEN_",",.03)=1
 .S FDA(FN,REQIEN_",",.02)=+VAL
 .D FILE^DIE("K","FDA")
 S RET=+VAL>0
 Q
TMPGBL() ;EP
 K ^TMP("APSPES7",$J) Q $NA(^($J))
