APSPPAL3 ;IHS/MSC/PLS - Pickup Activity Log Support ;01-Jul-2024 15:34;DU
 ;;7.0;IHS PHARMACY MODIFICATIONS;**1035**;Sep 23, 2004;Build 39
 ;FID 99319
EN ; -- main entry point for APSP PICKUP LOG
 D EN^VALM("APSP PICKUP LOG")
 Q
 ;
HDR ; -- header code
 K VALMHDR S HDR=^TMP("PSOHDR",$J,1,0)
 S:^TMP("PSOHDR",$J,8,0) X=IORVON_"<A>"_IORVOFF,HDR=$$SETSTR^VALM1(X,HDR,80-$L(X),80) S VALMHDR(1)=HDR
 I '(^TMP("PSOHDR",$J,8,0)) S PSONOAL="" D ALLERGY^PSOORUT2 I PSONOAL'="" D  K PSONOAL
 .S X=IORVON_"<NO ALLERGY ASSESSMENT>"_IORVOFF,HDR=$$SETSTR^VALM1(X,HDR,80-$L(X),80) S VALMHDR(1)=HDR
 S HDR="  PID: "_$$FMTSSN^APSPFUNC(^TMP("PSOHDR",$J,2,0))_"  (HRN: "_$G(VA("PID"))_")"
 S VALMHDR(2)=$$SETSTR^VALM1("Ht(cm): "_^TMP("PSOHDR",$J,7,0),HDR,52,27)
 S HDR="  DOB: "_^TMP("PSOHDR",$J,3,0)_" ("_^TMP("PSOHDR",$J,4,0)_")"
 S VALMHDR(3)=$$SETSTR^VALM1(" Wt(kg): "_^TMP("PSOHDR",$J,6,0),HDR,51,28)
 S HDR="  SEX: "_$E(^TMP("PSOHDR",$J,5,0),1,45)  ;IHS/MSC/PLS - 10/11/07 - CHANGED 44 TO 45
 S VALMHDR(4)=HDR
 S VALMHDR(5)="Rx #: "_IORVON_$P($G(RX),U,2)_IORVOFF
 Q
 ;
INIT ; -- init variables and list array
 S VALM("TITLE")="Prescription Pickup Log"
 S VALMCNT=0
 K @VALMAR
 I '$O(^PSRX(+RX,"ZPAL",0)) D  Q
 .S VALMCNT=1,APSPNUL=1
 .D SETARR(1,"No Pickup Activity recorded.",0)
 E  D BLDLST(+RX)
 Q
 ;
BLDLST(RX) ;-
 N L1,L2
 S APSPNUL=0
 S L1=$C(0) F  S L1=$O(^PSRX(RX,"ZPAL","B",L1),-1) Q:'L1  D
 .S L2=$C(0) F  S L2=$O(^PSRX(RX,"ZPAL","B",L1,L2),-1) Q:'L2  D
 ..D ADDITEM(RX,L2)
 Q
 ;
ADDITEM(RX,IEN) ;-
 N NOD0,PDT,LINE,IENS
 S NOD0=$G(^PSRX(RX,"ZPAL",IEN,0))
 S IENS=IEN_","_RX_","
 Q:'NOD0
 S VALMCNT=VALMCNT+1
 S LINE=$$SETFLD^VALM1(VALMCNT,"","ITEM")
 S LINE=$$SETFLD^VALM1($TR($$FMTE^XLFDT(+NOD0,"5Z"),"@"," "),LINE,"PICKUPDATE")
 S LINE=$$SETFLD^VALM1($$GET1^DIQ(52.999999951,IENS,.03),LINE,"DISPTYPE")
 S LINE=$$SETFLD^VALM1($P(NOD0,U,2),LINE,"FILLNUM")
 S LINE=$$SETFLD^VALM1($$GET1^DIQ(52.999999951,IENS,.04),LINE,"PERSONTYPE")
 S LINE=$$SETFLD^VALM1($P(NOD0,U,8),LINE,"IDNUM")
 S LINE=$$SETFLD^VALM1($$GET1^DIQ(52.999999951,IENS,".06:.02"),LINE,"IDJUR")
 S LINE=$$SETFLD^VALM1($$GET1^DIQ(52.999999951,IENS,.07),LINE,"IDQ")
 D SETARR(VALMCNT,LINE,IEN_","_RX)
 Q
 ;
HELP ; -- help code
 S X="?" D DISP^XQORM1 W !!
 Q
 ;
EXIT ; -- exit code
 K APSPNUL
 S VALMBCK="Q" Q
 ;
EXPND ; -- expand code
 Q
 ;
 ; Set line into array
SETARR(LINE,TEXT,IEN) ;EP-
 S @VALMAR@(LINE,0)=TEXT
 S:$G(IEN) @VALMAR@("IDX",LINE,LINE)=""
 S @VALMAR@(LINE,"PKPIEN")=LINE_U_IEN
 Q
 ;
SELLOG ;
 N Y
 S Y=$P(XQORNOD(0),"=",2)
 ;D PROC1
 Q
 ;
UPDLST ;-Refresh the list
 D CLEAN^VALM10
 D INIT
 S VALMBCK="R"
 Q
 ;
VIEWITM ;
 N ITM,VAL
 N DIR,DUOUT,DIRUT,Y
 S VALMBCK=""
 D EN^VALM2(XQORNOD(0),"SO")
 S ITM=$O(VALMY(""))
 Q:'ITM
 S VAL=$P(@VALMAR@(ITM,"PKPIEN"),U,2)
 Q:'VAL
 D DISPLAY^APSPPAL1($P(VAL,",",2),+VAL)
 S VALMBCK="R"
 Q
 ;
VIEWALL ;
 D DISPLAY^APSPPAL1(RX,0)
 S VALMBCK="R"
 Q
 ;
ADDPKUP ;-
 N PSORPDFN,APSPPOP
 S APSPPOP=0
 S PSORPDFN=+$P($G(^PSRX(+RX,0)),U,2)
 D FULL^VALM1
 ;I $$GETFILL^APSPPAL(+RX) S VALMBCK="R" Q
 D GETPUP1^APSPPAL(+RX)
 I APSPPOP S VALMBCK="R",VALMSG="" Q
 S VALMSG="Pickup Recorded"
 D INIT
 S VALMBCK="R"
 Q
 ;Remove a Pickup Entry from Prescription
DELPKUP ;-
 N ITM,VAL,IENS,POP
 N DIR,DUOUT,DIRUT,Y
 S VALMBCK=""
 D EN^VALM2(XQORNOD(0),"SO")
 S ITM=$O(VALMY(""))
 Q:'ITM
 S VAL=$P(@VALMAR@(ITM,"PKPIEN"),U,2)
 Q:'VAL
 I $$DIRYN^APSPUTIL("Are you sure you want to delete this entry?","YES",,.POP) D
 .S IENS=$P(VAL,U)_","
 .S DA=+VAL,DA(1)=$P(VAL,",",2),DIK="^PSRX("_DA(1)_",""ZPAL""," D ^DIK
 .D FIREEVT^APSPPAL($P(VAL,",",2),+VAL)
 D INIT
 S VALMBCK="R"
 Q
 ;Edit a Pickup Entry
EDITPKUP ;-
 N RXN,DA,IENS,ITM,VAL
 D FULL^VALM1
 S VALMBCK=""
 D EN^VALM2(XQORNOD(0),"SO")
 S ITM=$O(VALMY(""))
 Q:'ITM
 S VAL=$P(@VALMAR@(ITM,"PKPIEN"),U,2)
 Q:'VAL
 S IENS=$P(VAL,U)_","
 S DA=+VAL,DA(1)=$P(VAL,",",2),RXN=DA(1)
 D EN^APSPPAL4(RXN,+VAL)
 D FIREEVT^APSPPAL(RXN,+VAL)
 D INIT
 Q
