APSPCSA ;IHS/MSC/MGH - CONTROLLED SUBSTANCE AUDIT LOG ;10-May-2019 08:40;DU
 ;;7.0;IHS PHARMACY MODIFICATIONS;**1023**;Sept 23,2004;Build 121
 ;Process HL7 message and store into audit file
PROC(MSG) ;EP Parse the message and store into audit file
 N APSPMSG,APSPNMSP,APSPTYPE,MSH,HLSEG,PID,PV1,ORC,RXO,ZRX,ORVP,ORTS,ORL,CLASS,ORAPPT,LOOP
 N REASON,APSPROV,CNTRL,ORDER,CS,ORNMSP,ORTYPE,RXDRUG,PROCESS
 S ORAPPT="",ORL=0,PROCESS=1
 S (MSH,PID,PV1,ORC,RXO,ZRX)=""
 S APSPMSG=$S($L($G(MSG)):MSG,1:"MSG") ; MSG="NAME" or MSG(#)=message
 Q:'$O(@APSPMSG@(0))
 S LOOP=0 F  S LOOP=$O(@APSPMSG@(LOOP)) Q:LOOP'>0  D
 .S HLSEG=$E(@APSPMSG@(LOOP),1,3)
 .I HLSEG="MSH" S MSH=$G(@APSPMSG@(LOOP))
 .I HLSEG="PID" S PID=$G(@APSPMSG@(LOOP))
 .I HLSEG="PV1" S PV1=$G(@APSPMSG@(LOOP))
 .I HLSEG="ORC" S ORC=$G(@APSPMSG@(LOOP))
 .I HLSEG="RXO" S RXO=$G(@APSPMSG@(LOOP))
 .I HLSEG="ZRX" S ZRX=$G(@APSPMSG@(LOOP))
 Q:(MSH="")!(PID="")!(ORC="")!(PV1="")
 ;:$P(MSH,"|",9)="ORR"    ;Don't track automated messages
 S ORNMSP=$$NMSP^ORM($P(MSH,"|",3)),ORTYPE=$$NMSP^ORM($P(MSH,"|",5))
 Q:'$L(ORNMSP)
 Q:ORTYPE'="PS"&(ORNMSP'="PS")     ;Only processing pharmacy orders
 S DFN=+$P(PID,"|",4)
 I $D(^DPT(DFN,0)) S ORVP=DFN_";DPT("
 S CLASS=$P(PV1,"|",3)
 Q:CLASS'="O"     ;Inpatient orders do not count
 S ORDER=$P($P(ORC,"|",3),"^",1)
 S CS=0
 S RXIEN=$P($P(ORC,"|",4),"^",1)
 I RXIEN["S" S RXIEN=""
 I ORDER=""&(+RXIEN) D
 .S RXDRUG=$$GET1^DIQ(52,RXIEN,6,"I")
 .I +RXDRUG S CS=+$P($G(^PSDRUG(RXDRUG,0)),U,3)
 E  D CSVALUE^ORDEA(.CS,+ORDER)
 Q:+CS=0   ;Only process controlled substances
 S APSPROV=+$P(ORC,"|",13),REASON=$P(ORC,"|",17)
 S CNTRL=$P(ORC,"|",2)
 I $T(@CNTRL)]"" D @CNTRL
 Q
NW ;New Order
 N DEA
 S DEA=$O(^APSPAUDF("B","TI",""))
 D NEW(ORDER,RXIEN,DEA)
 Q
SN ;New backdoor order
 Q
 ;N DEA
 ;S DEA=$O(^APSPAUDF("B","CR",""))
 ;D NEW(ORDER,RXIEN,DEA)
 Q
OK ;Acknowledgement
NA ;Number assigned
 N IEN,DEA
 I CNTRL="OK" S DEA=$O(^APSPAUDF("B","RP",""))
 ;I CNTRL="NA" S DEA=$O(^APSPAUDF("B","PU",""))
 Q:CNTRL="NA"
 S IEN=$O(^APSPCSA("C",ORDER,""))
 I +IEN D UPDATE(IEN,ORDER,RXIEN,DEA)
 E  D NEW(ORDER,RXIEN,DEA)
 Q
DC ;Discontinue
CA ;Cancel
DR ;Discontinue
CR ;Cancel
OC ;Cancel
OD ;Discontinue
 D DISC(ORDER,RXIEN)
 Q
SC ;Status change
SS ;Status change
HR ;Hold
HD ;Hold
 S DEA=$O(^APSPAUDF("B","SC",""))
 D STAT(ORDER,RXIEN,DEA)
 Q
ZF ;Refill
 Q
ZD ;Dispense message
 S DEA=$O(^APSPAUDF("B","DI",""))
 D STAT(ORDER,RXIEN,DEA)
 Q
UA ; -- Unable to accept [ack]
UX ; -- Unable to change [ack]
UC ; -- Unable to cancel [ack]
UD ; -- Unable to discontinue [ack]
UH ; -- Unable to hold [ack]
UR ; -- Unable to release hold [ack]
 S DEA=$O(^APSPAUDF("B","UP",""))
 D STAT(ORDER,RXIEN,DEA)
XX ;change
XR ;change
XO ;Change order
RO ;Replacment order
 S DEA=$O(^APSPAUDF("B","XX",""))
 D STAT(ORDER,RXIEN,DEA)
 Q
NEW(ORDER,RXIEN,DEA) ;check to see if order is in audit log. If not add it.
 N CSIEN,SIG,FDA,RX,ERR,LIEN,FNUM,ACTION,SIGNBY,NATURE,BACK
 S CSIEN="",NATURE="",SIGNBY="",BACK=""
 S ORDER=$G(ORDER),RXIEN=$G(RXIEN)
 I ORDER="" D
 .S SIG=""
 .I RXIEN'="" D
 ..S CSIEN=$O(^APSPCSA("F",RXIEN,""))
 E  D
 .S CSIEN=$O(^APSPCSA("C",+ORDER,""))
 .S ACTION=$G(^OR(100,+ORDER,8,1,0))
 .S SIGNBY=$P(ACTION,U,5)
 .S SIG=$P($G(^OR(100,+ORDER,8,1,2)),U,3)
 I DEA="" D
 .I SIG=""&(SIGNBY="") S DEA=$O(^APSPAUDF("B","CR",""))
 .E  S DEA=$O(^APSPAUDF("B","DS",""))
 I +RXIEN S BACK=$$GET1^DIQ(52,RXIEN,311,"I")
 Q:+BACK ""
 I +CSIEN D UPDATE(CSIEN,+ORDER,RXIEN,DEA) Q
 I '+CSIEN D
 .S CSIEN=$$ADD(+ORDER,RXIEN)
 .Q:CSIEN=""
 .K FDA,IENS,ERR,DIERR
 .S SIEN=$$SUB(CNTRL,ORDER,RXIEN,CSIEN,DEA)
 .N ORZ,I,ORIGVIEW S ORIGVIEW=2 D TEXT^ORQ12(.ORZ,+ORDER_";1",80)   ;Store text
 .D MERGE(CSIEN,SIEN,.ORZ)
 Q
STAT(ORDER,RXIEN,DEA) ;Status change for order
 N CSIEN,SIEN,TIEN
 S RXIEN=$G(RXIEN),ORDER=$G(ORDER)
 S CSIEN=$O(^APSPCSA("C",+ORDER,""))
 I +CSIEN D UPDATE(CSIEN,ORDER,RXIEN,DEA)
 E  D
 .S CSIEN=$$ADD(+ORDER,RXIEN)
 .Q:CSIEN=""
 .S SIEN=$$SUB(CNTRL,ORDER,RXIEN,CSIEN,DEA)
 .S TIEN=999 S TIEN=$O(^OR(100,+ORDER,8,TIEN),-1)
 .Q:TIEN=""
 .N ORZ,I,ORIGVIEW S ORIGVIEW=2 D TEXT^ORQ12(.ORZ,+ORDER_";"_TIEN,80)   ;Store text
 .D MERGE(CSIEN,SIEN,.ORZ)
 Q
DISC(ORDER,RXIEN) ;Store the DC or cancellation of an order
 N CSIEN,DEA,TIEN,REASON,SIEN,RX
 S ORDER=$G(ORDER),RXIEN=$G(RXIEN)
 S CSIEN=$O(^APSPCSA("C",+ORDER,""))
 I '+CSIEN S CSIEN=$$ADD(+ORDER,RXIEN)
 Q:'+CSIEN
 Q:+$$GET1^DIQ(52,RXIEN,311,"I")
 S RX=$$GET1^DIQ(100,+ORDER,33)
 I CNTRL="OC"!(CNTRL="CA") S DEA=$O(^APSPAUDF("B","CA",""))
 E  S DEA=$O(^APSPAUDF("B","DC",""))
 S REASON=$$GET1^DIQ(100,+ORDER,65)
 I REASON="" S REASON=$$GET1^DIQ(100,+ORDER,64)
 S SIEN=$$SUB(CNTRL,+ORDER,RX,CSIEN,DEA,REASON)
 N ORZ,I,ORIGVIEW
 I +ORDER D
 .S TIEN=999 S TIEN=$O(^OR(100,+ORDER,8,TIEN),-1)
 .Q:TIEN=""
 .S ORIGVIEW=2 D TEXT^ORQ12(.ORZ,+ORDER_";"_TIEN,80)   ;Store text
 .D MERGE(CSIEN,SIEN,.ORZ)
 Q
MERGE(LIEN,SIEN,ORZ) ;Move the order text into the audit file
 N CNT,SUM
 S CNT=0
 F  S CNT=$O(ORZ(CNT)) Q:+CNT'>0  D
 .S ^APSPCSA(LIEN,1,SIEN,1,CNT,0)=$G(ORZ(CNT))
 .S ^APSPCSA(LIEN,1,SIEN,1,0)="^^"_CNT_"^"_CNT_"^"_DT_"^^"
 S SUM=$$CHECKSUM(LIEN,SIEN)
 K FDA,ERR
 S AIEN=SIEN_","_LIEN_","
 S FDA(9009036.01,AIEN,2)=SUM
 D FILE^DIE("","FDA","ERR")
 K FDA,ERR
 Q
CHECKSUM(LIEN,SIEN) ;Do the checksum
 N CNT,CHKSUM,TXT,NODE
 S CHKSUM=""
 ;S CNT=0 F  S CNT=$O(^APSPCSA(LIEN,1,SIEN,1,CNT)) Q:+CNT'>0  D
 ;.S X=$G(^APSPCSA(LIEN,1,SIEN,1,CNT,0))
 ;.N J
 ;.F J=1:1:$L(X) S CHKSUM=+$G(CHKSUM)+(($A(X,J)*CNT)*J)
 S CNT=0 F  S CNT=$O(^APSPCSA(LIEN,1,SIEN,1,CNT)) Q:+CNT'>0  D
 .S NODE=$G(^APSPCSA(LIEN,1,SIEN,1,CNT,0))
 .I CNT=1 S TXT=NODE
 .E  S TXT=TXT_" "_NODE
 S CHKSUM=$$HASH^APSPCSA1(LIEN,SIEN,TXT)
 Q CHKSUM
SUB(CNTRL,ORDER,RX,LIEN,DEA,REASON,FLG) ;Store a status update
 K FDA,ERR,IENS,DIERR,ORDIALOG
 N DRUG,AIEN,DIAL,CS,OI,BACK
 S DRUG="",OI="",BACK="",FLG=$G(FLG),CS=""
 S RX=$G(RX),REASON=$G(REASON)
 I +RX&(RX'["S") D
 .S DRUG=$$GET1^DIQ(52,+RX,6,"I")
 I +ORDER D
 .S DIAL=$P($G(^OR(100,+ORDER,0)),U,5)
 .D GETDLG1^ORCD(+DIAL),GETORDER^ORCD(+ORDER)
 .S OI=+$G(ORDIALOG($$PTR("ORDERABLE ITEM"),1))
 .I DRUG="" S DRUG=$G(ORDIALOG($$PTR("DISPENSE DRUG"),1))
 I +DRUG S CS=+$P($G(^PSDRUG(DRUG,0)),U,3)
 S SIEN=""
 S AIEN="+1,"_LIEN_","
 S FDA(9009036.01,AIEN,.01)=CNTRL
 S FDA(9009036.01,AIEN,.02)=$$NOW^XLFDT
 S FDA(9009036.01,AIEN,.03)=DRUG
 S FDA(9009036.01,AIEN,.05)=CS
 S FDA(9009036.01,AIEN,.06)=DEA
 S FDA(9009036.01,AIEN,.07)=DUZ
 S FDA(9009036.01,AIEN,2.1)=OI
 I REASON'="" S FDA(9009036.01,AIEN,.04)=REASON
 D UPDATE^DIE("","FDA","IENS","ERR")
 I '$D(DIERR) D
 .S SIEN=$G(IENS(1))
 .D LOGBUSA^APSPCSA1(ORDER,RX,LIEN,SIEN,.FLG)
 Q SIEN
ADD(ORDER,RXIEN) ;Add an entry to the audit file
 N PROV,PT,ENTER,SIG,FDA,X,ERR,DEA,LIEN,FNUM
 K FDA,IENS,ERR
 S LIEN="",PT=""
 S NATURE="",SIGNBY="",SIG=""
 S ORDER=$G(ORDER),RXIEN=$G(RXIEN)
 I +ORDER D
 .S PT=+$$GET1^DIQ(100,+ORDER,.02,"I")
 .S ENTER=$$GET1^DIQ(100,+ORDER,3,"I")
 .S RX=$$GET1^DIQ(100,+ORDER,33,"I")
 .S ACTION=$G(^OR(100,+ORDER,8,1,0))
 .S SIGNBY=$P(ACTION,U,5)
 .S PROV=+$P(ACTION,U,3)
 .S NATURE=$P(ACTION,U,12)
 .S SIG=$P($G(^OR(100,+ORDER,8,1,2)),U,3)
 Q:+RXIEN&(+ORDER=0) LIEN
 ;.S RX=RXIEN
 ;.S PT=$$GET1^DIQ(52,RXIEN,2,"I")
 ;.S PROV=$$GET1^DIQ(52,RXIEN,4,"I")
 ;.S ENTER=DUZ
 ;.S SIG=""
 ;.I $$GET1^DIQ(52,RXIEN,311)="YES" S NATURE="W"
 I PT="" S PT=$P(PID,"|",4)
 I PROV="" S PROV=$P($P(ORC,"|",11),U,1)
 Q:PT=""!(PROV="") LIEN
 S FNUM=9009036
 S FDA(FNUM,"+1,",.01)=PT
 I +ORDER S FDA(FNUM,"+1,",.02)=+ORDER
 I +PROV S FDA(FNUM,"+1,",.03)=+PROV
 S FDA(FNUM,"+1,",.04)=$$NOW^XLFDT
 I +RX&(RX'["S") S FDA(FNUM,"+1,",.05)=RX
 I +ENTER S FDA(FNUM,"+1,",.06)=ENTER
 I SIG'="" S FDA(FNUM,"+1,",.07)=SIG
 I NATURE'="" S FDA(FNUM,"+1,",.08)=NATURE
 S FDA(FNUM,"+1,",.09)=DUZ(2)
 D UPDATE^DIE("","FDA","IENS","ERR")
 I $D(IENS(1)) S LIEN=IENS(1)
 Q LIEN
EDIT(ORDER,CODE) ;Edit an entry
 N IEN,CNTRL,DEA,CNTRL,RX
 S ORDER=$G(ORDER),CODE=$G(CODE)
 Q:'+ORDER
 S DEA=$O(^APSPAUDF("B",CODE,""))
 Q:DEA=""
 S CNTRL=CODE
 S IEN=$O(^APSPCSA("C",+ORDER,""))
 I +IEN D
 .S RX=$P($G(^APSPCSA(IEN,0)),U,5)
 .D UPDATE(IEN,ORDER,RX,DEA)
 Q
AUDIT(RET,ORDER,CODE) ;Update AUDIT log
 N IEN,DEA,RET,OIEN,CNTRL,CSORD,FLG
 S RET=0,OIEN=0
 I CODE="" S RET=0 Q
 S:$D(ORDER)=1 ORDER(1)=ORDER
 F  S OIEN=$O(ORDER(OIEN)) Q:OIEN=""  D
 .S CSORD=+($G(ORDER(OIEN)))
 .S FLG=$P($G(ORDER(OIEN)),"~",2)
 .S IEN=$O(^APSPCSA("C",CSORD,""))
 .I +IEN D
 ..S DEA=$O(^APSPAUDF("B",CODE,""))
 ..S CNTRL=CODE
 ..D UPDATE(IEN,CSORD,"",DEA,.FLG)
 S RET=1
 Q
UPDATE(CSIEN,ORDER,RXIEN,DEA,FLG) ;Update the zero node if needed
 N REC,ERR,PROV,SIG,FNUM,ACTION,SIG,FDA,ERR,AUTO,PMY,STATE,PROCESS
 S FNUM=9009036,PROCESS=1,FLG=$G(FLG)
 S ORDER=$G(ORDER),RXIEN=$G(RXIEN),NOUP=$G(NOUP),FLG=$G(FLG)
 D GETS^DIQ(FNUM,CSIEN,".02;.03;.05;.07,","I","REC","ERR")
 I +RXIEN D
 .I $$GET1^DIQ(52,RXIEN,311,"I")=1 S PROCESS=0
 Q:'+PROCESS
 I $G(REC(FNUM,CSIEN_",",.02,"I"))="" S FDA(FNUM,CSIEN_",",.02)=ORDER
 I $G(REC(FNUM,CSIEN_",",.05,"I"))="" S FDA(FNUM,CSIEN_",",.05)=RXIEN
 I $G(REC(FNUM,CSIEN_",",.07,"I"))="" D
 .S ACTION=$G(^OR(100,+ORDER,8,1,2))
 .S SIG=$P(ACTION,U,3)
 .I SIG'="" S FDA(FNUM,CSIEN_",",.07)=SIG
 I +RXIEN D
 .S AUTO=$$GET1^DIQ(52,RXIEN,9999999.23,,"I")
 .I AUTO'="" S FDA(FNUM,CSIEN_",",2)=AUTO
 .S PMY=$$GET1^DIQ(52,RXIEN,9999999.24)
 .I PMY'="" S FDA(FNUM,CSIEN_",",3)=PMY
 .I CNTRL="NW" D
 ..I SIG'="" S DEA=$O(^APSPAUDF("B","DS",""))
 .;S STATE=$$PSTATE^BEHORXFN(RXIEN)
 .;S ACT=9999999
 .;S ACT=$O(^PSRX(RXIEN,"A",ACT),-1)  Q:'+ACT  D
 .;.S STATE=$P($G(^PSRX(RXIEN,"A",ACT,9999999)),U,2)
 .;.I STATE'="" D
 .;..S DEA=$S(STATE="P":11,STATE="R":12,STATE="T":9,STATE="E":9,STATE="F":7,STATE="X":13,1:DEA)
 Q:'+PROCESS
 I $D(FDA)>0 D FILE^DIE("","FDA","ERR")
 S SIEN=$$SUB(CNTRL,ORDER,RXIEN,CSIEN,DEA,"",.FLG)
 I +SIEN D
 .N ORZ,I,ORIGVIEW
 .I +ORDER D
 ..S TIEN=999 S TIEN=$O(^OR(100,+ORDER,8,TIEN),-1)
 ..Q:TIEN=""
 ..S ORIGVIEW=2 D TEXT^ORQ12(.ORZ,+ORDER_";"_TIEN,80)   ;Store text
 ..D MERGE(CSIEN,SIEN,.ORZ)
 Q
SAVE(ORDER) ;EP Save a new order when created
 N DEA,PKG,CS,CNTRL,CSIEN
 S DEA="",CNTRL=""
 Q:'+$G(ORDER)
 S PKG=$$GET1^DIQ(100,+ORDER,12)
 Q:PKG'="OUTPATIENT PHARMACY"
 D CSVALUE^ORDEA(.CS,ORDER)
 Q:CS=0
 S CSIEN=$O(^APSPCSA("C",+ORDER,""))
 I +CSIEN S CNTRL="SC",DEA=$O(^APSPAUDF("B","ED",""))
 E  S CNTRL="NO",DEA=$O(^APSPAUDF("B","CR",""))
 D NEW(ORDER,"",DEA)
 Q
ERX(RXIEN,CODE) ;Add an entry to the audit log if its a narcotic
 N ORDER,CS,CSIEN,DEA
 Q:'+$G(RXIEN)
 S CODE=$G(CODE)
 S ORDER=$$GET1^DIQ(52,RXIEN,39.3,"I")
 Q:'+ORDER
 D CSVALUE^ORDEA(.CS,ORDER)
 Q:CS=0   ;Only log controlled substances
 S CSIEN=$O(^APSPCSA("C",+ORDER,""))
 Q:'+CSIEN
 S CNTRL="SC"
 S DEA=$O(^APSPAUDF("B",CODE,""))
 D UPDATE(CSIEN,ORDER,RXIEN,DEA)
 Q
DELETE(ORDER) ;EP Remove order field from audit log if order was deleted before signature.
 N CSIEN,FDA,ERR,SIEN,DRUG,DIAL,OI,DEA
 Q:'+$G(ORDER)
 S CSIEN=$O(^APSPCSA("C",+ORDER,""))
 Q:'+CSIEN
 S FDA(9009036,CSIEN_",",.02)="@"
 D FILE^DIE("","FDA","ERR")
 K DIERR,ERR,FDA,IENS
 S AIEN="+1,"_CSIEN_","
 S DEA=$O(^APSPAUDF("B","DE",""))
 S FDA(9009036.01,AIEN,.01)="DE"
 S FDA(9009036.01,AIEN,.02)=$$NOW^XLFDT
 S FDA(9009036.01,AIEN,.06)=DEA
 S FDA(9009036.01,AIEN,.07)=DUZ
 I +ORDER D
 .S DIAL=$P($G(^OR(100,+ORDER,0)),U,5)
 .D GETDLG1^ORCD(+DIAL),GETORDER^ORCD(+ORDER)
 .S OI=+$G(ORDIALOG($$PTR("ORDERABLE ITEM"),1))
 .S DRUG=$G(ORDIALOG($$PTR("DISPENSE DRUG"),1))
 .S FDA(9009036.01,AIEN,.03)=DRUG
 D UPDATE^DIE("","FDA","IENS","ERR")
 I '$D(DIERR) D
 .S SIEN=$G(IENS(1))
 .D LOGBUSA^APSPCSA1("","",CSIEN,SIEN)
 Q
 ;
ATTEMPT(PROV,ITEM,FLAG,RE) ;EP  Store an attempt to order a narcotic that is rejected
 N FNUM,ERR,DIERR,IENS,TXT,DFN,LIEN,SIEN,DEA
 S FNUM=9009036
 Q:'+ITEM
 Q:'+PROV
 S LIEN=0
 S DFN=$$GETVAR^CIANBUTL("PATIENT.ID.MRN",,"CONTEXT.PATIENT")
 Q:'+DFN
 S TXT=$S($P(RE,U,1)=1:"No current DEA",$P(RE,U,1)=2:"Unauthorized for schedule "_$P(RE,U,2),1:"DEA failure")
 K FDA,ERR,DIERR,IENS
 S FDA(FNUM,"+1,",.01)=DFN
 S FDA(FNUM,"+1,",.02)="@"
 S FDA(FNUM,"+1,",.03)=PROV
 S FDA(FNUM,"+1,",.04)=$$NOW^XLFDT
 S FDA(FNUM,"+1,",.09)=DUZ(2)
 D UPDATE^DIE("","FDA","IENS","ERR")
 I $D(IENS(1)) S LIEN=IENS(1)
 Q:'+LIEN
 K FDA,ERR,IENS
 S AIEN="+1,"_LIEN_","
 S DEA=$O(^APSPAUDF("B","AT",""))
 S FDA(9009036.01,AIEN,.01)="AT"
 S FDA(9009036.01,AIEN,.02)=$$NOW^XLFDT
 S FDA(9009036.01,AIEN,2.1)=ITEM
 S FDA(9009036.01,AIEN,.05)=FLAG
 S FDA(9009036.01,AIEN,.06)=DEA
 S FDA(9009036.01,AIEN,.07)=DUZ
 S FDA(9009036.01,AIEN,.04)=TXT
 D UPDATE^DIE("","FDA","IENS","ERR")
 D LOGBUSA^APSPCSA1("","",LIEN,IENS(1))
 K FDA,IENS,ERR
 Q
 ;
CHKLOG(LST,IEN,FLAG) ;EP Check the audit file for tampering
 ;IEN of entry in log is input
 ;Return is LST=0 for all good or LST=number of bad entries
 ;LST(n)=IEN of sub entry changed and ^ status when changed
 N SUB,CNT,RECHK,OLD
 S CNT=0,FLAG=$G(FLAG)
 S SUB=0 F  S SUB=$O(^APSPCSA(IEN,1,SUB)) Q:'+SUB  D
 .S OLD=$P($G(^APSPCSA(IEN,1,SUB,2)),U,1)
 .I OLD'="" D
 ..S RECHK=$$CHECKSUM(IEN,SUB)
 ..I OLD'=RECHK S CNT=CNT+1
 ..I FLAG=1&(CNT>0) D
 ...S LST(CNT)=SUB_"^"_$P($G(^APSPCSA(IEN,1,SUB,0)),U,6)
 S LST(0)=CNT
 Q
PTR(NAME) ; -- Returns ptr value of prompt in Dialog file
 Q +$O(^ORD(101.41,"AB",$E("OR GTX "_NAME,1,63),0))
