APSPESG1 ;IHS/MSC/MGH - Display entries from refill queue in APSP REFILL REQUEST file ;27-Apr-2021 13:59;DU
 ;;7.0;IHS PHARMACY MODIFICATIONS;**1016,1023,1024,1025,1026,1027,1028**;Sep 23,2004;Build 50
 ;==================================================================
 ;IHS/MSC/MGH Modified HL7DATA+7&HL7DATA+42,DETAIL+4
 ;IHS/MSC/MGH Modified DESCAPE calls added for eRX
DETAIL(DATA,IEN,FLG) ;EP for RPC call
 N APSPPID,APSPDG1,APSPRXE,APSPRXO,APSPORC,STR,UNITS,ROUTE,NOUN,USCHDUR,MEDUNITS,SIGNAT,DONE,SCHITEM,SCHUPD,INTERVAL,SCHARY,TOTDUR,CONJ
 N HLECH,DEL,APSPMSH,APSPRXR,APSPRXD,DUR,SIGDAT,ITEM,MSGID,I,CTYPE
 ;IHS/MSC/MGH Added patch 1023
 N FS,CS,REP,ESCAPE,SUBCOMP,SEGTYP
 ;S HLECH=$P($G(APSPMSH),"|",2) I '$L(HLECH) S HLECH="^~\&"
 S MSGID=$$GET1^DIQ(9009033.91,IEN,.01,"E"),HLMSG=$$GHLDAT(IEN)
 S CTYPE=$$GET1^DIQ(9009033.91,IEN,.12)
 S DEL="|"
 S FLG=$G(FLG,0)
 D SHLVARS^APSPESG
 S HLECH=$P(APSPMSH,DEL,2) I '$L(HLECH) S HLECH="^~\&"
 S CS=$E(HLECH,1)
 S REP=$E(HLECH,2)
 S ESCAPE=$E(HLECH,3)
 S SUBCOMP=$E(HLECH,4)
 ;end changes
 F I=1:1:4 D
 .S HLECH(I)=$E(HLECH,I)
 D HL7DATA(.HL7,IEN)
 D MAPDATA(.MAP,IEN)
 ;Put together dosing information
 S STR=$P($G(APSPRXE),DEL,2),UNITS=$P($P($G(APSPRXE),DEL,5),HLECH(1),2),ROUTE=$P($G(APSPRXR),DEL,2)
 S NOUN=$P($G(APSPRXO),DEL,13) I $L(NOUN) D
 .S NOUN=$O(^APSPNCP(9009033.7,"D",NOUN,0))
 .S NOUN=$$GET1^DIQ(9009033.7,NOUN,1,"E")
 S USCHDUR=$P($G(APSPORC),DEL,8),MEDUNITS=$P($P($G(APSPRXO),DEL,20),HLECH(1),2)
 S SIGDAT=$P(APSPRXE,DEL,8)
 S DONE=0
 F I=1:1 D  Q:DONE
 .S SCHITEM=$P(USCHDUR,HLECH(2),I)
 .I '$L(SCHITEM) S DONE=1 Q
 .S SCHUPD=$P(SCHITEM,HLECH(1)) I 'SCHUPD S SCHUPD=1
 .S INTERVAL=$P(SCHITEM,HLECH(1),2),DUR=$P(SCHITEM,HLECH(1),3),CONJ=$P(SCHITEM,HLECH(1),9)
 .S SCHARY(I)=SCHUPD_U_INTERVAL_U_DUR_U_CONJ
 .S TOTDUR=$G(TOTDUR)+DUR
 S DATA=$$TMPGBL^CIAVMRPC
 I FLG D
 .D DISPHL7^APSPESG1(.HL7,.MAP,STR,UNITS,ROUTE,NOUN,.SCHARY,MEDUNITS,SIGDAT)
 E  D CAPTURE^CIAUHFS("D DISPHL7^APSPESG1(.HL7,.MAP,STR,UNITS,ROUTE,NOUN,.SCHARY,MEDUNITS,SIGDAT)",DATA)
 Q
MAPDATA(MAP,IEN) ; Get the data that was mapped
 K MAP
 N PAT,DPT,DOB,SEX,HRCN,Y,PHARM,PROV,SIGDAT,SIGI,SUB,CTYPE
 S (PAT,DPT,DOB,SEX,HRCN,PROV)=""
 S DPT=$$GET1^DIQ(9009033.91,IEN,1.2,"I")
 I DPT'="" D
 .S PAT=$$GET1^DIQ(2,DPT,.01,"E")
 .S DOB=$$GET1^DIQ(2,DPT,.03,"I")
 .S Y=DOB D DD^%DT S DOB=Y
 .S SEX=$$GET1^DIQ(2,DPT,.02,"E")
 .S HRCN=$$HRCN(DPT,$G(DUZ(2)))
 .S MAP("PADDR")=$$PTADDR(DPT)
 .S MAP("PPHONE")=$$FMTPHN^APSPES2($$GET1^DIQ(2,DPT,.131,"I"))
 E  S PAT="**UNKNOWN**"
 S MAP("PAT")=PAT
 S MAP("EXT")="DOB: "_DOB_" SEX: "_SEX_" HRCN: "_HRCN
 S PHARM=$$GET1^DIQ(9009033.91,IEN,1.7,"I")
 S MAP("PHARM")=$$GET1^DIQ(9009033.91,IEN,1.7,"E")_" Ph: "_$$FMTPHN^APSPES2($$GET1^DIQ(9009033.9,PHARM,2.1,"I"))
 S MAP("PHARMA")=$$PADDR(PHARM)
 S MAP("SUP")=$$GET1^DIQ(9009033.91,IEN,1.5,"E")
 S MAP("QTY")=$$GET1^DIQ(9009033.91,IEN,1.4,"E")
 S MAP("TIME")=$$GET1^DIQ(9009033.91,IEN,0.4,"E")
 S SUB=$$GET1^DIQ(9009033.91,IEN,1.12,"E")
 S MAP("DAW")=$S(SUB="NO":"Allow Substitution",1:"Dispense as written")
 S PROV=$$GET1^DIQ(9009033.91,IEN,1.3,"I")
 S MAP("PROV")=$$GET1^DIQ(9009033.91,IEN,1.3,"E")
 S MAP("OFF")=$$FMTPHN^APSPES2($$GET1^DIQ(200,PROV,.132,"I"))
 S MAP("PROVAD")=$$PROVAD(PROV)
 S MAP("DRUG")=$$GET1^DIQ(9009033.91,IEN,1.1,"E")
 S SIGI=0,SIGDAT=""
 F  S SIGI=$O(^APSPRREQ(IEN,3,SIGI)) Q:'+SIGI  D
 .I SIGDAT="" S SIGDAT=$G(^APSPRREQ(IEN,3,SIGI,0))
 .E  S SIGDAT=SIGDAT_" "_$G(^APSPRREQ(IEN,3,SIGI,0))
 S MAP("SIG")=SIGDAT
 ;S MAP("SIG")=$$GET1^DIQ(9009033.913,"1,"_IEN_",",.01)
 ;S MAP("NOTES")=$$GET1^DIQ(9009033.91,IEN,4.1)
 S MAP("DX")=$$GET1^DIQ(9009033.91,IEN,7.1)
 S CTYPE=$$GET1^DIQ(9009033.91,IEN,.12)
 I CTYPE="R" S MAP("REFIL")=$$GET1^DIQ(9009033.91,IEN,1.9)-1
 E  S MAP("REFIL")=$$GET1^DIQ(9009033.91,IEN,1.9)
 Q
HL7DATA(HL7,IEN) ;Get the data from the HL7 file
 N PAT,DOB,SEX,HRCN,HRCN12,PROV,PROVDAT,SUB,DSUB,DCODE,DRG,DCODEQ,NCPDP,SIG,PON
 K HL7
 S PAT=$$DESCAPE($$PATNAME^APSPESLP(APSPPID)) I '$L(PAT) S PAT="**UNKNOWN**"
 S HRCN12=$$DESCAPE($P($P(APSPPID,DEL,4),HLECH(1),1))
 S HRCN=+$E(HRCN12,7,12)
 S DOB=$$FMTE^XLFDT($$FMDATE^HLFNC($$DESCAPE($P(APSPPID,DEL,8))))
 S SEX=$$DESCAPE($P(APSPPID,DEL,9))
 ;IHS/GDIT/MSC/MGH Added for Patch 1023
 S NCPDP=$$DESCAPE($P(APSPRXO,DEL,13))
 I NCPDP'="" D
 .S NCPDP=$O(^APSPNCP(9009033.7,"D",NCPDP,""))
 .I +NCPDP S HL7("NCPDP")=$$GET1^DIQ(9009033.7,NCPDP,1)
 .E  S HL7("NCPDP")=""
 E  S HL7("NCPDP")=""
 ;END MOD
 S HL7("PAT")=PAT
 S HL7("EXT")="DOB: "_DOB_" SEX: "_SEX_" HRCN: "_HRCN
 ;S HL7("PPHONE")=$$FMTPHN^APSPES2($$DESCAPE($P($P(APSPPID,DEL,14),HLECH(1),1)))
 D PCOMARY($NA(HL7("PTCOMM")),$P(APSPPID,DEL,14))
 S HL7("PADD")=$$DESCAPE($$FMTADD($P(APSPPID,DEL,12)))
 S HL7("PHARM")=$$DESCAPE($P($P(APSPRXE,DEL,41),HLECH(1),2))_" Ph "_$$FMTPHN^APSPES2($$DESCAPE($P($P(APSPRXE,DEL,46),HLECH(1),1)))
 S HL7("DRUG")=$$DESCAPE($P($P(APSPRXE,DEL,3),HLECH(1),2))
 S HL7("SUP")=$$DESCAPE($P($P($P(APSPORC,DEL,8),HLECH(1),3),"~",1))
 S HL7("PON")=$$DESCAPE($P($P(APSPORC,DEL,3),HLECH(1),1))
 S HL7("QTY")=$$DESCAPE($P($P(APSPRXE,DEL,11),HLECH(1),1))
 S HL7("FORM")=$$DESCAPE($P($P(APSPRXE,DEL,6),HLECH(1),2))
 ;S HL7("SIG")=$$DESCAPE($P(APSPRXE,DEL,8))
 S SIG=$$DESCAPE($P(APSPRXE,DEL,8))
 S HL7("SIG")=$$SIGTXT(SIG)
 ;S HL7("INST")=$P($P(APSPRXO,DEL,7),HLECH(1),2)
 I CTYPE="R" S HL7("NOTE")=$$DESCAPE($P($P(APSPRXO,DEL,7),HLECH(1),2))
 E  S HL7("NOTE")=$$DESCAPE($P(APSPRXE,DEL,22))
 S HL7("REFIL")=$$DESCAPE($P($P(APSPRXE,DEL,13),HLECH(1),1))
 S HL7("REQUAL")=$$DESCAPE($P($P(APSPRXO,DEL,14),HLECH(1),2))
 S SUB=$S(CTYPE="R":$$DESCAPE($P(APSPRXO,DEL,10)),1:$$DESCAPE($P(APSPRXE,DEL,10)))
 S HL7("SUB")=$S(SUB="G":"Allow Generics",SUB="N":"Dispense as Written",1:"Allow Therapeutic Substitutions")
 S PROVDAT=$P(APSPORC,DEL,13),PROV=$P(PROVDAT,HLECH(1),2)_","_$P(PROVDAT,HLECH(1),3)
 S PROV=$$DESCAPE(PROV)
 S HL7("PROV")=PROV
 S HL7("PRADD")=$$FMTADD($P(APSPORC,DEL,25))
 S HL7("PRPH")=$$FMTPHN^APSPES2($$DESCAPE($P($P(APSPORC,DEL,24),HLECH(1),1)))
 S HL7("ISSUE")=$$FMTE^XLFDT($$FMDATE^HLFNC($$DESCAPE($P($P(APSPORC,DEL,10),HLECH(1),1))),"5DZ0")
 S HL7("PHADD")=$$FMTADD($P(APSPRXE,DEL,42))
 S HL7("LFIL")=$$FMTE^XLFDT($$FMDATE^HLFNC($P($P(APSPORC,DEL,27),HLECH(1),1)),"5DZ0")
 S DCODE=$$DESCAPE($P($P(APSPRXD,DEL,3),HLECH(1),1))
 S DRG=$$DESCAPE($P($P(APSPRXD,DEL,3),HLECH(1),2))
 S DCODEQ=$$DESCAPE($P($P(APSPRXD,DEL,3),HLECH(1),3))
 S HL7("DDRG")=DRG_$S($L(DCODE):" ("_DCODEQ_":"_DCODE_")",1:"")
 ;S HL7("DSIG")=$$DESCAPE($TR($P(APSPRXD,DEL,10),"^",""))
 S SIG=$$DESCAPE($TR($P(APSPRXD,DEL,10),"^",""))
 S HL7("DSIG")=$$SIGTXT(SIG)
 S HL7("DSUP")=$$DESCAPE($P($P(APSPRXD,DEL,23),HLECH(1),1))
 S HL7("DQTY")=$$DESCAPE($P($P(APSPRXD,DEL,5),HLECH(1),1))
 ;IHS/GDIT/MSC/MGH added for 1023
 S NCPDP=$$DESCAPE($P($P(APSPRXD,DEL,6),HLECH(1),1))
 I NCPDP'="" D
 .S NCPDP=$O(^APSPNCP(9009033.7,"D",NCPDP,""))
 .I +NCPDP S HL7("DFORM")=$$GET1^DIQ(9009033.7,NCPDP,1)
 .E  S HL7("DFORM")=""
 E  S HL7("DFORM")=""
 ;END MOD
 S HL7("DREFILL")=$$DESCAPE($P($P(APSPRXD,DEL,9),HLECH(1),1))
 S HL7("DNOTE")=$$DESCAPE($P($P(APSPRXD,DEL,16),HLECH(1),2))
 S HL7("DDATE")=$$FMTE^XLFDT($$FMDATE^HLFNC($P($P(APSPRXD,DEL,4),HLECH(1),1)),"5DZ0")
 S DSUB=$$DESCAPE($P(APSPRXO,DEL,10))
 S HL7("DSUB")=$S(DSUB="G":"Allow Generics",DSUB="N":"Dispense as Written",1:"Allow Therapeutic Substitutions")
 I APSPDG1'="" D
 .S HL7("DX")=$P($P(APSPDG1,DEL,4),HLECH(1),U,1)_" "_$P($P(APSPDG1,DEL,4),HLECH(1),2)
 Q
DISPHL7(HL7,MAP,STR,UNITS,ROUTE,NOUN,SCHARY,MEDUNITS,SIG,ARY) ; Display HL7 data
 N LINE,K,LP
 W !!
 S $P(LINE,"-",80)=""
 W LINE
 W !,"  DISPLAYING Ordered med HL7 data:",!
 W !,"        PON:     "_$G(HL7("PON"))
 W !,"        Patient: "_$G(HL7("PAT"))
 W !,"        Pt Data: "_$G(HL7("EXT"))
 W !,"     Pt Address: "_$G(HL7("PADD"))
 ;W !,"       Pt Phone: "_$G(HL7("PPHONE"))
 W !,"        Pt Comm: "
 S LP=0 F  S LP=$O(HL7("PTCOMM",LP)) Q:'LP  D
 .W !,"                 "_HL7("PTCOMM",LP)
 W !,"       Provider: "_$G(HL7("PROV"))_" Ph: "_$G(HL7("PRPH"))
 W !,"   Prov Address: "_$G(HL7("PRADD"))
 W !!,"     Medication: "_$G(HL7("DRUG"))
 W !,"            SIG: "_$G(HL7("SIG"))
 ;W !,"       Pt Instr: "_$G(HL7("INST"))
 W !,"         Supply: "_$G(HL7("SUP"))
 W !,"       Quantity: "_$G(HL7("QTY"))_" "_$G(HL7("NCPDP"))
 W !,"        Refills: "_$G(HL7("REFIL"))_" "_$S($G(HL7("REQUAL"))="PRN":$G(HL7("REQUAL")),1:"")
 W !,"             Dx: "_$G(HL7("DX"))
 W !,"            Sub: "_$G(HL7("SUB"))
 W !,"       Pharmacy: "_$G(HL7("PHARM"))
 W !,"     Ph Address: "_$G(HL7("PHADD"))
 W !," Notes to Pharm: "_$G(HL7("NOTE"))
 ;W !,"       Issue Dt: "_$G(HL7("ISSUE"))  ;p26
 W !!,"  DISPENSED Drug HL7 Information",!
 W !," Dispensed Drug: "_$G(HL7("DDRG"))
 W !,"            SIG: "_$G(HL7("DSIG"))
 W !,"         Supply: "_$G(HL7("DSUP"))
 W !,"       Quantity: "_$G(HL7("DQTY"))_" "_$G(HL7("DFORM"))
 W !,"          Fills: "_$G(HL7("DREFILL"))
 W !,"            Sub: "_$G(HL7("DSUB"))
 W !,"   Written Date: "_$G(HL7("DDATE"))
 W !,"  Notes to Prov: "_$G(HL7("DNOTE"))
 W !,""
 W LINE
 W !,"   MAPPED DATA:",!
 W !,"       Patient: "_$G(MAP("PAT"))
 W !,"       Pt Data: "_$G(MAP("EXT"))
 W !,"       Address: "_$G(MAP("PADDR"))
 W !,"      Pt Phone: "_$G(MAP("PPHONE"))
 W !,"      Provider: "_$G(MAP("PROV"))_" Ph: "_$G(MAP("OFF"))
 W !,"  Prov Address: "_$G(MAP("PROVAD"))
 W !!,"    Medication: "_$G(MAP("DRUG"))
 W !,"           SIG: "_$G(MAP("SIG"))
 W !,"        Supply: "_$G(MAP("SUP"))
 W !,"      Quantity: "_$G(MAP("QTY"))_" "_NOUN
 ;W !,"     Dose Form: "_$G(MAP("DFORM"))
 W !,"       Refills: "_$G(MAP("REFIL"))
 W !,"            Dx: "_$G(MAP("DX"))
 W !,"           Sub: "_$G(MAP("DAW"))
 W !,"      Pharmacy: "_$G(MAP("PHARM"))
 W !,"    Ph Address: "_$G(MAP("PHARMA"))
 ;W !,"        Notes: "_$G(MAP("NOTES"))
 W !!,"  Dosing information: (multiple line items indicates complex dosing)"
 W:$D(SCHARY) !,?3,"Units/Dose",?15,"Interval",?25,"Duration",?35,"Conjunction"
 F K=1:1 D  Q:'$D(SCHARY(K))
 .I $D(SCHARY(K)) W !,?5,$P(SCHARY(K),U),?15,$P(SCHARY(K),U,2),?25,$P(SCHARY(K),U,3),?35,$P(SCHARY(K),U,4)
 W !,LINE
 Q
 ;
HRCN(DFN,SITE) ;EP; IHS/MSC/MGH return chart number
 Q $P($G(^AUPNPAT(DFN,41,SITE,0)),U,2)
GHLDAT(IEN) ; Get HL7 message data from APSP REFILL REQUEST FILE
 N HLMSG
 S HLMSG=$$GET1^DIQ(9009033.91,IEN,5,"","HLDATA")
 Q HLMSG
 ;
CHKDEF(IEN,TEXT) ;
 N FOUND,X
 S FOUND=0
 S X=0 F  S X=$O(^APSPRREQ(ITEM,3,X)) Q:'X  D
 .I $G(^APSPRREQ(ITEM,3,X,0))=TEXT S FOUND=1
 Q FOUND
FMTADD(FIELD) ;
 ;Format the incoming address in HL7 file
 N ADDR,STR,CITY,ST,ZIP
 S ADDR=""
 I FIELD="" Q ADDR
 S STR=$P(FIELD,HLECH(1),1)
 S STR2=$P(FIELD,HLECH(1),2)
 S CITY=$P(FIELD,HLECH(1),3)
 S ST=$P(FIELD,HLECH(1),4)
 S ZIP=$P(FIELD,HLECH(1),5)
 I STR2'="" S STR=STR_" "_STR2
 S ADDR=STR_" "_CITY_", "_ST_" "_ZIP
 Q ADDR
PADDR(IEN) ;
 ;format pharmacy address from APSP Pharmacy file
 N ADDR,STR,STR2,CITY,ST,ZIP
 S ADDR=""
 S STR=$$GET1^DIQ(9009033.9,IEN,1.1,"E")
 S STR2=$$GET1^DIQ(9009033.9,IEN,1.2,"E")
 S CITY=$$GET1^DIQ(9009033.9,IEN,1.3,"E")
 S ST=$$GET1^DIQ(9009033.9,IEN,1.4,"E")
 S ZIP=$$GET1^DIQ(9009033.9,IEN,1.5,"E")
 I STR2'="" S STR=STR_" "_STR2
 S ADDR=STR_" "_CITY_" ,"_ST_" "_ZIP
 Q ADDR
PTADDR(DFN) ;Format patient address
 N ADDR,STR,STR2,CITY,ST,ZIP
 S ADDR=""
 S STR=$$GET1^DIQ(2,DFN,.111,"E")
 S STR2=$$GET1^DIQ(2,DFN,.112,"E")
 S CITY=$$GET1^DIQ(2,DFN,.114,"E")
 S ST=$$GET1^DIQ(2,DFN,.115,"E")
 S ZIP=$$GET1^DIQ(2,DFN,.116,"E")
 I STR2'="" S STR=STR_" "_STR2
 S ADDR=STR_" "_CITY_" ,"_ST_" "_ZIP
 Q ADDR
PROVAD(PROV) ;Format provider address
 N ADDR,STR,STR2,CITY,ST,ZIP
 S ADDR=""
 S STR=$$GET1^DIQ(200,PROV,.111,"E")
 S STR2=$$GET1^DIQ(200,PROV,.112,"E")
 S CITY=$$GET1^DIQ(200,PROV,.114,"E")
 S ST=$$GET1^DIQ(200,PROV,.115,"E")
 S ZIP=$$GET1^DIQ(200,PROV,.116,"E")
 I STR2'="" S STR=STR_" "_STR2
 S ADDR=STR_" "_CITY_" ,"_ST_" "_ZIP
 Q ADDR
DESCAPE(VALUE) ;remove escape characters from value
 N STRING
 S STRING=$$DESCAPE^HLOPRS1(VALUE,DEL,CS,SUBCOMP,REP,ESCAPE)
 Q STRING
SIGTXT(PIECE) ;Parse out multiples
 N X1,SIGX,SIG
 S SIG=""
 S X1=1
 F  S SIGX=$P(PIECE,"~",X1) Q:SIGX=""  D
 .I SIG="" S SIG=SIGX
 .E  S SIG=SIG_" "_SIGX
 .S X1=X1+1
 Q SIG
 ;Extract Patient Communication Info
PCOMARY(RET,VAL) ;-
 N LP,NS,PHN,EX,EM
 K @RET
 F LP=1:1:$L(VAL,"~") D
 .S NS=$P(VAL,"~",LP),PHN=$P(NS,U,1),EX=$P(NS,U,8),EM=$P(NS,U,4)
 .S @RET@(LP)=$$COMUSE($P(NS,U,2))_": "_$S($L(PHN):$$FMTPHN^APSPES2(PHN)_$S($L(EX):" x"_EX,1:""),1:"")_$S($L(EM):"  EMail: "_EM,1:"")
 Q
 ;
COMUSE(USE) ;-
 Q:USE="PRN" "Primary"
 Q:USE="BPN" "Beeper"
 Q:USE="FXN" "Fax"
 Q:USE="HMN" "Home"
 Q:USE="WPN" "Work"
 Q:USE="ORN" "Other"
 Q:USE="NET" "EMail"
 Q "Unknown"
 ;
COMTYP(TYP) ;-
 Q:TYP="BP" "Beeper"
 Q:TYP="CP" "Cell"
 Q:TYP="FX" "Fax"
 Q:TYP="MD" "Modem"
 Q:TYP="PH" "Phone"
 Q:TYP="X.400" "EMail"
 Q "Unknown"
STATCHK(IEN) ;Check to see if status should be changed
 N STAT,TYPE,MATCH,PT,PRV,OI,MATCH
 S STAT=$$GET1^DIQ(9009033.91,IEN,.03,"I")
 S TYPE=$$GET1^DIQ(9009033.91,IEN,.12,"I")
 S PT=$$GET1^DIQ(9009033.91,IEN,1.2,"I")
 S PRV=$$GET1^DIQ(9009033.91,IEN,1.3,"I")
 S OI=$$GET1^DIQ(9009033.91,IEN,1.1,"I")
 S MATCH=$$GET1^DIQ(9009033.91,IEN,.11,"I")
 I TYPE="C" D
 .I FLD=1.2&(+PRV) S STAT=0
 .I FLD=1.3&(+PT) S STAT=0
 E  I TYPE="R" D
 .I FLD=1.2&(+PRV) S STAT=$S('OI:5,1:6)
 .I FLD=1.3&(+PT) S STAT=$S('OI:5,1:6)
 .I ((FLD=1.2&+PRV)!(FLD=1.3&+PT))&(MATCH["M") S STAT=6
 Q STAT
