APSPESM ;IHS/MSC/PLS - Surescripts Mailbox Support;11-Jan-2023 12:01;DU
 ;;7.0;IHS PHARMACY MODIFICATIONS;**1024,1026,1027,1028,1032**;Sep 23, 2004;Build 26
 Q
 ; Returns list of patients with SS orders for the provider
ORDERS(DATA,PRV,DAYS) ;EP
 N LP,N0,SDT,TXDT,CNT,DAT,SRDT,ISSDT,EXPDT
 S DAYS=$G(DAYS,30)
 S SDT=$$FMADD^XLFDT(DT,-DAYS)
 S DATA=$$TMPGBL^CIAVMRPC("_ORDERS")
 K @DATA
 S TXDT=SDT F  S TXDT=$O(^PS(52.51,"AC1",TXDT)) Q:'TXDT  D
 .S LP=0 F  S LP=$O(^PS(52.51,"AC1",TXDT,LP)) Q:'LP  D
 ..S N0=$G(^PS(52.51,LP,0))
 ..Q:$P(N0,U,4)'=PRV
 ..S ISSDT=$$GET1^DIQ(52,+N0,1,"I")
 ..S EXPDT=$$GET1^DIQ(52,+N0,26,"I")
 ..S DAT=TXDT_U_$P(N0,U,2)_U_$$GET1^DIQ(2,$P(N0,U,2),.01)_U_$P(N0,U)_";"_$$GET1^DIQ(52.51,LP,.01)_U_$$GETORDNM(+N0)_U_ISSDT_U_EXPDT_U_$$GET1^DIQ(52,+N0,9999999.02)_U_$$GETORDTX(+N0)
 ..D ADD(DAT)
 Q
 ; Returns list of patients with SS Request
REQUESTS(DATA,PRV,STATUS) ;EP-
 N IEN,CNT,STA,SUR,SUR0,PRVSUR,SURSDT,SUREDT
 S STATUS=$G(STATUS,"016")
 S DATA=$$TMPGBL^CIAVMRPC("_REQUESTS")
 K @DATA
 S (IEN,CNT)=0 F  S IEN=$O(^APSPRREQ("APRV",PRV,IEN)) Q:'IEN  D
 .D REQADD(IEN,STATUS)
 ;Check for surrogates
 S SUR=0 F  S SUR=$O(^XTV(8992,"AC",PRV,SUR)) Q:'SUR  D
 .S SUR0=$G(^XTV(8992,SUR,0))
 .S SURSDT=$P(SUR0,U,3),SUREDT=$P(SUR0,U,4)
 .;todo - Should the return be restricted to Start and Stop dates
 .S IEN=0 F  S IEN=$O(^APSPRREQ("APRV",SUR,IEN)) Q:'IEN  D
 ..D REQADD(IEN,STATUS)
 Q
REQADD(IEN,STATUS) ;-
 Q:'$$CANSHOW^APSPESG(IEN,STATUS)
 S STA=+$P(^APSPRREQ(IEN,0),U,3)
 Q:$$TYPE^APSPESG(IEN,"R")&'STA  ;RxRenewals for STATUS 1
 D ADD($$GETITM^APSPESG(IEN,STATUS))
 Q
 ; Returns list of patients with SS Requests that were denied
DENIED(DATA,PRV,STATUS,DAYS) ;EP-
 N IEN,CNT,SRDT,SDT,D,FAKE,P
 S STATUS=$G(STATUS,3)
 S DAYS=$G(DAYS,30)
 S SDT=$$FMADD^XLFDT(DT,-DAYS)
 S DATA=$$TMPGBL^CIAVMRPC("_DENIED")
 K @DATA
 S (IEN,CNT)=0 F  S IEN=$O(^APSPRREQ("APRV",PRV,IEN)) Q:'IEN  D
 .Q:'$$CANSHOW^APSPESG(IEN,STATUS)
 .Q:'$$DTCHK(IEN,SDT)
 .S D=$$GETITM^APSPESG(IEN,STATUS)
 .I '$P($P(D,U,3),";") D   ;Assign fake IEN if missing
 ..S P=$P(D,U,3)
 ..S $P(P,";")=$$GNXTPNUM($P(P,";",2))
 ..S $P(D,U,3)=P
 .D ADD(D)
 Q
 ; Return Med History requests for provider
MEDHIST(DATA,PRV,DAYS) ;-
 N IEN,CNT,SRDT,SDT,LP,RESIEN
 N PRVD,PTD,STD,REQDT,PTNM,RESDT,CHGFLG,REQSDT,REQEDT
 S DAYS=$G(DAYS,30)
 S SDT=$$FMADD^XLFDT(DT,-DAYS)
 S DATA=$$TMPGBL^CIAVMRPC("_MEDHIST")
 K @DATA
 S LP=0 F  S LP=$O(^APSPMHRQ("C",PRV,LP)) Q:'LP  D
 .S RESIEN=+$$GET1^DIQ(9009033.85,LP,1,"I")
 .S PRVD=PRV_";"_$$GET1^DIQ(200,PRV,.01)
 .S PTD=$$GET1^DIQ(9009033.85,LP,.03,"I")_";"_$$GET1^DIQ(9009033.85,LP,.03)
 .S STD=$$GET1^DIQ(9009033.85,LP,.04)
 .S REQDT=$P(^APSPMHRQ(LP,0),U,1)
 .S PTNM=$$GET1^DIQ(9009033.85,LP,.03)
 .S RESDT=$$GET1^DIQ(9009033.86,RESIEN,.01,"I")
 .S CHGFLG=$$GET1^DIQ(9009033.85,LP,"2:.05","I")
 .S CHGFLG=$S(CHGFLG="Y":1,1:0)
 .S REQSDT=$$GET1^DIQ(9009033.85,LP,.06,"I")
 .S REQEDT=$$GET1^DIQ(9009033.85,LP,.07,"I")
 .D ADD(LP_U_PRVD_U_PTD_U_STD_U_REQDT_U_PTNM_U_RESDT_U_CHGFLG_U_REQSDT_U_REQEDT)
 Q
 ; Returns surrogate list for user
SURROGAT(DATA,PRV) ;EP-
 N SUR,CNT
 S DATA=$$TMPGBL^CIAVMRPC("_SURROGATES")
 S SUR=0 F  S SUR=$O(^XTV(8992,"AC",PRV,SUR)) Q:'SUR  D
 .D ADD(SUR_U_$$GET1^DIQ(200,SUR,.01)_U_$P(^XTV(8992,SUR,0),U,3)_U_$P(^XTV(8992,SUR,0),U,4))
 Q
 ;
ADD(STR) ;-
 S CNT=$G(CNT)+1
 S @DATA@(CNT)=STR
 Q
 ;
DTCHK(IEN,SDT) ;-
 Q $P($G(^APSPRREQ(IEN,0)),U,4)>(SDT-.001)
GETORDTX(RXIEN) ;EP-
 N ORIFN,TXT,RET,LP
 S ORIFN=$$GETORDNM(RXIEN)
 S RET=""
 D GETTXT^ORWORR(.TXT,ORIFN)
 S LP=0 F  S LP=$O(TXT(LP)) Q:'LP  D
 .S RET=RET_$S(RET'="":" "_TXT(LP),1:TXT(LP))
 Q RET
GETORDNM(RXIEN) ;-
 Q $P($G(^PSRX(RXIEN,"OR1")),U,2)
SSMBCHK(PRV) ;-
 N DFN,RET
 S DFN=$$GETVAR^CIANBUTL("PATIENT.ID.MRN",,"CONTEXT.PATIENT")
 S PRV=+$G(PRV,$$GETVAR^CIANBUTL("USER.ID.LOGON.VUECENTRIC",,"CONTEXT.USER"))
 S RET=$$GRECCNT(PRV,"R","16")_$$GRECCNT(PRV,"C","016")_$$GRECCNT(PRV,"V","016")
 Q RET_U_$S(DFN>0:$$PTHASPRQ(DFN),1:0)
SSMBCNT(DATA,PRV) ;EP-
 S DATA=$$SSMBCHK(.PRV)
 Q
 ; Return count of records for a type
GRECCNT(PRV,TYPE,STATUS) ;-
 N IEN,CNT,RES,SUR,PRVSUR,SURSDT,SUREDT
 S (IEN,CNT)=0
 S CNT=$$GRECCNT1(PRV)
 ;Check for surrogates
 S SUR=0 F  S SUR=$O(^XTV(8992,"AC",PRV,SUR)) Q:'SUR  D
 .S PRVSUR=$G(^XTV(8992,PRV,0))
 .S SURSDT=$P(PRVSUR,U,3),SUREDT=$P(PRVSUR,U,4)
 .S CNT=$$GRECCNT1(SUR)
 Q TYPE_CNT
GRECCNT1(PRV) ;-
 F  S IEN=$O(^APSPRREQ("APRV",PRV,IEN)) Q:'IEN  D
 .Q:'$$CANSHOW^APSPESG(IEN,STATUS)
 .Q:'$$TYPE^APSPESG(IEN,$S(TYPE="V":"C",1:TYPE))
 .I TYPE="C" Q:($$CHGTYP^APSPESG(IEN,"P")!($$CHGTYP^APSPESG(IEN,"U")))
 .I TYPE="V" Q:'($$CHGTYP^APSPESG(IEN,"P")!($$CHGTYP^APSPESG(IEN,"U")))
 .S CNT=CNT+1
 Q CNT
 ;
 ; Returns if provider has an active SPI number
PRVACTV(DATA,PRV) ;-  TODO
 N SPI
 S SPI=$$SPI^APSPES1(PRV)
 Q ''SPI
 ; Return string of Request information
GETITM(DATA,REQIEN) ;EP-
 S DATA=$$GETITM^APSPESG(REQIEN,$P(+$G(^APSPRREQ(REQIEN,0)),U,3))
 Q
 ; Returns if patient has a pending request
PTHASPRQ(DFN) ;-
 N RES
 S RES=0
 Q:'$D(^APSPRREQ("E",DFN)) RES
 N IEN
 S IEN=0 F  S IEN=$O(^APSPRREQ("E",DFN,IEN)) Q:'IEN  D  Q:RES
 .;I $D(^APSPRREQ("F",0,IEN))!($D(^APSPRREQ("F",1,IEN))) S RES=1
 .S RES=$$CANSHOW^APSPESG(IEN,"016")
 Q RES
 ; Generate Notification (99008) to prescriber
GSNFRPC(DATA,PRV) ;-
 S DATA=$$GSSNOTIF($G(PRV))
 Q
 ;
GSSNOTIF(PRV) ;-
 Q:'$G(PRV) 0
 D DSSALRT(PRV)  ;Delete notifications
 ;Only fire notification if requests are present
 N CNT
 S CNT=$P($$GRECCNT(PRV,"R","16"),"R",2)+$P($$GRECCNT(PRV,"C","016"),"C",2)+$P($$GRECCNT(PRV,"V","106"),"V",2)
 Q:'CNT 0
 N XQA,XQAID,XQADATA,XQAMSG,XQALERR
 S XQA(PRV)=""
 S XQAID="OR,,99008"
 Q:$$PKGPEND^XQALBUTL(PRV,XQAID) 0  ;Only need one alert
 S XQADATA="@99008"
 S XQAMSG="Surescripts Pending Request"
 Q ''$$SETUP1^XQALERT()
GNXTPNUM(PNAM) ;- Returns a fake identifier if patient hasn't been matched.
 N RET
 S:'$L(PNAM) PNAM="UNKNOWN"
 I $D(FAKE("B",PNAM)) S RET=FAKE("B",PNAM)
 E  D
 .S FAKE=$G(FAKE)+1
 .S FAKE("B",PNAM)=FAKE
 .S RET=FAKE
 Q -RET
 ; Delete Surescripts Pending Request alert(s) for user
DSSALRT(PRV) ;-
 N LP,XQAID,XQAKILL,X
 S LP=0 F  S LP=$O(^XTV(8992,PRV,"XQA",LP)) Q:'LP  S X=$G(^(LP,0)) D
 .Q:X'["OR,,99008"
 .S XQAID=$P(X,U,2)
 .S XQAKILL=0
 .D DELETE^XQALERT
 Q
 ; Return ability of user to process a request
CANPROC(DATA,USR,IEN) ;-
 N TYP,SPI,SVC,MSG
 S MSG=""
 S TYP=$$GET1^DIQ(9009033.91,IEN,.12,"I")
 S SPI=''$L($$SPI^APSPES1(USR))
 S SVC=$$GET^XPAR("USR.`"_USR,"APSP NCPDP USER SERVICE LEVEL",$S(TYP="C":"Change",1:"Refill"))
 S DATA=SPI&SVC
 I 'DATA D
 .S:'SPI MSG="User lacks SPI"
 .S:'SVC MSG=MSG_$S($L(MSG):". ",1:"")_"User does not have the necessary service level for request"
 .I $L(MSG) D
 ..S MSG=MSG_"."
 ..S $P(DATA,U,2)=MSG
 Q
