APSQPMI ;IHS/ASDS/ENM/POC - PRINTS THE PATIENT MEDICATION SHEETS 
 ;;6.0;IHS PHARMACY MODIFICATIONS;**3**;FEB 20, 2001
 ;S DFN=3862
 ;S PPL="55215,55216,55240,55248,"
 ;S PPL="54249,54250,54283,54291,"
EN ;EP - NORMAL ENTRY POINT
 S PSNDFN=DFN
 ;G PMI
 ;CALLED FROM ****
 ;S APSPCPP=$G(APSPCPP,0) ;DID YOU FORGET TO SET APSPCPP
 ;Q:('$D(APSPCCP)!(APSPCCP=IO))
 I ('$D(APSPCPP))!($G(APSPCPP)=ION) G PMI
TSK F I="PPL","APSPCPP","PSNDFN" S ZTSAVE(I)=""
 S ZTRTN="PMI^APSQPMI"
 S ZTDESC="PRINTS PATIENT MED SHEETS"
 S ZTDTH=$H
 S ZTIO=APSPCPP
 S ZTREQ="@"
 D ^%ZTLOAD
 Q
 ;
EN1 ;ENTRY FROM PATIENT NAME
 D PT^PSORX
 S PSONUM="LIST"
 D EN^PSONUM
 G:'$D(PSOLIST) END
 S PPL=PSOLIST(1) ;BETTER WATCH THIS AS IT CAN BE TOO LONG
 ;D PMI Q
 G EN
 ;
PMI ;SET UP AND PRINT
 I $E(IOST)="P" S APSQCOM=$P($G(^%ZIS(2,IOST(0),12.1)),"^"),APSQRSET=$P($G(^(6)),"^") W:APSQCOM]"" @APSQCOM ;COMPRESS IF A PRINTER TO 16 PITCH
 Q:'$D(PPL)  ;NO RXS TO PRINT SO NO MED SHEETS TO PRINT EITHER
 F I=1:1 S APSQIEN=$P(PPL,",",I) Q:'APSQIEN  D
 .S APSQDRG=$P(^PSRX(APSQIEN,0),"^",6)
 .Q:$$TEST(APSQDRG)
 .S APSQRXN=+^PSRX(APSQIEN,0)
 .S PPI=^PSDRUG(APSQDRG,"ND")
 .;S PPI=$P(^PSNDF(+APSQDRG,5,$P(APSQDRG,"^",3),0),"^",7)
 .S PPI=$P(^PSNDF(+PPI,5,$P(PPI,"^",3),0),"^",7)
 .S APSQ(I)=PPI_"^"_APSQDRG_"^"_APSQRXN ;SO ONLY GET ONE OF SHEET EVEN IF TWO DRUGS POINT TO SAME PATIENT INFORMATION SHEET
 .Q
 S TYPE=$S($G(APSQTYPE):APSQTYPE,1:2) ;IHS/OKCAO/POC APSQTYPE IS IN APSPCONTROL FILE FIELD 301
 S NUM=1
PRINT S JJ=0 F  S JJ=$O(APSQ(JJ)) Q:'JJ  S PPI=+APSQ(JJ),DRG=$P(APSQ(JJ),"^",2),PSRX=$P(APSQ(JJ),"^",3) D DOONE^PSNPPIP
END D EN^XBVK("APSQ")
 K PSRX,PSNDFN,NAM
 Q
TEST(N) ;TEST FOR ENTRY OF PATIENT MED SHEET IN ^PSPPI GLOBAL 
 N TEST S TEST=$G(^PSDRUG(N,"ND"))
 S TEST=$P($G(^PSNDF(+TEST,5,+$P(TEST,"^",3),0)),"^",7)
 I TEST,$D(^PSPPI(+TEST)),$S('$G(^PSDRUG(+N,"I")):1,DT'>^("I"):1,1:0) Q 0
 E  Q 1 ;1=NO GO
