DICL1 ;SEA/TOAD-VA FileMan: Lookup: Lister, Part 2 ;2/18/98  10:41 [ 09/09/1998  12:03 PM ]
 ;;21.0;VA Fileman;**1007**;SEP 8, 1998
 ;;21.0;VA FileMan;**17,41**;Dec 28, 1994
 ;Per VHA Directive 10-93-142, this routine should not be modified.
 ;12379;2538541;2601;
 ;
PREP 
 N DIEN,DIENTRY,DIOUT1,DIOUT2,DISUB1
 S DIOUT1=0
 S DIENTRY=DIFROM
 D DA^DILF(DIFIEN,.DIEN)
 I DINDEX("WAY")=1 S DILIST("ORDER")=0
 E  S DILIST("ORDER")=DINUMBER+1
 
REVERSE 
 N DIREVERS,DITO,DITOIN
 I DINUMBER="*",DINDEX("WAY")=-1 D
 . S DIREVERS=1
 . S DITO=DIFROM
 . S DITOIN=DIFROM("IEN")
 . S DINDEX("WAY")=1
 . S DIFROM=DIPART
 . I DIFROM'="" S DIUSEFRM=1
 . S DIFROM("IEN")=""
R1 . S DIENTRY=DIPART
 . S DILIST("ORDER")=0
 . Q
 E  D
 . S DIREVERS=0
 . S DITO=""
 . S DITOIN=""
 . Q
 
PREP2 ; prepare to list entries
 N DICODE,DID,DIDT,DIDVAL
 N DIMSG,DIOUT3,DISKIP,DIVAL,X,Y
 N DICOUNT D
 . S DICOUNT=0
 . S DICOUNT("MAX")=DINUMBER
 . S DICOUNT("JUST LOOKING")=0
 . S DICOUNT("LAST ENTRY")=""
 . S DICOUNT("LAST IEN")=""
 S DIENTRY("PREVIOUS")="",DIENTRY("PREVIOUS EXTERNAL")=""
P1 I +DIPART'=DIPART S DICOUNT("MORE?")=0
 E  D
 . I DINDEX("WAY")=1,+DIFROM=DIFROM S DICOUNT("MORE?")=1 Q
 . I DINDEX("WAY")=-1,+DIFROM'=DIFROM S DICOUNT("MORE?")=1 Q
 . S DICOUNT("MORE?")=0 Q
 I DINDEX("TYPE")="P",DIFLAGS'["I",DIFLAGS'["Q" D
 . S DIFLAGS=DIFLAGS_"p"
 . D POINT(.DIFILE,.DIROOT,.DINDEX,.DIFROM)
 
LONG 
 D
 . N DILENGTH S DILENGTH=+$P(DINDEX("NODE"),">",2)
 . I 'DILENGTH S DILENGTH=99999
 . S DIFROM=$E(DIFROM,1,DILENGTH)
 . S DIPART=$E(DIPART,1,DILENGTH)
 . S DITO=$E(DITO,1,DILENGTH)
 
GETLIST 
 ; I $G(ZRT) S ZRT(ZRT)="BRANCH^"_$ZH,ZRT=ZRT+1
 D LIST^DICL2
 
KTMPIX 
 I $G(DIFILE("NO B")) D
 . I DIFLAGS'["p" K @DIROOT@("B") Q
 . N DILVL,DIROOT F DILVL=1:1:DIFILE("STACK") D
 . . I '$G(DIFILE("STACK",DILVL,"NO B")) Q
 . . S DIROOT=U_$P(DIFILE("STACK",DILVL),U,2)
 . . K @DIROOT@("B")
FINAL 
 I $G(DIERR) K @DILIST D OUT^DICL Q
 S @DILIST@(0)=DICOUNT_U_DICOUNT("MAX")_U_DICOUNT("MORE?")
 K DIFROM("LOOKING FOR START")
 I DICOUNT("MORE?") D
 . S DIFROM=DIENTRY
 . S DIFROM("IEN")=$S(DIFLAGS'["p":DIEN,1:$G(DICOUNT("LAST IEN")))
 E  S DIFROM="",DIFROM("IEN")=""
 Q
 
POINT(DIFILE,DIROOT,DINDEX,DIFROM) ;
 ; prepare to list a pointer index
 S DIFILE("MAIN")=DIFILE
 S DIROOT("MAIN")=DIROOT
 S DIROOT("MAIN O")=DIROOT("O")
 D FOLLOW^DICL3(.DIFILE,.DIROOT,DINDEX("PTR"),DINDEX("NODE"))
 N TEMP M TEMP=DINDEX K DINDEX M DINDEX("MAIN")=TEMP
 S DINDEX="B",DINDEX("WAY")=DINDEX("MAIN","WAY")
 D INDEX^DICU1(.DIFILE,.DINDEX,DIROOT,1)
 S DIFROM("LOOKING FOR START")=DIFROM'=""&(DIFROM("IEN")'="")
 Q
 
 
