DICU2 ;SEA/TOAD-VA FileMan: Lookup Tools, Return IDs ;7/19/95  18:00 ; [ 09/09/1998  12:03 PM ]
 ;;21.0;VA Fileman;**1007**;SEP 8, 1998
 ;;21.0;VA FileMan;**17**;Dec 28, 1994
 ;Per VHA Directive 10-93-142, this routine should not be modified.
 ;11832;3636148;
 
IDS(DIFILE,DIEN,DIFLAGS,DIVALUE,DIROOT,DINDEX,DICOUNT,DIDENT,DILIST,DINODE) 
 ; ENTRY POINT--add an entry's identifiers to a list
 ; proc, DIEN, DINDEX, & DIDENT by reference
 N DICODE,DIDT,DIDVAL
 I DIFLAGS["P" N DICRSR,DILENGTH,DISAVE,DISUB D
 . S DICRSR="",DILENGTH=$L(DINODE(0)),DISAVE="",DISUB=0
 N DID,DIOUT S DID="",DIOUT=0 F  D  Q:DIOUT!$G(DIERR)
 . I DIFLAGS["P" S DID=DISAVE
 . S DID=$O(DIDENT(DID))
 . I DID="" S DIOUT=1 Q
 . I DIFLAGS["P" S (DICRSR,DISAVE)=DID,DID=$O(DIDENT(DICRSR,""))
 . I DID D
I0 . . N DIVAR
 . . S DIVAR=$S(DIFLAGS'["P":"DIDENT(DID)",1:"DIDENT(DICRSR,DID)")
 . . S DIDT=@DIVAR@("TYPE")
 . . S DICODE=$G(@DIVAR@("CODE"))
 . . I DIDT'="C" D
 . . . S @("DIDVAL="_@DIVAR)
 . . . I DIFLAGS'[1 S DIDVAL=$$FORMAT(DIFILE,DID,"I",DIDVAL,DIDT,DICODE)
I1 . . E  D
 . . . N %,%H,%T,A,B,C,D,DFN,I,X,X1,X2,Y,Z,Z0,Z1
 . . . N DA M DA=DIEN S DA=$P(DIEN,",")
 . . . N DIARG S DIARG="D0"
 . . . N DIMAX S DIMAX=$O(DA(""),-1)
 . . . N DIDVAR F DIDVAR=1:1:DIMAX S DIARG=DIARG_",D"_DIDVAR
 . . . N @DIARG F DIDVAR=0:1:DIMAX-1 S @("D"_DIDVAR)=DA(DIMAX-DIDVAR)
 . . . S @("D"_DIMAX)=DA
 . . . X @DIVAR S DIDVAL=X
 . . I DIFLAGS'["P" S @DILIST@("ID",DICOUNT,DID)=DIDVAL
I2 . . E  D ADD(.DINODE,.DISUB,.DILENGTH,DIDVAL)
 .
 . E  D
 . . N %,D,DIC,X,Y,Y1
 . . S D=DINDEX
 . . S DIC=DIROOT("O")
 . . S DIC(0)=$TR(DIFLAGS,"fglpqtuv1")
 . . S X=DIVALUE
 . . M Y=DIEN S Y=$P(DIEN,",")
 . . S Y1=$G(@DIROOT@(+DIEN,0)),Y1=DIEN
 . . N DIX D
 . . . I DIFLAGS'["P" S DIX=DIDENT(DID)
 . . . E  S DIX=DIDENT(DICRSR,DID)
 . . X DIX ;***** NAKED *****
I3 . . I $G(DIERR) D
 . . . N DICONTXT I DID="ZZZ ID" S DICONTXT="Identifier parameter"
 . . . E  S DICONTXT="MUMPS Identifier"
 . . . D ERR^DICF6(120,DIFILE,DIEN,"",DICONTXT)
 I '$G(DIERR) D
 . I DIFLAGS'["P" M @DILIST@("ID","WRITE",DICOUNT)=^TMP("DIMSG",$J) Q
 . N DI S DI="" F  S DI=$O(^TMP("DIMSG",$J,DI)) Q:DI=""  D
 . . D ADD(.DINODE,.DISUB,.DILENGTH,$G(^TMP("DIMSG",$J,DI)))
 K DIMSG,^TMP("DIMSG",$J)
 Q
 
FORMAT(DIFILE,DIFIELD,DIFLAG,DIVALUE,DITYPE,DICODE,DIENTRY) ;
 I DIVALUE="" Q ""
 I DITYPE=$TR(DITYPE,"DOPSV") Q DIVALUE
 Q $$EXTERNAL^DIDU(DIFILE,DIFIELD,"",DIVALUE)
 
 
ADD(DINODE,DISUB,DILENGTH,DINEW) 
 ; sub, add DINEW to DINODE, overflowing if need be
 N DINEWLEN S DINEWLEN=$L(DINEW)
 S DILENGTH=DILENGTH+1+DINEWLEN
 I DILENGTH>255 S DISUB=DISUB+1,DILENGTH=DINEWLEN,DINODE(DISUB)=DINEW Q
 S DINODE(DISUB)=DINODE(DISUB)_U_DINEW
 Q
 
TMPIX(DIROOT) 
 ; called by INDEX^DICU1
 ; builds a temporary B index on files that lack them
 ; DIROOT = global root of file to be temporarily indexed
 N DIENTRY,DIVALUE
 S DIENTRY=0 F  S DIENTRY=$O(@DIROOT@(DIENTRY)) Q:'DIENTRY  D
 . S DIVALUE=$P($G(@DIROOT@(DIENTRY,0)),U) Q:DIVALUE=""
 . S @DIROOT@("B",DIVALUE,DIENTRY)=""
 Q
