BPDMUS ;IHS/CMI/LAB - REPORT;
 ;;2.0;CONTROLLED DRUG EXPORT SYSTEM;**1,4,5,6**;NOV 15, 2011;Build 16
 ;; ;
 ;20220224 patch 6 12215 - add zero report to element update
 W !!,"This option is used to review and update the data elements"
 W !,"that are required by your State when transmitting Controlled Prescription"
 W !,"Drug information to the State.",!!
 W !,"You should only update those elements that are required by your"
 W !,"State.  If an item is required by ASAP it cannot be changed.",!!
 W !,"You must have the Site Parameters set up for your site before"
 W !,"using this option.",!
STATE ;
 S BPDMSTE=""
 K DIC S DIC="^BPDMSITE(",DIC(0)="AEMQ" D ^DIC K DIC
 I Y<0 D EXIT Q
 S BPDMSITE=+Y
 S BPDMSTE=$P(^BPDMSITE(BPDMSITE,0),U,4)
 I BPDMSTE="" W !!,"The State you are in is not defined in the PDM Site Parameters.",!,"Update the site parameters and then return to this option.",! D EXIT,PAUSE Q
 S BPDMVER=$P(^BPDMSITE(BPDMSITE,0),U,3)
 I BPDMVER="" W !!,"The ASAP version required by your state is not entered in the PDM Site",!,"Parameters.  Update the site parameters and then return to this option.",! D EXIT,PAUSE Q
 I $G(BPDMZERO) S BPDMVER="ZERO"
EN ; -- main entry point for BPDM UPDATE STATE REQ ELEMENTS
 D EN^VALM("BPDM UPDATE STATE REQ ELEMENTS")
 D CLEAR^VALM1
 D FULL^VALM1
 D EXIT
 Q
 ;
HDR ; -- header code
 S VALMHDR(1)="Review/Update Required Elements for "_$P(^DIC(5,BPDMSTE,0),U,1)_"."
 I BPDMVER="ZERO" S VALMHDR(1)="Review/Update Required Elements for the Zero Report"
 S X=" #",$E(X,7)="ID",$E(X,17)="Element Description",$E(X,46)="Required?"
 I $G(BPDMVER)="4.2B" S X=" #",$E(X,7)="ID",$E(X,17)="Element Description",$E(X,56)="Required?"  ;20211022 maw patch 5
 S VALMHDR(2)=X
 Q
 ;
INIT ; -- init variables and list array
 K BPDMX,BPDMS,C,BPDMO,BPDMREQ,BPDMREQE
 K BPDMUS S BPDMHIGH="",C=0
 I $E(BPDMVER)=3 D INIT3 Q
 I BPDMVER=1995 D INIT1995 Q
 I BPDMVER="4.2" D INIT42 Q
 I BPDMVER="4.2A" D INIT42A Q
 I BPDMVER="4.2B" D INIT42B Q
 I BPDMVER="ZERO" D ZERO Q
 S BPDMO=0 F  S BPDMO=$O(^BPDMREC("AO",BPDMO)) Q:BPDMO'=+BPDMO  D
 .S BPDMX=0 F  S BPDMX=$O(^BPDMREC("AO",BPDMO,BPDMX)) Q:BPDMX'=+BPDMX  D
 ..S BPDMP=0 F  S BPDMP=$O(^BPDMREC(BPDMX,11,"AP",BPDMP)) Q:BPDMP'=+BPDMP  D
 ...S BPDMI=0 F  S BPDMI=$O(^BPDMREC(BPDMX,11,"AP",BPDMP,BPDMI)) Q:BPDMI'=+BPDMI  D
 ....S BPDMID=$P(^BPDMREC(BPDMX,11,BPDMI,0),U,1)
 ....Q:BPDMID?.A
 ....S C=C+1
 ....;I '$D(^BPDMREC(BPDMX,11,BPDMI,12,BPDMSTE,0)) S X="State Information Missing"
 ....S BPDMREQ=$P($G(^BPDMREC(BPDMX,11,BPDMI,12,BPDMSTE,0)),U,2) S BPDMREQE=$$EXTSET^XBFUNC(9002315.031112,.02,BPDMREQ)
 ....S X=""
 ....S X=C_")  ",$E(X,8)=BPDMID,$E(X,17)=$E($P(^BPDMREC(BPDMX,11,BPDMI,0),U,2),1,25),$E(X,46)=BPDMREQE
 ....S BPDMUS(C,0)=X
 ....S BPDMUS("IDX",C,C)=BPDMX_U_BPDMI
 .Q
 S (VALMCNT,BPDMHIGH)=C
 Q
 ;
INIT3 ;
 S BPDMO=0 F  S BPDMO=$O(^BPDMVTRD("AO",BPDMO)) Q:BPDMO'=+BPDMO  D
 .S BPDMX=0 F  S BPDMX=$O(^BPDMVTRD("AO",BPDMO,BPDMX)) Q:BPDMX'=+BPDMX  D
 ..S BPDMP=0 F  S BPDMP=$O(^BPDMVTRD(BPDMX,11,"AP",BPDMP)) Q:BPDMP'=+BPDMP  D
 ...S BPDMI=0 F  S BPDMI=$O(^BPDMVTRD(BPDMX,11,"AP",BPDMP,BPDMI)) Q:BPDMI'=+BPDMI  D
 ....S BPDMID=$P(^BPDMVTRD(BPDMX,11,BPDMI,0),U,1)
 ....Q:BPDMID?.A
 ....S C=C+1
 ....;I '$D(^BPDMVTRD(BPDMX,11,BPDMI,12,BPDMSTE,0)) S X="State Information Missing"
 ....S BPDMREQ=$P($G(^BPDMVTRD(BPDMX,11,BPDMI,12,BPDMSTE,0)),U,2) S BPDMREQE=$$EXTSET^XBFUNC(9002315.031112,.02,BPDMREQ)
 ....S X=""
 ....S X=C_")  ",$E(X,8)=BPDMID,$E(X,17)=$E($P(^BPDMVTRD(BPDMX,11,BPDMI,0),U,2),1,25),$E(X,46)=BPDMREQE
 ....S BPDMUS(C,0)=X
 ....S BPDMUS("IDX",C,C)=BPDMX_U_BPDMI
 .Q
 S (VALMCNT,BPDMHIGH)=C
 Q
INIT1995 ;
 S BPDMO=0 F  S BPDMO=$O(^BPDMRDNF("AO",BPDMO)) Q:BPDMO'=+BPDMO  D
 .S BPDMX=0 F  S BPDMX=$O(^BPDMRDNF("AO",BPDMO,BPDMX)) Q:BPDMX'=+BPDMX  D
 ..S BPDMP=0 F  S BPDMP=$O(^BPDMRDNF(BPDMX,11,"AP",BPDMP)) Q:BPDMP'=+BPDMP  D
 ...S BPDMI=0 F  S BPDMI=$O(^BPDMRDNF(BPDMX,11,"AP",BPDMP,BPDMI)) Q:BPDMI'=+BPDMI  D
 ....S BPDMID=$P(^BPDMRDNF(BPDMX,11,BPDMI,0),U,1)
 ....Q:BPDMID?.A
 ....S C=C+1
 ....;I '$D(^BPDMRDNF(BPDMX,11,BPDMI,12,BPDMSTE,0)) S X="State Information Missing"
 ....S BPDMREQ=$P($G(^BPDMRDNF(BPDMX,11,BPDMI,12,BPDMSTE,0)),U,2) S BPDMREQE=$$EXTSET^XBFUNC(9002315.031112,.02,BPDMREQ)
 ....S X=""
 ....S X=C_")  ",$E(X,8)=BPDMID,$E(X,46)=BPDMREQE
 ....S BPDMUS(C,0)=X
 ....S BPDMUS("IDX",C,C)=BPDMX_U_BPDMI
 .Q
 S (VALMCNT,BPDMHIGH)=C
 Q
INIT42 ;
 S BPDMO=0 F  S BPDMO=$O(^BPDMRECA("AO",BPDMO)) Q:BPDMO'=+BPDMO  D
 .S BPDMX=0 F  S BPDMX=$O(^BPDMRECA("AO",BPDMO,BPDMX)) Q:BPDMX'=+BPDMX  D
 ..S BPDMP=0 F  S BPDMP=$O(^BPDMRECA(BPDMX,11,"AP",BPDMP)) Q:BPDMP'=+BPDMP  D
 ...S BPDMI=0 F  S BPDMI=$O(^BPDMRECA(BPDMX,11,"AP",BPDMP,BPDMI)) Q:BPDMI'=+BPDMI  D
 ....S BPDMID=$P(^BPDMRECA(BPDMX,11,BPDMI,0),U,1)
 ....Q:BPDMID?.A
 ....S C=C+1
 ....;I '$D(^BPDMREC(BPDMX,11,BPDMI,12,BPDMSTE,0)) S X="State Information Missing"
 ....S BPDMREQ=$P($G(^BPDMRECA(BPDMX,11,BPDMI,12,BPDMSTE,0)),U,2) S BPDMREQE=$$EXTSET^XBFUNC(9002315.071112,.02,BPDMREQ)
 ....S X=""
 ....S X=C_")  ",$E(X,8)=BPDMID,$E(X,17)=$E($P(^BPDMRECA(BPDMX,11,BPDMI,0),U,2),1,25),$E(X,46)=BPDMREQE
 ....S BPDMUS(C,0)=X
 ....S BPDMUS("IDX",C,C)=BPDMX_U_BPDMI
 .Q
 S (VALMCNT,BPDMHIGH)=C
 Q
INIT42A ;
 S BPDMO=0 F  S BPDMO=$O(^BPDMRECB("AO",BPDMO)) Q:BPDMO'=+BPDMO  D
 .S BPDMX=0 F  S BPDMX=$O(^BPDMRECB("AO",BPDMO,BPDMX)) Q:BPDMX'=+BPDMX  D
 ..S BPDMP=0 F  S BPDMP=$O(^BPDMRECB(BPDMX,11,"AP",BPDMP)) Q:BPDMP'=+BPDMP  D
 ...S BPDMI=0 F  S BPDMI=$O(^BPDMRECB(BPDMX,11,"AP",BPDMP,BPDMI)) Q:BPDMI'=+BPDMI  D
 ....S BPDMID=$P(^BPDMRECB(BPDMX,11,BPDMI,0),U,1)
 ....Q:BPDMID?.A
 ....S C=C+1
 ....;I '$D(^BPDMREC(BPDMX,11,BPDMI,12,BPDMSTE,0)) S X="State Information Missing"
 ....S BPDMREQ=$P($G(^BPDMRECB(BPDMX,11,BPDMI,12,BPDMSTE,0)),U,2) S BPDMREQE=$$EXTSET^XBFUNC(9002315.111112,.02,BPDMREQ)
 ....S X=""
 ....S X=C_")  ",$E(X,8)=BPDMID,$E(X,17)=$E($P(^BPDMRECB(BPDMX,11,BPDMI,0),U,2),1,25),$E(X,46)=BPDMREQE
 ....S BPDMUS(C,0)=X
 ....S BPDMUS("IDX",C,C)=BPDMX_U_BPDMI
 .Q
 S (VALMCNT,BPDMHIGH)=C
 Q
 ;
INIT42B ;
 S BPDMO=0 F  S BPDMO=$O(^BPDMRECC("AO",BPDMO)) Q:BPDMO'=+BPDMO  D
 .S BPDMX=0 F  S BPDMX=$O(^BPDMRECC("AO",BPDMO,BPDMX)) Q:BPDMX'=+BPDMX  D
 ..S BPDMP=0 F  S BPDMP=$O(^BPDMRECC(BPDMX,11,"AP",BPDMP)) Q:BPDMP'=+BPDMP  D
 ...S BPDMI=0 F  S BPDMI=$O(^BPDMRECC(BPDMX,11,"AP",BPDMP,BPDMI)) Q:BPDMI'=+BPDMI  D
 ....S BPDMID=$P(^BPDMRECC(BPDMX,11,BPDMI,0),U,1)
 ....Q:BPDMID?.A
 ....S C=C+1
 ....;I '$D(^BPDMREC(BPDMX,11,BPDMI,12,BPDMSTE,0)) S X="State Information Missing"
 ....S BPDMREQ=$P($G(^BPDMRECC(BPDMX,11,BPDMI,12,BPDMSTE,0)),U,2) S BPDMREQE=$$EXTSET^XBFUNC(9002315.131112,.02,BPDMREQ)
 ....S X=""
 ....S X=C_")  ",$E(X,8)=BPDMID,$E(X,17)=$E($P(^BPDMRECC(BPDMX,11,BPDMI,0),U,2),1,35),$E(X,56)=BPDMREQE
 ....S BPDMUS(C,0)=X
 ....S BPDMUS("IDX",C,C)=BPDMX_U_BPDMI
 .Q
 S (VALMCNT,BPDMHIGH)=C
 Q
 ;
ZERO ;
 ;20220221 patch 6 12215
 S BPDMO=0 F  S BPDMO=$O(^BPDMZERO("AO",BPDMO)) Q:BPDMO'=+BPDMO  D
 .S BPDMX=0 F  S BPDMX=$O(^BPDMZERO("AO",BPDMO,BPDMX)) Q:BPDMX'=+BPDMX  D
 ..S BPDMP=0 F  S BPDMP=$O(^BPDMZERO(BPDMX,11,"AP",BPDMP)) Q:BPDMP'=+BPDMP  D
 ...S BPDMI=0 F  S BPDMI=$O(^BPDMZERO(BPDMX,11,"AP",BPDMP,BPDMI)) Q:BPDMI'=+BPDMI  D
 ....S BPDMID=$P(^BPDMZERO(BPDMX,11,BPDMI,0),U,1)
 ....Q:BPDMID?.A
 ....S C=C+1
 ....;I '$D(^BPDMREC(BPDMX,11,BPDMI,12,BPDMSTE,0)) S X="State Information Missing"
 ....S BPDMREQ=$P($G(^BPDMZERO(BPDMX,11,BPDMI,12,BPDMSTE,0)),U,2) S BPDMREQE=$$EXTSET^XBFUNC(9002315.121112,.02,BPDMREQ)
 ....S X=""
 ....S X=C_")  ",$E(X,8)=BPDMID,$E(X,17)=$E($P(^BPDMZERO(BPDMX,11,BPDMI,0),U,2),1,35),$E(X,56)=BPDMREQE
 ....S BPDMUS(C,0)=X
 ....S BPDMUS("IDX",C,C)=BPDMX_U_BPDMI
 .Q
 S (VALMCNT,BPDMHIGH)=C
 Q
 ;
HELP ; -- help code
 S X="?" D DISP^XQORM1 W !!
 Q
 ;
EXIT ; -- exit code
 K DIC
 D EN^XBVK("BPDM")
 Q
 ;
EXPND ; -- expand code
 Q
 ;
 ;
BACK ;go back to listman
 D TERM^VALM0
 S VALMBCK="R"
 D INIT
 D HDR
 K DIR
 K X,Y,Z,I
 Q
 ;
EDIT ;EP - edit an item
 D FULL^VALM1
 W ! K DIR
 S DIR(0)="NO^1:"_BPDMHIGH,DIR("A")="Edit Which Item"
 D ^DIR K DIR S:$D(DUOUT) DIRUT=1
 I Y="" W !,"No item selected." G REMX
 I $D(DIRUT) W !,"No item selected." G REMX
 S BPDMX=$P(BPDMUS("IDX",Y,Y),U,1),BPDMI=$P(BPDMUS("IDX",Y,Y),U,2)
 ;get the id and see if it is required by ASAP and if so, don't allow change/edit
 I $E(BPDMVER)=3 S BPDMID=$P(^BPDMVTRD(BPDMX,11,BPDMI,0),U,1)
 I BPDMVER="4.0" S BPDMID=$P(^BPDMREC(BPDMX,11,BPDMI,0),U,1)  ;TODO check to see what bdmver is for 4
 I BPDMVER="4.2" S BPDMID=$P(^BPDMRECA(BPDMX,11,BPDMI,0),U,1)
 I BPDMVER=1995 S BPDMID=$P(^BPDMRDNF(BPDMX,11,BPDMI,0),U,1)
 I BPDMVER="4.2A" S BPDMID=$P(^BPDMRECB(BPDMX,11,BPDMI,0),U,1)
 I BPDMVER="4.2B" S BPDMID=$P(^BPDMRECC(BPDMX,11,BPDMI,0),U,1)
 I BPDMVER="ZERO" S BPDMID=$P(^BPDMZERO(BPDMX,11,BPDMI,0),U,1)
 ;I $D(^BPDMCTRL("AREQ",BPDMVER,BPDMID)) W !!,"That item is required by ASAP, you cannot change it.",! D PAUSE G REMX
 ;sure
 D ^XBFMK
 ;cmi/maw 20211028 p5 split line below
 S DA(2)=BPDMX
 S DA(1)=BPDMI
 S DA=BPDMSTE
 S VER=BPDMVER
 S DIE=$S(VER=1995:"^BPDMRDNF(",$G(VER)="ZERO":"^BPDMZERO(",$G(VER)="4.2B":"^BPDMRECC(",$G(VER)="4.2A":"^BPDMRECB(",$G(VER)="4.2":"^BPDMRECA(",$E(VER)=4:"^BPDMREC(",$E(VER)=3:"^BPDMVTRD(")_BPDMX_",11,"_BPDMI_",12,",DR=".02"
 D ^DIE
 K VER
REMX ;
 D ^XBFMK
 D BACK
 Q
PAUSE ;EP
 S DIR(0)="EO",DIR("A")="Press return to continue...." D ^DIR K DIR S:$D(DUOUT) DIRUT=1
 Q
