BPDMDR3 ; IHS/CMI/LAB - MAIN DRIVER FOR PDM REPORT ;
 ;;2.0;CONTROLLED DRUG EXPORT SYSTEM;**1,6**;NOV 15, 2011;Build 16
V1995 ;
 S BPDMCDI=""
 S BPDMDRUG=$P(^PSRX(BPDMR,0),U,6)
 S BPDMNDC=$P($G(^PSRX(BPDMR,2)),U,7)
 I BPDMNDC="" S BPDMNDC=$$VAL^XBDIQ1(50,BPDMDRUG,31)
 I BPDMNDC="" S BPDMMSG="NDC MISSING FOR THIS DRUG",BPDME=1 D RECORD Q
 S BPDMPROV=""
 I BPDMPART="01" S BPDMPROV=$P($G(^PSRX(BPDMR,"P",BPDMPFI,0)),U,17)
 I BPDMPROV="" S BPDMPROV=$P(BPDMREC,U,4)
 S BPDMORD=0 F  S BPDMORD=$O(^BPDMRDNF("AO",BPDMORD)) Q:BPDMORD'=+BPDMORD!(BPDME)  D
 .S BPDMX=$O(^BPDMRDNF("AO",BPDMORD,0))
 .Q:'$P(^BPDMRDNF(BPDMX,0),U,5)  ;DON'T DO PRE-CHECK
 .Q:$P(^BPDMRDNF(BPDMX,0),U,4)="N"  ;not used so skip it
 .S BPDMSID=$P(^BPDMRDNF(BPDMX,0),U,1)
 .;I $P(^PSDRUG(BPDMDRUG,0),U,3)[0!($P(^PSDRUG(BPDMDRUG,0),U,3)["M") S BPDMCDI=1
 .;I 'BPDMCDI,BPDMSID="CDI" Q
 .D V19951
 D N
 Q
REQ(T,I,S) ;EP  T segment ID, I is field ID, S is State ien
 NEW J,K,R
 S J=$O(^BPDMRDNF("B",T,0))
 I 'J Q ""
 S K=$O(^BPDMRDNF(J,11,"B",I,0))
 I 'K Q ""
 S R=$P($G(^BPDMRDNF(J,11,K,12,S,0)),U,2)
 I R="N" Q 0
 I R="RWA" Q 2
 Q 1
V19951 ;
 S BPDMSID=$P(^BPDMRDNF(BPDMX,0),U,1)
 S BPDMY=0 F  S BPDMY=$O(^BPDMRDNF(BPDMX,11,BPDMY)) Q:BPDMY'=+BPDMY!(BPDME)  D
 .S BPDMID=$P(^BPDMRDNF(BPDMX,11,BPDMY,0),U,1)
 .S BPDMREQ=$$REQ(BPDMSID,BPDMID,BPDMSTE)
 .Q:'BPDMREQ  ;$$REQ(BPDMSID,BPDMID,BPDMSTE)  ;not required so don't bother
 .S X=""
 .X ^BPDMRDNF(BPDMX,11,BPDMY,11)
 .I X="",BPDMREQ=1 S BPDMMSG=$P(^BPDMRDNF(BPDMX,11,BPDMY,0),U,2)_" is missing and is required.",BPDME=1 D RECORD Q
 Q
N Q:BPDME
 S BPDMMSG="EXPORTED" D RECORD
 S ^TMP($J,"EXPORT",DFN,BPDMR,BPDMRF,$G(BPDMPFI))=BPDMPART_U_BPDMSTAT
 Q
 ;
RECORD ;EP count and build tx
 ;if 4th piece is 1 it is a true error, otherwise if no export ju
 I $G(BPDME) D
 .S $P(^TMP($J,"ERROR",BPDMR),U,1)=BPDMR
 .S $P(^TMP($J,"ERROR",BPDMR),U,2)=BPDMMSG
 .S $P(^TMP($J,"ERROR",BPDMR),U,3)=BPDMRF
 .S $P(^TMP($J,"ERROR",BPDMR),U,4)=BPDMPFI
 .S $P(^TMP($J,"ERROR",BPDMR),U,5)=BPDMSTAT
 .S $P(^TMP($J,"ERROR",BPDMR),U,6)=BPDMFD
 .I $G(BPDME)=1 S BPDM("ERROR COUNT")=BPDM("ERROR COUNT")+1,$P(^TMP($J,"ERROR",BPDMR),U,4)=1,BPDMQFLG=1
 S $P(^TMP($J,"REVIEWED",BPDMR),U,1)=BPDMR
 S $P(^TMP($J,"REVIEWED",BPDMR),U,2)=BPDMMSG
 S $P(^TMP($J,"REVIEWED",BPDMR),U,3)=BPDMRF
 S $P(^TMP($J,"REVIEWED",BPDMR),U,4)=BPDMPFI
 S $P(^TMP($J,"REVIEWED",BPDMR),U,5)=BPDMSTAT
 S $P(^TMP($J,"REVIEWED",BPDMR),U,6)=BPDMFD
 I $G(BPDME)=1 S $P(^TMP($J,"REVIEWED",BPDMR),U,7)=1
 K BPDMMSG
 Q
TAPE ;EP - create and COPY TRANSACTIONS TO TAPE
 K BPDMCNT S BPDMCNT=0,BPDM("REC COUNT")=0
 ;do header record TH
 S BPDMFILE=$$FN(BPDMSITE,BPDM("RUN LOG"),BPDMPTYP)
 S Y=$$OPEN^%ZISH(BPDMSDIR,BPDMFILE,"W")
 I Y I '$D(ZTQUEUED) S BPDMNOFI=1 W !!,"Failed to create export file" Q  ;20220202 Patch 1 73211
 I Y,$D(ZTQUEUED) S BPDMQFLG=1,BPDMQMSG="COULD NOT OPEN HOST FILE "_BPDMSDIR_" "_BPDMFILE Q
 U IO
 K BPDMRCD
 S DFN=0 F  S DFN=$O(^TMP($J,"EXPORT",DFN)) Q:DFN'=+DFN  D
 .S BPDMR=0 F  S BPDMR=$O(^TMP($J,"EXPORT",DFN,BPDMR)) Q:BPDMR'=+BPDMR  D
 ..S BPDMRF="" F  S BPDMRF=$O(^TMP($J,"EXPORT",DFN,BPDMR,BPDMRF)) Q:BPDMRF=""  D
 ...S BPDMPFI="" F  S BPDMPFI=$O(^TMP($J,"EXPORT",DFN,BPDMR,BPDMRF,BPDMPFI)) Q:BPDMPFI=""  D
 ....;1995 segment
 ....S BPDMT=""
 ....S BPDMPART=$P(^TMP($J,"EXPORT",DFN,BPDMR,BPDMRF,BPDMPFI),U,1)
 ....S BPDMSTAT=$P(^TMP($J,"EXPORT",DFN,BPDMR,BPDMRF,BPDMPFI),U,2)
 ....S BPDMRDNF=^PSRX(BPDMR,0)
 ....S BPDMDRUG=$P(BPDMRDNF,U,6)
 ....S BPDMNDC=$P($G(^PSRX(BPDMR,2)),U,7)
 ....I BPDMNDC="" S BPDMNDC=$$VAL^XBDIQ1(50,BPDMDRUG,31)
 ....S BPDMNDC=$TR(BPDMNDC,"-","")
 ....S BPDMNDC=$$LZERO(BPDMNDC,11)
 ....S BPDMPROV=""
 ....I BPDMPART="01" S BPDMPROV=$P($G(^PSRX(BPDMR,"P",BPDMPFI,0)),U,17)
 ....I BPDMPROV="" S BPDMPROV=$P(BPDMRDNF,U,4)
 ....S BPDMFD=$$DATEFILL^BPDMUTL(BPDMR,$G(BPDMRF),$G(BPDMPFI),BPDMPART)
 ....I BPDMFD="",BPDMSTAT="02" S BPDMFD=BPDMOFD
 ....S BPDMORD="" F  S BPDMORD=$O(^BPDMRDNF("AO",BPDMORD)) Q:BPDMORD=""  D
 .....S BPDMY=$O(^BPDMRDNF("AO",BPDMORD,0))
 .....S BPDMC=0 F  S BPDMC=$O(^BPDMRDNF(BPDMY,11,"AP",BPDMC)) Q:BPDMC=""  D
 ......S BPDMX=0 F  S BPDMX=$O(^BPDMRDNF(BPDMY,11,"AP",BPDMC,BPDMX)) Q:BPDMX=""  D
 .......D REC
 ....W BPDMT,!
 ....Q
 ...Q
 D ^%ZISC
 Q
 ;
REC ;
 S X=""
 S BPDMID=$P(^BPDMRDNF(BPDMY,11,BPDMX,0),U,1)
 I '$$REQ(BPDMSID,BPDMID,BPDMSTE) Q  ;not required so don't bother
 X ^BPDMRDNF(BPDMY,11,BPDMX,11)
 S $E(BPDMT,BPDMC)=$E(X,1,$P(^BPDMRDNF(BPDMY,11,BPDMX,0),U,4))
 Q
 ;
FN(O,L,T) ;EP
 NEW FN,F,E
 S (FN,F,E)=""
 ;get 1st piece, if blank get Pharmacy DEA#, if blank get pharmacy name
 S F=$P($G(^BPDMSITE(O,11)),U,3)
 I F="" S F=$P(^BPDMSITE(O,0),U,8)
 I F="" S F=$P(^BPDMSITE(O,0),U,2)
 S F=$$STRIP^XLFSTR(F," ")
 I F="" S F="pdm_"_$$VAL^XBDIQ1(9002315.01,O,.01)  ;_$S(T="T":"T",1:"")
 I $G(F)]"" S F=F_"_"_(1700+$E(DT,1,3))_$E(DT,4,7)  ;CMI/GRL  add date to filename
 ;I $G(T)]"" S F=F_$S(T="T":"T",1:"")
 S E=$S(T="T":"T",1:"")_$$VAL^XBDIQ1(9002315.01,O,1104)  ;CMI/GRL
 I E="" S E=$S(T="T":"T",1:"")_".dat"  ;CMI/GRL
 S FN=F_"_"_L_E
 Q FN
DATE(D) ;EP
 I $G(D)="" Q ""
 Q (1700+$E(D,1,3))_$E(D,4,5)_$E(D,6,7)
RZERO(V,L) ;ep right zero fill 
 NEW %,I
 S %=$L(V),Z=L-% F I=1:1:Z S V=V_"0"
 Q V
LBLK(V,L) ;left blank fill
 NEW %,I
 S %=$L(V),Z=L-% F I=1:1:Z S V=" "_V
 Q V
RBLK(V,L) ;EP right blank fill
 NEW %,I
 S %=$L(V),Z=L-% F I=1:1:Z S V=V_" "
 Q V
LZERO(V,L) ;EP - left zero fill
 NEW %,I
 S %=$L(V),Z=L-% F I=1:1:Z S V="0"_V
 Q V
 ;
PHONE(P) ;EP
 NEW Y
 S Y=$P($G(^DPT(P,.13)),U,1)
 I Y="" Q ""
 NEW C,E,N
 S N=Y
 F C=1:1:$L(Y) S E=$E(Y,C) I E'?1N S N=$$STRIP^XLFSTR(N,E)
 I N'?10N S N=""
 Q N
CTR(X,Y) ;EP - Center X in a field Y wide.
 Q $J("",$S($D(Y):Y,1:IOM)-$L(X)\2)_X
 ;----------
USR() ;EP - Return name of current user from ^VA(200.
 Q $S($G(DUZ):$S($D(^VA(200,DUZ,0)):$P(^(0),U),1:"UNKNOWN"),1:"DUZ UNDEFINED OR 0")
 ;----------
LOC() ;EP - Return location name from file 4 based on DUZ(2).
 Q $S($G(DUZ(2)):$S($D(^DIC(4,DUZ(2),0)):$P(^(0),U),1:"UNKNOWN"),1:"DUZ(2) UNDEFINED OR 0")
