BPDMZERO ;ihs/cmi/maw - BPDM Zero Report
 ;;2.0;CONTROLLED DRUG EXPORT SYSTEM;**4,6,7**;NOV 15, 2011;Build 51
 Q
 ;
ZEROSET(BD,ED)  ;-- setup the zero report
 S BPDMISBD=BD,BPDMISED=ED
 W:'$D(ZTQUEUED) !,"Now generating a ZERO REPORT export..."
 S BPDM("RUN BEGIN")=BD_".000001",BPDM("RUN END")=ED_".235959"
 S BPDM("X")=$$FMTE^XLFDT(BD),BPDM("Y")=$$FMTE^XLFDT(ED)
 W:'$D(ZTQUEUED) !!,"The ZERO REPORT dates for this run are ",BPDM("X")," through ",BPDM("Y"),"."
 Q
 ;
RPT  ;lets generate the zero report
 K BPDMCNT S BPDMCNT=0,BPDM("REC COUNT")=0,BPDM("COUNT")=1
 S BPDMZFL=0
 ;do header record TH
 S BPDMFILE=$$FN^BPDMUTL(BPDMSITE,BPDM("RUN LOG"),BPDMPTYP)
 S Y=$$OPEN^%ZISH(BPDMSDIR,BPDMFILE,"W")
 I Y I '$D(ZTQUEUED) W !!,"Failed to create export file" S BPDMZFL=1,BPDMNOFI=1 Q
 I Y,$D(ZTQUEUED) S BPDMQFLG=1,BPDMQMSG="Failed to create export file "_BPDMSDIR_" "_BPDMFILE Q
 U IO
 K BPDMRCD
 S BPDMTP1=0,BPDMTT2=0
 S BPDMTYPE="TH" D REC S BPDMTT2=BPDMTT2+1 ;header record
 S BPDMTYPE="IS" D REC S BPDMTT2=BPDMTT2+1 ;information source record
 S BPDMTYPE="PHA" D REC S BPDMTP1=BPDMTP1+1,BPDMTT2=BPDMTT2+1 ;pharmacy record
 S BPDMTYPE="PAT" D REC S BPDMTP1=BPDMTP1+1,BPDMTT2=BPDMTT2+1  ;PATIENT DETAIL
 S BPDMTYPE="DSP" D REC S BPDMTP1=BPDMTP1+1,BPDMTT2=BPDMTT2+1
 S BPDMTYPE="PRE" D REC S BPDMTP1=BPDMTP1+1,BPDMTT2=BPDMTT2+1
 S BPDMTYPE="CDI" D REC S BPDMTP1=BPDMTP1+1,BPDMTT2=BPDMTT2+1
 S BPDMTYPE="AIR" D REC S BPDMTP1=BPDMTP1+1,BPDMTT2=BPDMTT2+1
 S BPDM("REC COUNT")=BPDM("REC COUNT")+1
 S BPDMTYPE="TP" D REC S BPDMTT2=BPDMTT2+1
 ;S BPDMTYPE="TT" D REC S BPDMTT2=BPDMTT2+1
 S BPDMTYPE="TT",BPDMTT2=BPDMTT2+1 D REC
 D ^%ZISC
 Q
 ;
REC ;
 S BPDMT=""
 S BPDMRIEN=$O(^BPDMZERO("B",BPDMTYPE,0))
 I BPDMRIEN="" W !,"BAD - ",BPDMTYPE,BPDMBOMB
 S BPDMY=0,BPDMT="" F  S BPDMY=$O(^BPDMZERO(BPDMRIEN,11,BPDMY)) Q:BPDMY'=+BPDMY  D
 .S X=""
 .S BPDMID=$P(^BPDMZERO(BPDMRIEN,11,BPDMY,0),U,1)
 .S BPDMP=$P(^BPDMZERO(BPDMRIEN,11,BPDMY,0),U,3)  ;piece
 .S X=""
 .I '$$REQZ^BPDMUTL(BPDMTYPE,BPDMID,BPDMSTE) S $P(BPDMT,BPDMFS,BPDMP)=X Q  ;not required so don't bother
 .;I '$$REQZ^BPDMUTL(BPDMTYPE,BPDMID,BPDMSTE) S BPDMT=BPDMT_$S(BPDMT]"":BPDMFS,1:"")_X Q  ;not required so don't bother
 .X ^BPDMZERO(BPDMRIEN,11,BPDMY,11)
 .I $P(^BPDMZERO(BPDMRIEN,11,BPDMY,0),U,1)="DSP01",$$VAL^XBDIQ1(9002315.01,BPDMSITE,.04)="MINNESOTA",$$VALI^XBDIQ1(9002315.01,BPDMSITE,.03)="4.0",X="00" S X=""
 .S $P(BPDMT,BPDMFS,BPDMP)=X
 S BPDMT=BPDMT_BPDMSS
 W BPDMT
 Q
 ;
IS03() ;-- get IS03 date range
 N IS03
 I '$G(BPDMISBD) S BPDMISBD=$P($P(^BPDMLOG(BPDM("RUN LOG"),0),U,2),".")
 I '$G(BPDMISED) S BPDMISED=$P($P(^BPDMLOG(BPDM("RUN LOG"),0),U,3),".")
 S X1=DT,X2=-1 D C^%DTC S IS03B=$$FMTHL7^XLFDT(BPDMISBD),IS03E=$$FMTHL7^XLFDT(BPDMISED)
 Q "#"_IS03B_"#-#"_IS03E_"#"
 ;
DSP05() ;-- get DSP05 date
 N DSP05
 S X1=DT,X2=-1 D C^%DTC S DSP05=$$FMTHL7^XLFDT(X)
 Q DSP05
 ;
