BPDMDR1N ; IHS/CMI/LAB - MAIN DRIVER FOR PDM REPORT ;
 ;;2.0;CONTROLLED DRUG EXPORT SYSTEM;**1,4,5,6,7**;NOV 15, 2011;Build 51
 ;
PROCESS ;EP
 K ^TMP($J)
 S BPDM("COUNT")=0,BPDMQFLG=0
 S BPDMCMOP=0
 S BPDMDTAX=$O(^ATXAX("B","BPDM DRUGS FOR PDM",0))
 W:'$D(ZTQUEUED) !,"Reviewing prescriptions...........  (1)"
 ;S BPDMSTAT="00"
 ;S BPDMPART="02"
 S BPDMPFI=0  ;not partials
 S BPDMLL=$$FNDLST(BPDMOSIT,1)  ;cmi/maw p4 find last export start there
 I $G(BPDMLL) S BPDM("CONTROL DATE")=$P($G(^BPDMLOG(BPDMLL,0)),U,3)  ;cmi/maw
 I '$G(BPDMLL) S BPDM("CONTROL DATE")=BPDM("RUN BEGIN")
 I $G(BPDMRTYP)=2 S BPDM("CONTROL DATE")=BPDM("RUN BEGIN")
 S BPDM("OCONTROL DATE")=$G(BPDM("CONTROL DATE"))  ;20250529 p7
 I $$CMOP^BPDMUTL1(BPDM("CONTROL DATE")) D  ;20230609 maw 96248 p7
 . S BPDMCMOP=1
 . S X1=BPDM("CONTROL DATE")
 . S X2=-1
 . D C^%DTC
 . S BPDM("CONTROL DATE")=X
 . S BPDM("CMOP DATE")=X
 ;20250402 maw new
 S BPDMCHKD=$$FMADD^XLFDT(DT,-181)  ;180 days first run of the day
 I $G(BPDMLR),$P($P($G(^BPDMLOG(BPDMLR,0)),U),".")=DT,$G(BPDMPTYP)="P" S BPDMCHKD=$$FMADD^XLFDT(DT,-7)  ;7 days for all other real time runs 20231102 maw p8
 S BPDM("EDIT CHECK")=BPDMCHKD  ;20231205 maw p7 
 ;end new
 S BPDMCNTR=0,BPDM("POSTING DATE")="      "
 F  S BPDM("CONTROL DATE")=$O(^PSRX("AL",BPDM("CONTROL DATE"))) Q:BPDM("CONTROL DATE")=""!(BPDM("CONTROL DATE")>BPDM("RUN END"))  D PROCESS2
 ;partials
 S BPDMPART="01"
 S BPDMRF=0
 S BPDM("POSTING DATE")="      "
 I $G(BPDMLL) S BPDM("CONTROL DATE")=$P($G(^BPDMLOG(BPDMLL,0)),U,3)  ;cmi/maw
 I '$G(BPDMLL) S BPDM("CONTROL DATE")=BPDM("RUN BEGIN")
 I $G(BPDMRTYP)=2 S BPDM("CONTROL DATE")=BPDM("RUN BEGIN")
 F  S BPDM("CONTROL DATE")=$O(^PSRX("AM",BPDM("CONTROL DATE"))) Q:BPDM("CONTROL DATE")=""!(BPDM("CONTROL DATE")>BPDM("RUN END"))  D
 .S BPDMR="" F  S BPDMR=$O(^PSRX("AM",BPDM("CONTROL DATE"),BPDMR)) Q:BPDMR=""  D
 ..S BPDMPFI="" F  S BPDMPFI=$O(^PSRX("AM",BPDM("CONTROL DATE"),BPDMR,BPDMPFI)) Q:BPDMPFI=""  D
 ...Q:$P($G(^PSRX(BPDMR,"P",BPDMPFI,0)),U,16)]""
 ...D PROCESS3
 Q
 ;
PROCESS2 ;
 S BPDMR="" F  S BPDMR=$O(^PSRX("AL",BPDM("CONTROL DATE"),BPDMR)) Q:BPDMR=""  D
 .S BPDMRF="" F  S BPDMRF=$O(^PSRX("AL",BPDM("CONTROL DATE"),BPDMR,BPDMRF)) Q:BPDMRF=""  D PROCESS3
 Q
PROCESS3 ;EP
 I '$G(BPDMSTAT) S BPDMSTAT="00"
 S BPDMPART="02"
 I '$D(^PSRX(BPDMR,0)) Q
 K BPDME,BPDMMSG,BPDMNG S BPDM("ERROR COUNT")=0
 S BPDMMSG=""
 S BPDME=0
 S BPDM("COUNT")=BPDM("COUNT")+1
 X BPDMCNT
 S BPDMREC=^PSRX(BPDMR,0)
 S BPDMPNE=""
 S BPDMDIVI=$$VALI^XBDIQ1(52,BPDMR,20)
 I $G(BPDMCMOP),'$G(BPDMCEXP),'$$REISS^BPDMUTL1(BPDM("OCONTROL DATE")) Q:$$EXPORTED^BPDMUTL1(BPDM("CMOP DATE"),BPDMR,BPDMRF,$G(BPDMSTAT),"")  ;20230609 maw p7 check to see if already exported
 ;ihs/cmi/maw 09142018 patch 4 CR10254
 I $G(BPDMRF) S BPDMDIVI=$P($G(^PSRX(BPDMR,1,BPDMRF,0)),U,9)  ;get refill division and only process if same as running site
 I $G(BPDMDIVI)="",'$G(BPDMRF) S BPDMMSG="OUTPATIENT SITE IN PRESCRIPTION MISSING",BPDME=1 D RECORD Q  ;cmi/maw 20211028 patch 5 CR75992 refill node was removed so cant continue
 I $G(BPDMDIVI)="",$G(BPDMRF),$D(^PSRX(BPDMR,1,BPDMRF,0)) S BPDMMSG="OUTPATIENT SITE IN PRESCRIPTION MISSING",BPDME=1 D RECORD Q  ;cmi/maw 20211028 patch 5 CR75992 refill node was removed so cant continue
 I $G(BPDMDIVI) Q:BPDMDIVI'=BPDMOSIT  ; not a prescription for this outpatient site being run for 20211101 maw p5
 S BPDMFD=$$DATEFILL^BPDMUTL(BPDMR,$G(BPDMRF),$G(BPDMPFI),BPDMPART)
 I $G(BPDMRTSC),$G(BPDMOFD) S BPDMFD=BPDMOFD  ;20230511 maw p7
 I $L(BPDMFD)<7,BPDMSTAT="02",$G(BPDMOFD) S BPDMFD=$$DATE(BPDMOFD)  ;20211101 cmi/maw p5
 I BPDMFD="" S BPDMMSG="NO FILL DATE FOUND_DSP05",BPDME=1 D RECORD Q
 S BPDMDRUG=$P(BPDMREC,U,6)
 I BPDMDRUG="" S BPDMMSG="NO DRUG ON THIS PRESCRIPTION",BPDME=1 D RECORD Q
 I '$D(^PSDRUG(BPDMDRUG)) S BPDMMSG="NO DRUG ON THIS PRESCRIPTION",BPDME=1 D RECORD Q
 I $P(^PSDRUG(BPDMDRUG,0),U,3)="" S BPDMMSG="NOT A SCHEDULE 2,3,4 DRUG",BPDMNG=1 D RECORD Q
 I '$$COND^BPDMUTL(BPDMDRUG,BPDMDTAX,BPDMSITE) S BPDMMSG="NOT A DRUG TO BE EXPORTED",BPDMNG=1 D RECORD Q
 I $P($G(^PSRX(BPDMR,"STA")),U)=1 S BPDMMSG="STATUS IS 1",BPDMNG=1 D RECORD Q
 I $P($G(^PSRX(BPDMR,"STA")),U)=3,'$G(BPDMRTSC) S BPDMMSG="STATUS IS 3",BPDMNG=1 D RECORD Q  ;20220310 p6 11950
 I $P($G(^PSRX(BPDMR,"STA")),U)=4 S BPDMMSG="STATUS IS 4",BPDMNG=1 D RECORD Q
 I $P($G(^PSRX(BPDMR,"STA")),U)=5,'$G(BPDMRTSC) S BPDMMSG="STATUS IS 5",BPDMNG=1 D RECORD Q  ;20220310 p6 11950
 I BPDMSTAT'="02",$P($G(^PSRX(BPDMR,"STA")),U)=15 S BPDMMSG="STATUS IS 15",BPDMNG=1 D RECORD Q
 I BPDMSTAT'="02",$P($G(^PSRX(BPDMR,"STA")),U)=13 S BPDMMSG="STATUS IS 13",BPDMNG=1 D RECORD Q
 I $P($G(^PSRX(BPDMR,"STA")),U)=16 S BPDMMSG="STATUS IS 16",BPDMNG=1 D RECORD Q
 ;20230509 patch 7 maw check if anything else before rts
 I BPDMSTAT'="02",$$RTS^BPDMUTL(BPDMR,BPDMRF,$G(BPDMPFI)) S BPDMMSG="RETURNED TO STOCK BEFORE EXPORT",BPDMNG=1 D RECORD Q
 S DFN=$P(BPDMREC,U,2)
 I DFN="" S BPDMMSG="NO PATIENT FOUND FOR PRESCRIPTION_PAT07",BPDME=1 D RECORD Q
 I '$D(^DPT(DFN,0)) S BPDMMSG="INVALID PATIENT FOR PRESCRIPTION",BPDME=1 D RECORD Q
 I $G(BPDMPTYP)="P",$P($G(^DPT(DFN,0)),U)["DEMO,PATIENT" S BPDMMSG="DEMO PATIENT",BPDMNG=1 D RECORD Q
 I $G(BPDMPTYP)="P" S X=$O(^DIBT("B","RPMS DEMO PATIENT NAMES",0)) I X,$D(^DIBT(X,1,DFN)) S BPDMMSG="DEMO PATIENT",BPDMNG=1 D RECORD Q
 I $E(BPDMVER)=3 D ^BPDMDR2 Q
 I BPDMVER=1995 D ^BPDMDR3 Q
 I BPDMVER="4.2" D ^BPDMDR42 Q
 I BPDMVER="4.2A" D ^BPDMDR4A Q
 I BPDMVER="4.2B" D ^BPDMDR4B ;Q
 ;I '$G(BPDMCEXP),$$EDITED^BPDMUTL1(),'$G(BPDMREDO),BPDMVER="4.2B" D ^BPDMDR4B S BPDMSTAT="" Q  ;20230515 96247 p7 set edited
 I '$G(BPDMCEXP),'$G(BPDMREDO),BPDMVER="4.2B" D  Q  ;20250411 96247 p7 set edited
 .D EDITCHK^BPDMUTL1  ;go back now to see if this was edited
 .S BPDMSTAT=""
 Q
 S BPDMX=$O(^BPDMREC("B","PAT",0))
 S BPDMY=0 F  S BPDMY=$O(^BPDMREC(BPDMX,11,BPDMY)) Q:BPDMY'=+BPDMY!(BPDME)  D
 .S BPDMID=$P(^BPDMREC(BPDMX,11,BPDMY,0),U,1)
 .S BPDMREQ=$$REQ^BPDMUTL("PAT",BPDMID,BPDMSTE)
 .Q:'$$REQ^BPDMUTL("PAT",BPDMID,BPDMSTE)
 .S X=""
 .X ^BPDMREC(BPDMX,11,BPDMY,11)
 .I X="",BPDMREQ=1 S BPDMMSG=$P(^BPDMREC(BPDMX,11,BPDMY,0),U,2)_"_"_$P(^BPDMREC(BPDMX,11,BPDMY,0),U,1)_" is missing and is required.",BPDME=1 D RECORD Q
 S BPDMDRUG=$P(^PSRX(BPDMR,0),U,6)
 S BPDMNDC=$P($G(^PSRX(BPDMR,2)),U,7)
 I BPDMNDC="" S BPDMNDC=$$VAL^XBDIQ1(50,BPDMDRUG,31)
 I BPDMNDC="" S BPDMMSG="NDC MISSING FOR THIS DRUG",BPDME=1 D RECORD Q
 S BPDMX=$O(^BPDMREC("B","DSP",0))
 S BPDMY=0 F  S BPDMY=$O(^BPDMREC(BPDMX,11,BPDMY)) Q:BPDMY'=+BPDMY!(BPDME)  D
 .S BPDMID=$P(^BPDMREC(BPDMX,11,BPDMY,0),U,1)
 .S BPDMREQ=$$REQ^BPDMUTL("DSP",BPDMID,BPDMSTE)
 .Q:'$$REQ^BPDMUTL("DSP",BPDMID,BPDMSTE)
 .S X=""
 .X ^BPDMREC(BPDMX,11,BPDMY,11)
 .I $P(^BPDMREC(BPDMX,11,BPDMY,0),U,1)="DSP01",$$VAL^XBDIQ1(9002315.01,BPDMSITE,.04)="MINNESOTA",$$VALI^XBDIQ1(9002315.01,BPDMSITE,.03)="4.0",BPDMSTAT="00" S X="" G NXT
 .I X="",BPDMREQ=1 S BPDMMSG=$P(^BPDMREC(BPDMX,11,BPDMY,0),U,2)_"_"_$P(^BPDMREC(BPDMX,11,BPDMY,0),U,1)_" is missing and is required.",BPDME=1 D RECORD Q
NXT S BPDMPROV=""
 I BPDMPART="01" S BPDMPROV=$P($G(^PSRX(BPDMR,"P",BPDMPFI,0)),U,17)
 I BPDMPROV="" S BPDMPROV=$P(BPDMREC,U,4)
 S BPDMX=$O(^BPDMREC("B","PRE",0))
 S BPDMY=0 F  S BPDMY=$O(^BPDMREC(BPDMX,11,BPDMY)) Q:BPDMY'=+BPDMY!(BPDME)  D
 .S BPDMID=$P(^BPDMREC(BPDMX,11,BPDMY,0),U,1)
 .S BPDMREQ=$$REQ^BPDMUTL("PRE",BPDMID,BPDMSTE)
 .Q:'$$REQ^BPDMUTL("PRE",BPDMID,BPDMSTE)
 .S X=""
 .X ^BPDMREC(BPDMX,11,BPDMY,11)
 .I X="",BPDMREQ=1 S BPDMMSG=$P(^BPDMREC(BPDMX,11,BPDMY,0),U,2)_"_"_$P(^BPDMREC(BPDMX,11,BPDMY,0),U,1)_" is missing and is required.",BPDME=1 D RECORD Q
 I $P(^PSDRUG(BPDMDRUG,0),U,3)[0!($P(^PSDRUG(BPDMDRUG,0),U,3)["M") D
 .S BPDMX=$O(^BPDMREC("B","CDI",0))
 .S BPDMY=0 F  S BPDMY=$O(^BPDMREC(BPDMX,11,BPDMY)) Q:BPDMY'=+BPDMY!(BPDME)  D
 ..S BPDMID=$P(^BPDMREC(BPDMX,11,BPDMY,0),U,1)
 ..S BPDMREQ=$$REQ^BPDMUTL("CDI",BPDMID,BPDMSTE)
 ..Q:'$$REQ^BPDMUTL("CDI",BPDMID,BPDMSTE)
 ..S X=""
 ..X ^BPDMREC(BPDMX,11,BPDMY,11)
 ..I X="",BPDMREQ=1 S BPDMMSG=$P(^BPDMREC(BPDMX,11,BPDMY,0),U,2)_"_"_$P(^BPDMREC(BPDMX,11,BPDMY,0),U,1)_" is missing and is required.",BPDME=1 D RECORD Q
 S BPDMX=$O(^BPDMREC("B","AIR",0))
 S BPDMY=0 F  S BPDMY=$O(^BPDMREC(BPDMX,11,BPDMY)) Q:BPDMY'=+BPDMY!(BPDME)  D
 .S BPDMID=$P(^BPDMREC(BPDMX,11,BPDMY,0),U,1)
 .S BPDMREQ=$$REQ^BPDMUTL("AIR",BPDMID,BPDMSTE)
 .Q:'$$REQ^BPDMUTL("AIR",BPDMID,BPDMSTE)
 .S X=""
 .X ^BPDMREC(BPDMX,11,BPDMY,11)
 .I X="",BPDMREQ=1 S BPDMMSG=$P(^BPDMREC(BPDMX,11,BPDMY,0),U,2)_"_"_$P(^BPDMREC(BPDMX,11,BPDMY,0),U,1)_" is missing and is required.",BPDME=1 D RECORD Q
N Q:BPDME
 S BPDMMSG="EXPORTED" D RECORD
 S ^TMP($J,"EXPORT",DFN,BPDMR,BPDMRF,$G(BPDMPFI))=BPDMPART_U_BPDMSTAT
 Q
 ;
RECORD ;EP count and build tx
 I $G(BPDME) D
 .S $P(^TMP($J,"ERROR",BPDMR),U,1)=BPDMR
 .S $P(^TMP($J,"ERROR",BPDMR),U,2)=BPDMMSG
 .S $P(^TMP($J,"ERROR",BPDMR),U,3)=BPDMRF
 .S $P(^TMP($J,"ERROR",BPDMR),U,4)=BPDMPFI
 .S $P(^TMP($J,"ERROR",BPDMR),U,5)=BPDMSTAT
 .S $P(^TMP($J,"ERROR",BPDMR),U,6)=BPDMFD
 .I $G(BPDME)=1 S BPDM("ERROR COUNT")=BPDM("ERROR COUNT")+1,$P(^TMP($J,"ERROR",BPDMR),U,4)=1,BPDMQFLG=1
 S $P(^TMP($J,"REVIEWED",BPDMR,BPDMSTAT),U,1)=BPDMR
 S $P(^TMP($J,"REVIEWED",BPDMR,BPDMSTAT),U,2)=BPDMMSG
 S $P(^TMP($J,"REVIEWED",BPDMR,BPDMSTAT),U,3)=BPDMRF
 S $P(^TMP($J,"REVIEWED",BPDMR,BPDMSTAT),U,4)=BPDMPFI
 S $P(^TMP($J,"REVIEWED",BPDMR,BPDMSTAT),U,5)=BPDMSTAT
 S $P(^TMP($J,"REVIEWED",BPDMR,BPDMSTAT),U,6)=BPDMFD
 I $G(BPDME)=1 S $P(^TMP($J,"REVIEWED",BPDMR),U,7)=1
 K BPDMMSG
 Q
TAPE ;EP - copy to file
 S BPDMNOFI=0  ;20220223 patch 6 73211
 I $E(BPDMVER)=3 D TAPE^BPDMDR2 Q
 I BPDMVER=1995 D TAPE^BPDMDR3 Q
 I BPDMVER="4.2" D TAPE^BPDMDR42 Q
 I BPDMVER="4.2A" D TAPE^BPDMDR4A Q
 I BPDMVER="4.2B" D TAPE^BPDMDR4B Q
 Q
 ;
LOG ;EP ;UPDATE LOG
 D ^XBFMK
 S BPDMXX=""
 S DA=BPDM("RUN LOG"),DIE="^BPDMLOG(",DR=".04///"_BPDM("COUNT")_";.05///"_BPDM("REC COUNT")_";.06///"_$G(BPDMFILE)_";.07///"_$S('BPDMQFLG:"S",1:"") D ^DIE
 ;now 21 multiple
 S:'$D(^BPDMLOG(BPDM("RUN LOG"),21,0)) ^BPDMLOG(BPDM("RUN LOG"),21,0)="^9002315.0921PA^^"
 S (BPDMX,BPDMC)=0 F  S BPDMX=$O(^TMP($J,"REVIEWED",BPDMX)) Q:BPDMX'=+BPDMX  D
 . S BPDMY="" F  S BPDMY=$O(^TMP($J,"REVIEWED",BPDMX,BPDMY)) Q:BPDMY=""  D
 .. S BPDMZ="" F  S BPDMZ=$O(^TMP($J,"REVIEWED",BPDMX,BPDMY,BPDMZ)) Q:BPDMZ=""  D
 ... S BPDMZZ="" F  S BPDMZZ=$O(^TMP($J,"REVIEWED",BPDMX,BPDMY,BPDMZ,BPDMZZ)) Q:BPDMZZ=""  D
 ....S BPDMC=BPDMC+1
 ....S ^BPDMLOG(BPDM("RUN LOG"),21,BPDMC,0)=^TMP($J,"REVIEWED",BPDMX,BPDMY,BPDMZ,BPDMZZ)
 ....S $P(^BPDMLOG(BPDM("RUN LOG"),21,0),U,3)=BPDMX,$P(^(0),U,4)=$P(^(0),U,4)+1
 ;now 31 multiple
 S:'$D(^BPDMLOG(BPDM("RUN LOG"),31,0)) ^BPDMLOG(BPDM("RUN LOG"),31,0)="^9002315.0931PA^^"
 S (BPDMX,BPDMC)=0 F  S BPDMX=$O(^TMP($J,"REVIEWED",BPDMX)) Q:BPDMX'=+BPDMX  D
 . S BPDMY="" F  S BPDMY=$O(^TMP($J,"REVIEWED",BPDMX,BPDMY)) Q:BPDMY=""  D
 .. S BPDMZ="" F  S BPDMZ=$O(^TMP($J,"REVIEWED",BPDMX,BPDMY,BPDMZ)) Q:BPDMZ=""  D
 ... S BPDMZZ="" F  S BPDMZZ=$O(^TMP($J,"REVIEWED",BPDMX,BPDMY,BPDMZ,BPDMZZ)) Q:BPDMZZ=""  D
 ....Q:$P(^TMP($J,"REVIEWED",BPDMX,BPDMY,BPDMZ,BPDMZZ),U,2)'="EXPORTED"
 ....S BPDMC=BPDMC+1
 ....S ^BPDMLOG(BPDM("RUN LOG"),31,BPDMC,0)=^TMP($J,"REVIEWED",BPDMX,BPDMY,BPDMZ,BPDMZZ)
 ....S $P(^BPDMLOG(BPDM("RUN LOG"),31,0),U,3)=BPDMX,$P(^(0),U,4)=$P(^(0),U,4)+1
 ....K ^BPDMLOG("AIR",BPDMX)  ;20240408 maw new AIR cleanup
 ;now 51 multiple
 S:'$D(^BPDMLOG(BPDM("RUN LOG"),51,0)) ^BPDMLOG(BPDM("RUN LOG"),51,0)="^9002315.0951PA^^"
 S (BPDMX,BPDMC)=0 F  S BPDMX=$O(^TMP($J,"ERROR",BPDMX)) Q:BPDMX'=+BPDMX  D
 .S BPDMC=BPDMC+1
 .S ^BPDMLOG(BPDM("RUN LOG"),51,BPDMC,0)=^TMP($J,"ERROR",BPDMX)
 .S $P(^BPDMLOG(BPDM("RUN LOG"),51,0),U,3)=BPDMX,$P(^(0),U,4)=$P(^(0),U,4)+1
 I $G(BPDMREDO) D AUDIT^BPDMCHKN(BPDM("RUN LOG"))
 S DA=BPDM("RUN LOG"),DIK="^BPDMLOG(" D IX^DIK
 Q
FNDLST(SITE,TYP) ;-- find the last log end time and start there
 N LST,LDA
 S LDA=0 F  S LDA=$O(^BPDMLOG("ABF",LDA)) Q:'LDA!($G(LST))  D
 . S LIEN=0 F  S LIEN=$O(^BPDMLOG("ABF",LDA,SITE,TYP,LIEN)) Q:'LIEN!($G(LST))  D
 .. I $G(BPDMPTYP)="P",$P($G(^BPDMLOG(LIEN,0)),U,9)="T" Q
 .. I $P($G(^BPDMLOG(LIEN,0)),U,7)="S" S LST=LIEN
 Q $G(LST)
 ;
DATE(D) ;EP
 I $G(D)="" Q ""
 Q (1700+$E(D,1,3))_$E(D,4,5)_$E(D,6,7)
RZERO(V,L) ;ep right zero fill 
 NEW %,I
 S %=$L(V),Z=L-% F I=1:1:Z S V=V_"0"
 Q V
LBLK(V,L) ;left blank fill
 NEW %,I
 S %=$L(V),Z=L-% F I=1:1:Z S V=" "_V
 Q V
RBLK(V,L) ;EP right blank fill
 NEW %,I
 S %=$L(V),Z=L-% F I=1:1:Z S V=V_" "
 Q V
LZERO(V,L) ;EP - left zero fill
 NEW %,I
 S %=$L(V),Z=L-% F I=1:1:Z S V="0"_V
 Q V
 ;
PHONE(P) ;EP
 NEW Y
 S Y=$P($G(^DPT(P,.13)),U,1)
 I Y="" Q ""
 NEW C,E,N
 S N=Y
 F C=1:1:$L(Y) S E=$E(Y,C) I E'?1N S N=$$STRIP^XLFSTR(N,E)
 I N'?10N S N=""
 Q N
CTR(X,Y) ;EP - Center X in a field Y wide.
 Q $J("",$S($D(Y):Y,1:IOM)-$L(X)\2)_X
 ;----------
USR() ;EP - Return current user
 Q $S($G(DUZ):$S($D(^VA(200,DUZ,0)):$P(^(0),U),1:"UNKNOWN"),1:"DUZ UNDEFINED OR 0")
 ;----------
LOC() ;EP - Return location
 Q $S($G(DUZ(2)):$S($D(^DIC(4,DUZ(2),0)):$P(^(0),U),1:"UNKNOWN"),1:"DUZ(2) UNDEFINED OR 0")
