ORDEA02 ;ISL/JLC - DEA PROVIDER REPORT ;06-Feb-2019 09:07;DU
 ;;3.0;ORDER ENTRY/RESULTS REPORTING;**371,1017**;Dec 17, 1997;Build 48
 ;
 ;Modified - 09/01/2017 - Added notification logic
 ;
EN ;TaskMan entry point
 N YR,MN,ORREPH,ORREP,ORPROV,BL,S1,S3,ORRX,PRVNME,DATA0,DATA1,DATA3,DATA5,ORPNM,ORDRUG,ORDEA,ORPT,ORCNT,ORISS,Y,ORDT,DIC,DA,DR,DIQ,ORS,ORIFN,ORQTY,PTIEN,DRG,CNT,BACKDOOR,IND,HARDCPY
 S ZTSTOP=0 K ^TMP($J,"CS BY PROV")
 S DT=$$NOW^XLFDT,YR=$E(DT,1,3)+1700,MN=$E(100+$E(DT,4,5)-1,2,99) I MN<1 S MN=12,YR=YR-1
 S Y=YR-1700_MN D DD^%DT S ORREPH=Y,ORREP=YR-1700_$E(MN+100,2,3),ORPROV=0,$P(BL," ",99)=""
 F  S ORPROV=$O(^ORPA(101.52,"C",ORPROV)) Q:'ORPROV  D  I ZTSTOP Q
 . S PRVNME=$$GET1^DIQ(200,ORPROV,.01)
 . S S1=ORREP K ^TMP($J,"CS BY PROV") S ORCNT=0
 . F  S S1=$O(^ORPA(101.52,"C",ORPROV,S1)) Q:'S1  I $E(S1,1,5)=ORREP D
 .. S S3=0
 .. F  S S3=$O(^ORPA(101.52,"C",ORPROV,S1,S3)) Q:'S3  D
 ... S DATA0=$G(^ORPA(101.52,S3,0)),DATA1=$G(^(1)),DATA3=$G(^(3)),DATA5=$G(^(5))
 ... S ORIFN=$P(DATA0,"^"),ORRX=$P(DATA0,"^",2)
 ... Q:'+ORIFN                  ;MGH PATCH 1017
 ... S IND=""
 ... I +ORRX D
 .... S BACKDOOR=$P($G(^PSRX(ORRX,"PKI")),U,2)
 .... I BACKDOOR=1 S IND="B"
 ....S HARDCPY=$P($G(^PSRX(ORRX,999999941)),U,2)
 ....I HARDCPY=1 S IND="H"
 ... I ORRX="" S DA=$P($G(^OR(100,ORIFN,3)),"^",3) I +DA S DIC=100.01,DR=.01,DIQ="ORS" D EN^DIQ1 S ORRX=ORS(100.01,DA,.01)
 ... S ORRX=ORRX_BL,ORPNM=$P(DATA5,"^")_BL,ORDRUG=$E($P(DATA1,"^",2),1,22)_BL,ORDEA=$E($P(DATA1,"^",4))_BL,ORQTY=$P(DATA1,"^",5)_BL
 ... ;S Y=$P(DATA1,"^") X ^DD("DD") S ORISS=Y_BL
 ... S ORISS=$P($TR($$FMTE^XLFDT($P(DATA1,"^"),"5Z"),"@"," "),":",1,2)_BL
 ... S ORCNT=ORCNT+1,^TMP($J,"CS TEMP",ORPNM,ORDRUG,ORCNT)=$E(ORPNM,1,25)_"  "_$E(ORDRUG,1,25)_" "_$E(ORQTY,1,6)_" "_$E(ORDEA)_"    "_$E(ORISS,1,10)_" "_IND
 ... ;_$E(ORRX,1,11)
 . S ORCNT=0
 . Q:$G(DATA3)=""
 . S ORCNT=ORCNT+1,^TMP($J,"CS BY PROV",ORCNT,0)=$E(BL,1,16)_"Monthly Controlled Substances Issued by Provider"
 . S ORCNT=ORCNT+1,^TMP($J,"CS BY PROV",ORCNT,0)="Report for: "_ORREPH_" for "_PRVNME
 . S ORCNT=ORCNT+1,^TMP($J,"CS BY PROV",ORCNT,0)=" "
 . S ORCNT=ORCNT+1,^TMP($J,"CS BY PROV",ORCNT,0)=$E("PATIENT NAME"_BL,1,27)_$E("DRUG NAME"_BL,1,25)_" QTY  "_"  SCH  "_$E("ISSUE DATE"_BL,1,10)_" ORD"
 . ;_$E("RX#/STATUS"_BL,1,12)
 . S ORCNT=ORCNT+1,^TMP($J,"CS BY PROV",ORCNT,0)=" "
 . S ORPT=0
 . F  S ORPT=$O(^TMP($J,"CS TEMP",ORPT)) Q:ORPT=""  D
 ..S DRG="" F  S DRG=$O(^TMP($J,"CS TEMP",ORPT,DRG)) Q:DRG=""  D
 ...S CNT=0 F  S CNT=$O(^TMP($J,"CS TEMP",ORPT,DRG,CNT)) Q:'+CNT  D
 ....S ORCNT=ORCNT+1,^TMP($J,"CS BY PROV",ORCNT,0)=$G(^TMP($J,"CS TEMP",ORPT,DRG,CNT))
 . D SEND
 . D ALERT
 . K ^TMP($J)
 . S ZTSTOP=$$REQ2STOP()
 S ZTREQ="@" Q
SEND ;
 Q:'$D(^TMP($J,"CS BY PROV"))  N XMY,XMDUZ,XMSUB,XMTEXT
 S XMDUZ="CPRS,REPORT",XMY(ORPROV)="",XMSUB="MONTHLY CONTROLLED SUBSTANCES REPORT",XMTEXT="^TMP("_$J_",""CS BY PROV"","
 D ^XMD Q
REQ2STOP() ;
 ; Check for task stop request
 ; Returns 1 if stop request made.
 N STATUS,X
 S STATUS=0
 I '$D(ZTQUEUED) Q 0
 S X=$$S^%ZTLOAD()
 I X D  ;
 . S STATUS=1
 . S X=$$S^%ZTLOAD("Received shutdown request")
 ;
 Q STATUS
ALERT ;Send alert
 Q:'$D(^TMP($J,"CS BY PROV"))
 N ATIME,DATA,ID,SUB,XTR,MSG,NUM,PRV,PT,DRG,CNT
 S CNT=0,NUM=0
 S ATIME=$$NOW^XLFDT
 S ID="BEHOXQ"
 S SUB="Monthly CS Report"
 S XTR="PRI=3"
 F  S CNT=$O(^TMP($J,"CS BY PROV",CNT)) Q:'+CNT  D
 .S NUM=NUM+1
 .S MSG(CNT,0)=$G(^TMP($J,"CS BY PROV",CNT,0))
 I NUM>0 D SCHALR^BEHOXQ(.DATA,ATIME,ID,SUB,XTR,.MSG,ORPROV)
 Q
