BMAGPS01 ;post install for the IHS Imaging Viewer;07-Jan-2014 15:58;PLS
 ;;1.0;BMAG;;Aug 23, 2013 build 39;Build 20
 ;
ENTRY ; REGISTER required Imaging RPCs to the CIAV VUECENTRIC Option
 I $$REGRPC^CIAURPC("MAGGUSER2","CIAV VUECENTRIC")
 I $$REGRPC^CIAURPC("MAGG CPRS RAD EXAM","CIAV VUECENTRIC")
 I $$REGRPC^CIAURPC("MAG3 CPRS TIU NOTE","CIAV VUECENTRIC")
 I $$REGRPC^CIAURPC("MAGG PAT INFO","CIAV VUECENTRIC")
 I $$REGRPC^CIAURPC("MAG4 PAT GET IMAGES","CIAV VUECENTRIC")
 I $$REGRPC^CIAURPC("MAG3 LOGACTION","CIAV VUECENTRIC")
 I $$REGRPC^CIAURPC("MAGGUSER2","CIAV VUECENTRIC")
 I $$REGRPC^CIAURPC("MAGG PAT EACH IMAGE","CIAV VUECENTRIC")
 Q
