BMAGFLUD ;IHS/WOIFO/BT - Imaging User Filter RPC ; 29 OCt 2021 4:16 PM
 ;;3.0;BMAG;**193**;May 05, 2022
 ;;
 Q
 ;
SAVE(MAGRY,FILTER) ; RPC: BMAG FILTER SAVE USER DEFAULT
 N DATA S DATA("LISTWIN1")="^^"_FILTER
 D SAVE^MAGGTUP(.MAGRY,.DATA)
 Q
