BJPC2P27 ; IHS/CMI/LAB - PCC Suite v2.0 PATCH 27 PRE/POST INIT
 ;;2.0;IHS PCC SUITE;**27**;MAY 14, 2009;Build 64
 ;
 ;
 ; The following line prevents the "Disable Options..." and "Move Routines..." questions from being asked during the install.
 I $G(XPDENV)=1 S (XPDDIQ("XPZ1"),XPDDIQ("XPZ2"))=0
 F X="XPO1","XPZ1","XPZ2","XPI1" S XPDDIQ(X)=0
 ;KERNEL
 I '$$INSTALLD("XU*8.0*1018") D SORRY(2)
 I '$$INSTALLD("DI*22.0*1018") D SORRY(2)
 I '$$INSTALLD("BJPC*2.0*26") D MES^XPDUTL($$CJ^XLFSTR("Requires BJPC V2.0 patch 26.  Not installed.",80)) D SORRY(2)
 ;
 Q
 ;
PRE ;
 Q
POST ;
 ;SET DUAL CODING TO NO, OBSOLETE
 S BJPCX=0 F  S BJPCX=$O(^APCDSITE(BJPCX)) Q:BJPCX'=+BJPCX  S DA=BJPCX,DR=".36///0",DIE="^APCDSITE(" D ^DIE K DA,DR,DIE
 ;REMOVE MENU OPTIONS AND REPORTS
 ;APCD SUPER FORMS TRACKING MENU from APCDSUPER
 S X=$$ADD^XPDMENU("APCDSUPER","APCD SUPER FORMS TRACKING MENU","FTM")
 S X=$$DELETE^XPDMENU("APCDSUPER","APCD SUPER ACCEPT COMMAND MENU")
 S X=$$DELETE^XPDMENU("APCD MENU ENTER LOG DATA","APCDEAPC")
 S X=$$DELETE^XPDMENU("APCD MENU ENTER LOG DATA","APCDEALAB")
 S X=$$ADD^XPDMENU("APCD MENU ENTER DATA","APCD FORMS COUNT DUZ","MFC",98)
 ;CRC    Living Patients by Community of Residence (*) [APCL P PATLIST BY CURRCOM]
 ;DOB    Living Patients by Date of Birth (*) [APCL P PATLIST DOB LISTING]
 ;DEM    Living Patients by Multiple Demographic Variables [APCL P PATLIST DEMOGRAPHICS]
 ;APCL M MAN PATIENT LISTINGS
 S X=$$DELETE^XPDMENU("APCL M MAN PATIENT LISTINGS","APCL P PATLIST BY CURRCOM")
 S X=$$DELETE^XPDMENU("APCL M MAN PATIENT LISTINGS","APCL P PATLIST DOB LISTING")
 S X=$$DELETE^XPDMENU("APCL M MAN PATIENT LISTINGS","APCL P PATLIST DEMOGRAPHICS")
 S X=$$DELETE^XPDMENU("APCLMENU","APCL M IMMUNIZATION")
 S X=$$DELETE^XPDMENU("APCD OTHER REPORTS","APCD FORMS TRACKING TRAN CODES")
 S X=$$DELETE^XPDMENU("APCDSUPER","APCD FORMS FILE OP")
 S X=$$ADD^XPDMENU("BDP MENU MANAGER","BDP REMOVE INACTIVE PTS","RINP")
 ;take out out of order on these 
 S DA=$O(^DIC(19,"B","APCD SUPER FORMS TRACKING MENU",0)) I DA S DIE="^DIC(19,",DR="2///@" D ^DIE K DA,DR,DIE
 S DA=$O(^DIC(19,"B","APCD FORMS FILE COUNTS",0)) I DA S DIE="^DIC(19,",DR="2///@" D ^DIE K DA,DR,DIE
 S DA=$O(^DIC(19,"B","APCD FORMS FILE PURGE",0)) I DA S DIE="^DIC(19,",DR="2///@" D ^DIE K DA,DR,DIE
 S DA=$O(^DIC(19,"B","APCD FORMS FILE QA",0)) I DA S DIE="^DIC(19,",DR="2///@" D ^DIE K DA,DR,DIE
 S DA=$O(^DIC(19,"B","APCD FORMS DISP OPERATOR",0)) I DA S DIE="^DIC(19,",DR="2///@" D ^DIE K DA,DR,DIE
 S DA=$O(^DIC(19,"B","APCD FORMS FILE",0)) I DA S DIE="^DIC(19,",DR="2///@" D ^DIE K DA,DR,DIE
 S DA=$O(^DIC(19,"B","APCD FORMS SUMMARY REPORT",0)) I DA S DIE="^DIC(19,",DR="2///@" D ^DIE K DA,DR,DIE
 S DA=$O(^DIC(19,"B","APCD FORMS COUNT DUZ",0)) I DA S DIE="^DIC(19,",DR="2///@" D ^DIE K DA,DR,DIE
 ;
X ;RENAME HEALTH SUMMARY COMPONENTS
 K DA,DR,DIE
 S DA=$O(^APCHSCMP("B","OUTPATIENT/FIELD VISITS",0)) I DA S DIE="^APCHSCMP(",DR="3///OUTPATIENT/FIELD/TELEMEDICINE VISITS" D ^DIE K DA,DIE,DR
 S DA=$O(^APCHSCMP("B","OUTPATIENT VISITS (EXCL CHR)",0)) I DA S DIE="^APCHSCMP(",DR="3///OUTPATIENT/FIELD/TELEMEDICINE VISITS (EXCLUDES CHR)" D ^DIE K DA,DIE,DR
 S DA=$O(^APCHSCMP("B","OUTPATIENT VISITS (SCREENED)",0)) I DA S DIE="^APCHSCMP(",DR="3///OUTPATIENT/FIELD/TELEMEDICINE VISITS (SCREENED)" D ^DIE K DA,DIE,DR
 Q
INSTALLD(BJPCSTAL) ;EP - Determine if patch BJPCSTAL was installed, where
 ; APCLSTAL is the name of the INSTALL.  E.g "AG*6.0*11".
 ;
 NEW BJPCY,DIC,X,Y
 S X=$P(BJPCSTAL,"*",1)
 S DIC="^DIC(9.4,",DIC(0)="FM",D="C"
 D IX^DIC
 I Y<1 D IMES Q 0
 S DIC=DIC_+Y_",22,",X=$P(BJPCSTAL,"*",2)
 D ^DIC
 I Y<1 D IMES Q 0
 S DIC=DIC_+Y_",""PAH"",",X=$P(BJPCSTAL,"*",3)
 D ^DIC
 S BJPCY=Y
 D IMES
 Q $S(BJPCY<1:0,1:1)
IMES ;
 D MES^XPDUTL($$CJ^XLFSTR("Patch """_BJPCSTAL_""" is"_$S(Y<1:" *NOT*",1:"")_" installed.",IOM))
 Q
SORRY(X) ;
 KILL DIFQ
 I X=3 S XPDQUIT=2 Q
 S XPDQUIT=X
 Q
